<a href="https://colab.research.google.com/github/shakil212/ZeroDay-IoT-ML-Project/blob/main/ZeroDay_IoT_Final_Training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#STEP 0 — Create the Final Colab Notebook

# Temporal Self-Supervised Representation Learning for Zero-Day IoT Intrusion Detection Using GRU Networks

## Final Research Training Notebook

**Notebook Name:** `ZeroDay_IoT_Final_Training.ipynb`

---

## Project Objective

The objective of this notebook is to implement and evaluate a machine-learning and deep-learning framework for **zero-day IoT intrusion detection**.

The research focuses on detecting attack families that were not available during model training.

The proposed approach combines:

- Temporal network-flow sequences
- Self-supervised representation learning
- GRU-based temporal modeling
- Contrastive learning
- Temporal-order prediction
- Supervised intrusion-detection fine-tuning

---

## Dataset

The experiments will use the **CICIoT2023** dataset.

The research considers seven IoT attack families:

1. DDoS
2. DoS
3. Mirai
4. Recon
5. Spoofing
6. Web
7. BruteForce

---

## Evaluation Strategy

The final experiment will use a strict:

**Leave-One-Attack-Family-Out (LOAFO)** evaluation protocol.

In each fold:

- One attack family will be completely held out.
- The held-out family will not be used for training.
- The held-out family will not be used for validation.
- The held-out family will be evaluated only during testing.

This simulates a realistic zero-day attack scenario.

---

## Main Evaluation Metrics

The final experiments will report:

- Precision
- Recall
- F1-Score
- ROC-AUC
- PR-AUC
- False Positive Rate (FPR)
- Zero-Day Recall
- Confusion Matrix

---

## Experimental Studies

The notebook will also include:

- Baseline machine-learning models
- Supervised GRU
- Self-supervised models
- Proposed MOT-SSL-GRU
- Temporal-window sensitivity analysis
- Temporal-order loss-weight sensitivity analysis
- Class-imbalance sensitivity analysis
- Ablation study
- Statistical analysis
- Graphs and result tables

---

## Research Integrity

The following rules will be maintained throughout the notebook:

- Real timestamps will be used for temporal ordering.
- Timestamp values will not be used as neural-network input features.
- Preprocessing will be fitted using training data only.
- The zero-day attack family will remain unseen during model development.
- Test data will not be used for hyperparameter selection.
- Smoke-test results will not be reported as final research results.

---

## Notebook Execution Plan

The notebook will be completed step by step.

Each section will contain:

1. Purpose
2. Research importance
3. Implementation details
4. Code
5. Expected result
6. Validation status

#STEP 1 — Environment and GPU Verification

# 1. Environment and GPU Verification

## 1.1 Purpose

The purpose of this section is to verify that the Google Colab environment is ready for machine-learning and deep-learning experiments.

The research includes GRU networks and self-supervised learning models. These models require considerably more computation than traditional machine-learning algorithms.

Therefore, GPU acceleration will be used whenever available.

---

## 1.2 Why GPU Is Important

The final experiment will include:

- Multiple machine-learning models
- GRU-based models
- Self-supervised pretraining
- Seven LOAFO folds
- Multiple random seeds
- Sensitivity experiments
- Ablation experiments

Using a GPU can significantly reduce the total training time.

---

## 1.3 Required Colab Setting

Before running the code below, select:

**Runtime → Change runtime type → T4 GPU → Save**

---

## 1.4 Expected Result

The section should finish with:

`✅ SECTION 1 PASSED — GPU environment is ready.`

If CUDA is unavailable, the runtime configuration should be checked before continuing.

#STEP 1.6 — GPU Verification Code

In [ ]:
# ================================================================
# SECTION 1 — ENVIRONMENT AND GPU VERIFICATION
# ================================================================

import sys
import platform
import torch

print("=" * 70)
print("SECTION 1 — ENVIRONMENT AND GPU VERIFICATION")
print("=" * 70)

# ------------------------------------------------
# Python environment
# ------------------------------------------------

print("\n[1] Python Environment")
print("-" * 70)

print("Python version :", sys.version.split()[0])
print("Platform       :", platform.platform())


# ------------------------------------------------
# PyTorch environment
# ------------------------------------------------

print("\n[2] PyTorch Environment")
print("-" * 70)

print("PyTorch version:", torch.__version__)


# ------------------------------------------------
# GPU / CUDA
# ------------------------------------------------

print("\n[3] GPU Status")
print("-" * 70)

cuda_available = torch.cuda.is_available()

print("CUDA available :", cuda_available)

if cuda_available:

    gpu_name = torch.cuda.get_device_name(0)

    gpu_info = torch.cuda.get_device_properties(0)

    gpu_memory = gpu_info.total_memory / (1024 ** 3)

    print("GPU detected   :", gpu_name)
    print("GPU memory     :", f"{gpu_memory:.2f} GB")

    print("\n" + "=" * 70)
    print("✅ SECTION 1 PASSED — GPU environment is ready.")
    print("=" * 70)

else:

    print("\n" + "=" * 70)
    print("❌ SECTION 1 FAILED — GPU is not enabled.")
    print("=" * 70)

    print(
        "\nGo to:\n"
        "Runtime → Change runtime type → T4 GPU → Save"
    )

======================================================================
SECTION 1 — ENVIRONMENT AND GPU VERIFICATION
======================================================================

[1] Python Environment
----------------------------------------------------------------------
Python version : 3.13.15
Platform       : Linux-6.6.122+-x86_64-with-glibc2.39

[2] PyTorch Environment
----------------------------------------------------------------------
PyTorch version: 2.11.0+cu128

[3] GPU Status
----------------------------------------------------------------------
CUDA available : True
GPU detected   : Tesla T4
GPU memory     : 14.56 GB

======================================================================
✅ SECTION 1 PASSED — GPU environment is ready.
======================================================================

# STEP 2 — Install and Verify Required Libraries

# 2. Install and Verify Required Libraries

## 2.1 Purpose

This section prepares the Python software environment required for the complete zero-day IoT intrusion-detection experiment.

The project uses different libraries for:

- Data loading and preprocessing
- Numerical computation
- Machine-learning baseline models
- Deep-learning models
- Statistical analysis
- Visualization
- Efficient dataset storage

---

## 2.2 Required Libraries

### NumPy
Used for numerical computations, arrays, random operations, and temporal-window processing.

### Pandas
Used for loading CSV files, cleaning data, analyzing attack-family distributions, and saving research results.

### Scikit-learn
Used for:

- Logistic Regression
- Random Forest
- Multi-Layer Perceptron
- Preprocessing
- Evaluation metrics
- Confusion matrices

### XGBoost
Used to implement the XGBoost machine-learning baseline.

### PyTorch
Used for:

- GRU networks
- Autoencoders
- Self-supervised learning
- Contrastive learning
- Temporal-order prediction
- Fine-tuning
- GPU-based training

PyTorch is already provided by Google Colab, so it will not be reinstalled.

### SciPy
Used for statistical significance testing.

### Matplotlib
Used for research figures such as:

- Training curves
- Model comparisons
- ROC curves
- Precision-Recall curves
- Sensitivity-analysis graphs
- Ablation-study graphs

### PyArrow
Used for efficient Parquet file processing and intermediate dataset storage.

---

## 2.3 Reproducibility

The installed software versions will be displayed and later saved as part of the experiment configuration.

Recording package versions is important because different versions can sometimes produce slightly different behavior or results.

---

## 2.4 Expected Result

This section should finish with:

`✅ SECTION 2 PASSED — All required libraries are available.`

If a required library is missing, the notebook will install it automatically.

In [ ]:
# ================================================================
# SECTION 2 — INSTALL AND VERIFY REQUIRED LIBRARIES
# ================================================================

import sys
import subprocess
import importlib

print("=" * 72)
print("SECTION 2 — INSTALL AND VERIFY REQUIRED LIBRARIES")
print("=" * 72)


# ------------------------------------------------
# 2.1 Required packages
# ------------------------------------------------

required_packages = {
    "numpy": "numpy",
    "pandas": "pandas",
    "scipy": "scipy",
    "sklearn": "scikit-learn",
    "xgboost": "xgboost",
    "matplotlib": "matplotlib",
    "pyarrow": "pyarrow"
}


# ------------------------------------------------
# 2.2 Check installed libraries
# ------------------------------------------------

print("\n[1] Checking required libraries")
print("-" * 72)

missing_packages = []

for import_name, package_name in required_packages.items():

    try:
        importlib.import_module(import_name)
        print(f"✅ {package_name:<20} available")

    except ImportError:
        print(f"⚠️ {package_name:<20} missing")
        missing_packages.append(package_name)


# ------------------------------------------------
# 2.3 Install missing libraries
# ------------------------------------------------

if missing_packages:

    print("\n[2] Installing missing libraries")
    print("-" * 72)

    command = [
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q"
    ] + missing_packages

    result = subprocess.run(
        command,
        capture_output=True,
        text=True
    )

    if result.returncode != 0:
        print(result.stderr)

        raise RuntimeError(
            "Required package installation failed."
        )

    print("✅ Missing libraries installed successfully.")

else:

    print("\n[2] Installation")
    print("-" * 72)

    print(
        "✅ No installation required."
    )


# ------------------------------------------------
# 2.4 Import all libraries
# ------------------------------------------------

print("\n[3] Importing libraries")
print("-" * 72)

import numpy as np
import pandas as pd
import scipy
import sklearn
import xgboost
import matplotlib
import pyarrow
import torch

print("✅ All libraries imported successfully.")


# ------------------------------------------------
# 2.5 Display versions
# ------------------------------------------------

print("\n[4] Software versions")
print("-" * 72)

print(f"Python         : {sys.version.split()[0]}")
print(f"PyTorch        : {torch.__version__}")
print(f"NumPy          : {np.__version__}")
print(f"Pandas         : {pd.__version__}")
print(f"SciPy          : {scipy.__version__}")
print(f"Scikit-learn   : {sklearn.__version__}")
print(f"XGBoost        : {xgboost.__version__}")
print(f"Matplotlib     : {matplotlib.__version__}")
print(f"PyArrow        : {pyarrow.__version__}")


# ------------------------------------------------
# 2.6 GPU re-check
# ------------------------------------------------

print("\n[5] GPU compatibility check")
print("-" * 72)

cuda_available = torch.cuda.is_available()

print("CUDA available :", cuda_available)

if cuda_available:
    print(
        "GPU            :",
        torch.cuda.get_device_name(0)
    )


# ------------------------------------------------
# 2.7 Final status
# ------------------------------------------------

print("\n" + "=" * 72)

if cuda_available:
    print(
        "✅ SECTION 2 PASSED — "
        "All required libraries are available."
    )
else:
    print(
        "⚠️ Libraries are ready, but GPU is unavailable."
    )

print("=" * 72)

========================================================================
SECTION 2 — INSTALL AND VERIFY REQUIRED LIBRARIES
========================================================================

[1] Checking required libraries
------------------------------------------------------------------------
✅ numpy                available
✅ pandas               available
✅ scipy                available
✅ scikit-learn         available
✅ xgboost              available
✅ matplotlib           available
✅ pyarrow              available

[2] Installation
------------------------------------------------------------------------
✅ No installation required.

[3] Importing libraries
------------------------------------------------------------------------
✅ All libraries imported successfully.

[4] Software versions
------------------------------------------------------------------------
Python         : 3.13.15
PyTorch        : 2.11.0+cu128
NumPy          : 2.1.3
Pandas         : 2.2.3
SciPy          : 1.16.3
Scikit-learn   : 1.6.1
XGBoost        : 3.4.1
Matplotlib     : 3.10.0
PyArrow        : 23.0.1

[5] GPU compatibility check
------------------------------------------------------------------------
CUDA available : True
GPU            : Tesla T4

========================================================================
✅ SECTION 2 PASSED — All required libraries are available.
========================================================================

# STEP 3 — Reproducibility and Global Experiment Configuration

# STEP 3A — Add the Markdown / Text Section

# 3. Reproducibility and Global Experiment Configuration

## 3.1 Purpose

The purpose of this section is to define all important experiment settings in one central location before dataset processing and model training begin.

A research experiment should not depend on hidden or manually changed parameters scattered throughout the notebook.

Therefore, this section establishes a single configuration for:

- Random seeds
- Attack families
- Temporal-window settings
- LOAFO evaluation
- Self-supervised learning
- Fine-tuning
- Batch size
- Loss-weight sensitivity
- Class-imbalance analysis
- Output folders
- Device selection

---

## 3.2 Reproducibility

Machine-learning and deep-learning experiments contain several sources of randomness, including:

- Weight initialization
- Mini-batch ordering
- Dataset sampling
- Data augmentation
- Train/validation splitting
- GPU operations

To reduce uncontrolled variation, the experiment will use fixed random seeds.

The planned seeds are:

`13, 29, 47, 71, 101`

Each final LOAFO experiment will eventually be repeated across these seeds.

Using several random seeds allows the research to report both average performance and performance variability.

---

## 3.3 Attack Families

The zero-day evaluation considers seven attack families:

1. DDoS
2. DoS
3. Mirai
4. Recon
5. Spoofing
6. Web
7. BruteForce

A strict Leave-One-Attack-Family-Out (LOAFO) protocol will later create seven folds.

For every fold, one entire attack family will be treated as unseen zero-day data.

---

## 3.4 Temporal Window Configuration

The main temporal-window size is:

\[
T = 8
\]

This means that each model input sequence will contain eight temporally ordered network-flow records.

The main experiment will therefore use:

- Window size = 8
- Stride = 8

The timestamp will be used only to establish chronological ordering.

Timestamp values themselves will not be provided as neural-network input features.

---

## 3.5 Self-Supervised Loss Configuration

The proposed framework combines contrastive representation learning with temporal-order prediction.

The combined objective is:

\[
L_{total} =
L_{NT-Xent}
+
\lambda_t L_{order}
\]

The temporal-order weight candidates are:

\[
\lambda_t \in
\{0.1,\ 0.25,\ 0.5,\ 1.0\}
\]

The final value must be selected using development data only.

The zero-day test family must never be used to select the value of \(\lambda_t\).

---

## 3.6 Primary Training Configuration

The initial training configuration used in this notebook is:

- SSL pretraining epochs: 30
- Supervised fine-tuning epochs: 20
- Batch size: 256
- Main temporal window: 8
- Main stride: 8
- Number of final random seeds: 5

These settings provide the starting configuration for the full experiment.

They may only be changed later if a documented technical reason requires it, such as GPU-memory limitations.

---

## 3.7 Sensitivity Experiments

The research requires sensitivity analysis for:

- Temporal-window size
- Temporal-order loss weight
- Class-imbalance handling

The paper explicitly specifies the \(\lambda_t\) candidates.

For window-size and imbalance experiments, the exact comparison settings will be finalized in their dedicated sections.

They will be clearly documented so that implementation choices are not confused with paper-defined requirements.

---

## 3.8 Output Organization

All experiment outputs will be stored under one central research directory.

The notebook will create separate folders for:

- Dataset audit information
- Processed data
- Model checkpoints
- Predictions
- Metrics
- Figures
- Training logs
- Sensitivity experiments
- Ablation experiments
- Statistical analysis
- Final exports

Keeping results organized is important for:

- Research reproducibility
- Faculty review
- GitHub publication
- Avoiding accidental mixing of smoke-test and final results

---

## 3.9 Research Integrity Rule

Configuration values used in final experiments must be established before evaluating the held-out zero-day test family.

No test-family result should be used to:

- Change preprocessing
- Select model parameters
- Select \(\lambda_t\)
- Select thresholds
- Select temporal-window settings
- Select imbalance strategies

This protects the zero-day evaluation from test-data leakage.

---

## 3.10 Expected Result

After running the following configuration cell, the notebook should:

- Detect the GPU device
- Define all seven attack families
- Define all five random seeds
- Set the main temporal window to 8
- Register all \(\lambda_t\) candidates
- Create the research output folders
- Save the experiment configuration to a JSON file

The section should finish with:

`✅ SECTION 3 PASSED — Global experiment configuration is ready.`

# STEP 3B — Global Configuration Code

In [ ]:
# ================================================================
# SECTION 3 — REPRODUCIBILITY AND GLOBAL EXPERIMENT CONFIGURATION
# ================================================================

import os
import json
import random
from pathlib import Path

import numpy as np
import torch

print("=" * 72)
print("SECTION 3 — REPRODUCIBILITY AND GLOBAL CONFIGURATION")
print("=" * 72)


# ================================================================
# 3.1 PROJECT / EXPERIMENT NAME
# ================================================================

PROJECT_NAME = "ZeroDay_IoT_Final_Training"

print("\n[1] Project")
print("-" * 72)
print("Project name :", PROJECT_NAME)


# ================================================================
# 3.2 DEVICE CONFIGURATION
# ================================================================

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("\n[2] Computing device")
print("-" * 72)

print("Device :", DEVICE)

if torch.cuda.is_available():
    print(
        "GPU    :",
        torch.cuda.get_device_name(0)
    )


# ================================================================
# 3.3 ATTACK FAMILIES
# ================================================================

ATTACK_FAMILIES = [
    "DDoS",
    "DoS",
    "Mirai",
    "Recon",
    "Spoofing",
    "Web",
    "BruteForce"
]

print("\n[3] LOAFO attack families")
print("-" * 72)

for number, family in enumerate(
    ATTACK_FAMILIES,
    start=1
):
    print(f"{number}. {family}")

print(
    "\nTotal attack families:",
    len(ATTACK_FAMILIES)
)


# ================================================================
# 3.4 RANDOM SEEDS
# ================================================================

RANDOM_SEEDS = [
    13,
    29,
    47,
    71,
    101
]

PRIMARY_SEED = RANDOM_SEEDS[0]

print("\n[4] Random seeds")
print("-" * 72)

print("Seeds        :", RANDOM_SEEDS)
print("Primary seed :", PRIMARY_SEED)


# ================================================================
# 3.5 TEMPORAL CONFIGURATION
# ================================================================

TEMPORAL_WINDOW = 8
TEMPORAL_STRIDE = 8

print("\n[5] Temporal configuration")
print("-" * 72)

print(
    "Window size (T) :",
    TEMPORAL_WINDOW
)

print(
    "Window stride   :",
    TEMPORAL_STRIDE
)


# ================================================================
# 3.6 SELF-SUPERVISED LEARNING CONFIGURATION
# ================================================================

SSL_TEMPERATURE = 0.2

LAMBDA_T_CANDIDATES = [
    0.1,
    0.25,
    0.5,
    1.0
]

# IMPORTANT:
# The final lambda_t value will NOT be chosen here.
# It must later be selected using development/validation data only.

SELECTED_LAMBDA_T = None


print("\n[6] Self-supervised configuration")
print("-" * 72)

print(
    "NT-Xent temperature :",
    SSL_TEMPERATURE
)

print(
    "Lambda_t candidates :",
    LAMBDA_T_CANDIDATES
)

print(
    "Selected lambda_t   :",
    SELECTED_LAMBDA_T,
    "(will be selected later using development data)"
)


# ================================================================
# 3.7 TRAINING CONFIGURATION
# ================================================================

SSL_EPOCHS = 30
FINETUNE_EPOCHS = 20

BATCH_SIZE = 256

LEARNING_RATE_SSL = 1e-3
LEARNING_RATE_FINETUNE = 1e-3


print("\n[7] Training configuration")
print("-" * 72)

print("SSL epochs             :", SSL_EPOCHS)
print("Fine-tuning epochs     :", FINETUNE_EPOCHS)
print("Batch size             :", BATCH_SIZE)
print("SSL learning rate      :", LEARNING_RATE_SSL)
print(
    "Fine-tune learning rate:",
    LEARNING_RATE_FINETUNE
)


# ================================================================
# 3.8 SENSITIVITY EXPERIMENT SETTINGS
# ================================================================

# ------------------------------------------------
# Paper-defined requirement:
# lambda_t sensitivity
# ------------------------------------------------

LAMBDA_SENSITIVITY_VALUES = (
    LAMBDA_T_CANDIDATES.copy()
)


# ------------------------------------------------
# Notebook implementation choices:
#
# The research requires window-size and class-
# imbalance sensitivity, but their exact candidate
# values will be finalized later.
# ------------------------------------------------

WINDOW_SENSITIVITY_VALUES = [
    4,
    8,
    16
]

CLASS_IMBALANCE_METHODS = [
    "none",
    "class_weight",
    "weighted_sampler"
]


print("\n[8] Sensitivity-analysis configuration")
print("-" * 72)

print(
    "Lambda_t values :",
    LAMBDA_SENSITIVITY_VALUES
)

print(
    "Window values   :",
    WINDOW_SENSITIVITY_VALUES
)

print(
    "Imbalance tests :",
    CLASS_IMBALANCE_METHODS
)

print(
    "\nNOTE: Window and class-imbalance candidate "
    "sets are notebook implementation choices."
)


# ================================================================
# 3.9 OUTPUT DIRECTORY STRUCTURE
# ================================================================

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

DIRECTORIES = {
    "root":
        PROJECT_ROOT,

    "dataset":
        PROJECT_ROOT / "dataset",

    "dataset_audit":
        PROJECT_ROOT / "dataset_audit",

    "processed":
        PROJECT_ROOT / "processed_data",

    "models":
        PROJECT_ROOT / "models",

    "checkpoints":
        PROJECT_ROOT / "checkpoints",

    "predictions":
        PROJECT_ROOT / "predictions",

    "metrics":
        PROJECT_ROOT / "metrics",

    "figures":
        PROJECT_ROOT / "figures",

    "logs":
        PROJECT_ROOT / "logs",

    "sensitivity":
        PROJECT_ROOT / "sensitivity",

    "ablation":
        PROJECT_ROOT / "ablation",

    "statistics":
        PROJECT_ROOT / "statistics",

    "exports":
        PROJECT_ROOT / "final_exports"
}


print("\n[9] Creating experiment directories")
print("-" * 72)

for directory_name, directory_path in (
    DIRECTORIES.items()
):

    directory_path.mkdir(
        parents=True,
        exist_ok=True
    )

    print(
        f"✅ {directory_name:<15} "
        f"{directory_path}"
    )


# ================================================================
# 3.10 REPRODUCIBILITY FUNCTION
# ================================================================

def set_reproducibility(seed):
    """
    Set commonly used random seeds so that
    experiments are as reproducible as practical.
    """

    os.environ[
        "PYTHONHASHSEED"
    ] = str(seed)

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed(seed)

        torch.cuda.manual_seed_all(seed)

        torch.backends.cudnn.deterministic = True

        torch.backends.cudnn.benchmark = False


set_reproducibility(
    PRIMARY_SEED
)


print("\n[10] Reproducibility")
print("-" * 72)

print(
    "Global random seed initialized:",
    PRIMARY_SEED
)

print(
    "Deterministic cuDNN mode:",
    (
        torch.backends.cudnn.deterministic
        if torch.cuda.is_available()
        else "N/A"
    )
)


# ================================================================
# 3.11 BUILD EXPERIMENT CONFIGURATION
# ================================================================

EXPERIMENT_CONFIG = {

    "project_name":
        PROJECT_NAME,

    "device":
        str(DEVICE),

    "attack_families":
        ATTACK_FAMILIES,

    "random_seeds":
        RANDOM_SEEDS,

    "primary_seed":
        PRIMARY_SEED,

    "temporal_window":
        TEMPORAL_WINDOW,

    "temporal_stride":
        TEMPORAL_STRIDE,

    "ssl_temperature":
        SSL_TEMPERATURE,

    "lambda_t_candidates":
        LAMBDA_T_CANDIDATES,

    "selected_lambda_t":
        SELECTED_LAMBDA_T,

    "ssl_epochs":
        SSL_EPOCHS,

    "finetune_epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "ssl_learning_rate":
        LEARNING_RATE_SSL,

    "finetune_learning_rate":
        LEARNING_RATE_FINETUNE,

    "window_sensitivity_values":
        WINDOW_SENSITIVITY_VALUES,

    "class_imbalance_methods":
        CLASS_IMBALANCE_METHODS
}


# ================================================================
# 3.12 SAVE CONFIGURATION FILE
# ================================================================

CONFIG_PATH = (
    PROJECT_ROOT
    / "experiment_config.json"
)

with open(
    CONFIG_PATH,
    "w"
) as file:

    json.dump(
        EXPERIMENT_CONFIG,
        file,
        indent=4
    )


print("\n[11] Configuration file")
print("-" * 72)

print(
    "Saved to:",
    CONFIG_PATH
)


# ================================================================
# 3.13 DISPLAY FINAL CONFIGURATION
# ================================================================

print("\n[12] Final experiment configuration")
print("-" * 72)

print(
    json.dumps(
        EXPERIMENT_CONFIG,
        indent=4
    )
)


# ================================================================
# 3.14 FINAL STATUS
# ================================================================

configuration_valid = (

    len(ATTACK_FAMILIES) == 7

    and

    len(RANDOM_SEEDS) == 5

    and

    TEMPORAL_WINDOW == 8

    and

    len(LAMBDA_T_CANDIDATES) == 4

    and

    CONFIG_PATH.exists()
)


print("\n" + "=" * 72)

if configuration_valid:

    print(
        "✅ SECTION 3 PASSED — "
        "Global experiment configuration is ready."
    )

else:

    print(
        "❌ SECTION 3 FAILED — "
        "Configuration validation failed."
    )

print("=" * 72)

========================================================================
SECTION 3 — REPRODUCIBILITY AND GLOBAL CONFIGURATION
========================================================================

[1] Project
------------------------------------------------------------------------
Project name : ZeroDay_IoT_Final_Training

[2] Computing device
------------------------------------------------------------------------
Device : cuda
GPU    : Tesla T4

[3] LOAFO attack families
------------------------------------------------------------------------
1. DDoS
2. DoS
3. Mirai
4. Recon
5. Spoofing
6. Web
7. BruteForce

Total attack families: 7

[4] Random seeds
------------------------------------------------------------------------
Seeds        : [13, 29, 47, 71, 101]
Primary seed : 13

[5] Temporal configuration
------------------------------------------------------------------------
Window size (T) : 8
Window stride   : 8

[6] Self-supervised configuration
------------------------------------------------------------------------
NT-Xent temperature : 0.2
Lambda_t candidates : [0.1, 0.25, 0.5, 1.0]
Selected lambda_t   : None (will be selected later using development data)

[7] Training configuration
------------------------------------------------------------------------
SSL epochs             : 30
Fine-tuning epochs     : 20
Batch size             : 256
SSL learning rate      : 0.001
Fine-tune learning rate: 0.001

[8] Sensitivity-analysis configuration
------------------------------------------------------------------------
Lambda_t values : [0.1, 0.25, 0.5, 1.0]
Window values   : [4, 8, 16]
Imbalance tests : ['none', 'class_weight', 'weighted_sampler']

NOTE: Window and class-imbalance candidate sets are notebook implementation choices.

[9] Creating experiment directories
------------------------------------------------------------------------
✅ root            /content/ZeroDay_IoT_Research
✅ dataset         /content/ZeroDay_IoT_Research/dataset
✅ dataset_audit   /content/ZeroDay_IoT_Research/dataset_audit
✅ processed       /content/ZeroDay_IoT_Research/processed_data
✅ models          /content/ZeroDay_IoT_Research/models
✅ checkpoints     /content/ZeroDay_IoT_Research/checkpoints
✅ predictions     /content/ZeroDay_IoT_Research/predictions
✅ metrics         /content/ZeroDay_IoT_Research/metrics
✅ figures         /content/ZeroDay_IoT_Research/figures
✅ logs            /content/ZeroDay_IoT_Research/logs
✅ sensitivity     /content/ZeroDay_IoT_Research/sensitivity
✅ ablation        /content/ZeroDay_IoT_Research/ablation
✅ statistics      /content/ZeroDay_IoT_Research/statistics
✅ exports         /content/ZeroDay_IoT_Research/final_exports

[10] Reproducibility
------------------------------------------------------------------------
Global random seed initialized: 13
Deterministic cuDNN mode: True

[11] Configuration file
------------------------------------------------------------------------
Saved to: /content/ZeroDay_IoT_Research/experiment_config.json

[12] Final experiment configuration
------------------------------------------------------------------------
{
    "project_name": "ZeroDay_IoT_Final_Training",
    "device": "cuda",
    "attack_families": [
        "DDoS",
        "DoS",
        "Mirai",
        "Recon",
        "Spoofing",
        "Web",
        "BruteForce"
    ],
    "random_seeds": [
        13,
        29,
        47,
        71,
        101
    ],
    "primary_seed": 13,
    "temporal_window": 8,
    "temporal_stride": 8,
    "ssl_temperature": 0.2,
    "lambda_t_candidates": [
        0.1,
        0.25,
        0.5,
        1.0
    ],
    "selected_lambda_t": null,
    "ssl_epochs": 30,
    "finetune_epochs": 20,
    "batch_size": 256,
    "ssl_learning_rate": 0.001,
    "finetune_learning_rate": 0.001,
    "window_sensitivity_values": [
        4,
        8,
        16
    ],
    "class_imbalance_methods": [
        "none",
        "class_weight",
        "weighted_sampler"
    ]
}

========================================================================
✅ SECTION 3 PASSED — Global experiment configuration is ready.
========================================================================

# STEP 4 — Acquire the Timestamp-Preserving CICIoT2023 Dataset

# STEP 4A — Add a Markdown Cell
# 4. Acquire the Timestamp-Preserving CICIoT2023 Coverage Dataset

## 4.1 Purpose

This section acquires the timestamp-preserving network-flow data required for the temporal zero-day intrusion-detection experiment.

The dataset source is the CICIoT2023Small repository, which provides CICIoT2023-derived flow records containing genuine timestamps.

The research requires attack data from multiple attack families. Therefore, this notebook obtains data from the repository's CSV collection rather than relying only on the smaller Parquet collection.

---

## 4.2 Why the CSV Collection Is Used

An initial inspection of the repository's Parquet collection showed that it contained only a limited subset of attack classes.

That subset did not provide sufficient coverage for the seven-family Leave-One-Attack-Family-Out evaluation required by this research.

The CSV collection provides broader coverage, including attack types associated with:

- DDoS
- DoS
- Mirai
- Reconnaissance
- Spoofing
- Web-based attacks
- Brute-force attacks
- Benign traffic

---

## 4.3 Colab-Friendly Coverage Strategy

Downloading every capture from the source repository would require considerably more disk space and processing time.

Therefore, this notebook initially selects one timestamp-preserving CSV capture from every available attack-class directory.

This strategy preserves broad attack-class coverage while keeping the experiment practical in Google Colab.

The selected files represent a research coverage subset rather than the complete original CICIoT2023 corpus.

This distinction will be reported clearly in the final methodology.

---

## 4.4 Temporal Requirement

Each selected flow file must contain a genuine timestamp column.

The timestamp will later be used only to establish chronological ordering of flow records.

The timestamp will not be included as a model input feature.

---

## 4.5 Reproducibility

The notebook will save a dataset manifest containing:

- Attack-class directory
- Selected source file
- Local file path

This makes the exact coverage subset reproducible.

---

## 4.6 Expected Result

The section should:

- Discover the available CSV attack-class directories
- Select one CSV file from each directory
- Download the selected files
- Verify the presence of a timestamp
- Save the selected-file manifest
- Confirm broad family coverage

The section should finish with:

`✅ SECTION 4 PASSED — Timestamp-preserving CICIoT2023 coverage dataset is ready.

# STEP 4B — Download the Correct Dataset

In [ ]:
# ================================================================
# SECTION 4 — ACQUIRE TIMESTAMP-PRESERVING CICIoT2023
# COVERAGE DATASET
# ================================================================

import sys
import subprocess
from pathlib import Path

import pandas as pd

print("=" * 72)
print("SECTION 4 — CICIoT2023 TIMESTAMP-PRESERVING COVERAGE DATASET")
print("=" * 72)


# ================================================================
# 4.1 PREPARE HUGGING FACE CLIENT
# ================================================================

print("\n[1] Preparing download tools")
print("-" * 72)

try:
    import huggingface_hub

except ImportError:

    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "huggingface_hub"
    ])

    import huggingface_hub


from huggingface_hub import (
    list_repo_files,
    hf_hub_download
)


print(
    "✅ huggingface_hub version:",
    huggingface_hub.__version__
)


# ================================================================
# 4.2 DATASET CONFIGURATION
# ================================================================

HF_DATASET_REPO = (
    "somnath0100/CICIoT2023Small"
)

COVERAGE_DATA_DIR = (
    DIRECTORIES["dataset"]
    / "timestamp_coverage"
)

COVERAGE_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


MANIFEST_PATH = (
    DIRECTORIES["dataset_audit"]
    / "CICIoT2023_selected_files.csv"
)


print("\n[2] Dataset source")
print("-" * 72)

print("Repository :", HF_DATASET_REPO)
print("Local path :", COVERAGE_DATA_DIR)


# ================================================================
# 4.3 DISCOVER ALL AVAILABLE CSV FILES
# ================================================================

print("\n[3] Discovering available CSV files")
print("-" * 72)


repo_files = list_repo_files(
    repo_id=HF_DATASET_REPO,
    repo_type="dataset"
)


available_csv_files = sorted([
    file_name
    for file_name in repo_files
    if (
        file_name.startswith("CSVS/")
        and file_name.lower().endswith(".csv")
    )
])


print(
    "Total CSV files available:",
    len(available_csv_files)
)


if len(available_csv_files) == 0:

    raise RuntimeError(
        "No CSV files were discovered."
    )


# ================================================================
# 4.4 GROUP FILES BY ATTACK-CLASS DIRECTORY
# ================================================================

print("\n[4] Discovering attack-class directories")
print("-" * 72)


files_by_class = {}


for remote_file in available_csv_files:

    path_parts = Path(
        remote_file
    ).parts

    # Expected:
    # CSVS / AttackClass / filename.csv

    if len(path_parts) < 3:
        continue

    class_name = (
        path_parts[1]
    )

    files_by_class.setdefault(
        class_name,
        []
    ).append(
        remote_file
    )


attack_class_names = sorted(
    files_by_class.keys()
)


print(
    "Attack-class directories found:",
    len(attack_class_names)
)


for number, class_name in enumerate(
    attack_class_names,
    start=1
):

    print(
        f"{number:02d}. "
        f"{class_name:<30} "
        f"{len(files_by_class[class_name])} file(s)"
    )


# ================================================================
# 4.5 SELECT ONE CAPTURE PER ATTACK CLASS
# ================================================================

print("\n[5] Selecting one CSV per class")
print("-" * 72)


selected_remote_files = []


for class_name in attack_class_names:

    candidate_files = sorted(
        files_by_class[class_name],
        key=lambda file_path: (
            len(Path(file_path).name),
            Path(file_path).name
        )
    )

    selected_file = (
        candidate_files[0]
    )

    selected_remote_files.append(
        selected_file
    )

    print(
        f"{class_name:<30} "
        f"→ {Path(selected_file).name}"
    )


print(
    "\nSelected files:",
    len(selected_remote_files)
)


# ================================================================
# 4.6 DOWNLOAD SELECTED FILES
# ================================================================

print("\n[6] Downloading selected CSV files")
print("-" * 72)

print(
    "This may take some time."
)

print(
    "Please keep the Colab tab open until completion."
)


download_records = []

LOCAL_CSV_FILES = []


for file_number, remote_file in enumerate(
    selected_remote_files,
    start=1
):

    class_name = (
        Path(remote_file).parts[1]
    )

    print(
        f"\nDownloading "
        f"{file_number}/{len(selected_remote_files)}:"
    )

    print(
        remote_file
    )


    downloaded_path = hf_hub_download(
        repo_id=HF_DATASET_REPO,
        repo_type="dataset",
        filename=remote_file,
        local_dir=str(
            COVERAGE_DATA_DIR
        )
    )


    local_path = Path(
        downloaded_path
    )


    LOCAL_CSV_FILES.append(
        local_path
    )


    download_records.append({
        "attack_class_directory":
            class_name,

        "source_file":
            remote_file,

        "local_path":
            str(local_path),

        "size_mb":
            round(
                local_path.stat().st_size
                / (1024 ** 2),
                3
            )
    })


# ================================================================
# 4.7 CREATE DATASET MANIFEST
# ================================================================

print("\n[7] Creating dataset manifest")
print("-" * 72)


dataset_manifest = pd.DataFrame(
    download_records
)


dataset_manifest.to_csv(
    MANIFEST_PATH,
    index=False
)


display(
    dataset_manifest
)


print(
    "\n✅ Manifest saved to:"
)

print(
    MANIFEST_PATH
)


# ================================================================
# 4.8 VERIFY SAMPLE SCHEMA
# ================================================================

print("\n[8] Verifying timestamp-preserving schema")
print("-" * 72)


example_file = (
    LOCAL_CSV_FILES[0]
)


example_df = pd.read_csv(
    example_file,
    nrows=5,
    low_memory=False
)


EXAMPLE_COLUMNS = list(
    example_df.columns
)


print(
    "Example file:",
    example_file.name
)

print(
    "Columns:",
    len(EXAMPLE_COLUMNS)
)


timestamp_candidates = [
    column
    for column in EXAMPLE_COLUMNS
    if "timestamp" in column.lower()
]


print(
    "Timestamp candidates:",
    timestamp_candidates
)


if len(timestamp_candidates) != 1:

    raise RuntimeError(
        "A single Timestamp column "
        "could not be verified."
    )


TIMESTAMP_COLUMN = (
    timestamp_candidates[0]
)


# ================================================================
# 4.9 VERIFY IMPORTANT METADATA COLUMNS
# ================================================================

required_metadata_columns = [
    TIMESTAMP_COLUMN,
    "Label",
    "Category",
    "Attack Name"
]


missing_metadata_columns = [
    column
    for column in required_metadata_columns
    if column not in EXAMPLE_COLUMNS
]


if missing_metadata_columns:

    raise RuntimeError(
        "Required metadata columns missing: "
        + ", ".join(
            missing_metadata_columns
        )
    )


print(
    "✅ Timestamp column:",
    TIMESTAMP_COLUMN
)

print(
    "✅ Label column: Label"
)

print(
    "✅ Category column: Category"
)

print(
    "✅ Attack Name column: Attack Name"
)


# ================================================================
# 4.10 VERIFY BROAD ATTACK-FAMILY COVERAGE
# ================================================================

print("\n[9] Broad family-coverage check")
print("-" * 72)


available_names = set(
    attack_class_names
)


coverage_checks = {

    "DDoS":
        any(
            name.startswith("DDoS-")
            for name in available_names
        ),

    "DoS":
        any(
            name.startswith("DoS-")
            for name in available_names
        ),

    "Mirai":
        any(
            name.startswith("Mirai-")
            for name in available_names
        ),

    "Recon":
        any(
            name.startswith("Recon-")
            for name in available_names
        ),

    "Spoofing":
        (
            "DNS_Spoofing"
            in available_names
            or
            "MITM-ArpSpoofing"
            in available_names
        ),

    "BruteForce":
        (
            "DictionaryBruteForce"
            in available_names
        ),

    "Web":
        any(
            name in available_names
            for name in [
                "Backdoor_Malware",
                "BrowserHijacking",
                "CommandInjection",
                "SqlInjection",
                "XSS"
            ]
        ),

    "Benign":
        (
            "Benign_Final"
            in available_names
        )
}


for family, available in (
    coverage_checks.items()
):

    symbol = (
        "✅"
        if available
        else "❌"
    )

    print(
        f"{symbol} {family}"
    )


# ================================================================
# 4.11 STORE VARIABLES FOR LATER STEPS
# ================================================================

DATASET_ROOT = (
    COVERAGE_DATA_DIR
)

DATA_FILES = (
    LOCAL_CSV_FILES
)

CSV_FILES = (
    LOCAL_CSV_FILES
)


print("\n[10] Dataset variables")
print("-" * 72)


print(
    "DATASET_ROOT :",
    DATASET_ROOT
)

print(
    "DATA_FILES   :",
    len(DATA_FILES)
)

print(
    "Timestamp    :",
    TIMESTAMP_COLUMN
)


# ================================================================
# 4.12 TOTAL DOWNLOADED SIZE
# ================================================================

total_download_size_mb = (
    dataset_manifest[
        "size_mb"
    ].sum()
)


print(
    "\nTotal selected dataset size:",
    f"{total_download_size_mb:.2f} MB"
)


# ================================================================
# 4.13 FINAL VALIDATION
# ================================================================

all_required_coverage = all(
    coverage_checks.values()
)


section_4_valid = (

    len(DATA_FILES) > 0

    and

    TIMESTAMP_COLUMN is not None

    and

    len(missing_metadata_columns) == 0

    and

    all_required_coverage

    and

    MANIFEST_PATH.exists()
)


print("\n" + "=" * 72)


if section_4_valid:

    print(
        "✅ SECTION 4 PASSED — "
        "Timestamp-preserving CICIoT2023 "
        "coverage dataset is ready."
    )

else:

    print(
        "❌ SECTION 4 FAILED — "
        "Required attack-family coverage "
        "was not confirmed."
    )


print("=" * 72)

========================================================================
SECTION 4 — CICIoT2023 TIMESTAMP-PRESERVING COVERAGE DATASET
========================================================================

[1] Preparing download tools
------------------------------------------------------------------------
✅ huggingface_hub version: 1.29.0

[2] Dataset source
------------------------------------------------------------------------
Repository : somnath0100/CICIoT2023Small
Local path : /content/ZeroDay_IoT_Research/dataset/timestamp_coverage

[3] Discovering available CSV files
------------------------------------------------------------------------
Total CSV files available: 310

[4] Discovering attack-class directories
------------------------------------------------------------------------
Attack-class directories found: 33
01. Backdoor_Malware               1 file(s)
02. Benign_Final                   4 file(s)
03. BrowserHijacking               1 file(s)
04. CommandInjection               1 file(s)
05. DDoS-ACK_Fragmentation         13 file(s)
06. DDoS-HTTP_Flood                1 file(s)
07. DDoS-ICMP_Flood                27 file(s)
08. DDoS-ICMP_Fragmentation        20 file(s)
09. DDoS-PSHACK_Flood              18 file(s)
10. DDoS-RSTFINFlood               16 file(s)
11. DDoS-SYN_Flood                 16 file(s)
12. DDoS-SlowLoris                 1 file(s)
13. DDoS-SynonymousIP_Flood        14 file(s)
14. DDoS-TCP_Flood                 18 file(s)
15. DDoS-UDP_Flood                 21 file(s)
16. DDoS-UDP_Fragmentation         13 file(s)
17. DNS_Spoofing                   1 file(s)
18. DictionaryBruteForce           1 file(s)
19. DoS-HTTP_Flood                 2 file(s)
20. DoS-SYN_Flood                  8 file(s)
21. DoS-TCP_Flood                  11 file(s)
22. DoS-UDP_Flood                  17 file(s)
23. MITM-ArpSpoofing               2 file(s)
24. Mirai-greeth_flood             29 file(s)
25. Mirai-greip_flood              22 file(s)
26. Mirai-udpplain                 25 file(s)
27. Recon-HostDiscovery            1 file(s)
28. Recon-OSScan                   1 file(s)
29. Recon-PingSweep                1 file(s)
30. Recon-PortScan                 1 file(s)
31. SqlInjection                   1 file(s)
32. VulnerabilityScan              1 file(s)
33. XSS                            1 file(s)

[5] Selecting one CSV per class
------------------------------------------------------------------------
Backdoor_Malware               → Backdoor_Malware_1.csv
Benign_Final                   → Benign_1.csv
BrowserHijacking               → BrowserHijacking_1.csv
CommandInjection               → CommandInjection_1.csv
DDoS-ACK_Fragmentation         → DDoS-ACK_Fragmentation_1.csv
DDoS-HTTP_Flood                → DDoS-HTTP_Flood_1.csv
DDoS-ICMP_Flood                → DDoS-ICMP_Flood_1.csv
DDoS-ICMP_Fragmentation        → DDoS-ICMP_Fragmentation_1.csv
DDoS-PSHACK_Flood              → DDoS-PSHACK_Flood_1.csv
DDoS-RSTFINFlood               → DDoS-RSTFINFlood.pcap_Flow.csv
DDoS-SYN_Flood                 → DDoS-SYN_Flood.pcap_Flow.csv
DDoS-SlowLoris                 → DDoS-SlowLoris.pcap_Flow.csv
DDoS-SynonymousIP_Flood        → DDoS-SynonymousIP_Flood.pcap_Flow.csv
DDoS-TCP_Flood                 → DDoS-TCP_Flood.pcap_Flow.csv
DDoS-UDP_Flood                 → DDoS-UDP_Flood.pcap_Flow.csv
DDoS-UDP_Fragmentation         → DDoS-UDP_Fragmentation.pcap_Flow.csv
DNS_Spoofing                   → DNS_Spoofing.pcap_Flow.csv
DictionaryBruteForce           → DictionaryBruteForce.pcap_Flow.csv
DoS-HTTP_Flood                 → DoS-HTTP_Flood.pcap_Flow.csv
DoS-SYN_Flood                  → DoS-SYN_Flood.pcap_Flow.csv
DoS-TCP_Flood                  → DoS-TCP_Flood.pcap_Flow.csv
DoS-UDP_Flood                  → DoS-UDP_Flood.pcap_Flow.csv
MITM-ArpSpoofing               → MITM-ArpSpoofing.pcap_Flow.csv
Mirai-greeth_flood             → Mirai-greeth_flood.pcap_Flow.csv
Mirai-greip_flood              → Mirai-greip_flood.pcap_Flow.csv
Mirai-udpplain                 → Mirai-udpplain.pcap_Flow.csv
Recon-HostDiscovery            → Recon-HostDiscovery.pcap_Flow.csv
Recon-OSScan                   → Recon-OSScan.pcap_Flow.csv
Recon-PingSweep                → Recon-PingSweep.pcap_Flow.csv
Recon-PortScan                 → Recon-PortScan.pcap_Flow.csv
SqlInjection                   → SqlInjection.pcap_Flow.csv
VulnerabilityScan              → VulnerabilityScan.pcap_Flow.csv
XSS                            → XSS.pcap_Flow.csv

Selected files: 33

[6] Downloading selected CSV files
------------------------------------------------------------------------
This may take some time.
Please keep the Colab tab open until completion.

Downloading 1/33:
CSVS/Backdoor_Malware/Backdoor_Malware_1.csv

Backdoor_Malware_1.csv:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Downloading 2/33:
CSVS/Benign_Final/Benign_1.csv

CSVS/Benign_Final/Benign_1.csv: reconstructing file:   0%|          |  0.00B / 51.5MB

CSVS/Benign_Final/Benign_1.csv: downloading bytes:           |  0.00B

Downloading 3/33:
CSVS/BrowserHijacking/BrowserHijacking_1.csv

BrowserHijacking_1.csv:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

Downloading 4/33:
CSVS/CommandInjection/CommandInjection_1.csv

CommandInjection_1.csv:   0%|          | 0.00/2.19M [00:00<?, ?B/s]

Downloading 5/33:
CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fragmentation_1.csv

CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fra(…): reconstructing file:   0%|          |  0.00B / 20.5MB

CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fra(…): downloading bytes:           |  0.00B

Downloading 6/33:
CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.csv

CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.c(…): reconstructing file:   0%|          |  0.00B /  267MB

CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.c(…): downloading bytes:           |  0.00B

Downloading 7/33:
CSVS/DDoS-ICMP_Flood/DDoS-ICMP_Flood_1.csv

DDoS-ICMP_Flood_1.csv:   0%|          | 0.00/4.37M [00:00<?, ?B/s]

Downloading 8/33:
CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_Fragmentation_1.csv

CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_F(…): reconstructing file:   0%|          |  0.00B / 14.2MB

CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_F(…): downloading bytes:           |  0.00B

Downloading 9/33:
CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood_1.csv

CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood(…): reconstructing file:   0%|          |  0.00B / 2.70GB

CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood(…): downloading bytes:           |  0.00B

Downloading 10/33:
CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.pcap_Flow.csv

CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.p(…): reconstructing file:   0%|          |  0.00B / 5.97GB

CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.p(…): downloading bytes:           |  0.00B

Downloading 11/33:
CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_Flow.csv

CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 3.27GB

CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 12/33:
CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_Flow.csv

CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_(…): reconstructing file:   0%|          |  0.00B /  114MB

CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_(…): downloading bytes:           |  0.00B

Downloading 13/33:
CSVS/DDoS-SynonymousIP_Flood/DDoS-SynonymousIP_Flood.pcap_Flow.csv

CSVS/DDoS-SynonymousIP_Flood/DDoS-Synony(…): reconstructing file:   0%|          |  0.00B /  445MB

CSVS/DDoS-SynonymousIP_Flood/DDoS-Synony(…): downloading bytes:           |  0.00B

Downloading 14/33:
CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_Flow.csv

CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 2.55GB

CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 15/33:
CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_Flow.csv

CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 20.6MB

CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 16/33:
CSVS/DDoS-UDP_Fragmentation/DDoS-UDP_Fragmentation.pcap_Flow.csv

DDoS-UDP_Fragmentation.pcap_Flow.csv:   0%|          | 0.00/5.30M [00:00<?, ?B/s]

Downloading 17/33:
CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow.csv

CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow(…): reconstructing file:   0%|          |  0.00B / 40.6MB

CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow(…): downloading bytes:           |  0.00B

Downloading 18/33:
CSVS/DictionaryBruteForce/DictionaryBruteForce.pcap_Flow.csv

DictionaryBruteForce.pcap_Flow.csv:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

Downloading 19/33:
CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_Flow.csv

CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B /  417MB

CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 20/33:
CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Flow.csv

CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B / 2.06GB

CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

Downloading 21/33:
CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Flow.csv

CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B /  832MB

CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

Downloading 22/33:
CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Flow.csv

CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B /  522MB

CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

Downloading 23/33:
CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.pcap_Flow.csv

CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.p(…): reconstructing file:   0%|          |  0.00B / 38.2MB

CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.p(…): downloading bytes:           |  0.00B

Downloading 24/33:
CSVS/Mirai-greeth_flood/Mirai-greeth_flood.pcap_Flow.csv

Mirai-greeth_flood.pcap_Flow.csv:   0%|          | 0.00/2.69M [00:00<?, ?B/s]

Downloading 25/33:
CSVS/Mirai-greip_flood/Mirai-greip_flood.pcap_Flow.csv

Mirai-greip_flood.pcap_Flow.csv:   0%|          | 0.00/5.60M [00:00<?, ?B/s]

Downloading 26/33:
CSVS/Mirai-udpplain/Mirai-udpplain.pcap_Flow.csv

Mirai-udpplain.pcap_Flow.csv:   0%|          | 0.00/3.97M [00:00<?, ?B/s]

Downloading 27/33:
CSVS/Recon-HostDiscovery/Recon-HostDiscovery.pcap_Flow.csv

CSVS/Recon-HostDiscovery/Recon-HostDisco(…): reconstructing file:   0%|          |  0.00B /  141MB

CSVS/Recon-HostDiscovery/Recon-HostDisco(…): downloading bytes:           |  0.00B

Downloading 28/33:
CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow.csv

CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow(…): reconstructing file:   0%|          |  0.00B / 72.1MB

CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow(…): downloading bytes:           |  0.00B

Downloading 29/33:
CSVS/Recon-PingSweep/Recon-PingSweep.pcap_Flow.csv

Recon-PingSweep.pcap_Flow.csv:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

Downloading 30/33:
CSVS/Recon-PortScan/Recon-PortScan.pcap_Flow.csv

CSVS/Recon-PortScan/Recon-PortScan.pcap_(…): reconstructing file:   0%|          |  0.00B / 77.5MB

CSVS/Recon-PortScan/Recon-PortScan.pcap_(…): downloading bytes:           |  0.00B

Downloading 31/33:
CSVS/SqlInjection/SqlInjection.pcap_Flow.csv

SqlInjection.pcap_Flow.csv:   0%|          | 0.00/3.49M [00:00<?, ?B/s]

Downloading 32/33:
CSVS/VulnerabilityScan/VulnerabilityScan.pcap_Flow.csv

CSVS/VulnerabilityScan/VulnerabilityScan(…): reconstructing file:   0%|          |  0.00B /  226MB

CSVS/VulnerabilityScan/VulnerabilityScan(…): downloading bytes:           |  0.00B

Downloading 33/33:
CSVS/XSS/XSS.pcap_Flow.csv

XSS.pcap_Flow.csv:   0%|          | 0.00/1.75M [00:00<?, ?B/s]

[7] Creating dataset manifest
------------------------------------------------------------------------

,attack_class_directory,source_file,local_path,size_mb
0,Backdoor_Malware,CSVS/Backdoor_Malware/Backdoor_Malware_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1.518
1,Benign_Final,CSVS/Benign_Final/Benign_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,49.145
2,BrowserHijacking,CSVS/BrowserHijacking/BrowserHijacking_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1.824
3,CommandInjection,CSVS/CommandInjection/CommandInjection_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,2.089
4,DDoS-ACK_Fragmentation,CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fragmenta...,/content/ZeroDay_IoT_Research/dataset/timestam...,19.536
5,DDoS-HTTP_Flood,CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,254.233
6,DDoS-ICMP_Flood,CSVS/DDoS-ICMP_Flood/DDoS-ICMP_Flood_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,4.171
7,DDoS-ICMP_Fragmentation,CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_Fragmen...,/content/ZeroDay_IoT_Research/dataset/timestam...,13.576
8,DDoS-PSHACK_Flood,CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,2570.856
9,DDoS-RSTFINFlood,CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.pcap_Fl...,/content/ZeroDay_IoT_Research/dataset/timestam...,5690.623
10,DDoS-SYN_Flood,CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,3118.254
11,DDoS-SlowLoris,CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,108.606
12,DDoS-SynonymousIP_Flood,CSVS/DDoS-SynonymousIP_Flood/DDoS-SynonymousIP...,/content/ZeroDay_IoT_Research/dataset/timestam...,424.050
13,DDoS-TCP_Flood,CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,2432.449
14,DDoS-UDP_Flood,CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,19.632
15,DDoS-UDP_Fragmentation,CSVS/DDoS-UDP_Fragmentation/DDoS-UDP_Fragmenta...,/content/ZeroDay_IoT_Research/dataset/timestam...,5.058
16,DNS_Spoofing,CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,38.674
17,DictionaryBruteForce,CSVS/DictionaryBruteForce/DictionaryBruteForce...,/content/ZeroDay_IoT_Research/dataset/timestam...,4.474
18,DoS-HTTP_Flood,CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,397.445
19,DoS-SYN_Flood,CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1967.714
20,DoS-TCP_Flood,CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,792.980
21,DoS-UDP_Flood,CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,498.245
22,MITM-ArpSpoofing,CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.pcap_Fl...,/content/ZeroDay_IoT_Research/dataset/timestam...,36.446
23,Mirai-greeth_flood,CSVS/Mirai-greeth_flood/Mirai-greeth_flood.pca...,/content/ZeroDay_IoT_Research/dataset/timestam...,2.566
24,Mirai-greip_flood,CSVS/Mirai-greip_flood/Mirai-greip_flood.pcap_...,/content/ZeroDay_IoT_Research/dataset/timestam...,5.337
25,Mirai-udpplain,CSVS/Mirai-udpplain/Mirai-udpplain.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,3.783
26,Recon-HostDiscovery,CSVS/Recon-HostDiscovery/Recon-HostDiscovery.p...,/content/ZeroDay_IoT_Research/dataset/timestam...,134.262
27,Recon-OSScan,CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,68.765
28,Recon-PingSweep,CSVS/Recon-PingSweep/Recon-PingSweep.pcap_Flow...,/content/ZeroDay_IoT_Research/dataset/timestam...,0.973
29,Recon-PortScan,CSVS/Recon-PortScan/Recon-PortScan.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,73.923
30,SqlInjection,CSVS/SqlInjection/SqlInjection.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,3.329
31,VulnerabilityScan,CSVS/VulnerabilityScan/VulnerabilityScan.pcap_...,/content/ZeroDay_IoT_Research/dataset/timestam...,215.637
32,XSS,CSVS/XSS/XSS.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1.672

✅ Manifest saved to:
/content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_selected_files.csv

[8] Verifying timestamp-preserving schema
------------------------------------------------------------------------
Example file: Backdoor_Malware_1.csv
Columns: 86
Timestamp candidates: ['Timestamp']
✅ Timestamp column: Timestamp
✅ Label column: Label
✅ Category column: Category
✅ Attack Name column: Attack Name

[9] Broad family-coverage check
------------------------------------------------------------------------
✅ DDoS
✅ DoS
✅ Mirai
✅ Recon
✅ Spoofing
✅ BruteForce
✅ Web
✅ Benign

[10] Dataset variables
------------------------------------------------------------------------
DATASET_ROOT : /content/ZeroDay_IoT_Research/dataset/timestamp_coverage
DATA_FILES   : 33
Timestamp    : Timestamp

Total selected dataset size: 18961.85 MB

========================================================================
✅ SECTION 4 PASSED — Timestamp-preserving CICIoT2023 coverage dataset is ready.
========================================================================

# STEP 5 — CICIoT2023 Coverage Dataset Integrity and Metadata Audit
This version of Step 5 is specifically written for your 33 CSV files.

# STEP 5A — Replace the old Markdown cell

# 5. CICIoT2023 Dataset Integrity and Source-Class Audit

## 5.1 Purpose

This section validates the timestamp-preserving CICIoT2023 coverage dataset before preprocessing and model development.

The dataset contains two compatible schema variants:

- Some CSV files contain 86 columns.
- Some CSV files contain 84 columns.

The additional columns available in some files are:

- `Category`
- `Attack Name`

These two metadata columns are not consistently available across every selected source file.

Therefore, they will not be treated as mandatory dataset columns.

---

## 5.2 Common Dataset Structure

The columns consistently available across the selected dataset include:

- Network-flow features
- `Timestamp`
- `Label`

The `Timestamp` column is required for chronological ordering.

The `Label` column contains the source binary traffic label.

The common schema will be used as the basis for later preprocessing.

---

## 5.3 Source Attack-Class Metadata

Every downloaded CSV file came from a clearly identified attack-class directory in the source repository.

For example:

`CSVS/DDoS-TCP_Flood/...`

`CSVS/DoS-SYN_Flood/...`

`CSVS/Mirai-udpplain/...`

The Step 4 dataset manifest records this source directory for every selected file.

Therefore, source attack-class identity will be taken from the dataset manifest rather than requiring every CSV file to contain an `Attack Name` column.

This approach preserves the original repository organization without modifying the raw CSV files.

---

## 5.4 Timestamp Integrity

Every selected file will be checked for:

- Missing timestamps
- Invalid timestamps
- Earliest timestamp
- Latest timestamp

Timestamps will be used only for temporal ordering.

They will not be included as neural-network input features.

---

## 5.5 Label Integrity

The notebook will check:

- Missing binary labels
- Binary-label distribution

No labels will be modified during this section.

---

## 5.6 Schema Audit

The notebook will identify:

- Number of columns in each file
- Columns common to all files
- Optional metadata columns
- Common model-feature candidates

The existence of both 84-column and 86-column source files will be documented rather than treated as dataset corruption.

---

## 5.7 Source-Class Distribution

The notebook will count the number of records contributed by every selected source attack class.

The resulting distribution will later be used to construct the seven research attack families:

- DDoS
- DoS
- Mirai
- Recon
- Spoofing
- Web
- BruteForce

Benign traffic will be maintained separately.

---

## 5.8 Audit Outputs

This section will save:

`CICIoT2023_schema_audit.csv`

`CICIoT2023_integrity_audit.csv`

`CICIoT2023_source_class_distribution.csv`

`CICIoT2023_binary_label_distribution.csv`

These files provide a reproducible record of the selected dataset.

---

## 5.9 Research Integrity

This section does not:

- Modify source CSV files
- Generate timestamps
- Rename source labels
- Normalize features
- Impute feature values
- Construct temporal windows
- Perform train/test splitting

It performs dataset inspection only.

---

## 5.10 Expected Result

The section should confirm:

- All 33 selected files are readable
- Timestamp is available in every file
- Label is available in every file
- All timestamps are auditable
- Source attack classes are available from the manifest
- The common feature schema can be identified

The section should finish with:

`✅ SECTION 5 PASSED — CICIoT2023 dataset integrity audit completed successfully.`

# STEP 5B — Add the Code Cell

In [ ]:
# ================================================================
# SECTION 5 — CICIoT2023 DATASET INTEGRITY
# AND SOURCE-CLASS AUDIT
# ================================================================

from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

print("=" * 72)
print("SECTION 5 — CICIoT2023 DATASET INTEGRITY AUDIT")
print("=" * 72)


# ================================================================
# 5.1 REQUIRED COMMON COLUMNS
# ================================================================

TIMESTAMP_COLUMN = "Timestamp"
LABEL_COLUMN = "Label"

REQUIRED_COMMON_COLUMNS = [
    TIMESTAMP_COLUMN,
    LABEL_COLUMN
]


print("\n[1] Required common columns")
print("-" * 72)

print("✅ Timestamp :", TIMESTAMP_COLUMN)
print("✅ Label     :", LABEL_COLUMN)


# ================================================================
# 5.2 VERIFY STEP 4 VARIABLES
# ================================================================

print("\n[2] Verifying Step 4 variables")
print("-" * 72)


required_variables = [
    "DATA_FILES",
    "DATASET_ROOT",
    "dataset_manifest",
    "DIRECTORIES"
]


missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Step 4."
    )


if len(DATA_FILES) != len(dataset_manifest):

    raise RuntimeError(
        "DATA_FILES and dataset_manifest "
        "do not contain the same number of files."
    )


print(
    "Selected files :",
    len(DATA_FILES)
)

print(
    "Manifest rows  :",
    len(dataset_manifest)
)

print(
    "Dataset root   :",
    DATASET_ROOT
)


# ================================================================
# 5.3 OUTPUT PATHS
# ================================================================

SCHEMA_AUDIT_PATH = (
    DIRECTORIES["dataset_audit"]
    / "CICIoT2023_schema_audit.csv"
)

INTEGRITY_AUDIT_PATH = (
    DIRECTORIES["dataset_audit"]
    / "CICIoT2023_integrity_audit.csv"
)

SOURCE_CLASS_DISTRIBUTION_PATH = (
    DIRECTORIES["dataset_audit"]
    / "CICIoT2023_source_class_distribution.csv"
)

BINARY_LABEL_DISTRIBUTION_PATH = (
    DIRECTORIES["dataset_audit"]
    / "CICIoT2023_binary_label_distribution.csv"
)


# ================================================================
# 5.4 CREATE LOCAL-PATH → SOURCE-CLASS MAPPING
# ================================================================

print("\n[3] Building source-class mapping")
print("-" * 72)


source_class_by_path = {}


for _, row in dataset_manifest.iterrows():

    local_path = str(
        Path(
            row["local_path"]
        ).resolve()
    )

    source_class_by_path[
        local_path
    ] = row[
        "attack_class_directory"
    ]


print(
    "Source classes recorded:",
    len(source_class_by_path)
)


# ================================================================
# 5.5 SCHEMA AUDIT
# ================================================================

print("\n[4] Auditing CSV schemas")
print("-" * 72)


schema_records = []

column_sets = []


for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    header = pd.read_csv(
        file_path,
        nrows=0
    )

    columns = list(
        header.columns
    )

    column_sets.append(
        set(columns)
    )


    source_class = (
        source_class_by_path.get(
            str(
                Path(file_path).resolve()
            ),
            "UNKNOWN"
        )
    )


    missing_common = [
        column
        for column in REQUIRED_COMMON_COLUMNS
        if column not in columns
    ]


    schema_records.append({

        "file_number":
            file_number,

        "file_name":
            file_path.name,

        "source_class":
            source_class,

        "column_count":
            len(columns),

        "timestamp_present":
            TIMESTAMP_COLUMN in columns,

        "label_present":
            LABEL_COLUMN in columns,

        "category_present":
            "Category" in columns,

        "attack_name_present":
            "Attack Name" in columns,

        "missing_common_columns":
            " | ".join(
                missing_common
            ),

        "status":
            (
                "OK"
                if len(missing_common) == 0
                else "MISSING_COMMON_COLUMNS"
            )
    })


    print(
        f"{file_number:02d}/{len(DATA_FILES)} "
        f"{file_path.name:<45} "
        f"{len(columns)} columns"
    )


schema_audit = pd.DataFrame(
    schema_records
)


schema_audit.to_csv(
    SCHEMA_AUDIT_PATH,
    index=False
)


# ================================================================
# 5.6 IDENTIFY COMMON SCHEMA
# ================================================================

print("\n[5] Common schema analysis")
print("-" * 72)


COMMON_COLUMNS = set.intersection(
    *column_sets
)

ALL_COLUMNS = set.union(
    *column_sets
)


print(
    "Columns common to all files:",
    len(COMMON_COLUMNS)
)

print(
    "Total distinct columns     :",
    len(ALL_COLUMNS)
)


schema_sizes = (
    schema_audit[
        "column_count"
    ]
    .value_counts()
    .sort_index()
)


print(
    "\nSchema-size distribution:"
)

print(
    schema_sizes
)


optional_columns = sorted(
    ALL_COLUMNS
    -
    COMMON_COLUMNS
)


print(
    "\nOptional columns:"
)

print(
    optional_columns
)


if (
    TIMESTAMP_COLUMN not in COMMON_COLUMNS
    or
    LABEL_COLUMN not in COMMON_COLUMNS
):

    raise RuntimeError(
        "Timestamp or Label is not common "
        "to every dataset file."
    )


print(
    "\n✅ Timestamp and Label are common "
    "to every selected file."
)


# ================================================================
# 5.7 DEFINE COMMON MODEL FEATURES
# ================================================================

COMMON_REFERENCE_ORDER = [

    column

    for column in pd.read_csv(
        DATA_FILES[0],
        nrows=0
    ).columns

    if column in COMMON_COLUMNS
]


MODEL_FEATURE_CANDIDATES = [

    column

    for column in COMMON_REFERENCE_ORDER

    if column not in {
        TIMESTAMP_COLUMN,
        LABEL_COLUMN
    }
]


print("\n[6] Common model-feature candidates")
print("-" * 72)

print(
    "Common columns              :",
    len(COMMON_REFERENCE_ORDER)
)

print(
    "Metadata columns excluded   :",
    2
)

print(
    "Model feature candidates    :",
    len(MODEL_FEATURE_CANDIDATES)
)

print(
    "Timestamp used as feature   :",
    False
)


# ================================================================
# 5.8 CHUNK-BASED FULL INTEGRITY AUDIT
# ================================================================

print("\n[7] Starting full integrity audit")
print("-" * 72)

print(
    "Only Timestamp and Label will be "
    "read during this audit."
)

print(
    "This may take some time because "
    "all 33 selected files are checked."
)


CHUNK_SIZE = 250_000


integrity_records = []

binary_label_counter = Counter()

source_class_row_counts = Counter()


TOTAL_ROWS = 0

TOTAL_MISSING_TIMESTAMPS = 0

TOTAL_INVALID_TIMESTAMPS = 0

TOTAL_MISSING_LABELS = 0


for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    source_class = (
        source_class_by_path.get(
            str(
                Path(file_path).resolve()
            ),
            "UNKNOWN"
        )
    )


    print("\n" + "-" * 72)

    print(
        f"Auditing {file_number}/{len(DATA_FILES)}"
    )

    print(
        "File         :",
        file_path.name
    )

    print(
        "Source class :",
        source_class
    )


    file_rows = 0

    missing_timestamp_count = 0

    invalid_timestamp_count = 0

    missing_label_count = 0

    earliest_timestamp = None

    latest_timestamp = None


    try:

        reader = pd.read_csv(

            file_path,

            usecols=[
                TIMESTAMP_COLUMN,
                LABEL_COLUMN
            ],

            chunksize=CHUNK_SIZE,

            low_memory=False
        )


        for chunk in reader:

            rows = len(
                chunk
            )

            file_rows += rows


            # ====================================================
            # TIMESTAMP AUDIT
            # ====================================================

            timestamp_raw = (
                chunk[
                    TIMESTAMP_COLUMN
                ]
            )


            timestamp_text = (

                timestamp_raw

                .astype("string")

                .str.strip()
            )


            missing_timestamp_mask = (

                timestamp_raw.isna()

                |

                timestamp_text.eq("")
            )


            # pandas 2.x:
            # format="mixed" handles mixed timestamp
            # representations without repeated warnings.

            parsed_timestamp = pd.to_datetime(

                timestamp_raw,

                errors="coerce",

                utc=True,

                format="mixed"
            )


            invalid_timestamp_mask = (

                parsed_timestamp.isna()

                &

                ~missing_timestamp_mask
            )


            missing_timestamp_count += int(
                missing_timestamp_mask.sum()
            )


            invalid_timestamp_count += int(
                invalid_timestamp_mask.sum()
            )


            valid_timestamp = (
                parsed_timestamp.dropna()
            )


            if not valid_timestamp.empty:

                chunk_min = (
                    valid_timestamp.min()
                )

                chunk_max = (
                    valid_timestamp.max()
                )


                if (
                    earliest_timestamp is None
                    or
                    chunk_min < earliest_timestamp
                ):

                    earliest_timestamp = (
                        chunk_min
                    )


                if (
                    latest_timestamp is None
                    or
                    chunk_max > latest_timestamp
                ):

                    latest_timestamp = (
                        chunk_max
                    )


            # ====================================================
            # BINARY LABEL AUDIT
            # ====================================================

            raw_label = (
                chunk[
                    LABEL_COLUMN
                ]
            )


            missing_label_mask = (
                raw_label.isna()
            )


            missing_label_count += int(
                missing_label_mask.sum()
            )


            valid_labels = (
                raw_label[
                    ~missing_label_mask
                ]
            )


            binary_label_counter.update(
                valid_labels.tolist()
            )


        # ========================================================
        # SAVE FILE-LEVEL RESULT
        # ========================================================

        TOTAL_ROWS += (
            file_rows
        )


        TOTAL_MISSING_TIMESTAMPS += (
            missing_timestamp_count
        )


        TOTAL_INVALID_TIMESTAMPS += (
            invalid_timestamp_count
        )


        TOTAL_MISSING_LABELS += (
            missing_label_count
        )


        source_class_row_counts[
            source_class
        ] += file_rows


        integrity_records.append({

            "file_name":
                file_path.name,

            "source_class":
                source_class,

            "rows":
                file_rows,

            "missing_timestamps":
                missing_timestamp_count,

            "invalid_timestamps":
                invalid_timestamp_count,

            "missing_labels":
                missing_label_count,

            "earliest_timestamp":
                (
                    str(earliest_timestamp)
                    if earliest_timestamp is not None
                    else ""
                ),

            "latest_timestamp":
                (
                    str(latest_timestamp)
                    if latest_timestamp is not None
                    else ""
                ),

            "status":
                "OK"
        })


        print(
            "Rows               :",
            f"{file_rows:,}"
        )

        print(
            "Missing timestamps :",
            f"{missing_timestamp_count:,}"
        )

        print(
            "Invalid timestamps :",
            f"{invalid_timestamp_count:,}"
        )

        print(
            "Missing labels     :",
            f"{missing_label_count:,}"
        )


    except Exception as error:

        integrity_records.append({

            "file_name":
                file_path.name,

            "source_class":
                source_class,

            "rows":
                file_rows,

            "missing_timestamps":
                np.nan,

            "invalid_timestamps":
                np.nan,

            "missing_labels":
                np.nan,

            "earliest_timestamp":
                "",

            "latest_timestamp":
                "",

            "status":
                f"ERROR: {error}"
        })


        print(
            "❌ ERROR:",
            error
        )


# ================================================================
# 5.9 SAVE INTEGRITY AUDIT
# ================================================================

integrity_audit = pd.DataFrame(
    integrity_records
)


integrity_audit.to_csv(
    INTEGRITY_AUDIT_PATH,
    index=False
)


print("\n[8] File-level integrity audit")
print("-" * 72)


display(
    integrity_audit
)


# ================================================================
# 5.10 SOURCE ATTACK-CLASS DISTRIBUTION
# ================================================================

print("\n[9] Source attack-class distribution")
print("-" * 72)


source_class_distribution = (
    pd.DataFrame(

        source_class_row_counts.items(),

        columns=[
            "source_attack_class",
            "count"
        ]
    )

    .sort_values(
        "count",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


source_class_distribution[
    "percentage"
] = (

    source_class_distribution[
        "count"
    ]

    /

    source_class_distribution[
        "count"
    ].sum()

    * 100
)


source_class_distribution.to_csv(

    SOURCE_CLASS_DISTRIBUTION_PATH,

    index=False
)


display(
    source_class_distribution
)


# ================================================================
# 5.11 BINARY LABEL DISTRIBUTION
# ================================================================

print("\n[10] Binary Label distribution")
print("-" * 72)


binary_label_distribution = (
    pd.DataFrame(

        binary_label_counter.items(),

        columns=[
            "label",
            "count"
        ]
    )

    .sort_values(
        "count",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


binary_label_distribution[
    "percentage"
] = (

    binary_label_distribution[
        "count"
    ]

    /

    binary_label_distribution[
        "count"
    ].sum()

    * 100
)


binary_label_distribution.to_csv(

    BINARY_LABEL_DISTRIBUTION_PATH,

    index=False
)


display(
    binary_label_distribution
)


# ================================================================
# 5.12 OVERALL DATASET SUMMARY
# ================================================================

print("\n[11] Overall dataset summary")
print("-" * 72)


successful_files = int(

    integrity_audit[
        "status"
    ]
    .eq("OK")
    .sum()
)


print(
    "Selected files             :",
    len(DATA_FILES)
)

print(
    "Successfully audited files :",
    successful_files
)

print(
    "Total rows                 :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Source attack classes      :",
    len(source_class_row_counts)
)

print(
    "Common columns             :",
    len(COMMON_REFERENCE_ORDER)
)

print(
    "Model feature candidates   :",
    len(MODEL_FEATURE_CANDIDATES)
)

print(
    "Missing timestamps         :",
    f"{TOTAL_MISSING_TIMESTAMPS:,}"
)

print(
    "Invalid timestamps         :",
    f"{TOTAL_INVALID_TIMESTAMPS:,}"
)

print(
    "Missing labels             :",
    f"{TOTAL_MISSING_LABELS:,}"
)

print(
    "Timestamp used as feature  :",
    False
)


# ================================================================
# 5.13 VALIDATE EXPECTED SOURCE CLASSES
# ================================================================

print("\n[12] Source-class coverage")
print("-" * 72)


print(
    "Source classes identified:",
    len(source_class_row_counts)
)


for number, source_class in enumerate(

    sorted(
        source_class_row_counts.keys()
    ),

    start=1
):

    print(
        f"{number:02d}. {source_class}"
    )


# ================================================================
# 5.14 FINAL VALIDATION
# ================================================================

section_5_valid = (

    successful_files
    ==
    len(DATA_FILES)

    and

    TOTAL_ROWS > 0

    and

    len(
        source_class_row_counts
    ) == 33

    and

    TIMESTAMP_COLUMN
    in COMMON_COLUMNS

    and

    LABEL_COLUMN
    in COMMON_COLUMNS

    and

    TOTAL_MISSING_TIMESTAMPS == 0

    and

    TOTAL_INVALID_TIMESTAMPS == 0

    and

    SCHEMA_AUDIT_PATH.exists()

    and

    INTEGRITY_AUDIT_PATH.exists()

    and

    SOURCE_CLASS_DISTRIBUTION_PATH.exists()

    and

    BINARY_LABEL_DISTRIBUTION_PATH.exists()
)


print("\n" + "=" * 72)


if section_5_valid:

    print(
        "✅ SECTION 5 PASSED — "
        "CICIoT2023 dataset integrity "
        "audit completed successfully."
    )

else:

    print(
        "❌ SECTION 5 FAILED — "
        "Dataset integrity audit "
        "requires further review."
    )


print("=" * 72)

========================================================================
SECTION 5 — CICIoT2023 DATASET INTEGRITY AUDIT
========================================================================

[1] Required common columns
------------------------------------------------------------------------
✅ Timestamp : Timestamp
✅ Label     : Label

[2] Verifying Step 4 variables
------------------------------------------------------------------------
Selected files : 33
Manifest rows  : 33
Dataset root   : /content/ZeroDay_IoT_Research/dataset/timestamp_coverage

[3] Building source-class mapping
------------------------------------------------------------------------
Source classes recorded: 33

[4] Auditing CSV schemas
------------------------------------------------------------------------
01/33 Backdoor_Malware_1.csv                        86 columns
02/33 Benign_1.csv                                  86 columns
03/33 BrowserHijacking_1.csv                        86 columns
04/33 CommandInjection_1.csv                        86 columns
05/33 DDoS-ACK_Fragmentation_1.csv                  86 columns
06/33 DDoS-HTTP_Flood_1.csv                         86 columns
07/33 DDoS-ICMP_Flood_1.csv                         86 columns
08/33 DDoS-ICMP_Fragmentation_1.csv                 86 columns
09/33 DDoS-PSHACK_Flood_1.csv                       86 columns
10/33 DDoS-RSTFINFlood.pcap_Flow.csv                84 columns
11/33 DDoS-SYN_Flood.pcap_Flow.csv                  84 columns
12/33 DDoS-SlowLoris.pcap_Flow.csv                  84 columns
13/33 DDoS-SynonymousIP_Flood.pcap_Flow.csv         84 columns
14/33 DDoS-TCP_Flood.pcap_Flow.csv                  84 columns
15/33 DDoS-UDP_Flood.pcap_Flow.csv                  84 columns
16/33 DDoS-UDP_Fragmentation.pcap_Flow.csv          84 columns
17/33 DNS_Spoofing.pcap_Flow.csv                    84 columns
18/33 DictionaryBruteForce.pcap_Flow.csv            84 columns
19/33 DoS-HTTP_Flood.pcap_Flow.csv                  84 columns
20/33 DoS-SYN_Flood.pcap_Flow.csv                   84 columns
21/33 DoS-TCP_Flood.pcap_Flow.csv                   84 columns
22/33 DoS-UDP_Flood.pcap_Flow.csv                   84 columns
23/33 MITM-ArpSpoofing.pcap_Flow.csv                84 columns
24/33 Mirai-greeth_flood.pcap_Flow.csv              84 columns
25/33 Mirai-greip_flood.pcap_Flow.csv               84 columns
26/33 Mirai-udpplain.pcap_Flow.csv                  84 columns
27/33 Recon-HostDiscovery.pcap_Flow.csv             84 columns
28/33 Recon-OSScan.pcap_Flow.csv                    84 columns
29/33 Recon-PingSweep.pcap_Flow.csv                 84 columns
30/33 Recon-PortScan.pcap_Flow.csv                  84 columns
31/33 SqlInjection.pcap_Flow.csv                    84 columns
32/33 VulnerabilityScan.pcap_Flow.csv               84 columns
33/33 XSS.pcap_Flow.csv                             84 columns

[5] Common schema analysis
------------------------------------------------------------------------
Columns common to all files: 84
Total distinct columns     : 86

Schema-size distribution:
column_count
84    24
86     9
Name: count, dtype: int64

Optional columns:
['Attack Name', 'Category']

✅ Timestamp and Label are common to every selected file.

[6] Common model-feature candidates
------------------------------------------------------------------------
Common columns              : 84
Metadata columns excluded   : 2
Model feature candidates    : 82
Timestamp used as feature   : False

[7] Starting full integrity audit
------------------------------------------------------------------------
Only Timestamp and Label will be read during this audit.
This may take some time because all 33 selected files are checked.

------------------------------------------------------------------------
Auditing 1/33
File         : Backdoor_Malware_1.csv
Source class : Backdoor_Malware
Rows               : 2,703
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 2/33
File         : Benign_1.csv
Source class : Benign_Final
Rows               : 91,506
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 3/33
File         : BrowserHijacking_1.csv
Source class : BrowserHijacking
Rows               : 3,286
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 4/33
File         : CommandInjection_1.csv
Source class : CommandInjection
Rows               : 3,848
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 5/33
File         : DDoS-ACK_Fragmentation_1.csv
Source class : DDoS-ACK_Fragmentation
Rows               : 37,296
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 6/33
File         : DDoS-HTTP_Flood_1.csv
Source class : DDoS-HTTP_Flood
Rows               : 513,672
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 7/33
File         : DDoS-ICMP_Flood_1.csv
Source class : DDoS-ICMP_Flood
Rows               : 7,834
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 8/33
File         : DDoS-ICMP_Fragmentation_1.csv
Source class : DDoS-ICMP_Fragmentation
Rows               : 25,106
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 9/33
File         : DDoS-PSHACK_Flood_1.csv
Source class : DDoS-PSHACK_Flood
Rows               : 5,007,067
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 10/33
File         : DDoS-RSTFINFlood.pcap_Flow.csv
Source class : DDoS-RSTFINFlood
Rows               : 12,968,618
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 11/33
File         : DDoS-SYN_Flood.pcap_Flow.csv
Source class : DDoS-SYN_Flood
Rows               : 6,366,353
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 12/33
File         : DDoS-SlowLoris.pcap_Flow.csv
Source class : DDoS-SlowLoris
Rows               : 196,578
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 13/33
File         : DDoS-SynonymousIP_Flood.pcap_Flow.csv
Source class : DDoS-SynonymousIP_Flood
Rows               : 799,351
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 14/33
File         : DDoS-TCP_Flood.pcap_Flow.csv
Source class : DDoS-TCP_Flood
Rows               : 4,945,887
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 15/33
File         : DDoS-UDP_Flood.pcap_Flow.csv
Source class : DDoS-UDP_Flood
Rows               : 41,146
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 16/33
File         : DDoS-UDP_Fragmentation.pcap_Flow.csv
Source class : DDoS-UDP_Fragmentation
Rows               : 9,757
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 17/33
File         : DNS_Spoofing.pcap_Flow.csv
Source class : DNS_Spoofing
Rows               : 74,938
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 18/33
File         : DictionaryBruteForce.pcap_Flow.csv
Source class : DictionaryBruteForce
Rows               : 8,488
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 19/33
File         : DoS-HTTP_Flood.pcap_Flow.csv
Source class : DoS-HTTP_Flood
Rows               : 965,554
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 20/33
File         : DoS-SYN_Flood.pcap_Flow.csv
Source class : DoS-SYN_Flood
Rows               : 3,997,110
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 21/33
File         : DoS-TCP_Flood.pcap_Flow.csv
Source class : DoS-TCP_Flood
Rows               : 1,638,068
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 22/33
File         : DoS-UDP_Flood.pcap_Flow.csv
Source class : DoS-UDP_Flood
Rows               : 934,009
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 23/33
File         : MITM-ArpSpoofing.pcap_Flow.csv
Source class : MITM-ArpSpoofing
Rows               : 72,853
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 24/33
File         : Mirai-greeth_flood.pcap_Flow.csv
Source class : Mirai-greeth_flood
Rows               : 5,155
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 25/33
File         : Mirai-greip_flood.pcap_Flow.csv
Source class : Mirai-greip_flood
Rows               : 10,401
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 26/33
File         : Mirai-udpplain.pcap_Flow.csv
Source class : Mirai-udpplain
Rows               : 7,455
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 27/33
File         : Recon-HostDiscovery.pcap_Flow.csv
Source class : Recon-HostDiscovery
Rows               : 329,985
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 28/33
File         : Recon-OSScan.pcap_Flow.csv
Source class : Recon-OSScan
Rows               : 158,682
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 29/33
File         : Recon-PingSweep.pcap_Flow.csv
Source class : Recon-PingSweep
Rows               : 1,947
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 30/33
File         : Recon-PortScan.pcap_Flow.csv
Source class : Recon-PortScan
Rows               : 175,050
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 31/33
File         : SqlInjection.pcap_Flow.csv
Source class : SqlInjection
Rows               : 6,596
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 32/33
File         : VulnerabilityScan.pcap_Flow.csv
Source class : VulnerabilityScan
Rows               : 442,122
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

------------------------------------------------------------------------
Auditing 33/33
File         : XSS.pcap_Flow.csv
Source class : XSS
Rows               : 3,198
Missing timestamps : 0
Invalid timestamps : 0
Missing labels     : 0

[8] File-level integrity audit
------------------------------------------------------------------------

,file_name,source_class,rows,missing_timestamps,invalid_timestamps,missing_labels,earliest_timestamp,latest_timestamp,status
0,Backdoor_Malware_1.csv,Backdoor_Malware,2703,0,0,0,2023-02-13 13:58:00+00:00,2023-02-13 14:32:00+00:00,OK
1,Benign_1.csv,Benign_Final,91506,0,0,0,2022-08-10 09:45:21+00:00,2022-08-10 17:47:19+00:00,OK
2,BrowserHijacking_1.csv,BrowserHijacking,3286,0,0,0,2022-11-14 20:23:00+00:00,2022-11-14 20:48:59+00:00,OK
3,CommandInjection_1.csv,CommandInjection,3848,0,0,0,2023-02-14 14:53:00+00:00,2023-02-14 15:32:00+00:00,OK
4,DDoS-ACK_Fragmentation_1.csv,DDoS-ACK_Fragmentation,37296,0,0,0,2022-10-26 19:56:11+00:00,2022-10-26 20:21:00+00:00,OK
5,DDoS-HTTP_Flood_1.csv,DDoS-HTTP_Flood,513672,0,0,0,2022-07-11 14:30:00+00:00,2022-09-14 14:14:44+00:00,OK
6,DDoS-ICMP_Flood_1.csv,DDoS-ICMP_Flood,7834,0,0,0,2022-06-09 19:30:59+00:00,2022-06-09 19:59:37+00:00,OK
7,DDoS-ICMP_Fragmentation_1.csv,DDoS-ICMP_Fragmentation,25106,0,0,0,2022-05-10 14:26:57+00:00,2022-05-10 16:50:25+00:00,OK
8,DDoS-PSHACK_Flood_1.csv,DDoS-PSHACK_Flood,5007067,0,0,0,2022-10-20 13:55:00+00:00,2022-10-20 14:47:57+00:00,OK
9,DDoS-RSTFINFlood.pcap_Flow.csv,DDoS-RSTFINFlood,12968618,0,0,0,2022-10-26 20:43:00+00:00,2022-10-27 12:45:52+00:00,OK
10,DDoS-SYN_Flood.pcap_Flow.csv,DDoS-SYN_Flood,6366353,0,0,0,2022-08-26 18:18:00+00:00,2022-08-29 12:31:44+00:00,OK
11,DDoS-SlowLoris.pcap_Flow.csv,DDoS-SlowLoris,196578,0,0,0,2022-03-11 18:18:00+00:00,2022-04-11 13:23:59+00:00,OK
12,DDoS-SynonymousIP_Flood.pcap_Flow.csv,DDoS-SynonymousIP_Flood,799351,0,0,0,2022-10-31 12:49:00+00:00,2022-10-31 13:40:37+00:00,OK
13,DDoS-TCP_Flood.pcap_Flow.csv,DDoS-TCP_Flood,4945887,0,0,0,2022-08-16 16:33:00+00:00,2022-08-16 19:03:37+00:00,OK
14,DDoS-UDP_Flood.pcap_Flow.csv,DDoS-UDP_Flood,41146,0,0,0,2022-08-31 13:19:00+00:00,2022-08-31 14:31:15+00:00,OK
15,DDoS-UDP_Fragmentation.pcap_Flow.csv,DDoS-UDP_Fragmentation,9757,0,0,0,2022-01-11 17:44:00+00:00,2022-01-11 18:36:12+00:00,OK
16,DNS_Spoofing.pcap_Flow.csv,DNS_Spoofing,74938,0,0,0,2022-11-15 16:16:00+00:00,2022-11-16 20:25:00+00:00,OK
17,DictionaryBruteForce.pcap_Flow.csv,DictionaryBruteForce,8488,0,0,0,2022-10-14 16:18:00+00:00,2022-10-17 15:02:00+00:00,OK
18,DoS-HTTP_Flood.pcap_Flow.csv,DoS-HTTP_Flood,965554,0,0,0,2022-08-08 16:25:00+00:00,2022-09-08 13:45:43+00:00,OK
19,DoS-SYN_Flood.pcap_Flow.csv,DoS-SYN_Flood,3997110,0,0,0,2022-02-08 13:42:00+00:00,2022-02-08 15:06:04+00:00,OK
20,DoS-TCP_Flood.pcap_Flow.csv,DoS-TCP_Flood,1638068,0,0,0,2022-07-22 14:41:31+00:00,2022-07-22 19:00:53+00:00,OK
21,DoS-UDP_Flood.pcap_Flow.csv,DoS-UDP_Flood,934009,0,0,0,2022-09-08 18:37:00+00:00,2022-10-08 13:19:33+00:00,OK
22,MITM-ArpSpoofing.pcap_Flow.csv,MITM-ArpSpoofing,72853,0,0,0,2022-10-17 20:20:00+00:00,2022-10-18 19:34:14+00:00,OK
23,Mirai-greeth_flood.pcap_Flow.csv,Mirai-greeth_flood,5155,0,0,0,2023-12-01 15:19:00+00:00,2023-12-01 15:37:06+00:00,OK
24,Mirai-greip_flood.pcap_Flow.csv,Mirai-greip_flood,10401,0,0,0,2022-12-19 16:23:00+00:00,2022-12-19 19:10:09+00:00,OK
25,Mirai-udpplain.pcap_Flow.csv,Mirai-udpplain,7455,0,0,0,2023-01-19 15:51:00+00:00,2023-01-19 16:23:25+00:00,OK
26,Recon-HostDiscovery.pcap_Flow.csv,Recon-HostDiscovery,329985,0,0,0,2022-11-14 22:38:00+00:00,2022-11-15 04:16:16+00:00,OK
27,Recon-OSScan.pcap_Flow.csv,Recon-OSScan,158682,0,0,0,2022-09-27 18:07:00+00:00,2022-09-28 19:38:00+00:00,OK
28,Recon-PingSweep.pcap_Flow.csv,Recon-PingSweep,1947,0,0,0,2022-09-29 16:58:00+00:00,2022-09-29 19:29:00+00:00,OK
29,Recon-PortScan.pcap_Flow.csv,Recon-PortScan,175050,0,0,0,2022-09-26 16:31:00+00:00,2022-09-27 17:16:00+00:00,OK
30,SqlInjection.pcap_Flow.csv,SqlInjection,6596,0,0,0,2022-03-10 17:17:00+00:00,2022-03-10 18:09:00+00:00,OK
31,VulnerabilityScan.pcap_Flow.csv,VulnerabilityScan,442122,0,0,0,2022-03-10 14:02:00+00:00,2022-04-10 12:31:03+00:00,OK
32,XSS.pcap_Flow.csv,XSS,3198,0,0,0,2023-02-14 15:46:00+00:00,2023-02-14 16:26:00+00:00,OK

[9] Source attack-class distribution
------------------------------------------------------------------------

        source_attack_class     count  percentage
0          DDoS-RSTFINFlood  12968618   32.542261
1            DDoS-SYN_Flood   6366353   15.975143
2         DDoS-PSHACK_Flood   5007067   12.564275
3            DDoS-TCP_Flood   4945887   12.410756
4             DoS-SYN_Flood   3997110   10.029981
5             DoS-TCP_Flood   1638068    4.110418
6            DoS-HTTP_Flood    965554    2.422873
7             DoS-UDP_Flood    934009    2.343717
8   DDoS-SynonymousIP_Flood    799351    2.005818
9           DDoS-HTTP_Flood    513672    1.288961
10        VulnerabilityScan    442122    1.109420
11      Recon-HostDiscovery    329985    0.828034
12           DDoS-SlowLoris    196578    0.493275
13           Recon-PortScan    175050    0.439254
14             Recon-OSScan    158682    0.398182
15             Benign_Final     91506    0.229617
16             DNS_Spoofing     74938    0.188043
17         MITM-ArpSpoofing     72853    0.182811
18           DDoS-UDP_Flood     41146    0.103248
19   DDoS-ACK_Fragmentation     37296    0.093587
20  DDoS-ICMP_Fragmentation     25106    0.062999
21        Mirai-greip_flood     10401    0.026099
22   DDoS-UDP_Fragmentation      9757    0.024483
23     DictionaryBruteForce      8488    0.021299
24          DDoS-ICMP_Flood      7834    0.019658
25           Mirai-udpplain      7455    0.018707
26             SqlInjection      6596    0.016551
27       Mirai-greeth_flood      5155    0.012935
28         CommandInjection      3848    0.009656
29         BrowserHijacking      3286    0.008246
30                      XSS      3198    0.008025
31         Backdoor_Malware      2703    0.006783
32          Recon-PingSweep      1947    0.004886

[10] Binary Label distribution
------------------------------------------------------------------------

             label     count  percentage
0  NeedManualLabel  34159301   85.716219
1               -1   5600812   14.054164
2                1     91506    0.229617

[11] Overall dataset summary
------------------------------------------------------------------------
Selected files             : 33
Successfully audited files : 33
Total rows                 : 39,851,619
Source attack classes      : 33
Common columns             : 84
Model feature candidates   : 82
Missing timestamps         : 0
Invalid timestamps         : 0
Missing labels             : 0
Timestamp used as feature  : False

[12] Source-class coverage
------------------------------------------------------------------------
Source classes identified: 33
01. Backdoor_Malware
02. Benign_Final
03. BrowserHijacking
04. CommandInjection
05. DDoS-ACK_Fragmentation
06. DDoS-HTTP_Flood
07. DDoS-ICMP_Flood
08. DDoS-ICMP_Fragmentation
09. DDoS-PSHACK_Flood
10. DDoS-RSTFINFlood
11. DDoS-SYN_Flood
12. DDoS-SlowLoris
13. DDoS-SynonymousIP_Flood
14. DDoS-TCP_Flood
15. DDoS-UDP_Flood
16. DDoS-UDP_Fragmentation
17. DNS_Spoofing
18. DictionaryBruteForce
19. DoS-HTTP_Flood
20. DoS-SYN_Flood
21. DoS-TCP_Flood
22. DoS-UDP_Flood
23. MITM-ArpSpoofing
24. Mirai-greeth_flood
25. Mirai-greip_flood
26. Mirai-udpplain
27. Recon-HostDiscovery
28. Recon-OSScan
29. Recon-PingSweep
30. Recon-PortScan
31. SqlInjection
32. VulnerabilityScan
33. XSS

========================================================================
✅ SECTION 5 PASSED — CICIoT2023 dataset integrity audit completed successfully.
========================================================================

# STEP 6 — Verified Mapping into the Seven Research Attack Families

# STEP 6A — Add the Markdown / Text Cell
# 6. Verified Mapping into the Seven Research Attack Families

## 6.1 Purpose

The purpose of this section is to convert the verified CICIoT2023 source attack classes into the seven higher-level attack families required by the research evaluation protocol.

The seven attack families are:

1. DDoS
2. DoS
3. Mirai
4. Recon
5. Spoofing
6. Web
7. BruteForce

Benign traffic is maintained separately.

These family assignments will later be used to implement strict seven-fold Leave-One-Attack-Family-Out (LOAFO) evaluation.

---

## 6.2 Why Attack-Family Mapping Is Required

The source dataset contains individual attack classes such as:

- DDoS-RSTFINFlood
- DoS-SYN_Flood
- Mirai-udpplain
- Recon-PortScan
- DNS_Spoofing
- SqlInjection
- DictionaryBruteForce

The research does not hold out individual attack subtypes.

Instead, one complete attack family is held out during each LOAFO fold.

For example:

**DDoS fold**

All DDoS attack subtypes are excluded from:

- Preprocessing fitting
- Self-supervised pretraining
- Supervised training
- Validation
- Hyperparameter selection
- Threshold selection

They appear only during final zero-day testing.

---

## 6.3 Verified Family Mapping

The available source attack classes are mapped as follows.

### DDoS

- DDoS-ACK_Fragmentation
- DDoS-HTTP_Flood
- DDoS-ICMP_Flood
- DDoS-ICMP_Fragmentation
- DDoS-PSHACK_Flood
- DDoS-RSTFINFlood
- DDoS-SYN_Flood
- DDoS-SlowLoris
- DDoS-SynonymousIP_Flood
- DDoS-TCP_Flood
- DDoS-UDP_Flood
- DDoS-UDP_Fragmentation

### DoS

- DoS-HTTP_Flood
- DoS-SYN_Flood
- DoS-TCP_Flood
- DoS-UDP_Flood

### Mirai

- Mirai-greeth_flood
- Mirai-greip_flood
- Mirai-udpplain

### Recon

- Recon-HostDiscovery
- Recon-OSScan
- Recon-PingSweep
- Recon-PortScan
- VulnerabilityScan

### Spoofing

- DNS_Spoofing
- MITM-ArpSpoofing

### Web

The notebook uses the internal family name `Web`.

This corresponds to the research paper's `Web-based` family.

Available timestamp-preserving Web attacks are:

- Backdoor_Malware
- BrowserHijacking
- CommandInjection
- SqlInjection
- XSS

### BruteForce

- DictionaryBruteForce

### Benign

- Benign_Final

---

## 6.4 Dataset Coverage Limitation

The original CICIoT2023 benchmark includes an additional Web-based attack:

`Uploading_Attack`

The timestamp-preserving coverage repository used by this notebook does not currently contain an `Uploading_Attack` source directory.

Therefore, the selected dataset contains:

- 32 available attack subtypes
- 7 attack families
- Benign traffic

The seven-family LOAFO experiment can still be performed because every required attack family is represented.

However, the final research documentation must describe the experimental dataset as a timestamp-preserving CICIoT2023 coverage subset rather than claiming that all 33 original attack subtypes were included.

---

## 6.5 Binary Research Target

The original `Label` column is preserved exactly as provided by the source data.

However, the audit showed that many source files contain the value:

`NeedManualLabel`

Therefore, the raw `Label` column will not be used as the final supervised-learning target.

Instead, the binary research target will be derived from the verified source attack class:

\[
BinaryTarget =
\begin{cases}
0, & \text{Benign}\\
1, & \text{Attack}
\end{cases}
\]

Thus:

`Benign_Final → 0`

and every verified attack class maps to:

`Attack → 1`

This derived target will be documented explicitly and will not overwrite the original source label.

---

## 6.6 Raw Data Preservation

The original CSV files will not be modified.

Instead, the notebook will create separate mapping tables describing:

- Source attack class
- Research family
- Binary target
- Number of records
- Percentage of selected dataset

Later processing stages will apply this mapping programmatically.

---

## 6.7 Output Files

This section will generate:

`CICIoT2023_attack_family_mapping.csv`

Contains the mapping from individual source attacks to research families.

`CICIoT2023_family_distribution.csv`

Contains the total number of records in each research family.

`CICIoT2023_file_research_metadata.csv`

Records the source class, family, and binary target associated with every selected dataset file.

---

## 6.8 LOAFO Families

The final attack-family list used by the experiment will be:

`DDoS`

`DoS`

`Mirai`

`Recon`

`Spoofing`

`Web`

`BruteForce`

Benign traffic is not a held-out zero-day family.

Benign examples are required for training, validation, false-positive-rate calculation, and binary intrusion detection.

---

## 6.9 Research Integrity Rules

This section will not:

- Modify raw CSV files
- Change timestamps
- Use the held-out family for preprocessing
- Create train/test splits
- Fit preprocessing parameters
- Normalize features
- Create temporal windows
- Train any model

It creates only deterministic research metadata.

---

## 6.10 Expected Result

The section should confirm:

- 33 source directories are accounted for
- 32 attack classes are mapped
- Benign is mapped separately
- No source class is unmapped
- Exactly seven attack families exist
- Every required LOAFO family has data
- Dataset row totals remain unchanged

The section should finish with:

`✅ SECTION 6 PASSED — Seven-family research mapping is valid.`

# STEP 6B — Add the Mapping Code Cell

In [ ]:
# ================================================================
# SECTION 6 — VERIFIED MAPPING INTO THE SEVEN
# RESEARCH ATTACK FAMILIES
# ================================================================

from pathlib import Path

import pandas as pd

print("=" * 72)
print("SECTION 6 — SEVEN-FAMILY ATTACK MAPPING")
print("=" * 72)


# ================================================================
# 6.1 DEFINE VERIFIED SOURCE-CLASS MAPPING
# ================================================================

SOURCE_CLASS_TO_FAMILY = {

    # ------------------------------------------------------------
    # DDoS
    # ------------------------------------------------------------

    "DDoS-ACK_Fragmentation":
        "DDoS",

    "DDoS-HTTP_Flood":
        "DDoS",

    "DDoS-ICMP_Flood":
        "DDoS",

    "DDoS-ICMP_Fragmentation":
        "DDoS",

    "DDoS-PSHACK_Flood":
        "DDoS",

    "DDoS-RSTFINFlood":
        "DDoS",

    "DDoS-SYN_Flood":
        "DDoS",

    "DDoS-SlowLoris":
        "DDoS",

    "DDoS-SynonymousIP_Flood":
        "DDoS",

    "DDoS-TCP_Flood":
        "DDoS",

    "DDoS-UDP_Flood":
        "DDoS",

    "DDoS-UDP_Fragmentation":
        "DDoS",


    # ------------------------------------------------------------
    # DoS
    # ------------------------------------------------------------

    "DoS-HTTP_Flood":
        "DoS",

    "DoS-SYN_Flood":
        "DoS",

    "DoS-TCP_Flood":
        "DoS",

    "DoS-UDP_Flood":
        "DoS",


    # ------------------------------------------------------------
    # Mirai
    # ------------------------------------------------------------

    "Mirai-greeth_flood":
        "Mirai",

    "Mirai-greip_flood":
        "Mirai",

    "Mirai-udpplain":
        "Mirai",


    # ------------------------------------------------------------
    # Recon
    # ------------------------------------------------------------

    "Recon-HostDiscovery":
        "Recon",

    "Recon-OSScan":
        "Recon",

    "Recon-PingSweep":
        "Recon",

    "Recon-PortScan":
        "Recon",

    "VulnerabilityScan":
        "Recon",


    # ------------------------------------------------------------
    # Spoofing
    # ------------------------------------------------------------

    "DNS_Spoofing":
        "Spoofing",

    "MITM-ArpSpoofing":
        "Spoofing",


    # ------------------------------------------------------------
    # Web-based
    #
    # Internal notebook name = Web
    # Research-paper name     = Web-based
    # ------------------------------------------------------------

    "Backdoor_Malware":
        "Web",

    "BrowserHijacking":
        "Web",

    "CommandInjection":
        "Web",

    "SqlInjection":
        "Web",

    "XSS":
        "Web",


    # ------------------------------------------------------------
    # Brute Force
    # ------------------------------------------------------------

    "DictionaryBruteForce":
        "BruteForce",


    # ------------------------------------------------------------
    # Benign
    # ------------------------------------------------------------

    "Benign_Final":
        "Benign"
}


# ================================================================
# 6.2 DEFINE OFFICIAL / RESEARCH FAMILY ORDER
# ================================================================

RESEARCH_ATTACK_FAMILIES = [

    "DDoS",
    "DoS",
    "Mirai",
    "Recon",
    "Spoofing",
    "Web",
    "BruteForce"
]


ALL_RESEARCH_CLASSES = (

    RESEARCH_ATTACK_FAMILIES

    +

    ["Benign"]
)


print("\n[1] Research families")
print("-" * 72)


for number, family in enumerate(
    RESEARCH_ATTACK_FAMILIES,
    start=1
):

    print(
        f"{number}. {family}"
    )


print(
    "\nBenign is maintained separately."
)


# ================================================================
# 6.3 VERIFY SOURCE CLASSES FROM STEP 5
# ================================================================

print("\n[2] Verifying source attack classes")
print("-" * 72)


observed_source_classes = set(

    source_class_distribution[
        "source_attack_class"
    ]
    .astype(str)
)


mapped_source_classes = set(

    SOURCE_CLASS_TO_FAMILY.keys()
)


unmapped_classes = sorted(

    observed_source_classes

    -

    mapped_source_classes
)


mapping_not_in_dataset = sorted(

    mapped_source_classes

    -

    observed_source_classes
)


print(
    "Observed source classes :",
    len(observed_source_classes)
)

print(
    "Mapping entries         :",
    len(mapped_source_classes)
)

print(
    "Unmapped source classes :",
    unmapped_classes
)


if mapping_not_in_dataset:

    print(
        "Mapping entries absent from dataset:",
        mapping_not_in_dataset
    )


if unmapped_classes:

    raise RuntimeError(
        "One or more observed source classes "
        "do not have a verified family mapping."
    )


print(
    "✅ Every observed source class is mapped."
)


# ================================================================
# 6.4 DOCUMENT ORIGINAL BENCHMARK COVERAGE DIFFERENCE
# ================================================================

print("\n[3] Benchmark-coverage note")
print("-" * 72)


OFFICIAL_WEB_ATTACKS = {

    "Backdoor_Malware",
    "BrowserHijacking",
    "CommandInjection",
    "SqlInjection",
    "Uploading_Attack",
    "XSS"
}


AVAILABLE_WEB_ATTACKS = {

    source_class

    for source_class, family
    in SOURCE_CLASS_TO_FAMILY.items()

    if family == "Web"
}


MISSING_OFFICIAL_WEB_ATTACKS = sorted(

    OFFICIAL_WEB_ATTACKS

    -

    AVAILABLE_WEB_ATTACKS
)


print(
    "Available Web attacks:",
    sorted(
        AVAILABLE_WEB_ATTACKS
    )
)

print(
    "Unavailable original benchmark attacks:",
    MISSING_OFFICIAL_WEB_ATTACKS
)


if (
    "Uploading_Attack"
    in MISSING_OFFICIAL_WEB_ATTACKS
):

    print(
        "\n⚠️ NOTE: Uploading_Attack is not "
        "available in the timestamp-preserving "
        "coverage repository."
    )

    print(
        "The experiment will therefore be reported "
        "as a 32-attack coverage subset."
    )


# ================================================================
# 6.5 CREATE ATTACK-CLASS MAPPING TABLE
# ================================================================

print("\n[4] Creating attack-family mapping table")
print("-" * 72)


attack_family_mapping = (

    source_class_distribution[
        [
            "source_attack_class",
            "count",
            "percentage"
        ]
    ]
    .copy()
)


attack_family_mapping[
    "research_family"
] = (

    attack_family_mapping[
        "source_attack_class"
    ]
    .map(
        SOURCE_CLASS_TO_FAMILY
    )
)


attack_family_mapping[
    "binary_target"
] = (

    attack_family_mapping[
        "research_family"
    ]
    .apply(
        lambda family:
            0
            if family == "Benign"
            else 1
    )
)


attack_family_mapping[
    "target_name"
] = (

    attack_family_mapping[
        "binary_target"
    ]
    .map({
        0: "Benign",
        1: "Attack"
    })
)


# ------------------------------------------------
# Sort into logical research order
# ------------------------------------------------

family_order = {

    family: number

    for number, family in enumerate(
        ALL_RESEARCH_CLASSES
    )
}


attack_family_mapping[
    "_family_order"
] = (

    attack_family_mapping[
        "research_family"
    ]
    .map(
        family_order
    )
)


attack_family_mapping = (

    attack_family_mapping

    .sort_values(
        [
            "_family_order",
            "source_attack_class"
        ]
    )

    .drop(
        columns=[
            "_family_order"
        ]
    )

    .reset_index(
        drop=True
    )
)


display(
    attack_family_mapping
)


# ================================================================
# 6.6 SAVE ATTACK-FAMILY MAPPING
# ================================================================

ATTACK_FAMILY_MAPPING_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_attack_family_mapping.csv"
)


attack_family_mapping.to_csv(

    ATTACK_FAMILY_MAPPING_PATH,

    index=False
)


print(
    "\n✅ Mapping saved:"
)

print(
    ATTACK_FAMILY_MAPPING_PATH
)


# ================================================================
# 6.7 CREATE FAMILY DISTRIBUTION
# ================================================================

print("\n[5] Research-family distribution")
print("-" * 72)


family_distribution = (

    attack_family_mapping

    .groupby(
        "research_family",
        as_index=False
    )

    .agg(

        records=(
            "count",
            "sum"
        ),

        source_classes=(
            "source_attack_class",
            "nunique"
        )
    )
)


family_distribution[
    "percentage"
] = (

    family_distribution[
        "records"
    ]

    /

    family_distribution[
        "records"
    ].sum()

    * 100
)


family_distribution[
    "_family_order"
] = (

    family_distribution[
        "research_family"
    ]
    .map(
        family_order
    )
)


family_distribution = (

    family_distribution

    .sort_values(
        "_family_order"
    )

    .drop(
        columns=[
            "_family_order"
        ]
    )

    .reset_index(
        drop=True
    )
)


display(
    family_distribution
)


FAMILY_DISTRIBUTION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_family_distribution.csv"
)


family_distribution.to_csv(

    FAMILY_DISTRIBUTION_PATH,

    index=False
)


print(
    "\n✅ Family distribution saved:"
)

print(
    FAMILY_DISTRIBUTION_PATH
)


# ================================================================
# 6.8 CREATE FILE-LEVEL RESEARCH METADATA
# ================================================================

print("\n[6] Creating file-level research metadata")
print("-" * 72)


file_research_metadata = (

    dataset_manifest[
        [
            "attack_class_directory",
            "source_file",
            "local_path",
            "size_mb"
        ]
    ]
    .copy()
)


file_research_metadata = (

    file_research_metadata

    .rename(
        columns={
            "attack_class_directory":
                "source_attack_class"
        }
    )
)


file_research_metadata[
    "research_family"
] = (

    file_research_metadata[
        "source_attack_class"
    ]
    .map(
        SOURCE_CLASS_TO_FAMILY
    )
)


file_research_metadata[
    "binary_target"
] = (

    file_research_metadata[
        "research_family"
    ]
    .apply(
        lambda family:
            0
            if family == "Benign"
            else 1
    )
)


file_research_metadata[
    "target_name"
] = (

    file_research_metadata[
        "binary_target"
    ]
    .map({
        0: "Benign",
        1: "Attack"
    })
)


FILE_RESEARCH_METADATA_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_file_research_metadata.csv"
)


file_research_metadata.to_csv(

    FILE_RESEARCH_METADATA_PATH,

    index=False
)


display(
    file_research_metadata
)


# ================================================================
# 6.9 CREATE FAST LOOKUP DICTIONARIES
# ================================================================

FILE_TO_SOURCE_CLASS = {}

FILE_TO_RESEARCH_FAMILY = {}

FILE_TO_BINARY_TARGET = {}


for _, row in (
    file_research_metadata.iterrows()
):

    resolved_path = str(
        Path(
            row[
                "local_path"
            ]
        ).resolve()
    )


    FILE_TO_SOURCE_CLASS[
        resolved_path
    ] = row[
        "source_attack_class"
    ]


    FILE_TO_RESEARCH_FAMILY[
        resolved_path
    ] = row[
        "research_family"
    ]


    FILE_TO_BINARY_TARGET[
        resolved_path
    ] = int(
        row[
            "binary_target"
        ]
    )


print(
    "\nLookup dictionaries created for:",
    len(
        FILE_TO_RESEARCH_FAMILY
    ),
    "files"
)


# ================================================================
# 6.10 VERIFY FAMILY COVERAGE
# ================================================================

print("\n[7] LOAFO family coverage validation")
print("-" * 72)


observed_families = set(

    family_distribution[
        "research_family"
    ]
)


missing_research_families = [

    family

    for family in RESEARCH_ATTACK_FAMILIES

    if family
    not in observed_families
]


for family in RESEARCH_ATTACK_FAMILIES:

    family_row = (

        family_distribution[
            family_distribution[
                "research_family"
            ]
            ==
            family
        ]
    )


    if len(
        family_row
    ) == 1:

        records = int(
            family_row.iloc[0][
                "records"
            ]
        )

        source_classes = int(
            family_row.iloc[0][
                "source_classes"
            ]
        )


        print(
            f"✅ {family:<12} "
            f"{records:>12,} records | "
            f"{source_classes} source class(es)"
        )

    else:

        print(
            f"❌ {family:<12} missing"
        )


# ================================================================
# 6.11 VERIFY BENIGN TRAFFIC
# ================================================================

print("\n[8] Benign coverage")
print("-" * 72)


benign_rows = (

    family_distribution[
        family_distribution[
            "research_family"
        ]
        ==
        "Benign"
    ]
)


if len(
    benign_rows
) != 1:

    raise RuntimeError(
        "Benign traffic could not be "
        "identified correctly."
    )


BENIGN_RECORDS = int(

    benign_rows.iloc[0][
        "records"
    ]
)


print(
    "✅ Benign records:",
    f"{BENIGN_RECORDS:,}"
)


# ================================================================
# 6.12 VERIFY ROW TOTALS
# ================================================================

print("\n[9] Row-count conservation")
print("-" * 72)


MAPPED_TOTAL_ROWS = int(

    family_distribution[
        "records"
    ].sum()
)


print(
    "Step 5 total rows :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Mapped total rows :",
    f"{MAPPED_TOTAL_ROWS:,}"
)


ROW_TOTAL_MATCH = (

    MAPPED_TOTAL_ROWS
    ==
    TOTAL_ROWS
)


print(
    "Row totals match  :",
    ROW_TOTAL_MATCH
)


# ================================================================
# 6.13 BINARY-TARGET NOTE
# ================================================================

print("\n[10] Binary-target policy")
print("-" * 72)


print(
    "Original source Label column:"
)

print(
    "  Preserved unchanged."
)

print(
    "\nResearch BinaryTarget:"
)

print(
    "  Benign → 0"
)

print(
    "  Attack → 1"
)

print(
    "\nBinaryTarget is derived from the "
    "verified source attack-class directory."
)

print(
    "It does NOT overwrite the source Label column."
)


# ================================================================
# 6.14 FINAL VALIDATION
# ================================================================

section_6_valid = (

    len(
        observed_source_classes
    ) == 33

    and

    len(
        unmapped_classes
    ) == 0

    and

    len(
        missing_research_families
    ) == 0

    and

    len(
        RESEARCH_ATTACK_FAMILIES
    ) == 7

    and

    "Benign"
    in observed_families

    and

    ROW_TOTAL_MATCH

    and

    ATTACK_FAMILY_MAPPING_PATH.exists()

    and

    FAMILY_DISTRIBUTION_PATH.exists()

    and

    FILE_RESEARCH_METADATA_PATH.exists()
)


print("\n" + "=" * 72)


if section_6_valid:

    print(
        "✅ SECTION 6 PASSED — "
        "Seven-family research mapping is valid."
    )

else:

    print(
        "❌ SECTION 6 FAILED — "
        "Attack-family mapping requires review."
    )


print("=" * 72)

========================================================================
SECTION 6 — SEVEN-FAMILY ATTACK MAPPING
========================================================================

[1] Research families
------------------------------------------------------------------------
1. DDoS
2. DoS
3. Mirai
4. Recon
5. Spoofing
6. Web
7. BruteForce

Benign is maintained separately.

[2] Verifying source attack classes
------------------------------------------------------------------------
Observed source classes : 33
Mapping entries         : 33
Unmapped source classes : []
✅ Every observed source class is mapped.

[3] Benchmark-coverage note
------------------------------------------------------------------------
Available Web attacks: ['Backdoor_Malware', 'BrowserHijacking', 'CommandInjection', 'SqlInjection', 'XSS']
Unavailable original benchmark attacks: ['Uploading_Attack']

⚠️ NOTE: Uploading_Attack is not available in the timestamp-preserving coverage repository.
The experiment will therefore be reported as a 32-attack coverage subset.

[4] Creating attack-family mapping table
------------------------------------------------------------------------

,source_attack_class,count,percentage,research_family,binary_target,target_name
0,DDoS-ACK_Fragmentation,37296,0.093587,DDoS,1,Attack
1,DDoS-HTTP_Flood,513672,1.288961,DDoS,1,Attack
2,DDoS-ICMP_Flood,7834,0.019658,DDoS,1,Attack
3,DDoS-ICMP_Fragmentation,25106,0.062999,DDoS,1,Attack
4,DDoS-PSHACK_Flood,5007067,12.564275,DDoS,1,Attack
5,DDoS-RSTFINFlood,12968618,32.542261,DDoS,1,Attack
6,DDoS-SYN_Flood,6366353,15.975143,DDoS,1,Attack
7,DDoS-SlowLoris,196578,0.493275,DDoS,1,Attack
8,DDoS-SynonymousIP_Flood,799351,2.005818,DDoS,1,Attack
9,DDoS-TCP_Flood,4945887,12.410756,DDoS,1,Attack
10,DDoS-UDP_Flood,41146,0.103248,DDoS,1,Attack
11,DDoS-UDP_Fragmentation,9757,0.024483,DDoS,1,Attack
12,DoS-HTTP_Flood,965554,2.422873,DoS,1,Attack
13,DoS-SYN_Flood,3997110,10.029981,DoS,1,Attack
14,DoS-TCP_Flood,1638068,4.110418,DoS,1,Attack
15,DoS-UDP_Flood,934009,2.343717,DoS,1,Attack
16,Mirai-greeth_flood,5155,0.012935,Mirai,1,Attack
17,Mirai-greip_flood,10401,0.026099,Mirai,1,Attack
18,Mirai-udpplain,7455,0.018707,Mirai,1,Attack
19,Recon-HostDiscovery,329985,0.828034,Recon,1,Attack
20,Recon-OSScan,158682,0.398182,Recon,1,Attack
21,Recon-PingSweep,1947,0.004886,Recon,1,Attack
22,Recon-PortScan,175050,0.439254,Recon,1,Attack
23,VulnerabilityScan,442122,1.109420,Recon,1,Attack
24,DNS_Spoofing,74938,0.188043,Spoofing,1,Attack
25,MITM-ArpSpoofing,72853,0.182811,Spoofing,1,Attack
26,Backdoor_Malware,2703,0.006783,Web,1,Attack
27,BrowserHijacking,3286,0.008246,Web,1,Attack
28,CommandInjection,3848,0.009656,Web,1,Attack
29,SqlInjection,6596,0.016551,Web,1,Attack
30,XSS,3198,0.008025,Web,1,Attack
31,DictionaryBruteForce,8488,0.021299,BruteForce,1,Attack
32,Benign_Final,91506,0.229617,Benign,0,Benign

✅ Mapping saved:
/content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_attack_family_mapping.csv

[5] Research-family distribution
------------------------------------------------------------------------

  research_family   records  source_classes  percentage
0            DDoS  30918665              12   77.584464
1             DoS   7534741               4   18.906988
2           Mirai     23011               3    0.057742
3           Recon   1107786               5    2.779777
4        Spoofing    147791               2    0.370853
5             Web     19631               5    0.049260
6      BruteForce      8488               1    0.021299
7          Benign     91506               1    0.229617

✅ Family distribution saved:
/content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_family_distribution.csv

[6] Creating file-level research metadata
------------------------------------------------------------------------

,source_attack_class,source_file,local_path,size_mb,research_family,binary_target,target_name
0,Backdoor_Malware,CSVS/Backdoor_Malware/Backdoor_Malware_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1.518,Web,1,Attack
1,Benign_Final,CSVS/Benign_Final/Benign_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,49.145,Benign,0,Benign
2,BrowserHijacking,CSVS/BrowserHijacking/BrowserHijacking_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1.824,Web,1,Attack
3,CommandInjection,CSVS/CommandInjection/CommandInjection_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,2.089,Web,1,Attack
4,DDoS-ACK_Fragmentation,CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fragmenta...,/content/ZeroDay_IoT_Research/dataset/timestam...,19.536,DDoS,1,Attack
5,DDoS-HTTP_Flood,CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,254.233,DDoS,1,Attack
6,DDoS-ICMP_Flood,CSVS/DDoS-ICMP_Flood/DDoS-ICMP_Flood_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,4.171,DDoS,1,Attack
7,DDoS-ICMP_Fragmentation,CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_Fragmen...,/content/ZeroDay_IoT_Research/dataset/timestam...,13.576,DDoS,1,Attack
8,DDoS-PSHACK_Flood,CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood_1.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,2570.856,DDoS,1,Attack
9,DDoS-RSTFINFlood,CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.pcap_Fl...,/content/ZeroDay_IoT_Research/dataset/timestam...,5690.623,DDoS,1,Attack
10,DDoS-SYN_Flood,CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,3118.254,DDoS,1,Attack
11,DDoS-SlowLoris,CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,108.606,DDoS,1,Attack
12,DDoS-SynonymousIP_Flood,CSVS/DDoS-SynonymousIP_Flood/DDoS-SynonymousIP...,/content/ZeroDay_IoT_Research/dataset/timestam...,424.050,DDoS,1,Attack
13,DDoS-TCP_Flood,CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,2432.449,DDoS,1,Attack
14,DDoS-UDP_Flood,CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,19.632,DDoS,1,Attack
15,DDoS-UDP_Fragmentation,CSVS/DDoS-UDP_Fragmentation/DDoS-UDP_Fragmenta...,/content/ZeroDay_IoT_Research/dataset/timestam...,5.058,DDoS,1,Attack
16,DNS_Spoofing,CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,38.674,Spoofing,1,Attack
17,DictionaryBruteForce,CSVS/DictionaryBruteForce/DictionaryBruteForce...,/content/ZeroDay_IoT_Research/dataset/timestam...,4.474,BruteForce,1,Attack
18,DoS-HTTP_Flood,CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,397.445,DoS,1,Attack
19,DoS-SYN_Flood,CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1967.714,DoS,1,Attack
20,DoS-TCP_Flood,CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,792.980,DoS,1,Attack
21,DoS-UDP_Flood,CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,498.245,DoS,1,Attack
22,MITM-ArpSpoofing,CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.pcap_Fl...,/content/ZeroDay_IoT_Research/dataset/timestam...,36.446,Spoofing,1,Attack
23,Mirai-greeth_flood,CSVS/Mirai-greeth_flood/Mirai-greeth_flood.pca...,/content/ZeroDay_IoT_Research/dataset/timestam...,2.566,Mirai,1,Attack
24,Mirai-greip_flood,CSVS/Mirai-greip_flood/Mirai-greip_flood.pcap_...,/content/ZeroDay_IoT_Research/dataset/timestam...,5.337,Mirai,1,Attack
25,Mirai-udpplain,CSVS/Mirai-udpplain/Mirai-udpplain.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,3.783,Mirai,1,Attack
26,Recon-HostDiscovery,CSVS/Recon-HostDiscovery/Recon-HostDiscovery.p...,/content/ZeroDay_IoT_Research/dataset/timestam...,134.262,Recon,1,Attack
27,Recon-OSScan,CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,68.765,Recon,1,Attack
28,Recon-PingSweep,CSVS/Recon-PingSweep/Recon-PingSweep.pcap_Flow...,/content/ZeroDay_IoT_Research/dataset/timestam...,0.973,Recon,1,Attack
29,Recon-PortScan,CSVS/Recon-PortScan/Recon-PortScan.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,73.923,Recon,1,Attack
30,SqlInjection,CSVS/SqlInjection/SqlInjection.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,3.329,Web,1,Attack
31,VulnerabilityScan,CSVS/VulnerabilityScan/VulnerabilityScan.pcap_...,/content/ZeroDay_IoT_Research/dataset/timestam...,215.637,Recon,1,Attack
32,XSS,CSVS/XSS/XSS.pcap_Flow.csv,/content/ZeroDay_IoT_Research/dataset/timestam...,1.672,Web,1,Attack

Lookup dictionaries created for: 33 files

[7] LOAFO family coverage validation
------------------------------------------------------------------------
✅ DDoS           30,918,665 records | 12 source class(es)
✅ DoS             7,534,741 records | 4 source class(es)
✅ Mirai              23,011 records | 3 source class(es)
✅ Recon           1,107,786 records | 5 source class(es)
✅ Spoofing          147,791 records | 2 source class(es)
✅ Web                19,631 records | 5 source class(es)
✅ BruteForce          8,488 records | 1 source class(es)

[8] Benign coverage
------------------------------------------------------------------------
✅ Benign records: 91,506

[9] Row-count conservation
------------------------------------------------------------------------
Step 5 total rows : 39,851,619
Mapped total rows : 39,851,619
Row totals match  : True

[10] Binary-target policy
------------------------------------------------------------------------
Original source Label column:
  Preserved unchanged.

Research BinaryTarget:
  Benign → 0
  Attack → 1

BinaryTarget is derived from the verified source attack-class directory.
It does NOT overwrite the source Label column.

========================================================================
✅ SECTION 6 PASSED — Seven-family research mapping is valid.
========================================================================

# STEP 7 — Feature Audit and Leakage-Safe Preprocessing Preparation

# STEP 7A — Add this Markdown / Text cell

# 7. Feature Audit and Leakage-Safe Preprocessing Preparation

## 7.1 Purpose

This section audits the common CICIoT2023 feature columns before constructing the Leave-One-Attack-Family-Out experiments.

The objectives are to identify:

- Numeric feature candidates
- Non-numeric or identifier-like columns
- Missing feature values
- Positive and negative infinity values
- Unexpected non-numeric values inside numeric columns
- Features that require later preprocessing

No model is trained in this section.

---

## 7.2 Current Feature Structure

The dataset integrity audit identified:

- 84 columns common to every selected CSV file
- `Timestamp`
- `Label`
- 82 initial structural feature candidates

The timestamp and original source label are not used as neural-network input features.

Therefore:

`84 common columns - Timestamp - Label = 82 structural candidates`

However, some of these columns may represent identifiers or non-numeric information.

This section determines which columns are suitable numeric candidates.

---

## 7.3 Why Final Feature Selection Is Not Performed Here

The research follows a strict zero-day evaluation protocol.

During a Leave-One-Attack-Family-Out fold, the held-out attack family must not influence:

- Missing-value imputation
- Infinite-value handling
- Zero-variance detection
- Feature selection
- Standardization
- Hyperparameter selection
- Threshold selection

Therefore, this section performs a descriptive dataset audit only.

Final preprocessing decisions will be fitted independently inside every LOAFO fold using development data only.

---

## 7.4 Numeric Feature Identification

A small sample from every source file will be inspected.

A structural feature will be considered a numeric candidate only when its observed non-missing sample values can be converted to numeric form.

Non-numeric columns will be documented separately.

They will not automatically be encoded or converted into model features.

---

## 7.5 Full Numeric Quality Audit

After numeric candidates are identified, the complete selected dataset will be scanned in memory-safe chunks.

For every numeric candidate, the notebook will count:

- Missing values
- Unexpected conversion failures
- Positive infinity values
- Negative infinity values

The audit statistics are descriptive only.

They will not be used to calculate global imputation or scaling parameters.

---

## 7.6 Leakage-Safe Preprocessing Policy

Later, inside each LOAFO fold:

1. One complete attack family will be held out.
2. Preprocessing statistics will be fitted only on development/training data.
3. Missing values will be handled using training-derived statistics.
4. Infinite values will be handled using training-derived statistics.
5. Zero-variance features will be detected using training data only.
6. Standardization parameters will be learned from training data only.
7. The exact fitted transformation will then be applied unchanged to validation and zero-day test data.

This prevents information from the unseen attack family from influencing model development.

---

## 7.7 Timestamp Policy

`Timestamp` is excluded from the model feature matrix.

It will be retained exclusively for chronological ordering and temporal-window construction.

---

## 7.8 Source Label Policy

The original source `Label` column is also excluded from the model feature matrix.

The supervised binary research target is the verified target constructed from source attack-class metadata:

- Benign → 0
- Attack → 1

The raw `Label` column will not be used as a predictor.

---

## 7.9 Audit Outputs

This section will generate:

`CICIoT2023_feature_structure_audit.csv`

`CICIoT2023_numeric_quality_audit.csv`

`CICIoT2023_non_numeric_features.csv`

`CICIoT2023_feature_policy.json`

These artifacts document how the feature space was inspected before leakage-safe preprocessing.

---

## 7.10 Expected Result

The section should identify:

- Structural feature candidates
- Numeric feature candidates
- Non-numeric feature candidates
- Missing-value counts
- Infinite-value counts
- Conversion failures

The section should finish with:

`✅ SECTION 7 PASSED — Feature audit completed and leakage-safe preprocessing policy is ready.`

# Complete Recovery + Step 7 Code

In [ ]:
# ======================================================================
# COMPLETE RUNTIME RECOVERY + STEP 7
# CICIoT2023 FEATURE AUDIT AND LEAKAGE-SAFE PREPROCESSING PREPARATION
# ======================================================================

import os
import sys
import json
import random
import shutil
import subprocess
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd

print("=" * 78)
print("COMPLETE RUNTIME RECOVERY + STEP 7")
print("=" * 78)


# ======================================================================
# PART A — RESTORE GLOBAL PROJECT CONFIGURATION
# ======================================================================

print("\n[A1] Restoring global project configuration")
print("-" * 78)


PROJECT_NAME = "ZeroDay_IoT_Final_Training"

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)


DIRECTORIES = {

    "dataset":
        PROJECT_ROOT / "dataset",

    "dataset_audit":
        PROJECT_ROOT / "dataset_audit",

    "processed_data":
        PROJECT_ROOT / "processed_data",

    "models":
        PROJECT_ROOT / "models",

    "checkpoints":
        PROJECT_ROOT / "checkpoints",

    "predictions":
        PROJECT_ROOT / "predictions",

    "metrics":
        PROJECT_ROOT / "metrics",

    "figures":
        PROJECT_ROOT / "figures",

    "logs":
        PROJECT_ROOT / "logs",

    "sensitivity":
        PROJECT_ROOT / "sensitivity",

    "ablation":
        PROJECT_ROOT / "ablation",

    "statistics":
        PROJECT_ROOT / "statistics",

    "final_exports":
        PROJECT_ROOT / "final_exports"
}


for directory in DIRECTORIES.values():

    directory.mkdir(
        parents=True,
        exist_ok=True
    )


ATTACK_FAMILIES = [

    "DDoS",
    "DoS",
    "Mirai",
    "Recon",
    "Spoofing",
    "Web",
    "BruteForce"
]


RANDOM_SEEDS = [
    13,
    29,
    47,
    71,
    101
]


PRIMARY_SEED = 13


TEMPORAL_WINDOW = 8

TEMPORAL_STRIDE = 8

SSL_TEMPERATURE = 0.2


LAMBDA_T_CANDIDATES = [
    0.1,
    0.25,
    0.5,
    1.0
]


SELECTED_LAMBDA_T = None


SSL_EPOCHS = 30

FINETUNE_EPOCHS = 20

BATCH_SIZE = 256


LEARNING_RATE_SSL = 1e-3

LEARNING_RATE_FINETUNE = 1e-3


WINDOW_SENSITIVITY_VALUES = [
    4,
    8,
    16
]


CLASS_IMBALANCE_METHODS = [
    "none",
    "class_weight",
    "weighted_sampler"
]


# ======================================================================
# PART B — REPRODUCIBILITY
# ======================================================================

print("\n[A2] Restoring reproducibility settings")
print("-" * 78)


def set_global_seed(seed):

    os.environ[
        "PYTHONHASHSEED"
    ] = str(seed)

    random.seed(
        seed
    )

    np.random.seed(
        seed
    )

    try:

        import torch

        torch.manual_seed(
            seed
        )

        if torch.cuda.is_available():

            torch.cuda.manual_seed(
                seed
            )

            torch.cuda.manual_seed_all(
                seed
            )


        torch.backends.cudnn.deterministic = True

        torch.backends.cudnn.benchmark = False

    except ImportError:

        pass


set_global_seed(
    PRIMARY_SEED
)


print(
    "Primary seed:",
    PRIMARY_SEED
)

print(
    "✅ Reproducibility settings restored."
)


# ======================================================================
# PART C — EXACT DATASET SOURCE
# ======================================================================

print("\n[A3] Restoring exact dataset specification")
print("-" * 78)


HF_DATASET_REPO = (
    "somnath0100/CICIoT2023Small"
)


DATASET_ROOT = (

    DIRECTORIES["dataset"]

    / "timestamp_coverage"
)


DATASET_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


# ----------------------------------------------------------------------
# Exact files selected in the verified Step 4 experiment.
# This prevents a future repository change from silently selecting
# different captures.
# ----------------------------------------------------------------------

SELECTED_REMOTE_FILES = [

    "CSVS/Backdoor_Malware/Backdoor_Malware_1.csv",

    "CSVS/Benign_Final/Benign_1.csv",

    "CSVS/BrowserHijacking/BrowserHijacking_1.csv",

    "CSVS/CommandInjection/CommandInjection_1.csv",

    "CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fragmentation_1.csv",

    "CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.csv",

    "CSVS/DDoS-ICMP_Flood/DDoS-ICMP_Flood_1.csv",

    "CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_Fragmentation_1.csv",

    "CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood_1.csv",

    "CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.pcap_Flow.csv",

    "CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_Flow.csv",

    "CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_Flow.csv",

    "CSVS/DDoS-SynonymousIP_Flood/DDoS-SynonymousIP_Flood.pcap_Flow.csv",

    "CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_Flow.csv",

    "CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_Flow.csv",

    "CSVS/DDoS-UDP_Fragmentation/DDoS-UDP_Fragmentation.pcap_Flow.csv",

    "CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow.csv",

    "CSVS/DictionaryBruteForce/DictionaryBruteForce.pcap_Flow.csv",

    "CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_Flow.csv",

    "CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Flow.csv",

    "CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Flow.csv",

    "CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Flow.csv",

    "CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.pcap_Flow.csv",

    "CSVS/Mirai-greeth_flood/Mirai-greeth_flood.pcap_Flow.csv",

    "CSVS/Mirai-greip_flood/Mirai-greip_flood.pcap_Flow.csv",

    "CSVS/Mirai-udpplain/Mirai-udpplain.pcap_Flow.csv",

    "CSVS/Recon-HostDiscovery/Recon-HostDiscovery.pcap_Flow.csv",

    "CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow.csv",

    "CSVS/Recon-PingSweep/Recon-PingSweep.pcap_Flow.csv",

    "CSVS/Recon-PortScan/Recon-PortScan.pcap_Flow.csv",

    "CSVS/SqlInjection/SqlInjection.pcap_Flow.csv",

    "CSVS/VulnerabilityScan/VulnerabilityScan.pcap_Flow.csv",

    "CSVS/XSS/XSS.pcap_Flow.csv"
]


print(
    "Expected dataset files:",
    len(SELECTED_REMOTE_FILES)
)


# ======================================================================
# PART D — CHECK WHETHER DATASET SURVIVED THE RUNTIME RESET
# ======================================================================

print("\n[A4] Checking local dataset files")
print("-" * 78)


def get_local_path(remote_file):

    return (
        DATASET_ROOT
        /
        remote_file
    )


existing_remote_files = []

missing_remote_files = []


for remote_file in SELECTED_REMOTE_FILES:

    local_path = get_local_path(
        remote_file
    )

    if (
        local_path.exists()
        and
        local_path.stat().st_size > 0
    ):

        existing_remote_files.append(
            remote_file
        )

    else:

        missing_remote_files.append(
            remote_file
        )


print(
    "Files already available:",
    len(existing_remote_files)
)

print(
    "Files missing          :",
    len(missing_remote_files)
)


# ======================================================================
# PART E — DOWNLOAD ONLY MISSING FILES
# ======================================================================

if missing_remote_files:

    print("\n[A5] Some dataset files are missing")
    print("-" * 78)

    print(
        "Colab probably cleared part or all "
        "of /content."
    )

    print(
        "\nOnly missing files will be downloaded."
    )


    # ------------------------------------------------------------------
    # Check free disk space
    # ------------------------------------------------------------------

    disk_usage = shutil.disk_usage(
        "/content"
    )

    free_gb = (
        disk_usage.free
        /
        (1024 ** 3)
    )


    print(
        "Free Colab disk space:",
        f"{free_gb:.2f} GB"
    )


    if free_gb < 22:

        raise RuntimeError(

            "Not enough free disk space for safe dataset recovery.\n"

            "At least about 22 GB of free space is recommended."
        )


    # ------------------------------------------------------------------
    # Install/import huggingface_hub
    # ------------------------------------------------------------------

    try:

        import huggingface_hub

    except ImportError:

        print(
            "\nInstalling huggingface_hub..."
        )

        subprocess.check_call([

            sys.executable,

            "-m",

            "pip",

            "install",

            "-q",

            "huggingface_hub"
        ])


    from huggingface_hub import (
        hf_hub_download
    )


    # ------------------------------------------------------------------
    # Download exact missing files
    # ------------------------------------------------------------------

    for number, remote_file in enumerate(
        missing_remote_files,
        start=1
    ):

        print(
            "\nDownloading "
            f"{number}/{len(missing_remote_files)}"
        )

        print(
            remote_file
        )


        hf_hub_download(

            repo_id=HF_DATASET_REPO,

            repo_type="dataset",

            filename=remote_file,

            local_dir=str(
                DATASET_ROOT
            )
        )


    print(
        "\n✅ Missing dataset files downloaded."
    )

else:

    print(
        "\n✅ All 33 dataset files survived "
        "the runtime reset."
    )


# ======================================================================
# PART F — FINAL DATASET FILE VALIDATION
# ======================================================================

print("\n[A6] Final dataset-file validation")
print("-" * 78)


DATA_FILES = [

    get_local_path(
        remote_file
    )

    for remote_file
    in SELECTED_REMOTE_FILES
]


still_missing = [

    str(file_path)

    for file_path
    in DATA_FILES

    if (
        not file_path.exists()
        or
        file_path.stat().st_size == 0
    )
]


if still_missing:

    raise RuntimeError(

        "Dataset recovery is incomplete.\n\nMissing files:\n"

        +

        "\n".join(
            still_missing
        )
    )


print(
    "Validated dataset files:",
    len(DATA_FILES)
)


total_dataset_size_gb = sum(

    file_path.stat().st_size

    for file_path
    in DATA_FILES

) / (1024 ** 3)


print(
    "Current dataset size:",
    f"{total_dataset_size_gb:.2f} GB"
)


# ======================================================================
# PART G — REBUILD DATASET MANIFEST
# ======================================================================

print("\n[A7] Rebuilding dataset manifest")
print("-" * 78)


manifest_records = []


for remote_file, local_path in zip(
    SELECTED_REMOTE_FILES,
    DATA_FILES
):

    source_class = (
        Path(remote_file).parts[1]
    )


    manifest_records.append({

        "attack_class_directory":
            source_class,

        "source_file":
            remote_file,

        "local_path":
            str(
                local_path
            ),

        "size_mb":
            round(
                local_path.stat().st_size
                /
                (1024 ** 2),
                3
            )
    })


dataset_manifest = pd.DataFrame(
    manifest_records
)


MANIFEST_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_selected_files.csv"
)


dataset_manifest.to_csv(
    MANIFEST_PATH,
    index=False
)


print(
    "Manifest rows:",
    len(dataset_manifest)
)

print(
    "✅ Dataset manifest rebuilt."
)


# ======================================================================
# PART H — RESTORE VERIFIED 7-FAMILY MAPPING
# ======================================================================

print("\n[A8] Restoring verified seven-family mapping")
print("-" * 78)


SOURCE_CLASS_TO_FAMILY = {

    # ==============================================================
    # DDoS
    # ==============================================================

    "DDoS-ACK_Fragmentation":
        "DDoS",

    "DDoS-HTTP_Flood":
        "DDoS",

    "DDoS-ICMP_Flood":
        "DDoS",

    "DDoS-ICMP_Fragmentation":
        "DDoS",

    "DDoS-PSHACK_Flood":
        "DDoS",

    "DDoS-RSTFINFlood":
        "DDoS",

    "DDoS-SYN_Flood":
        "DDoS",

    "DDoS-SlowLoris":
        "DDoS",

    "DDoS-SynonymousIP_Flood":
        "DDoS",

    "DDoS-TCP_Flood":
        "DDoS",

    "DDoS-UDP_Flood":
        "DDoS",

    "DDoS-UDP_Fragmentation":
        "DDoS",


    # ==============================================================
    # DoS
    # ==============================================================

    "DoS-HTTP_Flood":
        "DoS",

    "DoS-SYN_Flood":
        "DoS",

    "DoS-TCP_Flood":
        "DoS",

    "DoS-UDP_Flood":
        "DoS",


    # ==============================================================
    # Mirai
    # ==============================================================

    "Mirai-greeth_flood":
        "Mirai",

    "Mirai-greip_flood":
        "Mirai",

    "Mirai-udpplain":
        "Mirai",


    # ==============================================================
    # Recon
    # ==============================================================

    "Recon-HostDiscovery":
        "Recon",

    "Recon-OSScan":
        "Recon",

    "Recon-PingSweep":
        "Recon",

    "Recon-PortScan":
        "Recon",

    "VulnerabilityScan":
        "Recon",


    # ==============================================================
    # Spoofing
    # ==============================================================

    "DNS_Spoofing":
        "Spoofing",

    "MITM-ArpSpoofing":
        "Spoofing",


    # ==============================================================
    # Web
    # ==============================================================

    "Backdoor_Malware":
        "Web",

    "BrowserHijacking":
        "Web",

    "CommandInjection":
        "Web",

    "SqlInjection":
        "Web",

    "XSS":
        "Web",


    # ==============================================================
    # Brute Force
    # ==============================================================

    "DictionaryBruteForce":
        "BruteForce",


    # ==============================================================
    # Benign
    # ==============================================================

    "Benign_Final":
        "Benign"
}


observed_source_classes = set(

    dataset_manifest[
        "attack_class_directory"
    ]
)


unmapped_source_classes = sorted(

    observed_source_classes

    -

    set(
        SOURCE_CLASS_TO_FAMILY.keys()
    )
)


if unmapped_source_classes:

    raise RuntimeError(

        "Unmapped source classes found:\n"

        +

        "\n".join(
            unmapped_source_classes
        )
    )


print(
    "Observed source classes:",
    len(observed_source_classes)
)

print(
    "Unmapped source classes:",
    len(unmapped_source_classes)
)

print(
    "✅ Seven-family mapping restored."
)


# ======================================================================
# PART I — REBUILD FILE LOOKUP DICTIONARIES
# ======================================================================

FILE_TO_SOURCE_CLASS = {}

FILE_TO_RESEARCH_FAMILY = {}

FILE_TO_BINARY_TARGET = {}


for _, row in dataset_manifest.iterrows():

    file_path = str(

        Path(
            row[
                "local_path"
            ]
        ).resolve()
    )


    source_class = row[
        "attack_class_directory"
    ]


    research_family = (
        SOURCE_CLASS_TO_FAMILY[
            source_class
        ]
    )


    binary_target = (

        0

        if research_family
        == "Benign"

        else 1
    )


    FILE_TO_SOURCE_CLASS[
        file_path
    ] = source_class


    FILE_TO_RESEARCH_FAMILY[
        file_path
    ] = research_family


    FILE_TO_BINARY_TARGET[
        file_path
    ] = binary_target


print(
    "\nLookup dictionaries restored:",
    len(FILE_TO_RESEARCH_FAMILY)
)


# ======================================================================
# PART J — COMMON SCHEMA RECOVERY
# ======================================================================

print("\n[A9] Rebuilding common dataset schema")
print("-" * 78)


TIMESTAMP_COLUMN = "Timestamp"

LABEL_COLUMN = "Label"


schema_records = []

column_sets = []

header_columns_by_file = {}


for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    header = pd.read_csv(
        file_path,
        nrows=0
    )


    columns = list(
        header.columns
    )


    header_columns_by_file[
        str(file_path)
    ] = columns


    column_sets.append(
        set(columns)
    )


    schema_records.append({

        "file_number":
            file_number,

        "file_name":
            file_path.name,

        "source_class":
            FILE_TO_SOURCE_CLASS[
                str(
                    file_path.resolve()
                )
            ],

        "column_count":
            len(columns),

        "timestamp_present":
            TIMESTAMP_COLUMN
            in columns,

        "label_present":
            LABEL_COLUMN
            in columns
    })


schema_audit = pd.DataFrame(
    schema_records
)


COMMON_COLUMNS = set.intersection(
    *column_sets
)


ALL_COLUMNS = set.union(
    *column_sets
)


first_header = list(

    pd.read_csv(
        DATA_FILES[0],
        nrows=0
    ).columns
)


COMMON_REFERENCE_ORDER = [

    column

    for column
    in first_header

    if column
    in COMMON_COLUMNS
]


MODEL_FEATURE_CANDIDATES = [

    column

    for column
    in COMMON_REFERENCE_ORDER

    if column
    not in {
        TIMESTAMP_COLUMN,
        LABEL_COLUMN
    }
]


SCHEMA_AUDIT_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_schema_audit.csv"
)


schema_audit.to_csv(
    SCHEMA_AUDIT_PATH,
    index=False
)


print(
    "Common columns          :",
    len(COMMON_REFERENCE_ORDER)
)

print(
    "Total distinct columns  :",
    len(ALL_COLUMNS)
)

print(
    "Structural candidates   :",
    len(MODEL_FEATURE_CANDIDATES)
)

print(
    "Timestamp common        :",
    TIMESTAMP_COLUMN
    in COMMON_COLUMNS
)

print(
    "Label common            :",
    LABEL_COLUMN
    in COMMON_COLUMNS
)


if (
    TIMESTAMP_COLUMN
    not in COMMON_COLUMNS

    or

    LABEL_COLUMN
    not in COMMON_COLUMNS
):

    raise RuntimeError(
        "Timestamp or Label is not available "
        "in every selected file."
    )


# ======================================================================
# STEP 7 STARTS HERE
# ======================================================================

print("\n" + "=" * 78)
print("SECTION 7 — FEATURE AUDIT")
print("=" * 78)


# ======================================================================
# 7.1 OUTPUT PATHS
# ======================================================================

FEATURE_STRUCTURE_AUDIT_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_feature_structure_audit.csv"
)


NUMERIC_QUALITY_AUDIT_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_numeric_quality_audit.csv"
)


NON_NUMERIC_FEATURES_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_non_numeric_features.csv"
)


FEATURE_POLICY_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_feature_policy.json"
)


SOURCE_CLASS_DISTRIBUTION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_source_class_distribution.csv"
)


FAMILY_DISTRIBUTION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_family_distribution.csv"
)


ATTACK_FAMILY_MAPPING_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_attack_family_mapping.csv"
)


FILE_RESEARCH_METADATA_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_file_research_metadata.csv"
)


# ======================================================================
# 7.2 VERIFY STRUCTURAL CANDIDATES
# ======================================================================

print("\n[1] Structural feature candidates")
print("-" * 78)


STRUCTURAL_FEATURE_CANDIDATES = list(
    MODEL_FEATURE_CANDIDATES
)


print(
    "Common columns              :",
    len(COMMON_REFERENCE_ORDER)
)

print(
    "Structural feature candidates:",
    len(STRUCTURAL_FEATURE_CANDIDATES)
)

print(
    "Timestamp used as feature   :",
    TIMESTAMP_COLUMN
    in STRUCTURAL_FEATURE_CANDIDATES
)

print(
    "Raw Label used as feature   :",
    LABEL_COLUMN
    in STRUCTURAL_FEATURE_CANDIDATES
)


# ======================================================================
# 7.3 SAMPLE-BASED TYPE AUDIT
# ======================================================================

print("\n[2] Identifying numeric/non-numeric features")
print("-" * 78)


SAMPLE_ROWS_PER_FILE = 5_000


sample_non_missing = Counter()

sample_missing = Counter()

sample_conversion_failures = Counter()


for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    print(
        f"Sampling "
        f"{file_number:02d}/{len(DATA_FILES)}: "
        f"{file_path.name}"
    )


    sample = pd.read_csv(

        file_path,

        usecols=STRUCTURAL_FEATURE_CANDIDATES,

        nrows=SAMPLE_ROWS_PER_FILE,

        low_memory=False
    )


    for column in STRUCTURAL_FEATURE_CANDIDATES:

        values = sample[
            column
        ]


        missing_mask = (
            values.isna()
        )


        non_missing_mask = (
            ~missing_mask
        )


        numeric_values = pd.to_numeric(

            values,

            errors="coerce"
        )


        conversion_failure_mask = (

            non_missing_mask

            &

            numeric_values.isna()
        )


        sample_missing[
            column
        ] += int(
            missing_mask.sum()
        )


        sample_non_missing[
            column
        ] += int(
            non_missing_mask.sum()
        )


        sample_conversion_failures[
            column
        ] += int(
            conversion_failure_mask.sum()
        )


# ======================================================================
# 7.4 CREATE FEATURE-STRUCTURE TABLE
# ======================================================================

structure_records = []


for column in STRUCTURAL_FEATURE_CANDIDATES:

    non_missing_count = int(
        sample_non_missing[
            column
        ]
    )


    conversion_failure_count = int(
        sample_conversion_failures[
            column
        ]
    )


    numeric_candidate = (

        non_missing_count > 0

        and

        conversion_failure_count == 0
    )


    structure_records.append({

        "feature":
            column,

        "sample_non_missing_values":
            non_missing_count,

        "sample_missing_values":
            int(
                sample_missing[
                    column
                ]
            ),

        "sample_conversion_failures":
            conversion_failure_count,

        "numeric_candidate":
            numeric_candidate
    })


feature_structure_audit = pd.DataFrame(
    structure_records
)


NUMERIC_FEATURE_CANDIDATES = (

    feature_structure_audit.loc[

        feature_structure_audit[
            "numeric_candidate"
        ],

        "feature"
    ]

    .tolist()
)


NON_NUMERIC_FEATURE_CANDIDATES = (

    feature_structure_audit.loc[

        ~feature_structure_audit[
            "numeric_candidate"
        ],

        "feature"
    ]

    .tolist()
)


feature_structure_audit.to_csv(

    FEATURE_STRUCTURE_AUDIT_PATH,

    index=False
)


print(
    "\nNumeric feature candidates    :",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "Non-numeric candidates       :",
    len(NON_NUMERIC_FEATURE_CANDIDATES)
)


if len(
    NUMERIC_FEATURE_CANDIDATES
) == 0:

    raise RuntimeError(
        "No numeric feature candidates were identified."
    )


# ======================================================================
# 7.5 SAVE/DISPLAY NON-NUMERIC FEATURES
# ======================================================================

print("\n[3] Non-numeric feature candidates")
print("-" * 78)


non_numeric_features = (

    feature_structure_audit.loc[

        ~feature_structure_audit[
            "numeric_candidate"
        ]

    ]

    .copy()

    .reset_index(
        drop=True
    )
)


non_numeric_features.to_csv(

    NON_NUMERIC_FEATURES_PATH,

    index=False
)


if non_numeric_features.empty:

    print(
        "No non-numeric structural features detected."
    )

else:

    display(
        non_numeric_features
    )


# ======================================================================
# 7.6 NUMERIC FEATURE LIST
# ======================================================================

print("\n[4] Numeric feature candidates")
print("-" * 78)


for number, feature in enumerate(
    NUMERIC_FEATURE_CANDIDATES,
    start=1
):

    print(
        f"{number:02d}. {feature}"
    )


# ======================================================================
# 7.7 FULL DATASET QUALITY AUDIT
# ======================================================================

print("\n[5] Full feature-quality audit")
print("-" * 78)

print(
    "All selected rows will now be scanned."
)

print(
    "The process is chunk-based to protect Colab RAM."
)

print(
    "Do not interrupt the runtime while this section is running."
)


AUDIT_CHUNK_SIZE = 100_000


global_missing_counts = Counter()

global_conversion_failure_counts = Counter()

global_positive_infinity_counts = Counter()

global_negative_infinity_counts = Counter()


raw_label_counter = Counter()

source_class_row_counts = Counter()


TOTAL_MISSING_TIMESTAMPS = 0

TOTAL_INVALID_TIMESTAMPS = 0

TOTAL_MISSING_RAW_LABELS = 0


ROWS_SCANNED_FOR_FEATURE_AUDIT = 0


# Previous verified count.
# Used only as a reproducibility check.
EXPECTED_TOTAL_ROWS = 39_851_619


AUDIT_COLUMNS = (

    [
        TIMESTAMP_COLUMN,
        LABEL_COLUMN
    ]

    +

    NUMERIC_FEATURE_CANDIDATES
)


for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    print("\n" + "-" * 78)

    print(
        f"Auditing "
        f"{file_number}/{len(DATA_FILES)}:"
    )

    print(
        file_path.name
    )


    resolved_path = str(
        file_path.resolve()
    )


    source_class = (
        FILE_TO_SOURCE_CLASS[
            resolved_path
        ]
    )


    file_rows = 0


    reader = pd.read_csv(

        file_path,

        usecols=AUDIT_COLUMNS,

        chunksize=AUDIT_CHUNK_SIZE,

        low_memory=False
    )


    for chunk in reader:

        rows = len(
            chunk
        )


        file_rows += rows


        ROWS_SCANNED_FOR_FEATURE_AUDIT += (
            rows
        )


        # ==========================================================
        # TIMESTAMP AUDIT
        # ==========================================================

        raw_timestamp = (
            chunk[
                TIMESTAMP_COLUMN
            ]
        )


        timestamp_text = (

            raw_timestamp

            .astype("string")

            .str.strip()
        )


        missing_timestamp_mask = (

            raw_timestamp.isna()

            |

            timestamp_text.eq("")
        )


        parsed_timestamp = pd.to_datetime(

            raw_timestamp,

            errors="coerce",

            utc=True,

            format="mixed"
        )


        invalid_timestamp_mask = (

            parsed_timestamp.isna()

            &

            ~missing_timestamp_mask
        )


        TOTAL_MISSING_TIMESTAMPS += int(
            missing_timestamp_mask.sum()
        )


        TOTAL_INVALID_TIMESTAMPS += int(
            invalid_timestamp_mask.sum()
        )


        # ==========================================================
        # RAW LABEL AUDIT
        # ==========================================================

        raw_label = (
            chunk[
                LABEL_COLUMN
            ]
        )


        missing_raw_label_mask = (
            raw_label.isna()
        )


        TOTAL_MISSING_RAW_LABELS += int(
            missing_raw_label_mask.sum()
        )


        raw_label_counter.update(

            raw_label[
                ~missing_raw_label_mask
            ]
            .astype(str)
            .tolist()
        )


        # ==========================================================
        # NUMERIC FEATURE AUDIT
        # ==========================================================

        feature_chunk = (

            chunk[
                NUMERIC_FEATURE_CANDIDATES
            ]
        )


        raw_missing_mask = (
            feature_chunk.isna()
        )


        missing_counts = (
            raw_missing_mask.sum()
        )


        for column, count in (
            missing_counts.items()
        ):

            global_missing_counts[
                column
            ] += int(count)


        converted = feature_chunk.apply(

            pd.to_numeric,

            errors="coerce"
        )


        conversion_failure_counts = (

            converted.isna()

            &

            ~raw_missing_mask

        ).sum()


        for column, count in (
            conversion_failure_counts.items()
        ):

            global_conversion_failure_counts[
                column
            ] += int(count)


        numeric_array = converted.to_numpy(

            dtype=np.float64,

            copy=False
        )


        positive_inf_counts = np.isposinf(
            numeric_array
        ).sum(
            axis=0
        )


        negative_inf_counts = np.isneginf(
            numeric_array
        ).sum(
            axis=0
        )


        for index, column in enumerate(
            NUMERIC_FEATURE_CANDIDATES
        ):

            global_positive_infinity_counts[
                column
            ] += int(
                positive_inf_counts[
                    index
                ]
            )


            global_negative_infinity_counts[
                column
            ] += int(
                negative_inf_counts[
                    index
                ]
            )


    source_class_row_counts[
        source_class
    ] += file_rows


    print(
        "Rows audited:",
        f"{file_rows:,}"
    )


# ======================================================================
# 7.8 RESTORE TOTAL ROW COUNT
# ======================================================================

TOTAL_ROWS = int(
    ROWS_SCANNED_FOR_FEATURE_AUDIT
)


print("\n[6] Complete row-count validation")
print("-" * 78)


print(
    "Expected verified rows:",
    f"{EXPECTED_TOTAL_ROWS:,}"
)

print(
    "Rows scanned          :",
    f"{TOTAL_ROWS:,}"
)


ROW_AUDIT_MATCH = (

    TOTAL_ROWS

    ==

    EXPECTED_TOTAL_ROWS
)


print(
    "Verified row count matches:",
    ROW_AUDIT_MATCH
)


# ======================================================================
# 7.9 NUMERIC QUALITY TABLE
# ======================================================================

quality_records = []


for feature in NUMERIC_FEATURE_CANDIDATES:

    missing_values = int(

        global_missing_counts[
            feature
        ]
    )


    conversion_failures = int(

        global_conversion_failure_counts[
            feature
        ]
    )


    positive_infinity = int(

        global_positive_infinity_counts[
            feature
        ]
    )


    negative_infinity = int(

        global_negative_infinity_counts[
            feature
        ]
    )


    total_infinity = (

        positive_infinity

        +

        negative_infinity
    )


    total_quality_issues = (

        missing_values

        +

        conversion_failures

        +

        total_infinity
    )


    quality_records.append({

        "feature":
            feature,

        "missing_values":
            missing_values,

        "missing_percentage":
            (
                missing_values
                /
                TOTAL_ROWS
                *
                100
            ),

        "conversion_failures":
            conversion_failures,

        "positive_infinity":
            positive_infinity,

        "negative_infinity":
            negative_infinity,

        "total_infinity":
            total_infinity,

        "total_quality_issues":
            total_quality_issues
    })


numeric_quality_audit = pd.DataFrame(
    quality_records
)


numeric_quality_audit = (

    numeric_quality_audit

    .sort_values(

        [
            "total_quality_issues",
            "feature"
        ],

        ascending=[
            False,
            True
        ]
    )

    .reset_index(
        drop=True
    )
)


numeric_quality_audit.to_csv(

    NUMERIC_QUALITY_AUDIT_PATH,

    index=False
)


# ======================================================================
# 7.10 FEATURES WITH DATA-QUALITY ISSUES
# ======================================================================

print("\n[7] Features with missing/infinite/conversion issues")
print("-" * 78)


features_with_issues = (

    numeric_quality_audit[

        numeric_quality_audit[
            "total_quality_issues"
        ] > 0

    ]
)


if features_with_issues.empty:

    print(
        "✅ No numeric feature-quality issues detected."
    )

else:

    display(
        features_with_issues
    )


# ======================================================================
# 7.11 FEATURE QUALITY SUMMARY
# ======================================================================

print("\n[8] Feature-quality summary")
print("-" * 78)


TOTAL_FEATURE_MISSING_VALUES = int(

    numeric_quality_audit[
        "missing_values"
    ].sum()
)


TOTAL_FEATURE_CONVERSION_FAILURES = int(

    numeric_quality_audit[
        "conversion_failures"
    ].sum()
)


TOTAL_FEATURE_POSITIVE_INFINITY = int(

    numeric_quality_audit[
        "positive_infinity"
    ].sum()
)


TOTAL_FEATURE_NEGATIVE_INFINITY = int(

    numeric_quality_audit[
        "negative_infinity"
    ].sum()
)


TOTAL_FEATURE_INFINITY = (

    TOTAL_FEATURE_POSITIVE_INFINITY

    +

    TOTAL_FEATURE_NEGATIVE_INFINITY
)


print(
    "Rows scanned              :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Structural candidates     :",
    len(
        STRUCTURAL_FEATURE_CANDIDATES
    )
)

print(
    "Numeric candidates        :",
    len(
        NUMERIC_FEATURE_CANDIDATES
    )
)

print(
    "Non-numeric candidates    :",
    len(
        NON_NUMERIC_FEATURE_CANDIDATES
    )
)

print(
    "Missing numeric values    :",
    f"{TOTAL_FEATURE_MISSING_VALUES:,}"
)

print(
    "Conversion failures       :",
    f"{TOTAL_FEATURE_CONVERSION_FAILURES:,}"
)

print(
    "Positive infinity values  :",
    f"{TOTAL_FEATURE_POSITIVE_INFINITY:,}"
)

print(
    "Negative infinity values  :",
    f"{TOTAL_FEATURE_NEGATIVE_INFINITY:,}"
)

print(
    "Total infinity values     :",
    f"{TOTAL_FEATURE_INFINITY:,}"
)

print(
    "Missing timestamps        :",
    f"{TOTAL_MISSING_TIMESTAMPS:,}"
)

print(
    "Invalid timestamps        :",
    f"{TOTAL_INVALID_TIMESTAMPS:,}"
)

print(
    "Missing raw labels        :",
    f"{TOTAL_MISSING_RAW_LABELS:,}"
)


# ======================================================================
# 7.12 REBUILD SOURCE-CLASS DISTRIBUTION
# ======================================================================

print("\n[9] Rebuilding source attack-class distribution")
print("-" * 78)


source_class_distribution = (

    pd.DataFrame(

        source_class_row_counts.items(),

        columns=[
            "source_attack_class",
            "count"
        ]
    )

    .sort_values(
        "count",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


source_class_distribution[
    "percentage"
] = (

    source_class_distribution[
        "count"
    ]

    /

    source_class_distribution[
        "count"
    ].sum()

    *

    100
)


source_class_distribution.to_csv(

    SOURCE_CLASS_DISTRIBUTION_PATH,

    index=False
)


display(
    source_class_distribution
)


# ======================================================================
# 7.13 REBUILD FAMILY MAPPING TABLE
# ======================================================================

attack_family_mapping = (

    source_class_distribution.copy()
)


attack_family_mapping[
    "research_family"
] = (

    attack_family_mapping[
        "source_attack_class"
    ]

    .map(
        SOURCE_CLASS_TO_FAMILY
    )
)


attack_family_mapping[
    "binary_target"
] = (

    attack_family_mapping[
        "research_family"
    ]

    .apply(

        lambda family:

            0

            if family == "Benign"

            else 1
    )
)


attack_family_mapping[
    "target_name"
] = (

    attack_family_mapping[
        "binary_target"
    ]

    .map({

        0:
            "Benign",

        1:
            "Attack"
    })
)


attack_family_mapping.to_csv(

    ATTACK_FAMILY_MAPPING_PATH,

    index=False
)


# ======================================================================
# 7.14 REBUILD FAMILY DISTRIBUTION
# ======================================================================

family_distribution = (

    attack_family_mapping

    .groupby(
        "research_family",
        as_index=False
    )

    .agg(

        records=(
            "count",
            "sum"
        ),

        source_classes=(
            "source_attack_class",
            "nunique"
        )
    )
)


family_distribution[
    "percentage"
] = (

    family_distribution[
        "records"
    ]

    /

    family_distribution[
        "records"
    ].sum()

    *

    100
)


family_order = {

    "DDoS":
        0,

    "DoS":
        1,

    "Mirai":
        2,

    "Recon":
        3,

    "Spoofing":
        4,

    "Web":
        5,

    "BruteForce":
        6,

    "Benign":
        7
}


family_distribution[
    "_order"
] = (

    family_distribution[
        "research_family"
    ]

    .map(
        family_order
    )
)


family_distribution = (

    family_distribution

    .sort_values(
        "_order"
    )

    .drop(
        columns=[
            "_order"
        ]
    )

    .reset_index(
        drop=True
    )
)


family_distribution.to_csv(

    FAMILY_DISTRIBUTION_PATH,

    index=False
)


print("\n[10] Research-family distribution")
print("-" * 78)


display(
    family_distribution
)


# ======================================================================
# 7.15 REBUILD FILE-LEVEL RESEARCH METADATA
# ======================================================================

file_research_metadata = (

    dataset_manifest[
        [
            "attack_class_directory",
            "source_file",
            "local_path",
            "size_mb"
        ]
    ]

    .copy()
)


file_research_metadata.rename(

    columns={

        "attack_class_directory":
            "source_attack_class"
    },

    inplace=True
)


file_research_metadata[
    "research_family"
] = (

    file_research_metadata[
        "source_attack_class"
    ]

    .map(
        SOURCE_CLASS_TO_FAMILY
    )
)


file_research_metadata[
    "binary_target"
] = (

    file_research_metadata[
        "research_family"
    ]

    .apply(

        lambda family:

            0

            if family == "Benign"

            else 1
    )
)


file_research_metadata[
    "target_name"
] = (

    file_research_metadata[
        "binary_target"
    ]

    .map({

        0:
            "Benign",

        1:
            "Attack"
    })
)


file_research_metadata.to_csv(

    FILE_RESEARCH_METADATA_PATH,

    index=False
)


# ======================================================================
# 7.16 SAVE FEATURE POLICY
# ======================================================================

print("\n[11] Saving leakage-safe preprocessing policy")
print("-" * 78)


feature_policy = {

    "dataset":
        "Timestamp-preserving CICIoT2023 coverage subset",

    "dataset_files":
        len(DATA_FILES),

    "verified_total_rows":
        TOTAL_ROWS,

    "timestamp_column":
        TIMESTAMP_COLUMN,

    "raw_label_column":
        LABEL_COLUMN,

    "timestamp_is_model_feature":
        False,

    "raw_label_is_model_feature":
        False,

    "structural_feature_candidates":
        STRUCTURAL_FEATURE_CANDIDATES,

    "numeric_feature_candidates":
        NUMERIC_FEATURE_CANDIDATES,

    "non_numeric_feature_candidates":
        NON_NUMERIC_FEATURE_CANDIDATES,

    "research_attack_families":
        ATTACK_FAMILIES,

    "research_binary_target":
        {
            "Benign": 0,
            "Attack": 1
        },

    "preprocessing_scope":
        "fit independently inside each LOAFO fold",

    "held_out_family_used_for_preprocessing_fit":
        False,

    "global_audit_statistics_used_for_model_fitting":
        False,

    "missing_value_policy":
        (
            "fit imputation/replacement statistics "
            "on development training data only"
        ),

    "infinity_policy":
        (
            "fit finite replacement/clipping statistics "
            "on development training data only"
        ),

    "zero_variance_policy":
        (
            "detect zero-variance features "
            "using development training data only"
        ),

    "standardization_policy":
        (
            "fit StandardScaler using "
            "development training data only"
        ),

    "timestamp_policy":
        (
            "Timestamp retained only for chronological ordering; "
            "never passed to the model"
        )
}


with open(

    FEATURE_POLICY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        feature_policy,

        file,

        indent=4
    )


print(
    "✅ Feature policy saved:"
)

print(
    FEATURE_POLICY_PATH
)


# ======================================================================
# 7.17 SAVE RECOVERED EXPERIMENT CONFIGURATION
# ======================================================================

EXPERIMENT_CONFIG_PATH = (

    PROJECT_ROOT

    / "experiment_config.json"
)


experiment_config = {

    "project_name":
        PROJECT_NAME,

    "attack_families":
        ATTACK_FAMILIES,

    "random_seeds":
        RANDOM_SEEDS,

    "primary_seed":
        PRIMARY_SEED,

    "temporal_window":
        TEMPORAL_WINDOW,

    "temporal_stride":
        TEMPORAL_STRIDE,

    "ssl_temperature":
        SSL_TEMPERATURE,

    "lambda_t_candidates":
        LAMBDA_T_CANDIDATES,

    "ssl_epochs":
        SSL_EPOCHS,

    "finetune_epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate_ssl":
        LEARNING_RATE_SSL,

    "learning_rate_finetune":
        LEARNING_RATE_FINETUNE,

    "window_sensitivity_values":
        WINDOW_SENSITIVITY_VALUES,

    "class_imbalance_methods":
        CLASS_IMBALANCE_METHODS,

    "dataset_repo":
        HF_DATASET_REPO,

    "dataset_files":
        len(DATA_FILES),

    "verified_total_rows":
        TOTAL_ROWS
}


with open(

    EXPERIMENT_CONFIG_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        experiment_config,

        file,

        indent=4
    )


# ======================================================================
# 7.18 FINAL LEAKAGE-SAFETY REMINDER
# ======================================================================

print("\n[12] Leakage-safety policy")
print("-" * 78)


print(
    "GLOBAL FEATURE AUDIT:"
)

print(
    "  Used only for structural/data-quality documentation."
)


print(
    "\nINSIDE EACH LOAFO FOLD:"
)

print(
    "  Imputation fitting       → development training only"
)

print(
    "  Infinity handling        → development training only"
)

print(
    "  Zero-variance removal    → development training only"
)

print(
    "  Feature selection        → development training only"
)

print(
    "  StandardScaler fitting   → development training only"
)

print(
    "  Threshold selection      → development validation only"
)

print(
    "  Held-out attack family   → NEVER used for fitting/tuning"
)


# ======================================================================
# 7.19 FINAL VALIDATION
# ======================================================================

print("\n[13] Final validation")
print("-" * 78)


required_output_files = [

    MANIFEST_PATH,

    SCHEMA_AUDIT_PATH,

    FEATURE_STRUCTURE_AUDIT_PATH,

    NUMERIC_QUALITY_AUDIT_PATH,

    NON_NUMERIC_FEATURES_PATH,

    FEATURE_POLICY_PATH,

    SOURCE_CLASS_DISTRIBUTION_PATH,

    FAMILY_DISTRIBUTION_PATH,

    ATTACK_FAMILY_MAPPING_PATH,

    FILE_RESEARCH_METADATA_PATH,

    EXPERIMENT_CONFIG_PATH
]


all_output_files_exist = all(

    file_path.exists()

    for file_path
    in required_output_files
)


all_required_families_present = all(

    family
    in set(
        family_distribution[
            "research_family"
        ]
    )

    for family
    in ATTACK_FAMILIES
)


section_7_valid = (

    len(DATA_FILES) == 33

    and

    len(observed_source_classes) == 33

    and

    TIMESTAMP_COLUMN in COMMON_COLUMNS

    and

    LABEL_COLUMN in COMMON_COLUMNS

    and

    len(
        STRUCTURAL_FEATURE_CANDIDATES
    ) > 0

    and

    len(
        NUMERIC_FEATURE_CANDIDATES
    ) > 0

    and

    TOTAL_FEATURE_CONVERSION_FAILURES == 0

    and

    TOTAL_MISSING_TIMESTAMPS == 0

    and

    TOTAL_INVALID_TIMESTAMPS == 0

    and

    TOTAL_MISSING_RAW_LABELS == 0

    and

    ROW_AUDIT_MATCH

    and

    all_required_families_present

    and

    "Benign"
    in set(
        family_distribution[
            "research_family"
        ]
    )

    and

    all_output_files_exist
)


print(
    "Dataset files                    :",
    len(DATA_FILES)
)

print(
    "Source classes                   :",
    len(observed_source_classes)
)

print(
    "Verified total rows              :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Common columns                   :",
    len(COMMON_REFERENCE_ORDER)
)

print(
    "Structural feature candidates    :",
    len(STRUCTURAL_FEATURE_CANDIDATES)
)

print(
    "Numeric feature candidates       :",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "Non-numeric feature candidates   :",
    len(NON_NUMERIC_FEATURE_CANDIDATES)
)

print(
    "Feature conversion failures      :",
    f"{TOTAL_FEATURE_CONVERSION_FAILURES:,}"
)

print(
    "Missing timestamps               :",
    f"{TOTAL_MISSING_TIMESTAMPS:,}"
)

print(
    "Invalid timestamps               :",
    f"{TOTAL_INVALID_TIMESTAMPS:,}"
)

print(
    "All seven LOAFO families present :",
    all_required_families_present
)

print(
    "All audit artifacts saved        :",
    all_output_files_exist
)


print("\n" + "=" * 78)


if section_7_valid:

    print(
        "✅ SECTION 7 PASSED — "
        "Runtime recovered, feature audit completed, "
        "and leakage-safe preprocessing policy is ready."
    )

else:

    print(
        "❌ SECTION 7 FAILED — "
        "Please send the final validation output "
        "before continuing."
    )


print("=" * 78)

==============================================================================
COMPLETE RUNTIME RECOVERY + STEP 7
==============================================================================

[A1] Restoring global project configuration
------------------------------------------------------------------------------

[A2] Restoring reproducibility settings
------------------------------------------------------------------------------
Primary seed: 13
✅ Reproducibility settings restored.

[A3] Restoring exact dataset specification
------------------------------------------------------------------------------
Expected dataset files: 33

[A4] Checking local dataset files
------------------------------------------------------------------------------
Files already available: 0
Files missing          : 33

[A5] Some dataset files are missing
------------------------------------------------------------------------------
Colab probably cleared part or all of /content.

Only missing files will be downloaded.
Free Colab disk space: 87.36 GB

Downloading 1/33
CSVS/Backdoor_Malware/Backdoor_Malware_1.csv

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Backdoor_Malware_1.csv:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

Downloading 2/33
CSVS/Benign_Final/Benign_1.csv

CSVS/Benign_Final/Benign_1.csv: reconstructing file:   0%|          |  0.00B / 51.5MB

CSVS/Benign_Final/Benign_1.csv: downloading bytes:           |  0.00B

Downloading 3/33
CSVS/BrowserHijacking/BrowserHijacking_1.csv

BrowserHijacking_1.csv:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

Downloading 4/33
CSVS/CommandInjection/CommandInjection_1.csv

CommandInjection_1.csv:   0%|          | 0.00/2.19M [00:00<?, ?B/s]

Downloading 5/33
CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fragmentation_1.csv

CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fra(…): reconstructing file:   0%|          |  0.00B / 20.5MB

CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fra(…): downloading bytes:           |  0.00B

Downloading 6/33
CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.csv

CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.c(…): reconstructing file:   0%|          |  0.00B /  267MB

CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.c(…): downloading bytes:           |  0.00B

Downloading 7/33
CSVS/DDoS-ICMP_Flood/DDoS-ICMP_Flood_1.csv

DDoS-ICMP_Flood_1.csv:   0%|          | 0.00/4.37M [00:00<?, ?B/s]

Downloading 8/33
CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_Fragmentation_1.csv

CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_F(…): reconstructing file:   0%|          |  0.00B / 14.2MB

CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_F(…): downloading bytes:           |  0.00B

Downloading 9/33
CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood_1.csv

CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood(…): reconstructing file:   0%|          |  0.00B / 2.70GB

CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood(…): downloading bytes:           |  0.00B

Downloading 10/33
CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.pcap_Flow.csv

CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.p(…): reconstructing file:   0%|          |  0.00B / 5.97GB

CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.p(…): downloading bytes:           |  0.00B

Downloading 11/33
CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_Flow.csv

CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 3.27GB

CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 12/33
CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_Flow.csv

CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_(…): reconstructing file:   0%|          |  0.00B /  114MB

CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_(…): downloading bytes:           |  0.00B

Downloading 13/33
CSVS/DDoS-SynonymousIP_Flood/DDoS-SynonymousIP_Flood.pcap_Flow.csv

CSVS/DDoS-SynonymousIP_Flood/DDoS-Synony(…): reconstructing file:   0%|          |  0.00B /  445MB

CSVS/DDoS-SynonymousIP_Flood/DDoS-Synony(…): downloading bytes:           |  0.00B

Downloading 14/33
CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_Flow.csv

CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 2.55GB

CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 15/33
CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_Flow.csv

CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 20.6MB

CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 16/33
CSVS/DDoS-UDP_Fragmentation/DDoS-UDP_Fragmentation.pcap_Flow.csv

DDoS-UDP_Fragmentation.pcap_Flow.csv:   0%|          | 0.00/5.30M [00:00<?, ?B/s]

Downloading 17/33
CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow.csv

CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow(…): reconstructing file:   0%|          |  0.00B / 40.6MB

CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow(…): downloading bytes:           |  0.00B

Downloading 18/33
CSVS/DictionaryBruteForce/DictionaryBruteForce.pcap_Flow.csv

DictionaryBruteForce.pcap_Flow.csv:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

Downloading 19/33
CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_Flow.csv

CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B /  417MB

CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_(…): downloading bytes:           |  0.00B

Downloading 20/33
CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Flow.csv

CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B / 2.06GB

CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

Downloading 21/33
CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Flow.csv

CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B /  832MB

CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

Downloading 22/33
CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Flow.csv

CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B /  522MB

CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

Downloading 23/33
CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.pcap_Flow.csv

CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.p(…): reconstructing file:   0%|          |  0.00B / 38.2MB

CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.p(…): downloading bytes:           |  0.00B

Downloading 24/33
CSVS/Mirai-greeth_flood/Mirai-greeth_flood.pcap_Flow.csv

Mirai-greeth_flood.pcap_Flow.csv:   0%|          | 0.00/2.69M [00:00<?, ?B/s]

Downloading 25/33
CSVS/Mirai-greip_flood/Mirai-greip_flood.pcap_Flow.csv

Mirai-greip_flood.pcap_Flow.csv:   0%|          | 0.00/5.60M [00:00<?, ?B/s]

Downloading 26/33
CSVS/Mirai-udpplain/Mirai-udpplain.pcap_Flow.csv

Mirai-udpplain.pcap_Flow.csv:   0%|          | 0.00/3.97M [00:00<?, ?B/s]

Downloading 27/33
CSVS/Recon-HostDiscovery/Recon-HostDiscovery.pcap_Flow.csv

CSVS/Recon-HostDiscovery/Recon-HostDisco(…): reconstructing file:   0%|          |  0.00B /  141MB

CSVS/Recon-HostDiscovery/Recon-HostDisco(…): downloading bytes:           |  0.00B

Downloading 28/33
CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow.csv

CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow(…): reconstructing file:   0%|          |  0.00B / 72.1MB

CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow(…): downloading bytes:           |  0.00B

Downloading 29/33
CSVS/Recon-PingSweep/Recon-PingSweep.pcap_Flow.csv

Recon-PingSweep.pcap_Flow.csv:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

Downloading 30/33
CSVS/Recon-PortScan/Recon-PortScan.pcap_Flow.csv

CSVS/Recon-PortScan/Recon-PortScan.pcap_(…): reconstructing file:   0%|          |  0.00B / 77.5MB

CSVS/Recon-PortScan/Recon-PortScan.pcap_(…): downloading bytes:           |  0.00B

Downloading 31/33
CSVS/SqlInjection/SqlInjection.pcap_Flow.csv

SqlInjection.pcap_Flow.csv:   0%|          | 0.00/3.49M [00:00<?, ?B/s]

Downloading 32/33
CSVS/VulnerabilityScan/VulnerabilityScan.pcap_Flow.csv

CSVS/VulnerabilityScan/VulnerabilityScan(…): reconstructing file:   0%|          |  0.00B /  226MB

CSVS/VulnerabilityScan/VulnerabilityScan(…): downloading bytes:           |  0.00B

Downloading 33/33
CSVS/XSS/XSS.pcap_Flow.csv

XSS.pcap_Flow.csv:   0%|          | 0.00/1.75M [00:00<?, ?B/s]

✅ Missing dataset files downloaded.

[A6] Final dataset-file validation
------------------------------------------------------------------------------
Validated dataset files: 33
Current dataset size: 18.52 GB

[A7] Rebuilding dataset manifest
------------------------------------------------------------------------------
Manifest rows: 33
✅ Dataset manifest rebuilt.

[A8] Restoring verified seven-family mapping
------------------------------------------------------------------------------
Observed source classes: 33
Unmapped source classes: 0
✅ Seven-family mapping restored.

Lookup dictionaries restored: 33

[A9] Rebuilding common dataset schema
------------------------------------------------------------------------------
Common columns          : 84
Total distinct columns  : 86
Structural candidates   : 82
Timestamp common        : True
Label common            : True

==============================================================================
SECTION 7 — FEATURE AUDIT
==============================================================================

[1] Structural feature candidates
------------------------------------------------------------------------------
Common columns              : 84
Structural feature candidates: 82
Timestamp used as feature   : False
Raw Label used as feature   : False

[2] Identifying numeric/non-numeric features
------------------------------------------------------------------------------
Sampling 01/33: Backdoor_Malware_1.csv
Sampling 02/33: Benign_1.csv
Sampling 03/33: BrowserHijacking_1.csv
Sampling 04/33: CommandInjection_1.csv
Sampling 05/33: DDoS-ACK_Fragmentation_1.csv
Sampling 06/33: DDoS-HTTP_Flood_1.csv
Sampling 07/33: DDoS-ICMP_Flood_1.csv
Sampling 08/33: DDoS-ICMP_Fragmentation_1.csv
Sampling 09/33: DDoS-PSHACK_Flood_1.csv
Sampling 10/33: DDoS-RSTFINFlood.pcap_Flow.csv
Sampling 11/33: DDoS-SYN_Flood.pcap_Flow.csv
Sampling 12/33: DDoS-SlowLoris.pcap_Flow.csv
Sampling 13/33: DDoS-SynonymousIP_Flood.pcap_Flow.csv
Sampling 14/33: DDoS-TCP_Flood.pcap_Flow.csv
Sampling 15/33: DDoS-UDP_Flood.pcap_Flow.csv
Sampling 16/33: DDoS-UDP_Fragmentation.pcap_Flow.csv
Sampling 17/33: DNS_Spoofing.pcap_Flow.csv
Sampling 18/33: DictionaryBruteForce.pcap_Flow.csv
Sampling 19/33: DoS-HTTP_Flood.pcap_Flow.csv
Sampling 20/33: DoS-SYN_Flood.pcap_Flow.csv
Sampling 21/33: DoS-TCP_Flood.pcap_Flow.csv
Sampling 22/33: DoS-UDP_Flood.pcap_Flow.csv
Sampling 23/33: MITM-ArpSpoofing.pcap_Flow.csv
Sampling 24/33: Mirai-greeth_flood.pcap_Flow.csv
Sampling 25/33: Mirai-greip_flood.pcap_Flow.csv
Sampling 26/33: Mirai-udpplain.pcap_Flow.csv
Sampling 27/33: Recon-HostDiscovery.pcap_Flow.csv
Sampling 28/33: Recon-OSScan.pcap_Flow.csv
Sampling 29/33: Recon-PingSweep.pcap_Flow.csv
Sampling 30/33: Recon-PortScan.pcap_Flow.csv
Sampling 31/33: SqlInjection.pcap_Flow.csv
Sampling 32/33: VulnerabilityScan.pcap_Flow.csv
Sampling 33/33: XSS.pcap_Flow.csv

Numeric feature candidates    : 79
Non-numeric candidates       : 3

[3] Non-numeric feature candidates
------------------------------------------------------------------------------

,feature,sample_non_missing_values,sample_missing_values,sample_conversion_failures,numeric_candidate
0,Flow ID,154982,0,154982,False
1,Src IP,154982,0,154982,False
2,Dst IP,154982,0,154982,False

[4] Numeric feature candidates
------------------------------------------------------------------------------
01. Src Port
02. Dst Port
03. Protocol
04. Flow Duration
05. Total Fwd Packet
06. Total Bwd packets
07. Total Length of Fwd Packet
08. Total Length of Bwd Packet
09. Fwd Packet Length Max
10. Fwd Packet Length Min
11. Fwd Packet Length Mean
12. Fwd Packet Length Std
13. Bwd Packet Length Max
14. Bwd Packet Length Min
15. Bwd Packet Length Mean
16. Bwd Packet Length Std
17. Flow Bytes/s
18. Flow Packets/s
19. Flow IAT Mean
20. Flow IAT Std
21. Flow IAT Max
22. Flow IAT Min
23. Fwd IAT Total
24. Fwd IAT Mean
25. Fwd IAT Std
26. Fwd IAT Max
27. Fwd IAT Min
28. Bwd IAT Total
29. Bwd IAT Mean
30. Bwd IAT Std
31. Bwd IAT Max
32. Bwd IAT Min
33. Fwd PSH Flags
34. Bwd PSH Flags
35. Fwd URG Flags
36. Bwd URG Flags
37. Fwd Header Length
38. Bwd Header Length
39. Fwd Packets/s
40. Bwd Packets/s
41. Packet Length Min
42. Packet Length Max
43. Packet Length Mean
44. Packet Length Std
45. Packet Length Variance
46. FIN Flag Count
47. SYN Flag Count
48. RST Flag Count
49. PSH Flag Count
50. ACK Flag Count
51. URG Flag Count
52. CWR Flag Count
53. ECE Flag Count
54. Down/Up Ratio
55. Average Packet Size
56. Fwd Segment Size Avg
57. Bwd Segment Size Avg
58. Fwd Bytes/Bulk Avg
59. Fwd Packet/Bulk Avg
60. Fwd Bulk Rate Avg
61. Bwd Bytes/Bulk Avg
62. Bwd Packet/Bulk Avg
63. Bwd Bulk Rate Avg
64. Subflow Fwd Packets
65. Subflow Fwd Bytes
66. Subflow Bwd Packets
67. Subflow Bwd Bytes
68. FWD Init Win Bytes
69. Bwd Init Win Bytes
70. Fwd Act Data Pkts
71. Fwd Seg Size Min
72. Active Mean
73. Active Std
74. Active Max
75. Active Min
76. Idle Mean
77. Idle Std
78. Idle Max
79. Idle Min

[5] Full feature-quality audit
------------------------------------------------------------------------------
All selected rows will now be scanned.
The process is chunk-based to protect Colab RAM.
Do not interrupt the runtime while this section is running.

------------------------------------------------------------------------------
Auditing 1/33:
Backdoor_Malware_1.csv
Rows audited: 2,703

------------------------------------------------------------------------------
Auditing 2/33:
Benign_1.csv
Rows audited: 91,506

------------------------------------------------------------------------------
Auditing 3/33:
BrowserHijacking_1.csv
Rows audited: 3,286

------------------------------------------------------------------------------
Auditing 4/33:
CommandInjection_1.csv
Rows audited: 3,848

------------------------------------------------------------------------------
Auditing 5/33:
DDoS-ACK_Fragmentation_1.csv
Rows audited: 37,296

------------------------------------------------------------------------------
Auditing 6/33:
DDoS-HTTP_Flood_1.csv
Rows audited: 513,672

------------------------------------------------------------------------------
Auditing 7/33:
DDoS-ICMP_Flood_1.csv
Rows audited: 7,834

------------------------------------------------------------------------------
Auditing 8/33:
DDoS-ICMP_Fragmentation_1.csv
Rows audited: 25,106

------------------------------------------------------------------------------
Auditing 9/33:
DDoS-PSHACK_Flood_1.csv
Rows audited: 5,007,067

------------------------------------------------------------------------------
Auditing 10/33:
DDoS-RSTFINFlood.pcap_Flow.csv
Rows audited: 12,968,618

------------------------------------------------------------------------------
Auditing 11/33:
DDoS-SYN_Flood.pcap_Flow.csv
Rows audited: 6,366,353

------------------------------------------------------------------------------
Auditing 12/33:
DDoS-SlowLoris.pcap_Flow.csv
Rows audited: 196,578

------------------------------------------------------------------------------
Auditing 13/33:
DDoS-SynonymousIP_Flood.pcap_Flow.csv
Rows audited: 799,351

------------------------------------------------------------------------------
Auditing 14/33:
DDoS-TCP_Flood.pcap_Flow.csv
Rows audited: 4,945,887

------------------------------------------------------------------------------
Auditing 15/33:
DDoS-UDP_Flood.pcap_Flow.csv
Rows audited: 41,146

------------------------------------------------------------------------------
Auditing 16/33:
DDoS-UDP_Fragmentation.pcap_Flow.csv
Rows audited: 9,757

------------------------------------------------------------------------------
Auditing 17/33:
DNS_Spoofing.pcap_Flow.csv
Rows audited: 74,938

------------------------------------------------------------------------------
Auditing 18/33:
DictionaryBruteForce.pcap_Flow.csv
Rows audited: 8,488

------------------------------------------------------------------------------
Auditing 19/33:
DoS-HTTP_Flood.pcap_Flow.csv
Rows audited: 965,554

------------------------------------------------------------------------------
Auditing 20/33:
DoS-SYN_Flood.pcap_Flow.csv
Rows audited: 3,997,110

------------------------------------------------------------------------------
Auditing 21/33:
DoS-TCP_Flood.pcap_Flow.csv
Rows audited: 1,638,068

------------------------------------------------------------------------------
Auditing 22/33:
DoS-UDP_Flood.pcap_Flow.csv
Rows audited: 934,009

------------------------------------------------------------------------------
Auditing 23/33:
MITM-ArpSpoofing.pcap_Flow.csv
Rows audited: 72,853

------------------------------------------------------------------------------
Auditing 24/33:
Mirai-greeth_flood.pcap_Flow.csv
Rows audited: 5,155

------------------------------------------------------------------------------
Auditing 25/33:
Mirai-greip_flood.pcap_Flow.csv
Rows audited: 10,401

------------------------------------------------------------------------------
Auditing 26/33:
Mirai-udpplain.pcap_Flow.csv
Rows audited: 7,455

------------------------------------------------------------------------------
Auditing 27/33:
Recon-HostDiscovery.pcap_Flow.csv
Rows audited: 329,985

------------------------------------------------------------------------------
Auditing 28/33:
Recon-OSScan.pcap_Flow.csv
Rows audited: 158,682

------------------------------------------------------------------------------
Auditing 29/33:
Recon-PingSweep.pcap_Flow.csv
Rows audited: 1,947

------------------------------------------------------------------------------
Auditing 30/33:
Recon-PortScan.pcap_Flow.csv
Rows audited: 175,050

------------------------------------------------------------------------------
Auditing 31/33:
SqlInjection.pcap_Flow.csv
Rows audited: 6,596

------------------------------------------------------------------------------
Auditing 32/33:
VulnerabilityScan.pcap_Flow.csv
Rows audited: 442,122

------------------------------------------------------------------------------
Auditing 33/33:
XSS.pcap_Flow.csv
Rows audited: 3,198

[6] Complete row-count validation
------------------------------------------------------------------------------
Expected verified rows: 39,851,619
Rows scanned          : 39,851,619
Verified row count matches: True

[7] Features with missing/infinite/conversion issues
------------------------------------------------------------------------------

,feature,missing_values,missing_percentage,conversion_failures,positive_infinity,negative_infinity,total_infinity,total_quality_issues
0,Flow Bytes/s,42838,0.107494,0,1789,0,1789,44627
1,Flow Packets/s,0,0.000000,0,44627,0,44627,44627

[8] Feature-quality summary
------------------------------------------------------------------------------
Rows scanned              : 39,851,619
Structural candidates     : 82
Numeric candidates        : 79
Non-numeric candidates    : 3
Missing numeric values    : 42,838
Conversion failures       : 0
Positive infinity values  : 46,416
Negative infinity values  : 0
Total infinity values     : 46,416
Missing timestamps        : 0
Invalid timestamps        : 0
Missing raw labels        : 0

[9] Rebuilding source attack-class distribution
------------------------------------------------------------------------------

        source_attack_class     count  percentage
0          DDoS-RSTFINFlood  12968618   32.542261
1            DDoS-SYN_Flood   6366353   15.975143
2         DDoS-PSHACK_Flood   5007067   12.564275
3            DDoS-TCP_Flood   4945887   12.410756
4             DoS-SYN_Flood   3997110   10.029981
5             DoS-TCP_Flood   1638068    4.110418
6            DoS-HTTP_Flood    965554    2.422873
7             DoS-UDP_Flood    934009    2.343717
8   DDoS-SynonymousIP_Flood    799351    2.005818
9           DDoS-HTTP_Flood    513672    1.288961
10        VulnerabilityScan    442122    1.109420
11      Recon-HostDiscovery    329985    0.828034
12           DDoS-SlowLoris    196578    0.493275
13           Recon-PortScan    175050    0.439254
14             Recon-OSScan    158682    0.398182
15             Benign_Final     91506    0.229617
16             DNS_Spoofing     74938    0.188043
17         MITM-ArpSpoofing     72853    0.182811
18           DDoS-UDP_Flood     41146    0.103248
19   DDoS-ACK_Fragmentation     37296    0.093587
20  DDoS-ICMP_Fragmentation     25106    0.062999
21        Mirai-greip_flood     10401    0.026099
22   DDoS-UDP_Fragmentation      9757    0.024483
23     DictionaryBruteForce      8488    0.021299
24          DDoS-ICMP_Flood      7834    0.019658
25           Mirai-udpplain      7455    0.018707
26             SqlInjection      6596    0.016551
27       Mirai-greeth_flood      5155    0.012935
28         CommandInjection      3848    0.009656
29         BrowserHijacking      3286    0.008246
30                      XSS      3198    0.008025
31         Backdoor_Malware      2703    0.006783
32          Recon-PingSweep      1947    0.004886

[10] Research-family distribution
------------------------------------------------------------------------------

  research_family   records  source_classes  percentage
0            DDoS  30918665              12   77.584464
1             DoS   7534741               4   18.906988
2           Mirai     23011               3    0.057742
3           Recon   1107786               5    2.779777
4        Spoofing    147791               2    0.370853
5             Web     19631               5    0.049260
6      BruteForce      8488               1    0.021299
7          Benign     91506               1    0.229617

[11] Saving leakage-safe preprocessing policy
------------------------------------------------------------------------------
✅ Feature policy saved:
/content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_feature_policy.json

[12] Leakage-safety policy
------------------------------------------------------------------------------
GLOBAL FEATURE AUDIT:
  Used only for structural/data-quality documentation.

INSIDE EACH LOAFO FOLD:
  Imputation fitting       → development training only
  Infinity handling        → development training only
  Zero-variance removal    → development training only
  Feature selection        → development training only
  StandardScaler fitting   → development training only
  Threshold selection      → development validation only
  Held-out attack family   → NEVER used for fitting/tuning

[13] Final validation
------------------------------------------------------------------------------
Dataset files                    : 33
Source classes                   : 33
Verified total rows              : 39,851,619
Common columns                   : 84
Structural feature candidates    : 82
Numeric feature candidates       : 79
Non-numeric feature candidates   : 3
Feature conversion failures      : 0
Missing timestamps               : 0
Invalid timestamps               : 0
All seven LOAFO families present : True
All audit artifacts saved        : True

==============================================================================
✅ SECTION 7 PASSED — Runtime recovered, feature audit completed, and leakage-safe preprocessing policy is ready.
==============================================================================

# STEP 8 — Strict Seven-Fold LOAFO Partition Construction

# STEP 8A — Add this Markdown / Text cell

# 8. Strict Seven-Fold LOAFO Partition Construction

## 8.1 Purpose

This section constructs the complete Leave-One-Attack-Family-Out (LOAFO) partition plan used for zero-day evaluation.

Seven independent folds are created:

1. DDoS held out
2. DoS held out
3. Mirai held out
4. Recon held out
5. Spoofing held out
6. Web held out
7. BruteForce held out

During each fold, one complete attack family is treated as an unseen zero-day family.

---

## 8.2 Strict Isolation Principle

For a given LOAFO fold, the held-out attack family must never participate in:

- Preprocessing fitting
- Missing-value statistic estimation
- Infinite-value handling
- Feature selection
- Standardization
- Self-supervised pretraining
- Supervised training
- Validation
- Hyperparameter tuning
- Threshold selection

The held-out family is available only during final zero-day evaluation.

This is the core requirement that makes the experiment a genuine zero-day simulation.

---

## 8.3 Development Split

For attack families that are not held out, each source capture is partitioned chronologically into:

- 70% development training
- 15% development validation
- 15% known-family testing

Benign traffic is partitioned using the same proportions:

- 70% benign training
- 15% benign validation
- 15% benign testing

The split is chronological rather than randomly shuffled.

---

## 8.4 Zero-Day Test Composition

For each LOAFO fold:

**Zero-day attack test data**

contains 100% of the held-out attack-family records.

**Benign test data**

contains the final 15% chronological portion of the benign capture.

Therefore, the later zero-day binary evaluation will combine:

`held-out attack-family test + benign test`

This enables calculation of:

- Zero-day recall
- Precision
- F1
- ROC-AUC
- PR-AUC
- False-positive rate

---

## 8.5 Known-Family Test Data

For non-held-out attack families, the final 15% chronological portion is reserved as known-family test data.

This test partition is not used for:

- Training
- Validation
- Preprocessing fitting
- Threshold selection

It allows known-family performance to be reported separately from zero-day performance.

---

## 8.6 Temporal Integrity

Because the proposed GRU framework depends on temporal structure, record ordering must be verified before row-range splits are created.

For every source CSV file, this section verifies that:

- Timestamps are valid
- Timestamp order is monotonically increasing
- No backward temporal transitions occur
- Audited row counts match the verified dataset counts

Temporal windows created later will never cross:

- Training/validation boundaries
- Validation/test boundaries
- Source-file boundaries
- LOAFO family boundaries

---

## 8.7 Disk-Efficient Partition Representation

The raw 18+ GB dataset will not be duplicated seven times.

Instead, this section creates a partition manifest containing:

- Fold
- Held-out family
- Source file
- Source attack class
- Research family
- Partition role
- Start row
- End row
- Number of rows
- Binary target
- Model-development permissions

Later sections will stream the required row ranges from the original files.

---

## 8.8 Partition Roles

The partition manifest uses five roles:

### development_train

May be used for:

- Preprocessing fitting
- SSL pretraining
- Supervised training

### development_validation

May be used for:

- Hyperparameter selection
- Threshold selection
- Early stopping

It may not fit preprocessing parameters.

### known_test

Used only for final known-family evaluation.

### zero_day_attack_test

Contains the entire held-out attack family.

Used only for zero-day evaluation.

### benign_test

Reserved benign traffic used during final evaluation.

---

## 8.9 Random Seeds

LOAFO partition boundaries are deterministic and chronological.

Therefore, the dataset partition itself does not change across random seeds.

The five research seeds affect:

- Model initialization
- Mini-batch ordering
- Stochastic augmentation
- Optimization

This ensures that performance variability reflects model stochasticity rather than changing test sets.

---

## 8.10 Output Artifacts

This section generates:

`CICIoT2023_temporal_order_audit.csv`

`CICIoT2023_LOAFO_split_manifest.csv`

`CICIoT2023_LOAFO_fold_summary.csv`

`CICIoT2023_LOAFO_integrity_checks.csv`

`CICIoT2023_LOAFO_policy.json`

---

## 8.11 Expected Result

A valid Step 8 must confirm:

- All 33 source files remain chronologically ordered
- All seven LOAFO folds are created
- The held-out family contributes zero rows to training
- The held-out family contributes zero rows to validation
- The held-out family contributes zero rows to known-family testing
- 100% of held-out-family records appear in zero-day testing
- Every fold conserves all dataset rows
- Benign training, validation, and test partitions exist
- No data leakage is detected

The section should finish with:

`✅ SECTION 8 PASSED — Strict seven-fold LOAFO partitions are valid and leakage-free.`

# STEP 8.1 — Check the timestamp format

In [ ]:
import pandas as pd

print("=" * 60)
print("STEP 8.1 — CHECK TIMESTAMP FORMAT")
print("=" * 60)

sample = pd.read_csv(
    DATA_FILES[0],
    usecols=["Timestamp"],
    nrows=10
)

print("\nFirst 10 timestamps:\n")

print(
    sample["Timestamp"].to_string(
        index=False
    )
)

print("\n" + "=" * 60)
print("✅ STEP 8.1 COMPLETE")
print("=" * 60)

============================================================
STEP 8.1 — CHECK TIMESTAMP FORMAT
============================================================

First 10 timestamps:

13/02/2023 01:58:04 PM
13/02/2023 01:58:04 PM
13/02/2023 01:58:05 PM
13/02/2023 01:58:05 PM
13/02/2023 01:58:23 PM
13/02/2023 01:58:23 PM
13/02/2023 01:58:24 PM
13/02/2023 01:58:19 PM
13/02/2023 01:58:00 PM
13/02/2023 01:58:33 PM

============================================================
✅ STEP 8.1 COMPLETE
============================================================

# STEP 8.2 — Verify this timestamp format across all 33 files

In [ ]:
# ================================================================
# STEP 8.2 — VERIFY TIMESTAMP FORMAT ACROSS ALL FILES
# ================================================================

import pandas as pd

print("=" * 70)
print("STEP 8.2 — VERIFY TIMESTAMP FORMAT")
print("=" * 70)

TIMESTAMP_FORMAT = "%d/%m/%Y %I:%M:%S %p"

files_passed = 0
files_failed = 0

results = []

for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    print(
        f"\nChecking {file_number:02d}/{len(DATA_FILES)}: "
        f"{file_path.name}"
    )

    # Read only a small sample.
    sample = pd.read_csv(
        file_path,
        usecols=["Timestamp"],
        nrows=5000,
        dtype={"Timestamp": "string"}
    )

    parsed = pd.to_datetime(
        sample["Timestamp"],
        format=TIMESTAMP_FORMAT,
        errors="coerce"
    )

    invalid_count = int(
        parsed.isna().sum()
    )

    if invalid_count == 0:

        status = "PASS"

        files_passed += 1

        print(
            "✅ Timestamp format valid"
        )

    else:

        status = "FAIL"

        files_failed += 1

        print(
            f"❌ Invalid timestamps in sample: "
            f"{invalid_count}"
        )


    results.append({

        "file_name":
            file_path.name,

        "sample_rows":
            len(sample),

        "invalid_timestamps":
            invalid_count,

        "status":
            status
    })


timestamp_format_check = pd.DataFrame(
    results
)


print("\n" + "=" * 70)

print("STEP 8.2 SUMMARY")

print("=" * 70)

print(
    "Files checked :",
    len(DATA_FILES)
)

print(
    "Files passed  :",
    files_passed
)

print(
    "Files failed  :",
    files_failed
)


if files_failed == 0:

    print(
        "\n✅ STEP 8.2 PASSED — "
        "Timestamp format is consistent."
    )

else:

    print(
        "\n❌ STEP 8.2 FAILED — "
        "Some files use a different timestamp format."
    )


print("=" * 70)

======================================================================
STEP 8.2 — VERIFY TIMESTAMP FORMAT
======================================================================

Checking 01/33: Backdoor_Malware_1.csv
✅ Timestamp format valid

Checking 02/33: Benign_1.csv
✅ Timestamp format valid

Checking 03/33: BrowserHijacking_1.csv
✅ Timestamp format valid

Checking 04/33: CommandInjection_1.csv
✅ Timestamp format valid

Checking 05/33: DDoS-ACK_Fragmentation_1.csv
✅ Timestamp format valid

Checking 06/33: DDoS-HTTP_Flood_1.csv
✅ Timestamp format valid

Checking 07/33: DDoS-ICMP_Flood_1.csv
✅ Timestamp format valid

Checking 08/33: DDoS-ICMP_Fragmentation_1.csv
✅ Timestamp format valid

Checking 09/33: DDoS-PSHACK_Flood_1.csv
✅ Timestamp format valid

Checking 10/33: DDoS-RSTFINFlood.pcap_Flow.csv
✅ Timestamp format valid

Checking 11/33: DDoS-SYN_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 12/33: DDoS-SlowLoris.pcap_Flow.csv
✅ Timestamp format valid

Checking 13/33: DDoS-SynonymousIP_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 14/33: DDoS-TCP_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 15/33: DDoS-UDP_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 16/33: DDoS-UDP_Fragmentation.pcap_Flow.csv
✅ Timestamp format valid

Checking 17/33: DNS_Spoofing.pcap_Flow.csv
✅ Timestamp format valid

Checking 18/33: DictionaryBruteForce.pcap_Flow.csv
✅ Timestamp format valid

Checking 19/33: DoS-HTTP_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 20/33: DoS-SYN_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 21/33: DoS-TCP_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 22/33: DoS-UDP_Flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 23/33: MITM-ArpSpoofing.pcap_Flow.csv
✅ Timestamp format valid

Checking 24/33: Mirai-greeth_flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 25/33: Mirai-greip_flood.pcap_Flow.csv
✅ Timestamp format valid

Checking 26/33: Mirai-udpplain.pcap_Flow.csv
✅ Timestamp format valid

Checking 27/33: Recon-HostDiscovery.pcap_Flow.csv
✅ Timestamp format valid

Checking 28/33: Recon-OSScan.pcap_Flow.csv
✅ Timestamp format valid

Checking 29/33: Recon-PingSweep.pcap_Flow.csv
✅ Timestamp format valid

Checking 30/33: Recon-PortScan.pcap_Flow.csv
✅ Timestamp format valid

Checking 31/33: SqlInjection.pcap_Flow.csv
✅ Timestamp format valid

Checking 32/33: VulnerabilityScan.pcap_Flow.csv
✅ Timestamp format valid

Checking 33/33: XSS.pcap_Flow.csv
✅ Timestamp format valid

======================================================================
STEP 8.2 SUMMARY
======================================================================
Files checked : 33
Files passed  : 33
Files failed  : 0

✅ STEP 8.2 PASSED — Timestamp format is consistent.
======================================================================

# STEP 8.3 — Sort All Files Chronologically

In [ ]:
# ======================================================================
# STEP 8.3 — CREATE CHRONOLOGICALLY SORTED DATASET
# ======================================================================
#
# IMPORTANT:
# - Original CSV files are NEVER modified.
# - A new Parquet file is created for every source class.
# - Sorting uses the genuine Timestamp column.
# - Equal timestamps retain source-row order as a deterministic tie-break.
# - DuckDB can spill sorting work to disk, protecting Colab RAM.
# - The process is resumable: completed files are reused after interruption.
# ======================================================================

import os
import re
import gc
import sys
import time
import shutil
import subprocess
from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq

print("=" * 78)
print("STEP 8.3 — CREATE CHRONOLOGICALLY SORTED DATASET")
print("=" * 78)


# ======================================================================
# 8.3.1 — INSTALL / IMPORT DUCKDB
# ======================================================================

print("\n[1] Preparing disk-backed sorting engine")
print("-" * 78)

try:
    import duckdb

    print(
        "✅ DuckDB already installed:",
        duckdb.__version__
    )

except ImportError:

    print(
        "Installing DuckDB..."
    )

    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "duckdb"
    ])

    import duckdb

    print(
        "✅ DuckDB installed:",
        duckdb.__version__
    )


# ======================================================================
# 8.3.2 — VERIFY REQUIRED VARIABLES
# ======================================================================

print("\n[2] Verifying current runtime")
print("-" * 78)

required_variables = [
    "DATA_FILES",
    "TOTAL_ROWS",
    "TIMESTAMP_COLUMN",
    "NUMERIC_FEATURE_CANDIDATES",
    "NON_NUMERIC_FEATURE_CANDIDATES",
    "dataset_manifest",
    "source_class_distribution",
    "FILE_TO_SOURCE_CLASS",
    "DIRECTORIES",
    "PROJECT_ROOT"
]

missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]

if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun the complete recovery + Step 7 cell."
    )


print(
    "Dataset files :",
    len(DATA_FILES)
)

print(
    "Dataset rows  :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Numeric fields:",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "✅ Required variables are available."
)


# ======================================================================
# 8.3.3 — EXACT TIMESTAMP FORMAT
# ======================================================================

TIMESTAMP_FORMAT = (
    "%d/%m/%Y %I:%M:%S %p"
)


print("\n[3] Timestamp parsing policy")
print("-" * 78)

print(
    "Raw format:",
    "DD/MM/YYYY HH:MM:SS AM/PM"
)

print(
    "Parser    :",
    TIMESTAMP_FORMAT
)

print(
    "✅ Format verified in Step 8.2."
)


# ======================================================================
# 8.3.4 — OUTPUT LOCATIONS
# ======================================================================

SORTED_DATA_DIR = (
    DIRECTORIES["dataset"]
    / "chronological_parquet"
)

SORTED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


SORT_TEMP_ROOT = (
    PROJECT_ROOT
    / "duckdb_sort_temp"
)

SORT_TEMP_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


SORT_MANIFEST_PATH = (
    DIRECTORIES["dataset_audit"]
    / "CICIoT2023_chronological_sort_manifest.csv"
)


print("\n[4] Output locations")
print("-" * 78)

print(
    "Sorted dataset:"
)

print(
    SORTED_DATA_DIR
)

print(
    "\nProgress manifest:"
)

print(
    SORT_MANIFEST_PATH
)


# ======================================================================
# 8.3.5 — SOURCE CLASS ROW COUNTS
# ======================================================================

SOURCE_CLASS_TO_ROW_COUNT = dict(

    zip(

        source_class_distribution[
            "source_attack_class"
        ].astype(str),

        source_class_distribution[
            "count"
        ].astype(int)
    )
)


if len(
    SOURCE_CLASS_TO_ROW_COUNT
) != 33:

    raise RuntimeError(
        "Expected 33 source-class row counts, "
        f"but found {len(SOURCE_CLASS_TO_ROW_COUNT)}."
    )


# ======================================================================
# 8.3.6 — HELPER FUNCTIONS
# ======================================================================

def safe_file_name(text):

    return re.sub(
        r"[^A-Za-z0-9_.-]+",
        "_",
        str(text)
    )


def escape_sql_string(text):

    return (
        str(text)
        .replace(
            "'",
            "''"
        )
    )


def build_duckdb_type_map(
    file_path
):

    columns = list(

        pd.read_csv(
            file_path,
            nrows=0
        ).columns
    )


    forbidden_names = {
        "__sort_timestamp",
        "__source_row_id"
    }


    collisions = (
        forbidden_names
        &
        set(columns)
    )


    if collisions:

        raise RuntimeError(
            "Reserved sorting columns already exist: "
            + str(collisions)
        )


    type_entries = []


    for column in columns:

        escaped_column = (
            str(column)
            .replace(
                "'",
                "''"
            )
        )


        if (
            column
            in NUMERIC_FEATURE_CANDIDATES
        ):

            duckdb_type = (
                "DOUBLE"
            )

        else:

            # Timestamp, Label, Flow ID,
            # Src IP, Dst IP,
            # Category and Attack Name
            # remain strings.
            duckdb_type = (
                "VARCHAR"
            )


        type_entries.append(

            f"'{escaped_column}': "
            f"'{duckdb_type}'"
        )


    return (
        "{"
        +
        ", ".join(
            type_entries
        )
        +
        "}"
    )


def save_progress(
    records
):

    if len(records) > 0:

        pd.DataFrame(
            records
        ).to_csv(
            SORT_MANIFEST_PATH,
            index=False
        )


# ======================================================================
# 8.3.7 — INITIAL DISK CHECK
# ======================================================================

print("\n[5] Initial storage check")
print("-" * 78)


disk = shutil.disk_usage(
    "/content"
)


free_disk_gb = (
    disk.free
    /
    (1024 ** 3)
)


print(
    "Current free disk:",
    f"{free_disk_gb:.2f} GB"
)


if free_disk_gb < 25:

    raise RuntimeError(
        "Less than 25 GB of free disk space remains. "
        "Do not start chronological sorting."
    )


print(
    "✅ Sufficient starting disk space detected."
)


# ======================================================================
# 8.3.8 — SORT EVERY FILE
# ======================================================================

print("\n[6] Starting chronological sorting")
print("-" * 78)

print(
    "This is a large-data operation."
)

print(
    "Some DDoS files may take much longer than the small files."
)

print(
    "Completed files will be reused if this cell is run again."
)


sort_records = []


for file_number, file_path in enumerate(
    DATA_FILES,
    start=1
):

    resolved_input_path = str(
        Path(file_path).resolve()
    )


    source_class = (
        FILE_TO_SOURCE_CLASS[
            resolved_input_path
        ]
    )


    expected_rows = int(

        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    output_name = (
        safe_file_name(
            source_class
        )
        +
        ".parquet"
    )


    output_path = (
        SORTED_DATA_DIR
        /
        output_name
    )


    partial_path = (
        SORTED_DATA_DIR
        /
        (
            safe_file_name(
                source_class
            )
            +
            ".partial.parquet"
        )
    )


    print("\n" + "=" * 78)

    print(
        f"SORTING {file_number:02d}/{len(DATA_FILES)}"
    )

    print(
        "Source class :",
        source_class
    )

    print(
        "Input file   :",
        file_path.name
    )

    print(
        "Expected rows:",
        f"{expected_rows:,}"
    )


    # ==================================================================
    # REUSE AN ALREADY COMPLETED FILE
    # ==================================================================

    if output_path.exists():

        try:

            existing_rows = int(

                pq.ParquetFile(
                    output_path
                )
                .metadata
                .num_rows
            )


            if (
                existing_rows
                ==
                expected_rows
            ):

                output_size_gb = (

                    output_path.stat().st_size

                    /

                    (1024 ** 3)
                )


                print(
                    "✅ Existing sorted file is valid."
                )

                print(
                    "Reusing:",
                    output_path.name
                )


                sort_records.append({

                    "file_number":
                        file_number,

                    "source_attack_class":
                        source_class,

                    "input_file":
                        str(file_path),

                    "output_file":
                        str(output_path),

                    "expected_rows":
                        expected_rows,

                    "output_rows":
                        existing_rows,

                    "input_size_gb":
                        round(
                            file_path.stat().st_size
                            /
                            (1024 ** 3),
                            4
                        ),

                    "output_size_gb":
                        round(
                            output_size_gb,
                            4
                        ),

                    "status":
                        "REUSED"
                })


                save_progress(
                    sort_records
                )

                continue


            else:

                print(
                    "⚠️ Existing output has wrong row count."
                )

                print(
                    "It will be rebuilt."
                )

                output_path.unlink()


        except Exception:

            print(
                "⚠️ Existing output could not be validated."
            )

            print(
                "It will be rebuilt."
            )

            output_path.unlink(
                missing_ok=True
            )


    # ==================================================================
    # REMOVE AN OLD INCOMPLETE OUTPUT
    # ==================================================================

    if partial_path.exists():

        partial_path.unlink()


    # ==================================================================
    # PER-FILE STORAGE SAFETY CHECK
    # ==================================================================

    input_size_gb = (

        file_path.stat().st_size

        /

        (1024 ** 3)
    )


    disk = shutil.disk_usage(
        "/content"
    )


    free_disk_gb = (

        disk.free

        /

        (1024 ** 3)
    )


    minimum_safe_free_gb = max(

        12.0,

        (
            input_size_gb
            *
            2.5
        )
        +
        4.0
    )


    print(
        "Input size    :",
        f"{input_size_gb:.2f} GB"
    )

    print(
        "Free disk     :",
        f"{free_disk_gb:.2f} GB"
    )

    print(
        "Safety minimum:",
        f"{minimum_safe_free_gb:.2f} GB"
    )


    if (
        free_disk_gb
        <
        minimum_safe_free_gb
    ):

        save_progress(
            sort_records
        )

        raise RuntimeError(

            f"Not enough free disk space to safely sort "
            f"{source_class}."
        )


    # ==================================================================
    # PREPARE TEMPORARY DUCKDB DIRECTORY
    # ==================================================================

    temp_dir = (

        SORT_TEMP_ROOT

        /

        (
            f"{file_number:02d}_"
            +
            safe_file_name(
                source_class
            )
        )
    )


    if temp_dir.exists():

        shutil.rmtree(
            temp_dir,
            ignore_errors=True
        )


    temp_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    spill_dir = (
        temp_dir
        /
        "spill"
    )


    spill_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    database_path = (
        temp_dir
        /
        "sorting.duckdb"
    )


    connection = None


    start_time = time.time()


    try:

        # ==============================================================
        # BUILD EXPLICIT CSV TYPE MAP
        # ==============================================================

        type_map_sql = (
            build_duckdb_type_map(
                file_path
            )
        )


        input_sql = (
            escape_sql_string(
                Path(
                    file_path
                ).resolve()
            )
        )


        partial_sql = (
            escape_sql_string(
                partial_path.resolve()
            )
        )


        spill_sql = (
            escape_sql_string(
                spill_dir.resolve()
            )
        )


        # ==============================================================
        # CREATE DUCKDB CONNECTION
        # ==============================================================

        connection = duckdb.connect(
            database=str(
                database_path
            )
        )


        connection.execute(
            "SET threads = 2"
        )


        connection.execute(
            "SET memory_limit = '4GB'"
        )


        connection.execute(
            "SET preserve_insertion_order = true"
        )


        connection.execute(

            f"SET temp_directory = "
            f"'{spill_sql}'"
        )


        # ==============================================================
        # SORT
        #
        # __source_row_id is used only as a stable tie-break when
        # multiple flows have exactly the same second-level timestamp.
        #
        # The two helper columns are removed before saving.
        # ==============================================================

        sort_query = f"""

        COPY (

            SELECT
                * EXCLUDE (
                    __sort_timestamp,
                    __source_row_id
                )

            FROM (

                SELECT

                    *,

                    strptime(
                        "Timestamp",
                        '{TIMESTAMP_FORMAT}'
                    )
                    AS __sort_timestamp,

                    row_number()
                    OVER ()
                    AS __source_row_id

                FROM read_csv_auto(

                    '{input_sql}',

                    header = true,

                    types = {type_map_sql},

                    nullstr = '',

                    ignore_errors = false
                )
            )

            ORDER BY

                __sort_timestamp ASC,

                __source_row_id ASC

        )

        TO '{partial_sql}'

        (
            FORMAT PARQUET,
            COMPRESSION ZSTD,
            ROW_GROUP_SIZE 100000
        );

        """


        print(
            "Sorting..."
        )


        connection.execute(
            sort_query
        )


        connection.close()

        connection = None


        # ==============================================================
        # VERIFY ROW COUNT BEFORE FINALIZING
        # ==============================================================

        if not partial_path.exists():

            raise RuntimeError(
                "Sorted temporary Parquet file "
                "was not created."
            )


        output_rows = int(

            pq.ParquetFile(
                partial_path
            )
            .metadata
            .num_rows
        )


        print(
            "Sorted rows   :",
            f"{output_rows:,}"
        )


        if (
            output_rows
            !=
            expected_rows
        ):

            raise RuntimeError(

                f"Row-count mismatch for {source_class}: "
                f"expected {expected_rows:,}, "
                f"got {output_rows:,}."
            )


        # ==============================================================
        # ATOMIC FINALIZATION
        # ==============================================================

        os.replace(
            partial_path,
            output_path
        )


        output_size_gb = (

            output_path.stat().st_size

            /

            (1024 ** 3)
        )


        elapsed_minutes = (

            time.time()
            -
            start_time

        ) / 60


        print(
            "✅ Sorted file created."
        )

        print(
            "Output size   :",
            f"{output_size_gb:.2f} GB"
        )

        print(
            "Time          :",
            f"{elapsed_minutes:.2f} minutes"
        )


        sort_records.append({

            "file_number":
                file_number,

            "source_attack_class":
                source_class,

            "input_file":
                str(file_path),

            "output_file":
                str(output_path),

            "expected_rows":
                expected_rows,

            "output_rows":
                output_rows,

            "input_size_gb":
                round(
                    input_size_gb,
                    4
                ),

            "output_size_gb":
                round(
                    output_size_gb,
                    4
                ),

            "status":
                "SORTED"
        })


        save_progress(
            sort_records
        )


    except Exception as error:

        if connection is not None:

            try:
                connection.close()

            except Exception:
                pass


        if partial_path.exists():

            partial_path.unlink(
                missing_ok=True
            )


        sort_records.append({

            "file_number":
                file_number,

            "source_attack_class":
                source_class,

            "input_file":
                str(file_path),

            "output_file":
                str(output_path),

            "expected_rows":
                expected_rows,

            "output_rows":
                0,

            "input_size_gb":
                round(
                    input_size_gb,
                    4
                ),

            "output_size_gb":
                0.0,

            "status":
                "ERROR: "
                +
                str(error)
        })


        save_progress(
            sort_records
        )


        shutil.rmtree(
            temp_dir,
            ignore_errors=True
        )


        raise RuntimeError(

            f"Chronological sorting failed for "
            f"{source_class}.\n\n"
            f"Original error:\n{error}"
        )


    finally:

        if connection is not None:

            try:
                connection.close()

            except Exception:
                pass


        shutil.rmtree(
            temp_dir,
            ignore_errors=True
        )


        gc.collect()


# ======================================================================
# 8.3.9 — BUILD SORTED DATASET VARIABLES
# ======================================================================

print("\n" + "=" * 78)

print("[7] Building chronological dataset variables")

print("-" * 78)


SORTED_FILE_BY_SOURCE_CLASS = {}


for source_class in (
    dataset_manifest[
        "attack_class_directory"
    ]
    .astype(str)
):

    output_path = (

        SORTED_DATA_DIR

        /

        (
            safe_file_name(
                source_class
            )
            +
            ".parquet"
        )
    )


    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ] = output_path


SORTED_DATA_FILES = [

    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ]

    for source_class
    in dataset_manifest[
        "attack_class_directory"
    ].astype(str)
]


missing_sorted_files = [

    str(path)

    for path in SORTED_DATA_FILES

    if not path.exists()
]


if missing_sorted_files:

    raise RuntimeError(

        "Some sorted files are missing:\n"

        +

        "\n".join(
            missing_sorted_files
        )
    )


print(
    "Sorted files:",
    len(SORTED_DATA_FILES)
)


# ======================================================================
# 8.3.10 — VERIFY TOTAL ROW CONSERVATION
# ======================================================================

print("\n[8] Row-count conservation")
print("-" * 78)


sorted_row_counts = []


for source_class, path in (
    SORTED_FILE_BY_SOURCE_CLASS.items()
):

    rows = int(

        pq.ParquetFile(
            path
        )
        .metadata
        .num_rows
    )


    sorted_row_counts.append(
        rows
    )


SORTED_TOTAL_ROWS = int(
    sum(
        sorted_row_counts
    )
)


SORTED_ROW_TOTAL_MATCH = (

    SORTED_TOTAL_ROWS
    ==
    TOTAL_ROWS
)


print(
    "Original rows:",
    f"{TOTAL_ROWS:,}"
)

print(
    "Sorted rows  :",
    f"{SORTED_TOTAL_ROWS:,}"
)

print(
    "Totals match :",
    SORTED_ROW_TOTAL_MATCH
)


# ======================================================================
# 8.3.11 — FINAL SORT MANIFEST
# ======================================================================

SORTED_DATASET_MANIFEST = pd.DataFrame(
    sort_records
)


SORTED_DATASET_MANIFEST.to_csv(

    SORT_MANIFEST_PATH,

    index=False
)


total_sorted_size_gb = sum(

    path.stat().st_size

    for path
    in SORTED_DATA_FILES

) / (1024 ** 3)


final_free_disk_gb = (

    shutil.disk_usage(
        "/content"
    ).free

    /

    (1024 ** 3)
)


print("\n[9] Chronological dataset summary")
print("-" * 78)


print(
    "Sorted source files :",
    len(SORTED_DATA_FILES)
)

print(
    "Sorted total rows   :",
    f"{SORTED_TOTAL_ROWS:,}"
)

print(
    "Sorted dataset size :",
    f"{total_sorted_size_gb:.2f} GB"
)

print(
    "Free disk remaining :",
    f"{final_free_disk_gb:.2f} GB"
)

print(
    "Original CSV changed:",
    False
)


# ======================================================================
# 8.3.12 — FINAL VALIDATION
# ======================================================================

step_8_3_valid = (

    len(
        SORTED_DATA_FILES
    ) == 33

    and

    all(
        path.exists()
        for path
        in SORTED_DATA_FILES
    )

    and

    SORTED_ROW_TOTAL_MATCH

    and

    SORT_MANIFEST_PATH.exists()
)


print("\n" + "=" * 78)


if step_8_3_valid:

    print(
        "✅ STEP 8.3 PASSED — "
        "Chronologically sorted dataset derivatives were created."
    )

    print(
        "Next step: verify chronological ordering "
        "before constructing LOAFO partitions."
    )

else:

    print(
        "❌ STEP 8.3 FAILED — "
        "Do not continue to partition construction."
    )


print("=" * 78)

==============================================================================
STEP 8.3 — CREATE CHRONOLOGICALLY SORTED DATASET
==============================================================================

[1] Preparing disk-backed sorting engine
------------------------------------------------------------------------------
✅ DuckDB already installed: 1.3.2

[2] Verifying current runtime
------------------------------------------------------------------------------
Dataset files : 33
Dataset rows  : 39,851,619
Numeric fields: 79
✅ Required variables are available.

[3] Timestamp parsing policy
------------------------------------------------------------------------------
Raw format: DD/MM/YYYY HH:MM:SS AM/PM
Parser    : %d/%m/%Y %I:%M:%S %p
✅ Format verified in Step 8.2.

[4] Output locations
------------------------------------------------------------------------------
Sorted dataset:
/content/ZeroDay_IoT_Research/dataset/chronological_parquet

Progress manifest:
/content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_chronological_sort_manifest.csv

[5] Initial storage check
------------------------------------------------------------------------------
Current free disk: 68.84 GB
✅ Sufficient starting disk space detected.

[6] Starting chronological sorting
------------------------------------------------------------------------------
This is a large-data operation.
Some DDoS files may take much longer than the small files.
Completed files will be reused if this cell is run again.

==============================================================================
SORTING 01/33
Source class : Backdoor_Malware
Input file   : Backdoor_Malware_1.csv
Expected rows: 2,703
Input size    : 0.00 GB
Free disk     : 68.84 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 2,703
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 02/33
Source class : Benign_Final
Input file   : Benign_1.csv
Expected rows: 91,506
Input size    : 0.05 GB
Free disk     : 68.83 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 91,506
✅ Sorted file created.
Output size   : 0.01 GB
Time          : 0.09 minutes

==============================================================================
SORTING 03/33
Source class : BrowserHijacking
Input file   : BrowserHijacking_1.csv
Expected rows: 3,286
Input size    : 0.00 GB
Free disk     : 68.82 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 3,286
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 04/33
Source class : CommandInjection
Input file   : CommandInjection_1.csv
Expected rows: 3,848
Input size    : 0.00 GB
Free disk     : 68.82 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 3,848
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 05/33
Source class : DDoS-ACK_Fragmentation
Input file   : DDoS-ACK_Fragmentation_1.csv
Expected rows: 37,296
Input size    : 0.02 GB
Free disk     : 68.82 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 37,296
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.04 minutes

==============================================================================
SORTING 06/33
Source class : DDoS-HTTP_Flood
Input file   : DDoS-HTTP_Flood_1.csv
Expected rows: 513,672
Input size    : 0.25 GB
Free disk     : 68.82 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 513,672
✅ Sorted file created.
Output size   : 0.04 GB
Time          : 0.32 minutes

==============================================================================
SORTING 07/33
Source class : DDoS-ICMP_Flood
Input file   : DDoS-ICMP_Flood_1.csv
Expected rows: 7,834
Input size    : 0.00 GB
Free disk     : 68.78 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 7,834
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 08/33
Source class : DDoS-ICMP_Fragmentation
Input file   : DDoS-ICMP_Fragmentation_1.csv
Expected rows: 25,106
Input size    : 0.01 GB
Free disk     : 68.78 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 25,106
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.02 minutes

==============================================================================
SORTING 09/33
Source class : DDoS-PSHACK_Flood
Input file   : DDoS-PSHACK_Flood_1.csv
Expected rows: 5,007,067
Input size    : 2.51 GB
Free disk     : 68.78 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 5,007,067
✅ Sorted file created.
Output size   : 0.23 GB
Time          : 6.23 minutes

==============================================================================
SORTING 10/33
Source class : DDoS-RSTFINFlood
Input file   : DDoS-RSTFINFlood.pcap_Flow.csv
Expected rows: 12,968,618
Input size    : 5.56 GB
Free disk     : 68.55 GB
Safety minimum: 17.89 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 12,968,618
✅ Sorted file created.
Output size   : 0.25 GB
Time          : 19.37 minutes

==============================================================================
SORTING 11/33
Source class : DDoS-SYN_Flood
Input file   : DDoS-SYN_Flood.pcap_Flow.csv
Expected rows: 6,366,353
Input size    : 3.05 GB
Free disk     : 68.30 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 6,366,353
✅ Sorted file created.
Output size   : 0.24 GB
Time          : 7.86 minutes

==============================================================================
SORTING 12/33
Source class : DDoS-SlowLoris
Input file   : DDoS-SlowLoris.pcap_Flow.csv
Expected rows: 196,578
Input size    : 0.11 GB
Free disk     : 68.06 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 196,578
✅ Sorted file created.
Output size   : 0.02 GB
Time          : 0.11 minutes

==============================================================================
SORTING 13/33
Source class : DDoS-SynonymousIP_Flood
Input file   : DDoS-SynonymousIP_Flood.pcap_Flow.csv
Expected rows: 799,351
Input size    : 0.41 GB
Free disk     : 68.04 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 799,351
✅ Sorted file created.
Output size   : 0.05 GB
Time          : 0.25 minutes

==============================================================================
SORTING 14/33
Source class : DDoS-TCP_Flood
Input file   : DDoS-TCP_Flood.pcap_Flow.csv
Expected rows: 4,945,887
Input size    : 2.38 GB
Free disk     : 67.99 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 4,945,887
✅ Sorted file created.
Output size   : 0.18 GB
Time          : 5.38 minutes

==============================================================================
SORTING 15/33
Source class : DDoS-UDP_Flood
Input file   : DDoS-UDP_Flood.pcap_Flow.csv
Expected rows: 41,146
Input size    : 0.02 GB
Free disk     : 67.81 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 41,146
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.03 minutes

==============================================================================
SORTING 16/33
Source class : DDoS-UDP_Fragmentation
Input file   : DDoS-UDP_Fragmentation.pcap_Flow.csv
Expected rows: 9,757
Input size    : 0.00 GB
Free disk     : 67.81 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 9,757
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 17/33
Source class : DNS_Spoofing
Input file   : DNS_Spoofing.pcap_Flow.csv
Expected rows: 74,938
Input size    : 0.04 GB
Free disk     : 67.81 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 74,938
✅ Sorted file created.
Output size   : 0.01 GB
Time          : 0.05 minutes

==============================================================================
SORTING 18/33
Source class : DictionaryBruteForce
Input file   : DictionaryBruteForce.pcap_Flow.csv
Expected rows: 8,488
Input size    : 0.00 GB
Free disk     : 67.80 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 8,488
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.02 minutes

==============================================================================
SORTING 19/33
Source class : DoS-HTTP_Flood
Input file   : DoS-HTTP_Flood.pcap_Flow.csv
Expected rows: 965,554
Input size    : 0.39 GB
Free disk     : 67.80 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 965,554
✅ Sorted file created.
Output size   : 0.04 GB
Time          : 0.36 minutes

==============================================================================
SORTING 20/33
Source class : DoS-SYN_Flood
Input file   : DoS-SYN_Flood.pcap_Flow.csv
Expected rows: 3,997,110
Input size    : 1.92 GB
Free disk     : 67.76 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 3,997,110
✅ Sorted file created.
Output size   : 0.18 GB
Time          : 2.72 minutes

==============================================================================
SORTING 21/33
Source class : DoS-TCP_Flood
Input file   : DoS-TCP_Flood.pcap_Flow.csv
Expected rows: 1,638,068
Input size    : 0.77 GB
Free disk     : 67.58 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 1,638,068
✅ Sorted file created.
Output size   : 0.07 GB
Time          : 0.70 minutes

==============================================================================
SORTING 22/33
Source class : DoS-UDP_Flood
Input file   : DoS-UDP_Flood.pcap_Flow.csv
Expected rows: 934,009
Input size    : 0.49 GB
Free disk     : 67.52 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 934,009
✅ Sorted file created.
Output size   : 0.05 GB
Time          : 0.38 minutes

==============================================================================
SORTING 23/33
Source class : MITM-ArpSpoofing
Input file   : MITM-ArpSpoofing.pcap_Flow.csv
Expected rows: 72,853
Input size    : 0.04 GB
Free disk     : 67.47 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 72,853
✅ Sorted file created.
Output size   : 0.01 GB
Time          : 0.06 minutes

==============================================================================
SORTING 24/33
Source class : Mirai-greeth_flood
Input file   : Mirai-greeth_flood.pcap_Flow.csv
Expected rows: 5,155
Input size    : 0.00 GB
Free disk     : 67.46 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 5,155
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 25/33
Source class : Mirai-greip_flood
Input file   : Mirai-greip_flood.pcap_Flow.csv
Expected rows: 10,401
Input size    : 0.01 GB
Free disk     : 67.46 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 10,401
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 26/33
Source class : Mirai-udpplain
Input file   : Mirai-udpplain.pcap_Flow.csv
Expected rows: 7,455
Input size    : 0.00 GB
Free disk     : 67.46 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 7,455
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 27/33
Source class : Recon-HostDiscovery
Input file   : Recon-HostDiscovery.pcap_Flow.csv
Expected rows: 329,985
Input size    : 0.13 GB
Free disk     : 67.46 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 329,985
✅ Sorted file created.
Output size   : 0.02 GB
Time          : 0.13 minutes

==============================================================================
SORTING 28/33
Source class : Recon-OSScan
Input file   : Recon-OSScan.pcap_Flow.csv
Expected rows: 158,682
Input size    : 0.07 GB
Free disk     : 67.44 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 158,682
✅ Sorted file created.
Output size   : 0.01 GB
Time          : 0.09 minutes

==============================================================================
SORTING 29/33
Source class : Recon-PingSweep
Input file   : Recon-PingSweep.pcap_Flow.csv
Expected rows: 1,947
Input size    : 0.00 GB
Free disk     : 67.43 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 1,947
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 30/33
Source class : Recon-PortScan
Input file   : Recon-PortScan.pcap_Flow.csv
Expected rows: 175,050
Input size    : 0.07 GB
Free disk     : 67.43 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 175,050
✅ Sorted file created.
Output size   : 0.01 GB
Time          : 0.07 minutes

==============================================================================
SORTING 31/33
Source class : SqlInjection
Input file   : SqlInjection.pcap_Flow.csv
Expected rows: 6,596
Input size    : 0.00 GB
Free disk     : 67.42 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 6,596
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
SORTING 32/33
Source class : VulnerabilityScan
Input file   : VulnerabilityScan.pcap_Flow.csv
Expected rows: 442,122
Input size    : 0.21 GB
Free disk     : 67.42 GB
Safety minimum: 12.00 GB
Sorting...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows   : 442,122
✅ Sorted file created.
Output size   : 0.04 GB
Time          : 0.22 minutes

==============================================================================
SORTING 33/33
Source class : XSS
Input file   : XSS.pcap_Flow.csv
Expected rows: 3,198
Input size    : 0.00 GB
Free disk     : 67.38 GB
Safety minimum: 12.00 GB
Sorting...
Sorted rows   : 3,198
✅ Sorted file created.
Output size   : 0.00 GB
Time          : 0.01 minutes

==============================================================================
[7] Building chronological dataset variables
------------------------------------------------------------------------------
Sorted files: 33

[8] Row-count conservation
------------------------------------------------------------------------------
Original rows: 39,851,619
Sorted rows  : 39,851,619
Totals match : True

[9] Chronological dataset summary
------------------------------------------------------------------------------
Sorted source files : 33
Sorted total rows   : 39,851,619
Sorted dataset size : 1.46 GB
Free disk remaining : 67.38 GB
Original CSV changed: False

==============================================================================
✅ STEP 8.3 PASSED — Chronologically sorted dataset derivatives were created.
Next step: verify chronological ordering before constructing LOAFO partitions.
==============================================================================

# STEP 8.4 — Verify the Sorted Files Are Truly Chronological

In [ ]:
# ======================================================================
# STEP 8.4 — VERIFY CHRONOLOGICAL PARQUET DATASET
# ======================================================================

from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

print("=" * 78)
print("STEP 8.4 — VERIFY CHRONOLOGICAL PARQUET DATASET")
print("=" * 78)


# ======================================================================
# 8.4.1 — VERIFY REQUIRED VARIABLES
# ======================================================================

print("\n[1] Verifying Step 8.3 variables")
print("-" * 78)

required_variables = [

    "SORTED_DATA_FILES",
    "SORTED_FILE_BY_SOURCE_CLASS",
    "SOURCE_CLASS_TO_ROW_COUNT",
    "TOTAL_ROWS",
    "TIMESTAMP_FORMAT",
    "DIRECTORIES"
]


missing_variables = [

    variable

    for variable
    in required_variables

    if variable
    not in globals()
]


if missing_variables:

    raise RuntimeError(

        "Missing variables: "

        + ", ".join(
            missing_variables
        )

        + "\nPlease rerun Step 8.3."
    )


print(
    "Sorted files :",
    len(SORTED_DATA_FILES)
)

print(
    "Expected rows:",
    f"{TOTAL_ROWS:,}"
)

print(
    "Timestamp format:",
    TIMESTAMP_FORMAT
)


# ======================================================================
# 8.4.2 — OUTPUT PATH
# ======================================================================

CHRONOLOGICAL_VERIFICATION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_chronological_verification.csv"
)


# ======================================================================
# 8.4.3 — VERIFY EVERY PARQUET FILE
# ======================================================================

print("\n[2] Verifying chronological ordering")
print("-" * 78)

print(
    "Only the Timestamp column will be scanned."
)

print(
    "This should be much faster than scanning the original CSV files."
)


VERIFY_BATCH_SIZE = 250_000


verification_records = []


for file_number, source_class in enumerate(

    SORTED_FILE_BY_SOURCE_CLASS.keys(),

    start=1
):

    parquet_path = (

        SORTED_FILE_BY_SOURCE_CLASS[
            source_class
        ]
    )


    expected_rows = int(

        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    print("\n" + "-" * 78)

    print(
        f"Checking {file_number:02d}/{len(SORTED_DATA_FILES)}"
    )

    print(
        "Source class:",
        source_class
    )

    print(
        "File        :",
        parquet_path.name
    )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    metadata_rows = int(

        parquet_file.metadata.num_rows
    )


    rows_checked = 0

    missing_timestamps = 0

    invalid_timestamps = 0

    backward_transitions = 0


    previous_last_timestamp_ns = None

    earliest_timestamp = None

    latest_timestamp = None


    for batch in parquet_file.iter_batches(

        columns=[
            "Timestamp"
        ],

        batch_size=VERIFY_BATCH_SIZE
    ):

        timestamp_series = (

            batch
            .column(0)
            .to_pandas()
        )


        timestamp_text = (

            timestamp_series

            .astype("string")

            .str.strip()
        )


        missing_mask = (

            timestamp_series.isna()

            |

            timestamp_text.eq("")
        )


        parsed_timestamp = pd.to_datetime(

            timestamp_series,

            format=TIMESTAMP_FORMAT,

            errors="coerce"
        )


        invalid_mask = (

            parsed_timestamp.isna()

            &

            ~missing_mask
        )


        missing_timestamps += int(

            missing_mask.sum()
        )


        invalid_timestamps += int(

            invalid_mask.sum()
        )


        valid_timestamp = (

            parsed_timestamp.dropna()
        )


        if not valid_timestamp.empty:

            timestamp_ns = (

                valid_timestamp

                .astype("int64")

                .to_numpy()
            )


            # ----------------------------------------------------------
            # Check transition between batches
            # ----------------------------------------------------------

            if (

                previous_last_timestamp_ns
                is not None

                and

                timestamp_ns[0]
                <
                previous_last_timestamp_ns
            ):

                backward_transitions += 1


            # ----------------------------------------------------------
            # Check order inside current batch
            # ----------------------------------------------------------

            if len(
                timestamp_ns
            ) > 1:

                backward_transitions += int(

                    np.count_nonzero(

                        timestamp_ns[1:]

                        <

                        timestamp_ns[:-1]
                    )
                )


            previous_last_timestamp_ns = int(

                timestamp_ns[-1]
            )


            batch_min = (

                valid_timestamp.min()
            )


            batch_max = (

                valid_timestamp.max()
            )


            if (

                earliest_timestamp is None

                or

                batch_min
                <
                earliest_timestamp
            ):

                earliest_timestamp = (
                    batch_min
                )


            if (

                latest_timestamp is None

                or

                batch_max
                >
                latest_timestamp
            ):

                latest_timestamp = (
                    batch_max
                )


        rows_checked += len(
            timestamp_series
        )


    # ==================================================================
    # FILE VALIDATION
    # ==================================================================

    row_count_match = (

        rows_checked
        ==
        expected_rows
        ==
        metadata_rows
    )


    chronological = (

        backward_transitions == 0

        and

        missing_timestamps == 0

        and

        invalid_timestamps == 0
    )


    status = (

        "PASS"

        if (
            row_count_match
            and
            chronological
        )

        else "FAIL"
    )


    verification_records.append({

        "source_attack_class":
            source_class,

        "parquet_file":
            str(
                parquet_path
            ),

        "expected_rows":
            expected_rows,

        "metadata_rows":
            metadata_rows,

        "rows_checked":
            rows_checked,

        "row_count_match":
            row_count_match,

        "missing_timestamps":
            missing_timestamps,

        "invalid_timestamps":
            invalid_timestamps,

        "backward_transitions":
            backward_transitions,

        "chronological":
            chronological,

        "earliest_timestamp":
            str(
                earliest_timestamp
            ),

        "latest_timestamp":
            str(
                latest_timestamp
            ),

        "status":
            status
    })


    print(
        "Rows checked        :",
        f"{rows_checked:,}"
    )

    print(
        "Backward transitions:",
        f"{backward_transitions:,}"
    )

    print(
        "Chronological       :",
        chronological
    )

    print(
        "Status              :",
        status
    )


# ======================================================================
# 8.4.4 — BUILD VERIFICATION TABLE
# ======================================================================

chronological_verification = pd.DataFrame(

    verification_records
)


chronological_verification.to_csv(

    CHRONOLOGICAL_VERIFICATION_PATH,

    index=False
)


# ======================================================================
# 8.4.5 — OVERALL SUMMARY
# ======================================================================

print("\n[3] Chronological verification summary")
print("-" * 78)


FILES_CHECKED = len(
    chronological_verification
)


FILES_PASSED = int(

    (
        chronological_verification[
            "status"
        ]
        ==
        "PASS"
    ).sum()
)


FILES_FAILED = int(

    (
        chronological_verification[
            "status"
        ]
        ==
        "FAIL"
    ).sum()
)


TOTAL_VERIFIED_ROWS = int(

    chronological_verification[
        "rows_checked"
    ].sum()
)


TOTAL_BACKWARD_TRANSITIONS_SORTED = int(

    chronological_verification[
        "backward_transitions"
    ].sum()
)


TOTAL_SORTED_MISSING_TIMESTAMPS = int(

    chronological_verification[
        "missing_timestamps"
    ].sum()
)


TOTAL_SORTED_INVALID_TIMESTAMPS = int(

    chronological_verification[
        "invalid_timestamps"
    ].sum()
)


print(
    "Files checked        :",
    FILES_CHECKED
)

print(
    "Files passed         :",
    FILES_PASSED
)

print(
    "Files failed         :",
    FILES_FAILED
)

print(
    "Rows verified        :",
    f"{TOTAL_VERIFIED_ROWS:,}"
)

print(
    "Expected total rows  :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Backward transitions :",
    f"{TOTAL_BACKWARD_TRANSITIONS_SORTED:,}"
)

print(
    "Missing timestamps   :",
    f"{TOTAL_SORTED_MISSING_TIMESTAMPS:,}"
)

print(
    "Invalid timestamps   :",
    f"{TOTAL_SORTED_INVALID_TIMESTAMPS:,}"
)


# ======================================================================
# 8.4.6 — SHOW FAILURES IF ANY
# ======================================================================

if FILES_FAILED > 0:

    print(
        "\nFiles requiring review:"
    )

    display(

        chronological_verification[

            chronological_verification[
                "status"
            ]
            ==
            "FAIL"
        ]
    )


# ======================================================================
# 8.4.7 — FINAL VALIDATION
# ======================================================================

TOTAL_ROWS_MATCH = (

    TOTAL_VERIFIED_ROWS
    ==
    TOTAL_ROWS
)


STEP_8_4_VALID = (

    FILES_CHECKED == 33

    and

    FILES_PASSED == 33

    and

    FILES_FAILED == 0

    and

    TOTAL_ROWS_MATCH

    and

    TOTAL_BACKWARD_TRANSITIONS_SORTED == 0

    and

    TOTAL_SORTED_MISSING_TIMESTAMPS == 0

    and

    TOTAL_SORTED_INVALID_TIMESTAMPS == 0

    and

    CHRONOLOGICAL_VERIFICATION_PATH.exists()
)


print("\n[4] Final validation")
print("-" * 78)

print(
    "All 33 files chronological:",
    FILES_PASSED == 33
)

print(
    "Row totals match           :",
    TOTAL_ROWS_MATCH
)

print(
    "Backward transitions zero  :",
    TOTAL_BACKWARD_TRANSITIONS_SORTED == 0
)

print(
    "Timestamp errors zero      :",
    (
        TOTAL_SORTED_MISSING_TIMESTAMPS == 0
        and
        TOTAL_SORTED_INVALID_TIMESTAMPS == 0
    )
)


print("\n" + "=" * 78)


if STEP_8_4_VALID:

    print(
        "✅ STEP 8.4 PASSED — "
        "All 33 chronological dataset files are verified."
    )

else:

    print(
        "❌ STEP 8.4 FAILED — "
        "Do not construct LOAFO partitions yet."
    )


print("=" * 78)

==============================================================================
STEP 8.4 — VERIFY CHRONOLOGICAL PARQUET DATASET
==============================================================================

[1] Verifying Step 8.3 variables
------------------------------------------------------------------------------
Sorted files : 33
Expected rows: 39,851,619
Timestamp format: %d/%m/%Y %I:%M:%S %p

[2] Verifying chronological ordering
------------------------------------------------------------------------------
Only the Timestamp column will be scanned.
This should be much faster than scanning the original CSV files.

------------------------------------------------------------------------------
Checking 01/33
Source class: Backdoor_Malware
File        : Backdoor_Malware.parquet
Rows checked        : 2,703
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 02/33
Source class: Benign_Final
File        : Benign_Final.parquet
Rows checked        : 91,506
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 03/33
Source class: BrowserHijacking
File        : BrowserHijacking.parquet
Rows checked        : 3,286
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 04/33
Source class: CommandInjection
File        : CommandInjection.parquet
Rows checked        : 3,848
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 05/33
Source class: DDoS-ACK_Fragmentation
File        : DDoS-ACK_Fragmentation.parquet
Rows checked        : 37,296
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 06/33
Source class: DDoS-HTTP_Flood
File        : DDoS-HTTP_Flood.parquet
Rows checked        : 513,672
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 07/33
Source class: DDoS-ICMP_Flood
File        : DDoS-ICMP_Flood.parquet
Rows checked        : 7,834
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 08/33
Source class: DDoS-ICMP_Fragmentation
File        : DDoS-ICMP_Fragmentation.parquet
Rows checked        : 25,106
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 09/33
Source class: DDoS-PSHACK_Flood
File        : DDoS-PSHACK_Flood.parquet
Rows checked        : 5,007,067
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 10/33
Source class: DDoS-RSTFINFlood
File        : DDoS-RSTFINFlood.parquet
Rows checked        : 12,968,618
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 11/33
Source class: DDoS-SYN_Flood
File        : DDoS-SYN_Flood.parquet
Rows checked        : 6,366,353
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 12/33
Source class: DDoS-SlowLoris
File        : DDoS-SlowLoris.parquet
Rows checked        : 196,578
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 13/33
Source class: DDoS-SynonymousIP_Flood
File        : DDoS-SynonymousIP_Flood.parquet
Rows checked        : 799,351
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 14/33
Source class: DDoS-TCP_Flood
File        : DDoS-TCP_Flood.parquet
Rows checked        : 4,945,887
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 15/33
Source class: DDoS-UDP_Flood
File        : DDoS-UDP_Flood.parquet
Rows checked        : 41,146
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 16/33
Source class: DDoS-UDP_Fragmentation
File        : DDoS-UDP_Fragmentation.parquet
Rows checked        : 9,757
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 17/33
Source class: DNS_Spoofing
File        : DNS_Spoofing.parquet
Rows checked        : 74,938
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 18/33
Source class: DictionaryBruteForce
File        : DictionaryBruteForce.parquet
Rows checked        : 8,488
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 19/33
Source class: DoS-HTTP_Flood
File        : DoS-HTTP_Flood.parquet
Rows checked        : 965,554
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 20/33
Source class: DoS-SYN_Flood
File        : DoS-SYN_Flood.parquet
Rows checked        : 3,997,110
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 21/33
Source class: DoS-TCP_Flood
File        : DoS-TCP_Flood.parquet
Rows checked        : 1,638,068
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 22/33
Source class: DoS-UDP_Flood
File        : DoS-UDP_Flood.parquet
Rows checked        : 934,009
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 23/33
Source class: MITM-ArpSpoofing
File        : MITM-ArpSpoofing.parquet
Rows checked        : 72,853
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 24/33
Source class: Mirai-greeth_flood
File        : Mirai-greeth_flood.parquet
Rows checked        : 5,155
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 25/33
Source class: Mirai-greip_flood
File        : Mirai-greip_flood.parquet
Rows checked        : 10,401
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 26/33
Source class: Mirai-udpplain
File        : Mirai-udpplain.parquet
Rows checked        : 7,455
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 27/33
Source class: Recon-HostDiscovery
File        : Recon-HostDiscovery.parquet
Rows checked        : 329,985
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 28/33
Source class: Recon-OSScan
File        : Recon-OSScan.parquet
Rows checked        : 158,682
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 29/33
Source class: Recon-PingSweep
File        : Recon-PingSweep.parquet
Rows checked        : 1,947
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 30/33
Source class: Recon-PortScan
File        : Recon-PortScan.parquet
Rows checked        : 175,050
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 31/33
Source class: SqlInjection
File        : SqlInjection.parquet
Rows checked        : 6,596
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 32/33
Source class: VulnerabilityScan
File        : VulnerabilityScan.parquet
Rows checked        : 442,122
Backward transitions: 0
Chronological       : True
Status              : PASS

------------------------------------------------------------------------------
Checking 33/33
Source class: XSS
File        : XSS.parquet
Rows checked        : 3,198
Backward transitions: 0
Chronological       : True
Status              : PASS

[3] Chronological verification summary
------------------------------------------------------------------------------
Files checked        : 33
Files passed         : 33
Files failed         : 0
Rows verified        : 39,851,619
Expected total rows  : 39,851,619
Backward transitions : 0
Missing timestamps   : 0
Invalid timestamps   : 0

[4] Final validation
------------------------------------------------------------------------------
All 33 files chronological: True
Row totals match           : True
Backward transitions zero  : True
Timestamp errors zero      : True

==============================================================================
✅ STEP 8.4 PASSED — All 33 chronological dataset files are verified.
==============================================================================

# STEP 8.5 — Build the 7 Strict LOAFO Fold Manifests
# 8.5 Strict Seven-Fold LOAFO Partition Construction

The timestamp-preserving CICIoT2023 coverage subset has now been sorted and independently verified to be chronological.

This section constructs the final Leave-One-Attack-Family-Out (LOAFO) data partitions.

For each of the seven folds:

- One complete attack family is reserved as the unseen zero-day family.
- The held-out family contributes no records to training or validation.
- Known attack-family source files are divided chronologically into:
  - 70% development training
  - 15% development validation
  - 15% known-family testing
- Benign traffic is divided chronologically using the same 70/15/15 rule.
- The complete held-out attack family is used only for zero-day testing.

No physical dataset duplication is performed.

Instead, each partition is represented by a row range within the verified chronological Parquet files.

This preserves temporal order while avoiding unnecessary storage duplication.

The following integrity conditions are enforced:

1. Every source file is represented exactly once per fold when its row ranges are combined.
2. No row ranges overlap.
3. No gaps occur between partitions.
4. Every fold conserves all 39,851,619 records.
5. The held-out attack family has zero development records.
6. One hundred percent of the held-out family is reserved for zero-day testing.
7. Benign training, validation, and testing ranges are disjoint.
8. Preprocessing fitting will later use only the development-training partition.

In [ ]:
# ======================================================================
# STEP 8.5 — STRICT SEVEN-FOLD LOAFO PARTITION MANIFESTS
# ======================================================================

from pathlib import Path
import json

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

print("=" * 78)
print("STEP 8.5 — STRICT SEVEN-FOLD LOAFO PARTITION CONSTRUCTION")
print("=" * 78)


# ======================================================================
# 8.5.1 — VERIFY PREVIOUS STEP
# ======================================================================

print("\n[1] Verifying chronological dataset")
print("-" * 78)

required_variables = [

    "SORTED_DATA_FILES",
    "SORTED_FILE_BY_SOURCE_CLASS",
    "SOURCE_CLASS_TO_ROW_COUNT",
    "SOURCE_CLASS_TO_FAMILY",
    "ATTACK_FAMILIES",
    "TOTAL_ROWS",
    "DIRECTORIES",
    "RANDOM_SEEDS",
    "STEP_8_4_VALID"
]


missing_variables = [

    variable

    for variable in required_variables

    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun the required previous cells."
    )


if not STEP_8_4_VALID:

    raise RuntimeError(
        "Step 8.4 did not pass. "
        "LOAFO partitions must not be created."
    )


print(
    "Chronological files:",
    len(SORTED_DATA_FILES)
)

print(
    "Verified rows       :",
    f"{TOTAL_ROWS:,}"
)

print(
    "LOAFO families      :",
    len(ATTACK_FAMILIES)
)

print(
    "✅ Chronological dataset is ready."
)


# ======================================================================
# 8.5.2 — PARTITION CONFIGURATION
# ======================================================================

print("\n[2] Partition policy")
print("-" * 78)


TRAIN_RATIO = 0.70

VALIDATION_RATIO = 0.15

TEST_RATIO = 0.15


if not np.isclose(

    TRAIN_RATIO
    +
    VALIDATION_RATIO
    +
    TEST_RATIO,

    1.0
):

    raise RuntimeError(
        "Split ratios must sum to 1.0."
    )


print(
    "Development train      :",
    f"{TRAIN_RATIO:.0%}"
)

print(
    "Development validation :",
    f"{VALIDATION_RATIO:.0%}"
)

print(
    "Known/benign test      :",
    f"{TEST_RATIO:.0%}"
)

print(
    "Held-out attack family : 100% zero-day test"
)


# ======================================================================
# 8.5.3 — OUTPUT LOCATIONS
# ======================================================================

LOAFO_DIR = (

    DIRECTORIES["processed_data"]

    / "loafo_manifests"
)


LOAFO_DIR.mkdir(

    parents=True,

    exist_ok=True
)


LOAFO_SPLIT_MANIFEST_PATH = (

    LOAFO_DIR

    / "CICIoT2023_LOAFO_split_manifest.csv"
)


LOAFO_FOLD_SUMMARY_PATH = (

    LOAFO_DIR

    / "CICIoT2023_LOAFO_fold_summary.csv"
)


LOAFO_RANGE_CHECK_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_LOAFO_range_integrity.csv"
)


LOAFO_INTEGRITY_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_LOAFO_integrity_checks.csv"
)


LOAFO_POLICY_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_LOAFO_policy.json"
)


# ======================================================================
# 8.5.4 — VERIFY SORTED PARQUET ROW COUNTS AGAIN
# ======================================================================

print("\n[3] Verifying source-class row counts")
print("-" * 78)


for source_class, parquet_path in (
    SORTED_FILE_BY_SOURCE_CLASS.items()
):

    expected_rows = int(

        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    actual_rows = int(

        pq.ParquetFile(
            parquet_path
        )
        .metadata
        .num_rows
    )


    if actual_rows != expected_rows:

        raise RuntimeError(

            f"Row-count mismatch for {source_class}: "
            f"expected {expected_rows:,}, "
            f"found {actual_rows:,}."
        )


print(
    "✅ All 33 sorted source files match "
    "their verified row counts."
)


# ======================================================================
# 8.5.5 — CHRONOLOGICAL SPLIT FUNCTION
# ======================================================================

def chronological_split(
    total_rows
):

    train_rows = int(
        np.floor(
            total_rows
            *
            TRAIN_RATIO
        )
    )


    validation_rows = int(
        np.floor(
            total_rows
            *
            VALIDATION_RATIO
        )
    )


    test_rows = (

        total_rows

        -

        train_rows

        -

        validation_rows
    )


    train_start = 0

    train_end = train_rows


    validation_start = train_end

    validation_end = (

        validation_start

        +

        validation_rows
    )


    test_start = validation_end

    test_end = total_rows


    return {

        "development_train": {

            "start":
                train_start,

            "end":
                train_end,

            "rows":
                train_rows
        },


        "development_validation": {

            "start":
                validation_start,

            "end":
                validation_end,

            "rows":
                validation_rows
        },


        "test": {

            "start":
                test_start,

            "end":
                test_end,

            "rows":
                test_rows
        }
    }


# ======================================================================
# 8.5.6 — PERMISSION POLICY
# ======================================================================

PARTITION_PERMISSIONS = {

    "development_train": {

        "preprocessing_fit":
            True,

        "ssl_pretraining":
            True,

        "supervised_training":
            True,

        "validation_tuning":
            False,

        "final_evaluation_only":
            False
    },


    "development_validation": {

        "preprocessing_fit":
            False,

        "ssl_pretraining":
            False,

        "supervised_training":
            False,

        "validation_tuning":
            True,

        "final_evaluation_only":
            False
    },


    "known_test": {

        "preprocessing_fit":
            False,

        "ssl_pretraining":
            False,

        "supervised_training":
            False,

        "validation_tuning":
            False,

        "final_evaluation_only":
            True
    },


    "zero_day_attack_test": {

        "preprocessing_fit":
            False,

        "ssl_pretraining":
            False,

        "supervised_training":
            False,

        "validation_tuning":
            False,

        "final_evaluation_only":
            True
    },


    "benign_test": {

        "preprocessing_fit":
            False,

        "ssl_pretraining":
            False,

        "supervised_training":
            False,

        "validation_tuning":
            False,

        "final_evaluation_only":
            True
    }
}


# ======================================================================
# 8.5.7 — MANIFEST RECORD HELPER
# ======================================================================

def make_manifest_record(
    fold_number,
    held_out_family,
    source_class,
    research_family,
    partition,
    start_row,
    end_row,
    total_source_rows
):

    parquet_path = (

        SORTED_FILE_BY_SOURCE_CLASS[
            source_class
        ]
    )


    binary_target = (

        0

        if research_family
        ==
        "Benign"

        else 1
    )


    permissions = (

        PARTITION_PERMISSIONS[
            partition
        ]
    )


    rows = (

        end_row

        -

        start_row
    )


    return {

        "fold_number":
            int(
                fold_number
            ),

        "held_out_family":
            held_out_family,

        "source_attack_class":
            source_class,

        "research_family":
            research_family,

        "binary_target":
            binary_target,

        "partition":
            partition,

        "parquet_path":
            str(
                Path(
                    parquet_path
                ).resolve()
            ),

        "start_row":
            int(
                start_row
            ),

        "end_row_exclusive":
            int(
                end_row
            ),

        "rows":
            int(
                rows
            ),

        "source_total_rows":
            int(
                total_source_rows
            ),

        "is_held_out_family":
            bool(
                research_family
                ==
                held_out_family
            ),

        "is_benign":
            bool(
                research_family
                ==
                "Benign"
            ),

        "allowed_preprocessing_fit":
            permissions[
                "preprocessing_fit"
            ],

        "allowed_ssl_pretraining":
            permissions[
                "ssl_pretraining"
            ],

        "allowed_supervised_training":
            permissions[
                "supervised_training"
            ],

        "allowed_validation_tuning":
            permissions[
                "validation_tuning"
            ],

        "final_evaluation_only":
            permissions[
                "final_evaluation_only"
            ]
    }


# ======================================================================
# 8.5.8 — CONSTRUCT ALL SEVEN FOLDS
# ======================================================================

print("\n[4] Constructing seven LOAFO folds")
print("-" * 78)


LOAFO_FAMILIES = list(
    ATTACK_FAMILIES
)


manifest_records = []


for fold_number, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    print(
        f"Fold {fold_number}: "
        f"{held_out_family} held out"
    )


    for source_class, parquet_path in (
        SORTED_FILE_BY_SOURCE_CLASS.items()
    ):

        research_family = (

            SOURCE_CLASS_TO_FAMILY[
                source_class
            ]
        )


        source_rows = int(

            SOURCE_CLASS_TO_ROW_COUNT[
                source_class
            ]
        )


        # ==============================================================
        # HELD-OUT ATTACK FAMILY
        # ==============================================================

        if (
            research_family
            ==
            held_out_family
        ):

            manifest_records.append(

                make_manifest_record(

                    fold_number=
                        fold_number,

                    held_out_family=
                        held_out_family,

                    source_class=
                        source_class,

                    research_family=
                        research_family,

                    partition=
                        "zero_day_attack_test",

                    start_row=
                        0,

                    end_row=
                        source_rows,

                    total_source_rows=
                        source_rows
                )
            )


        # ==============================================================
        # BENIGN SOURCE FILE
        # ==============================================================

        elif (
            research_family
            ==
            "Benign"
        ):

            splits = (
                chronological_split(
                    source_rows
                )
            )


            train = splits[
                "development_train"
            ]

            validation = splits[
                "development_validation"
            ]

            test = splits[
                "test"
            ]


            manifest_records.append(

                make_manifest_record(

                    fold_number,
                    held_out_family,
                    source_class,
                    research_family,
                    "development_train",
                    train["start"],
                    train["end"],
                    source_rows
                )
            )


            manifest_records.append(

                make_manifest_record(

                    fold_number,
                    held_out_family,
                    source_class,
                    research_family,
                    "development_validation",
                    validation["start"],
                    validation["end"],
                    source_rows
                )
            )


            manifest_records.append(

                make_manifest_record(

                    fold_number,
                    held_out_family,
                    source_class,
                    research_family,
                    "benign_test",
                    test["start"],
                    test["end"],
                    source_rows
                )
            )


        # ==============================================================
        # KNOWN ATTACK FAMILY
        # ==============================================================

        else:

            splits = (
                chronological_split(
                    source_rows
                )
            )


            train = splits[
                "development_train"
            ]

            validation = splits[
                "development_validation"
            ]

            test = splits[
                "test"
            ]


            manifest_records.append(

                make_manifest_record(

                    fold_number,
                    held_out_family,
                    source_class,
                    research_family,
                    "development_train",
                    train["start"],
                    train["end"],
                    source_rows
                )
            )


            manifest_records.append(

                make_manifest_record(

                    fold_number,
                    held_out_family,
                    source_class,
                    research_family,
                    "development_validation",
                    validation["start"],
                    validation["end"],
                    source_rows
                )
            )


            manifest_records.append(

                make_manifest_record(

                    fold_number,
                    held_out_family,
                    source_class,
                    research_family,
                    "known_test",
                    test["start"],
                    test["end"],
                    source_rows
                )
            )


# ======================================================================
# 8.5.9 — CREATE MASTER MANIFEST
# ======================================================================

LOAFO_SPLIT_MANIFEST = pd.DataFrame(
    manifest_records
)


LOAFO_SPLIT_MANIFEST[
    "partition_id"
] = (

    "fold_"

    +

    LOAFO_SPLIT_MANIFEST[
        "fold_number"
    ]
    .astype(str)
    .str.zfill(2)

    +

    "__"

    +

    LOAFO_SPLIT_MANIFEST[
        "source_attack_class"
    ]
    .astype(str)

    +

    "__"

    +

    LOAFO_SPLIT_MANIFEST[
        "partition"
    ]
    .astype(str)
)


LOAFO_SPLIT_MANIFEST.to_csv(

    LOAFO_SPLIT_MANIFEST_PATH,

    index=False
)


print(
    "\nManifest records:",
    len(
        LOAFO_SPLIT_MANIFEST
    )
)

print(
    "Manifest saved:"
)

print(
    LOAFO_SPLIT_MANIFEST_PATH
)


# ======================================================================
# 8.5.10 — RANGE INTEGRITY CHECK
# ======================================================================

print("\n[5] Checking row-range coverage and overlap")
print("-" * 78)


range_check_records = []


for fold_number in range(
    1,
    len(LOAFO_FAMILIES) + 1
):

    fold_data = (

        LOAFO_SPLIT_MANIFEST[

            LOAFO_SPLIT_MANIFEST[
                "fold_number"
            ]
            ==
            fold_number

        ]
    )


    for source_class in (
        SORTED_FILE_BY_SOURCE_CLASS.keys()
    ):

        source_data = (

            fold_data[

                fold_data[
                    "source_attack_class"
                ]
                ==
                source_class

            ]

            .sort_values(
                "start_row"
            )
        )


        expected_rows = int(

            SOURCE_CLASS_TO_ROW_COUNT[
                source_class
            ]
        )


        starts = (

            source_data[
                "start_row"
            ]
            .astype(int)
            .tolist()
        )


        ends = (

            source_data[
                "end_row_exclusive"
            ]
            .astype(int)
            .tolist()
        )


        recorded_rows = int(

            source_data[
                "rows"
            ].sum()
        )


        starts_at_zero = (

            len(starts) > 0

            and

            starts[0] == 0
        )


        ends_at_total = (

            len(ends) > 0

            and

            ends[-1]
            ==
            expected_rows
        )


        contiguous = True


        if len(starts) > 1:

            for index in range(
                1,
                len(starts)
            ):

                if (
                    starts[index]
                    !=
                    ends[index - 1]
                ):

                    contiguous = False

                    break


        positive_ranges = bool(

            (
                source_data[
                    "rows"
                ]
                >
                0
            ).all()
        )


        row_total_match = (

            recorded_rows
            ==
            expected_rows
        )


        valid = (

            starts_at_zero

            and

            ends_at_total

            and

            contiguous

            and

            positive_ranges

            and

            row_total_match
        )


        range_check_records.append({

            "fold_number":
                fold_number,

            "held_out_family":
                LOAFO_FAMILIES[
                    fold_number - 1
                ],

            "source_attack_class":
                source_class,

            "research_family":
                SOURCE_CLASS_TO_FAMILY[
                    source_class
                ],

            "number_of_ranges":
                len(
                    source_data
                ),

            "expected_rows":
                expected_rows,

            "recorded_rows":
                recorded_rows,

            "starts_at_zero":
                starts_at_zero,

            "ends_at_total":
                ends_at_total,

            "contiguous_no_gap_or_overlap":
                contiguous,

            "positive_ranges":
                positive_ranges,

            "row_total_match":
                row_total_match,

            "range_valid":
                valid
        })


LOAFO_RANGE_CHECKS = pd.DataFrame(
    range_check_records
)


LOAFO_RANGE_CHECKS.to_csv(

    LOAFO_RANGE_CHECK_PATH,

    index=False
)


INVALID_RANGE_COUNT = int(

    (
        ~LOAFO_RANGE_CHECKS[
            "range_valid"
        ]
    ).sum()
)


print(
    "Source-file/fold checks:",
    len(
        LOAFO_RANGE_CHECKS
    )
)

print(
    "Invalid range checks    :",
    INVALID_RANGE_COUNT
)


# ======================================================================
# 8.5.11 — BUILD FOLD SUMMARY
# ======================================================================

print("\n[6] Building LOAFO fold summary")
print("-" * 78)


fold_summary_records = []


for fold_number, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold_data = (

        LOAFO_SPLIT_MANIFEST[

            LOAFO_SPLIT_MANIFEST[
                "fold_number"
            ]
            ==
            fold_number

        ]
    )


    def get_partition_rows(
        partition_name
    ):

        return int(

            fold_data.loc[

                fold_data[
                    "partition"
                ]
                ==
                partition_name,

                "rows"

            ].sum()
        )


    train_rows = (
        get_partition_rows(
            "development_train"
        )
    )


    validation_rows = (
        get_partition_rows(
            "development_validation"
        )
    )


    known_test_attack_rows = (
        get_partition_rows(
            "known_test"
        )
    )


    zero_day_attack_rows = (
        get_partition_rows(
            "zero_day_attack_test"
        )
    )


    benign_test_rows = (
        get_partition_rows(
            "benign_test"
        )
    )


    known_evaluation_rows = (

        known_test_attack_rows

        +

        benign_test_rows
    )


    zero_day_evaluation_rows = (

        zero_day_attack_rows

        +

        benign_test_rows
    )


    fold_total_rows = int(

        fold_data[
            "rows"
        ].sum()
    )


    fold_summary_records.append({

        "fold_number":
            fold_number,

        "held_out_family":
            held_out_family,

        "development_train_rows":
            train_rows,

        "development_validation_rows":
            validation_rows,

        "known_test_attack_rows":
            known_test_attack_rows,

        "zero_day_attack_rows":
            zero_day_attack_rows,

        "benign_test_rows":
            benign_test_rows,

        "known_evaluation_rows":
            known_evaluation_rows,

        "zero_day_evaluation_rows":
            zero_day_evaluation_rows,

        "fold_total_rows":
            fold_total_rows
    })


LOAFO_FOLD_SUMMARY = pd.DataFrame(
    fold_summary_records
)


LOAFO_FOLD_SUMMARY.to_csv(

    LOAFO_FOLD_SUMMARY_PATH,

    index=False
)


display(
    LOAFO_FOLD_SUMMARY
)


# ======================================================================
# 8.5.12 — STRICT FAMILY-ISOLATION CHECKS
# ======================================================================

print("\n[7] Running strict zero-day leakage checks")
print("-" * 78)


integrity_records = []


for fold_number, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold_data = (

        LOAFO_SPLIT_MANIFEST[

            LOAFO_SPLIT_MANIFEST[
                "fold_number"
            ]
            ==
            fold_number

        ]
    )


    # ------------------------------------------------------------------
    # HELD-OUT FAMILY IN DEVELOPMENT?
    # ------------------------------------------------------------------

    forbidden_partitions = [

        "development_train",
        "development_validation",
        "known_test"
    ]


    held_out_development_rows = int(

        fold_data.loc[

            (
                fold_data[
                    "research_family"
                ]
                ==
                held_out_family
            )

            &

            (
                fold_data[
                    "partition"
                ]
                .isin(
                    forbidden_partitions
                )
            ),

            "rows"

        ].sum()
    )


    # ------------------------------------------------------------------
    # COMPLETE HELD-OUT FAMILY?
    # ------------------------------------------------------------------

    expected_zero_day_rows = int(

        sum(

            SOURCE_CLASS_TO_ROW_COUNT[
                source_class
            ]

            for source_class, family
            in SOURCE_CLASS_TO_FAMILY.items()

            if family
            ==
            held_out_family
        )
    )


    actual_zero_day_rows = int(

        fold_data.loc[

            fold_data[
                "partition"
            ]
            ==
            "zero_day_attack_test",

            "rows"

        ].sum()
    )


    # ------------------------------------------------------------------
    # BENIGN PARTITIONS
    # ------------------------------------------------------------------

    benign_train_rows = int(

        fold_data.loc[

            (
                fold_data[
                    "research_family"
                ]
                ==
                "Benign"
            )

            &

            (
                fold_data[
                    "partition"
                ]
                ==
                "development_train"
            ),

            "rows"

        ].sum()
    )


    benign_validation_rows = int(

        fold_data.loc[

            (
                fold_data[
                    "research_family"
                ]
                ==
                "Benign"
            )

            &

            (
                fold_data[
                    "partition"
                ]
                ==
                "development_validation"
            ),

            "rows"

        ].sum()
    )


    benign_test_rows = int(

        fold_data.loc[

            fold_data[
                "partition"
            ]
            ==
            "benign_test",

            "rows"

        ].sum()
    )


    fold_total_rows = int(

        fold_data[
            "rows"
        ].sum()
    )


    # ------------------------------------------------------------------
    # PERMISSIONS
    # ------------------------------------------------------------------

    held_out_permission_violations = int(

        fold_data.loc[

            fold_data[
                "research_family"
            ]
            ==
            held_out_family,

            [
                "allowed_preprocessing_fit",
                "allowed_ssl_pretraining",
                "allowed_supervised_training",
                "allowed_validation_tuning"
            ]

        ]
        .to_numpy(
            dtype=bool
        )
        .sum()
    )


    no_held_out_leakage = (

        held_out_development_rows
        ==
        0

        and

        held_out_permission_violations
        ==
        0
    )


    complete_zero_day_family = (

        expected_zero_day_rows
        ==
        actual_zero_day_rows
    )


    fold_rows_conserved = (

        fold_total_rows
        ==
        TOTAL_ROWS
    )


    benign_partitions_valid = (

        benign_train_rows > 0

        and

        benign_validation_rows > 0

        and

        benign_test_rows > 0

        and

        (
            benign_train_rows
            +
            benign_validation_rows
            +
            benign_test_rows
        )
        ==
        SOURCE_CLASS_TO_ROW_COUNT[
            "Benign_Final"
        ]
    )


    fold_range_valid = bool(

        LOAFO_RANGE_CHECKS.loc[

            LOAFO_RANGE_CHECKS[
                "fold_number"
            ]
            ==
            fold_number,

            "range_valid"

        ].all()
    )


    fold_valid = (

        no_held_out_leakage

        and

        complete_zero_day_family

        and

        fold_rows_conserved

        and

        benign_partitions_valid

        and

        fold_range_valid
    )


    integrity_records.append({

        "fold_number":
            fold_number,

        "held_out_family":
            held_out_family,

        "held_out_rows_in_development":
            held_out_development_rows,

        "held_out_permission_violations":
            held_out_permission_violations,

        "expected_zero_day_attack_rows":
            expected_zero_day_rows,

        "actual_zero_day_attack_rows":
            actual_zero_day_rows,

        "complete_zero_day_family":
            complete_zero_day_family,

        "benign_train_rows":
            benign_train_rows,

        "benign_validation_rows":
            benign_validation_rows,

        "benign_test_rows":
            benign_test_rows,

        "fold_total_rows":
            fold_total_rows,

        "row_conservation":
            fold_rows_conserved,

        "range_integrity":
            fold_range_valid,

        "no_held_out_leakage":
            no_held_out_leakage,

        "fold_valid":
            fold_valid
    })


LOAFO_INTEGRITY_CHECKS = pd.DataFrame(
    integrity_records
)


LOAFO_INTEGRITY_CHECKS.to_csv(

    LOAFO_INTEGRITY_PATH,

    index=False
)


display(
    LOAFO_INTEGRITY_CHECKS
)


# ======================================================================
# 8.5.13 — ZERO-DAY COMPOSITION
# ======================================================================

print("\n[8] Zero-day evaluation composition")
print("-" * 78)


for _, row in (
    LOAFO_FOLD_SUMMARY.iterrows()
):

    print(

        f"Fold {int(row['fold_number'])} | "
        f"Held out: {row['held_out_family']:<12} | "
        f"Zero-day attack: "
        f"{int(row['zero_day_attack_rows']):>12,} | "
        f"Benign test: "
        f"{int(row['benign_test_rows']):>8,} | "
        f"Evaluation total: "
        f"{int(row['zero_day_evaluation_rows']):>12,}"
    )


# ======================================================================
# 8.5.14 — SAVE POLICY
# ======================================================================

print("\n[9] Saving LOAFO policy")
print("-" * 78)


LOAFO_POLICY = {

    "protocol":
        "Strict seven-fold Leave-One-Attack-Family-Out",

    "data_source":
        (
            "Verified chronologically sorted "
            "timestamp-preserving Parquet derivatives"
        ),

    "attack_families":
        LOAFO_FAMILIES,

    "development_train_ratio":
        TRAIN_RATIO,

    "development_validation_ratio":
        VALIDATION_RATIO,

    "known_test_ratio":
        TEST_RATIO,

    "held_out_family_attack_split":
        "100% zero-day attack test",

    "split_unit":
        "source attack-class file",

    "split_order":
        "chronological",

    "physical_partition_duplication":
        False,

    "partition_representation":
        "start_row / end_row_exclusive manifest",

    "preprocessing_fit":
        "development_train only",

    "ssl_pretraining":
        "development_train only",

    "supervised_training":
        "development_train only",

    "hyperparameter_selection":
        "development_validation only",

    "threshold_selection":
        "development_validation only",

    "known_test_usage":
        "final evaluation only",

    "zero_day_attack_test_usage":
        "final evaluation only",

    "benign_test_usage":
        "final evaluation only",

    "held_out_family_used_for_preprocessing":
        False,

    "held_out_family_used_for_ssl_pretraining":
        False,

    "held_out_family_used_for_supervised_training":
        False,

    "held_out_family_used_for_validation":
        False,

    "held_out_family_used_for_threshold_selection":
        False,

    "partition_changes_across_random_seeds":
        False,

    "random_seeds":
        RANDOM_SEEDS,

    "temporal_windows_cross_partition_boundaries":
        False,

    "temporal_windows_cross_source_files":
        False,

    "timestamp_is_model_feature":
        False,

    "split_ratio_note":
        (
            "70/15/15 is the experiment's "
            "development partition policy. "
            "The strict methodological requirement "
            "is complete held-out-family isolation."
        )
}


with open(

    LOAFO_POLICY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        LOAFO_POLICY,

        file,

        indent=4
    )


print(
    "✅ Policy saved:"
)

print(
    LOAFO_POLICY_PATH
)


# ======================================================================
# 8.5.15 — FINAL VALIDATION
# ======================================================================

print("\n[10] Final Step 8.5 validation")
print("-" * 78)


EXPECTED_MANIFEST_RECORDS = 629


manifest_record_count_valid = (

    len(
        LOAFO_SPLIT_MANIFEST
    )
    ==
    EXPECTED_MANIFEST_RECORDS
)


all_folds_valid = bool(

    LOAFO_INTEGRITY_CHECKS[
        "fold_valid"
    ].all()
)


all_ranges_valid = bool(

    LOAFO_RANGE_CHECKS[
        "range_valid"
    ].all()
)


no_held_out_leakage = bool(

    LOAFO_INTEGRITY_CHECKS[
        "no_held_out_leakage"
    ].all()
)


all_zero_day_complete = bool(

    LOAFO_INTEGRITY_CHECKS[
        "complete_zero_day_family"
    ].all()
)


all_rows_conserved = bool(

    LOAFO_INTEGRITY_CHECKS[
        "row_conservation"
    ].all()
)


required_outputs = [

    LOAFO_SPLIT_MANIFEST_PATH,

    LOAFO_FOLD_SUMMARY_PATH,

    LOAFO_RANGE_CHECK_PATH,

    LOAFO_INTEGRITY_PATH,

    LOAFO_POLICY_PATH
]


all_outputs_saved = all(

    path.exists()

    for path
    in required_outputs
)


STEP_8_5_VALID = (

    manifest_record_count_valid

    and

    len(
        LOAFO_FOLD_SUMMARY
    ) == 7

    and

    all_folds_valid

    and

    all_ranges_valid

    and

    no_held_out_leakage

    and

    all_zero_day_complete

    and

    all_rows_conserved

    and

    all_outputs_saved
)


print(
    "LOAFO folds created          :",
    len(
        LOAFO_FOLD_SUMMARY
    )
)

print(
    "Manifest records             :",
    len(
        LOAFO_SPLIT_MANIFEST
    ),
    "/",
    EXPECTED_MANIFEST_RECORDS
)

print(
    "All row ranges valid         :",
    all_ranges_valid
)

print(
    "Held-out leakage detected    :",
    not no_held_out_leakage
)

print(
    "All zero-day families complete:",
    all_zero_day_complete
)

print(
    "All fold rows conserved      :",
    all_rows_conserved
)

print(
    "All output artifacts saved   :",
    all_outputs_saved
)


print("\n" + "=" * 78)


if STEP_8_5_VALID:

    print(
        "✅ STEP 8.5 PASSED — "
        "All seven strict LOAFO folds are "
        "valid, chronological, complete, and leakage-free."
    )

else:

    print(
        "❌ STEP 8.5 FAILED — "
        "Do not start preprocessing."
    )


print("=" * 78)

==============================================================================
STEP 8.5 — STRICT SEVEN-FOLD LOAFO PARTITION CONSTRUCTION
==============================================================================

[1] Verifying chronological dataset
------------------------------------------------------------------------------
Chronological files: 33
Verified rows       : 39,851,619
LOAFO families      : 7
✅ Chronological dataset is ready.

[2] Partition policy
------------------------------------------------------------------------------
Development train      : 70%
Development validation : 15%
Known/benign test      : 15%
Held-out attack family : 100% zero-day test

[3] Verifying source-class row counts
------------------------------------------------------------------------------
✅ All 33 sorted source files match their verified row counts.

[4] Constructing seven LOAFO folds
------------------------------------------------------------------------------
Fold 1: DDoS held out
Fold 2: DoS held out
Fold 3: Mirai held out
Fold 4: Recon held out
Fold 5: Spoofing held out
Fold 6: Web held out
Fold 7: BruteForce held out

Manifest records: 629
Manifest saved:
/content/ZeroDay_IoT_Research/processed_data/loafo_manifests/CICIoT2023_LOAFO_split_manifest.csv

[5] Checking row-range coverage and overlap
------------------------------------------------------------------------------
Source-file/fold checks: 231
Invalid range checks    : 0

[6] Building LOAFO fold summary
------------------------------------------------------------------------------

,fold_number,held_out_family,development_train_rows,development_validation_rows,known_test_attack_rows,zero_day_attack_rows,benign_test_rows,known_evaluation_rows,zero_day_evaluation_rows,fold_total_rows
0,1,DDoS,6253058,1339934,1326235,30918665,13727,1339962,30932392,39851619
1,2,DoS,22621800,4847517,4833834,7534741,13727,4847561,7548468,39851619
2,3,Mirai,27880011,5974276,5960594,23011,13727,5974321,36738,39851619
3,4,Recon,27120670,5811561,5797875,1107786,13727,5811602,1121513,39851619
4,5,Spoofing,27792664,5955560,5941877,147791,13727,5955604,161518,39851619
5,6,Web,27882377,5974785,5961099,19631,13727,5974826,33358,39851619
6,7,BruteForce,27890176,5976454,5962774,8488,13727,5976501,22215,39851619

[7] Running strict zero-day leakage checks
------------------------------------------------------------------------------

,fold_number,held_out_family,held_out_rows_in_development,held_out_permission_violations,expected_zero_day_attack_rows,actual_zero_day_attack_rows,complete_zero_day_family,benign_train_rows,benign_validation_rows,benign_test_rows,fold_total_rows,row_conservation,range_integrity,no_held_out_leakage,fold_valid
0,1,DDoS,0,0,30918665,30918665,True,64054,13725,13727,39851619,True,True,True,True
1,2,DoS,0,0,7534741,7534741,True,64054,13725,13727,39851619,True,True,True,True
2,3,Mirai,0,0,23011,23011,True,64054,13725,13727,39851619,True,True,True,True
3,4,Recon,0,0,1107786,1107786,True,64054,13725,13727,39851619,True,True,True,True
4,5,Spoofing,0,0,147791,147791,True,64054,13725,13727,39851619,True,True,True,True
5,6,Web,0,0,19631,19631,True,64054,13725,13727,39851619,True,True,True,True
6,7,BruteForce,0,0,8488,8488,True,64054,13725,13727,39851619,True,True,True,True

[8] Zero-day evaluation composition
------------------------------------------------------------------------------
Fold 1 | Held out: DDoS         | Zero-day attack:   30,918,665 | Benign test:   13,727 | Evaluation total:   30,932,392
Fold 2 | Held out: DoS          | Zero-day attack:    7,534,741 | Benign test:   13,727 | Evaluation total:    7,548,468
Fold 3 | Held out: Mirai        | Zero-day attack:       23,011 | Benign test:   13,727 | Evaluation total:       36,738
Fold 4 | Held out: Recon        | Zero-day attack:    1,107,786 | Benign test:   13,727 | Evaluation total:    1,121,513
Fold 5 | Held out: Spoofing     | Zero-day attack:      147,791 | Benign test:   13,727 | Evaluation total:      161,518
Fold 6 | Held out: Web          | Zero-day attack:       19,631 | Benign test:   13,727 | Evaluation total:       33,358
Fold 7 | Held out: BruteForce   | Zero-day attack:        8,488 | Benign test:   13,727 | Evaluation total:       22,215

[9] Saving LOAFO policy
------------------------------------------------------------------------------
✅ Policy saved:
/content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_LOAFO_policy.json

[10] Final Step 8.5 validation
------------------------------------------------------------------------------
LOAFO folds created          : 7
Manifest records             : 629 / 629
All row ranges valid         : True
Held-out leakage detected    : False
All zero-day families complete: True
All fold rows conserved      : True
All output artifacts saved   : True

==============================================================================
✅ STEP 8.5 PASSED — All seven strict LOAFO folds are valid, chronological, complete, and leakage-free.
==============================================================================

## STEP 9.1 — Fit preprocessing for Fold 1 only
# 9.1 Leakage-Safe Preprocessing Fit — Fold 1 (DDoS Held Out)

This section fits preprocessing parameters for the first LOAFO fold.

**Held-out zero-day family:** DDoS

Only the `development_train` partition may contribute to preprocessing
statistics.

The following operations are fitted using training records only:

- Non-finite value detection
- Missing-value imputation statistics
- Infinite-value replacement statistics
- Zero-variance feature detection
- Standardization mean and variance

Missing values and positive/negative infinity are treated as non-finite.
Their replacement value is the finite training mean of the corresponding
feature.

Mean imputation is an implementation choice for the current experiment.
The essential leakage-prevention rule is that this value is estimated only
from the development-training partition.

No DDoS record, validation record, known-family test record, or final test
record is used to fit these parameters.

This step only calculates and saves preprocessing parameters.
It does not yet transform the data or create temporal windows.

In [ ]:
# ======================================================================
# STEP 9.1 — FOLD 1 LEAKAGE-SAFE PREPROCESSING FIT
# DDoS HELD OUT
# ======================================================================

from pathlib import Path
import json
import gc

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

print("=" * 78)
print("STEP 9.1 — FOLD 1 LEAKAGE-SAFE PREPROCESSING FIT")
print("HELD-OUT ZERO-DAY FAMILY: DDoS")
print("=" * 78)


# ======================================================================
# 9.1.1 — VERIFY REQUIRED STATE
# ======================================================================

print("\n[1] Verifying Step 8.5 state")
print("-" * 78)


required_variables = [

    "STEP_8_5_VALID",
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY",
    "NUMERIC_FEATURE_CANDIDATES",
    "ATTACK_FAMILIES",
    "DIRECTORIES"
]


missing_variables = [

    variable

    for variable in required_variables

    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(

        "Missing variables: "

        + ", ".join(
            missing_variables
        )

        + "\nPlease rerun the required previous cells."
    )


if not STEP_8_5_VALID:

    raise RuntimeError(
        "Step 8.5 has not passed. "
        "Do not fit preprocessing."
    )


print(
    "Numeric feature candidates:",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "✅ Required LOAFO state is available."
)


# ======================================================================
# 9.1.2 — SELECT FOLD 1
# ======================================================================

print("\n[2] Selecting Fold 1")
print("-" * 78)


FOLD_NUMBER = 1

HELD_OUT_FAMILY = "DDoS"


fold_manifest = (

    LOAFO_SPLIT_MANIFEST[

        LOAFO_SPLIT_MANIFEST[
            "fold_number"
        ]
        ==
        FOLD_NUMBER

    ]

    .copy()

    .reset_index(
        drop=True
    )
)


train_manifest = (

    fold_manifest[

        fold_manifest[
            "partition"
        ]
        ==
        "development_train"

    ]

    .copy()

    .reset_index(
        drop=True
    )
)


expected_train_rows = int(

    LOAFO_FOLD_SUMMARY.loc[

        LOAFO_FOLD_SUMMARY[
            "fold_number"
        ]
        ==
        FOLD_NUMBER,

        "development_train_rows"

    ].iloc[0]
)


print(
    "Fold number             :",
    FOLD_NUMBER
)

print(
    "Held-out family         :",
    HELD_OUT_FAMILY
)

print(
    "Training source ranges  :",
    len(train_manifest)
)

print(
    "Expected training rows  :",
    f"{expected_train_rows:,}"
)


# ======================================================================
# 9.1.3 — ZERO-DAY ISOLATION CHECK
# ======================================================================

print("\n[3] Checking DDoS isolation")
print("-" * 78)


held_out_rows_in_training = int(

    train_manifest.loc[

        train_manifest[
            "research_family"
        ]
        ==
        HELD_OUT_FAMILY,

        "rows"

    ].sum()
)


held_out_sources_in_training = int(

    (
        train_manifest[
            "research_family"
        ]
        ==
        HELD_OUT_FAMILY
    ).sum()
)


print(
    "DDoS source ranges in training:",
    held_out_sources_in_training
)

print(
    "DDoS rows in training         :",
    held_out_rows_in_training
)


if (
    held_out_sources_in_training != 0

    or

    held_out_rows_in_training != 0
):

    raise RuntimeError(

        "LEAKAGE DETECTED: "
        "DDoS appears in Fold 1 training data."
    )


print(
    "✅ DDoS is completely absent from preprocessing fit data."
)


# ======================================================================
# 9.1.4 — OUTPUT DIRECTORY
# ======================================================================

PREPROCESSING_ROOT = (

    DIRECTORIES["processed_data"]

    / "preprocessing"
)


FOLD_PREPROCESSING_DIR = (

    PREPROCESSING_ROOT

    / "fold_01_DDoS"
)


FOLD_PREPROCESSING_DIR.mkdir(

    parents=True,

    exist_ok=True
)


PREPROCESSING_PARAMETERS_PATH = (

    FOLD_PREPROCESSING_DIR

    / "preprocessing_parameters.csv"
)


PREPROCESSING_FEATURE_LIST_PATH = (

    FOLD_PREPROCESSING_DIR

    / "retained_features.json"
)


PREPROCESSING_POLICY_PATH = (

    FOLD_PREPROCESSING_DIR

    / "preprocessing_policy.json"
)


# ======================================================================
# 9.1.5 — INITIALIZE STREAMING STATISTICS
# ======================================================================

print("\n[4] Initializing streaming statistics")
print("-" * 78)


FEATURES = list(
    NUMERIC_FEATURE_CANDIDATES
)


N_FEATURES = len(
    FEATURES
)


finite_counts = np.zeros(
    N_FEATURES,
    dtype=np.int64
)


running_means = np.zeros(
    N_FEATURES,
    dtype=np.float64
)


running_m2 = np.zeros(
    N_FEATURES,
    dtype=np.float64
)


missing_counts = np.zeros(
    N_FEATURES,
    dtype=np.int64
)


positive_inf_counts = np.zeros(
    N_FEATURES,
    dtype=np.int64
)


negative_inf_counts = np.zeros(
    N_FEATURES,
    dtype=np.int64
)


finite_minimums = np.full(
    N_FEATURES,
    np.inf,
    dtype=np.float64
)


finite_maximums = np.full(
    N_FEATURES,
    -np.inf,
    dtype=np.float64
)


BATCH_SIZE_PREPROCESS = 50_000


print(
    "Features:",
    N_FEATURES
)

print(
    "Batch size:",
    f"{BATCH_SIZE_PREPROCESS:,}"
)


# ======================================================================
# 9.1.6 — ONLINE STATISTICS MERGE
# ======================================================================

def update_feature_statistics(
    feature_index,
    values
):

    global finite_counts
    global running_means
    global running_m2
    global missing_counts
    global positive_inf_counts
    global negative_inf_counts
    global finite_minimums
    global finite_maximums


    values = np.asarray(
        values,
        dtype=np.float64
    )


    # --------------------------------------------------------------
    # Count non-finite categories
    # --------------------------------------------------------------

    nan_mask = np.isnan(
        values
    )


    pos_inf_mask = np.isposinf(
        values
    )


    neg_inf_mask = np.isneginf(
        values
    )


    missing_counts[
        feature_index
    ] += int(
        nan_mask.sum()
    )


    positive_inf_counts[
        feature_index
    ] += int(
        pos_inf_mask.sum()
    )


    negative_inf_counts[
        feature_index
    ] += int(
        neg_inf_mask.sum()
    )


    # --------------------------------------------------------------
    # Retain finite values only
    # --------------------------------------------------------------

    finite_values = values[
        np.isfinite(
            values
        )
    ]


    batch_count = int(
        finite_values.size
    )


    if batch_count == 0:

        return


    # --------------------------------------------------------------
    # Batch statistics
    # --------------------------------------------------------------

    batch_mean = float(

        np.mean(
            finite_values,
            dtype=np.float64
        )
    )


    batch_m2 = float(

        np.sum(

            (
                finite_values
                -
                batch_mean
            )
            ** 2,

            dtype=np.float64
        )
    )


    batch_min = float(
        np.min(
            finite_values
        )
    )


    batch_max = float(
        np.max(
            finite_values
        )
    )


    # --------------------------------------------------------------
    # Numerically stable Welford merge
    # --------------------------------------------------------------

    old_count = int(

        finite_counts[
            feature_index
        ]
    )


    old_mean = float(

        running_means[
            feature_index
        ]
    )


    old_m2 = float(

        running_m2[
            feature_index
        ]
    )


    if old_count == 0:

        new_count = batch_count

        new_mean = batch_mean

        new_m2 = batch_m2

    else:

        new_count = (

            old_count

            +

            batch_count
        )


        delta = (

            batch_mean

            -

            old_mean
        )


        new_mean = (

            old_mean

            +

            delta

            *
            batch_count

            /

            new_count
        )


        new_m2 = (

            old_m2

            +

            batch_m2

            +

            (
                delta
                ** 2
            )

            *
            old_count

            *
            batch_count

            /

            new_count
        )


    finite_counts[
        feature_index
    ] = new_count


    running_means[
        feature_index
    ] = new_mean


    running_m2[
        feature_index
    ] = new_m2


    finite_minimums[
        feature_index
    ] = min(

        finite_minimums[
            feature_index
        ],

        batch_min
    )


    finite_maximums[
        feature_index
    ] = max(

        finite_maximums[
            feature_index
        ],

        batch_max
    )


# ======================================================================
# 9.1.7 — STREAM ONLY DEVELOPMENT-TRAINING ROW RANGES
# ======================================================================

print("\n[5] Fitting statistics from development_train only")
print("-" * 78)


total_training_rows_scanned = 0


for source_number, row in train_manifest.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    research_family = str(
        row[
            "research_family"
        ]
    )


    parquet_path = Path(
        row[
            "parquet_path"
        ]
    )


    start_row = int(
        row[
            "start_row"
        ]
    )


    end_row = int(
        row[
            "end_row_exclusive"
        ]
    )


    required_rows = int(
        row[
            "rows"
        ]
    )


    print(
        f"\n{source_number + 1:02d}/{len(train_manifest)} "
        f"{source_class}"
    )

    print(
        "Family:",
        research_family
    )

    print(
        "Training rows:",
        f"{required_rows:,}"
    )


    if research_family == HELD_OUT_FAMILY:

        raise RuntimeError(
            "Held-out DDoS source entered preprocessing."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    current_file_row = 0

    source_rows_scanned = 0


    for batch in parquet_file.iter_batches(

        columns=FEATURES,

        batch_size=BATCH_SIZE_PREPROCESS,

        use_threads=True
    ):

        batch_start = (
            current_file_row
        )


        batch_end = (

            current_file_row

            +

            batch.num_rows
        )


        current_file_row = (
            batch_end
        )


        # ----------------------------------------------------------
        # Batch occurs completely before requested range
        # ----------------------------------------------------------

        if batch_end <= start_row:

            continue


        # ----------------------------------------------------------
        # Requested range already completed
        # ----------------------------------------------------------

        if batch_start >= end_row:

            break


        # ----------------------------------------------------------
        # Determine overlap with requested manifest range
        # ----------------------------------------------------------

        overlap_start = max(
            start_row,
            batch_start
        )


        overlap_end = min(
            end_row,
            batch_end
        )


        local_start = (

            overlap_start

            -

            batch_start
        )


        local_length = (

            overlap_end

            -

            overlap_start
        )


        if local_length <= 0:

            continue


        selected_batch = batch.slice(

            local_start,

            local_length
        )


        source_rows_scanned += (
            local_length
        )


        total_training_rows_scanned += (
            local_length
        )


        # ----------------------------------------------------------
        # Update all feature statistics
        # ----------------------------------------------------------

        for feature_index in range(
            N_FEATURES
        ):

            arrow_array = (

                selected_batch
                .column(
                    feature_index
                )
            )


            values = arrow_array.to_numpy(

                zero_copy_only=False
            )


            update_feature_statistics(

                feature_index,

                values
            )


    # --------------------------------------------------------------
    # Verify exact manifest range
    # --------------------------------------------------------------

    if (
        source_rows_scanned
        !=
        required_rows
    ):

        raise RuntimeError(

            f"Training range mismatch for {source_class}: "
            f"expected {required_rows:,}, "
            f"scanned {source_rows_scanned:,}."
        )


    print(
        "✅ Scanned:",
        f"{source_rows_scanned:,}"
    )


    gc.collect()


# ======================================================================
# 9.1.8 — VERIFY TOTAL TRAINING ROWS
# ======================================================================

print("\n[6] Training-row validation")
print("-" * 78)


print(
    "Expected training rows:",
    f"{expected_train_rows:,}"
)

print(
    "Scanned training rows :",
    f"{total_training_rows_scanned:,}"
)


TRAINING_ROW_COUNT_MATCH = (

    total_training_rows_scanned

    ==

    expected_train_rows
)


print(
    "Rows match:",
    TRAINING_ROW_COUNT_MATCH
)


if not TRAINING_ROW_COUNT_MATCH:

    raise RuntimeError(
        "Preprocessing fit did not scan "
        "the exact training partition."
    )


# ======================================================================
# 9.1.9 — CALCULATE FOLD-SPECIFIC PARAMETERS
# ======================================================================

print("\n[7] Calculating preprocessing parameters")
print("-" * 78)


parameter_records = []


ZERO_VARIANCE_TOLERANCE = 1e-12


for feature_index, feature in enumerate(
    FEATURES
):

    finite_count = int(

        finite_counts[
            feature_index
        ]
    )


    missing_count = int(

        missing_counts[
            feature_index
        ]
    )


    positive_inf_count = int(

        positive_inf_counts[
            feature_index
        ]
    )


    negative_inf_count = int(

        negative_inf_counts[
            feature_index
        ]
    )


    nonfinite_count = (

        missing_count

        +

        positive_inf_count

        +

        negative_inf_count
    )


    # --------------------------------------------------------------
    # Feature has no finite training values
    # --------------------------------------------------------------

    if finite_count == 0:

        imputation_mean = np.nan

        scaler_mean = np.nan

        scaler_variance = np.nan

        scaler_std = np.nan

        zero_variance = True

        usable_feature = False

        finite_min = np.nan

        finite_max = np.nan

    else:

        imputation_mean = float(

            running_means[
                feature_index
            ]
        )


        scaler_mean = (
            imputation_mean
        )


        # ----------------------------------------------------------
        # Missing / inf values will be imputed with training mean.
        #
        # Therefore imputed observations contribute zero squared
        # deviation around that same mean.
        #
        # StandardScaler uses population variance (ddof=0), so M2
        # is divided by the TOTAL training-row count.
        # ----------------------------------------------------------

        scaler_variance = float(

            running_m2[
                feature_index
            ]

            /

            expected_train_rows
        )


        # Protect against tiny negative floating-point artifacts
        scaler_variance = max(

            scaler_variance,

            0.0
        )


        scaler_std = float(

            np.sqrt(
                scaler_variance
            )
        )


        zero_variance = bool(

            scaler_std
            <=
            ZERO_VARIANCE_TOLERANCE
        )


        usable_feature = bool(

            not zero_variance

            and

            np.isfinite(
                scaler_std
            )
        )


        finite_min = float(

            finite_minimums[
                feature_index
            ]
        )


        finite_max = float(

            finite_maximums[
                feature_index
            ]
        )


    parameter_records.append({

        "feature":
            feature,

        "training_rows":
            expected_train_rows,

        "finite_count":
            finite_count,

        "missing_count":
            missing_count,

        "positive_inf_count":
            positive_inf_count,

        "negative_inf_count":
            negative_inf_count,

        "nonfinite_count":
            nonfinite_count,

        "nonfinite_percentage":
            (
                nonfinite_count

                /

                expected_train_rows

                *

                100
            ),

        "imputation_value":
            imputation_mean,

        "finite_min":
            finite_min,

        "finite_max":
            finite_max,

        "scaler_mean":
            scaler_mean,

        "scaler_variance":
            scaler_variance,

        "scaler_std":
            scaler_std,

        "zero_variance":
            zero_variance,

        "retained_feature":
            usable_feature
    })


PREPROCESSING_PARAMETERS = pd.DataFrame(
    parameter_records
)


# ======================================================================
# 9.1.10 — RETAINED FEATURE LIST
# ======================================================================

RETAINED_FEATURES_FOLD_1 = (

    PREPROCESSING_PARAMETERS.loc[

        PREPROCESSING_PARAMETERS[
            "retained_feature"
        ],

        "feature"

    ]

    .tolist()
)


ZERO_VARIANCE_FEATURES_FOLD_1 = (

    PREPROCESSING_PARAMETERS.loc[

        PREPROCESSING_PARAMETERS[
            "zero_variance"
        ],

        "feature"

    ]

    .tolist()
)


FEATURES_WITH_NONFINITE_FOLD_1 = (

    PREPROCESSING_PARAMETERS.loc[

        PREPROCESSING_PARAMETERS[
            "nonfinite_count"
        ]
        >
        0

    ]

    .copy()

    .sort_values(

        "nonfinite_count",

        ascending=False
    )

    .reset_index(
        drop=True
    )
)


# ======================================================================
# 9.1.11 — SAVE PARAMETERS
# ======================================================================

PREPROCESSING_PARAMETERS.to_csv(

    PREPROCESSING_PARAMETERS_PATH,

    index=False
)


with open(

    PREPROCESSING_FEATURE_LIST_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        {

            "fold_number":
                FOLD_NUMBER,

            "held_out_family":
                HELD_OUT_FAMILY,

            "input_numeric_features":
                FEATURES,

            "zero_variance_features":
                ZERO_VARIANCE_FEATURES_FOLD_1,

            "retained_features":
                RETAINED_FEATURES_FOLD_1
        },

        file,

        indent=4
    )


# ======================================================================
# 9.1.12 — SAVE PREPROCESSING POLICY
# ======================================================================

included_training_classes = (

    train_manifest[
        "source_attack_class"
    ]
    .astype(str)
    .tolist()
)


included_training_families = sorted(

    train_manifest[
        "research_family"
    ]
    .astype(str)
    .unique()
    .tolist()
)


PREPROCESSING_POLICY_FOLD_1 = {

    "fold_number":
        FOLD_NUMBER,

    "held_out_family":
        HELD_OUT_FAMILY,

    "preprocessing_fit_partition":
        "development_train",

    "training_rows":
        expected_train_rows,

    "input_numeric_features":
        len(FEATURES),

    "imputation_strategy":
        (
            "Replace NaN, +inf and -inf "
            "with finite development-training mean "
            "of the corresponding feature"
        ),

    "standardization":
        (
            "Population mean/std fitted on "
            "development-training data after mean imputation"
        ),

    "zero_variance_detection":
        "development-training partition only",

    "zero_variance_tolerance":
        ZERO_VARIANCE_TOLERANCE,

    "held_out_family_used":
        False,

    "validation_used_for_fit":
        False,

    "known_test_used_for_fit":
        False,

    "zero_day_test_used_for_fit":
        False,

    "included_training_families":
        included_training_families,

    "included_training_source_classes":
        included_training_classes,

    "retained_feature_count":
        len(
            RETAINED_FEATURES_FOLD_1
        ),

    "zero_variance_feature_count":
        len(
            ZERO_VARIANCE_FEATURES_FOLD_1
        )
}


with open(

    PREPROCESSING_POLICY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        PREPROCESSING_POLICY_FOLD_1,

        file,

        indent=4
    )


# ======================================================================
# 9.1.13 — DISPLAY DATA-QUALITY RESULTS
# ======================================================================

print("\n[8] Training non-finite feature audit")
print("-" * 78)


if FEATURES_WITH_NONFINITE_FOLD_1.empty:

    print(
        "✅ No non-finite values occur "
        "in Fold 1 development training."
    )

else:

    display(
        FEATURES_WITH_NONFINITE_FOLD_1[
            [
                "feature",
                "missing_count",
                "positive_inf_count",
                "negative_inf_count",
                "nonfinite_count",
                "nonfinite_percentage",
                "imputation_value"
            ]
        ]
    )


# ======================================================================
# 9.1.14 — DISPLAY ZERO-VARIANCE RESULTS
# ======================================================================

print("\n[9] Fold-specific zero-variance features")
print("-" * 78)


print(
    "Input numeric features :",
    len(FEATURES)
)

print(
    "Zero-variance features :",
    len(
        ZERO_VARIANCE_FEATURES_FOLD_1
    )
)

print(
    "Retained features      :",
    len(
        RETAINED_FEATURES_FOLD_1
    )
)


if ZERO_VARIANCE_FEATURES_FOLD_1:

    print(
        "\nDropped only because they have "
        "zero variance in Fold 1 training:"
    )

    for feature in (
        ZERO_VARIANCE_FEATURES_FOLD_1
    ):

        print(
            " -",
            feature
        )


# ======================================================================
# 9.1.15 — LEAKAGE-SAFETY SUMMARY
# ======================================================================

print("\n[10] Leakage-safety summary")
print("-" * 78)


print(
    "Held-out family              :",
    HELD_OUT_FAMILY
)

print(
    "Held-out rows used for fit   :",
    0
)

print(
    "Validation rows used for fit :",
    0
)

print(
    "Known-test rows used for fit :",
    0
)

print(
    "Zero-day rows used for fit   :",
    0
)

print(
    "Training rows used for fit   :",
    f"{total_training_rows_scanned:,}"
)


# ======================================================================
# 9.1.16 — FINAL VALIDATION
# ======================================================================

print("\n[11] Final Step 9.1 validation")
print("-" * 78)


all_retained_parameters_finite = bool(

    PREPROCESSING_PARAMETERS.loc[

        PREPROCESSING_PARAMETERS[
            "retained_feature"
        ],

        [
            "imputation_value",
            "scaler_mean",
            "scaler_std"
        ]

    ]
    .apply(
        np.isfinite
    )
    .all()
    .all()
)


all_retained_std_positive = bool(

    (
        PREPROCESSING_PARAMETERS.loc[

            PREPROCESSING_PARAMETERS[
                "retained_feature"
            ],

            "scaler_std"
        ]

        >

        ZERO_VARIANCE_TOLERANCE

    ).all()
)


output_files_saved = all(

    path.exists()

    for path in [

        PREPROCESSING_PARAMETERS_PATH,
        PREPROCESSING_FEATURE_LIST_PATH,
        PREPROCESSING_POLICY_PATH
    ]
)


STEP_9_1_VALID = (

    TRAINING_ROW_COUNT_MATCH

    and

    held_out_rows_in_training == 0

    and

    held_out_sources_in_training == 0

    and

    len(
        RETAINED_FEATURES_FOLD_1
    ) > 0

    and

    all_retained_parameters_finite

    and

    all_retained_std_positive

    and

    output_files_saved
)


print(
    "Training rows exact             :",
    TRAINING_ROW_COUNT_MATCH
)

print(
    "Held-out DDoS rows used         :",
    held_out_rows_in_training
)

print(
    "Input numeric features          :",
    len(FEATURES)
)

print(
    "Retained features               :",
    len(
        RETAINED_FEATURES_FOLD_1
    )
)

print(
    "All retained parameters finite  :",
    all_retained_parameters_finite
)

print(
    "All retained std > 0            :",
    all_retained_std_positive
)

print(
    "Output artifacts saved          :",
    output_files_saved
)


print("\n" + "=" * 78)


if STEP_9_1_VALID:

    print(
        "✅ STEP 9.1 PASSED — "
        "Fold 1 preprocessing parameters were fitted "
        "using development-training data only."
    )

else:

    print(
        "❌ STEP 9.1 FAILED — "
        "Do not transform data yet."
    )


print("=" * 78)

==============================================================================
STEP 9.1 — FOLD 1 LEAKAGE-SAFE PREPROCESSING FIT
HELD-OUT ZERO-DAY FAMILY: DDoS
==============================================================================

[1] Verifying Step 8.5 state
------------------------------------------------------------------------------
Numeric feature candidates: 79
✅ Required LOAFO state is available.

[2] Selecting Fold 1
------------------------------------------------------------------------------
Fold number             : 1
Held-out family         : DDoS
Training source ranges  : 21
Expected training rows  : 6,253,058

[3] Checking DDoS isolation
------------------------------------------------------------------------------
DDoS source ranges in training: 0
DDoS rows in training         : 0
✅ DDoS is completely absent from preprocessing fit data.

[4] Initializing streaming statistics
------------------------------------------------------------------------------
Features: 79
Batch size: 50,000

[5] Fitting statistics from development_train only
------------------------------------------------------------------------------

01/21 Backdoor_Malware
Family: Web
Training rows: 1,892
✅ Scanned: 1,892

02/21 Benign_Final
Family: Benign
Training rows: 64,054
✅ Scanned: 64,054

03/21 BrowserHijacking
Family: Web
Training rows: 2,300
✅ Scanned: 2,300

04/21 CommandInjection
Family: Web
Training rows: 2,693
✅ Scanned: 2,693

05/21 DNS_Spoofing
Family: Spoofing
Training rows: 52,456
✅ Scanned: 52,456

06/21 DictionaryBruteForce
Family: BruteForce
Training rows: 5,941
✅ Scanned: 5,941

07/21 DoS-HTTP_Flood
Family: DoS
Training rows: 675,887
✅ Scanned: 675,887

08/21 DoS-SYN_Flood
Family: DoS
Training rows: 2,797,977
✅ Scanned: 2,797,977

09/21 DoS-TCP_Flood
Family: DoS
Training rows: 1,146,647
✅ Scanned: 1,146,647

10/21 DoS-UDP_Flood
Family: DoS
Training rows: 653,806
✅ Scanned: 653,806

11/21 MITM-ArpSpoofing
Family: Spoofing
Training rows: 50,997
✅ Scanned: 50,997

12/21 Mirai-greeth_flood
Family: Mirai
Training rows: 3,608
✅ Scanned: 3,608

13/21 Mirai-greip_flood
Family: Mirai
Training rows: 7,280
✅ Scanned: 7,280

14/21 Mirai-udpplain
Family: Mirai
Training rows: 5,218
✅ Scanned: 5,218

15/21 Recon-HostDiscovery
Family: Recon
Training rows: 230,989
✅ Scanned: 230,989

16/21 Recon-OSScan
Family: Recon
Training rows: 111,077
✅ Scanned: 111,077

17/21 Recon-PingSweep
Family: Recon
Training rows: 1,362
✅ Scanned: 1,362

18/21 Recon-PortScan
Family: Recon
Training rows: 122,534
✅ Scanned: 122,534

19/21 SqlInjection
Family: Web
Training rows: 4,617
✅ Scanned: 4,617

20/21 VulnerabilityScan
Family: Recon
Training rows: 309,485
✅ Scanned: 309,485

21/21 XSS
Family: Web
Training rows: 2,238
✅ Scanned: 2,238

[6] Training-row validation
------------------------------------------------------------------------------
Expected training rows: 6,253,058
Scanned training rows : 6,253,058
Rows match: True

[7] Calculating preprocessing parameters
------------------------------------------------------------------------------

[8] Training non-finite feature audit
------------------------------------------------------------------------------

,feature,missing_count,positive_inf_count,negative_inf_count,nonfinite_count,nonfinite_percentage,imputation_value
0,Flow Bytes/s,28608,809,0,29417,0.470442,59606.832888
1,Flow Packets/s,0,29417,0,29417,0.470442,2843.526353

[9] Fold-specific zero-variance features
------------------------------------------------------------------------------
Input numeric features : 79
Zero-variance features : 4
Retained features      : 75

Dropped only because they have zero variance in Fold 1 training:
 - Bwd URG Flags
 - Fwd Bytes/Bulk Avg
 - Fwd Packet/Bulk Avg
 - Fwd Bulk Rate Avg

[10] Leakage-safety summary
------------------------------------------------------------------------------
Held-out family              : DDoS
Held-out rows used for fit   : 0
Validation rows used for fit : 0
Known-test rows used for fit : 0
Zero-day rows used for fit   : 0
Training rows used for fit   : 6,253,058

[11] Final Step 9.1 validation
------------------------------------------------------------------------------
Training rows exact             : True
Held-out DDoS rows used         : 0
Input numeric features          : 79
Retained features               : 75
All retained parameters finite  : True
All retained std > 0            : True
Output artifacts saved          : True

==============================================================================
✅ STEP 9.1 PASSED — Fold 1 preprocessing parameters were fitted using development-training data only.
==============================================================================

# STEP 9.2 — Verify Fold 1 preprocessing
# 9.2 Fold 1 Preprocessing Verification

This section independently verifies the preprocessing parameters fitted
for Fold 1.

The verification uses only the Fold-1 `development_train` partition.

For each retained feature:

1. NaN, positive infinity, and negative infinity are replaced using the
   training-only imputation value fitted in Step 9.1.
2. The feature is standardized using the training-only mean and standard
   deviation.
3. Streaming statistics are calculated again over the transformed
   development-training partition.

A correct preprocessing fit should produce:

- approximately zero mean for every retained feature;
- approximately unit standard deviation for every retained feature;
- no NaN values after preprocessing;
- no positive or negative infinity after preprocessing;
- exactly the same training-row count used in Step 9.1.

No validation, known-test, benign-test, or zero-day attack-test records
are used in this verification.

In [ ]:
# ======================================================================
# STEP 9.2 — VERIFY FOLD 1 PREPROCESSING PARAMETERS
# ======================================================================

from pathlib import Path
import json
import gc

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

print("=" * 78)
print("STEP 9.2 — VERIFY FOLD 1 PREPROCESSING PARAMETERS")
print("=" * 78)


# ======================================================================
# 9.2.1 — VERIFY REQUIRED STATE
# ======================================================================

print("\n[1] Verifying Step 9.1 state")
print("-" * 78)


required_variables = [

    "STEP_9_1_VALID",
    "PREPROCESSING_PARAMETERS",
    "RETAINED_FEATURES_FOLD_1",
    "ZERO_VARIANCE_FEATURES_FOLD_1",
    "train_manifest",
    "expected_train_rows",
    "PREPROCESSING_PARAMETERS_PATH",
    "PREPROCESSING_FEATURE_LIST_PATH",
    "PREPROCESSING_POLICY_PATH",
    "FOLD_PREPROCESSING_DIR"
]


missing_variables = [

    variable

    for variable in required_variables

    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(

        "Missing variables: "

        + ", ".join(
            missing_variables
        )

        + "\nPlease rerun Step 9.1."
    )


if not STEP_9_1_VALID:

    raise RuntimeError(
        "Step 9.1 did not pass."
    )


print(
    "Training rows    :",
    f"{expected_train_rows:,}"
)

print(
    "Retained features:",
    len(
        RETAINED_FEATURES_FOLD_1
    )
)

print(
    "Zero-variance features:",
    len(
        ZERO_VARIANCE_FEATURES_FOLD_1
    )
)

print(
    "✅ Step 9.1 state is valid."
)


# ======================================================================
# 9.2.2 — RELOAD SAVED PARAMETERS
# ======================================================================

print("\n[2] Reloading saved preprocessing parameters")
print("-" * 78)


saved_parameters = pd.read_csv(
    PREPROCESSING_PARAMETERS_PATH
)


with open(

    PREPROCESSING_FEATURE_LIST_PATH,

    "r",

    encoding="utf-8"

) as file:

    saved_feature_policy = json.load(
        file
    )


saved_retained_features = (

    saved_feature_policy[
        "retained_features"
    ]
)


saved_zero_variance_features = (

    saved_feature_policy[
        "zero_variance_features"
    ]
)


retained_list_match = (

    saved_retained_features

    ==

    RETAINED_FEATURES_FOLD_1
)


zero_variance_list_match = (

    saved_zero_variance_features

    ==

    ZERO_VARIANCE_FEATURES_FOLD_1
)


print(
    "Saved retained-feature list matches:",
    retained_list_match
)

print(
    "Saved zero-variance list matches   :",
    zero_variance_list_match
)


if not retained_list_match:

    raise RuntimeError(
        "Saved retained-feature list does not match memory."
    )


if not zero_variance_list_match:

    raise RuntimeError(
        "Saved zero-variance list does not match memory."
    )


# ======================================================================
# 9.2.3 — EXTRACT RETAINED PARAMETERS
# ======================================================================

parameter_lookup = (

    saved_parameters

    .set_index(
        "feature"
    )
)


missing_parameter_features = [

    feature

    for feature
    in RETAINED_FEATURES_FOLD_1

    if feature
    not in parameter_lookup.index
]


if missing_parameter_features:

    raise RuntimeError(

        "Missing preprocessing parameters for:\n"

        +

        "\n".join(
            missing_parameter_features
        )
    )


retained_parameters = (

    parameter_lookup.loc[
        RETAINED_FEATURES_FOLD_1
    ]

    .copy()
)


IMPUTATION_VALUES = (

    retained_parameters[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    retained_parameters[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    retained_parameters[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


N_RETAINED = len(
    RETAINED_FEATURES_FOLD_1
)


parameter_values_valid = bool(

    np.isfinite(
        IMPUTATION_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "\nPreprocessing parameter arrays valid:",
    parameter_values_valid
)


if not parameter_values_valid:

    raise RuntimeError(
        "Invalid retained preprocessing parameters."
    )


# ======================================================================
# 9.2.4 — INITIALIZE TRANSFORM VERIFICATION
# ======================================================================

print("\n[3] Initializing transformation verification")
print("-" * 78)


VERIFY_BATCH_SIZE = 50_000


standardized_sum = np.zeros(
    N_RETAINED,
    dtype=np.float64
)


standardized_squared_sum = np.zeros(
    N_RETAINED,
    dtype=np.float64
)


raw_nonfinite_seen = np.zeros(
    N_RETAINED,
    dtype=np.int64
)


post_transform_nonfinite = np.zeros(
    N_RETAINED,
    dtype=np.int64
)


total_rows_verified = 0


print(
    "Verification batch size:",
    f"{VERIFY_BATCH_SIZE:,}"
)


# ======================================================================
# 9.2.5 — STREAM DEVELOPMENT TRAINING ONLY
# ======================================================================

print("\n[4] Reapplying preprocessing to development_train")
print("-" * 78)


for source_number, row in train_manifest.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    family = str(
        row[
            "research_family"
        ]
    )


    parquet_path = Path(
        row[
            "parquet_path"
        ]
    )


    start_row = int(
        row[
            "start_row"
        ]
    )


    end_row = int(
        row[
            "end_row_exclusive"
        ]
    )


    required_rows = int(
        row[
            "rows"
        ]
    )


    print(

        f"\n{source_number + 1:02d}/{len(train_manifest)} "
        f"{source_class} "
        f"({family})"

    )


    # --------------------------------------------------------------
    # Fold 1 zero-day safety check
    # --------------------------------------------------------------

    if family == "DDoS":

        raise RuntimeError(

            "LEAKAGE DETECTED: "
            "DDoS entered Step 9.2."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    current_file_row = 0

    source_rows_verified = 0


    for batch in parquet_file.iter_batches(

        columns=
            RETAINED_FEATURES_FOLD_1,

        batch_size=
            VERIFY_BATCH_SIZE,

        use_threads=True
    ):

        batch_start = (
            current_file_row
        )


        batch_end = (

            current_file_row

            +

            batch.num_rows
        )


        current_file_row = (
            batch_end
        )


        # ----------------------------------------------------------
        # Entire batch before requested range
        # ----------------------------------------------------------

        if batch_end <= start_row:

            continue


        # ----------------------------------------------------------
        # Requested range already finished
        # ----------------------------------------------------------

        if batch_start >= end_row:

            break


        overlap_start = max(

            batch_start,

            start_row
        )


        overlap_end = min(

            batch_end,

            end_row
        )


        local_start = (

            overlap_start

            -

            batch_start
        )


        local_length = (

            overlap_end

            -

            overlap_start
        )


        if local_length <= 0:

            continue


        selected_batch = batch.slice(

            local_start,

            local_length
        )


        # ----------------------------------------------------------
        # Convert retained feature batch to NumPy matrix
        # ----------------------------------------------------------

        X = np.empty(

            (
                local_length,
                N_RETAINED
            ),

            dtype=np.float64
        )


        for feature_index in range(
            N_RETAINED
        ):

            X[
                :,
                feature_index
            ] = (

                selected_batch

                .column(
                    feature_index
                )

                .to_numpy(
                    zero_copy_only=False
                )
            )


        # ----------------------------------------------------------
        # Identify original non-finite values
        # ----------------------------------------------------------

        nonfinite_mask = (

            ~np.isfinite(
                X
            )
        )


        raw_nonfinite_seen += (

            nonfinite_mask

            .sum(
                axis=0
            )

            .astype(
                np.int64
            )
        )


        # ----------------------------------------------------------
        # Mean imputation using Fold-1 TRAINING statistics
        # ----------------------------------------------------------

        if nonfinite_mask.any():

            bad_rows, bad_columns = np.where(
                nonfinite_mask
            )


            X[
                bad_rows,
                bad_columns
            ] = (

                IMPUTATION_VALUES[
                    bad_columns
                ]
            )


        # ----------------------------------------------------------
        # Standardization
        # ----------------------------------------------------------

        Z = (

            X

            -

            SCALER_MEANS

        ) / SCALER_STDS


        # ----------------------------------------------------------
        # Check transformed non-finite values
        # ----------------------------------------------------------

        post_mask = (

            ~np.isfinite(
                Z
            )
        )


        post_transform_nonfinite += (

            post_mask

            .sum(
                axis=0
            )

            .astype(
                np.int64
            )
        )


        if post_mask.any():

            raise RuntimeError(

                f"Non-finite transformed values detected "
                f"in {source_class}."
            )


        # ----------------------------------------------------------
        # Streaming standardized statistics
        # ----------------------------------------------------------

        standardized_sum += np.sum(

            Z,

            axis=0,

            dtype=np.float64
        )


        standardized_squared_sum += np.sum(

            Z * Z,

            axis=0,

            dtype=np.float64
        )


        source_rows_verified += (
            local_length
        )


        total_rows_verified += (
            local_length
        )


    if (

        source_rows_verified

        !=

        required_rows
    ):

        raise RuntimeError(

            f"Row-range verification failed for "
            f"{source_class}: "
            f"expected {required_rows:,}, "
            f"verified {source_rows_verified:,}."
        )


    print(
        "✅ Verified:",
        f"{source_rows_verified:,}"
    )


    gc.collect()


# ======================================================================
# 9.2.6 — ROW-COUNT VALIDATION
# ======================================================================

print("\n[5] Verification row-count check")
print("-" * 78)


ROW_COUNT_VERIFIED = (

    total_rows_verified

    ==

    expected_train_rows
)


print(
    "Expected rows:",
    f"{expected_train_rows:,}"
)

print(
    "Verified rows:",
    f"{total_rows_verified:,}"
)

print(
    "Rows match   :",
    ROW_COUNT_VERIFIED
)


# ======================================================================
# 9.2.7 — CALCULATE POST-TRANSFORM STATISTICS
# ======================================================================

print("\n[6] Calculating standardized training statistics")
print("-" * 78)


verified_means = (

    standardized_sum

    /

    total_rows_verified
)


verified_variances = (

    standardized_squared_sum

    /

    total_rows_verified

    -

    verified_means ** 2
)


verified_variances = np.maximum(

    verified_variances,

    0.0
)


verified_stds = np.sqrt(

    verified_variances
)


mean_absolute_error = np.abs(

    verified_means
)


std_absolute_error = np.abs(

    verified_stds

    -

    1.0
)


MAX_ABS_STANDARDIZED_MEAN = float(

    np.max(
        mean_absolute_error
    )
)


MAX_ABS_STANDARDIZED_STD_ERROR = float(

    np.max(
        std_absolute_error
    )
)


# ======================================================================
# 9.2.8 — CREATE FEATURE VERIFICATION TABLE
# ======================================================================

verification_table = pd.DataFrame({

    "feature":
        RETAINED_FEATURES_FOLD_1,

    "raw_nonfinite_values":
        raw_nonfinite_seen,

    "post_transform_nonfinite":
        post_transform_nonfinite,

    "verified_standardized_mean":
        verified_means,

    "verified_standardized_std":
        verified_stds,

    "absolute_mean_error":
        mean_absolute_error,

    "absolute_std_error":
        std_absolute_error
})


VERIFICATION_TABLE_PATH = (

    FOLD_PREPROCESSING_DIR

    / "preprocessing_verification.csv"
)


verification_table.to_csv(

    VERIFICATION_TABLE_PATH,

    index=False
)


# ======================================================================
# 9.2.9 — VERIFY PREPROCESSING QUALITY
# ======================================================================

print("\n[7] Preprocessing verification results")
print("-" * 78)


MEAN_TOLERANCE = 1e-5

STD_TOLERANCE = 1e-5


MEANS_VALID = (

    MAX_ABS_STANDARDIZED_MEAN

    <=

    MEAN_TOLERANCE
)


STDS_VALID = (

    MAX_ABS_STANDARDIZED_STD_ERROR

    <=

    STD_TOLERANCE
)


POST_TRANSFORM_FINITE = (

    int(
        post_transform_nonfinite.sum()
    )

    ==

    0
)


print(
    "Maximum |training mean|       :",
    f"{MAX_ABS_STANDARDIZED_MEAN:.10f}"
)

print(
    "Allowed mean tolerance        :",
    MEAN_TOLERANCE
)

print(
    "Maximum |training std - 1|    :",
    f"{MAX_ABS_STANDARDIZED_STD_ERROR:.10f}"
)

print(
    "Allowed std tolerance         :",
    STD_TOLERANCE
)

print(
    "Post-transform nonfinite count:",
    f"{int(post_transform_nonfinite.sum()):,}"
)

print(
    "Means approximately zero      :",
    MEANS_VALID
)

print(
    "Standard deviations ≈ 1       :",
    STDS_VALID
)

print(
    "All transformed values finite :",
    POST_TRANSFORM_FINITE
)


# ======================================================================
# 9.2.10 — SHOW WORST VERIFICATION ERRORS
# ======================================================================

print("\n[8] Largest numerical verification errors")
print("-" * 78)


display(

    verification_table

    .sort_values(

        [
            "absolute_std_error",
            "absolute_mean_error"
        ],

        ascending=False
    )

    .head(10)
)


# ======================================================================
# 9.2.11 — SAVE SUMMARY
# ======================================================================

VERIFICATION_SUMMARY_PATH = (

    FOLD_PREPROCESSING_DIR

    / "preprocessing_verification_summary.json"
)


verification_summary = {

    "fold_number":
        1,

    "held_out_family":
        "DDoS",

    "partition_verified":
        "development_train",

    "training_rows_expected":
        int(
            expected_train_rows
        ),

    "training_rows_verified":
        int(
            total_rows_verified
        ),

    "retained_features":
        int(
            N_RETAINED
        ),

    "maximum_absolute_standardized_mean":
        MAX_ABS_STANDARDIZED_MEAN,

    "maximum_absolute_standardized_std_error":
        MAX_ABS_STANDARDIZED_STD_ERROR,

    "mean_tolerance":
        MEAN_TOLERANCE,

    "std_tolerance":
        STD_TOLERANCE,

    "post_transform_nonfinite_count":
        int(
            post_transform_nonfinite.sum()
        ),

    "held_out_family_used":
        False,

    "validation_used":
        False,

    "known_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(

    VERIFICATION_SUMMARY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        verification_summary,

        file,

        indent=4
    )


# ======================================================================
# 9.2.12 — FINAL VALIDATION
# ======================================================================

print("\n[9] Final Step 9.2 validation")
print("-" * 78)


verification_outputs_saved = (

    VERIFICATION_TABLE_PATH.exists()

    and

    VERIFICATION_SUMMARY_PATH.exists()
)


STEP_9_2_VALID = (

    ROW_COUNT_VERIFIED

    and

    retained_list_match

    and

    zero_variance_list_match

    and

    parameter_values_valid

    and

    MEANS_VALID

    and

    STDS_VALID

    and

    POST_TRANSFORM_FINITE

    and

    verification_outputs_saved
)


print(
    "Exact training rows verified    :",
    ROW_COUNT_VERIFIED
)

print(
    "Retained feature list verified  :",
    retained_list_match
)

print(
    "Zero-variance list verified     :",
    zero_variance_list_match
)

print(
    "Preprocessing parameters valid  :",
    parameter_values_valid
)

print(
    "Standardized means ≈ 0          :",
    MEANS_VALID
)

print(
    "Standardized std values ≈ 1     :",
    STDS_VALID
)

print(
    "Post-transform values finite    :",
    POST_TRANSFORM_FINITE
)

print(
    "Verification artifacts saved    :",
    verification_outputs_saved
)


print("\n" + "=" * 78)


if STEP_9_2_VALID:

    print(
        "✅ STEP 9.2 PASSED — "
        "Fold 1 preprocessing parameters were independently verified."
    )

else:

    print(
        "❌ STEP 9.2 FAILED — "
        "Do not transform validation or test data."
    )


print("=" * 78)

==============================================================================
STEP 9.2 — VERIFY FOLD 1 PREPROCESSING PARAMETERS
==============================================================================

[1] Verifying Step 9.1 state
------------------------------------------------------------------------------
Training rows    : 6,253,058
Retained features: 75
Zero-variance features: 4
✅ Step 9.1 state is valid.

[2] Reloading saved preprocessing parameters
------------------------------------------------------------------------------
Saved retained-feature list matches: True
Saved zero-variance list matches   : True

Preprocessing parameter arrays valid: True

[3] Initializing transformation verification
------------------------------------------------------------------------------
Verification batch size: 50,000

[4] Reapplying preprocessing to development_train
------------------------------------------------------------------------------

01/21 Backdoor_Malware (Web)
✅ Verified: 1,892

02/21 Benign_Final (Benign)
✅ Verified: 64,054

03/21 BrowserHijacking (Web)
✅ Verified: 2,300

04/21 CommandInjection (Web)
✅ Verified: 2,693

05/21 DNS_Spoofing (Spoofing)
✅ Verified: 52,456

06/21 DictionaryBruteForce (BruteForce)
✅ Verified: 5,941

07/21 DoS-HTTP_Flood (DoS)
✅ Verified: 675,887

08/21 DoS-SYN_Flood (DoS)
✅ Verified: 2,797,977

09/21 DoS-TCP_Flood (DoS)
✅ Verified: 1,146,647

10/21 DoS-UDP_Flood (DoS)
✅ Verified: 653,806

11/21 MITM-ArpSpoofing (Spoofing)
✅ Verified: 50,997

12/21 Mirai-greeth_flood (Mirai)
✅ Verified: 3,608

13/21 Mirai-greip_flood (Mirai)
✅ Verified: 7,280

14/21 Mirai-udpplain (Mirai)
✅ Verified: 5,218

15/21 Recon-HostDiscovery (Recon)
✅ Verified: 230,989

16/21 Recon-OSScan (Recon)
✅ Verified: 111,077

17/21 Recon-PingSweep (Recon)
✅ Verified: 1,362

18/21 Recon-PortScan (Recon)
✅ Verified: 122,534

19/21 SqlInjection (Web)
✅ Verified: 4,617

20/21 VulnerabilityScan (Recon)
✅ Verified: 309,485

21/21 XSS (Web)
✅ Verified: 2,238

[5] Verification row-count check
------------------------------------------------------------------------------
Expected rows: 6,253,058
Verified rows: 6,253,058
Rows match   : True

[6] Calculating standardized training statistics
------------------------------------------------------------------------------

[7] Preprocessing verification results
------------------------------------------------------------------------------
Maximum |training mean|       : 0.0000000000
Allowed mean tolerance        : 1e-05
Maximum |training std - 1|    : 0.0000000000
Allowed std tolerance         : 1e-05
Post-transform nonfinite count: 0
Means approximately zero      : True
Standard deviations ≈ 1       : True
All transformed values finite : True

[8] Largest numerical verification errors
------------------------------------------------------------------------------

,feature,raw_nonfinite_values,post_transform_nonfinite,verified_standardized_mean,verified_standardized_std,absolute_mean_error,absolute_std_error
56,Bwd Bytes/Bulk Avg,0,0,2.276983e-15,1.0,2.276983e-15,1.212697e-12
48,ACK Flag Count,0,0,2.822266e-15,1.0,2.822266e-15,1.120881e-12
47,PSH Flag Count,0,0,2.386054e-15,1.0,2.386054e-15,6.652456e-13
62,Subflow Bwd Bytes,0,0,-3.003192e-15,1.0,3.003192e-15,6.359357e-13
49,URG Flag Count,0,0,3.334972e-16,1.0,3.334972e-16,4.904965e-13
35,Fwd Header Length,0,0,-8.858976e-17,1.0,8.858976e-17,4.760636e-13
58,Bwd Bulk Rate Avg,0,0,-1.106502e-14,1.0,1.106502e-14,3.486100e-13
5,Total Bwd packets,0,0,1.820282e-15,1.0,1.820282e-15,3.050893e-13
50,CWR Flag Count,0,0,-1.555203e-15,1.0,1.555203e-15,2.985390e-13
34,Fwd URG Flags,0,0,8.339244e-15,1.0,8.339244e-15,2.734479e-13

[9] Final Step 9.2 validation
------------------------------------------------------------------------------
Exact training rows verified    : True
Retained feature list verified  : True
Zero-variance list verified     : True
Preprocessing parameters valid  : True
Standardized means ≈ 0          : True
Standardized std values ≈ 1     : True
Post-transform values finite    : True
Verification artifacts saved    : True

==============================================================================
✅ STEP 9.2 PASSED — Fold 1 preprocessing parameters were independently verified.
==============================================================================

## STEP 9.3 — Apply Frozen Fold-1 Preprocessing to Validation and Test Data
# 9.3 Apply Frozen Fold-1 Preprocessing to Validation and Test Data

This section applies the Fold-1 preprocessing parameters to all
non-training partitions without refitting any statistic.

The following partitions are processed:

- Development validation
- Known-family attack test
- Benign test
- DDoS zero-day attack test

The preprocessing parameters remain exactly those fitted using the
Fold-1 development-training partition.

For every retained feature:

1. NaN, positive infinity, and negative infinity are replaced using
   the frozen training-only imputation value.
2. The value is standardized using the frozen training-only mean and
   standard deviation.
3. The transformed value is checked for numerical validity.

No mean, variance, imputation value, zero-variance decision, or feature
selection rule is recomputed using validation or test data.

Validation and test distributions are not expected to have zero mean or
unit variance because those partitions were not used to fit the scaler.

To avoid unnecessary storage duplication, transformed row-level copies
are not persisted in this step. Temporal-window creation will later
apply the same frozen transformation while constructing model-ready
sequences.

# 2. Add this Code cell

In [ ]:
# ======================================================================
# STEP 9.3 — APPLY FROZEN FOLD-1 PREPROCESSING
# VALIDATION + KNOWN TEST + BENIGN TEST + ZERO-DAY DDoS TEST
# ======================================================================

from pathlib import Path
import json
import gc

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

print("=" * 78)
print("STEP 9.3 — APPLY FROZEN FOLD-1 PREPROCESSING")
print("HELD-OUT ZERO-DAY FAMILY: DDoS")
print("=" * 78)


# ======================================================================
# 9.3.1 — VERIFY PREVIOUS STEP
# ======================================================================

print("\n[1] Verifying Step 9.2 state")
print("-" * 78)


required_variables = [

    "STEP_9_2_VALID",
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY",
    "PREPROCESSING_PARAMETERS_PATH",
    "PREPROCESSING_FEATURE_LIST_PATH",
    "FOLD_PREPROCESSING_DIR"
]


missing_variables = [

    variable
    for variable in required_variables

    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(

        "Missing variables: "

        + ", ".join(
            missing_variables
        )

        + "\nPlease rerun the required previous cells."
    )


if not STEP_9_2_VALID:

    raise RuntimeError(
        "Step 9.2 did not pass."
    )


print(
    "✅ Fold-1 preprocessing parameters "
    "have already been independently verified."
)


# ======================================================================
# 9.3.2 — FIX FOLD IDENTITY
# ======================================================================

FOLD_NUMBER = 1

HELD_OUT_FAMILY = "DDoS"


fold_manifest = (

    LOAFO_SPLIT_MANIFEST[

        LOAFO_SPLIT_MANIFEST[
            "fold_number"
        ]
        ==
        FOLD_NUMBER

    ]

    .copy()

    .reset_index(
        drop=True
    )
)


# ======================================================================
# 9.3.3 — SELECT NON-TRAINING PARTITIONS
# ======================================================================

print("\n[2] Selecting non-training partitions")
print("-" * 78)


TARGET_PARTITIONS = [

    "development_validation",

    "known_test",

    "benign_test",

    "zero_day_attack_test"
]


evaluation_manifest = (

    fold_manifest[

        fold_manifest[
            "partition"
        ]
        .isin(
            TARGET_PARTITIONS
        )

    ]

    .copy()

    .reset_index(
        drop=True
    )
)


print(
    "Partition ranges to process:",
    len(
        evaluation_manifest
    )
)


print(
    "\nPartition row totals:"
)


partition_row_totals = (

    evaluation_manifest

    .groupby(
        "partition"
    )[
        "rows"
    ]

    .sum()

    .astype(int)
)


for partition in TARGET_PARTITIONS:

    rows = int(

        partition_row_totals.get(
            partition,
            0
        )
    )

    print(
        f"  {partition:<25}: "
        f"{rows:,}"
    )


# ======================================================================
# 9.3.4 — EXPECTED ROW COUNTS FROM FOLD SUMMARY
# ======================================================================

fold_summary_row = (

    LOAFO_FOLD_SUMMARY[

        LOAFO_FOLD_SUMMARY[
            "fold_number"
        ]
        ==
        FOLD_NUMBER

    ]

    .iloc[0]
)


EXPECTED_PARTITION_ROWS = {

    "development_validation":
        int(
            fold_summary_row[
                "development_validation_rows"
            ]
        ),

    "known_test":
        int(
            fold_summary_row[
                "known_test_attack_rows"
            ]
        ),

    "benign_test":
        int(
            fold_summary_row[
                "benign_test_rows"
            ]
        ),

    "zero_day_attack_test":
        int(
            fold_summary_row[
                "zero_day_attack_rows"
            ]
        )
}


print(
    "\nExpected Fold-1 rows:"
)


for partition, rows in (
    EXPECTED_PARTITION_ROWS.items()
):

    print(
        f"  {partition:<25}: "
        f"{rows:,}"
    )


# ======================================================================
# 9.3.5 — RELOAD FROZEN PARAMETERS FROM DISK
# ======================================================================

print("\n[3] Loading frozen training-only preprocessing parameters")
print("-" * 78)


saved_parameters = pd.read_csv(
    PREPROCESSING_PARAMETERS_PATH
)


with open(

    PREPROCESSING_FEATURE_LIST_PATH,

    "r",

    encoding="utf-8"

) as file:

    saved_feature_information = (
        json.load(
            file
        )
    )


FROZEN_FEATURES = (

    saved_feature_information[
        "retained_features"
    ]
)


N_FEATURES = len(
    FROZEN_FEATURES
)


parameter_lookup = (

    saved_parameters

    .set_index(
        "feature"
    )

    .loc[
        FROZEN_FEATURES
    ]
)


FROZEN_IMPUTATION_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


FROZEN_SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


FROZEN_SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


frozen_parameters_valid = bool(

    np.isfinite(
        FROZEN_IMPUTATION_VALUES
    ).all()

    and

    np.isfinite(
        FROZEN_SCALER_MEANS
    ).all()

    and

    np.isfinite(
        FROZEN_SCALER_STDS
    ).all()

    and

    (
        FROZEN_SCALER_STDS > 0
    ).all()
)


print(
    "Frozen retained features:",
    N_FEATURES
)

print(
    "Frozen parameters valid :",
    frozen_parameters_valid
)


if not frozen_parameters_valid:

    raise RuntimeError(
        "Frozen preprocessing parameters are invalid."
    )


# ======================================================================
# 9.3.6 — CONFIRM NO REFITTING WILL OCCUR
# ======================================================================

print("\n[4] Leakage-safety policy")
print("-" * 78)


print(
    "Imputation values fitted here : False"
)

print(
    "Scaler means fitted here      : False"
)

print(
    "Scaler stds fitted here       : False"
)

print(
    "Feature selection fitted here : False"
)

print(
    "Zero-variance fitting here    : False"
)

print(
    "All parameters source         : Fold-1 development_train"
)


# ======================================================================
# 9.3.7 — TRANSFORMATION FUNCTION
# ======================================================================

def apply_frozen_preprocessing(
    X
):

    """
    Apply Fold-1 training-only preprocessing.

    No fitting occurs here.
    """

    X = np.asarray(
        X,
        dtype=np.float64
    )


    nonfinite_mask = (

        ~np.isfinite(
            X
        )
    )


    raw_nonfinite_count = int(

        nonfinite_mask.sum()
    )


    if nonfinite_mask.any():

        bad_rows, bad_columns = np.where(
            nonfinite_mask
        )


        X[
            bad_rows,
            bad_columns
        ] = (

            FROZEN_IMPUTATION_VALUES[
                bad_columns
            ]
        )


    Z = (

        X

        -

        FROZEN_SCALER_MEANS

    ) / FROZEN_SCALER_STDS


    post_float64_nonfinite = int(

        (
            ~np.isfinite(
                Z
            )
        ).sum()
    )


    # --------------------------------------------------------------
    # Models will later use float32 tensors.
    # Verify that conversion to float32 also stays finite.
    # --------------------------------------------------------------

    Z_float32 = Z.astype(
        np.float32
    )


    post_float32_nonfinite = int(

        (
            ~np.isfinite(
                Z_float32
            )
        ).sum()
    )


    return (

        Z,

        raw_nonfinite_count,

        post_float64_nonfinite,

        post_float32_nonfinite
    )


# ======================================================================
# 9.3.8 — PROCESS EVERY NON-TRAINING RANGE
# ======================================================================

print("\n[5] Applying frozen parameters")
print("-" * 78)


BATCH_SIZE_APPLY = 50_000


partition_audit_records = []


overall_rows_processed = 0


for range_number, row in (
    evaluation_manifest.iterrows()
):

    partition = str(
        row[
            "partition"
        ]
    )


    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    research_family = str(
        row[
            "research_family"
        ]
    )


    parquet_path = Path(
        row[
            "parquet_path"
        ]
    )


    start_row = int(
        row[
            "start_row"
        ]
    )


    end_row = int(
        row[
            "end_row_exclusive"
        ]
    )


    required_rows = int(
        row[
            "rows"
        ]
    )


    print("\n" + "-" * 78)

    print(
        f"{range_number + 1:02d}/"
        f"{len(evaluation_manifest)}"
    )

    print(
        "Partition :",
        partition
    )

    print(
        "Class     :",
        source_class
    )

    print(
        "Family    :",
        research_family
    )

    print(
        "Rows      :",
        f"{required_rows:,}"
    )


    # --------------------------------------------------------------
    # Safety checks for held-out DDoS
    # --------------------------------------------------------------

    if (
        research_family
        ==
        HELD_OUT_FAMILY

        and

        partition
        !=
        "zero_day_attack_test"
    ):

        raise RuntimeError(

            "LEAKAGE DETECTED: "
            "DDoS appears outside zero-day test."
        )


    if (
        partition
        ==
        "zero_day_attack_test"

        and

        research_family
        !=
        HELD_OUT_FAMILY
    ):

        raise RuntimeError(

            "Invalid zero-day partition: "
            "non-DDoS family found."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    current_file_row = 0

    range_rows_processed = 0


    raw_nonfinite_total = 0

    post_float64_nonfinite_total = 0

    post_float32_nonfinite_total = 0


    maximum_absolute_z = 0.0


    for batch in parquet_file.iter_batches(

        columns=
            FROZEN_FEATURES,

        batch_size=
            BATCH_SIZE_APPLY,

        use_threads=True
    ):

        batch_start = (
            current_file_row
        )


        batch_end = (

            current_file_row

            +

            batch.num_rows
        )


        current_file_row = (
            batch_end
        )


        if batch_end <= start_row:

            continue


        if batch_start >= end_row:

            break


        overlap_start = max(

            batch_start,

            start_row
        )


        overlap_end = min(

            batch_end,

            end_row
        )


        local_start = (

            overlap_start

            -

            batch_start
        )


        local_length = (

            overlap_end

            -

            overlap_start
        )


        if local_length <= 0:

            continue


        selected_batch = batch.slice(

            local_start,

            local_length
        )


        X = np.empty(

            (
                local_length,
                N_FEATURES
            ),

            dtype=np.float64
        )


        for feature_index in range(
            N_FEATURES
        ):

            X[
                :,
                feature_index
            ] = (

                selected_batch

                .column(
                    feature_index
                )

                .to_numpy(
                    zero_copy_only=False
                )
            )


        (
            Z,
            raw_nonfinite,
            post_float64_nonfinite,
            post_float32_nonfinite

        ) = apply_frozen_preprocessing(
            X
        )


        raw_nonfinite_total += (
            raw_nonfinite
        )


        post_float64_nonfinite_total += (
            post_float64_nonfinite
        )


        post_float32_nonfinite_total += (
            post_float32_nonfinite
        )


        if Z.size > 0:

            batch_max_abs_z = float(

                np.max(
                    np.abs(
                        Z
                    )
                )
            )


            maximum_absolute_z = max(

                maximum_absolute_z,

                batch_max_abs_z
            )


        range_rows_processed += (
            local_length
        )


        overall_rows_processed += (
            local_length
        )


        del X
        del Z


    if (
        range_rows_processed
        !=
        required_rows
    ):

        raise RuntimeError(

            f"Row mismatch for {source_class} / {partition}: "
            f"expected {required_rows:,}, "
            f"processed {range_rows_processed:,}."
        )


    status = (

        "PASS"

        if (

            post_float64_nonfinite_total == 0

            and

            post_float32_nonfinite_total == 0

        )

        else "FAIL"
    )


    print(
        "Raw non-finite values :",
        f"{raw_nonfinite_total:,}"
    )

    print(
        "Float64 non-finite out:",
        f"{post_float64_nonfinite_total:,}"
    )

    print(
        "Float32 non-finite out:",
        f"{post_float32_nonfinite_total:,}"
    )

    print(
        "Status                :",
        status
    )


    partition_audit_records.append({

        "fold_number":
            FOLD_NUMBER,

        "held_out_family":
            HELD_OUT_FAMILY,

        "partition":
            partition,

        "source_attack_class":
            source_class,

        "research_family":
            research_family,

        "expected_rows":
            required_rows,

        "processed_rows":
            range_rows_processed,

        "raw_nonfinite_values":
            raw_nonfinite_total,

        "post_float64_nonfinite_values":
            post_float64_nonfinite_total,

        "post_float32_nonfinite_values":
            post_float32_nonfinite_total,

        "maximum_absolute_standardized_value":
            maximum_absolute_z,

        "status":
            status
    })


    gc.collect()


# ======================================================================
# 9.3.9 — CREATE AUDIT TABLE
# ======================================================================

APPLICATION_AUDIT = pd.DataFrame(
    partition_audit_records
)


APPLICATION_AUDIT_PATH = (

    FOLD_PREPROCESSING_DIR

    / "nontraining_preprocessing_application_audit.csv"
)


APPLICATION_AUDIT.to_csv(

    APPLICATION_AUDIT_PATH,

    index=False
)


# ======================================================================
# 9.3.10 — PARTITION SUMMARY
# ======================================================================

print("\n[6] Partition transformation summary")
print("-" * 78)


partition_summary = (

    APPLICATION_AUDIT

    .groupby(
        "partition",
        as_index=False
    )

    .agg(

        source_ranges=(
            "source_attack_class",
            "count"
        ),

        expected_rows=(
            "expected_rows",
            "sum"
        ),

        processed_rows=(
            "processed_rows",
            "sum"
        ),

        raw_nonfinite_values=(
            "raw_nonfinite_values",
            "sum"
        ),

        post_float64_nonfinite_values=(
            "post_float64_nonfinite_values",
            "sum"
        ),

        post_float32_nonfinite_values=(
            "post_float32_nonfinite_values",
            "sum"
        ),

        maximum_absolute_standardized_value=(
            "maximum_absolute_standardized_value",
            "max"
        )
    )
)


display(
    partition_summary
)


# ======================================================================
# 9.3.11 — CHECK EXPECTED PARTITION COUNTS
# ======================================================================

print("\n[7] Partition row-count validation")
print("-" * 78)


partition_count_checks = {}


for partition in TARGET_PARTITIONS:

    actual_rows = int(

        APPLICATION_AUDIT.loc[

            APPLICATION_AUDIT[
                "partition"
            ]
            ==
            partition,

            "processed_rows"

        ].sum()
    )


    expected_rows = int(

        EXPECTED_PARTITION_ROWS[
            partition
        ]
    )


    match = (

        actual_rows

        ==

        expected_rows
    )


    partition_count_checks[
        partition
    ] = match


    print(

        f"{partition:<25} "
        f"expected={expected_rows:>12,} "
        f"processed={actual_rows:>12,} "
        f"match={match}"
    )


# ======================================================================
# 9.3.12 — NUMERICAL VALIDITY
# ======================================================================

print("\n[8] Frozen transformation validity")
print("-" * 78)


TOTAL_RAW_NONFINITE = int(

    APPLICATION_AUDIT[
        "raw_nonfinite_values"
    ].sum()
)


TOTAL_POST_FLOAT64_NONFINITE = int(

    APPLICATION_AUDIT[
        "post_float64_nonfinite_values"
    ].sum()
)


TOTAL_POST_FLOAT32_NONFINITE = int(

    APPLICATION_AUDIT[
        "post_float32_nonfinite_values"
    ].sum()
)


ALL_RANGE_STATUSES_PASS = bool(

    (
        APPLICATION_AUDIT[
            "status"
        ]
        ==
        "PASS"
    ).all()
)


print(
    "Raw non-finite values encountered :",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "Non-finite after float64 transform:",
    f"{TOTAL_POST_FLOAT64_NONFINITE:,}"
)

print(
    "Non-finite after float32 transform:",
    f"{TOTAL_POST_FLOAT32_NONFINITE:,}"
)

print(
    "All source ranges passed          :",
    ALL_RANGE_STATUSES_PASS
)


# ======================================================================
# 9.3.13 — LEAKAGE CHECK
# ======================================================================

print("\n[9] Leakage-safety verification")
print("-" * 78)


DDoS_NON_ZERO_DAY_ROWS = int(

    evaluation_manifest.loc[

        (
            evaluation_manifest[
                "research_family"
            ]
            ==
            HELD_OUT_FAMILY
        )

        &

        (
            evaluation_manifest[
                "partition"
            ]
            !=
            "zero_day_attack_test"
        ),

        "rows"

    ].sum()
)


ZERO_DAY_NON_DDoS_ROWS = int(

    evaluation_manifest.loc[

        (
            evaluation_manifest[
                "partition"
            ]
            ==
            "zero_day_attack_test"
        )

        &

        (
            evaluation_manifest[
                "research_family"
            ]
            !=
            HELD_OUT_FAMILY
        ),

        "rows"

    ].sum()
)


print(
    "DDoS rows outside zero-day test:",
    DDoS_NON_ZERO_DAY_ROWS
)

print(
    "Non-DDoS rows in zero-day attack test:",
    ZERO_DAY_NON_DDoS_ROWS
)

print(
    "Parameters refitted:",
    False
)


LEAKAGE_SAFE = (

    DDoS_NON_ZERO_DAY_ROWS == 0

    and

    ZERO_DAY_NON_DDoS_ROWS == 0
)


print(
    "Leakage-safe:",
    LEAKAGE_SAFE
)


# ======================================================================
# 9.3.14 — SAVE SUMMARY JSON
# ======================================================================

APPLICATION_SUMMARY_PATH = (

    FOLD_PREPROCESSING_DIR

    / "nontraining_preprocessing_application_summary.json"
)


application_summary = {

    "fold_number":
        FOLD_NUMBER,

    "held_out_family":
        HELD_OUT_FAMILY,

    "frozen_feature_count":
        N_FEATURES,

    "parameters_refitted":
        False,

    "imputation_refitted":
        False,

    "scaler_refitted":
        False,

    "feature_selection_refitted":
        False,

    "zero_variance_detection_refitted":
        False,

    "processed_partitions":
        TARGET_PARTITIONS,

    "total_rows_processed":
        int(
            overall_rows_processed
        ),

    "total_raw_nonfinite_values":
        TOTAL_RAW_NONFINITE,

    "total_post_float64_nonfinite_values":
        TOTAL_POST_FLOAT64_NONFINITE,

    "total_post_float32_nonfinite_values":
        TOTAL_POST_FLOAT32_NONFINITE,

    "leakage_safe":
        bool(
            LEAKAGE_SAFE
        ),

    "full_transformed_dataset_persisted":
        False,

    "reason_full_copy_not_persisted":
        (
            "Temporal windows will apply the frozen "
            "preprocessing parameters directly while "
            "constructing model-ready sequences."
        )
}


with open(

    APPLICATION_SUMMARY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        application_summary,

        file,

        indent=4
    )


# ======================================================================
# 9.3.15 — FINAL VALIDATION
# ======================================================================

print("\n[10] Final Step 9.3 validation")
print("-" * 78)


ALL_PARTITION_COUNTS_MATCH = all(

    partition_count_checks.values()
)


APPLICATION_OUTPUTS_SAVED = (

    APPLICATION_AUDIT_PATH.exists()

    and

    APPLICATION_SUMMARY_PATH.exists()
)


STEP_9_3_VALID = (

    frozen_parameters_valid

    and

    ALL_PARTITION_COUNTS_MATCH

    and

    TOTAL_POST_FLOAT64_NONFINITE == 0

    and

    TOTAL_POST_FLOAT32_NONFINITE == 0

    and

    ALL_RANGE_STATUSES_PASS

    and

    LEAKAGE_SAFE

    and

    APPLICATION_OUTPUTS_SAVED
)


print(
    "Frozen parameters valid          :",
    frozen_parameters_valid
)

print(
    "All partition row counts exact   :",
    ALL_PARTITION_COUNTS_MATCH
)

print(
    "All float64 transformed finite   :",
    TOTAL_POST_FLOAT64_NONFINITE == 0
)

print(
    "All float32 transformed finite   :",
    TOTAL_POST_FLOAT32_NONFINITE == 0
)

print(
    "All source ranges passed         :",
    ALL_RANGE_STATUSES_PASS
)

print(
    "Held-out isolation preserved     :",
    LEAKAGE_SAFE
)

print(
    "Audit artifacts saved            :",
    APPLICATION_OUTPUTS_SAVED
)


print("\n" + "=" * 78)


if STEP_9_3_VALID:

    print(
        "✅ STEP 9.3 PASSED — "
        "Frozen Fold-1 preprocessing was safely applied "
        "to all validation and test partitions without refitting."
    )

else:

    print(
        "❌ STEP 9.3 FAILED — "
        "Do not create temporal windows yet."
    )


print("=" * 78)

==============================================================================
STEP 9.3 — APPLY FROZEN FOLD-1 PREPROCESSING
HELD-OUT ZERO-DAY FAMILY: DDoS
==============================================================================

[1] Verifying Step 9.2 state
------------------------------------------------------------------------------
✅ Fold-1 preprocessing parameters have already been independently verified.

[2] Selecting non-training partitions
------------------------------------------------------------------------------
Partition ranges to process: 54

Partition row totals:
  development_validation   : 1,339,934
  known_test               : 1,326,235
  benign_test              : 13,727
  zero_day_attack_test     : 30,918,665

Expected Fold-1 rows:
  development_validation   : 1,339,934
  known_test               : 1,326,235
  benign_test              : 13,727
  zero_day_attack_test     : 30,918,665

[3] Loading frozen training-only preprocessing parameters
------------------------------------------------------------------------------
Frozen retained features: 75
Frozen parameters valid : True

[4] Leakage-safety policy
------------------------------------------------------------------------------
Imputation values fitted here : False
Scaler means fitted here      : False
Scaler stds fitted here       : False
Feature selection fitted here : False
Zero-variance fitting here    : False
All parameters source         : Fold-1 development_train

[5] Applying frozen parameters
------------------------------------------------------------------------------

------------------------------------------------------------------------------
01/54
Partition : development_validation
Class     : Backdoor_Malware
Family    : Web
Rows      : 405
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
02/54
Partition : known_test
Class     : Backdoor_Malware
Family    : Web
Rows      : 406
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
03/54
Partition : development_validation
Class     : Benign_Final
Family    : Benign
Rows      : 13,725
Raw non-finite values : 20
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
04/54
Partition : benign_test
Class     : Benign_Final
Family    : Benign
Rows      : 13,727
Raw non-finite values : 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
05/54
Partition : development_validation
Class     : BrowserHijacking
Family    : Web
Rows      : 492
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
06/54
Partition : known_test
Class     : BrowserHijacking
Family    : Web
Rows      : 494
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
07/54
Partition : development_validation
Class     : CommandInjection
Family    : Web
Rows      : 577
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
08/54
Partition : known_test
Class     : CommandInjection
Family    : Web
Rows      : 578
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
09/54
Partition : zero_day_attack_test
Class     : DDoS-ACK_Fragmentation
Family    : DDoS
Rows      : 37,296
Raw non-finite values : 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
10/54
Partition : zero_day_attack_test
Class     : DDoS-HTTP_Flood
Family    : DDoS
Rows      : 513,672
Raw non-finite values : 2,300
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
11/54
Partition : zero_day_attack_test
Class     : DDoS-ICMP_Flood
Family    : DDoS
Rows      : 7,834
Raw non-finite values : 58
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
12/54
Partition : zero_day_attack_test
Class     : DDoS-ICMP_Fragmentation
Family    : DDoS
Rows      : 25,106
Raw non-finite values : 44
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
13/54
Partition : zero_day_attack_test
Class     : DDoS-PSHACK_Flood
Family    : DDoS
Rows      : 5,007,067
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
14/54
Partition : zero_day_attack_test
Class     : DDoS-RSTFINFlood
Family    : DDoS
Rows      : 12,968,618
Raw non-finite values : 8
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
15/54
Partition : zero_day_attack_test
Class     : DDoS-SYN_Flood
Family    : DDoS
Rows      : 6,366,353
Raw non-finite values : 324
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
16/54
Partition : zero_day_attack_test
Class     : DDoS-SlowLoris
Family    : DDoS
Rows      : 196,578
Raw non-finite values : 66
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
17/54
Partition : zero_day_attack_test
Class     : DDoS-SynonymousIP_Flood
Family    : DDoS
Rows      : 799,351
Raw non-finite values : 6
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
18/54
Partition : zero_day_attack_test
Class     : DDoS-TCP_Flood
Family    : DDoS
Rows      : 4,945,887
Raw non-finite values : 246
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
19/54
Partition : zero_day_attack_test
Class     : DDoS-UDP_Flood
Family    : DDoS
Rows      : 41,146
Raw non-finite values : 262
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
20/54
Partition : zero_day_attack_test
Class     : DDoS-UDP_Fragmentation
Family    : DDoS
Rows      : 9,757
Raw non-finite values : 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
21/54
Partition : development_validation
Class     : DNS_Spoofing
Family    : Spoofing
Rows      : 11,240
Raw non-finite values : 18
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
22/54
Partition : known_test
Class     : DNS_Spoofing
Family    : Spoofing
Rows      : 11,242
Raw non-finite values : 14
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
23/54
Partition : development_validation
Class     : DictionaryBruteForce
Family    : BruteForce
Rows      : 1,273
Raw non-finite values : 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
24/54
Partition : known_test
Class     : DictionaryBruteForce
Family    : BruteForce
Rows      : 1,274
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
25/54
Partition : development_validation
Class     : DoS-HTTP_Flood
Family    : DoS
Rows      : 144,833
Raw non-finite values : 180
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
26/54
Partition : known_test
Class     : DoS-HTTP_Flood
Family    : DoS
Rows      : 144,834
Raw non-finite values : 24,082
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
27/54
Partition : development_validation
Class     : DoS-SYN_Flood
Family    : DoS
Rows      : 599,566
Raw non-finite values : 108
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
28/54
Partition : known_test
Class     : DoS-SYN_Flood
Family    : DoS
Rows      : 599,567
Raw non-finite values : 66
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
29/54
Partition : development_validation
Class     : DoS-TCP_Flood
Family    : DoS
Rows      : 245,710
Raw non-finite values : 660
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
30/54
Partition : known_test
Class     : DoS-TCP_Flood
Family    : DoS
Rows      : 245,711
Raw non-finite values : 818
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
31/54
Partition : development_validation
Class     : DoS-UDP_Flood
Family    : DoS
Rows      : 140,101
Raw non-finite values : 68
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
32/54
Partition : known_test
Class     : DoS-UDP_Flood
Family    : DoS
Rows      : 140,102
Raw non-finite values : 34
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
33/54
Partition : development_validation
Class     : MITM-ArpSpoofing
Family    : Spoofing
Rows      : 10,927
Raw non-finite values : 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
34/54
Partition : known_test
Class     : MITM-ArpSpoofing
Family    : Spoofing
Rows      : 10,929
Raw non-finite values : 22
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
35/54
Partition : development_validation
Class     : Mirai-greeth_flood
Family    : Mirai
Rows      : 773
Raw non-finite values : 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
36/54
Partition : known_test
Class     : Mirai-greeth_flood
Family    : Mirai
Rows      : 774
Raw non-finite values : 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
37/54
Partition : development_validation
Class     : Mirai-greip_flood
Family    : Mirai
Rows      : 1,560
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
38/54
Partition : known_test
Class     : Mirai-greip_flood
Family    : Mirai
Rows      : 1,561
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
39/54
Partition : development_validation
Class     : Mirai-udpplain
Family    : Mirai
Rows      : 1,118
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
40/54
Partition : known_test
Class     : Mirai-udpplain
Family    : Mirai
Rows      : 1,119
Raw non-finite values : 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
41/54
Partition : development_validation
Class     : Recon-HostDiscovery
Family    : Recon
Rows      : 49,497
Raw non-finite values : 28
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
42/54
Partition : known_test
Class     : Recon-HostDiscovery
Family    : Recon
Rows      : 49,499
Raw non-finite values : 32
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
43/54
Partition : development_validation
Class     : Recon-OSScan
Family    : Recon
Rows      : 23,802
Raw non-finite values : 8
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
44/54
Partition : known_test
Class     : Recon-OSScan
Family    : Recon
Rows      : 23,803
Raw non-finite values : 62
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
45/54
Partition : development_validation
Class     : Recon-PingSweep
Family    : Recon
Rows      : 292
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
46/54
Partition : known_test
Class     : Recon-PingSweep
Family    : Recon
Rows      : 293
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
47/54
Partition : development_validation
Class     : Recon-PortScan
Family    : Recon
Rows      : 26,257
Raw non-finite values : 22
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
48/54
Partition : known_test
Class     : Recon-PortScan
Family    : Recon
Rows      : 26,259
Raw non-finite values : 28
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
49/54
Partition : development_validation
Class     : SqlInjection
Family    : Web
Rows      : 989
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
50/54
Partition : known_test
Class     : SqlInjection
Family    : Web
Rows      : 990
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
51/54
Partition : development_validation
Class     : VulnerabilityScan
Family    : Recon
Rows      : 66,318
Raw non-finite values : 390
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
52/54
Partition : known_test
Class     : VulnerabilityScan
Family    : Recon
Rows      : 66,319
Raw non-finite values : 398
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
53/54
Partition : development_validation
Class     : XSS
Family    : Web
Rows      : 479
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

------------------------------------------------------------------------------
54/54
Partition : known_test
Class     : XSS
Family    : Web
Rows      : 481
Raw non-finite values : 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Status                : PASS

[6] Partition transformation summary
------------------------------------------------------------------------------

,partition,source_ranges,expected_rows,processed_rows,raw_nonfinite_values,post_float64_nonfinite_values,post_float32_nonfinite_values,maximum_absolute_standardized_value
0,benign_test,1,13727,13727,10,0,0,2.473136e+02
1,development_validation,21,1339934,1339934,1516,0,0,2.365808e+03
2,known_test,20,1326235,1326235,25560,0,0,4.807810e+12
3,zero_day_attack_test,12,30918665,30918665,3334,0,0,8.433646e+05

[7] Partition row-count validation
------------------------------------------------------------------------------
development_validation    expected=   1,339,934 processed=   1,339,934 match=True
known_test                expected=   1,326,235 processed=   1,326,235 match=True
benign_test               expected=      13,727 processed=      13,727 match=True
zero_day_attack_test      expected=  30,918,665 processed=  30,918,665 match=True

[8] Frozen transformation validity
------------------------------------------------------------------------------
Raw non-finite values encountered : 30,420
Non-finite after float64 transform: 0
Non-finite after float32 transform: 0
All source ranges passed          : True

[9] Leakage-safety verification
------------------------------------------------------------------------------
DDoS rows outside zero-day test: 0
Non-DDoS rows in zero-day attack test: 0
Parameters refitted: False
Leakage-safe: True

[10] Final Step 9.3 validation
------------------------------------------------------------------------------
Frozen parameters valid          : True
All partition row counts exact   : True
All float64 transformed finite   : True
All float32 transformed finite   : True
All source ranges passed         : True
Held-out isolation preserved     : True
Audit artifacts saved            : True

==============================================================================
✅ STEP 9.3 PASSED — Frozen Fold-1 preprocessing was safely applied to all validation and test partitions without refitting.
==============================================================================

# STEP 9.4A — Find Which Source Range Has the Extreme Value

In [ ]:
# ======================================================================
# STEP 9.4A — LOCATE EXTREME STANDARDIZED SOURCE RANGES
# ======================================================================

import pandas as pd
import numpy as np

print("=" * 78)
print("STEP 9.4A — LOCATE EXTREME STANDARDIZED SOURCE RANGES")
print("=" * 78)


# ======================================================================
# 1 — VERIFY STEP 9.3 STATE
# ======================================================================

print("\n[1] Verifying Step 9.3 state")
print("-" * 78)

required_variables = [
    "STEP_9_3_VALID",
    "APPLICATION_AUDIT"
]

missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Step 9.3."
    )

if not STEP_9_3_VALID:
    raise RuntimeError(
        "Step 9.3 did not pass."
    )

print("✅ Step 9.3 state is available.")


# ======================================================================
# 2 — SORT SOURCE RANGES BY MAXIMUM ABSOLUTE Z-VALUE
# ======================================================================

print("\n[2] Largest standardized values by source range")
print("-" * 78)

extreme_ranges = (
    APPLICATION_AUDIT[
        [
            "partition",
            "source_attack_class",
            "research_family",
            "processed_rows",
            "raw_nonfinite_values",
            "maximum_absolute_standardized_value"
        ]
    ]
    .sort_values(
        "maximum_absolute_standardized_value",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    extreme_ranges.head(15)
)


# ======================================================================
# 3 — WORST RANGE PER PARTITION
# ======================================================================

print("\n[3] Worst source range in each partition")
print("-" * 78)

worst_by_partition = (
    extreme_ranges
    .sort_values(
        "maximum_absolute_standardized_value",
        ascending=False
    )
    .groupby(
        "partition",
        as_index=False
    )
    .first()
    .sort_values(
        "maximum_absolute_standardized_value",
        ascending=False
    )
    .reset_index(drop=True)
)

display(
    worst_by_partition
)


# ======================================================================
# 4 — TRAINING SCALER STDS
# ======================================================================

print("\n[4] Smallest Fold-1 training standard deviations")
print("-" * 78)

smallest_training_stds = (
    PREPROCESSING_PARAMETERS[
        PREPROCESSING_PARAMETERS[
            "retained_feature"
        ]
    ][
        [
            "feature",
            "scaler_mean",
            "scaler_std",
            "finite_min",
            "finite_max"
        ]
    ]
    .sort_values(
        "scaler_std",
        ascending=True
    )
    .reset_index(drop=True)
)

display(
    smallest_training_stds.head(15)
)


# ======================================================================
# 5 — FINAL SUMMARY
# ======================================================================

worst_row = extreme_ranges.iloc[0]

print("\n[5] Diagnostic summary")
print("-" * 78)

print(
    "Worst partition    :",
    worst_row["partition"]
)

print(
    "Worst source class :",
    worst_row["source_attack_class"]
)

print(
    "Research family    :",
    worst_row["research_family"]
)

print(
    "Maximum absolute Z :",
    f"{worst_row['maximum_absolute_standardized_value']:.6e}"
)

print("\n" + "=" * 78)
print(
    "✅ STEP 9.4A COMPLETE — "
    "Extreme source range has been identified."
)
print("=" * 78)

==============================================================================
STEP 9.4A — LOCATE EXTREME STANDARDIZED SOURCE RANGES
==============================================================================

[1] Verifying Step 9.3 state
------------------------------------------------------------------------------

RuntimeError: Missing variables: STEP_9_3_VALID, APPLICATION_AUDIT
Please rerun Step 9.3.

# Step 9.4A-R — Recover the saved Step 9.3 results

In [ ]:
# ======================================================================
# STEP 9.4A-R — RECOVER SAVED STEP 9.3 RESULTS
# ======================================================================

from pathlib import Path
import pandas as pd

print("=" * 72)
print("STEP 9.4A-R — RECOVER SAVED STEP 9.3 RESULTS")
print("=" * 72)

# Saved Fold-1 folder
FOLD_PREPROCESSING_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/preprocessing/fold_01_DDoS"
)

APPLICATION_AUDIT_PATH = (
    FOLD_PREPROCESSING_DIR
    / "nontraining_preprocessing_application_audit.csv"
)

PREPROCESSING_PARAMETERS_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

print("\n[1] Checking saved files")
print("-" * 72)

print(
    "Step 9.3 audit exists :",
    APPLICATION_AUDIT_PATH.exists()
)

print(
    "Step 9.1 parameters exist :",
    PREPROCESSING_PARAMETERS_PATH.exists()
)


# ----------------------------------------------------------------------
# If files disappeared, STOP safely
# ----------------------------------------------------------------------

if not APPLICATION_AUDIT_PATH.exists():

    print("\n❌ Step 9.3 saved audit is missing.")

    print(
        "This means Colab probably cleared "
        "the /content storage."
    )

    print(
        "\nSTOP HERE and send me this output."
    )

else:

    # ------------------------------------------------------------------
    # Reload Step 9.3 audit
    # ------------------------------------------------------------------

    APPLICATION_AUDIT = pd.read_csv(
        APPLICATION_AUDIT_PATH
    )

    print("\n[2] Step 9.3 audit restored")
    print("-" * 72)

    print(
        "Audit rows:",
        len(APPLICATION_AUDIT)
    )

    # ------------------------------------------------------------------
    # Revalidate saved result
    # ------------------------------------------------------------------

    row_counts_ok = bool(
        (
            APPLICATION_AUDIT["expected_rows"]
            ==
            APPLICATION_AUDIT["processed_rows"]
        ).all()
    )

    float64_ok = bool(
        (
            APPLICATION_AUDIT[
                "post_float64_nonfinite_values"
            ]
            ==
            0
        ).all()
    )

    float32_ok = bool(
        (
            APPLICATION_AUDIT[
                "post_float32_nonfinite_values"
            ]
            ==
            0
        ).all()
    )

    statuses_ok = bool(
        (
            APPLICATION_AUDIT["status"]
            ==
            "PASS"
        ).all()
    )

    ddoS_outside_zero_day = int(
        APPLICATION_AUDIT.loc[
            (
                APPLICATION_AUDIT[
                    "research_family"
                ]
                ==
                "DDoS"
            )
            &
            (
                APPLICATION_AUDIT[
                    "partition"
                ]
                !=
                "zero_day_attack_test"
            ),
            "processed_rows"
        ].sum()
    )

    non_ddos_inside_zero_day = int(
        APPLICATION_AUDIT.loc[
            (
                APPLICATION_AUDIT[
                    "partition"
                ]
                ==
                "zero_day_attack_test"
            )
            &
            (
                APPLICATION_AUDIT[
                    "research_family"
                ]
                !=
                "DDoS"
            ),
            "processed_rows"
        ].sum()
    )

    STEP_9_3_VALID = bool(
        len(APPLICATION_AUDIT) == 54
        and row_counts_ok
        and float64_ok
        and float32_ok
        and statuses_ok
        and ddoS_outside_zero_day == 0
        and non_ddos_inside_zero_day == 0
    )

    print(
        "Row counts exact       :",
        row_counts_ok
    )

    print(
        "Float64 outputs finite :",
        float64_ok
    )

    print(
        "Float32 outputs finite :",
        float32_ok
    )

    print(
        "All statuses PASS      :",
        statuses_ok
    )

    print(
        "DDoS outside zero-day  :",
        ddoS_outside_zero_day
    )

    print(
        "Non-DDoS in zero-day   :",
        non_ddos_inside_zero_day
    )

    print("\n" + "=" * 72)

    if STEP_9_3_VALID:

        print(
            "✅ STEP 9.4A-R PASSED — "
            "Step 9.3 state recovered successfully."
        )

    else:

        print(
            "❌ STEP 9.4A-R FAILED — "
            "Do not continue yet."
        )

    print("=" * 72)

========================================================================
STEP 9.4A-R — RECOVER SAVED STEP 9.3 RESULTS
========================================================================

[1] Checking saved files
------------------------------------------------------------------------
Step 9.3 audit exists : False
Step 9.1 parameters exist : False

❌ Step 9.3 saved audit is missing.
This means Colab probably cleared the /content storage.

STOP HERE and send me this output.

# Recovery Step R1 — Check what files remain

In [ ]:
# ======================================================================
# RECOVERY STEP R1 — CHECK WHAT SURVIVED THE COLAB RESET
# ======================================================================

from pathlib import Path

print("=" * 72)
print("RECOVERY STEP R1 — CHECK PROJECT STORAGE")
print("=" * 72)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

RAW_DATA_DIR = (
    PROJECT_ROOT
    / "dataset"
    / "timestamp_coverage"
)

SORTED_DATA_DIR = (
    PROJECT_ROOT
    / "dataset"
    / "chronological_parquet"
)

AUDIT_DIR = (
    PROJECT_ROOT
    / "dataset_audit"
)

PROCESSED_DIR = (
    PROJECT_ROOT
    / "processed_data"
)

print("\nProject root exists       :", PROJECT_ROOT.exists())
print("Raw dataset folder exists :", RAW_DATA_DIR.exists())
print("Sorted dataset exists     :", SORTED_DATA_DIR.exists())
print("Audit folder exists        :", AUDIT_DIR.exists())
print("Processed folder exists    :", PROCESSED_DIR.exists())


# ----------------------------------------------------------------------
# Count raw CSV files
# ----------------------------------------------------------------------

raw_files = []

if RAW_DATA_DIR.exists():
    raw_files = list(
        RAW_DATA_DIR.rglob("*.csv")
    )

print(
    "\nRaw CSV files found        :",
    len(raw_files)
)


# ----------------------------------------------------------------------
# Count sorted Parquet files
# ----------------------------------------------------------------------

sorted_files = []

if SORTED_DATA_DIR.exists():
    sorted_files = list(
        SORTED_DATA_DIR.glob("*.parquet")
    )

print(
    "Sorted Parquet files found :",
    len(sorted_files)
)


# ----------------------------------------------------------------------
# Count audit / processed artifacts
# ----------------------------------------------------------------------

audit_files = []

if AUDIT_DIR.exists():
    audit_files = list(
        AUDIT_DIR.rglob("*")
    )

audit_files = [
    path
    for path in audit_files
    if path.is_file()
]


processed_files = []

if PROCESSED_DIR.exists():
    processed_files = list(
        PROCESSED_DIR.rglob("*")
    )

processed_files = [
    path
    for path in processed_files
    if path.is_file()
]

print(
    "Audit files found          :",
    len(audit_files)
)

print(
    "Processed files found      :",
    len(processed_files)
)


# ----------------------------------------------------------------------
# Google Drive status
# ----------------------------------------------------------------------

DRIVE_ROOT = Path(
    "/content/drive/MyDrive"
)

print(
    "\nGoogle Drive currently mounted:",
    DRIVE_ROOT.exists()
)


print("\n" + "=" * 72)
print("✅ RECOVERY STEP R1 COMPLETE")
print("=" * 72)

========================================================================
RECOVERY STEP R1 — CHECK PROJECT STORAGE
========================================================================

Project root exists       : False
Raw dataset folder exists : False
Sorted dataset exists     : False
Audit folder exists        : False
Processed folder exists    : False

Raw CSV files found        : 0
Sorted Parquet files found : 0
Audit files found          : 0
Processed files found      : 0

Google Drive currently mounted: False

========================================================================
✅ RECOVERY STEP R1 COMPLETE
========================================================================

# Recovery Step R2 — Mount Google Drive

In [ ]:
# ======================================================================
# RECOVERY STEP R2 — MOUNT GOOGLE DRIVE FOR PERSISTENT BACKUP
# ======================================================================

from google.colab import drive
from pathlib import Path

print("=" * 72)
print("RECOVERY STEP R2 — MOUNT GOOGLE DRIVE")
print("=" * 72)

# Mount Google Drive
drive.mount(
    "/content/drive"
)

# Persistent project location
DRIVE_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

DRIVE_PROJECT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

# Important persistent subfolders
DRIVE_BACKUP_DIRS = {
    "sorted_dataset":
        DRIVE_PROJECT_ROOT / "chronological_parquet",

    "dataset_audit":
        DRIVE_PROJECT_ROOT / "dataset_audit",

    "processed_data":
        DRIVE_PROJECT_ROOT / "processed_data",

    "models":
        DRIVE_PROJECT_ROOT / "models",

    "checkpoints":
        DRIVE_PROJECT_ROOT / "checkpoints",

    "predictions":
        DRIVE_PROJECT_ROOT / "predictions",

    "metrics":
        DRIVE_PROJECT_ROOT / "metrics",

    "figures":
        DRIVE_PROJECT_ROOT / "figures"
}

for folder in DRIVE_BACKUP_DIRS.values():
    folder.mkdir(
        parents=True,
        exist_ok=True
    )

print("\nGoogle Drive mounted :",
      Path("/content/drive/MyDrive").exists())

print(
    "Backup folder exists:",
    DRIVE_PROJECT_ROOT.exists()
)

print(
    "\nPersistent backup location:"
)

print(
    DRIVE_PROJECT_ROOT
)

print("\nCreated backup folders:")

for name, path in DRIVE_BACKUP_DIRS.items():
    print(
        f"  {name:<18}: {path.exists()}"
    )

print("\n" + "=" * 72)
print("✅ RECOVERY STEP R2 COMPLETE")
print("=" * 72)

========================================================================
RECOVERY STEP R2 — MOUNT GOOGLE DRIVE
========================================================================
Mounted at /content/drive

Google Drive mounted : True
Backup folder exists: True

Persistent backup location:
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup

Created backup folders:
  sorted_dataset    : True
  dataset_audit     : True
  processed_data    : True
  models            : True
  checkpoints       : True
  predictions       : True
  metrics           : True
  figures           : True

========================================================================
✅ RECOVERY STEP R2 COMPLETE
========================================================================

# Recovery Step R3 — Redownload the exact 33 source files

In [ ]:
# ======================================================================
# RECOVERY STEP R3 — REBUILD PROJECT + REDOWNLOAD EXACT 33 CSV FILES
# ======================================================================

from pathlib import Path
import shutil
import subprocess
import sys
import time
import pandas as pd

print("=" * 78)
print("RECOVERY STEP R3 — REBUILD PROJECT + REDOWNLOAD EXACT 33 CSV FILES")
print("=" * 78)


# ======================================================================
# 1 — REBUILD PROJECT DIRECTORIES
# ======================================================================

print("\n[1] Rebuilding temporary Colab project")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

DIRECTORIES = {
    "dataset":
        PROJECT_ROOT / "dataset",

    "dataset_audit":
        PROJECT_ROOT / "dataset_audit",

    "processed_data":
        PROJECT_ROOT / "processed_data",

    "models":
        PROJECT_ROOT / "models",

    "checkpoints":
        PROJECT_ROOT / "checkpoints",

    "predictions":
        PROJECT_ROOT / "predictions",

    "metrics":
        PROJECT_ROOT / "metrics",

    "figures":
        PROJECT_ROOT / "figures",

    "logs":
        PROJECT_ROOT / "logs",

    "sensitivity":
        PROJECT_ROOT / "sensitivity",

    "ablation":
        PROJECT_ROOT / "ablation",

    "statistics":
        PROJECT_ROOT / "statistics",

    "final_exports":
        PROJECT_ROOT / "final_exports"
}

for folder in DIRECTORIES.values():
    folder.mkdir(
        parents=True,
        exist_ok=True
    )


DATASET_ROOT = (
    DIRECTORIES["dataset"]
    / "timestamp_coverage"
)

DATASET_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "Project root:",
    PROJECT_ROOT
)

print(
    "Dataset root:",
    DATASET_ROOT
)

print(
    "✅ Project directories rebuilt."
)


# ======================================================================
# 2 — INSTALL / IMPORT HUGGING FACE HUB
# ======================================================================

print("\n[2] Preparing download client")
print("-" * 78)

try:
    from huggingface_hub import hf_hub_download

except ImportError:

    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "huggingface_hub"
    ])

    from huggingface_hub import hf_hub_download


print(
    "✅ huggingface_hub is ready."
)


# ======================================================================
# 3 — EXACT SOURCE REPOSITORY
# ======================================================================

REPO_ID = "somnath0100/CICIoT2023Small"

print("\n[3] Repository")
print("-" * 78)

print(
    "Dataset repository:",
    REPO_ID
)


# ======================================================================
# 4 — EXACT 33 FILES USED IN OUR EXPERIMENT
# ======================================================================

SELECTED_REPO_FILES = [

    "CSVS/Backdoor_Malware/Backdoor_Malware_1.csv",

    "CSVS/Benign_Final/Benign_1.csv",

    "CSVS/BrowserHijacking/BrowserHijacking_1.csv",

    "CSVS/CommandInjection/CommandInjection_1.csv",

    "CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fragmentation_1.csv",

    "CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.csv",

    "CSVS/DDoS-ICMP_Flood/DDoS-ICMP_Flood_1.csv",

    "CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_Fragmentation_1.csv",

    "CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood_1.csv",

    "CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.pcap_Flow.csv",

    "CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_Flow.csv",

    "CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_Flow.csv",

    "CSVS/DDoS-SynonymousIP_Flood/DDoS-SynonymousIP_Flood.pcap_Flow.csv",

    "CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_Flow.csv",

    "CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_Flow.csv",

    "CSVS/DDoS-UDP_Fragmentation/DDoS-UDP_Fragmentation.pcap_Flow.csv",

    "CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow.csv",

    "CSVS/DictionaryBruteForce/DictionaryBruteForce.pcap_Flow.csv",

    "CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_Flow.csv",

    "CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Flow.csv",

    "CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Flow.csv",

    "CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Flow.csv",

    "CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.pcap_Flow.csv",

    "CSVS/Mirai-greeth_flood/Mirai-greeth_flood.pcap_Flow.csv",

    "CSVS/Mirai-greip_flood/Mirai-greip_flood.pcap_Flow.csv",

    "CSVS/Mirai-udpplain/Mirai-udpplain.pcap_Flow.csv",

    "CSVS/Recon-HostDiscovery/Recon-HostDiscovery.pcap_Flow.csv",

    "CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow.csv",

    "CSVS/Recon-PingSweep/Recon-PingSweep.pcap_Flow.csv",

    "CSVS/Recon-PortScan/Recon-PortScan.pcap_Flow.csv",

    "CSVS/SqlInjection/SqlInjection.pcap_Flow.csv",

    "CSVS/VulnerabilityScan/VulnerabilityScan.pcap_Flow.csv",

    "CSVS/XSS/XSS.pcap_Flow.csv"
]


if len(SELECTED_REPO_FILES) != 33:
    raise RuntimeError(
        "Expected exactly 33 selected files."
    )


print("\n[4] Selected-file manifest")
print("-" * 78)

print(
    "Selected files:",
    len(SELECTED_REPO_FILES)
)

print(
    "✅ Exact 33-file list restored."
)


# ======================================================================
# 5 — EXPECTED ROW COUNTS FROM OUR VERIFIED DATASET
# ======================================================================

EXPECTED_ROWS = {

    "Backdoor_Malware":
        2703,

    "Benign_Final":
        91506,

    "BrowserHijacking":
        3286,

    "CommandInjection":
        3848,

    "DDoS-ACK_Fragmentation":
        37296,

    "DDoS-HTTP_Flood":
        513672,

    "DDoS-ICMP_Flood":
        7834,

    "DDoS-ICMP_Fragmentation":
        25106,

    "DDoS-PSHACK_Flood":
        5007067,

    "DDoS-RSTFINFlood":
        12968618,

    "DDoS-SYN_Flood":
        6366353,

    "DDoS-SlowLoris":
        196578,

    "DDoS-SynonymousIP_Flood":
        799351,

    "DDoS-TCP_Flood":
        4945887,

    "DDoS-UDP_Flood":
        41146,

    "DDoS-UDP_Fragmentation":
        9757,

    "DNS_Spoofing":
        74938,

    "DictionaryBruteForce":
        8488,

    "DoS-HTTP_Flood":
        965554,

    "DoS-SYN_Flood":
        3997110,

    "DoS-TCP_Flood":
        1638068,

    "DoS-UDP_Flood":
        934009,

    "MITM-ArpSpoofing":
        72853,

    "Mirai-greeth_flood":
        5155,

    "Mirai-greip_flood":
        10401,

    "Mirai-udpplain":
        7455,

    "Recon-HostDiscovery":
        329985,

    "Recon-OSScan":
        158682,

    "Recon-PingSweep":
        1947,

    "Recon-PortScan":
        175050,

    "SqlInjection":
        6596,

    "VulnerabilityScan":
        442122,

    "XSS":
        3198
}


TOTAL_ROWS = int(
    sum(
        EXPECTED_ROWS.values()
    )
)


print(
    "Expected total rows:",
    f"{TOTAL_ROWS:,}"
)


if TOTAL_ROWS != 39_851_619:

    raise RuntimeError(
        "Expected row-total constant is incorrect."
    )


# ======================================================================
# 6 — STORAGE CHECK
# ======================================================================

print("\n[5] Checking Colab storage")
print("-" * 78)


disk = shutil.disk_usage(
    "/content"
)


free_gb = (
    disk.free
    /
    (1024 ** 3)
)


print(
    "Free /content storage:",
    f"{free_gb:.2f} GB"
)


if free_gb < 25:

    raise RuntimeError(
        "Less than 25 GB free. "
        "Do not start the 18.5 GB dataset download."
    )


print(
    "✅ Enough temporary storage is available."
)


# ======================================================================
# 7 — DOWNLOAD EXACT FILES
# ======================================================================

print("\n[6] Downloading exact 33 selected files")
print("-" * 78)

print(
    "Large files can take time."
)

print(
    "Completed Hugging Face downloads can be reused "
    "if this cell is rerun."
)


download_records = []

DATA_FILES = []


for index, repo_path in enumerate(
    SELECTED_REPO_FILES,
    start=1
):

    parts = Path(
        repo_path
    ).parts

    source_class = parts[-2]

    expected_file_name = parts[-1]


    print("\n" + "=" * 78)

    print(
        f"DOWNLOAD {index:02d}/33"
    )

    print(
        "Class :",
        source_class
    )

    print(
        "File  :",
        expected_file_name
    )


    start_time = time.time()


    downloaded_path = Path(

        hf_hub_download(

            repo_id=
                REPO_ID,

            repo_type=
                "dataset",

            filename=
                repo_path,

            local_dir=
                DATASET_ROOT
        )
    )


    if not downloaded_path.exists():

        raise RuntimeError(
            f"Download failed: {repo_path}"
        )


    if downloaded_path.stat().st_size == 0:

        raise RuntimeError(
            f"Downloaded file is empty: {repo_path}"
        )


    elapsed = (
        time.time()
        -
        start_time
    )


    file_size_gb = (

        downloaded_path.stat().st_size

        /

        (1024 ** 3)
    )


    print(
        "✅ Downloaded"
    )

    print(
        "Size:",
        f"{file_size_gb:.3f} GB"
    )

    print(
        "Time:",
        f"{elapsed / 60:.2f} minutes"
    )


    DATA_FILES.append(
        downloaded_path
    )


    download_records.append({

        "source_attack_class":
            source_class,

        "repo_path":
            repo_path,

        "local_path":
            str(
                downloaded_path.resolve()
            ),

        "file_name":
            downloaded_path.name,

        "expected_rows":
            EXPECTED_ROWS[
                source_class
            ],

        "size_bytes":
            downloaded_path.stat().st_size,

        "size_gb":
            file_size_gb,

        "status":
            "DOWNLOADED"
    })


# ======================================================================
# 8 — BASIC FILE VALIDATION
# ======================================================================

print("\n[7] Basic validation")
print("-" * 78)


missing_files = [
    str(path)
    for path in DATA_FILES
    if not path.exists()
]


empty_files = [
    str(path)
    for path in DATA_FILES
    if (
        path.exists()
        and
        path.stat().st_size == 0
    )
]


print(
    "Expected files:",
    33
)

print(
    "Available files:",
    len(DATA_FILES)
)

print(
    "Missing files:",
    len(missing_files)
)

print(
    "Empty files:",
    len(empty_files)
)


if missing_files:
    print("\nMissing:")
    for path in missing_files:
        print(" -", path)


if empty_files:
    print("\nEmpty:")
    for path in empty_files:
        print(" -", path)


# ======================================================================
# 9 — VERIFY REQUIRED COLUMNS ON ALL 33 FILES
# ======================================================================

print("\n[8] Checking Timestamp + Label columns")
print("-" * 78)


schema_records = []


for index, file_path in enumerate(
    DATA_FILES,
    start=1
):

    header = pd.read_csv(
        file_path,
        nrows=0
    )


    columns = list(
        header.columns
    )


    timestamp_present = (
        "Timestamp"
        in columns
    )


    label_present = (
        "Label"
        in columns
    )


    source_class = (
        Path(file_path)
        .parent
        .name
    )


    schema_records.append({

        "source_attack_class":
            source_class,

        "file_name":
            file_path.name,

        "column_count":
            len(columns),

        "timestamp_present":
            timestamp_present,

        "label_present":
            label_present
    })


    print(
        f"{index:02d}/33 "
        f"{source_class:<30} "
        f"columns={len(columns):>2} "
        f"Timestamp={timestamp_present} "
        f"Label={label_present}"
    )


schema_table = pd.DataFrame(
    schema_records
)


ALL_TIMESTAMP_PRESENT = bool(

    schema_table[
        "timestamp_present"
    ].all()
)


ALL_LABEL_PRESENT = bool(

    schema_table[
        "label_present"
    ].all()
)


# ======================================================================
# 10 — SAVE RECOVERY MANIFEST
# ======================================================================

print("\n[9] Saving recovery manifest")
print("-" * 78)


RECOVERY_MANIFEST = pd.DataFrame(
    download_records
)


RECOVERY_MANIFEST_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_recovery_selected_files.csv"
)


RECOVERY_SCHEMA_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_recovery_schema_check.csv"
)


RECOVERY_MANIFEST.to_csv(

    RECOVERY_MANIFEST_PATH,

    index=False
)


schema_table.to_csv(

    RECOVERY_SCHEMA_PATH,

    index=False
)


print(
    "Manifest:",
    RECOVERY_MANIFEST_PATH
)

print(
    "Schema audit:",
    RECOVERY_SCHEMA_PATH
)


# ======================================================================
# 11 — SAVE SMALL RECOVERY ARTIFACTS TO GOOGLE DRIVE
# ======================================================================

print("\n[10] Backing up recovery metadata to Google Drive")
print("-" * 78)


DRIVE_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


DRIVE_AUDIT_DIR = (

    DRIVE_PROJECT_ROOT

    / "dataset_audit"
)


DRIVE_AUDIT_DIR.mkdir(

    parents=True,

    exist_ok=True
)


shutil.copy2(

    RECOVERY_MANIFEST_PATH,

    DRIVE_AUDIT_DIR
    /
    RECOVERY_MANIFEST_PATH.name
)


shutil.copy2(

    RECOVERY_SCHEMA_PATH,

    DRIVE_AUDIT_DIR
    /
    RECOVERY_SCHEMA_PATH.name
)


print(
    "✅ Recovery metadata backed up to Drive."
)


# ======================================================================
# 12 — FINAL SUMMARY
# ======================================================================

total_download_size_gb = sum(

    path.stat().st_size

    for path in DATA_FILES

) / (1024 ** 3)


final_free_gb = (

    shutil.disk_usage(
        "/content"
    ).free

    /

    (1024 ** 3)
)


R3_VALID = (

    len(DATA_FILES) == 33

    and

    len(missing_files) == 0

    and

    len(empty_files) == 0

    and

    ALL_TIMESTAMP_PRESENT

    and

    ALL_LABEL_PRESENT

    and

    RECOVERY_MANIFEST_PATH.exists()

    and

    RECOVERY_SCHEMA_PATH.exists()
)


print("\n[11] Recovery Step R3 summary")
print("-" * 78)

print(
    "Files recovered       :",
    len(DATA_FILES),
    "/ 33"
)

print(
    "Expected dataset rows :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Timestamp in all files:",
    ALL_TIMESTAMP_PRESENT
)

print(
    "Label in all files    :",
    ALL_LABEL_PRESENT
)

print(
    "Downloaded size       :",
    f"{total_download_size_gb:.2f} GB"
)

print(
    "Free disk remaining   :",
    f"{final_free_gb:.2f} GB"
)


print("\n" + "=" * 78)


if R3_VALID:

    print(
        "✅ RECOVERY STEP R3 PASSED — "
        "The exact 33-file dataset has been restored."
    )

else:

    print(
        "❌ RECOVERY STEP R3 FAILED — "
        "Do not continue yet."
    )


print("=" * 78)

==============================================================================
RECOVERY STEP R3 — REBUILD PROJECT + REDOWNLOAD EXACT 33 CSV FILES
==============================================================================

[1] Rebuilding temporary Colab project
------------------------------------------------------------------------------
Project root: /content/ZeroDay_IoT_Research
Dataset root: /content/ZeroDay_IoT_Research/dataset/timestamp_coverage
✅ Project directories rebuilt.

[2] Preparing download client
------------------------------------------------------------------------------
✅ huggingface_hub is ready.

[3] Repository
------------------------------------------------------------------------------
Dataset repository: somnath0100/CICIoT2023Small

[4] Selected-file manifest
------------------------------------------------------------------------------
Selected files: 33
✅ Exact 33-file list restored.
Expected total rows: 39,851,619

[5] Checking Colab storage
------------------------------------------------------------------------------
Free /content storage: 65.24 GB
✅ Enough temporary storage is available.

[6] Downloading exact 33 selected files
------------------------------------------------------------------------------
Large files can take time.
Completed Hugging Face downloads can be reused if this cell is rerun.

==============================================================================
DOWNLOAD 01/33
Class : Backdoor_Malware
File  : Backdoor_Malware_1.csv

Backdoor_Malware_1.csv:   0%|          | 0.00/1.59M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

✅ Downloaded
Size: 0.001 GB
Time: 0.04 minutes

==============================================================================
DOWNLOAD 02/33
Class : Benign_Final
File  : Benign_1.csv

CSVS/Benign_Final/Benign_1.csv: reconstructing file:   0%|          |  0.00B / 51.5MB

CSVS/Benign_Final/Benign_1.csv: downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.048 GB
Time: 0.17 minutes

==============================================================================
DOWNLOAD 03/33
Class : BrowserHijacking
File  : BrowserHijacking_1.csv

BrowserHijacking_1.csv:   0%|          | 0.00/1.91M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.002 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 04/33
Class : CommandInjection
File  : CommandInjection_1.csv

CommandInjection_1.csv:   0%|          | 0.00/2.19M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.002 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 05/33
Class : DDoS-ACK_Fragmentation
File  : DDoS-ACK_Fragmentation_1.csv

CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fra(…): reconstructing file:   0%|          |  0.00B / 20.5MB

CSVS/DDoS-ACK_Fragmentation/DDoS-ACK_Fra(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.019 GB
Time: 0.04 minutes

==============================================================================
DOWNLOAD 06/33
Class : DDoS-HTTP_Flood
File  : DDoS-HTTP_Flood_1.csv

CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.c(…): reconstructing file:   0%|          |  0.00B /  267MB

CSVS/DDoS-HTTP_Flood/DDoS-HTTP_Flood_1.c(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.248 GB
Time: 0.10 minutes

==============================================================================
DOWNLOAD 07/33
Class : DDoS-ICMP_Flood
File  : DDoS-ICMP_Flood_1.csv

DDoS-ICMP_Flood_1.csv:   0%|          | 0.00/4.37M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.004 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 08/33
Class : DDoS-ICMP_Fragmentation
File  : DDoS-ICMP_Fragmentation_1.csv

CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_F(…): reconstructing file:   0%|          |  0.00B / 14.2MB

CSVS/DDoS-ICMP_Fragmentation/DDoS-ICMP_F(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.013 GB
Time: 0.03 minutes

==============================================================================
DOWNLOAD 09/33
Class : DDoS-PSHACK_Flood
File  : DDoS-PSHACK_Flood_1.csv

CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood(…): reconstructing file:   0%|          |  0.00B / 2.70GB

CSVS/DDoS-PSHACK_Flood/DDoS-PSHACK_Flood(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 2.511 GB
Time: 0.33 minutes

==============================================================================
DOWNLOAD 10/33
Class : DDoS-RSTFINFlood
File  : DDoS-RSTFINFlood.pcap_Flow.csv

CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.p(…): reconstructing file:   0%|          |  0.00B / 5.97GB

CSVS/DDoS-RSTFINFlood/DDoS-RSTFINFlood.p(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 5.557 GB
Time: 0.66 minutes

==============================================================================
DOWNLOAD 11/33
Class : DDoS-SYN_Flood
File  : DDoS-SYN_Flood.pcap_Flow.csv

CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 3.27GB

CSVS/DDoS-SYN_Flood/DDoS-SYN_Flood.pcap_(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 3.045 GB
Time: 0.42 minutes

==============================================================================
DOWNLOAD 12/33
Class : DDoS-SlowLoris
File  : DDoS-SlowLoris.pcap_Flow.csv

CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_(…): reconstructing file:   0%|          |  0.00B /  114MB

CSVS/DDoS-SlowLoris/DDoS-SlowLoris.pcap_(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.106 GB
Time: 0.07 minutes

==============================================================================
DOWNLOAD 13/33
Class : DDoS-SynonymousIP_Flood
File  : DDoS-SynonymousIP_Flood.pcap_Flow.csv

CSVS/DDoS-SynonymousIP_Flood/DDoS-Synony(…): reconstructing file:   0%|          |  0.00B /  445MB

CSVS/DDoS-SynonymousIP_Flood/DDoS-Synony(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.414 GB
Time: 0.07 minutes

==============================================================================
DOWNLOAD 14/33
Class : DDoS-TCP_Flood
File  : DDoS-TCP_Flood.pcap_Flow.csv

CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 2.55GB

CSVS/DDoS-TCP_Flood/DDoS-TCP_Flood.pcap_(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 2.375 GB
Time: 0.36 minutes

==============================================================================
DOWNLOAD 15/33
Class : DDoS-UDP_Flood
File  : DDoS-UDP_Flood.pcap_Flow.csv

CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B / 20.6MB

CSVS/DDoS-UDP_Flood/DDoS-UDP_Flood.pcap_(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.019 GB
Time: 0.04 minutes

==============================================================================
DOWNLOAD 16/33
Class : DDoS-UDP_Fragmentation
File  : DDoS-UDP_Fragmentation.pcap_Flow.csv

DDoS-UDP_Fragmentation.pcap_Flow.csv:   0%|          | 0.00/5.30M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.005 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 17/33
Class : DNS_Spoofing
File  : DNS_Spoofing.pcap_Flow.csv

CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow(…): reconstructing file:   0%|          |  0.00B / 40.6MB

CSVS/DNS_Spoofing/DNS_Spoofing.pcap_Flow(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.038 GB
Time: 0.04 minutes

==============================================================================
DOWNLOAD 18/33
Class : DictionaryBruteForce
File  : DictionaryBruteForce.pcap_Flow.csv

DictionaryBruteForce.pcap_Flow.csv:   0%|          | 0.00/4.69M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.004 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 19/33
Class : DoS-HTTP_Flood
File  : DoS-HTTP_Flood.pcap_Flow.csv

CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_(…): reconstructing file:   0%|          |  0.00B /  417MB

CSVS/DoS-HTTP_Flood/DoS-HTTP_Flood.pcap_(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.388 GB
Time: 0.06 minutes

==============================================================================
DOWNLOAD 20/33
Class : DoS-SYN_Flood
File  : DoS-SYN_Flood.pcap_Flow.csv

CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B / 2.06GB

CSVS/DoS-SYN_Flood/DoS-SYN_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 1.922 GB
Time: 1.05 minutes

==============================================================================
DOWNLOAD 21/33
Class : DoS-TCP_Flood
File  : DoS-TCP_Flood.pcap_Flow.csv

CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B /  832MB

CSVS/DoS-TCP_Flood/DoS-TCP_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.774 GB
Time: 0.11 minutes

==============================================================================
DOWNLOAD 22/33
Class : DoS-UDP_Flood
File  : DoS-UDP_Flood.pcap_Flow.csv

CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Fl(…): reconstructing file:   0%|          |  0.00B /  522MB

CSVS/DoS-UDP_Flood/DoS-UDP_Flood.pcap_Fl(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.487 GB
Time: 0.21 minutes

==============================================================================
DOWNLOAD 23/33
Class : MITM-ArpSpoofing
File  : MITM-ArpSpoofing.pcap_Flow.csv

CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.p(…): reconstructing file:   0%|          |  0.00B / 38.2MB

CSVS/MITM-ArpSpoofing/MITM-ArpSpoofing.p(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.036 GB
Time: 0.04 minutes

==============================================================================
DOWNLOAD 24/33
Class : Mirai-greeth_flood
File  : Mirai-greeth_flood.pcap_Flow.csv

Mirai-greeth_flood.pcap_Flow.csv:   0%|          | 0.00/2.69M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.003 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 25/33
Class : Mirai-greip_flood
File  : Mirai-greip_flood.pcap_Flow.csv

Mirai-greip_flood.pcap_Flow.csv:   0%|          | 0.00/5.60M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.005 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 26/33
Class : Mirai-udpplain
File  : Mirai-udpplain.pcap_Flow.csv

Mirai-udpplain.pcap_Flow.csv:   0%|          | 0.00/3.97M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.004 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 27/33
Class : Recon-HostDiscovery
File  : Recon-HostDiscovery.pcap_Flow.csv

CSVS/Recon-HostDiscovery/Recon-HostDisco(…): reconstructing file:   0%|          |  0.00B /  141MB

CSVS/Recon-HostDiscovery/Recon-HostDisco(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.131 GB
Time: 0.05 minutes

==============================================================================
DOWNLOAD 28/33
Class : Recon-OSScan
File  : Recon-OSScan.pcap_Flow.csv

CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow(…): reconstructing file:   0%|          |  0.00B / 72.1MB

CSVS/Recon-OSScan/Recon-OSScan.pcap_Flow(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.067 GB
Time: 0.05 minutes

==============================================================================
DOWNLOAD 29/33
Class : Recon-PingSweep
File  : Recon-PingSweep.pcap_Flow.csv

Recon-PingSweep.pcap_Flow.csv:   0%|          | 0.00/1.02M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.001 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 30/33
Class : Recon-PortScan
File  : Recon-PortScan.pcap_Flow.csv

CSVS/Recon-PortScan/Recon-PortScan.pcap_(…): reconstructing file:   0%|          |  0.00B / 77.5MB

CSVS/Recon-PortScan/Recon-PortScan.pcap_(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.072 GB
Time: 0.05 minutes

==============================================================================
DOWNLOAD 31/33
Class : SqlInjection
File  : SqlInjection.pcap_Flow.csv

SqlInjection.pcap_Flow.csv:   0%|          | 0.00/3.49M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.003 GB
Time: 0.01 minutes

==============================================================================
DOWNLOAD 32/33
Class : VulnerabilityScan
File  : VulnerabilityScan.pcap_Flow.csv

CSVS/VulnerabilityScan/VulnerabilityScan(…): reconstructing file:   0%|          |  0.00B /  226MB

CSVS/VulnerabilityScan/VulnerabilityScan(…): downloading bytes:           |  0.00B

✅ Downloaded
Size: 0.211 GB
Time: 0.07 minutes

==============================================================================
DOWNLOAD 33/33
Class : XSS
File  : XSS.pcap_Flow.csv

XSS.pcap_Flow.csv:   0%|          | 0.00/1.75M [00:00<?, ?B/s]

✅ Downloaded
Size: 0.002 GB
Time: 0.01 minutes

[7] Basic validation
------------------------------------------------------------------------------
Expected files: 33
Available files: 33
Missing files: 0
Empty files: 0

[8] Checking Timestamp + Label columns
------------------------------------------------------------------------------
01/33 Backdoor_Malware               columns=86 Timestamp=True Label=True
02/33 Benign_Final                   columns=86 Timestamp=True Label=True
03/33 BrowserHijacking               columns=86 Timestamp=True Label=True
04/33 CommandInjection               columns=86 Timestamp=True Label=True
05/33 DDoS-ACK_Fragmentation         columns=86 Timestamp=True Label=True
06/33 DDoS-HTTP_Flood                columns=86 Timestamp=True Label=True
07/33 DDoS-ICMP_Flood                columns=86 Timestamp=True Label=True
08/33 DDoS-ICMP_Fragmentation        columns=86 Timestamp=True Label=True
09/33 DDoS-PSHACK_Flood              columns=86 Timestamp=True Label=True
10/33 DDoS-RSTFINFlood               columns=84 Timestamp=True Label=True
11/33 DDoS-SYN_Flood                 columns=84 Timestamp=True Label=True
12/33 DDoS-SlowLoris                 columns=84 Timestamp=True Label=True
13/33 DDoS-SynonymousIP_Flood        columns=84 Timestamp=True Label=True
14/33 DDoS-TCP_Flood                 columns=84 Timestamp=True Label=True
15/33 DDoS-UDP_Flood                 columns=84 Timestamp=True Label=True
16/33 DDoS-UDP_Fragmentation         columns=84 Timestamp=True Label=True
17/33 DNS_Spoofing                   columns=84 Timestamp=True Label=True
18/33 DictionaryBruteForce           columns=84 Timestamp=True Label=True
19/33 DoS-HTTP_Flood                 columns=84 Timestamp=True Label=True
20/33 DoS-SYN_Flood                  columns=84 Timestamp=True Label=True
21/33 DoS-TCP_Flood                  columns=84 Timestamp=True Label=True
22/33 DoS-UDP_Flood                  columns=84 Timestamp=True Label=True
23/33 MITM-ArpSpoofing               columns=84 Timestamp=True Label=True
24/33 Mirai-greeth_flood             columns=84 Timestamp=True Label=True
25/33 Mirai-greip_flood              columns=84 Timestamp=True Label=True
26/33 Mirai-udpplain                 columns=84 Timestamp=True Label=True
27/33 Recon-HostDiscovery            columns=84 Timestamp=True Label=True
28/33 Recon-OSScan                   columns=84 Timestamp=True Label=True
29/33 Recon-PingSweep                columns=84 Timestamp=True Label=True
30/33 Recon-PortScan                 columns=84 Timestamp=True Label=True
31/33 SqlInjection                   columns=84 Timestamp=True Label=True
32/33 VulnerabilityScan              columns=84 Timestamp=True Label=True
33/33 XSS                            columns=84 Timestamp=True Label=True

[9] Saving recovery manifest
------------------------------------------------------------------------------
Manifest: /content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_recovery_selected_files.csv
Schema audit: /content/ZeroDay_IoT_Research/dataset_audit/CICIoT2023_recovery_schema_check.csv

[10] Backing up recovery metadata to Google Drive
------------------------------------------------------------------------------
✅ Recovery metadata backed up to Drive.

[11] Recovery Step R3 summary
------------------------------------------------------------------------------
Files recovered       : 33 / 33
Expected dataset rows : 39,851,619
Timestamp in all files: True
Label in all files    : True
Downloaded size       : 18.52 GB
Free disk remaining   : 46.72 GB

==============================================================================
✅ RECOVERY STEP R3 PASSED — The exact 33-file dataset has been restored.
==============================================================================

# Recovery Step R4 — Restore Experiment Metadata

In [ ]:
# ======================================================================
# RECOVERY STEP R4 — RESTORE EXPERIMENT METADATA AND CONFIGURATION
# ======================================================================

from pathlib import Path
import json
import shutil
import pandas as pd
import torch

print("=" * 78)
print("RECOVERY STEP R4 — RESTORE EXPERIMENT METADATA")
print("=" * 78)


# ======================================================================
# 1 — VERIFY R3 STATE
# ======================================================================

print("\n[1] Verifying Recovery Step R3")
print("-" * 78)

required_variables = [
    "DATA_FILES",
    "SELECTED_REPO_FILES",
    "EXPECTED_ROWS",
    "TOTAL_ROWS",
    "DIRECTORIES",
    "PROJECT_ROOT",
    "DRIVE_PROJECT_ROOT"
]

missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing R3 variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step R3."
    )

available_files = [
    path
    for path in DATA_FILES
    if Path(path).exists()
]

print(
    "Dataset files available:",
    len(available_files),
    "/ 33"
)

print(
    "Expected total rows:",
    f"{TOTAL_ROWS:,}"
)

if len(available_files) != 33:
    raise RuntimeError(
        "The exact 33 dataset files are not available."
    )

print("✅ R3 dataset state is available.")


# ======================================================================
# 2 — RESTORE EXPERIMENT CONFIGURATION
# ======================================================================

print("\n[2] Restoring experiment configuration")
print("-" * 78)

PROJECT_NAME = "ZeroDay_IoT_Final_Training"

DEVICE = (
    torch.device("cuda")
    if torch.cuda.is_available()
    else torch.device("cpu")
)

ATTACK_FAMILIES = [
    "DDoS",
    "DoS",
    "Mirai",
    "Recon",
    "Spoofing",
    "Web",
    "BruteForce"
]

RANDOM_SEEDS = [
    13,
    29,
    47,
    71,
    101
]

PRIMARY_SEED = 13

TEMPORAL_WINDOW = 8
TEMPORAL_STRIDE = 8

SSL_TEMPERATURE = 0.2

LAMBDA_T_CANDIDATES = [
    0.1,
    0.25,
    0.5,
    1.0
]

SELECTED_LAMBDA_T = None

SSL_EPOCHS = 30
FINETUNE_EPOCHS = 20

BATCH_SIZE = 256

LEARNING_RATE_SSL = 1e-3
LEARNING_RATE_FINETUNE = 1e-3

LAMBDA_SENSITIVITY_VALUES = (
    LAMBDA_T_CANDIDATES.copy()
)

WINDOW_SENSITIVITY_VALUES = [
    4,
    8,
    16
]

CLASS_IMBALANCE_METHODS = [
    "none",
    "class_weight",
    "weighted_sampler"
]

TIMESTAMP_COLUMN = "Timestamp"
RAW_LABEL_COLUMN = "Label"

print(
    "Device:",
    DEVICE
)

print(
    "Attack families:",
    ATTACK_FAMILIES
)

print(
    "Seeds:",
    RANDOM_SEEDS
)

print(
    "Temporal window:",
    TEMPORAL_WINDOW
)


# ======================================================================
# 3 — RESTORE SOURCE CLASS → RESEARCH FAMILY MAPPING
# ======================================================================

print("\n[3] Restoring attack-family mapping")
print("-" * 78)

SOURCE_CLASS_TO_FAMILY = {

    # --------------------------------------------------------------
    # DDoS
    # --------------------------------------------------------------
    "DDoS-ACK_Fragmentation":
        "DDoS",

    "DDoS-HTTP_Flood":
        "DDoS",

    "DDoS-ICMP_Flood":
        "DDoS",

    "DDoS-ICMP_Fragmentation":
        "DDoS",

    "DDoS-PSHACK_Flood":
        "DDoS",

    "DDoS-RSTFINFlood":
        "DDoS",

    "DDoS-SYN_Flood":
        "DDoS",

    "DDoS-SlowLoris":
        "DDoS",

    "DDoS-SynonymousIP_Flood":
        "DDoS",

    "DDoS-TCP_Flood":
        "DDoS",

    "DDoS-UDP_Flood":
        "DDoS",

    "DDoS-UDP_Fragmentation":
        "DDoS",


    # --------------------------------------------------------------
    # DoS
    # --------------------------------------------------------------
    "DoS-HTTP_Flood":
        "DoS",

    "DoS-SYN_Flood":
        "DoS",

    "DoS-TCP_Flood":
        "DoS",

    "DoS-UDP_Flood":
        "DoS",


    # --------------------------------------------------------------
    # Mirai
    # --------------------------------------------------------------
    "Mirai-greeth_flood":
        "Mirai",

    "Mirai-greip_flood":
        "Mirai",

    "Mirai-udpplain":
        "Mirai",


    # --------------------------------------------------------------
    # Recon
    # --------------------------------------------------------------
    "Recon-HostDiscovery":
        "Recon",

    "Recon-OSScan":
        "Recon",

    "Recon-PingSweep":
        "Recon",

    "Recon-PortScan":
        "Recon",

    "VulnerabilityScan":
        "Recon",


    # --------------------------------------------------------------
    # Spoofing
    # --------------------------------------------------------------
    "DNS_Spoofing":
        "Spoofing",

    "MITM-ArpSpoofing":
        "Spoofing",


    # --------------------------------------------------------------
    # Web
    # --------------------------------------------------------------
    "Backdoor_Malware":
        "Web",

    "BrowserHijacking":
        "Web",

    "CommandInjection":
        "Web",

    "SqlInjection":
        "Web",

    "XSS":
        "Web",


    # --------------------------------------------------------------
    # Brute Force
    # --------------------------------------------------------------
    "DictionaryBruteForce":
        "BruteForce",


    # --------------------------------------------------------------
    # Benign
    # --------------------------------------------------------------
    "Benign_Final":
        "Benign"
}


if len(SOURCE_CLASS_TO_FAMILY) != 33:
    raise RuntimeError(
        "Expected 33 source-class mappings."
    )


# ======================================================================
# 4 — RESTORE FILE → SOURCE CLASS LOOKUP
# ======================================================================

FILE_TO_SOURCE_CLASS = {}

SOURCE_CLASS_TO_FILE = {}

for file_path in DATA_FILES:

    file_path = Path(file_path)

    source_class = (
        file_path
        .parent
        .name
    )

    resolved = str(
        file_path.resolve()
    )

    FILE_TO_SOURCE_CLASS[
        resolved
    ] = source_class

    SOURCE_CLASS_TO_FILE[
        source_class
    ] = file_path


SOURCE_CLASS_TO_ROW_COUNT = {
    key: int(value)
    for key, value
    in EXPECTED_ROWS.items()
}


print(
    "Source classes:",
    len(SOURCE_CLASS_TO_FILE)
)

print(
    "Mappings      :",
    len(SOURCE_CLASS_TO_FAMILY)
)


unmapped_classes = sorted(
    set(
        SOURCE_CLASS_TO_FILE.keys()
    )
    -
    set(
        SOURCE_CLASS_TO_FAMILY.keys()
    )
)

if unmapped_classes:

    raise RuntimeError(
        "Unmapped classes: "
        + str(unmapped_classes)
    )

print(
    "✅ All 33 source classes are mapped."
)


# ======================================================================
# 5 — REBUILD COMMON SCHEMA
# ======================================================================

print("\n[4] Rebuilding common schema")
print("-" * 78)

headers = {}

for file_path in DATA_FILES:

    file_path = Path(file_path)

    source_class = (
        file_path
        .parent
        .name
    )

    columns = list(
        pd.read_csv(
            file_path,
            nrows=0
        ).columns
    )

    headers[
        source_class
    ] = columns


first_source = next(
    iter(headers)
)

first_columns = headers[
    first_source
]


common_column_set = set(
    first_columns
)

for columns in headers.values():

    common_column_set &= set(
        columns
    )


# Preserve original column order
COMMON_COLUMNS = [
    column
    for column in first_columns
    if column in common_column_set
]


ALL_DISTINCT_COLUMNS = sorted(
    set().union(
        *[
            set(columns)
            for columns
            in headers.values()
        ]
    )
)


print(
    "Common columns  :",
    len(COMMON_COLUMNS)
)

print(
    "Distinct columns:",
    len(ALL_DISTINCT_COLUMNS)
)


if len(COMMON_COLUMNS) != 84:

    raise RuntimeError(
        "Expected 84 common columns, "
        f"but found {len(COMMON_COLUMNS)}."
    )


if TIMESTAMP_COLUMN not in COMMON_COLUMNS:

    raise RuntimeError(
        "Timestamp is not in the common schema."
    )


if RAW_LABEL_COLUMN not in COMMON_COLUMNS:

    raise RuntimeError(
        "Label is not in the common schema."
    )


# ======================================================================
# 6 — RESTORE MODEL FEATURE POLICY
# ======================================================================

print("\n[5] Restoring numeric feature policy")
print("-" * 78)


STRUCTURAL_FEATURE_CANDIDATES = [

    column

    for column in COMMON_COLUMNS

    if column not in [
        TIMESTAMP_COLUMN,
        RAW_LABEL_COLUMN
    ]
]


NON_NUMERIC_FEATURE_CANDIDATES = [
    "Flow ID",
    "Src IP",
    "Dst IP"
]


for column in NON_NUMERIC_FEATURE_CANDIDATES:

    if column not in STRUCTURAL_FEATURE_CANDIDATES:

        raise RuntimeError(
            f"Expected identifier column missing: {column}"
        )


NUMERIC_FEATURE_CANDIDATES = [

    column

    for column
    in STRUCTURAL_FEATURE_CANDIDATES

    if column
    not in NON_NUMERIC_FEATURE_CANDIDATES
]


print(
    "Structural candidates:",
    len(
        STRUCTURAL_FEATURE_CANDIDATES
    )
)

print(
    "Non-numeric IDs      :",
    len(
        NON_NUMERIC_FEATURE_CANDIDATES
    )
)

print(
    "Numeric candidates   :",
    len(
        NUMERIC_FEATURE_CANDIDATES
    )
)


if len(
    STRUCTURAL_FEATURE_CANDIDATES
) != 82:

    raise RuntimeError(
        "Expected 82 structural feature candidates."
    )


if len(
    NUMERIC_FEATURE_CANDIDATES
) != 79:

    raise RuntimeError(
        "Expected 79 numeric feature candidates."
    )


print(
    "✅ 79-feature numeric candidate policy restored."
)


# ======================================================================
# 7 — REBUILD DATASET MANIFEST
# ======================================================================

print("\n[6] Rebuilding dataset manifest")
print("-" * 78)


manifest_records = []


for repo_path, local_path in zip(
    SELECTED_REPO_FILES,
    DATA_FILES
):

    local_path = Path(
        local_path
    )

    source_class = (
        local_path
        .parent
        .name
    )

    research_family = (
        SOURCE_CLASS_TO_FAMILY[
            source_class
        ]
    )

    binary_target = (
        0
        if research_family == "Benign"
        else 1
    )

    manifest_records.append({

        "attack_class_directory":
            source_class,

        "source_attack_class":
            source_class,

        "research_family":
            research_family,

        "binary_target":
            binary_target,

        "repo_path":
            repo_path,

        "local_path":
            str(
                local_path.resolve()
            ),

        "file_name":
            local_path.name,

        "expected_rows":
            int(
                SOURCE_CLASS_TO_ROW_COUNT[
                    source_class
                ]
            )
    })


dataset_manifest = pd.DataFrame(
    manifest_records
)


source_class_distribution = (

    dataset_manifest[
        [
            "source_attack_class",
            "expected_rows"
        ]
    ]

    .rename(
        columns={
            "expected_rows":
                "count"
        }
    )

    .copy()
)


family_distribution = (

    dataset_manifest

    .groupby(
        "research_family",
        as_index=False
    )[
        "expected_rows"
    ]

    .sum()

    .rename(
        columns={
            "expected_rows":
                "count"
        }
    )
)


print(
    "Dataset manifest rows:",
    len(dataset_manifest)
)


# ======================================================================
# 8 — CHECK FAMILY COVERAGE
# ======================================================================

print("\n[7] Checking seven-family LOAFO coverage")
print("-" * 78)


represented_attack_families = sorted(

    set(
        dataset_manifest.loc[
            dataset_manifest[
                "research_family"
            ]
            !=
            "Benign",

            "research_family"
        ]
    )
)


missing_families = sorted(

    set(
        ATTACK_FAMILIES
    )
    -
    set(
        represented_attack_families
    )
)


print(
    "Represented attack families:",
    represented_attack_families
)

print(
    "Missing families:",
    missing_families
)


if missing_families:

    raise RuntimeError(
        "Seven-fold LOAFO coverage is incomplete."
    )


print(
    "✅ All seven attack families are represented."
)


# ======================================================================
# 9 — SAVE RECOVERED METADATA LOCALLY
# ======================================================================

print("\n[8] Saving recovered metadata")
print("-" * 78)


MAPPING_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_source_family_mapping.csv"
)


FEATURE_POLICY_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_feature_policy.json"
)


DATASET_MANIFEST_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_selected_files.csv"
)


FAMILY_DISTRIBUTION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_family_distribution.csv"
)


dataset_manifest.to_csv(

    DATASET_MANIFEST_PATH,

    index=False
)


mapping_table = pd.DataFrame({

    "source_attack_class":
        list(
            SOURCE_CLASS_TO_FAMILY.keys()
        ),

    "research_family":
        list(
            SOURCE_CLASS_TO_FAMILY.values()
        )
})


mapping_table.to_csv(

    MAPPING_PATH,

    index=False
)


family_distribution.to_csv(

    FAMILY_DISTRIBUTION_PATH,

    index=False
)


FEATURE_POLICY = {

    "common_column_count":
        len(COMMON_COLUMNS),

    "structural_feature_candidates":
        STRUCTURAL_FEATURE_CANDIDATES,

    "non_numeric_identifiers":
        NON_NUMERIC_FEATURE_CANDIDATES,

    "numeric_feature_candidates":
        NUMERIC_FEATURE_CANDIDATES,

    "numeric_feature_count":
        len(
            NUMERIC_FEATURE_CANDIDATES
        ),

    "timestamp_column":
        TIMESTAMP_COLUMN,

    "timestamp_is_model_feature":
        False,

    "raw_label_column":
        RAW_LABEL_COLUMN,

    "binary_target_source":
        (
            "Source attack-class directory: "
            "Benign_Final=0, attack classes=1"
        )
}


with open(

    FEATURE_POLICY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        FEATURE_POLICY,

        file,

        indent=4
    )


# ======================================================================
# 10 — SAVE RECOVERED METADATA TO GOOGLE DRIVE
# ======================================================================

print("\n[9] Persisting metadata to Google Drive")
print("-" * 78)


DRIVE_AUDIT_DIR = (

    DRIVE_PROJECT_ROOT

    / "dataset_audit"
)


DRIVE_AUDIT_DIR.mkdir(

    parents=True,

    exist_ok=True
)


metadata_files = [

    DATASET_MANIFEST_PATH,
    MAPPING_PATH,
    FAMILY_DISTRIBUTION_PATH,
    FEATURE_POLICY_PATH
]


for source_path in metadata_files:

    destination = (

        DRIVE_AUDIT_DIR

        / source_path.name
    )

    shutil.copy2(

        source_path,

        destination
    )


print(
    "Metadata files backed up:",
    len(metadata_files)
)


# ======================================================================
# 11 — FINAL VALIDATION
# ======================================================================

R4_VALID = (

    len(DATA_FILES) == 33

    and

    TOTAL_ROWS == 39_851_619

    and

    len(dataset_manifest) == 33

    and

    len(SOURCE_CLASS_TO_FAMILY) == 33

    and

    len(COMMON_COLUMNS) == 84

    and

    len(
        STRUCTURAL_FEATURE_CANDIDATES
    ) == 82

    and

    len(
        NON_NUMERIC_FEATURE_CANDIDATES
    ) == 3

    and

    len(
        NUMERIC_FEATURE_CANDIDATES
    ) == 79

    and

    len(missing_families) == 0

    and

    all(
        (
            DRIVE_AUDIT_DIR
            /
            path.name
        ).exists()

        for path in metadata_files
    )
)


print("\n[10] Recovery Step R4 summary")
print("-" * 78)

print(
    "Source files                 :",
    len(DATA_FILES)
)

print(
    "Expected rows                :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Common schema columns        :",
    len(COMMON_COLUMNS)
)

print(
    "Structural feature candidates:",
    len(
        STRUCTURAL_FEATURE_CANDIDATES
    )
)

print(
    "Numeric feature candidates   :",
    len(
        NUMERIC_FEATURE_CANDIDATES
    )
)

print(
    "Non-numeric identifiers      :",
    NON_NUMERIC_FEATURE_CANDIDATES
)

print(
    "Attack families represented  :",
    len(
        represented_attack_families
    ),
    "/ 7"
)

print(
    "Metadata saved to Drive      :",
    True
)


print("\n" + "=" * 78)


if R4_VALID:

    print(
        "✅ RECOVERY STEP R4 PASSED — "
        "Experiment metadata and configuration were restored."
    )

else:

    print(
        "❌ RECOVERY STEP R4 FAILED — "
        "Do not continue yet."
    )


print("=" * 78)

==============================================================================
RECOVERY STEP R4 — RESTORE EXPERIMENT METADATA
==============================================================================

[1] Verifying Recovery Step R3
------------------------------------------------------------------------------
Dataset files available: 33 / 33
Expected total rows: 39,851,619
✅ R3 dataset state is available.

[2] Restoring experiment configuration
------------------------------------------------------------------------------
Device: cuda
Attack families: ['DDoS', 'DoS', 'Mirai', 'Recon', 'Spoofing', 'Web', 'BruteForce']
Seeds: [13, 29, 47, 71, 101]
Temporal window: 8

[3] Restoring attack-family mapping
------------------------------------------------------------------------------
Source classes: 33
Mappings      : 33
✅ All 33 source classes are mapped.

[4] Rebuilding common schema
------------------------------------------------------------------------------
Common columns  : 84
Distinct columns: 86

[5] Restoring numeric feature policy
------------------------------------------------------------------------------
Structural candidates: 82
Non-numeric IDs      : 3
Numeric candidates   : 79
✅ 79-feature numeric candidate policy restored.

[6] Rebuilding dataset manifest
------------------------------------------------------------------------------
Dataset manifest rows: 33

[7] Checking seven-family LOAFO coverage
------------------------------------------------------------------------------
Represented attack families: ['BruteForce', 'DDoS', 'DoS', 'Mirai', 'Recon', 'Spoofing', 'Web']
Missing families: []
✅ All seven attack families are represented.

[8] Saving recovered metadata
------------------------------------------------------------------------------

[9] Persisting metadata to Google Drive
------------------------------------------------------------------------------
Metadata files backed up: 4

[10] Recovery Step R4 summary
------------------------------------------------------------------------------
Source files                 : 33
Expected rows                : 39,851,619
Common schema columns        : 84
Structural feature candidates: 82
Numeric feature candidates   : 79
Non-numeric identifiers      : ['Flow ID', 'Src IP', 'Dst IP']
Attack families represented  : 7 / 7
Metadata saved to Drive      : True

==============================================================================
✅ RECOVERY STEP R4 PASSED — Experiment metadata and configuration were restored.
==============================================================================

Recovery Step R5 — Recreate + Permanently Back Up Chronological Parquet

In [ ]:
# ======================================================================
# RECOVERY STEP R5
# RECREATE CHRONOLOGICAL PARQUET + BACK UP EACH FILE TO GOOGLE DRIVE
# ======================================================================

import os
import re
import gc
import sys
import time
import json
import shutil
import subprocess

from pathlib import Path

import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP R5 — RECREATE CHRONOLOGICAL PARQUET DATASET")
print("=" * 78)


# ======================================================================
# 1 — VERIFY R4 STATE
# ======================================================================

print("\n[1] Verifying Recovery Step R4")
print("-" * 78)


required_variables = [
    "DATA_FILES",
    "TOTAL_ROWS",
    "NUMERIC_FEATURE_CANDIDATES",
    "SOURCE_CLASS_TO_ROW_COUNT",
    "SOURCE_CLASS_TO_FILE",
    "DIRECTORIES",
    "PROJECT_ROOT",
    "DRIVE_PROJECT_ROOT"
]


missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing R4 variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step R4."
    )


if len(DATA_FILES) != 33:

    raise RuntimeError(
        "Expected 33 raw dataset files."
    )


print(
    "Raw source files:",
    len(DATA_FILES)
)

print(
    "Expected rows   :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Numeric features:",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "✅ R4 state is available."
)


# ======================================================================
# 2 — PREPARE DUCKDB
# ======================================================================

print("\n[2] Preparing DuckDB")
print("-" * 78)


try:

    import duckdb

except ImportError:

    subprocess.check_call([
        sys.executable,
        "-m",
        "pip",
        "install",
        "-q",
        "duckdb"
    ])

    import duckdb


print(
    "DuckDB version:",
    duckdb.__version__
)


# ======================================================================
# 3 — TIMESTAMP POLICY
# ======================================================================

TIMESTAMP_COLUMN = "Timestamp"

TIMESTAMP_FORMAT = (
    "%d/%m/%Y %I:%M:%S %p"
)


print("\n[3] Timestamp policy")
print("-" * 78)

print(
    "Timestamp column:",
    TIMESTAMP_COLUMN
)

print(
    "Timestamp format:",
    TIMESTAMP_FORMAT
)

print(
    "Timestamp used as model feature:",
    False
)


# ======================================================================
# 4 — LOCAL + DRIVE OUTPUT DIRECTORIES
# ======================================================================

print("\n[4] Preparing persistent output locations")
print("-" * 78)


SORTED_DATA_DIR = (

    DIRECTORIES["dataset"]

    / "chronological_parquet"
)


SORTED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_SORTED_DATA_DIR = (

    DRIVE_PROJECT_ROOT

    / "chronological_parquet"
)


DRIVE_SORTED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


SORT_TEMP_ROOT = (

    PROJECT_ROOT

    / "duckdb_sort_temp"
)


SORT_TEMP_ROOT.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_SORT_MANIFEST_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_chronological_sort_manifest.csv"
)


DRIVE_SORT_MANIFEST_PATH = (

    DRIVE_PROJECT_ROOT

    / "dataset_audit"

    / "CICIoT2023_chronological_sort_manifest.csv"
)


print(
    "Local sorted folder:"
)

print(
    SORTED_DATA_DIR
)

print(
    "\nDrive backup folder:"
)

print(
    DRIVE_SORTED_DATA_DIR
)


# ======================================================================
# 5 — HELPER FUNCTIONS
# ======================================================================

def safe_file_name(text):

    return re.sub(
        r"[^A-Za-z0-9_.-]+",
        "_",
        str(text)
    )


def sql_escape(text):

    return str(text).replace(
        "'",
        "''"
    )


def build_duckdb_type_map(
    file_path
):

    columns = list(

        pd.read_csv(
            file_path,
            nrows=0
        ).columns
    )


    entries = []


    for column in columns:

        escaped_column = (
            str(column)
            .replace(
                "'",
                "''"
            )
        )


        if column in NUMERIC_FEATURE_CANDIDATES:

            duck_type = "DOUBLE"

        else:

            duck_type = "VARCHAR"


        entries.append(

            f"'{escaped_column}': "
            f"'{duck_type}'"
        )


    return (
        "{"
        +
        ", ".join(entries)
        +
        "}"
    )


def parquet_row_count(
    path
):

    return int(

        pq.ParquetFile(
            path
        )
        .metadata
        .num_rows
    )


def save_manifest(
    records
):

    if len(records) == 0:
        return


    table = pd.DataFrame(
        records
    )


    table.to_csv(
        LOCAL_SORT_MANIFEST_PATH,
        index=False
    )


    shutil.copy2(
        LOCAL_SORT_MANIFEST_PATH,
        DRIVE_SORT_MANIFEST_PATH
    )


# ======================================================================
# 6 — STORAGE CHECK
# ======================================================================

print("\n[5] Checking storage")
print("-" * 78)


local_free_gb = (

    shutil.disk_usage(
        "/content"
    ).free

    /

    (1024 ** 3)
)


drive_free_gb = (

    shutil.disk_usage(
        "/content/drive"
    ).free

    /

    (1024 ** 3)
)


print(
    "Local free storage:",
    f"{local_free_gb:.2f} GB"
)

print(
    "Drive free storage:",
    f"{drive_free_gb:.2f} GB"
)


if local_free_gb < 20:

    raise RuntimeError(
        "Less than 20 GB local storage remains."
    )


if drive_free_gb < 3:

    raise RuntimeError(
        "Less than 3 GB free Google Drive storage remains."
    )


print(
    "✅ Storage check passed."
)


# ======================================================================
# 7 — CREATE / RESTORE SORTED FILES
# ======================================================================

print("\n[6] Recreating chronological Parquet files")
print("-" * 78)

print(
    "Important:"
)

print(
    "- Existing valid Drive backups will be reused."
)

print(
    "- Newly sorted files are copied to Drive immediately."
)

print(
    "- Original CSV files are never modified."
)


sort_records = []

SORTED_FILE_BY_SOURCE_CLASS = {}


source_classes = list(
    SOURCE_CLASS_TO_FILE.keys()
)


for file_number, source_class in enumerate(
    source_classes,
    start=1
):

    input_path = Path(

        SOURCE_CLASS_TO_FILE[
            source_class
        ]
    )


    expected_rows = int(

        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    output_name = (

        safe_file_name(
            source_class
        )

        + ".parquet"
    )


    local_output = (

        SORTED_DATA_DIR

        / output_name
    )


    drive_output = (

        DRIVE_SORTED_DATA_DIR

        / output_name
    )


    partial_output = (

        SORTED_DATA_DIR

        / (
            safe_file_name(
                source_class
            )
            +
            ".partial.parquet"
        )
    )


    print("\n" + "=" * 78)

    print(
        f"FILE {file_number:02d}/33"
    )

    print(
        "Source class :",
        source_class
    )

    print(
        "Expected rows:",
        f"{expected_rows:,}"
    )


    # ==================================================================
    # A — REUSE VALID LOCAL FILE
    # ==================================================================

    local_valid = False


    if local_output.exists():

        try:

            local_rows = (
                parquet_row_count(
                    local_output
                )
            )


            local_valid = (

                local_rows
                ==
                expected_rows
            )

        except Exception:

            local_valid = False


    if local_valid:

        print(
            "✅ Valid local chronological file already exists."
        )


        # Ensure Drive also has a valid copy
        drive_valid = False


        if drive_output.exists():

            try:

                drive_valid = (

                    parquet_row_count(
                        drive_output
                    )

                    ==

                    expected_rows
                )

            except Exception:

                drive_valid = False


        if not drive_valid:

            print(
                "Backing local file up to Drive..."
            )


            shutil.copy2(
                local_output,
                drive_output
            )


            copied_rows = (
                parquet_row_count(
                    drive_output
                )
            )


            if copied_rows != expected_rows:

                raise RuntimeError(
                    "Drive backup row count mismatch."
                )


        SORTED_FILE_BY_SOURCE_CLASS[
            source_class
        ] = local_output


        sort_records.append({

            "file_number":
                file_number,

            "source_attack_class":
                source_class,

            "expected_rows":
                expected_rows,

            "local_file":
                str(
                    local_output
                ),

            "drive_file":
                str(
                    drive_output
                ),

            "status":
                "REUSED_LOCAL"
        })


        save_manifest(
            sort_records
        )


        continue


    # ==================================================================
    # B — RESTORE VALID DRIVE BACKUP
    # ==================================================================

    drive_valid = False


    if drive_output.exists():

        try:

            drive_rows = (
                parquet_row_count(
                    drive_output
                )
            )


            drive_valid = (

                drive_rows
                ==
                expected_rows
            )

        except Exception:

            drive_valid = False


    if drive_valid:

        print(
            "✅ Valid Google Drive backup found."
        )

        print(
            "Restoring it to local Colab storage..."
        )


        shutil.copy2(
            drive_output,
            local_output
        )


        local_rows = (
            parquet_row_count(
                local_output
            )
        )


        if local_rows != expected_rows:

            raise RuntimeError(
                "Restored local row count mismatch."
            )


        print(
            "✅ Restored from Drive."
        )


        SORTED_FILE_BY_SOURCE_CLASS[
            source_class
        ] = local_output


        sort_records.append({

            "file_number":
                file_number,

            "source_attack_class":
                source_class,

            "expected_rows":
                expected_rows,

            "local_file":
                str(
                    local_output
                ),

            "drive_file":
                str(
                    drive_output
                ),

            "status":
                "RESTORED_FROM_DRIVE"
        })


        save_manifest(
            sort_records
        )


        continue


    # ==================================================================
    # C — SORT RAW CSV
    # ==================================================================

    print(
        "No valid sorted copy exists."
    )

    print(
        "Sorting raw CSV chronologically..."
    )


    input_size_gb = (

        input_path.stat().st_size

        /

        (1024 ** 3)
    )


    current_free_gb = (

        shutil.disk_usage(
            "/content"
        ).free

        /

        (1024 ** 3)
    )


    safety_requirement_gb = max(

        12.0,

        (
            input_size_gb
            *
            2.5
        )
        +
        4.0
    )


    print(
        "Input size        :",
        f"{input_size_gb:.2f} GB"
    )

    print(
        "Local free space  :",
        f"{current_free_gb:.2f} GB"
    )

    print(
        "Safety requirement:",
        f"{safety_requirement_gb:.2f} GB"
    )


    if current_free_gb < safety_requirement_gb:

        raise RuntimeError(

            f"Insufficient local space to safely sort "
            f"{source_class}."
        )


    if partial_output.exists():

        partial_output.unlink()


    temp_dir = (

        SORT_TEMP_ROOT

        / (
            f"{file_number:02d}_"
            +
            safe_file_name(
                source_class
            )
        )
    )


    if temp_dir.exists():

        shutil.rmtree(
            temp_dir,
            ignore_errors=True
        )


    temp_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    spill_dir = (

        temp_dir

        / "spill"
    )


    spill_dir.mkdir(
        parents=True,
        exist_ok=True
    )


    database_path = (

        temp_dir

        / "sort.duckdb"
    )


    connection = None

    start_time = time.time()


    try:

        type_map_sql = (
            build_duckdb_type_map(
                input_path
            )
        )


        input_sql = sql_escape(
            input_path.resolve()
        )


        partial_sql = sql_escape(
            partial_output.resolve()
        )


        spill_sql = sql_escape(
            spill_dir.resolve()
        )


        connection = duckdb.connect(
            database=str(
                database_path
            )
        )


        connection.execute(
            "SET threads = 2"
        )


        connection.execute(
            "SET memory_limit = '4GB'"
        )


        connection.execute(
            "SET preserve_insertion_order = true"
        )


        connection.execute(

            f"SET temp_directory = "
            f"'{spill_sql}'"
        )


        query = f"""

        COPY (

            SELECT

                * EXCLUDE (
                    __sort_timestamp,
                    __source_row_id
                )

            FROM (

                SELECT

                    *,

                    strptime(
                        "Timestamp",
                        '{TIMESTAMP_FORMAT}'
                    )
                    AS __sort_timestamp,

                    row_number()
                    OVER ()
                    AS __source_row_id

                FROM read_csv_auto(

                    '{input_sql}',

                    header = true,

                    types = {type_map_sql},

                    nullstr = '',

                    ignore_errors = false
                )
            )

            ORDER BY

                __sort_timestamp ASC,

                __source_row_id ASC
        )

        TO '{partial_sql}'

        (
            FORMAT PARQUET,
            COMPRESSION ZSTD,
            ROW_GROUP_SIZE 100000
        );

        """


        connection.execute(
            query
        )


        connection.close()

        connection = None


        # --------------------------------------------------------------
        # Validate sorted temporary output
        # --------------------------------------------------------------

        if not partial_output.exists():

            raise RuntimeError(
                "Sorted Parquet was not created."
            )


        sorted_rows = (
            parquet_row_count(
                partial_output
            )
        )


        print(
            "Sorted rows:",
            f"{sorted_rows:,}"
        )


        if sorted_rows != expected_rows:

            raise RuntimeError(

                f"Row-count mismatch: "
                f"expected {expected_rows:,}, "
                f"got {sorted_rows:,}."
            )


        # --------------------------------------------------------------
        # Finalize local output
        # --------------------------------------------------------------

        os.replace(
            partial_output,
            local_output
        )


        # --------------------------------------------------------------
        # Immediately persist to Google Drive
        # --------------------------------------------------------------

        print(
            "Copying completed file to Google Drive..."
        )


        shutil.copy2(
            local_output,
            drive_output
        )


        drive_rows = (
            parquet_row_count(
                drive_output
            )
        )


        if drive_rows != expected_rows:

            raise RuntimeError(
                "Google Drive copy failed row validation."
            )


        elapsed_minutes = (

            time.time()
            -
            start_time

        ) / 60


        local_size_gb = (

            local_output.stat().st_size

            /

            (1024 ** 3)
        )


        print(
            "✅ Chronological file complete."
        )

        print(
            "Local rows :",
            f"{sorted_rows:,}"
        )

        print(
            "Drive rows :",
            f"{drive_rows:,}"
        )

        print(
            "Parquet size:",
            f"{local_size_gb:.3f} GB"
        )

        print(
            "Time:",
            f"{elapsed_minutes:.2f} minutes"
        )


        SORTED_FILE_BY_SOURCE_CLASS[
            source_class
        ] = local_output


        sort_records.append({

            "file_number":
                file_number,

            "source_attack_class":
                source_class,

            "expected_rows":
                expected_rows,

            "local_file":
                str(
                    local_output
                ),

            "drive_file":
                str(
                    drive_output
                ),

            "status":
                "SORTED_AND_BACKED_UP"
        })


        save_manifest(
            sort_records
        )


    except Exception as error:

        if connection is not None:

            try:

                connection.close()

            except Exception:

                pass


        if partial_output.exists():

            partial_output.unlink(
                missing_ok=True
            )


        save_manifest(
            sort_records
        )


        raise RuntimeError(

            f"R5 failed while processing "
            f"{source_class}.\n\n"
            f"Original error:\n{error}"
        )


    finally:

        if connection is not None:

            try:

                connection.close()

            except Exception:

                pass


        shutil.rmtree(
            temp_dir,
            ignore_errors=True
        )


        gc.collect()


# ======================================================================
# 8 — BUILD SORTED DATASET VARIABLES
# ======================================================================

print("\n[7] Building chronological dataset variables")
print("-" * 78)


SORTED_DATA_FILES = [

    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ]

    for source_class
    in source_classes
]


print(
    "Sorted files available:",
    len(SORTED_DATA_FILES)
)


# ======================================================================
# 9 — VERIFY LOCAL + DRIVE ROW COUNTS
# ======================================================================

print("\n[8] Verifying all local and Drive copies")
print("-" * 78)


verification_records = []


for source_class in source_classes:

    local_path = (

        SORTED_FILE_BY_SOURCE_CLASS[
            source_class
        ]
    )


    drive_path = (

        DRIVE_SORTED_DATA_DIR

        / (
            safe_file_name(
                source_class
            )
            +
            ".parquet"
        )
    )


    expected_rows = int(

        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    local_rows = (

        parquet_row_count(
            local_path
        )

        if local_path.exists()

        else -1
    )


    drive_rows = (

        parquet_row_count(
            drive_path
        )

        if drive_path.exists()

        else -1
    )


    valid = (

        local_rows
        ==
        expected_rows

        and

        drive_rows
        ==
        expected_rows
    )


    verification_records.append({

        "source_attack_class":
            source_class,

        "expected_rows":
            expected_rows,

        "local_rows":
            local_rows,

        "drive_rows":
            drive_rows,

        "valid":
            valid
    })


SORTED_BACKUP_VERIFICATION = pd.DataFrame(
    verification_records
)


invalid_files = int(

    (
        ~SORTED_BACKUP_VERIFICATION[
            "valid"
        ]
    ).sum()
)


print(
    "Files checked:",
    len(
        SORTED_BACKUP_VERIFICATION
    )
)

print(
    "Invalid files:",
    invalid_files
)


# ======================================================================
# 10 — TOTAL ROW CONSERVATION
# ======================================================================

print("\n[9] Row-count conservation")
print("-" * 78)


SORTED_TOTAL_ROWS = int(

    SORTED_BACKUP_VERIFICATION[
        "local_rows"
    ].sum()
)


DRIVE_TOTAL_ROWS = int(

    SORTED_BACKUP_VERIFICATION[
        "drive_rows"
    ].sum()
)


print(
    "Expected rows:",
    f"{TOTAL_ROWS:,}"
)

print(
    "Local rows   :",
    f"{SORTED_TOTAL_ROWS:,}"
)

print(
    "Drive rows   :",
    f"{DRIVE_TOTAL_ROWS:,}"
)


LOCAL_TOTAL_MATCH = (

    SORTED_TOTAL_ROWS
    ==
    TOTAL_ROWS
)


DRIVE_TOTAL_MATCH = (

    DRIVE_TOTAL_ROWS
    ==
    TOTAL_ROWS
)


print(
    "Local total match:",
    LOCAL_TOTAL_MATCH
)

print(
    "Drive total match:",
    DRIVE_TOTAL_MATCH
)


# ======================================================================
# 11 — SAVE VERIFICATION TABLE
# ======================================================================

SORTED_BACKUP_VERIFICATION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_sorted_backup_verification.csv"
)


DRIVE_SORTED_BACKUP_VERIFICATION_PATH = (

    DRIVE_PROJECT_ROOT

    / "dataset_audit"

    / "CICIoT2023_sorted_backup_verification.csv"
)


SORTED_BACKUP_VERIFICATION.to_csv(

    SORTED_BACKUP_VERIFICATION_PATH,

    index=False
)


shutil.copy2(

    SORTED_BACKUP_VERIFICATION_PATH,

    DRIVE_SORTED_BACKUP_VERIFICATION_PATH
)


# ======================================================================
# 12 — SIZE SUMMARY
# ======================================================================

local_sorted_size_gb = sum(

    path.stat().st_size

    for path
    in SORTED_DATA_FILES

) / (1024 ** 3)


drive_sorted_size_gb = sum(

    (
        DRIVE_SORTED_DATA_DIR
        /
        (
            safe_file_name(
                source_class
            )
            +
            ".parquet"
        )
    ).stat().st_size

    for source_class
    in source_classes

) / (1024 ** 3)


print("\n[10] Persistent chronological dataset summary")
print("-" * 78)

print(
    "Local chronological files:",
    len(SORTED_DATA_FILES)
)

print(
    "Drive chronological files:",
    len(
        list(
            DRIVE_SORTED_DATA_DIR.glob(
                "*.parquet"
            )
        )
    )
)

print(
    "Local sorted dataset size:",
    f"{local_sorted_size_gb:.2f} GB"
)

print(
    "Drive backup dataset size:",
    f"{drive_sorted_size_gb:.2f} GB"
)


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

R5_VALID = (

    len(
        SORTED_DATA_FILES
    ) == 33

    and

    invalid_files == 0

    and

    LOCAL_TOTAL_MATCH

    and

    DRIVE_TOTAL_MATCH

    and

    DRIVE_SORT_MANIFEST_PATH.exists()

    and

    DRIVE_SORTED_BACKUP_VERIFICATION_PATH.exists()
)


print("\n[11] Recovery Step R5 validation")
print("-" * 78)

print(
    "Chronological files local   :",
    len(SORTED_DATA_FILES),
    "/ 33"
)

print(
    "Chronological files in Drive:",
    len(
        list(
            DRIVE_SORTED_DATA_DIR.glob(
                "*.parquet"
            )
        )
    ),
    "/ 33"
)

print(
    "Invalid local/Drive copies  :",
    invalid_files
)

print(
    "All local rows conserved    :",
    LOCAL_TOTAL_MATCH
)

print(
    "All Drive rows conserved    :",
    DRIVE_TOTAL_MATCH
)

print(
    "Progress manifest in Drive  :",
    DRIVE_SORT_MANIFEST_PATH.exists()
)


print("\n" + "=" * 78)


if R5_VALID:

    print(
        "✅ RECOVERY STEP R5 PASSED — "
        "The chronological dataset has been recreated "
        "and permanently backed up to Google Drive."
    )

else:

    print(
        "❌ RECOVERY STEP R5 FAILED — "
        "Do not continue yet."
    )


print("=" * 78)

==============================================================================
RECOVERY STEP R5 — RECREATE CHRONOLOGICAL PARQUET DATASET
==============================================================================

[1] Verifying Recovery Step R4
------------------------------------------------------------------------------
Raw source files: 33
Expected rows   : 39,851,619
Numeric features: 79
✅ R4 state is available.

[2] Preparing DuckDB
------------------------------------------------------------------------------
DuckDB version: 1.3.2

[3] Timestamp policy
------------------------------------------------------------------------------
Timestamp column: Timestamp
Timestamp format: %d/%m/%Y %I:%M:%S %p
Timestamp used as model feature: False

[4] Preparing persistent output locations
------------------------------------------------------------------------------
Local sorted folder:
/content/ZeroDay_IoT_Research/dataset/chronological_parquet

Drive backup folder:
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/chronological_parquet

[5] Checking storage
------------------------------------------------------------------------------
Local free storage: 46.71 GB
Drive free storage: 44.38 GB
✅ Storage check passed.

[6] Recreating chronological Parquet files
------------------------------------------------------------------------------
Important:
- Existing valid Drive backups will be reused.
- Newly sorted files are copied to Drive immediately.
- Original CSV files are never modified.

==============================================================================
FILE 01/33
Source class : Backdoor_Malware
Expected rows: 2,703
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 46.71 GB
Safety requirement: 12.00 GB
Sorted rows: 2,703
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 2,703
Drive rows : 2,703
Parquet size: 0.001 GB
Time: 0.02 minutes

==============================================================================
FILE 02/33
Source class : Benign_Final
Expected rows: 91,506
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.05 GB
Local free space  : 46.71 GB
Safety requirement: 12.00 GB
Sorted rows: 91,506
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 91,506
Drive rows : 91,506
Parquet size: 0.011 GB
Time: 0.04 minutes

==============================================================================
FILE 03/33
Source class : BrowserHijacking
Expected rows: 3,286
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 46.69 GB
Safety requirement: 12.00 GB
Sorted rows: 3,286
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 3,286
Drive rows : 3,286
Parquet size: 0.001 GB
Time: 0.00 minutes

==============================================================================
FILE 04/33
Source class : CommandInjection
Expected rows: 3,848
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 46.69 GB
Safety requirement: 12.00 GB
Sorted rows: 3,848
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 3,848
Drive rows : 3,848
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 05/33
Source class : DDoS-ACK_Fragmentation
Expected rows: 37,296
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.02 GB
Local free space  : 46.69 GB
Safety requirement: 12.00 GB
Sorted rows: 37,296
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 37,296
Drive rows : 37,296
Parquet size: 0.003 GB
Time: 0.02 minutes

==============================================================================
FILE 06/33
Source class : DDoS-HTTP_Flood
Expected rows: 513,672
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.25 GB
Local free space  : 46.68 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 513,672
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 513,672
Drive rows : 513,672
Parquet size: 0.035 GB
Time: 0.15 minutes

==============================================================================
FILE 07/33
Source class : DDoS-ICMP_Flood
Expected rows: 7,834
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 46.61 GB
Safety requirement: 12.00 GB
Sorted rows: 7,834
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 7,834
Drive rows : 7,834
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 08/33
Source class : DDoS-ICMP_Fragmentation
Expected rows: 25,106
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.01 GB
Local free space  : 46.61 GB
Safety requirement: 12.00 GB
Sorted rows: 25,106
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 25,106
Drive rows : 25,106
Parquet size: 0.003 GB
Time: 0.01 minutes

==============================================================================
FILE 09/33
Source class : DDoS-PSHACK_Flood
Expected rows: 5,007,067
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 2.51 GB
Local free space  : 46.60 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 5,007,067
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 5,007,067
Drive rows : 5,007,067
Parquet size: 0.229 GB
Time: 9.79 minutes

==============================================================================
FILE 10/33
Source class : DDoS-RSTFINFlood
Expected rows: 12,968,618
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 5.56 GB
Local free space  : 46.14 GB
Safety requirement: 17.89 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 12,968,618
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 12,968,618
Drive rows : 12,968,618
Parquet size: 0.250 GB
Time: 16.77 minutes

==============================================================================
FILE 11/33
Source class : DDoS-SYN_Flood
Expected rows: 6,366,353
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 3.05 GB
Local free space  : 45.64 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 6,366,353
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 6,366,353
Drive rows : 6,366,353
Parquet size: 0.239 GB
Time: 7.76 minutes

==============================================================================
FILE 12/33
Source class : DDoS-SlowLoris
Expected rows: 196,578
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.11 GB
Local free space  : 45.16 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 196,578
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 196,578
Drive rows : 196,578
Parquet size: 0.021 GB
Time: 0.10 minutes

==============================================================================
FILE 13/33
Source class : DDoS-SynonymousIP_Flood
Expected rows: 799,351
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.41 GB
Local free space  : 45.12 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 799,351
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 799,351
Drive rows : 799,351
Parquet size: 0.051 GB
Time: 0.23 minutes

==============================================================================
FILE 14/33
Source class : DDoS-TCP_Flood
Expected rows: 4,945,887
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 2.38 GB
Local free space  : 45.02 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 4,945,887
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 4,945,887
Drive rows : 4,945,887
Parquet size: 0.177 GB
Time: 4.82 minutes

==============================================================================
FILE 15/33
Source class : DDoS-UDP_Flood
Expected rows: 41,146
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.02 GB
Local free space  : 44.66 GB
Safety requirement: 12.00 GB
Sorted rows: 41,146
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 41,146
Drive rows : 41,146
Parquet size: 0.004 GB
Time: 0.02 minutes

==============================================================================
FILE 16/33
Source class : DDoS-UDP_Fragmentation
Expected rows: 9,757
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 44.65 GB
Safety requirement: 12.00 GB
Sorted rows: 9,757
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 9,757
Drive rows : 9,757
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 17/33
Source class : DNS_Spoofing
Expected rows: 74,938
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.04 GB
Local free space  : 44.65 GB
Safety requirement: 12.00 GB
Sorted rows: 74,938
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 74,938
Drive rows : 74,938
Parquet size: 0.009 GB
Time: 0.04 minutes

==============================================================================
FILE 18/33
Source class : DictionaryBruteForce
Expected rows: 8,488
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 44.63 GB
Safety requirement: 12.00 GB
Sorted rows: 8,488
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 8,488
Drive rows : 8,488
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 19/33
Source class : DoS-HTTP_Flood
Expected rows: 965,554
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.39 GB
Local free space  : 44.63 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 965,554
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 965,554
Drive rows : 965,554
Parquet size: 0.039 GB
Time: 0.38 minutes

==============================================================================
FILE 20/33
Source class : DoS-SYN_Flood
Expected rows: 3,997,110
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 1.92 GB
Local free space  : 44.55 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 3,997,110
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 3,997,110
Drive rows : 3,997,110
Parquet size: 0.175 GB
Time: 2.55 minutes

==============================================================================
FILE 21/33
Source class : DoS-TCP_Flood
Expected rows: 1,638,068
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.77 GB
Local free space  : 44.20 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 1,638,068
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 1,638,068
Drive rows : 1,638,068
Parquet size: 0.066 GB
Time: 0.43 minutes

==============================================================================
FILE 22/33
Source class : DoS-UDP_Flood
Expected rows: 934,009
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.49 GB
Local free space  : 44.07 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 934,009
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 934,009
Drive rows : 934,009
Parquet size: 0.050 GB
Time: 0.24 minutes

==============================================================================
FILE 23/33
Source class : MITM-ArpSpoofing
Expected rows: 72,853
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.04 GB
Local free space  : 43.97 GB
Safety requirement: 12.00 GB
Sorted rows: 72,853
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 72,853
Drive rows : 72,853
Parquet size: 0.008 GB
Time: 0.03 minutes

==============================================================================
FILE 24/33
Source class : Mirai-greeth_flood
Expected rows: 5,155
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 43.95 GB
Safety requirement: 12.00 GB
Sorted rows: 5,155
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 5,155
Drive rows : 5,155
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 25/33
Source class : Mirai-greip_flood
Expected rows: 10,401
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.01 GB
Local free space  : 43.95 GB
Safety requirement: 12.00 GB
Sorted rows: 10,401
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 10,401
Drive rows : 10,401
Parquet size: 0.002 GB
Time: 0.01 minutes

==============================================================================
FILE 26/33
Source class : Mirai-udpplain
Expected rows: 7,455
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 43.94 GB
Safety requirement: 12.00 GB
Sorted rows: 7,455
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 7,455
Drive rows : 7,455
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 27/33
Source class : Recon-HostDiscovery
Expected rows: 329,985
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.13 GB
Local free space  : 43.94 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 329,985
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 329,985
Drive rows : 329,985
Parquet size: 0.017 GB
Time: 0.08 minutes

==============================================================================
FILE 28/33
Source class : Recon-OSScan
Expected rows: 158,682
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.07 GB
Local free space  : 43.91 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 158,682
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 158,682
Drive rows : 158,682
Parquet size: 0.010 GB
Time: 0.06 minutes

==============================================================================
FILE 29/33
Source class : Recon-PingSweep
Expected rows: 1,947
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 43.89 GB
Safety requirement: 12.00 GB
Sorted rows: 1,947
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 1,947
Drive rows : 1,947
Parquet size: 0.000 GB
Time: 0.01 minutes

==============================================================================
FILE 30/33
Source class : Recon-PortScan
Expected rows: 175,050
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.07 GB
Local free space  : 43.89 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 175,050
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 175,050
Drive rows : 175,050
Parquet size: 0.010 GB
Time: 0.05 minutes

==============================================================================
FILE 31/33
Source class : SqlInjection
Expected rows: 6,596
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 43.87 GB
Safety requirement: 12.00 GB
Sorted rows: 6,596
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 6,596
Drive rows : 6,596
Parquet size: 0.001 GB
Time: 0.01 minutes

==============================================================================
FILE 32/33
Source class : VulnerabilityScan
Expected rows: 442,122
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.21 GB
Local free space  : 43.87 GB
Safety requirement: 12.00 GB

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Sorted rows: 442,122
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 442,122
Drive rows : 442,122
Parquet size: 0.041 GB
Time: 0.14 minutes

==============================================================================
FILE 33/33
Source class : XSS
Expected rows: 3,198
No valid sorted copy exists.
Sorting raw CSV chronologically...
Input size        : 0.00 GB
Local free space  : 43.78 GB
Safety requirement: 12.00 GB
Sorted rows: 3,198
Copying completed file to Google Drive...
✅ Chronological file complete.
Local rows : 3,198
Drive rows : 3,198
Parquet size: 0.001 GB
Time: 0.01 minutes

[7] Building chronological dataset variables
------------------------------------------------------------------------------
Sorted files available: 33

[8] Verifying all local and Drive copies
------------------------------------------------------------------------------
Files checked: 33
Invalid files: 0

[9] Row-count conservation
------------------------------------------------------------------------------
Expected rows: 39,851,619
Local rows   : 39,851,619
Drive rows   : 39,851,619
Local total match: True
Drive total match: True

[10] Persistent chronological dataset summary
------------------------------------------------------------------------------
Local chronological files: 33
Drive chronological files: 33
Local sorted dataset size: 1.46 GB
Drive backup dataset size: 1.46 GB

[11] Recovery Step R5 validation
------------------------------------------------------------------------------
Chronological files local   : 33 / 33
Chronological files in Drive: 33 / 33
Invalid local/Drive copies  : 0
All local rows conserved    : True
All Drive rows conserved    : True
Progress manifest in Drive  : True

==============================================================================
✅ RECOVERY STEP R5 PASSED — The chronological dataset has been recreated and permanently backed up to Google Drive.
==============================================================================

# Recovery Step R6 — Verify the Persistent Chronological Dataset

In [ ]:
# ======================================================================
# RECOVERY STEP R6 — VERIFY PERSISTENT CHRONOLOGICAL DATASET
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP R6 — VERIFY PERSISTENT CHRONOLOGICAL DATASET")
print("=" * 78)


# ======================================================================
# 1 — VERIFY R5 STATE
# ======================================================================

print("\n[1] Verifying Recovery Step R5")
print("-" * 78)


required_variables = [
    "SORTED_FILE_BY_SOURCE_CLASS",
    "SOURCE_CLASS_TO_ROW_COUNT",
    "TOTAL_ROWS",
    "TIMESTAMP_FORMAT",
    "DIRECTORIES",
    "DRIVE_PROJECT_ROOT"
]


missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing R5 variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step R5."
    )


print(
    "Chronological files:",
    len(SORTED_FILE_BY_SOURCE_CLASS)
)

print(
    "Expected total rows:",
    f"{TOTAL_ROWS:,}"
)


if len(SORTED_FILE_BY_SOURCE_CLASS) != 33:

    raise RuntimeError(
        "Expected 33 chronological files."
    )


print(
    "✅ R5 chronological dataset state is available."
)


# ======================================================================
# 2 — OUTPUT PATHS
# ======================================================================

LOCAL_VERIFICATION_PATH = (

    DIRECTORIES["dataset_audit"]

    / "CICIoT2023_chronological_verification.csv"
)


DRIVE_AUDIT_DIR = (

    DRIVE_PROJECT_ROOT

    / "dataset_audit"
)


DRIVE_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_VERIFICATION_PATH = (

    DRIVE_AUDIT_DIR

    / "CICIoT2023_chronological_verification.csv"
)


DRIVE_VERIFICATION_SUMMARY_PATH = (

    DRIVE_AUDIT_DIR

    / "CICIoT2023_chronological_verification_summary.json"
)


# ======================================================================
# 3 — VERIFY EVERY FILE
# ======================================================================

print("\n[2] Checking timestamp order in all 33 Parquet files")
print("-" * 78)

print(
    "Only the Timestamp column will be scanned."
)


VERIFY_BATCH_SIZE = 250_000


verification_records = []


for file_number, (
    source_class,
    parquet_path
) in enumerate(
    SORTED_FILE_BY_SOURCE_CLASS.items(),
    start=1
):

    parquet_path = Path(
        parquet_path
    )


    expected_rows = int(

        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    print("\n" + "-" * 78)

    print(
        f"Checking {file_number:02d}/33"
    )

    print(
        "Source class:",
        source_class
    )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    metadata_rows = int(
        parquet_file.metadata.num_rows
    )


    rows_checked = 0
    missing_timestamps = 0
    invalid_timestamps = 0
    backward_transitions = 0

    previous_last_timestamp = None

    earliest_timestamp = None
    latest_timestamp = None


    for batch in parquet_file.iter_batches(

        columns=[
            "Timestamp"
        ],

        batch_size=
            VERIFY_BATCH_SIZE
    ):

        timestamp_series = (

            batch
            .column(0)
            .to_pandas()
        )


        timestamp_text = (

            timestamp_series
            .astype("string")
            .str.strip()
        )


        missing_mask = (

            timestamp_series.isna()

            |

            timestamp_text.eq("")
        )


        parsed_timestamp = pd.to_datetime(

            timestamp_series,

            format=
                TIMESTAMP_FORMAT,

            errors=
                "coerce"
        )


        invalid_mask = (

            parsed_timestamp.isna()

            &

            ~missing_mask
        )


        missing_timestamps += int(
            missing_mask.sum()
        )


        invalid_timestamps += int(
            invalid_mask.sum()
        )


        valid_timestamp = (

            parsed_timestamp
            .dropna()
        )


        if not valid_timestamp.empty:

            timestamp_ns = (

                valid_timestamp
                .astype("int64")
                .to_numpy()
            )


            # ----------------------------------------------------------
            # Transition between consecutive batches
            # ----------------------------------------------------------

            if (
                previous_last_timestamp
                is not None

                and

                timestamp_ns[0]
                <
                previous_last_timestamp
            ):

                backward_transitions += 1


            # ----------------------------------------------------------
            # Transitions within current batch
            # ----------------------------------------------------------

            if len(timestamp_ns) > 1:

                backward_transitions += int(

                    np.count_nonzero(

                        timestamp_ns[1:]

                        <

                        timestamp_ns[:-1]
                    )
                )


            previous_last_timestamp = int(
                timestamp_ns[-1]
            )


            batch_min = (
                valid_timestamp.min()
            )

            batch_max = (
                valid_timestamp.max()
            )


            if (
                earliest_timestamp is None

                or

                batch_min
                <
                earliest_timestamp
            ):

                earliest_timestamp = (
                    batch_min
                )


            if (
                latest_timestamp is None

                or

                batch_max
                >
                latest_timestamp
            ):

                latest_timestamp = (
                    batch_max
                )


        rows_checked += len(
            timestamp_series
        )


    # ==================================================================
    # FILE-LEVEL CHECKS
    # ==================================================================

    row_count_match = bool(

        rows_checked
        ==
        metadata_rows
        ==
        expected_rows
    )


    chronological = bool(

        backward_transitions == 0

        and

        missing_timestamps == 0

        and

        invalid_timestamps == 0
    )


    status = (

        "PASS"

        if (
            row_count_match
            and
            chronological
        )

        else "FAIL"
    )


    verification_records.append({

        "source_attack_class":
            source_class,

        "parquet_file":
            str(
                parquet_path.resolve()
            ),

        "expected_rows":
            expected_rows,

        "metadata_rows":
            metadata_rows,

        "rows_checked":
            rows_checked,

        "row_count_match":
            row_count_match,

        "missing_timestamps":
            missing_timestamps,

        "invalid_timestamps":
            invalid_timestamps,

        "backward_transitions":
            backward_transitions,

        "chronological":
            chronological,

        "earliest_timestamp":
            str(
                earliest_timestamp
            ),

        "latest_timestamp":
            str(
                latest_timestamp
            ),

        "status":
            status
    })


    print(
        "Rows checked        :",
        f"{rows_checked:,}"
    )

    print(
        "Backward transitions:",
        f"{backward_transitions:,}"
    )

    print(
        "Missing timestamps  :",
        f"{missing_timestamps:,}"
    )

    print(
        "Invalid timestamps  :",
        f"{invalid_timestamps:,}"
    )

    print(
        "Status              :",
        status
    )


# ======================================================================
# 4 — SAVE VERIFICATION TABLE
# ======================================================================

CHRONOLOGICAL_VERIFICATION = pd.DataFrame(
    verification_records
)


CHRONOLOGICAL_VERIFICATION.to_csv(

    LOCAL_VERIFICATION_PATH,

    index=False
)


shutil.copy2(

    LOCAL_VERIFICATION_PATH,

    DRIVE_VERIFICATION_PATH
)


# ======================================================================
# 5 — OVERALL SUMMARY
# ======================================================================

print("\n[3] Chronological verification summary")
print("-" * 78)


FILES_CHECKED = len(
    CHRONOLOGICAL_VERIFICATION
)


FILES_PASSED = int(

    (
        CHRONOLOGICAL_VERIFICATION[
            "status"
        ]
        ==
        "PASS"
    ).sum()
)


FILES_FAILED = (

    FILES_CHECKED

    -

    FILES_PASSED
)


TOTAL_VERIFIED_ROWS = int(

    CHRONOLOGICAL_VERIFICATION[
        "rows_checked"
    ].sum()
)


TOTAL_BACKWARD_TRANSITIONS = int(

    CHRONOLOGICAL_VERIFICATION[
        "backward_transitions"
    ].sum()
)


TOTAL_MISSING_TIMESTAMPS = int(

    CHRONOLOGICAL_VERIFICATION[
        "missing_timestamps"
    ].sum()
)


TOTAL_INVALID_TIMESTAMPS = int(

    CHRONOLOGICAL_VERIFICATION[
        "invalid_timestamps"
    ].sum()
)


print(
    "Files checked        :",
    FILES_CHECKED
)

print(
    "Files passed         :",
    FILES_PASSED
)

print(
    "Files failed         :",
    FILES_FAILED
)

print(
    "Rows verified        :",
    f"{TOTAL_VERIFIED_ROWS:,}"
)

print(
    "Expected rows        :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Backward transitions :",
    f"{TOTAL_BACKWARD_TRANSITIONS:,}"
)

print(
    "Missing timestamps   :",
    f"{TOTAL_MISSING_TIMESTAMPS:,}"
)

print(
    "Invalid timestamps   :",
    f"{TOTAL_INVALID_TIMESTAMPS:,}"
)


# ======================================================================
# 6 — VALIDATION
# ======================================================================

ROW_TOTAL_MATCH = bool(

    TOTAL_VERIFIED_ROWS
    ==
    TOTAL_ROWS
)


R6_VALID = bool(

    FILES_CHECKED == 33

    and

    FILES_PASSED == 33

    and

    FILES_FAILED == 0

    and

    ROW_TOTAL_MATCH

    and

    TOTAL_BACKWARD_TRANSITIONS == 0

    and

    TOTAL_MISSING_TIMESTAMPS == 0

    and

    TOTAL_INVALID_TIMESTAMPS == 0

    and

    DRIVE_VERIFICATION_PATH.exists()
)


# ======================================================================
# 7 — SAVE PERSISTENT SUMMARY
# ======================================================================

verification_summary = {

    "files_checked":
        FILES_CHECKED,

    "files_passed":
        FILES_PASSED,

    "files_failed":
        FILES_FAILED,

    "total_rows_expected":
        int(
            TOTAL_ROWS
        ),

    "total_rows_verified":
        TOTAL_VERIFIED_ROWS,

    "backward_transitions":
        TOTAL_BACKWARD_TRANSITIONS,

    "missing_timestamps":
        TOTAL_MISSING_TIMESTAMPS,

    "invalid_timestamps":
        TOTAL_INVALID_TIMESTAMPS,

    "timestamp_format":
        TIMESTAMP_FORMAT,

    "timestamp_used_as_model_feature":
        False,

    "verification_passed":
        R6_VALID
}


with open(

    DRIVE_VERIFICATION_SUMMARY_PATH,

    "w",

    encoding="utf-8"

) as file:

    json.dump(

        verification_summary,

        file,

        indent=4
    )


# ======================================================================
# 8 — FINAL VALIDATION
# ======================================================================

print("\n[4] Recovery Step R6 validation")
print("-" * 78)


print(
    "All 33 files chronological:",
    FILES_PASSED == 33
)

print(
    "All rows conserved        :",
    ROW_TOTAL_MATCH
)

print(
    "Backward transitions zero :",
    TOTAL_BACKWARD_TRANSITIONS == 0
)

print(
    "Timestamp errors zero     :",
    (
        TOTAL_MISSING_TIMESTAMPS == 0
        and
        TOTAL_INVALID_TIMESTAMPS == 0
    )
)

print(
    "Verification saved locally:",
    LOCAL_VERIFICATION_PATH.exists()
)

print(
    "Verification saved to Drive:",
    DRIVE_VERIFICATION_PATH.exists()
)


print("\n" + "=" * 78)


if R6_VALID:

    print(
        "✅ RECOVERY STEP R6 PASSED — "
        "All persistent chronological files are verified."
    )

else:

    print(
        "❌ RECOVERY STEP R6 FAILED — "
        "Do not rebuild LOAFO partitions yet."
    )


print("=" * 78)

==============================================================================
RECOVERY STEP R6 — VERIFY PERSISTENT CHRONOLOGICAL DATASET
==============================================================================

[1] Verifying Recovery Step R5
------------------------------------------------------------------------------

RuntimeError: Missing R5 variables: SORTED_FILE_BY_SOURCE_CLASS, SOURCE_CLASS_TO_ROW_COUNT, TOTAL_ROWS, TIMESTAMP_FORMAT, DIRECTORIES, DRIVE_PROJECT_ROOT
Please rerun Recovery Step R5.

# Do only this now — Recovery Step R6-R

In [ ]:
# ======================================================================
# RECOVERY STEP R6-R — RESTORE R5 STATE FROM GOOGLE DRIVE
# ======================================================================

from pathlib import Path
import pyarrow.parquet as pq

print("=" * 78)
print("RECOVERY STEP R6-R — RESTORE R5 STATE FROM GOOGLE DRIVE")
print("=" * 78)


# ======================================================================
# 1 — MOUNT GOOGLE DRIVE IF NECESSARY
# ======================================================================

print("\n[1] Checking Google Drive")
print("-" * 78)

DRIVE_MOUNT = Path(
    "/content/drive/MyDrive"
)

if not DRIVE_MOUNT.exists():

    from google.colab import drive

    print(
        "Google Drive is not mounted."
    )

    print(
        "Mounting Google Drive..."
    )

    drive.mount(
        "/content/drive"
    )


if not DRIVE_MOUNT.exists():

    raise RuntimeError(
        "Google Drive could not be mounted."
    )


print(
    "Google Drive mounted:",
    True
)


# ======================================================================
# 2 — RESTORE PROJECT PATHS
# ======================================================================

print("\n[2] Restoring project paths")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

PROJECT_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

DIRECTORIES = {

    "dataset":
        PROJECT_ROOT / "dataset",

    "dataset_audit":
        PROJECT_ROOT / "dataset_audit",

    "processed_data":
        PROJECT_ROOT / "processed_data",

    "models":
        PROJECT_ROOT / "models",

    "checkpoints":
        PROJECT_ROOT / "checkpoints",

    "predictions":
        PROJECT_ROOT / "predictions",

    "metrics":
        PROJECT_ROOT / "metrics",

    "figures":
        PROJECT_ROOT / "figures"
}


for folder in DIRECTORIES.values():

    folder.mkdir(
        parents=True,
        exist_ok=True
    )


DRIVE_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


DRIVE_SORTED_DATA_DIR = (
    DRIVE_PROJECT_ROOT
    / "chronological_parquet"
)


print(
    "Drive project root:",
    DRIVE_PROJECT_ROOT
)

print(
    "Drive sorted-data folder:",
    DRIVE_SORTED_DATA_DIR
)


if not DRIVE_SORTED_DATA_DIR.exists():

    raise RuntimeError(
        "Persistent chronological dataset folder "
        "was not found in Google Drive."
    )


# ======================================================================
# 3 — RESTORE VERIFIED ROW COUNTS
# ======================================================================

print("\n[3] Restoring source-class metadata")
print("-" * 78)

SOURCE_CLASS_TO_ROW_COUNT = {

    "Backdoor_Malware":
        2703,

    "Benign_Final":
        91506,

    "BrowserHijacking":
        3286,

    "CommandInjection":
        3848,

    "DDoS-ACK_Fragmentation":
        37296,

    "DDoS-HTTP_Flood":
        513672,

    "DDoS-ICMP_Flood":
        7834,

    "DDoS-ICMP_Fragmentation":
        25106,

    "DDoS-PSHACK_Flood":
        5007067,

    "DDoS-RSTFINFlood":
        12968618,

    "DDoS-SYN_Flood":
        6366353,

    "DDoS-SlowLoris":
        196578,

    "DDoS-SynonymousIP_Flood":
        799351,

    "DDoS-TCP_Flood":
        4945887,

    "DDoS-UDP_Flood":
        41146,

    "DDoS-UDP_Fragmentation":
        9757,

    "DNS_Spoofing":
        74938,

    "DictionaryBruteForce":
        8488,

    "DoS-HTTP_Flood":
        965554,

    "DoS-SYN_Flood":
        3997110,

    "DoS-TCP_Flood":
        1638068,

    "DoS-UDP_Flood":
        934009,

    "MITM-ArpSpoofing":
        72853,

    "Mirai-greeth_flood":
        5155,

    "Mirai-greip_flood":
        10401,

    "Mirai-udpplain":
        7455,

    "Recon-HostDiscovery":
        329985,

    "Recon-OSScan":
        158682,

    "Recon-PingSweep":
        1947,

    "Recon-PortScan":
        175050,

    "SqlInjection":
        6596,

    "VulnerabilityScan":
        442122,

    "XSS":
        3198
}


TOTAL_ROWS = int(
    sum(
        SOURCE_CLASS_TO_ROW_COUNT.values()
    )
)


TIMESTAMP_FORMAT = (
    "%d/%m/%Y %I:%M:%S %p"
)


print(
    "Source classes:",
    len(
        SOURCE_CLASS_TO_ROW_COUNT
    )
)

print(
    "Expected rows:",
    f"{TOTAL_ROWS:,}"
)


# ======================================================================
# 4 — REBUILD SORTED FILE LOOKUP USING DRIVE FILES
# ======================================================================

print("\n[4] Rebuilding chronological file lookup")
print("-" * 78)

SORTED_FILE_BY_SOURCE_CLASS = {}

missing_files = []

row_mismatches = []


for source_class, expected_rows in (
    SOURCE_CLASS_TO_ROW_COUNT.items()
):

    parquet_path = (

        DRIVE_SORTED_DATA_DIR

        / f"{source_class}.parquet"
    )


    if not parquet_path.exists():

        missing_files.append(
            source_class
        )

        continue


    actual_rows = int(
        pq.ParquetFile(
            parquet_path
        )
        .metadata
        .num_rows
    )


    if actual_rows != expected_rows:

        row_mismatches.append({
            "source_class":
                source_class,

            "expected":
                expected_rows,

            "actual":
                actual_rows
        })

        continue


    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ] = parquet_path


print(
    "Valid Drive Parquet files:",
    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ),
    "/ 33"
)

print(
    "Missing files:",
    len(
        missing_files
    )
)

print(
    "Row-count mismatches:",
    len(
        row_mismatches
    )
)


# ======================================================================
# 5 — FINAL RECOVERY CHECK
# ======================================================================

R6_RECOVERY_VALID = bool(

    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ) == 33

    and

    len(
        missing_files
    ) == 0

    and

    len(
        row_mismatches
    ) == 0

    and

    TOTAL_ROWS == 39_851_619
)


print("\n[5] Recovery validation")
print("-" * 78)

print(
    "33 persistent files available:",
    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ) == 33
)

print(
    "All metadata row counts valid:",
    len(
        row_mismatches
    ) == 0
)

print(
    "Expected total rows correct:",
    TOTAL_ROWS == 39_851_619
)


print("\n" + "=" * 78)

if R6_RECOVERY_VALID:

    print(
        "✅ RECOVERY STEP R6-R PASSED — "
        "R5 state restored directly from Google Drive."
    )

else:

    print(
        "❌ RECOVERY STEP R6-R FAILED — "
        "Do not rerun R5 yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP R6-R — RESTORE R5 STATE FROM GOOGLE DRIVE
==============================================================================

[1] Checking Google Drive
------------------------------------------------------------------------------
Google Drive is not mounted.
Mounting Google Drive...
Mounted at /content/drive
Google Drive mounted: True

[2] Restoring project paths
------------------------------------------------------------------------------
Drive project root: /content/drive/MyDrive/ZeroDay_IoT_Research_Backup
Drive sorted-data folder: /content/drive/MyDrive/ZeroDay_IoT_Research_Backup/chronological_parquet

[3] Restoring source-class metadata
------------------------------------------------------------------------------
Source classes: 33
Expected rows: 39,851,619

[4] Rebuilding chronological file lookup
------------------------------------------------------------------------------

OSError: [Errno 107] Error reading bytes from file. Detail: [errno 107] Transport endpoint is not connected

# Recovery Step R6-R2 — Remount Drive and Restore Parquet Locally

In [ ]:
# ======================================================================
# RECOVERY STEP R6-R2
# REMOUNT GOOGLE DRIVE + RESTORE PERSISTENT PARQUET FILES LOCALLY
# ======================================================================

from google.colab import drive
from pathlib import Path

import os
import time
import shutil
import pyarrow.parquet as pq

print("=" * 78)
print("RECOVERY STEP R6-R2 — RESTORE DRIVE PARQUET DATASET LOCALLY")
print("=" * 78)


# ======================================================================
# 1 — MAKE SURE SOURCE METADATA SURVIVED
# ======================================================================

print("\n[1] Checking recovered metadata")
print("-" * 78)

if "SOURCE_CLASS_TO_ROW_COUNT" not in globals():

    raise RuntimeError(
        "SOURCE_CLASS_TO_ROW_COUNT is missing. "
        "Send me this output; do not rerun R5."
    )

print(
    "Source classes:",
    len(SOURCE_CLASS_TO_ROW_COUNT)
)

print(
    "Expected rows:",
    f"{sum(SOURCE_CLASS_TO_ROW_COUNT.values()):,}"
)


# ======================================================================
# 2 — CLEANLY DISCONNECT BROKEN DRIVE MOUNT
# ======================================================================

print("\n[2] Resetting Google Drive connection")
print("-" * 78)

try:

    drive.flush_and_unmount()

    print(
        "Previous Drive mount disconnected."
    )

except Exception as error:

    print(
        "Previous mount could not be cleanly disconnected."
    )

    print(
        "This is okay:",
        str(error)[:150]
    )


# Small pause before remount
time.sleep(3)


# ======================================================================
# 3 — FORCE REMOUNT GOOGLE DRIVE
# ======================================================================

print("\n[3] Remounting Google Drive")
print("-" * 78)

drive.mount(
    "/content/drive",
    force_remount=True
)


DRIVE_ROOT = Path(
    "/content/drive/MyDrive"
)


if not DRIVE_ROOT.exists():

    raise RuntimeError(
        "Google Drive remount failed."
    )


print(
    "Google Drive mounted:",
    True
)


# ======================================================================
# 4 — LOCATE PERSISTENT PARQUET DATASET
# ======================================================================

print("\n[4] Checking persistent chronological dataset")
print("-" * 78)


DRIVE_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


DRIVE_SORTED_DATA_DIR = (
    DRIVE_PROJECT_ROOT
    / "chronological_parquet"
)


if not DRIVE_SORTED_DATA_DIR.exists():

    raise RuntimeError(
        "chronological_parquet folder is missing from Google Drive."
    )


drive_parquet_files = sorted(
    DRIVE_SORTED_DATA_DIR.glob("*.parquet")
)


print(
    "Parquet files found in Drive:",
    len(drive_parquet_files)
)


if len(drive_parquet_files) != 33:

    raise RuntimeError(
        f"Expected 33 Drive Parquet files, "
        f"but found {len(drive_parquet_files)}."
    )


print(
    "✅ All 33 persistent files are visible."
)


# ======================================================================
# 5 — PREPARE LOCAL RESTORE DIRECTORY
# ======================================================================

print("\n[5] Preparing local restore directory")
print("-" * 78)


PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)


SORTED_DATA_DIR = (
    PROJECT_ROOT
    / "dataset"
    / "chronological_parquet"
)


SORTED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "Local restore folder:",
    SORTED_DATA_DIR
)


# ======================================================================
# 6 — COPY EACH DRIVE FILE LOCALLY WITH RETRY
# ======================================================================

print("\n[6] Restoring 33 Parquet files from Drive")
print("-" * 78)


SORTED_FILE_BY_SOURCE_CLASS = {}

restore_records = []


for index, (
    source_class,
    expected_rows
) in enumerate(
    SOURCE_CLASS_TO_ROW_COUNT.items(),
    start=1
):

    file_name = (
        source_class
        + ".parquet"
    )


    drive_path = (
        DRIVE_SORTED_DATA_DIR
        / file_name
    )


    local_path = (
        SORTED_DATA_DIR
        / file_name
    )


    print(
        f"\n{index:02d}/33 "
        f"{source_class}"
    )


    if not drive_path.exists():

        raise RuntimeError(
            f"Drive file missing: {drive_path}"
        )


    # --------------------------------------------------------------
    # Reuse valid local file if already restored
    # --------------------------------------------------------------

    local_valid = False


    if local_path.exists():

        try:

            local_rows = int(
                pq.ParquetFile(
                    local_path
                )
                .metadata
                .num_rows
            )

            local_valid = (
                local_rows
                ==
                expected_rows
            )

        except Exception:

            local_valid = False


    if local_valid:

        print(
            "✅ Valid local file already exists."
        )

    else:

        if local_path.exists():
            local_path.unlink()


        copied = False
        last_error = None


        for attempt in range(
            1,
            4
        ):

            try:

                print(
                    f"Copy attempt {attempt}/3..."
                )

                shutil.copyfile(
                    drive_path,
                    local_path
                )


                # Validate local Parquet footer
                local_rows = int(
                    pq.ParquetFile(
                        local_path
                    )
                    .metadata
                    .num_rows
                )


                if local_rows != expected_rows:

                    raise RuntimeError(
                        f"Row mismatch: "
                        f"expected {expected_rows:,}, "
                        f"got {local_rows:,}"
                    )


                copied = True

                print(
                    "✅ Restored and validated:",
                    f"{local_rows:,}",
                    "rows"
                )

                break


            except Exception as error:

                last_error = error

                print(
                    "⚠️ Attempt failed:",
                    str(error)[:180]
                )


                if local_path.exists():

                    local_path.unlink(
                        missing_ok=True
                    )


                time.sleep(
                    5
                )


        if not copied:

            raise RuntimeError(
                f"Could not restore {source_class} "
                f"after 3 attempts.\n"
                f"Last error: {last_error}"
            )


    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ] = local_path


    restore_records.append({
        "source_attack_class":
            source_class,

        "expected_rows":
            int(expected_rows),

        "local_file":
            str(local_path),

        "restored":
            True
    })


# ======================================================================
# 7 — FINAL LOCAL VALIDATION
# ======================================================================

print("\n[7] Final local dataset validation")
print("-" * 78)


total_local_rows = 0
invalid_local_files = []


for (
    source_class,
    local_path
) in SORTED_FILE_BY_SOURCE_CLASS.items():

    expected_rows = int(
        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    try:

        actual_rows = int(
            pq.ParquetFile(
                local_path
            )
            .metadata
            .num_rows
        )

    except Exception as error:

        invalid_local_files.append(
            (
                source_class,
                str(error)
            )
        )

        continue


    if actual_rows != expected_rows:

        invalid_local_files.append(
            (
                source_class,
                f"{actual_rows} != {expected_rows}"
            )
        )

    else:

        total_local_rows += actual_rows


TOTAL_ROWS = int(
    sum(
        SOURCE_CLASS_TO_ROW_COUNT.values()
    )
)


LOCAL_RESTORE_VALID = bool(

    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ) == 33

    and

    len(
        invalid_local_files
    ) == 0

    and

    total_local_rows
    ==
    TOTAL_ROWS
)


print(
    "Local Parquet files:",
    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ),
    "/ 33"
)

print(
    "Invalid local files:",
    len(
        invalid_local_files
    )
)

print(
    "Local rows restored:",
    f"{total_local_rows:,}"
)

print(
    "Expected rows      :",
    f"{TOTAL_ROWS:,}"
)


print("\n" + "=" * 78)

if LOCAL_RESTORE_VALID:

    print(
        "✅ RECOVERY STEP R6-R2 PASSED — "
        "All 33 chronological Parquet files were restored "
        "from Google Drive to local Colab storage."
    )

else:

    print(
        "❌ RECOVERY STEP R6-R2 FAILED — "
        "Do not continue yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP R6-R2 — RESTORE DRIVE PARQUET DATASET LOCALLY
==============================================================================

[1] Checking recovered metadata
------------------------------------------------------------------------------
Source classes: 33
Expected rows: 39,851,619

[2] Resetting Google Drive connection
------------------------------------------------------------------------------
Previous Drive mount disconnected.

[3] Remounting Google Drive
------------------------------------------------------------------------------
Mounted at /content/drive
Google Drive mounted: True

[4] Checking persistent chronological dataset
------------------------------------------------------------------------------
Parquet files found in Drive: 33
✅ All 33 persistent files are visible.

[5] Preparing local restore directory
------------------------------------------------------------------------------
Local restore folder: /content/ZeroDay_IoT_Research/dataset/chronological_parquet

[6] Restoring 33 Parquet files from Drive
------------------------------------------------------------------------------

01/33 Backdoor_Malware
Copy attempt 1/3...
✅ Restored and validated: 2,703 rows

02/33 Benign_Final
Copy attempt 1/3...
✅ Restored and validated: 91,506 rows

03/33 BrowserHijacking
Copy attempt 1/3...
✅ Restored and validated: 3,286 rows

04/33 CommandInjection
Copy attempt 1/3...
✅ Restored and validated: 3,848 rows

05/33 DDoS-ACK_Fragmentation
Copy attempt 1/3...
✅ Restored and validated: 37,296 rows

06/33 DDoS-HTTP_Flood
Copy attempt 1/3...
✅ Restored and validated: 513,672 rows

07/33 DDoS-ICMP_Flood
Copy attempt 1/3...
✅ Restored and validated: 7,834 rows

08/33 DDoS-ICMP_Fragmentation
Copy attempt 1/3...
✅ Restored and validated: 25,106 rows

09/33 DDoS-PSHACK_Flood
Copy attempt 1/3...
✅ Restored and validated: 5,007,067 rows

10/33 DDoS-RSTFINFlood
Copy attempt 1/3...
✅ Restored and validated: 12,968,618 rows

11/33 DDoS-SYN_Flood
Copy attempt 1/3...
✅ Restored and validated: 6,366,353 rows

12/33 DDoS-SlowLoris
Copy attempt 1/3...
✅ Restored and validated: 196,578 rows

13/33 DDoS-SynonymousIP_Flood
Copy attempt 1/3...
✅ Restored and validated: 799,351 rows

14/33 DDoS-TCP_Flood
Copy attempt 1/3...
✅ Restored and validated: 4,945,887 rows

15/33 DDoS-UDP_Flood
Copy attempt 1/3...
✅ Restored and validated: 41,146 rows

16/33 DDoS-UDP_Fragmentation
Copy attempt 1/3...
✅ Restored and validated: 9,757 rows

17/33 DNS_Spoofing
Copy attempt 1/3...
✅ Restored and validated: 74,938 rows

18/33 DictionaryBruteForce
Copy attempt 1/3...
✅ Restored and validated: 8,488 rows

19/33 DoS-HTTP_Flood
Copy attempt 1/3...
✅ Restored and validated: 965,554 rows

20/33 DoS-SYN_Flood
Copy attempt 1/3...
✅ Restored and validated: 3,997,110 rows

21/33 DoS-TCP_Flood
Copy attempt 1/3...
✅ Restored and validated: 1,638,068 rows

22/33 DoS-UDP_Flood
Copy attempt 1/3...
✅ Restored and validated: 934,009 rows

23/33 MITM-ArpSpoofing
Copy attempt 1/3...
✅ Restored and validated: 72,853 rows

24/33 Mirai-greeth_flood
Copy attempt 1/3...
✅ Restored and validated: 5,155 rows

25/33 Mirai-greip_flood
Copy attempt 1/3...
✅ Restored and validated: 10,401 rows

26/33 Mirai-udpplain
Copy attempt 1/3...
✅ Restored and validated: 7,455 rows

27/33 Recon-HostDiscovery
Copy attempt 1/3...
✅ Restored and validated: 329,985 rows

28/33 Recon-OSScan
Copy attempt 1/3...
✅ Restored and validated: 158,682 rows

29/33 Recon-PingSweep
Copy attempt 1/3...
✅ Restored and validated: 1,947 rows

30/33 Recon-PortScan
Copy attempt 1/3...
✅ Restored and validated: 175,050 rows

31/33 SqlInjection
Copy attempt 1/3...
✅ Restored and validated: 6,596 rows

32/33 VulnerabilityScan
Copy attempt 1/3...
✅ Restored and validated: 442,122 rows

33/33 XSS
Copy attempt 1/3...
✅ Restored and validated: 3,198 rows

[7] Final local dataset validation
------------------------------------------------------------------------------
Local Parquet files: 33 / 33
Invalid local files: 0
Local rows restored: 39,851,619
Expected rows      : 39,851,619

==============================================================================
✅ RECOVERY STEP R6-R2 PASSED — All 33 chronological Parquet files were restored from Google Drive to local Colab storage.
==============================================================================

# Recovery Step R6-V — Verify chronological order locally

In [ ]:
# ======================================================================
# RECOVERY STEP R6-R2
# REMOUNT GOOGLE DRIVE + RESTORE PERSISTENT PARQUET FILES LOCALLY
# ======================================================================

from google.colab import drive
from pathlib import Path

import os
import time
import shutil
import pyarrow.parquet as pq

print("=" * 78)
print("RECOVERY STEP R6-R2 — RESTORE DRIVE PARQUET DATASET LOCALLY")
print("=" * 78)


# ======================================================================
# 1 — MAKE SURE SOURCE METADATA SURVIVED
# ======================================================================

print("\n[1] Checking recovered metadata")
print("-" * 78)

if "SOURCE_CLASS_TO_ROW_COUNT" not in globals():

    raise RuntimeError(
        "SOURCE_CLASS_TO_ROW_COUNT is missing. "
        "Send me this output; do not rerun R5."
    )

print(
    "Source classes:",
    len(SOURCE_CLASS_TO_ROW_COUNT)
)

print(
    "Expected rows:",
    f"{sum(SOURCE_CLASS_TO_ROW_COUNT.values()):,}"
)


# ======================================================================
# 2 — CLEANLY DISCONNECT BROKEN DRIVE MOUNT
# ======================================================================

print("\n[2] Resetting Google Drive connection")
print("-" * 78)

try:

    drive.flush_and_unmount()

    print(
        "Previous Drive mount disconnected."
    )

except Exception as error:

    print(
        "Previous mount could not be cleanly disconnected."
    )

    print(
        "This is okay:",
        str(error)[:150]
    )


# Small pause before remount
time.sleep(3)


# ======================================================================
# 3 — FORCE REMOUNT GOOGLE DRIVE
# ======================================================================

print("\n[3] Remounting Google Drive")
print("-" * 78)

drive.mount(
    "/content/drive",
    force_remount=True
)


DRIVE_ROOT = Path(
    "/content/drive/MyDrive"
)


if not DRIVE_ROOT.exists():

    raise RuntimeError(
        "Google Drive remount failed."
    )


print(
    "Google Drive mounted:",
    True
)


# ======================================================================
# 4 — LOCATE PERSISTENT PARQUET DATASET
# ======================================================================

print("\n[4] Checking persistent chronological dataset")
print("-" * 78)


DRIVE_PROJECT_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


DRIVE_SORTED_DATA_DIR = (
    DRIVE_PROJECT_ROOT
    / "chronological_parquet"
)


if not DRIVE_SORTED_DATA_DIR.exists():

    raise RuntimeError(
        "chronological_parquet folder is missing from Google Drive."
    )


drive_parquet_files = sorted(
    DRIVE_SORTED_DATA_DIR.glob("*.parquet")
)


print(
    "Parquet files found in Drive:",
    len(drive_parquet_files)
)


if len(drive_parquet_files) != 33:

    raise RuntimeError(
        f"Expected 33 Drive Parquet files, "
        f"but found {len(drive_parquet_files)}."
    )


print(
    "✅ All 33 persistent files are visible."
)


# ======================================================================
# 5 — PREPARE LOCAL RESTORE DIRECTORY
# ======================================================================

print("\n[5] Preparing local restore directory")
print("-" * 78)


PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)


SORTED_DATA_DIR = (
    PROJECT_ROOT
    / "dataset"
    / "chronological_parquet"
)


SORTED_DATA_DIR.mkdir(
    parents=True,
    exist_ok=True
)


print(
    "Local restore folder:",
    SORTED_DATA_DIR
)


# ======================================================================
# 6 — COPY EACH DRIVE FILE LOCALLY WITH RETRY
# ======================================================================

print("\n[6] Restoring 33 Parquet files from Drive")
print("-" * 78)


SORTED_FILE_BY_SOURCE_CLASS = {}

restore_records = []


for index, (
    source_class,
    expected_rows
) in enumerate(
    SOURCE_CLASS_TO_ROW_COUNT.items(),
    start=1
):

    file_name = (
        source_class
        + ".parquet"
    )


    drive_path = (
        DRIVE_SORTED_DATA_DIR
        / file_name
    )


    local_path = (
        SORTED_DATA_DIR
        / file_name
    )


    print(
        f"\n{index:02d}/33 "
        f"{source_class}"
    )


    if not drive_path.exists():

        raise RuntimeError(
            f"Drive file missing: {drive_path}"
        )


    # --------------------------------------------------------------
    # Reuse valid local file if already restored
    # --------------------------------------------------------------

    local_valid = False


    if local_path.exists():

        try:

            local_rows = int(
                pq.ParquetFile(
                    local_path
                )
                .metadata
                .num_rows
            )

            local_valid = (
                local_rows
                ==
                expected_rows
            )

        except Exception:

            local_valid = False


    if local_valid:

        print(
            "✅ Valid local file already exists."
        )

    else:

        if local_path.exists():
            local_path.unlink()


        copied = False
        last_error = None


        for attempt in range(
            1,
            4
        ):

            try:

                print(
                    f"Copy attempt {attempt}/3..."
                )

                shutil.copyfile(
                    drive_path,
                    local_path
                )


                # Validate local Parquet footer
                local_rows = int(
                    pq.ParquetFile(
                        local_path
                    )
                    .metadata
                    .num_rows
                )


                if local_rows != expected_rows:

                    raise RuntimeError(
                        f"Row mismatch: "
                        f"expected {expected_rows:,}, "
                        f"got {local_rows:,}"
                    )


                copied = True

                print(
                    "✅ Restored and validated:",
                    f"{local_rows:,}",
                    "rows"
                )

                break


            except Exception as error:

                last_error = error

                print(
                    "⚠️ Attempt failed:",
                    str(error)[:180]
                )


                if local_path.exists():

                    local_path.unlink(
                        missing_ok=True
                    )


                time.sleep(
                    5
                )


        if not copied:

            raise RuntimeError(
                f"Could not restore {source_class} "
                f"after 3 attempts.\n"
                f"Last error: {last_error}"
            )


    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ] = local_path


    restore_records.append({
        "source_attack_class":
            source_class,

        "expected_rows":
            int(expected_rows),

        "local_file":
            str(local_path),

        "restored":
            True
    })


# ======================================================================
# 7 — FINAL LOCAL VALIDATION
# ======================================================================

print("\n[7] Final local dataset validation")
print("-" * 78)


total_local_rows = 0
invalid_local_files = []


for (
    source_class,
    local_path
) in SORTED_FILE_BY_SOURCE_CLASS.items():

    expected_rows = int(
        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )


    try:

        actual_rows = int(
            pq.ParquetFile(
                local_path
            )
            .metadata
            .num_rows
        )

    except Exception as error:

        invalid_local_files.append(
            (
                source_class,
                str(error)
            )
        )

        continue


    if actual_rows != expected_rows:

        invalid_local_files.append(
            (
                source_class,
                f"{actual_rows} != {expected_rows}"
            )
        )

    else:

        total_local_rows += actual_rows


TOTAL_ROWS = int(
    sum(
        SOURCE_CLASS_TO_ROW_COUNT.values()
    )
)


LOCAL_RESTORE_VALID = bool(

    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ) == 33

    and

    len(
        invalid_local_files
    ) == 0

    and

    total_local_rows
    ==
    TOTAL_ROWS
)


print(
    "Local Parquet files:",
    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ),
    "/ 33"
)

print(
    "Invalid local files:",
    len(
        invalid_local_files
    )
)

print(
    "Local rows restored:",
    f"{total_local_rows:,}"
)

print(
    "Expected rows      :",
    f"{TOTAL_ROWS:,}"
)


print("\n" + "=" * 78)

if LOCAL_RESTORE_VALID:

    print(
        "✅ RECOVERY STEP R6-R2 PASSED — "
        "All 33 chronological Parquet files were restored "
        "from Google Drive to local Colab storage."
    )

else:

    print(
        "❌ RECOVERY STEP R6-R2 FAILED — "
        "Do not continue yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP R6-R2 — RESTORE DRIVE PARQUET DATASET LOCALLY
==============================================================================

[1] Checking recovered metadata
------------------------------------------------------------------------------

RuntimeError: SOURCE_CLASS_TO_ROW_COUNT is missing. Send me this output; do not rerun R5.

# Account Check A1 — Verify backup access from the new account

In [ ]:
# ======================================================================
# ACCOUNT CHECK A1 — VERIFY BACKUP ACCESS FROM NEW GOOGLE ACCOUNT
# ======================================================================

from google.colab import drive
from pathlib import Path

print("=" * 78)
print("ACCOUNT CHECK A1 — VERIFY NEW ACCOUNT BACKUP ACCESS")
print("=" * 78)

# ----------------------------------------------------------------------
# 1. Disconnect any previous Drive session
# ----------------------------------------------------------------------

print("\n[1] Resetting Google Drive connection")
print("-" * 78)

try:
    drive.flush_and_unmount()
    print("Previous Drive connection removed.")
except Exception:
    print("No active Drive connection needed to be removed.")

# ----------------------------------------------------------------------
# 2. Mount Drive using the NEW Google account
# ----------------------------------------------------------------------

print("\n[2] Mounting Google Drive")
print("-" * 78)

drive.mount(
    "/content/drive",
    force_remount=True
)

# ----------------------------------------------------------------------
# 3. Check expected backup location
# ----------------------------------------------------------------------

print("\n[3] Checking research backup")
print("-" * 78)

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

PARQUET_DIR = (
    BACKUP_ROOT
    / "chronological_parquet"
)

backup_exists = BACKUP_ROOT.exists()
parquet_dir_exists = PARQUET_DIR.exists()

parquet_files = []

if parquet_dir_exists:
    parquet_files = list(
        PARQUET_DIR.glob("*.parquet")
    )

print(
    "Backup folder exists       :",
    backup_exists
)

print(
    "Chronological folder exists:",
    parquet_dir_exists
)

print(
    "Parquet files found        :",
    len(parquet_files)
)

# ----------------------------------------------------------------------
# 4. Final result
# ----------------------------------------------------------------------

print("\n" + "=" * 78)

if (
    backup_exists
    and parquet_dir_exists
    and len(parquet_files) == 33
):
    print(
        "✅ ACCOUNT CHECK A1 PASSED — "
        "The new Google account can access all 33 backup files."
    )

else:
    print(
        "⚠️ ACCOUNT CHECK A1 NOT READY"
    )

    print(
        "\nThe backup is not visible inside the new account's My Drive."
    )

    print(
        "Do NOT rerun dataset download or sorting."
    )

print("=" * 78)

==============================================================================
ACCOUNT CHECK A1 — VERIFY NEW ACCOUNT BACKUP ACCESS
==============================================================================

[1] Resetting Google Drive connection
------------------------------------------------------------------------------
Drive not mounted, so nothing to flush and unmount.
Previous Drive connection removed.

[2] Mounting Google Drive
------------------------------------------------------------------------------
Mounted at /content/drive

[3] Checking research backup
------------------------------------------------------------------------------
Backup folder exists       : True
Chronological folder exists: True
Parquet files found        : 33

==============================================================================
✅ ACCOUNT CHECK A1 PASSED — The new Google account can access all 33 backup files.
==============================================================================

# Recovery Step A2 — Restore the 33 Parquet files locally

In [ ]:
# ======================================================================
# RECOVERY STEP A2 — RESTORE 33 PARQUET FILES FROM NEW ACCOUNT
# ======================================================================

from pathlib import Path
import shutil
import time
import pyarrow.parquet as pq

print("=" * 78)
print("RECOVERY STEP A2 — RESTORE CHRONOLOGICAL DATASET LOCALLY")
print("=" * 78)


# ======================================================================
# 1 — SOURCE ROW COUNTS
# ======================================================================

SOURCE_CLASS_TO_ROW_COUNT = {

    "Backdoor_Malware": 2703,
    "Benign_Final": 91506,
    "BrowserHijacking": 3286,
    "CommandInjection": 3848,

    "DDoS-ACK_Fragmentation": 37296,
    "DDoS-HTTP_Flood": 513672,
    "DDoS-ICMP_Flood": 7834,
    "DDoS-ICMP_Fragmentation": 25106,
    "DDoS-PSHACK_Flood": 5007067,
    "DDoS-RSTFINFlood": 12968618,
    "DDoS-SYN_Flood": 6366353,
    "DDoS-SlowLoris": 196578,
    "DDoS-SynonymousIP_Flood": 799351,
    "DDoS-TCP_Flood": 4945887,
    "DDoS-UDP_Flood": 41146,
    "DDoS-UDP_Fragmentation": 9757,

    "DNS_Spoofing": 74938,
    "DictionaryBruteForce": 8488,

    "DoS-HTTP_Flood": 965554,
    "DoS-SYN_Flood": 3997110,
    "DoS-TCP_Flood": 1638068,
    "DoS-UDP_Flood": 934009,

    "MITM-ArpSpoofing": 72853,

    "Mirai-greeth_flood": 5155,
    "Mirai-greip_flood": 10401,
    "Mirai-udpplain": 7455,

    "Recon-HostDiscovery": 329985,
    "Recon-OSScan": 158682,
    "Recon-PingSweep": 1947,
    "Recon-PortScan": 175050,

    "SqlInjection": 6596,
    "VulnerabilityScan": 442122,
    "XSS": 3198
}

TOTAL_ROWS = sum(
    SOURCE_CLASS_TO_ROW_COUNT.values()
)

print("\n[1] Metadata")
print("-" * 78)

print(
    "Source classes:",
    len(SOURCE_CLASS_TO_ROW_COUNT)
)

print(
    "Expected rows:",
    f"{TOTAL_ROWS:,}"
)


# ======================================================================
# 2 — SOURCE + DESTINATION
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

DRIVE_PARQUET_DIR = (
    BACKUP_ROOT
    / "chronological_parquet"
)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

LOCAL_PARQUET_DIR = (
    PROJECT_ROOT
    / "dataset"
    / "chronological_parquet"
)

LOCAL_PARQUET_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("\n[2] Restore locations")
print("-" * 78)

print(
    "Drive source:",
    DRIVE_PARQUET_DIR
)

print(
    "Local target:",
    LOCAL_PARQUET_DIR
)


# ======================================================================
# 3 — RESTORE FILES
# ======================================================================

print("\n[3] Restoring files")
print("-" * 78)

SORTED_FILE_BY_SOURCE_CLASS = {}

for index, (
    source_class,
    expected_rows
) in enumerate(
    SOURCE_CLASS_TO_ROW_COUNT.items(),
    start=1
):

    drive_file = (
        DRIVE_PARQUET_DIR
        / f"{source_class}.parquet"
    )

    local_file = (
        LOCAL_PARQUET_DIR
        / f"{source_class}.parquet"
    )

    print(
        f"\n{index:02d}/33 "
        f"{source_class}"
    )

    if not drive_file.exists():
        raise RuntimeError(
            f"Missing backup file: {drive_file}"
        )

    # --------------------------------------------------------------
    # Reuse valid local copy
    # --------------------------------------------------------------

    local_valid = False

    if local_file.exists():

        try:

            local_rows = int(
                pq.ParquetFile(
                    local_file
                )
                .metadata
                .num_rows
            )

            local_valid = (
                local_rows
                ==
                expected_rows
            )

        except Exception:

            local_valid = False


    if local_valid:

        print(
            "✅ Valid local copy already exists."
        )

    else:

        if local_file.exists():
            local_file.unlink()

        copied = False
        last_error = None

        for attempt in range(1, 4):

            try:

                print(
                    f"Copy attempt {attempt}/3..."
                )

                shutil.copyfile(
                    drive_file,
                    local_file
                )

                local_rows = int(
                    pq.ParquetFile(
                        local_file
                    )
                    .metadata
                    .num_rows
                )

                if local_rows != expected_rows:

                    raise RuntimeError(
                        f"Expected {expected_rows:,} rows, "
                        f"found {local_rows:,}."
                    )

                copied = True

                print(
                    "✅ Restored:",
                    f"{local_rows:,}",
                    "rows"
                )

                break

            except Exception as error:

                last_error = error

                print(
                    "⚠️ Attempt failed:",
                    str(error)[:180]
                )

                if local_file.exists():
                    local_file.unlink()

                time.sleep(5)

        if not copied:

            raise RuntimeError(
                f"Could not restore {source_class}.\n"
                f"Last error: {last_error}"
            )


    SORTED_FILE_BY_SOURCE_CLASS[
        source_class
    ] = local_file


# ======================================================================
# 4 — FINAL VALIDATION
# ======================================================================

print("\n[4] Final local validation")
print("-" * 78)

invalid_files = []

local_total_rows = 0


for source_class, local_file in (
    SORTED_FILE_BY_SOURCE_CLASS.items()
):

    expected_rows = (
        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )

    try:

        actual_rows = int(
            pq.ParquetFile(
                local_file
            )
            .metadata
            .num_rows
        )

    except Exception as error:

        invalid_files.append(
            (
                source_class,
                str(error)
            )
        )

        continue


    if actual_rows != expected_rows:

        invalid_files.append(
            (
                source_class,
                f"{actual_rows} != {expected_rows}"
            )
        )

    else:

        local_total_rows += actual_rows


A2_VALID = bool(

    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ) == 33

    and

    len(
        invalid_files
    ) == 0

    and

    local_total_rows
    ==
    TOTAL_ROWS
)


print(
    "Local Parquet files:",
    len(
        SORTED_FILE_BY_SOURCE_CLASS
    ),
    "/ 33"
)

print(
    "Invalid files:",
    len(
        invalid_files
    )
)

print(
    "Rows restored:",
    f"{local_total_rows:,}"
)

print(
    "Expected rows:",
    f"{TOTAL_ROWS:,}"
)


print("\n" + "=" * 78)

if A2_VALID:

    print(
        "✅ RECOVERY STEP A2 PASSED — "
        "All 33 chronological Parquet files are ready locally."
    )

else:

    print(
        "❌ RECOVERY STEP A2 FAILED — "
        "Do not continue yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A2 — RESTORE CHRONOLOGICAL DATASET LOCALLY
==============================================================================

[1] Metadata
------------------------------------------------------------------------------
Source classes: 33
Expected rows: 39,851,619

[2] Restore locations
------------------------------------------------------------------------------
Drive source: /content/drive/MyDrive/ZeroDay_IoT_Research_Backup/chronological_parquet
Local target: /content/ZeroDay_IoT_Research/dataset/chronological_parquet

[3] Restoring files
------------------------------------------------------------------------------

01/33 Backdoor_Malware
Copy attempt 1/3...
✅ Restored: 2,703 rows

02/33 Benign_Final
Copy attempt 1/3...
✅ Restored: 91,506 rows

03/33 BrowserHijacking
Copy attempt 1/3...
✅ Restored: 3,286 rows

04/33 CommandInjection
Copy attempt 1/3...
✅ Restored: 3,848 rows

05/33 DDoS-ACK_Fragmentation
Copy attempt 1/3...
✅ Restored: 37,296 rows

06/33 DDoS-HTTP_Flood
Copy attempt 1/3...
✅ Restored: 513,672 rows

07/33 DDoS-ICMP_Flood
Copy attempt 1/3...
✅ Restored: 7,834 rows

08/33 DDoS-ICMP_Fragmentation
Copy attempt 1/3...
✅ Restored: 25,106 rows

09/33 DDoS-PSHACK_Flood
Copy attempt 1/3...
✅ Restored: 5,007,067 rows

10/33 DDoS-RSTFINFlood
Copy attempt 1/3...
✅ Restored: 12,968,618 rows

11/33 DDoS-SYN_Flood
Copy attempt 1/3...
✅ Restored: 6,366,353 rows

12/33 DDoS-SlowLoris
Copy attempt 1/3...
✅ Restored: 196,578 rows

13/33 DDoS-SynonymousIP_Flood
Copy attempt 1/3...
✅ Restored: 799,351 rows

14/33 DDoS-TCP_Flood
Copy attempt 1/3...
✅ Restored: 4,945,887 rows

15/33 DDoS-UDP_Flood
Copy attempt 1/3...
✅ Restored: 41,146 rows

16/33 DDoS-UDP_Fragmentation
Copy attempt 1/3...
✅ Restored: 9,757 rows

17/33 DNS_Spoofing
Copy attempt 1/3...
✅ Restored: 74,938 rows

18/33 DictionaryBruteForce
Copy attempt 1/3...
✅ Restored: 8,488 rows

19/33 DoS-HTTP_Flood
Copy attempt 1/3...
✅ Restored: 965,554 rows

20/33 DoS-SYN_Flood
Copy attempt 1/3...
✅ Restored: 3,997,110 rows

21/33 DoS-TCP_Flood
Copy attempt 1/3...
✅ Restored: 1,638,068 rows

22/33 DoS-UDP_Flood
Copy attempt 1/3...
✅ Restored: 934,009 rows

23/33 MITM-ArpSpoofing
Copy attempt 1/3...
✅ Restored: 72,853 rows

24/33 Mirai-greeth_flood
Copy attempt 1/3...
✅ Restored: 5,155 rows

25/33 Mirai-greip_flood
Copy attempt 1/3...
✅ Restored: 10,401 rows

26/33 Mirai-udpplain
Copy attempt 1/3...
✅ Restored: 7,455 rows

27/33 Recon-HostDiscovery
Copy attempt 1/3...
✅ Restored: 329,985 rows

28/33 Recon-OSScan
Copy attempt 1/3...
✅ Restored: 158,682 rows

29/33 Recon-PingSweep
Copy attempt 1/3...
✅ Restored: 1,947 rows

30/33 Recon-PortScan
Copy attempt 1/3...
✅ Restored: 175,050 rows

31/33 SqlInjection
Copy attempt 1/3...
✅ Restored: 6,596 rows

32/33 VulnerabilityScan
Copy attempt 1/3...
✅ Restored: 442,122 rows

33/33 XSS
Copy attempt 1/3...
✅ Restored: 3,198 rows

[4] Final local validation
------------------------------------------------------------------------------
Local Parquet files: 33 / 33
Invalid files: 0
Rows restored: 39,851,619
Expected rows: 39,851,619

==============================================================================
✅ RECOVERY STEP A2 PASSED — All 33 chronological Parquet files are ready locally.
==============================================================================

# Next only: Recovery Step A3 — Verify chronological order

In [ ]:
# ======================================================================
# RECOVERY STEP A3 — VERIFY LOCAL CHRONOLOGICAL ORDER
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP A3 — VERIFY LOCAL CHRONOLOGICAL ORDER")
print("=" * 78)


# ======================================================================
# 1 — CHECK A2 STATE
# ======================================================================

print("\n[1] Checking A2 state")
print("-" * 78)

required_variables = [
    "SORTED_FILE_BY_SOURCE_CLASS",
    "SOURCE_CLASS_TO_ROW_COUNT",
    "TOTAL_ROWS"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A2."
    )

print(
    "Local Parquet files:",
    len(SORTED_FILE_BY_SOURCE_CLASS),
    "/ 33"
)

print(
    "Expected total rows:",
    f"{TOTAL_ROWS:,}"
)

if len(SORTED_FILE_BY_SOURCE_CLASS) != 33:
    raise RuntimeError(
        "Expected 33 local chronological files."
    )


# ======================================================================
# 2 — TIMESTAMP POLICY
# ======================================================================

TIMESTAMP_FORMAT = "%d/%m/%Y %I:%M:%S %p"

print("\n[2] Timestamp policy")
print("-" * 78)

print(
    "Format:",
    TIMESTAMP_FORMAT
)

print(
    "Timestamp is model input:",
    False
)


# ======================================================================
# 3 — OUTPUT PATHS
# ======================================================================

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

LOCAL_AUDIT_DIR = (
    PROJECT_ROOT
    / "dataset_audit"
)

LOCAL_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

DRIVE_BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

DRIVE_AUDIT_DIR = (
    DRIVE_BACKUP_ROOT
    / "dataset_audit"
)

DRIVE_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

LOCAL_VERIFICATION_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_chronological_verification.csv"
)

LOCAL_SUMMARY_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_chronological_verification_summary.json"
)

DRIVE_VERIFICATION_PATH = (
    DRIVE_AUDIT_DIR
    / LOCAL_VERIFICATION_PATH.name
)

DRIVE_SUMMARY_PATH = (
    DRIVE_AUDIT_DIR
    / LOCAL_SUMMARY_PATH.name
)


# ======================================================================
# 4 — VERIFY ALL FILES
# ======================================================================

print("\n[3] Scanning Timestamp column")
print("-" * 78)

BATCH_SIZE = 250_000

verification_records = []


for file_number, (
    source_class,
    parquet_path
) in enumerate(
    SORTED_FILE_BY_SOURCE_CLASS.items(),
    start=1
):

    parquet_path = Path(parquet_path)

    expected_rows = int(
        SOURCE_CLASS_TO_ROW_COUNT[
            source_class
        ]
    )

    print(
        f"\n{file_number:02d}/33 "
        f"{source_class}"
    )

    parquet_file = pq.ParquetFile(
        parquet_path
    )

    metadata_rows = int(
        parquet_file.metadata.num_rows
    )

    rows_checked = 0
    missing_timestamps = 0
    invalid_timestamps = 0
    backward_transitions = 0

    previous_last_ns = None


    for batch in parquet_file.iter_batches(
        columns=["Timestamp"],
        batch_size=BATCH_SIZE
    ):

        timestamp_series = (
            batch
            .column(0)
            .to_pandas()
        )

        timestamp_text = (
            timestamp_series
            .astype("string")
            .str.strip()
        )

        missing_mask = (
            timestamp_series.isna()
            |
            timestamp_text.eq("")
        )

        parsed = pd.to_datetime(
            timestamp_text,
            format=TIMESTAMP_FORMAT,
            errors="coerce"
        )

        invalid_mask = (
            parsed.isna()
            &
            ~missing_mask
        )

        missing_timestamps += int(
            missing_mask.sum()
        )

        invalid_timestamps += int(
            invalid_mask.sum()
        )

        valid = parsed.dropna()

        if not valid.empty:

            timestamp_ns = (
                valid
                .astype("int64")
                .to_numpy()
            )

            # Check transition between batches
            if (
                previous_last_ns is not None
                and
                timestamp_ns[0] < previous_last_ns
            ):
                backward_transitions += 1

            # Check transitions inside batch
            if len(timestamp_ns) > 1:

                backward_transitions += int(
                    np.count_nonzero(
                        timestamp_ns[1:]
                        <
                        timestamp_ns[:-1]
                    )
                )

            previous_last_ns = int(
                timestamp_ns[-1]
            )

        rows_checked += len(
            timestamp_series
        )


    row_count_match = bool(
        rows_checked
        ==
        metadata_rows
        ==
        expected_rows
    )

    chronological = bool(
        backward_transitions == 0
        and
        missing_timestamps == 0
        and
        invalid_timestamps == 0
    )

    status = (
        "PASS"
        if (
            row_count_match
            and chronological
        )
        else "FAIL"
    )

    verification_records.append({

        "source_attack_class":
            source_class,

        "expected_rows":
            expected_rows,

        "metadata_rows":
            metadata_rows,

        "rows_checked":
            rows_checked,

        "row_count_match":
            row_count_match,

        "missing_timestamps":
            missing_timestamps,

        "invalid_timestamps":
            invalid_timestamps,

        "backward_transitions":
            backward_transitions,

        "chronological":
            chronological,

        "status":
            status
    })

    print(
        "Rows checked        :",
        f"{rows_checked:,}"
    )

    print(
        "Backward transitions:",
        backward_transitions
    )

    print(
        "Missing timestamps  :",
        missing_timestamps
    )

    print(
        "Invalid timestamps  :",
        invalid_timestamps
    )

    print(
        "Status              :",
        status
    )


# ======================================================================
# 5 — SUMMARY
# ======================================================================

VERIFICATION_TABLE = pd.DataFrame(
    verification_records
)

FILES_CHECKED = len(
    VERIFICATION_TABLE
)

FILES_PASSED = int(
    (
        VERIFICATION_TABLE[
            "status"
        ] == "PASS"
    ).sum()
)

FILES_FAILED = (
    FILES_CHECKED
    -
    FILES_PASSED
)

TOTAL_VERIFIED_ROWS = int(
    VERIFICATION_TABLE[
        "rows_checked"
    ].sum()
)

TOTAL_BACKWARD_TRANSITIONS = int(
    VERIFICATION_TABLE[
        "backward_transitions"
    ].sum()
)

TOTAL_MISSING_TIMESTAMPS = int(
    VERIFICATION_TABLE[
        "missing_timestamps"
    ].sum()
)

TOTAL_INVALID_TIMESTAMPS = int(
    VERIFICATION_TABLE[
        "invalid_timestamps"
    ].sum()
)


print("\n[4] Chronological verification summary")
print("-" * 78)

print(
    "Files checked        :",
    FILES_CHECKED
)

print(
    "Files passed         :",
    FILES_PASSED
)

print(
    "Files failed         :",
    FILES_FAILED
)

print(
    "Rows verified        :",
    f"{TOTAL_VERIFIED_ROWS:,}"
)

print(
    "Expected rows        :",
    f"{TOTAL_ROWS:,}"
)

print(
    "Backward transitions :",
    TOTAL_BACKWARD_TRANSITIONS
)

print(
    "Missing timestamps   :",
    TOTAL_MISSING_TIMESTAMPS
)

print(
    "Invalid timestamps   :",
    TOTAL_INVALID_TIMESTAMPS
)


# ======================================================================
# 6 — FINAL PASS / FAIL
# ======================================================================

A3_VALID = bool(

    FILES_CHECKED == 33
    and

    FILES_PASSED == 33
    and

    FILES_FAILED == 0
    and

    TOTAL_VERIFIED_ROWS == TOTAL_ROWS
    and

    TOTAL_BACKWARD_TRANSITIONS == 0
    and

    TOTAL_MISSING_TIMESTAMPS == 0
    and

    TOTAL_INVALID_TIMESTAMPS == 0
)


# ======================================================================
# 7 — SAVE LOCALLY + DRIVE
# ======================================================================

VERIFICATION_TABLE.to_csv(
    LOCAL_VERIFICATION_PATH,
    index=False
)

summary = {

    "files_checked":
        FILES_CHECKED,

    "files_passed":
        FILES_PASSED,

    "files_failed":
        FILES_FAILED,

    "expected_rows":
        int(TOTAL_ROWS),

    "verified_rows":
        TOTAL_VERIFIED_ROWS,

    "backward_transitions":
        TOTAL_BACKWARD_TRANSITIONS,

    "missing_timestamps":
        TOTAL_MISSING_TIMESTAMPS,

    "invalid_timestamps":
        TOTAL_INVALID_TIMESTAMPS,

    "timestamp_format":
        TIMESTAMP_FORMAT,

    "timestamp_used_as_model_feature":
        False,

    "verification_passed":
        A3_VALID
}


with open(
    LOCAL_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        summary,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_VERIFICATION_PATH,
    DRIVE_VERIFICATION_PATH
)

shutil.copy2(
    LOCAL_SUMMARY_PATH,
    DRIVE_SUMMARY_PATH
)


print("\n[5] Recovery Step A3 validation")
print("-" * 78)

print(
    "All 33 files passed       :",
    FILES_PASSED == 33
)

print(
    "All rows conserved        :",
    TOTAL_VERIFIED_ROWS == TOTAL_ROWS
)

print(
    "Backward transitions zero :",
    TOTAL_BACKWARD_TRANSITIONS == 0
)

print(
    "Missing timestamps zero   :",
    TOTAL_MISSING_TIMESTAMPS == 0
)

print(
    "Invalid timestamps zero   :",
    TOTAL_INVALID_TIMESTAMPS == 0
)

print(
    "Audit backed up to Drive  :",
    (
        DRIVE_VERIFICATION_PATH.exists()
        and
        DRIVE_SUMMARY_PATH.exists()
    )
)


print("\n" + "=" * 78)

if A3_VALID:

    print(
        "✅ RECOVERY STEP A3 PASSED — "
        "All 33 chronological files are verified."
    )

else:

    print(
        "❌ RECOVERY STEP A3 FAILED — "
        "Do not continue yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A3 — VERIFY LOCAL CHRONOLOGICAL ORDER
==============================================================================

[1] Checking A2 state
------------------------------------------------------------------------------
Local Parquet files: 33 / 33
Expected total rows: 39,851,619

[2] Timestamp policy
------------------------------------------------------------------------------
Format: %d/%m/%Y %I:%M:%S %p
Timestamp is model input: False

[3] Scanning Timestamp column
------------------------------------------------------------------------------

01/33 Backdoor_Malware
Rows checked        : 2,703
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

02/33 Benign_Final
Rows checked        : 91,506
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

03/33 BrowserHijacking
Rows checked        : 3,286
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

04/33 CommandInjection
Rows checked        : 3,848
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

05/33 DDoS-ACK_Fragmentation
Rows checked        : 37,296
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

06/33 DDoS-HTTP_Flood
Rows checked        : 513,672
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

07/33 DDoS-ICMP_Flood
Rows checked        : 7,834
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

08/33 DDoS-ICMP_Fragmentation
Rows checked        : 25,106
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

09/33 DDoS-PSHACK_Flood
Rows checked        : 5,007,067
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

10/33 DDoS-RSTFINFlood
Rows checked        : 12,968,618
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

11/33 DDoS-SYN_Flood
Rows checked        : 6,366,353
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

12/33 DDoS-SlowLoris
Rows checked        : 196,578
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

13/33 DDoS-SynonymousIP_Flood
Rows checked        : 799,351
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

14/33 DDoS-TCP_Flood
Rows checked        : 4,945,887
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

15/33 DDoS-UDP_Flood
Rows checked        : 41,146
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

16/33 DDoS-UDP_Fragmentation
Rows checked        : 9,757
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

17/33 DNS_Spoofing
Rows checked        : 74,938
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

18/33 DictionaryBruteForce
Rows checked        : 8,488
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

19/33 DoS-HTTP_Flood
Rows checked        : 965,554
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

20/33 DoS-SYN_Flood
Rows checked        : 3,997,110
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

21/33 DoS-TCP_Flood
Rows checked        : 1,638,068
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

22/33 DoS-UDP_Flood
Rows checked        : 934,009
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

23/33 MITM-ArpSpoofing
Rows checked        : 72,853
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

24/33 Mirai-greeth_flood
Rows checked        : 5,155
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

25/33 Mirai-greip_flood
Rows checked        : 10,401
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

26/33 Mirai-udpplain
Rows checked        : 7,455
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

27/33 Recon-HostDiscovery
Rows checked        : 329,985
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

28/33 Recon-OSScan
Rows checked        : 158,682
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

29/33 Recon-PingSweep
Rows checked        : 1,947
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

30/33 Recon-PortScan
Rows checked        : 175,050
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

31/33 SqlInjection
Rows checked        : 6,596
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

32/33 VulnerabilityScan
Rows checked        : 442,122
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

33/33 XSS
Rows checked        : 3,198
Backward transitions: 0
Missing timestamps  : 0
Invalid timestamps  : 0
Status              : PASS

[4] Chronological verification summary
------------------------------------------------------------------------------
Files checked        : 33
Files passed         : 33
Files failed         : 0
Rows verified        : 39,851,619
Expected rows        : 39,851,619
Backward transitions : 0
Missing timestamps   : 0
Invalid timestamps   : 0

[5] Recovery Step A3 validation
------------------------------------------------------------------------------
All 33 files passed       : True
All rows conserved        : True
Backward transitions zero : True
Missing timestamps zero   : True
Invalid timestamps zero   : True
Audit backed up to Drive  : True

==============================================================================
✅ RECOVERY STEP A3 PASSED — All 33 chronological files are verified.
==============================================================================

Recovery Step A4 — Rebuild strict 7-fold LOAFO manifests

In [ ]:
# ======================================================================
# RECOVERY STEP A4 — REBUILD STRICT 7-FOLD LOAFO MANIFESTS
# ======================================================================

from pathlib import Path
import json
import shutil
import pandas as pd


print("=" * 78)
print("RECOVERY STEP A4 — REBUILD STRICT 7-FOLD LOAFO MANIFESTS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A3 STATE
# ======================================================================

print("\n[1] Verifying A3 state")
print("-" * 78)

required_variables = [
    "SORTED_FILE_BY_SOURCE_CLASS",
    "SOURCE_CLASS_TO_ROW_COUNT",
    "TOTAL_ROWS"
]

missing_variables = [
    variable
    for variable in required_variables
    if variable not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A2/A3."
    )

if len(SORTED_FILE_BY_SOURCE_CLASS) != 33:
    raise RuntimeError(
        "Expected 33 verified chronological files."
    )

if TOTAL_ROWS != 39_851_619:
    raise RuntimeError(
        "Unexpected total dataset row count."
    )

print(
    "Chronological files:",
    len(SORTED_FILE_BY_SOURCE_CLASS),
    "/ 33"
)

print(
    "Dataset rows:",
    f"{TOTAL_ROWS:,}"
)

print("✅ A3 state is available.")


# ======================================================================
# 2 — SOURCE CLASS → FAMILY MAPPING
# ======================================================================

print("\n[2] Restoring research-family mapping")
print("-" * 78)

SOURCE_CLASS_TO_FAMILY = {

    # DDoS
    "DDoS-ACK_Fragmentation": "DDoS",
    "DDoS-HTTP_Flood": "DDoS",
    "DDoS-ICMP_Flood": "DDoS",
    "DDoS-ICMP_Fragmentation": "DDoS",
    "DDoS-PSHACK_Flood": "DDoS",
    "DDoS-RSTFINFlood": "DDoS",
    "DDoS-SYN_Flood": "DDoS",
    "DDoS-SlowLoris": "DDoS",
    "DDoS-SynonymousIP_Flood": "DDoS",
    "DDoS-TCP_Flood": "DDoS",
    "DDoS-UDP_Flood": "DDoS",
    "DDoS-UDP_Fragmentation": "DDoS",

    # DoS
    "DoS-HTTP_Flood": "DoS",
    "DoS-SYN_Flood": "DoS",
    "DoS-TCP_Flood": "DoS",
    "DoS-UDP_Flood": "DoS",

    # Mirai
    "Mirai-greeth_flood": "Mirai",
    "Mirai-greip_flood": "Mirai",
    "Mirai-udpplain": "Mirai",

    # Recon
    "Recon-HostDiscovery": "Recon",
    "Recon-OSScan": "Recon",
    "Recon-PingSweep": "Recon",
    "Recon-PortScan": "Recon",
    "VulnerabilityScan": "Recon",

    # Spoofing
    "DNS_Spoofing": "Spoofing",
    "MITM-ArpSpoofing": "Spoofing",

    # Web
    "Backdoor_Malware": "Web",
    "BrowserHijacking": "Web",
    "CommandInjection": "Web",
    "SqlInjection": "Web",
    "XSS": "Web",

    # Brute Force
    "DictionaryBruteForce": "BruteForce",

    # Benign
    "Benign_Final": "Benign"
}


LOAFO_FAMILIES = [
    "DDoS",
    "DoS",
    "Mirai",
    "Recon",
    "Spoofing",
    "Web",
    "BruteForce"
]


if len(SOURCE_CLASS_TO_FAMILY) != 33:
    raise RuntimeError(
        "Expected 33 source-class mappings."
    )


missing_source_mappings = sorted(
    set(SOURCE_CLASS_TO_ROW_COUNT)
    -
    set(SOURCE_CLASS_TO_FAMILY)
)


if missing_source_mappings:
    raise RuntimeError(
        "Missing mappings: "
        + str(missing_source_mappings)
    )


print(
    "Mapped source classes:",
    len(SOURCE_CLASS_TO_FAMILY)
)

print(
    "LOAFO folds:",
    len(LOAFO_FAMILIES)
)


for fold_id, family in enumerate(
    LOAFO_FAMILIES,
    start=1
):
    print(
        f"Fold {fold_id}: {family}"
    )


# ======================================================================
# 3 — SPLIT POLICY
# ======================================================================

print("\n[3] Split policy")
print("-" * 78)

TRAIN_PERCENT = 70
VALIDATION_PERCENT = 15


print(
    "Known source train      : 70%"
)

print(
    "Known source validation : 15%"
)

print(
    "Known source test       : remaining 15%"
)

print(
    "Held-out family         : 100% zero-day attack test"
)

print(
    "Timestamp order         : preserved within every range"
)


# ======================================================================
# 4 — BUILD MANIFEST
# ======================================================================

print("\n[4] Building seven LOAFO manifests")
print("-" * 78)


manifest_records = []


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    for source_class, total_rows in (
        SOURCE_CLASS_TO_ROW_COUNT.items()
    ):

        family = SOURCE_CLASS_TO_FAMILY[
            source_class
        ]

        parquet_path = Path(
            SORTED_FILE_BY_SOURCE_CLASS[
                source_class
            ]
        )

        binary_target = (
            0
            if family == "Benign"
            else 1
        )


        # ==============================================================
        # HELD-OUT ATTACK FAMILY
        # ==============================================================

        if family == held_out_family:

            manifest_records.append({

                "fold_id":
                    fold_id,

                "held_out_family":
                    held_out_family,

                "source_attack_class":
                    source_class,

                "research_family":
                    family,

                "binary_target":
                    binary_target,

                "partition":
                    "zero_day_attack_test",

                "start_row":
                    0,

                "end_row_exclusive":
                    int(total_rows),

                "row_count":
                    int(total_rows),

                "parquet_path":
                    str(parquet_path),

                "allowed_preprocessing_fit":
                    False,

                "allowed_ssl_pretraining":
                    False,

                "allowed_supervised_training":
                    False,

                "allowed_validation_tuning":
                    False,

                "allowed_threshold_selection":
                    False,

                "allowed_final_evaluation":
                    True
            })

            continue


        # ==============================================================
        # KNOWN SOURCE / BENIGN CHRONOLOGICAL SPLIT
        # ==============================================================

        train_rows = (
            int(total_rows)
            * TRAIN_PERCENT
            // 100
        )

        validation_rows = (
            int(total_rows)
            * VALIDATION_PERCENT
            // 100
        )

        train_start = 0
        train_end = train_rows

        validation_start = train_end
        validation_end = (
            validation_start
            +
            validation_rows
        )

        test_start = validation_end
        test_end = int(total_rows)

        test_rows = (
            test_end
            -
            test_start
        )


        # --------------------------------------------------------------
        # Development training
        # --------------------------------------------------------------

        manifest_records.append({

            "fold_id":
                fold_id,

            "held_out_family":
                held_out_family,

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                binary_target,

            "partition":
                "development_train",

            "start_row":
                train_start,

            "end_row_exclusive":
                train_end,

            "row_count":
                train_rows,

            "parquet_path":
                str(parquet_path),

            "allowed_preprocessing_fit":
                True,

            "allowed_ssl_pretraining":
                True,

            "allowed_supervised_training":
                True,

            "allowed_validation_tuning":
                False,

            "allowed_threshold_selection":
                False,

            "allowed_final_evaluation":
                False
        })


        # --------------------------------------------------------------
        # Development validation
        # --------------------------------------------------------------

        manifest_records.append({

            "fold_id":
                fold_id,

            "held_out_family":
                held_out_family,

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                binary_target,

            "partition":
                "development_validation",

            "start_row":
                validation_start,

            "end_row_exclusive":
                validation_end,

            "row_count":
                validation_rows,

            "parquet_path":
                str(parquet_path),

            "allowed_preprocessing_fit":
                False,

            "allowed_ssl_pretraining":
                False,

            "allowed_supervised_training":
                False,

            "allowed_validation_tuning":
                True,

            "allowed_threshold_selection":
                True,

            "allowed_final_evaluation":
                False
        })


        # --------------------------------------------------------------
        # Test range
        # --------------------------------------------------------------

        test_partition = (
            "benign_test"
            if family == "Benign"
            else "known_test"
        )


        manifest_records.append({

            "fold_id":
                fold_id,

            "held_out_family":
                held_out_family,

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                binary_target,

            "partition":
                test_partition,

            "start_row":
                test_start,

            "end_row_exclusive":
                test_end,

            "row_count":
                test_rows,

            "parquet_path":
                str(parquet_path),

            "allowed_preprocessing_fit":
                False,

            "allowed_ssl_pretraining":
                False,

            "allowed_supervised_training":
                False,

            "allowed_validation_tuning":
                False,

            "allowed_threshold_selection":
                False,

            "allowed_final_evaluation":
                True
        })


LOAFO_SPLIT_MANIFEST = pd.DataFrame(
    manifest_records
)


print(
    "Manifest records:",
    len(LOAFO_SPLIT_MANIFEST)
)


# ======================================================================
# 5 — RANGE-INTEGRITY CHECKS
# ======================================================================

print("\n[5] Checking all source ranges")
print("-" * 78)


range_check_records = []


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold_manifest = (
        LOAFO_SPLIT_MANIFEST[
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == fold_id
        ]
    )


    for source_class, expected_rows in (
        SOURCE_CLASS_TO_ROW_COUNT.items()
    ):

        family = SOURCE_CLASS_TO_FAMILY[
            source_class
        ]


        source_ranges = (

            fold_manifest[
                fold_manifest[
                    "source_attack_class"
                ] == source_class
            ]

            .sort_values(
                "start_row"
            )
        )


        row_sum = int(
            source_ranges[
                "row_count"
            ].sum()
        )


        range_lengths_correct = bool(

            (
                source_ranges[
                    "end_row_exclusive"
                ]

                -

                source_ranges[
                    "start_row"
                ]

                ==

                source_ranges[
                    "row_count"
                ]
            ).all()
        )


        starts_at_zero = bool(

            len(source_ranges) > 0

            and

            int(
                source_ranges.iloc[0][
                    "start_row"
                ]
            ) == 0
        )


        ends_at_expected = bool(

            len(source_ranges) > 0

            and

            int(
                source_ranges.iloc[-1][
                    "end_row_exclusive"
                ]
            ) == int(expected_rows)
        )


        contiguous = True

        if len(source_ranges) > 1:

            previous_ends = (
                source_ranges[
                    "end_row_exclusive"
                ]
                .iloc[:-1]
                .to_numpy()
            )

            next_starts = (
                source_ranges[
                    "start_row"
                ]
                .iloc[1:]
                .to_numpy()
            )

            contiguous = bool(
                (
                    previous_ends
                    ==
                    next_starts
                ).all()
            )


        expected_range_count = (
            1
            if family == held_out_family
            else 3
        )


        correct_range_count = bool(
            len(source_ranges)
            ==
            expected_range_count
        )


        if family == held_out_family:

            correct_partition_policy = bool(

                len(source_ranges) == 1

                and

                source_ranges.iloc[0][
                    "partition"
                ]
                ==
                "zero_day_attack_test"
            )

        else:

            expected_partitions = {
                "development_train",
                "development_validation",
                (
                    "benign_test"
                    if family == "Benign"
                    else "known_test"
                )
            }

            correct_partition_policy = bool(

                set(
                    source_ranges[
                        "partition"
                    ]
                )
                ==
                expected_partitions
            )


        valid = bool(

            row_sum
            ==
            int(expected_rows)

            and

            range_lengths_correct

            and

            starts_at_zero

            and

            ends_at_expected

            and

            contiguous

            and

            correct_range_count

            and

            correct_partition_policy
        )


        range_check_records.append({

            "fold_id":
                fold_id,

            "held_out_family":
                held_out_family,

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "expected_rows":
                int(expected_rows),

            "manifest_rows":
                row_sum,

            "range_count":
                len(source_ranges),

            "expected_range_count":
                expected_range_count,

            "ranges_contiguous":
                contiguous,

            "range_lengths_correct":
                range_lengths_correct,

            "partition_policy_correct":
                correct_partition_policy,

            "valid":
                valid
        })


LOAFO_RANGE_CHECKS = pd.DataFrame(
    range_check_records
)


INVALID_RANGE_CHECKS = int(

    (
        ~LOAFO_RANGE_CHECKS[
            "valid"
        ]
    ).sum()
)


print(
    "Range checks:",
    len(LOAFO_RANGE_CHECKS)
)

print(
    "Invalid checks:",
    INVALID_RANGE_CHECKS
)


# ======================================================================
# 6 — BUILD FOLD SUMMARIES
# ======================================================================

print("\n[6] Building fold summaries")
print("-" * 78)


fold_summary_records = []


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold_data = (
        LOAFO_SPLIT_MANIFEST[
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == fold_id
        ]
    )


    development_train_rows = int(
        fold_data.loc[
            fold_data[
                "partition"
            ] == "development_train",
            "row_count"
        ].sum()
    )


    development_validation_rows = int(
        fold_data.loc[
            fold_data[
                "partition"
            ] == "development_validation",
            "row_count"
        ].sum()
    )


    known_test_attack_rows = int(
        fold_data.loc[
            fold_data[
                "partition"
            ] == "known_test",
            "row_count"
        ].sum()
    )


    benign_test_rows = int(
        fold_data.loc[
            fold_data[
                "partition"
            ] == "benign_test",
            "row_count"
        ].sum()
    )


    zero_day_attack_rows = int(
        fold_data.loc[
            fold_data[
                "partition"
            ] == "zero_day_attack_test",
            "row_count"
        ].sum()
    )


    known_evaluation_rows = (
        known_test_attack_rows
        +
        benign_test_rows
    )


    zero_day_evaluation_rows = (
        zero_day_attack_rows
        +
        benign_test_rows
    )


    conserved_dataset_rows = (

        development_train_rows
        +
        development_validation_rows
        +
        known_test_attack_rows
        +
        benign_test_rows
        +
        zero_day_attack_rows
    )


    fold_summary_records.append({

        "fold_id":
            fold_id,

        "held_out_family":
            held_out_family,

        "development_train_rows":
            development_train_rows,

        "development_validation_rows":
            development_validation_rows,

        "known_test_attack_rows":
            known_test_attack_rows,

        "benign_test_rows":
            benign_test_rows,

        "zero_day_attack_rows":
            zero_day_attack_rows,

        "known_evaluation_rows":
            known_evaluation_rows,

        "zero_day_evaluation_rows":
            zero_day_evaluation_rows,

        "conserved_dataset_rows":
            conserved_dataset_rows
    })


LOAFO_FOLD_SUMMARY = pd.DataFrame(
    fold_summary_records
)


display(
    LOAFO_FOLD_SUMMARY
)


# ======================================================================
# 7 — COMPARE WITH OUR PREVIOUS VERIFIED LOAFO COUNTS
# ======================================================================

print("\n[7] Comparing with previous verified fold totals")
print("-" * 78)


EXPECTED_FOLD_TOTALS = {

    "DDoS": {
        "development_train_rows": 6_253_058,
        "development_validation_rows": 1_339_934,
        "known_test_attack_rows": 1_326_235,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 30_918_665,
        "known_evaluation_rows": 1_339_962,
        "zero_day_evaluation_rows": 30_932_392
    },

    "DoS": {
        "development_train_rows": 22_621_800,
        "development_validation_rows": 4_847_517,
        "known_test_attack_rows": 4_833_834,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 7_534_741,
        "known_evaluation_rows": 4_847_561,
        "zero_day_evaluation_rows": 7_548_468
    },

    "Mirai": {
        "development_train_rows": 27_880_011,
        "development_validation_rows": 5_974_276,
        "known_test_attack_rows": 5_960_594,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 23_011,
        "known_evaluation_rows": 5_974_321,
        "zero_day_evaluation_rows": 36_738
    },

    "Recon": {
        "development_train_rows": 27_120_670,
        "development_validation_rows": 5_811_561,
        "known_test_attack_rows": 5_797_875,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 1_107_786,
        "known_evaluation_rows": 5_811_602,
        "zero_day_evaluation_rows": 1_121_513
    },

    "Spoofing": {
        "development_train_rows": 27_792_664,
        "development_validation_rows": 5_955_560,
        "known_test_attack_rows": 5_941_877,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 147_791,
        "known_evaluation_rows": 5_955_604,
        "zero_day_evaluation_rows": 161_518
    },

    "Web": {
        "development_train_rows": 27_882_377,
        "development_validation_rows": 5_974_785,
        "known_test_attack_rows": 5_961_099,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 19_631,
        "known_evaluation_rows": 5_974_826,
        "zero_day_evaluation_rows": 33_358
    },

    "BruteForce": {
        "development_train_rows": 27_890_176,
        "development_validation_rows": 5_976_454,
        "known_test_attack_rows": 5_962_774,
        "benign_test_rows": 13_727,
        "zero_day_attack_rows": 8_488,
        "known_evaluation_rows": 5_976_501,
        "zero_day_evaluation_rows": 22_215
    }
}


historical_match = True


for _, row in LOAFO_FOLD_SUMMARY.iterrows():

    family = row[
        "held_out_family"
    ]

    expected = EXPECTED_FOLD_TOTALS[
        family
    ]

    fold_match = True


    for column, expected_value in (
        expected.items()
    ):

        if int(row[column]) != expected_value:

            fold_match = False

            historical_match = False

            print(
                f"❌ {family} mismatch: "
                f"{column} "
                f"expected={expected_value:,}, "
                f"actual={int(row[column]):,}"
            )


    print(
        f"Fold {int(row['fold_id'])} "
        f"{family:<10}: "
        f"{'MATCH' if fold_match else 'MISMATCH'}"
    )


# ======================================================================
# 8 — STRICT LEAKAGE CHECKS
# ======================================================================

print("\n[8] Strict held-out leakage checks")
print("-" * 78)


integrity_records = []


permission_columns = [
    "allowed_preprocessing_fit",
    "allowed_ssl_pretraining",
    "allowed_supervised_training",
    "allowed_validation_tuning",
    "allowed_threshold_selection"
]


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold_data = (
        LOAFO_SPLIT_MANIFEST[
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == fold_id
        ]
    )


    held_out_rows = (
        fold_data[
            fold_data[
                "research_family"
            ] == held_out_family
        ]
    )


    held_out_non_zero_day_rows = int(

        held_out_rows.loc[
            held_out_rows[
                "partition"
            ]
            !=
            "zero_day_attack_test",

            "row_count"
        ].sum()
    )


    permission_violations = int(

        held_out_rows[
            permission_columns
        ]
        .astype(int)
        .to_numpy()
        .sum()
    )


    expected_zero_day_rows = int(

        sum(
            SOURCE_CLASS_TO_ROW_COUNT[
                source_class
            ]

            for source_class, family
            in SOURCE_CLASS_TO_FAMILY.items()

            if family == held_out_family
        )
    )


    actual_zero_day_rows = int(

        held_out_rows.loc[
            held_out_rows[
                "partition"
            ]
            ==
            "zero_day_attack_test",

            "row_count"
        ].sum()
    )


    rows_conserved = bool(

        int(
            fold_data[
                "row_count"
            ].sum()
        )
        ==
        TOTAL_ROWS
    )


    fold_range_integrity = bool(

        LOAFO_RANGE_CHECKS.loc[
            LOAFO_RANGE_CHECKS[
                "fold_id"
            ] == fold_id,

            "valid"
        ].all()
    )


    no_held_out_leakage = bool(

        held_out_non_zero_day_rows == 0

        and

        permission_violations == 0
    )


    zero_day_complete = bool(

        actual_zero_day_rows
        ==
        expected_zero_day_rows
    )


    fold_valid = bool(

        rows_conserved

        and
        fold_range_integrity

        and
        no_held_out_leakage

        and
        zero_day_complete
    )


    integrity_records.append({

        "fold_id":
            fold_id,

        "held_out_family":
            held_out_family,

        "held_out_rows_outside_zero_day":
            held_out_non_zero_day_rows,

        "held_out_permission_violations":
            permission_violations,

        "expected_zero_day_rows":
            expected_zero_day_rows,

        "actual_zero_day_rows":
            actual_zero_day_rows,

        "rows_conserved":
            rows_conserved,

        "range_integrity":
            fold_range_integrity,

        "no_held_out_leakage":
            no_held_out_leakage,

        "zero_day_complete":
            zero_day_complete,

        "fold_valid":
            fold_valid
    })


LOAFO_INTEGRITY_CHECKS = pd.DataFrame(
    integrity_records
)


display(
    LOAFO_INTEGRITY_CHECKS
)


# ======================================================================
# 9 — SAVE LOCALLY
# ======================================================================

print("\n[9] Saving LOAFO artifacts locally")
print("-" * 78)


PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)


LOCAL_LOAFO_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "loafo_manifests"
)


LOCAL_AUDIT_DIR = (
    PROJECT_ROOT
    / "dataset_audit"
)


LOCAL_LOAFO_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOAFO_MANIFEST_PATH = (
    LOCAL_LOAFO_DIR
    / "CICIoT2023_LOAFO_split_manifest.csv"
)


LOAFO_FOLD_SUMMARY_PATH = (
    LOCAL_LOAFO_DIR
    / "CICIoT2023_LOAFO_fold_summary.csv"
)


LOAFO_RANGE_CHECKS_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_LOAFO_range_integrity.csv"
)


LOAFO_INTEGRITY_CHECKS_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_LOAFO_integrity_checks.csv"
)


LOAFO_POLICY_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_LOAFO_policy.json"
)


LOAFO_SPLIT_MANIFEST.to_csv(
    LOAFO_MANIFEST_PATH,
    index=False
)


LOAFO_FOLD_SUMMARY.to_csv(
    LOAFO_FOLD_SUMMARY_PATH,
    index=False
)


LOAFO_RANGE_CHECKS.to_csv(
    LOAFO_RANGE_CHECKS_PATH,
    index=False
)


LOAFO_INTEGRITY_CHECKS.to_csv(
    LOAFO_INTEGRITY_CHECKS_PATH,
    index=False
)


loafo_policy = {

    "fold_order":
        LOAFO_FAMILIES,

    "known_source_split":
        "70% train / 15% validation / remaining test",

    "held_out_family_policy":
        "100% zero-day attack test",

    "timestamp_order_preserved":
        True,

    "timestamp_used_as_model_feature":
        False,

    "held_out_allowed_preprocessing_fit":
        False,

    "held_out_allowed_ssl_pretraining":
        False,

    "held_out_allowed_supervised_training":
        False,

    "held_out_allowed_validation_tuning":
        False,

    "held_out_allowed_threshold_selection":
        False
}


with open(
    LOAFO_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        loafo_policy,
        file,
        indent=4
    )


# ======================================================================
# 10 — BACK UP TO GOOGLE DRIVE
# ======================================================================

print("\n[10] Persisting LOAFO artifacts to Google Drive")
print("-" * 78)


DRIVE_BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


DRIVE_LOAFO_DIR = (
    DRIVE_BACKUP_ROOT
    / "processed_data"
    / "loafo_manifests"
)


DRIVE_AUDIT_DIR = (
    DRIVE_BACKUP_ROOT
    / "dataset_audit"
)


DRIVE_LOAFO_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in [
    LOAFO_MANIFEST_PATH,
    LOAFO_FOLD_SUMMARY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_LOAFO_DIR
        / source_path.name
    )


for source_path in [
    LOAFO_RANGE_CHECKS_PATH,
    LOAFO_INTEGRITY_CHECKS_PATH,
    LOAFO_POLICY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_AUDIT_DIR
        / source_path.name
    )


print(
    "✅ LOAFO artifacts copied to Drive."
)


# ======================================================================
# 11 — FINAL VALIDATION
# ======================================================================

all_folds_valid = bool(

    LOAFO_INTEGRITY_CHECKS[
        "fold_valid"
    ].all()
)


all_ranges_valid = bool(

    LOAFO_RANGE_CHECKS[
        "valid"
    ].all()
)


manifest_count_correct = bool(

    len(
        LOAFO_SPLIT_MANIFEST
    ) == 629
)


range_count_correct = bool(

    len(
        LOAFO_RANGE_CHECKS
    ) == 231
)


drive_outputs_exist = all([

    (
        DRIVE_LOAFO_DIR
        / LOAFO_MANIFEST_PATH.name
    ).exists(),

    (
        DRIVE_LOAFO_DIR
        / LOAFO_FOLD_SUMMARY_PATH.name
    ).exists(),

    (
        DRIVE_AUDIT_DIR
        / LOAFO_RANGE_CHECKS_PATH.name
    ).exists(),

    (
        DRIVE_AUDIT_DIR
        / LOAFO_INTEGRITY_CHECKS_PATH.name
    ).exists(),

    (
        DRIVE_AUDIT_DIR
        / LOAFO_POLICY_PATH.name
    ).exists()
])


A4_VALID = bool(

    manifest_count_correct

    and
    range_count_correct

    and
    INVALID_RANGE_CHECKS == 0

    and
    all_ranges_valid

    and
    all_folds_valid

    and
    historical_match

    and
    drive_outputs_exist
)


# Compatibility variable for our previous pipeline
STEP_8_5_VALID = A4_VALID


print("\n[11] Recovery Step A4 validation")
print("-" * 78)

print(
    "LOAFO folds                 :",
    len(LOAFO_FAMILIES),
    "/ 7"
)

print(
    "Manifest records            :",
    len(LOAFO_SPLIT_MANIFEST),
    "/ 629"
)

print(
    "Range integrity checks      :",
    len(LOAFO_RANGE_CHECKS),
    "/ 231"
)

print(
    "Invalid ranges              :",
    INVALID_RANGE_CHECKS
)

print(
    "All ranges valid            :",
    all_ranges_valid
)

print(
    "All folds leakage-safe      :",
    bool(
        LOAFO_INTEGRITY_CHECKS[
            "no_held_out_leakage"
        ].all()
    )
)

print(
    "All zero-day sets complete  :",
    bool(
        LOAFO_INTEGRITY_CHECKS[
            "zero_day_complete"
        ].all()
    )
)

print(
    "All fold rows conserved     :",
    bool(
        LOAFO_INTEGRITY_CHECKS[
            "rows_conserved"
        ].all()
    )
)

print(
    "Previous fold totals matched:",
    historical_match
)

print(
    "Artifacts backed up to Drive:",
    drive_outputs_exist
)


print("\n" + "=" * 78)

if A4_VALID:

    print(
        "✅ RECOVERY STEP A4 PASSED — "
        "All seven strict LOAFO manifests were rebuilt "
        "and permanently backed up."
    )

else:

    print(
        "❌ RECOVERY STEP A4 FAILED — "
        "Do not continue to preprocessing yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A4 — REBUILD STRICT 7-FOLD LOAFO MANIFESTS
==============================================================================

[1] Verifying A3 state
------------------------------------------------------------------------------
Chronological files: 33 / 33
Dataset rows: 39,851,619
✅ A3 state is available.

[2] Restoring research-family mapping
------------------------------------------------------------------------------
Mapped source classes: 33
LOAFO folds: 7
Fold 1: DDoS
Fold 2: DoS
Fold 3: Mirai
Fold 4: Recon
Fold 5: Spoofing
Fold 6: Web
Fold 7: BruteForce

[3] Split policy
------------------------------------------------------------------------------
Known source train      : 70%
Known source validation : 15%
Known source test       : remaining 15%
Held-out family         : 100% zero-day attack test
Timestamp order         : preserved within every range

[4] Building seven LOAFO manifests
------------------------------------------------------------------------------
Manifest records: 629

[5] Checking all source ranges
------------------------------------------------------------------------------
Range checks: 231
Invalid checks: 0

[6] Building fold summaries
------------------------------------------------------------------------------

,fold_id,held_out_family,development_train_rows,development_validation_rows,known_test_attack_rows,benign_test_rows,zero_day_attack_rows,known_evaluation_rows,zero_day_evaluation_rows,conserved_dataset_rows
0,1,DDoS,6253059,1339934,1326234,13727,30918665,1339961,30932392,39851619
1,2,DoS,22621801,4847517,4833833,13727,7534741,4847560,7548468,39851619
2,3,Mirai,27880012,5974276,5960593,13727,23011,5974320,36738,39851619
3,4,Recon,27120670,5811561,5797875,13727,1107786,5811602,1121513,39851619
4,5,Spoofing,27792665,5955560,5941876,13727,147791,5955603,161518,39851619
5,6,Web,27882378,5974785,5961098,13727,19631,5974825,33358,39851619
6,7,BruteForce,27890177,5976454,5962773,13727,8488,5976500,22215,39851619

[7] Comparing with previous verified fold totals
------------------------------------------------------------------------------
❌ DDoS mismatch: development_train_rows expected=6,253,058, actual=6,253,059
❌ DDoS mismatch: known_test_attack_rows expected=1,326,235, actual=1,326,234
❌ DDoS mismatch: known_evaluation_rows expected=1,339,962, actual=1,339,961
Fold 1 DDoS      : MISMATCH
❌ DoS mismatch: development_train_rows expected=22,621,800, actual=22,621,801
❌ DoS mismatch: known_test_attack_rows expected=4,833,834, actual=4,833,833
❌ DoS mismatch: known_evaluation_rows expected=4,847,561, actual=4,847,560
Fold 2 DoS       : MISMATCH
❌ Mirai mismatch: development_train_rows expected=27,880,011, actual=27,880,012
❌ Mirai mismatch: known_test_attack_rows expected=5,960,594, actual=5,960,593
❌ Mirai mismatch: known_evaluation_rows expected=5,974,321, actual=5,974,320
Fold 3 Mirai     : MISMATCH
Fold 4 Recon     : MATCH
❌ Spoofing mismatch: development_train_rows expected=27,792,664, actual=27,792,665
❌ Spoofing mismatch: known_test_attack_rows expected=5,941,877, actual=5,941,876
❌ Spoofing mismatch: known_evaluation_rows expected=5,955,604, actual=5,955,603
Fold 5 Spoofing  : MISMATCH
❌ Web mismatch: development_train_rows expected=27,882,377, actual=27,882,378
❌ Web mismatch: known_test_attack_rows expected=5,961,099, actual=5,961,098
❌ Web mismatch: known_evaluation_rows expected=5,974,826, actual=5,974,825
Fold 6 Web       : MISMATCH
❌ BruteForce mismatch: development_train_rows expected=27,890,176, actual=27,890,177
❌ BruteForce mismatch: known_test_attack_rows expected=5,962,774, actual=5,962,773
❌ BruteForce mismatch: known_evaluation_rows expected=5,976,501, actual=5,976,500
Fold 7 BruteForce: MISMATCH

[8] Strict held-out leakage checks
------------------------------------------------------------------------------

,fold_id,held_out_family,held_out_rows_outside_zero_day,held_out_permission_violations,expected_zero_day_rows,actual_zero_day_rows,rows_conserved,range_integrity,no_held_out_leakage,zero_day_complete,fold_valid
0,1,DDoS,0,0,30918665,30918665,True,True,True,True,True
1,2,DoS,0,0,7534741,7534741,True,True,True,True,True
2,3,Mirai,0,0,23011,23011,True,True,True,True,True
3,4,Recon,0,0,1107786,1107786,True,True,True,True,True
4,5,Spoofing,0,0,147791,147791,True,True,True,True,True
5,6,Web,0,0,19631,19631,True,True,True,True,True
6,7,BruteForce,0,0,8488,8488,True,True,True,True,True

[9] Saving LOAFO artifacts locally
------------------------------------------------------------------------------

[10] Persisting LOAFO artifacts to Google Drive
------------------------------------------------------------------------------
✅ LOAFO artifacts copied to Drive.

[11] Recovery Step A4 validation
------------------------------------------------------------------------------
LOAFO folds                 : 7 / 7
Manifest records            : 629 / 629
Range integrity checks      : 231 / 231
Invalid ranges              : 0
All ranges valid            : True
All folds leakage-safe      : True
All zero-day sets complete  : True
All fold rows conserved     : True
Previous fold totals matched: False
Artifacts backed up to Drive: True

==============================================================================
❌ RECOVERY STEP A4 FAILED — Do not continue to preprocessing yet.
==============================================================================

# Do only this now — Recovery Step A4-FIX

In [ ]:
# ======================================================================
# RECOVERY STEP A4-FIX
# RESTORE ORIGINAL LOAFO SPLIT ARITHMETIC EXACTLY
# ======================================================================

from pathlib import Path
import json
import shutil
import pandas as pd

print("=" * 78)
print("RECOVERY STEP A4-FIX — RESTORE ORIGINAL LOAFO SPLITS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY REQUIRED STATE
# ======================================================================

print("\n[1] Checking current A4 state")
print("-" * 78)

required_variables = [
    "SOURCE_CLASS_TO_ROW_COUNT",
    "SOURCE_CLASS_TO_FAMILY",
    "SORTED_FILE_BY_SOURCE_CLASS",
    "LOAFO_FAMILIES",
    "TOTAL_ROWS"
]

missing = [
    name
    for name in required_variables
    if name not in globals()
]

if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
        + "\nPlease rerun A2 and A4 first."
    )

print("Source classes :", len(SOURCE_CLASS_TO_ROW_COUNT))
print("LOAFO families :", len(LOAFO_FAMILIES))
print("Dataset rows   :", f"{TOTAL_ROWS:,}")


# ======================================================================
# 2 — SHOW THE EXACT ROUNDING DIFFERENCE
# ======================================================================

print("\n[2] Confirming original split arithmetic")
print("-" * 78)

recon_portscan_rows = SOURCE_CLASS_TO_ROW_COUNT[
    "Recon-PortScan"
]

integer_method = (
    recon_portscan_rows * 70 // 100
)

original_method = int(
    recon_portscan_rows * 0.70
)

print(
    "Recon-PortScan rows              :",
    f"{recon_portscan_rows:,}"
)

print(
    "Integer-floor reconstruction     :",
    f"{integer_method:,}"
)

print(
    "Original float-truncation result :",
    f"{original_method:,}"
)

print(
    "Difference                      :",
    integer_method - original_method
)


# ======================================================================
# 3 — REBUILD MANIFEST USING ORIGINAL ARITHMETIC
# ======================================================================

print("\n[3] Rebuilding exact original LOAFO manifest")
print("-" * 78)

manifest_records = []


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    for source_class, total_rows in (
        SOURCE_CLASS_TO_ROW_COUNT.items()
    ):

        family = SOURCE_CLASS_TO_FAMILY[
            source_class
        ]

        parquet_path = Path(
            SORTED_FILE_BY_SOURCE_CLASS[
                source_class
            ]
        )

        binary_target = (
            0
            if family == "Benign"
            else 1
        )


        # --------------------------------------------------------------
        # Held-out attack family = 100% zero-day test
        # --------------------------------------------------------------

        if family == held_out_family:

            manifest_records.append({

                "fold_id":
                    fold_id,

                "held_out_family":
                    held_out_family,

                "source_attack_class":
                    source_class,

                "research_family":
                    family,

                "binary_target":
                    binary_target,

                "partition":
                    "zero_day_attack_test",

                "start_row":
                    0,

                "end_row_exclusive":
                    int(total_rows),

                "row_count":
                    int(total_rows),

                "parquet_path":
                    str(parquet_path),

                "allowed_preprocessing_fit":
                    False,

                "allowed_ssl_pretraining":
                    False,

                "allowed_supervised_training":
                    False,

                "allowed_validation_tuning":
                    False,

                "allowed_threshold_selection":
                    False,

                "allowed_final_evaluation":
                    True
            })

            continue


        # --------------------------------------------------------------
        # IMPORTANT:
        # Reproduce original pipeline arithmetic EXACTLY.
        #
        # Do NOT replace these with:
        # total_rows * 70 // 100
        #
        # The original notebook used float multiplication + int()
        # truncation.
        # --------------------------------------------------------------

        train_rows = int(
            int(total_rows) * 0.70
        )

        validation_rows = int(
            int(total_rows) * 0.15
        )

        train_start = 0
        train_end = train_rows

        validation_start = train_end

        validation_end = (
            validation_start
            +
            validation_rows
        )

        test_start = validation_end

        test_end = int(
            total_rows
        )

        test_rows = (
            test_end
            -
            test_start
        )


        ranges = [

            (
                "development_train",
                train_start,
                train_end,
                train_rows
            ),

            (
                "development_validation",
                validation_start,
                validation_end,
                validation_rows
            ),

            (
                (
                    "benign_test"
                    if family == "Benign"
                    else "known_test"
                ),
                test_start,
                test_end,
                test_rows
            )
        ]


        for (
            partition,
            start_row,
            end_row,
            row_count
        ) in ranges:

            is_train = (
                partition
                ==
                "development_train"
            )

            is_validation = (
                partition
                ==
                "development_validation"
            )

            is_final_test = (
                partition
                in {
                    "known_test",
                    "benign_test"
                }
            )


            manifest_records.append({

                "fold_id":
                    fold_id,

                "held_out_family":
                    held_out_family,

                "source_attack_class":
                    source_class,

                "research_family":
                    family,

                "binary_target":
                    binary_target,

                "partition":
                    partition,

                "start_row":
                    int(start_row),

                "end_row_exclusive":
                    int(end_row),

                "row_count":
                    int(row_count),

                "parquet_path":
                    str(parquet_path),

                "allowed_preprocessing_fit":
                    is_train,

                "allowed_ssl_pretraining":
                    is_train,

                "allowed_supervised_training":
                    is_train,

                "allowed_validation_tuning":
                    is_validation,

                "allowed_threshold_selection":
                    is_validation,

                "allowed_final_evaluation":
                    is_final_test
            })


LOAFO_SPLIT_MANIFEST = pd.DataFrame(
    manifest_records
)

print(
    "Manifest records:",
    len(LOAFO_SPLIT_MANIFEST)
)


# ======================================================================
# 4 — REBUILD RANGE INTEGRITY CHECKS
# ======================================================================

print("\n[4] Rechecking source ranges")
print("-" * 78)

range_records = []


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold_manifest = (
        LOAFO_SPLIT_MANIFEST[
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == fold_id
        ]
    )


    for source_class, expected_rows in (
        SOURCE_CLASS_TO_ROW_COUNT.items()
    ):

        family = SOURCE_CLASS_TO_FAMILY[
            source_class
        ]

        ranges = (
            fold_manifest[
                fold_manifest[
                    "source_attack_class"
                ] == source_class
            ]
            .sort_values(
                "start_row"
            )
            .reset_index(drop=True)
        )


        expected_range_count = (
            1
            if family == held_out_family
            else 3
        )


        row_sum_ok = bool(
            int(
                ranges[
                    "row_count"
                ].sum()
            )
            ==
            int(expected_rows)
        )


        length_ok = bool(
            (
                (
                    ranges[
                        "end_row_exclusive"
                    ]
                    -
                    ranges[
                        "start_row"
                    ]
                )
                ==
                ranges[
                    "row_count"
                ]
            ).all()
        )


        starts_zero = bool(
            int(
                ranges.iloc[0][
                    "start_row"
                ]
            ) == 0
        )


        ends_correct = bool(
            int(
                ranges.iloc[-1][
                    "end_row_exclusive"
                ]
            )
            ==
            int(expected_rows)
        )


        contiguous = True

        if len(ranges) > 1:

            contiguous = bool(
                (
                    ranges[
                        "end_row_exclusive"
                    ]
                    .iloc[:-1]
                    .to_numpy()
                    ==
                    ranges[
                        "start_row"
                    ]
                    .iloc[1:]
                    .to_numpy()
                ).all()
            )


        valid = bool(

            len(ranges)
            ==
            expected_range_count

            and
            row_sum_ok

            and
            length_ok

            and
            starts_zero

            and
            ends_correct

            and
            contiguous
        )


        range_records.append({

            "fold_id":
                fold_id,

            "held_out_family":
                held_out_family,

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "expected_rows":
                int(expected_rows),

            "manifest_rows":
                int(
                    ranges[
                        "row_count"
                    ].sum()
                ),

            "range_count":
                len(ranges),

            "expected_range_count":
                expected_range_count,

            "ranges_contiguous":
                contiguous,

            "range_lengths_correct":
                length_ok,

            "valid":
                valid
        })


LOAFO_RANGE_CHECKS = pd.DataFrame(
    range_records
)


INVALID_RANGE_CHECKS = int(
    (
        ~LOAFO_RANGE_CHECKS[
            "valid"
        ]
    ).sum()
)


print(
    "Range checks:",
    len(LOAFO_RANGE_CHECKS)
)

print(
    "Invalid checks:",
    INVALID_RANGE_CHECKS
)


# ======================================================================
# 5 — REBUILD FOLD SUMMARIES
# ======================================================================

print("\n[5] Rebuilding fold summaries")
print("-" * 78)

summary_records = []


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold = (
        LOAFO_SPLIT_MANIFEST[
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == fold_id
        ]
    )


    def partition_rows(name):

        return int(
            fold.loc[
                fold[
                    "partition"
                ] == name,
                "row_count"
            ].sum()
        )


    train_rows = partition_rows(
        "development_train"
    )

    validation_rows = partition_rows(
        "development_validation"
    )

    known_attack_rows = partition_rows(
        "known_test"
    )

    benign_rows = partition_rows(
        "benign_test"
    )

    zero_day_rows = partition_rows(
        "zero_day_attack_test"
    )


    summary_records.append({

        "fold_id":
            fold_id,

        "held_out_family":
            held_out_family,

        "development_train_rows":
            train_rows,

        "development_validation_rows":
            validation_rows,

        "known_test_attack_rows":
            known_attack_rows,

        "benign_test_rows":
            benign_rows,

        "zero_day_attack_rows":
            zero_day_rows,

        "known_evaluation_rows":
            known_attack_rows
            +
            benign_rows,

        "zero_day_evaluation_rows":
            zero_day_rows
            +
            benign_rows,

        "conserved_dataset_rows":
            train_rows
            +
            validation_rows
            +
            known_attack_rows
            +
            benign_rows
            +
            zero_day_rows
    })


LOAFO_FOLD_SUMMARY = pd.DataFrame(
    summary_records
)

display(
    LOAFO_FOLD_SUMMARY
)


# ======================================================================
# 6 — ORIGINAL VERIFIED FOLD TOTALS
# ======================================================================

EXPECTED_FOLD_TOTALS = {

    "DDoS": [
        6_253_058,
        1_339_934,
        1_326_235,
        13_727,
        30_918_665
    ],

    "DoS": [
        22_621_800,
        4_847_517,
        4_833_834,
        13_727,
        7_534_741
    ],

    "Mirai": [
        27_880_011,
        5_974_276,
        5_960_594,
        13_727,
        23_011
    ],

    "Recon": [
        27_120_670,
        5_811_561,
        5_797_875,
        13_727,
        1_107_786
    ],

    "Spoofing": [
        27_792_664,
        5_955_560,
        5_941_877,
        13_727,
        147_791
    ],

    "Web": [
        27_882_377,
        5_974_785,
        5_961_099,
        13_727,
        19_631
    ],

    "BruteForce": [
        27_890_176,
        5_976_454,
        5_962_774,
        13_727,
        8_488
    ]
}


columns_to_compare = [

    "development_train_rows",

    "development_validation_rows",

    "known_test_attack_rows",

    "benign_test_rows",

    "zero_day_attack_rows"
]


historical_match = True


print("\n[6] Comparing exact original fold totals")
print("-" * 78)


for _, row in LOAFO_FOLD_SUMMARY.iterrows():

    family = row[
        "held_out_family"
    ]

    actual = [
        int(
            row[column]
        )
        for column
        in columns_to_compare
    ]

    expected = EXPECTED_FOLD_TOTALS[
        family
    ]

    matches = (
        actual
        ==
        expected
    )


    print(
        f"Fold {int(row['fold_id'])} "
        f"{family:<10}: "
        f"{'MATCH' if matches else 'MISMATCH'}"
    )


    historical_match &= matches


# ======================================================================
# 7 — HELD-OUT LEAKAGE CHECKS
# ======================================================================

print("\n[7] Rechecking strict held-out isolation")
print("-" * 78)

integrity_records = []


permission_columns = [
    "allowed_preprocessing_fit",
    "allowed_ssl_pretraining",
    "allowed_supervised_training",
    "allowed_validation_tuning",
    "allowed_threshold_selection"
]


for fold_id, held_out_family in enumerate(
    LOAFO_FAMILIES,
    start=1
):

    fold = (
        LOAFO_SPLIT_MANIFEST[
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == fold_id
        ]
    )


    held_out = (
        fold[
            fold[
                "research_family"
            ] == held_out_family
        ]
    )


    outside_zero_day = int(
        held_out.loc[
            held_out[
                "partition"
            ]
            !=
            "zero_day_attack_test",
            "row_count"
        ].sum()
    )


    permission_violations = int(
        held_out[
            permission_columns
        ]
        .astype(int)
        .to_numpy()
        .sum()
    )


    expected_zero_day = int(
        sum(
            rows
            for source_class, rows
            in SOURCE_CLASS_TO_ROW_COUNT.items()
            if SOURCE_CLASS_TO_FAMILY[
                source_class
            ] == held_out_family
        )
    )


    actual_zero_day = int(
        held_out[
            "row_count"
        ].sum()
    )


    rows_conserved = bool(
        int(
            fold[
                "row_count"
            ].sum()
        )
        ==
        TOTAL_ROWS
    )


    range_integrity = bool(
        LOAFO_RANGE_CHECKS.loc[
            LOAFO_RANGE_CHECKS[
                "fold_id"
            ] == fold_id,
            "valid"
        ].all()
    )


    no_leakage = bool(
        outside_zero_day == 0
        and
        permission_violations == 0
    )


    zero_day_complete = bool(
        actual_zero_day
        ==
        expected_zero_day
    )


    fold_valid = bool(
        rows_conserved
        and
        range_integrity
        and
        no_leakage
        and
        zero_day_complete
    )


    integrity_records.append({

        "fold_id":
            fold_id,

        "held_out_family":
            held_out_family,

        "held_out_rows_outside_zero_day":
            outside_zero_day,

        "held_out_permission_violations":
            permission_violations,

        "expected_zero_day_rows":
            expected_zero_day,

        "actual_zero_day_rows":
            actual_zero_day,

        "rows_conserved":
            rows_conserved,

        "range_integrity":
            range_integrity,

        "no_held_out_leakage":
            no_leakage,

        "zero_day_complete":
            zero_day_complete,

        "fold_valid":
            fold_valid
    })


LOAFO_INTEGRITY_CHECKS = pd.DataFrame(
    integrity_records
)


display(
    LOAFO_INTEGRITY_CHECKS
)


# ======================================================================
# 8 — SAVE CORRECTED ARTIFACTS
# ======================================================================

print("\n[8] Saving corrected LOAFO artifacts")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

LOCAL_LOAFO_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "loafo_manifests"
)

LOCAL_AUDIT_DIR = (
    PROJECT_ROOT
    / "dataset_audit"
)

LOCAL_LOAFO_DIR.mkdir(
    parents=True,
    exist_ok=True
)

LOCAL_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOAFO_MANIFEST_PATH = (
    LOCAL_LOAFO_DIR
    / "CICIoT2023_LOAFO_split_manifest.csv"
)

LOAFO_FOLD_SUMMARY_PATH = (
    LOCAL_LOAFO_DIR
    / "CICIoT2023_LOAFO_fold_summary.csv"
)

LOAFO_RANGE_CHECKS_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_LOAFO_range_integrity.csv"
)

LOAFO_INTEGRITY_CHECKS_PATH = (
    LOCAL_AUDIT_DIR
    / "CICIoT2023_LOAFO_integrity_checks.csv"
)


LOAFO_SPLIT_MANIFEST.to_csv(
    LOAFO_MANIFEST_PATH,
    index=False
)

LOAFO_FOLD_SUMMARY.to_csv(
    LOAFO_FOLD_SUMMARY_PATH,
    index=False
)

LOAFO_RANGE_CHECKS.to_csv(
    LOAFO_RANGE_CHECKS_PATH,
    index=False
)

LOAFO_INTEGRITY_CHECKS.to_csv(
    LOAFO_INTEGRITY_CHECKS_PATH,
    index=False
)


# ======================================================================
# 9 — OVERWRITE DRIVE ARTIFACTS WITH CORRECTED VERSION
# ======================================================================

DRIVE_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

DRIVE_LOAFO_DIR = (
    DRIVE_ROOT
    / "processed_data"
    / "loafo_manifests"
)

DRIVE_AUDIT_DIR = (
    DRIVE_ROOT
    / "dataset_audit"
)

DRIVE_LOAFO_DIR.mkdir(
    parents=True,
    exist_ok=True
)

DRIVE_AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


shutil.copy2(
    LOAFO_MANIFEST_PATH,
    DRIVE_LOAFO_DIR
    / LOAFO_MANIFEST_PATH.name
)

shutil.copy2(
    LOAFO_FOLD_SUMMARY_PATH,
    DRIVE_LOAFO_DIR
    / LOAFO_FOLD_SUMMARY_PATH.name
)

shutil.copy2(
    LOAFO_RANGE_CHECKS_PATH,
    DRIVE_AUDIT_DIR
    / LOAFO_RANGE_CHECKS_PATH.name
)

shutil.copy2(
    LOAFO_INTEGRITY_CHECKS_PATH,
    DRIVE_AUDIT_DIR
    / LOAFO_INTEGRITY_CHECKS_PATH.name
)


# ======================================================================
# 10 — FINAL VALIDATION
# ======================================================================

A4_VALID = bool(

    len(
        LOAFO_SPLIT_MANIFEST
    ) == 629

    and

    len(
        LOAFO_RANGE_CHECKS
    ) == 231

    and

    INVALID_RANGE_CHECKS == 0

    and

    bool(
        LOAFO_RANGE_CHECKS[
            "valid"
        ].all()
    )

    and

    bool(
        LOAFO_INTEGRITY_CHECKS[
            "fold_valid"
        ].all()
    )

    and

    historical_match
)


STEP_8_5_VALID = A4_VALID


print("\n[9] Recovery Step A4-FIX validation")
print("-" * 78)

print(
    "Manifest records            :",
    len(LOAFO_SPLIT_MANIFEST),
    "/ 629"
)

print(
    "Range checks                :",
    len(LOAFO_RANGE_CHECKS),
    "/ 231"
)

print(
    "Invalid ranges              :",
    INVALID_RANGE_CHECKS
)

print(
    "All folds leakage-safe      :",
    bool(
        LOAFO_INTEGRITY_CHECKS[
            "no_held_out_leakage"
        ].all()
    )
)

print(
    "All rows conserved          :",
    bool(
        LOAFO_INTEGRITY_CHECKS[
            "rows_conserved"
        ].all()
    )
)

print(
    "All zero-day sets complete  :",
    bool(
        LOAFO_INTEGRITY_CHECKS[
            "zero_day_complete"
        ].all()
    )
)

print(
    "Original fold totals matched:",
    historical_match
)

print(
    "Corrected artifacts in Drive:",
    (
        (
            DRIVE_LOAFO_DIR
            /
            LOAFO_MANIFEST_PATH.name
        ).exists()
        and
        (
            DRIVE_LOAFO_DIR
            /
            LOAFO_FOLD_SUMMARY_PATH.name
        ).exists()
    )
)


print("\n" + "=" * 78)

if A4_VALID:

    print(
        "✅ RECOVERY STEP A4-FIX PASSED — "
        "The exact original strict LOAFO manifests "
        "have been restored."
    )

else:

    print(
        "❌ RECOVERY STEP A4-FIX FAILED — "
        "Do not continue yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A4-FIX — RESTORE ORIGINAL LOAFO SPLITS
==============================================================================

[1] Checking current A4 state
------------------------------------------------------------------------------
Source classes : 33
LOAFO families : 7
Dataset rows   : 39,851,619

[2] Confirming original split arithmetic
------------------------------------------------------------------------------
Recon-PortScan rows              : 175,050
Integer-floor reconstruction     : 122,535
Original float-truncation result : 122,534
Difference                      : 1

[3] Rebuilding exact original LOAFO manifest
------------------------------------------------------------------------------
Manifest records: 629

[4] Rechecking source ranges
------------------------------------------------------------------------------
Range checks: 231
Invalid checks: 0

[5] Rebuilding fold summaries
------------------------------------------------------------------------------

,fold_id,held_out_family,development_train_rows,development_validation_rows,known_test_attack_rows,benign_test_rows,zero_day_attack_rows,known_evaluation_rows,zero_day_evaluation_rows,conserved_dataset_rows
0,1,DDoS,6253058,1339934,1326235,13727,30918665,1339962,30932392,39851619
1,2,DoS,22621800,4847517,4833834,13727,7534741,4847561,7548468,39851619
2,3,Mirai,27880011,5974276,5960594,13727,23011,5974321,36738,39851619
3,4,Recon,27120670,5811561,5797875,13727,1107786,5811602,1121513,39851619
4,5,Spoofing,27792664,5955560,5941877,13727,147791,5955604,161518,39851619
5,6,Web,27882377,5974785,5961099,13727,19631,5974826,33358,39851619
6,7,BruteForce,27890176,5976454,5962774,13727,8488,5976501,22215,39851619

[6] Comparing exact original fold totals
------------------------------------------------------------------------------
Fold 1 DDoS      : MATCH
Fold 2 DoS       : MATCH
Fold 3 Mirai     : MATCH
Fold 4 Recon     : MATCH
Fold 5 Spoofing  : MATCH
Fold 6 Web       : MATCH
Fold 7 BruteForce: MATCH

[7] Rechecking strict held-out isolation
------------------------------------------------------------------------------

,fold_id,held_out_family,held_out_rows_outside_zero_day,held_out_permission_violations,expected_zero_day_rows,actual_zero_day_rows,rows_conserved,range_integrity,no_held_out_leakage,zero_day_complete,fold_valid
0,1,DDoS,0,0,30918665,30918665,True,True,True,True,True
1,2,DoS,0,0,7534741,7534741,True,True,True,True,True
2,3,Mirai,0,0,23011,23011,True,True,True,True,True
3,4,Recon,0,0,1107786,1107786,True,True,True,True,True
4,5,Spoofing,0,0,147791,147791,True,True,True,True,True
5,6,Web,0,0,19631,19631,True,True,True,True,True
6,7,BruteForce,0,0,8488,8488,True,True,True,True,True

[8] Saving corrected LOAFO artifacts
------------------------------------------------------------------------------

[9] Recovery Step A4-FIX validation
------------------------------------------------------------------------------
Manifest records            : 629 / 629
Range checks                : 231 / 231
Invalid ranges              : 0
All folds leakage-safe      : True
All rows conserved          : True
All zero-day sets complete  : True
Original fold totals matched: True
Corrected artifacts in Drive: True

==============================================================================
✅ RECOVERY STEP A4-FIX PASSED — The exact original strict LOAFO manifests have been restored.
==============================================================================

# Do only this now — Recovery Step A5

In [ ]:
# ======================================================================
# RECOVERY STEP A5 — CHECK FOR EXISTING FOLD-1 PREPROCESSING ARTIFACTS
# ======================================================================

from pathlib import Path

print("=" * 78)
print("RECOVERY STEP A5 — CHECK FOLD-1 PREPROCESSING BACKUP")
print("=" * 78)


DRIVE_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

FOLD1_DRIVE_DIR = (
    DRIVE_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


expected_files = [
    "preprocessing_parameters.csv",
    "retained_features.json",
    "preprocessing_policy.json",
    "preprocessing_verification.csv",
    "preprocessing_verification_summary.json",
    "nontraining_preprocessing_application_audit.csv",
    "nontraining_preprocessing_application_summary.json"
]


print("\nFold-1 preprocessing folder:")
print(FOLD1_DRIVE_DIR)

print("\nFolder exists:", FOLD1_DRIVE_DIR.exists())

print("\nExpected artifacts:")
print("-" * 78)


found_count = 0

for file_name in expected_files:

    file_path = (
        FOLD1_DRIVE_DIR
        / file_name
    )

    exists = file_path.exists()

    if exists:
        found_count += 1

    print(
        f"{file_name:<55} : {exists}"
    )


print("\n" + "-" * 78)

print(
    "Artifacts found:",
    found_count,
    "/",
    len(expected_files)
)


print("\n" + "=" * 78)

if found_count == len(expected_files):

    print(
        "✅ RECOVERY STEP A5 — COMPLETE FOLD-1 BACKUP FOUND"
    )

elif found_count == 0:

    print(
        "ℹ️ RECOVERY STEP A5 — NO OLD FOLD-1 PREPROCESSING BACKUP FOUND"
    )

    print(
        "We will safely rebuild Fold-1 preprocessing next."
    )

else:

    print(
        "⚠️ RECOVERY STEP A5 — PARTIAL BACKUP FOUND"
    )

    print(
        "Do not use it yet; we will validate the available files first."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A5 — CHECK FOLD-1 PREPROCESSING BACKUP
==============================================================================

Fold-1 preprocessing folder:
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/preprocessing/fold_01_DDoS

Folder exists: False

Expected artifacts:
------------------------------------------------------------------------------
preprocessing_parameters.csv                            : False
retained_features.json                                  : False
preprocessing_policy.json                               : False
preprocessing_verification.csv                          : False
preprocessing_verification_summary.json                 : False
nontraining_preprocessing_application_audit.csv         : False
nontraining_preprocessing_application_summary.json      : False

------------------------------------------------------------------------------
Artifacts found: 0 / 7

==============================================================================
ℹ️ RECOVERY STEP A5 — NO OLD FOLD-1 PREPROCESSING BACKUP FOUND
We will safely rebuild Fold-1 preprocessing next.
==============================================================================

# Recovery Step A6 — Rebuild Fold-1 training-only preprocessing

In [ ]:
# ======================================================================
# RECOVERY STEP A6
# REBUILD FOLD-1 TRAINING-ONLY PREPROCESSING
# HELD-OUT FAMILY: DDoS
# ======================================================================

from pathlib import Path
import json
import shutil
import warnings

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP A6 — REBUILD FOLD-1 PREPROCESSING")
print("HELD-OUT ZERO-DAY FAMILY: DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY RECOVERED LOAFO STATE
# ======================================================================

print("\n[1] Verifying recovered LOAFO state")
print("-" * 78)

required_variables = [
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY",
    "SOURCE_CLASS_TO_FAMILY",
    "SORTED_FILE_BY_SOURCE_CLASS",
    "STEP_8_5_VALID"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun A4-FIX."
    )

if not STEP_8_5_VALID:
    raise RuntimeError(
        "Recovered LOAFO manifests did not pass validation."
    )

FOLD_ID = 1
HELD_OUT_FAMILY = "DDoS"

print(
    "Fold:",
    FOLD_ID
)

print(
    "Held-out family:",
    HELD_OUT_FAMILY
)

print(
    "LOAFO state valid:",
    STEP_8_5_VALID
)


# ======================================================================
# 2 — REBUILD THE 79 NUMERIC CANDIDATE FEATURES
# ======================================================================

print("\n[2] Rebuilding common feature schema")
print("-" * 78)

schema_sets = []
first_schema = None

for source_class, parquet_path in (
    SORTED_FILE_BY_SOURCE_CLASS.items()
):

    schema_names = list(
        pq.ParquetFile(
            parquet_path
        ).schema_arrow.names
    )

    if first_schema is None:
        first_schema = schema_names

    schema_sets.append(
        set(schema_names)
    )


common_columns_set = set.intersection(
    *schema_sets
)

COMMON_COLUMNS = [
    column
    for column in first_schema
    if column in common_columns_set
]


EXCLUDED_COLUMNS = [
    "Timestamp",
    "Label",
    "Flow ID",
    "Src IP",
    "Dst IP"
]


NUMERIC_FEATURE_CANDIDATES = [
    column
    for column in COMMON_COLUMNS
    if column not in EXCLUDED_COLUMNS
]


print(
    "Common columns:",
    len(COMMON_COLUMNS)
)

print(
    "Excluded columns:",
    EXCLUDED_COLUMNS
)

print(
    "Numeric candidates:",
    len(NUMERIC_FEATURE_CANDIDATES)
)


if len(COMMON_COLUMNS) != 84:
    raise RuntimeError(
        f"Expected 84 common columns, found {len(COMMON_COLUMNS)}."
    )

if len(NUMERIC_FEATURE_CANDIDATES) != 79:
    raise RuntimeError(
        f"Expected 79 numeric features, "
        f"found {len(NUMERIC_FEATURE_CANDIDATES)}."
    )


# ======================================================================
# 3 — SELECT FOLD-1 DEVELOPMENT TRAIN ONLY
# ======================================================================

print("\n[3] Selecting Fold-1 development training ranges")
print("-" * 78)

train_manifest = (
    LOAFO_SPLIT_MANIFEST[
        (LOAFO_SPLIT_MANIFEST["fold_id"] == FOLD_ID)
        &
        (
            LOAFO_SPLIT_MANIFEST["partition"]
            ==
            "development_train"
        )
    ]
    .copy()
    .reset_index(drop=True)
)


expected_train_rows = int(
    LOAFO_FOLD_SUMMARY.loc[
        LOAFO_FOLD_SUMMARY["fold_id"] == FOLD_ID,
        "development_train_rows"
    ].iloc[0]
)


held_out_train_rows = int(
    train_manifest.loc[
        train_manifest["research_family"]
        ==
        HELD_OUT_FAMILY,
        "row_count"
    ].sum()
)


print(
    "Training source ranges:",
    len(train_manifest)
)

print(
    "Expected training rows:",
    f"{expected_train_rows:,}"
)

print(
    "DDoS rows in training:",
    held_out_train_rows
)


if expected_train_rows != 6_253_058:
    raise RuntimeError(
        "Fold-1 expected training-row total "
        "does not match the original verified split."
    )

if held_out_train_rows != 0:
    raise RuntimeError(
        "DDoS leakage detected in Fold-1 training."
    )


print("\nTraining rows by source class:")

for _, row in train_manifest.iterrows():

    print(
        f"  {row['source_attack_class']:<30}"
        f"{int(row['row_count']):>12,}"
    )


# ======================================================================
# 4 — PREPARE OUTPUT DIRECTORIES
# ======================================================================

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

FOLD_PREPROCESSING_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

FOLD_PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

DRIVE_FOLD_PREPROCESSING_DIR = (
    DRIVE_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

DRIVE_FOLD_PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREPROCESSING_PARAMETERS_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

RETAINED_FEATURES_PATH = (
    FOLD_PREPROCESSING_DIR
    / "retained_features.json"
)

PREPROCESSING_POLICY_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_policy.json"
)


# ======================================================================
# 5 — INITIALIZE ONLINE SUFFICIENT STATISTICS
# ======================================================================

print("\n[4] Initializing training-only statistics")
print("-" * 78)

n_features = len(
    NUMERIC_FEATURE_CANDIDATES
)

finite_count = np.zeros(
    n_features,
    dtype=np.int64
)

running_mean = np.zeros(
    n_features,
    dtype=np.float64
)

running_M2 = np.zeros(
    n_features,
    dtype=np.float64
)

missing_count = np.zeros(
    n_features,
    dtype=np.int64
)

positive_infinity_count = np.zeros(
    n_features,
    dtype=np.int64
)

negative_infinity_count = np.zeros(
    n_features,
    dtype=np.int64
)

finite_min = np.full(
    n_features,
    np.inf,
    dtype=np.float64
)

finite_max = np.full(
    n_features,
    -np.inf,
    dtype=np.float64
)


# ======================================================================
# 6 — STREAM EXACT TRAINING RANGES
# ======================================================================

print("\n[5] Fitting preprocessing on development_train only")
print("-" * 78)

BATCH_SIZE = 50_000

scanned_train_rows = 0


for source_number, row in train_manifest.iterrows():

    source_class = row[
        "source_attack_class"
    ]

    research_family = row[
        "research_family"
    ]

    start_row = int(
        row["start_row"]
    )

    end_row = int(
        row["end_row_exclusive"]
    )

    expected_source_rows = int(
        row["row_count"]
    )

    parquet_path = Path(
        row["parquet_path"]
    )


    if research_family == HELD_OUT_FAMILY:

        raise RuntimeError(
            f"Leakage detected: {source_class} "
            f"belongs to {HELD_OUT_FAMILY}."
        )


    print(
        f"\n{source_number + 1:02d}/{len(train_manifest):02d} "
        f"{source_class}"
    )

    print(
        "Rows:",
        f"{expected_source_rows:,}"
    )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    source_rows_read = 0
    absolute_position = 0


    for batch in parquet_file.iter_batches(
        columns=NUMERIC_FEATURE_CANDIDATES,
        batch_size=BATCH_SIZE
    ):

        batch_rows = batch.num_rows

        batch_start = absolute_position
        batch_end = (
            absolute_position
            +
            batch_rows
        )

        absolute_position = batch_end


        # Batch lies completely before desired range
        if batch_end <= start_row:
            continue


        # Desired range is already finished
        if batch_start >= end_row:
            break


        local_start = max(
            0,
            start_row - batch_start
        )

        local_end = min(
            batch_rows,
            end_row - batch_start
        )


        if local_end <= local_start:
            continue


        sliced_batch = batch.slice(
            local_start,
            local_end - local_start
        )


        batch_df = (
            sliced_batch
            .to_pandas()
        )


        X = batch_df.to_numpy(
            dtype=np.float64,
            copy=True
        )


        current_rows = X.shape[0]


        # --------------------------------------------------------------
        # Non-finite audit
        # --------------------------------------------------------------

        missing_mask = np.isnan(X)

        positive_inf_mask = np.isposinf(X)

        negative_inf_mask = np.isneginf(X)

        finite_mask = np.isfinite(X)


        missing_count += (
            missing_mask
            .sum(axis=0)
            .astype(np.int64)
        )

        positive_infinity_count += (
            positive_inf_mask
            .sum(axis=0)
            .astype(np.int64)
        )

        negative_infinity_count += (
            negative_inf_mask
            .sum(axis=0)
            .astype(np.int64)
        )


        # --------------------------------------------------------------
        # Batch statistics over finite values only
        # --------------------------------------------------------------

        batch_finite_count = (
            finite_mask
            .sum(axis=0)
            .astype(np.int64)
        )


        safe_X = np.where(
            finite_mask,
            X,
            0.0
        )


        batch_sum = safe_X.sum(
            axis=0,
            dtype=np.float64
        )


        batch_mean = np.zeros(
            n_features,
            dtype=np.float64
        )


        has_finite = (
            batch_finite_count > 0
        )


        batch_mean[
            has_finite
        ] = (
            batch_sum[
                has_finite
            ]
            /
            batch_finite_count[
                has_finite
            ]
        )


        centered = (
            safe_X
            -
            batch_mean
        )


        centered[
            ~finite_mask
        ] = 0.0


        batch_M2 = (
            centered
            *
            centered
        ).sum(
            axis=0,
            dtype=np.float64
        )


        batch_min = np.min(
            np.where(
                finite_mask,
                X,
                np.inf
            ),
            axis=0
        )


        batch_max = np.max(
            np.where(
                finite_mask,
                X,
                -np.inf
            ),
            axis=0
        )


        # --------------------------------------------------------------
        # Merge batch Welford statistics into global training stats
        # --------------------------------------------------------------

        active = (
            batch_finite_count > 0
        )


        old_count = finite_count.copy()

        new_count = (
            old_count
            +
            batch_finite_count
        )


        delta = (
            batch_mean
            -
            running_mean
        )


        merge_mask = active


        running_mean[
            merge_mask
        ] = (
            running_mean[
                merge_mask
            ]
            +
            delta[
                merge_mask
            ]
            *
            batch_finite_count[
                merge_mask
            ]
            /
            new_count[
                merge_mask
            ]
        )


        running_M2[
            merge_mask
        ] = (
            running_M2[
                merge_mask
            ]
            +
            batch_M2[
                merge_mask
            ]
            +
            (
                delta[
                    merge_mask
                ]
                ** 2
            )
            *
            old_count[
                merge_mask
            ]
            *
            batch_finite_count[
                merge_mask
            ]
            /
            new_count[
                merge_mask
            ]
        )


        finite_count = new_count


        finite_min = np.minimum(
            finite_min,
            batch_min
        )


        finite_max = np.maximum(
            finite_max,
            batch_max
        )


        source_rows_read += (
            current_rows
        )

        scanned_train_rows += (
            current_rows
        )


    print(
        "Scanned:",
        f"{source_rows_read:,}"
    )


    if source_rows_read != expected_source_rows:

        raise RuntimeError(
            f"Range scan mismatch for {source_class}: "
            f"expected {expected_source_rows:,}, "
            f"scanned {source_rows_read:,}."
        )


# ======================================================================
# 7 — VERIFY EXACT TRAINING ROW TOTAL
# ======================================================================

print("\n[6] Training-row validation")
print("-" * 78)

print(
    "Expected rows:",
    f"{expected_train_rows:,}"
)

print(
    "Scanned rows :",
    f"{scanned_train_rows:,}"
)

TRAIN_ROW_COUNT_EXACT = (
    scanned_train_rows
    ==
    expected_train_rows
)

print(
    "Exact match  :",
    TRAIN_ROW_COUNT_EXACT
)


if not TRAIN_ROW_COUNT_EXACT:
    raise RuntimeError(
        "Fold-1 training row count mismatch."
    )


# ======================================================================
# 8 — DERIVE IMPUTATION + STANDARDIZATION PARAMETERS
# ======================================================================

print("\n[7] Deriving training-only preprocessing parameters")
print("-" * 78)


nonfinite_count = (
    missing_count
    +
    positive_infinity_count
    +
    negative_infinity_count
)


if np.any(
    finite_count
    +
    nonfinite_count
    !=
    expected_train_rows
):

    raise RuntimeError(
        "Finite/non-finite accounting does not equal "
        "the training row total for every feature."
    )


if np.any(
    finite_count == 0
):

    bad_features = [
        NUMERIC_FEATURE_CANDIDATES[index]
        for index
        in np.where(
            finite_count == 0
        )[0]
    ]

    raise RuntimeError(
        "Features with no finite training values: "
        + str(bad_features)
    )


# Mean imputation fitted on finite development-training values
imputation_values = (
    running_mean.copy()
)


# Because every non-finite value is imputed to the training finite mean,
# those imputed observations contribute zero squared deviation.
scaler_means = (
    running_mean.copy()
)


post_imputation_variance = (
    running_M2
    /
    float(
        expected_train_rows
    )
)


post_imputation_variance = np.maximum(
    post_imputation_variance,
    0.0
)


scaler_stds = np.sqrt(
    post_imputation_variance
)


ZERO_VARIANCE_TOLERANCE = 1e-12


zero_variance_mask = (
    scaler_stds
    <=
    ZERO_VARIANCE_TOLERANCE
)


retained_mask = (
    ~zero_variance_mask
)


ZERO_VARIANCE_FEATURES_FOLD_1 = [
    NUMERIC_FEATURE_CANDIDATES[index]
    for index
    in np.where(
        zero_variance_mask
    )[0]
]


RETAINED_FEATURES_FOLD_1 = [
    NUMERIC_FEATURE_CANDIDATES[index]
    for index
    in np.where(
        retained_mask
    )[0]
]


FEATURES_WITH_NONFINITE_FOLD_1 = [
    NUMERIC_FEATURE_CANDIDATES[index]
    for index
    in np.where(
        nonfinite_count > 0
    )[0]
]


print(
    "Input numeric candidates:",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "Zero-variance features  :",
    len(ZERO_VARIANCE_FEATURES_FOLD_1)
)

print(
    "Retained features       :",
    len(RETAINED_FEATURES_FOLD_1)
)

print(
    "Features with non-finite:",
    len(FEATURES_WITH_NONFINITE_FOLD_1)
)


# ======================================================================
# 9 — NON-FINITE FEATURE REPORT
# ======================================================================

print("\n[8] Training non-finite-value report")
print("-" * 78)


for feature in FEATURES_WITH_NONFINITE_FOLD_1:

    index = NUMERIC_FEATURE_CANDIDATES.index(
        feature
    )

    print(
        f"\nFeature: {feature}"
    )

    print(
        "  Missing        :",
        f"{missing_count[index]:,}"
    )

    print(
        "  +Infinity      :",
        f"{positive_infinity_count[index]:,}"
    )

    print(
        "  -Infinity      :",
        f"{negative_infinity_count[index]:,}"
    )

    print(
        "  Total nonfinite:",
        f"{nonfinite_count[index]:,}"
    )

    print(
        "  Percent        :",
        f"{100.0 * nonfinite_count[index] / expected_train_rows:.6f}%"
    )

    print(
        "  Imputation mean:",
        f"{imputation_values[index]:.6f}"
    )


# ======================================================================
# 10 — ZERO-VARIANCE REPORT
# ======================================================================

print("\n[9] Fold-1 zero-variance features")
print("-" * 78)

for feature in ZERO_VARIANCE_FEATURES_FOLD_1:
    print(
        " -",
        feature
    )


# ======================================================================
# 11 — BUILD PARAMETER TABLE
# ======================================================================

PREPROCESSING_PARAMETERS = pd.DataFrame({

    "feature":
        NUMERIC_FEATURE_CANDIDATES,

    "finite_count":
        finite_count,

    "missing_count":
        missing_count,

    "positive_infinity_count":
        positive_infinity_count,

    "negative_infinity_count":
        negative_infinity_count,

    "nonfinite_count":
        nonfinite_count,

    "nonfinite_percent":
        (
            100.0
            *
            nonfinite_count
            /
            expected_train_rows
        ),

    "finite_min":
        finite_min,

    "finite_max":
        finite_max,

    "imputation_value":
        imputation_values,

    "scaler_mean":
        scaler_means,

    "scaler_std":
        scaler_stds,

    "zero_variance":
        zero_variance_mask,

    "retained_feature":
        retained_mask
})


# ======================================================================
# 12 — REPRODUCIBILITY CHECK AGAINST PREVIOUS VERIFIED STEP 9.1
# ======================================================================

print("\n[10] Reproducibility checks")
print("-" * 78)


EXPECTED_ZERO_VARIANCE = {
    "Bwd URG Flags",
    "Fwd Bytes/Bulk Avg",
    "Fwd Packet/Bulk Avg",
    "Fwd Bulk Rate Avg"
}


ZERO_VARIANCE_MATCH = (
    set(
        ZERO_VARIANCE_FEATURES_FOLD_1
    )
    ==
    EXPECTED_ZERO_VARIANCE
)


EXPECTED_NONFINITE = {
    "Flow Bytes/s",
    "Flow Packets/s"
}


NONFINITE_FEATURES_MATCH = (
    set(
        FEATURES_WITH_NONFINITE_FOLD_1
    )
    ==
    EXPECTED_NONFINITE
)


def feature_index(name):

    return NUMERIC_FEATURE_CANDIDATES.index(
        name
    )


flow_bytes_index = feature_index(
    "Flow Bytes/s"
)

flow_packets_index = feature_index(
    "Flow Packets/s"
)


NONFINITE_COUNTS_MATCH = bool(

    missing_count[
        flow_bytes_index
    ] == 28_608

    and

    positive_infinity_count[
        flow_bytes_index
    ] == 809

    and

    negative_infinity_count[
        flow_bytes_index
    ] == 0

    and

    nonfinite_count[
        flow_bytes_index
    ] == 29_417

    and

    missing_count[
        flow_packets_index
    ] == 0

    and

    positive_infinity_count[
        flow_packets_index
    ] == 29_417

    and

    negative_infinity_count[
        flow_packets_index
    ] == 0

    and

    nonfinite_count[
        flow_packets_index
    ] == 29_417
)


print(
    "Original zero-variance list matched:",
    ZERO_VARIANCE_MATCH
)

print(
    "Original non-finite feature list matched:",
    NONFINITE_FEATURES_MATCH
)

print(
    "Original non-finite counts matched:",
    NONFINITE_COUNTS_MATCH
)


# ======================================================================
# 13 — LEAKAGE-SAFETY SUMMARY
# ======================================================================

print("\n[11] Leakage-safety summary")
print("-" * 78)


validation_rows_used = 0
known_test_rows_used = 0
benign_test_rows_used = 0
zero_day_rows_used = 0


print(
    "Development-train rows used :",
    f"{scanned_train_rows:,}"
)

print(
    "Validation rows used        :",
    validation_rows_used
)

print(
    "Known-test rows used        :",
    known_test_rows_used
)

print(
    "Benign-test rows used       :",
    benign_test_rows_used
)

print(
    "Zero-day DDoS rows used     :",
    zero_day_rows_used
)

print(
    "Held-out family used in fit :",
    False
)


# ======================================================================
# 14 — SAVE ARTIFACTS LOCALLY
# ======================================================================

print("\n[12] Saving Fold-1 preprocessing artifacts")
print("-" * 78)


PREPROCESSING_PARAMETERS.to_csv(
    PREPROCESSING_PARAMETERS_PATH,
    index=False
)


with open(
    RETAINED_FEATURES_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        RETAINED_FEATURES_FOLD_1,
        file,
        indent=4
    )


PREPROCESSING_POLICY = {

    "fold_id":
        FOLD_ID,

    "held_out_family":
        HELD_OUT_FAMILY,

    "input_numeric_feature_count":
        len(
            NUMERIC_FEATURE_CANDIDATES
        ),

    "retained_feature_count":
        len(
            RETAINED_FEATURES_FOLD_1
        ),

    "zero_variance_feature_count":
        len(
            ZERO_VARIANCE_FEATURES_FOLD_1
        ),

    "training_rows":
        int(
            expected_train_rows
        ),

    "imputation_policy":
        (
            "Replace NaN, +inf and -inf using the finite mean "
            "computed from Fold-1 development_train only."
        ),

    "standardization_policy":
        (
            "Population mean/std fitted from Fold-1 "
            "development_train only after mean imputation."
        ),

    "zero_variance_policy":
        (
            "Remove features whose training-only post-imputation "
            "standard deviation is <= 1e-12."
        ),

    "validation_used_for_fit":
        False,

    "known_test_used_for_fit":
        False,

    "benign_test_used_for_fit":
        False,

    "zero_day_used_for_fit":
        False,

    "timestamp_used_as_feature":
        False,

    "identifier_features_used":
        False
}


with open(
    PREPROCESSING_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        PREPROCESSING_POLICY,
        file,
        indent=4
    )


# ======================================================================
# 15 — COPY ARTIFACTS TO GOOGLE DRIVE IMMEDIATELY
# ======================================================================

print("\n[13] Backing up Fold-1 preprocessing to Google Drive")
print("-" * 78)


for source_path in [
    PREPROCESSING_PARAMETERS_PATH,
    RETAINED_FEATURES_PATH,
    PREPROCESSING_POLICY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_FOLD_PREPROCESSING_DIR
        / source_path.name
    )


DRIVE_OUTPUTS_EXIST = all(

    (
        DRIVE_FOLD_PREPROCESSING_DIR
        /
        source_path.name
    ).exists()

    for source_path in [
        PREPROCESSING_PARAMETERS_PATH,
        RETAINED_FEATURES_PATH,
        PREPROCESSING_POLICY_PATH
    ]
)


print(
    "Drive preprocessing folder:"
)

print(
    DRIVE_FOLD_PREPROCESSING_DIR
)

print(
    "Core artifacts backed up:",
    DRIVE_OUTPUTS_EXIST
)


# ======================================================================
# 16 — FINAL NUMERICAL VALIDATION
# ======================================================================

retained_parameter_rows = (
    PREPROCESSING_PARAMETERS[
        PREPROCESSING_PARAMETERS[
            "retained_feature"
        ]
    ]
)


RETAINED_PARAMS_FINITE = bool(

    np.isfinite(
        retained_parameter_rows[
            [
                "imputation_value",
                "scaler_mean",
                "scaler_std"
            ]
        ].to_numpy(
            dtype=np.float64
        )
    ).all()
)


RETAINED_STDS_POSITIVE = bool(

    (
        retained_parameter_rows[
            "scaler_std"
        ]
        >
        0
    ).all()
)


STEP_9_1_VALID = bool(

    TRAIN_ROW_COUNT_EXACT

    and

    held_out_train_rows == 0

    and

    len(
        NUMERIC_FEATURE_CANDIDATES
    ) == 79

    and

    len(
        ZERO_VARIANCE_FEATURES_FOLD_1
    ) == 4

    and

    len(
        RETAINED_FEATURES_FOLD_1
    ) == 75

    and

    ZERO_VARIANCE_MATCH

    and

    NONFINITE_FEATURES_MATCH

    and

    NONFINITE_COUNTS_MATCH

    and

    RETAINED_PARAMS_FINITE

    and

    RETAINED_STDS_POSITIVE

    and

    PREPROCESSING_PARAMETERS_PATH.exists()

    and

    RETAINED_FEATURES_PATH.exists()

    and

    PREPROCESSING_POLICY_PATH.exists()

    and

    DRIVE_OUTPUTS_EXIST
)


print("\n[14] Recovery Step A6 validation")
print("-" * 78)

print(
    "Training rows exact             :",
    TRAIN_ROW_COUNT_EXACT
)

print(
    "Held-out DDoS rows in fit       :",
    held_out_train_rows
)

print(
    "Numeric input features          :",
    len(NUMERIC_FEATURE_CANDIDATES)
)

print(
    "Zero-variance features          :",
    len(ZERO_VARIANCE_FEATURES_FOLD_1)
)

print(
    "Retained features               :",
    len(RETAINED_FEATURES_FOLD_1)
)

print(
    "Original zero-var list matched  :",
    ZERO_VARIANCE_MATCH
)

print(
    "Original nonfinite list matched :",
    NONFINITE_FEATURES_MATCH
)

print(
    "Original nonfinite counts match :",
    NONFINITE_COUNTS_MATCH
)

print(
    "Retained parameters finite      :",
    RETAINED_PARAMS_FINITE
)

print(
    "Retained stds positive          :",
    RETAINED_STDS_POSITIVE
)

print(
    "Artifacts backed up to Drive    :",
    DRIVE_OUTPUTS_EXIST
)


print("\n" + "=" * 78)

if STEP_9_1_VALID:

    print(
        "✅ RECOVERY STEP A6 PASSED — "
        "Fold-1 training-only preprocessing was rebuilt "
        "and permanently backed up."
    )

else:

    print(
        "❌ RECOVERY STEP A6 FAILED — "
        "Do not continue to preprocessing verification yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A6 — REBUILD FOLD-1 PREPROCESSING
HELD-OUT ZERO-DAY FAMILY: DDoS
==============================================================================

[1] Verifying recovered LOAFO state
------------------------------------------------------------------------------
Fold: 1
Held-out family: DDoS
LOAFO state valid: True

[2] Rebuilding common feature schema
------------------------------------------------------------------------------
Common columns: 84
Excluded columns: ['Timestamp', 'Label', 'Flow ID', 'Src IP', 'Dst IP']
Numeric candidates: 79

[3] Selecting Fold-1 development training ranges
------------------------------------------------------------------------------
Training source ranges: 21
Expected training rows: 6,253,058
DDoS rows in training: 0

Training rows by source class:
  Backdoor_Malware                     1,892
  Benign_Final                        64,054
  BrowserHijacking                     2,300
  CommandInjection                     2,693
  DNS_Spoofing                        52,456
  DictionaryBruteForce                 5,941
  DoS-HTTP_Flood                     675,887
  DoS-SYN_Flood                    2,797,977
  DoS-TCP_Flood                    1,146,647
  DoS-UDP_Flood                      653,806
  MITM-ArpSpoofing                    50,997
  Mirai-greeth_flood                   3,608
  Mirai-greip_flood                    7,280
  Mirai-udpplain                       5,218
  Recon-HostDiscovery                230,989
  Recon-OSScan                       111,077
  Recon-PingSweep                      1,362
  Recon-PortScan                     122,534
  SqlInjection                         4,617
  VulnerabilityScan                  309,485
  XSS                                  2,238

[4] Initializing training-only statistics
------------------------------------------------------------------------------

[5] Fitting preprocessing on development_train only
------------------------------------------------------------------------------

01/21 Backdoor_Malware
Rows: 1,892
Scanned: 1,892

02/21 Benign_Final
Rows: 64,054
Scanned: 64,054

03/21 BrowserHijacking
Rows: 2,300
Scanned: 2,300

04/21 CommandInjection
Rows: 2,693
Scanned: 2,693

05/21 DNS_Spoofing
Rows: 52,456
Scanned: 52,456

06/21 DictionaryBruteForce
Rows: 5,941
Scanned: 5,941

07/21 DoS-HTTP_Flood
Rows: 675,887
Scanned: 675,887

08/21 DoS-SYN_Flood
Rows: 2,797,977
Scanned: 2,797,977

09/21 DoS-TCP_Flood
Rows: 1,146,647
Scanned: 1,146,647

10/21 DoS-UDP_Flood
Rows: 653,806
Scanned: 653,806

11/21 MITM-ArpSpoofing
Rows: 50,997
Scanned: 50,997

12/21 Mirai-greeth_flood
Rows: 3,608
Scanned: 3,608

13/21 Mirai-greip_flood
Rows: 7,280
Scanned: 7,280

14/21 Mirai-udpplain
Rows: 5,218
Scanned: 5,218

15/21 Recon-HostDiscovery
Rows: 230,989
Scanned: 230,989

16/21 Recon-OSScan
Rows: 111,077
Scanned: 111,077

17/21 Recon-PingSweep
Rows: 1,362
Scanned: 1,362

18/21 Recon-PortScan
Rows: 122,534
Scanned: 122,534

19/21 SqlInjection
Rows: 4,617
Scanned: 4,617

20/21 VulnerabilityScan
Rows: 309,485
Scanned: 309,485

21/21 XSS
Rows: 2,238
Scanned: 2,238

[6] Training-row validation
------------------------------------------------------------------------------
Expected rows: 6,253,058
Scanned rows : 6,253,058
Exact match  : True

[7] Deriving training-only preprocessing parameters
------------------------------------------------------------------------------
Input numeric candidates: 79
Zero-variance features  : 4
Retained features       : 75
Features with non-finite: 2

[8] Training non-finite-value report
------------------------------------------------------------------------------

Feature: Flow Bytes/s
  Missing        : 28,608
  +Infinity      : 809
  -Infinity      : 0
  Total nonfinite: 29,417
  Percent        : 0.470442%
  Imputation mean: 59606.832888

Feature: Flow Packets/s
  Missing        : 0
  +Infinity      : 29,417
  -Infinity      : 0
  Total nonfinite: 29,417
  Percent        : 0.470442%
  Imputation mean: 2843.526353

[9] Fold-1 zero-variance features
------------------------------------------------------------------------------
 - Bwd URG Flags
 - Fwd Bytes/Bulk Avg
 - Fwd Packet/Bulk Avg
 - Fwd Bulk Rate Avg

[10] Reproducibility checks
------------------------------------------------------------------------------
Original zero-variance list matched: True
Original non-finite feature list matched: True
Original non-finite counts matched: True

[11] Leakage-safety summary
------------------------------------------------------------------------------
Development-train rows used : 6,253,058
Validation rows used        : 0
Known-test rows used        : 0
Benign-test rows used       : 0
Zero-day DDoS rows used     : 0
Held-out family used in fit : False

[12] Saving Fold-1 preprocessing artifacts
------------------------------------------------------------------------------

[13] Backing up Fold-1 preprocessing to Google Drive
------------------------------------------------------------------------------
Drive preprocessing folder:
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/preprocessing/fold_01_DDoS
Core artifacts backed up: True

[14] Recovery Step A6 validation
------------------------------------------------------------------------------
Training rows exact             : True
Held-out DDoS rows in fit       : 0
Numeric input features          : 79
Zero-variance features          : 4
Retained features               : 75
Original zero-var list matched  : True
Original nonfinite list matched : True
Original nonfinite counts match : True
Retained parameters finite      : True
Retained stds positive          : True
Artifacts backed up to Drive    : True

==============================================================================
✅ RECOVERY STEP A6 PASSED — Fold-1 training-only preprocessing was rebuilt and permanently backed up.
==============================================================================

# Recovery Step A7 — Independently verify Fold-1 preprocessing

In [ ]:
# ======================================================================
# RECOVERY STEP A7
# INDEPENDENTLY VERIFY FOLD-1 TRAINING-ONLY PREPROCESSING
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP A7 — VERIFY FOLD-1 PREPROCESSING")
print("HELD-OUT ZERO-DAY FAMILY: DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A6 STATE
# ======================================================================

print("\n[1] Verifying A6 state")
print("-" * 78)

required_variables = [
    "STEP_9_1_VALID",
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A6."
    )

if not STEP_9_1_VALID:
    raise RuntimeError(
        "Recovery Step A6 did not pass."
    )

print(
    "A6 preprocessing valid:",
    STEP_9_1_VALID
)


# ======================================================================
# 2 — LOAD SAVED PARAMETERS INDEPENDENTLY
# ======================================================================

print("\n[2] Reloading saved preprocessing artifacts")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

FOLD_PREPROCESSING_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

PREPROCESSING_PARAMETERS_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

RETAINED_FEATURES_PATH = (
    FOLD_PREPROCESSING_DIR
    / "retained_features.json"
)


if not PREPROCESSING_PARAMETERS_PATH.exists():
    raise RuntimeError(
        "preprocessing_parameters.csv is missing."
    )

if not RETAINED_FEATURES_PATH.exists():
    raise RuntimeError(
        "retained_features.json is missing."
    )


PREPROCESSING_PARAMETERS = pd.read_csv(
    PREPROCESSING_PARAMETERS_PATH
)


with open(
    RETAINED_FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES_FOLD_1 = json.load(
        file
    )


print(
    "Parameter rows:",
    len(PREPROCESSING_PARAMETERS)
)

print(
    "Retained features:",
    len(RETAINED_FEATURES_FOLD_1)
)


if len(PREPROCESSING_PARAMETERS) != 79:
    raise RuntimeError(
        "Expected 79 preprocessing parameter rows."
    )

if len(RETAINED_FEATURES_FOLD_1) != 75:
    raise RuntimeError(
        "Expected 75 retained Fold-1 features."
    )


# ======================================================================
# 3 — RECOVER ZERO-VARIANCE FEATURE LIST FROM SAVED TABLE
# ======================================================================

zero_variance_column = (
    PREPROCESSING_PARAMETERS[
        "zero_variance"
    ]
)

if zero_variance_column.dtype == bool:

    zero_variance_mask = (
        zero_variance_column
    )

else:

    zero_variance_mask = (
        zero_variance_column
        .astype(str)
        .str.lower()
        .eq("true")
    )


ZERO_VARIANCE_FEATURES_FOLD_1 = (

    PREPROCESSING_PARAMETERS.loc[
        zero_variance_mask,
        "feature"
    ]
    .tolist()
)


EXPECTED_ZERO_VARIANCE = {
    "Bwd URG Flags",
    "Fwd Bytes/Bulk Avg",
    "Fwd Packet/Bulk Avg",
    "Fwd Bulk Rate Avg"
}


ZERO_VARIANCE_LIST_MATCH = (
    set(
        ZERO_VARIANCE_FEATURES_FOLD_1
    )
    ==
    EXPECTED_ZERO_VARIANCE
)


print(
    "Zero-variance features:",
    len(
        ZERO_VARIANCE_FEATURES_FOLD_1
    )
)

print(
    "Zero-var list correct:",
    ZERO_VARIANCE_LIST_MATCH
)


# ======================================================================
# 4 — BUILD FROZEN RETAINED-FEATURE PARAMETER ARRAYS
# ======================================================================

parameter_lookup = (
    PREPROCESSING_PARAMETERS
    .set_index("feature")
)


missing_retained_parameters = [
    feature
    for feature
    in RETAINED_FEATURES_FOLD_1
    if feature not in parameter_lookup.index
]


if missing_retained_parameters:
    raise RuntimeError(
        "Missing saved parameters for retained features: "
        + str(missing_retained_parameters)
    )


retained_parameter_table = (
    parameter_lookup
    .loc[
        RETAINED_FEATURES_FOLD_1
    ]
)


IMPUTATION_VALUES = (
    retained_parameter_table[
        "imputation_value"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (
    retained_parameter_table[
        "scaler_mean"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (
    retained_parameter_table[
        "scaler_std"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


PARAMETERS_VALID = bool(

    np.isfinite(
        IMPUTATION_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Frozen parameter arrays valid:",
    PARAMETERS_VALID
)


if not PARAMETERS_VALID:
    raise RuntimeError(
        "Saved preprocessing parameters are invalid."
    )


# ======================================================================
# 5 — SELECT EXACT FOLD-1 DEVELOPMENT TRAIN RANGES
# ======================================================================

print("\n[3] Selecting verification rows")
print("-" * 78)


train_manifest = (
    LOAFO_SPLIT_MANIFEST[
        (
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == 1
        )
        &
        (
            LOAFO_SPLIT_MANIFEST[
                "partition"
            ]
            ==
            "development_train"
        )
    ]
    .copy()
    .reset_index(drop=True)
)


expected_train_rows = int(

    LOAFO_FOLD_SUMMARY.loc[
        LOAFO_FOLD_SUMMARY[
            "fold_id"
        ] == 1,
        "development_train_rows"
    ]
    .iloc[0]
)


ddos_rows = int(

    train_manifest.loc[
        train_manifest[
            "research_family"
        ]
        ==
        "DDoS",
        "row_count"
    ]
    .sum()
)


print(
    "Training source ranges:",
    len(train_manifest)
)

print(
    "Expected rows:",
    f"{expected_train_rows:,}"
)

print(
    "DDoS rows:",
    ddos_rows
)


if expected_train_rows != 6_253_058:
    raise RuntimeError(
        "Unexpected Fold-1 training-row count."
    )

if ddos_rows != 0:
    raise RuntimeError(
        "DDoS leakage detected."
    )


# ======================================================================
# 6 — INITIALIZE ONLINE VERIFICATION STATISTICS
# ======================================================================

print("\n[4] Reapplying frozen preprocessing")
print("-" * 78)

n_features = len(
    RETAINED_FEATURES_FOLD_1
)

verification_count = 0

verification_mean = np.zeros(
    n_features,
    dtype=np.float64
)

verification_M2 = np.zeros(
    n_features,
    dtype=np.float64
)

POST_TRANSFORM_NONFINITE = 0

BATCH_SIZE = 50_000


# ======================================================================
# 7 — STREAM EXACT DEVELOPMENT-TRAIN ROWS
# ======================================================================

for source_number, row in train_manifest.iterrows():

    source_class = row[
        "source_attack_class"
    ]

    start_row = int(
        row["start_row"]
    )

    end_row = int(
        row["end_row_exclusive"]
    )

    expected_source_rows = int(
        row["row_count"]
    )

    parquet_path = Path(
        row["parquet_path"]
    )


    print(
        f"\n{source_number + 1:02d}/{len(train_manifest):02d} "
        f"{source_class}"
    )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    absolute_position = 0
    source_rows_processed = 0


    for batch in parquet_file.iter_batches(

        columns=
            RETAINED_FEATURES_FOLD_1,

        batch_size=
            BATCH_SIZE
    ):

        batch_rows = (
            batch.num_rows
        )

        batch_start = (
            absolute_position
        )

        batch_end = (
            batch_start
            +
            batch_rows
        )

        absolute_position = (
            batch_end
        )


        if batch_end <= start_row:
            continue


        if batch_start >= end_row:
            break


        local_start = max(
            0,
            start_row - batch_start
        )


        local_end = min(
            batch_rows,
            end_row - batch_start
        )


        if local_end <= local_start:
            continue


        sliced_batch = batch.slice(

            local_start,

            local_end - local_start
        )


        X = (
            sliced_batch
            .to_pandas()
            .to_numpy(
                dtype=np.float64,
                copy=True
            )
        )


        # --------------------------------------------------------------
        # Apply FROZEN training-only imputation
        # --------------------------------------------------------------

        nonfinite_mask = (
            ~np.isfinite(X)
        )


        if nonfinite_mask.any():

            row_indices, feature_indices = (
                np.where(
                    nonfinite_mask
                )
            )


            X[
                row_indices,
                feature_indices
            ] = (
                IMPUTATION_VALUES[
                    feature_indices
                ]
            )


        # --------------------------------------------------------------
        # Apply FROZEN training-only standardization
        # --------------------------------------------------------------

        Z = (
            X
            -
            SCALER_MEANS
        ) / SCALER_STDS


        post_nonfinite = int(
            (
                ~np.isfinite(Z)
            ).sum()
        )


        POST_TRANSFORM_NONFINITE += (
            post_nonfinite
        )


        if post_nonfinite != 0:

            raise RuntimeError(
                f"Non-finite transformed values "
                f"found in {source_class}."
            )


        # --------------------------------------------------------------
        # Independent online mean / variance of transformed data
        # --------------------------------------------------------------

        batch_count = (
            Z.shape[0]
        )


        batch_mean = (
            Z.mean(
                axis=0,
                dtype=np.float64
            )
        )


        centered = (
            Z
            -
            batch_mean
        )


        batch_M2 = (
            centered
            *
            centered
        ).sum(
            axis=0,
            dtype=np.float64
        )


        if verification_count == 0:

            verification_mean = (
                batch_mean.copy()
            )

            verification_M2 = (
                batch_M2.copy()
            )

            verification_count = (
                batch_count
            )

        else:

            combined_count = (
                verification_count
                +
                batch_count
            )


            delta = (
                batch_mean
                -
                verification_mean
            )


            verification_mean = (

                verification_mean

                +

                delta
                *
                batch_count
                /
                combined_count
            )


            verification_M2 = (

                verification_M2

                +

                batch_M2

                +

                (
                    delta
                    *
                    delta
                )
                *
                verification_count
                *
                batch_count
                /
                combined_count
            )


            verification_count = (
                combined_count
            )


        source_rows_processed += (
            batch_count
        )


    print(
        "Processed:",
        f"{source_rows_processed:,}"
    )


    if source_rows_processed != expected_source_rows:

        raise RuntimeError(
            f"Verification row mismatch for "
            f"{source_class}: "
            f"expected {expected_source_rows:,}, "
            f"processed {source_rows_processed:,}."
        )


# ======================================================================
# 8 — FINAL TRANSFORMED STATISTICS
# ======================================================================

print("\n[5] Computing verification statistics")
print("-" * 78)


VERIFICATION_ROW_COUNT_EXACT = (
    verification_count
    ==
    expected_train_rows
)


verification_variance = (
    verification_M2
    /
    float(
        verification_count
    )
)


verification_std = np.sqrt(
    np.maximum(
        verification_variance,
        0.0
    )
)


absolute_mean_error = np.abs(
    verification_mean
)


absolute_std_error = np.abs(
    verification_std
    -
    1.0
)


MAX_ABSOLUTE_MEAN_ERROR = float(
    absolute_mean_error.max()
)


MAX_ABSOLUTE_STD_ERROR = float(
    absolute_std_error.max()
)


VERIFICATION_TOLERANCE = 1e-5


MEANS_APPROX_ZERO = bool(
    MAX_ABSOLUTE_MEAN_ERROR
    <=
    VERIFICATION_TOLERANCE
)


STDS_APPROX_ONE = bool(
    MAX_ABSOLUTE_STD_ERROR
    <=
    VERIFICATION_TOLERANCE
)


ALL_TRANSFORMED_FINITE = (
    POST_TRANSFORM_NONFINITE == 0
)


print(
    "Expected rows:",
    f"{expected_train_rows:,}"
)

print(
    "Verified rows:",
    f"{verification_count:,}"
)

print(
    "Exact row match:",
    VERIFICATION_ROW_COUNT_EXACT
)

print(
    "Max |training mean|:",
    f"{MAX_ABSOLUTE_MEAN_ERROR:.10f}"
)

print(
    "Max |training std - 1|:",
    f"{MAX_ABSOLUTE_STD_ERROR:.10f}"
)

print(
    "Tolerance:",
    VERIFICATION_TOLERANCE
)

print(
    "Means approximately zero:",
    MEANS_APPROX_ZERO
)

print(
    "Stds approximately one:",
    STDS_APPROX_ONE
)

print(
    "Post-transform non-finite:",
    POST_TRANSFORM_NONFINITE
)


# ======================================================================
# 9 — BUILD PER-FEATURE VERIFICATION TABLE
# ======================================================================

verification_table = pd.DataFrame({

    "feature":
        RETAINED_FEATURES_FOLD_1,

    "transformed_mean":
        verification_mean,

    "transformed_std":
        verification_std,

    "absolute_mean_error":
        absolute_mean_error,

    "absolute_std_error_from_one":
        absolute_std_error
})


print("\n[6] Largest verification errors")
print("-" * 78)


print("\nLargest absolute mean errors:")

display(

    verification_table
    .sort_values(
        "absolute_mean_error",
        ascending=False
    )
    .head(10)
)


print("\nLargest standard-deviation errors:")

display(

    verification_table
    .sort_values(
        "absolute_std_error_from_one",
        ascending=False
    )
    .head(10)
)


# ======================================================================
# 10 — SAVE VERIFICATION ARTIFACTS
# ======================================================================

print("\n[7] Saving verification artifacts")
print("-" * 78)


VERIFICATION_TABLE_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_verification.csv"
)


VERIFICATION_SUMMARY_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_verification_summary.json"
)


verification_table.to_csv(
    VERIFICATION_TABLE_PATH,
    index=False
)


verification_summary = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "expected_training_rows":
        int(expected_train_rows),

    "verified_training_rows":
        int(verification_count),

    "retained_feature_count":
        len(RETAINED_FEATURES_FOLD_1),

    "maximum_absolute_transformed_mean":
        MAX_ABSOLUTE_MEAN_ERROR,

    "maximum_absolute_transformed_std_error":
        MAX_ABSOLUTE_STD_ERROR,

    "tolerance":
        VERIFICATION_TOLERANCE,

    "means_approximately_zero":
        MEANS_APPROX_ZERO,

    "standard_deviations_approximately_one":
        STDS_APPROX_ONE,

    "post_transform_nonfinite_values":
        int(
            POST_TRANSFORM_NONFINITE
        )
}


with open(
    VERIFICATION_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        verification_summary,
        file,
        indent=4
    )


# ======================================================================
# 11 — COPY TO GOOGLE DRIVE
# ======================================================================

DRIVE_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


DRIVE_FOLD_PREPROCESSING_DIR = (
    DRIVE_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


DRIVE_FOLD_PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in [
    VERIFICATION_TABLE_PATH,
    VERIFICATION_SUMMARY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_FOLD_PREPROCESSING_DIR
        / source_path.name
    )


DRIVE_VERIFICATION_OUTPUTS_EXIST = all(

    (
        DRIVE_FOLD_PREPROCESSING_DIR
        /
        source_path.name
    ).exists()

    for source_path in [
        VERIFICATION_TABLE_PATH,
        VERIFICATION_SUMMARY_PATH
    ]
)


# ======================================================================
# 12 — FINAL VALIDATION
# ======================================================================

STEP_9_2_VALID = bool(

    VERIFICATION_ROW_COUNT_EXACT

    and

    ZERO_VARIANCE_LIST_MATCH

    and

    PARAMETERS_VALID

    and

    MEANS_APPROX_ZERO

    and

    STDS_APPROX_ONE

    and

    ALL_TRANSFORMED_FINITE

    and

    VERIFICATION_TABLE_PATH.exists()

    and

    VERIFICATION_SUMMARY_PATH.exists()

    and

    DRIVE_VERIFICATION_OUTPUTS_EXIST
)


print("\n[8] Recovery Step A7 validation")
print("-" * 78)

print(
    "Training rows exact          :",
    VERIFICATION_ROW_COUNT_EXACT
)

print(
    "Retained feature count       :",
    len(RETAINED_FEATURES_FOLD_1)
)

print(
    "Zero-var list verified       :",
    ZERO_VARIANCE_LIST_MATCH
)

print(
    "Frozen parameters valid      :",
    PARAMETERS_VALID
)

print(
    "Means approximately zero     :",
    MEANS_APPROX_ZERO
)

print(
    "Stds approximately one       :",
    STDS_APPROX_ONE
)

print(
    "All transformed values finite:",
    ALL_TRANSFORMED_FINITE
)

print(
    "Artifacts backed up to Drive :",
    DRIVE_VERIFICATION_OUTPUTS_EXIST
)


print("\n" + "=" * 78)

if STEP_9_2_VALID:

    print(
        "✅ RECOVERY STEP A7 PASSED — "
        "Fold-1 preprocessing was independently verified "
        "and backed up to Google Drive."
    )

else:

    print(
        "❌ RECOVERY STEP A7 FAILED — "
        "Do not apply preprocessing to validation/test yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A7 — VERIFY FOLD-1 PREPROCESSING
HELD-OUT ZERO-DAY FAMILY: DDoS
==============================================================================

[1] Verifying A6 state
------------------------------------------------------------------------------
A6 preprocessing valid: True

[2] Reloading saved preprocessing artifacts
------------------------------------------------------------------------------
Parameter rows: 79
Retained features: 75
Zero-variance features: 4
Zero-var list correct: True
Frozen parameter arrays valid: True

[3] Selecting verification rows
------------------------------------------------------------------------------
Training source ranges: 21
Expected rows: 6,253,058
DDoS rows: 0

[4] Reapplying frozen preprocessing
------------------------------------------------------------------------------

01/21 Backdoor_Malware
Processed: 1,892

02/21 Benign_Final
Processed: 64,054

03/21 BrowserHijacking
Processed: 2,300

04/21 CommandInjection
Processed: 2,693

05/21 DNS_Spoofing
Processed: 52,456

06/21 DictionaryBruteForce
Processed: 5,941

07/21 DoS-HTTP_Flood
Processed: 675,887

08/21 DoS-SYN_Flood
Processed: 2,797,977

09/21 DoS-TCP_Flood
Processed: 1,146,647

10/21 DoS-UDP_Flood
Processed: 653,806

11/21 MITM-ArpSpoofing
Processed: 50,997

12/21 Mirai-greeth_flood
Processed: 3,608

13/21 Mirai-greip_flood
Processed: 7,280

14/21 Mirai-udpplain
Processed: 5,218

15/21 Recon-HostDiscovery
Processed: 230,989

16/21 Recon-OSScan
Processed: 111,077

17/21 Recon-PingSweep
Processed: 1,362

18/21 Recon-PortScan
Processed: 122,534

19/21 SqlInjection
Processed: 4,617

20/21 VulnerabilityScan
Processed: 309,485

21/21 XSS
Processed: 2,238

[5] Computing verification statistics
------------------------------------------------------------------------------
Expected rows: 6,253,058
Verified rows: 6,253,058
Exact row match: True
Max |training mean|: 0.0000000000
Max |training std - 1|: 0.0000000000
Tolerance: 1e-05
Means approximately zero: True
Stds approximately one: True
Post-transform non-finite: 0

[6] Largest verification errors
------------------------------------------------------------------------------

Largest absolute mean errors:

,feature,transformed_mean,transformed_std,absolute_mean_error,absolute_std_error_from_one
50,CWR Flag Count,2.646429e-15,1.0,2.646429e-15,1.332268e-15
32,Fwd PSH Flags,8.422625e-16,1.0,8.422625e-16,1.110223e-16
51,ECE Flag Count,7.166847e-16,1.0,7.166847e-16,6.661338e-16
66,Fwd Seg Size Min,5.149418e-16,1.0,5.149418e-16,2.220446e-16
22,Fwd IAT Total,-2.694141e-16,1.0,2.694141e-16,3.330669e-16
27,Bwd IAT Total,2.504778e-16,1.0,2.504778e-16,0.000000e+00
74,Idle Min,-2.274656e-16,1.0,2.274656e-16,0.000000e+00
28,Bwd IAT Mean,2.145636e-16,1.0,2.145636e-16,2.220446e-16
21,Flow IAT Min,-2.117684e-16,1.0,2.117684e-16,0.000000e+00
44,FIN Flag Count,2.020140e-16,1.0,2.020140e-16,4.440892e-16

Largest standard-deviation errors:

,feature,transformed_mean,transformed_std,absolute_mean_error,absolute_std_error_from_one
34,Fwd URG Flags,1.797616e-18,1.0,1.797616e-18,9.992007e-15
33,Bwd PSH Flags,1.200483e-16,1.0,1.200483e-16,1.776357e-15
50,CWR Flag Count,2.646429e-15,1.0,2.646429e-15,1.332268e-15
64,Bwd Init Win Bytes,1.198314e-16,1.0,1.198314e-16,1.110223e-15
62,Subflow Bwd Bytes,1.038462e-18,1.0,1.038462e-18,8.881784e-16
46,RST Flag Count,7.611099e-17,1.0,7.611099e-17,6.661338e-16
51,ECE Flag Count,7.166847e-16,1.0,7.166847e-16,6.661338e-16
13,Bwd Packet Length Min,5.206881e-17,1.0,5.206881e-17,4.440892e-16
2,Protocol,1.623051e-16,1.0,1.623051e-16,4.440892e-16
9,Fwd Packet Length Min,-4.068469e-17,1.0,4.068469e-17,4.440892e-16

[7] Saving verification artifacts
------------------------------------------------------------------------------

[8] Recovery Step A7 validation
------------------------------------------------------------------------------
Training rows exact          : True
Retained feature count       : 75
Zero-var list verified       : True
Frozen parameters valid      : True
Means approximately zero     : True
Stds approximately one       : True
All transformed values finite: True
Artifacts backed up to Drive : True

==============================================================================
✅ RECOVERY STEP A7 PASSED — Fold-1 preprocessing was independently verified and backed up to Google Drive.
==============================================================================

# Recovery Step A8 — Apply frozen preprocessing to validation/test

In [ ]:
# ======================================================================
# RECOVERY STEP A8
# APPLY FROZEN FOLD-1 PREPROCESSING TO ALL NON-TRAINING PARTITIONS
# + TRACK EXTREME STANDARDIZED VALUES
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP A8 — APPLY FROZEN FOLD-1 PREPROCESSING")
print("HELD-OUT ZERO-DAY FAMILY: DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A7 STATE
# ======================================================================

print("\n[1] Verifying A7 state")
print("-" * 78)

required_variables = [
    "STEP_9_2_VALID",
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A7."
    )

if not STEP_9_2_VALID:
    raise RuntimeError(
        "Recovery Step A7 did not pass."
    )

print(
    "Fold-1 preprocessing independently verified:",
    STEP_9_2_VALID
)


# ======================================================================
# 2 — LOAD FROZEN PREPROCESSING FROM DISK
# ======================================================================

print("\n[2] Loading frozen training-only parameters")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

FOLD_PREPROCESSING_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

PARAMETERS_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

RETAINED_FEATURES_PATH = (
    FOLD_PREPROCESSING_DIR
    / "retained_features.json"
)


PREPROCESSING_PARAMETERS = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    RETAINED_FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES_FOLD_1 = json.load(
        file
    )


parameter_lookup = (
    PREPROCESSING_PARAMETERS
    .set_index("feature")
)


retained_parameter_table = (
    parameter_lookup
    .loc[
        RETAINED_FEATURES_FOLD_1
    ]
)


IMPUTATION_VALUES = (
    retained_parameter_table[
        "imputation_value"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (
    retained_parameter_table[
        "scaler_mean"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (
    retained_parameter_table[
        "scaler_std"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


FROZEN_PARAMETERS_VALID = bool(

    len(
        RETAINED_FEATURES_FOLD_1
    ) == 75

    and

    np.isfinite(
        IMPUTATION_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Frozen retained features:",
    len(
        RETAINED_FEATURES_FOLD_1
    )
)

print(
    "Frozen parameters valid:",
    FROZEN_PARAMETERS_VALID
)


if not FROZEN_PARAMETERS_VALID:
    raise RuntimeError(
        "Frozen preprocessing parameters are invalid."
    )


# ======================================================================
# 3 — SELECT NON-TRAINING PARTITIONS
# ======================================================================

print("\n[3] Selecting Fold-1 non-training partitions")
print("-" * 78)


TARGET_PARTITIONS = [
    "development_validation",
    "known_test",
    "benign_test",
    "zero_day_attack_test"
]


application_manifest = (
    LOAFO_SPLIT_MANIFEST[
        (
            LOAFO_SPLIT_MANIFEST[
                "fold_id"
            ] == 1
        )
        &
        (
            LOAFO_SPLIT_MANIFEST[
                "partition"
            ].isin(
                TARGET_PARTITIONS
            )
        )
    ]
    .copy()
    .reset_index(drop=True)
)


print(
    "Source ranges to process:",
    len(application_manifest)
)


expected_partition_rows = {

    partition: int(
        application_manifest.loc[
            application_manifest[
                "partition"
            ] == partition,
            "row_count"
        ].sum()
    )

    for partition
    in TARGET_PARTITIONS
}


print("\nExpected rows:")

for partition in TARGET_PARTITIONS:

    print(
        f"  {partition:<27}: "
        f"{expected_partition_rows[partition]:,}"
    )


# ======================================================================
# 4 — LEAKAGE POLICY
# ======================================================================

print("\n[4] Frozen preprocessing policy")
print("-" * 78)

print(
    "Imputation refitted here       : False"
)

print(
    "Scaler mean refitted here      : False"
)

print(
    "Scaler std refitted here       : False"
)

print(
    "Feature selection refitted here: False"
)

print(
    "Zero-variance fitting here     : False"
)

print(
    "All parameters source          : Fold-1 development_train"
)


# ======================================================================
# 5 — STREAM AND APPLY FROZEN PARAMETERS
# ======================================================================

print("\n[5] Applying frozen preprocessing")
print("-" * 78)


BATCH_SIZE = 50_000

audit_records = []


for range_number, row in application_manifest.iterrows():

    partition = row[
        "partition"
    ]

    source_class = row[
        "source_attack_class"
    ]

    research_family = row[
        "research_family"
    ]

    start_row = int(
        row["start_row"]
    )

    end_row = int(
        row["end_row_exclusive"]
    )

    expected_rows = int(
        row["row_count"]
    )

    parquet_path = Path(
        row["parquet_path"]
    )


    # --------------------------------------------------------------
    # Strict zero-day isolation safety
    # --------------------------------------------------------------

    if (
        research_family == "DDoS"
        and
        partition != "zero_day_attack_test"
    ):
        raise RuntimeError(
            "DDoS leakage detected outside zero-day partition."
        )


    if (
        partition == "zero_day_attack_test"
        and
        research_family != "DDoS"
    ):
        raise RuntimeError(
            "Non-DDoS source detected inside zero-day partition."
        )


    print("\n" + "-" * 78)

    print(
        f"{range_number + 1:02d}/{len(application_manifest)}"
    )

    print(
        "Partition:",
        partition
    )

    print(
        "Class    :",
        source_class
    )

    print(
        "Family   :",
        research_family
    )

    print(
        "Rows     :",
        f"{expected_rows:,}"
    )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    absolute_position = 0

    processed_rows = 0

    raw_nonfinite_values = 0

    float64_nonfinite_values = 0

    float32_nonfinite_values = 0


    # --------------------------------------------------------------
    # Extreme-value diagnostics
    # --------------------------------------------------------------

    range_max_abs_z = -np.inf

    range_max_feature = None

    range_max_value_used = None

    range_max_was_imputed = None


    for batch in parquet_file.iter_batches(

        columns=
            RETAINED_FEATURES_FOLD_1,

        batch_size=
            BATCH_SIZE
    ):

        batch_rows = (
            batch.num_rows
        )

        batch_start = (
            absolute_position
        )

        batch_end = (
            batch_start
            +
            batch_rows
        )

        absolute_position = (
            batch_end
        )


        if batch_end <= start_row:
            continue


        if batch_start >= end_row:
            break


        local_start = max(
            0,
            start_row - batch_start
        )


        local_end = min(
            batch_rows,
            end_row - batch_start
        )


        if local_end <= local_start:
            continue


        sliced_batch = batch.slice(

            local_start,

            local_end - local_start
        )


        X = (
            sliced_batch
            .to_pandas()
            .to_numpy(
                dtype=np.float64,
                copy=True
            )
        )


        # ----------------------------------------------------------
        # Count raw non-finite values
        # ----------------------------------------------------------

        nonfinite_mask = (
            ~np.isfinite(X)
        )


        raw_nonfinite_values += int(
            nonfinite_mask.sum()
        )


        # ----------------------------------------------------------
        # Frozen mean imputation
        # ----------------------------------------------------------

        if nonfinite_mask.any():

            row_indices, feature_indices = (
                np.where(
                    nonfinite_mask
                )
            )


            X[
                row_indices,
                feature_indices
            ] = (
                IMPUTATION_VALUES[
                    feature_indices
                ]
            )


        # ----------------------------------------------------------
        # Frozen z-score standardization
        # ----------------------------------------------------------

        Z = (
            X
            -
            SCALER_MEANS
        ) / SCALER_STDS


        current_float64_nonfinite = int(
            (
                ~np.isfinite(Z)
            ).sum()
        )


        float64_nonfinite_values += (
            current_float64_nonfinite
        )


        # ----------------------------------------------------------
        # Track exact largest absolute standardized value
        # ----------------------------------------------------------

        if Z.size > 0:

            absolute_Z = np.abs(
                Z
            )

            flat_index = int(
                np.argmax(
                    absolute_Z
                )
            )


            batch_max_abs_z = float(
                absolute_Z.flat[
                    flat_index
                ]
            )


            if batch_max_abs_z > range_max_abs_z:

                row_index, feature_index = (
                    np.unravel_index(
                        flat_index,
                        Z.shape
                    )
                )


                range_max_abs_z = (
                    batch_max_abs_z
                )


                range_max_feature = (
                    RETAINED_FEATURES_FOLD_1[
                        feature_index
                    ]
                )


                range_max_value_used = float(
                    X[
                        row_index,
                        feature_index
                    ]
                )


                range_max_was_imputed = bool(
                    nonfinite_mask[
                        row_index,
                        feature_index
                    ]
                )


        # ----------------------------------------------------------
        # Float32 safety check
        # ----------------------------------------------------------

        with np.errstate(
            over="ignore",
            invalid="ignore"
        ):

            Z_float32 = Z.astype(
                np.float32
            )


        current_float32_nonfinite = int(
            (
                ~np.isfinite(
                    Z_float32
                )
            ).sum()
        )


        float32_nonfinite_values += (
            current_float32_nonfinite
        )


        processed_rows += (
            X.shape[0]
        )


    # --------------------------------------------------------------
    # Range-level checks
    # --------------------------------------------------------------

    row_count_match = bool(
        processed_rows
        ==
        expected_rows
    )


    range_pass = bool(

        row_count_match

        and

        float64_nonfinite_values == 0

        and

        float32_nonfinite_values == 0
    )


    print(
        "Processed rows       :",
        f"{processed_rows:,}"
    )

    print(
        "Raw non-finite values:",
        f"{raw_nonfinite_values:,}"
    )

    print(
        "Float64 non-finite out:",
        float64_nonfinite_values
    )

    print(
        "Float32 non-finite out:",
        float32_nonfinite_values
    )

    print(
        "Max |Z|             :",
        f"{range_max_abs_z:.6e}"
    )

    print(
        "Max |Z| feature     :",
        range_max_feature
    )

    print(
        "Status              :",
        "PASS"
        if range_pass
        else "FAIL"
    )


    audit_records.append({

        "partition":
            partition,

        "source_attack_class":
            source_class,

        "research_family":
            research_family,

        "expected_rows":
            expected_rows,

        "processed_rows":
            processed_rows,

        "raw_nonfinite_values":
            raw_nonfinite_values,

        "post_float64_nonfinite_values":
            float64_nonfinite_values,

        "post_float32_nonfinite_values":
            float32_nonfinite_values,

        "maximum_absolute_standardized_value":
            range_max_abs_z,

        "maximum_z_feature":
            range_max_feature,

        "value_used_at_maximum_z":
            range_max_value_used,

        "maximum_z_value_was_imputed":
            range_max_was_imputed,

        "status":
            (
                "PASS"
                if range_pass
                else "FAIL"
            )
    })


# ======================================================================
# 6 — BUILD AUDIT TABLE
# ======================================================================

APPLICATION_AUDIT = pd.DataFrame(
    audit_records
)


print("\n[6] Partition transformation summary")
print("-" * 78)


partition_summary = (

    APPLICATION_AUDIT

    .groupby(
        "partition",
        as_index=False
    )

    .agg(

        source_ranges=
            (
                "source_attack_class",
                "count"
            ),

        expected_rows=
            (
                "expected_rows",
                "sum"
            ),

        processed_rows=
            (
                "processed_rows",
                "sum"
            ),

        raw_nonfinite_values=
            (
                "raw_nonfinite_values",
                "sum"
            ),

        post_float64_nonfinite_values=
            (
                "post_float64_nonfinite_values",
                "sum"
            ),

        post_float32_nonfinite_values=
            (
                "post_float32_nonfinite_values",
                "sum"
            ),

        maximum_absolute_standardized_value=
            (
                "maximum_absolute_standardized_value",
                "max"
            )
    )
)


display(
    partition_summary
)


# ======================================================================
# 7 — SHOW LARGEST STANDARDIZED VALUES
# ======================================================================

print("\n[7] Largest standardized values by source range")
print("-" * 78)


EXTREME_RANGES = (

    APPLICATION_AUDIT

    .sort_values(
        "maximum_absolute_standardized_value",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


display(

    EXTREME_RANGES[
        [
            "partition",
            "source_attack_class",
            "research_family",
            "maximum_absolute_standardized_value",
            "maximum_z_feature",
            "value_used_at_maximum_z",
            "maximum_z_value_was_imputed"
        ]
    ]
    .head(15)
)


# ======================================================================
# 8 — PARTITION ROW-COUNT VALIDATION
# ======================================================================

print("\n[8] Partition row-count validation")
print("-" * 78)


PARTITION_ROW_COUNTS_EXACT = True


for partition in TARGET_PARTITIONS:

    expected = int(
        expected_partition_rows[
            partition
        ]
    )

    processed = int(

        APPLICATION_AUDIT.loc[
            APPLICATION_AUDIT[
                "partition"
            ] == partition,
            "processed_rows"
        ].sum()
    )


    match = (
        expected
        ==
        processed
    )


    PARTITION_ROW_COUNTS_EXACT &= (
        match
    )


    print(
        f"{partition:<27} "
        f"expected={expected:>12,} "
        f"processed={processed:>12,} "
        f"match={match}"
    )


# ======================================================================
# 9 — NUMERICAL VALIDITY
# ======================================================================

TOTAL_RAW_NONFINITE = int(
    APPLICATION_AUDIT[
        "raw_nonfinite_values"
    ].sum()
)


TOTAL_FLOAT64_NONFINITE = int(
    APPLICATION_AUDIT[
        "post_float64_nonfinite_values"
    ].sum()
)


TOTAL_FLOAT32_NONFINITE = int(
    APPLICATION_AUDIT[
        "post_float32_nonfinite_values"
    ].sum()
)


ALL_RANGES_PASS = bool(
    (
        APPLICATION_AUDIT[
            "status"
        ] == "PASS"
    ).all()
)


ALL_FLOAT64_FINITE = (
    TOTAL_FLOAT64_NONFINITE == 0
)


ALL_FLOAT32_FINITE = (
    TOTAL_FLOAT32_NONFINITE == 0
)


print("\n[9] Frozen transformation validity")
print("-" * 78)

print(
    "Raw non-finite values encountered :",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "Non-finite after float64 transform:",
    TOTAL_FLOAT64_NONFINITE
)

print(
    "Non-finite after float32 transform:",
    TOTAL_FLOAT32_NONFINITE
)

print(
    "All source ranges passed          :",
    ALL_RANGES_PASS
)


# ======================================================================
# 10 — LEAKAGE-SAFETY CHECK
# ======================================================================

print("\n[10] Leakage-safety verification")
print("-" * 78)


DDoS_OUTSIDE_ZERO_DAY = int(

    APPLICATION_AUDIT.loc[
        (
            APPLICATION_AUDIT[
                "research_family"
            ] == "DDoS"
        )
        &
        (
            APPLICATION_AUDIT[
                "partition"
            ]
            !=
            "zero_day_attack_test"
        ),
        "processed_rows"
    ].sum()
)


NON_DDoS_INSIDE_ZERO_DAY = int(

    APPLICATION_AUDIT.loc[
        (
            APPLICATION_AUDIT[
                "partition"
            ]
            ==
            "zero_day_attack_test"
        )
        &
        (
            APPLICATION_AUDIT[
                "research_family"
            ]
            !=
            "DDoS"
        ),
        "processed_rows"
    ].sum()
)


LEAKAGE_SAFE = bool(

    DDoS_OUTSIDE_ZERO_DAY == 0

    and

    NON_DDoS_INSIDE_ZERO_DAY == 0
)


print(
    "DDoS rows outside zero-day test:",
    DDoS_OUTSIDE_ZERO_DAY
)

print(
    "Non-DDoS rows in zero-day test :",
    NON_DDoS_INSIDE_ZERO_DAY
)

print(
    "Parameters refitted             :",
    False
)

print(
    "Leakage-safe                    :",
    LEAKAGE_SAFE
)


# ======================================================================
# 11 — SAVE ARTIFACTS
# ======================================================================

print("\n[11] Saving A8 artifacts")
print("-" * 78)


APPLICATION_AUDIT_PATH = (
    FOLD_PREPROCESSING_DIR
    / "nontraining_preprocessing_application_audit.csv"
)


APPLICATION_SUMMARY_PATH = (
    FOLD_PREPROCESSING_DIR
    / "nontraining_preprocessing_application_summary.json"
)


APPLICATION_AUDIT.to_csv(
    APPLICATION_AUDIT_PATH,
    index=False
)


worst_row = (
    EXTREME_RANGES.iloc[0]
)


application_summary = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "retained_feature_count":
        len(
            RETAINED_FEATURES_FOLD_1
        ),

    "target_partitions":
        TARGET_PARTITIONS,

    "total_raw_nonfinite_values":
        TOTAL_RAW_NONFINITE,

    "total_post_float64_nonfinite_values":
        TOTAL_FLOAT64_NONFINITE,

    "total_post_float32_nonfinite_values":
        TOTAL_FLOAT32_NONFINITE,

    "all_partition_row_counts_exact":
        bool(
            PARTITION_ROW_COUNTS_EXACT
        ),

    "all_source_ranges_pass":
        ALL_RANGES_PASS,

    "held_out_isolation_preserved":
        LEAKAGE_SAFE,

    "maximum_absolute_standardized_value":
        float(
            worst_row[
                "maximum_absolute_standardized_value"
            ]
        ),

    "maximum_z_partition":
        str(
            worst_row[
                "partition"
            ]
        ),

    "maximum_z_source_class":
        str(
            worst_row[
                "source_attack_class"
            ]
        ),

    "maximum_z_feature":
        str(
            worst_row[
                "maximum_z_feature"
            ]
        ),

    "value_used_at_maximum_z":
        float(
            worst_row[
                "value_used_at_maximum_z"
            ]
        )
}


with open(
    APPLICATION_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        application_summary,
        file,
        indent=4
    )


# ======================================================================
# 12 — BACK UP A8 ARTIFACTS TO GOOGLE DRIVE
# ======================================================================

DRIVE_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


DRIVE_FOLD_PREPROCESSING_DIR = (
    DRIVE_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


DRIVE_FOLD_PREPROCESSING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in [
    APPLICATION_AUDIT_PATH,
    APPLICATION_SUMMARY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_FOLD_PREPROCESSING_DIR
        / source_path.name
    )


DRIVE_APPLICATION_OUTPUTS_EXIST = all(

    (
        DRIVE_FOLD_PREPROCESSING_DIR
        /
        source_path.name
    ).exists()

    for source_path in [
        APPLICATION_AUDIT_PATH,
        APPLICATION_SUMMARY_PATH
    ]
)


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

STEP_9_3_VALID = bool(

    FROZEN_PARAMETERS_VALID

    and

    PARTITION_ROW_COUNTS_EXACT

    and

    ALL_FLOAT64_FINITE

    and

    ALL_FLOAT32_FINITE

    and

    ALL_RANGES_PASS

    and

    LEAKAGE_SAFE

    and

    DRIVE_APPLICATION_OUTPUTS_EXIST
)


print("\n[12] Recovery Step A8 validation")
print("-" * 78)

print(
    "Frozen parameters valid          :",
    FROZEN_PARAMETERS_VALID
)

print(
    "All partition row counts exact   :",
    PARTITION_ROW_COUNTS_EXACT
)

print(
    "All float64 transformed finite   :",
    ALL_FLOAT64_FINITE
)

print(
    "All float32 transformed finite   :",
    ALL_FLOAT32_FINITE
)

print(
    "All source ranges passed         :",
    ALL_RANGES_PASS
)

print(
    "Held-out isolation preserved     :",
    LEAKAGE_SAFE
)

print(
    "Artifacts backed up to Drive     :",
    DRIVE_APPLICATION_OUTPUTS_EXIST
)


print("\nLargest observed standardized value:")

print(
    "  Partition :",
    worst_row[
        "partition"
    ]
)

print(
    "  Class     :",
    worst_row[
        "source_attack_class"
    ]
)

print(
    "  Feature   :",
    worst_row[
        "maximum_z_feature"
    ]
)

print(
    "  Max |Z|   :",
    f"{worst_row['maximum_absolute_standardized_value']:.6e}"
)

print(
    "  Raw/value used:",
    worst_row[
        "value_used_at_maximum_z"
    ]
)


print("\n" + "=" * 78)

if STEP_9_3_VALID:

    print(
        "✅ RECOVERY STEP A8 PASSED — "
        "Frozen Fold-1 preprocessing was safely applied "
        "to all validation and test partitions."
    )

else:

    print(
        "❌ RECOVERY STEP A8 FAILED — "
        "Do not continue to temporal windows yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A8 — APPLY FROZEN FOLD-1 PREPROCESSING
HELD-OUT ZERO-DAY FAMILY: DDoS
==============================================================================

[1] Verifying A7 state
------------------------------------------------------------------------------
Fold-1 preprocessing independently verified: True

[2] Loading frozen training-only parameters
------------------------------------------------------------------------------
Frozen retained features: 75
Frozen parameters valid: True

[3] Selecting Fold-1 non-training partitions
------------------------------------------------------------------------------
Source ranges to process: 54

Expected rows:
  development_validation     : 1,339,934
  known_test                 : 1,326,235
  benign_test                : 13,727
  zero_day_attack_test       : 30,918,665

[4] Frozen preprocessing policy
------------------------------------------------------------------------------
Imputation refitted here       : False
Scaler mean refitted here      : False
Scaler std refitted here       : False
Feature selection refitted here: False
Zero-variance fitting here     : False
All parameters source          : Fold-1 development_train

[5] Applying frozen preprocessing
------------------------------------------------------------------------------

------------------------------------------------------------------------------
01/54
Partition: development_validation
Class    : Backdoor_Malware
Family   : Web
Rows     : 405
Processed rows       : 405
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 5.828771e+01
Max |Z| feature     : Bwd Packet Length Max
Status              : PASS

------------------------------------------------------------------------------
02/54
Partition: known_test
Class    : Backdoor_Malware
Family   : Web
Rows     : 406
Processed rows       : 406
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 4.863623e+01
Max |Z| feature     : Fwd Packet Length Max
Status              : PASS

------------------------------------------------------------------------------
03/54
Partition: development_validation
Class    : Benign_Final
Family   : Benign
Rows     : 13,725
Processed rows       : 13,725
Raw non-finite values: 20
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.483280e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
04/54
Partition: benign_test
Class    : Benign_Final
Family   : Benign
Rows     : 13,727
Processed rows       : 13,727
Raw non-finite values: 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.473136e+02
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
05/54
Partition: development_validation
Class    : BrowserHijacking
Family   : Web
Rows     : 492
Processed rows       : 492
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 5.495628e+01
Max |Z| feature     : Active Min
Status              : PASS

------------------------------------------------------------------------------
06/54
Partition: known_test
Class    : BrowserHijacking
Family   : Web
Rows     : 494
Processed rows       : 494
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.224962e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
07/54
Partition: development_validation
Class    : CommandInjection
Family   : Web
Rows     : 577
Processed rows       : 577
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 4.723188e+01
Max |Z| feature     : Packet Length Variance
Status              : PASS

------------------------------------------------------------------------------
08/54
Partition: known_test
Class    : CommandInjection
Family   : Web
Rows     : 578
Processed rows       : 578
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.610558e+02
Max |Z| feature     : Bwd Header Length
Status              : PASS

------------------------------------------------------------------------------
09/54
Partition: zero_day_attack_test
Class    : DDoS-ACK_Fragmentation
Family   : DDoS
Rows     : 37,296
Processed rows       : 37,296
Raw non-finite values: 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 8.433646e+05
Max |Z| feature     : ECE Flag Count
Status              : PASS

------------------------------------------------------------------------------
10/54
Partition: zero_day_attack_test
Class    : DDoS-HTTP_Flood
Family   : DDoS
Rows     : 513,672
Processed rows       : 513,672
Raw non-finite values: 2,300
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.138723e+03
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
11/54
Partition: zero_day_attack_test
Class    : DDoS-ICMP_Flood
Family   : DDoS
Rows     : 7,834
Processed rows       : 7,834
Raw non-finite values: 58
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 4.718098e+04
Max |Z| feature     : Subflow Bwd Packets
Status              : PASS

------------------------------------------------------------------------------
12/54
Partition: zero_day_attack_test
Class    : DDoS-ICMP_Fragmentation
Family   : DDoS
Rows     : 25,106
Processed rows       : 25,106
Raw non-finite values: 44
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.064469e+03
Max |Z| feature     : Subflow Fwd Packets
Status              : PASS

------------------------------------------------------------------------------
13/54
Partition: zero_day_attack_test
Class    : DDoS-PSHACK_Flood
Family   : DDoS
Rows     : 5,007,067
Processed rows       : 5,007,067
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.918978e+02
Max |Z| feature     : ECE Flag Count
Status              : PASS

------------------------------------------------------------------------------
14/54
Partition: zero_day_attack_test
Class    : DDoS-RSTFINFlood
Family   : DDoS
Rows     : 12,968,618
Processed rows       : 12,968,618
Raw non-finite values: 8
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.876422e+02
Max |Z| feature     : ECE Flag Count
Status              : PASS

------------------------------------------------------------------------------
15/54
Partition: zero_day_attack_test
Class    : DDoS-SYN_Flood
Family   : DDoS
Rows     : 6,366,353
Processed rows       : 6,366,353
Raw non-finite values: 324
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.224962e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
16/54
Partition: zero_day_attack_test
Class    : DDoS-SlowLoris
Family   : DDoS
Rows     : 196,578
Processed rows       : 196,578
Raw non-finite values: 66
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.164901e+03
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
17/54
Partition: zero_day_attack_test
Class    : DDoS-SynonymousIP_Flood
Family   : DDoS
Rows     : 799,351
Processed rows       : 799,351
Raw non-finite values: 6
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.918978e+02
Max |Z| feature     : ECE Flag Count
Status              : PASS

------------------------------------------------------------------------------
18/54
Partition: zero_day_attack_test
Class    : DDoS-TCP_Flood
Family   : DDoS
Rows     : 4,945,887
Processed rows       : 4,945,887
Raw non-finite values: 246
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.483280e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
19/54
Partition: zero_day_attack_test
Class    : DDoS-UDP_Flood
Family   : DDoS
Rows     : 41,146
Processed rows       : 41,146
Raw non-finite values: 262
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.270913e+03
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
20/54
Partition: zero_day_attack_test
Class    : DDoS-UDP_Fragmentation
Family   : DDoS
Rows     : 9,757
Processed rows       : 9,757
Raw non-finite values: 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 3.795661e+02
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
21/54
Partition: development_validation
Class    : DNS_Spoofing
Family   : Spoofing
Rows     : 11,240
Processed rows       : 11,240
Raw non-finite values: 18
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 6.544790e+02
Max |Z| feature     : Subflow Fwd Bytes
Status              : PASS

------------------------------------------------------------------------------
22/54
Partition: known_test
Class    : DNS_Spoofing
Family   : Spoofing
Rows     : 11,242
Processed rows       : 11,242
Raw non-finite values: 14
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.209939e+02
Max |Z| feature     : CWR Flag Count
Status              : PASS

------------------------------------------------------------------------------
23/54
Partition: development_validation
Class    : DictionaryBruteForce
Family   : BruteForce
Rows     : 1,273
Processed rows       : 1,273
Raw non-finite values: 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 7.365283e+01
Max |Z| feature     : CWR Flag Count
Status              : PASS

------------------------------------------------------------------------------
24/54
Partition: known_test
Class    : DictionaryBruteForce
Family   : BruteForce
Rows     : 1,274
Processed rows       : 1,274
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.483280e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
25/54
Partition: development_validation
Class    : DoS-HTTP_Flood
Family   : DoS
Rows     : 144,833
Processed rows       : 144,833
Raw non-finite values: 180
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 6.112332e+01
Max |Z| feature     : Bwd Packet Length Min
Status              : PASS

------------------------------------------------------------------------------
26/54
Partition: known_test
Class    : DoS-HTTP_Flood
Family   : DoS
Rows     : 144,834
Processed rows       : 144,834
Raw non-finite values: 24,082
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 4.634438e+02
Max |Z| feature     : Flow Bytes/s
Status              : PASS

------------------------------------------------------------------------------
27/54
Partition: development_validation
Class    : DoS-SYN_Flood
Family   : DoS
Rows     : 599,566
Processed rows       : 599,566
Raw non-finite values: 108
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 5.826252e+01
Max |Z| feature     : Active Std
Status              : PASS

------------------------------------------------------------------------------
28/54
Partition: known_test
Class    : DoS-SYN_Flood
Family   : DoS
Rows     : 599,567
Processed rows       : 599,567
Raw non-finite values: 66
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.224962e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
29/54
Partition: development_validation
Class    : DoS-TCP_Flood
Family   : DoS
Rows     : 245,710
Processed rows       : 245,710
Raw non-finite values: 660
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.365808e+03
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
30/54
Partition: known_test
Class    : DoS-TCP_Flood
Family   : DoS
Rows     : 245,711
Processed rows       : 245,711
Raw non-finite values: 818
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.293445e+02
Max |Z| feature     : ECE Flag Count
Status              : PASS

------------------------------------------------------------------------------
31/54
Partition: development_validation
Class    : DoS-UDP_Flood
Family   : DoS
Rows     : 140,101
Processed rows       : 140,101
Raw non-finite values: 68
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.483280e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
32/54
Partition: known_test
Class    : DoS-UDP_Flood
Family   : DoS
Rows     : 140,102
Processed rows       : 140,102
Raw non-finite values: 34
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 4.807810e+12
Max |Z| feature     : Bwd IAT Std
Status              : PASS

------------------------------------------------------------------------------
33/54
Partition: development_validation
Class    : MITM-ArpSpoofing
Family   : Spoofing
Rows     : 10,927
Processed rows       : 10,927
Raw non-finite values: 10
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.062538e+03
Max |Z| feature     : Subflow Bwd Bytes
Status              : PASS

------------------------------------------------------------------------------
34/54
Partition: known_test
Class    : MITM-ArpSpoofing
Family   : Spoofing
Rows     : 10,929
Processed rows       : 10,929
Raw non-finite values: 22
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.967089e+03
Max |Z| feature     : Subflow Bwd Bytes
Status              : PASS

------------------------------------------------------------------------------
35/54
Partition: development_validation
Class    : Mirai-greeth_flood
Family   : Mirai
Rows     : 773
Processed rows       : 773
Raw non-finite values: 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 5.467524e+02
Max |Z| feature     : Total Fwd Packet
Status              : PASS

------------------------------------------------------------------------------
36/54
Partition: known_test
Class    : Mirai-greeth_flood
Family   : Mirai
Rows     : 774
Processed rows       : 774
Raw non-finite values: 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 5.342613e+02
Max |Z| feature     : Subflow Fwd Packets
Status              : PASS

------------------------------------------------------------------------------
37/54
Partition: development_validation
Class    : Mirai-greip_flood
Family   : Mirai
Rows     : 1,560
Processed rows       : 1,560
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 6.680642e+02
Max |Z| feature     : Subflow Fwd Packets
Status              : PASS

------------------------------------------------------------------------------
38/54
Partition: known_test
Class    : Mirai-greip_flood
Family   : Mirai
Rows     : 1,561
Processed rows       : 1,561
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 9.214404e+02
Max |Z| feature     : Subflow Fwd Packets
Status              : PASS

------------------------------------------------------------------------------
39/54
Partition: development_validation
Class    : Mirai-udpplain
Family   : Mirai
Rows     : 1,118
Processed rows       : 1,118
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 5.307014e+01
Max |Z| feature     : Fwd Packet Length Max
Status              : PASS

------------------------------------------------------------------------------
40/54
Partition: known_test
Class    : Mirai-udpplain
Family   : Mirai
Rows     : 1,119
Processed rows       : 1,119
Raw non-finite values: 2
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 3.602656e+02
Max |Z| feature     : Fwd Act Data Pkts
Status              : PASS

------------------------------------------------------------------------------
41/54
Partition: development_validation
Class    : Recon-HostDiscovery
Family   : Recon
Rows     : 49,497
Processed rows       : 49,497
Raw non-finite values: 28
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.224962e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
42/54
Partition: known_test
Class    : Recon-HostDiscovery
Family   : Recon
Rows     : 49,499
Processed rows       : 49,499
Raw non-finite values: 32
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 2.224962e+02
Max |Z| feature     : Bwd Packets/s
Status              : PASS

------------------------------------------------------------------------------
43/54
Partition: development_validation
Class    : Recon-OSScan
Family   : Recon
Rows     : 23,802
Processed rows       : 23,802
Raw non-finite values: 8
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.879548e+02
Max |Z| feature     : Fwd URG Flags
Status              : PASS

------------------------------------------------------------------------------
44/54
Partition: known_test
Class    : Recon-OSScan
Family   : Recon
Rows     : 23,803
Processed rows       : 23,803
Raw non-finite values: 62
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.879548e+02
Max |Z| feature     : Fwd URG Flags
Status              : PASS

------------------------------------------------------------------------------
45/54
Partition: development_validation
Class    : Recon-PingSweep
Family   : Recon
Rows     : 292
Processed rows       : 292
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 3.976843e+01
Max |Z| feature     : Fwd Packet Length Max
Status              : PASS

------------------------------------------------------------------------------
46/54
Partition: known_test
Class    : Recon-PingSweep
Family   : Recon
Rows     : 293
Processed rows       : 293
Raw non-finite values: 0
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 3.234679e+01
Max |Z| feature     : Bwd Packet Length Mean
Status              : PASS

------------------------------------------------------------------------------
47/54
Partition: development_validation
Class    : Recon-PortScan
Family   : Recon
Rows     : 26,257
Processed rows       : 26,257
Raw non-finite values: 22
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.841586e+02
Max |Z| feature     : CWR Flag Count
Status              : PASS

------------------------------------------------------------------------------
48/54
Partition: known_test
Class    : Recon-PortScan
Family   : Recon
Rows     : 26,259
Processed rows       : 26,259
Raw non-finite values: 28
Float64 non-finite out: 0
Float32 non-finite out: 0
Max |Z|             : 1.639552e+02
Max |Z| feature     : Bwd Bulk Rate Avg
Status              : PASS

------------------------------------------------------------------------------
49/54

,partition,source_ranges,expected_rows,processed_rows,raw_nonfinite_values,post_float64_nonfinite_values,post_float32_nonfinite_values,maximum_absolute_standardized_value
0,benign_test,1,13727,13727,10,0,0,2.473136e+02
1,development_validation,21,1339934,1339934,1516,0,0,2.365808e+03
2,known_test,20,1326235,1326235,25560,0,0,4.807810e+12
3,zero_day_attack_test,12,30918665,30918665,3334,0,0,8.433646e+05

[7] Largest standardized values by source range
------------------------------------------------------------------------------

,partition,source_attack_class,research_family,maximum_absolute_standardized_value,maximum_z_feature,value_used_at_maximum_z,maximum_z_value_was_imputed
0,known_test,DoS-UDP_Flood,DoS,4.807810e+12,Bwd IAT Std,1.065023e+19,False
1,zero_day_attack_test,DDoS-ACK_Fragmentation,DDoS,8.433646e+05,ECE Flag Count,4.044700e+04,False
2,zero_day_attack_test,DDoS-ICMP_Flood,DDoS,4.718098e+04,Subflow Bwd Packets,6.104980e+05,False
3,known_test,MITM-ArpSpoofing,Spoofing,2.967089e+03,Subflow Bwd Bytes,7.053720e+07,False
4,development_validation,DoS-TCP_Flood,DoS,2.365808e+03,Bwd Bulk Rate Avg,1.446000e+09,False
5,zero_day_attack_test,DDoS-UDP_Flood,DDoS,2.270913e+03,Bwd Bulk Rate Avg,1.388000e+09,False
6,zero_day_attack_test,DDoS-SlowLoris,DDoS,1.164901e+03,Bwd Bulk Rate Avg,7.120000e+08,False
7,zero_day_attack_test,DDoS-HTTP_Flood,DDoS,1.138723e+03,Bwd Bulk Rate Avg,6.960000e+08,False
8,zero_day_attack_test,DDoS-ICMP_Fragmentation,DDoS,1.064469e+03,Subflow Fwd Packets,4.361300e+04,False
9,development_validation,MITM-ArpSpoofing,Spoofing,1.062538e+03,Subflow Bwd Bytes,2.525998e+07,False
10,known_test,Mirai-greip_flood,Mirai,9.214404e+02,Subflow Fwd Packets,3.775300e+04,False
11,development_validation,Mirai-greip_flood,Mirai,6.680642e+02,Subflow Fwd Packets,2.737200e+04,False
12,development_validation,DNS_Spoofing,Spoofing,6.544790e+02,Subflow Fwd Bytes,1.223541e+07,False
13,development_validation,Mirai-greeth_flood,Mirai,5.467524e+02,Total Fwd Packet,1.617400e+05,False
14,known_test,Mirai-greeth_flood,Mirai,5.342613e+02,Subflow Fwd Packets,2.189000e+04,False

[8] Partition row-count validation
------------------------------------------------------------------------------
development_validation      expected=   1,339,934 processed=   1,339,934 match=True
known_test                  expected=   1,326,235 processed=   1,326,235 match=True
benign_test                 expected=      13,727 processed=      13,727 match=True
zero_day_attack_test        expected=  30,918,665 processed=  30,918,665 match=True

[9] Frozen transformation validity
------------------------------------------------------------------------------
Raw non-finite values encountered : 30,420
Non-finite after float64 transform: 0
Non-finite after float32 transform: 0
All source ranges passed          : True

[10] Leakage-safety verification
------------------------------------------------------------------------------
DDoS rows outside zero-day test: 0
Non-DDoS rows in zero-day test : 0
Parameters refitted             : False
Leakage-safe                    : True

[11] Saving A8 artifacts
------------------------------------------------------------------------------

[12] Recovery Step A8 validation
------------------------------------------------------------------------------
Frozen parameters valid          : True
All partition row counts exact   : True
All float64 transformed finite   : True
All float32 transformed finite   : True
All source ranges passed         : True
Held-out isolation preserved     : True
Artifacts backed up to Drive     : True

Largest observed standardized value:
  Partition : known_test
  Class     : DoS-UDP_Flood
  Feature   : Bwd IAT Std
  Max |Z|   : 4.807810e+12
  Raw/value used: 1.0650232656628044e+19

==============================================================================
✅ RECOVERY STEP A8 PASSED — Frozen Fold-1 preprocessing was safely applied to all validation and test partitions.
==============================================================================

# Do only Recovery Step A9 — Diagnose Bwd IAT Std

In [ ]:
# ======================================================================
# RECOVERY STEP A9
# DIAGNOSE EXTREME Bwd IAT Std VALUE
# Fold 1 — DoS-UDP_Flood known_test
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP A9 — DIAGNOSE EXTREME STANDARDIZED VALUE")
print("TARGET: DoS-UDP_Flood / known_test / Bwd IAT Std")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A8 STATE
# ======================================================================

print("\n[1] Verifying A8 state")
print("-" * 78)

required_variables = [
    "STEP_9_3_VALID",
    "LOAFO_SPLIT_MANIFEST"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A8."
    )

if not STEP_9_3_VALID:
    raise RuntimeError(
        "Recovery Step A8 did not pass."
    )

print(
    "A8 valid:",
    STEP_9_3_VALID
)


# ======================================================================
# 2 — LOAD FROZEN TRAINING PARAMETERS
# ======================================================================

print("\n[2] Loading Fold-1 training-only parameters")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

FOLD_PREPROCESSING_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

PARAMETERS_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

params = pd.read_csv(
    PARAMETERS_PATH
)

TARGET_FEATURE = "Bwd IAT Std"

target_param = (
    params[
        params["feature"] == TARGET_FEATURE
    ]
    .iloc[0]
)

TRAIN_IMPUTATION = float(
    target_param["imputation_value"]
)

TRAIN_MEAN = float(
    target_param["scaler_mean"]
)

TRAIN_STD = float(
    target_param["scaler_std"]
)

TRAIN_MIN = float(
    target_param["finite_min"]
)

TRAIN_MAX = float(
    target_param["finite_max"]
)


print(
    "Feature:",
    TARGET_FEATURE
)

print(
    "Training finite min :",
    f"{TRAIN_MIN:.6e}"
)

print(
    "Training finite max :",
    f"{TRAIN_MAX:.6e}"
)

print(
    "Training mean       :",
    f"{TRAIN_MEAN:.6e}"
)

print(
    "Training std        :",
    f"{TRAIN_STD:.6e}"
)

print(
    "Training imputation :",
    f"{TRAIN_IMPUTATION:.6e}"
)


if (
    not np.isfinite(TRAIN_MEAN)
    or
    not np.isfinite(TRAIN_STD)
    or
    TRAIN_STD <= 0
):
    raise RuntimeError(
        "Frozen training parameters are invalid."
    )


# ======================================================================
# 3 — SELECT EXACT DoS-UDP_Flood KNOWN-TEST RANGE
# ======================================================================

print("\n[3] Selecting exact known-test range")
print("-" * 78)

target_manifest = (
    LOAFO_SPLIT_MANIFEST[
        (LOAFO_SPLIT_MANIFEST["fold_id"] == 1)
        &
        (
            LOAFO_SPLIT_MANIFEST["partition"]
            ==
            "known_test"
        )
        &
        (
            LOAFO_SPLIT_MANIFEST["source_attack_class"]
            ==
            "DoS-UDP_Flood"
        )
    ]
    .copy()
)


if len(target_manifest) != 1:
    raise RuntimeError(
        "Expected exactly one DoS-UDP_Flood known-test range."
    )


target_row = target_manifest.iloc[0]

START_ROW = int(
    target_row["start_row"]
)

END_ROW = int(
    target_row["end_row_exclusive"]
)

EXPECTED_ROWS = int(
    target_row["row_count"]
)

PARQUET_PATH = Path(
    target_row["parquet_path"]
)


print(
    "Start row:",
    f"{START_ROW:,}"
)

print(
    "End row exclusive:",
    f"{END_ROW:,}"
)

print(
    "Expected rows:",
    f"{EXPECTED_ROWS:,}"
)

print(
    "Parquet:",
    PARQUET_PATH
)


if EXPECTED_ROWS != 140_102:
    raise RuntimeError(
        "Unexpected known-test row count."
    )


# ======================================================================
# 4 — READ ONLY TIMESTAMP + TARGET FEATURE
# ======================================================================

print("\n[4] Reading target range")
print("-" * 78)

parquet_file = pq.ParquetFile(
    PARQUET_PATH
)

BATCH_SIZE = 50_000

value_parts = []
timestamp_parts = []
absolute_index_parts = []

absolute_position = 0
processed_rows = 0


for batch in parquet_file.iter_batches(
    columns=[
        "Timestamp",
        TARGET_FEATURE
    ],
    batch_size=BATCH_SIZE
):

    batch_rows = batch.num_rows

    batch_start = absolute_position
    batch_end = (
        batch_start
        +
        batch_rows
    )

    absolute_position = batch_end


    if batch_end <= START_ROW:
        continue

    if batch_start >= END_ROW:
        break


    local_start = max(
        0,
        START_ROW - batch_start
    )

    local_end = min(
        batch_rows,
        END_ROW - batch_start
    )


    if local_end <= local_start:
        continue


    sliced = batch.slice(
        local_start,
        local_end - local_start
    )


    timestamps = (
        sliced
        .column(0)
        .to_pandas()
        .astype("string")
        .to_numpy()
    )


    values = (
        sliced
        .column(1)
        .to_pandas()
        .to_numpy(
            dtype=np.float64
        )
    )


    absolute_indices = np.arange(
        batch_start + local_start,
        batch_start + local_end,
        dtype=np.int64
    )


    timestamp_parts.append(
        timestamps
    )

    value_parts.append(
        values
    )

    absolute_index_parts.append(
        absolute_indices
    )

    processed_rows += len(
        values
    )


VALUES_RAW = np.concatenate(
    value_parts
)

TIMESTAMPS = np.concatenate(
    timestamp_parts
)

ABSOLUTE_ROW_INDICES = np.concatenate(
    absolute_index_parts
)


print(
    "Processed rows:",
    f"{processed_rows:,}"
)


if processed_rows != EXPECTED_ROWS:
    raise RuntimeError(
        "Target-range row count mismatch."
    )


# ======================================================================
# 5 — APPLY THE SAME FROZEN TRANSFORMATION
# ======================================================================

print("\n[5] Applying frozen Bwd IAT Std transformation")
print("-" * 78)

VALUES_USED = VALUES_RAW.copy()

nonfinite_mask = (
    ~np.isfinite(
        VALUES_USED
    )
)

NONFINITE_COUNT = int(
    nonfinite_mask.sum()
)


VALUES_USED[
    nonfinite_mask
] = TRAIN_IMPUTATION


Z = (
    VALUES_USED
    -
    TRAIN_MEAN
) / TRAIN_STD


if not np.isfinite(Z).all():
    raise RuntimeError(
        "Non-finite standardized Bwd IAT Std values detected."
    )


MAX_POSITION = int(
    np.argmax(
        np.abs(Z)
    )
)


MAX_RAW_VALUE = float(
    VALUES_RAW[
        MAX_POSITION
    ]
)

MAX_USED_VALUE = float(
    VALUES_USED[
        MAX_POSITION
    ]
)

MAX_Z = float(
    Z[
        MAX_POSITION
    ]
)

MAX_ABS_Z = float(
    abs(MAX_Z)
)

MAX_ABSOLUTE_SOURCE_ROW = int(
    ABSOLUTE_ROW_INDICES[
        MAX_POSITION
    ]
)

MAX_PARTITION_OFFSET = int(
    MAX_ABSOLUTE_SOURCE_ROW
    -
    START_ROW
)

MAX_TIMESTAMP = str(
    TIMESTAMPS[
        MAX_POSITION
    ]
)


print(
    "Raw non-finite count:",
    NONFINITE_COUNT
)

print(
    "Maximum raw value:",
    f"{MAX_RAW_VALUE:.15e}"
)

print(
    "Maximum standardized value:",
    f"{MAX_Z:.15e}"
)

print(
    "Maximum |Z|:",
    f"{MAX_ABS_Z:.15e}"
)

print(
    "Source absolute row:",
    f"{MAX_ABSOLUTE_SOURCE_ROW:,}"
)

print(
    "Known-test offset:",
    f"{MAX_PARTITION_OFFSET:,}"
)

print(
    "Timestamp:",
    MAX_TIMESTAMP
)


# ======================================================================
# 6 — COMPARE WITH TRAINING RANGE
# ======================================================================

print("\n[6] Comparing extreme value with training distribution")
print("-" * 78)


if TRAIN_MAX != 0:
    MAX_TO_TRAIN_MAX_RATIO = (
        abs(MAX_USED_VALUE)
        /
        abs(TRAIN_MAX)
    )
else:
    MAX_TO_TRAIN_MAX_RATIO = np.inf


print(
    "Training maximum:",
    f"{TRAIN_MAX:.15e}"
)

print(
    "Known-test maximum:",
    f"{MAX_USED_VALUE:.15e}"
)

print(
    "|test max| / |training max|:",
    f"{MAX_TO_TRAIN_MAX_RATIO:.6e}"
)


# ======================================================================
# 7 — DISTRIBUTION DIAGNOSTICS
# ======================================================================

print("\n[7] Known-test distribution diagnostics")
print("-" * 78)

finite_raw = VALUES_RAW[
    np.isfinite(
        VALUES_RAW
    )
]


quantile_levels = [
    0.50,
    0.90,
    0.95,
    0.99,
    0.999,
    0.9999,
    1.0
]


quantiles = np.quantile(
    finite_raw,
    quantile_levels
)


for q, value in zip(
    quantile_levels,
    quantiles
):

    print(
        f"q={q:<7} : "
        f"{value:.15e}"
    )


thresholds = [
    10,
    100,
    1_000,
    1_000_000,
    1_000_000_000,
    1_000_000_000_000
]


print("\nAbsolute Z threshold counts:")

for threshold in thresholds:

    count = int(
        (
            np.abs(Z)
            >
            threshold
        ).sum()
    )

    print(
        f"  |Z| > {threshold:>13,}: "
        f"{count:,}"
    )


# ======================================================================
# 8 — TOP 20 EXTREME VALUES
# ======================================================================

print("\n[8] Top 20 Bwd IAT Std standardized values")
print("-" * 78)

top_count = min(
    20,
    len(Z)
)


top_indices = np.argpartition(
    np.abs(Z),
    -top_count
)[
    -top_count:
]


top_indices = top_indices[
    np.argsort(
        np.abs(
            Z[top_indices]
        )
    )[::-1]
]


TOP_EXTREMES = pd.DataFrame({

    "source_absolute_row":
        ABSOLUTE_ROW_INDICES[
            top_indices
        ],

    "known_test_offset":
        (
            ABSOLUTE_ROW_INDICES[
                top_indices
            ]
            -
            START_ROW
        ),

    "timestamp":
        TIMESTAMPS[
            top_indices
        ],

    "raw_Bwd_IAT_Std":
        VALUES_RAW[
            top_indices
        ],

    "value_used":
        VALUES_USED[
            top_indices
        ],

    "standardized_z":
        Z[
            top_indices
        ],

    "absolute_z":
        np.abs(
            Z[
                top_indices
            ]
        ),

    "was_imputed":
        nonfinite_mask[
            top_indices
        ]
})


display(
    TOP_EXTREMES
)


# ======================================================================
# 9 — LOCAL NEIGHBORHOOD AROUND THE MAXIMUM
# ======================================================================

print("\n[9] Rows around the maximum")
print("-" * 78)

neighborhood_start = max(
    0,
    MAX_POSITION - 5
)

neighborhood_end = min(
    len(Z),
    MAX_POSITION + 6
)


NEIGHBORHOOD = pd.DataFrame({

    "source_absolute_row":
        ABSOLUTE_ROW_INDICES[
            neighborhood_start:
            neighborhood_end
        ],

    "known_test_offset":
        (
            ABSOLUTE_ROW_INDICES[
                neighborhood_start:
                neighborhood_end
            ]
            -
            START_ROW
        ),

    "timestamp":
        TIMESTAMPS[
            neighborhood_start:
            neighborhood_end
        ],

    "raw_Bwd_IAT_Std":
        VALUES_RAW[
            neighborhood_start:
            neighborhood_end
        ],

    "standardized_z":
        Z[
            neighborhood_start:
            neighborhood_end
        ]
})


display(
    NEIGHBORHOOD
)


# ======================================================================
# 10 — SAVE DIAGNOSTIC ARTIFACTS
# ======================================================================

print("\n[10] Saving diagnostic artifacts")
print("-" * 78)

DIAGNOSTIC_DIR = (
    FOLD_PREPROCESSING_DIR
    / "diagnostics"
)

DIAGNOSTIC_DIR.mkdir(
    parents=True,
    exist_ok=True
)


TOP_EXTREMES_PATH = (
    DIAGNOSTIC_DIR
    / "Bwd_IAT_Std_top_extremes_DoS_UDP_known_test.csv"
)


NEIGHBORHOOD_PATH = (
    DIAGNOSTIC_DIR
    / "Bwd_IAT_Std_extreme_neighborhood.csv"
)


SUMMARY_PATH = (
    DIAGNOSTIC_DIR
    / "Bwd_IAT_Std_extreme_summary.json"
)


TOP_EXTREMES.to_csv(
    TOP_EXTREMES_PATH,
    index=False
)


NEIGHBORHOOD.to_csv(
    NEIGHBORHOOD_PATH,
    index=False
)


summary = {

    "fold_id":
        1,

    "partition":
        "known_test",

    "source_attack_class":
        "DoS-UDP_Flood",

    "feature":
        TARGET_FEATURE,

    "training_finite_min":
        TRAIN_MIN,

    "training_finite_max":
        TRAIN_MAX,

    "training_mean":
        TRAIN_MEAN,

    "training_std":
        TRAIN_STD,

    "maximum_raw_value":
        MAX_RAW_VALUE,

    "maximum_value_used":
        MAX_USED_VALUE,

    "maximum_standardized_z":
        MAX_Z,

    "maximum_absolute_z":
        MAX_ABS_Z,

    "maximum_source_absolute_row":
        MAX_ABSOLUTE_SOURCE_ROW,

    "maximum_partition_offset":
        MAX_PARTITION_OFFSET,

    "maximum_timestamp":
        MAX_TIMESTAMP,

    "maximum_was_imputed":
        bool(
            nonfinite_mask[
                MAX_POSITION
            ]
        ),

    "test_max_to_training_max_ratio":
        float(
            MAX_TO_TRAIN_MAX_RATIO
        ),

    "known_test_rows":
        int(
            EXPECTED_ROWS
        ),

    "known_test_nonfinite_count":
        NONFINITE_COUNT
}


with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        summary,
        file,
        indent=4
    )


# ======================================================================
# 11 — BACK UP DIAGNOSTICS TO GOOGLE DRIVE
# ======================================================================

DRIVE_DIAGNOSTIC_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/preprocessing/"
    "fold_01_DDoS/diagnostics"
)


DRIVE_DIAGNOSTIC_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in [
    TOP_EXTREMES_PATH,
    NEIGHBORHOOD_PATH,
    SUMMARY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_DIAGNOSTIC_DIR
        / source_path.name
    )


DRIVE_DIAGNOSTICS_SAVED = all(

    (
        DRIVE_DIAGNOSTIC_DIR
        /
        path.name
    ).exists()

    for path in [
        TOP_EXTREMES_PATH,
        NEIGHBORHOOD_PATH,
        SUMMARY_PATH
    ]
)


# ======================================================================
# 12 — FINAL DIAGNOSTIC STATUS
# ======================================================================

A9_VALID = bool(

    processed_rows == EXPECTED_ROWS

    and
    np.isfinite(MAX_ABS_Z)

    and
    MAX_ABS_Z > 1e12

    and
    TARGET_FEATURE == "Bwd IAT Std"

    and
    DRIVE_DIAGNOSTICS_SAVED
)


print("\n[11] Recovery Step A9 summary")
print("-" * 78)

print(
    "Rows inspected              :",
    f"{processed_rows:,}"
)

print(
    "Feature                     :",
    TARGET_FEATURE
)

print(
    "Training maximum            :",
    f"{TRAIN_MAX:.6e}"
)

print(
    "Extreme known-test value    :",
    f"{MAX_USED_VALUE:.6e}"
)

print(
    "Extreme |Z|                 :",
    f"{MAX_ABS_Z:.6e}"
)

print(
    "Extreme value was imputed   :",
    bool(
        nonfinite_mask[
            MAX_POSITION
        ]
    )
)

print(
    "Diagnostics backed up       :",
    DRIVE_DIAGNOSTICS_SAVED
)


print("\n" + "=" * 78)

if A9_VALID:

    print(
        "✅ RECOVERY STEP A9 COMPLETE — "
        "The extreme Bwd IAT Std value has been isolated "
        "without changing preprocessing."
    )

else:

    print(
        "❌ RECOVERY STEP A9 FAILED — "
        "Do not change preprocessing yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A9 — DIAGNOSE EXTREME STANDARDIZED VALUE
TARGET: DoS-UDP_Flood / known_test / Bwd IAT Std
==============================================================================

[1] Verifying A8 state
------------------------------------------------------------------------------
A8 valid: True

[2] Loading Fold-1 training-only parameters
------------------------------------------------------------------------------
Feature: Bwd IAT Std
Training finite min : 0.000000e+00
Training finite max : 8.409412e+07
Training mean       : 6.836156e+05
Training std        : 2.215194e+06
Training imputation : 6.836156e+05

[3] Selecting exact known-test range
------------------------------------------------------------------------------
Start row: 793,907
End row exclusive: 934,009
Expected rows: 140,102
Parquet: /content/ZeroDay_IoT_Research/dataset/chronological_parquet/DoS-UDP_Flood.parquet

[4] Reading target range
------------------------------------------------------------------------------
Processed rows: 140,102

[5] Applying frozen Bwd IAT Std transformation
------------------------------------------------------------------------------
Raw non-finite count: 0
Maximum raw value: 1.065023265662804e+19
Maximum standardized value: 4.807809865461043e+12
Maximum |Z|: 4.807809865461043e+12
Source absolute row: 867,733
Known-test offset: 73,826
Timestamp: 10/08/2022 01:17:55 PM

[6] Comparing extreme value with training distribution
------------------------------------------------------------------------------
Training maximum: 8.409412493572515e+07
Known-test maximum: 1.065023265662804e+19
|test max| / |training max|: 1.266466e+11

[7] Known-test distribution diagnostics
------------------------------------------------------------------------------
q=0.5     : 0.000000000000000e+00
q=0.9     : 0.000000000000000e+00
q=0.95    : 0.000000000000000e+00
q=0.99    : 0.000000000000000e+00
q=0.999   : 2.585743740940660e+06
q=0.9999  : 3.399817952510709e+07
q=1.0     : 1.065023265662804e+19

Absolute Z threshold counts:
  |Z| >            10: 26
  |Z| >           100: 2
  |Z| >         1,000: 2
  |Z| >     1,000,000: 2
  |Z| > 1,000,000,000: 2
  |Z| > 1,000,000,000,000: 1

[8] Top 20 Bwd IAT Std standardized values
------------------------------------------------------------------------------

,source_absolute_row,known_test_offset,timestamp,raw_Bwd_IAT_Std,value_used,standardized_z,absolute_z,was_imputed
0,867733,73826,10/08/2022 01:17:55 PM,1.065023e+19,1.065023e+19,4.807810e+12,4.807810e+12,False
1,801361,7454,10/08/2022 01:16:03 PM,8.754437e+17,8.754437e+17,3.951995e+11,3.951995e+11,False
2,867148,73241,10/08/2022 01:16:29 PM,4.483171e+07,4.483171e+07,1.992967e+01,1.992967e+01,False
3,867485,73578,10/08/2022 01:17:10 PM,4.477302e+07,4.477302e+07,1.990318e+01,1.990318e+01,False
4,867403,73496,10/08/2022 01:16:59 PM,4.396408e+07,4.396408e+07,1.953800e+01,1.953800e+01,False
5,867818,73911,10/08/2022 01:18:03 PM,4.254110e+07,4.254110e+07,1.889563e+01,1.889563e+01,False
6,800476,6569,09/08/2022 07:48:45 PM,4.040548e+07,4.040548e+07,1.793155e+01,1.793155e+01,False
7,933475,139568,10/08/2022 01:18:17 PM,3.955915e+07,3.955915e+07,1.754949e+01,1.754949e+01,False
8,866964,73057,10/08/2022 01:16:10 PM,3.682628e+07,3.682628e+07,1.631580e+01,1.631580e+01,False
9,867055,73148,10/08/2022 01:16:18 PM,3.479595e+07,3.479595e+07,1.539925e+01,1.539925e+01,False
10,867277,73370,10/08/2022 01:16:44 PM,3.455332e+07,3.455332e+07,1.528972e+01,1.528972e+01,False
11,801316,7409,10/08/2022 01:16:00 PM,3.408708e+07,3.408708e+07,1.507925e+01,1.507925e+01,False
12,801357,7450,10/08/2022 01:16:03 PM,3.407678e+07,3.407678e+07,1.507460e+01,1.507460e+01,False
13,867006,73099,10/08/2022 01:16:14 PM,3.405219e+07,3.405219e+07,1.506350e+01,1.506350e+01,False
14,801358,7451,10/08/2022 01:16:03 PM,3.399863e+07,3.399863e+07,1.503932e+01,1.503932e+01,False
15,866965,73058,10/08/2022 01:16:10 PM,3.395412e+07,3.395412e+07,1.501923e+01,1.501923e+01,False
16,867084,73177,10/08/2022 01:16:20 PM,3.394379e+07,3.394379e+07,1.501456e+01,1.501456e+01,False
17,867040,73133,10/08/2022 01:16:17 PM,3.388336e+07,3.388336e+07,1.498728e+01,1.498728e+01,False
18,867607,73700,10/08/2022 01:17:28 PM,3.179319e+07,3.179319e+07,1.404373e+01,1.404373e+01,False
19,867225,73318,10/08/2022 01:16:39 PM,2.993873e+07,2.993873e+07,1.320657e+01,1.320657e+01,False

[9] Rows around the maximum
------------------------------------------------------------------------------

,source_absolute_row,known_test_offset,timestamp,raw_Bwd_IAT_Std,standardized_z
0,867728,73821,10/08/2022 01:17:54 PM,8.175049e+04,-2.716986e-01
1,867729,73822,10/08/2022 01:17:54 PM,0.000000e+00,-3.086030e-01
2,867730,73823,10/08/2022 01:17:54 PM,0.000000e+00,-3.086030e-01
3,867731,73824,10/08/2022 01:17:54 PM,0.000000e+00,-3.086030e-01
4,867732,73825,10/08/2022 01:17:54 PM,0.000000e+00,-3.086030e-01
5,867733,73826,10/08/2022 01:17:55 PM,1.065023e+19,4.807810e+12
6,867734,73827,10/08/2022 01:17:55 PM,0.000000e+00,-3.086030e-01
7,867735,73828,10/08/2022 01:17:55 PM,0.000000e+00,-3.086030e-01
8,867736,73829,10/08/2022 01:17:56 PM,7.238789e+04,-2.759251e-01
9,867737,73830,10/08/2022 01:17:56 PM,0.000000e+00,-3.086030e-01
10,867738,73831,10/08/2022 01:17:57 PM,7.272189e+04,-2.757743e-01

[10] Saving diagnostic artifacts
------------------------------------------------------------------------------

[11] Recovery Step A9 summary
------------------------------------------------------------------------------
Rows inspected              : 140,102
Feature                     : Bwd IAT Std
Training maximum            : 8.409412e+07
Extreme known-test value    : 1.065023e+19
Extreme |Z|                 : 4.807810e+12
Extreme value was imputed   : False
Diagnostics backed up       : True

==============================================================================
✅ RECOVERY STEP A9 COMPLETE — The extreme Bwd IAT Std value has been isolated without changing preprocessing.
==============================================================================

# Recovery Step A10 — Freeze preprocessing and build Fold-1 temporal-window manifest

In [ ]:
# ======================================================================
# RECOVERY STEP A10
# FREEZE FOLD-1 PREPROCESSING + BUILD TEMPORAL WINDOW MANIFEST
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("RECOVERY STEP A10 — BUILD FOLD-1 TEMPORAL WINDOW MANIFEST")
print("WINDOW = 8 | STRIDE = 8 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREVIOUS RECOVERY STATE
# ======================================================================

print("\n[1] Verifying recovered state")
print("-" * 78)

required_variables = [
    "STEP_9_3_VALID",
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun A8 if the runtime restarted."
    )

if not STEP_9_3_VALID:
    raise RuntimeError(
        "Fold-1 frozen preprocessing did not pass A8."
    )

print(
    "Frozen preprocessing valid:",
    STEP_9_3_VALID
)


# ======================================================================
# 2 — FREEZE PREPROCESSING DECISION
# ======================================================================

print("\n[2] Freezing preprocessing protocol")
print("-" * 78)

PREPROCESSING_FROZEN = True

INPUT_CLIPPING_ENABLED = False
TEST_DRIVEN_ROW_REMOVAL = False
TEST_DRIVEN_REFITTING = False

print(
    "Preprocessing frozen          :",
    PREPROCESSING_FROZEN
)

print(
    "Input clipping               :",
    INPUT_CLIPPING_ENABLED
)

print(
    "Test-driven row removal      :",
    TEST_DRIVEN_ROW_REMOVAL
)

print(
    "Test-driven parameter refit  :",
    TEST_DRIVEN_REFITTING
)

print(
    "Decision: preserve the training-only preprocessing exactly."
)


# ======================================================================
# 3 — TEMPORAL CONFIGURATION
# ======================================================================

print("\n[3] Temporal configuration")
print("-" * 78)

TEMPORAL_WINDOW = 8
TEMPORAL_STRIDE = 8

FOLD_ID = 1
HELD_OUT_FAMILY = "DDoS"

TIMESTAMP_USED_AS_MODEL_FEATURE = False


print(
    "Fold:",
    FOLD_ID
)

print(
    "Held-out family:",
    HELD_OUT_FAMILY
)

print(
    "Window length T:",
    TEMPORAL_WINDOW
)

print(
    "Stride:",
    TEMPORAL_STRIDE
)

print(
    "Timestamp used as model feature:",
    TIMESTAMP_USED_AS_MODEL_FEATURE
)


if TEMPORAL_WINDOW <= 0:
    raise RuntimeError(
        "Window length must be positive."
    )

if TEMPORAL_STRIDE <= 0:
    raise RuntimeError(
        "Stride must be positive."
    )


# ======================================================================
# 4 — SELECT EXACT FOLD-1 LOAFO RANGES
# ======================================================================

print("\n[4] Loading Fold-1 source/partition ranges")
print("-" * 78)

fold_manifest = (
    LOAFO_SPLIT_MANIFEST[
        LOAFO_SPLIT_MANIFEST[
            "fold_id"
        ] == FOLD_ID
    ]
    .copy()
    .reset_index(drop=True)
)


print(
    "Fold-1 manifest ranges:",
    len(fold_manifest)
)


if len(fold_manifest) != 75:
    raise RuntimeError(
        f"Expected 75 Fold-1 source ranges, "
        f"found {len(fold_manifest)}."
    )


# ======================================================================
# 5 — BUILD TEMPORAL WINDOW MANIFEST
# ======================================================================

print("\n[5] Building legal temporal-window ranges")
print("-" * 78)

window_records = []


for _, row in fold_manifest.iterrows():

    start_row = int(
        row["start_row"]
    )

    end_row = int(
        row["end_row_exclusive"]
    )

    row_count = int(
        row["row_count"]
    )


    # --------------------------------------------------------------
    # Number of complete windows fully contained in THIS range only.
    # No window may cross its range boundary.
    # --------------------------------------------------------------

    if row_count < TEMPORAL_WINDOW:

        window_count = 0

    else:

        window_count = (
            1
            +
            (
                row_count
                -
                TEMPORAL_WINDOW
            )
            //
            TEMPORAL_STRIDE
        )


    if window_count > 0:

        first_window_start = (
            start_row
        )

        first_window_end = (
            first_window_start
            +
            TEMPORAL_WINDOW
        )


        last_window_start = (

            start_row

            +

            (
                window_count
                -
                1
            )
            *
            TEMPORAL_STRIDE
        )


        last_window_end = (

            last_window_start

            +

            TEMPORAL_WINDOW
        )


        unused_tail_rows = (

            end_row
            -
            last_window_end
        )

    else:

        first_window_start = None
        first_window_end = None
        last_window_start = None
        last_window_end = None

        unused_tail_rows = (
            row_count
        )


    bounds_valid = bool(

        window_count >= 0

        and

        (
            window_count == 0

            or

            (
                first_window_start
                >=
                start_row

                and

                first_window_end
                <=
                end_row

                and

                last_window_start
                >=
                start_row

                and

                last_window_end
                <=
                end_row
            )
        )

        and

        unused_tail_rows >= 0
    )


    window_records.append({

        "fold_id":
            int(row["fold_id"]),

        "held_out_family":
            row["held_out_family"],

        "partition":
            row["partition"],

        "source_attack_class":
            row["source_attack_class"],

        "research_family":
            row["research_family"],

        "binary_target":
            int(row["binary_target"]),

        "parquet_path":
            row["parquet_path"],

        "partition_start_row":
            start_row,

        "partition_end_row_exclusive":
            end_row,

        "partition_row_count":
            row_count,

        "window_size":
            TEMPORAL_WINDOW,

        "stride":
            TEMPORAL_STRIDE,

        "window_count":
            int(window_count),

        "first_window_start":
            first_window_start,

        "first_window_end_exclusive":
            first_window_end,

        "last_window_start":
            last_window_start,

        "last_window_end_exclusive":
            last_window_end,

        "unused_tail_rows":
            int(unused_tail_rows),

        "window_bounds_valid":
            bounds_valid
    })


TEMPORAL_WINDOW_MANIFEST = pd.DataFrame(
    window_records
)


print(
    "Temporal manifest records:",
    len(TEMPORAL_WINDOW_MANIFEST)
)


# ======================================================================
# 6 — VALIDATE WINDOW BOUNDARIES
# ======================================================================

print("\n[6] Window-boundary validation")
print("-" * 78)


ALL_WINDOW_BOUNDS_VALID = bool(

    TEMPORAL_WINDOW_MANIFEST[
        "window_bounds_valid"
    ].all()
)


NEGATIVE_WINDOW_COUNTS = int(

    (
        TEMPORAL_WINDOW_MANIFEST[
            "window_count"
        ] < 0
    ).sum()
)


print(
    "All window bounds valid:",
    ALL_WINDOW_BOUNDS_VALID
)

print(
    "Negative window counts:",
    NEGATIVE_WINDOW_COUNTS
)


# ======================================================================
# 7 — STRICT PARTITION / FAMILY CHECKS
# ======================================================================

print("\n[7] Zero-day isolation checks")
print("-" * 78)


DDoS_OUTSIDE_ZERO_DAY_WINDOWS = int(

    TEMPORAL_WINDOW_MANIFEST.loc[
        (
            TEMPORAL_WINDOW_MANIFEST[
                "research_family"
            ] == HELD_OUT_FAMILY
        )
        &
        (
            TEMPORAL_WINDOW_MANIFEST[
                "partition"
            ]
            !=
            "zero_day_attack_test"
        ),
        "window_count"
    ].sum()
)


NON_DDoS_INSIDE_ZERO_DAY_WINDOWS = int(

    TEMPORAL_WINDOW_MANIFEST.loc[
        (
            TEMPORAL_WINDOW_MANIFEST[
                "research_family"
            ]
            !=
            HELD_OUT_FAMILY
        )
        &
        (
            TEMPORAL_WINDOW_MANIFEST[
                "partition"
            ]
            ==
            "zero_day_attack_test"
        ),
        "window_count"
    ].sum()
)


ZERO_DAY_WINDOW_ISOLATION_VALID = bool(

    DDoS_OUTSIDE_ZERO_DAY_WINDOWS == 0

    and

    NON_DDoS_INSIDE_ZERO_DAY_WINDOWS == 0
)


print(
    "DDoS windows outside zero-day:",
    DDoS_OUTSIDE_ZERO_DAY_WINDOWS
)

print(
    "Non-DDoS windows in zero-day:",
    NON_DDoS_INSIDE_ZERO_DAY_WINDOWS
)

print(
    "Isolation valid:",
    ZERO_DAY_WINDOW_ISOLATION_VALID
)


# ======================================================================
# 8 — PARTITION SUMMARY
# ======================================================================

print("\n[8] Temporal-window partition summary")
print("-" * 78)


WINDOW_PARTITION_SUMMARY = (

    TEMPORAL_WINDOW_MANIFEST

    .groupby(
        "partition",
        as_index=False
    )

    .agg(

        source_ranges=
            (
                "source_attack_class",
                "count"
            ),

        source_rows=
            (
                "partition_row_count",
                "sum"
            ),

        windows=
            (
                "window_count",
                "sum"
            ),

        unused_tail_rows=
            (
                "unused_tail_rows",
                "sum"
            )
    )
)


partition_order = [
    "development_train",
    "development_validation",
    "known_test",
    "benign_test",
    "zero_day_attack_test"
]


WINDOW_PARTITION_SUMMARY[
    "_order"
] = (

    WINDOW_PARTITION_SUMMARY[
        "partition"
    ]
    .map(
        {
            name: index
            for index, name
            in enumerate(
                partition_order
            )
        }
    )
)


WINDOW_PARTITION_SUMMARY = (

    WINDOW_PARTITION_SUMMARY

    .sort_values(
        "_order"
    )

    .drop(
        columns="_order"
    )

    .reset_index(
        drop=True
    )
)


display(
    WINDOW_PARTITION_SUMMARY
)


# ======================================================================
# 9 — WINDOW LABEL / CLASS SUMMARY
# ======================================================================

print("\n[9] Window-label summary")
print("-" * 78)


WINDOW_LABEL_SUMMARY = (

    TEMPORAL_WINDOW_MANIFEST

    .groupby(
        [
            "partition",
            "binary_target"
        ],
        as_index=False
    )

    .agg(
        windows=(
            "window_count",
            "sum"
        )
    )
)


display(
    WINDOW_LABEL_SUMMARY
)


# ======================================================================
# 10 — DEVELOPMENT-TRAIN FAMILY WINDOW COUNTS
# ======================================================================

print("\n[10] Development-training windows by family")
print("-" * 78)


TRAIN_FAMILY_WINDOW_SUMMARY = (

    TEMPORAL_WINDOW_MANIFEST[
        TEMPORAL_WINDOW_MANIFEST[
            "partition"
        ]
        ==
        "development_train"
    ]

    .groupby(
        "research_family",
        as_index=False
    )

    .agg(
        windows=(
            "window_count",
            "sum"
        )
    )

    .sort_values(
        "windows",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


display(
    TRAIN_FAMILY_WINDOW_SUMMARY
)


# ======================================================================
# 11 — CORE WINDOWING INTEGRITY CHECKS
# ======================================================================

print("\n[11] Temporal integrity checks")
print("-" * 78)


EXPECTED_PARTITIONS = {
    "development_train",
    "development_validation",
    "known_test",
    "benign_test",
    "zero_day_attack_test"
}


PARTITIONS_CORRECT = bool(

    set(
        TEMPORAL_WINDOW_MANIFEST[
            "partition"
        ].unique()
    )
    ==
    EXPECTED_PARTITIONS
)


ALL_WINDOWS_WITHIN_SOURCE_RANGE = bool(

    TEMPORAL_WINDOW_MANIFEST[
        "window_bounds_valid"
    ].all()
)


NO_CROSS_SOURCE_WINDOWS = True

NO_CROSS_PARTITION_WINDOWS = True


# Every window is defined from one manifest row only.
# Therefore source/partition crossing is structurally impossible.
for _, row in TEMPORAL_WINDOW_MANIFEST.iterrows():

    if int(
        row["window_count"]
    ) <= 0:
        continue

    if (
        int(
            row["first_window_start"]
        )
        <
        int(
            row["partition_start_row"]
        )
    ):

        NO_CROSS_PARTITION_WINDOWS = False


    if (
        int(
            row[
                "last_window_end_exclusive"
            ]
        )
        >
        int(
            row[
                "partition_end_row_exclusive"
            ]
        )
    ):

        NO_CROSS_PARTITION_WINDOWS = False


TOTAL_WINDOWS = int(

    TEMPORAL_WINDOW_MANIFEST[
        "window_count"
    ].sum()
)


ALL_WINDOW_COUNTS_POSITIVE_OR_ZERO = bool(

    (
        TEMPORAL_WINDOW_MANIFEST[
            "window_count"
        ]
        >=
        0
    ).all()
)


print(
    "Expected partitions present   :",
    PARTITIONS_CORRECT
)

print(
    "Windows inside source ranges  :",
    ALL_WINDOWS_WITHIN_SOURCE_RANGE
)

print(
    "No cross-source windows       :",
    NO_CROSS_SOURCE_WINDOWS
)

print(
    "No cross-partition windows    :",
    NO_CROSS_PARTITION_WINDOWS
)

print(
    "Timestamp excluded from input :",
    not TIMESTAMP_USED_AS_MODEL_FEATURE
)

print(
    "Total Fold-1 windows          :",
    f"{TOTAL_WINDOWS:,}"
)


# ======================================================================
# 12 — SAVE WINDOW MANIFESTS
# ======================================================================

print("\n[12] Saving temporal-window artifacts")
print("-" * 78)


LOCAL_WINDOW_DIR = (

    PROJECT_ROOT

    / "processed_data"

    / "temporal_windows"

    / "fold_01_DDoS"
)


LOCAL_WINDOW_DIR.mkdir(
    parents=True,
    exist_ok=True
)


WINDOW_MANIFEST_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_temporal_window_manifest.csv"
)


WINDOW_SUMMARY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_temporal_window_summary.csv"
)


WINDOW_LABEL_SUMMARY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_window_label_summary.csv"
)


TRAIN_FAMILY_SUMMARY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_train_family_window_summary.csv"
)


WINDOW_POLICY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_temporal_window_policy.json"
)


TEMPORAL_WINDOW_MANIFEST.to_csv(
    WINDOW_MANIFEST_PATH,
    index=False
)


WINDOW_PARTITION_SUMMARY.to_csv(
    WINDOW_SUMMARY_PATH,
    index=False
)


WINDOW_LABEL_SUMMARY.to_csv(
    WINDOW_LABEL_SUMMARY_PATH,
    index=False
)


TRAIN_FAMILY_WINDOW_SUMMARY.to_csv(
    TRAIN_FAMILY_SUMMARY_PATH,
    index=False
)


WINDOW_POLICY = {

    "fold_id":
        FOLD_ID,

    "held_out_family":
        HELD_OUT_FAMILY,

    "window_size":
        TEMPORAL_WINDOW,

    "stride":
        TEMPORAL_STRIDE,

    "timestamp_used_as_model_feature":
        False,

    "window_created_across_source_boundary":
        False,

    "window_created_across_partition_boundary":
        False,

    "preprocessing_frozen_before_windowing":
        True,

    "input_clipping_after_test_diagnostic":
        False,

    "test_driven_row_removal":
        False,

    "test_driven_parameter_refitting":
        False,

    "window_label_policy":
        (
            "Every source file represents one source class, "
            "so every temporal window inherits the binary target "
            "of its source-range manifest."
        ),

    "tail_policy":
        (
            "Rows that cannot form a complete T=8 window "
            "inside the same source and partition are discarded."
        )
}


with open(
    WINDOW_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        WINDOW_POLICY,
        file,
        indent=4
    )


# ======================================================================
# 13 — SAVE PREPROCESSING FREEZE RECORD
# ======================================================================

FREEZE_RECORD_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_preprocessing_freeze_record.json"
)


FREEZE_RECORD = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "preprocessing_status":
        "frozen",

    "retained_features":
        75,

    "input_clipping":
        False,

    "test_based_feature_removal":
        False,

    "test_based_row_removal":
        False,

    "test_based_parameter_refitting":
        False,

    "diagnostic_note":
        (
            "Extreme finite Bwd IAT Std values were observed "
            "during the post-freeze numerical audit. "
            "No preprocessing decision was altered using "
            "validation or test values."
        )
}


with open(
    FREEZE_RECORD_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        FREEZE_RECORD,
        file,
        indent=4
    )


# ======================================================================
# 14 — BACK UP TO GOOGLE DRIVE
# ======================================================================

print("\n[13] Backing up temporal artifacts to Google Drive")
print("-" * 78)


DRIVE_WINDOW_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/temporal_windows/"
    "fold_01_DDoS"
)


DRIVE_WINDOW_DIR.mkdir(
    parents=True,
    exist_ok=True
)


OUTPUT_FILES = [
    WINDOW_MANIFEST_PATH,
    WINDOW_SUMMARY_PATH,
    WINDOW_LABEL_SUMMARY_PATH,
    TRAIN_FAMILY_SUMMARY_PATH,
    WINDOW_POLICY_PATH,
    FREEZE_RECORD_PATH
]


for source_path in OUTPUT_FILES:

    shutil.copy2(
        source_path,
        DRIVE_WINDOW_DIR
        /
        source_path.name
    )


DRIVE_OUTPUTS_EXIST = all(

    (
        DRIVE_WINDOW_DIR
        /
        source_path.name
    ).exists()

    for source_path
    in OUTPUT_FILES
)


print(
    "Artifacts backed up:",
    DRIVE_OUTPUTS_EXIST
)


# ======================================================================
# 15 — FINAL VALIDATION
# ======================================================================

A10_VALID = bool(

    PREPROCESSING_FROZEN

    and

    len(
        TEMPORAL_WINDOW_MANIFEST
    ) == 75

    and

    ALL_WINDOW_BOUNDS_VALID

    and

    NEGATIVE_WINDOW_COUNTS == 0

    and

    ZERO_DAY_WINDOW_ISOLATION_VALID

    and

    PARTITIONS_CORRECT

    and

    ALL_WINDOWS_WITHIN_SOURCE_RANGE

    and

    NO_CROSS_SOURCE_WINDOWS

    and

    NO_CROSS_PARTITION_WINDOWS

    and

    not TIMESTAMP_USED_AS_MODEL_FEATURE

    and

    TOTAL_WINDOWS > 0

    and

    DRIVE_OUTPUTS_EXIST
)


STEP_10_WINDOW_MANIFEST_VALID = (
    A10_VALID
)


print("\n[14] Recovery Step A10 validation")
print("-" * 78)

print(
    "Preprocessing frozen          :",
    PREPROCESSING_FROZEN
)

print(
    "Manifest records              :",
    len(TEMPORAL_WINDOW_MANIFEST),
    "/ 75"
)

print(
    "All window bounds valid       :",
    ALL_WINDOW_BOUNDS_VALID
)

print(
    "Zero-day isolation valid      :",
    ZERO_DAY_WINDOW_ISOLATION_VALID
)

print(
    "No cross-source windows       :",
    NO_CROSS_SOURCE_WINDOWS
)

print(
    "No cross-partition windows    :",
    NO_CROSS_PARTITION_WINDOWS
)

print(
    "Timestamp excluded            :",
    not TIMESTAMP_USED_AS_MODEL_FEATURE
)

print(
    "Total temporal windows        :",
    f"{TOTAL_WINDOWS:,}"
)

print(
    "Artifacts backed up to Drive  :",
    DRIVE_OUTPUTS_EXIST
)


print("\n" + "=" * 78)

if A10_VALID:

    print(
        "✅ RECOVERY STEP A10 PASSED — "
        "Fold-1 temporal windows are defined without "
        "source, partition, or zero-day leakage."
    )

else:

    print(
        "❌ RECOVERY STEP A10 FAILED — "
        "Do not create model datasets yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A10 — BUILD FOLD-1 TEMPORAL WINDOW MANIFEST
WINDOW = 8 | STRIDE = 8 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying recovered state
------------------------------------------------------------------------------
Frozen preprocessing valid: True

[2] Freezing preprocessing protocol
------------------------------------------------------------------------------
Preprocessing frozen          : True
Input clipping               : False
Test-driven row removal      : False
Test-driven parameter refit  : False
Decision: preserve the training-only preprocessing exactly.

[3] Temporal configuration
------------------------------------------------------------------------------
Fold: 1
Held-out family: DDoS
Window length T: 8
Stride: 8
Timestamp used as model feature: False

[4] Loading Fold-1 source/partition ranges
------------------------------------------------------------------------------
Fold-1 manifest ranges: 75

[5] Building legal temporal-window ranges
------------------------------------------------------------------------------
Temporal manifest records: 75

[6] Window-boundary validation
------------------------------------------------------------------------------
All window bounds valid: True
Negative window counts: 0

[7] Zero-day isolation checks
------------------------------------------------------------------------------
DDoS windows outside zero-day: 0
Non-DDoS windows in zero-day: 0
Isolation valid: True

[8] Temporal-window partition summary
------------------------------------------------------------------------------

,partition,source_ranges,source_rows,windows,unused_tail_rows
0,development_train,21,6253058,781622,82
1,development_validation,21,1339934,167482,78
2,known_test,20,1326235,165769,83
3,benign_test,1,13727,1715,7
4,zero_day_attack_test,12,30918665,3864829,33

[9] Window-label summary
------------------------------------------------------------------------------

                partition  binary_target  windows
0             benign_test              0     1715
1       development_train              0     8006
2       development_train              1   773616
3  development_validation              0     1715
4  development_validation              1   165767
5              known_test              1   165769
6    zero_day_attack_test              1  3864829

[10] Development-training windows by family
------------------------------------------------------------------------------

  research_family  windows
0             DoS   659287
1           Recon    96928
2        Spoofing    12931
3          Benign     8006
4           Mirai     2013
5             Web     1715
6      BruteForce      742

[11] Temporal integrity checks
------------------------------------------------------------------------------
Expected partitions present   : True
Windows inside source ranges  : True
No cross-source windows       : True
No cross-partition windows    : True
Timestamp excluded from input : True
Total Fold-1 windows          : 4,981,417

[12] Saving temporal-window artifacts
------------------------------------------------------------------------------

[13] Backing up temporal artifacts to Google Drive
------------------------------------------------------------------------------
Artifacts backed up: True

[14] Recovery Step A10 validation
------------------------------------------------------------------------------
Preprocessing frozen          : True
Manifest records              : 75 / 75
All window bounds valid       : True
Zero-day isolation valid      : True
No cross-source windows       : True
No cross-partition windows    : True
Timestamp excluded            : True
Total temporal windows        : 4,981,417
Artifacts backed up to Drive  : True

==============================================================================
✅ RECOVERY STEP A10 PASSED — Fold-1 temporal windows are defined without source, partition, or zero-day leakage.
==============================================================================

# Recovery Step A10 — Freeze preprocessing and build Fold-1 temporal-window manifest

In [ ]:
# ======================================================================
# RECOVERY STEP A10
# FREEZE FOLD-1 PREPROCESSING + BUILD TEMPORAL WINDOW MANIFEST
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("RECOVERY STEP A10 — BUILD FOLD-1 TEMPORAL WINDOW MANIFEST")
print("WINDOW = 8 | STRIDE = 8 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREVIOUS RECOVERY STATE
# ======================================================================

print("\n[1] Verifying recovered state")
print("-" * 78)

required_variables = [
    "STEP_9_3_VALID",
    "LOAFO_SPLIT_MANIFEST",
    "LOAFO_FOLD_SUMMARY"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun A8 if the runtime restarted."
    )

if not STEP_9_3_VALID:
    raise RuntimeError(
        "Fold-1 frozen preprocessing did not pass A8."
    )

print(
    "Frozen preprocessing valid:",
    STEP_9_3_VALID
)


# ======================================================================
# 2 — FREEZE PREPROCESSING DECISION
# ======================================================================

print("\n[2] Freezing preprocessing protocol")
print("-" * 78)

PREPROCESSING_FROZEN = True

INPUT_CLIPPING_ENABLED = False
TEST_DRIVEN_ROW_REMOVAL = False
TEST_DRIVEN_REFITTING = False

print(
    "Preprocessing frozen          :",
    PREPROCESSING_FROZEN
)

print(
    "Input clipping               :",
    INPUT_CLIPPING_ENABLED
)

print(
    "Test-driven row removal      :",
    TEST_DRIVEN_ROW_REMOVAL
)

print(
    "Test-driven parameter refit  :",
    TEST_DRIVEN_REFITTING
)

print(
    "Decision: preserve the training-only preprocessing exactly."
)


# ======================================================================
# 3 — TEMPORAL CONFIGURATION
# ======================================================================

print("\n[3] Temporal configuration")
print("-" * 78)

TEMPORAL_WINDOW = 8
TEMPORAL_STRIDE = 8

FOLD_ID = 1
HELD_OUT_FAMILY = "DDoS"

TIMESTAMP_USED_AS_MODEL_FEATURE = False


print(
    "Fold:",
    FOLD_ID
)

print(
    "Held-out family:",
    HELD_OUT_FAMILY
)

print(
    "Window length T:",
    TEMPORAL_WINDOW
)

print(
    "Stride:",
    TEMPORAL_STRIDE
)

print(
    "Timestamp used as model feature:",
    TIMESTAMP_USED_AS_MODEL_FEATURE
)


if TEMPORAL_WINDOW <= 0:
    raise RuntimeError(
        "Window length must be positive."
    )

if TEMPORAL_STRIDE <= 0:
    raise RuntimeError(
        "Stride must be positive."
    )


# ======================================================================
# 4 — SELECT EXACT FOLD-1 LOAFO RANGES
# ======================================================================

print("\n[4] Loading Fold-1 source/partition ranges")
print("-" * 78)

fold_manifest = (
    LOAFO_SPLIT_MANIFEST[
        LOAFO_SPLIT_MANIFEST[
            "fold_id"
        ] == FOLD_ID
    ]
    .copy()
    .reset_index(drop=True)
)


print(
    "Fold-1 manifest ranges:",
    len(fold_manifest)
)


if len(fold_manifest) != 75:
    raise RuntimeError(
        f"Expected 75 Fold-1 source ranges, "
        f"found {len(fold_manifest)}."
    )


# ======================================================================
# 5 — BUILD TEMPORAL WINDOW MANIFEST
# ======================================================================

print("\n[5] Building legal temporal-window ranges")
print("-" * 78)

window_records = []


for _, row in fold_manifest.iterrows():

    start_row = int(
        row["start_row"]
    )

    end_row = int(
        row["end_row_exclusive"]
    )

    row_count = int(
        row["row_count"]
    )


    # --------------------------------------------------------------
    # Number of complete windows fully contained in THIS range only.
    # No window may cross its range boundary.
    # --------------------------------------------------------------

    if row_count < TEMPORAL_WINDOW:

        window_count = 0

    else:

        window_count = (
            1
            +
            (
                row_count
                -
                TEMPORAL_WINDOW
            )
            //
            TEMPORAL_STRIDE
        )


    if window_count > 0:

        first_window_start = (
            start_row
        )

        first_window_end = (
            first_window_start
            +
            TEMPORAL_WINDOW
        )


        last_window_start = (

            start_row

            +

            (
                window_count
                -
                1
            )
            *
            TEMPORAL_STRIDE
        )


        last_window_end = (

            last_window_start

            +

            TEMPORAL_WINDOW
        )


        unused_tail_rows = (

            end_row
            -
            last_window_end
        )

    else:

        first_window_start = None
        first_window_end = None
        last_window_start = None
        last_window_end = None

        unused_tail_rows = (
            row_count
        )


    bounds_valid = bool(

        window_count >= 0

        and

        (
            window_count == 0

            or

            (
                first_window_start
                >=
                start_row

                and

                first_window_end
                <=
                end_row

                and

                last_window_start
                >=
                start_row

                and

                last_window_end
                <=
                end_row
            )
        )

        and

        unused_tail_rows >= 0
    )


    window_records.append({

        "fold_id":
            int(row["fold_id"]),

        "held_out_family":
            row["held_out_family"],

        "partition":
            row["partition"],

        "source_attack_class":
            row["source_attack_class"],

        "research_family":
            row["research_family"],

        "binary_target":
            int(row["binary_target"]),

        "parquet_path":
            row["parquet_path"],

        "partition_start_row":
            start_row,

        "partition_end_row_exclusive":
            end_row,

        "partition_row_count":
            row_count,

        "window_size":
            TEMPORAL_WINDOW,

        "stride":
            TEMPORAL_STRIDE,

        "window_count":
            int(window_count),

        "first_window_start":
            first_window_start,

        "first_window_end_exclusive":
            first_window_end,

        "last_window_start":
            last_window_start,

        "last_window_end_exclusive":
            last_window_end,

        "unused_tail_rows":
            int(unused_tail_rows),

        "window_bounds_valid":
            bounds_valid
    })


TEMPORAL_WINDOW_MANIFEST = pd.DataFrame(
    window_records
)


print(
    "Temporal manifest records:",
    len(TEMPORAL_WINDOW_MANIFEST)
)


# ======================================================================
# 6 — VALIDATE WINDOW BOUNDARIES
# ======================================================================

print("\n[6] Window-boundary validation")
print("-" * 78)


ALL_WINDOW_BOUNDS_VALID = bool(

    TEMPORAL_WINDOW_MANIFEST[
        "window_bounds_valid"
    ].all()
)


NEGATIVE_WINDOW_COUNTS = int(

    (
        TEMPORAL_WINDOW_MANIFEST[
            "window_count"
        ] < 0
    ).sum()
)


print(
    "All window bounds valid:",
    ALL_WINDOW_BOUNDS_VALID
)

print(
    "Negative window counts:",
    NEGATIVE_WINDOW_COUNTS
)


# ======================================================================
# 7 — STRICT PARTITION / FAMILY CHECKS
# ======================================================================

print("\n[7] Zero-day isolation checks")
print("-" * 78)


DDoS_OUTSIDE_ZERO_DAY_WINDOWS = int(

    TEMPORAL_WINDOW_MANIFEST.loc[
        (
            TEMPORAL_WINDOW_MANIFEST[
                "research_family"
            ] == HELD_OUT_FAMILY
        )
        &
        (
            TEMPORAL_WINDOW_MANIFEST[
                "partition"
            ]
            !=
            "zero_day_attack_test"
        ),
        "window_count"
    ].sum()
)


NON_DDoS_INSIDE_ZERO_DAY_WINDOWS = int(

    TEMPORAL_WINDOW_MANIFEST.loc[
        (
            TEMPORAL_WINDOW_MANIFEST[
                "research_family"
            ]
            !=
            HELD_OUT_FAMILY
        )
        &
        (
            TEMPORAL_WINDOW_MANIFEST[
                "partition"
            ]
            ==
            "zero_day_attack_test"
        ),
        "window_count"
    ].sum()
)


ZERO_DAY_WINDOW_ISOLATION_VALID = bool(

    DDoS_OUTSIDE_ZERO_DAY_WINDOWS == 0

    and

    NON_DDoS_INSIDE_ZERO_DAY_WINDOWS == 0
)


print(
    "DDoS windows outside zero-day:",
    DDoS_OUTSIDE_ZERO_DAY_WINDOWS
)

print(
    "Non-DDoS windows in zero-day:",
    NON_DDoS_INSIDE_ZERO_DAY_WINDOWS
)

print(
    "Isolation valid:",
    ZERO_DAY_WINDOW_ISOLATION_VALID
)


# ======================================================================
# 8 — PARTITION SUMMARY
# ======================================================================

print("\n[8] Temporal-window partition summary")
print("-" * 78)


WINDOW_PARTITION_SUMMARY = (

    TEMPORAL_WINDOW_MANIFEST

    .groupby(
        "partition",
        as_index=False
    )

    .agg(

        source_ranges=
            (
                "source_attack_class",
                "count"
            ),

        source_rows=
            (
                "partition_row_count",
                "sum"
            ),

        windows=
            (
                "window_count",
                "sum"
            ),

        unused_tail_rows=
            (
                "unused_tail_rows",
                "sum"
            )
    )
)


partition_order = [
    "development_train",
    "development_validation",
    "known_test",
    "benign_test",
    "zero_day_attack_test"
]


WINDOW_PARTITION_SUMMARY[
    "_order"
] = (

    WINDOW_PARTITION_SUMMARY[
        "partition"
    ]
    .map(
        {
            name: index
            for index, name
            in enumerate(
                partition_order
            )
        }
    )
)


WINDOW_PARTITION_SUMMARY = (

    WINDOW_PARTITION_SUMMARY

    .sort_values(
        "_order"
    )

    .drop(
        columns="_order"
    )

    .reset_index(
        drop=True
    )
)


display(
    WINDOW_PARTITION_SUMMARY
)


# ======================================================================
# 9 — WINDOW LABEL / CLASS SUMMARY
# ======================================================================

print("\n[9] Window-label summary")
print("-" * 78)


WINDOW_LABEL_SUMMARY = (

    TEMPORAL_WINDOW_MANIFEST

    .groupby(
        [
            "partition",
            "binary_target"
        ],
        as_index=False
    )

    .agg(
        windows=(
            "window_count",
            "sum"
        )
    )
)


display(
    WINDOW_LABEL_SUMMARY
)


# ======================================================================
# 10 — DEVELOPMENT-TRAIN FAMILY WINDOW COUNTS
# ======================================================================

print("\n[10] Development-training windows by family")
print("-" * 78)


TRAIN_FAMILY_WINDOW_SUMMARY = (

    TEMPORAL_WINDOW_MANIFEST[
        TEMPORAL_WINDOW_MANIFEST[
            "partition"
        ]
        ==
        "development_train"
    ]

    .groupby(
        "research_family",
        as_index=False
    )

    .agg(
        windows=(
            "window_count",
            "sum"
        )
    )

    .sort_values(
        "windows",
        ascending=False
    )

    .reset_index(
        drop=True
    )
)


display(
    TRAIN_FAMILY_WINDOW_SUMMARY
)


# ======================================================================
# 11 — CORE WINDOWING INTEGRITY CHECKS
# ======================================================================

print("\n[11] Temporal integrity checks")
print("-" * 78)


EXPECTED_PARTITIONS = {
    "development_train",
    "development_validation",
    "known_test",
    "benign_test",
    "zero_day_attack_test"
}


PARTITIONS_CORRECT = bool(

    set(
        TEMPORAL_WINDOW_MANIFEST[
            "partition"
        ].unique()
    )
    ==
    EXPECTED_PARTITIONS
)


ALL_WINDOWS_WITHIN_SOURCE_RANGE = bool(

    TEMPORAL_WINDOW_MANIFEST[
        "window_bounds_valid"
    ].all()
)


NO_CROSS_SOURCE_WINDOWS = True

NO_CROSS_PARTITION_WINDOWS = True


# Every window is defined from one manifest row only.
# Therefore source/partition crossing is structurally impossible.
for _, row in TEMPORAL_WINDOW_MANIFEST.iterrows():

    if int(
        row["window_count"]
    ) <= 0:
        continue

    if (
        int(
            row["first_window_start"]
        )
        <
        int(
            row["partition_start_row"]
        )
    ):

        NO_CROSS_PARTITION_WINDOWS = False


    if (
        int(
            row[
                "last_window_end_exclusive"
            ]
        )
        >
        int(
            row[
                "partition_end_row_exclusive"
            ]
        )
    ):

        NO_CROSS_PARTITION_WINDOWS = False


TOTAL_WINDOWS = int(

    TEMPORAL_WINDOW_MANIFEST[
        "window_count"
    ].sum()
)


ALL_WINDOW_COUNTS_POSITIVE_OR_ZERO = bool(

    (
        TEMPORAL_WINDOW_MANIFEST[
            "window_count"
        ]
        >=
        0
    ).all()
)


print(
    "Expected partitions present   :",
    PARTITIONS_CORRECT
)

print(
    "Windows inside source ranges  :",
    ALL_WINDOWS_WITHIN_SOURCE_RANGE
)

print(
    "No cross-source windows       :",
    NO_CROSS_SOURCE_WINDOWS
)

print(
    "No cross-partition windows    :",
    NO_CROSS_PARTITION_WINDOWS
)

print(
    "Timestamp excluded from input :",
    not TIMESTAMP_USED_AS_MODEL_FEATURE
)

print(
    "Total Fold-1 windows          :",
    f"{TOTAL_WINDOWS:,}"
)


# ======================================================================
# 12 — SAVE WINDOW MANIFESTS
# ======================================================================

print("\n[12] Saving temporal-window artifacts")
print("-" * 78)


LOCAL_WINDOW_DIR = (

    PROJECT_ROOT

    / "processed_data"

    / "temporal_windows"

    / "fold_01_DDoS"
)


LOCAL_WINDOW_DIR.mkdir(
    parents=True,
    exist_ok=True
)


WINDOW_MANIFEST_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_temporal_window_manifest.csv"
)


WINDOW_SUMMARY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_temporal_window_summary.csv"
)


WINDOW_LABEL_SUMMARY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_window_label_summary.csv"
)


TRAIN_FAMILY_SUMMARY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_train_family_window_summary.csv"
)


WINDOW_POLICY_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_temporal_window_policy.json"
)


TEMPORAL_WINDOW_MANIFEST.to_csv(
    WINDOW_MANIFEST_PATH,
    index=False
)


WINDOW_PARTITION_SUMMARY.to_csv(
    WINDOW_SUMMARY_PATH,
    index=False
)


WINDOW_LABEL_SUMMARY.to_csv(
    WINDOW_LABEL_SUMMARY_PATH,
    index=False
)


TRAIN_FAMILY_WINDOW_SUMMARY.to_csv(
    TRAIN_FAMILY_SUMMARY_PATH,
    index=False
)


WINDOW_POLICY = {

    "fold_id":
        FOLD_ID,

    "held_out_family":
        HELD_OUT_FAMILY,

    "window_size":
        TEMPORAL_WINDOW,

    "stride":
        TEMPORAL_STRIDE,

    "timestamp_used_as_model_feature":
        False,

    "window_created_across_source_boundary":
        False,

    "window_created_across_partition_boundary":
        False,

    "preprocessing_frozen_before_windowing":
        True,

    "input_clipping_after_test_diagnostic":
        False,

    "test_driven_row_removal":
        False,

    "test_driven_parameter_refitting":
        False,

    "window_label_policy":
        (
            "Every source file represents one source class, "
            "so every temporal window inherits the binary target "
            "of its source-range manifest."
        ),

    "tail_policy":
        (
            "Rows that cannot form a complete T=8 window "
            "inside the same source and partition are discarded."
        )
}


with open(
    WINDOW_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        WINDOW_POLICY,
        file,
        indent=4
    )


# ======================================================================
# 13 — SAVE PREPROCESSING FREEZE RECORD
# ======================================================================

FREEZE_RECORD_PATH = (

    LOCAL_WINDOW_DIR

    / "fold_01_DDoS_preprocessing_freeze_record.json"
)


FREEZE_RECORD = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "preprocessing_status":
        "frozen",

    "retained_features":
        75,

    "input_clipping":
        False,

    "test_based_feature_removal":
        False,

    "test_based_row_removal":
        False,

    "test_based_parameter_refitting":
        False,

    "diagnostic_note":
        (
            "Extreme finite Bwd IAT Std values were observed "
            "during the post-freeze numerical audit. "
            "No preprocessing decision was altered using "
            "validation or test values."
        )
}


with open(
    FREEZE_RECORD_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        FREEZE_RECORD,
        file,
        indent=4
    )


# ======================================================================
# 14 — BACK UP TO GOOGLE DRIVE
# ======================================================================

print("\n[13] Backing up temporal artifacts to Google Drive")
print("-" * 78)


DRIVE_WINDOW_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/temporal_windows/"
    "fold_01_DDoS"
)


DRIVE_WINDOW_DIR.mkdir(
    parents=True,
    exist_ok=True
)


OUTPUT_FILES = [
    WINDOW_MANIFEST_PATH,
    WINDOW_SUMMARY_PATH,
    WINDOW_LABEL_SUMMARY_PATH,
    TRAIN_FAMILY_SUMMARY_PATH,
    WINDOW_POLICY_PATH,
    FREEZE_RECORD_PATH
]


for source_path in OUTPUT_FILES:

    shutil.copy2(
        source_path,
        DRIVE_WINDOW_DIR
        /
        source_path.name
    )


DRIVE_OUTPUTS_EXIST = all(

    (
        DRIVE_WINDOW_DIR
        /
        source_path.name
    ).exists()

    for source_path
    in OUTPUT_FILES
)


print(
    "Artifacts backed up:",
    DRIVE_OUTPUTS_EXIST
)


# ======================================================================
# 15 — FINAL VALIDATION
# ======================================================================

A10_VALID = bool(

    PREPROCESSING_FROZEN

    and

    len(
        TEMPORAL_WINDOW_MANIFEST
    ) == 75

    and

    ALL_WINDOW_BOUNDS_VALID

    and

    NEGATIVE_WINDOW_COUNTS == 0

    and

    ZERO_DAY_WINDOW_ISOLATION_VALID

    and

    PARTITIONS_CORRECT

    and

    ALL_WINDOWS_WITHIN_SOURCE_RANGE

    and

    NO_CROSS_SOURCE_WINDOWS

    and

    NO_CROSS_PARTITION_WINDOWS

    and

    not TIMESTAMP_USED_AS_MODEL_FEATURE

    and

    TOTAL_WINDOWS > 0

    and

    DRIVE_OUTPUTS_EXIST
)


STEP_10_WINDOW_MANIFEST_VALID = (
    A10_VALID
)


print("\n[14] Recovery Step A10 validation")
print("-" * 78)

print(
    "Preprocessing frozen          :",
    PREPROCESSING_FROZEN
)

print(
    "Manifest records              :",
    len(TEMPORAL_WINDOW_MANIFEST),
    "/ 75"
)

print(
    "All window bounds valid       :",
    ALL_WINDOW_BOUNDS_VALID
)

print(
    "Zero-day isolation valid      :",
    ZERO_DAY_WINDOW_ISOLATION_VALID
)

print(
    "No cross-source windows       :",
    NO_CROSS_SOURCE_WINDOWS
)

print(
    "No cross-partition windows    :",
    NO_CROSS_PARTITION_WINDOWS
)

print(
    "Timestamp excluded            :",
    not TIMESTAMP_USED_AS_MODEL_FEATURE
)

print(
    "Total temporal windows        :",
    f"{TOTAL_WINDOWS:,}"
)

print(
    "Artifacts backed up to Drive  :",
    DRIVE_OUTPUTS_EXIST
)


print("\n" + "=" * 78)

if A10_VALID:

    print(
        "✅ RECOVERY STEP A10 PASSED — "
        "Fold-1 temporal windows are defined without "
        "source, partition, or zero-day leakage."
    )

else:

    print(
        "❌ RECOVERY STEP A10 FAILED — "
        "Do not create model datasets yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A10 — BUILD FOLD-1 TEMPORAL WINDOW MANIFEST
WINDOW = 8 | STRIDE = 8 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying recovered state
------------------------------------------------------------------------------
Frozen preprocessing valid: True

[2] Freezing preprocessing protocol
------------------------------------------------------------------------------
Preprocessing frozen          : True
Input clipping               : False
Test-driven row removal      : False
Test-driven parameter refit  : False
Decision: preserve the training-only preprocessing exactly.

[3] Temporal configuration
------------------------------------------------------------------------------
Fold: 1
Held-out family: DDoS
Window length T: 8
Stride: 8
Timestamp used as model feature: False

[4] Loading Fold-1 source/partition ranges
------------------------------------------------------------------------------
Fold-1 manifest ranges: 75

[5] Building legal temporal-window ranges
------------------------------------------------------------------------------
Temporal manifest records: 75

[6] Window-boundary validation
------------------------------------------------------------------------------
All window bounds valid: True
Negative window counts: 0

[7] Zero-day isolation checks
------------------------------------------------------------------------------
DDoS windows outside zero-day: 0
Non-DDoS windows in zero-day: 0
Isolation valid: True

[8] Temporal-window partition summary
------------------------------------------------------------------------------

,partition,source_ranges,source_rows,windows,unused_tail_rows
0,development_train,21,6253058,781622,82
1,development_validation,21,1339934,167482,78
2,known_test,20,1326235,165769,83
3,benign_test,1,13727,1715,7
4,zero_day_attack_test,12,30918665,3864829,33

[9] Window-label summary
------------------------------------------------------------------------------

                partition  binary_target  windows
0             benign_test              0     1715
1       development_train              0     8006
2       development_train              1   773616
3  development_validation              0     1715
4  development_validation              1   165767
5              known_test              1   165769
6    zero_day_attack_test              1  3864829

[10] Development-training windows by family
------------------------------------------------------------------------------

  research_family  windows
0             DoS   659287
1           Recon    96928
2        Spoofing    12931
3          Benign     8006
4           Mirai     2013
5             Web     1715
6      BruteForce      742

[11] Temporal integrity checks
------------------------------------------------------------------------------
Expected partitions present   : True
Windows inside source ranges  : True
No cross-source windows       : True
No cross-partition windows    : True
Timestamp excluded from input : True
Total Fold-1 windows          : 4,981,417

[12] Saving temporal-window artifacts
------------------------------------------------------------------------------

[13] Backing up temporal artifacts to Google Drive
------------------------------------------------------------------------------
Artifacts backed up: True

[14] Recovery Step A10 validation
------------------------------------------------------------------------------
Preprocessing frozen          : True
Manifest records              : 75 / 75
All window bounds valid       : True
Zero-day isolation valid      : True
No cross-source windows       : True
No cross-partition windows    : True
Timestamp excluded            : True
Total temporal windows        : 4,981,417
Artifacts backed up to Drive  : True

==============================================================================
✅ RECOVERY STEP A10 PASSED — Fold-1 temporal windows are defined without source, partition, or zero-day leakage.
==============================================================================

# Recovery Step A11 — Create a fixed training-window sampling plan

In [ ]:
# ======================================================================
# RECOVERY STEP A11
# BUILD FIXED FOLD-1 TRAINING-WINDOW SAMPLING PLAN
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("RECOVERY STEP A11 — TRAINING-WINDOW SAMPLING PLAN")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A10 STATE
# ======================================================================

print("\n[1] Verifying temporal-window state")
print("-" * 78)

required_variables = [
    "STEP_10_WINDOW_MANIFEST_VALID",
    "TEMPORAL_WINDOW_MANIFEST"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A10."
    )

if not STEP_10_WINDOW_MANIFEST_VALID:
    raise RuntimeError(
        "Recovery Step A10 did not pass."
    )


print(
    "A10 temporal manifest valid:",
    STEP_10_WINDOW_MANIFEST_VALID
)


# ======================================================================
# 2 — FIX TRAINING-SAMPLING POLICY
# ======================================================================

print("\n[2] Training sampling policy")
print("-" * 78)

MAX_WINDOWS_PER_TRAIN_SOURCE = 10_000

TRAINING_SAMPLING_METHOD = (
    "deterministic_temporal_coverage"
)

SAMPLING_USES_BINARY_TARGET = False

SAMPLING_USES_FAMILY_LABEL = False

SAME_SAMPLE_ACROSS_MODEL_SEEDS = True


print(
    "Maximum windows/source       :",
    f"{MAX_WINDOWS_PER_TRAIN_SOURCE:,}"
)

print(
    "Sampling method              :",
    TRAINING_SAMPLING_METHOD
)

print(
    "Uses binary target           :",
    SAMPLING_USES_BINARY_TARGET
)

print(
    "Uses research-family label   :",
    SAMPLING_USES_FAMILY_LABEL
)

print(
    "Same sample across seeds     :",
    SAME_SAMPLE_ACROSS_MODEL_SEEDS
)


# ======================================================================
# 3 — SELECT DEVELOPMENT-TRAIN RANGES ONLY
# ======================================================================

print("\n[3] Selecting development-training source ranges")
print("-" * 78)

train_windows = (
    TEMPORAL_WINDOW_MANIFEST[
        TEMPORAL_WINDOW_MANIFEST[
            "partition"
        ]
        ==
        "development_train"
    ]
    .copy()
    .reset_index(drop=True)
)


print(
    "Training source ranges:",
    len(train_windows)
)


if len(train_windows) != 21:
    raise RuntimeError(
        f"Expected 21 Fold-1 training source ranges, "
        f"found {len(train_windows)}."
    )


# ======================================================================
# 4 — BUILD SOURCE-LEVEL SAMPLE PLAN
# ======================================================================

print("\n[4] Building deterministic sampling plan")
print("-" * 78)

sampling_records = []


for _, row in train_windows.iterrows():

    available_windows = int(
        row["window_count"]
    )


    sampled_windows = min(
        available_windows,
        MAX_WINDOWS_PER_TRAIN_SOURCE
    )


    if sampled_windows == 0:

        selection_rule = "none"


    elif sampled_windows == available_windows:

        selection_rule = "all_windows"


    else:

        selection_rule = (
            "evenly_spaced_window_ordinals"
        )


    sampling_records.append({

        "fold_id":
            int(row["fold_id"]),

        "held_out_family":
            row["held_out_family"],

        "partition":
            row["partition"],

        "source_attack_class":
            row["source_attack_class"],

        # Kept for audit/reporting only.
        # These fields are NOT used to choose the cap.
        "research_family":
            row["research_family"],

        "binary_target":
            int(row["binary_target"]),

        "parquet_path":
            row["parquet_path"],

        "partition_start_row":
            int(
                row["partition_start_row"]
            ),

        "partition_end_row_exclusive":
            int(
                row[
                    "partition_end_row_exclusive"
                ]
            ),

        "window_size":
            int(
                row["window_size"]
            ),

        "stride":
            int(
                row["stride"]
            ),

        "available_windows":
            available_windows,

        "maximum_allowed_windows":
            MAX_WINDOWS_PER_TRAIN_SOURCE,

        "sampled_windows":
            sampled_windows,

        "selection_rule":
            selection_rule,

        "selection_uses_binary_target":
            False,

        "selection_uses_family_label":
            False
    })


TRAIN_SAMPLING_PLAN = pd.DataFrame(
    sampling_records
)


# ======================================================================
# 5 — DISPLAY SOURCE-LEVEL PLAN
# ======================================================================

print("\n[5] Source-level training sampling plan")
print("-" * 78)


display(

    TRAIN_SAMPLING_PLAN[
        [
            "source_attack_class",
            "research_family",
            "binary_target",
            "available_windows",
            "sampled_windows",
            "selection_rule"
        ]
    ]

)


# ======================================================================
# 6 — VALIDATE CAP POLICY
# ======================================================================

print("\n[6] Sampling-plan validation")
print("-" * 78)


CAP_RESPECTED = bool(

    (
        TRAIN_SAMPLING_PLAN[
            "sampled_windows"
        ]
        <=
        MAX_WINDOWS_PER_TRAIN_SOURCE
    ).all()
)


SAMPLE_NOT_GREATER_THAN_AVAILABLE = bool(

    (
        TRAIN_SAMPLING_PLAN[
            "sampled_windows"
        ]
        <=
        TRAIN_SAMPLING_PLAN[
            "available_windows"
        ]
    ).all()
)


small_sources = (

    TRAIN_SAMPLING_PLAN[
        TRAIN_SAMPLING_PLAN[
            "available_windows"
        ]
        <=
        MAX_WINDOWS_PER_TRAIN_SOURCE
    ]
)


ALL_SMALL_SOURCES_PRESERVED = bool(

    (
        small_sources[
            "sampled_windows"
        ]
        ==
        small_sources[
            "available_windows"
        ]
    ).all()
)


large_sources = (

    TRAIN_SAMPLING_PLAN[
        TRAIN_SAMPLING_PLAN[
            "available_windows"
        ]
        >
        MAX_WINDOWS_PER_TRAIN_SOURCE
    ]
)


ALL_LARGE_SOURCES_CAPPED = bool(

    (
        large_sources[
            "sampled_windows"
        ]
        ==
        MAX_WINDOWS_PER_TRAIN_SOURCE
    ).all()
)


print(
    "Cap respected                 :",
    CAP_RESPECTED
)

print(
    "Sample <= available           :",
    SAMPLE_NOT_GREATER_THAN_AVAILABLE
)

print(
    "All small sources fully kept  :",
    ALL_SMALL_SOURCES_PRESERVED
)

print(
    "All large sources capped      :",
    ALL_LARGE_SOURCES_CAPPED
)

print(
    "Large sources requiring cap   :",
    len(large_sources)
)


# ======================================================================
# 7 — CHECK ZERO-DAY ISOLATION
# ======================================================================

print("\n[7] Held-out-family isolation")
print("-" * 78)


DDoS_TRAIN_WINDOWS = int(

    TRAIN_SAMPLING_PLAN.loc[
        TRAIN_SAMPLING_PLAN[
            "research_family"
        ]
        ==
        "DDoS",
        "sampled_windows"
    ].sum()
)


ONLY_DEVELOPMENT_TRAIN = bool(

    (
        TRAIN_SAMPLING_PLAN[
            "partition"
        ]
        ==
        "development_train"
    ).all()
)


HELD_OUT_ISOLATION_VALID = bool(

    DDoS_TRAIN_WINDOWS == 0

    and

    ONLY_DEVELOPMENT_TRAIN
)


print(
    "Sampled DDoS training windows:",
    DDoS_TRAIN_WINDOWS
)

print(
    "Only development_train used   :",
    ONLY_DEVELOPMENT_TRAIN
)

print(
    "Held-out isolation valid      :",
    HELD_OUT_ISOLATION_VALID
)


# ======================================================================
# 8 — TOTAL SAMPLE SIZE
# ======================================================================

TOTAL_AVAILABLE_TRAIN_WINDOWS = int(

    TRAIN_SAMPLING_PLAN[
        "available_windows"
    ].sum()
)


TOTAL_SAMPLED_TRAIN_WINDOWS = int(

    TRAIN_SAMPLING_PLAN[
        "sampled_windows"
    ].sum()
)


SAMPLING_FRACTION = (

    TOTAL_SAMPLED_TRAIN_WINDOWS

    /

    TOTAL_AVAILABLE_TRAIN_WINDOWS
)


print("\n[8] Training sample size")
print("-" * 78)

print(
    "Available training windows:",
    f"{TOTAL_AVAILABLE_TRAIN_WINDOWS:,}"
)

print(
    "Sampled training windows  :",
    f"{TOTAL_SAMPLED_TRAIN_WINDOWS:,}"
)

print(
    "Sampling fraction         :",
    f"{SAMPLING_FRACTION:.4%}"
)


# ======================================================================
# 9 — FAMILY SUMMARY
# ======================================================================

print("\n[9] Sampled windows by family")
print("-" * 78)


TRAIN_SAMPLE_FAMILY_SUMMARY = (

    TRAIN_SAMPLING_PLAN

    .groupby(
        "research_family",
        as_index=False
    )

    .agg(

        source_classes=
            (
                "source_attack_class",
                "count"
            ),

        available_windows=
            (
                "available_windows",
                "sum"
            ),

        sampled_windows=
            (
                "sampled_windows",
                "sum"
            )
    )

    .sort_values(
        "sampled_windows",
        ascending=False
    )

    .reset_index(drop=True)
)


display(
    TRAIN_SAMPLE_FAMILY_SUMMARY
)


# ======================================================================
# 10 — BINARY-LABEL SUMMARY
# ======================================================================

print("\n[10] Sampled windows by binary target")
print("-" * 78)


TRAIN_SAMPLE_LABEL_SUMMARY = (

    TRAIN_SAMPLING_PLAN

    .groupby(
        "binary_target",
        as_index=False
    )

    .agg(

        available_windows=
            (
                "available_windows",
                "sum"
            ),

        sampled_windows=
            (
                "sampled_windows",
                "sum"
            )
    )
)


display(
    TRAIN_SAMPLE_LABEL_SUMMARY
)


BENIGN_SAMPLED_WINDOWS = int(

    TRAIN_SAMPLE_LABEL_SUMMARY.loc[
        TRAIN_SAMPLE_LABEL_SUMMARY[
            "binary_target"
        ] == 0,
        "sampled_windows"
    ].iloc[0]
)


ATTACK_SAMPLED_WINDOWS = int(

    TRAIN_SAMPLE_LABEL_SUMMARY.loc[
        TRAIN_SAMPLE_LABEL_SUMMARY[
            "binary_target"
        ] == 1,
        "sampled_windows"
    ].iloc[0]
)


ATTACK_TO_BENIGN_RATIO = (

    ATTACK_SAMPLED_WINDOWS
    /
    BENIGN_SAMPLED_WINDOWS
)


print(
    "Benign sampled windows:",
    f"{BENIGN_SAMPLED_WINDOWS:,}"
)

print(
    "Attack sampled windows:",
    f"{ATTACK_SAMPLED_WINDOWS:,}"
)

print(
    "Attack : benign ratio :",
    f"{ATTACK_TO_BENIGN_RATIO:.3f} : 1"
)


# ======================================================================
# 11 — REPRODUCIBILITY EXPECTATIONS
# ======================================================================

print("\n[11] Reproducibility checks")
print("-" * 78)


EXPECTED_TOTAL_SAMPLE = 105_577

EXPECTED_BENIGN_SAMPLE = 8_006

EXPECTED_ATTACK_SAMPLE = 97_571


TOTAL_SAMPLE_MATCH = (
    TOTAL_SAMPLED_TRAIN_WINDOWS
    ==
    EXPECTED_TOTAL_SAMPLE
)


BENIGN_SAMPLE_MATCH = (
    BENIGN_SAMPLED_WINDOWS
    ==
    EXPECTED_BENIGN_SAMPLE
)


ATTACK_SAMPLE_MATCH = (
    ATTACK_SAMPLED_WINDOWS
    ==
    EXPECTED_ATTACK_SAMPLE
)


print(
    "Expected sampled total:",
    f"{EXPECTED_TOTAL_SAMPLE:,}",
    "| Actual:",
    f"{TOTAL_SAMPLED_TRAIN_WINDOWS:,}",
    "| Match:",
    TOTAL_SAMPLE_MATCH
)

print(
    "Expected benign:",
    f"{EXPECTED_BENIGN_SAMPLE:,}",
    "| Actual:",
    f"{BENIGN_SAMPLED_WINDOWS:,}",
    "| Match:",
    BENIGN_SAMPLE_MATCH
)

print(
    "Expected attack:",
    f"{EXPECTED_ATTACK_SAMPLE:,}",
    "| Actual:",
    f"{ATTACK_SAMPLED_WINDOWS:,}",
    "| Match:",
    ATTACK_SAMPLE_MATCH
)


# ======================================================================
# 12 — VALIDATION / TEST POLICY
# ======================================================================

print("\n[12] Validation and test policy")
print("-" * 78)

VALIDATION_SAMPLED = False
KNOWN_TEST_SAMPLED = False
BENIGN_TEST_SAMPLED = False
ZERO_DAY_TEST_SAMPLED = False


print(
    "Validation sampling :",
    VALIDATION_SAMPLED
)

print(
    "Known-test sampling :",
    KNOWN_TEST_SAMPLED
)

print(
    "Benign-test sampling:",
    BENIGN_TEST_SAMPLED
)

print(
    "Zero-day sampling   :",
    ZERO_DAY_TEST_SAMPLED
)

print(
    "All non-training partitions remain complete."
)


# ======================================================================
# 13 — SAVE SAMPLING POLICY
# ======================================================================

print("\n[13] Saving sampling artifacts")
print("-" * 78)


PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)


LOCAL_SAMPLING_DIR = (

    PROJECT_ROOT

    / "processed_data"

    / "training_sampling"

    / "fold_01_DDoS"
)


LOCAL_SAMPLING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


SAMPLING_PLAN_PATH = (

    LOCAL_SAMPLING_DIR

    / "fold_01_DDoS_training_sampling_plan.csv"
)


FAMILY_SUMMARY_PATH = (

    LOCAL_SAMPLING_DIR

    / "fold_01_DDoS_training_sampling_family_summary.csv"
)


LABEL_SUMMARY_PATH = (

    LOCAL_SAMPLING_DIR

    / "fold_01_DDoS_training_sampling_label_summary.csv"
)


SAMPLING_POLICY_PATH = (

    LOCAL_SAMPLING_DIR

    / "fold_01_DDoS_training_sampling_policy.json"
)


TRAIN_SAMPLING_PLAN.to_csv(
    SAMPLING_PLAN_PATH,
    index=False
)


TRAIN_SAMPLE_FAMILY_SUMMARY.to_csv(
    FAMILY_SUMMARY_PATH,
    index=False
)


TRAIN_SAMPLE_LABEL_SUMMARY.to_csv(
    LABEL_SUMMARY_PATH,
    index=False
)


SAMPLING_POLICY = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "maximum_windows_per_training_source":
        MAX_WINDOWS_PER_TRAIN_SOURCE,

    "selection_method":
        TRAINING_SAMPLING_METHOD,

    "selection_description":
        (
            "For each development-training source range, "
            "retain all windows if the range contains at most "
            "10,000 windows. Otherwise select exactly 10,000 "
            "window ordinals evenly across the chronological "
            "source range."
        ),

    "selection_uses_binary_target":
        False,

    "selection_uses_research_family":
        False,

    "same_selected_windows_across_training_seeds":
        True,

    "training_window_count_before_sampling":
        TOTAL_AVAILABLE_TRAIN_WINDOWS,

    "training_window_count_after_sampling":
        TOTAL_SAMPLED_TRAIN_WINDOWS,

    "validation_sampled":
        False,

    "known_test_sampled":
        False,

    "benign_test_sampled":
        False,

    "zero_day_test_sampled":
        False,

    "implementation_note":
        (
            "The 10,000-window source cap is a computational "
            "implementation choice and is not presented as a "
            "requirement of CICIoT2023 or the paper."
        )
}


with open(
    SAMPLING_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SAMPLING_POLICY,
        file,
        indent=4
    )


# ======================================================================
# 14 — BACK UP TO GOOGLE DRIVE
# ======================================================================

print("\n[14] Backing up sampling artifacts to Google Drive")
print("-" * 78)


DRIVE_SAMPLING_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/training_sampling/"
    "fold_01_DDoS"
)


DRIVE_SAMPLING_DIR.mkdir(
    parents=True,
    exist_ok=True
)


OUTPUT_FILES = [
    SAMPLING_PLAN_PATH,
    FAMILY_SUMMARY_PATH,
    LABEL_SUMMARY_PATH,
    SAMPLING_POLICY_PATH
]


for source_path in OUTPUT_FILES:

    shutil.copy2(
        source_path,
        DRIVE_SAMPLING_DIR
        /
        source_path.name
    )


DRIVE_OUTPUTS_EXIST = all(

    (
        DRIVE_SAMPLING_DIR
        /
        source_path.name
    ).exists()

    for source_path
    in OUTPUT_FILES
)


print(
    "Sampling artifacts backed up:",
    DRIVE_OUTPUTS_EXIST
)


# ======================================================================
# 15 — FINAL VALIDATION
# ======================================================================

A11_VALID = bool(

    CAP_RESPECTED

    and

    SAMPLE_NOT_GREATER_THAN_AVAILABLE

    and

    ALL_SMALL_SOURCES_PRESERVED

    and

    ALL_LARGE_SOURCES_CAPPED

    and

    HELD_OUT_ISOLATION_VALID

    and

    TOTAL_SAMPLE_MATCH

    and

    BENIGN_SAMPLE_MATCH

    and

    ATTACK_SAMPLE_MATCH

    and

    not SAMPLING_USES_BINARY_TARGET

    and

    not SAMPLING_USES_FAMILY_LABEL

    and

    not VALIDATION_SAMPLED

    and

    not KNOWN_TEST_SAMPLED

    and

    not BENIGN_TEST_SAMPLED

    and

    not ZERO_DAY_TEST_SAMPLED

    and

    DRIVE_OUTPUTS_EXIST
)


STEP_11_TRAIN_SAMPLING_VALID = (
    A11_VALID
)


print("\n[15] Recovery Step A11 validation")
print("-" * 78)

print(
    "Training sources              :",
    len(TRAIN_SAMPLING_PLAN),
    "/ 21"
)

print(
    "Available train windows       :",
    f"{TOTAL_AVAILABLE_TRAIN_WINDOWS:,}"
)

print(
    "Selected train windows        :",
    f"{TOTAL_SAMPLED_TRAIN_WINDOWS:,}"
)

print(
    "Maximum/source                :",
    f"{MAX_WINDOWS_PER_TRAIN_SOURCE:,}"
)

print(
    "All small sources preserved   :",
    ALL_SMALL_SOURCES_PRESERVED
)

print(
    "All large sources capped      :",
    ALL_LARGE_SOURCES_CAPPED
)

print(
    "Held-out isolation valid      :",
    HELD_OUT_ISOLATION_VALID
)

print(
    "Sampling independent of labels:",
    (
        not SAMPLING_USES_BINARY_TARGET
        and
        not SAMPLING_USES_FAMILY_LABEL
    )
)

print(
    "Non-training sets remain full :",
    (
        not VALIDATION_SAMPLED
        and
        not KNOWN_TEST_SAMPLED
        and
        not BENIGN_TEST_SAMPLED
        and
        not ZERO_DAY_TEST_SAMPLED
    )
)

print(
    "Artifacts backed up to Drive  :",
    DRIVE_OUTPUTS_EXIST
)


print("\n" + "=" * 78)

if A11_VALID:

    print(
        "✅ RECOVERY STEP A11 PASSED — "
        "A fixed, leakage-safe and reproducible "
        "training-window sampling plan is ready."
    )

else:

    print(
        "❌ RECOVERY STEP A11 FAILED — "
        "Do not create training tensors yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A11 — TRAINING-WINDOW SAMPLING PLAN
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying temporal-window state
------------------------------------------------------------------------------
A10 temporal manifest valid: True

[2] Training sampling policy
------------------------------------------------------------------------------
Maximum windows/source       : 10,000
Sampling method              : deterministic_temporal_coverage
Uses binary target           : False
Uses research-family label   : False
Same sample across seeds     : True

[3] Selecting development-training source ranges
------------------------------------------------------------------------------
Training source ranges: 21

[4] Building deterministic sampling plan
------------------------------------------------------------------------------

[5] Source-level training sampling plan
------------------------------------------------------------------------------

,source_attack_class,research_family,binary_target,available_windows,sampled_windows,selection_rule
0,Backdoor_Malware,Web,1,236,236,all_windows
1,Benign_Final,Benign,0,8006,8006,all_windows
2,BrowserHijacking,Web,1,287,287,all_windows
3,CommandInjection,Web,1,336,336,all_windows
4,DNS_Spoofing,Spoofing,1,6557,6557,all_windows
5,DictionaryBruteForce,BruteForce,1,742,742,all_windows
6,DoS-HTTP_Flood,DoS,1,84485,10000,evenly_spaced_window_ordinals
7,DoS-SYN_Flood,DoS,1,349747,10000,evenly_spaced_window_ordinals
8,DoS-TCP_Flood,DoS,1,143330,10000,evenly_spaced_window_ordinals
9,DoS-UDP_Flood,DoS,1,81725,10000,evenly_spaced_window_ordinals
10,MITM-ArpSpoofing,Spoofing,1,6374,6374,all_windows
11,Mirai-greeth_flood,Mirai,1,451,451,all_windows
12,Mirai-greip_flood,Mirai,1,910,910,all_windows
13,Mirai-udpplain,Mirai,1,652,652,all_windows
14,Recon-HostDiscovery,Recon,1,28873,10000,evenly_spaced_window_ordinals
15,Recon-OSScan,Recon,1,13884,10000,evenly_spaced_window_ordinals
16,Recon-PingSweep,Recon,1,170,170,all_windows
17,Recon-PortScan,Recon,1,15316,10000,evenly_spaced_window_ordinals
18,SqlInjection,Web,1,577,577,all_windows
19,VulnerabilityScan,Recon,1,38685,10000,evenly_spaced_window_ordinals
20,XSS,Web,1,279,279,all_windows

[6] Sampling-plan validation
------------------------------------------------------------------------------
Cap respected                 : True
Sample <= available           : True
All small sources fully kept  : True
All large sources capped      : True
Large sources requiring cap   : 8

[7] Held-out-family isolation
------------------------------------------------------------------------------
Sampled DDoS training windows: 0
Only development_train used   : True
Held-out isolation valid      : True

[8] Training sample size
------------------------------------------------------------------------------
Available training windows: 781,622
Sampled training windows  : 105,577
Sampling fraction         : 13.5074%

[9] Sampled windows by family
------------------------------------------------------------------------------

  research_family  source_classes  available_windows  sampled_windows
0           Recon               5              96928            40170
1             DoS               4             659287            40000
2        Spoofing               2              12931            12931
3          Benign               1               8006             8006
4           Mirai               3               2013             2013
5             Web               5               1715             1715
6      BruteForce               1                742              742

[10] Sampled windows by binary target
------------------------------------------------------------------------------

   binary_target  available_windows  sampled_windows
0              0               8006             8006
1              1             773616            97571

Benign sampled windows: 8,006
Attack sampled windows: 97,571
Attack : benign ratio : 12.187 : 1

[11] Reproducibility checks
------------------------------------------------------------------------------
Expected sampled total: 105,577 | Actual: 105,577 | Match: True
Expected benign: 8,006 | Actual: 8,006 | Match: True
Expected attack: 97,571 | Actual: 97,571 | Match: True

[12] Validation and test policy
------------------------------------------------------------------------------
Validation sampling : False
Known-test sampling : False
Benign-test sampling: False
Zero-day sampling   : False
All non-training partitions remain complete.

[13] Saving sampling artifacts
------------------------------------------------------------------------------

[14] Backing up sampling artifacts to Google Drive
------------------------------------------------------------------------------
Sampling artifacts backed up: True

[15] Recovery Step A11 validation
------------------------------------------------------------------------------
Training sources              : 21 / 21
Available train windows       : 781,622
Selected train windows        : 105,577
Maximum/source                : 10,000
All small sources preserved   : True
All large sources capped      : True
Held-out isolation valid      : True
Sampling independent of labels: True
Non-training sets remain full : True
Artifacts backed up to Drive  : True

==============================================================================
✅ RECOVERY STEP A11 PASSED — A fixed, leakage-safe and reproducible training-window sampling plan is ready.
==============================================================================

# Do only Recovery Step A12 — Build actual Fold-1 training tensors

In [ ]:
# ======================================================================
# RECOVERY STEP A12
# BUILD ACTUAL FOLD-1 TRAINING TENSOR SHARDS
#
# Shape per window: [8 timesteps, 75 features]
# Total selected windows: 105,577
# ======================================================================

from pathlib import Path
import hashlib
import json
import re
import shutil

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("RECOVERY STEP A12 — BUILD FOLD-1 TRAINING TENSOR SHARDS")
print("WINDOW = 8 | FEATURES = 75 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A11 STATE
# ======================================================================

print("\n[1] Verifying training-sampling state")
print("-" * 78)

required_variables = [
    "STEP_11_TRAIN_SAMPLING_VALID",
    "TRAIN_SAMPLING_PLAN"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A11."
    )

if not STEP_11_TRAIN_SAMPLING_VALID:
    raise RuntimeError(
        "Recovery Step A11 did not pass."
    )

print(
    "A11 sampling plan valid:",
    STEP_11_TRAIN_SAMPLING_VALID
)


# ======================================================================
# 2 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[2] Loading frozen Fold-1 preprocessing")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

FOLD_PREPROCESSING_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

PARAMETERS_PATH = (
    FOLD_PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

RETAINED_FEATURES_PATH = (
    FOLD_PREPROCESSING_DIR
    / "retained_features.json"
)


if not PARAMETERS_PATH.exists():
    raise RuntimeError(
        "preprocessing_parameters.csv is missing."
    )

if not RETAINED_FEATURES_PATH.exists():
    raise RuntimeError(
        "retained_features.json is missing."
    )


PREPROCESSING_PARAMETERS = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    RETAINED_FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:
    raise RuntimeError(
        f"Expected 75 retained features, "
        f"found {len(RETAINED_FEATURES)}."
    )


parameter_lookup = (
    PREPROCESSING_PARAMETERS
    .set_index("feature")
)


retained_params = (
    parameter_lookup
    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTATION_VALUES = (
    retained_params[
        "imputation_value"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (
    retained_params[
        "scaler_mean"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (
    retained_params[
        "scaler_std"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    len(RETAINED_FEATURES) == 75

    and

    np.isfinite(
        IMPUTATION_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen parameters valid:",
    PREPROCESSING_VALID
)


if not PREPROCESSING_VALID:
    raise RuntimeError(
        "Frozen preprocessing parameters are invalid."
    )


# ======================================================================
# 3 — HASH FROZEN PREPROCESSING ARTIFACTS
# ======================================================================

def sha256_file(path):

    hasher = hashlib.sha256()

    with open(
        path,
        "rb"
    ) as file:

        while True:

            chunk = file.read(
                1024 * 1024
            )

            if not chunk:
                break

            hasher.update(
                chunk
            )

    return hasher.hexdigest()


PARAMETERS_SHA256 = sha256_file(
    PARAMETERS_PATH
)

FEATURES_SHA256 = sha256_file(
    RETAINED_FEATURES_PATH
)


print(
    "Parameter SHA256:",
    PARAMETERS_SHA256
)

print(
    "Feature-list SHA256:",
    FEATURES_SHA256
)


# ======================================================================
# 4 — OUTPUT DIRECTORIES
# ======================================================================

LOCAL_MODEL_READY_DIR = (

    PROJECT_ROOT

    / "processed_data"

    / "model_ready"

    / "fold_01_DDoS"
)


LOCAL_SHARD_DIR = (
    LOCAL_MODEL_READY_DIR
    / "train_shards"
)


LOCAL_SHARD_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_MODEL_READY_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS"
)


DRIVE_SHARD_DIR = (
    DRIVE_MODEL_READY_DIR
    / "train_shards"
)


DRIVE_SHARD_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ======================================================================
# 5 — FIXED WINDOW CONFIGURATION
# ======================================================================

WINDOW_SIZE = 8
STRIDE = 8
FEATURE_COUNT = 75

EXPECTED_TOTAL_WINDOWS = 105_577
EXPECTED_BENIGN_WINDOWS = 8_006
EXPECTED_ATTACK_WINDOWS = 97_571

BATCH_SIZE = 50_000


print("\n[3] Tensor configuration")
print("-" * 78)

print(
    "Window size:",
    WINDOW_SIZE
)

print(
    "Stride:",
    STRIDE
)

print(
    "Features:",
    FEATURE_COUNT
)

print(
    "Expected training windows:",
    f"{EXPECTED_TOTAL_WINDOWS:,}"
)


# ======================================================================
# 6 — DETERMINISTIC WINDOW-ORDINAL FUNCTION
# ======================================================================

def deterministic_window_ordinals(
    available_windows,
    sampled_windows
):

    available_windows = int(
        available_windows
    )

    sampled_windows = int(
        sampled_windows
    )


    if sampled_windows < 0:

        raise ValueError(
            "sampled_windows cannot be negative."
        )


    if sampled_windows > available_windows:

        raise ValueError(
            "Cannot select more windows than available."
        )


    if sampled_windows == 0:

        return np.empty(
            0,
            dtype=np.int64
        )


    if sampled_windows == available_windows:

        return np.arange(
            available_windows,
            dtype=np.int64
        )


    if sampled_windows == 1:

        return np.array(
            [0],
            dtype=np.int64
        )


    # Exact deterministic integer spacing.
    # Includes the earliest and latest legal windows.
    ordinals = (

        np.arange(
            sampled_windows,
            dtype=np.int64
        )

        *

        (
            available_windows
            -
            1
        )

        //

        (
            sampled_windows
            -
            1
        )
    )


    if len(
        np.unique(
            ordinals
        )
    ) != sampled_windows:

        raise RuntimeError(
            "Deterministic spacing produced duplicate ordinals."
        )


    if not (
        np.diff(
            ordinals
        ) > 0
    ).all():

        raise RuntimeError(
            "Selected ordinals are not strictly increasing."
        )


    return ordinals


# ======================================================================
# 7 — BUILD EACH SOURCE SHARD
# ======================================================================

print("\n[4] Building 21 model-ready training shards")
print("-" * 78)


shard_records = []

selected_index_parts = []

TOTAL_CONSTRUCTED_WINDOWS = 0
TOTAL_SELECTED_RAW_NONFINITE = 0

ALL_SHARDS_FINITE = True
ALL_SELECTIONS_VALID = True
ALL_SHARDS_BACKED_UP = True


for shard_number, row in TRAIN_SAMPLING_PLAN.iterrows():

    source_class = row[
        "source_attack_class"
    ]

    family = row[
        "research_family"
    ]

    binary_target = int(
        row[
            "binary_target"
        ]
    )

    parquet_path = Path(
        row[
            "parquet_path"
        ]
    )

    partition_start = int(
        row[
            "partition_start_row"
        ]
    )

    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )

    available_windows = int(
        row[
            "available_windows"
        ]
    )

    sampled_windows = int(
        row[
            "sampled_windows"
        ]
    )


    print("\n" + "=" * 78)

    print(
        f"Shard {shard_number + 1:02d}/"
        f"{len(TRAIN_SAMPLING_PLAN):02d}"
    )

    print(
        "Source:",
        source_class
    )

    print(
        "Family:",
        family
    )

    print(
        "Target:",
        binary_target
    )

    print(
        "Available windows:",
        f"{available_windows:,}"
    )

    print(
        "Selected windows :",
        f"{sampled_windows:,}"
    )


    # --------------------------------------------------------------
    # Strict DDoS isolation
    # --------------------------------------------------------------

    if family == "DDoS":

        raise RuntimeError(
            "Held-out DDoS source found in training plan."
        )


    # --------------------------------------------------------------
    # Select deterministic window ordinals
    # --------------------------------------------------------------

    selected_ordinals = (
        deterministic_window_ordinals(
            available_windows,
            sampled_windows
        )
    )


    selected_starts = (

        partition_start

        +

        selected_ordinals
        *
        STRIDE
    )


    selected_ends = (
        selected_starts
        +
        WINDOW_SIZE
    )


    selection_valid = bool(

        len(
            selected_ordinals
        ) == sampled_windows

        and

        (
            sampled_windows == 0

            or

            (
                selected_starts.min()
                >=
                partition_start

                and

                selected_ends.max()
                <=
                partition_end
            )
        )
    )


    ALL_SELECTIONS_VALID &= (
        selection_valid
    )


    if not selection_valid:

        raise RuntimeError(
            f"Invalid window selection for "
            f"{source_class}."
        )


    # --------------------------------------------------------------
    # Allocate output tensor:
    # [windows, timesteps, features]
    # --------------------------------------------------------------

    X_shard = np.empty(
        (
            sampled_windows,
            WINDOW_SIZE,
            FEATURE_COUNT
        ),
        dtype=np.float32
    )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    absolute_position = 0

    next_selected_index = 0

    selected_raw_nonfinite = 0

    shard_max_abs_value = 0.0


    # Carry at most 7 rows between batches so an 8-row window
    # may safely cross an internal PyArrow batch boundary.
    carry_Z = np.empty(
        (
            0,
            FEATURE_COUNT
        ),
        dtype=np.float32
    )

    carry_nonfinite = np.empty(
        (
            0,
            FEATURE_COUNT
        ),
        dtype=bool
    )

    carry_start = None


    # --------------------------------------------------------------
    # Scan only this source's development-training range
    # --------------------------------------------------------------

    for batch in parquet_file.iter_batches(

        columns=
            RETAINED_FEATURES,

        batch_size=
            BATCH_SIZE
    ):

        batch_rows = (
            batch.num_rows
        )

        batch_start = (
            absolute_position
        )

        batch_end = (
            batch_start
            +
            batch_rows
        )

        absolute_position = (
            batch_end
        )


        # Completely before training range
        if batch_end <= partition_start:
            continue


        # Training range finished
        if batch_start >= partition_end:
            break


        local_start = max(
            0,
            partition_start
            -
            batch_start
        )


        local_end = min(
            batch_rows,
            partition_end
            -
            batch_start
        )


        if local_end <= local_start:
            continue


        current_absolute_start = (
            batch_start
            +
            local_start
        )


        sliced_batch = batch.slice(
            local_start,
            local_end
            -
            local_start
        )


        X = (
            sliced_batch
            .to_pandas()
            .to_numpy(
                dtype=np.float64,
                copy=True
            )
        )


        # ----------------------------------------------------------
        # Frozen mean imputation
        # ----------------------------------------------------------

        nonfinite_mask = (
            ~np.isfinite(
                X
            )
        )


        if nonfinite_mask.any():

            row_indices, feature_indices = (
                np.where(
                    nonfinite_mask
                )
            )


            X[
                row_indices,
                feature_indices
            ] = (
                IMPUTATION_VALUES[
                    feature_indices
                ]
            )


        # ----------------------------------------------------------
        # Frozen standardization
        # ----------------------------------------------------------

        Z64 = (
            X
            -
            SCALER_MEANS
        ) / SCALER_STDS


        if not np.isfinite(
            Z64
        ).all():

            raise RuntimeError(
                f"Non-finite float64 transform "
                f"in {source_class}."
            )


        with np.errstate(
            over="ignore",
            invalid="ignore"
        ):

            Z32 = Z64.astype(
                np.float32
            )


        if not np.isfinite(
            Z32
        ).all():

            raise RuntimeError(
                f"Non-finite float32 transform "
                f"in {source_class}."
            )


        # ----------------------------------------------------------
        # Join previous 7-row carry with this batch
        # ----------------------------------------------------------

        if len(
            carry_Z
        ) > 0:

            expected_current_start = (
                carry_start
                +
                len(
                    carry_Z
                )
            )


            if (
                expected_current_start
                !=
                current_absolute_start
            ):

                raise RuntimeError(
                    f"Non-contiguous batch stream in "
                    f"{source_class}."
                )


            combined_Z = np.concatenate(
                [
                    carry_Z,
                    Z32
                ],
                axis=0
            )


            combined_nonfinite = np.concatenate(
                [
                    carry_nonfinite,
                    nonfinite_mask
                ],
                axis=0
            )


            combined_start = (
                carry_start
            )

        else:

            combined_Z = Z32

            combined_nonfinite = (
                nonfinite_mask
            )

            combined_start = (
                current_absolute_start
            )


        combined_end = (
            combined_start
            +
            len(
                combined_Z
            )
        )


        # ----------------------------------------------------------
        # Extract every selected complete window currently available
        # ----------------------------------------------------------

        while (
            next_selected_index
            <
            sampled_windows
        ):

            window_start = int(
                selected_starts[
                    next_selected_index
                ]
            )

            window_end = (
                window_start
                +
                WINDOW_SIZE
            )


            # Need more rows from the next batch
            if window_end > combined_end:
                break


            if window_start < combined_start:

                raise RuntimeError(
                    f"Selected window fell behind "
                    f"stream buffer in {source_class}."
                )


            offset = (
                window_start
                -
                combined_start
            )


            window_Z = (
                combined_Z[
                    offset:
                    offset
                    +
                    WINDOW_SIZE
                ]
            )


            window_nonfinite = (
                combined_nonfinite[
                    offset:
                    offset
                    +
                    WINDOW_SIZE
                ]
            )


            if window_Z.shape != (
                WINDOW_SIZE,
                FEATURE_COUNT
            ):

                raise RuntimeError(
                    f"Incorrect window shape in "
                    f"{source_class}: "
                    f"{window_Z.shape}"
                )


            X_shard[
                next_selected_index
            ] = (
                window_Z
            )


            selected_raw_nonfinite += int(
                window_nonfinite.sum()
            )


            current_max = float(
                np.max(
                    np.abs(
                        window_Z
                    )
                )
            )


            shard_max_abs_value = max(
                shard_max_abs_value,
                current_max
            )


            next_selected_index += 1


        # ----------------------------------------------------------
        # Retain last 7 rows for possible cross-batch window
        # ----------------------------------------------------------

        keep_rows = min(
            WINDOW_SIZE - 1,
            len(
                combined_Z
            )
        )


        if keep_rows > 0:

            carry_Z = (
                combined_Z[
                    -keep_rows:
                ]
                .copy()
            )


            carry_nonfinite = (
                combined_nonfinite[
                    -keep_rows:
                ]
                .copy()
            )


            carry_start = (
                combined_end
                -
                keep_rows
            )

        else:

            carry_Z = np.empty(
                (
                    0,
                    FEATURE_COUNT
                ),
                dtype=np.float32
            )

            carry_nonfinite = np.empty(
                (
                    0,
                    FEATURE_COUNT
                ),
                dtype=bool
            )

            carry_start = None


    # --------------------------------------------------------------
    # Source-level final checks
    # --------------------------------------------------------------

    if (
        next_selected_index
        !=
        sampled_windows
    ):

        raise RuntimeError(
            f"{source_class}: expected "
            f"{sampled_windows:,} windows but "
            f"constructed {next_selected_index:,}."
        )


    shard_finite = bool(
        np.isfinite(
            X_shard
        ).all()
    )


    ALL_SHARDS_FINITE &= (
        shard_finite
    )


    if not shard_finite:

        raise RuntimeError(
            f"Non-finite tensor values found in "
            f"{source_class}."
        )


    # --------------------------------------------------------------
    # Save source tensor as .npy
    # This format can later be memory-mapped by PyTorch Dataset.
    # --------------------------------------------------------------

    safe_source_name = re.sub(
        r"[^A-Za-z0-9._-]+",
        "_",
        source_class
    )


    SHARD_PATH = (

        LOCAL_SHARD_DIR

        /
        (
            f"{shard_number + 1:02d}_"
            f"{safe_source_name}_X.npy"
        )
    )


    np.save(
        SHARD_PATH,
        X_shard,
        allow_pickle=False
    )


    if not SHARD_PATH.exists():

        raise RuntimeError(
            f"Shard file was not created: "
            f"{SHARD_PATH}"
        )


    # --------------------------------------------------------------
    # Immediately back up this tensor shard to Drive
    # --------------------------------------------------------------

    DRIVE_SHARD_PATH = (
        DRIVE_SHARD_DIR
        /
        SHARD_PATH.name
    )


    shutil.copy2(
        SHARD_PATH,
        DRIVE_SHARD_PATH
    )


    shard_backed_up = (
        DRIVE_SHARD_PATH.exists()
    )


    ALL_SHARDS_BACKED_UP &= (
        shard_backed_up
    )


    # --------------------------------------------------------------
    # Build selected-window audit index
    # --------------------------------------------------------------

    source_index_table = pd.DataFrame({

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            binary_target,

        "sample_index_within_source":
            np.arange(
                sampled_windows,
                dtype=np.int64
            ),

        "window_ordinal":
            selected_ordinals,

        "source_row_start":
            selected_starts,

        "source_row_end_exclusive":
            selected_ends,

        "tensor_shard":
            SHARD_PATH.name
    })


    selected_index_parts.append(
        source_index_table
    )


    shard_size_bytes = int(
        SHARD_PATH.stat().st_size
    )


    shard_records.append({

        "shard_number":
            shard_number + 1,

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            binary_target,

        "available_windows":
            available_windows,

        "selected_windows":
            sampled_windows,

        "tensor_shape":
            (
                f"{sampled_windows}x"
                f"{WINDOW_SIZE}x"
                f"{FEATURE_COUNT}"
            ),

        "dtype":
            "float32",

        "selected_raw_nonfinite_values":
            selected_raw_nonfinite,

        "maximum_absolute_transformed_value":
            shard_max_abs_value,

        "local_tensor_path":
            str(
                SHARD_PATH
            ),

        "drive_tensor_path":
            str(
                DRIVE_SHARD_PATH
            ),

        "file_size_bytes":
            shard_size_bytes,

        "all_tensor_values_finite":
            shard_finite,

        "drive_backup_exists":
            shard_backed_up
    })


    TOTAL_CONSTRUCTED_WINDOWS += (
        sampled_windows
    )


    TOTAL_SELECTED_RAW_NONFINITE += (
        selected_raw_nonfinite
    )


    print(
        "Constructed:",
        f"{sampled_windows:,}"
    )

    print(
        "Tensor shape:",
        X_shard.shape
    )

    print(
        "Raw non-finite values in selected windows:",
        f"{selected_raw_nonfinite:,}"
    )

    print(
        "Max |transformed value|:",
        f"{shard_max_abs_value:.6e}"
    )

    print(
        "All tensor values finite:",
        shard_finite
    )

    print(
        "Backed up to Drive:",
        shard_backed_up
    )


    # Release source tensor before next source
    del X_shard


# ======================================================================
# 8 — COMBINE AUDIT INDEX
# ======================================================================

print("\n[5] Building global selected-window index")
print("-" * 78)


TRAIN_TENSOR_SHARD_MANIFEST = pd.DataFrame(
    shard_records
)


SELECTED_WINDOW_INDEX = pd.concat(
    selected_index_parts,
    ignore_index=True
)


print(
    "Tensor shards:",
    len(
        TRAIN_TENSOR_SHARD_MANIFEST
    )
)

print(
    "Selected-window index rows:",
    f"{len(SELECTED_WINDOW_INDEX):,}"
)


# ======================================================================
# 9 — LABEL / FAMILY VALIDATION
# ======================================================================

print("\n[6] Constructed tensor validation")
print("-" * 78)


CONSTRUCTED_BENIGN_WINDOWS = int(

    TRAIN_TENSOR_SHARD_MANIFEST.loc[
        TRAIN_TENSOR_SHARD_MANIFEST[
            "binary_target"
        ] == 0,
        "selected_windows"
    ].sum()
)


CONSTRUCTED_ATTACK_WINDOWS = int(

    TRAIN_TENSOR_SHARD_MANIFEST.loc[
        TRAIN_TENSOR_SHARD_MANIFEST[
            "binary_target"
        ] == 1,
        "selected_windows"
    ].sum()
)


CONSTRUCTED_DDoS_WINDOWS = int(

    TRAIN_TENSOR_SHARD_MANIFEST.loc[
        TRAIN_TENSOR_SHARD_MANIFEST[
            "research_family"
        ] == "DDoS",
        "selected_windows"
    ].sum()
)


TOTAL_SHARD_BYTES = int(

    TRAIN_TENSOR_SHARD_MANIFEST[
        "file_size_bytes"
    ].sum()
)


TOTAL_SHARD_MIB = (
    TOTAL_SHARD_BYTES
    /
    (1024 ** 2)
)


print(
    "Constructed windows:",
    f"{TOTAL_CONSTRUCTED_WINDOWS:,}"
)

print(
    "Benign windows:",
    f"{CONSTRUCTED_BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{CONSTRUCTED_ATTACK_WINDOWS:,}"
)

print(
    "DDoS training windows:",
    CONSTRUCTED_DDoS_WINDOWS
)

print(
    "All tensor values finite:",
    ALL_SHARDS_FINITE
)

print(
    "Total tensor size:",
    f"{TOTAL_SHARD_MIB:.2f} MiB"
)


# ======================================================================
# 10 — VERIFY WINDOW INDEX BOUNDS
# ======================================================================

INDEX_BOUNDS_VALID = bool(

    (
        SELECTED_WINDOW_INDEX[
            "source_row_end_exclusive"
        ]
        -
        SELECTED_WINDOW_INDEX[
            "source_row_start"
        ]
        ==
        WINDOW_SIZE
    ).all()
)


ORDINAL_DUPLICATES = int(

    SELECTED_WINDOW_INDEX.duplicated(
        subset=[
            "source_attack_class",
            "window_ordinal"
        ]
    ).sum()
)


print(
    "Every selected window length = 8:",
    INDEX_BOUNDS_VALID
)

print(
    "Duplicate source/window ordinals:",
    ORDINAL_DUPLICATES
)


# ======================================================================
# 11 — SAVE MANIFEST + GLOBAL INDEX
# ======================================================================

print("\n[7] Saving model-ready metadata")
print("-" * 78)


SHARD_MANIFEST_PATH = (

    LOCAL_MODEL_READY_DIR

    / "fold_01_DDoS_train_tensor_shards.csv"
)


SELECTED_INDEX_PATH = (

    LOCAL_MODEL_READY_DIR

    / "fold_01_DDoS_selected_training_windows.csv"
)


BUILD_SUMMARY_PATH = (

    LOCAL_MODEL_READY_DIR

    / "fold_01_DDoS_training_tensor_build_summary.json"
)


TRAIN_TENSOR_SHARD_MANIFEST.to_csv(
    SHARD_MANIFEST_PATH,
    index=False
)


SELECTED_WINDOW_INDEX.to_csv(
    SELECTED_INDEX_PATH,
    index=False
)


BUILD_SUMMARY = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        WINDOW_SIZE,

    "stride":
        STRIDE,

    "feature_count":
        FEATURE_COUNT,

    "dtype":
        "float32",

    "tensor_layout":
        "[window, timestep, feature]",

    "training_shard_count":
        int(
            len(
                TRAIN_TENSOR_SHARD_MANIFEST
            )
        ),

    "training_window_count":
        int(
            TOTAL_CONSTRUCTED_WINDOWS
        ),

    "benign_training_windows":
        int(
            CONSTRUCTED_BENIGN_WINDOWS
        ),

    "attack_training_windows":
        int(
            CONSTRUCTED_ATTACK_WINDOWS
        ),

    "held_out_DDoS_training_windows":
        int(
            CONSTRUCTED_DDoS_WINDOWS
        ),

    "selected_raw_nonfinite_values_before_imputation":
        int(
            TOTAL_SELECTED_RAW_NONFINITE
        ),

    "all_model_ready_values_finite":
        bool(
            ALL_SHARDS_FINITE
        ),

    "input_clipping_applied":
        False,

    "timestamp_in_model_input":
        False,

    "preprocessing_parameters_sha256":
        PARAMETERS_SHA256,

    "retained_features_sha256":
        FEATURES_SHA256,

    "total_tensor_bytes":
        int(
            TOTAL_SHARD_BYTES
        ),

    "total_tensor_mib":
        float(
            TOTAL_SHARD_MIB
        ),

    "sampling_policy":
        (
            "At most 10,000 deterministic "
            "chronologically distributed windows "
            "per development-training source."
        )
}


with open(
    BUILD_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        BUILD_SUMMARY,
        file,
        indent=4
    )


# ======================================================================
# 12 — BACK UP METADATA TO DRIVE
# ======================================================================

for source_path in [
    SHARD_MANIFEST_PATH,
    SELECTED_INDEX_PATH,
    BUILD_SUMMARY_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_MODEL_READY_DIR
        /
        source_path.name
    )


METADATA_BACKED_UP = all(

    (
        DRIVE_MODEL_READY_DIR
        /
        source_path.name
    ).exists()

    for source_path in [
        SHARD_MANIFEST_PATH,
        SELECTED_INDEX_PATH,
        BUILD_SUMMARY_PATH
    ]
)


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

TOTAL_MATCH = (
    TOTAL_CONSTRUCTED_WINDOWS
    ==
    EXPECTED_TOTAL_WINDOWS
)


BENIGN_MATCH = (
    CONSTRUCTED_BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN_WINDOWS
)


ATTACK_MATCH = (
    CONSTRUCTED_ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK_WINDOWS
)


SHARD_COUNT_MATCH = (
    len(
        TRAIN_TENSOR_SHARD_MANIFEST
    ) == 21
)


INDEX_COUNT_MATCH = (
    len(
        SELECTED_WINDOW_INDEX
    )
    ==
    EXPECTED_TOTAL_WINDOWS
)


A12_VALID = bool(

    PREPROCESSING_VALID

    and

    ALL_SELECTIONS_VALID

    and

    ALL_SHARDS_FINITE

    and

    ALL_SHARDS_BACKED_UP

    and

    METADATA_BACKED_UP

    and

    TOTAL_MATCH

    and

    BENIGN_MATCH

    and

    ATTACK_MATCH

    and

    CONSTRUCTED_DDoS_WINDOWS == 0

    and

    SHARD_COUNT_MATCH

    and

    INDEX_COUNT_MATCH

    and

    INDEX_BOUNDS_VALID

    and

    ORDINAL_DUPLICATES == 0
)


STEP_12_TRAIN_TENSORS_VALID = (
    A12_VALID
)


print("\n[8] Recovery Step A12 validation")
print("-" * 78)

print(
    "Tensor shards                  :",
    len(
        TRAIN_TENSOR_SHARD_MANIFEST
    ),
    "/ 21"
)

print(
    "Constructed training windows   :",
    f"{TOTAL_CONSTRUCTED_WINDOWS:,}",
    "/ 105,577"
)

print(
    "Benign windows                 :",
    f"{CONSTRUCTED_BENIGN_WINDOWS:,}",
    "/ 8,006"
)

print(
    "Attack windows                 :",
    f"{CONSTRUCTED_ATTACK_WINDOWS:,}",
    "/ 97,571"
)

print(
    "DDoS training windows          :",
    CONSTRUCTED_DDoS_WINDOWS
)

print(
    "All selections valid           :",
    ALL_SELECTIONS_VALID
)

print(
    "All tensor values finite       :",
    ALL_SHARDS_FINITE
)

print(
    "Every window length = 8        :",
    INDEX_BOUNDS_VALID
)

print(
    "Duplicate selected windows     :",
    ORDINAL_DUPLICATES
)

print(
    "Tensor shards backed up        :",
    ALL_SHARDS_BACKED_UP
)

print(
    "Metadata backed up             :",
    METADATA_BACKED_UP
)

print(
    "Total tensor storage           :",
    f"{TOTAL_SHARD_MIB:.2f} MiB"
)


print("\n" + "=" * 78)

if A12_VALID:

    print(
        "✅ RECOVERY STEP A12 PASSED — "
        "Fold-1 model-ready training tensor shards "
        "were constructed and backed up."
    )

else:

    print(
        "❌ RECOVERY STEP A12 FAILED — "
        "Do not create the PyTorch Dataset yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A12 — BUILD FOLD-1 TRAINING TENSOR SHARDS
WINDOW = 8 | FEATURES = 75 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying training-sampling state
------------------------------------------------------------------------------
A11 sampling plan valid: True

[2] Loading frozen Fold-1 preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen parameters valid: True
Parameter SHA256: f0b19faf3575342cd4acd5252bda08e2baee321f03ff4296931e1c54027d176a
Feature-list SHA256: e5db01766ac945531ab1a5b59f7b3ab777467f59be03c74dbebf333f38ddcb25

[3] Tensor configuration
------------------------------------------------------------------------------
Window size: 8
Stride: 8
Features: 75
Expected training windows: 105,577

[4] Building 21 model-ready training shards
------------------------------------------------------------------------------

==============================================================================
Shard 01/21
Source: Backdoor_Malware
Family: Web
Target: 1
Available windows: 236
Selected windows : 236
Constructed: 236
Tensor shape: (236, 8, 75)
Raw non-finite values in selected windows: 0
Max |transformed value|: 9.332910e+01
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 02/21
Source: Benign_Final
Family: Benign
Target: 0
Available windows: 8,006
Selected windows : 8,006
Constructed: 8,006
Tensor shape: (8006, 8, 75)
Raw non-finite values in selected windows: 62
Max |transformed value|: 2.473136e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 03/21
Source: BrowserHijacking
Family: Web
Target: 1
Available windows: 287
Selected windows : 287
Constructed: 287
Tensor shape: (287, 8, 75)
Raw non-finite values in selected windows: 0
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 04/21
Source: CommandInjection
Family: Web
Target: 1
Available windows: 336
Selected windows : 336
Constructed: 336
Tensor shape: (336, 8, 75)
Raw non-finite values in selected windows: 0
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 05/21
Source: DNS_Spoofing
Family: Spoofing
Target: 1
Available windows: 6,557
Selected windows : 6,557
Constructed: 6,557
Tensor shape: (6557, 8, 75)
Raw non-finite values in selected windows: 104
Max |transformed value|: 1.009359e+03
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 06/21
Source: DictionaryBruteForce
Family: BruteForce
Target: 1
Available windows: 742
Selected windows : 742
Constructed: 742
Tensor shape: (742, 8, 75)
Raw non-finite values in selected windows: 6
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 07/21
Source: DoS-HTTP_Flood
Family: DoS
Target: 1
Available windows: 84,485
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 6,646
Max |transformed value|: 3.098163e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 08/21
Source: DoS-SYN_Flood
Family: DoS
Target: 1
Available windows: 349,747
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 4
Max |transformed value|: 7.366877e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 09/21
Source: DoS-TCP_Flood
Family: DoS
Target: 1
Available windows: 143,330
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 4
Max |transformed value|: 4.168452e+01
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 10/21
Source: DoS-UDP_Flood
Family: DoS
Target: 1
Available windows: 81,725
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 42
Max |transformed value|: 3.544537e+01
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 11/21
Source: MITM-ArpSpoofing
Family: Spoofing
Target: 1
Available windows: 6,374
Selected windows : 6,374
Constructed: 6,374
Tensor shape: (6374, 8, 75)
Raw non-finite values in selected windows: 42
Max |transformed value|: 1.674877e+03
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 12/21
Source: Mirai-greeth_flood
Family: Mirai
Target: 1
Available windows: 451
Selected windows : 451
Constructed: 451
Tensor shape: (451, 8, 75)
Raw non-finite values in selected windows: 0
Max |transformed value|: 4.427285e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 13/21
Source: Mirai-greip_flood
Family: Mirai
Target: 1
Available windows: 910
Selected windows : 910
Constructed: 910
Tensor shape: (910, 8, 75)
Raw non-finite values in selected windows: 14
Max |transformed value|: 1.002596e+03
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 14/21
Source: Mirai-udpplain
Family: Mirai
Target: 1
Available windows: 652
Selected windows : 652
Constructed: 652
Tensor shape: (652, 8, 75)
Raw non-finite values in selected windows: 4
Max |transformed value|: 8.242676e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 15/21
Source: Recon-HostDiscovery
Family: Recon
Target: 1
Available windows: 28,873
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 2
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 16/21
Source: Recon-OSScan
Family: Recon
Target: 1
Available windows: 13,884
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 70
Max |transformed value|: 8.261143e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 17/21
Source: Recon-PingSweep
Family: Recon
Target: 1
Available windows: 170
Selected windows : 170
Constructed: 170
Tensor shape: (170, 8, 75)
Raw non-finite values in selected windows: 0
Max |transformed value|: 3.544537e+01
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 18/21
Source: Recon-PortScan
Family: Recon
Target: 1
Available windows: 15,316
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 12
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 19/21
Source: SqlInjection
Family: Web
Target: 1
Available windows: 577
Selected windows : 577
Constructed: 577
Tensor shape: (577, 8, 75)
Raw non-finite values in selected windows: 6
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 20/21
Source: VulnerabilityScan
Family: Recon
Target: 1
Available windows: 38,685
Selected windows : 10,000
Constructed: 10,000
Tensor shape: (10000, 8, 75)
Raw non-finite values in selected windows: 444
Max |transformed value|: 4.451240e+02
All tensor values finite: True
Backed up to Drive: True

==============================================================================
Shard 21/21
Source: XSS
Family: Web
Target: 1
Available windows: 279
Selected windows : 279
Constructed: 279
Tensor shape: (279, 8, 75)
Raw non-finite values in selected windows: 0
Max |transformed value|: 1.483280e+02
All tensor values finite: True
Backed up to Drive: True

[5] Building global selected-window index
------------------------------------------------------------------------------
Tensor shards: 21
Selected-window index rows: 105,577

[6] Constructed tensor validation
------------------------------------------------------------------------------
Constructed windows: 105,577
Benign windows: 8,006
Attack windows: 97,571
DDoS training windows: 0
All tensor values finite: True
Total tensor size: 241.65 MiB
Every selected window length = 8: True
Duplicate source/window ordinals: 0

[7] Saving model-ready metadata
------------------------------------------------------------------------------

[8] Recovery Step A12 validation
------------------------------------------------------------------------------
Tensor shards                  : 21 / 21
Constructed training windows   : 105,577 / 105,577
Benign windows                 : 8,006 / 8,006
Attack windows                 : 97,571 / 97,571
DDoS training windows          : 0
All selections valid           : True
All tensor values finite       : True
Every window length = 8        : True
Duplicate selected windows     : 0
Tensor shards backed up        : True
Metadata backed up             : True
Total tensor storage           : 241.65 MiB

==============================================================================
✅ RECOVERY STEP A12 PASSED — Fold-1 model-ready training tensor shards were constructed and backed up.
==============================================================================

# Do only Recovery Step A13 — PyTorch Dataset + DataLoader

In [ ]:
# ======================================================================
# RECOVERY STEP A13
# BUILD MEMORY-MAPPED PYTORCH DATASET + DATALOADER
#
# NO MODEL TRAINING IN THIS STEP
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import torch

from torch.utils.data import (
    Dataset,
    DataLoader
)


print("=" * 78)
print("RECOVERY STEP A13 — PYTORCH DATASET + DATALOADER")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A12 STATE
# ======================================================================

print("\n[1] Verifying A12 state")
print("-" * 78)

if (
    "STEP_12_TRAIN_TENSORS_VALID"
    in globals()
):

    print(
        "A12 tensor build valid:",
        STEP_12_TRAIN_TENSORS_VALID
    )

    if not STEP_12_TRAIN_TENSORS_VALID:

        raise RuntimeError(
            "Recovery Step A12 did not pass."
        )

else:

    print(
        "A12 runtime variable not found."
    )

    print(
        "Will verify directly from saved artifacts."
    )


# ======================================================================
# 2 — LOCATE SAVED A12 ARTIFACTS
# ======================================================================

print("\n[2] Loading tensor-shard metadata")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

MODEL_READY_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
)

SHARD_MANIFEST_PATH = (
    MODEL_READY_DIR
    / "fold_01_DDoS_train_tensor_shards.csv"
)

BUILD_SUMMARY_PATH = (
    MODEL_READY_DIR
    / "fold_01_DDoS_training_tensor_build_summary.json"
)


if not SHARD_MANIFEST_PATH.exists():

    raise RuntimeError(
        "Training tensor shard manifest is missing."
    )


if not BUILD_SUMMARY_PATH.exists():

    raise RuntimeError(
        "Training tensor build summary is missing."
    )


SHARD_MANIFEST = pd.read_csv(
    SHARD_MANIFEST_PATH
)


with open(
    BUILD_SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as file:

    BUILD_SUMMARY = json.load(
        file
    )


print(
    "Tensor shards:",
    len(
        SHARD_MANIFEST
    )
)

print(
    "Training windows:",
    f"{int(BUILD_SUMMARY['training_window_count']):,}"
)

print(
    "Window size:",
    BUILD_SUMMARY[
        "window_size"
    ]
)

print(
    "Feature count:",
    BUILD_SUMMARY[
        "feature_count"
    ]
)


if len(SHARD_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 tensor shards."
    )


if int(
    BUILD_SUMMARY[
        "training_window_count"
    ]
) != 105_577:

    raise RuntimeError(
        "Expected 105,577 training windows."
    )


# ======================================================================
# 3 — RESOLVE LOCAL OR DRIVE SHARD PATHS
# ======================================================================

print("\n[3] Resolving tensor shard files")
print("-" * 78)


def resolve_shard_path(row):

    local_path = Path(
        row[
            "local_tensor_path"
        ]
    )

    drive_path = Path(
        row[
            "drive_tensor_path"
        ]
    )


    if local_path.exists():

        return local_path


    if drive_path.exists():

        return drive_path


    raise FileNotFoundError(
        "Tensor shard missing from both local "
        f"storage and Drive:\n{local_path}\n{drive_path}"
    )


RESOLVED_SHARD_PATHS = [

    resolve_shard_path(row)

    for _, row
    in SHARD_MANIFEST.iterrows()
]


print(
    "Resolved shards:",
    len(
        RESOLVED_SHARD_PATHS
    ),
    "/ 21"
)


# ======================================================================
# 4 — DEFINE MEMORY-MAPPED DATASET
# ======================================================================

print("\n[4] Creating memory-mapped PyTorch Dataset")
print("-" * 78)


class ShardedTemporalDataset(Dataset):

    def __init__(
        self,
        shard_manifest,
        shard_paths
    ):

        self.manifest = (
            shard_manifest
            .reset_index(drop=True)
            .copy()
        )


        self.shard_paths = [
            Path(path)
            for path
            in shard_paths
        ]


        self.window_counts = (

            self.manifest[
                "selected_windows"
            ]
            .astype(np.int64)
            .to_numpy()
        )


        self.cumulative_counts = (
            np.cumsum(
                self.window_counts
            )
        )


        self.total_windows = int(
            self.cumulative_counts[-1]
        )


        self.targets = (

            self.manifest[
                "binary_target"
            ]
            .astype(np.int64)
            .to_numpy()
        )


        # --------------------------------------------------------------
        # Memory map each .npy file.
        # This does NOT load the complete tensors into RAM.
        # --------------------------------------------------------------

        self.shards = [

            np.load(
                path,
                mmap_mode="r",
                allow_pickle=False
            )

            for path
            in self.shard_paths
        ]


        # --------------------------------------------------------------
        # Validate every shard
        # --------------------------------------------------------------

        for index, shard in enumerate(
            self.shards
        ):

            expected_windows = int(
                self.window_counts[
                    index
                ]
            )


            expected_shape = (
                expected_windows,
                8,
                75
            )


            if shard.shape != expected_shape:

                raise RuntimeError(
                    f"Shard {index + 1} shape mismatch: "
                    f"expected {expected_shape}, "
                    f"found {shard.shape}."
                )


            if shard.dtype != np.float32:

                raise RuntimeError(
                    f"Shard {index + 1} has dtype "
                    f"{shard.dtype}; expected float32."
                )


    def __len__(self):

        return self.total_windows


    def _locate_index(
        self,
        global_index
    ):

        if global_index < 0:

            global_index += (
                self.total_windows
            )


        if (
            global_index < 0
            or
            global_index >= self.total_windows
        ):

            raise IndexError(
                "Dataset index out of range."
            )


        shard_index = int(

            np.searchsorted(
                self.cumulative_counts,
                global_index,
                side="right"
            )
        )


        previous_count = (

            0

            if shard_index == 0

            else int(
                self.cumulative_counts[
                    shard_index - 1
                ]
            )
        )


        local_index = int(
            global_index
            -
            previous_count
        )


        return (
            shard_index,
            local_index
        )


    def __getitem__(
        self,
        global_index
    ):

        shard_index, local_index = (
            self._locate_index(
                global_index
            )
        )


        # --------------------------------------------------------------
        # Copy only ONE requested 8x75 window from the memory map.
        # --------------------------------------------------------------

        window = np.array(

            self.shards[
                shard_index
            ][
                local_index
            ],

            dtype=np.float32,

            copy=True
        )


        target = np.float32(

            self.targets[
                shard_index
            ]
        )


        X_tensor = (
            torch.from_numpy(
                window
            )
        )


        y_tensor = torch.tensor(
            target,
            dtype=torch.float32
        )


        return (
            X_tensor,
            y_tensor
        )


# ======================================================================
# 5 — INSTANTIATE DATASET
# ======================================================================

TRAIN_DATASET = ShardedTemporalDataset(
    SHARD_MANIFEST,
    RESOLVED_SHARD_PATHS
)


print(
    "Dataset windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Memory-mapped shards:",
    sum(
        isinstance(
            shard,
            np.memmap
        )
        for shard
        in TRAIN_DATASET.shards
    ),
    "/",
    len(
        TRAIN_DATASET.shards
    )
)


# ======================================================================
# 6 — VERIFY LABEL COUNTS WITHOUT LOADING TENSORS
# ======================================================================

print("\n[5] Dataset label verification")
print("-" * 78)


BENIGN_WINDOWS = int(

    SHARD_MANIFEST.loc[
        SHARD_MANIFEST[
            "binary_target"
        ] == 0,
        "selected_windows"
    ].sum()
)


ATTACK_WINDOWS = int(

    SHARD_MANIFEST.loc[
        SHARD_MANIFEST[
            "binary_target"
        ] == 1,
        "selected_windows"
    ].sum()
)


DDoS_WINDOWS = int(

    SHARD_MANIFEST.loc[
        SHARD_MANIFEST[
            "research_family"
        ] == "DDoS",
        "selected_windows"
    ].sum()
)


print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDoS_WINDOWS
)


# ======================================================================
# 7 — VERIFY INDIVIDUAL DATASET ITEMS
# ======================================================================

print("\n[6] Individual-sample verification")
print("-" * 78)


TEST_INDICES = [
    0,
    len(TRAIN_DATASET) // 2,
    len(TRAIN_DATASET) - 1
]


INDIVIDUAL_SAMPLES_VALID = True


for index in TEST_INDICES:

    X_sample, y_sample = (
        TRAIN_DATASET[
            index
        ]
    )


    sample_valid = bool(

        tuple(
            X_sample.shape
        ) == (8, 75)

        and

        X_sample.dtype
        ==
        torch.float32

        and

        y_sample.dtype
        ==
        torch.float32

        and

        torch.isfinite(
            X_sample
        ).all()
    )


    INDIVIDUAL_SAMPLES_VALID &= (
        sample_valid
    )


    print(
        f"Index {index:>7,}"
        f" | X={tuple(X_sample.shape)}"
        f" | y={float(y_sample):.0f}"
        f" | finite={bool(torch.isfinite(X_sample).all())}"
    )


# ======================================================================
# 8 — REPRODUCIBLE TRAINING DATALOADER
# ======================================================================

print("\n[7] Creating reproducible DataLoader")
print("-" * 78)


PRIMARY_SEED = 13
BATCH_SIZE = 256


loader_generator = (
    torch.Generator()
)

loader_generator.manual_seed(
    PRIMARY_SEED
)


TRAIN_LOADER = DataLoader(

    TRAIN_DATASET,

    batch_size=
        BATCH_SIZE,

    shuffle=
        True,

    num_workers=
        0,

    pin_memory=
        torch.cuda.is_available(),

    drop_last=
        False,

    generator=
        loader_generator
)


print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Shuffle:",
    True
)

print(
    "Random seed:",
    PRIMARY_SEED
)

print(
    "num_workers:",
    0
)

print(
    "pin_memory:",
    torch.cuda.is_available()
)

print(
    "Batches/epoch:",
    len(
        TRAIN_LOADER
    )
)


# ======================================================================
# 9 — LOAD ONE REAL BATCH
# ======================================================================

print("\n[8] First DataLoader batch")
print("-" * 78)


X_batch, y_batch = next(
    iter(
        TRAIN_LOADER
    )
)


BATCH_VALUES_FINITE = bool(
    torch.isfinite(
        X_batch
    ).all()
)


BATCH_SHAPE_VALID = bool(

    X_batch.ndim == 3

    and

    X_batch.shape[1] == 8

    and

    X_batch.shape[2] == 75

    and

    y_batch.ndim == 1

    and

    X_batch.shape[0]
    ==
    y_batch.shape[0]
)


print(
    "X batch shape:",
    tuple(
        X_batch.shape
    )
)

print(
    "y batch shape:",
    tuple(
        y_batch.shape
    )
)

print(
    "X dtype:",
    X_batch.dtype
)

print(
    "y dtype:",
    y_batch.dtype
)

print(
    "All batch values finite:",
    BATCH_VALUES_FINITE
)

print(
    "Benign in first batch:",
    int(
        (
            y_batch == 0
        ).sum()
    )
)

print(
    "Attack in first batch:",
    int(
        (
            y_batch == 1
        ).sum()
    )
)


batch_memory_mib = (

    X_batch.numel()
    *
    X_batch.element_size()
    /
    (1024 ** 2)
)


print(
    "X batch memory:",
    f"{batch_memory_mib:.3f} MiB"
)


# ======================================================================
# 10 — DEVICE CHECK
# ======================================================================

print("\n[9] Device readiness")
print("-" * 78)


DEVICE = torch.device(

    "cuda"

    if torch.cuda.is_available()

    else "cpu"
)


print(
    "Training device:",
    DEVICE
)


if torch.cuda.is_available():

    print(
        "GPU:",
        torch.cuda.get_device_name(
            0
        )
    )


# ======================================================================
# 11 — SAVE DATASET / LOADER POLICY
# ======================================================================

print("\n[10] Saving PyTorch dataset policy")
print("-" * 78)


PYTORCH_DIR = (

    MODEL_READY_DIR

    / "pytorch"
)


PYTORCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DATASET_POLICY_PATH = (

    PYTORCH_DIR

    / "fold_01_DDoS_pytorch_dataset_policy.json"
)


VALIDATION_PATH = (

    PYTORCH_DIR

    / "fold_01_DDoS_pytorch_dataset_validation.json"
)


DATASET_POLICY = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "dataset_type":
        "memory_mapped_sharded_temporal_dataset",

    "training_windows":
        len(
            TRAIN_DATASET
        ),

    "tensor_shards":
        len(
            TRAIN_DATASET.shards
        ),

    "window_size":
        8,

    "feature_count":
        75,

    "tensor_dtype":
        "float32",

    "batch_size":
        BATCH_SIZE,

    "shuffle":
        True,

    "shuffle_seed":
        PRIMARY_SEED,

    "num_workers":
        0,

    "pin_memory":
        bool(
            torch.cuda.is_available()
        ),

    "full_training_tensor_loaded_into_ram":
        False,

    "memory_mapping_enabled":
        True,

    "timestamp_in_model_input":
        False,

    "held_out_DDoS_training_windows":
        DDoS_WINDOWS,

    "training_data_clipped":
        False
}


with open(
    DATASET_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        DATASET_POLICY,
        file,
        indent=4
    )


DATASET_VALIDATION = {

    "dataset_length":
        len(
            TRAIN_DATASET
        ),

    "expected_dataset_length":
        105_577,

    "memory_mapped_shards":
        sum(
            isinstance(
                shard,
                np.memmap
            )
            for shard
            in TRAIN_DATASET.shards
        ),

    "expected_shards":
        21,

    "benign_windows":
        BENIGN_WINDOWS,

    "attack_windows":
        ATTACK_WINDOWS,

    "DDoS_training_windows":
        DDoS_WINDOWS,

    "individual_samples_valid":
        bool(
            INDIVIDUAL_SAMPLES_VALID
        ),

    "first_batch_shape":
        list(
            X_batch.shape
        ),

    "first_batch_finite":
        BATCH_VALUES_FINITE,

    "device":
        str(
            DEVICE
        )
}


with open(
    VALIDATION_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        DATASET_VALIDATION,
        file,
        indent=4
    )


# ======================================================================
# 12 — BACK UP POLICY TO DRIVE
# ======================================================================

DRIVE_PYTORCH_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS/pytorch"
)


DRIVE_PYTORCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in [
    DATASET_POLICY_PATH,
    VALIDATION_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_PYTORCH_DIR
        /
        source_path.name
    )


DRIVE_POLICY_BACKUP_VALID = all(

    (
        DRIVE_PYTORCH_DIR
        /
        path.name
    ).exists()

    for path
    in [
        DATASET_POLICY_PATH,
        VALIDATION_PATH
    ]
)


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

MEMMAP_SHARDS = sum(

    isinstance(
        shard,
        np.memmap
    )

    for shard
    in TRAIN_DATASET.shards
)


DATASET_LENGTH_VALID = (
    len(
        TRAIN_DATASET
    )
    ==
    105_577
)


LABEL_COUNTS_VALID = bool(

    BENIGN_WINDOWS == 8_006

    and

    ATTACK_WINDOWS == 97_571
)


A13_VALID = bool(

    DATASET_LENGTH_VALID

    and

    MEMMAP_SHARDS == 21

    and

    LABEL_COUNTS_VALID

    and

    DDoS_WINDOWS == 0

    and

    INDIVIDUAL_SAMPLES_VALID

    and

    BATCH_SHAPE_VALID

    and

    BATCH_VALUES_FINITE

    and

    DRIVE_POLICY_BACKUP_VALID
)


STEP_13_PYTORCH_DATA_VALID = (
    A13_VALID
)


print("\n[11] Recovery Step A13 validation")
print("-" * 78)

print(
    "Dataset windows               :",
    f"{len(TRAIN_DATASET):,}",
    "/ 105,577"
)

print(
    "Memory-mapped tensor shards   :",
    MEMMAP_SHARDS,
    "/ 21"
)

print(
    "Benign windows                :",
    f"{BENIGN_WINDOWS:,}",
    "/ 8,006"
)

print(
    "Attack windows                :",
    f"{ATTACK_WINDOWS:,}",
    "/ 97,571"
)

print(
    "DDoS training windows         :",
    DDoS_WINDOWS
)

print(
    "Individual samples valid      :",
    INDIVIDUAL_SAMPLES_VALID
)

print(
    "Batch shape valid             :",
    BATCH_SHAPE_VALID
)

print(
    "Batch values finite           :",
    BATCH_VALUES_FINITE
)

print(
    "Dataset policy backed up      :",
    DRIVE_POLICY_BACKUP_VALID
)


print("\n" + "=" * 78)

if A13_VALID:

    print(
        "✅ RECOVERY STEP A13 PASSED — "
        "The Fold-1 memory-mapped PyTorch "
        "Dataset and DataLoader are ready."
    )

else:

    print(
        "❌ RECOVERY STEP A13 FAILED — "
        "Do not start model training yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A13 — PYTORCH DATASET + DATALOADER
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying A12 state
------------------------------------------------------------------------------
A12 runtime variable not found.
Will verify directly from saved artifacts.

[2] Loading tensor-shard metadata
------------------------------------------------------------------------------

RuntimeError: Training tensor shard manifest is missing.

# Recovery Step A13-R1 — Restore A12 metadata from Drive

In [ ]:
# ======================================================================
# RECOVERY STEP A13-R1
# RESTORE A12 MODEL-READY METADATA FROM GOOGLE DRIVE
# ======================================================================

from pathlib import Path
import shutil
import pandas as pd
import json


print("=" * 78)
print("RECOVERY STEP A13-R1 — RESTORE A12 METADATA FROM DRIVE")
print("=" * 78)


# ======================================================================
# 1 — DEFINE DRIVE + LOCAL LOCATIONS
# ======================================================================

DRIVE_MODEL_READY_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS"
)


DRIVE_SHARD_DIR = (
    DRIVE_MODEL_READY_DIR
    / "train_shards"
)


LOCAL_MODEL_READY_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/model_ready/"
    "fold_01_DDoS"
)


LOCAL_MODEL_READY_DIR.mkdir(
    parents=True,
    exist_ok=True
)


SHARD_MANIFEST_NAME = (
    "fold_01_DDoS_train_tensor_shards.csv"
)

SELECTED_INDEX_NAME = (
    "fold_01_DDoS_selected_training_windows.csv"
)

BUILD_SUMMARY_NAME = (
    "fold_01_DDoS_training_tensor_build_summary.json"
)


# ======================================================================
# 2 — CHECK DRIVE BACKUP
# ======================================================================

print("\n[1] Checking Google Drive A12 backup")
print("-" * 78)


expected_drive_files = [
    DRIVE_MODEL_READY_DIR / SHARD_MANIFEST_NAME,
    DRIVE_MODEL_READY_DIR / SELECTED_INDEX_NAME,
    DRIVE_MODEL_READY_DIR / BUILD_SUMMARY_NAME
]


for path in expected_drive_files:

    print(
        f"{path.name:<55}",
        path.exists()
    )


print(
    "\nDrive shard folder exists:",
    DRIVE_SHARD_DIR.exists()
)


drive_shards = sorted(
    DRIVE_SHARD_DIR.glob(
        "*_X.npy"
    )
) if DRIVE_SHARD_DIR.exists() else []


print(
    "Tensor shards found in Drive:",
    len(drive_shards)
)


# ======================================================================
# 3 — STRICT BACKUP CHECK
# ======================================================================

DRIVE_METADATA_COMPLETE = all(
    path.exists()
    for path
    in expected_drive_files
)


DRIVE_SHARDS_COMPLETE = (
    len(drive_shards) == 21
)


if not DRIVE_METADATA_COMPLETE:

    raise RuntimeError(
        "A12 metadata backup is incomplete in Drive."
    )


if not DRIVE_SHARDS_COMPLETE:

    raise RuntimeError(
        f"Expected 21 tensor shards in Drive, "
        f"found {len(drive_shards)}."
    )


# ======================================================================
# 4 — RESTORE ONLY SMALL METADATA FILES LOCALLY
# ======================================================================

print("\n[2] Restoring small metadata files locally")
print("-" * 78)


for drive_path in expected_drive_files:

    local_path = (
        LOCAL_MODEL_READY_DIR
        / drive_path.name
    )

    shutil.copy2(
        drive_path,
        local_path
    )

    print(
        "Restored:",
        local_path
    )


# ======================================================================
# 5 — LOAD + VERIFY BUILD SUMMARY
# ======================================================================

print("\n[3] Verifying restored A12 metadata")
print("-" * 78)


LOCAL_SHARD_MANIFEST_PATH = (
    LOCAL_MODEL_READY_DIR
    / SHARD_MANIFEST_NAME
)


LOCAL_BUILD_SUMMARY_PATH = (
    LOCAL_MODEL_READY_DIR
    / BUILD_SUMMARY_NAME
)


SHARD_MANIFEST = pd.read_csv(
    LOCAL_SHARD_MANIFEST_PATH
)


with open(
    LOCAL_BUILD_SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as file:

    BUILD_SUMMARY = json.load(
        file
    )


print(
    "Manifest rows:",
    len(SHARD_MANIFEST)
)

print(
    "Training windows:",
    f"{int(BUILD_SUMMARY['training_window_count']):,}"
)

print(
    "Benign windows:",
    f"{int(BUILD_SUMMARY['benign_training_windows']):,}"
)

print(
    "Attack windows:",
    f"{int(BUILD_SUMMARY['attack_training_windows']):,}"
)

print(
    "DDoS training windows:",
    int(
        BUILD_SUMMARY[
            "held_out_DDoS_training_windows"
        ]
    )
)


# ======================================================================
# 6 — VERIFY EVERY DRIVE SHARD AGAINST MANIFEST
# ======================================================================

print("\n[4] Verifying all 21 Drive tensor shards")
print("-" * 78)


missing_shards = []


for _, row in SHARD_MANIFEST.iterrows():

    shard_name = Path(
        row[
            "drive_tensor_path"
        ]
    ).name


    drive_shard_path = (
        DRIVE_SHARD_DIR
        / shard_name
    )


    if not drive_shard_path.exists():

        missing_shards.append(
            shard_name
        )


print(
    "Missing Drive shards:",
    len(missing_shards)
)


if missing_shards:

    for name in missing_shards:

        print(
            " -",
            name
        )


# ======================================================================
# 7 — FINAL VALIDATION
# ======================================================================

A13_R1_VALID = bool(

    DRIVE_METADATA_COMPLETE

    and

    DRIVE_SHARDS_COMPLETE

    and

    len(
        SHARD_MANIFEST
    ) == 21

    and

    int(
        BUILD_SUMMARY[
            "training_window_count"
        ]
    ) == 105_577

    and

    int(
        BUILD_SUMMARY[
            "benign_training_windows"
        ]
    ) == 8_006

    and

    int(
        BUILD_SUMMARY[
            "attack_training_windows"
        ]
    ) == 97_571

    and

    int(
        BUILD_SUMMARY[
            "held_out_DDoS_training_windows"
        ]
    ) == 0

    and

    len(
        missing_shards
    ) == 0
)


print("\n[5] Recovery Step A13-R1 validation")
print("-" * 78)

print(
    "A12 metadata complete in Drive :",
    DRIVE_METADATA_COMPLETE
)

print(
    "21 tensor shards in Drive      :",
    DRIVE_SHARDS_COMPLETE
)

print(
    "Manifest rows                  :",
    len(SHARD_MANIFEST),
    "/ 21"
)

print(
    "Training windows               :",
    f"{int(BUILD_SUMMARY['training_window_count']):,}",
    "/ 105,577"
)

print(
    "Benign windows                 :",
    f"{int(BUILD_SUMMARY['benign_training_windows']):,}",
    "/ 8,006"
)

print(
    "Attack windows                 :",
    f"{int(BUILD_SUMMARY['attack_training_windows']):,}",
    "/ 97,571"
)

print(
    "DDoS training windows          :",
    int(
        BUILD_SUMMARY[
            "held_out_DDoS_training_windows"
        ]
    )
)

print(
    "Missing tensor shards          :",
    len(missing_shards)
)


print("\n" + "=" * 78)

if A13_R1_VALID:

    print(
        "✅ RECOVERY STEP A13-R1 PASSED — "
        "A12 artifacts are safe in Drive and "
        "the required metadata was restored locally."
    )

else:

    print(
        "❌ RECOVERY STEP A13-R1 FAILED — "
        "Do not rerun A12 yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A13-R1 — RESTORE A12 METADATA FROM DRIVE
==============================================================================

[1] Checking Google Drive A12 backup
------------------------------------------------------------------------------
fold_01_DDoS_train_tensor_shards.csv                    False
fold_01_DDoS_selected_training_windows.csv              False
fold_01_DDoS_training_tensor_build_summary.json         False

Drive shard folder exists: False
Tensor shards found in Drive: 0

RuntimeError: A12 metadata backup is incomplete in Drive.

# Recovery Step A13-R2 — Check current Google Drive mount

In [ ]:
# ======================================================================
# RECOVERY STEP A13-R2
# DIAGNOSE CURRENT GOOGLE DRIVE MOUNT / ACCOUNT
# ======================================================================

from pathlib import Path


print("=" * 78)
print("RECOVERY STEP A13-R2 — DIAGNOSE GOOGLE DRIVE MOUNT")
print("=" * 78)


# ======================================================================
# 1 — BASIC DRIVE PATH CHECK
# ======================================================================

DRIVE_ROOT = Path("/content/drive")
MYDRIVE_ROOT = Path("/content/drive/MyDrive")

BACKUP_ROOT = (
    MYDRIVE_ROOT
    / "ZeroDay_IoT_Research_Backup"
)

MODEL_READY_ROOT = (
    BACKUP_ROOT
    / "processed_data"
    / "model_ready"
)

FOLD1_MODEL_READY = (
    MODEL_READY_ROOT
    / "fold_01_DDoS"
)

TRAIN_SHARDS_DIR = (
    FOLD1_MODEL_READY
    / "train_shards"
)


print("\n[1] Drive mount paths")
print("-" * 78)

print(
    "/content/drive exists:",
    DRIVE_ROOT.exists()
)

print(
    "/content/drive/MyDrive exists:",
    MYDRIVE_ROOT.exists()
)

print(
    "Backup root exists:",
    BACKUP_ROOT.exists()
)

print(
    "model_ready exists:",
    MODEL_READY_ROOT.exists()
)

print(
    "fold_01_DDoS exists:",
    FOLD1_MODEL_READY.exists()
)

print(
    "train_shards exists:",
    TRAIN_SHARDS_DIR.exists()
)


# ======================================================================
# 2 — SHOW CURRENT MyDrive ROOT CONTENTS
# ======================================================================

print("\n[2] Current MyDrive root contents")
print("-" * 78)

if MYDRIVE_ROOT.exists():

    root_items = sorted(
        MYDRIVE_ROOT.iterdir(),
        key=lambda p: p.name.lower()
    )

    print(
        "Root items found:",
        len(root_items)
    )

    for item in root_items[:50]:

        print(
            "[DIR] " if item.is_dir() else "[FILE]",
            item.name
        )

else:

    print(
        "MyDrive is not currently available."
    )


# ======================================================================
# 3 — IF BACKUP ROOT EXISTS, INSPECT ITS MAIN CONTENTS
# ======================================================================

print("\n[3] Backup-root inspection")
print("-" * 78)

if BACKUP_ROOT.exists():

    backup_items = sorted(
        BACKUP_ROOT.iterdir(),
        key=lambda p: p.name.lower()
    )

    print(
        "Backup root:"
    )

    print(
        BACKUP_ROOT
    )

    print(
        "\nTop-level items:"
    )

    for item in backup_items:

        print(
            "[DIR] " if item.is_dir() else "[FILE]",
            item.name
        )

else:

    print(
        "ZeroDay_IoT_Research_Backup is NOT visible "
        "in the currently mounted MyDrive."
    )


# ======================================================================
# 4 — CHECK PREVIOUSLY KNOWN RECOVERY DATA
# ======================================================================

print("\n[4] Previously known backup locations")
print("-" * 78)

known_paths = [

    BACKUP_ROOT
    / "dataset"
    / "chronological_parquet",

    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS",

    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS",

    BACKUP_ROOT
    / "processed_data"
    / "training_sampling"
    / "fold_01_DDoS",

    BACKUP_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
]


for path in known_paths:

    print(
        f"{str(path):<115}",
        path.exists()
    )


# ======================================================================
# 5 — SEARCH ONLY NEAR MyDrive ROOT FOR A BACKUP WITH A SIMILAR NAME
# ======================================================================

print("\n[5] Searching nearby for backup-like folders")
print("-" * 78)

nearby_candidates = []


if MYDRIVE_ROOT.exists():

    # Root
    for path in MYDRIVE_ROOT.iterdir():

        if (
            path.is_dir()
            and
            (
                "zeroday" in path.name.lower()
                or
                "iot" in path.name.lower()
                or
                "research" in path.name.lower()
                or
                "backup" in path.name.lower()
            )
        ):

            nearby_candidates.append(
                path
            )


    # One level below root only
    for parent in list(
        MYDRIVE_ROOT.iterdir()
    )[:100]:

        if not parent.is_dir():
            continue

        try:

            for path in parent.iterdir():

                if (
                    path.is_dir()
                    and
                    (
                        "zeroday" in path.name.lower()
                        or
                        "iot" in path.name.lower()
                        or
                        "research" in path.name.lower()
                        or
                        "backup" in path.name.lower()
                    )
                ):

                    nearby_candidates.append(
                        path
                    )

        except Exception:

            pass


# Remove duplicates
unique_candidates = []

seen = set()


for path in nearby_candidates:

    path_string = str(
        path
    )

    if path_string not in seen:

        seen.add(
            path_string
        )

        unique_candidates.append(
            path
        )


if unique_candidates:

    for path in unique_candidates:

        print(
            path
        )

else:

    print(
        "No nearby backup-like folders found."
    )


# ======================================================================
# 6 — DIAGNOSTIC RESULT
# ======================================================================

print("\n[6] A13-R2 diagnostic result")
print("-" * 78)


if not MYDRIVE_ROOT.exists():

    print(
        "⚠️ RESULT: Google Drive is not currently mounted."
    )


elif not BACKUP_ROOT.exists():

    print(
        "⚠️ RESULT: Drive is mounted, but the expected "
        "ZeroDay_IoT_Research_Backup folder is not visible."
    )

    print(
        "This commonly means the notebook is currently "
        "connected to a different Google Drive account."
    )


elif not TRAIN_SHARDS_DIR.exists():

    print(
        "⚠️ RESULT: Correct backup root is visible, "
        "but the A12 model_ready/train_shards folder is missing."
    )


else:

    shard_files = sorted(
        TRAIN_SHARDS_DIR.glob(
            "*_X.npy"
        )
    )

    print(
        "✅ RESULT: A12 shard directory found."
    )

    print(
        "Tensor shards:",
        len(shard_files)
    )


print("=" * 78)

==============================================================================
RECOVERY STEP A13-R2 — DIAGNOSE GOOGLE DRIVE MOUNT
==============================================================================

[1] Drive mount paths
------------------------------------------------------------------------------
/content/drive exists: False
/content/drive/MyDrive exists: False
Backup root exists: False
model_ready exists: False
fold_01_DDoS exists: False
train_shards exists: False

[2] Current MyDrive root contents
------------------------------------------------------------------------------
MyDrive is not currently available.

[3] Backup-root inspection
------------------------------------------------------------------------------
ZeroDay_IoT_Research_Backup is NOT visible in the currently mounted MyDrive.

[4] Previously known backup locations
------------------------------------------------------------------------------
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/dataset/chronological_parquet                                    False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/preprocessing/fold_01_DDoS                        False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/temporal_windows/fold_01_DDoS                     False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/training_sampling/fold_01_DDoS                    False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/model_ready/fold_01_DDoS                          False

[5] Searching nearby for backup-like folders
------------------------------------------------------------------------------
No nearby backup-like folders found.

[6] A13-R2 diagnostic result
------------------------------------------------------------------------------
⚠️ RESULT: Google Drive is not currently mounted.
==============================================================================

# Recovery Step A13-R3 — Mount Google Drive

In [ ]:
# ======================================================================
# RECOVERY STEP A13-R3
# MOUNT GOOGLE DRIVE
# ======================================================================

from google.colab import drive
from pathlib import Path


print("=" * 78)
print("RECOVERY STEP A13-R3 — MOUNT GOOGLE DRIVE")
print("=" * 78)


# Force a clean mount for this runtime.
drive.mount(
    "/content/drive",
    force_remount=True
)


print("\n[1] Verifying Drive mount")
print("-" * 78)

DRIVE_ROOT = Path(
    "/content/drive"
)

MYDRIVE_ROOT = Path(
    "/content/drive/MyDrive"
)

BACKUP_ROOT = (
    MYDRIVE_ROOT
    / "ZeroDay_IoT_Research_Backup"
)


print(
    "/content/drive exists:",
    DRIVE_ROOT.exists()
)

print(
    "/content/drive/MyDrive exists:",
    MYDRIVE_ROOT.exists()
)

print(
    "Research backup exists:",
    BACKUP_ROOT.exists()
)


print("\n[2] Checking important backup folders")
print("-" * 78)

important_paths = [

    BACKUP_ROOT
    / "dataset"
    / "chronological_parquet",

    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS",

    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS",

    BACKUP_ROOT
    / "processed_data"
    / "training_sampling"
    / "fold_01_DDoS",

    BACKUP_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
]


for path in important_paths:

    print(
        f"{path.name:<35}",
        path.exists()
    )


print("\n" + "=" * 78)

if BACKUP_ROOT.exists():

    print(
        "✅ RECOVERY STEP A13-R3 PASSED — "
        "Google Drive is mounted and the research backup is visible."
    )

else:

    print(
        "⚠️ Drive mounted, but the expected research backup "
        "is not visible."
    )

    print(
        "This usually means the wrong Google account "
        "was selected during Drive authorization."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A13-R3 — MOUNT GOOGLE DRIVE
==============================================================================
Mounted at /content/drive

[1] Verifying Drive mount
------------------------------------------------------------------------------
/content/drive exists: True
/content/drive/MyDrive exists: True
Research backup exists: True

[2] Checking important backup folders
------------------------------------------------------------------------------
chronological_parquet               False
fold_01_DDoS                        True
fold_01_DDoS                        True
fold_01_DDoS                        True
fold_01_DDoS                        True

==============================================================================
✅ RECOVERY STEP A13-R3 PASSED — Google Drive is mounted and the research backup is visible.
==============================================================================

# Recovery Step A13-R4 — Verify the A12 tensor backup

In [ ]:
# ======================================================================
# RECOVERY STEP A13-R4
# VERIFY A12 MODEL-READY BACKUP IN GOOGLE DRIVE
# ======================================================================

from pathlib import Path
import shutil
import pandas as pd
import json


print("=" * 78)
print("RECOVERY STEP A13-R4 — VERIFY A12 TENSOR BACKUP")
print("=" * 78)


# ======================================================================
# 1 — DEFINE PATHS
# ======================================================================

DRIVE_MODEL_READY_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS"
)

DRIVE_SHARD_DIR = (
    DRIVE_MODEL_READY_DIR
    / "train_shards"
)


SHARD_MANIFEST_NAME = (
    "fold_01_DDoS_train_tensor_shards.csv"
)

SELECTED_INDEX_NAME = (
    "fold_01_DDoS_selected_training_windows.csv"
)

BUILD_SUMMARY_NAME = (
    "fold_01_DDoS_training_tensor_build_summary.json"
)


# ======================================================================
# 2 — CHECK DIRECTORY CONTENTS
# ======================================================================

print("\n[1] Drive model-ready directory")
print("-" * 78)

print(
    "model_ready/fold_01_DDoS exists:",
    DRIVE_MODEL_READY_DIR.exists()
)

print(
    "train_shards exists:",
    DRIVE_SHARD_DIR.exists()
)


if DRIVE_MODEL_READY_DIR.exists():

    print("\nFiles/folders:")

    for path in sorted(
        DRIVE_MODEL_READY_DIR.iterdir(),
        key=lambda p: p.name.lower()
    ):

        print(
            "[DIR] " if path.is_dir() else "[FILE]",
            path.name
        )


# ======================================================================
# 3 — CHECK THREE A12 METADATA FILES
# ======================================================================

print("\n[2] A12 metadata files")
print("-" * 78)


metadata_paths = [

    DRIVE_MODEL_READY_DIR
    / SHARD_MANIFEST_NAME,

    DRIVE_MODEL_READY_DIR
    / SELECTED_INDEX_NAME,

    DRIVE_MODEL_READY_DIR
    / BUILD_SUMMARY_NAME
]


for path in metadata_paths:

    print(
        f"{path.name:<60}",
        path.exists()
    )


METADATA_COMPLETE = all(
    path.exists()
    for path
    in metadata_paths
)


# ======================================================================
# 4 — CHECK ALL TENSOR SHARDS
# ======================================================================

print("\n[3] Tensor shards")
print("-" * 78)


if DRIVE_SHARD_DIR.exists():

    shard_files = sorted(
        DRIVE_SHARD_DIR.glob(
            "*_X.npy"
        )
    )

else:

    shard_files = []


print(
    "Tensor shards found:",
    len(shard_files)
)


for path in shard_files:

    print(
        path.name,
        f"{path.stat().st_size / (1024 ** 2):.2f} MiB"
    )


SHARD_COUNT_VALID = (
    len(shard_files) == 21
)


# ======================================================================
# 5 — LOAD A12 SUMMARY
# ======================================================================

print("\n[4] A12 build-summary validation")
print("-" * 78)


if not METADATA_COMPLETE:

    raise RuntimeError(
        "A12 metadata is incomplete in Drive."
    )


summary_path = (
    DRIVE_MODEL_READY_DIR
    / BUILD_SUMMARY_NAME
)


with open(
    summary_path,
    "r",
    encoding="utf-8"
) as file:

    BUILD_SUMMARY = json.load(
        file
    )


print(
    "Training windows:",
    f"{int(BUILD_SUMMARY['training_window_count']):,}"
)

print(
    "Benign windows:",
    f"{int(BUILD_SUMMARY['benign_training_windows']):,}"
)

print(
    "Attack windows:",
    f"{int(BUILD_SUMMARY['attack_training_windows']):,}"
)

print(
    "DDoS training windows:",
    int(
        BUILD_SUMMARY[
            "held_out_DDoS_training_windows"
        ]
    )
)

print(
    "Tensor size:",
    f"{float(BUILD_SUMMARY['total_tensor_mib']):.2f} MiB"
)


# ======================================================================
# 6 — LOAD MANIFEST AND VERIFY ALL SHARD NAMES
# ======================================================================

manifest_path = (
    DRIVE_MODEL_READY_DIR
    / SHARD_MANIFEST_NAME
)


SHARD_MANIFEST = pd.read_csv(
    manifest_path
)


print("\n[5] Manifest verification")
print("-" * 78)

print(
    "Manifest rows:",
    len(SHARD_MANIFEST)
)


missing_manifest_shards = []


for _, row in SHARD_MANIFEST.iterrows():

    shard_name = Path(
        row["drive_tensor_path"]
    ).name


    expected_path = (
        DRIVE_SHARD_DIR
        / shard_name
    )


    if not expected_path.exists():

        missing_manifest_shards.append(
            shard_name
        )


print(
    "Missing manifest-referenced shards:",
    len(missing_manifest_shards)
)


# ======================================================================
# 7 — RESTORE ONLY SMALL METADATA LOCALLY
# ======================================================================

print("\n[6] Restoring small metadata locally")
print("-" * 78)


LOCAL_MODEL_READY_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/model_ready/"
    "fold_01_DDoS"
)


LOCAL_MODEL_READY_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in metadata_paths:

    destination = (
        LOCAL_MODEL_READY_DIR
        / source_path.name
    )

    shutil.copy2(
        source_path,
        destination
    )

    print(
        "Restored:",
        destination.name
    )


# ======================================================================
# 8 — FINAL VALIDATION
# ======================================================================

A13_R4_VALID = bool(

    METADATA_COMPLETE

    and

    SHARD_COUNT_VALID

    and

    len(
        SHARD_MANIFEST
    ) == 21

    and

    len(
        missing_manifest_shards
    ) == 0

    and

    int(
        BUILD_SUMMARY[
            "training_window_count"
        ]
    ) == 105_577

    and

    int(
        BUILD_SUMMARY[
            "benign_training_windows"
        ]
    ) == 8_006

    and

    int(
        BUILD_SUMMARY[
            "attack_training_windows"
        ]
    ) == 97_571

    and

    int(
        BUILD_SUMMARY[
            "held_out_DDoS_training_windows"
        ]
    ) == 0
)


print("\n[7] Recovery Step A13-R4 validation")
print("-" * 78)

print(
    "A12 metadata complete         :",
    METADATA_COMPLETE
)

print(
    "Tensor shards                 :",
    len(shard_files),
    "/ 21"
)

print(
    "Manifest rows                 :",
    len(SHARD_MANIFEST),
    "/ 21"
)

print(
    "Missing referenced shards     :",
    len(missing_manifest_shards)
)

print(
    "Training windows              :",
    f"{int(BUILD_SUMMARY['training_window_count']):,}"
)

print(
    "Benign windows                :",
    f"{int(BUILD_SUMMARY['benign_training_windows']):,}"
)

print(
    "Attack windows                :",
    f"{int(BUILD_SUMMARY['attack_training_windows']):,}"
)

print(
    "DDoS training windows         :",
    int(
        BUILD_SUMMARY[
            "held_out_DDoS_training_windows"
        ]
    )
)


print("\n" + "=" * 78)

if A13_R4_VALID:

    print(
        "✅ RECOVERY STEP A13-R4 PASSED — "
        "All A12 tensor shards and metadata are safe in Drive."
    )

else:

    print(
        "❌ RECOVERY STEP A13-R4 FAILED — "
        "Do not rerun A12 yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A13-R4 — VERIFY A12 TENSOR BACKUP
==============================================================================

[1] Drive model-ready directory
------------------------------------------------------------------------------
model_ready/fold_01_DDoS exists: True
train_shards exists: True

Files/folders:
[FILE] fold_01_DDoS_selected_training_windows.csv
[FILE] fold_01_DDoS_train_tensor_shards.csv
[FILE] fold_01_DDoS_training_tensor_build_summary.json
[DIR]  train_shards

[2] A12 metadata files
------------------------------------------------------------------------------
fold_01_DDoS_train_tensor_shards.csv                         True
fold_01_DDoS_selected_training_windows.csv                   True
fold_01_DDoS_training_tensor_build_summary.json              True

[3] Tensor shards
------------------------------------------------------------------------------
Tensor shards found: 21
01_Backdoor_Malware_X.npy 0.54 MiB
02_Benign_Final_X.npy 18.32 MiB
03_BrowserHijacking_X.npy 0.66 MiB
04_CommandInjection_X.npy 0.77 MiB
05_DNS_Spoofing_X.npy 15.01 MiB
06_DictionaryBruteForce_X.npy 1.70 MiB
07_DoS-HTTP_Flood_X.npy 22.89 MiB
08_DoS-SYN_Flood_X.npy 22.89 MiB
09_DoS-TCP_Flood_X.npy 22.89 MiB
10_DoS-UDP_Flood_X.npy 22.89 MiB
11_MITM-ArpSpoofing_X.npy 14.59 MiB
12_Mirai-greeth_flood_X.npy 1.03 MiB
13_Mirai-greip_flood_X.npy 2.08 MiB
14_Mirai-udpplain_X.npy 1.49 MiB
15_Recon-HostDiscovery_X.npy 22.89 MiB
16_Recon-OSScan_X.npy 22.89 MiB
17_Recon-PingSweep_X.npy 0.39 MiB
18_Recon-PortScan_X.npy 22.89 MiB
19_SqlInjection_X.npy 1.32 MiB
20_VulnerabilityScan_X.npy 22.89 MiB
21_XSS_X.npy 0.64 MiB

[4] A12 build-summary validation
------------------------------------------------------------------------------
Training windows: 105,577
Benign windows: 8,006
Attack windows: 97,571
DDoS training windows: 0
Tensor size: 241.65 MiB

[5] Manifest verification
------------------------------------------------------------------------------
Manifest rows: 21
Missing manifest-referenced shards: 0

[6] Restoring small metadata locally
------------------------------------------------------------------------------
Restored: fold_01_DDoS_train_tensor_shards.csv
Restored: fold_01_DDoS_selected_training_windows.csv
Restored: fold_01_DDoS_training_tensor_build_summary.json

[7] Recovery Step A13-R4 validation
------------------------------------------------------------------------------
A12 metadata complete         : True
Tensor shards                 : 21 / 21
Manifest rows                 : 21 / 21
Missing referenced shards     : 0
Training windows              : 105,577
Benign windows                : 8,006
Attack windows                : 97,571
DDoS training windows         : 0

==============================================================================
✅ RECOVERY STEP A13-R4 PASSED — All A12 tensor shards and metadata are safe in Drive.
==============================================================================

# Recovery Step A13 — PyTorch Dataset + DataLoader

In [ ]:
# ======================================================================
# RECOVERY STEP A13
# RESTORE A12 SHARDS LOCALLY + BUILD PYTORCH DATASET / DATALOADER
#
# NO MODEL TRAINING IN THIS STEP
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd
import torch

from torch.utils.data import Dataset, DataLoader


print("=" * 78)
print("RECOVERY STEP A13 — PYTORCH DATASET + DATALOADER")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — DEFINE PATHS
# ======================================================================

print("\n[1] Defining model-ready paths")
print("-" * 78)

PROJECT_ROOT = Path(
    "/content/ZeroDay_IoT_Research"
)

LOCAL_MODEL_READY_DIR = (
    PROJECT_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
)

LOCAL_SHARD_DIR = (
    LOCAL_MODEL_READY_DIR
    / "train_shards"
)

DRIVE_MODEL_READY_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS"
)

DRIVE_SHARD_DIR = (
    DRIVE_MODEL_READY_DIR
    / "train_shards"
)

SHARD_MANIFEST_PATH = (
    LOCAL_MODEL_READY_DIR
    / "fold_01_DDoS_train_tensor_shards.csv"
)

BUILD_SUMMARY_PATH = (
    LOCAL_MODEL_READY_DIR
    / "fold_01_DDoS_training_tensor_build_summary.json"
)


if not SHARD_MANIFEST_PATH.exists():
    raise RuntimeError(
        "Restored A12 shard manifest is missing."
    )

if not BUILD_SUMMARY_PATH.exists():
    raise RuntimeError(
        "Restored A12 build summary is missing."
    )

if not DRIVE_SHARD_DIR.exists():
    raise RuntimeError(
        "Drive tensor-shard folder is missing."
    )


# ======================================================================
# 2 — LOAD A12 METADATA
# ======================================================================

print("\n[2] Loading recovered A12 metadata")
print("-" * 78)

SHARD_MANIFEST = pd.read_csv(
    SHARD_MANIFEST_PATH
)

with open(
    BUILD_SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as file:

    BUILD_SUMMARY = json.load(file)


print(
    "Manifest rows:",
    len(SHARD_MANIFEST)
)

print(
    "Training windows:",
    f"{int(BUILD_SUMMARY['training_window_count']):,}"
)

print(
    "Tensor storage:",
    f"{float(BUILD_SUMMARY['total_tensor_mib']):.2f} MiB"
)


if len(SHARD_MANIFEST) != 21:
    raise RuntimeError(
        "Expected 21 tensor shards."
    )

if int(
    BUILD_SUMMARY[
        "training_window_count"
    ]
) != 105_577:

    raise RuntimeError(
        "Unexpected training-window count."
    )


# ======================================================================
# 3 — RESTORE A12 SHARDS TO LOCAL /content
# ======================================================================

print("\n[3] Restoring tensor shards locally")
print("-" * 78)

LOCAL_SHARD_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_SHARD_PATHS = []

ALL_LOCAL_SHARDS_VALID = True


for index, row in SHARD_MANIFEST.iterrows():

    shard_name = Path(
        row[
            "drive_tensor_path"
        ]
    ).name

    drive_path = (
        DRIVE_SHARD_DIR
        / shard_name
    )

    local_path = (
        LOCAL_SHARD_DIR
        / shard_name
    )

    expected_size = int(
        row[
            "file_size_bytes"
        ]
    )


    if not drive_path.exists():

        raise RuntimeError(
            f"Drive shard missing: {shard_name}"
        )


    # --------------------------------------------------------------
    # Reuse local copy if it already exists and size is exact.
    # Otherwise restore from Drive.
    # --------------------------------------------------------------

    local_valid_before = bool(

        local_path.exists()

        and

        local_path.stat().st_size
        ==
        expected_size
    )


    if not local_valid_before:

        shutil.copy2(
            drive_path,
            local_path
        )


    local_valid_after = bool(

        local_path.exists()

        and

        local_path.stat().st_size
        ==
        expected_size
    )


    ALL_LOCAL_SHARDS_VALID &= (
        local_valid_after
    )


    if not local_valid_after:

        raise RuntimeError(
            f"Local shard restoration failed: "
            f"{shard_name}"
        )


    LOCAL_SHARD_PATHS.append(
        local_path
    )


    print(
        f"{index + 1:02d}/21",
        shard_name,
        "OK"
    )


print(
    "\nAll 21 local shards valid:",
    ALL_LOCAL_SHARDS_VALID
)


# ======================================================================
# 4 — DEFINE MEMORY-MAPPED DATASET
# ======================================================================

print("\n[4] Creating memory-mapped PyTorch Dataset")
print("-" * 78)


class ShardedTemporalDataset(Dataset):

    def __init__(
        self,
        manifest,
        shard_paths
    ):

        self.manifest = (
            manifest
            .reset_index(drop=True)
            .copy()
        )

        self.shard_paths = [
            Path(path)
            for path
            in shard_paths
        ]


        self.window_counts = (

            self.manifest[
                "selected_windows"
            ]
            .astype(np.int64)
            .to_numpy()
        )


        self.targets = (

            self.manifest[
                "binary_target"
            ]
            .astype(np.int64)
            .to_numpy()
        )


        self.cumulative_counts = np.cumsum(
            self.window_counts
        )


        self.total_windows = int(
            self.cumulative_counts[-1]
        )


        # Memory-map rather than loading every tensor into RAM.
        self.shards = [

            np.load(
                path,
                mmap_mode="r",
                allow_pickle=False
            )

            for path in self.shard_paths
        ]


        for i, shard in enumerate(
            self.shards
        ):

            expected_shape = (
                int(
                    self.window_counts[i]
                ),
                8,
                75
            )


            if shard.shape != expected_shape:

                raise RuntimeError(
                    f"Shard {i + 1} shape mismatch. "
                    f"Expected {expected_shape}, "
                    f"found {shard.shape}."
                )


            if shard.dtype != np.float32:

                raise RuntimeError(
                    f"Shard {i + 1} dtype mismatch: "
                    f"{shard.dtype}"
                )


    def __len__(self):

        return self.total_windows


    def _locate(self, index):

        if index < 0:

            index += self.total_windows


        if (
            index < 0
            or
            index >= self.total_windows
        ):

            raise IndexError(
                "Dataset index out of range."
            )


        shard_index = int(

            np.searchsorted(
                self.cumulative_counts,
                index,
                side="right"
            )
        )


        previous_count = (

            0

            if shard_index == 0

            else int(
                self.cumulative_counts[
                    shard_index - 1
                ]
            )
        )


        local_index = int(
            index - previous_count
        )


        return (
            shard_index,
            local_index
        )


    def __getitem__(self, index):

        shard_index, local_index = (
            self._locate(index)
        )


        # Copy only one 8x75 window from the mmap.
        window = np.array(

            self.shards[
                shard_index
            ][
                local_index
            ],

            dtype=np.float32,
            copy=True
        )


        target = float(
            self.targets[
                shard_index
            ]
        )


        X = torch.from_numpy(
            window
        )


        y = torch.tensor(
            target,
            dtype=torch.float32
        )


        return X, y


# ======================================================================
# 5 — CREATE DATASET
# ======================================================================

TRAIN_DATASET = ShardedTemporalDataset(
    SHARD_MANIFEST,
    LOCAL_SHARD_PATHS
)


MEMMAP_SHARD_COUNT = sum(

    isinstance(
        shard,
        np.memmap
    )

    for shard
    in TRAIN_DATASET.shards
)


print(
    "Dataset windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Memory-mapped shards:",
    MEMMAP_SHARD_COUNT,
    "/ 21"
)


# ======================================================================
# 6 — LABEL / HELD-OUT CHECK
# ======================================================================

print("\n[5] Dataset-label verification")
print("-" * 78)


BENIGN_WINDOWS = int(

    SHARD_MANIFEST.loc[
        SHARD_MANIFEST[
            "binary_target"
        ] == 0,
        "selected_windows"
    ].sum()
)


ATTACK_WINDOWS = int(

    SHARD_MANIFEST.loc[
        SHARD_MANIFEST[
            "binary_target"
        ] == 1,
        "selected_windows"
    ].sum()
)


DDoS_WINDOWS = int(

    SHARD_MANIFEST.loc[
        SHARD_MANIFEST[
            "research_family"
        ] == "DDoS",
        "selected_windows"
    ].sum()
)


print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS training windows:",
    DDoS_WINDOWS
)


# ======================================================================
# 7 — VERIFY INDIVIDUAL SAMPLES
# ======================================================================

print("\n[6] Individual-sample verification")
print("-" * 78)

TEST_INDICES = [
    0,
    len(TRAIN_DATASET) // 2,
    len(TRAIN_DATASET) - 1
]


INDIVIDUAL_SAMPLES_VALID = True


for index in TEST_INDICES:

    X_sample, y_sample = (
        TRAIN_DATASET[index]
    )


    valid = bool(

        tuple(
            X_sample.shape
        ) == (8, 75)

        and

        X_sample.dtype
        ==
        torch.float32

        and

        y_sample.dtype
        ==
        torch.float32

        and

        bool(
            torch.isfinite(
                X_sample
            ).all()
        )
    )


    INDIVIDUAL_SAMPLES_VALID &= (
        valid
    )


    print(
        f"Index {index:>7,}"
        f" | X={tuple(X_sample.shape)}"
        f" | y={float(y_sample):.0f}"
        f" | finite="
        f"{bool(torch.isfinite(X_sample).all())}"
    )


# ======================================================================
# 8 — CREATE REPRODUCIBLE DATALOADER
# ======================================================================

print("\n[7] Creating reproducible DataLoader")
print("-" * 78)

PRIMARY_SEED = 13
BATCH_SIZE = 256


loader_generator = torch.Generator()

loader_generator.manual_seed(
    PRIMARY_SEED
)


TRAIN_LOADER = DataLoader(

    TRAIN_DATASET,

    batch_size=
        BATCH_SIZE,

    shuffle=
        True,

    num_workers=
        0,

    pin_memory=
        torch.cuda.is_available(),

    drop_last=
        False,

    generator=
        loader_generator
)


print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Shuffle:",
    True
)

print(
    "Seed:",
    PRIMARY_SEED
)

print(
    "Batches per epoch:",
    len(TRAIN_LOADER)
)


# ======================================================================
# 9 — LOAD ONE REAL BATCH
# ======================================================================

print("\n[8] First DataLoader batch")
print("-" * 78)

X_batch, y_batch = next(
    iter(TRAIN_LOADER)
)


BATCH_SHAPE_VALID = bool(

    X_batch.ndim == 3

    and

    tuple(
        X_batch.shape[1:]
    ) == (8, 75)

    and

    y_batch.ndim == 1

    and

    X_batch.shape[0]
    ==
    y_batch.shape[0]
)


BATCH_VALUES_FINITE = bool(
    torch.isfinite(
        X_batch
    ).all()
)


print(
    "X batch shape:",
    tuple(X_batch.shape)
)

print(
    "y batch shape:",
    tuple(y_batch.shape)
)

print(
    "X dtype:",
    X_batch.dtype
)

print(
    "y dtype:",
    y_batch.dtype
)

print(
    "All batch values finite:",
    BATCH_VALUES_FINITE
)

print(
    "Benign in first batch:",
    int(
        (y_batch == 0).sum()
    )
)

print(
    "Attack in first batch:",
    int(
        (y_batch == 1).sum()
    )
)


# ======================================================================
# 10 — DEVICE READINESS
# ======================================================================

print("\n[9] Device readiness")
print("-" * 78)

DEVICE = torch.device(

    "cuda"

    if torch.cuda.is_available()

    else "cpu"
)


print(
    "Device:",
    DEVICE
)


if torch.cuda.is_available():

    print(
        "GPU:",
        torch.cuda.get_device_name(0)
    )


# ======================================================================
# 11 — SAVE DATASET POLICY
# ======================================================================

print("\n[10] Saving dataset/DataLoader policy")
print("-" * 78)

PYTORCH_DIR = (
    LOCAL_MODEL_READY_DIR
    / "pytorch"
)

PYTORCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)


POLICY_PATH = (
    PYTORCH_DIR
    / "fold_01_DDoS_pytorch_dataset_policy.json"
)


VALIDATION_PATH = (
    PYTORCH_DIR
    / "fold_01_DDoS_pytorch_dataset_validation.json"
)


DATASET_POLICY = {

    "fold_id": 1,

    "held_out_family":
        "DDoS",

    "dataset_type":
        "local_memory_mapped_sharded_temporal_dataset",

    "training_windows":
        len(TRAIN_DATASET),

    "shard_count":
        len(TRAIN_DATASET.shards),

    "window_size":
        8,

    "feature_count":
        75,

    "dtype":
        "float32",

    "batch_size":
        BATCH_SIZE,

    "shuffle":
        True,

    "shuffle_seed":
        PRIMARY_SEED,

    "num_workers":
        0,

    "pin_memory":
        bool(
            torch.cuda.is_available()
        ),

    "full_tensor_loaded_into_ram":
        False,

    "memory_mapping_enabled":
        True,

    "held_out_DDoS_training_windows":
        DDoS_WINDOWS
}


DATASET_VALIDATION = {

    "dataset_length":
        len(TRAIN_DATASET),

    "memory_mapped_shards":
        MEMMAP_SHARD_COUNT,

    "benign_windows":
        BENIGN_WINDOWS,

    "attack_windows":
        ATTACK_WINDOWS,

    "DDoS_training_windows":
        DDoS_WINDOWS,

    "individual_samples_valid":
        INDIVIDUAL_SAMPLES_VALID,

    "batch_shape":
        list(
            X_batch.shape
        ),

    "batch_values_finite":
        BATCH_VALUES_FINITE,

    "device":
        str(DEVICE)
}


with open(
    POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        DATASET_POLICY,
        file,
        indent=4
    )


with open(
    VALIDATION_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        DATASET_VALIDATION,
        file,
        indent=4
    )


# ======================================================================
# 12 — BACK UP POLICY TO DRIVE
# ======================================================================

DRIVE_PYTORCH_DIR = (
    DRIVE_MODEL_READY_DIR
    / "pytorch"
)


DRIVE_PYTORCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)


for source_path in [
    POLICY_PATH,
    VALIDATION_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_PYTORCH_DIR
        / source_path.name
    )


POLICY_BACKUP_VALID = all(

    (
        DRIVE_PYTORCH_DIR
        / path.name
    ).exists()

    for path in [
        POLICY_PATH,
        VALIDATION_PATH
    ]
)


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

A13_VALID = bool(

    ALL_LOCAL_SHARDS_VALID

    and

    len(TRAIN_DATASET)
    ==
    105_577

    and

    MEMMAP_SHARD_COUNT
    ==
    21

    and

    BENIGN_WINDOWS
    ==
    8_006

    and

    ATTACK_WINDOWS
    ==
    97_571

    and

    DDoS_WINDOWS
    ==
    0

    and

    INDIVIDUAL_SAMPLES_VALID

    and

    BATCH_SHAPE_VALID

    and

    BATCH_VALUES_FINITE

    and

    POLICY_BACKUP_VALID
)


STEP_13_PYTORCH_DATA_VALID = (
    A13_VALID
)


print("\n[11] Recovery Step A13 validation")
print("-" * 78)

print(
    "Local tensor shards valid     :",
    ALL_LOCAL_SHARDS_VALID
)

print(
    "Dataset windows               :",
    f"{len(TRAIN_DATASET):,}",
    "/ 105,577"
)

print(
    "Memory-mapped shards          :",
    MEMMAP_SHARD_COUNT,
    "/ 21"
)

print(
    "Benign windows                :",
    f"{BENIGN_WINDOWS:,}",
    "/ 8,006"
)

print(
    "Attack windows                :",
    f"{ATTACK_WINDOWS:,}",
    "/ 97,571"
)

print(
    "DDoS training windows         :",
    DDoS_WINDOWS
)

print(
    "Individual samples valid      :",
    INDIVIDUAL_SAMPLES_VALID
)

print(
    "Batch shape valid             :",
    BATCH_SHAPE_VALID
)

print(
    "Batch values finite           :",
    BATCH_VALUES_FINITE
)

print(
    "Dataset policy backed up      :",
    POLICY_BACKUP_VALID
)


print("\n" + "=" * 78)

if A13_VALID:

    print(
        "✅ RECOVERY STEP A13 PASSED — "
        "The Fold-1 PyTorch Dataset and DataLoader are ready."
    )

else:

    print(
        "❌ RECOVERY STEP A13 FAILED — "
        "Do not start model training yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A13 — PYTORCH DATASET + DATALOADER
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Defining model-ready paths
------------------------------------------------------------------------------

[2] Loading recovered A12 metadata
------------------------------------------------------------------------------
Manifest rows: 21
Training windows: 105,577
Tensor storage: 241.65 MiB

[3] Restoring tensor shards locally
------------------------------------------------------------------------------
01/21 01_Backdoor_Malware_X.npy OK
02/21 02_Benign_Final_X.npy OK
03/21 03_BrowserHijacking_X.npy OK
04/21 04_CommandInjection_X.npy OK
05/21 05_DNS_Spoofing_X.npy OK
06/21 06_DictionaryBruteForce_X.npy OK
07/21 07_DoS-HTTP_Flood_X.npy OK
08/21 08_DoS-SYN_Flood_X.npy OK
09/21 09_DoS-TCP_Flood_X.npy OK
10/21 10_DoS-UDP_Flood_X.npy OK
11/21 11_MITM-ArpSpoofing_X.npy OK
12/21 12_Mirai-greeth_flood_X.npy OK
13/21 13_Mirai-greip_flood_X.npy OK
14/21 14_Mirai-udpplain_X.npy OK
15/21 15_Recon-HostDiscovery_X.npy OK
16/21 16_Recon-OSScan_X.npy OK
17/21 17_Recon-PingSweep_X.npy OK
18/21 18_Recon-PortScan_X.npy OK
19/21 19_SqlInjection_X.npy OK
20/21 20_VulnerabilityScan_X.npy OK
21/21 21_XSS_X.npy OK

All 21 local shards valid: True

[4] Creating memory-mapped PyTorch Dataset
------------------------------------------------------------------------------
Dataset windows: 105,577
Memory-mapped shards: 21 / 21

[5] Dataset-label verification
------------------------------------------------------------------------------
Benign windows: 8,006
Attack windows: 97,571
DDoS training windows: 0

[6] Individual-sample verification
------------------------------------------------------------------------------
Index       0 | X=(8, 75) | y=1 | finite=True
Index  52,788 | X=(8, 75) | y=1 | finite=True
Index 105,576 | X=(8, 75) | y=1 | finite=True

[7] Creating reproducible DataLoader
------------------------------------------------------------------------------
Batch size: 256
Shuffle: True
Seed: 13
Batches per epoch: 413

[8] First DataLoader batch
------------------------------------------------------------------------------
X batch shape: (256, 8, 75)
y batch shape: (256,)
X dtype: torch.float32
y dtype: torch.float32
All batch values finite: True
Benign in first batch: 28
Attack in first batch: 228

[9] Device readiness
------------------------------------------------------------------------------
Device: cuda
GPU: Tesla T4

[10] Saving dataset/DataLoader policy
------------------------------------------------------------------------------

[11] Recovery Step A13 validation
------------------------------------------------------------------------------
Local tensor shards valid     : True
Dataset windows               : 105,577 / 105,577
Memory-mapped shards          : 21 / 21
Benign windows                : 8,006 / 8,006
Attack windows                : 97,571 / 97,571
DDoS training windows         : 0
Individual samples valid      : True
Batch shape valid             : True
Batch values finite           : True
Dataset policy backed up      : True

==============================================================================
✅ RECOVERY STEP A13 PASSED — The Fold-1 PyTorch Dataset and DataLoader are ready.
==============================================================================

Recovery Step A14 — Define and validate MOT-SSL-GRU

In [ ]:
# ======================================================================
# RECOVERY STEP A14
# DEFINE + VALIDATE MOT-SSL-GRU ARCHITECTURE
#
# NO TRAINING IN THIS STEP
# ======================================================================

from pathlib import Path
import json
import shutil
import random

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


print("=" * 78)
print("RECOVERY STEP A14 — MOT-SSL-GRU ARCHITECTURE")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A13
# ======================================================================

print("\n[1] Verifying PyTorch data state")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "TRAIN_DATASET",
    "TRAIN_LOADER",
    "X_batch",
    "y_batch",
    "DEVICE"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun Recovery Step A13."
    )

if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError(
        "Recovery Step A13 did not pass."
    )


print(
    "A13 valid:",
    STEP_13_PYTORCH_DATA_VALID
)

print(
    "Device:",
    DEVICE
)

print(
    "Input batch:",
    tuple(X_batch.shape)
)


# ======================================================================
# 2 — FREEZE ARCHITECTURE CONFIGURATION
# ======================================================================

print("\n[2] Architecture configuration")
print("-" * 78)

INPUT_DIM = 75
WINDOW_SIZE = 8

FEATURE_EMBED_DIM = 128
GRU_HIDDEN_DIM = 128
GRU_NUM_LAYERS = 1

PROJECTION_DIM = 64
ORDER_HIDDEN_DIM = 128
CLASSIFIER_HIDDEN_DIM = 64

DROPOUT = 0.10

SSL_TEMPERATURE = 0.20

LAMBDA_T_CANDIDATES = [
    0.10,
    0.25,
    0.50,
    1.00
]

PRIMARY_SEED = 13


print(
    "Input features:",
    INPUT_DIM
)

print(
    "Temporal window:",
    WINDOW_SIZE
)

print(
    "Feature embedding:",
    FEATURE_EMBED_DIM
)

print(
    "GRU hidden dimension:",
    GRU_HIDDEN_DIM
)

print(
    "GRU layers:",
    GRU_NUM_LAYERS
)

print(
    "Projection dimension:",
    PROJECTION_DIM
)

print(
    "Dropout:",
    DROPOUT
)

print(
    "NT-Xent temperature:",
    SSL_TEMPERATURE
)

print(
    "Lambda_t candidates:",
    LAMBDA_T_CANDIDATES
)


# ======================================================================
# 3 — REPRODUCIBILITY HELPER
# ======================================================================

def set_seed(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_seed(
    PRIMARY_SEED
)


# ======================================================================
# 4 — SHARED PER-TIMESTEP FEATURE ENCODER
# ======================================================================

class SharedFeatureEncoder(nn.Module):

    def __init__(
        self,
        input_dim,
        embedding_dim,
        dropout
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                embedding_dim
            ),

            nn.LayerNorm(
                embedding_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            )
        )


    def forward(self, x):

        # x:
        # [batch, time, input_features]

        return self.network(x)


# ======================================================================
# 5 — GRU TEMPORAL ENCODER
# ======================================================================

class GRUTemporalEncoder(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim,
        num_layers=1
    ):

        super().__init__()

        self.hidden_dim = hidden_dim

        self.gru = nn.GRU(

            input_size=
                input_dim,

            hidden_size=
                hidden_dim,

            num_layers=
                num_layers,

            batch_first=
                True,

            bidirectional=
                False
        )


    def forward(self, x):

        # sequence_states:
        # [batch, time, hidden_dim]
        #
        # final_hidden:
        # [num_layers, batch, hidden_dim]

        sequence_states, final_hidden = (
            self.gru(x)
        )


        # Final GRU hidden state is used as
        # the window-level representation.
        representation = (
            final_hidden[-1]
        )


        return (
            sequence_states,
            representation
        )


# ======================================================================
# 6 — CONTRASTIVE PROJECTION HEAD
# ======================================================================

class ProjectionHead(nn.Module):

    def __init__(
        self,
        hidden_dim,
        projection_dim
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                hidden_dim,
                hidden_dim
            ),

            nn.LayerNorm(
                hidden_dim
            ),

            nn.GELU(),

            nn.Linear(
                hidden_dim,
                projection_dim
            )
        )


    def forward(self, representation):

        z = self.network(
            representation
        )


        # L2 normalization required for
        # cosine-similarity contrastive learning.
        z = F.normalize(
            z,
            p=2,
            dim=1
        )


        return z


# ======================================================================
# 7 — TEMPORAL-ORDER PREDICTION HEAD
# ======================================================================

class TemporalOrderHead(nn.Module):

    def __init__(
        self,
        hidden_dim,
        intermediate_dim,
        dropout
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                hidden_dim * 2,
                intermediate_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                intermediate_dim,
                1
            )
        )


    def forward(
        self,
        first_state,
        second_state
    ):

        pair = torch.cat(
            [
                first_state,
                second_state
            ],
            dim=-1
        )


        logits = self.network(
            pair
        )


        return logits.squeeze(-1)


# ======================================================================
# 8 — BINARY FINE-TUNING CLASSIFIER
# ======================================================================

class BinaryClassifierHead(nn.Module):

    def __init__(
        self,
        hidden_dim,
        classifier_dim,
        dropout
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                hidden_dim,
                classifier_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                classifier_dim,
                1
            )
        )


    def forward(self, representation):

        logits = self.network(
            representation
        )

        return logits.squeeze(-1)


# ======================================================================
# 9 — COMPLETE MOT-SSL-GRU MODEL
# ======================================================================

class MOTSSLGRU(nn.Module):

    def __init__(
        self,
        input_dim=75,
        feature_embed_dim=128,
        gru_hidden_dim=128,
        gru_num_layers=1,
        projection_dim=64,
        order_hidden_dim=128,
        classifier_hidden_dim=64,
        dropout=0.10
    ):

        super().__init__()


        self.feature_encoder = (
            SharedFeatureEncoder(
                input_dim=
                    input_dim,

                embedding_dim=
                    feature_embed_dim,

                dropout=
                    dropout
            )
        )


        self.temporal_encoder = (
            GRUTemporalEncoder(
                input_dim=
                    feature_embed_dim,

                hidden_dim=
                    gru_hidden_dim,

                num_layers=
                    gru_num_layers
            )
        )


        self.projection_head = (
            ProjectionHead(
                hidden_dim=
                    gru_hidden_dim,

                projection_dim=
                    projection_dim
            )
        )


        self.temporal_order_head = (
            TemporalOrderHead(
                hidden_dim=
                    gru_hidden_dim,

                intermediate_dim=
                    order_hidden_dim,

                dropout=
                    dropout
            )
        )


        self.classifier_head = (
            BinaryClassifierHead(
                hidden_dim=
                    gru_hidden_dim,

                classifier_dim=
                    classifier_hidden_dim,

                dropout=
                    dropout
            )
        )


    # --------------------------------------------------------------
    # Core encoder
    # --------------------------------------------------------------

    def encode(self, x):

        feature_sequence = (
            self.feature_encoder(x)
        )


        sequence_states, representation = (
            self.temporal_encoder(
                feature_sequence
            )
        )


        return (
            sequence_states,
            representation
        )


    # --------------------------------------------------------------
    # SSL path
    # --------------------------------------------------------------

    def forward_ssl(self, x):

        sequence_states, representation = (
            self.encode(x)
        )


        projection = (
            self.projection_head(
                representation
            )
        )


        return (
            sequence_states,
            representation,
            projection
        )


    # --------------------------------------------------------------
    # Binary-classification path
    # --------------------------------------------------------------

    def forward_classifier(self, x):

        _, representation = (
            self.encode(x)
        )


        logits = (
            self.classifier_head(
                representation
            )
        )


        return logits


# ======================================================================
# 10 — INSTANTIATE MODEL
# ======================================================================

print("\n[3] Instantiating MOT-SSL-GRU")
print("-" * 78)

set_seed(
    PRIMARY_SEED
)


MODEL = MOTSSLGRU(

    input_dim=
        INPUT_DIM,

    feature_embed_dim=
        FEATURE_EMBED_DIM,

    gru_hidden_dim=
        GRU_HIDDEN_DIM,

    gru_num_layers=
        GRU_NUM_LAYERS,

    projection_dim=
        PROJECTION_DIM,

    order_hidden_dim=
        ORDER_HIDDEN_DIM,

    classifier_hidden_dim=
        CLASSIFIER_HIDDEN_DIM,

    dropout=
        DROPOUT
)


MODEL = MODEL.to(
    DEVICE
)


print(MODEL)


# ======================================================================
# 11 — PARAMETER COUNTS
# ======================================================================

print("\n[4] Parameter counts")
print("-" * 78)


def count_parameters(module):

    return sum(
        parameter.numel()
        for parameter
        in module.parameters()
    )


TOTAL_PARAMETERS = count_parameters(
    MODEL
)


ENCODER_PARAMETERS = (

    count_parameters(
        MODEL.feature_encoder
    )

    +

    count_parameters(
        MODEL.temporal_encoder
    )
)


SSL_HEAD_PARAMETERS = (

    count_parameters(
        MODEL.projection_head
    )

    +

    count_parameters(
        MODEL.temporal_order_head
    )
)


CLASSIFIER_PARAMETERS = (
    count_parameters(
        MODEL.classifier_head
    )
)


print(
    "Encoder parameters:",
    f"{ENCODER_PARAMETERS:,}"
)

print(
    "SSL-head parameters:",
    f"{SSL_HEAD_PARAMETERS:,}"
)

print(
    "Classifier parameters:",
    f"{CLASSIFIER_PARAMETERS:,}"
)

print(
    "Total parameters:",
    f"{TOTAL_PARAMETERS:,}"
)


# ======================================================================
# 12 — FORWARD-PASS SMOKE TEST
# ======================================================================

print("\n[5] Forward-pass smoke test")
print("-" * 78)

MODEL.eval()


X_SMOKE = (
    X_batch[:4]
    .to(
        DEVICE
    )
)


Y_SMOKE = (
    y_batch[:4]
    .to(
        DEVICE
    )
)


with torch.no_grad():

    (
        SEQUENCE_STATES,
        REPRESENTATIONS,
        PROJECTIONS
    ) = MODEL.forward_ssl(
        X_SMOKE
    )


    CLASSIFICATION_LOGITS = (
        MODEL.forward_classifier(
            X_SMOKE
        )
    )


    # All adjacent forward-order pairs
    FORWARD_FIRST = (
        SEQUENCE_STATES[
            :,
            :-1,
            :
        ]
        .reshape(
            -1,
            GRU_HIDDEN_DIM
        )
    )


    FORWARD_SECOND = (
        SEQUENCE_STATES[
            :,
            1:,
            :
        ]
        .reshape(
            -1,
            GRU_HIDDEN_DIM
        )
    )


    ORDER_FORWARD_LOGITS = (
        MODEL.temporal_order_head(
            FORWARD_FIRST,
            FORWARD_SECOND
        )
    )


    ORDER_REVERSED_LOGITS = (
        MODEL.temporal_order_head(
            FORWARD_SECOND,
            FORWARD_FIRST
        )
    )


print(
    "Input:",
    tuple(X_SMOKE.shape)
)

print(
    "Sequence states:",
    tuple(
        SEQUENCE_STATES.shape
    )
)

print(
    "Window representations:",
    tuple(
        REPRESENTATIONS.shape
    )
)

print(
    "Contrastive projections:",
    tuple(
        PROJECTIONS.shape
    )
)

print(
    "Classification logits:",
    tuple(
        CLASSIFICATION_LOGITS.shape
    )
)

print(
    "Forward-order logits:",
    tuple(
        ORDER_FORWARD_LOGITS.shape
    )
)

print(
    "Reversed-order logits:",
    tuple(
        ORDER_REVERSED_LOGITS.shape
    )
)


# ======================================================================
# 13 — PROJECTION NORMALIZATION CHECK
# ======================================================================

print("\n[6] Projection normalization")
print("-" * 78)


projection_norms = torch.linalg.vector_norm(
    PROJECTIONS,
    ord=2,
    dim=1
)


MAX_PROJECTION_NORM_ERROR = float(

    torch.max(
        torch.abs(
            projection_norms
            -
            1.0
        )
    ).item()
)


print(
    "Projection norms:",
    projection_norms
    .detach()
    .cpu()
    .numpy()
)

print(
    "Max |norm - 1|:",
    f"{MAX_PROJECTION_NORM_ERROR:.10e}"
)


# ======================================================================
# 14 — FINITE OUTPUT CHECK
# ======================================================================

print("\n[7] Output validity")
print("-" * 78)


OUTPUTS_FINITE = bool(

    torch.isfinite(
        SEQUENCE_STATES
    ).all()

    and

    torch.isfinite(
        REPRESENTATIONS
    ).all()

    and

    torch.isfinite(
        PROJECTIONS
    ).all()

    and

    torch.isfinite(
        CLASSIFICATION_LOGITS
    ).all()

    and

    torch.isfinite(
        ORDER_FORWARD_LOGITS
    ).all()

    and

    torch.isfinite(
        ORDER_REVERSED_LOGITS
    ).all()
)


print(
    "All architecture outputs finite:",
    OUTPUTS_FINITE
)


# ======================================================================
# 15 — BACKPROPAGATION SMOKE TEST
# ======================================================================

print("\n[8] Gradient smoke test")
print("-" * 78)

MODEL.train()

MODEL.zero_grad(
    set_to_none=True
)


sequence_states, representations, projections = (
    MODEL.forward_ssl(
        X_SMOKE
    )
)


classification_logits = (
    MODEL.classifier_head(
        representations
    )
)


forward_first = (
    sequence_states[
        :,
        :-1,
        :
    ]
    .reshape(
        -1,
        GRU_HIDDEN_DIM
    )
)


forward_second = (
    sequence_states[
        :,
        1:,
        :
    ]
    .reshape(
        -1,
        GRU_HIDDEN_DIM
    )
)


forward_order_logits = (
    MODEL.temporal_order_head(
        forward_first,
        forward_second
    )
)


reverse_order_logits = (
    MODEL.temporal_order_head(
        forward_second,
        forward_first
    )
)


forward_targets = torch.ones_like(
    forward_order_logits
)

reverse_targets = torch.zeros_like(
    reverse_order_logits
)


classification_loss = (
    F.binary_cross_entropy_with_logits(
        classification_logits,
        Y_SMOKE
    )
)


order_loss = (

    F.binary_cross_entropy_with_logits(
        forward_order_logits,
        forward_targets
    )

    +

    F.binary_cross_entropy_with_logits(
        reverse_order_logits,
        reverse_targets
    )

) / 2.0


# Tiny projection term is used ONLY to verify that
# projection-head gradients propagate during this smoke test.
projection_gradient_probe = (
    0.01
    *
    projections.mean()
)


SMOKE_LOSS = (

    classification_loss

    +

    order_loss

    +

    projection_gradient_probe
)


SMOKE_LOSS.backward()


GRADIENT_TENSORS = 0
FINITE_GRADIENT_TENSORS = 0
NONFINITE_GRADIENT_TENSORS = 0


for parameter in MODEL.parameters():

    if parameter.grad is None:
        continue

    GRADIENT_TENSORS += 1


    if torch.isfinite(
        parameter.grad
    ).all():

        FINITE_GRADIENT_TENSORS += 1

    else:

        NONFINITE_GRADIENT_TENSORS += 1


GRADIENTS_VALID = bool(

    GRADIENT_TENSORS > 0

    and

    NONFINITE_GRADIENT_TENSORS == 0
)


print(
    "Smoke loss:",
    f"{float(SMOKE_LOSS.detach().cpu()):.6f}"
)

print(
    "Gradient tensors:",
    GRADIENT_TENSORS
)

print(
    "Finite gradient tensors:",
    FINITE_GRADIENT_TENSORS
)

print(
    "Non-finite gradient tensors:",
    NONFINITE_GRADIENT_TENSORS
)

print(
    "Gradients valid:",
    GRADIENTS_VALID
)


MODEL.zero_grad(
    set_to_none=True
)


# ======================================================================
# 16 — STRUCTURAL VALIDATION
# ======================================================================

print("\n[9] Structural validation")
print("-" * 78)


SHAPES_VALID = bool(

    tuple(
        SEQUENCE_STATES.shape
    )
    ==
    (
        4,
        8,
        GRU_HIDDEN_DIM
    )

    and

    tuple(
        REPRESENTATIONS.shape
    )
    ==
    (
        4,
        GRU_HIDDEN_DIM
    )

    and

    tuple(
        PROJECTIONS.shape
    )
    ==
    (
        4,
        PROJECTION_DIM
    )

    and

    tuple(
        CLASSIFICATION_LOGITS.shape
    )
    ==
    (4,)

    and

    tuple(
        ORDER_FORWARD_LOGITS.shape
    )
    ==
    (
        4 * (WINDOW_SIZE - 1),
    )
)


PROJECTIONS_NORMALIZED = bool(

    MAX_PROJECTION_NORM_ERROR
    <
    1e-5
)


print(
    "All output shapes valid:",
    SHAPES_VALID
)

print(
    "Projection normalization valid:",
    PROJECTIONS_NORMALIZED
)

print(
    "All outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Gradient flow valid:",
    GRADIENTS_VALID
)


# ======================================================================
# 17 — SAVE ARCHITECTURE SPECIFICATION
# ======================================================================

print("\n[10] Saving architecture specification")
print("-" * 78)


LOCAL_ARCH_DIR = (

    Path(
        "/content/ZeroDay_IoT_Research"
    )

    / "models"

    / "architecture"

    / "fold_01_DDoS"
)


DRIVE_ARCH_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "models/architecture/"
    "fold_01_DDoS"
)


LOCAL_ARCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_ARCH_DIR.mkdir(
    parents=True,
    exist_ok=True
)


ARCHITECTURE_JSON_PATH = (
    LOCAL_ARCH_DIR
    / "fold_01_DDoS_MOT_SSL_GRU_architecture.json"
)


ARCHITECTURE_TEXT_PATH = (
    LOCAL_ARCH_DIR
    / "fold_01_DDoS_MOT_SSL_GRU_model.txt"
)


ARCHITECTURE_SPEC = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "paper_grounded_components": {

        "temporal_window":
            8,

        "shared_feature_encoder":
            True,

        "GRU_temporal_encoder":
            True,

        "contrastive_objective":
            "NT-Xent",

        "NT_Xent_temperature":
            0.2,

        "auxiliary_objective":
            "binary temporal-order prediction",

        "fine_tuning_task":
            "binary benign_vs_malicious classification"
    },


    "implementation_choices": {

        "input_features":
            INPUT_DIM,

        "feature_embedding_dimension":
            FEATURE_EMBED_DIM,

        "GRU_hidden_dimension":
            GRU_HIDDEN_DIM,

        "GRU_layers":
            GRU_NUM_LAYERS,

        "bidirectional_GRU":
            False,

        "window_representation":
            "final_GRU_hidden_state",

        "projection_dimension":
            PROJECTION_DIM,

        "temporal_order_hidden_dimension":
            ORDER_HIDDEN_DIM,

        "classifier_hidden_dimension":
            CLASSIFIER_HIDDEN_DIM,

        "dropout":
            DROPOUT
    },


    "lambda_t_candidates":
        LAMBDA_T_CANDIDATES,

    "architecture_seed_for_validation":
        PRIMARY_SEED,

    "total_parameters":
        TOTAL_PARAMETERS,

    "encoder_parameters":
        ENCODER_PARAMETERS,

    "SSL_head_parameters":
        SSL_HEAD_PARAMETERS,

    "classifier_parameters":
        CLASSIFIER_PARAMETERS,

    "note":
        (
            "Hidden widths, projection size, dropout, "
            "number of GRU layers, and final-hidden-state "
            "pooling are documented implementation choices. "
            "They are not claimed as fixed values from the "
            "research methodology document."
        )
}


with open(
    ARCHITECTURE_JSON_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        ARCHITECTURE_SPEC,
        file,
        indent=4
    )


with open(
    ARCHITECTURE_TEXT_PATH,
    "w",
    encoding="utf-8"
) as file:

    file.write(
        str(MODEL)
    )

    file.write(
        "\n\n"
    )

    file.write(
        f"Total parameters: "
        f"{TOTAL_PARAMETERS:,}\n"
    )

    file.write(
        f"Encoder parameters: "
        f"{ENCODER_PARAMETERS:,}\n"
    )

    file.write(
        f"SSL-head parameters: "
        f"{SSL_HEAD_PARAMETERS:,}\n"
    )

    file.write(
        f"Classifier parameters: "
        f"{CLASSIFIER_PARAMETERS:,}\n"
    )


# ======================================================================
# 18 — BACK UP ARCHITECTURE TO DRIVE
# ======================================================================

for source_path in [
    ARCHITECTURE_JSON_PATH,
    ARCHITECTURE_TEXT_PATH
]:

    shutil.copy2(
        source_path,
        DRIVE_ARCH_DIR
        / source_path.name
    )


ARCHITECTURE_BACKED_UP = all(

    (
        DRIVE_ARCH_DIR
        / path.name
    ).exists()

    for path in [
        ARCHITECTURE_JSON_PATH,
        ARCHITECTURE_TEXT_PATH
    ]
)


# ======================================================================
# 19 — FINAL A14 VALIDATION
# ======================================================================

A14_VALID = bool(

    SHAPES_VALID

    and

    PROJECTIONS_NORMALIZED

    and

    OUTPUTS_FINITE

    and

    GRADIENTS_VALID

    and

    TOTAL_PARAMETERS > 0

    and

    ARCHITECTURE_BACKED_UP
)


STEP_14_MODEL_ARCHITECTURE_VALID = (
    A14_VALID
)


print("\n[11] Recovery Step A14 validation")
print("-" * 78)

print(
    "Input dimension               :",
    INPUT_DIM
)

print(
    "Window size                   :",
    WINDOW_SIZE
)

print(
    "GRU hidden dimension          :",
    GRU_HIDDEN_DIM
)

print(
    "Projection dimension          :",
    PROJECTION_DIM
)

print(
    "Total parameters              :",
    f"{TOTAL_PARAMETERS:,}"
)

print(
    "Output shapes valid           :",
    SHAPES_VALID
)

print(
    "Projection norms valid        :",
    PROJECTIONS_NORMALIZED
)

print(
    "All outputs finite            :",
    OUTPUTS_FINITE
)

print(
    "All computed gradients finite :",
    GRADIENTS_VALID
)

print(
    "Architecture backed up        :",
    ARCHITECTURE_BACKED_UP
)


print("\n" + "=" * 78)

if A14_VALID:

    print(
        "✅ RECOVERY STEP A14 PASSED — "
        "The MOT-SSL-GRU architecture is defined, "
        "numerically valid, and ready for SSL training."
    )

else:

    print(
        "❌ RECOVERY STEP A14 FAILED — "
        "Do not begin SSL training."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A14 — MOT-SSL-GRU ARCHITECTURE
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying PyTorch data state
------------------------------------------------------------------------------
A13 valid: True
Device: cuda
Input batch: (256, 8, 75)

[2] Architecture configuration
------------------------------------------------------------------------------
Input features: 75
Temporal window: 8
Feature embedding: 128
GRU hidden dimension: 128
GRU layers: 1
Projection dimension: 64
Dropout: 0.1
NT-Xent temperature: 0.2
Lambda_t candidates: [0.1, 0.25, 0.5, 1.0]

[3] Instantiating MOT-SSL-GRU
------------------------------------------------------------------------------
MOTSSLGRU(
  (feature_encoder): SharedFeatureEncoder(
    (network): Sequential(
      (0): Linear(in_features=75, out_features=128, bias=True)
      (1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (2): GELU(approximate='none')
      (3): Dropout(p=0.1, inplace=False)
    )
  )
  (temporal_encoder): GRUTemporalEncoder(
    (gru): GRU(128, 128, batch_first=True)
  )
  (projection_head): ProjectionHead(
    (network): Sequential(
      (0): Linear(in_features=128, out_features=128, bias=True)
      (1): LayerNorm((128,), eps=1e-05, elementwise_affine=True)
      (2): GELU(approximate='none')
      (3): Linear(in_features=128, out_features=64, bias=True)
    )
  )
  (temporal_order_head): TemporalOrderHead(
    (network): Sequential(
      (0): Linear(in_features=256, out_features=128, bias=True)
      (1): GELU(approximate='none')
      (2): Dropout(p=0.1, inplace=False)
      (3): Linear(in_features=128, out_features=1, bias=True)
    )
  )
  (classifier_head): BinaryClassifierHead(
    (network): Sequential(
      (0): Linear(in_features=128, out_features=64, bias=True)
      (1): GELU(approximate='none')
      (2): Dropout(p=0.1, inplace=False)
      (3): Linear(in_features=64, out_features=1, bias=True)
    )
  )
)

[4] Parameter counts
------------------------------------------------------------------------------
Encoder parameters: 109,056
SSL-head parameters: 58,049
Classifier parameters: 8,321
Total parameters: 175,426

[5] Forward-pass smoke test
------------------------------------------------------------------------------
Input: (4, 8, 75)
Sequence states: (4, 8, 128)
Window representations: (4, 128)
Contrastive projections: (4, 64)
Classification logits: (4,)
Forward-order logits: (28,)
Reversed-order logits: (28,)

[6] Projection normalization
------------------------------------------------------------------------------
Projection norms: [1. 1. 1. 1.]
Max |norm - 1|: 0.0000000000e+00

[7] Output validity
------------------------------------------------------------------------------
All architecture outputs finite: True

[8] Gradient smoke test
------------------------------------------------------------------------------
Smoke loss: 1.381374
Gradient tensors: 22
Finite gradient tensors: 22
Non-finite gradient tensors: 0
Gradients valid: True

[9] Structural validation
------------------------------------------------------------------------------
All output shapes valid: True
Projection normalization valid: True
All outputs finite: True
Gradient flow valid: True

[10] Saving architecture specification
------------------------------------------------------------------------------

[11] Recovery Step A14 validation
------------------------------------------------------------------------------
Input dimension               : 75
Window size                   : 8
GRU hidden dimension          : 128
Projection dimension          : 64
Total parameters              : 175,426
Output shapes valid           : True
Projection norms valid        : True
All outputs finite            : True
All computed gradients finite : True
Architecture backed up        : True

==============================================================================
✅ RECOVERY STEP A14 PASSED — The MOT-SSL-GRU architecture is defined, numerically valid, and ready for SSL training.
==============================================================================

# Recovery Step A15 — Real SSL Pretraining

In [ ]:
# ======================================================================
# RECOVERY STEP A15
# REAL MOT-SSL-GRU SELF-SUPERVISED PRETRAINING
#
# Fold 1: DDoS held out
# Labels are NOT used during SSL.
# Checkpoint backed up after EVERY epoch.
# ======================================================================

from pathlib import Path
from contextlib import nullcontext
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("RECOVERY STEP A15 — MOT-SSL-GRU SELF-SUPERVISED PRETRAINING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A13 + A14 STATE
# ======================================================================

print("\n[1] Verifying training state")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nPlease rerun A13 and A14."
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError(
        "A13 did not pass."
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError(
        "A14 did not pass."
    )


print(
    "A13 PyTorch data valid:",
    STEP_13_PYTORCH_DATA_VALID
)

print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — SSL TRAINING CONFIGURATION
# ======================================================================

print("\n[2] SSL training configuration")
print("-" * 78)

PRIMARY_SEED = 13

SSL_EPOCHS = 30
SSL_BATCH_SIZE = 256
SSL_LEARNING_RATE = 1e-3

SSL_TEMPERATURE = 0.20

# --------------------------------------------------------------
# PROVISIONAL implementation value.
# Not claimed as tuned/optimal.
# Later sensitivity analysis compares:
# 0.1, 0.25, 0.5, 1.0
# --------------------------------------------------------------

PRIMARY_LAMBDA_T = 0.25

LAMBDA_T_CANDIDATES = [
    0.10,
    0.25,
    0.50,
    1.00
]

# --------------------------------------------------------------
# Augmentation implementation choices.
#
# These are not claimed to be fixed by the methodology document.
#
# Feature masking:
# 10% of standardized scalar inputs are replaced by 0,
# which corresponds approximately to the training mean after
# standardization.
#
# Gaussian jitter:
# Small noise in standardized feature units.
#
# Temporal order is NEVER shuffled here.
# --------------------------------------------------------------

FEATURE_MASK_PROBABILITY = 0.10
GAUSSIAN_JITTER_STD = 0.01

MAX_GRADIENT_NORM = 5.0

WEIGHT_DECAY = 0.0

USE_AMP = bool(
    DEVICE.type == "cuda"
)


print(
    "Epochs:",
    SSL_EPOCHS
)

print(
    "Batch size:",
    SSL_BATCH_SIZE
)

print(
    "Learning rate:",
    SSL_LEARNING_RATE
)

print(
    "NT-Xent temperature:",
    SSL_TEMPERATURE
)

print(
    "Provisional lambda_t:",
    PRIMARY_LAMBDA_T
)

print(
    "Lambda_t candidates:",
    LAMBDA_T_CANDIDATES
)

print(
    "Feature masking probability:",
    FEATURE_MASK_PROBABILITY
)

print(
    "Gaussian jitter std:",
    GAUSSIAN_JITTER_STD
)

print(
    "Gradient clipping:",
    MAX_GRADIENT_NORM
)

print(
    "Mixed precision:",
    USE_AMP
)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(
    PRIMARY_SEED
)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — BUILD A FRESH SSL MODEL
# ======================================================================

print("\n[3] Creating clean SSL model")
print("-" * 78)

set_all_seeds(
    PRIMARY_SEED
)


SSL_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10
).to(
    DEVICE
)


# ======================================================================
# 5 — SSL-ONLY OPTIMIZER
# ======================================================================

# IMPORTANT:
# Classifier head is intentionally NOT included.
#
# SSL trains only:
#   1. feature encoder
#   2. GRU temporal encoder
#   3. projection head
#   4. temporal-order head

SSL_PARAMETERS = (

    list(
        SSL_MODEL.feature_encoder.parameters()
    )

    +

    list(
        SSL_MODEL.temporal_encoder.parameters()
    )

    +

    list(
        SSL_MODEL.projection_head.parameters()
    )

    +

    list(
        SSL_MODEL.temporal_order_head.parameters()
    )
)


SSL_OPTIMIZER = torch.optim.Adam(

    SSL_PARAMETERS,

    lr=
        SSL_LEARNING_RATE,

    weight_decay=
        WEIGHT_DECAY
)


ssl_parameter_ids = {
    id(parameter)
    for parameter
    in SSL_PARAMETERS
}


classifier_parameter_ids = {
    id(parameter)
    for parameter
    in SSL_MODEL.classifier_head.parameters()
}


CLASSIFIER_INCLUDED_IN_SSL = bool(

    len(
        ssl_parameter_ids
        &
        classifier_parameter_ids
    ) > 0
)


SSL_PARAMETER_COUNT = sum(

    parameter.numel()

    for parameter
    in SSL_PARAMETERS
)


print(
    "SSL trainable parameters:",
    f"{SSL_PARAMETER_COUNT:,}"
)

print(
    "Classifier included in SSL optimizer:",
    CLASSIFIER_INCLUDED_IN_SSL
)


if CLASSIFIER_INCLUDED_IN_SSL:

    raise RuntimeError(
        "Classifier must NOT be optimized during SSL."
    )


# ======================================================================
# 6 — AMP GRADIENT SCALER
# ======================================================================

if hasattr(torch, "amp"):

    AMP_SCALER = torch.amp.GradScaler(
        "cuda",
        enabled=USE_AMP
    )

else:

    AMP_SCALER = torch.cuda.amp.GradScaler(
        enabled=USE_AMP
    )


def autocast_context():

    if USE_AMP:

        return torch.autocast(
            device_type="cuda",
            dtype=torch.float16
        )

    return nullcontext()


# ======================================================================
# 7 — DETERMINISTIC SSL DATALOADER PER EPOCH
# ======================================================================

def make_ssl_train_loader(epoch_number):

    generator = torch.Generator()

    # A deterministic independent shuffle for every epoch.
    generator.manual_seed(
        PRIMARY_SEED
        +
        int(epoch_number)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=
            SSL_BATCH_SIZE,

        shuffle=
            True,

        num_workers=
            0,

        pin_memory=
            torch.cuda.is_available(),

        drop_last=
            False,

        generator=
            generator
    )


# ======================================================================
# 8 — TWO INDEPENDENT SSL AUGMENTED VIEWS
# ======================================================================

def augment_ssl_view(x):

    augmented = x.clone()


    # --------------------------------------------------------------
    # Small Gaussian jitter
    # --------------------------------------------------------------

    if GAUSSIAN_JITTER_STD > 0:

        augmented = (

            augmented

            +

            torch.randn_like(
                augmented
            )
            *
            GAUSSIAN_JITTER_STD
        )


    # --------------------------------------------------------------
    # Feature masking
    # --------------------------------------------------------------

    if FEATURE_MASK_PROBABILITY > 0:

        mask = (

            torch.rand_like(
                augmented
            )

            <
            FEATURE_MASK_PROBABILITY
        )


        augmented = augmented.masked_fill(
            mask,
            0.0
        )


    return augmented


# ======================================================================
# 9 — NT-XENT LOSS
# ======================================================================

def nt_xent_loss(
    z1,
    z2,
    temperature
):

    batch_size = int(
        z1.shape[0]
    )


    if batch_size < 2:

        raise RuntimeError(
            "NT-Xent requires at least 2 samples."
        )


    # Projection head already L2 normalizes z1/z2.
    # Force similarity calculation to float32 for stability.
    z = torch.cat(
        [
            z1,
            z2
        ],
        dim=0
    ).float()


    similarity = (

        torch.matmul(
            z,
            z.T
        )

        /
        temperature
    )


    total = (
        2 * batch_size
    )


    # A representation cannot match itself.
    self_mask = torch.eye(
        total,
        device=
            similarity.device,
        dtype=
            torch.bool
    )


    similarity = similarity.masked_fill(
        self_mask,
        float("-inf")
    )


    # Positive pair:
    # view1[i] ↔ view2[i]
    targets = (

        torch.arange(
            total,
            device=
                similarity.device
        )

        +

        batch_size

    ) % total


    loss = F.cross_entropy(
        similarity,
        targets
    )


    return loss


# ======================================================================
# 10 — TEMPORAL-ORDER LOSS
# ======================================================================

def temporal_order_loss(
    sequence_states,
    order_head
):

    # sequence_states:
    # [batch, 8, hidden]

    hidden_dim = (
        sequence_states.shape[-1]
    )


    earlier = (

        sequence_states[
            :,
            :-1,
            :
        ]

        .reshape(
            -1,
            hidden_dim
        )
    )


    later = (

        sequence_states[
            :,
            1:,
            :
        ]

        .reshape(
            -1,
            hidden_dim
        )
    )


    # Correct order: [h_t, h_t+1] -> 1
    forward_logits = (
        order_head(
            earlier,
            later
        )
    )


    # Reversed order: [h_t+1, h_t] -> 0
    reversed_logits = (
        order_head(
            later,
            earlier
        )
    )


    forward_targets = torch.ones_like(
        forward_logits
    )


    reversed_targets = torch.zeros_like(
        reversed_logits
    )


    forward_loss = (
        F.binary_cross_entropy_with_logits(
            forward_logits,
            forward_targets
        )
    )


    reversed_loss = (
        F.binary_cross_entropy_with_logits(
            reversed_logits,
            reversed_targets
        )
    )


    return (
        forward_loss
        +
        reversed_loss
    ) / 2.0


# ======================================================================
# 11 — CHECKPOINT DIRECTORIES
# ======================================================================

LOCAL_SSL_DIR = (

    Path(
        "/content/ZeroDay_IoT_Research"
    )

    / "models"

    / "ssl_pretraining"

    / "fold_01_DDoS"

    / "seed_13"

    / "lambda_0p25"
)


DRIVE_SSL_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_0p25"
)


LOCAL_SSL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_SSL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_LATEST_CHECKPOINT = (
    LOCAL_SSL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_LATEST_CHECKPOINT = (
    DRIVE_SSL_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY_PATH = (
    LOCAL_SSL_DIR
    / "ssl_training_history.csv"
)


DRIVE_HISTORY_PATH = (
    DRIVE_SSL_DIR
    / "ssl_training_history.csv"
)


LOCAL_POLICY_PATH = (
    LOCAL_SSL_DIR
    / "ssl_training_policy.json"
)


DRIVE_POLICY_PATH = (
    DRIVE_SSL_DIR
    / "ssl_training_policy.json"
)


LOCAL_FINAL_MODEL = (
    LOCAL_SSL_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


DRIVE_FINAL_MODEL = (
    DRIVE_SSL_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


# ======================================================================
# 12 — SAVE TRAINING POLICY BEFORE EXPENSIVE WORK
# ======================================================================

SSL_TRAINING_POLICY = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        PRIMARY_SEED,

    "epochs":
        SSL_EPOCHS,

    "batch_size":
        SSL_BATCH_SIZE,

    "learning_rate":
        SSL_LEARNING_RATE,

    "optimizer":
        "Adam",

    "weight_decay":
        WEIGHT_DECAY,

    "NT_Xent_temperature":
        SSL_TEMPERATURE,

    "lambda_t":
        PRIMARY_LAMBDA_T,

    "lambda_t_status":
        "provisional_implementation_choice_not_yet_tuned",

    "lambda_t_candidates":
        LAMBDA_T_CANDIDATES,

    "feature_mask_probability":
        FEATURE_MASK_PROBABILITY,

    "gaussian_jitter_std":
        GAUSSIAN_JITTER_STD,

    "augmentation_preserves_temporal_order":
        True,

    "maximum_gradient_norm":
        MAX_GRADIENT_NORM,

    "mixed_precision":
        USE_AMP,

    "binary_labels_used_during_SSL":
        False,

    "classifier_head_optimized_during_SSL":
        False,

    "held_out_family_used_during_SSL":
        False,

    "checkpoint_frequency":
        "every_epoch",

    "note":
        (
            "Feature masking, Gaussian jitter, and lambda_t=0.25 "
            "for this initial run are documented implementation "
            "choices. lambda_t is not claimed as tuned or optimal."
        )
}


with open(
    LOCAL_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SSL_TRAINING_POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY_PATH,
    DRIVE_POLICY_PATH
)


# ======================================================================
# 13 — AUTOMATIC RESUME SUPPORT
# ======================================================================

print("\n[4] Checking for resumable SSL checkpoint")
print("-" * 78)


START_EPOCH = 1

training_history = []


if DRIVE_LATEST_CHECKPOINT.exists():

    print(
        "Existing Drive checkpoint found."
    )


    checkpoint = torch.load(
        DRIVE_LATEST_CHECKPOINT,
        map_location=
            DEVICE,
        weights_only=False
    )


    checkpoint_lambda = float(
        checkpoint[
            "lambda_t"
        ]
    )


    checkpoint_temperature = float(
        checkpoint[
            "temperature"
        ]
    )


    if not np.isclose(
        checkpoint_lambda,
        PRIMARY_LAMBDA_T
    ):

        raise RuntimeError(
            "Checkpoint lambda_t does not match "
            "this A15 configuration."
        )


    if not np.isclose(
        checkpoint_temperature,
        SSL_TEMPERATURE
    ):

        raise RuntimeError(
            "Checkpoint temperature does not match."
        )


    SSL_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    SSL_OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    if (
        "scaler_state_dict"
        in checkpoint
        and
        checkpoint[
            "scaler_state_dict"
        ] is not None
    ):

        AMP_SCALER.load_state_dict(
            checkpoint[
                "scaler_state_dict"
            ]
        )


    START_EPOCH = (
        int(
            checkpoint[
                "epoch"
            ]
        )
        +
        1
    )


    print(
        "Resuming after epoch:",
        checkpoint[
            "epoch"
        ]
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


    if DRIVE_HISTORY_PATH.exists():

        old_history = pd.read_csv(
            DRIVE_HISTORY_PATH
        )


        training_history = (
            old_history
            .to_dict(
                orient="records"
            )
        )


else:

    print(
        "No previous checkpoint."
    )

    print(
        "Starting SSL training from epoch 1."
    )


# ======================================================================
# 14 — TRAINING LOOP
# ======================================================================

print("\n[5] Starting real SSL training")
print("-" * 78)


SSL_LABELS_USED = False

NONFINITE_BATCHES = 0

TRAINING_START_TIME = time.time()


if START_EPOCH <= SSL_EPOCHS:

    for epoch in range(
        START_EPOCH,
        SSL_EPOCHS + 1
    ):

        epoch_start_time = time.time()


        # ----------------------------------------------------------
        # Deterministic epoch-level seed.
        # Allows reproducible recovery/resume.
        # ----------------------------------------------------------

        set_all_seeds(
            PRIMARY_SEED
            +
            epoch * 10_000
        )


        SSL_TRAIN_LOADER = (
            make_ssl_train_loader(
                epoch
            )
        )


        SSL_MODEL.train()


        running_total_loss = 0.0
        running_nt_xent_loss = 0.0
        running_order_loss = 0.0

        epoch_examples = 0

        epoch_max_gradient_norm = 0.0


        for batch_index, (
            X,
            _
        ) in enumerate(
            SSL_TRAIN_LOADER,
            start=1
        ):

            # ------------------------------------------------------
            # IMPORTANT:
            # The second DataLoader item is deliberately named "_".
            # Binary attack/benign labels are not used.
            # ------------------------------------------------------

            X = X.to(
                DEVICE,
                non_blocking=
                    torch.cuda.is_available()
            )


            batch_size = int(
                X.shape[0]
            )


            view_1 = augment_ssl_view(
                X
            )


            view_2 = augment_ssl_view(
                X
            )


            SSL_OPTIMIZER.zero_grad(
                set_to_none=True
            )


            with autocast_context():

                (
                    sequence_1,
                    _,
                    projection_1
                ) = SSL_MODEL.forward_ssl(
                    view_1
                )


                (
                    sequence_2,
                    _,
                    projection_2
                ) = SSL_MODEL.forward_ssl(
                    view_2
                )


                contrastive_loss = (
                    nt_xent_loss(
                        projection_1,
                        projection_2,
                        SSL_TEMPERATURE
                    )
                )


                order_loss_1 = (
                    temporal_order_loss(
                        sequence_1,
                        SSL_MODEL.temporal_order_head
                    )
                )


                order_loss_2 = (
                    temporal_order_loss(
                        sequence_2,
                        SSL_MODEL.temporal_order_head
                    )
                )


                order_loss = (
                    order_loss_1
                    +
                    order_loss_2
                ) / 2.0


                total_loss = (

                    contrastive_loss

                    +

                    PRIMARY_LAMBDA_T
                    *
                    order_loss
                )


            # ------------------------------------------------------
            # Fail immediately if loss becomes non-finite.
            # ------------------------------------------------------

            if not bool(
                torch.isfinite(
                    total_loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite SSL loss at "
                    f"epoch {epoch}, batch {batch_index}."
                )


            # ------------------------------------------------------
            # Backpropagation with AMP
            # ------------------------------------------------------

            AMP_SCALER.scale(
                total_loss
            ).backward()


            AMP_SCALER.unscale_(
                SSL_OPTIMIZER
            )


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    SSL_PARAMETERS,
                    max_norm=
                        MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm.detach().cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                raise RuntimeError(
                    f"Non-finite gradient norm at "
                    f"epoch {epoch}, batch {batch_index}."
                )


            epoch_max_gradient_norm = max(
                epoch_max_gradient_norm,
                gradient_norm_value
            )


            AMP_SCALER.step(
                SSL_OPTIMIZER
            )


            AMP_SCALER.update()


            # ------------------------------------------------------
            # Running metrics
            # ------------------------------------------------------

            running_total_loss += (
                float(
                    total_loss
                    .detach()
                    .cpu()
                )
                *
                batch_size
            )


            running_nt_xent_loss += (
                float(
                    contrastive_loss
                    .detach()
                    .cpu()
                )
                *
                batch_size
            )


            running_order_loss += (
                float(
                    order_loss
                    .detach()
                    .cpu()
                )
                *
                batch_size
            )


            epoch_examples += (
                batch_size
            )


            # ------------------------------------------------------
            # Lightweight progress message
            # ------------------------------------------------------

            if (
                batch_index % 100 == 0
                or
                batch_index
                ==
                len(
                    SSL_TRAIN_LOADER
                )
            ):

                print(
                    f"Epoch {epoch:02d}/{SSL_EPOCHS} "
                    f"| Batch {batch_index:03d}/"
                    f"{len(SSL_TRAIN_LOADER):03d} "
                    f"| Loss "
                    f"{float(total_loss.detach().cpu()):.4f}"
                )


        # ----------------------------------------------------------
        # Epoch statistics
        # ----------------------------------------------------------

        epoch_total_loss = (
            running_total_loss
            /
            epoch_examples
        )


        epoch_nt_xent_loss = (
            running_nt_xent_loss
            /
            epoch_examples
        )


        epoch_order_loss = (
            running_order_loss
            /
            epoch_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start_time
        )


        epoch_record = {

            "epoch":
                epoch,

            "total_loss":
                epoch_total_loss,

            "NT_Xent_loss":
                epoch_nt_xent_loss,

            "temporal_order_loss":
                epoch_order_loss,

            "lambda_t":
                PRIMARY_LAMBDA_T,

            "learning_rate":
                SSL_OPTIMIZER
                .param_groups[0]["lr"],

            "examples":
                epoch_examples,

            "batches":
                len(
                    SSL_TRAIN_LOADER
                ),

            "maximum_preclip_gradient_norm":
                epoch_max_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        # Remove old record if rerunning same epoch.
        training_history = [

            record

            for record
            in training_history

            if int(
                record[
                    "epoch"
                ]
            )
            !=
            epoch
        ]


        training_history.append(
            epoch_record
        )


        history_df = (

            pd.DataFrame(
                training_history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY_PATH,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY_PATH,
            DRIVE_HISTORY_PATH
        )


        # ----------------------------------------------------------
        # Save checkpoint after EVERY epoch
        # ----------------------------------------------------------

        checkpoint = {

            "epoch":
                epoch,

            "model_state_dict":
                SSL_MODEL.state_dict(),

            "optimizer_state_dict":
                SSL_OPTIMIZER.state_dict(),

            "scaler_state_dict":
                AMP_SCALER.state_dict(),

            "lambda_t":
                PRIMARY_LAMBDA_T,

            "temperature":
                SSL_TEMPERATURE,

            "seed":
                PRIMARY_SEED,

            "feature_mask_probability":
                FEATURE_MASK_PROBABILITY,

            "gaussian_jitter_std":
                GAUSSIAN_JITTER_STD,

            "epoch_metrics":
                epoch_record
        }


        torch.save(
            checkpoint,
            LOCAL_LATEST_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_LATEST_CHECKPOINT,
            DRIVE_LATEST_CHECKPOINT
        )


        print(
            "\n"
            f"Epoch {epoch:02d} complete "
            f"| total={epoch_total_loss:.6f} "
            f"| NT-Xent={epoch_nt_xent_loss:.6f} "
            f"| order={epoch_order_loss:.6f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "Checkpoint already contains all 30 epochs."
    )


# ======================================================================
# 15 — LOAD FINAL TRAINING HISTORY
# ======================================================================

print("\n[6] SSL training history")
print("-" * 78)


if LOCAL_HISTORY_PATH.exists():

    SSL_TRAINING_HISTORY = pd.read_csv(
        LOCAL_HISTORY_PATH
    )

elif DRIVE_HISTORY_PATH.exists():

    SSL_TRAINING_HISTORY = pd.read_csv(
        DRIVE_HISTORY_PATH
    )

else:

    raise RuntimeError(
        "SSL training history was not found."
    )


display(
    SSL_TRAINING_HISTORY
)


COMPLETED_EPOCHS = int(
    SSL_TRAINING_HISTORY[
        "epoch"
    ].max()
)


# ======================================================================
# 16 — FINAL MODEL NUMERICAL CHECK
# ======================================================================

print("\n[7] Final pretrained-model validation")
print("-" * 78)


MODEL_PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in SSL_MODEL.parameters()
)


SSL_MODEL.eval()


# Deterministic small post-training check.
POST_SSL_LOADER = DataLoader(

    TRAIN_DATASET,

    batch_size=
        32,

    shuffle=
        False,

    num_workers=
        0
)


POST_X, _ = next(
    iter(
        POST_SSL_LOADER
    )
)


POST_X = POST_X.to(
    DEVICE
)


with torch.no_grad():

    (
        POST_SEQUENCE,
        POST_REPRESENTATION,
        POST_PROJECTION
    ) = SSL_MODEL.forward_ssl(
        POST_X
    )


POST_OUTPUTS_FINITE = bool(

    torch.isfinite(
        POST_SEQUENCE
    ).all()

    and

    torch.isfinite(
        POST_REPRESENTATION
    ).all()

    and

    torch.isfinite(
        POST_PROJECTION
    ).all()
)


POST_PROJECTION_NORMS = (
    torch.linalg.vector_norm(
        POST_PROJECTION,
        ord=2,
        dim=1
    )
)


POST_MAX_NORM_ERROR = float(

    torch.max(
        torch.abs(
            POST_PROJECTION_NORMS
            -
            1.0
        )
    )
    .detach()
    .cpu()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "All model parameters finite:",
    MODEL_PARAMETERS_FINITE
)

print(
    "All post-training outputs finite:",
    POST_OUTPUTS_FINITE
)

print(
    "Max projection norm error:",
    f"{POST_MAX_NORM_ERROR:.10e}"
)


# ======================================================================
# 17 — SAVE FINAL SSL-PRETRAINED MODEL
# ======================================================================

print("\n[8] Saving final pretrained model")
print("-" * 78)


FINAL_SSL_PACKAGE = {

    "model_state_dict":
        SSL_MODEL.state_dict(),

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        PRIMARY_SEED,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "lambda_t":
        PRIMARY_LAMBDA_T,

    "lambda_t_status":
        "provisional_not_yet_tuned",

    "temperature":
        SSL_TEMPERATURE,

    "feature_mask_probability":
        FEATURE_MASK_PROBABILITY,

    "gaussian_jitter_std":
        GAUSSIAN_JITTER_STD,

    "labels_used_during_SSL":
        False,

    "classifier_optimized_during_SSL":
        False
}


torch.save(
    FINAL_SSL_PACKAGE,
    LOCAL_FINAL_MODEL
)


shutil.copy2(
    LOCAL_FINAL_MODEL,
    DRIVE_FINAL_MODEL
)


FINAL_MODEL_BACKED_UP = (
    DRIVE_FINAL_MODEL.exists()
)


HISTORY_BACKED_UP = (
    DRIVE_HISTORY_PATH.exists()
)


CHECKPOINT_BACKED_UP = (
    DRIVE_LATEST_CHECKPOINT.exists()
)


POLICY_BACKED_UP = (
    DRIVE_POLICY_PATH.exists()
)


print(
    "Final model backed up:",
    FINAL_MODEL_BACKED_UP
)

print(
    "History backed up:",
    HISTORY_BACKED_UP
)

print(
    "Latest checkpoint backed up:",
    CHECKPOINT_BACKED_UP
)

print(
    "Policy backed up:",
    POLICY_BACKED_UP
)


# ======================================================================
# 18 — FINAL A15 VALIDATION
# ======================================================================

LAST_ROW = (

    SSL_TRAINING_HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


FINAL_LOSSES_FINITE = bool(

    np.isfinite(
        float(
            LAST_ROW[
                "total_loss"
            ]
        )
    )

    and

    np.isfinite(
        float(
            LAST_ROW[
                "NT_Xent_loss"
            ]
        )
    )

    and

    np.isfinite(
        float(
            LAST_ROW[
                "temporal_order_loss"
            ]
        )
    )
)


A15_VALID = bool(

    COMPLETED_EPOCHS
    ==
    SSL_EPOCHS

    and

    not CLASSIFIER_INCLUDED_IN_SSL

    and

    not SSL_LABELS_USED

    and

    NONFINITE_BATCHES == 0

    and

    FINAL_LOSSES_FINITE

    and

    MODEL_PARAMETERS_FINITE

    and

    POST_OUTPUTS_FINITE

    and

    POST_MAX_NORM_ERROR
    <
    1e-5

    and

    FINAL_MODEL_BACKED_UP

    and

    HISTORY_BACKED_UP

    and

    CHECKPOINT_BACKED_UP

    and

    POLICY_BACKED_UP
)


STEP_15_SSL_PRETRAINING_VALID = (
    A15_VALID
)


TOTAL_TRAINING_SECONDS = (
    time.time()
    -
    TRAINING_START_TIME
)


print("\n[9] Recovery Step A15 validation")
print("-" * 78)

print(
    "Completed SSL epochs           :",
    COMPLETED_EPOCHS,
    "/ 30"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Binary labels used             :",
    SSL_LABELS_USED
)

print(
    "Classifier optimized           :",
    CLASSIFIER_INCLUDED_IN_SSL
)

print(
    "Held-out DDoS used             :",
    False
)

print(
    "lambda_t                       :",
    PRIMARY_LAMBDA_T,
    "(provisional)"
)

print(
    "Final total loss               :",
    f"{float(LAST_ROW['total_loss']):.6f}"
)

print(
    "Final NT-Xent loss             :",
    f"{float(LAST_ROW['NT_Xent_loss']):.6f}"
)

print(
    "Final temporal-order loss      :",
    f"{float(LAST_ROW['temporal_order_loss']):.6f}"
)

print(
    "All model parameters finite    :",
    MODEL_PARAMETERS_FINITE
)

print(
    "Post-training outputs finite   :",
    POST_OUTPUTS_FINITE
)

print(
    "Projection normalization valid :",
    POST_MAX_NORM_ERROR
    <
    1e-5
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Final model backed up          :",
    FINAL_MODEL_BACKED_UP
)

print(
    "Latest checkpoint backed up    :",
    CHECKPOINT_BACKED_UP
)

print(
    "Training history backed up     :",
    HISTORY_BACKED_UP
)

print(
    "Total A15 runtime              :",
    f"{TOTAL_TRAINING_SECONDS / 60:.2f} minutes"
)


print("\n" + "=" * 78)

if A15_VALID:

    print(
        "✅ RECOVERY STEP A15 PASSED — "
        "30-epoch Fold-1 MOT-SSL-GRU self-supervised "
        "pretraining completed and was backed up to Drive."
    )

else:

    print(
        "❌ RECOVERY STEP A15 INCOMPLETE — "
        "Rerun this same A15 cell to resume from the "
        "latest Drive checkpoint."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A15 — MOT-SSL-GRU SELF-SUPERVISED PRETRAINING
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying training state
------------------------------------------------------------------------------
A13 PyTorch data valid: True
A14 architecture valid: True
Training windows: 105,577
Device: cuda

[2] SSL training configuration
------------------------------------------------------------------------------
Epochs: 30
Batch size: 256
Learning rate: 0.001
NT-Xent temperature: 0.2
Provisional lambda_t: 0.25
Lambda_t candidates: [0.1, 0.25, 0.5, 1.0]
Feature masking probability: 0.1
Gaussian jitter std: 0.01
Gradient clipping: 5.0
Mixed precision: True

[3] Creating clean SSL model
------------------------------------------------------------------------------
SSL trainable parameters: 167,105
Classifier included in SSL optimizer: False

[4] Checking for resumable SSL checkpoint
------------------------------------------------------------------------------
No previous checkpoint.
Starting SSL training from epoch 1.

[5] Starting real SSL training
------------------------------------------------------------------------------
Epoch 01/30 | Batch 100/413 | Loss 2.3728
Epoch 01/30 | Batch 200/413 | Loss 2.1988
Epoch 01/30 | Batch 300/413 | Loss 2.2551
Epoch 01/30 | Batch 400/413 | Loss 2.1500
Epoch 01/30 | Batch 413/413 | Loss 1.3642

Epoch 01 complete | total=2.387853 | NT-Xent=2.362503 | order=0.101400 | time=8.5s | checkpoint=Drive
Epoch 02/30 | Batch 100/413 | Loss 2.1220
Epoch 02/30 | Batch 200/413 | Loss 2.0570
Epoch 02/30 | Batch 300/413 | Loss 2.0914
Epoch 02/30 | Batch 400/413 | Loss 2.0252
Epoch 02/30 | Batch 413/413 | Loss 1.2776

Epoch 02 complete | total=2.078250 | NT-Xent=2.077768 | order=0.001927 | time=6.7s | checkpoint=Drive
Epoch 03/30 | Batch 100/413 | Loss 1.9762
Epoch 03/30 | Batch 200/413 | Loss 2.0220
Epoch 03/30 | Batch 300/413 | Loss 1.9707
Epoch 03/30 | Batch 400/413 | Loss 1.9397
Epoch 03/30 | Batch 413/413 | Loss 1.3072

Epoch 03 complete | total=2.004188 | NT-Xent=2.003909 | order=0.001115 | time=8.0s | checkpoint=Drive
Epoch 04/30 | Batch 100/413 | Loss 1.9713
Epoch 04/30 | Batch 200/413 | Loss 1.9684
Epoch 04/30 | Batch 300/413 | Loss 1.9650
Epoch 04/30 | Batch 400/413 | Loss 1.9904
Epoch 04/30 | Batch 413/413 | Loss 1.2112

Epoch 04 complete | total=1.963946 | NT-Xent=1.963759 | order=0.000748 | time=7.1s | checkpoint=Drive
Epoch 05/30 | Batch 100/413 | Loss 1.9901
Epoch 05/30 | Batch 200/413 | Loss 1.9242
Epoch 05/30 | Batch 300/413 | Loss 1.9426
Epoch 05/30 | Batch 400/413 | Loss 1.8832
Epoch 05/30 | Batch 413/413 | Loss 1.2757

Epoch 05 complete | total=1.935656 | NT-Xent=1.935490 | order=0.000663 | time=7.8s | checkpoint=Drive
Epoch 06/30 | Batch 100/413 | Loss 1.9190
Epoch 06/30 | Batch 200/413 | Loss 1.9209
Epoch 06/30 | Batch 300/413 | Loss 1.9010
Epoch 06/30 | Batch 400/413 | Loss 1.8822
Epoch 06/30 | Batch 413/413 | Loss 1.2006

Epoch 06 complete | total=1.916331 | NT-Xent=1.916188 | order=0.000571 | time=6.8s | checkpoint=Drive
Epoch 07/30 | Batch 100/413 | Loss 1.8855
Epoch 07/30 | Batch 200/413 | Loss 1.8867
Epoch 07/30 | Batch 300/413 | Loss 1.8994
Epoch 07/30 | Batch 400/413 | Loss 1.8892
Epoch 07/30 | Batch 413/413 | Loss 1.2040

Epoch 07 complete | total=1.899218 | NT-Xent=1.899078 | order=0.000559 | time=9.0s | checkpoint=Drive
Epoch 08/30 | Batch 100/413 | Loss 1.8855
Epoch 08/30 | Batch 200/413 | Loss 1.8967
Epoch 08/30 | Batch 300/413 | Loss 1.8928
Epoch 08/30 | Batch 400/413 | Loss 1.8583
Epoch 08/30 | Batch 413/413 | Loss 1.1849

Epoch 08 complete | total=1.889874 | NT-Xent=1.889735 | order=0.000555 | time=7.2s | checkpoint=Drive
Epoch 09/30 | Batch 100/413 | Loss 1.8706
Epoch 09/30 | Batch 200/413 | Loss 1.8364
Epoch 09/30 | Batch 300/413 | Loss 1.8290
Epoch 09/30 | Batch 400/413 | Loss 1.8820
Epoch 09/30 | Batch 413/413 | Loss 1.1793

Epoch 09 complete | total=1.876776 | NT-Xent=1.876636 | order=0.000560 | time=7.5s | checkpoint=Drive
Epoch 10/30 | Batch 100/413 | Loss 1.8747
Epoch 10/30 | Batch 200/413 | Loss 1.8678
Epoch 10/30 | Batch 300/413 | Loss 1.8284
Epoch 10/30 | Batch 400/413 | Loss 1.8816
Epoch 10/30 | Batch 413/413 | Loss 1.1391

Epoch 10 complete | total=1.869249 | NT-Xent=1.869121 | order=0.000509 | time=7.6s | checkpoint=Drive
Epoch 11/30 | Batch 100/413 | Loss 1.8831
Epoch 11/30 | Batch 200/413 | Loss 1.8508
Epoch 11/30 | Batch 300/413 | Loss 1.8827

RuntimeError: Non-finite gradient norm at epoch 11, batch 328.

# A15-FIX — Restart SSL in stable FP32

In [ ]:
# ======================================================================
# RECOVERY STEP A15-FIX
# STABLE FULL-FLOAT32 MOT-SSL-GRU PRETRAINING
#
# Fresh run from Epoch 1.
# Previous AMP run is preserved unchanged.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("RECOVERY STEP A15-FIX — STABLE FP32 SSL PRETRAINING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY REQUIRED STATE
# ======================================================================

print("\n[1] Verifying A13 + A14 state")
print("-" * 78)

required = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing = [
    name for name in required
    if name not in globals()
]

if missing:
    raise RuntimeError(
        "Missing runtime variables: "
        + ", ".join(missing)
        + "\nRerun A13 and A14 first."
    )

if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")


print("A13 valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("Training windows:", f"{len(TRAIN_DATASET):,}")
print("Device:", DEVICE)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

print("\n[2] Stable FP32 configuration")
print("-" * 78)

SEED = 13

EPOCHS = 30
BATCH_SIZE = 256
LEARNING_RATE = 1e-3

TEMPERATURE = 0.20
LAMBDA_T = 0.25

FEATURE_MASK_PROBABILITY = 0.10
GAUSSIAN_JITTER_STD = 0.01

MAX_GRADIENT_NORM = 5.0


print("Epochs:", EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Temperature:", TEMPERATURE)
print("lambda_t:", LAMBDA_T, "(provisional)")
print("Feature masking:", FEATURE_MASK_PROBABILITY)
print("Gaussian jitter:", GAUSSIAN_JITTER_STD)

print(
    "Mixed precision:",
    False,
    "← changed for numerical stability"
)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)

if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — FRESH MODEL
# ======================================================================

print("\n[3] Creating fresh FP32 SSL model")
print("-" * 78)

set_all_seeds(SEED)


SSL_MODEL_FP32 = MOTSSLGRU(

    input_dim=75,
    feature_embed_dim=128,
    gru_hidden_dim=128,
    gru_num_layers=1,
    projection_dim=64,
    order_hidden_dim=128,
    classifier_hidden_dim=64,
    dropout=0.10

).to(
    DEVICE
)


SSL_MODEL_FP32 = SSL_MODEL_FP32.float()


SSL_PARAMETERS_FP32 = (

    list(
        SSL_MODEL_FP32.feature_encoder.parameters()
    )
    +
    list(
        SSL_MODEL_FP32.temporal_encoder.parameters()
    )
    +
    list(
        SSL_MODEL_FP32.projection_head.parameters()
    )
    +
    list(
        SSL_MODEL_FP32.temporal_order_head.parameters()
    )
)


OPTIMIZER_FP32 = torch.optim.Adam(

    SSL_PARAMETERS_FP32,

    lr=LEARNING_RATE
)


ssl_ids = {
    id(p)
    for p in SSL_PARAMETERS_FP32
}


classifier_ids = {
    id(p)
    for p in SSL_MODEL_FP32.classifier_head.parameters()
}


CLASSIFIER_INCLUDED = bool(
    ssl_ids & classifier_ids
)


print(
    "SSL parameters:",
    f"{sum(p.numel() for p in SSL_PARAMETERS_FP32):,}"
)

print(
    "Classifier included:",
    CLASSIFIER_INCLUDED
)


if CLASSIFIER_INCLUDED:
    raise RuntimeError(
        "Classifier must not be trained during SSL."
    )


# ======================================================================
# 5 — DETERMINISTIC DATALOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED + int(epoch)
    )

    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        shuffle=True,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False,

        generator=generator
    )


# ======================================================================
# 6 — SSL AUGMENTATION
# ======================================================================

def augment_view(x):

    out = x.clone()


    if GAUSSIAN_JITTER_STD > 0:

        out = (
            out
            +
            torch.randn_like(out)
            *
            GAUSSIAN_JITTER_STD
        )


    if FEATURE_MASK_PROBABILITY > 0:

        mask = (
            torch.rand_like(out)
            <
            FEATURE_MASK_PROBABILITY
        )

        out = out.masked_fill(
            mask,
            0.0
        )


    return out


# ======================================================================
# 7 — NT-XENT LOSS
# ======================================================================

def nt_xent_loss_fp32(
    z1,
    z2,
    temperature
):

    batch_size = z1.shape[0]

    if batch_size < 2:
        raise RuntimeError(
            "NT-Xent requires >= 2 samples."
        )


    z = torch.cat(
        [z1, z2],
        dim=0
    ).float()


    similarity = (
        z @ z.T
    ) / temperature


    total = 2 * batch_size


    identity = torch.eye(
        total,
        dtype=torch.bool,
        device=z.device
    )


    similarity = similarity.masked_fill(
        identity,
        float("-inf")
    )


    targets = (

        torch.arange(
            total,
            device=z.device
        )

        +

        batch_size

    ) % total


    return F.cross_entropy(
        similarity,
        targets
    )


# ======================================================================
# 8 — TEMPORAL-ORDER LOSS
# ======================================================================

def order_loss_fp32(
    sequence_states,
    head
):

    hidden = sequence_states.shape[-1]


    earlier = (
        sequence_states[:, :-1, :]
        .reshape(-1, hidden)
    )


    later = (
        sequence_states[:, 1:, :]
        .reshape(-1, hidden)
    )


    forward_logits = head(
        earlier,
        later
    )


    reverse_logits = head(
        later,
        earlier
    )


    forward_targets = torch.ones_like(
        forward_logits
    )


    reverse_targets = torch.zeros_like(
        reverse_logits
    )


    forward_loss = (
        F.binary_cross_entropy_with_logits(
            forward_logits,
            forward_targets
        )
    )


    reverse_loss = (
        F.binary_cross_entropy_with_logits(
            reverse_logits,
            reverse_targets
        )
    )


    return (
        forward_loss
        +
        reverse_loss
    ) / 2.0


# ======================================================================
# 9 — NEW FP32 OUTPUT DIRECTORY
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_0p25_fp32"
)


DRIVE_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_0p25_fp32"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "ssl_training_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "ssl_training_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "ssl_training_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "ssl_training_policy.json"
)


# ======================================================================
# 10 — SAVE POLICY BEFORE TRAINING
# ======================================================================

POLICY = {

    "fold_id": 1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "epochs":
        EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "temperature":
        TEMPERATURE,

    "lambda_t":
        LAMBDA_T,

    "lambda_t_status":
        "provisional_not_yet_tuned",

    "feature_mask_probability":
        FEATURE_MASK_PROBABILITY,

    "gaussian_jitter_std":
        GAUSSIAN_JITTER_STD,

    "precision":
        "float32",

    "automatic_mixed_precision":
        False,

    "labels_used_during_SSL":
        False,

    "held_out_DDoS_used":
        False,

    "classifier_optimized":
        False,

    "maximum_gradient_norm":
        MAX_GRADIENT_NORM,

    "reason_for_fp32":
        (
            "Initial AMP run produced a non-finite "
            "gradient norm at epoch 11 batch 328. "
            "The FP32 experiment was restarted "
            "from epoch 1 to keep numerical precision "
            "consistent across all epochs."
        )
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        POLICY,
        f,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 11 — RESUME ONLY AN EXISTING FP32 RUN
# ======================================================================

print("\n[4] Checking FP32 recovery checkpoint")
print("-" * 78)

START_EPOCH = 1
history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if checkpoint.get(
        "precision"
    ) != "float32":

        raise RuntimeError(
            "Existing checkpoint is not an FP32 checkpoint."
        )


    SSL_MODEL_FP32.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER_FP32.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (
        int(
            checkpoint[
                "epoch"
            ]
        )
        +
        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )
            .to_dict(
                orient="records"
            )
        )


    print(
        "Resuming FP32 run from epoch:",
        START_EPOCH
    )


else:

    print(
        "No FP32 checkpoint found."
    )

    print(
        "Starting cleanly from epoch 1."
    )


# ======================================================================
# 12 — REAL FP32 TRAINING
# ======================================================================

print("\n[5] Starting stable FP32 SSL training")
print("-" * 78)

NONFINITE_BATCHES = 0

TOTAL_START = time.time()


if START_EPOCH <= EPOCHS:

    for epoch in range(
        START_EPOCH,
        EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        SSL_MODEL_FP32.train()


        sum_total = 0.0
        sum_contrastive = 0.0
        sum_order = 0.0

        examples = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            _
        ) in enumerate(
            loader,
            start=1
        ):

            # ------------------------------------------------------
            # "_" deliberately ignores binary labels.
            # ------------------------------------------------------

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(X).all()
            ):

                raise RuntimeError(
                    f"Non-finite input at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            view1 = augment_view(X)
            view2 = augment_view(X)


            OPTIMIZER_FP32.zero_grad(
                set_to_none=True
            )


            seq1, _, z1 = (
                SSL_MODEL_FP32.forward_ssl(
                    view1
                )
            )


            seq2, _, z2 = (
                SSL_MODEL_FP32.forward_ssl(
                    view2
                )
            )


            contrastive = (
                nt_xent_loss_fp32(
                    z1,
                    z2,
                    TEMPERATURE
                )
            )


            order1 = order_loss_fp32(
                seq1,
                SSL_MODEL_FP32.temporal_order_head
            )


            order2 = order_loss_fp32(
                seq2,
                SSL_MODEL_FP32.temporal_order_head
            )


            temporal_loss = (
                order1
                +
                order2
            ) / 2.0


            total_loss = (

                contrastive

                +

                LAMBDA_T
                *
                temporal_loss
            )


            if not bool(
                torch.isfinite(
                    total_loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite loss at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            total_loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    SSL_PARAMETERS_FP32,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm.detach().cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1


                diagnostic = {

                    "epoch":
                        epoch,

                    "batch":
                        batch_number,

                    "maximum_absolute_input":
                        float(
                            torch.max(
                                torch.abs(X)
                            )
                            .detach()
                            .cpu()
                        ),

                    "total_loss":
                        float(
                            total_loss
                            .detach()
                            .cpu()
                        ),

                    "contrastive_loss":
                        float(
                            contrastive
                            .detach()
                            .cpu()
                        ),

                    "order_loss":
                        float(
                            temporal_loss
                            .detach()
                            .cpu()
                        )
                }


                failure_path = (
                    DRIVE_DIR
                    /
                    "nonfinite_gradient_diagnostic.json"
                )


                with open(
                    failure_path,
                    "w",
                    encoding="utf-8"
                ) as f:

                    json.dump(
                        diagnostic,
                        f,
                        indent=4
                    )


                raise RuntimeError(
                    f"FP32 also produced a non-finite "
                    f"gradient at epoch {epoch}, "
                    f"batch {batch_number}. "
                    f"Diagnostic saved to Drive."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER_FP32.step()


            batch_size = int(
                X.shape[0]
            )


            sum_total += (
                float(
                    total_loss.detach().cpu()
                )
                *
                batch_size
            )


            sum_contrastive += (
                float(
                    contrastive.detach().cpu()
                )
                *
                batch_size
            )


            sum_order += (
                float(
                    temporal_loss.detach().cpu()
                )
                *
                batch_size
            )


            examples += batch_size


            if (
                batch_number % 100 == 0
                or
                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/{EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| Loss "
                    f"{float(total_loss.detach().cpu()):.4f}"
                )


        # ----------------------------------------------------------
        # Epoch summary
        # ----------------------------------------------------------

        mean_total = (
            sum_total / examples
        )


        mean_contrastive = (
            sum_contrastive / examples
        )


        mean_order = (
            sum_order / examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        row = {

            "epoch":
                epoch,

            "total_loss":
                mean_total,

            "NT_Xent_loss":
                mean_contrastive,

            "temporal_order_loss":
                mean_order,

            "lambda_t":
                LAMBDA_T,

            "examples":
                examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            ) != epoch
        ]


        history.append(
            row
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "precision":
                "float32",

            "model_state_dict":
                SSL_MODEL_FP32.state_dict(),

            "optimizer_state_dict":
                OPTIMIZER_FP32.state_dict(),

            "lambda_t":
                LAMBDA_T,

            "temperature":
                TEMPERATURE,

            "seed":
                SEED,

            "epoch_metrics":
                row
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| total={mean_total:.6f} "
            f"| NT-Xent={mean_contrastive:.6f} "
            f"| order={mean_order:.6f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "The FP32 checkpoint already contains "
        "all 30 epochs."
    )


# ======================================================================
# 13 — FINAL HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    SSL_FP32_HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    SSL_FP32_HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    SSL_FP32_HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 SSL epochs")
print("-" * 78)

display(
    SSL_FP32_HISTORY.tail(5)
)


# ======================================================================
# 14 — FINAL NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(p).all()
    )

    for p in SSL_MODEL_FP32.parameters()
)


validation_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=32,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(validation_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


SSL_MODEL_FP32.eval()


with torch.no_grad():

    seq_check, rep_check, z_check = (
        SSL_MODEL_FP32.forward_ssl(
            X_check
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(seq_check).all()

    and

    torch.isfinite(rep_check).all()

    and

    torch.isfinite(z_check).all()
)


norm_error = float(

    torch.max(

        torch.abs(

            torch.linalg.vector_norm(
                z_check,
                dim=1
            )

            -

            1.0
        )
    )
    .detach()
    .cpu()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "All parameters finite:",
    PARAMETERS_FINITE
)

print(
    "All outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Max projection norm error:",
    f"{norm_error:.10e}"
)


# ======================================================================
# 15 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        SSL_MODEL_FP32.state_dict(),

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "lambda_t":
        LAMBDA_T,

    "lambda_t_status":
        "provisional_not_yet_tuned",

    "temperature":
        TEMPERATURE,

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 16 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    SSL_FP32_HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A15_FIX_VALID = bool(

    COMPLETED_EPOCHS == 30

    and

    not CLASSIFIER_INCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    norm_error < 1e-5

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_15_SSL_PRETRAINING_VALID = (
    A15_FIX_VALID
)


print("\n[8] Recovery Step A15-FIX validation")
print("-" * 78)

print(
    "Completed SSL epochs           :",
    COMPLETED_EPOCHS,
    "/ 30"
)

print(
    "Precision                      :",
    "float32"
)

print(
    "Binary labels used             :",
    False
)

print(
    "Classifier optimized           :",
    CLASSIFIER_INCLUDED
)

print(
    "Held-out DDoS used             :",
    False
)

print(
    "lambda_t                       :",
    LAMBDA_T,
    "(provisional)"
)

print(
    "Final total loss               :",
    f"{float(FINAL_ROW['total_loss']):.6f}"
)

print(
    "Final NT-Xent loss             :",
    f"{float(FINAL_ROW['NT_Xent_loss']):.6f}"
)

print(
    "Final temporal-order loss      :",
    f"{float(FINAL_ROW['temporal_order_loss']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "All model parameters finite    :",
    PARAMETERS_FINITE
)

print(
    "Post-training outputs finite   :",
    OUTPUTS_FINITE
)

print(
    "Projection normalization valid :",
    norm_error < 1e-5
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Latest checkpoint backed up    :",
    DRIVE_CHECKPOINT.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A15_FIX_VALID:

    print(
        "✅ RECOVERY STEP A15-FIX PASSED — "
        "30-epoch Fold-1 SSL pretraining completed "
        "successfully in consistent FP32 precision."
    )

else:

    print(
        "❌ RECOVERY STEP A15-FIX INCOMPLETE — "
        "rerun this same cell to resume the FP32 run."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A15-FIX — STABLE FP32 SSL PRETRAINING
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying A13 + A14 state
------------------------------------------------------------------------------
A13 valid: True
A14 valid: True
Training windows: 105,577
Device: cuda

[2] Stable FP32 configuration
------------------------------------------------------------------------------
Epochs: 30
Batch size: 256
Learning rate: 0.001
Temperature: 0.2
lambda_t: 0.25 (provisional)
Feature masking: 0.1
Gaussian jitter: 0.01
Mixed precision: False ← changed for numerical stability

[3] Creating fresh FP32 SSL model
------------------------------------------------------------------------------
SSL parameters: 167,105
Classifier included: False

[4] Checking FP32 recovery checkpoint
------------------------------------------------------------------------------
No FP32 checkpoint found.
Starting cleanly from epoch 1.

[5] Starting stable FP32 SSL training
------------------------------------------------------------------------------
Epoch 01/30 | Batch 100/413 | Loss 2.3727
Epoch 01/30 | Batch 200/413 | Loss 2.1992
Epoch 01/30 | Batch 300/413 | Loss 2.2550
Epoch 01/30 | Batch 400/413 | Loss 2.1499
Epoch 01/30 | Batch 413/413 | Loss 1.3641

Epoch 01 complete | total=2.387869 | NT-Xent=2.362503 | order=0.101462 | time=6.6s | checkpoint=Drive
Epoch 02/30 | Batch 100/413 | Loss 2.1221
Epoch 02/30 | Batch 200/413 | Loss 2.0570
Epoch 02/30 | Batch 300/413 | Loss 2.0916
Epoch 02/30 | Batch 400/413 | Loss 2.0252
Epoch 02/30 | Batch 413/413 | Loss 1.2776

Epoch 02 complete | total=2.078221 | NT-Xent=2.077735 | order=0.001942 | time=6.0s | checkpoint=Drive
Epoch 03/30 | Batch 100/413 | Loss 1.9761
Epoch 03/30 | Batch 200/413 | Loss 2.0219
Epoch 03/30 | Batch 300/413 | Loss 1.9710
Epoch 03/30 | Batch 400/413 | Loss 1.9398
Epoch 03/30 | Batch 413/413 | Loss 1.3068

Epoch 03 complete | total=2.004164 | NT-Xent=2.003886 | order=0.001114 | time=7.6s | checkpoint=Drive
Epoch 04/30 | Batch 100/413 | Loss 1.9713
Epoch 04/30 | Batch 200/413 | Loss 1.9683
Epoch 04/30 | Batch 300/413 | Loss 1.9649
Epoch 04/30 | Batch 400/413 | Loss 1.9906
Epoch 04/30 | Batch 413/413 | Loss 1.2112

Epoch 04 complete | total=1.963915 | NT-Xent=1.963727 | order=0.000755 | time=6.1s | checkpoint=Drive
Epoch 05/30 | Batch 100/413 | Loss 1.9903
Epoch 05/30 | Batch 200/413 | Loss 1.9241
Epoch 05/30 | Batch 300/413 | Loss 1.9426
Epoch 05/30 | Batch 400/413 | Loss 1.8831
Epoch 05/30 | Batch 413/413 | Loss 1.2753

Epoch 05 complete | total=1.935657 | NT-Xent=1.935489 | order=0.000672 | time=6.2s | checkpoint=Drive
Epoch 06/30 | Batch 100/413 | Loss 1.9193
Epoch 06/30 | Batch 200/413 | Loss 1.9209
Epoch 06/30 | Batch 300/413 | Loss 1.9008
Epoch 06/30 | Batch 400/413 | Loss 1.8825
Epoch 06/30 | Batch 413/413 | Loss 1.2006

Epoch 06 complete | total=1.916339 | NT-Xent=1.916195 | order=0.000574 | time=6.5s | checkpoint=Drive
Epoch 07/30 | Batch 100/413 | Loss 1.8853
Epoch 07/30 | Batch 200/413 | Loss 1.8862
Epoch 07/30 | Batch 300/413 | Loss 1.8994
Epoch 07/30 | Batch 400/413 | Loss 1.8890
Epoch 07/30 | Batch 413/413 | Loss 1.2037

Epoch 07 complete | total=1.899245 | NT-Xent=1.899103 | order=0.000569 | time=5.8s | checkpoint=Drive
Epoch 08/30 | Batch 100/413 | Loss 1.8856
Epoch 08/30 | Batch 200/413 | Loss 1.8965
Epoch 08/30 | Batch 300/413 | Loss 1.8953
Epoch 08/30 | Batch 400/413 | Loss 1.8583
Epoch 08/30 | Batch 413/413 | Loss 1.1833

Epoch 08 complete | total=1.889929 | NT-Xent=1.889792 | order=0.000549 | time=7.0s | checkpoint=Drive
Epoch 09/30 | Batch 100/413 | Loss 1.8703
Epoch 09/30 | Batch 200/413 | Loss 1.8369
Epoch 09/30 | Batch 300/413 | Loss 1.8282
Epoch 09/30 | Batch 400/413 | Loss 1.8784
Epoch 09/30 | Batch 413/413 | Loss 1.1830

Epoch 09 complete | total=1.876904 | NT-Xent=1.876765 | order=0.000559 | time=5.8s | checkpoint=Drive
Epoch 10/30 | Batch 100/413 | Loss 1.8733
Epoch 10/30 | Batch 200/413 | Loss 1.8677
Epoch 10/30 | Batch 300/413 | Loss 1.8281
Epoch 10/30 | Batch 400/413 | Loss 1.8844
Epoch 10/30 | Batch 413/413 | Loss 1.1396

Epoch 10 complete | total=1.869318 | NT-Xent=1.869186 | order=0.000529 | time=7.0s | checkpoint=Drive
Epoch 11/30 | Batch 100/413 | Loss 1.8817
Epoch 11/30 | Batch 200/413 | Loss 1.8543
Epoch 11/30 | Batch 300/413 | Loss 1.8843
Epoch 11/30 | Batch 400/413 | Loss 1.8654
Epoch 11/30 | Batch 413/413 | Loss 1.1620

Epoch 11 complete | total=1.863159 | NT-Xent=1.863045 | order=0.000455 | time=6.2s | checkpoint=Drive
Epoch 12/30 | Batch 100/413 | Loss 1.8475
Epoch 12/30 | Batch 200/413 | Loss 1.8466
Epoch 12/30 | Batch 300/413 | Loss 1.8669
Epoch 12/30 | Batch 400/413 | Loss 1.8553
Epoch 12/30 | Batch 413/413 | Loss 1.0977

Epoch 12 complete | total=1.853462 | NT-Xent=1.853358 | order=0.000417 | time=7.2s | checkpoint=Drive
Epoch 13/30 | Batch 100/413 | Loss 1.8455
Epoch 13/30 | Batch 200/413 | Loss 1.8019
Epoch 13/30 | Batch 300/413 | Loss 1.8761
Epoch 13/30 | Batch 400/413 | Loss 1.8884
Epoch 13/30 | Batch 413/413 | Loss 1.1145

Epoch 13 complete | total=1.848929 | NT-Xent=1.848808 | order=0.000485 | time=6.0s | checkpoint=Drive
Epoch 14/30 | Batch 100/413 | Loss 1.8257
Epoch 14/30 | Batch 200/413 | Loss 1.8351
Epoch 14/30 | Batch 300/413 | Loss 1.8320
Epoch 14/30 | Batch 400/413 | Loss 1.8181
Epoch 14/30 | Batch 413/413 | Loss 1.1858

Epoch 14 complete | total=1.845669 | NT-Xent=1.845568 | order=0.000404 | time=6.9s | checkpoint=Drive
Epoch 15/30 | Batch 100/413 | Loss 1.8740
Epoch 15/30 | Batch 200/413 | Loss 1.8260
Epoch 15/30 | Batch 300/413 | Loss 1.8364
Epoch 15/30 | Batch 400/413 | Loss 1.8063
Epoch 15/30 | Batch 413/413 | Loss 1.1526

Epoch 15 complete | total=1.837203 | NT-Xent=1.837121 | order=0.000331 | time=6.0s | checkpoint=Drive
Epoch 16/30 | Batch 100/413 | Loss 1.8351
Epoch 16/30 | Batch 200/413 | Loss 1.8537
Epoch 16/30 | Batch 300/413 | Loss 1.7894
Epoch 16/30 | Batch 400/413 | Loss 1.8357
Epoch 16/30 | Batch 413/413 | Loss 1.1597

Epoch 16 complete | total=1.835646 | NT-Xent=1.835555 | order=0.000362 | time=7.1s | checkpoint=Drive
Epoch 17/30 | Batch 100/413 | Loss 1.7902
Epoch 17/30 | Batch 200/413 | Loss 1.8648
Epoch 17/30 | Batch 300/413 | Loss 1.8721
Epoch 17/30 | Batch 400/413 | Loss 1.8280
Epoch 17/30 | Batch 413/413 | Loss 1.1217

Epoch 17 complete | total=1.832057 | NT-Xent=1.831968 | order=0.000357 | time=5.9s | checkpoint=Drive
Epoch 18/30 | Batch 100/413 | Loss 1.8273
Epoch 18/30 | Batch 200/413 | Loss 1.8061
Epoch 18/30 | Batch 300/413 | Loss 1.8020
Epoch 18/30 | Batch 400/413 | Loss 1.8331
Epoch 18/30 | Batch 413/413 | Loss 1.1337

Epoch 18 complete | total=1.826751 | NT-Xent=1.826674 | order=0.000310 | time=6.5s | checkpoint=Drive
Epoch 19/30 | Batch 100/413 | Loss 1.7978
Epoch 19/30 | Batch 200/413 | Loss 1.8256
Epoch 19/30 | Batch 300/413 | Loss 1.8255
Epoch 19/30 | Batch 400/413 | Loss 1.8420
Epoch 19/30 | Batch 413/413 | Loss 1.0878

Epoch 19 complete | total=1.824177 | NT-Xent=1.824102 | order=0.000300 | time=6.1s | checkpoint=Drive
Epoch 20/30 | Batch 100/413 | Loss 1.8410
Epoch 20/30 | Batch 200/413 | Loss 1.8068
Epoch 20/30 | Batch 300/413 | Loss 1.8635
Epoch 20/30 | Batch 400/413 | Loss 1.8498
Epoch 20/30 | Batch 413/413 | Loss 1.1030

Epoch 20 complete | total=1.820426 | NT-Xent=1.820341 | order=0.000343 | time=6.6s | checkpoint=Drive
Epoch 21/30 | Batch 100/413 | Loss 1.7824
Epoch 21/30 | Batch 200/413 | Loss 1.7803
Epoch 21/30 | Batch 300/413 | Loss 1.7975
Epoch 21/30 | Batch 400/413 | Loss 1.8306
Epoch 21/30 | Batch 413/413 | Loss 1.1069

Epoch 21 complete | total=1.815977 | NT-Xent=1.815898 | order=0.000315 | time=6.7s | checkpoint=Drive
Epoch 22/30 | Batch 100/413 | Loss 1.8309
Epoch 22/30 | Batch 200/413 | Loss 1.8262
Epoch 22/30 | Batch 300/413 | Loss 1.8299
Epoch 22/30 | Batch 400/413 | Loss 1.8179
Epoch 22/30 | Batch 413/413 | Loss 1.1222

Epoch 22 complete | total=1.815112 | NT-Xent=1.815048 | order=0.000258 | time=6.1s | checkpoint=Drive
Epoch 23/30 | Batch 100/413 | Loss 1.8554
Epoch 23/30 | Batch 200/413 | Loss 1.8128
Epoch 23/30 | Batch 300/413 | Loss 1.7976
Epoch 23/30 | Batch 400/413 | Loss 1.7846
Epoch 23/30 | Batch 413/413 | Loss 1.1108

Epoch 23 complete | total=1.811695 | NT-Xent=1.811621 | order=0.000295 | time=8.0s | checkpoint=Drive
Epoch 24/30 | Batch 100/413 | Loss 1.8053
Epoch 24/30 | Batch 200/413 | Loss 1.8292
Epoch 24/30 | Batch 300/413 | Loss 1.8259
Epoch 24/30 | Batch 400/413 | Loss 1.8412
Epoch 24/30 | Batch 413/413 | Loss 1.0553

Epoch 24 complete | total=1.809408 | NT-Xent=1.809349 | order=0.000237 | time=5.8s | checkpoint=Drive
Epoch 25/30 | Batch 100/413 | Loss 1.8227
Epoch 25/30 | Batch 200/413 | Loss 1.8226
Epoch 25/30 | Batch 300/413 | Loss 1.8359
Epoch 25/30 | Batch 400/413 | Loss 1.8547
Epoch 25/30 | Batch 413/413 | Loss 1.0867

Epoch 25 complete | total=1.808192 | NT-Xent=1.808125 | order=0.000270 | time=6.8s | checkpoint=Drive
Epoch 26/30 | Batch 100/413 | Loss 1.7842
Epoch 26/30 | Batch 200/413 | Loss 1.8168
Epoch 26/30 | Batch 300/413 | Loss 1.8299
Epoch 26/30 | Batch 400/413 | Loss 1.7929
Epoch 26/30 | Batch 413/413 | Loss 1.1004

Epoch 26 complete | total=1.803042 | NT-Xent=1.802993 | order=0.000195 | time=5.8s | checkpoint=Drive
Epoch 27/30 | Batch 100/413 | Loss 1.8233
Epoch 27/30 | Batch 200/413 | Loss 1.8218
Epoch 27/30 | Batch 300/413 | Loss 1.7743
Epoch 27/30 | Batch 400/413 | Loss 1.8152
Epoch 27/30 | Batch 413/413 | Loss 1.1072

Epoch 27 complete | total=1.802321 | NT-Xent=1.802256 | order=0.000258 | time=6.9s | checkpoint=Drive
Epoch 28/30 | Batch 100/413 | Loss 1.8089
Epoch 28/30 | Batch 200/413 | Loss 1.8256
Epoch 28/30 | Batch 300/413 | Loss 1.8298
Epoch 28/30 | Batch 400/413 | Loss 1.8269
Epoch 28/30 | Batch 413/413 | Loss 1.0534

Epoch 28 complete | total=1.804435 | NT-Xent=1.804381 | order=0.000218 | time=5.8s | checkpoint=Drive
Epoch 29/30 | Batch 100/413 | Loss 1.8105
Epoch 29/30 | Batch 200/413 | Loss 1.7752
Epoch 29/30 | Batch 300/413 | Loss 1.8181
Epoch 29/30 | Batch 400/413 | Loss 1.8232
Epoch 29/30 | Batch 413/413 | Loss 1.1683

Epoch 29 complete | total=1.800630 | NT-Xent=1.800579 | order=0.000202 | time=6.9s | checkpoint=Drive
Epoch 30/30 | Batch 100/413 | Loss 1.7909
Epoch 30/30 | Batch 200/413 | Loss 1.8091
Epoch 30/30 | Batch 300/413 | Loss 1.7786
Epoch 30/30 | Batch 400/413 | Loss 1.7786
Epoch 30/30 | Batch 413/413 | Loss 1.0744

Epoch 30 complete | total=1.797466 | NT-Xent=1.797412 | order=0.000216 | time=5.8s | checkpoint=Drive

[6] Last 5 SSL epochs
------------------------------------------------------------------------------

,epoch,total_loss,NT_Xent_loss,temporal_order_loss,lambda_t,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
25,26,1.803042,1.802993,0.000195,0.25,105577,413,1.134300,5.765197
26,27,1.802321,1.802256,0.000258,0.25,105577,413,0.952553,6.871090
27,28,1.804435,1.804381,0.000218,0.25,105577,413,1.845819,5.771499
28,29,1.800630,1.800579,0.000202,0.25,105577,413,1.135230,6.923454
29,30,1.797466,1.797412,0.000216,0.25,105577,413,1.074137,5.797894

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 30
All parameters finite: True
All outputs finite: True
Max projection norm error: 5.9604644775e-08

[8] Recovery Step A15-FIX validation
------------------------------------------------------------------------------
Completed SSL epochs           : 30 / 30
Precision                      : float32
Binary labels used             : False
Classifier optimized           : False
Held-out DDoS used             : False
lambda_t                       : 0.25 (provisional)
Final total loss               : 1.797466
Final NT-Xent loss             : 1.797412
Final temporal-order loss      : 0.000216
Non-finite batches             : 0
All model parameters finite    : True
Post-training outputs finite   : True
Projection normalization valid : True
Final model backed up          : True
Latest checkpoint backed up    : True
Training history backed up     : True

==============================================================================
✅ RECOVERY STEP A15-FIX PASSED — 30-epoch Fold-1 SSL pretraining completed successfully in consistent FP32 precision.
==============================================================================

# Recovery Step A16 — Supervised fine-tuning

In [ ]:
# ======================================================================
# RECOVERY STEP A16
# SUPERVISED FINE-TUNING OF SSL-PRETRAINED MOT-SSL-GRU
#
# Fold 1: DDoS held out
# Fixed 20 epochs
# FP32
# No threshold tuning in this step
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("RECOVERY STEP A16 — SUPERVISED FINE-TUNING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying fine-tuning prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_15_SSL_PRETRAINING_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
        + "\nRerun the required recovery steps first."
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_15_SSL_PRETRAINING_VALID:
    raise RuntimeError("A15-FIX did not pass.")


print("A13 data valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 architecture valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A15 SSL valid:", STEP_15_SSL_PRETRAINING_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

print("\n[2] Fine-tuning configuration")
print("-" * 78)

SEED = 13

FINETUNE_EPOCHS = 20
BATCH_SIZE = 256

LEARNING_RATE = 1e-3

MAX_GRADIENT_NORM = 5.0

IMBALANCE_METHOD = "none"

PRECISION = "float32"


print("Epochs:", FINETUNE_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Precision:", PRECISION)
print("Imbalance method:", IMBALANCE_METHOD)
print("Gradient clipping:", MAX_GRADIENT_NORM)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — LOCATE FINAL SSL-PRETRAINED MODEL
# ======================================================================

print("\n[3] Loading SSL-pretrained encoder")
print("-" * 78)


DRIVE_SSL_MODEL = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_0p25_fp32/"
    "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


if not DRIVE_SSL_MODEL.exists():

    raise RuntimeError(
        "Final A15-FIX pretrained model "
        "was not found in Drive."
    )


SSL_PACKAGE = torch.load(
    DRIVE_SSL_MODEL,
    map_location=DEVICE,
    weights_only=False
)


print(
    "SSL completed epochs:",
    SSL_PACKAGE[
        "completed_epochs"
    ]
)

print(
    "SSL precision:",
    SSL_PACKAGE[
        "precision"
    ]
)

print(
    "SSL lambda_t:",
    SSL_PACKAGE[
        "lambda_t"
    ]
)

print(
    "SSL labels used:",
    SSL_PACKAGE[
        "labels_used_during_SSL"
    ]
)


# ======================================================================
# 5 — CREATE FINE-TUNING MODEL
# ======================================================================

set_all_seeds(SEED)


FINETUNE_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


# --------------------------------------------------------------
# Load pretrained network state.
# --------------------------------------------------------------

FINETUNE_MODEL.load_state_dict(
    SSL_PACKAGE[
        "model_state_dict"
    ],
    strict=True
)


# ======================================================================
# 6 — REINITIALIZE CLASSIFIER HEAD
# ======================================================================

# The classifier was deliberately excluded during SSL.
# Reinitialize it explicitly before supervised training.

set_all_seeds(
    SEED + 1000
)


for module in FINETUNE_MODEL.classifier_head.modules():

    if hasattr(
        module,
        "reset_parameters"
    ):

        module.reset_parameters()


print(
    "SSL encoder loaded:",
    True
)

print(
    "Classifier freshly initialized:",
    True
)


# ======================================================================
# 7 — SELECT FINE-TUNING PARAMETERS
# ======================================================================

# Full fine-tuning:
# feature encoder + GRU encoder + classifier.
#
# SSL-only heads are excluded.

FINETUNE_PARAMETERS = (

    list(
        FINETUNE_MODEL.feature_encoder.parameters()
    )

    +

    list(
        FINETUNE_MODEL.temporal_encoder.parameters()
    )

    +

    list(
        FINETUNE_MODEL.classifier_head.parameters()
    )
)


PROJECTION_TRAINED = False
ORDER_HEAD_TRAINED = False


FINETUNE_PARAMETER_COUNT = sum(

    parameter.numel()

    for parameter
    in FINETUNE_PARAMETERS
)


print(
    "Fine-tuned parameters:",
    f"{FINETUNE_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    PROJECTION_TRAINED
)

print(
    "Temporal-order head optimized:",
    ORDER_HEAD_TRAINED
)


# ======================================================================
# 8 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    FINETUNE_PARAMETERS,

    lr=
        LEARNING_RATE
)


# ======================================================================
# 9 — REPRODUCIBLE TRAINING LOADER
# ======================================================================

def make_finetune_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED + int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=
            BATCH_SIZE,

        shuffle=
            True,

        num_workers=
            0,

        pin_memory=
            torch.cuda.is_available(),

        drop_last=
            False,

        generator=
            generator
    )


# ======================================================================
# 10 — OUTPUT DIRECTORIES
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_0p25_fp32/"
    "imbalance_none"
)


DRIVE_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_0p25_fp32/"
    "imbalance_none"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "fine_tuning_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "fine_tuning_history.csv"
)


LOCAL_FINAL_MODEL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


DRIVE_FINAL_MODEL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fine_tuning_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fine_tuning_policy.json"
)


# ======================================================================
# 11 — SAVE FINE-TUNING POLICY
# ======================================================================

POLICY = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "initialization":
        "A15-FIX SSL-pretrained encoder",

    "SSL_lambda_t":
        0.25,

    "SSL_lambda_status":
        "provisional_not_yet_tuned",

    "epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "optimizer":
        "Adam",

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "imbalance_method_status":
        (
            "initial_no-rebalancing_condition; "
            "RQ4 later compares none, class_weight, "
            "and weighted_sampler"
        ),

    "classifier_head_reinitialized":
        True,

    "feature_encoder_trainable":
        True,

    "GRU_encoder_trainable":
        True,

    "classifier_trainable":
        True,

    "projection_head_trainable":
        False,

    "temporal_order_head_trainable":
        False,

    "held_out_DDoS_used":
        False,

    "threshold_selected":
        False,

    "threshold_selection_stage":
        "A17_using_development_validation_only"
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 12 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking supervised recovery checkpoint")
print("-" * 78)


START_EPOCH = 1
history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if checkpoint.get(
        "precision"
    ) != "float32":

        raise RuntimeError(
            "Fine-tuning checkpoint precision mismatch."
        )


    if checkpoint.get(
        "imbalance_method"
    ) != IMBALANCE_METHOD:

        raise RuntimeError(
            "Fine-tuning imbalance-policy mismatch."
        )


    FINETUNE_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (
        int(
            checkpoint[
                "epoch"
            ]
        )
        +
        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No fine-tuning checkpoint."
    )

    print(
        "Starting supervised training from epoch 1."
    )


# ======================================================================
# 13 — SUPERVISED TRAINING
# ======================================================================

print("\n[5] Starting supervised fine-tuning")
print("-" * 78)


NONFINITE_BATCHES = 0

TOTAL_START = time.time()


if START_EPOCH <= FINETUNE_EPOCHS:

    for epoch in range(
        START_EPOCH,
        FINETUNE_EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_finetune_loader(
            epoch
        )


        FINETUNE_MODEL.train()


        running_loss = 0.0

        total_examples = 0


        # These are only diagnostic at threshold 0.5.
        diagnostic_correct = 0

        predicted_attack_count = 0
        predicted_benign_count = 0

        actual_attack_count = 0
        actual_benign_count = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            y
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            y = y.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(X).all()
            ):

                raise RuntimeError(
                    f"Non-finite input at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            logits = (
                FINETUNE_MODEL
                .forward_classifier(
                    X
                )
            )


            loss = (
                F.binary_cross_entropy_with_logits(
                    logits,
                    y
                )
            )


            if not bool(
                torch.isfinite(loss)
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite supervised loss at "
                    f"epoch {epoch}, batch {batch_number}."
                )


            loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    FINETUNE_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            running_loss += (

                float(
                    loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            total_examples += (
                batch_size
            )


            # ------------------------------------------------------
            # 0.5 threshold is diagnostic only.
            # It is NOT the final selected threshold.
            # ------------------------------------------------------

            with torch.no_grad():

                probabilities = torch.sigmoid(
                    logits
                )


                predictions = (
                    probabilities
                    >=
                    0.5
                ).float()


                diagnostic_correct += int(

                    (
                        predictions
                        ==
                        y
                    )
                    .sum()
                    .item()
                )


                predicted_attack_count += int(
                    (
                        predictions == 1
                    ).sum().item()
                )


                predicted_benign_count += int(
                    (
                        predictions == 0
                    ).sum().item()
                )


                actual_attack_count += int(
                    (
                        y == 1
                    ).sum().item()
                )


                actual_benign_count += int(
                    (
                        y == 0
                    ).sum().item()
                )


            if (
                batch_number % 100 == 0
                or
                batch_number
                ==
                len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/"
                    f"{FINETUNE_EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| BCE "
                    f"{float(loss.detach().cpu()):.6f}"
                )


        # ----------------------------------------------------------
        # Epoch metrics
        # ----------------------------------------------------------

        mean_loss = (
            running_loss
            /
            total_examples
        )


        diagnostic_accuracy = (

            diagnostic_correct

            /
            total_examples
        )


        predicted_attack_fraction = (

            predicted_attack_count

            /
            total_examples
        )


        predicted_benign_fraction = (

            predicted_benign_count

            /
            total_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "training_BCE_loss":
                mean_loss,

            "diagnostic_accuracy_at_0p5":
                diagnostic_accuracy,

            "predicted_attack_fraction_at_0p5":
                predicted_attack_fraction,

            "predicted_benign_fraction_at_0p5":
                predicted_benign_fraction,

            "actual_attack_windows":
                actual_attack_count,

            "actual_benign_windows":
                actual_benign_count,

            "examples":
                total_examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old_record

            for old_record in history

            if int(
                old_record[
                    "epoch"
                ]
            ) != epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "precision":
                "float32",

            "imbalance_method":
                IMBALANCE_METHOD,

            "model_state_dict":
                FINETUNE_MODEL.state_dict(),

            "optimizer_state_dict":
                OPTIMIZER.state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| BCE={mean_loss:.6f} "
            f"| diagnostic_acc@0.5="
            f"{diagnostic_accuracy:.4f} "
            f"| predicted_attack="
            f"{predicted_attack_fraction:.4f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "Fine-tuning checkpoint already "
        "contains all 20 epochs."
    )


# ======================================================================
# 14 — LOAD COMPLETE HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    FINETUNE_HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    FINETUNE_HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    FINETUNE_HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 supervised epochs")
print("-" * 78)

display(
    FINETUNE_HISTORY.tail(5)
)


# ======================================================================
# 15 — FINAL NUMERICAL CHECK
# ======================================================================

print("\n[7] Final model numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in FINETUNE_MODEL.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=64,

    shuffle=False,

    num_workers=0
)


X_check, y_check = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


FINETUNE_MODEL.eval()


with torch.no_grad():

    check_logits = (
        FINETUNE_MODEL
        .forward_classifier(
            X_check
        )
    )


    check_probabilities = (
        torch.sigmoid(
            check_logits
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        check_logits
    ).all()

    and

    torch.isfinite(
        check_probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    (
        check_probabilities
        >=
        0.0
    ).all()

    and

    (
        check_probabilities
        <=
        1.0
    ).all()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "All parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Classifier outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 16 — SAVE FINAL FINE-TUNED MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        FINETUNE_MODEL.state_dict(),

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "SSL_lambda_t":
        0.25,

    "SSL_lambda_status":
        "provisional_not_yet_tuned",

    "imbalance_method":
        IMBALANCE_METHOD,

    "threshold_selected":
        False,

    "threshold_note":
        (
            "Decision threshold must be selected "
            "using development validation only."
        )
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL_MODEL
)


shutil.copy2(
    LOCAL_FINAL_MODEL,
    DRIVE_FINAL_MODEL
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    FINETUNE_HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


FINAL_LOSS_FINITE = bool(

    np.isfinite(

        float(
            FINAL_ROW[
                "training_BCE_loss"
            ]
        )
    )
)


A16_VALID = bool(

    COMPLETED_EPOCHS
    ==
    FINETUNE_EPOCHS

    and

    NONFINITE_BATCHES
    ==
    0

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    FINAL_LOSS_FINITE

    and

    DRIVE_FINAL_MODEL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_16_FINETUNING_VALID = (
    A16_VALID
)


print("\n[8] Recovery Step A16 validation")
print("-" * 78)

print(
    "Completed fine-tuning epochs   :",
    COMPLETED_EPOCHS,
    "/ 20"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Held-out DDoS used             :",
    False
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Threshold tuned                :",
    False
)

print(
    "Final training BCE             :",
    f"{float(FINAL_ROW['training_BCE_loss']):.6f}"
)

print(
    "Diagnostic accuracy @ 0.5      :",
    f"{float(FINAL_ROW['diagnostic_accuracy_at_0p5']):.6f}"
)

print(
    "Predicted attack fraction      :",
    f"{float(FINAL_ROW['predicted_attack_fraction_at_0p5']):.6f}"
)

print(
    "Predicted benign fraction      :",
    f"{float(FINAL_ROW['predicted_benign_fraction_at_0p5']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "All parameters finite          :",
    PARAMETERS_FINITE
)

print(
    "Classifier outputs finite      :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL_MODEL.exists()
)

print(
    "Latest checkpoint backed up    :",
    DRIVE_CHECKPOINT.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A16_VALID:

    print(
        "✅ RECOVERY STEP A16 PASSED — "
        "Fold-1 SSL-pretrained MOT-SSL-GRU "
        "completed 20 supervised fine-tuning epochs."
    )

else:

    print(
        "❌ RECOVERY STEP A16 INCOMPLETE — "
        "rerun this same A16 cell to resume "
        "from the latest Drive checkpoint."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A16 — SUPERVISED FINE-TUNING
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying fine-tuning prerequisites
------------------------------------------------------------------------------
A13 data valid: True
A14 architecture valid: True
A15 SSL valid: True
Training windows: 105,577
Device: cuda

[2] Fine-tuning configuration
------------------------------------------------------------------------------
Epochs: 20
Batch size: 256
Learning rate: 0.001
Precision: float32
Imbalance method: none
Gradient clipping: 5.0

[3] Loading SSL-pretrained encoder
------------------------------------------------------------------------------
SSL completed epochs: 30
SSL precision: float32
SSL lambda_t: 0.25
SSL labels used: False
SSL encoder loaded: True
Classifier freshly initialized: True
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[4] Checking supervised recovery checkpoint
------------------------------------------------------------------------------
No fine-tuning checkpoint.
Starting supervised training from epoch 1.

[5] Starting supervised fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/413 | BCE 0.129999
Epoch 01/20 | Batch 200/413 | BCE 0.157540
Epoch 01/20 | Batch 300/413 | BCE 0.089006
Epoch 01/20 | Batch 400/413 | BCE 0.080559
Epoch 01/20 | Batch 413/413 | BCE 0.105926

Epoch 01 complete | BCE=0.131346 | diagnostic_acc@0.5=0.9451 | predicted_attack=0.9430 | time=5.9s | checkpoint=Drive
Epoch 02/20 | Batch 100/413 | BCE 0.090747
Epoch 02/20 | Batch 200/413 | BCE 0.072866
Epoch 02/20 | Batch 300/413 | BCE 0.087076
Epoch 02/20 | Batch 400/413 | BCE 0.077581
Epoch 02/20 | Batch 413/413 | BCE 0.062259

Epoch 02 complete | BCE=0.074911 | diagnostic_acc@0.5=0.9668 | predicted_attack=0.9277 | time=5.0s | checkpoint=Drive
Epoch 03/20 | Batch 100/413 | BCE 0.057607
Epoch 03/20 | Batch 200/413 | BCE 0.053677
Epoch 03/20 | Batch 300/413 | BCE 0.056898
Epoch 03/20 | Batch 400/413 | BCE 0.048758
Epoch 03/20 | Batch 413/413 | BCE 0.069028

Epoch 03 complete | BCE=0.063146 | diagnostic_acc@0.5=0.9724 | predicted_attack=0.9261 | time=4.4s | checkpoint=Drive
Epoch 04/20 | Batch 100/413 | BCE 0.038715
Epoch 04/20 | Batch 200/413 | BCE 0.061891
Epoch 04/20 | Batch 300/413 | BCE 0.065739
Epoch 04/20 | Batch 400/413 | BCE 0.055846
Epoch 04/20 | Batch 413/413 | BCE 0.093654

Epoch 04 complete | BCE=0.056387 | diagnostic_acc@0.5=0.9758 | predicted_attack=0.9256 | time=3.8s | checkpoint=Drive
Epoch 05/20 | Batch 100/413 | BCE 0.055552
Epoch 05/20 | Batch 200/413 | BCE 0.042181
Epoch 05/20 | Batch 300/413 | BCE 0.074915
Epoch 05/20 | Batch 400/413 | BCE 0.085573
Epoch 05/20 | Batch 413/413 | BCE 0.047981

Epoch 05 complete | BCE=0.049362 | diagnostic_acc@0.5=0.9793 | predicted_attack=0.9245 | time=3.8s | checkpoint=Drive
Epoch 06/20 | Batch 100/413 | BCE 0.020223
Epoch 06/20 | Batch 200/413 | BCE 0.069808
Epoch 06/20 | Batch 300/413 | BCE 0.051109
Epoch 06/20 | Batch 400/413 | BCE 0.038786
Epoch 06/20 | Batch 413/413 | BCE 0.078519

Epoch 06 complete | BCE=0.044574 | diagnostic_acc@0.5=0.9812 | predicted_attack=0.9245 | time=4.7s | checkpoint=Drive
Epoch 07/20 | Batch 100/413 | BCE 0.038807
Epoch 07/20 | Batch 200/413 | BCE 0.031994
Epoch 07/20 | Batch 300/413 | BCE 0.030206
Epoch 07/20 | Batch 400/413 | BCE 0.061409
Epoch 07/20 | Batch 413/413 | BCE 0.030782

Epoch 07 complete | BCE=0.041029 | diagnostic_acc@0.5=0.9828 | predicted_attack=0.9248 | time=3.8s | checkpoint=Drive
Epoch 08/20 | Batch 100/413 | BCE 0.057568
Epoch 08/20 | Batch 200/413 | BCE 0.049934
Epoch 08/20 | Batch 300/413 | BCE 0.028825
Epoch 08/20 | Batch 400/413 | BCE 0.034936
Epoch 08/20 | Batch 413/413 | BCE 0.036371

Epoch 08 complete | BCE=0.036010 | diagnostic_acc@0.5=0.9851 | predicted_attack=0.9246 | time=3.8s | checkpoint=Drive
Epoch 09/20 | Batch 100/413 | BCE 0.019334
Epoch 09/20 | Batch 200/413 | BCE 0.042974
Epoch 09/20 | Batch 300/413 | BCE 0.042443
Epoch 09/20 | Batch 400/413 | BCE 0.042447
Epoch 09/20 | Batch 413/413 | BCE 0.027393

Epoch 09 complete | BCE=0.032192 | diagnostic_acc@0.5=0.9865 | predicted_attack=0.9240 | time=4.4s | checkpoint=Drive
Epoch 10/20 | Batch 100/413 | BCE 0.032214
Epoch 10/20 | Batch 200/413 | BCE 0.022914
Epoch 10/20 | Batch 300/413 | BCE 0.012625
Epoch 10/20 | Batch 400/413 | BCE 0.032301
Epoch 10/20 | Batch 413/413 | BCE 0.059794

Epoch 10 complete | BCE=0.028892 | diagnostic_acc@0.5=0.9879 | predicted_attack=0.9242 | time=4.2s | checkpoint=Drive
Epoch 11/20 | Batch 100/413 | BCE 0.005884
Epoch 11/20 | Batch 200/413 | BCE 0.019739
Epoch 11/20 | Batch 300/413 | BCE 0.030067
Epoch 11/20 | Batch 400/413 | BCE 0.042468
Epoch 11/20 | Batch 413/413 | BCE 0.043713

Epoch 11 complete | BCE=0.026516 | diagnostic_acc@0.5=0.9889 | predicted_attack=0.9239 | time=3.8s | checkpoint=Drive
Epoch 12/20 | Batch 100/413 | BCE 0.013043
Epoch 12/20 | Batch 200/413 | BCE 0.024711
Epoch 12/20 | Batch 300/413 | BCE 0.033113
Epoch 12/20 | Batch 400/413 | BCE 0.020658
Epoch 12/20 | Batch 413/413 | BCE 0.010185

Epoch 12 complete | BCE=0.023801 | diagnostic_acc@0.5=0.9905 | predicted_attack=0.9242 | time=4.0s | checkpoint=Drive
Epoch 13/20 | Batch 100/413 | BCE 0.056158
Epoch 13/20 | Batch 200/413 | BCE 0.036740
Epoch 13/20 | Batch 300/413 | BCE 0.021351
Epoch 13/20 | Batch 400/413 | BCE 0.032195
Epoch 13/20 | Batch 413/413 | BCE 0.013287

Epoch 13 complete | BCE=0.021175 | diagnostic_acc@0.5=0.9913 | predicted_attack=0.9242 | time=4.6s | checkpoint=Drive
Epoch 14/20 | Batch 100/413 | BCE 0.038342
Epoch 14/20 | Batch 200/413 | BCE 0.008268
Epoch 14/20 | Batch 300/413 | BCE 0.034444
Epoch 14/20 | Batch 400/413 | BCE 0.024206
Epoch 14/20 | Batch 413/413 | BCE 0.022272

Epoch 14 complete | BCE=0.019420 | diagnostic_acc@0.5=0.9920 | predicted_attack=0.9242 | time=3.8s | checkpoint=Drive
Epoch 15/20 | Batch 100/413 | BCE 0.010495
Epoch 15/20 | Batch 200/413 | BCE 0.025071
Epoch 15/20 | Batch 300/413 | BCE 0.009617
Epoch 15/20 | Batch 400/413 | BCE 0.024736
Epoch 15/20 | Batch 413/413 | BCE 0.008519

Epoch 15 complete | BCE=0.018254 | diagnostic_acc@0.5=0.9925 | predicted_attack=0.9239 | time=3.8s | checkpoint=Drive
Epoch 16/20 | Batch 100/413 | BCE 0.011368
Epoch 16/20 | Batch 200/413 | BCE 0.022072
Epoch 16/20 | Batch 300/413 | BCE 0.015271
Epoch 16/20 | Batch 400/413 | BCE 0.026746
Epoch 16/20 | Batch 413/413 | BCE 0.001215

Epoch 16 complete | BCE=0.015882 | diagnostic_acc@0.5=0.9935 | predicted_attack=0.9239 | time=4.7s | checkpoint=Drive
Epoch 17/20 | Batch 100/413 | BCE 0.024811
Epoch 17/20 | Batch 200/413 | BCE 0.001735
Epoch 17/20 | Batch 300/413 | BCE 0.012460
Epoch 17/20 | Batch 400/413 | BCE 0.014300
Epoch 17/20 | Batch 413/413 | BCE 0.003363

Epoch 17 complete | BCE=0.014985 | diagnostic_acc@0.5=0.9938 | predicted_attack=0.9239 | time=3.8s | checkpoint=Drive
Epoch 18/20 | Batch 100/413 | BCE 0.011143
Epoch 18/20 | Batch 200/413 | BCE 0.014632
Epoch 18/20 | Batch 300/413 | BCE 0.019883
Epoch 18/20 | Batch 400/413 | BCE 0.010386
Epoch 18/20 | Batch 413/413 | BCE 0.001338

Epoch 18 complete | BCE=0.014062 | diagnostic_acc@0.5=0.9945 | predicted_attack=0.9240 | time=3.8s | checkpoint=Drive
Epoch 19/20 | Batch 100/413 | BCE 0.029426
Epoch 19/20 | Batch 200/413 | BCE 0.013930
Epoch 19/20 | Batch 300/413 | BCE 0.015918
Epoch 19/20 | Batch 400/413 | BCE 0.025005
Epoch 19/20 | Batch 413/413 | BCE 0.037479

Epoch 19 complete | BCE=0.013771 | diagnostic_acc@0.5=0.9947 | predicted_attack=0.9240 | time=5.2s | checkpoint=Drive
Epoch 20/20 | Batch 100/413 | BCE 0.012708
Epoch 20/20 | Batch 200/413 | BCE 0.005712
Epoch 20/20 | Batch 300/413 | BCE 0.008137
Epoch 20/20 | Batch 400/413 | BCE 0.020064
Epoch 20/20 | Batch 413/413 | BCE 0.003612

Epoch 20 complete | BCE=0.012195 | diagnostic_acc@0.5=0.9951 | predicted_attack=0.9240 | time=4.1s | checkpoint=Drive

[6] Last 5 supervised epochs
------------------------------------------------------------------------------

,epoch,training_BCE_loss,diagnostic_accuracy_at_0p5,predicted_attack_fraction_at_0p5,predicted_benign_fraction_at_0p5,actual_attack_windows,actual_benign_windows,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
15,16,0.015882,0.993521,0.923904,0.076096,97571,8006,105577,413,0.862040,4.727904
16,17,0.014985,0.993768,0.923923,0.076077,97571,8006,105577,413,1.071893,3.774189
17,18,0.014062,0.994487,0.924018,0.075982,97571,8006,105577,413,0.782049,3.795107
18,19,0.013771,0.994667,0.924008,0.075992,97571,8006,105577,413,0.932454,5.211466
19,20,0.012195,0.995122,0.924046,0.075954,97571,8006,105577,413,1.229544,4.086804

[7] Final model numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
All parameters finite: True
Classifier outputs finite: True
Probability range valid: True

[8] Recovery Step A16 validation
------------------------------------------------------------------------------
Completed fine-tuning epochs   : 20 / 20
Training windows               : 105,577
Held-out DDoS used             : False
Imbalance method               : none
Threshold tuned                : False
Final training BCE             : 0.012195
Diagnostic accuracy @ 0.5      : 0.995122
Predicted attack fraction      : 0.924046
Predicted benign fraction      : 0.075954
Non-finite batches             : 0
All parameters finite          : True
Classifier outputs finite      : True
Final model backed up          : True
Latest checkpoint backed up    : True
Training history backed up     : True

==============================================================================
✅ RECOVERY STEP A16 PASSED — Fold-1 SSL-pretrained MOT-SSL-GRU completed 20 supervised fine-tuning epochs.
==============================================================================

# A17-R1 — Check validation data availability

In [ ]:
# ======================================================================
# RECOVERY STEP A17-R1
# VERIFY DEVELOPMENT-VALIDATION DATA AVAILABILITY
#
# No model inference.
# No threshold tuning.
# No test/zero-day access.
# ======================================================================

from pathlib import Path
import os
import json

import pandas as pd


print("=" * 78)
print("RECOVERY STEP A17-R1 — VALIDATION-DATA READINESS")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — DEFINE BACKUP ROOT
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


print("\n[1] Checking core Fold-1 artifacts")
print("-" * 78)


TEMPORAL_MANIFEST = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_PARAMETERS = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
    / "preprocessing_parameters.csv"
)


RETAINED_FEATURES = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
    / "retained_features.json"
)


FINETUNED_MODEL = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


core_paths = {

    "Temporal manifest":
        TEMPORAL_MANIFEST,

    "Preprocessing parameters":
        PREPROCESSING_PARAMETERS,

    "Retained features":
        RETAINED_FEATURES,

    "Fine-tuned model":
        FINETUNED_MODEL
}


for label, path in core_paths.items():

    print(
        f"{label:<30}:",
        path.exists()
    )


CORE_ARTIFACTS_VALID = all(
    path.exists()
    for path in core_paths.values()
)


if not CORE_ARTIFACTS_VALID:

    raise RuntimeError(
        "One or more required Fold-1 artifacts are missing."
    )


# ======================================================================
# 2 — LOAD TEMPORAL MANIFEST
# ======================================================================

print("\n[2] Loading temporal-window manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST
)


print(
    "Manifest records:",
    len(manifest)
)


print(
    "Columns:"
)

for column in manifest.columns:

    print(
        " -",
        column
    )


# ======================================================================
# 3 — IDENTIFY IMPORTANT COLUMNS ROBUSTLY
# ======================================================================

def choose_column(
    dataframe,
    candidates,
    purpose
):

    for candidate in candidates:

        if candidate in dataframe.columns:

            return candidate


    raise RuntimeError(
        f"Could not identify {purpose} column. "
        f"Available columns: "
        f"{list(dataframe.columns)}"
    )


PARTITION_COLUMN = choose_column(

    manifest,

    [
        "partition",
        "partition_name",
        "partition_type",
        "split"
    ],

    "partition"
)


PARQUET_COLUMN = choose_column(

    manifest,

    [
        "parquet_path",
        "source_parquet_path",
        "sorted_parquet_path",
        "file_path"
    ],

    "Parquet path"
)


WINDOW_COUNT_COLUMN = choose_column(

    manifest,

    [
        "window_count",
        "available_windows",
        "temporal_windows",
        "windows"
    ],

    "window-count"
)


print(
    "\nDetected partition column:",
    PARTITION_COLUMN
)

print(
    "Detected Parquet column:",
    PARQUET_COLUMN
)

print(
    "Detected window-count column:",
    WINDOW_COUNT_COLUMN
)


# ======================================================================
# 4 — SELECT ONLY DEVELOPMENT VALIDATION
# ======================================================================

print("\n[3] Selecting development-validation records")
print("-" * 78)


partition_values = (

    manifest[
        PARTITION_COLUMN
    ]

    .astype(str)
)


validation_mask = (

    partition_values
    .str.strip()
    .str.lower()
    ==
    "development_validation"
)


VALIDATION_MANIFEST = (

    manifest.loc[
        validation_mask
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


VALIDATION_RANGES = len(
    VALIDATION_MANIFEST
)


VALIDATION_WINDOWS = int(

    VALIDATION_MANIFEST[
        WINDOW_COUNT_COLUMN
    ].sum()
)


print(
    "Validation source ranges:",
    VALIDATION_RANGES
)

print(
    "Validation windows:",
    f"{VALIDATION_WINDOWS:,}"
)


print(
    "Expected source ranges:",
    21
)

print(
    "Expected validation windows:",
    "167,482"
)


# ======================================================================
# 5 — EXTRACT REQUIRED PARQUET FILENAMES
# ======================================================================

required_basenames = sorted({

    Path(
        str(path)
    ).name

    for path in VALIDATION_MANIFEST[
        PARQUET_COLUMN
    ]
})


print("\n[4] Required validation source files")
print("-" * 78)

print(
    "Unique Parquet files required:",
    len(required_basenames)
)


for name in required_basenames:

    print(
        " -",
        name
    )


# ======================================================================
# 6 — CHECK COMMON PARQUET LOCATIONS
# ======================================================================

print("\n[5] Searching known chronological-Parquet locations")
print("-" * 78)


CANDIDATE_ROOTS = [

    Path(
        "/content/ZeroDay_IoT_Research/"
        "dataset/chronological_parquet"
    ),

    BACKUP_ROOT
    / "dataset"
    / "chronological_parquet",

    BACKUP_ROOT
    / "chronological_parquet",

    BACKUP_ROOT
    / "dataset"
    / "sorted_parquet",

    BACKUP_ROOT
    / "processed_data"
    / "chronological_parquet"
]


for root in CANDIDATE_ROOTS:

    print(
        str(root),
        "->",
        root.exists()
    )


# ======================================================================
# 7 — BUILD FILE INDEX FROM KNOWN ROOTS
# ======================================================================

resolved = {}


for root in CANDIDATE_ROOTS:

    if not root.exists():
        continue


    for basename in required_basenames:

        candidate = (
            root
            /
            basename
        )


        if candidate.exists():

            resolved[
                basename
            ] = candidate


# ======================================================================
# 8 — FALLBACK LIMITED SEARCH UNDER BACKUP ROOT
# ======================================================================

missing_before_search = [

    basename

    for basename in required_basenames

    if basename not in resolved
]


if missing_before_search:

    print(
        "\nKnown locations did not contain all files."
    )

    print(
        "Running limited fallback search "
        "inside research backup..."
    )


    needed = set(
        missing_before_search
    )


    backup_depth = len(
        BACKUP_ROOT.parts
    )


    for directory, subdirs, files in os.walk(
        BACKUP_ROOT
    ):

        directory_path = Path(
            directory
        )


        depth = (
            len(
                directory_path.parts
            )
            -
            backup_depth
        )


        # Do not recursively scan arbitrarily deep Drive trees.
        if depth >= 5:

            subdirs[:] = []


        file_set = set(
            files
        )


        matches = (
            needed
            &
            file_set
        )


        for basename in matches:

            resolved[
                basename
            ] = (
                directory_path
                /
                basename
            )


        needed -= matches


        if not needed:

            break


# ======================================================================
# 9 — REPORT RESOLUTION STATUS
# ======================================================================

print("\n[6] Validation source resolution")
print("-" * 78)


missing_files = [

    basename

    for basename in required_basenames

    if basename not in resolved
]


print(
    "Required source files:",
    len(required_basenames)
)

print(
    "Resolved source files:",
    len(resolved)
)

print(
    "Missing source files:",
    len(missing_files)
)


if missing_files:

    print(
        "\nMissing files:"
    )

    for basename in missing_files:

        print(
            " -",
            basename
        )


else:

    print(
        "\nAll development-validation source "
        "Parquet files are accessible."
    )


# ======================================================================
# 10 — VALIDATE FILE SIZES ARE NON-ZERO
# ======================================================================

NONEMPTY_FILES = True


for path in resolved.values():

    if (
        not path.exists()
        or
        path.stat().st_size <= 0
    ):

        NONEMPTY_FILES = False

        break


print(
    "All resolved files non-empty:",
    NONEMPTY_FILES
)


# ======================================================================
# 11 — SAVE READINESS AUDIT
# ======================================================================

AUDIT_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "validation_inference"
    / "fold_01_DDoS"
)


AUDIT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


AUDIT_PATH = (
    AUDIT_DIR
    / "A17_validation_data_readiness.json"
)


audit = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "validation_only":
        True,

    "validation_source_ranges":
        int(
            VALIDATION_RANGES
        ),

    "validation_windows":
        int(
            VALIDATION_WINDOWS
        ),

    "required_parquet_files":
        len(
            required_basenames
        ),

    "resolved_parquet_files":
        len(
            resolved
        ),

    "missing_parquet_files":
        missing_files,

    "core_artifacts_valid":
        bool(
            CORE_ARTIFACTS_VALID
        ),

    "all_resolved_files_nonempty":
        bool(
            NONEMPTY_FILES
        ),

    "test_data_read":
        False,

    "zero_day_data_read":
        False
}


with open(
    AUDIT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        audit,
        file,
        indent=4
    )


# ======================================================================
# 12 — FINAL READINESS CHECK
# ======================================================================

A17_R1_VALID = bool(

    CORE_ARTIFACTS_VALID

    and

    VALIDATION_RANGES
    ==
    21

    and

    VALIDATION_WINDOWS
    ==
    167_482

    and

    len(
        required_basenames
    )
    ==
    21

    and

    len(
        resolved
    )
    ==
    21

    and

    len(
        missing_files
    )
    ==
    0

    and

    NONEMPTY_FILES
)


STEP_17_VALIDATION_DATA_READY = (
    A17_R1_VALID
)


print("\n[7] Recovery Step A17-R1 validation")
print("-" * 78)

print(
    "Core Fold-1 artifacts          :",
    CORE_ARTIFACTS_VALID
)

print(
    "Validation source ranges       :",
    VALIDATION_RANGES,
    "/ 21"
)

print(
    "Validation windows             :",
    f"{VALIDATION_WINDOWS:,}",
    "/ 167,482"
)

print(
    "Required validation Parquets   :",
    len(required_basenames),
    "/ 21"
)

print(
    "Resolved validation Parquets   :",
    len(resolved),
    "/ 21"
)

print(
    "Missing validation Parquets    :",
    len(missing_files)
)

print(
    "All resolved files non-empty   :",
    NONEMPTY_FILES
)

print(
    "Test data accessed             :",
    False
)

print(
    "Zero-day data accessed         :",
    False
)

print(
    "Readiness audit saved          :",
    AUDIT_PATH.exists()
)


print("\n" + "=" * 78)

if A17_R1_VALID:

    print(
        "✅ RECOVERY STEP A17-R1 PASSED — "
        "Fold-1 development-validation data "
        "is ready for leakage-safe threshold selection."
    )

else:

    print(
        "❌ RECOVERY STEP A17-R1 FAILED — "
        "Do not perform threshold tuning yet."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A17-R1 — VALIDATION-DATA READINESS
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Checking core Fold-1 artifacts
------------------------------------------------------------------------------
Temporal manifest             : True
Preprocessing parameters      : True
Retained features             : True
Fine-tuned model              : True

[2] Loading temporal-window manifest
------------------------------------------------------------------------------
Manifest records: 75
Columns:
 - fold_id
 - held_out_family
 - partition
 - source_attack_class
 - research_family
 - binary_target
 - parquet_path
 - partition_start_row
 - partition_end_row_exclusive
 - partition_row_count
 - window_size
 - stride
 - window_count
 - first_window_start
 - first_window_end_exclusive
 - last_window_start
 - last_window_end_exclusive
 - unused_tail_rows
 - window_bounds_valid

Detected partition column: partition
Detected Parquet column: parquet_path
Detected window-count column: window_count

[3] Selecting development-validation records
------------------------------------------------------------------------------
Validation source ranges: 21
Validation windows: 167,482
Expected source ranges: 21
Expected validation windows: 167,482

[4] Required validation source files
------------------------------------------------------------------------------
Unique Parquet files required: 21
 - Backdoor_Malware.parquet
 - Benign_Final.parquet
 - BrowserHijacking.parquet
 - CommandInjection.parquet
 - DNS_Spoofing.parquet
 - DictionaryBruteForce.parquet
 - DoS-HTTP_Flood.parquet
 - DoS-SYN_Flood.parquet
 - DoS-TCP_Flood.parquet
 - DoS-UDP_Flood.parquet
 - MITM-ArpSpoofing.parquet
 - Mirai-greeth_flood.parquet
 - Mirai-greip_flood.parquet
 - Mirai-udpplain.parquet
 - Recon-HostDiscovery.parquet
 - Recon-OSScan.parquet
 - Recon-PingSweep.parquet
 - Recon-PortScan.parquet
 - SqlInjection.parquet
 - VulnerabilityScan.parquet
 - XSS.parquet

[5] Searching known chronological-Parquet locations
------------------------------------------------------------------------------
/content/ZeroDay_IoT_Research/dataset/chronological_parquet -> False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/dataset/chronological_parquet -> False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/chronological_parquet -> True
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/dataset/sorted_parquet -> False
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/chronological_parquet -> False

[6] Validation source resolution
------------------------------------------------------------------------------
Required source files: 21
Resolved source files: 21
Missing source files: 0

All development-validation source Parquet files are accessible.
All resolved files non-empty: True

[7] Recovery Step A17-R1 validation
------------------------------------------------------------------------------
Core Fold-1 artifacts          : True
Validation source ranges       : 21 / 21
Validation windows             : 167,482 / 167,482
Required validation Parquets   : 21 / 21
Resolved validation Parquets   : 21 / 21
Missing validation Parquets    : 0
All resolved files non-empty   : True
Test data accessed             : False
Zero-day data accessed         : False
Readiness audit saved          : True

==============================================================================
✅ RECOVERY STEP A17-R1 PASSED — Fold-1 development-validation data is ready for leakage-safe threshold selection.
==============================================================================

# A17 — Validation inference and threshold selection

In [ ]:
# ======================================================================
# RECOVERY STEP A17
# DEVELOPMENT-VALIDATION INFERENCE + THRESHOLD SELECTION
#
# Fold 1: DDoS held out
#
# Threshold rule:
#   Maximize F1 on development_validation ONLY.
#
# NO known-test access.
# NO benign-test access.
# NO zero-day DDoS access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    accuracy_score
)


print("=" * 78)
print("RECOVERY STEP A17 — VALIDATION INFERENCE + THRESHOLD SELECTION")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_16_FINETUNING_VALID",
    "STEP_17_VALIDATION_DATA_READY",
    "MOTSSLGRU",
    "DEVICE"
]


missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:

    raise RuntimeError(
        "A14 model architecture is not valid."
    )


if not STEP_16_FINETUNING_VALID:

    raise RuntimeError(
        "A16 fine-tuning did not pass."
    )


if not STEP_17_VALIDATION_DATA_READY:

    raise RuntimeError(
        "A17-R1 validation data is not ready."
    )


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A16 fine-tuned model valid:",
    STEP_16_FINETUNING_VALID
)

print(
    "A17-R1 validation data ready:",
    STEP_17_VALIDATION_DATA_READY
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — DEFINE PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


FINETUNED_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


for path in [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    FINETUNED_MODEL_PATH
]:

    if not path.exists():

        raise RuntimeError(
            f"Required path missing:\n{path}"
        )


# ======================================================================
# 3 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[2] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        f"Expected 75 retained features, "
        f"found {len(RETAINED_FEATURES)}."
    )


parameter_lookup = (
    parameters
    .set_index("feature")
    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    len(RETAINED_FEATURES) == 75

    and

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Clipping applied:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing is invalid."
    )


# ======================================================================
# 4 — LOAD VALIDATION WINDOW MANIFEST
# ======================================================================

print("\n[3] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_validation"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


actual_manifest_windows = int(
    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDoS_VAL_WINDOWS = int(

    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation source ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{actual_manifest_windows:,}"
)

print(
    "DDoS validation windows:",
    DDoS_VAL_WINDOWS
)


if len(VAL_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if actual_manifest_windows != EXPECTED_WINDOWS:

    raise RuntimeError(
        "Validation window count mismatch."
    )


if DDoS_VAL_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 5 — LOAD FINAL FINE-TUNED MODEL FROM DRIVE
# ======================================================================

print("\n[4] Loading final fine-tuned model")
print("-" * 78)


model_package = torch.load(
    FINETUNED_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


THRESHOLD_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


THRESHOLD_MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


THRESHOLD_MODEL.eval()


MODEL_PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in THRESHOLD_MODEL.parameters()
)


print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Existing threshold selected:",
    model_package[
        "threshold_selected"
    ]
)

print(
    "Model parameters finite:",
    MODEL_PARAMETERS_FINITE
)


if not MODEL_PARAMETERS_FINITE:

    raise RuntimeError(
        "Fine-tuned model contains non-finite parameters."
    )


# ======================================================================
# 6 — PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(
    table
):

    X = (

        table
        .to_pandas()
        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        row_indices, feature_indices = (
            np.where(
                bad_mask
            )
        )


        X[
            row_indices,
            feature_indices
        ] = (
            IMPUTE_VALUES[
                feature_indices
            ]
        )


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite values after frozen preprocessing."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite float32 values after preprocessing."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 7 — MODEL INFERENCE HELPER
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(
    windows
):

    probabilities = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,

            len(windows)
        )


        X = torch.from_numpy(
            windows[
                start:stop
            ]
        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                THRESHOLD_MODEL
                .forward_classifier(
                    X
                )
            )


            probs = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                probs
            ).all()
        ):

            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        probabilities.append(

            probs
            .detach()
            .cpu()
            .numpy()
            .astype(
                np.float64
            )
        )


    return np.concatenate(
        probabilities
    )


# ======================================================================
# 8 — STREAM VALIDATION DATA
# ======================================================================

print("\n[5] Running validation-only inference")
print("-" * 78)


prediction_parts = []

TOTAL_WINDOWS = 0
TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start_time = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = row[
        "source_attack_class"
    ]


    family = row[
        "research_family"
    ]


    target = int(
        row[
            "binary_target"
        ]
    )


    partition_start = int(
        row[
            "partition_start_row"
        ]
    )


    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    expected_source_windows = int(
        row[
            "window_count"
        ]
    )


    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )


    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():

        raise RuntimeError(
            f"Missing source Parquet: "
            f"{parquet_name}"
        )


    if family == "DDoS":

        raise RuntimeError(
            "DDoS source reached validation inference."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending_rows = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probabilities = []

    source_raw_nonfinite = 0

    absolute_row = 0


    # --------------------------------------------------------------
    # Read only row groups overlapping the validation range.
    # --------------------------------------------------------------

    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(

            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row

        group_end = (
            group_start
            +
            row_group_rows
        )


        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(

            row_group_index,

            columns=
                RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(

            local_start,

            local_end
            -
            local_start
        )


        Z, raw_nonfinite = (
            frozen_preprocess(
                table
            )
        )


        source_raw_nonfinite += (
            raw_nonfinite
        )


        # ----------------------------------------------------------
        # Add rows left over from the previous row group.
        # ----------------------------------------------------------

        if len(
            pending_rows
        ) > 0:

            Z = np.concatenate(
                [
                    pending_rows,
                    Z
                ],
                axis=0
            )


        # ----------------------------------------------------------
        # T = 8, stride = 8.
        # Create only complete windows.
        # ----------------------------------------------------------

        complete_window_count = (
            len(Z)
            //
            8
        )


        complete_row_count = (
            complete_window_count
            *
            8
        )


        if complete_window_count > 0:

            windows = (

                Z[
                    :complete_row_count
                ]

                .reshape(
                    complete_window_count,
                    8,
                    75
                )
            )


            probs = predict_windows(
                windows
            )


            source_probabilities.append(
                probs
            )


        pending_rows = (

            Z[
                complete_row_count:
            ]

            .copy()
        )


    # --------------------------------------------------------------
    # Source-level validation
    # --------------------------------------------------------------

    if source_probabilities:

        source_probabilities = (
            np.concatenate(
                source_probabilities
            )
        )

    else:

        source_probabilities = np.empty(
            0,
            dtype=np.float64
        )


    source_window_count = int(
        len(
            source_probabilities
        )
    )


    source_tail = int(
        len(
            pending_rows
        )
    )


    source_valid = bool(

        source_window_count
        ==
        expected_source_windows

        and

        source_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()

        and

        (
            (
                source_probabilities
                >=
                0.0
            )
            &
            (
                source_probabilities
                <=
                1.0
            )
        ).all()
    )


    SOURCE_CHECKS_VALID &= (
        source_valid
    )


    if not source_valid:

        raise RuntimeError(
            f"Validation construction failed "
            f"for {source_class}."
        )


    window_ordinals = np.arange(
        source_window_count,
        dtype=np.int64
    )


    window_start_rows = (

        partition_start

        +

        window_ordinals
        *
        8
    )


    source_predictions = pd.DataFrame({

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            target,

        "window_ordinal":
            window_ordinals,

        "source_row_start":
            window_start_rows,

        "source_row_end_exclusive":
            window_start_rows
            +
            8,

        "malicious_probability":
            source_probabilities
    })


    prediction_parts.append(
        source_predictions
    )


    TOTAL_WINDOWS += (
        source_window_count
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={source_window_count:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 9 — COMBINE VALIDATION PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (

    VALIDATION_PREDICTIONS[
        "binary_target"
    ]

    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (

    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


print("\n[6] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(VALIDATION_PREDICTIONS):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDoS_VAL_WINDOWS
)

print(
    "Raw non-finite scalar values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{(time.time() - inference_start_time):.2f} seconds"
)


# ======================================================================
# 10 — STRICT VALIDATION-ONLY COUNT CHECK
# ======================================================================

COUNTS_VALID = bool(

    len(
        VALIDATION_PREDICTIONS
    )
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDoS_VAL_WINDOWS
    ==
    0
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Validation label/window counts do not "
        "match the frozen temporal manifest."
    )


# ======================================================================
# 11 — THRESHOLD SEARCH
#
# IMPLEMENTATION CHOICE:
# Maximize F1 on development validation only.
#
# Tie-break rule:
# choose the HIGHEST threshold among exact max-F1 ties.
# ======================================================================

print("\n[7] Selecting threshold using validation F1 only")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


# Last precision/recall entries do not correspond
# to a threshold.
threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (

    2.0
    *
    threshold_precision
    *
    threshold_recall

    /

    np.maximum(
        threshold_precision
        +
        threshold_recall,
        1e-15
    )
)


MAX_VALIDATION_F1 = float(
    np.max(
        threshold_f1
    )
)


# Exact/tiny numerical ties.
candidate_indices = np.flatnonzero(

    np.isclose(
        threshold_f1,
        MAX_VALIDATION_F1,
        rtol=0.0,
        atol=1e-12
    )
)


# Higher threshold is the deterministic tie-break.
BEST_INDEX = int(

    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_VALIDATION_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Tie-break:",
    "highest threshold"
)


# ======================================================================
# 12 — VALIDATION METRICS AT SELECTED THRESHOLD
# ======================================================================

y_pred_selected = (

    y_probability

    >=

    SELECTED_THRESHOLD

).astype(
    np.int64
)


tn, fp, fn, tp = (
    confusion_matrix(
        y_true,
        y_pred_selected,
        labels=[
            0,
            1
        ]
    )
    .ravel()
)


SELECTED_PRECISION = float(

    precision_score(
        y_true,
        y_pred_selected,
        zero_division=0
    )
)


SELECTED_RECALL = float(

    recall_score(
        y_true,
        y_pred_selected,
        zero_division=0
    )
)


SELECTED_F1 = float(

    f1_score(
        y_true,
        y_pred_selected,
        zero_division=0
    )
)


SELECTED_ACCURACY = float(

    accuracy_score(
        y_true,
        y_pred_selected
    )
)


SELECTED_FPR = float(

    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_PR_AUC = float(

    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(

    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[8] Selected-threshold validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "TP:",
    int(tp)
)

print(
    "TN:",
    int(tn)
)

print(
    "FP:",
    int(fp)
)

print(
    "FN:",
    int(fn)
)

print(
    "Precision:",
    f"{SELECTED_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{SELECTED_RECALL:.10f}"
)

print(
    "F1:",
    f"{SELECTED_F1:.10f}"
)

print(
    "FPR:",
    f"{SELECTED_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{SELECTED_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 13 — DIAGNOSTIC COMPARISON WITH THRESHOLD 0.5
#
# This does NOT alter threshold selection.
# ======================================================================

y_pred_05 = (

    y_probability

    >=

    0.5

).astype(
    np.int64
)


tn05, fp05, fn05, tp05 = (
    confusion_matrix(
        y_true,
        y_pred_05,
        labels=[
            0,
            1
        ]
    )
    .ravel()
)


F1_AT_05 = float(

    f1_score(
        y_true,
        y_pred_05,
        zero_division=0
    )
)


FPR_AT_05 = float(

    fp05
    /
    max(
        fp05 + tn05,
        1
    )
)


RECALL_AT_05 = float(

    recall_score(
        y_true,
        y_pred_05,
        zero_division=0
    )
)


print("\n[9] Diagnostic threshold-0.5 comparison")
print("-" * 78)

print(
    "F1 @ 0.5:",
    f"{F1_AT_05:.10f}"
)

print(
    "Recall @ 0.5:",
    f"{RECALL_AT_05:.10f}"
)

print(
    "FPR @ 0.5:",
    f"{FPR_AT_05:.10f}"
)


# ======================================================================
# 14 — BUILD THRESHOLD CURVE TABLE
# ======================================================================

THRESHOLD_CURVE = pd.DataFrame({

    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1
})


# ======================================================================
# 15 — SAVE PREDICTIONS + THRESHOLD ARTIFACTS LOCALLY
# ======================================================================

print("\n[10] Saving threshold-selection artifacts")
print("-" * 78)


LOCAL_OUTPUT_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "predictions/threshold_selection/"
    "fold_01_DDoS/"
    "seed_13/"
    "MOT_SSL_GRU"
)


DRIVE_OUTPUT_DIR = (
    BACKUP_ROOT
    / "predictions"
    / "threshold_selection"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
)


LOCAL_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    LOCAL_OUTPUT_DIR
    / "development_validation_predictions.csv"
)


CURVE_PATH = (
    LOCAL_OUTPUT_DIR
    / "validation_threshold_search.csv"
)


THRESHOLD_JSON_PATH = (
    LOCAL_OUTPUT_DIR
    / "selected_threshold.json"
)


POLICY_PATH = (
    LOCAL_OUTPUT_DIR
    / "threshold_selection_policy.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = y_pred_selected


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


THRESHOLD_CURVE.to_csv(
    CURVE_PATH,
    index=False
)


THRESHOLD_RECORD = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "model":
        "MOT-SSL-GRU",

    "seed":
        13,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(
                y_true
            )
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selection_rule":
        "maximize_validation_F1",

    "tie_break":
        "highest_threshold",

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        SELECTED_PRECISION,

    "validation_recall":
        SELECTED_RECALL,

    "validation_F1":
        SELECTED_F1,

    "validation_FPR":
        SELECTED_FPR,

    "validation_accuracy":
        SELECTED_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    THRESHOLD_JSON_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        THRESHOLD_RECORD,
        file,
        indent=4
    )


THRESHOLD_POLICY = {

    "selection_partition":
        "development_validation_only",

    "selection_metric":
        "F1",

    "selection_rule":
        "maximize F1",

    "tie_break":
        "highest threshold among numerical max-F1 ties",

    "selection_rule_status":
        (
            "documented implementation choice; "
            "methodology requires leakage-safe "
            "threshold selection but does not specify "
            "an exact optimization criterion"
        ),

    "test_partitions_used":
        False,

    "zero_day_family_used":
        False,

    "threshold_frozen_after_A17":
        True,

    "note":
        (
            "This frozen threshold must be reused "
            "unchanged for Fold-1 known-test and "
            "zero-day evaluation."
        )
}


with open(
    POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        THRESHOLD_POLICY,
        file,
        indent=4
    )


# ======================================================================
# 16 — BACK UP ALL A17 ARTIFACTS TO DRIVE
# ======================================================================

for source_path in [
    PREDICTIONS_PATH,
    CURVE_PATH,
    THRESHOLD_JSON_PATH,
    POLICY_PATH
]:

    shutil.copy2(

        source_path,

        DRIVE_OUTPUT_DIR
        /
        source_path.name
    )


ARTIFACTS_BACKED_UP = all(

    (
        DRIVE_OUTPUT_DIR
        /
        source_path.name
    ).exists()

    for source_path in [
        PREDICTIONS_PATH,
        CURVE_PATH,
        THRESHOLD_JSON_PATH,
        POLICY_PATH
    ]
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

THRESHOLD_VALID = bool(

    np.isfinite(
        SELECTED_THRESHOLD
    )

    and

    0.0
    <=
    SELECTED_THRESHOLD
    <=
    1.0
)


METRICS_FINITE = all(

    np.isfinite(value)

    for value in [
        SELECTED_PRECISION,
        SELECTED_RECALL,
        SELECTED_F1,
        SELECTED_FPR,
        SELECTED_ACCURACY,
        VALIDATION_PR_AUC,
        VALIDATION_ROC_AUC
    ]
)


A17_VALID = bool(

    COUNTS_VALID

    and

    SOURCE_CHECKS_VALID

    and

    PREPROCESSING_VALID

    and

    MODEL_PARAMETERS_FINITE

    and

    THRESHOLD_VALID

    and

    METRICS_FINITE

    and

    DDoS_VAL_WINDOWS
    ==
    0

    and

    ARTIFACTS_BACKED_UP
)


STEP_17_THRESHOLD_SELECTION_VALID = (
    A17_VALID
)


FROZEN_FOLD1_THRESHOLD = (
    SELECTED_THRESHOLD
)


print("\n[11] Recovery Step A17 validation")
print("-" * 78)

print(
    "Validation windows             :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDoS_VAL_WINDOWS
)

print(
    "Selected threshold             :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Selection criterion            :",
    "maximize validation F1"
)

print(
    "Validation F1                  :",
    f"{SELECTED_F1:.10f}"
)

print(
    "Validation recall              :",
    f"{SELECTED_RECALL:.10f}"
)

print(
    "Validation FPR                 :",
    f"{SELECTED_FPR:.10f}"
)

print(
    "Known-test accessed            :",
    False
)

print(
    "Benign-test accessed           :",
    False
)

print(
    "Zero-day DDoS accessed         :",
    False
)

print(
    "Threshold now frozen           :",
    True
)

print(
    "Artifacts backed up            :",
    ARTIFACTS_BACKED_UP
)


print("\n" + "=" * 78)

if A17_VALID:

    print(
        "✅ RECOVERY STEP A17 PASSED — "
        "Fold-1 threshold was selected using "
        "development validation only and is now frozen."
    )

else:

    print(
        "❌ RECOVERY STEP A17 FAILED — "
        "Do not evaluate test or zero-day data."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A17 — VALIDATION INFERENCE + THRESHOLD SELECTION
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A16 fine-tuned model valid: True
A17-R1 validation data ready: True
Device: cuda

[2] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Clipping applied: False

[3] Loading development-validation manifest
------------------------------------------------------------------------------
Validation source ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[4] Loading final fine-tuned model
------------------------------------------------------------------------------
Fine-tuning epochs: 20
Imbalance method: none
Existing threshold selected: False
Model parameters finite: True

[5] Running validation-only inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[6] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite scalar values imputed: 1,516
All source checks valid: True
Probability min: 0.0000000000
Probability max: 1.0000000000
Inference runtime: 53.96 seconds

[7] Selecting threshold using validation F1 only
------------------------------------------------------------------------------
Threshold candidates: 9,813
Maximum validation F1: 0.9972670927
Selected threshold: 0.0147513831
Max-F1 tie count: 1
Tie-break: highest threshold

[8] Selected-threshold validation metrics
------------------------------------------------------------------------------
Threshold: 0.0147513831
TP: 165487
TN: 1088
FP: 627
FN: 280
Precision: 0.9962254837
Recall: 0.9983108821
F1: 0.9972670927
FPR: 0.3655976676
Accuracy: 0.9945844927
PR-AUC: 0.9999505003
ROC-AUC: 0.9959748044

[9] Diagnostic threshold-0.5 comparison
------------------------------------------------------------------------------
F1 @ 0.5: 0.9967792616
Recall @ 0.5: 0.9951136233
FPR @ 0.5: 0.1492711370

[10] Saving threshold-selection artifacts
------------------------------------------------------------------------------

[11] Recovery Step A17 validation
------------------------------------------------------------------------------
Validation windows             : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
Selected threshold             : 0.0147513831
Selection criterion            : maximize validation F1
Validation F1                  : 0.9972670927
Validation recall              : 0.9983108821
Validation FPR                 : 0.3655976676
Known-test accessed            : False
Benign-test accessed           : False
Zero-day DDoS accessed         : False
Threshold now frozen           : True
Artifacts backed up            : True

==============================================================================
✅ RECOVERY STEP A17 PASSED — Fold-1 threshold was selected using development validation only and is now frozen.
==============================================================================

# A17 — Validation inference and threshold selection

In [ ]:
# ======================================================================
# RECOVERY STEP A17
# DEVELOPMENT-VALIDATION INFERENCE + THRESHOLD SELECTION
#
# Fold 1: DDoS held out
#
# Threshold rule:
#   Maximize F1 on development_validation ONLY.
#
# NO known-test access.
# NO benign-test access.
# NO zero-day DDoS access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    roc_auc_score,
    average_precision_score,
    accuracy_score
)


print("=" * 78)
print("RECOVERY STEP A17 — VALIDATION INFERENCE + THRESHOLD SELECTION")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_16_FINETUNING_VALID",
    "STEP_17_VALIDATION_DATA_READY",
    "MOTSSLGRU",
    "DEVICE"
]


missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:

    raise RuntimeError(
        "A14 model architecture is not valid."
    )


if not STEP_16_FINETUNING_VALID:

    raise RuntimeError(
        "A16 fine-tuning did not pass."
    )


if not STEP_17_VALIDATION_DATA_READY:

    raise RuntimeError(
        "A17-R1 validation data is not ready."
    )


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A16 fine-tuned model valid:",
    STEP_16_FINETUNING_VALID
)

print(
    "A17-R1 validation data ready:",
    STEP_17_VALIDATION_DATA_READY
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — DEFINE PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


FINETUNED_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


for path in [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    FINETUNED_MODEL_PATH
]:

    if not path.exists():

        raise RuntimeError(
            f"Required path missing:\n{path}"
        )


# ======================================================================
# 3 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[2] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        f"Expected 75 retained features, "
        f"found {len(RETAINED_FEATURES)}."
    )


parameter_lookup = (
    parameters
    .set_index("feature")
    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    len(RETAINED_FEATURES) == 75

    and

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Clipping applied:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing is invalid."
    )


# ======================================================================
# 4 — LOAD VALIDATION WINDOW MANIFEST
# ======================================================================

print("\n[3] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_validation"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


actual_manifest_windows = int(
    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDoS_VAL_WINDOWS = int(

    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation source ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{actual_manifest_windows:,}"
)

print(
    "DDoS validation windows:",
    DDoS_VAL_WINDOWS
)


if len(VAL_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if actual_manifest_windows != EXPECTED_WINDOWS:

    raise RuntimeError(
        "Validation window count mismatch."
    )


if DDoS_VAL_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 5 — LOAD FINAL FINE-TUNED MODEL FROM DRIVE
# ======================================================================

print("\n[4] Loading final fine-tuned model")
print("-" * 78)


model_package = torch.load(
    FINETUNED_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


THRESHOLD_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


THRESHOLD_MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


THRESHOLD_MODEL.eval()


MODEL_PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in THRESHOLD_MODEL.parameters()
)


print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Existing threshold selected:",
    model_package[
        "threshold_selected"
    ]
)

print(
    "Model parameters finite:",
    MODEL_PARAMETERS_FINITE
)


if not MODEL_PARAMETERS_FINITE:

    raise RuntimeError(
        "Fine-tuned model contains non-finite parameters."
    )


# ======================================================================
# 6 — PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(
    table
):

    X = (

        table
        .to_pandas()
        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        row_indices, feature_indices = (
            np.where(
                bad_mask
            )
        )


        X[
            row_indices,
            feature_indices
        ] = (
            IMPUTE_VALUES[
                feature_indices
            ]
        )


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite values after frozen preprocessing."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite float32 values after preprocessing."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 7 — MODEL INFERENCE HELPER
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(
    windows
):

    probabilities = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,

            len(windows)
        )


        X = torch.from_numpy(
            windows[
                start:stop
            ]
        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                THRESHOLD_MODEL
                .forward_classifier(
                    X
                )
            )


            probs = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                probs
            ).all()
        ):

            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        probabilities.append(

            probs
            .detach()
            .cpu()
            .numpy()
            .astype(
                np.float64
            )
        )


    return np.concatenate(
        probabilities
    )


# ======================================================================
# 8 — STREAM VALIDATION DATA
# ======================================================================

print("\n[5] Running validation-only inference")
print("-" * 78)


prediction_parts = []

TOTAL_WINDOWS = 0
TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start_time = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = row[
        "source_attack_class"
    ]


    family = row[
        "research_family"
    ]


    target = int(
        row[
            "binary_target"
        ]
    )


    partition_start = int(
        row[
            "partition_start_row"
        ]
    )


    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    expected_source_windows = int(
        row[
            "window_count"
        ]
    )


    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )


    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():

        raise RuntimeError(
            f"Missing source Parquet: "
            f"{parquet_name}"
        )


    if family == "DDoS":

        raise RuntimeError(
            "DDoS source reached validation inference."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending_rows = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probabilities = []

    source_raw_nonfinite = 0

    absolute_row = 0


    # --------------------------------------------------------------
    # Read only row groups overlapping the validation range.
    # --------------------------------------------------------------

    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(

            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row

        group_end = (
            group_start
            +
            row_group_rows
        )


        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(

            row_group_index,

            columns=
                RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(

            local_start,

            local_end
            -
            local_start
        )


        Z, raw_nonfinite = (
            frozen_preprocess(
                table
            )
        )


        source_raw_nonfinite += (
            raw_nonfinite
        )


        # ----------------------------------------------------------
        # Add rows left over from the previous row group.
        # ----------------------------------------------------------

        if len(
            pending_rows
        ) > 0:

            Z = np.concatenate(
                [
                    pending_rows,
                    Z
                ],
                axis=0
            )


        # ----------------------------------------------------------
        # T = 8, stride = 8.
        # Create only complete windows.
        # ----------------------------------------------------------

        complete_window_count = (
            len(Z)
            //
            8
        )


        complete_row_count = (
            complete_window_count
            *
            8
        )


        if complete_window_count > 0:

            windows = (

                Z[
                    :complete_row_count
                ]

                .reshape(
                    complete_window_count,
                    8,
                    75
                )
            )


            probs = predict_windows(
                windows
            )


            source_probabilities.append(
                probs
            )


        pending_rows = (

            Z[
                complete_row_count:
            ]

            .copy()
        )


    # --------------------------------------------------------------
    # Source-level validation
    # --------------------------------------------------------------

    if source_probabilities:

        source_probabilities = (
            np.concatenate(
                source_probabilities
            )
        )

    else:

        source_probabilities = np.empty(
            0,
            dtype=np.float64
        )


    source_window_count = int(
        len(
            source_probabilities
        )
    )


    source_tail = int(
        len(
            pending_rows
        )
    )


    source_valid = bool(

        source_window_count
        ==
        expected_source_windows

        and

        source_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()

        and

        (
            (
                source_probabilities
                >=
                0.0
            )
            &
            (
                source_probabilities
                <=
                1.0
            )
        ).all()
    )


    SOURCE_CHECKS_VALID &= (
        source_valid
    )


    if not source_valid:

        raise RuntimeError(
            f"Validation construction failed "
            f"for {source_class}."
        )


    window_ordinals = np.arange(
        source_window_count,
        dtype=np.int64
    )


    window_start_rows = (

        partition_start

        +

        window_ordinals
        *
        8
    )


    source_predictions = pd.DataFrame({

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            target,

        "window_ordinal":
            window_ordinals,

        "source_row_start":
            window_start_rows,

        "source_row_end_exclusive":
            window_start_rows
            +
            8,

        "malicious_probability":
            source_probabilities
    })


    prediction_parts.append(
        source_predictions
    )


    TOTAL_WINDOWS += (
        source_window_count
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={source_window_count:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 9 — COMBINE VALIDATION PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (

    VALIDATION_PREDICTIONS[
        "binary_target"
    ]

    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (

    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


print("\n[6] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(VALIDATION_PREDICTIONS):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDoS_VAL_WINDOWS
)

print(
    "Raw non-finite scalar values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{(time.time() - inference_start_time):.2f} seconds"
)


# ======================================================================
# 10 — STRICT VALIDATION-ONLY COUNT CHECK
# ======================================================================

COUNTS_VALID = bool(

    len(
        VALIDATION_PREDICTIONS
    )
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDoS_VAL_WINDOWS
    ==
    0
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Validation label/window counts do not "
        "match the frozen temporal manifest."
    )


# ======================================================================
# 11 — THRESHOLD SEARCH
#
# IMPLEMENTATION CHOICE:
# Maximize F1 on development validation only.
#
# Tie-break rule:
# choose the HIGHEST threshold among exact max-F1 ties.
# ======================================================================

print("\n[7] Selecting threshold using validation F1 only")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


# Last precision/recall entries do not correspond
# to a threshold.
threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (

    2.0
    *
    threshold_precision
    *
    threshold_recall

    /

    np.maximum(
        threshold_precision
        +
        threshold_recall,
        1e-15
    )
)


MAX_VALIDATION_F1 = float(
    np.max(
        threshold_f1
    )
)


# Exact/tiny numerical ties.
candidate_indices = np.flatnonzero(

    np.isclose(
        threshold_f1,
        MAX_VALIDATION_F1,
        rtol=0.0,
        atol=1e-12
    )
)


# Higher threshold is the deterministic tie-break.
BEST_INDEX = int(

    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_VALIDATION_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Tie-break:",
    "highest threshold"
)


# ======================================================================
# 12 — VALIDATION METRICS AT SELECTED THRESHOLD
# ======================================================================

y_pred_selected = (

    y_probability

    >=

    SELECTED_THRESHOLD

).astype(
    np.int64
)


tn, fp, fn, tp = (
    confusion_matrix(
        y_true,
        y_pred_selected,
        labels=[
            0,
            1
        ]
    )
    .ravel()
)


SELECTED_PRECISION = float(

    precision_score(
        y_true,
        y_pred_selected,
        zero_division=0
    )
)


SELECTED_RECALL = float(

    recall_score(
        y_true,
        y_pred_selected,
        zero_division=0
    )
)


SELECTED_F1 = float(

    f1_score(
        y_true,
        y_pred_selected,
        zero_division=0
    )
)


SELECTED_ACCURACY = float(

    accuracy_score(
        y_true,
        y_pred_selected
    )
)


SELECTED_FPR = float(

    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_PR_AUC = float(

    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(

    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[8] Selected-threshold validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "TP:",
    int(tp)
)

print(
    "TN:",
    int(tn)
)

print(
    "FP:",
    int(fp)
)

print(
    "FN:",
    int(fn)
)

print(
    "Precision:",
    f"{SELECTED_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{SELECTED_RECALL:.10f}"
)

print(
    "F1:",
    f"{SELECTED_F1:.10f}"
)

print(
    "FPR:",
    f"{SELECTED_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{SELECTED_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 13 — DIAGNOSTIC COMPARISON WITH THRESHOLD 0.5
#
# This does NOT alter threshold selection.
# ======================================================================

y_pred_05 = (

    y_probability

    >=

    0.5

).astype(
    np.int64
)


tn05, fp05, fn05, tp05 = (
    confusion_matrix(
        y_true,
        y_pred_05,
        labels=[
            0,
            1
        ]
    )
    .ravel()
)


F1_AT_05 = float(

    f1_score(
        y_true,
        y_pred_05,
        zero_division=0
    )
)


FPR_AT_05 = float(

    fp05
    /
    max(
        fp05 + tn05,
        1
    )
)


RECALL_AT_05 = float(

    recall_score(
        y_true,
        y_pred_05,
        zero_division=0
    )
)


print("\n[9] Diagnostic threshold-0.5 comparison")
print("-" * 78)

print(
    "F1 @ 0.5:",
    f"{F1_AT_05:.10f}"
)

print(
    "Recall @ 0.5:",
    f"{RECALL_AT_05:.10f}"
)

print(
    "FPR @ 0.5:",
    f"{FPR_AT_05:.10f}"
)


# ======================================================================
# 14 — BUILD THRESHOLD CURVE TABLE
# ======================================================================

THRESHOLD_CURVE = pd.DataFrame({

    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1
})


# ======================================================================
# 15 — SAVE PREDICTIONS + THRESHOLD ARTIFACTS LOCALLY
# ======================================================================

print("\n[10] Saving threshold-selection artifacts")
print("-" * 78)


LOCAL_OUTPUT_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "predictions/threshold_selection/"
    "fold_01_DDoS/"
    "seed_13/"
    "MOT_SSL_GRU"
)


DRIVE_OUTPUT_DIR = (
    BACKUP_ROOT
    / "predictions"
    / "threshold_selection"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
)


LOCAL_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    LOCAL_OUTPUT_DIR
    / "development_validation_predictions.csv"
)


CURVE_PATH = (
    LOCAL_OUTPUT_DIR
    / "validation_threshold_search.csv"
)


THRESHOLD_JSON_PATH = (
    LOCAL_OUTPUT_DIR
    / "selected_threshold.json"
)


POLICY_PATH = (
    LOCAL_OUTPUT_DIR
    / "threshold_selection_policy.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = y_pred_selected


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


THRESHOLD_CURVE.to_csv(
    CURVE_PATH,
    index=False
)


THRESHOLD_RECORD = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "model":
        "MOT-SSL-GRU",

    "seed":
        13,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(
                y_true
            )
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selection_rule":
        "maximize_validation_F1",

    "tie_break":
        "highest_threshold",

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        SELECTED_PRECISION,

    "validation_recall":
        SELECTED_RECALL,

    "validation_F1":
        SELECTED_F1,

    "validation_FPR":
        SELECTED_FPR,

    "validation_accuracy":
        SELECTED_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    THRESHOLD_JSON_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        THRESHOLD_RECORD,
        file,
        indent=4
    )


THRESHOLD_POLICY = {

    "selection_partition":
        "development_validation_only",

    "selection_metric":
        "F1",

    "selection_rule":
        "maximize F1",

    "tie_break":
        "highest threshold among numerical max-F1 ties",

    "selection_rule_status":
        (
            "documented implementation choice; "
            "methodology requires leakage-safe "
            "threshold selection but does not specify "
            "an exact optimization criterion"
        ),

    "test_partitions_used":
        False,

    "zero_day_family_used":
        False,

    "threshold_frozen_after_A17":
        True,

    "note":
        (
            "This frozen threshold must be reused "
            "unchanged for Fold-1 known-test and "
            "zero-day evaluation."
        )
}


with open(
    POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        THRESHOLD_POLICY,
        file,
        indent=4
    )


# ======================================================================
# 16 — BACK UP ALL A17 ARTIFACTS TO DRIVE
# ======================================================================

for source_path in [
    PREDICTIONS_PATH,
    CURVE_PATH,
    THRESHOLD_JSON_PATH,
    POLICY_PATH
]:

    shutil.copy2(

        source_path,

        DRIVE_OUTPUT_DIR
        /
        source_path.name
    )


ARTIFACTS_BACKED_UP = all(

    (
        DRIVE_OUTPUT_DIR
        /
        source_path.name
    ).exists()

    for source_path in [
        PREDICTIONS_PATH,
        CURVE_PATH,
        THRESHOLD_JSON_PATH,
        POLICY_PATH
    ]
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

THRESHOLD_VALID = bool(

    np.isfinite(
        SELECTED_THRESHOLD
    )

    and

    0.0
    <=
    SELECTED_THRESHOLD
    <=
    1.0
)


METRICS_FINITE = all(

    np.isfinite(value)

    for value in [
        SELECTED_PRECISION,
        SELECTED_RECALL,
        SELECTED_F1,
        SELECTED_FPR,
        SELECTED_ACCURACY,
        VALIDATION_PR_AUC,
        VALIDATION_ROC_AUC
    ]
)


A17_VALID = bool(

    COUNTS_VALID

    and

    SOURCE_CHECKS_VALID

    and

    PREPROCESSING_VALID

    and

    MODEL_PARAMETERS_FINITE

    and

    THRESHOLD_VALID

    and

    METRICS_FINITE

    and

    DDoS_VAL_WINDOWS
    ==
    0

    and

    ARTIFACTS_BACKED_UP
)


STEP_17_THRESHOLD_SELECTION_VALID = (
    A17_VALID
)


FROZEN_FOLD1_THRESHOLD = (
    SELECTED_THRESHOLD
)


print("\n[11] Recovery Step A17 validation")
print("-" * 78)

print(
    "Validation windows             :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDoS_VAL_WINDOWS
)

print(
    "Selected threshold             :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Selection criterion            :",
    "maximize validation F1"
)

print(
    "Validation F1                  :",
    f"{SELECTED_F1:.10f}"
)

print(
    "Validation recall              :",
    f"{SELECTED_RECALL:.10f}"
)

print(
    "Validation FPR                 :",
    f"{SELECTED_FPR:.10f}"
)

print(
    "Known-test accessed            :",
    False
)

print(
    "Benign-test accessed           :",
    False
)

print(
    "Zero-day DDoS accessed         :",
    False
)

print(
    "Threshold now frozen           :",
    True
)

print(
    "Artifacts backed up            :",
    ARTIFACTS_BACKED_UP
)


print("\n" + "=" * 78)

if A17_VALID:

    print(
        "✅ RECOVERY STEP A17 PASSED — "
        "Fold-1 threshold was selected using "
        "development validation only and is now frozen."
    )

else:

    print(
        "❌ RECOVERY STEP A17 FAILED — "
        "Do not evaluate test or zero-day data."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A17 — VALIDATION INFERENCE + THRESHOLD SELECTION
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A16 fine-tuned model valid: True
A17-R1 validation data ready: True
Device: cuda

[2] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Clipping applied: False

[3] Loading development-validation manifest
------------------------------------------------------------------------------
Validation source ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[4] Loading final fine-tuned model
------------------------------------------------------------------------------
Fine-tuning epochs: 20
Imbalance method: none
Existing threshold selected: False
Model parameters finite: True

[5] Running validation-only inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[6] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite scalar values imputed: 1,516
All source checks valid: True
Probability min: 0.0000000000
Probability max: 1.0000000000
Inference runtime: 7.22 seconds

[7] Selecting threshold using validation F1 only
------------------------------------------------------------------------------
Threshold candidates: 9,813
Maximum validation F1: 0.9972670927
Selected threshold: 0.0147513831
Max-F1 tie count: 1
Tie-break: highest threshold

[8] Selected-threshold validation metrics
------------------------------------------------------------------------------
Threshold: 0.0147513831
TP: 165487
TN: 1088
FP: 627
FN: 280
Precision: 0.9962254837
Recall: 0.9983108821
F1: 0.9972670927
FPR: 0.3655976676
Accuracy: 0.9945844927
PR-AUC: 0.9999505003
ROC-AUC: 0.9959748044

[9] Diagnostic threshold-0.5 comparison
------------------------------------------------------------------------------
F1 @ 0.5: 0.9967792616
Recall @ 0.5: 0.9951136233
FPR @ 0.5: 0.1492711370

[10] Saving threshold-selection artifacts
------------------------------------------------------------------------------

[11] Recovery Step A17 validation
------------------------------------------------------------------------------
Validation windows             : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
Selected threshold             : 0.0147513831
Selection criterion            : maximize validation F1
Validation F1                  : 0.9972670927
Validation recall              : 0.9983108821
Validation FPR                 : 0.3655976676
Known-test accessed            : False
Benign-test accessed           : False
Zero-day DDoS accessed         : False
Threshold now frozen           : True
Artifacts backed up            : True

==============================================================================
✅ RECOVERY STEP A17 PASSED — Fold-1 threshold was selected using development validation only and is now frozen.
==============================================================================

# A18 — Final Fold-1 Known + Zero-Day Evaluation

In [ ]:
# ======================================================================
# RECOVERY STEP A18
# FINAL FOLD-1 KNOWN + ZERO-DAY EVALUATION
#
# Held-out family: DDoS
# Threshold is FROZEN from A17.
#
# NO fitting.
# NO tuning.
# NO threshold modification.
# NO preprocessing refit.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    accuracy_score,
    average_precision_score,
    roc_auc_score
)


print("=" * 78)
print("RECOVERY STEP A18 — FINAL FOLD-1 EVALUATION")
print("HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_16_FINETUNING_VALID",
    "STEP_17_THRESHOLD_SELECTION_VALID",
    "MOTSSLGRU",
    "DEVICE"
]


missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing runtime variables: "
        + ", ".join(missing_variables)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:

    raise RuntimeError(
        "A14 did not pass."
    )


if not STEP_16_FINETUNING_VALID:

    raise RuntimeError(
        "A16 did not pass."
    )


if not STEP_17_THRESHOLD_SELECTION_VALID:

    raise RuntimeError(
        "A17 did not pass."
    )


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A16 fine-tuning valid:",
    STEP_16_FINETUNING_VALID
)

print(
    "A17 threshold valid:",
    STEP_17_THRESHOLD_SELECTION_VALID
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


THRESHOLD_PATH = (
    BACKUP_ROOT
    / "predictions"
    / "threshold_selection"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
    / "selected_threshold.json"
)


required_paths = [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    MODEL_PATH,
    THRESHOLD_PATH
]


for path in required_paths:

    if not path.exists():

        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 3 — LOAD FROZEN THRESHOLD
# ======================================================================

print("\n[2] Loading frozen A17 threshold")
print("-" * 78)


with open(
    THRESHOLD_PATH,
    "r",
    encoding="utf-8"
) as file:

    threshold_record = json.load(
        file
    )


FROZEN_THRESHOLD = float(
    threshold_record[
        "selected_threshold"
    ]
)


if threshold_record.get(
    "partition_used"
) != "development_validation":

    raise RuntimeError(
        "Threshold was not selected from "
        "development validation."
    )


if threshold_record.get(
    "zero_day_test_used"
):

    raise RuntimeError(
        "Threshold artifact indicates "
        "zero-day test leakage."
    )


if threshold_record.get(
    "known_test_used"
):

    raise RuntimeError(
        "Threshold artifact indicates "
        "known-test leakage."
    )


print(
    "Frozen threshold:",
    f"{FROZEN_THRESHOLD:.10f}"
)

print(
    "Threshold source:",
    "development_validation"
)

print(
    "Threshold selection rule:",
    threshold_record[
        "selection_rule"
    ]
)

print(
    "Threshold refitted in A18:",
    False
)


# ======================================================================
# 4 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[3] Loading frozen training-only preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        "Expected exactly 75 retained features."
    )


parameter_lookup = (

    parameters

    .set_index(
        "feature"
    )

    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Preprocessing parameters valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)

print(
    "Test-driven clipping:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing invalid."
    )


# ======================================================================
# 5 — LOAD TEMPORAL MANIFEST
# ======================================================================

print("\n[4] Loading frozen temporal manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


KNOWN_ATTACK_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "known_test"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


BENIGN_TEST_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "benign_test"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


ZERO_DAY_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "zero_day_attack_test"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


KNOWN_ATTACK_EXPECTED = int(
    KNOWN_ATTACK_MANIFEST[
        "window_count"
    ].sum()
)


BENIGN_EXPECTED = int(
    BENIGN_TEST_MANIFEST[
        "window_count"
    ].sum()
)


ZERO_DAY_EXPECTED = int(
    ZERO_DAY_MANIFEST[
        "window_count"
    ].sum()
)


print(
    "Known attack source ranges:",
    len(KNOWN_ATTACK_MANIFEST)
)

print(
    "Known attack windows:",
    f"{KNOWN_ATTACK_EXPECTED:,}"
)

print(
    "Benign-test source ranges:",
    len(BENIGN_TEST_MANIFEST)
)

print(
    "Benign-test windows:",
    f"{BENIGN_EXPECTED:,}"
)

print(
    "Zero-day source ranges:",
    len(ZERO_DAY_MANIFEST)
)

print(
    "Zero-day DDoS windows:",
    f"{ZERO_DAY_EXPECTED:,}"
)


if len(KNOWN_ATTACK_MANIFEST) != 20:

    raise RuntimeError(
        "Expected 20 known-test attack ranges."
    )


if len(BENIGN_TEST_MANIFEST) != 1:

    raise RuntimeError(
        "Expected one benign-test range."
    )


if len(ZERO_DAY_MANIFEST) != 12:

    raise RuntimeError(
        "Expected 12 held-out DDoS ranges."
    )


if KNOWN_ATTACK_EXPECTED != 165_769:

    raise RuntimeError(
        "Known-test window count mismatch."
    )


if BENIGN_EXPECTED != 1_715:

    raise RuntimeError(
        "Benign-test window count mismatch."
    )


if ZERO_DAY_EXPECTED != 3_864_829:

    raise RuntimeError(
        "Zero-day window count mismatch."
    )


# ======================================================================
# 6 — STRICT FAMILY ISOLATION CHECK
# ======================================================================

KNOWN_DDOS_WINDOWS = int(

    KNOWN_ATTACK_MANIFEST.loc[
        KNOWN_ATTACK_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


ZERO_NON_DDOS_WINDOWS = int(

    ZERO_DAY_MANIFEST.loc[
        ZERO_DAY_MANIFEST[
            "research_family"
        ]
        !=
        "DDoS",
        "window_count"
    ].sum()
)


print("\n[5] LOAFO isolation check")
print("-" * 78)

print(
    "DDoS windows in known test:",
    KNOWN_DDOS_WINDOWS
)

print(
    "Non-DDoS windows in zero-day test:",
    ZERO_NON_DDOS_WINDOWS
)


if KNOWN_DDOS_WINDOWS != 0:

    raise RuntimeError(
        "DDoS leaked into known-test attacks."
    )


if ZERO_NON_DDOS_WINDOWS != 0:

    raise RuntimeError(
        "Non-DDoS data appeared in zero-day attack test."
    )


# ======================================================================
# 7 — LOAD FINAL MODEL
# ======================================================================

print("\n[6] Loading final Fold-1 model")
print("-" * 78)


model_package = torch.load(
    MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


EVAL_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


EVAL_MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


EVAL_MODEL.eval()


MODEL_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in EVAL_MODEL.parameters()
)


print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Model parameters finite:",
    MODEL_FINITE
)


if not MODEL_FINITE:

    raise RuntimeError(
        "Model contains non-finite parameters."
    )


# ======================================================================
# 8 — FROZEN PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(
    table
):

    X = (

        table
        .to_pandas()
        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        row_indices, feature_indices = (
            np.where(
                bad_mask
            )
        )


        X[
            row_indices,
            feature_indices
        ] = (
            IMPUTE_VALUES[
                feature_indices
            ]
        )


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite transformed float64 values."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite transformed float32 values."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 9 — MODEL INFERENCE FUNCTION
# ======================================================================

INFERENCE_BATCH_SIZE = 8192


def predict_windows(
    windows
):

    outputs = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,
            len(windows)
        )


        tensor = torch.from_numpy(
            windows[
                start:stop
            ]
        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                EVAL_MODEL
                .forward_classifier(
                    tensor
                )
            )


            probabilities = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                logits
            ).all()
        ):

            raise RuntimeError(
                "Non-finite model logits during A18."
            )


        if not bool(
            torch.isfinite(
                probabilities
            ).all()
        ):

            raise RuntimeError(
                "Non-finite probabilities during A18."
            )


        outputs.append(

            probabilities

            .detach()

            .cpu()

            .numpy()

            .astype(
                np.float32
            )
        )


    return np.concatenate(
        outputs
    )


# ======================================================================
# 10 — STREAM ONE MANIFEST PARTITION
# ======================================================================

def evaluate_manifest_ranges(
    partition_manifest,
    label
):

    print(
        f"\nProcessing: {label}"
    )

    print("-" * 78)


    probability_parts = []

    source_records = []

    total_windows = 0

    total_raw_nonfinite = 0

    maximum_absolute_z = 0.0


    for source_index, row in (
        partition_manifest
        .iterrows()
    ):

        source_class = str(
            row[
                "source_attack_class"
            ]
        )


        family = str(
            row[
                "research_family"
            ]
        )


        target = int(
            row[
                "binary_target"
            ]
        )


        start_row = int(
            row[
                "partition_start_row"
            ]
        )


        end_row = int(
            row[
                "partition_end_row_exclusive"
            ]
        )


        expected_windows = int(
            row[
                "window_count"
            ]
        )


        expected_tail = int(
            row[
                "unused_tail_rows"
            ]
        )


        parquet_name = Path(
            str(
                row[
                    "parquet_path"
                ]
            )
        ).name


        parquet_path = (
            CHRONOLOGICAL_ROOT
            /
            parquet_name
        )


        if not parquet_path.exists():

            raise RuntimeError(
                f"Missing Parquet: {parquet_name}"
            )


        parquet_file = pq.ParquetFile(
            parquet_path
        )


        pending = np.empty(
            (
                0,
                75
            ),
            dtype=np.float32
        )


        source_probability_parts = []

        source_raw_nonfinite = 0

        source_max_abs_z = 0.0

        absolute_row = 0


        for row_group_index in range(
            parquet_file.num_row_groups
        ):

            row_group_rows = int(

                parquet_file
                .metadata
                .row_group(
                    row_group_index
                )
                .num_rows
            )


            group_start = absolute_row

            group_end = (
                group_start
                +
                row_group_rows
            )


            absolute_row = group_end


            if group_end <= start_row:
                continue


            if group_start >= end_row:
                break


            table = parquet_file.read_row_group(

                row_group_index,

                columns=
                    RETAINED_FEATURES
            )


            local_start = max(
                0,
                start_row
                -
                group_start
            )


            local_end = min(
                row_group_rows,
                end_row
                -
                group_start
            )


            if local_end <= local_start:
                continue


            table = table.slice(

                local_start,

                local_end
                -
                local_start
            )


            Z, raw_nonfinite = (
                frozen_preprocess(
                    table
                )
            )


            source_raw_nonfinite += (
                raw_nonfinite
            )


            if Z.size > 0:

                source_max_abs_z = max(

                    source_max_abs_z,

                    float(
                        np.max(
                            np.abs(
                                Z
                            )
                        )
                    )
                )


            if len(
                pending
            ) > 0:

                Z = np.concatenate(
                    [
                        pending,
                        Z
                    ],
                    axis=0
                )


            complete_windows = (
                len(Z)
                //
                8
            )


            complete_rows = (
                complete_windows
                *
                8
            )


            if complete_windows > 0:

                windows = (

                    Z[
                        :complete_rows
                    ]

                    .reshape(
                        complete_windows,
                        8,
                        75
                    )
                )


                probabilities = (
                    predict_windows(
                        windows
                    )
                )


                source_probability_parts.append(
                    probabilities
                )


            pending = (

                Z[
                    complete_rows:
                ]

                .copy()
            )


        if source_probability_parts:

            source_probabilities = (
                np.concatenate(
                    source_probability_parts
                )
            )

        else:

            source_probabilities = np.empty(
                0,
                dtype=np.float32
            )


        actual_windows = int(
            len(
                source_probabilities
            )
        )


        actual_tail = int(
            len(
                pending
            )
        )


        if (
            actual_windows
            !=
            expected_windows
        ):

            raise RuntimeError(
                f"Window-count mismatch for "
                f"{source_class}: "
                f"{actual_windows:,} != "
                f"{expected_windows:,}"
            )


        if (
            actual_tail
            !=
            expected_tail
        ):

            raise RuntimeError(
                f"Tail-row mismatch for "
                f"{source_class}: "
                f"{actual_tail} != "
                f"{expected_tail}"
            )


        predicted_positive = (

            source_probabilities

            >=

            FROZEN_THRESHOLD
        )


        positive_rate = float(
            predicted_positive.mean()
        ) if actual_windows else np.nan


        source_records.append({

            "evaluation_group":
                label,

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                target,

            "windows":
                actual_windows,

            "predicted_malicious_fraction":
                positive_rate,

            "probability_mean":
                float(
                    source_probabilities.mean()
                ) if actual_windows else np.nan,

            "probability_min":
                float(
                    source_probabilities.min()
                ) if actual_windows else np.nan,

            "probability_max":
                float(
                    source_probabilities.max()
                ) if actual_windows else np.nan,

            "raw_nonfinite_imputed":
                source_raw_nonfinite,

            "maximum_absolute_transformed_value":
                source_max_abs_z
        })


        probability_parts.append(
            source_probabilities
        )


        total_windows += (
            actual_windows
        )


        total_raw_nonfinite += (
            source_raw_nonfinite
        )


        maximum_absolute_z = max(
            maximum_absolute_z,
            source_max_abs_z
        )


        print(
            f"{source_index + 1:02d}/"
            f"{len(partition_manifest):02d} "
            f"{source_class:<30} "
            f"| windows={actual_windows:>9,} "
            f"| predicted_attack="
            f"{positive_rate:.6f}"
        )


    all_probabilities = (
        np.concatenate(
            probability_parts
        )
    )


    return {

        "probabilities":
            all_probabilities,

        "source_metrics":
            pd.DataFrame(
                source_records
            ),

        "windows":
            total_windows,

        "raw_nonfinite":
            total_raw_nonfinite,

        "max_abs_z":
            maximum_absolute_z
    }


# ======================================================================
# 11 — RUN BENIGN TEST ONCE
# ======================================================================

print("\n[7] Running fixed-threshold evaluation")
print("=" * 78)


evaluation_start = time.time()


BENIGN_RESULT = evaluate_manifest_ranges(

    BENIGN_TEST_MANIFEST,

    "benign_test"
)


# ======================================================================
# 12 — RUN KNOWN-ATTACK TEST
# ======================================================================

KNOWN_RESULT = evaluate_manifest_ranges(

    KNOWN_ATTACK_MANIFEST,

    "known_test_attack"
)


# ======================================================================
# 13 — RUN ZERO-DAY DDoS TEST
# ======================================================================

ZERO_RESULT = evaluate_manifest_ranges(

    ZERO_DAY_MANIFEST,

    "zero_day_DDoS_attack"
)


# ======================================================================
# 14 — VERIFY EXACT WINDOW COUNTS
# ======================================================================

print("\n[8] Exact evaluation-window validation")
print("-" * 78)


print(
    "Benign-test windows:",
    f"{BENIGN_RESULT['windows']:,}",
    "/ 1,715"
)

print(
    "Known attack windows:",
    f"{KNOWN_RESULT['windows']:,}",
    "/ 165,769"
)

print(
    "Zero-day DDoS windows:",
    f"{ZERO_RESULT['windows']:,}",
    "/ 3,864,829"
)


COUNTS_VALID = bool(

    BENIGN_RESULT[
        "windows"
    ]
    ==
    1_715

    and

    KNOWN_RESULT[
        "windows"
    ]
    ==
    165_769

    and

    ZERO_RESULT[
        "windows"
    ]
    ==
    3_864_829
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Final evaluation window counts are invalid."
    )


# ======================================================================
# 15 — CREATE KNOWN EVALUATION ARRAYS
# ======================================================================

known_attack_probabilities = (
    KNOWN_RESULT[
        "probabilities"
    ]
)


benign_probabilities = (
    BENIGN_RESULT[
        "probabilities"
    ]
)


known_y_true = np.concatenate([

    np.ones(
        len(
            known_attack_probabilities
        ),
        dtype=np.uint8
    ),

    np.zeros(
        len(
            benign_probabilities
        ),
        dtype=np.uint8
    )
])


known_probabilities = np.concatenate([

    known_attack_probabilities,

    benign_probabilities
])


# ======================================================================
# 16 — CREATE ZERO-DAY EVALUATION ARRAYS
# ======================================================================

zero_attack_probabilities = (
    ZERO_RESULT[
        "probabilities"
    ]
)


zero_y_true = np.concatenate([

    np.ones(
        len(
            zero_attack_probabilities
        ),
        dtype=np.uint8
    ),

    np.zeros(
        len(
            benign_probabilities
        ),
        dtype=np.uint8
    )
])


zero_probabilities = np.concatenate([

    zero_attack_probabilities,

    benign_probabilities
])


# ======================================================================
# 17 — FIXED-THRESHOLD METRICS FUNCTION
# ======================================================================

def calculate_metrics(
    y_true,
    probabilities,
    threshold
):

    predictions = (

        probabilities

        >=

        threshold

    ).astype(
        np.uint8
    )


    tn, fp, fn, tp = (

        confusion_matrix(

            y_true,

            predictions,

            labels=[
                0,
                1
            ]

        ).ravel()
    )


    precision = float(

        precision_score(
            y_true,
            predictions,
            zero_division=0
        )
    )


    recall = float(

        recall_score(
            y_true,
            predictions,
            zero_division=0
        )
    )


    f1 = float(

        f1_score(
            y_true,
            predictions,
            zero_division=0
        )
    )


    accuracy = float(

        accuracy_score(
            y_true,
            predictions
        )
    )


    fpr = float(

        fp
        /
        max(
            fp + tn,
            1
        )
    )


    pr_auc = float(

        average_precision_score(
            y_true,
            probabilities
        )
    )


    roc_auc = float(

        roc_auc_score(
            y_true,
            probabilities
        )
    )


    return {

        "threshold":
            float(
                threshold
            ),

        "windows":
            int(
                len(
                    y_true
                )
            ),

        "benign_windows":
            int(
                (
                    y_true == 0
                ).sum()
            ),

        "attack_windows":
            int(
                (
                    y_true == 1
                ).sum()
            ),

        "TP":
            int(tp),

        "TN":
            int(tn),

        "FP":
            int(fp),

        "FN":
            int(fn),

        "precision":
            precision,

        "recall":
            recall,

        "F1":
            f1,

        "FPR":
            fpr,

        "accuracy":
            accuracy,

        "PR_AUC":
            pr_auc,

        "ROC_AUC":
            roc_auc
    }


# ======================================================================
# 18 — COMPUTE FINAL METRICS
# ======================================================================

print("\n[9] Computing final metrics")
print("-" * 78)


KNOWN_METRICS = calculate_metrics(

    known_y_true,

    known_probabilities,

    FROZEN_THRESHOLD
)


ZERO_METRICS = calculate_metrics(

    zero_y_true,

    zero_probabilities,

    FROZEN_THRESHOLD
)


print(
    "Known evaluation windows:",
    f"{KNOWN_METRICS['windows']:,}"
)

print(
    "Zero-day evaluation windows:",
    f"{ZERO_METRICS['windows']:,}"
)


# ======================================================================
# 19 — DISPLAY KNOWN PERFORMANCE
# ======================================================================

print("\n[10] KNOWN-FAMILY TEST PERFORMANCE")
print("-" * 78)


print(
    "Threshold :",
    f"{FROZEN_THRESHOLD:.10f}"
)

print(
    "TP        :",
    f"{KNOWN_METRICS['TP']:,}"
)

print(
    "TN        :",
    f"{KNOWN_METRICS['TN']:,}"
)

print(
    "FP        :",
    f"{KNOWN_METRICS['FP']:,}"
)

print(
    "FN        :",
    f"{KNOWN_METRICS['FN']:,}"
)

print(
    "Precision :",
    f"{KNOWN_METRICS['precision']:.10f}"
)

print(
    "Recall    :",
    f"{KNOWN_METRICS['recall']:.10f}"
)

print(
    "F1        :",
    f"{KNOWN_METRICS['F1']:.10f}"
)

print(
    "FPR       :",
    f"{KNOWN_METRICS['FPR']:.10f}"
)

print(
    "PR-AUC    :",
    f"{KNOWN_METRICS['PR_AUC']:.10f}"
)

print(
    "ROC-AUC   :",
    f"{KNOWN_METRICS['ROC_AUC']:.10f}"
)


# ======================================================================
# 20 — DISPLAY ZERO-DAY PERFORMANCE
# ======================================================================

print("\n[11] ZERO-DAY DDoS PERFORMANCE")
print("-" * 78)


print(
    "Threshold       :",
    f"{FROZEN_THRESHOLD:.10f}"
)

print(
    "TP              :",
    f"{ZERO_METRICS['TP']:,}"
)

print(
    "TN              :",
    f"{ZERO_METRICS['TN']:,}"
)

print(
    "FP              :",
    f"{ZERO_METRICS['FP']:,}"
)

print(
    "FN              :",
    f"{ZERO_METRICS['FN']:,}"
)

print(
    "Precision       :",
    f"{ZERO_METRICS['precision']:.10f}"
)

print(
    "Zero-Day Recall :",
    f"{ZERO_METRICS['recall']:.10f}"
)

print(
    "F1              :",
    f"{ZERO_METRICS['F1']:.10f}"
)

print(
    "FPR             :",
    f"{ZERO_METRICS['FPR']:.10f}"
)

print(
    "PR-AUC          :",
    f"{ZERO_METRICS['PR_AUC']:.10f}"
)

print(
    "ROC-AUC         :",
    f"{ZERO_METRICS['ROC_AUC']:.10f}"
)


# ======================================================================
# 21 — SOURCE-LEVEL SUMMARY
# ======================================================================

SOURCE_METRICS = pd.concat([

    BENIGN_RESULT[
        "source_metrics"
    ],

    KNOWN_RESULT[
        "source_metrics"
    ],

    ZERO_RESULT[
        "source_metrics"
    ]

], ignore_index=True)


print("\n[12] Source-level fixed-threshold summary")
print("-" * 78)

display(
    SOURCE_METRICS
)


# ======================================================================
# 22 — CREATE RESULT TABLE
# ======================================================================

FINAL_METRICS_TABLE = pd.DataFrame([

    {

        "evaluation":
            "known_family_test",

        **KNOWN_METRICS
    },

    {

        "evaluation":
            "zero_day_DDoS",

        **ZERO_METRICS
    }
])


print("\n[13] Final Fold-1 metric table")
print("-" * 78)

display(
    FINAL_METRICS_TABLE
)


# ======================================================================
# 23 — SAVE ARTIFACTS
# ======================================================================

print("\n[14] Saving Fold-1 final evaluation artifacts")
print("-" * 78)


LOCAL_OUTPUT_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "metrics/final_evaluation/"
    "fold_01_DDoS/"
    "seed_13/"
    "MOT_SSL_GRU"
)


DRIVE_OUTPUT_DIR = (
    BACKUP_ROOT
    / "metrics"
    / "final_evaluation"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
)


LOCAL_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


METRICS_CSV = (
    LOCAL_OUTPUT_DIR
    / "fold_01_DDoS_final_metrics.csv"
)


SOURCE_CSV = (
    LOCAL_OUTPUT_DIR
    / "fold_01_DDoS_source_level_metrics.csv"
)


SUMMARY_JSON = (
    LOCAL_OUTPUT_DIR
    / "fold_01_DDoS_evaluation_summary.json"
)


KNOWN_PREDICTIONS_NPZ = (
    LOCAL_OUTPUT_DIR
    / "known_evaluation_predictions.npz"
)


ZERO_PREDICTIONS_NPZ = (
    LOCAL_OUTPUT_DIR
    / "zero_day_evaluation_predictions.npz"
)


FINAL_METRICS_TABLE.to_csv(
    METRICS_CSV,
    index=False
)


SOURCE_METRICS.to_csv(
    SOURCE_CSV,
    index=False
)


# Compact per-window prediction artifacts.
np.savez_compressed(

    KNOWN_PREDICTIONS_NPZ,

    y_true=
        known_y_true,

    malicious_probability=
        known_probabilities.astype(
            np.float32
        ),

    threshold=
        np.array(
            [
                FROZEN_THRESHOLD
            ],
            dtype=np.float64
        )
)


np.savez_compressed(

    ZERO_PREDICTIONS_NPZ,

    y_true=
        zero_y_true,

    malicious_probability=
        zero_probabilities.astype(
            np.float32
        ),

    threshold=
        np.array(
            [
                FROZEN_THRESHOLD
            ],
            dtype=np.float64
        )
)


SUMMARY = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "model":
        "MOT-SSL-GRU",

    "seed":
        13,

    "SSL_lambda_t":
        0.25,

    "SSL_lambda_status":
        "provisional_not_yet_tuned",

    "imbalance_method":
        "none",

    "threshold":
        FROZEN_THRESHOLD,

    "threshold_source":
        "development_validation_only",

    "threshold_refitted_on_test":
        False,

    "preprocessing_refitted_on_test":
        False,

    "test_driven_clipping":
        False,

    "known_evaluation":
        KNOWN_METRICS,

    "zero_day_evaluation":
        ZERO_METRICS,

    "zero_day_recall":
        ZERO_METRICS[
            "recall"
        ],

    "raw_nonfinite_imputed": {

        "benign_test":
            int(
                BENIGN_RESULT[
                    "raw_nonfinite"
                ]
            ),

        "known_test_attack":
            int(
                KNOWN_RESULT[
                    "raw_nonfinite"
                ]
            ),

        "zero_day_DDoS":
            int(
                ZERO_RESULT[
                    "raw_nonfinite"
                ]
            )
    },

    "maximum_absolute_transformed_value": {

        "benign_test":
            float(
                BENIGN_RESULT[
                    "max_abs_z"
                ]
            ),

        "known_test_attack":
            float(
                KNOWN_RESULT[
                    "max_abs_z"
                ]
            ),

        "zero_day_DDoS":
            float(
                ZERO_RESULT[
                    "max_abs_z"
                ]
            )
    }
}


with open(
    SUMMARY_JSON,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SUMMARY,
        file,
        indent=4
    )


# ======================================================================
# 24 — BACK UP ALL RESULTS TO DRIVE
# ======================================================================

artifact_paths = [

    METRICS_CSV,

    SOURCE_CSV,

    SUMMARY_JSON,

    KNOWN_PREDICTIONS_NPZ,

    ZERO_PREDICTIONS_NPZ
]


for source_path in artifact_paths:

    shutil.copy2(

        source_path,

        DRIVE_OUTPUT_DIR
        /
        source_path.name
    )


ARTIFACTS_BACKED_UP = all(

    (
        DRIVE_OUTPUT_DIR
        /
        path.name
    ).exists()

    for path in artifact_paths
)


# ======================================================================
# 25 — FINAL INTEGRITY VALIDATION
# ======================================================================

METRICS_FINITE = all(

    np.isfinite(
        value
    )

    for value in [

        KNOWN_METRICS[
            "precision"
        ],

        KNOWN_METRICS[
            "recall"
        ],

        KNOWN_METRICS[
            "F1"
        ],

        KNOWN_METRICS[
            "FPR"
        ],

        KNOWN_METRICS[
            "PR_AUC"
        ],

        KNOWN_METRICS[
            "ROC_AUC"
        ],

        ZERO_METRICS[
            "precision"
        ],

        ZERO_METRICS[
            "recall"
        ],

        ZERO_METRICS[
            "F1"
        ],

        ZERO_METRICS[
            "FPR"
        ],

        ZERO_METRICS[
            "PR_AUC"
        ],

        ZERO_METRICS[
            "ROC_AUC"
        ]
    ]
)


CONFUSIONS_VALID = bool(

    (
        KNOWN_METRICS[
            "TP"
        ]

        +

        KNOWN_METRICS[
            "TN"
        ]

        +

        KNOWN_METRICS[
            "FP"
        ]

        +

        KNOWN_METRICS[
            "FN"
        ]
    )
    ==
    167_484

    and

    (
        ZERO_METRICS[
            "TP"
        ]

        +

        ZERO_METRICS[
            "TN"
        ]

        +

        ZERO_METRICS[
            "FP"
        ]

        +

        ZERO_METRICS[
            "FN"
        ]
    )
    ==
    3_866_544
)


A18_VALID = bool(

    COUNTS_VALID

    and

    KNOWN_DDOS_WINDOWS
    ==
    0

    and

    ZERO_NON_DDOS_WINDOWS
    ==
    0

    and

    MODEL_FINITE

    and

    PREPROCESSING_VALID

    and

    METRICS_FINITE

    and

    CONFUSIONS_VALID

    and

    ARTIFACTS_BACKED_UP
)


STEP_18_FOLD1_EVALUATION_VALID = (
    A18_VALID
)


total_runtime = (
    time.time()
    -
    evaluation_start
)


print("\n[15] Recovery Step A18 validation")
print("-" * 78)

print(
    "Frozen threshold reused        :",
    f"{FROZEN_THRESHOLD:.10f}"
)

print(
    "Threshold refitted             :",
    False
)

print(
    "Preprocessing refitted         :",
    False
)

print(
    "Known evaluation windows       :",
    f"{KNOWN_METRICS['windows']:,}",
    "/ 167,484"
)

print(
    "Zero-day evaluation windows    :",
    f"{ZERO_METRICS['windows']:,}",
    "/ 3,866,544"
)

print(
    "DDoS in known attack test      :",
    KNOWN_DDOS_WINDOWS
)

print(
    "Non-DDoS in zero-day attacks   :",
    ZERO_NON_DDOS_WINDOWS
)

print(
    "Known-test F1                  :",
    f"{KNOWN_METRICS['F1']:.10f}"
)

print(
    "Known-test FPR                 :",
    f"{KNOWN_METRICS['FPR']:.10f}"
)

print(
    "Zero-Day Recall                :",
    f"{ZERO_METRICS['recall']:.10f}"
)

print(
    "Zero-Day F1                    :",
    f"{ZERO_METRICS['F1']:.10f}"
)

print(
    "Zero-Day FPR                   :",
    f"{ZERO_METRICS['FPR']:.10f}"
)

print(
    "Zero-Day PR-AUC                :",
    f"{ZERO_METRICS['PR_AUC']:.10f}"
)

print(
    "Zero-Day ROC-AUC               :",
    f"{ZERO_METRICS['ROC_AUC']:.10f}"
)

print(
    "Confusion totals valid         :",
    CONFUSIONS_VALID
)

print(
    "Artifacts backed up            :",
    ARTIFACTS_BACKED_UP
)

print(
    "Total A18 runtime              :",
    f"{total_runtime / 60:.2f} minutes"
)


print("\n" + "=" * 78)

if A18_VALID:

    print(
        "✅ RECOVERY STEP A18 PASSED — "
        "Fold-1 DDoS LOAFO evaluation completed "
        "using the frozen validation-selected threshold."
    )

else:

    print(
        "❌ RECOVERY STEP A18 FAILED — "
        "Do not treat Fold 1 as finalized."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A18 — FINAL FOLD-1 EVALUATION
HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A16 fine-tuning valid: True
A17 threshold valid: True
Device: cuda

[2] Loading frozen A17 threshold
------------------------------------------------------------------------------
Frozen threshold: 0.0147513831
Threshold source: development_validation
Threshold selection rule: maximize_validation_F1
Threshold refitted in A18: False

[3] Loading frozen training-only preprocessing
------------------------------------------------------------------------------
Retained features: 75
Preprocessing parameters valid: True
Preprocessing refitted: False
Test-driven clipping: False

[4] Loading frozen temporal manifest
------------------------------------------------------------------------------
Known attack source ranges: 20
Known attack windows: 165,769
Benign-test source ranges: 1
Benign-test windows: 1,715
Zero-day source ranges: 12
Zero-day DDoS windows: 3,864,829

[5] LOAFO isolation check
------------------------------------------------------------------------------
DDoS windows in known test: 0
Non-DDoS windows in zero-day test: 0

[6] Loading final Fold-1 model
------------------------------------------------------------------------------
Fine-tuning epochs: 20
Imbalance method: none
Model parameters finite: True

[7] Running fixed-threshold evaluation
==============================================================================

Processing: benign_test
------------------------------------------------------------------------------
01/01 Benign_Final                   | windows=    1,715 | predicted_attack=0.397668

Processing: known_test_attack
------------------------------------------------------------------------------
01/20 Backdoor_Malware               | windows=       50 | predicted_attack=1.000000
02/20 BrowserHijacking               | windows=       61 | predicted_attack=0.967213
03/20 CommandInjection               | windows=       72 | predicted_attack=0.986111
04/20 DNS_Spoofing                   | windows=    1,405 | predicted_attack=0.958007
05/20 DictionaryBruteForce           | windows=      159 | predicted_attack=0.993711
06/20 DoS-HTTP_Flood                 | windows=   18,104 | predicted_attack=0.999669
07/20 DoS-SYN_Flood                  | windows=   74,945 | predicted_attack=1.000000
08/20 DoS-TCP_Flood                  | windows=   30,713 | predicted_attack=0.999902
09/20 DoS-UDP_Flood                  | windows=   17,512 | predicted_attack=0.999943
10/20 MITM-ArpSpoofing               | windows=    1,366 | predicted_attack=0.998536
11/20 Mirai-greeth_flood             | windows=       96 | predicted_attack=0.989583
12/20 Mirai-greip_flood              | windows=      195 | predicted_attack=0.994872
13/20 Mirai-udpplain                 | windows=      139 | predicted_attack=0.956835
14/20 Recon-HostDiscovery            | windows=    6,187 | predicted_attack=0.956037
15/20 Recon-OSScan                   | windows=    2,975 | predicted_attack=0.998655
16/20 Recon-PingSweep                | windows=       36 | predicted_attack=1.000000
17/20 Recon-PortScan                 | windows=    3,282 | predicted_attack=0.999391
18/20 SqlInjection                   | windows=      123 | predicted_attack=1.000000
19/20 VulnerabilityScan              | windows=    8,289 | predicted_attack=0.996622
20/20 XSS                            | windows=       60 | predicted_attack=1.000000

Processing: zero_day_DDoS_attack
------------------------------------------------------------------------------
01/12 DDoS-ACK_Fragmentation         | windows=    4,662 | predicted_attack=0.920635
02/12 DDoS-HTTP_Flood                | windows=   64,209 | predicted_attack=0.999143
03/12 DDoS-ICMP_Flood                | windows=      979 | predicted_attack=1.000000
04/12 DDoS-ICMP_Fragmentation        | windows=    3,138 | predicted_attack=0.998088
05/12 DDoS-PSHACK_Flood              | windows=  625,883 | predicted_attack=0.999990
06/12 DDoS-RSTFINFlood               | windows=1,621,077 | predicted_attack=0.999983
07/12 DDoS-SYN_Flood                 | windows=  795,794 | predicted_attack=0.999649
08/12 DDoS-SlowLoris                 | windows=   24,572 | predicted_attack=0.990192
09/12 DDoS-SynonymousIP_Flood        | windows=   99,918 | predicted_attack=0.999960
10/12 DDoS-TCP_Flood                 | windows=  618,235 | predicted_attack=0.999968
11/12 DDoS-UDP_Flood                 | windows=    5,143 | predicted_attack=0.999806
12/12 DDoS-UDP_Fragmentation         | windows=    1,219 | predicted_attack=0.977851

[8] Exact evaluation-window validation
------------------------------------------------------------------------------
Benign-test windows: 1,715 / 1,715
Known attack windows: 165,769 / 165,769
Zero-day DDoS windows: 3,864,829 / 3,864,829

[9] Computing final metrics
------------------------------------------------------------------------------
Known evaluation windows: 167,484
Zero-day evaluation windows: 3,866,544

[10] KNOWN-FAMILY TEST PERFORMANCE
------------------------------------------------------------------------------
Threshold : 0.0147513831
TP        : 165,380
TN        : 1,033
FP        : 682
FN        : 389
Precision : 0.9958931002
Recall    : 0.9976533610
F1        : 0.9967724534
FPR       : 0.3976676385
PR-AUC    : 0.9998518864
ROC-AUC   : 0.9882727900

[11] ZERO-DAY DDoS PERFORMANCE
------------------------------------------------------------------------------
Threshold       : 0.0147513831
TP              : 3,863,793
TN              : 1,033
FP              : 682
FN              : 1,036
Precision       : 0.9998235207
Zero-Day Recall : 0.9997319416
F1              : 0.9997777290
FPR             : 0.3976676385
PR-AUC          : 0.9999926425
ROC-AUC         : 0.9877325376

[12] Source-level fixed-threshold summary
------------------------------------------------------------------------------

,evaluation_group,source_attack_class,research_family,binary_target,windows,predicted_malicious_fraction,probability_mean,probability_min,probability_max,raw_nonfinite_imputed,maximum_absolute_transformed_value
0,benign_test,Benign_Final,Benign,0,1715,0.397668,0.202546,6.023584e-12,1.0,10,2.473136e+02
1,known_test_attack,Backdoor_Malware,Web,1,50,1.000000,0.974999,3.721921e-01,1.0,0,4.863623e+01
2,known_test_attack,BrowserHijacking,Web,1,61,0.967213,0.960731,1.818136e-04,1.0,0,2.224962e+02
3,known_test_attack,CommandInjection,Web,1,72,0.986111,0.948814,8.035383e-04,1.0,0,1.610558e+02
4,known_test_attack,DNS_Spoofing,Spoofing,1,1405,0.958007,0.884533,1.816550e-07,1.0,14,2.209939e+02
5,known_test_attack,DictionaryBruteForce,BruteForce,1,159,0.993711,0.976730,8.278713e-03,1.0,0,1.483280e+02
6,known_test_attack,DoS-HTTP_Flood,DoS,1,18104,0.999669,0.997878,7.796056e-04,1.0,24082,4.634438e+02
7,known_test_attack,DoS-SYN_Flood,DoS,1,74945,1.000000,0.999987,2.535050e-01,1.0,66,2.224962e+02
8,known_test_attack,DoS-TCP_Flood,DoS,1,30713,0.999902,0.986793,6.754443e-04,1.0,818,2.293445e+02
9,known_test_attack,DoS-UDP_Flood,DoS,1,17512,0.999943,0.999847,1.272125e-02,1.0,34,4.807810e+12
10,known_test_attack,MITM-ArpSpoofing,Spoofing,1,1366,0.998536,0.978161,2.818147e-04,1.0,22,2.967089e+03
11,known_test_attack,Mirai-greeth_flood,Mirai,1,96,0.989583,0.971273,2.352947e-03,1.0,2,5.342613e+02
12,known_test_attack,Mirai-greip_flood,Mirai,1,195,0.994872,0.984408,2.870449e-03,1.0,0,9.214404e+02
13,known_test_attack,Mirai-udpplain,Mirai,1,139,0.956835,0.852136,1.445529e-05,1.0,2,3.602656e+02
14,known_test_attack,Recon-HostDiscovery,Recon,1,6187,0.956037,0.889456,1.633876e-08,1.0,32,2.224962e+02
15,known_test_attack,Recon-OSScan,Recon,1,2975,0.998655,0.993495,3.812508e-06,1.0,62,1.879548e+02
16,known_test_attack,Recon-PingSweep,Recon,1,36,1.000000,0.998001,9.280414e-01,1.0,0,3.234679e+01
17,known_test_attack,Recon-PortScan,Recon,1,3282,0.999391,0.996991,1.865523e-05,1.0,28,1.639552e+02
18,known_test_attack,SqlInjection,Web,1,123,1.000000,0.998688,8.406441e-01,1.0,0,3.533453e+01
19,known_test_attack,VulnerabilityScan,Recon,1,8289,0.996622,0.986040,9.710576e-07,1.0,398,2.224962e+02
20,known_test_attack,XSS,Web,1,60,1.000000,0.952561,3.769661e-01,1.0,0,7.415977e+01
21,zero_day_DDoS_attack,DDoS-ACK_Fragmentation,DDoS,1,4662,0.920635,0.810730,3.748453e-06,1.0,10,8.433646e+05
22,zero_day_DDoS_attack,DDoS-HTTP_Flood,DDoS,1,64209,0.999143,0.996196,1.109324e-06,1.0,2300,1.138723e+03
23,zero_day_DDoS_attack,DDoS-ICMP_Flood,DDoS,1,979,1.000000,0.992858,2.015004e-02,1.0,58,4.718098e+04
24,zero_day_DDoS_attack,DDoS-ICMP_Fragmentation,DDoS,1,3138,0.998088,0.988196,5.073743e-05,1.0,44,1.064469e+03
25,zero_day_DDoS_attack,DDoS-PSHACK_Flood,DDoS,1,625883,0.999990,0.999607,1.376901e-05,1.0,0,2.918978e+02
26,zero_day_DDoS_attack,DDoS-RSTFINFlood,DDoS,1,1621077,0.999983,0.999882,5.469334e-06,1.0,8,1.876422e+02
27,zero_day_DDoS_attack,DDoS-SYN_Flood,DDoS,1,795794,0.999649,0.987372,1.178498e-04,1.0,324,2.224962e+02
28,zero_day_DDoS_attack,DDoS-SlowLoris,DDoS,1,24572,0.990192,0.977777,6.326519e-10,1.0,66,1.164901e+03
29,zero_day_DDoS_attack,DDoS-SynonymousIP_Flood,DDoS,1,99918,0.999960,0.999836,4.396109e-05,1.0,6,2.918978e+02
30,zero_day_DDoS_attack,DDoS-TCP_Flood,DDoS,1,618235,0.999968,0.985147,5.145599e-04,1.0,246,1.483280e+02
31,zero_day_DDoS_attack,DDoS-UDP_Flood,DDoS,1,5143,0.999806,0.999023,8.848291e-03,1.0,262,2.270913e+03
32,zero_day_DDoS_attack,DDoS-UDP_Fragmentation,DDoS,1,1219,0.977851,0.938991,1.322699e-08,1.0,10,3.795661e+02

[13] Final Fold-1 metric table
------------------------------------------------------------------------------

,evaluation,threshold,windows,benign_windows,attack_windows,TP,TN,FP,FN,precision,recall,F1,FPR,accuracy,PR_AUC,ROC_AUC
0,known_family_test,0.014751,167484,1715,165769,165380,1033,682,389,0.995893,0.997653,0.996772,0.397668,0.993605,0.999852,0.988273
1,zero_day_DDoS,0.014751,3866544,1715,3864829,3863793,1033,682,1036,0.999824,0.999732,0.999778,0.397668,0.999556,0.999993,0.987733

[14] Saving Fold-1 final evaluation artifacts
------------------------------------------------------------------------------

[15] Recovery Step A18 validation
------------------------------------------------------------------------------
Frozen threshold reused        : 0.0147513831
Threshold refitted             : False
Preprocessing refitted         : False
Known evaluation windows       : 167,484 / 167,484
Zero-day evaluation windows    : 3,866,544 / 3,866,544
DDoS in known attack test      : 0
Non-DDoS in zero-day attacks   : 0
Known-test F1                  : 0.9967724534
Known-test FPR                 : 0.3976676385
Zero-Day Recall                : 0.9997319416
Zero-Day F1                    : 0.9997777290
Zero-Day FPR                   : 0.3976676385
Zero-Day PR-AUC                : 0.9999926425
Zero-Day ROC-AUC               : 0.9877325376
Confusion totals valid         : True
Artifacts backed up            : True
Total A18 runtime              : 2.30 minutes

==============================================================================
✅ RECOVERY STEP A18 PASSED — Fold-1 DDoS LOAFO evaluation completed using the frozen validation-selected threshold.
==============================================================================

# A19 — Freeze the Fold-1 result before moving on

In [ ]:
# ======================================================================
# STEP A19
# FREEZE FOLD-1 SEED-13 PROVISIONAL EXPERIMENT MILESTONE
# ======================================================================

from pathlib import Path
import json
import shutil
from datetime import datetime, timezone


print("=" * 78)
print("STEP A19 — FREEZE FOLD-1 EXPERIMENT MILESTONE")
print("=" * 78)


# ======================================================================
# 1 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


A18_SUMMARY = (
    BACKUP_ROOT
    / "metrics"
    / "final_evaluation"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
    / "fold_01_DDoS_evaluation_summary.json"
)


A17_THRESHOLD = (
    BACKUP_ROOT
    / "predictions"
    / "threshold_selection"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
    / "selected_threshold.json"
)


A16_MODEL = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


for path in [
    A18_SUMMARY,
    A17_THRESHOLD,
    A16_MODEL
]:

    if not path.exists():

        raise RuntimeError(
            f"Required Fold-1 artifact missing:\n{path}"
        )


print(
    "A18 summary exists:",
    A18_SUMMARY.exists()
)

print(
    "A17 threshold exists:",
    A17_THRESHOLD.exists()
)

print(
    "A16 final model exists:",
    A16_MODEL.exists()
)


# ======================================================================
# 2 — LOAD FINAL RESULTS
# ======================================================================

with open(
    A18_SUMMARY,
    "r",
    encoding="utf-8"
) as file:

    result = json.load(file)


with open(
    A17_THRESHOLD,
    "r",
    encoding="utf-8"
) as file:

    threshold_record = json.load(file)


# ======================================================================
# 3 — BUILD MILESTONE RECORD
# ======================================================================

milestone = {

    "experiment_status":
        "completed_provisional_fold1_configuration",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "model":
        "MOT-SSL-GRU",

    "seed":
        13,

    "temporal_window":
        8,

    "retained_features":
        75,

    "SSL_epochs":
        30,

    "fine_tuning_epochs":
        20,

    "SSL_precision":
        "float32",

    "SSL_lambda_t":
        0.25,

    "SSL_lambda_t_status":
        "provisional_not_yet_tuned",

    "imbalance_method":
        "none",

    "imbalance_method_status":
        "baseline_condition_not_yet_compared",

    "threshold_selection":
        "maximize_F1_on_development_validation_only",

    "threshold":
        float(
            threshold_record[
                "selected_threshold"
            ]
        ),

    "known_test": {

        "F1":
            result[
                "known_evaluation"
            ][
                "F1"
            ],

        "recall":
            result[
                "known_evaluation"
            ][
                "recall"
            ],

        "precision":
            result[
                "known_evaluation"
            ][
                "precision"
            ],

        "FPR":
            result[
                "known_evaluation"
            ][
                "FPR"
            ],

        "PR_AUC":
            result[
                "known_evaluation"
            ][
                "PR_AUC"
            ],

        "ROC_AUC":
            result[
                "known_evaluation"
            ][
                "ROC_AUC"
            ]
    },

    "zero_day_DDoS": {

        "F1":
            result[
                "zero_day_evaluation"
            ][
                "F1"
            ],

        "zero_day_recall":
            result[
                "zero_day_evaluation"
            ][
                "recall"
            ],

        "precision":
            result[
                "zero_day_evaluation"
            ][
                "precision"
            ],

        "FPR":
            result[
                "zero_day_evaluation"
            ][
                "FPR"
            ],

        "PR_AUC":
            result[
                "zero_day_evaluation"
            ][
                "PR_AUC"
            ],

        "ROC_AUC":
            result[
                "zero_day_evaluation"
            ][
                "ROC_AUC"
            ]
    },

    "leakage_integrity": {

        "held_out_family_used_in_training":
            False,

        "held_out_family_used_in_validation":
            False,

        "threshold_selected_from_test":
            False,

        "preprocessing_refitted_on_test":
            False
    },

    "important_interpretation": (
        "Zero-day recall is very high, but benign-test "
        "false-positive rate is also high. This result "
        "must be retained transparently and must not be "
        "changed using test information."
    ),

    "remaining_work": [
        "lambda_t sensitivity",
        "class imbalance sensitivity",
        "additional seeds",
        "remaining six LOAFO folds",
        "baselines",
        "ablation",
        "statistical analysis"
    ],

    "milestone_created_utc":
        datetime.now(
            timezone.utc
        ).isoformat()
}


# ======================================================================
# 4 — SAVE MILESTONE
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "final_exports/experiment_milestones"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "final_exports"
    / "experiment_milestones"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_PATH = (
    LOCAL_DIR
    / "fold_01_DDoS_seed13_provisional_milestone.json"
)


DRIVE_PATH = (
    DRIVE_DIR
    / "fold_01_DDoS_seed13_provisional_milestone.json"
)


with open(
    LOCAL_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        milestone,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_PATH,
    DRIVE_PATH
)


# ======================================================================
# 5 — FINAL CHECK
# ======================================================================

A19_VALID = bool(

    DRIVE_PATH.exists()

    and

    milestone[
        "zero_day_DDoS"
    ][
        "zero_day_recall"
    ]
    ==
    result[
        "zero_day_evaluation"
    ][
        "recall"
    ]

    and

    milestone[
        "known_test"
    ][
        "F1"
    ]
    ==
    result[
        "known_evaluation"
    ][
        "F1"
    ]
)


print("\nFold-1 milestone summary")
print("-" * 78)

print(
    "Known F1        :",
    f"{milestone['known_test']['F1']:.10f}"
)

print(
    "Known FPR       :",
    f"{milestone['known_test']['FPR']:.10f}"
)

print(
    "Zero-Day Recall :",
    f"{milestone['zero_day_DDoS']['zero_day_recall']:.10f}"
)

print(
    "Zero-Day F1     :",
    f"{milestone['zero_day_DDoS']['F1']:.10f}"
)

print(
    "Zero-Day FPR    :",
    f"{milestone['zero_day_DDoS']['FPR']:.10f}"
)

print(
    "Drive milestone:",
    DRIVE_PATH.exists()
)


print("\n" + "=" * 78)

if A19_VALID:

    print(
        "✅ STEP A19 PASSED — "
        "Fold-1 Seed-13 provisional result is frozen "
        "and safely recorded in Drive."
    )

else:

    print(
        "❌ STEP A19 FAILED — "
        "Do not move to the next experiment yet."
    )

print("=" * 78)

==============================================================================
STEP A19 — FREEZE FOLD-1 EXPERIMENT MILESTONE
==============================================================================
A18 summary exists: True
A17 threshold exists: True
A16 final model exists: True

Fold-1 milestone summary
------------------------------------------------------------------------------
Known F1        : 0.9967724534
Known FPR       : 0.3976676385
Zero-Day Recall : 0.9997319416
Zero-Day F1     : 0.9997777290
Zero-Day FPR    : 0.3976676385
Drive milestone: True

==============================================================================
✅ STEP A19 PASSED — Fold-1 Seed-13 provisional result is frozen and safely recorded in Drive.
==============================================================================

# Step A20 — Freeze λ sensitivity experiment plan

In [ ]:
# ======================================================================
# STEP A20
# FREEZE LAMBDA_T SENSITIVITY EXPERIMENT PROTOCOL
#
# No training in this step.
# No test data access.
# No zero-day data access.
# ======================================================================

from pathlib import Path
import json
import shutil

import pandas as pd


print("=" * 78)
print("STEP A20 — FREEZE LAMBDA_T SENSITIVITY PROTOCOL")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — CONFIGURATION
# ======================================================================

LAMBDA_CANDIDATES = [
    0.10,
    0.25,
    0.50,
    1.00
]

SEED = 13

TEMPORAL_WINDOW = 8

SSL_EPOCHS = 30

FINETUNE_EPOCHS = 20

IMBALANCE_METHOD = "none"

THRESHOLD_RULE = (
    "maximize_F1_on_development_validation"
)

LAMBDA_SELECTION_METRIC = (
    "development_validation_F1"
)

LAMBDA_TIEBREAK_1 = (
    "lower_development_validation_FPR"
)

LAMBDA_TIEBREAK_2 = (
    "smaller_lambda_t"
)


print(
    "Lambda candidates:",
    LAMBDA_CANDIDATES
)

print(
    "Seed:",
    SEED
)

print(
    "Temporal window:",
    TEMPORAL_WINDOW
)

print(
    "SSL epochs:",
    SSL_EPOCHS
)

print(
    "Fine-tuning epochs:",
    FINETUNE_EPOCHS
)

print(
    "Imbalance method:",
    IMBALANCE_METHOD
)

print(
    "Lambda selection metric:",
    LAMBDA_SELECTION_METRIC
)


# ======================================================================
# 2 — LOAD COMPLETED λ=0.25 VALIDATION RESULT ONLY
# ======================================================================

print("\n[1] Loading existing lambda=0.25 validation result")
print("-" * 78)


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


LAMBDA_025_THRESHOLD_PATH = (
    BACKUP_ROOT
    / "predictions"
    / "threshold_selection"
    / "fold_01_DDoS"
    / "seed_13"
    / "MOT_SSL_GRU"
    / "selected_threshold.json"
)


if not LAMBDA_025_THRESHOLD_PATH.exists():

    raise RuntimeError(
        "Existing lambda=0.25 A17 result is missing."
    )


with open(
    LAMBDA_025_THRESHOLD_PATH,
    "r",
    encoding="utf-8"
) as file:

    lambda025_validation = json.load(
        file
    )


# Strictly validate that this came from development validation.
if (
    lambda025_validation[
        "partition_used"
    ]
    !=
    "development_validation"
):

    raise RuntimeError(
        "lambda=0.25 result was not generated "
        "from development validation."
    )


if (
    lambda025_validation[
        "held_out_DDoS_windows_used"
    ]
    !=
    0
):

    raise RuntimeError(
        "Held-out DDoS was used in threshold selection."
    )


print(
    "Existing lambda:",
    0.25
)

print(
    "Validation threshold:",
    f"{lambda025_validation['selected_threshold']:.10f}"
)

print(
    "Validation F1:",
    f"{lambda025_validation['validation_F1']:.10f}"
)

print(
    "Validation FPR:",
    f"{lambda025_validation['validation_FPR']:.10f}"
)

print(
    "Held-out DDoS used:",
    False
)


# ======================================================================
# 3 — CREATE EXPERIMENT REGISTRY
# ======================================================================

print("\n[2] Creating lambda experiment registry")
print("-" * 78)


records = []


for lambda_t in LAMBDA_CANDIDATES:

    completed = bool(
        lambda_t == 0.25
    )


    record = {

        "fold_id":
            1,

        "held_out_family":
            "DDoS",

        "seed":
            SEED,

        "temporal_window":
            TEMPORAL_WINDOW,

        "lambda_t":
            lambda_t,

        "SSL_epochs":
            SSL_EPOCHS,

        "fine_tuning_epochs":
            FINETUNE_EPOCHS,

        "imbalance_method":
            IMBALANCE_METHOD,

        "status":
            (
                "validation_complete"
                if completed
                else
                "pending"
            ),

        "selected_threshold":
            (
                float(
                    lambda025_validation[
                        "selected_threshold"
                    ]
                )
                if completed
                else
                None
            ),

        "validation_F1":
            (
                float(
                    lambda025_validation[
                        "validation_F1"
                    ]
                )
                if completed
                else
                None
            ),

        "validation_FPR":
            (
                float(
                    lambda025_validation[
                        "validation_FPR"
                    ]
                )
                if completed
                else
                None
            ),

        "validation_recall":
            (
                float(
                    lambda025_validation[
                        "validation_recall"
                    ]
                )
                if completed
                else
                None
            ),

        "test_metrics_used_for_selection":
            False,

        "zero_day_metrics_used_for_selection":
            False
    }


    records.append(
        record
    )


LAMBDA_REGISTRY = pd.DataFrame(
    records
)


display(
    LAMBDA_REGISTRY
)


# ======================================================================
# 4 — DEFINE FINAL SELECTION POLICY
# ======================================================================

SELECTION_POLICY = {

    "research_question":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "lambda_candidates":
        LAMBDA_CANDIDATES,

    "selection_data":
        "development_validation_only",

    "threshold_selection_per_lambda":
        THRESHOLD_RULE,

    "lambda_primary_selection_metric":
        LAMBDA_SELECTION_METRIC,

    "lambda_tiebreak_1":
        LAMBDA_TIEBREAK_1,

    "lambda_tiebreak_2":
        LAMBDA_TIEBREAK_2,

    "test_data_allowed_for_lambda_selection":
        False,

    "zero_day_data_allowed_for_lambda_selection":
        False,

    "existing_lambda_0p25_test_result":
        (
            "provisional_only_not_used_for_lambda_selection"
        ),

    "controlled_variables": {

        "seed":
            SEED,

        "temporal_window":
            TEMPORAL_WINDOW,

        "training_sample":
            "same_A11_sample",

        "architecture":
            "same_A14_architecture",

        "SSL_epochs":
            SSL_EPOCHS,

        "fine_tuning_epochs":
            FINETUNE_EPOCHS,

        "imbalance_method":
            IMBALANCE_METHOD,

        "precision":
            "float32"
    },

    "important_rule":
        (
            "The selected lambda_t must be determined "
            "before comparing final test or zero-day "
            "performance across lambda candidates."
        )
}


# ======================================================================
# 5 — SAVE TO LOCAL + DRIVE
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/lambda_t/"
    "fold_01_DDoS"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_REGISTRY_PATH = (
    LOCAL_DIR
    / "fold_01_lambda_t_experiment_registry.csv"
)


DRIVE_REGISTRY_PATH = (
    DRIVE_DIR
    / "fold_01_lambda_t_experiment_registry.csv"
)


LOCAL_POLICY_PATH = (
    LOCAL_DIR
    / "fold_01_lambda_t_selection_policy.json"
)


DRIVE_POLICY_PATH = (
    DRIVE_DIR
    / "fold_01_lambda_t_selection_policy.json"
)


LAMBDA_REGISTRY.to_csv(
    LOCAL_REGISTRY_PATH,
    index=False
)


with open(
    LOCAL_POLICY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SELECTION_POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_REGISTRY_PATH,
    DRIVE_REGISTRY_PATH
)


shutil.copy2(
    LOCAL_POLICY_PATH,
    DRIVE_POLICY_PATH
)


# ======================================================================
# 6 — FINAL VALIDATION
# ======================================================================

REGISTRY_VALID = bool(

    len(
        LAMBDA_REGISTRY
    )
    ==
    4

    and

    set(
        LAMBDA_REGISTRY[
            "lambda_t"
        ].tolist()
    )
    ==
    {
        0.10,
        0.25,
        0.50,
        1.00
    }

    and

    int(
        (
            LAMBDA_REGISTRY[
                "status"
            ]
            ==
            "validation_complete"
        ).sum()
    )
    ==
    1

    and

    float(
        LAMBDA_REGISTRY.loc[
            LAMBDA_REGISTRY[
                "lambda_t"
            ]
            ==
            0.25,
            "validation_F1"
        ].iloc[0]
    )
    ==
    float(
        lambda025_validation[
            "validation_F1"
        ]
    )

    and

    DRIVE_REGISTRY_PATH.exists()

    and

    DRIVE_POLICY_PATH.exists()
)


STEP_20_LAMBDA_PROTOCOL_VALID = (
    REGISTRY_VALID
)


print("\n[3] Step A20 validation")
print("-" * 78)

print(
    "Lambda candidates              :",
    len(LAMBDA_REGISTRY),
    "/ 4"
)

print(
    "Completed validation configs   :",
    int(
        (
            LAMBDA_REGISTRY[
                "status"
            ]
            ==
            "validation_complete"
        ).sum()
    ),
    "/ 4"
)

print(
    "lambda=0.25 validation F1      :",
    f"{lambda025_validation['validation_F1']:.10f}"
)

print(
    "lambda=0.25 validation FPR     :",
    f"{lambda025_validation['validation_FPR']:.10f}"
)

print(
    "Selection uses test metrics    :",
    False
)

print(
    "Selection uses zero-day metrics:",
    False
)

print(
    "Registry backed up             :",
    DRIVE_REGISTRY_PATH.exists()
)

print(
    "Policy backed up               :",
    DRIVE_POLICY_PATH.exists()
)


print("\n" + "=" * 78)

if REGISTRY_VALID:

    print(
        "✅ STEP A20 PASSED — "
        "lambda_t sensitivity protocol is frozen "
        "before running the remaining candidates."
    )

else:

    print(
        "❌ STEP A20 FAILED — "
        "Do not train another lambda_t configuration."
    )

print("=" * 78)

==============================================================================
STEP A20 — FREEZE LAMBDA_T SENSITIVITY PROTOCOL
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================
Lambda candidates: [0.1, 0.25, 0.5, 1.0]
Seed: 13
Temporal window: 8
SSL epochs: 30
Fine-tuning epochs: 20
Imbalance method: none
Lambda selection metric: development_validation_F1

[1] Loading existing lambda=0.25 validation result
------------------------------------------------------------------------------
Existing lambda: 0.25
Validation threshold: 0.0147513831
Validation F1: 0.9972670927
Validation FPR: 0.3655976676
Held-out DDoS used: False

[2] Creating lambda experiment registry
------------------------------------------------------------------------------

,fold_id,held_out_family,seed,temporal_window,lambda_t,SSL_epochs,fine_tuning_epochs,imbalance_method,status,selected_threshold,validation_F1,validation_FPR,validation_recall,test_metrics_used_for_selection,zero_day_metrics_used_for_selection
0,1,DDoS,13,8,0.10,30,20,none,pending,NaN,NaN,NaN,NaN,False,False
1,1,DDoS,13,8,0.25,30,20,none,validation_complete,0.014751,0.997267,0.365598,0.998311,False,False
2,1,DDoS,13,8,0.50,30,20,none,pending,NaN,NaN,NaN,NaN,False,False
3,1,DDoS,13,8,1.00,30,20,none,pending,NaN,NaN,NaN,NaN,False,False

[3] Step A20 validation
------------------------------------------------------------------------------
Lambda candidates              : 4 / 4
Completed validation configs   : 1 / 4
lambda=0.25 validation F1      : 0.9972670927
lambda=0.25 validation FPR     : 0.3655976676
Selection uses test metrics    : False
Selection uses zero-day metrics: False
Registry backed up             : True
Policy backed up               : True

==============================================================================
✅ STEP A20 PASSED — lambda_t sensitivity protocol is frozen before running the remaining candidates.
==============================================================================

# A21 — SSL pretraining for λₜ = 0.10

In [ ]:
# ======================================================================
# STEP A21
# LAMBDA_T SENSITIVITY — SSL PRETRAINING FOR lambda_t = 0.10
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# FP32
# 30 SSL epochs
#
# NO test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A21 — SSL PRETRAINING | lambda_t = 0.10")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing = [
    name
    for name in required_variables
    if name not in globals()
]

if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")


print("A13 valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A20 protocol valid:", STEP_20_LAMBDA_PROTOCOL_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

print("\n[2] Controlled lambda=0.10 configuration")
print("-" * 78)

SEED = 13

LAMBDA_T = 0.10

EPOCHS = 30

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

TEMPERATURE = 0.20

FEATURE_MASK_PROBABILITY = 0.10

GAUSSIAN_JITTER_STD = 0.01

MAX_GRADIENT_NORM = 5.0


print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Temperature:", TEMPERATURE)
print("Feature masking:", FEATURE_MASK_PROBABILITY)
print("Gaussian jitter:", GAUSSIAN_JITTER_STD)
print("Precision:", "float32")


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — CREATE FRESH MODEL
# ======================================================================

print("\n[3] Creating fresh lambda=0.10 model")
print("-" * 78)


set_all_seeds(SEED)


SSL_MODEL_L010 = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


# ======================================================================
# 5 — SSL PARAMETERS ONLY
# ======================================================================

SSL_PARAMETERS = (

    list(
        SSL_MODEL_L010
        .feature_encoder
        .parameters()
    )

    +

    list(
        SSL_MODEL_L010
        .temporal_encoder
        .parameters()
    )

    +

    list(
        SSL_MODEL_L010
        .projection_head
        .parameters()
    )

    +

    list(
        SSL_MODEL_L010
        .temporal_order_head
        .parameters()
    )
)


ssl_ids = {
    id(p)
    for p in SSL_PARAMETERS
}


classifier_ids = {
    id(p)
    for p in SSL_MODEL_L010
    .classifier_head
    .parameters()
}


CLASSIFIER_INCLUDED = bool(
    ssl_ids
    &
    classifier_ids
)


if CLASSIFIER_INCLUDED:

    raise RuntimeError(
        "Classifier must not be optimized during SSL."
    )


SSL_PARAMETER_COUNT = sum(
    p.numel()
    for p in SSL_PARAMETERS
)


print(
    "SSL parameters:",
    f"{SSL_PARAMETER_COUNT:,}"
)

print(
    "Classifier included:",
    CLASSIFIER_INCLUDED
)


# ======================================================================
# 6 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    SSL_PARAMETERS,

    lr=
        LEARNING_RATE
)


# ======================================================================
# 7 — DETERMINISTIC LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=
            BATCH_SIZE,

        shuffle=
            True,

        num_workers=
            0,

        pin_memory=
            torch.cuda.is_available(),

        drop_last=
            False,

        generator=
            generator
    )


# ======================================================================
# 8 — AUGMENTATION
# ======================================================================

def augment_view(x):

    out = x.clone()


    out = (

        out

        +

        torch.randn_like(
            out
        )
        *
        GAUSSIAN_JITTER_STD
    )


    mask = (

        torch.rand_like(
            out
        )

        <
        FEATURE_MASK_PROBABILITY
    )


    out = out.masked_fill(
        mask,
        0.0
    )


    return out


# ======================================================================
# 9 — NT-XENT
# ======================================================================

def nt_xent_loss(
    z1,
    z2,
    temperature
):

    batch_size = int(
        z1.shape[0]
    )


    if batch_size < 2:

        raise RuntimeError(
            "NT-Xent requires at least 2 samples."
        )


    z = torch.cat(
        [
            z1,
            z2
        ],
        dim=0
    ).float()


    similarity = (

        torch.matmul(
            z,
            z.T
        )

        /

        temperature
    )


    total = (
        2
        *
        batch_size
    )


    identity = torch.eye(

        total,

        dtype=torch.bool,

        device=
            similarity.device
    )


    similarity = similarity.masked_fill(
        identity,
        float("-inf")
    )


    targets = (

        torch.arange(
            total,
            device=
                similarity.device
        )

        +

        batch_size

    ) % total


    return F.cross_entropy(
        similarity,
        targets
    )


# ======================================================================
# 10 — TEMPORAL-ORDER LOSS
# ======================================================================

def temporal_order_loss(
    sequence_states,
    head
):

    hidden = int(
        sequence_states.shape[-1]
    )


    earlier = (

        sequence_states[
            :,
            :-1,
            :
        ]

        .reshape(
            -1,
            hidden
        )
    )


    later = (

        sequence_states[
            :,
            1:,
            :
        ]

        .reshape(
            -1,
            hidden
        )
    )


    forward_logits = head(
        earlier,
        later
    )


    reverse_logits = head(
        later,
        earlier
    )


    forward_targets = torch.ones_like(
        forward_logits
    )


    reverse_targets = torch.zeros_like(
        reverse_logits
    )


    return (

        F.binary_cross_entropy_with_logits(
            forward_logits,
            forward_targets
        )

        +

        F.binary_cross_entropy_with_logits(
            reverse_logits,
            reverse_targets
        )

    ) / 2.0


# ======================================================================
# 11 — OUTPUT DIRECTORIES
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_0p10_fp32"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_0p10_fp32"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "ssl_training_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "ssl_training_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "ssl_training_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "ssl_training_policy.json"
)


# ======================================================================
# 12 — SAVE POLICY
# ======================================================================

POLICY = {

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "epochs":
        EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "temperature":
        TEMPERATURE,

    "feature_mask_probability":
        FEATURE_MASK_PROBABILITY,

    "gaussian_jitter_std":
        GAUSSIAN_JITTER_STD,

    "precision":
        "float32",

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False,

    "held_out_DDoS_used":
        False,

    "test_data_used":
        False,

    "zero_day_data_used":
        False,

    "controlled_against_lambda_0p25":
        True
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 13 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking lambda=0.10 checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Checkpoint lambda mismatch."
        )


    SSL_MODEL_L010.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No lambda=0.10 checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 14 — TRAIN
# ======================================================================

print("\n[5] Starting lambda=0.10 SSL training")
print("-" * 78)


NONFINITE_BATCHES = 0

training_start = time.time()


if START_EPOCH <= EPOCHS:

    for epoch in range(
        START_EPOCH,
        EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        SSL_MODEL_L010.train()


        total_loss_sum = 0.0

        contrastive_loss_sum = 0.0

        order_loss_sum = 0.0

        examples = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            _
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite input at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            view1 = augment_view(
                X
            )


            view2 = augment_view(
                X
            )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            seq1, _, z1 = (
                SSL_MODEL_L010
                .forward_ssl(
                    view1
                )
            )


            seq2, _, z2 = (
                SSL_MODEL_L010
                .forward_ssl(
                    view2
                )
            )


            contrastive = nt_xent_loss(

                z1,

                z2,

                TEMPERATURE
            )


            order1 = temporal_order_loss(

                seq1,

                SSL_MODEL_L010
                .temporal_order_head
            )


            order2 = temporal_order_loss(

                seq2,

                SSL_MODEL_L010
                .temporal_order_head
            )


            order_loss = (

                order1

                +

                order2

            ) / 2.0


            total_loss = (

                contrastive

                +

                LAMBDA_T
                *
                order_loss
            )


            if not bool(
                torch.isfinite(
                    total_loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite loss at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            total_loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    SSL_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            total_loss_sum += (

                float(
                    total_loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            contrastive_loss_sum += (

                float(
                    contrastive
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            order_loss_sum += (

                float(
                    order_loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            examples += (
                batch_size
            )


            if (
                batch_number % 100 == 0

                or

                batch_number
                ==
                len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/{EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| Loss "
                    f"{float(total_loss.detach().cpu()):.4f}"
                )


        mean_total = (
            total_loss_sum
            /
            examples
        )


        mean_contrastive = (
            contrastive_loss_sum
            /
            examples
        )


        mean_order = (
            order_loss_sum
            /
            examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "total_loss":
                mean_total,

            "NT_Xent_loss":
                mean_contrastive,

            "temporal_order_loss":
                mean_order,

            "examples":
                examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            !=
            epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "precision":
                "float32",

            "model_state_dict":
                SSL_MODEL_L010
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| total={mean_total:.6f} "
            f"| NT-Xent={mean_contrastive:.6f} "
            f"| order={mean_order:.6f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "lambda=0.10 already completed 30 epochs."
    )


# ======================================================================
# 15 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 lambda=0.10 SSL epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 16 — FINAL NUMERICAL CHECK
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            p
        ).all()
    )

    for p in SSL_MODEL_L010.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=32,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


SSL_MODEL_L010.eval()


with torch.no_grad():

    seq_check, rep_check, z_check = (

        SSL_MODEL_L010
        .forward_ssl(
            X_check
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        seq_check
    ).all()

    and

    torch.isfinite(
        rep_check
    ).all()

    and

    torch.isfinite(
        z_check
    ).all()
)


NORM_ERROR = float(

    torch.max(

        torch.abs(

            torch.linalg.vector_norm(
                z_check,
                dim=1
            )

            -

            1.0
        )
    )

    .detach()

    .cpu()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Projection norm error:",
    f"{NORM_ERROR:.10e}"
)


# ======================================================================
# 17 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        SSL_MODEL_L010
        .state_dict(),

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "temperature":
        TEMPERATURE,

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False,

    "test_data_used":
        False,

    "zero_day_data_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 18 — FINAL A21 VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A21_VALID = bool(

    COMPLETED_EPOCHS == 30

    and

    not CLASSIFIER_INCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    NORM_ERROR < 1e-5

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_21_LAMBDA_010_SSL_VALID = (
    A21_VALID
)


print("\n[8] Step A21 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Completed SSL epochs           :",
    COMPLETED_EPOCHS,
    "/ 30"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Binary labels used             :",
    False
)

print(
    "Classifier optimized           :",
    CLASSIFIER_INCLUDED
)

print(
    "Held-out DDoS used             :",
    False
)

print(
    "Test data used                 :",
    False
)

print(
    "Zero-day data used             :",
    False
)

print(
    "Final total loss               :",
    f"{float(FINAL_ROW['total_loss']):.6f}"
)

print(
    "Final NT-Xent loss             :",
    f"{float(FINAL_ROW['NT_Xent_loss']):.6f}"
)

print(
    "Final temporal-order loss      :",
    f"{float(FINAL_ROW['temporal_order_loss']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A21_VALID:

    print(
        "✅ STEP A21 PASSED — "
        "lambda_t=0.10 completed 30-epoch "
        "Fold-1 SSL pretraining successfully."
    )

else:

    print(
        "❌ STEP A21 INCOMPLETE — "
        "rerun this same cell to resume "
        "lambda_t=0.10 training."
    )

print("=" * 78)

==============================================================================
STEP A21 — SSL PRETRAINING | lambda_t = 0.10
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 valid: True
A14 valid: True
A20 protocol valid: True
Training windows: 105,577
Device: cuda

[2] Controlled lambda=0.10 configuration
------------------------------------------------------------------------------
lambda_t: 0.1
Seed: 13
Epochs: 30
Batch size: 256
Learning rate: 0.001
Temperature: 0.2
Feature masking: 0.1
Gaussian jitter: 0.01
Precision: float32

[3] Creating fresh lambda=0.10 model
------------------------------------------------------------------------------
SSL parameters: 167,105
Classifier included: False

[4] Checking lambda=0.10 checkpoint
------------------------------------------------------------------------------
No lambda=0.10 checkpoint.
Starting from epoch 1.

[5] Starting lambda=0.10 SSL training
------------------------------------------------------------------------------
Epoch 01/30 | Batch 100/413 | Loss 2.3774
Epoch 01/30 | Batch 200/413 | Loss 2.1961
Epoch 01/30 | Batch 300/413 | Loss 2.2523
Epoch 01/30 | Batch 400/413 | Loss 2.1443
Epoch 01/30 | Batch 413/413 | Loss 1.3575

Epoch 01 complete | total=2.369533 | NT-Xent=2.357379 | order=0.121538 | time=11.0s | checkpoint=Drive
Epoch 02/30 | Batch 100/413 | Loss 2.1146
Epoch 02/30 | Batch 200/413 | Loss 2.0509
Epoch 02/30 | Batch 300/413 | Loss 2.0854
Epoch 02/30 | Batch 400/413 | Loss 2.0198
Epoch 02/30 | Batch 413/413 | Loss 1.2721

Epoch 02 complete | total=2.072538 | NT-Xent=2.072132 | order=0.004064 | time=11.9s | checkpoint=Drive
Epoch 03/30 | Batch 100/413 | Loss 1.9693
Epoch 03/30 | Batch 200/413 | Loss 2.0083
Epoch 03/30 | Batch 300/413 | Loss 1.9616
Epoch 03/30 | Batch 400/413 | Loss 1.9368
Epoch 03/30 | Batch 413/413 | Loss 1.2953

Epoch 03 complete | total=1.998183 | NT-Xent=1.997933 | order=0.002494 | time=8.0s | checkpoint=Drive
Epoch 04/30 | Batch 100/413 | Loss 1.9665
Epoch 04/30 | Batch 200/413 | Loss 1.9615
Epoch 04/30 | Batch 300/413 | Loss 1.9699
Epoch 04/30 | Batch 400/413 | Loss 1.9885
Epoch 04/30 | Batch 413/413 | Loss 1.2100

Epoch 04 complete | total=1.958954 | NT-Xent=1.958794 | order=0.001604 | time=6.1s | checkpoint=Drive
Epoch 05/30 | Batch 100/413 | Loss 1.9855
Epoch 05/30 | Batch 200/413 | Loss 1.9167
Epoch 05/30 | Batch 300/413 | Loss 1.9404
Epoch 05/30 | Batch 400/413 | Loss 1.8802
Epoch 05/30 | Batch 413/413 | Loss 1.2756

Epoch 05 complete | total=1.931798 | NT-Xent=1.931658 | order=0.001406 | time=6.6s | checkpoint=Drive
Epoch 06/30 | Batch 100/413 | Loss 1.9141
Epoch 06/30 | Batch 200/413 | Loss 1.9125
Epoch 06/30 | Batch 300/413 | Loss 1.9054
Epoch 06/30 | Batch 400/413 | Loss 1.8809
Epoch 06/30 | Batch 413/413 | Loss 1.1975

Epoch 06 complete | total=1.913085 | NT-Xent=1.912966 | order=0.001184 | time=6.2s | checkpoint=Drive
Epoch 07/30 | Batch 100/413 | Loss 1.8839
Epoch 07/30 | Batch 200/413 | Loss 1.8806
Epoch 07/30 | Batch 300/413 | Loss 1.8927
Epoch 07/30 | Batch 400/413 | Loss 1.8798
Epoch 07/30 | Batch 413/413 | Loss 1.2117

Epoch 07 complete | total=1.896508 | NT-Xent=1.896403 | order=0.001046 | time=6.5s | checkpoint=Drive
Epoch 08/30 | Batch 100/413 | Loss 1.8834
Epoch 08/30 | Batch 200/413 | Loss 1.8932
Epoch 08/30 | Batch 300/413 | Loss 1.8980
Epoch 08/30 | Batch 400/413 | Loss 1.8568
Epoch 08/30 | Batch 413/413 | Loss 1.1777

Epoch 08 complete | total=1.887679 | NT-Xent=1.887572 | order=0.001069 | time=6.5s | checkpoint=Drive
Epoch 09/30 | Batch 100/413 | Loss 1.8655
Epoch 09/30 | Batch 200/413 | Loss 1.8354
Epoch 09/30 | Batch 300/413 | Loss 1.8263
Epoch 09/30 | Batch 400/413 | Loss 1.8761
Epoch 09/30 | Batch 413/413 | Loss 1.1796

Epoch 09 complete | total=1.873655 | NT-Xent=1.873560 | order=0.000957 | time=6.4s | checkpoint=Drive
Epoch 10/30 | Batch 100/413 | Loss 1.8672
Epoch 10/30 | Batch 200/413 | Loss 1.8692
Epoch 10/30 | Batch 300/413 | Loss 1.8250
Epoch 10/30 | Batch 400/413 | Loss 1.8810
Epoch 10/30 | Batch 413/413 | Loss 1.1294

Epoch 10 complete | total=1.865613 | NT-Xent=1.865526 | order=0.000864 | time=6.7s | checkpoint=Drive
Epoch 11/30 | Batch 100/413 | Loss 1.8824
Epoch 11/30 | Batch 200/413 | Loss 1.8482
Epoch 11/30 | Batch 300/413 | Loss 1.8775
Epoch 11/30 | Batch 400/413 | Loss 1.8629
Epoch 11/30 | Batch 413/413 | Loss 1.1581

Epoch 11 complete | total=1.858597 | NT-Xent=1.858527 | order=0.000701 | time=5.8s | checkpoint=Drive
Epoch 12/30 | Batch 100/413 | Loss 1.8366
Epoch 12/30 | Batch 200/413 | Loss 1.8444
Epoch 12/30 | Batch 300/413 | Loss 1.8592
Epoch 12/30 | Batch 400/413 | Loss 1.8559
Epoch 12/30 | Batch 413/413 | Loss 1.1012

Epoch 12 complete | total=1.850338 | NT-Xent=1.850263 | order=0.000750 | time=6.9s | checkpoint=Drive
Epoch 13/30 | Batch 100/413 | Loss 1.8426
Epoch 13/30 | Batch 200/413 | Loss 1.7969
Epoch 13/30 | Batch 300/413 | Loss 1.8653
Epoch 13/30 | Batch 400/413 | Loss 1.8772
Epoch 13/30 | Batch 413/413 | Loss 1.1161

Epoch 13 complete | total=1.844434 | NT-Xent=1.844369 | order=0.000646 | time=6.0s | checkpoint=Drive
Epoch 14/30 | Batch 100/413 | Loss 1.8227
Epoch 14/30 | Batch 200/413 | Loss 1.8319
Epoch 14/30 | Batch 300/413 | Loss 1.8317
Epoch 14/30 | Batch 400/413 | Loss 1.8212
Epoch 14/30 | Batch 413/413 | Loss 1.1869

Epoch 14 complete | total=1.842088 | NT-Xent=1.842038 | order=0.000504 | time=7.8s | checkpoint=Drive
Epoch 15/30 | Batch 100/413 | Loss 1.8750
Epoch 15/30 | Batch 200/413 | Loss 1.8143
Epoch 15/30 | Batch 300/413 | Loss 1.8448
Epoch 15/30 | Batch 400/413 | Loss 1.7930
Epoch 15/30 | Batch 413/413 | Loss 1.1610

Epoch 15 complete | total=1.833434 | NT-Xent=1.833384 | order=0.000502 | time=5.8s | checkpoint=Drive
Epoch 16/30 | Batch 100/413 | Loss 1.8395
Epoch 16/30 | Batch 200/413 | Loss 1.8441
Epoch 16/30 | Batch 300/413 | Loss 1.7967
Epoch 16/30 | Batch 400/413 | Loss 1.8255
Epoch 16/30 | Batch 413/413 | Loss 1.1626

Epoch 16 complete | total=1.831585 | NT-Xent=1.831540 | order=0.000448 | time=7.1s | checkpoint=Drive
Epoch 17/30 | Batch 100/413 | Loss 1.7849
Epoch 17/30 | Batch 200/413 | Loss 1.8527
Epoch 17/30 | Batch 300/413 | Loss 1.8477
Epoch 17/30 | Batch 400/413 | Loss 1.8247
Epoch 17/30 | Batch 413/413 | Loss 1.1062

Epoch 17 complete | total=1.827354 | NT-Xent=1.827315 | order=0.000389 | time=5.7s | checkpoint=Drive
Epoch 18/30 | Batch 100/413 | Loss 1.8312
Epoch 18/30 | Batch 200/413 | Loss 1.7997
Epoch 18/30 | Batch 300/413 | Loss 1.8071
Epoch 18/30 | Batch 400/413 | Loss 1.8269
Epoch 18/30 | Batch 413/413 | Loss 1.1504

Epoch 18 complete | total=1.823283 | NT-Xent=1.823245 | order=0.000374 | time=6.9s | checkpoint=Drive
Epoch 19/30 | Batch 100/413 | Loss 1.7913
Epoch 19/30 | Batch 200/413 | Loss 1.8194
Epoch 19/30 | Batch 300/413 | Loss 1.8219
Epoch 19/30 | Batch 400/413 | Loss 1.8355
Epoch 19/30 | Batch 413/413 | Loss 1.0891

Epoch 19 complete | total=1.819990 | NT-Xent=1.819955 | order=0.000347 | time=5.8s | checkpoint=Drive
Epoch 20/30 | Batch 100/413 | Loss 1.8473
Epoch 20/30 | Batch 200/413 | Loss 1.7989
Epoch 20/30 | Batch 300/413 | Loss 1.8602
Epoch 20/30 | Batch 400/413 | Loss 1.8356
Epoch 20/30 | Batch 413/413 | Loss 1.0960

Epoch 20 complete | total=1.816805 | NT-Xent=1.816773 | order=0.000323 | time=6.4s | checkpoint=Drive
Epoch 21/30 | Batch 100/413 | Loss 1.7829
Epoch 21/30 | Batch 200/413 | Loss 1.7796
Epoch 21/30 | Batch 300/413 | Loss 1.7960
Epoch 21/30 | Batch 400/413 | Loss 1.8280
Epoch 21/30 | Batch 413/413 | Loss 1.1038

Epoch 21 complete | total=1.812939 | NT-Xent=1.812909 | order=0.000300 | time=6.5s | checkpoint=Drive
Epoch 22/30 | Batch 100/413 | Loss 1.8387
Epoch 22/30 | Batch 200/413 | Loss 1.8219
Epoch 22/30 | Batch 300/413 | Loss 1.8332
Epoch 22/30 | Batch 400/413 | Loss 1.8111
Epoch 22/30 | Batch 413/413 | Loss 1.1049

Epoch 22 complete | total=1.812849 | NT-Xent=1.812823 | order=0.000261 | time=6.0s | checkpoint=Drive
Epoch 23/30 | Batch 100/413 | Loss 1.8395
Epoch 23/30 | Batch 200/413 | Loss 1.8062
Epoch 23/30 | Batch 300/413 | Loss 1.7975
Epoch 23/30 | Batch 400/413 | Loss 1.7850
Epoch 23/30 | Batch 413/413 | Loss 1.0991

Epoch 23 complete | total=1.808563 | NT-Xent=1.808528 | order=0.000344 | time=7.1s | checkpoint=Drive
Epoch 24/30 | Batch 100/413 | Loss 1.8067
Epoch 24/30 | Batch 200/413 | Loss 1.8177
Epoch 24/30 | Batch 300/413 | Loss 1.8259
Epoch 24/30 | Batch 400/413 | Loss 1.8251
Epoch 24/30 | Batch 413/413 | Loss 1.0495

Epoch 24 complete | total=1.807472 | NT-Xent=1.807446 | order=0.000262 | time=5.7s | checkpoint=Drive
Epoch 25/30 | Batch 100/413 | Loss 1.8196
Epoch 25/30 | Batch 200/413 | Loss 1.8247
Epoch 25/30 | Batch 300/413 | Loss 1.8407
Epoch 25/30 | Batch 400/413 | Loss 1.8497
Epoch 25/30 | Batch 413/413 | Loss 1.0916

Epoch 25 complete | total=1.805509 | NT-Xent=1.805473 | order=0.000361 | time=7.0s | checkpoint=Drive
Epoch 26/30 | Batch 100/413 | Loss 1.7772
Epoch 26/30 | Batch 200/413 | Loss 1.8143
Epoch 26/30 | Batch 300/413 | Loss 1.8168
Epoch 26/30 | Batch 400/413 | Loss 1.8039
Epoch 26/30 | Batch 413/413 | Loss 1.1098

Epoch 26 complete | total=1.801634 | NT-Xent=1.801609 | order=0.000253 | time=5.9s | checkpoint=Drive
Epoch 27/30 | Batch 100/413 | Loss 1.8232
Epoch 27/30 | Batch 200/413 | Loss 1.8254
Epoch 27/30 | Batch 300/413 | Loss 1.7753
Epoch 27/30 | Batch 400/413 | Loss 1.8105
Epoch 27/30 | Batch 413/413 | Loss 1.1117

Epoch 27 complete | total=1.801475 | NT-Xent=1.801453 | order=0.000221 | time=6.9s | checkpoint=Drive
Epoch 28/30 | Batch 100/413 | Loss 1.8041
Epoch 28/30 | Batch 200/413 | Loss 1.8201
Epoch 28/30 | Batch 300/413 | Loss 1.8022
Epoch 28/30 | Batch 400/413 | Loss 1.8313
Epoch 28/30 | Batch 413/413 | Loss 1.0508

Epoch 28 complete | total=1.799897 | NT-Xent=1.799869 | order=0.000280 | time=5.8s | checkpoint=Drive
Epoch 29/30 | Batch 100/413 | Loss 1.8056
Epoch 29/30 | Batch 200/413 | Loss 1.7721
Epoch 29/30 | Batch 300/413 | Loss 1.8190
Epoch 29/30 | Batch 400/413 | Loss 1.8250
Epoch 29/30 | Batch 413/413 | Loss 1.1610

Epoch 29 complete | total=1.797166 | NT-Xent=1.797138 | order=0.000282 | time=6.8s | checkpoint=Drive
Epoch 30/30 | Batch 100/413 | Loss 1.7928
Epoch 30/30 | Batch 200/413 | Loss 1.7869
Epoch 30/30 | Batch 300/413 | Loss 1.7833
Epoch 30/30 | Batch 400/413 | Loss 1.7852
Epoch 30/30 | Batch 413/413 | Loss 1.0749

Epoch 30 complete | total=1.794154 | NT-Xent=1.794120 | order=0.000338 | time=6.1s | checkpoint=Drive

[6] Last 5 lambda=0.10 SSL epochs
------------------------------------------------------------------------------

,epoch,lambda_t,total_loss,NT_Xent_loss,temporal_order_loss,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
25,26,0.1,1.801634,1.801609,0.000253,105577,413,1.047843,5.906498
26,27,0.1,1.801475,1.801453,0.000221,105577,413,1.123038,6.907778
27,28,0.1,1.799897,1.799869,0.000280,105577,413,0.949718,5.763329
28,29,0.1,1.797166,1.797138,0.000282,105577,413,1.093769,6.794581
29,30,0.1,1.794154,1.794120,0.000338,105577,413,1.044095,6.135701

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 30
Parameters finite: True
Outputs finite: True
Projection norm error: 1.1920928955e-07

[8] Step A21 validation
------------------------------------------------------------------------------
lambda_t                       : 0.1
Completed SSL epochs           : 30 / 30
Training windows               : 105,577
Binary labels used             : False
Classifier optimized           : False
Held-out DDoS used             : False
Test data used                 : False
Zero-day data used             : False
Final total loss               : 1.794154
Final NT-Xent loss             : 1.794120
Final temporal-order loss      : 0.000338
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A21 PASSED — lambda_t=0.10 completed 30-epoch Fold-1 SSL pretraining successfully.
==============================================================================

# Step A22 — Fine-tune λₜ = 0.10

In [ ]:
# ======================================================================
# STEP A22
# LAMBDA_T SENSITIVITY — SUPERVISED FINE-TUNING FOR lambda_t = 0.10
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# FP32
# 20 fine-tuning epochs
# Imbalance method: none
#
# NO threshold selection here.
# NO known-test access.
# NO benign-test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A22 — SUPERVISED FINE-TUNING | lambda_t = 0.10")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_21_LAMBDA_010_SSL_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]


if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_21_LAMBDA_010_SSL_VALID:
    raise RuntimeError("A21 did not pass.")


print("A13 data valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 architecture valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A20 protocol valid:", STEP_20_LAMBDA_PROTOCOL_VALID)
print("A21 lambda=0.10 SSL valid:", STEP_21_LAMBDA_010_SSL_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

print("\n[2] Controlled fine-tuning configuration")
print("-" * 78)

SEED = 13

LAMBDA_T = 0.10

FINETUNE_EPOCHS = 20

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

MAX_GRADIENT_NORM = 5.0

IMBALANCE_METHOD = "none"

PRECISION = "float32"


print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", FINETUNE_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Precision:", PRECISION)
print("Imbalance method:", IMBALANCE_METHOD)
print("Gradient clipping:", MAX_GRADIENT_NORM)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — LOCATE lambda=0.10 SSL MODEL
# ======================================================================

print("\n[3] Loading lambda=0.10 SSL-pretrained encoder")
print("-" * 78)


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


SSL_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_0p10_fp32"
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


if not SSL_MODEL_PATH.exists():

    raise RuntimeError(
        "lambda=0.10 SSL final model "
        "was not found in Drive."
    )


SSL_PACKAGE = torch.load(
    SSL_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        SSL_PACKAGE[
            "lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Loaded SSL model has wrong lambda_t."
    )


if int(
    SSL_PACKAGE[
        "completed_epochs"
    ]
) != 30:

    raise RuntimeError(
        "lambda=0.10 SSL model did not complete 30 epochs."
    )


if SSL_PACKAGE.get(
    "labels_used_during_SSL"
):

    raise RuntimeError(
        "SSL package indicates labels were used."
    )


print(
    "SSL epochs:",
    SSL_PACKAGE[
        "completed_epochs"
    ]
)

print(
    "SSL lambda_t:",
    SSL_PACKAGE[
        "lambda_t"
    ]
)

print(
    "SSL precision:",
    SSL_PACKAGE[
        "precision"
    ]
)

print(
    "Labels used during SSL:",
    SSL_PACKAGE[
        "labels_used_during_SSL"
    ]
)


# ======================================================================
# 5 — CREATE FINE-TUNING MODEL
# ======================================================================

set_all_seeds(SEED)


FINETUNE_MODEL_L010 = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


FINETUNE_MODEL_L010.load_state_dict(
    SSL_PACKAGE[
        "model_state_dict"
    ],
    strict=True
)


print(
    "lambda=0.10 SSL state loaded:",
    True
)


# ======================================================================
# 6 — REINITIALIZE CLASSIFIER IDENTICALLY TO lambda=0.25 RUN
# ======================================================================

# Same classifier initialization policy used in A16.
# This keeps the lambda comparison controlled.

set_all_seeds(
    SEED + 1000
)


for module in (
    FINETUNE_MODEL_L010
    .classifier_head
    .modules()
):

    if hasattr(
        module,
        "reset_parameters"
    ):

        module.reset_parameters()


print(
    "Classifier freshly initialized:",
    True
)

print(
    "Classifier initialization seed:",
    SEED + 1000
)


# ======================================================================
# 7 — FINE-TUNING PARAMETERS
# ======================================================================

# Train:
#   feature encoder
#   GRU temporal encoder
#   classifier
#
# Do NOT train:
#   projection head
#   temporal-order head

FINETUNE_PARAMETERS = (

    list(
        FINETUNE_MODEL_L010
        .feature_encoder
        .parameters()
    )

    +

    list(
        FINETUNE_MODEL_L010
        .temporal_encoder
        .parameters()
    )

    +

    list(
        FINETUNE_MODEL_L010
        .classifier_head
        .parameters()
    )
)


finetune_ids = {
    id(p)
    for p in FINETUNE_PARAMETERS
}


projection_ids = {
    id(p)
    for p in FINETUNE_MODEL_L010
    .projection_head
    .parameters()
}


order_ids = {
    id(p)
    for p in FINETUNE_MODEL_L010
    .temporal_order_head
    .parameters()
}


PROJECTION_INCLUDED = bool(
    finetune_ids
    &
    projection_ids
)


ORDER_HEAD_INCLUDED = bool(
    finetune_ids
    &
    order_ids
)


if PROJECTION_INCLUDED:

    raise RuntimeError(
        "Projection head must not be fine-tuned."
    )


if ORDER_HEAD_INCLUDED:

    raise RuntimeError(
        "Temporal-order head must not be fine-tuned."
    )


FINETUNE_PARAMETER_COUNT = sum(
    p.numel()
    for p in FINETUNE_PARAMETERS
)


print(
    "Fine-tuned parameters:",
    f"{FINETUNE_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized:",
    ORDER_HEAD_INCLUDED
)


# ======================================================================
# 8 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    FINETUNE_PARAMETERS,

    lr=
        LEARNING_RATE
)


# ======================================================================
# 9 — DETERMINISTIC TRAINING LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=
            BATCH_SIZE,

        shuffle=
            True,

        num_workers=
            0,

        pin_memory=
            torch.cuda.is_available(),

        drop_last=
            False,

        generator=
            generator
    )


# ======================================================================
# 10 — OUTPUT DIRECTORIES
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_0p10_fp32/"
    "imbalance_none"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p10_fp32"
    / "imbalance_none"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "fine_tuning_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "fine_tuning_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fine_tuning_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fine_tuning_policy.json"
)


# ======================================================================
# 11 — SAVE CONTROLLED POLICY
# ======================================================================

POLICY = {

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "initialization":
        "lambda_0p10_FP32_SSL_encoder",

    "epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "classifier_reinitialized":
        True,

    "classifier_initialization_seed":
        SEED + 1000,

    "feature_encoder_trainable":
        True,

    "GRU_encoder_trainable":
        True,

    "classifier_trainable":
        True,

    "projection_head_trainable":
        False,

    "temporal_order_head_trainable":
        False,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False,

    "controlled_against_lambda_0p25":
        True
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 12 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking lambda=0.10 fine-tuning checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Fine-tuning checkpoint lambda mismatch."
        )


    if checkpoint.get(
        "imbalance_method"
    ) != IMBALANCE_METHOD:

        raise RuntimeError(
            "Fine-tuning imbalance method mismatch."
        )


    FINETUNE_MODEL_L010.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No lambda=0.10 fine-tuning checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 13 — SUPERVISED FINE-TUNING
# ======================================================================

print("\n[5] Starting lambda=0.10 supervised fine-tuning")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= FINETUNE_EPOCHS:

    for epoch in range(
        START_EPOCH,
        FINETUNE_EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        FINETUNE_MODEL_L010.train()


        running_loss = 0.0

        total_examples = 0

        correct_at_05 = 0

        predicted_attack_count = 0

        predicted_benign_count = 0

        actual_attack_count = 0

        actual_benign_count = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            y
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            y = y.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite X at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            logits = (
                FINETUNE_MODEL_L010
                .forward_classifier(
                    X
                )
            )


            loss = (
                F.binary_cross_entropy_with_logits(
                    logits,
                    y
                )
            )


            if not bool(
                torch.isfinite(
                    loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite BCE at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    FINETUNE_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            running_loss += (

                float(
                    loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            total_examples += (
                batch_size
            )


            # ------------------------------------------------------
            # Diagnostic only.
            # Threshold 0.5 is NOT selected/frozen here.
            # ------------------------------------------------------

            with torch.no_grad():

                probabilities = torch.sigmoid(
                    logits
                )


                predictions = (
                    probabilities
                    >=
                    0.5
                ).float()


                correct_at_05 += int(

                    (
                        predictions
                        ==
                        y
                    )
                    .sum()
                    .item()
                )


                predicted_attack_count += int(

                    (
                        predictions
                        ==
                        1
                    )
                    .sum()
                    .item()
                )


                predicted_benign_count += int(

                    (
                        predictions
                        ==
                        0
                    )
                    .sum()
                    .item()
                )


                actual_attack_count += int(

                    (
                        y
                        ==
                        1
                    )
                    .sum()
                    .item()
                )


                actual_benign_count += int(

                    (
                        y
                        ==
                        0
                    )
                    .sum()
                    .item()
                )


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/"
                    f"{FINETUNE_EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| BCE "
                    f"{float(loss.detach().cpu()):.6f}"
                )


        mean_loss = (
            running_loss
            /
            total_examples
        )


        diagnostic_accuracy = (
            correct_at_05
            /
            total_examples
        )


        predicted_attack_fraction = (
            predicted_attack_count
            /
            total_examples
        )


        predicted_benign_fraction = (
            predicted_benign_count
            /
            total_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "training_BCE_loss":
                mean_loss,

            "diagnostic_accuracy_at_0p5":
                diagnostic_accuracy,

            "predicted_attack_fraction_at_0p5":
                predicted_attack_fraction,

            "predicted_benign_fraction_at_0p5":
                predicted_benign_fraction,

            "actual_attack_windows":
                actual_attack_count,

            "actual_benign_windows":
                actual_benign_count,

            "examples":
                total_examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            !=
            epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "precision":
                "float32",

            "imbalance_method":
                IMBALANCE_METHOD,

            "model_state_dict":
                FINETUNE_MODEL_L010
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| BCE={mean_loss:.6f} "
            f"| diagnostic_acc@0.5="
            f"{diagnostic_accuracy:.4f} "
            f"| predicted_attack="
            f"{predicted_attack_fraction:.4f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "lambda=0.10 fine-tuning already "
        "contains all 20 epochs."
    )


# ======================================================================
# 14 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 lambda=0.10 fine-tuning epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 15 — NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            p
        ).all()
    )

    for p in FINETUNE_MODEL_L010.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=64,

    shuffle=False,

    num_workers=0
)


X_check, y_check = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


FINETUNE_MODEL_L010.eval()


with torch.no_grad():

    check_logits = (
        FINETUNE_MODEL_L010
        .forward_classifier(
            X_check
        )
    )


    check_probabilities = (
        torch.sigmoid(
            check_logits
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        check_logits
    ).all()

    and

    torch.isfinite(
        check_probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    (
        check_probabilities
        >=
        0
    ).all()

    and

    (
        check_probabilities
        <=
        1
    ).all()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 16 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        FINETUNE_MODEL_L010
        .state_dict(),

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A22_VALID = bool(

    COMPLETED_EPOCHS
    ==
    20

    and

    NONFINITE_BATCHES
    ==
    0

    and

    not PROJECTION_INCLUDED

    and

    not ORDER_HEAD_INCLUDED

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_22_LAMBDA_010_FINETUNE_VALID = (
    A22_VALID
)


print("\n[8] Step A22 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Completed fine-tuning epochs   :",
    COMPLETED_EPOCHS,
    "/ 20"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Projection head optimized      :",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized  :",
    ORDER_HEAD_INCLUDED
)

print(
    "Threshold selected             :",
    False
)

print(
    "Known-test used                :",
    False
)

print(
    "Benign-test used               :",
    False
)

print(
    "Zero-day DDoS used             :",
    False
)

print(
    "Final BCE                      :",
    f"{float(FINAL_ROW['training_BCE_loss']):.6f}"
)

print(
    "Diagnostic accuracy @ 0.5      :",
    f"{float(FINAL_ROW['diagnostic_accuracy_at_0p5']):.6f}"
)

print(
    "Predicted attack fraction      :",
    f"{float(FINAL_ROW['predicted_attack_fraction_at_0p5']):.6f}"
)

print(
    "Predicted benign fraction      :",
    f"{float(FINAL_ROW['predicted_benign_fraction_at_0p5']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A22_VALID:

    print(
        "✅ STEP A22 PASSED — "
        "lambda_t=0.10 completed controlled "
        "20-epoch supervised fine-tuning."
    )

else:

    print(
        "❌ STEP A22 INCOMPLETE — "
        "rerun this same cell to resume."
    )

print("=" * 78)

==============================================================================
STEP A22 — SUPERVISED FINE-TUNING | lambda_t = 0.10
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 data valid: True
A14 architecture valid: True
A20 protocol valid: True
A21 lambda=0.10 SSL valid: True
Training windows: 105,577
Device: cuda

[2] Controlled fine-tuning configuration
------------------------------------------------------------------------------
lambda_t: 0.1
Seed: 13
Epochs: 20
Batch size: 256
Learning rate: 0.001
Precision: float32
Imbalance method: none
Gradient clipping: 5.0

[3] Loading lambda=0.10 SSL-pretrained encoder
------------------------------------------------------------------------------
SSL epochs: 30
SSL lambda_t: 0.1
SSL precision: float32
Labels used during SSL: False
lambda=0.10 SSL state loaded: True
Classifier freshly initialized: True
Classifier initialization seed: 1013
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[4] Checking lambda=0.10 fine-tuning checkpoint
------------------------------------------------------------------------------
No lambda=0.10 fine-tuning checkpoint.
Starting from epoch 1.

[5] Starting lambda=0.10 supervised fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/413 | BCE 0.125460
Epoch 01/20 | Batch 200/413 | BCE 0.159169
Epoch 01/20 | Batch 300/413 | BCE 0.085914
Epoch 01/20 | Batch 400/413 | BCE 0.074785
Epoch 01/20 | Batch 413/413 | BCE 0.084456

Epoch 01 complete | BCE=0.131796 | diagnostic_acc@0.5=0.9449 | predicted_attack=0.9441 | time=7.7s | checkpoint=Drive
Epoch 02/20 | Batch 100/413 | BCE 0.103428
Epoch 02/20 | Batch 200/413 | BCE 0.078008
Epoch 02/20 | Batch 300/413 | BCE 0.078168
Epoch 02/20 | Batch 400/413 | BCE 0.087890
Epoch 02/20 | Batch 413/413 | BCE 0.076872

Epoch 02 complete | BCE=0.074585 | diagnostic_acc@0.5=0.9673 | predicted_attack=0.9273 | time=6.0s | checkpoint=Drive
Epoch 03/20 | Batch 100/413 | BCE 0.066541
Epoch 03/20 | Batch 200/413 | BCE 0.051571
Epoch 03/20 | Batch 300/413 | BCE 0.058412
Epoch 03/20 | Batch 400/413 | BCE 0.040936
Epoch 03/20 | Batch 413/413 | BCE 0.063132

Epoch 03 complete | BCE=0.064290 | diagnostic_acc@0.5=0.9714 | predicted_attack=0.9261 | time=7.3s | checkpoint=Drive
Epoch 04/20 | Batch 100/413 | BCE 0.042509
Epoch 04/20 | Batch 200/413 | BCE 0.071070
Epoch 04/20 | Batch 300/413 | BCE 0.063043
Epoch 04/20 | Batch 400/413 | BCE 0.049742
Epoch 04/20 | Batch 413/413 | BCE 0.079608

Epoch 04 complete | BCE=0.056223 | diagnostic_acc@0.5=0.9752 | predicted_attack=0.9253 | time=5.1s | checkpoint=Drive
Epoch 05/20 | Batch 100/413 | BCE 0.066846
Epoch 05/20 | Batch 200/413 | BCE 0.062066
Epoch 05/20 | Batch 300/413 | BCE 0.087853
Epoch 05/20 | Batch 400/413 | BCE 0.093468
Epoch 05/20 | Batch 413/413 | BCE 0.059018

Epoch 05 complete | BCE=0.050693 | diagnostic_acc@0.5=0.9782 | predicted_attack=0.9242 | time=3.9s | checkpoint=Drive
Epoch 06/20 | Batch 100/413 | BCE 0.015916
Epoch 06/20 | Batch 200/413 | BCE 0.074108
Epoch 06/20 | Batch 300/413 | BCE 0.057437
Epoch 06/20 | Batch 400/413 | BCE 0.041434
Epoch 06/20 | Batch 413/413 | BCE 0.053649

Epoch 06 complete | BCE=0.045034 | diagnostic_acc@0.5=0.9805 | predicted_attack=0.9242 | time=4.3s | checkpoint=Drive
Epoch 07/20 | Batch 100/413 | BCE 0.032837
Epoch 07/20 | Batch 200/413 | BCE 0.033056
Epoch 07/20 | Batch 300/413 | BCE 0.040856
Epoch 07/20 | Batch 400/413 | BCE 0.060746
Epoch 07/20 | Batch 413/413 | BCE 0.040914

Epoch 07 complete | BCE=0.041191 | diagnostic_acc@0.5=0.9823 | predicted_attack=0.9244 | time=4.7s | checkpoint=Drive
Epoch 08/20 | Batch 100/413 | BCE 0.038694
Epoch 08/20 | Batch 200/413 | BCE 0.045826
Epoch 08/20 | Batch 300/413 | BCE 0.022680
Epoch 08/20 | Batch 400/413 | BCE 0.034488
Epoch 08/20 | Batch 413/413 | BCE 0.040799

Epoch 08 complete | BCE=0.036739 | diagnostic_acc@0.5=0.9838 | predicted_attack=0.9243 | time=3.9s | checkpoint=Drive
Epoch 09/20 | Batch 100/413 | BCE 0.025511
Epoch 09/20 | Batch 200/413 | BCE 0.042227
Epoch 09/20 | Batch 300/413 | BCE 0.033132
Epoch 09/20 | Batch 400/413 | BCE 0.038205
Epoch 09/20 | Batch 413/413 | BCE 0.028307

Epoch 09 complete | BCE=0.033410 | diagnostic_acc@0.5=0.9860 | predicted_attack=0.9240 | time=3.9s | checkpoint=Drive
Epoch 10/20 | Batch 100/413 | BCE 0.050669
Epoch 10/20 | Batch 200/413 | BCE 0.030875
Epoch 10/20 | Batch 300/413 | BCE 0.022334
Epoch 10/20 | Batch 400/413 | BCE 0.053757
Epoch 10/20 | Batch 413/413 | BCE 0.032591

Epoch 10 complete | BCE=0.030011 | diagnostic_acc@0.5=0.9870 | predicted_attack=0.9240 | time=4.8s | checkpoint=Drive
Epoch 11/20 | Batch 100/413 | BCE 0.011778
Epoch 11/20 | Batch 200/413 | BCE 0.012235
Epoch 11/20 | Batch 300/413 | BCE 0.018117
Epoch 11/20 | Batch 400/413 | BCE 0.025592
Epoch 11/20 | Batch 413/413 | BCE 0.038417

Epoch 11 complete | BCE=0.026815 | diagnostic_acc@0.5=0.9886 | predicted_attack=0.9241 | time=3.9s | checkpoint=Drive
Epoch 12/20 | Batch 100/413 | BCE 0.030219
Epoch 12/20 | Batch 200/413 | BCE 0.021495
Epoch 12/20 | Batch 300/413 | BCE 0.018197
Epoch 12/20 | Batch 400/413 | BCE 0.021914
Epoch 12/20 | Batch 413/413 | BCE 0.011018

Epoch 12 complete | BCE=0.024483 | diagnostic_acc@0.5=0.9899 | predicted_attack=0.9238 | time=3.9s | checkpoint=Drive
Epoch 13/20 | Batch 100/413 | BCE 0.051514
Epoch 13/20 | Batch 200/413 | BCE 0.037707
Epoch 13/20 | Batch 300/413 | BCE 0.031404
Epoch 13/20 | Batch 400/413 | BCE 0.015596
Epoch 13/20 | Batch 413/413 | BCE 0.006457

Epoch 13 complete | BCE=0.022308 | diagnostic_acc@0.5=0.9903 | predicted_attack=0.9242 | time=4.7s | checkpoint=Drive
Epoch 14/20 | Batch 100/413 | BCE 0.035296
Epoch 14/20 | Batch 200/413 | BCE 0.016134
Epoch 14/20 | Batch 300/413 | BCE 0.016656
Epoch 14/20 | Batch 400/413 | BCE 0.019026
Epoch 14/20 | Batch 413/413 | BCE 0.012975

Epoch 14 complete | BCE=0.019901 | diagnostic_acc@0.5=0.9919 | predicted_attack=0.9242 | time=4.0s | checkpoint=Drive
Epoch 15/20 | Batch 100/413 | BCE 0.017995
Epoch 15/20 | Batch 200/413 | BCE 0.062754
Epoch 15/20 | Batch 300/413 | BCE 0.003515
Epoch 15/20 | Batch 400/413 | BCE 0.019931
Epoch 15/20 | Batch 413/413 | BCE 0.002978

Epoch 15 complete | BCE=0.018763 | diagnostic_acc@0.5=0.9924 | predicted_attack=0.9242 | time=4.1s | checkpoint=Drive
Epoch 16/20 | Batch 100/413 | BCE 0.047786
Epoch 16/20 | Batch 200/413 | BCE 0.007798
Epoch 16/20 | Batch 300/413 | BCE 0.013353
Epoch 16/20 | Batch 400/413 | BCE 0.015111
Epoch 16/20 | Batch 413/413 | BCE 0.034482

Epoch 16 complete | BCE=0.016759 | diagnostic_acc@0.5=0.9928 | predicted_attack=0.9240 | time=4.8s | checkpoint=Drive
Epoch 17/20 | Batch 100/413 | BCE 0.013414
Epoch 17/20 | Batch 200/413 | BCE 0.005081
Epoch 17/20 | Batch 300/413 | BCE 0.013157
Epoch 17/20 | Batch 400/413 | BCE 0.005454
Epoch 17/20 | Batch 413/413 | BCE 0.005061

Epoch 17 complete | BCE=0.015509 | diagnostic_acc@0.5=0.9936 | predicted_attack=0.9240 | time=4.6s | checkpoint=Drive
Epoch 18/20 | Batch 100/413 | BCE 0.002809
Epoch 18/20 | Batch 200/413 | BCE 0.049539
Epoch 18/20 | Batch 300/413 | BCE 0.026195
Epoch 18/20 | Batch 400/413 | BCE 0.012534
Epoch 18/20 | Batch 413/413 | BCE 0.000451

Epoch 18 complete | BCE=0.014220 | diagnostic_acc@0.5=0.9943 | predicted_attack=0.9241 | time=4.1s | checkpoint=Drive
Epoch 19/20 | Batch 100/413 | BCE 0.012437
Epoch 19/20 | Batch 200/413 | BCE 0.009870
Epoch 19/20 | Batch 300/413 | BCE 0.003286
Epoch 19/20 | Batch 400/413 | BCE 0.009734
Epoch 19/20 | Batch 413/413 | BCE 0.012351

Epoch 19 complete | BCE=0.013704 | diagnostic_acc@0.5=0.9943 | predicted_attack=0.9242 | time=5.2s | checkpoint=Drive
Epoch 20/20 | Batch 100/413 | BCE 0.009184
Epoch 20/20 | Batch 200/413 | BCE 0.009204
Epoch 20/20 | Batch 300/413 | BCE 0.015156
Epoch 20/20 | Batch 400/413 | BCE 0.023471
Epoch 20/20 | Batch 413/413 | BCE 0.009828

Epoch 20 complete | BCE=0.011688 | diagnostic_acc@0.5=0.9953 | predicted_attack=0.9239 | time=4.7s | checkpoint=Drive

[6] Last 5 lambda=0.10 fine-tuning epochs
------------------------------------------------------------------------------

,epoch,lambda_t,training_BCE_loss,diagnostic_accuracy_at_0p5,predicted_attack_fraction_at_0p5,predicted_benign_fraction_at_0p5,actual_attack_windows,actual_benign_windows,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
15,16,0.1,0.016759,0.992830,0.923989,0.076011,97571,8006,105577,413,1.056619,4.817141
16,17,0.1,0.015509,0.993616,0.924018,0.075982,97571,8006,105577,413,0.754676,4.589953
17,18,0.1,0.014220,0.994279,0.924055,0.075945,97571,8006,105577,413,0.868316,4.058125
18,19,0.1,0.013704,0.994307,0.924216,0.075784,97571,8006,105577,413,0.772441,5.225256
19,20,0.1,0.011688,0.995349,0.923932,0.076068,97571,8006,105577,413,0.727605,4.681698

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
Parameters finite: True
Outputs finite: True
Probability range valid: True

[8] Step A22 validation
------------------------------------------------------------------------------
lambda_t                       : 0.1
Completed fine-tuning epochs   : 20 / 20
Training windows               : 105,577
Imbalance method               : none
Projection head optimized      : False
Temporal-order head optimized  : False
Threshold selected             : False
Known-test used                : False
Benign-test used               : False
Zero-day DDoS used             : False
Final BCE                      : 0.011688
Diagnostic accuracy @ 0.5      : 0.995349
Predicted attack fraction      : 0.923932
Predicted benign fraction      : 0.076068
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A22 PASSED — lambda_t=0.10 completed controlled 20-epoch supervised fine-tuning.
==============================================================================

# Step A23 — Validate λₜ = 0.10 and update the λ registry

In [ ]:
# ======================================================================
# STEP A23
# LAMBDA_T = 0.10 DEVELOPMENT-VALIDATION EVALUATION
#
# Fold 1: DDoS held out
#
# Uses:
#   development_validation ONLY
#
# Does NOT use:
#   known test
#   benign test
#   zero-day DDoS
#
# After validation:
#   update frozen A20 lambda experiment registry.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    accuracy_score,
    average_precision_score,
    roc_auc_score
)


print("=" * 78)
print("STEP A23 — VALIDATION | lambda_t = 0.10")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_22_LAMBDA_010_FINETUNE_VALID",
    "MOTSSLGRU",
    "DEVICE"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_22_LAMBDA_010_FINETUNE_VALID:
    raise RuntimeError("A22 did not pass.")


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A20 lambda protocol valid:",
    STEP_20_LAMBDA_PROTOCOL_VALID
)

print(
    "A22 lambda=0.10 fine-tuning valid:",
    STEP_22_LAMBDA_010_FINETUNE_VALID
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

LAMBDA_T = 0.10

SEED = 13

EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


print("\n[2] Validation configuration")
print("-" * 78)

print(
    "lambda_t:",
    LAMBDA_T
)

print(
    "Seed:",
    SEED
)

print(
    "Expected validation windows:",
    f"{EXPECTED_WINDOWS:,}"
)

print(
    "Expected benign windows:",
    f"{EXPECTED_BENIGN:,}"
)

print(
    "Expected attack windows:",
    f"{EXPECTED_ATTACK:,}"
)

print(
    "Threshold rule:",
    "maximize development-validation F1"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p10_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


REGISTRY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "fold_01_lambda_t_experiment_registry.csv"
)


POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "fold_01_lambda_t_selection_policy.json"
)


required_paths = [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    MODEL_PATH,
    REGISTRY_PATH,
    POLICY_PATH
]


for path in required_paths:

    if not path.exists():

        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 4 — VERIFY FROZEN A20 POLICY
# ======================================================================

print("\n[3] Verifying frozen A20 protocol")
print("-" * 78)


with open(
    POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:

    lambda_policy = json.load(
        file
    )


if lambda_policy[
    "selection_data"
] != "development_validation_only":

    raise RuntimeError(
        "A20 selection policy mismatch."
    )


if lambda_policy[
    "test_data_allowed_for_lambda_selection"
]:

    raise RuntimeError(
        "A20 incorrectly allows test metrics."
    )


if lambda_policy[
    "zero_day_data_allowed_for_lambda_selection"
]:

    raise RuntimeError(
        "A20 incorrectly allows zero-day metrics."
    )


print(
    "Selection data:",
    lambda_policy[
        "selection_data"
    ]
)

print(
    "Test metrics allowed:",
    False
)

print(
    "Zero-day metrics allowed:",
    False
)


# ======================================================================
# 5 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[4] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        "Expected 75 retained features."
    )


parameter_lookup = (

    parameters

    .set_index(
        "feature"
    )

    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing invalid."
    )


# ======================================================================
# 6 — LOAD VALIDATION MANIFEST
# ======================================================================

print("\n[5] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_validation"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


VALIDATION_WINDOWS_MANIFEST = int(

    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDOS_WINDOWS = int(

    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{VALIDATION_WINDOWS_MANIFEST:,}"
)

print(
    "DDoS validation windows:",
    DDOS_WINDOWS
)


if len(VAL_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if VALIDATION_WINDOWS_MANIFEST != EXPECTED_WINDOWS:

    raise RuntimeError(
        "Validation window mismatch."
    )


if DDOS_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 7 — LOAD lambda=0.10 FINE-TUNED MODEL
# ======================================================================

print("\n[6] Loading lambda=0.10 model")
print("-" * 78)


model_package = torch.load(
    MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        model_package[
            "SSL_lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Fine-tuned model lambda mismatch."
    )


if model_package.get(
    "threshold_selected"
):

    raise RuntimeError(
        "Model package already indicates "
        "threshold selection."
    )


MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


MODEL.eval()


MODEL_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in MODEL.parameters()
)


print(
    "Loaded SSL lambda_t:",
    model_package[
        "SSL_lambda_t"
    ]
)

print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Model finite:",
    MODEL_FINITE
)


if not MODEL_FINITE:

    raise RuntimeError(
        "Model parameters are non-finite."
    )


# ======================================================================
# 8 — FROZEN PREPROCESS FUNCTION
# ======================================================================

def frozen_preprocess(table):

    X = (

        table
        .to_pandas()
        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        rows, cols = np.where(
            bad_mask
        )


        X[
            rows,
            cols
        ] = IMPUTE_VALUES[
            cols
        ]


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite values after preprocessing."
        )


    Z = Z.astype(
        np.float32
    )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 9 — MODEL PREDICTION FUNCTION
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(windows):

    outputs = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start + INFERENCE_BATCH_SIZE,
            len(windows)
        )


        X = torch.from_numpy(

            windows[
                start:stop
            ]

        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                MODEL
                .forward_classifier(
                    X
                )
            )


            probabilities = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                probabilities
            ).all()
        ):

            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        outputs.append(

            probabilities
            .detach()
            .cpu()
            .numpy()
            .astype(
                np.float64
            )
        )


    return np.concatenate(
        outputs
    )


# ======================================================================
# 10 — VALIDATION-ONLY INFERENCE
# ======================================================================

print("\n[7] Running lambda=0.10 validation inference")
print("-" * 78)


prediction_parts = []

TOTAL_WINDOWS = 0

TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    family = str(
        row[
            "research_family"
        ]
    )


    target = int(
        row[
            "binary_target"
        ]
    )


    partition_start = int(
        row[
            "partition_start_row"
        ]
    )


    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    expected_windows = int(
        row[
            "window_count"
        ]
    )


    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )


    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():

        raise RuntimeError(
            f"Missing Parquet: "
            f"{parquet_name}"
        )


    if family == "DDoS":

        raise RuntimeError(
            "DDoS reached validation inference."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probability_parts = []

    source_raw_nonfinite = 0

    absolute_row = 0


    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(

            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row

        group_end = (
            group_start
            +
            row_group_rows
        )


        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(

            row_group_index,

            columns=
                RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(

            local_start,

            local_end
            -
            local_start
        )


        Z, bad_count = (
            frozen_preprocess(
                table
            )
        )


        source_raw_nonfinite += (
            bad_count
        )


        if len(pending) > 0:

            Z = np.concatenate(
                [
                    pending,
                    Z
                ],
                axis=0
            )


        complete_windows = (
            len(Z)
            //
            8
        )


        complete_rows = (
            complete_windows
            *
            8
        )


        if complete_windows > 0:

            windows = (

                Z[
                    :complete_rows
                ]

                .reshape(
                    complete_windows,
                    8,
                    75
                )
            )


            probabilities = (
                predict_windows(
                    windows
                )
            )


            source_probability_parts.append(
                probabilities
            )


        pending = (

            Z[
                complete_rows:
            ]

            .copy()
        )


    if source_probability_parts:

        source_probabilities = (
            np.concatenate(
                source_probability_parts
            )
        )

    else:

        source_probabilities = (
            np.empty(
                0,
                dtype=np.float64
            )
        )


    actual_windows = int(
        len(
            source_probabilities
        )
    )


    actual_tail = int(
        len(
            pending
        )
    )


    source_valid = bool(

        actual_windows
        ==
        expected_windows

        and

        actual_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()
    )


    SOURCE_CHECKS_VALID &= (
        source_valid
    )


    if not source_valid:

        raise RuntimeError(
            f"Validation construction mismatch "
            f"for {source_class}."
        )


    source_frame = pd.DataFrame({

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            target,

        "malicious_probability":
            source_probabilities
    })


    prediction_parts.append(
        source_frame
    )


    TOTAL_WINDOWS += (
        actual_windows
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={actual_windows:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 11 — COMBINE PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (

    VALIDATION_PREDICTIONS[
        "binary_target"
    ]

    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (

    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


COUNTS_VALID = bool(

    len(
        y_true
    )
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDOS_WINDOWS
    ==
    0
)


print("\n[8] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(y_true):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDOS_WINDOWS
)

print(
    "Raw non-finite values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{time.time() - inference_start:.2f} seconds"
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Validation counts invalid."
    )


# ======================================================================
# 12 — THRESHOLD SEARCH
# ======================================================================

print("\n[9] Selecting lambda=0.10 validation threshold")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (

    2.0
    *
    threshold_precision
    *
    threshold_recall

    /

    np.maximum(
        threshold_precision
        +
        threshold_recall,
        1e-15
    )
)


MAX_F1 = float(
    np.max(
        threshold_f1
    )
)


candidate_indices = np.flatnonzero(

    np.isclose(
        threshold_f1,
        MAX_F1,
        rtol=0.0,
        atol=1e-12
    )
)


BEST_INDEX = int(

    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Threshold tie-break:",
    "highest threshold"
)


# ======================================================================
# 13 — VALIDATION METRICS
# ======================================================================

predictions = (

    y_probability

    >=

    SELECTED_THRESHOLD

).astype(
    np.int64
)


tn, fp, fn, tp = (

    confusion_matrix(

        y_true,

        predictions,

        labels=[
            0,
            1
        ]

    ).ravel()
)


VALIDATION_PRECISION = float(

    precision_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_RECALL = float(

    recall_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_F1 = float(

    f1_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_ACCURACY = float(

    accuracy_score(
        y_true,
        predictions
    )
)


VALIDATION_FPR = float(

    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_PR_AUC = float(

    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(

    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[10] lambda=0.10 validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "TP:",
    int(tp)
)

print(
    "TN:",
    int(tn)
)

print(
    "FP:",
    int(fp)
)

print(
    "FN:",
    int(fn)
)

print(
    "Precision:",
    f"{VALIDATION_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "F1:",
    f"{VALIDATION_F1:.10f}"
)

print(
    "FPR:",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{VALIDATION_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 14 — SAVE lambda=0.10 VALIDATION ARTIFACTS
# ======================================================================

OUTPUT_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "lambda_0p10"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    OUTPUT_DIR
    / "development_validation_predictions.csv"
)


THRESHOLD_CURVE_PATH = (
    OUTPUT_DIR
    / "validation_threshold_search.csv"
)


RESULT_PATH = (
    OUTPUT_DIR
    / "validation_result.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = predictions


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


threshold_table = pd.DataFrame({

    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1
})


threshold_table.to_csv(
    THRESHOLD_CURVE_PATH,
    index=False
)


validation_result = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(
                y_true
            )
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        VALIDATION_PRECISION,

    "validation_recall":
        VALIDATION_RECALL,

    "validation_F1":
        VALIDATION_F1,

    "validation_FPR":
        VALIDATION_FPR,

    "validation_accuracy":
        VALIDATION_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "selection_rule":
        "maximize_validation_F1",

    "threshold_tiebreak":
        "highest_threshold",

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    RESULT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        validation_result,
        file,
        indent=4
    )


# ======================================================================
# 15 — UPDATE A20 REGISTRY
# ======================================================================

print("\n[11] Updating frozen lambda registry")
print("-" * 78)


registry = pd.read_csv(
    REGISTRY_PATH
)


lambda_mask = np.isclose(

    registry[
        "lambda_t"
    ].to_numpy(
        dtype=float
    ),

    LAMBDA_T
)


if int(
    lambda_mask.sum()
) != 1:

    raise RuntimeError(
        "Could not uniquely identify lambda=0.10 "
        "in A20 registry."
    )


registry.loc[
    lambda_mask,
    "status"
] = "validation_complete"


registry.loc[
    lambda_mask,
    "selected_threshold"
] = SELECTED_THRESHOLD


registry.loc[
    lambda_mask,
    "validation_F1"
] = VALIDATION_F1


registry.loc[
    lambda_mask,
    "validation_FPR"
] = VALIDATION_FPR


registry.loc[
    lambda_mask,
    "validation_recall"
] = VALIDATION_RECALL


registry.loc[
    lambda_mask,
    "test_metrics_used_for_selection"
] = False


registry.loc[
    lambda_mask,
    "zero_day_metrics_used_for_selection"
] = False


registry.to_csv(
    REGISTRY_PATH,
    index=False
)


print(
    registry[
        [
            "lambda_t",
            "status",
            "selected_threshold",
            "validation_F1",
            "validation_FPR",
            "validation_recall"
        ]
    ]
)


# ======================================================================
# 16 — SAVE LOCAL COPY OF UPDATED REGISTRY
# ======================================================================

LOCAL_REGISTRY_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/lambda_t/"
    "fold_01_DDoS"
)


LOCAL_REGISTRY_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_REGISTRY = (
    LOCAL_REGISTRY_DIR
    / "fold_01_lambda_t_experiment_registry.csv"
)


shutil.copy2(
    REGISTRY_PATH,
    LOCAL_REGISTRY
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

completed_configs = int(

    (
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


lambda_010_row = (

    registry.loc[
        lambda_mask
    ]

    .iloc[0]
)


REGISTRY_UPDATE_VALID = bool(

    completed_configs
    ==
    2

    and

    np.isclose(
        float(
            lambda_010_row[
                "validation_F1"
            ]
        ),
        VALIDATION_F1
    )

    and

    np.isclose(
        float(
            lambda_010_row[
                "validation_FPR"
            ]
        ),
        VALIDATION_FPR
    )
)


ARTIFACTS_VALID = bool(

    PREDICTIONS_PATH.exists()

    and

    THRESHOLD_CURVE_PATH.exists()

    and

    RESULT_PATH.exists()

    and

    REGISTRY_PATH.exists()
)


A23_VALID = bool(

    COUNTS_VALID

    and

    SOURCE_CHECKS_VALID

    and

    MODEL_FINITE

    and

    PREPROCESSING_VALID

    and

    DDOS_WINDOWS == 0

    and

    np.isfinite(
        SELECTED_THRESHOLD
    )

    and

    np.isfinite(
        VALIDATION_F1
    )

    and

    np.isfinite(
        VALIDATION_FPR
    )

    and

    REGISTRY_UPDATE_VALID

    and

    ARTIFACTS_VALID
)


STEP_23_LAMBDA_010_VALIDATION_VALID = (
    A23_VALID
)


print("\n[12] Step A23 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Validation windows             :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDOS_WINDOWS
)

print(
    "Selected threshold             :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Validation F1                  :",
    f"{VALIDATION_F1:.10f}"
)

print(
    "Validation recall              :",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "Validation FPR                 :",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Known-test accessed            :",
    False
)

print(
    "Benign-test accessed           :",
    False
)

print(
    "Zero-day DDoS accessed         :",
    False
)

print(
    "Completed lambda configs       :",
    completed_configs,
    "/ 4"
)

print(
    "Registry updated               :",
    REGISTRY_UPDATE_VALID
)

print(
    "Artifacts saved                :",
    ARTIFACTS_VALID
)


print("\n" + "=" * 78)

if A23_VALID:

    print(
        "✅ STEP A23 PASSED — "
        "lambda_t=0.10 development-validation "
        "result recorded successfully."
    )

else:

    print(
        "❌ STEP A23 FAILED — "
        "do not continue to lambda_t=0.50 yet."
    )

print("=" * 78)

==============================================================================
STEP A23 — VALIDATION | lambda_t = 0.10
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A20 lambda protocol valid: True
A22 lambda=0.10 fine-tuning valid: True
Device: cuda

[2] Validation configuration
------------------------------------------------------------------------------
lambda_t: 0.1
Seed: 13
Expected validation windows: 167,482
Expected benign windows: 1,715
Expected attack windows: 165,767
Threshold rule: maximize development-validation F1

[3] Verifying frozen A20 protocol
------------------------------------------------------------------------------
Selection data: development_validation_only
Test metrics allowed: False
Zero-day metrics allowed: False

[4] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Preprocessing refitted: False

[5] Loading development-validation manifest
------------------------------------------------------------------------------
Validation ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[6] Loading lambda=0.10 model
------------------------------------------------------------------------------
Loaded SSL lambda_t: 0.1
Fine-tuning epochs: 20
Imbalance method: none
Model finite: True

[7] Running lambda=0.10 validation inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[8] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite values imputed: 1,516
All source checks valid: True
Probability min: 0.0000000000
Probability max: 1.0000000000
Inference runtime: 6.25 seconds

[9] Selecting lambda=0.10 validation threshold
------------------------------------------------------------------------------
Threshold candidates: 7,253
Maximum validation F1: 0.9971224105
Selected threshold: 0.0021844069
Max-F1 tie count: 1
Threshold tie-break: highest threshold

[10] lambda=0.10 validation metrics
------------------------------------------------------------------------------
Threshold: 0.0021844069
TP: 165460
TN: 1067
FP: 648
FN: 307
Precision: 0.9960989236
Recall: 0.9981480029
F1: 0.9971224105
FPR: 0.3778425656
Accuracy: 0.9942978947
PR-AUC: 0.9999650787
ROC-AUC: 0.9966645621

[11] Updating frozen lambda registry
------------------------------------------------------------------------------
   lambda_t               status  selected_threshold  validation_F1  \
0      0.10  validation_complete            0.002184       0.997122
1      0.25  validation_complete            0.014751       0.997267
2      0.50              pending                 NaN            NaN
3      1.00              pending                 NaN            NaN

   validation_FPR  validation_recall
0        0.377843           0.998148
1        0.365598           0.998311
2             NaN                NaN
3             NaN                NaN

[12] Step A23 validation
------------------------------------------------------------------------------
lambda_t                       : 0.1
Validation windows             : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
Selected threshold             : 0.0021844069
Validation F1                  : 0.9971224105
Validation recall              : 0.9981480029
Validation FPR                 : 0.3778425656
Known-test accessed            : False
Benign-test accessed           : False
Zero-day DDoS accessed         : False
Completed lambda configs       : 2 / 4
Registry updated               : True
Artifacts saved                : True

==============================================================================
✅ STEP A23 PASSED — lambda_t=0.10 development-validation result recorded successfully.
==============================================================================

# Step A24 — SSL pretraining for λₜ = 0.50

In [ ]:
# ======================================================================
# STEP A24
# LAMBDA_T SENSITIVITY — SSL PRETRAINING FOR lambda_t = 0.50
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# FP32
# 30 SSL epochs
#
# NO test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A24 — SSL PRETRAINING | lambda_t = 0.50")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_23_LAMBDA_010_VALIDATION_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing = [
    name
    for name in required_variables
    if name not in globals()
]

if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )

if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_23_LAMBDA_010_VALIDATION_VALID:
    raise RuntimeError("A23 did not pass.")


print("A13 valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A20 protocol valid:", STEP_20_LAMBDA_PROTOCOL_VALID)
print("A23 lambda=0.10 validation valid:", STEP_23_LAMBDA_010_VALIDATION_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

print("\n[2] Controlled lambda=0.50 configuration")
print("-" * 78)

SEED = 13

LAMBDA_T = 0.50

EPOCHS = 30

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

TEMPERATURE = 0.20

FEATURE_MASK_PROBABILITY = 0.10

GAUSSIAN_JITTER_STD = 0.01

MAX_GRADIENT_NORM = 5.0


print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Temperature:", TEMPERATURE)
print("Feature masking:", FEATURE_MASK_PROBABILITY)
print("Gaussian jitter:", GAUSSIAN_JITTER_STD)
print("Precision:", "float32")


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — CREATE FRESH MODEL
# ======================================================================

print("\n[3] Creating fresh lambda=0.50 model")
print("-" * 78)


set_all_seeds(SEED)


SSL_MODEL_L050 = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


# ======================================================================
# 5 — SSL PARAMETERS ONLY
# ======================================================================

SSL_PARAMETERS = (

    list(
        SSL_MODEL_L050
        .feature_encoder
        .parameters()
    )

    +

    list(
        SSL_MODEL_L050
        .temporal_encoder
        .parameters()
    )

    +

    list(
        SSL_MODEL_L050
        .projection_head
        .parameters()
    )

    +

    list(
        SSL_MODEL_L050
        .temporal_order_head
        .parameters()
    )
)


ssl_ids = {
    id(p)
    for p in SSL_PARAMETERS
}


classifier_ids = {
    id(p)
    for p in SSL_MODEL_L050
    .classifier_head
    .parameters()
}


CLASSIFIER_INCLUDED = bool(
    ssl_ids
    &
    classifier_ids
)


if CLASSIFIER_INCLUDED:
    raise RuntimeError(
        "Classifier must not be optimized during SSL."
    )


SSL_PARAMETER_COUNT = sum(
    p.numel()
    for p in SSL_PARAMETERS
)


print(
    "SSL parameters:",
    f"{SSL_PARAMETER_COUNT:,}"
)

print(
    "Classifier included:",
    CLASSIFIER_INCLUDED
)


# ======================================================================
# 6 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    SSL_PARAMETERS,

    lr=LEARNING_RATE
)


# ======================================================================
# 7 — DETERMINISTIC LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        shuffle=True,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False,

        generator=generator
    )


# ======================================================================
# 8 — AUGMENTATION
# ======================================================================

def augment_view(x):

    out = x.clone()


    out = (

        out

        +

        torch.randn_like(
            out
        )
        *
        GAUSSIAN_JITTER_STD
    )


    mask = (

        torch.rand_like(
            out
        )

        <
        FEATURE_MASK_PROBABILITY
    )


    out = out.masked_fill(
        mask,
        0.0
    )


    return out


# ======================================================================
# 9 — NT-XENT LOSS
# ======================================================================

def nt_xent_loss(
    z1,
    z2,
    temperature
):

    batch_size = int(
        z1.shape[0]
    )


    if batch_size < 2:

        raise RuntimeError(
            "NT-Xent requires at least 2 samples."
        )


    z = torch.cat(
        [
            z1,
            z2
        ],
        dim=0
    ).float()


    similarity = (

        torch.matmul(
            z,
            z.T
        )

        /

        temperature
    )


    total = (
        2
        *
        batch_size
    )


    identity = torch.eye(

        total,

        dtype=torch.bool,

        device=similarity.device
    )


    similarity = similarity.masked_fill(
        identity,
        float("-inf")
    )


    targets = (

        torch.arange(
            total,
            device=similarity.device
        )

        +

        batch_size

    ) % total


    return F.cross_entropy(
        similarity,
        targets
    )


# ======================================================================
# 10 — TEMPORAL-ORDER LOSS
# ======================================================================

def temporal_order_loss(
    sequence_states,
    head
):

    hidden = int(
        sequence_states.shape[-1]
    )


    earlier = (

        sequence_states[
            :,
            :-1,
            :
        ]

        .reshape(
            -1,
            hidden
        )
    )


    later = (

        sequence_states[
            :,
            1:,
            :
        ]

        .reshape(
            -1,
            hidden
        )
    )


    forward_logits = head(
        earlier,
        later
    )


    reverse_logits = head(
        later,
        earlier
    )


    forward_targets = torch.ones_like(
        forward_logits
    )


    reverse_targets = torch.zeros_like(
        reverse_logits
    )


    return (

        F.binary_cross_entropy_with_logits(
            forward_logits,
            forward_targets
        )

        +

        F.binary_cross_entropy_with_logits(
            reverse_logits,
            reverse_targets
        )

    ) / 2.0


# ======================================================================
# 11 — OUTPUT DIRECTORIES
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_0p50_fp32"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_0p50_fp32"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "ssl_training_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "ssl_training_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "ssl_training_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "ssl_training_policy.json"
)


# ======================================================================
# 12 — SAVE POLICY
# ======================================================================

POLICY = {

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "epochs":
        EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "temperature":
        TEMPERATURE,

    "feature_mask_probability":
        FEATURE_MASK_PROBABILITY,

    "gaussian_jitter_std":
        GAUSSIAN_JITTER_STD,

    "precision":
        "float32",

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False,

    "held_out_DDoS_used":
        False,

    "test_data_used":
        False,

    "zero_day_data_used":
        False,

    "controlled_against_other_lambdas":
        True
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 13 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking lambda=0.50 checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Checkpoint lambda mismatch."
        )


    SSL_MODEL_L050.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No lambda=0.50 checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 14 — TRAIN
# ======================================================================

print("\n[5] Starting lambda=0.50 SSL training")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= EPOCHS:

    for epoch in range(
        START_EPOCH,
        EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        SSL_MODEL_L050.train()


        total_loss_sum = 0.0

        contrastive_loss_sum = 0.0

        order_loss_sum = 0.0

        examples = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            _
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite input at "
                    f"epoch {epoch}, batch {batch_number}."
                )


            view1 = augment_view(
                X
            )


            view2 = augment_view(
                X
            )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            seq1, _, z1 = (
                SSL_MODEL_L050
                .forward_ssl(
                    view1
                )
            )


            seq2, _, z2 = (
                SSL_MODEL_L050
                .forward_ssl(
                    view2
                )
            )


            contrastive = nt_xent_loss(

                z1,

                z2,

                TEMPERATURE
            )


            order1 = temporal_order_loss(

                seq1,

                SSL_MODEL_L050
                .temporal_order_head
            )


            order2 = temporal_order_loss(

                seq2,

                SSL_MODEL_L050
                .temporal_order_head
            )


            order_loss = (

                order1

                +

                order2

            ) / 2.0


            total_loss = (

                contrastive

                +

                LAMBDA_T
                *
                order_loss
            )


            if not bool(
                torch.isfinite(
                    total_loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite loss at "
                    f"epoch {epoch}, batch {batch_number}."
                )


            total_loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    SSL_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at "
                    f"epoch {epoch}, batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            total_loss_sum += (

                float(
                    total_loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            contrastive_loss_sum += (

                float(
                    contrastive
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            order_loss_sum += (

                float(
                    order_loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            examples += batch_size


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/{EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| Loss "
                    f"{float(total_loss.detach().cpu()):.4f}"
                )


        mean_total = (
            total_loss_sum
            /
            examples
        )


        mean_contrastive = (
            contrastive_loss_sum
            /
            examples
        )


        mean_order = (
            order_loss_sum
            /
            examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "total_loss":
                mean_total,

            "NT_Xent_loss":
                mean_contrastive,

            "temporal_order_loss":
                mean_order,

            "examples":
                examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            != epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "precision":
                "float32",

            "model_state_dict":
                SSL_MODEL_L050
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| total={mean_total:.6f} "
            f"| NT-Xent={mean_contrastive:.6f} "
            f"| order={mean_order:.6f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "lambda=0.50 already completed 30 epochs."
    )


# ======================================================================
# 15 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 lambda=0.50 SSL epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 16 — FINAL NUMERICAL CHECK
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            p
        ).all()
    )

    for p in SSL_MODEL_L050.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=32,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


SSL_MODEL_L050.eval()


with torch.no_grad():

    seq_check, rep_check, z_check = (

        SSL_MODEL_L050
        .forward_ssl(
            X_check
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        seq_check
    ).all()

    and

    torch.isfinite(
        rep_check
    ).all()

    and

    torch.isfinite(
        z_check
    ).all()
)


NORM_ERROR = float(

    torch.max(

        torch.abs(

            torch.linalg.vector_norm(
                z_check,
                dim=1
            )

            -

            1.0
        )
    )

    .detach()

    .cpu()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Projection norm error:",
    f"{NORM_ERROR:.10e}"
)


# ======================================================================
# 17 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        SSL_MODEL_L050
        .state_dict(),

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "temperature":
        TEMPERATURE,

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False,

    "test_data_used":
        False,

    "zero_day_data_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 18 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A24_VALID = bool(

    COMPLETED_EPOCHS == 30

    and

    not CLASSIFIER_INCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    NORM_ERROR < 1e-5

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_24_LAMBDA_050_SSL_VALID = (
    A24_VALID
)


print("\n[8] Step A24 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Completed SSL epochs           :",
    COMPLETED_EPOCHS,
    "/ 30"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Binary labels used             :",
    False
)

print(
    "Classifier optimized           :",
    CLASSIFIER_INCLUDED
)

print(
    "Held-out DDoS used             :",
    False
)

print(
    "Test data used                 :",
    False
)

print(
    "Zero-day data used             :",
    False
)

print(
    "Final total loss               :",
    f"{float(FINAL_ROW['total_loss']):.6f}"
)

print(
    "Final NT-Xent loss             :",
    f"{float(FINAL_ROW['NT_Xent_loss']):.6f}"
)

print(
    "Final temporal-order loss      :",
    f"{float(FINAL_ROW['temporal_order_loss']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A24_VALID:

    print(
        "✅ STEP A24 PASSED — "
        "lambda_t=0.50 completed 30-epoch "
        "Fold-1 SSL pretraining successfully."
    )

else:

    print(
        "❌ STEP A24 INCOMPLETE — "
        "rerun this same cell to resume "
        "lambda_t=0.50 training."
    )

print("=" * 78)

==============================================================================
STEP A24 — SSL PRETRAINING | lambda_t = 0.50
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 valid: True
A14 valid: True
A20 protocol valid: True
A23 lambda=0.10 validation valid: True
Training windows: 105,577
Device: cuda

[2] Controlled lambda=0.50 configuration
------------------------------------------------------------------------------
lambda_t: 0.5
Seed: 13
Epochs: 30
Batch size: 256
Learning rate: 0.001
Temperature: 0.2
Feature masking: 0.1
Gaussian jitter: 0.01
Precision: float32

[3] Creating fresh lambda=0.50 model
------------------------------------------------------------------------------
SSL parameters: 167,105
Classifier included: False

[4] Checking lambda=0.50 checkpoint
------------------------------------------------------------------------------
No lambda=0.50 checkpoint.
Starting from epoch 1.

[5] Starting lambda=0.50 SSL training
------------------------------------------------------------------------------
Epoch 01/30 | Batch 100/413 | Loss 2.3719
Epoch 01/30 | Batch 200/413 | Loss 2.2099
Epoch 01/30 | Batch 300/413 | Loss 2.2592
Epoch 01/30 | Batch 400/413 | Loss 2.1566
Epoch 01/30 | Batch 413/413 | Loss 1.3717

Epoch 01 complete | total=2.414378 | NT-Xent=2.370527 | order=0.087703 | time=11.8s | checkpoint=Drive
Epoch 02/30 | Batch 100/413 | Loss 2.1312
Epoch 02/30 | Batch 200/413 | Loss 2.0672
Epoch 02/30 | Batch 300/413 | Loss 2.1050
Epoch 02/30 | Batch 400/413 | Loss 2.0338
Epoch 02/30 | Batch 413/413 | Loss 1.2850

Epoch 02 complete | total=2.085696 | NT-Xent=2.085102 | order=0.001188 | time=12.5s | checkpoint=Drive
Epoch 03/30 | Batch 100/413 | Loss 1.9841
Epoch 03/30 | Batch 200/413 | Loss 2.0310
Epoch 03/30 | Batch 300/413 | Loss 1.9773
Epoch 03/30 | Batch 400/413 | Loss 1.9449
Epoch 03/30 | Batch 413/413 | Loss 1.3094

Epoch 03 complete | total=2.010047 | NT-Xent=2.009719 | order=0.000656 | time=6.6s | checkpoint=Drive
Epoch 04/30 | Batch 100/413 | Loss 1.9745
Epoch 04/30 | Batch 200/413 | Loss 1.9728
Epoch 04/30 | Batch 300/413 | Loss 1.9678
Epoch 04/30 | Batch 400/413 | Loss 1.9918
Epoch 04/30 | Batch 413/413 | Loss 1.2076

Epoch 04 complete | total=1.968705 | NT-Xent=1.968471 | order=0.000467 | time=6.9s | checkpoint=Drive
Epoch 05/30 | Batch 100/413 | Loss 1.9922
Epoch 05/30 | Batch 200/413 | Loss 1.9273
Epoch 05/30 | Batch 300/413 | Loss 1.9468
Epoch 05/30 | Batch 400/413 | Loss 1.8852
Epoch 05/30 | Batch 413/413 | Loss 1.2758

Epoch 05 complete | total=1.939262 | NT-Xent=1.939061 | order=0.000402 | time=5.7s | checkpoint=Drive
Epoch 06/30 | Batch 100/413 | Loss 1.9282
Epoch 06/30 | Batch 200/413 | Loss 1.9158
Epoch 06/30 | Batch 300/413 | Loss 1.9050
Epoch 06/30 | Batch 400/413 | Loss 1.8858
Epoch 06/30 | Batch 413/413 | Loss 1.2054

Epoch 06 complete | total=1.919522 | NT-Xent=1.919356 | order=0.000331 | time=6.5s | checkpoint=Drive
Epoch 07/30 | Batch 100/413 | Loss 1.8872
Epoch 07/30 | Batch 200/413 | Loss 1.8929
Epoch 07/30 | Batch 300/413 | Loss 1.9093
Epoch 07/30 | Batch 400/413 | Loss 1.8830
Epoch 07/30 | Batch 413/413 | Loss 1.2105

Epoch 07 complete | total=1.901683 | NT-Xent=1.901526 | order=0.000314 | time=6.3s | checkpoint=Drive
Epoch 08/30 | Batch 100/413 | Loss 1.8829
Epoch 08/30 | Batch 200/413 | Loss 1.8999
Epoch 08/30 | Batch 300/413 | Loss 1.9037
Epoch 08/30 | Batch 400/413 | Loss 1.8650
Epoch 08/30 | Batch 413/413 | Loss 1.1817

Epoch 08 complete | total=1.892444 | NT-Xent=1.892292 | order=0.000303 | time=6.1s | checkpoint=Drive
Epoch 09/30 | Batch 100/413 | Loss 1.8733
Epoch 09/30 | Batch 200/413 | Loss 1.8422
Epoch 09/30 | Batch 300/413 | Loss 1.8395
Epoch 09/30 | Batch 400/413 | Loss 1.8909
Epoch 09/30 | Batch 413/413 | Loss 1.1812

Epoch 09 complete | total=1.879655 | NT-Xent=1.879509 | order=0.000293 | time=6.6s | checkpoint=Drive
Epoch 10/30 | Batch 100/413 | Loss 1.8825
Epoch 10/30 | Batch 200/413 | Loss 1.8754
Epoch 10/30 | Batch 300/413 | Loss 1.8368
Epoch 10/30 | Batch 400/413 | Loss 1.8892
Epoch 10/30 | Batch 413/413 | Loss 1.1311

Epoch 10 complete | total=1.872115 | NT-Xent=1.871978 | order=0.000274 | time=6.0s | checkpoint=Drive
Epoch 11/30 | Batch 100/413 | Loss 1.8924
Epoch 11/30 | Batch 200/413 | Loss 1.8493
Epoch 11/30 | Batch 300/413 | Loss 1.8868
Epoch 11/30 | Batch 400/413 | Loss 1.8668
Epoch 11/30 | Batch 413/413 | Loss 1.1629

Epoch 11 complete | total=1.865088 | NT-Xent=1.864954 | order=0.000269 | time=6.9s | checkpoint=Drive
Epoch 12/30 | Batch 100/413 | Loss 1.8524
Epoch 12/30 | Batch 200/413 | Loss 1.8465
Epoch 12/30 | Batch 300/413 | Loss 1.8648
Epoch 12/30 | Batch 400/413 | Loss 1.8638
Epoch 12/30 | Batch 413/413 | Loss 1.0888

Epoch 12 complete | total=1.856131 | NT-Xent=1.855995 | order=0.000272 | time=5.9s | checkpoint=Drive
Epoch 13/30 | Batch 100/413 | Loss 1.8466
Epoch 13/30 | Batch 200/413 | Loss 1.7961
Epoch 13/30 | Batch 300/413 | Loss 1.8702
Epoch 13/30 | Batch 400/413 | Loss 1.8830
Epoch 13/30 | Batch 413/413 | Loss 1.1213

Epoch 13 complete | total=1.850814 | NT-Xent=1.850689 | order=0.000252 | time=7.7s | checkpoint=Drive
Epoch 14/30 | Batch 100/413 | Loss 1.8293
Epoch 14/30 | Batch 200/413 | Loss 1.8458
Epoch 14/30 | Batch 300/413 | Loss 1.8377
Epoch 14/30 | Batch 400/413 | Loss 1.8162
Epoch 14/30 | Batch 413/413 | Loss 1.1908

Epoch 14 complete | total=1.848369 | NT-Xent=1.848246 | order=0.000246 | time=5.8s | checkpoint=Drive
Epoch 15/30 | Batch 100/413 | Loss 1.8756
Epoch 15/30 | Batch 200/413 | Loss 1.8236
Epoch 15/30 | Batch 300/413 | Loss 1.8359
Epoch 15/30 | Batch 400/413 | Loss 1.8152
Epoch 15/30 | Batch 413/413 | Loss 1.1638

Epoch 15 complete | total=1.839542 | NT-Xent=1.839440 | order=0.000204 | time=7.0s | checkpoint=Drive
Epoch 16/30 | Batch 100/413 | Loss 1.8340
Epoch 16/30 | Batch 200/413 | Loss 1.8497
Epoch 16/30 | Batch 300/413 | Loss 1.7971
Epoch 16/30 | Batch 400/413 | Loss 1.8461
Epoch 16/30 | Batch 413/413 | Loss 1.1681

Epoch 16 complete | total=1.836470 | NT-Xent=1.836355 | order=0.000231 | time=5.9s | checkpoint=Drive
Epoch 17/30 | Batch 100/413 | Loss 1.7947
Epoch 17/30 | Batch 200/413 | Loss 1.8638
Epoch 17/30 | Batch 300/413 | Loss 1.8578
Epoch 17/30 | Batch 400/413 | Loss 1.8275
Epoch 17/30 | Batch 413/413 | Loss 1.1208

Epoch 17 complete | total=1.832962 | NT-Xent=1.832860 | order=0.000205 | time=7.0s | checkpoint=Drive
Epoch 18/30 | Batch 100/413 | Loss 1.8319
Epoch 18/30 | Batch 200/413 | Loss 1.8138
Epoch 18/30 | Batch 300/413 | Loss 1.8173
Epoch 18/30 | Batch 400/413 | Loss 1.8289
Epoch 18/30 | Batch 413/413 | Loss 1.1473

Epoch 18 complete | total=1.828503 | NT-Xent=1.828383 | order=0.000239 | time=5.9s | checkpoint=Drive
Epoch 19/30 | Batch 100/413 | Loss 1.8067
Epoch 19/30 | Batch 200/413 | Loss 1.8303
Epoch 19/30 | Batch 300/413 | Loss 1.8336
Epoch 19/30 | Batch 400/413 | Loss 1.8397
Epoch 19/30 | Batch 413/413 | Loss 1.1070

Epoch 19 complete | total=1.826794 | NT-Xent=1.826709 | order=0.000171 | time=6.5s | checkpoint=Drive
Epoch 20/30 | Batch 100/413 | Loss 1.8399
Epoch 20/30 | Batch 200/413 | Loss 1.8099
Epoch 20/30 | Batch 300/413 | Loss 1.8595
Epoch 20/30 | Batch 400/413 | Loss 1.8467
Epoch 20/30 | Batch 413/413 | Loss 1.0873

Epoch 20 complete | total=1.822843 | NT-Xent=1.822738 | order=0.000210 | time=6.6s | checkpoint=Drive
Epoch 21/30 | Batch 100/413 | Loss 1.7849
Epoch 21/30 | Batch 200/413 | Loss 1.7771
Epoch 21/30 | Batch 300/413 | Loss 1.7985
Epoch 21/30 | Batch 400/413 | Loss 1.8172
Epoch 21/30 | Batch 413/413 | Loss 1.1002

Epoch 21 complete | total=1.817304 | NT-Xent=1.817206 | order=0.000196 | time=6.2s | checkpoint=Drive
Epoch 22/30 | Batch 100/413 | Loss 1.8428
Epoch 22/30 | Batch 200/413 | Loss 1.8221
Epoch 22/30 | Batch 300/413 | Loss 1.8200
Epoch 22/30 | Batch 400/413 | Loss 1.8183
Epoch 22/30 | Batch 413/413 | Loss 1.1130

Epoch 22 complete | total=1.816580 | NT-Xent=1.816486 | order=0.000188 | time=7.0s | checkpoint=Drive
Epoch 23/30 | Batch 100/413 | Loss 1.8646
Epoch 23/30 | Batch 200/413 | Loss 1.8164
Epoch 23/30 | Batch 300/413 | Loss 1.7981
Epoch 23/30 | Batch 400/413 | Loss 1.7897
Epoch 23/30 | Batch 413/413 | Loss 1.1223

Epoch 23 complete | total=1.814561 | NT-Xent=1.814448 | order=0.000226 | time=5.9s | checkpoint=Drive
Epoch 24/30 | Batch 100/413 | Loss 1.8020
Epoch 24/30 | Batch 200/413 | Loss 1.8271
Epoch 24/30 | Batch 300/413 | Loss 1.8268
Epoch 24/30 | Batch 400/413 | Loss 1.8376
Epoch 24/30 | Batch 413/413 | Loss 1.0579

Epoch 24 complete | total=1.811358 | NT-Xent=1.811271 | order=0.000173 | time=7.0s | checkpoint=Drive
Epoch 25/30 | Batch 100/413 | Loss 1.8294
Epoch 25/30 | Batch 200/413 | Loss 1.8157
Epoch 25/30 | Batch 300/413 | Loss 1.8444
Epoch 25/30 | Batch 400/413 | Loss 1.8739
Epoch 25/30 | Batch 413/413 | Loss 1.0891

Epoch 25 complete | total=1.809809 | NT-Xent=1.809724 | order=0.000170 | time=5.9s | checkpoint=Drive
Epoch 26/30 | Batch 100/413 | Loss 1.7865
Epoch 26/30 | Batch 200/413 | Loss 1.8241
Epoch 26/30 | Batch 300/413 | Loss 1.8244
Epoch 26/30 | Batch 400/413 | Loss 1.7948
Epoch 26/30 | Batch 413/413 | Loss 1.1118

Epoch 26 complete | total=1.806036 | NT-Xent=1.805950 | order=0.000171 | time=7.0s | checkpoint=Drive
Epoch 27/30 | Batch 100/413 | Loss 1.8392
Epoch 27/30 | Batch 200/413 | Loss 1.8212
Epoch 27/30 | Batch 300/413 | Loss 1.7652
Epoch 27/30 | Batch 400/413 | Loss 1.8226
Epoch 27/30 | Batch 413/413 | Loss 1.1121

Epoch 27 complete | total=1.805215 | NT-Xent=1.805129 | order=0.000172 | time=5.9s | checkpoint=Drive
Epoch 28/30 | Batch 100/413 | Loss 1.8028
Epoch 28/30 | Batch 200/413 | Loss 1.8270
Epoch 28/30 | Batch 300/413 | Loss 1.8115
Epoch 28/30 | Batch 400/413 | Loss 1.8329
Epoch 28/30 | Batch 413/413 | Loss 1.0608

Epoch 28 complete | total=1.803225 | NT-Xent=1.803147 | order=0.000156 | time=7.1s | checkpoint=Drive
Epoch 29/30 | Batch 100/413 | Loss 1.8087
Epoch 29/30 | Batch 200/413 | Loss 1.7751
Epoch 29/30 | Batch 300/413 | Loss 1.8284
Epoch 29/30 | Batch 400/413 | Loss 1.8291
Epoch 29/30 | Batch 413/413 | Loss 1.1726

Epoch 29 complete | total=1.800909 | NT-Xent=1.800828 | order=0.000161 | time=6.0s | checkpoint=Drive
Epoch 30/30 | Batch 100/413 | Loss 1.7920
Epoch 30/30 | Batch 200/413 | Loss 1.8031
Epoch 30/30 | Batch 300/413 | Loss 1.7785
Epoch 30/30 | Batch 400/413 | Loss 1.7724
Epoch 30/30 | Batch 413/413 | Loss 1.0800

Epoch 30 complete | total=1.798243 | NT-Xent=1.798170 | order=0.000145 | time=7.1s | checkpoint=Drive

[6] Last 5 lambda=0.50 SSL epochs
------------------------------------------------------------------------------

,epoch,lambda_t,total_loss,NT_Xent_loss,temporal_order_loss,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
25,26,0.5,1.806036,1.805950,0.000171,105577,413,1.149675,6.997755
26,27,0.5,1.805215,1.805129,0.000172,105577,413,0.862573,5.883368
27,28,0.5,1.803225,1.803147,0.000156,105577,413,1.037689,7.074841
28,29,0.5,1.800909,1.800828,0.000161,105577,413,1.021901,5.983637
29,30,0.5,1.798243,1.798170,0.000145,105577,413,0.999838,7.053333

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 30
Parameters finite: True
Outputs finite: True
Projection norm error: 5.9604644775e-08

[8] Step A24 validation
------------------------------------------------------------------------------
lambda_t                       : 0.5
Completed SSL epochs           : 30 / 30
Training windows               : 105,577
Binary labels used             : False
Classifier optimized           : False
Held-out DDoS used             : False
Test data used                 : False
Zero-day data used             : False
Final total loss               : 1.798243
Final NT-Xent loss             : 1.798170
Final temporal-order loss      : 0.000145
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A24 PASSED — lambda_t=0.50 completed 30-epoch Fold-1 SSL pretraining successfully.
==============================================================================

# Step A25 — Fine-tune λₜ = 0.50

In [ ]:
# ======================================================================
# STEP A25
# LAMBDA_T SENSITIVITY — SUPERVISED FINE-TUNING FOR lambda_t = 0.50
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# FP32
# 20 fine-tuning epochs
# Imbalance method: none
#
# NO threshold selection here.
# NO known-test access.
# NO benign-test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A25 — SUPERVISED FINE-TUNING | lambda_t = 0.50")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_24_LAMBDA_050_SSL_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing_variables = [
    name
    for name in required_variables
    if name not in globals()
]

if missing_variables:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing_variables)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_24_LAMBDA_050_SSL_VALID:
    raise RuntimeError("A24 did not pass.")


print("A13 data valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 architecture valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A20 protocol valid:", STEP_20_LAMBDA_PROTOCOL_VALID)
print("A24 lambda=0.50 SSL valid:", STEP_24_LAMBDA_050_SSL_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

print("\n[2] Controlled fine-tuning configuration")
print("-" * 78)

SEED = 13

LAMBDA_T = 0.50

FINETUNE_EPOCHS = 20

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

MAX_GRADIENT_NORM = 5.0

IMBALANCE_METHOD = "none"

PRECISION = "float32"


print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", FINETUNE_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Precision:", PRECISION)
print("Imbalance method:", IMBALANCE_METHOD)
print("Gradient clipping:", MAX_GRADIENT_NORM)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — LOCATE lambda=0.50 SSL MODEL
# ======================================================================

print("\n[3] Loading lambda=0.50 SSL-pretrained encoder")
print("-" * 78)


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


SSL_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_0p50_fp32"
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


if not SSL_MODEL_PATH.exists():

    raise RuntimeError(
        "lambda=0.50 SSL final model "
        "was not found in Drive."
    )


SSL_PACKAGE = torch.load(
    SSL_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        SSL_PACKAGE[
            "lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Loaded SSL model has wrong lambda_t."
    )


if int(
    SSL_PACKAGE[
        "completed_epochs"
    ]
) != 30:

    raise RuntimeError(
        "lambda=0.50 SSL model did not complete 30 epochs."
    )


if SSL_PACKAGE.get(
    "labels_used_during_SSL"
):

    raise RuntimeError(
        "SSL package indicates labels were used."
    )


print(
    "SSL epochs:",
    SSL_PACKAGE[
        "completed_epochs"
    ]
)

print(
    "SSL lambda_t:",
    SSL_PACKAGE[
        "lambda_t"
    ]
)

print(
    "SSL precision:",
    SSL_PACKAGE[
        "precision"
    ]
)

print(
    "Labels used during SSL:",
    SSL_PACKAGE[
        "labels_used_during_SSL"
    ]
)


# ======================================================================
# 5 — CREATE FINE-TUNING MODEL
# ======================================================================

set_all_seeds(SEED)


FINETUNE_MODEL_L050 = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


FINETUNE_MODEL_L050.load_state_dict(
    SSL_PACKAGE[
        "model_state_dict"
    ],
    strict=True
)


print(
    "lambda=0.50 SSL state loaded:",
    True
)


# ======================================================================
# 6 — REINITIALIZE CLASSIFIER IDENTICALLY
# ======================================================================

set_all_seeds(
    SEED + 1000
)


for module in (
    FINETUNE_MODEL_L050
    .classifier_head
    .modules()
):

    if hasattr(
        module,
        "reset_parameters"
    ):

        module.reset_parameters()


print(
    "Classifier freshly initialized:",
    True
)

print(
    "Classifier initialization seed:",
    SEED + 1000
)


# ======================================================================
# 7 — FINE-TUNING PARAMETERS
# ======================================================================

FINETUNE_PARAMETERS = (

    list(
        FINETUNE_MODEL_L050
        .feature_encoder
        .parameters()
    )

    +

    list(
        FINETUNE_MODEL_L050
        .temporal_encoder
        .parameters()
    )

    +

    list(
        FINETUNE_MODEL_L050
        .classifier_head
        .parameters()
    )
)


finetune_ids = {
    id(p)
    for p in FINETUNE_PARAMETERS
}


projection_ids = {
    id(p)
    for p in FINETUNE_MODEL_L050
    .projection_head
    .parameters()
}


order_ids = {
    id(p)
    for p in FINETUNE_MODEL_L050
    .temporal_order_head
    .parameters()
}


PROJECTION_INCLUDED = bool(
    finetune_ids
    &
    projection_ids
)


ORDER_HEAD_INCLUDED = bool(
    finetune_ids
    &
    order_ids
)


if PROJECTION_INCLUDED:

    raise RuntimeError(
        "Projection head must not be fine-tuned."
    )


if ORDER_HEAD_INCLUDED:

    raise RuntimeError(
        "Temporal-order head must not be fine-tuned."
    )


FINETUNE_PARAMETER_COUNT = sum(
    p.numel()
    for p in FINETUNE_PARAMETERS
)


print(
    "Fine-tuned parameters:",
    f"{FINETUNE_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized:",
    ORDER_HEAD_INCLUDED
)


# ======================================================================
# 8 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    FINETUNE_PARAMETERS,

    lr=LEARNING_RATE
)


# ======================================================================
# 9 — DETERMINISTIC TRAINING LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        shuffle=True,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False,

        generator=generator
    )


# ======================================================================
# 10 — OUTPUT DIRECTORIES
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_0p50_fp32/"
    "imbalance_none"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p50_fp32"
    / "imbalance_none"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "fine_tuning_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "fine_tuning_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fine_tuning_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fine_tuning_policy.json"
)


# ======================================================================
# 11 — SAVE CONTROLLED POLICY
# ======================================================================

POLICY = {

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "initialization":
        "lambda_0p50_FP32_SSL_encoder",

    "epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "classifier_reinitialized":
        True,

    "classifier_initialization_seed":
        SEED + 1000,

    "feature_encoder_trainable":
        True,

    "GRU_encoder_trainable":
        True,

    "classifier_trainable":
        True,

    "projection_head_trainable":
        False,

    "temporal_order_head_trainable":
        False,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False,

    "controlled_against_other_lambdas":
        True
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 12 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking lambda=0.50 fine-tuning checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Fine-tuning checkpoint lambda mismatch."
        )


    if checkpoint.get(
        "imbalance_method"
    ) != IMBALANCE_METHOD:

        raise RuntimeError(
            "Fine-tuning imbalance method mismatch."
        )


    FINETUNE_MODEL_L050.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No lambda=0.50 fine-tuning checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 13 — SUPERVISED FINE-TUNING
# ======================================================================

print("\n[5] Starting lambda=0.50 supervised fine-tuning")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= FINETUNE_EPOCHS:

    for epoch in range(
        START_EPOCH,
        FINETUNE_EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        FINETUNE_MODEL_L050.train()


        running_loss = 0.0

        total_examples = 0

        correct_at_05 = 0

        predicted_attack_count = 0

        predicted_benign_count = 0

        actual_attack_count = 0

        actual_benign_count = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            y
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            y = y.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite X at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            logits = (
                FINETUNE_MODEL_L050
                .forward_classifier(
                    X
                )
            )


            loss = (
                F.binary_cross_entropy_with_logits(
                    logits,
                    y
                )
            )


            if not bool(
                torch.isfinite(
                    loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite BCE at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    FINETUNE_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            running_loss += (

                float(
                    loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            total_examples += batch_size


            # Diagnostic only; not final threshold.
            with torch.no_grad():

                probabilities = torch.sigmoid(
                    logits
                )


                predictions = (
                    probabilities
                    >=
                    0.5
                ).float()


                correct_at_05 += int(

                    (
                        predictions
                        ==
                        y
                    )
                    .sum()
                    .item()
                )


                predicted_attack_count += int(

                    (
                        predictions
                        ==
                        1
                    )
                    .sum()
                    .item()
                )


                predicted_benign_count += int(

                    (
                        predictions
                        ==
                        0
                    )
                    .sum()
                    .item()
                )


                actual_attack_count += int(

                    (
                        y
                        ==
                        1
                    )
                    .sum()
                    .item()
                )


                actual_benign_count += int(

                    (
                        y
                        ==
                        0
                    )
                    .sum()
                    .item()
                )


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/"
                    f"{FINETUNE_EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| BCE "
                    f"{float(loss.detach().cpu()):.6f}"
                )


        mean_loss = (
            running_loss
            /
            total_examples
        )


        diagnostic_accuracy = (
            correct_at_05
            /
            total_examples
        )


        predicted_attack_fraction = (
            predicted_attack_count
            /
            total_examples
        )


        predicted_benign_fraction = (
            predicted_benign_count
            /
            total_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "training_BCE_loss":
                mean_loss,

            "diagnostic_accuracy_at_0p5":
                diagnostic_accuracy,

            "predicted_attack_fraction_at_0p5":
                predicted_attack_fraction,

            "predicted_benign_fraction_at_0p5":
                predicted_benign_fraction,

            "actual_attack_windows":
                actual_attack_count,

            "actual_benign_windows":
                actual_benign_count,

            "examples":
                total_examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            !=
            epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "precision":
                "float32",

            "imbalance_method":
                IMBALANCE_METHOD,

            "model_state_dict":
                FINETUNE_MODEL_L050
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| BCE={mean_loss:.6f} "
            f"| diagnostic_acc@0.5="
            f"{diagnostic_accuracy:.4f} "
            f"| predicted_attack="
            f"{predicted_attack_fraction:.4f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "lambda=0.50 fine-tuning already "
        "contains all 20 epochs."
    )


# ======================================================================
# 14 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 lambda=0.50 fine-tuning epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 15 — NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            p
        ).all()
    )

    for p in FINETUNE_MODEL_L050.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=64,

    shuffle=False,

    num_workers=0
)


X_check, y_check = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


FINETUNE_MODEL_L050.eval()


with torch.no_grad():

    check_logits = (
        FINETUNE_MODEL_L050
        .forward_classifier(
            X_check
        )
    )


    check_probabilities = (
        torch.sigmoid(
            check_logits
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        check_logits
    ).all()

    and

    torch.isfinite(
        check_probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    (
        check_probabilities
        >=
        0
    ).all()

    and

    (
        check_probabilities
        <=
        1
    ).all()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 16 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        FINETUNE_MODEL_L050
        .state_dict(),

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A25_VALID = bool(

    COMPLETED_EPOCHS
    ==
    20

    and

    NONFINITE_BATCHES
    ==
    0

    and

    not PROJECTION_INCLUDED

    and

    not ORDER_HEAD_INCLUDED

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_25_LAMBDA_050_FINETUNE_VALID = (
    A25_VALID
)


print("\n[8] Step A25 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Completed fine-tuning epochs   :",
    COMPLETED_EPOCHS,
    "/ 20"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Projection head optimized      :",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized  :",
    ORDER_HEAD_INCLUDED
)

print(
    "Threshold selected             :",
    False
)

print(
    "Known-test used                :",
    False
)

print(
    "Benign-test used               :",
    False
)

print(
    "Zero-day DDoS used             :",
    False
)

print(
    "Final BCE                      :",
    f"{float(FINAL_ROW['training_BCE_loss']):.6f}"
)

print(
    "Diagnostic accuracy @ 0.5      :",
    f"{float(FINAL_ROW['diagnostic_accuracy_at_0p5']):.6f}"
)

print(
    "Predicted attack fraction      :",
    f"{float(FINAL_ROW['predicted_attack_fraction_at_0p5']):.6f}"
)

print(
    "Predicted benign fraction      :",
    f"{float(FINAL_ROW['predicted_benign_fraction_at_0p5']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A25_VALID:

    print(
        "✅ STEP A25 PASSED — "
        "lambda_t=0.50 completed controlled "
        "20-epoch supervised fine-tuning."
    )

else:

    print(
        "❌ STEP A25 INCOMPLETE — "
        "rerun this same cell to resume."
    )

print("=" * 78)

==============================================================================
STEP A25 — SUPERVISED FINE-TUNING | lambda_t = 0.50
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 data valid: True
A14 architecture valid: True
A20 protocol valid: True
A24 lambda=0.50 SSL valid: True
Training windows: 105,577
Device: cuda

[2] Controlled fine-tuning configuration
------------------------------------------------------------------------------
lambda_t: 0.5
Seed: 13
Epochs: 20
Batch size: 256
Learning rate: 0.001
Precision: float32
Imbalance method: none
Gradient clipping: 5.0

[3] Loading lambda=0.50 SSL-pretrained encoder
------------------------------------------------------------------------------
SSL epochs: 30
SSL lambda_t: 0.5
SSL precision: float32
Labels used during SSL: False
lambda=0.50 SSL state loaded: True
Classifier freshly initialized: True
Classifier initialization seed: 1013
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[4] Checking lambda=0.50 fine-tuning checkpoint
------------------------------------------------------------------------------
No lambda=0.50 fine-tuning checkpoint.
Starting from epoch 1.

[5] Starting lambda=0.50 supervised fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/413 | BCE 0.134295
Epoch 01/20 | Batch 200/413 | BCE 0.159422
Epoch 01/20 | Batch 300/413 | BCE 0.085890
Epoch 01/20 | Batch 400/413 | BCE 0.084299
Epoch 01/20 | Batch 413/413 | BCE 0.098368

Epoch 01 complete | BCE=0.130021 | diagnostic_acc@0.5=0.9452 | predicted_attack=0.9426 | time=6.8s | checkpoint=Drive
Epoch 02/20 | Batch 100/413 | BCE 0.098688
Epoch 02/20 | Batch 200/413 | BCE 0.071605
Epoch 02/20 | Batch 300/413 | BCE 0.080599
Epoch 02/20 | Batch 400/413 | BCE 0.079287
Epoch 02/20 | Batch 413/413 | BCE 0.084808

Epoch 02 complete | BCE=0.074810 | diagnostic_acc@0.5=0.9665 | predicted_attack=0.9271 | time=7.7s | checkpoint=Drive
Epoch 03/20 | Batch 100/413 | BCE 0.066941
Epoch 03/20 | Batch 200/413 | BCE 0.054314
Epoch 03/20 | Batch 300/413 | BCE 0.056075
Epoch 03/20 | Batch 400/413 | BCE 0.047379
Epoch 03/20 | Batch 413/413 | BCE 0.069931

Epoch 03 complete | BCE=0.063704 | diagnostic_acc@0.5=0.9716 | predicted_attack=0.9261 | time=6.9s | checkpoint=Drive
Epoch 04/20 | Batch 100/413 | BCE 0.046576
Epoch 04/20 | Batch 200/413 | BCE 0.062263
Epoch 04/20 | Batch 300/413 | BCE 0.053087
Epoch 04/20 | Batch 400/413 | BCE 0.056521
Epoch 04/20 | Batch 413/413 | BCE 0.102371

Epoch 04 complete | BCE=0.056888 | diagnostic_acc@0.5=0.9755 | predicted_attack=0.9252 | time=7.7s | checkpoint=Drive
Epoch 05/20 | Batch 100/413 | BCE 0.055924
Epoch 05/20 | Batch 200/413 | BCE 0.041715
Epoch 05/20 | Batch 300/413 | BCE 0.086777
Epoch 05/20 | Batch 400/413 | BCE 0.087200
Epoch 05/20 | Batch 413/413 | BCE 0.050438

Epoch 05 complete | BCE=0.049694 | diagnostic_acc@0.5=0.9784 | predicted_attack=0.9244 | time=4.7s | checkpoint=Drive
Epoch 06/20 | Batch 100/413 | BCE 0.019143
Epoch 06/20 | Batch 200/413 | BCE 0.062820
Epoch 06/20 | Batch 300/413 | BCE 0.041044
Epoch 06/20 | Batch 400/413 | BCE 0.040543
Epoch 06/20 | Batch 413/413 | BCE 0.046680

Epoch 06 complete | BCE=0.045437 | diagnostic_acc@0.5=0.9805 | predicted_attack=0.9245 | time=3.9s | checkpoint=Drive
Epoch 07/20 | Batch 100/413 | BCE 0.041701
Epoch 07/20 | Batch 200/413 | BCE 0.059285
Epoch 07/20 | Batch 300/413 | BCE 0.025227
Epoch 07/20 | Batch 400/413 | BCE 0.076406
Epoch 07/20 | Batch 413/413 | BCE 0.031146

Epoch 07 complete | BCE=0.041798 | diagnostic_acc@0.5=0.9822 | predicted_attack=0.9245 | time=4.1s | checkpoint=Drive
Epoch 08/20 | Batch 100/413 | BCE 0.031931
Epoch 08/20 | Batch 200/413 | BCE 0.059390
Epoch 08/20 | Batch 300/413 | BCE 0.034955
Epoch 08/20 | Batch 400/413 | BCE 0.044715
Epoch 08/20 | Batch 413/413 | BCE 0.059375

Epoch 08 complete | BCE=0.037158 | diagnostic_acc@0.5=0.9841 | predicted_attack=0.9244 | time=4.8s | checkpoint=Drive
Epoch 09/20 | Batch 100/413 | BCE 0.014885
Epoch 09/20 | Batch 200/413 | BCE 0.024707
Epoch 09/20 | Batch 300/413 | BCE 0.021521
Epoch 09/20 | Batch 400/413 | BCE 0.035360
Epoch 09/20 | Batch 413/413 | BCE 0.037795

Epoch 09 complete | BCE=0.033209 | diagnostic_acc@0.5=0.9857 | predicted_attack=0.9241 | time=3.9s | checkpoint=Drive
Epoch 10/20 | Batch 100/413 | BCE 0.037087
Epoch 10/20 | Batch 200/413 | BCE 0.034124
Epoch 10/20 | Batch 300/413 | BCE 0.011620
Epoch 10/20 | Batch 400/413 | BCE 0.045438
Epoch 10/20 | Batch 413/413 | BCE 0.029936

Epoch 10 complete | BCE=0.030556 | diagnostic_acc@0.5=0.9872 | predicted_attack=0.9243 | time=3.9s | checkpoint=Drive
Epoch 11/20 | Batch 100/413 | BCE 0.007499
Epoch 11/20 | Batch 200/413 | BCE 0.032894
Epoch 11/20 | Batch 300/413 | BCE 0.031646
Epoch 11/20 | Batch 400/413 | BCE 0.015547
Epoch 11/20 | Batch 413/413 | BCE 0.033293

Epoch 11 complete | BCE=0.026773 | diagnostic_acc@0.5=0.9888 | predicted_attack=0.9242 | time=4.9s | checkpoint=Drive
Epoch 12/20 | Batch 100/413 | BCE 0.033162
Epoch 12/20 | Batch 200/413 | BCE 0.016369
Epoch 12/20 | Batch 300/413 | BCE 0.025882
Epoch 12/20 | Batch 400/413 | BCE 0.015954
Epoch 12/20 | Batch 413/413 | BCE 0.012583

Epoch 12 complete | BCE=0.024720 | diagnostic_acc@0.5=0.9897 | predicted_attack=0.9239 | time=3.9s | checkpoint=Drive
Epoch 13/20 | Batch 100/413 | BCE 0.055469
Epoch 13/20 | Batch 200/413 | BCE 0.027064
Epoch 13/20 | Batch 300/413 | BCE 0.027189
Epoch 13/20 | Batch 400/413 | BCE 0.022024
Epoch 13/20 | Batch 413/413 | BCE 0.015325

Epoch 13 complete | BCE=0.023198 | diagnostic_acc@0.5=0.9901 | predicted_attack=0.9241 | time=3.9s | checkpoint=Drive
Epoch 14/20 | Batch 100/413 | BCE 0.035575
Epoch 14/20 | Batch 200/413 | BCE 0.006671
Epoch 14/20 | Batch 300/413 | BCE 0.045927
Epoch 14/20 | Batch 400/413 | BCE 0.018206
Epoch 14/20 | Batch 413/413 | BCE 0.019448

Epoch 14 complete | BCE=0.019747 | diagnostic_acc@0.5=0.9919 | predicted_attack=0.9238 | time=4.5s | checkpoint=Drive
Epoch 15/20 | Batch 100/413 | BCE 0.012062
Epoch 15/20 | Batch 200/413 | BCE 0.016709
Epoch 15/20 | Batch 300/413 | BCE 0.012140
Epoch 15/20 | Batch 400/413 | BCE 0.025712
Epoch 15/20 | Batch 413/413 | BCE 0.026060

Epoch 15 complete | BCE=0.019201 | diagnostic_acc@0.5=0.9922 | predicted_attack=0.9238 | time=4.3s | checkpoint=Drive
Epoch 16/20 | Batch 100/413 | BCE 0.022313
Epoch 16/20 | Batch 200/413 | BCE 0.012665
Epoch 16/20 | Batch 300/413 | BCE 0.012104
Epoch 16/20 | Batch 400/413 | BCE 0.033949
Epoch 16/20 | Batch 413/413 | BCE 0.005115

Epoch 16 complete | BCE=0.018259 | diagnostic_acc@0.5=0.9925 | predicted_attack=0.9239 | time=3.9s | checkpoint=Drive
Epoch 17/20 | Batch 100/413 | BCE 0.024203
Epoch 17/20 | Batch 200/413 | BCE 0.004665
Epoch 17/20 | Batch 300/413 | BCE 0.019479
Epoch 17/20 | Batch 400/413 | BCE 0.022491
Epoch 17/20 | Batch 413/413 | BCE 0.011045

Epoch 17 complete | BCE=0.016108 | diagnostic_acc@0.5=0.9931 | predicted_attack=0.9240 | time=4.1s | checkpoint=Drive
Epoch 18/20 | Batch 100/413 | BCE 0.040528
Epoch 18/20 | Batch 200/413 | BCE 0.020697
Epoch 18/20 | Batch 300/413 | BCE 0.007871
Epoch 18/20 | Batch 400/413 | BCE 0.016932
Epoch 18/20 | Batch 413/413 | BCE 0.001606

Epoch 18 complete | BCE=0.015469 | diagnostic_acc@0.5=0.9934 | predicted_attack=0.9244 | time=4.7s | checkpoint=Drive
Epoch 19/20 | Batch 100/413 | BCE 0.019769
Epoch 19/20 | Batch 200/413 | BCE 0.007690
Epoch 19/20 | Batch 300/413 | BCE 0.014168
Epoch 19/20 | Batch 400/413 | BCE 0.005485
Epoch 19/20 | Batch 413/413 | BCE 0.020197

Epoch 19 complete | BCE=0.013440 | diagnostic_acc@0.5=0.9944 | predicted_attack=0.9242 | time=3.9s | checkpoint=Drive
Epoch 20/20 | Batch 100/413 | BCE 0.030549
Epoch 20/20 | Batch 200/413 | BCE 0.023204
Epoch 20/20 | Batch 300/413 | BCE 0.005762
Epoch 20/20 | Batch 400/413 | BCE 0.003880
Epoch 20/20 | Batch 413/413 | BCE 0.003628

Epoch 20 complete | BCE=0.013386 | diagnostic_acc@0.5=0.9948 | predicted_attack=0.9240 | time=3.9s | checkpoint=Drive

[6] Last 5 lambda=0.50 fine-tuning epochs
------------------------------------------------------------------------------

,epoch,lambda_t,training_BCE_loss,diagnostic_accuracy_at_0p5,predicted_attack_fraction_at_0p5,predicted_benign_fraction_at_0p5,actual_attack_windows,actual_benign_windows,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
15,16,0.5,0.018259,0.992470,0.923932,0.076068,97571,8006,105577,413,0.918588,3.876359
16,17,0.5,0.016108,0.993142,0.924036,0.075964,97571,8006,105577,413,0.934927,4.092394
17,18,0.5,0.015469,0.993446,0.924359,0.075641,97571,8006,105577,413,0.884309,4.669276
18,19,0.5,0.013440,0.994440,0.924179,0.075821,97571,8006,105577,413,0.888886,3.915280
19,20,0.5,0.013386,0.994800,0.924008,0.075992,97571,8006,105577,413,1.058724,3.897762

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
Parameters finite: True
Outputs finite: True
Probability range valid: True

[8] Step A25 validation
------------------------------------------------------------------------------
lambda_t                       : 0.5
Completed fine-tuning epochs   : 20 / 20
Training windows               : 105,577
Imbalance method               : none
Projection head optimized      : False
Temporal-order head optimized  : False
Threshold selected             : False
Known-test used                : False
Benign-test used               : False
Zero-day DDoS used             : False
Final BCE                      : 0.013386
Diagnostic accuracy @ 0.5      : 0.994800
Predicted attack fraction      : 0.924008
Predicted benign fraction      : 0.075992
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A25 PASSED — lambda_t=0.50 completed controlled 20-epoch supervised fine-tuning.
==============================================================================

# Step A26 — Validate λₜ = 0.50

In [ ]:
# ======================================================================
# STEP A26
# LAMBDA_T = 0.50 DEVELOPMENT-VALIDATION EVALUATION
#
# Fold 1: DDoS held out
# Development validation ONLY.
#
# NO known-test access.
# NO benign-test access.
# NO zero-day DDoS access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    accuracy_score,
    average_precision_score,
    roc_auc_score
)


print("=" * 78)
print("STEP A26 — VALIDATION | lambda_t = 0.50")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_25_LAMBDA_050_FINETUNE_VALID",
    "MOTSSLGRU",
    "DEVICE"
]

missing = [
    name
    for name in required_variables
    if name not in globals()
]

if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_25_LAMBDA_050_FINETUNE_VALID:
    raise RuntimeError("A25 did not pass.")


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A20 lambda protocol valid:",
    STEP_20_LAMBDA_PROTOCOL_VALID
)

print(
    "A25 lambda=0.50 fine-tuning valid:",
    STEP_25_LAMBDA_050_FINETUNE_VALID
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

LAMBDA_T = 0.50
SEED = 13

EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


print("\n[2] Validation configuration")
print("-" * 78)

print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)

print(
    "Expected validation windows:",
    f"{EXPECTED_WINDOWS:,}"
)

print(
    "Expected benign windows:",
    f"{EXPECTED_BENIGN:,}"
)

print(
    "Expected attack windows:",
    f"{EXPECTED_ATTACK:,}"
)

print(
    "Threshold rule:",
    "maximize development-validation F1"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)

CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)

TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)

PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)

PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)

FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)

MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p50_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)

REGISTRY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "fold_01_lambda_t_experiment_registry.csv"
)

POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "fold_01_lambda_t_selection_policy.json"
)


required_paths = [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    MODEL_PATH,
    REGISTRY_PATH,
    POLICY_PATH
]

for path in required_paths:

    if not path.exists():

        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 4 — VERIFY A20 POLICY
# ======================================================================

print("\n[3] Verifying frozen A20 protocol")
print("-" * 78)


with open(
    POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:

    lambda_policy = json.load(file)


if (
    lambda_policy[
        "selection_data"
    ]
    !=
    "development_validation_only"
):

    raise RuntimeError(
        "A20 selection-data policy mismatch."
    )


if lambda_policy[
    "test_data_allowed_for_lambda_selection"
]:

    raise RuntimeError(
        "Test metrics are incorrectly allowed."
    )


if lambda_policy[
    "zero_day_data_allowed_for_lambda_selection"
]:

    raise RuntimeError(
        "Zero-day metrics are incorrectly allowed."
    )


print(
    "Selection data:",
    lambda_policy[
        "selection_data"
    ]
)

print(
    "Test metrics allowed:",
    False
)

print(
    "Zero-day metrics allowed:",
    False
)


# ======================================================================
# 5 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[4] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(file)


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        "Expected exactly 75 retained features."
    )


parameter_lookup = (

    parameters

    .set_index(
        "feature"
    )

    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing invalid."
    )


# ======================================================================
# 6 — LOAD DEVELOPMENT VALIDATION MANIFEST
# ======================================================================

print("\n[5] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_validation"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


VALIDATION_WINDOWS_MANIFEST = int(

    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDOS_WINDOWS = int(

    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{VALIDATION_WINDOWS_MANIFEST:,}"
)

print(
    "DDoS validation windows:",
    DDOS_WINDOWS
)


if len(VAL_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if VALIDATION_WINDOWS_MANIFEST != EXPECTED_WINDOWS:

    raise RuntimeError(
        "Validation window mismatch."
    )


if DDOS_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 7 — LOAD lambda=0.50 MODEL
# ======================================================================

print("\n[6] Loading lambda=0.50 model")
print("-" * 78)


model_package = torch.load(
    MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        model_package[
            "SSL_lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Fine-tuned model lambda mismatch."
    )


if model_package.get(
    "threshold_selected"
):

    raise RuntimeError(
        "Model package already indicates "
        "threshold selection."
    )


MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


MODEL.eval()


MODEL_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in MODEL.parameters()
)


print(
    "Loaded SSL lambda_t:",
    model_package[
        "SSL_lambda_t"
    ]
)

print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Model finite:",
    MODEL_FINITE
)


if not MODEL_FINITE:

    raise RuntimeError(
        "Model parameters are non-finite."
    )


# ======================================================================
# 8 — FROZEN PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(table):

    X = (

        table

        .to_pandas()

        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        rows, cols = np.where(
            bad_mask
        )


        X[
            rows,
            cols
        ] = IMPUTE_VALUES[
            cols
        ]


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite values after frozen preprocessing."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite float32 transformed values."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 9 — MODEL INFERENCE FUNCTION
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(windows):

    outputs = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,
            len(windows)
        )


        X = torch.from_numpy(

            windows[
                start:stop
            ]

        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                MODEL
                .forward_classifier(
                    X
                )
            )


            probabilities = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                probabilities
            ).all()
        ):

            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        outputs.append(

            probabilities

            .detach()

            .cpu()

            .numpy()

            .astype(
                np.float64
            )
        )


    return np.concatenate(
        outputs
    )


# ======================================================================
# 10 — RUN VALIDATION INFERENCE
# ======================================================================

print("\n[7] Running lambda=0.50 validation inference")
print("-" * 78)


prediction_parts = []

TOTAL_WINDOWS = 0

TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    family = str(
        row[
            "research_family"
        ]
    )


    target = int(
        row[
            "binary_target"
        ]
    )


    partition_start = int(
        row[
            "partition_start_row"
        ]
    )


    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    expected_windows = int(
        row[
            "window_count"
        ]
    )


    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )


    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():

        raise RuntimeError(
            f"Missing Parquet: {parquet_name}"
        )


    if family == "DDoS":

        raise RuntimeError(
            "DDoS reached validation inference."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probability_parts = []

    source_raw_nonfinite = 0

    absolute_row = 0


    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(

            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row

        group_end = (
            group_start
            +
            row_group_rows
        )


        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(

            row_group_index,

            columns=
                RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(

            local_start,

            local_end
            -
            local_start
        )


        Z, bad_count = (
            frozen_preprocess(
                table
            )
        )


        source_raw_nonfinite += (
            bad_count
        )


        if len(pending) > 0:

            Z = np.concatenate(
                [
                    pending,
                    Z
                ],
                axis=0
            )


        complete_windows = (
            len(Z)
            //
            8
        )


        complete_rows = (
            complete_windows
            *
            8
        )


        if complete_windows > 0:

            windows = (

                Z[
                    :complete_rows
                ]

                .reshape(
                    complete_windows,
                    8,
                    75
                )
            )


            probabilities = (
                predict_windows(
                    windows
                )
            )


            source_probability_parts.append(
                probabilities
            )


        pending = (

            Z[
                complete_rows:
            ]

            .copy()
        )


    if source_probability_parts:

        source_probabilities = np.concatenate(
            source_probability_parts
        )

    else:

        source_probabilities = np.empty(
            0,
            dtype=np.float64
        )


    actual_windows = int(
        len(
            source_probabilities
        )
    )


    actual_tail = int(
        len(
            pending
        )
    )


    source_valid = bool(

        actual_windows
        ==
        expected_windows

        and

        actual_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()

        and

        (
            (
                source_probabilities >= 0
            )
            &
            (
                source_probabilities <= 1
            )
        ).all()
    )


    SOURCE_CHECKS_VALID &= (
        source_valid
    )


    if not source_valid:

        raise RuntimeError(
            f"Validation construction mismatch "
            f"for {source_class}."
        )


    source_frame = pd.DataFrame({

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            target,

        "malicious_probability":
            source_probabilities
    })


    prediction_parts.append(
        source_frame
    )


    TOTAL_WINDOWS += (
        actual_windows
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={actual_windows:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 11 — COMBINE PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (

    VALIDATION_PREDICTIONS[
        "binary_target"
    ]

    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (

    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


COUNTS_VALID = bool(

    len(y_true)
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDOS_WINDOWS
    ==
    0
)


print("\n[8] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(y_true):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDOS_WINDOWS
)

print(
    "Raw non-finite values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{time.time() - inference_start:.2f} seconds"
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Validation counts are invalid."
    )


# ======================================================================
# 12 — THRESHOLD SEARCH
# ======================================================================

print("\n[9] Selecting lambda=0.50 validation threshold")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (

    2.0

    *

    threshold_precision

    *

    threshold_recall

    /

    np.maximum(

        threshold_precision
        +
        threshold_recall,

        1e-15
    )
)


MAX_F1 = float(
    np.max(
        threshold_f1
    )
)


candidate_indices = np.flatnonzero(

    np.isclose(

        threshold_f1,

        MAX_F1,

        rtol=0.0,

        atol=1e-12
    )
)


BEST_INDEX = int(

    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Threshold tie-break:",
    "highest threshold"
)


# ======================================================================
# 13 — VALIDATION METRICS
# ======================================================================

predictions = (

    y_probability

    >=

    SELECTED_THRESHOLD

).astype(
    np.int64
)


tn, fp, fn, tp = (

    confusion_matrix(

        y_true,

        predictions,

        labels=[
            0,
            1
        ]

    ).ravel()
)


VALIDATION_PRECISION = float(

    precision_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_RECALL = float(

    recall_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_F1 = float(

    f1_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_ACCURACY = float(

    accuracy_score(
        y_true,
        predictions
    )
)


VALIDATION_FPR = float(

    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_PR_AUC = float(

    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(

    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[10] lambda=0.50 validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "TP:",
    int(tp)
)

print(
    "TN:",
    int(tn)
)

print(
    "FP:",
    int(fp)
)

print(
    "FN:",
    int(fn)
)

print(
    "Precision:",
    f"{VALIDATION_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "F1:",
    f"{VALIDATION_F1:.10f}"
)

print(
    "FPR:",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{VALIDATION_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 14 — SAVE lambda=0.50 VALIDATION ARTIFACTS
# ======================================================================

OUTPUT_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "lambda_0p50"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    OUTPUT_DIR
    / "development_validation_predictions.csv"
)


THRESHOLD_CURVE_PATH = (
    OUTPUT_DIR
    / "validation_threshold_search.csv"
)


RESULT_PATH = (
    OUTPUT_DIR
    / "validation_result.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = predictions


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


threshold_table = pd.DataFrame({

    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1
})


threshold_table.to_csv(
    THRESHOLD_CURVE_PATH,
    index=False
)


validation_result = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(y_true)
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        VALIDATION_PRECISION,

    "validation_recall":
        VALIDATION_RECALL,

    "validation_F1":
        VALIDATION_F1,

    "validation_FPR":
        VALIDATION_FPR,

    "validation_accuracy":
        VALIDATION_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "selection_rule":
        "maximize_validation_F1",

    "threshold_tiebreak":
        "highest_threshold",

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    RESULT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        validation_result,
        file,
        indent=4
    )


# ======================================================================
# 15 — UPDATE A20 REGISTRY
# ======================================================================

print("\n[11] Updating frozen lambda registry")
print("-" * 78)


registry = pd.read_csv(
    REGISTRY_PATH
)


lambda_mask = np.isclose(

    registry[
        "lambda_t"
    ].to_numpy(
        dtype=float
    ),

    LAMBDA_T
)


if int(
    lambda_mask.sum()
) != 1:

    raise RuntimeError(
        "Could not uniquely identify "
        "lambda=0.50 in registry."
    )


registry.loc[
    lambda_mask,
    "status"
] = "validation_complete"


registry.loc[
    lambda_mask,
    "selected_threshold"
] = SELECTED_THRESHOLD


registry.loc[
    lambda_mask,
    "validation_F1"
] = VALIDATION_F1


registry.loc[
    lambda_mask,
    "validation_FPR"
] = VALIDATION_FPR


registry.loc[
    lambda_mask,
    "validation_recall"
] = VALIDATION_RECALL


registry.loc[
    lambda_mask,
    "test_metrics_used_for_selection"
] = False


registry.loc[
    lambda_mask,
    "zero_day_metrics_used_for_selection"
] = False


registry.to_csv(
    REGISTRY_PATH,
    index=False
)


print(
    registry[
        [
            "lambda_t",
            "status",
            "selected_threshold",
            "validation_F1",
            "validation_FPR",
            "validation_recall"
        ]
    ]
)


# ======================================================================
# 16 — SAVE LOCAL REGISTRY COPY
# ======================================================================

LOCAL_REGISTRY_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/lambda_t/"
    "fold_01_DDoS"
)


LOCAL_REGISTRY_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_REGISTRY_PATH = (
    LOCAL_REGISTRY_DIR
    / "fold_01_lambda_t_experiment_registry.csv"
)


shutil.copy2(
    REGISTRY_PATH,
    LOCAL_REGISTRY_PATH
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

completed_configs = int(

    (
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


lambda_row = (

    registry.loc[
        lambda_mask
    ]

    .iloc[0]
)


REGISTRY_UPDATE_VALID = bool(

    completed_configs
    ==
    3

    and

    np.isclose(
        float(
            lambda_row[
                "validation_F1"
            ]
        ),
        VALIDATION_F1
    )

    and

    np.isclose(
        float(
            lambda_row[
                "validation_FPR"
            ]
        ),
        VALIDATION_FPR
    )
)


ARTIFACTS_VALID = bool(

    PREDICTIONS_PATH.exists()

    and

    THRESHOLD_CURVE_PATH.exists()

    and

    RESULT_PATH.exists()

    and

    REGISTRY_PATH.exists()
)


A26_VALID = bool(

    COUNTS_VALID

    and

    SOURCE_CHECKS_VALID

    and

    MODEL_FINITE

    and

    PREPROCESSING_VALID

    and

    DDOS_WINDOWS == 0

    and

    np.isfinite(
        SELECTED_THRESHOLD
    )

    and

    np.isfinite(
        VALIDATION_F1
    )

    and

    np.isfinite(
        VALIDATION_FPR
    )

    and

    REGISTRY_UPDATE_VALID

    and

    ARTIFACTS_VALID
)


STEP_26_LAMBDA_050_VALIDATION_VALID = (
    A26_VALID
)


print("\n[12] Step A26 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Validation windows             :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDOS_WINDOWS
)

print(
    "Selected threshold             :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Validation F1                  :",
    f"{VALIDATION_F1:.10f}"
)

print(
    "Validation recall              :",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "Validation FPR                 :",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Known-test accessed            :",
    False
)

print(
    "Benign-test accessed           :",
    False
)

print(
    "Zero-day DDoS accessed         :",
    False
)

print(
    "Completed lambda configs       :",
    completed_configs,
    "/ 4"
)

print(
    "Registry updated               :",
    REGISTRY_UPDATE_VALID
)

print(
    "Artifacts saved                :",
    ARTIFACTS_VALID
)


print("\n" + "=" * 78)

if A26_VALID:

    print(
        "✅ STEP A26 PASSED — "
        "lambda_t=0.50 development-validation "
        "result recorded successfully."
    )

else:

    print(
        "❌ STEP A26 FAILED — "
        "do not continue to lambda_t=1.00 yet."
    )

print("=" * 78)

==============================================================================
STEP A26 — VALIDATION | lambda_t = 0.50
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A20 lambda protocol valid: True
A25 lambda=0.50 fine-tuning valid: True
Device: cuda

[2] Validation configuration
------------------------------------------------------------------------------
lambda_t: 0.5
Seed: 13
Expected validation windows: 167,482
Expected benign windows: 1,715
Expected attack windows: 165,767
Threshold rule: maximize development-validation F1

[3] Verifying frozen A20 protocol
------------------------------------------------------------------------------
Selection data: development_validation_only
Test metrics allowed: False
Zero-day metrics allowed: False

[4] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Preprocessing refitted: False

[5] Loading development-validation manifest
------------------------------------------------------------------------------
Validation ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[6] Loading lambda=0.50 model
------------------------------------------------------------------------------
Loaded SSL lambda_t: 0.5
Fine-tuning epochs: 20
Imbalance method: none
Model finite: True

[7] Running lambda=0.50 validation inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[8] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite values imputed: 1,516
All source checks valid: True
Probability min: 0.0000000000
Probability max: 1.0000000000
Inference runtime: 5.84 seconds

[9] Selecting lambda=0.50 validation threshold
------------------------------------------------------------------------------
Threshold candidates: 5,594
Maximum validation F1: 0.9971257269
Selected threshold: 0.0022796169
Max-F1 tie count: 1
Threshold tie-break: highest threshold

[10] lambda=0.50 validation metrics
------------------------------------------------------------------------------
Threshold: 0.0022796169
TP: 165478
TN: 1050
FP: 665
FN: 289
Precision: 0.9959974239
Recall: 0.9982565891
F1: 0.9971257269
FPR: 0.3877551020
Accuracy: 0.9943038655
PR-AUC: 0.9999716439
ROC-AUC: 0.9972772314

[11] Updating frozen lambda registry
------------------------------------------------------------------------------
   lambda_t               status  selected_threshold  validation_F1  \
0      0.10  validation_complete            0.002184       0.997122
1      0.25  validation_complete            0.014751       0.997267
2      0.50  validation_complete            0.002280       0.997126
3      1.00              pending                 NaN            NaN

   validation_FPR  validation_recall
0        0.377843           0.998148
1        0.365598           0.998311
2        0.387755           0.998257
3             NaN                NaN

[12] Step A26 validation
------------------------------------------------------------------------------
lambda_t                       : 0.5
Validation windows             : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
Selected threshold             : 0.0022796169
Validation F1                  : 0.9971257269
Validation recall              : 0.9982565891
Validation FPR                 : 0.3877551020
Known-test accessed            : False
Benign-test accessed           : False
Zero-day DDoS accessed         : False
Completed lambda configs       : 3 / 4
Registry updated               : True
Artifacts saved                : True

==============================================================================
✅ STEP A26 PASSED — lambda_t=0.50 development-validation result recorded successfully.
==============================================================================

# Step A27 — SSL pretraining for λₜ = 1.00

In [ ]:
# ======================================================================
# STEP A27
# LAMBDA_T SENSITIVITY — SSL PRETRAINING FOR lambda_t = 1.00
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# FP32
# 30 SSL epochs
#
# NO test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A27 — SSL PRETRAINING | lambda_t = 1.00")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_26_LAMBDA_050_VALIDATION_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_26_LAMBDA_050_VALIDATION_VALID:
    raise RuntimeError("A26 did not pass.")


print(
    "A13 valid:",
    STEP_13_PYTORCH_DATA_VALID
)

print(
    "A14 valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A20 protocol valid:",
    STEP_20_LAMBDA_PROTOCOL_VALID
)

print(
    "A26 lambda=0.50 validation valid:",
    STEP_26_LAMBDA_050_VALIDATION_VALID
)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

print("\n[2] Controlled lambda=1.00 configuration")
print("-" * 78)


SEED = 13

LAMBDA_T = 1.00

EPOCHS = 30

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

TEMPERATURE = 0.20

FEATURE_MASK_PROBABILITY = 0.10

GAUSSIAN_JITTER_STD = 0.01

MAX_GRADIENT_NORM = 5.0


print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Temperature:", TEMPERATURE)
print("Feature masking:", FEATURE_MASK_PROBABILITY)
print("Gaussian jitter:", GAUSSIAN_JITTER_STD)
print("Precision:", "float32")


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — CREATE FRESH MODEL
# ======================================================================

print("\n[3] Creating fresh lambda=1.00 model")
print("-" * 78)


set_all_seeds(SEED)


SSL_MODEL_L100 = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


# ======================================================================
# 5 — SSL PARAMETERS ONLY
# ======================================================================

SSL_PARAMETERS = (

    list(
        SSL_MODEL_L100
        .feature_encoder
        .parameters()
    )

    +

    list(
        SSL_MODEL_L100
        .temporal_encoder
        .parameters()
    )

    +

    list(
        SSL_MODEL_L100
        .projection_head
        .parameters()
    )

    +

    list(
        SSL_MODEL_L100
        .temporal_order_head
        .parameters()
    )
)


ssl_ids = {
    id(p)
    for p in SSL_PARAMETERS
}


classifier_ids = {
    id(p)
    for p in SSL_MODEL_L100
    .classifier_head
    .parameters()
}


CLASSIFIER_INCLUDED = bool(
    ssl_ids
    &
    classifier_ids
)


if CLASSIFIER_INCLUDED:

    raise RuntimeError(
        "Classifier must not be optimized during SSL."
    )


SSL_PARAMETER_COUNT = sum(
    p.numel()
    for p in SSL_PARAMETERS
)


print(
    "SSL parameters:",
    f"{SSL_PARAMETER_COUNT:,}"
)

print(
    "Classifier included:",
    CLASSIFIER_INCLUDED
)


# ======================================================================
# 6 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    SSL_PARAMETERS,

    lr=LEARNING_RATE
)


# ======================================================================
# 7 — DETERMINISTIC LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        shuffle=True,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False,

        generator=generator
    )


# ======================================================================
# 8 — AUGMENTATION
# ======================================================================

def augment_view(x):

    out = x.clone()


    out = (

        out

        +

        torch.randn_like(
            out
        )
        *
        GAUSSIAN_JITTER_STD
    )


    mask = (

        torch.rand_like(
            out
        )

        <
        FEATURE_MASK_PROBABILITY
    )


    out = out.masked_fill(
        mask,
        0.0
    )


    return out


# ======================================================================
# 9 — NT-XENT LOSS
# ======================================================================

def nt_xent_loss(
    z1,
    z2,
    temperature
):

    batch_size = int(
        z1.shape[0]
    )


    if batch_size < 2:

        raise RuntimeError(
            "NT-Xent requires at least 2 samples."
        )


    z = torch.cat(
        [
            z1,
            z2
        ],
        dim=0
    ).float()


    similarity = (

        torch.matmul(
            z,
            z.T
        )

        /

        temperature
    )


    total = (
        2
        *
        batch_size
    )


    identity = torch.eye(

        total,

        dtype=torch.bool,

        device=similarity.device
    )


    similarity = similarity.masked_fill(
        identity,
        float("-inf")
    )


    targets = (

        torch.arange(
            total,
            device=similarity.device
        )

        +

        batch_size

    ) % total


    return F.cross_entropy(
        similarity,
        targets
    )


# ======================================================================
# 10 — TEMPORAL-ORDER LOSS
# ======================================================================

def temporal_order_loss(
    sequence_states,
    head
):

    hidden = int(
        sequence_states.shape[-1]
    )


    earlier = (

        sequence_states[
            :,
            :-1,
            :
        ]

        .reshape(
            -1,
            hidden
        )
    )


    later = (

        sequence_states[
            :,
            1:,
            :
        ]

        .reshape(
            -1,
            hidden
        )
    )


    forward_logits = head(
        earlier,
        later
    )


    reverse_logits = head(
        later,
        earlier
    )


    forward_targets = torch.ones_like(
        forward_logits
    )


    reverse_targets = torch.zeros_like(
        reverse_logits
    )


    return (

        F.binary_cross_entropy_with_logits(
            forward_logits,
            forward_targets
        )

        +

        F.binary_cross_entropy_with_logits(
            reverse_logits,
            reverse_targets
        )

    ) / 2.0


# ======================================================================
# 11 — OUTPUT DIRECTORIES
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/ssl_pretraining/"
    "fold_01_DDoS/"
    "seed_13/"
    "lambda_1p00_fp32"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_1p00_fp32"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "ssl_training_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "ssl_training_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "ssl_training_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "ssl_training_policy.json"
)


# ======================================================================
# 12 — SAVE POLICY
# ======================================================================

POLICY = {

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "epochs":
        EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "temperature":
        TEMPERATURE,

    "feature_mask_probability":
        FEATURE_MASK_PROBABILITY,

    "gaussian_jitter_std":
        GAUSSIAN_JITTER_STD,

    "precision":
        "float32",

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False,

    "held_out_DDoS_used":
        False,

    "test_data_used":
        False,

    "zero_day_data_used":
        False,

    "controlled_against_other_lambdas":
        True
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 13 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking lambda=1.00 checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Checkpoint lambda mismatch."
        )


    SSL_MODEL_L100.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No lambda=1.00 checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 14 — TRAIN
# ======================================================================

print("\n[5] Starting lambda=1.00 SSL training")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= EPOCHS:

    for epoch in range(
        START_EPOCH,
        EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        SSL_MODEL_L100.train()


        total_loss_sum = 0.0

        contrastive_loss_sum = 0.0

        order_loss_sum = 0.0

        examples = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            _
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite input at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            view1 = augment_view(
                X
            )


            view2 = augment_view(
                X
            )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            seq1, _, z1 = (
                SSL_MODEL_L100
                .forward_ssl(
                    view1
                )
            )


            seq2, _, z2 = (
                SSL_MODEL_L100
                .forward_ssl(
                    view2
                )
            )


            contrastive = nt_xent_loss(

                z1,

                z2,

                TEMPERATURE
            )


            order1 = temporal_order_loss(

                seq1,

                SSL_MODEL_L100
                .temporal_order_head
            )


            order2 = temporal_order_loss(

                seq2,

                SSL_MODEL_L100
                .temporal_order_head
            )


            order_loss = (

                order1

                +

                order2

            ) / 2.0


            total_loss = (

                contrastive

                +

                LAMBDA_T
                *
                order_loss
            )


            if not bool(
                torch.isfinite(
                    total_loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite loss at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            total_loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    SSL_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            total_loss_sum += (

                float(
                    total_loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            contrastive_loss_sum += (

                float(
                    contrastive
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            order_loss_sum += (

                float(
                    order_loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            examples += batch_size


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/{EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| Loss "
                    f"{float(total_loss.detach().cpu()):.4f}"
                )


        mean_total = (
            total_loss_sum
            /
            examples
        )


        mean_contrastive = (
            contrastive_loss_sum
            /
            examples
        )


        mean_order = (
            order_loss_sum
            /
            examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "total_loss":
                mean_total,

            "NT_Xent_loss":
                mean_contrastive,

            "temporal_order_loss":
                mean_order,

            "examples":
                examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            !=
            epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "precision":
                "float32",

            "model_state_dict":
                SSL_MODEL_L100
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| total={mean_total:.6f} "
            f"| NT-Xent={mean_contrastive:.6f} "
            f"| order={mean_order:.6f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "lambda=1.00 already completed 30 epochs."
    )


# ======================================================================
# 15 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 lambda=1.00 SSL epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 16 — FINAL NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            p
        ).all()
    )

    for p in SSL_MODEL_L100.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=32,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


SSL_MODEL_L100.eval()


with torch.no_grad():

    seq_check, rep_check, z_check = (

        SSL_MODEL_L100
        .forward_ssl(
            X_check
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        seq_check
    ).all()

    and

    torch.isfinite(
        rep_check
    ).all()

    and

    torch.isfinite(
        z_check
    ).all()
)


NORM_ERROR = float(

    torch.max(

        torch.abs(

            torch.linalg.vector_norm(
                z_check,
                dim=1
            )

            -

            1.0
        )
    )

    .detach()

    .cpu()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Projection norm error:",
    f"{NORM_ERROR:.10e}"
)


# ======================================================================
# 17 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        SSL_MODEL_L100
        .state_dict(),

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "temperature":
        TEMPERATURE,

    "labels_used_during_SSL":
        False,

    "classifier_optimized":
        False,

    "test_data_used":
        False,

    "zero_day_data_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 18 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A27_VALID = bool(

    COMPLETED_EPOCHS == 30

    and

    not CLASSIFIER_INCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    NORM_ERROR < 1e-5

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_27_LAMBDA_100_SSL_VALID = (
    A27_VALID
)


print("\n[8] Step A27 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Completed SSL epochs           :",
    COMPLETED_EPOCHS,
    "/ 30"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Binary labels used             :",
    False
)

print(
    "Classifier optimized           :",
    CLASSIFIER_INCLUDED
)

print(
    "Held-out DDoS used             :",
    False
)

print(
    "Test data used                 :",
    False
)

print(
    "Zero-day data used             :",
    False
)

print(
    "Final total loss               :",
    f"{float(FINAL_ROW['total_loss']):.6f}"
)

print(
    "Final NT-Xent loss             :",
    f"{float(FINAL_ROW['NT_Xent_loss']):.6f}"
)

print(
    "Final temporal-order loss      :",
    f"{float(FINAL_ROW['temporal_order_loss']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A27_VALID:

    print(
        "✅ STEP A27 PASSED — "
        "lambda_t=1.00 completed 30-epoch "
        "Fold-1 SSL pretraining successfully."
    )

else:

    print(
        "❌ STEP A27 INCOMPLETE — "
        "rerun this same cell to resume "
        "lambda_t=1.00 training."
    )

print("=" * 78)

==============================================================================
STEP A27 — SSL PRETRAINING | lambda_t = 1.00
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 valid: True
A14 valid: True
A20 protocol valid: True
A26 lambda=0.50 validation valid: True
Training windows: 105,577
Device: cuda

[2] Controlled lambda=1.00 configuration
------------------------------------------------------------------------------
lambda_t: 1.0
Seed: 13
Epochs: 30
Batch size: 256
Learning rate: 0.001
Temperature: 0.2
Feature masking: 0.1
Gaussian jitter: 0.01
Precision: float32

[3] Creating fresh lambda=1.00 model
------------------------------------------------------------------------------
SSL parameters: 167,105
Classifier included: False

[4] Checking lambda=1.00 checkpoint
------------------------------------------------------------------------------
No lambda=1.00 checkpoint.
Starting from epoch 1.

[5] Starting lambda=1.00 SSL training
------------------------------------------------------------------------------
Epoch 01/30 | Batch 100/413 | Loss 2.3926
Epoch 01/30 | Batch 200/413 | Loss 2.2328
Epoch 01/30 | Batch 300/413 | Loss 2.2758
Epoch 01/30 | Batch 400/413 | Loss 2.1687
Epoch 01/30 | Batch 413/413 | Loss 1.3788

Epoch 01 complete | total=2.459400 | NT-Xent=2.384457 | order=0.074943 | time=11.4s | checkpoint=Drive
Epoch 02/30 | Batch 100/413 | Loss 2.1397
Epoch 02/30 | Batch 200/413 | Loss 2.0806
Epoch 02/30 | Batch 300/413 | Loss 2.1226
Epoch 02/30 | Batch 400/413 | Loss 2.0452
Epoch 02/30 | Batch 413/413 | Loss 1.2949

Epoch 02 complete | total=2.096148 | NT-Xent=2.095430 | order=0.000718 | time=11.7s | checkpoint=Drive
Epoch 03/30 | Batch 100/413 | Loss 1.9948
Epoch 03/30 | Batch 200/413 | Loss 2.0368
Epoch 03/30 | Batch 300/413 | Loss 1.9745
Epoch 03/30 | Batch 400/413 | Loss 1.9553
Epoch 03/30 | Batch 413/413 | Loss 1.3047

Epoch 03 complete | total=2.017024 | NT-Xent=2.016633 | order=0.000391 | time=8.7s | checkpoint=Drive
Epoch 04/30 | Batch 100/413 | Loss 1.9798
Epoch 04/30 | Batch 200/413 | Loss 1.9794
Epoch 04/30 | Batch 300/413 | Loss 1.9671
Epoch 04/30 | Batch 400/413 | Loss 1.9959
Epoch 04/30 | Batch 413/413 | Loss 1.2125

Epoch 04 complete | total=1.973296 | NT-Xent=1.973022 | order=0.000274 | time=5.9s | checkpoint=Drive
Epoch 05/30 | Batch 100/413 | Loss 1.9962
Epoch 05/30 | Batch 200/413 | Loss 1.9249
Epoch 05/30 | Batch 300/413 | Loss 1.9411
Epoch 05/30 | Batch 400/413 | Loss 1.8905
Epoch 05/30 | Batch 413/413 | Loss 1.2818

Epoch 05 complete | total=1.943805 | NT-Xent=1.943575 | order=0.000230 | time=7.1s | checkpoint=Drive
Epoch 06/30 | Batch 100/413 | Loss 1.9388
Epoch 06/30 | Batch 200/413 | Loss 1.9207
Epoch 06/30 | Batch 300/413 | Loss 1.9103
Epoch 06/30 | Batch 400/413 | Loss 1.8850
Epoch 06/30 | Batch 413/413 | Loss 1.2055

Epoch 06 complete | total=1.923664 | NT-Xent=1.923486 | order=0.000178 | time=5.8s | checkpoint=Drive
Epoch 07/30 | Batch 100/413 | Loss 1.8840
Epoch 07/30 | Batch 200/413 | Loss 1.9003
Epoch 07/30 | Batch 300/413 | Loss 1.9149
Epoch 07/30 | Batch 400/413 | Loss 1.8847
Epoch 07/30 | Batch 413/413 | Loss 1.2227

Epoch 07 complete | total=1.906289 | NT-Xent=1.906119 | order=0.000170 | time=7.0s | checkpoint=Drive
Epoch 08/30 | Batch 100/413 | Loss 1.8844
Epoch 08/30 | Batch 200/413 | Loss 1.9107
Epoch 08/30 | Batch 300/413 | Loss 1.9196
Epoch 08/30 | Batch 400/413 | Loss 1.8626
Epoch 08/30 | Batch 413/413 | Loss 1.1876

Epoch 08 complete | total=1.896312 | NT-Xent=1.896118 | order=0.000194 | time=5.9s | checkpoint=Drive
Epoch 09/30 | Batch 100/413 | Loss 1.8762
Epoch 09/30 | Batch 200/413 | Loss 1.8476
Epoch 09/30 | Batch 300/413 | Loss 1.8452
Epoch 09/30 | Batch 400/413 | Loss 1.8912
Epoch 09/30 | Batch 413/413 | Loss 1.1872

Epoch 09 complete | total=1.883433 | NT-Xent=1.883285 | order=0.000148 | time=6.9s | checkpoint=Drive
Epoch 10/30 | Batch 100/413 | Loss 1.8878
Epoch 10/30 | Batch 200/413 | Loss 1.8802
Epoch 10/30 | Batch 300/413 | Loss 1.8390
Epoch 10/30 | Batch 400/413 | Loss 1.8963
Epoch 10/30 | Batch 413/413 | Loss 1.1310

Epoch 10 complete | total=1.875282 | NT-Xent=1.875131 | order=0.000152 | time=5.8s | checkpoint=Drive
Epoch 11/30 | Batch 100/413 | Loss 1.8884
Epoch 11/30 | Batch 200/413 | Loss 1.8524
Epoch 11/30 | Batch 300/413 | Loss 1.8900
Epoch 11/30 | Batch 400/413 | Loss 1.8678
Epoch 11/30 | Batch 413/413 | Loss 1.1609

Epoch 11 complete | total=1.868934 | NT-Xent=1.868774 | order=0.000160 | time=7.3s | checkpoint=Drive
Epoch 12/30 | Batch 100/413 | Loss 1.8557
Epoch 12/30 | Batch 200/413 | Loss 1.8615
Epoch 12/30 | Batch 300/413 | Loss 1.8808
Epoch 12/30 | Batch 400/413 | Loss 1.8714
Epoch 12/30 | Batch 413/413 | Loss 1.1016

Epoch 12 complete | total=1.858833 | NT-Xent=1.858673 | order=0.000160 | time=6.0s | checkpoint=Drive
Epoch 13/30 | Batch 100/413 | Loss 1.8610
Epoch 13/30 | Batch 200/413 | Loss 1.8078
Epoch 13/30 | Batch 300/413 | Loss 1.8839
Epoch 13/30 | Batch 400/413 | Loss 1.8938
Epoch 13/30 | Batch 413/413 | Loss 1.1160

Epoch 13 complete | total=1.854279 | NT-Xent=1.854127 | order=0.000152 | time=6.4s | checkpoint=Drive
Epoch 14/30 | Batch 100/413 | Loss 1.8343
Epoch 14/30 | Batch 200/413 | Loss 1.8550
Epoch 14/30 | Batch 300/413 | Loss 1.8370
Epoch 14/30 | Batch 400/413 | Loss 1.8211
Epoch 14/30 | Batch 413/413 | Loss 1.1929

Epoch 14 complete | total=1.851789 | NT-Xent=1.851640 | order=0.000150 | time=6.4s | checkpoint=Drive
Epoch 15/30 | Batch 100/413 | Loss 1.8793
Epoch 15/30 | Batch 200/413 | Loss 1.8298
Epoch 15/30 | Batch 300/413 | Loss 1.8425
Epoch 15/30 | Batch 400/413 | Loss 1.8125
Epoch 15/30 | Batch 413/413 | Loss 1.1583

Epoch 15 complete | total=1.841842 | NT-Xent=1.841704 | order=0.000138 | time=5.8s | checkpoint=Drive
Epoch 16/30 | Batch 100/413 | Loss 1.8467
Epoch 16/30 | Batch 200/413 | Loss 1.8425
Epoch 16/30 | Batch 300/413 | Loss 1.7963
Epoch 16/30 | Batch 400/413 | Loss 1.8342
Epoch 16/30 | Batch 413/413 | Loss 1.1657

Epoch 16 complete | total=1.838693 | NT-Xent=1.838508 | order=0.000185 | time=7.4s | checkpoint=Drive
Epoch 17/30 | Batch 100/413 | Loss 1.7908
Epoch 17/30 | Batch 200/413 | Loss 1.8579
Epoch 17/30 | Batch 300/413 | Loss 1.8675
Epoch 17/30 | Batch 400/413 | Loss 1.8212
Epoch 17/30 | Batch 413/413 | Loss 1.1259

Epoch 17 complete | total=1.834068 | NT-Xent=1.833955 | order=0.000113 | time=5.8s | checkpoint=Drive
Epoch 18/30 | Batch 100/413 | Loss 1.8403
Epoch 18/30 | Batch 200/413 | Loss 1.8066
Epoch 18/30 | Batch 300/413 | Loss 1.8145
Epoch 18/30 | Batch 400/413 | Loss 1.8211
Epoch 18/30 | Batch 413/413 | Loss 1.1536

Epoch 18 complete | total=1.829718 | NT-Xent=1.829587 | order=0.000131 | time=7.1s | checkpoint=Drive
Epoch 19/30 | Batch 100/413 | Loss 1.7981
Epoch 19/30 | Batch 200/413 | Loss 1.8156
Epoch 19/30 | Batch 300/413 | Loss 1.8299
Epoch 19/30 | Batch 400/413 | Loss 1.8360
Epoch 19/30 | Batch 413/413 | Loss 1.0952

Epoch 19 complete | total=1.825337 | NT-Xent=1.825201 | order=0.000136 | time=5.8s | checkpoint=Drive
Epoch 20/30 | Batch 100/413 | Loss 1.8525
Epoch 20/30 | Batch 200/413 | Loss 1.8194
Epoch 20/30 | Batch 300/413 | Loss 1.8554
Epoch 20/30 | Batch 400/413 | Loss 1.8364
Epoch 20/30 | Batch 413/413 | Loss 1.1120

Epoch 20 complete | total=1.822195 | NT-Xent=1.822057 | order=0.000138 | time=7.0s | checkpoint=Drive
Epoch 21/30 | Batch 100/413 | Loss 1.7861
Epoch 21/30 | Batch 200/413 | Loss 1.7705
Epoch 21/30 | Batch 300/413 | Loss 1.7989
Epoch 21/30 | Batch 400/413 | Loss 1.8211
Epoch 21/30 | Batch 413/413 | Loss 1.0983

Epoch 21 complete | total=1.817238 | NT-Xent=1.817120 | order=0.000119 | time=6.0s | checkpoint=Drive
Epoch 22/30 | Batch 100/413 | Loss 1.8370
Epoch 22/30 | Batch 200/413 | Loss 1.8216
Epoch 22/30 | Batch 300/413 | Loss 1.8257
Epoch 22/30 | Batch 400/413 | Loss 1.8214
Epoch 22/30 | Batch 413/413 | Loss 1.1287

Epoch 22 complete | total=1.815732 | NT-Xent=1.815602 | order=0.000130 | time=7.0s | checkpoint=Drive
Epoch 23/30 | Batch 100/413 | Loss 1.8656
Epoch 23/30 | Batch 200/413 | Loss 1.8188
Epoch 23/30 | Batch 300/413 | Loss 1.7928
Epoch 23/30 | Batch 400/413 | Loss 1.7866
Epoch 23/30 | Batch 413/413 | Loss 1.1110

Epoch 23 complete | total=1.812039 | NT-Xent=1.811916 | order=0.000122 | time=5.9s | checkpoint=Drive
Epoch 24/30 | Batch 100/413 | Loss 1.8008
Epoch 24/30 | Batch 200/413 | Loss 1.8179
Epoch 24/30 | Batch 300/413 | Loss 1.8170
Epoch 24/30 | Batch 400/413 | Loss 1.8359
Epoch 24/30 | Batch 413/413 | Loss 1.0608

Epoch 24 complete | total=1.808903 | NT-Xent=1.808793 | order=0.000109 | time=6.6s | checkpoint=Drive
Epoch 25/30 | Batch 100/413 | Loss 1.8343
Epoch 25/30 | Batch 200/413 | Loss 1.8178
Epoch 25/30 | Batch 300/413 | Loss 1.8482
Epoch 25/30 | Batch 400/413 | Loss 1.8617
Epoch 25/30 | Batch 413/413 | Loss 1.0927

Epoch 25 complete | total=1.807869 | NT-Xent=1.807773 | order=0.000096 | time=6.3s | checkpoint=Drive
Epoch 26/30 | Batch 100/413 | Loss 1.7869
Epoch 26/30 | Batch 200/413 | Loss 1.8151
Epoch 26/30 | Batch 300/413 | Loss 1.8263
Epoch 26/30 | Batch 400/413 | Loss 1.7976
Epoch 26/30 | Batch 413/413 | Loss 1.1212

Epoch 26 complete | total=1.804195 | NT-Xent=1.804104 | order=0.000091 | time=6.2s | checkpoint=Drive
Epoch 27/30 | Batch 100/413 | Loss 1.8236
Epoch 27/30 | Batch 200/413 | Loss 1.8235
Epoch 27/30 | Batch 300/413 | Loss 1.7802
Epoch 27/30 | Batch 400/413 | Loss 1.8087
Epoch 27/30 | Batch 413/413 | Loss 1.1206

Epoch 27 complete | total=1.801869 | NT-Xent=1.801744 | order=0.000125 | time=6.7s | checkpoint=Drive
Epoch 28/30 | Batch 100/413 | Loss 1.7888
Epoch 28/30 | Batch 200/413 | Loss 1.8218
Epoch 28/30 | Batch 300/413 | Loss 1.8138
Epoch 28/30 | Batch 400/413 | Loss 1.8301
Epoch 28/30 | Batch 413/413 | Loss 1.0583

Epoch 28 complete | total=1.800532 | NT-Xent=1.800444 | order=0.000088 | time=5.8s | checkpoint=Drive
Epoch 29/30 | Batch 100/413 | Loss 1.8112
Epoch 29/30 | Batch 200/413 | Loss 1.7757
Epoch 29/30 | Batch 300/413 | Loss 1.8215
Epoch 29/30 | Batch 400/413 | Loss 1.8205
Epoch 29/30 | Batch 413/413 | Loss 1.1541

Epoch 29 complete | total=1.799776 | NT-Xent=1.799710 | order=0.000066 | time=7.2s | checkpoint=Drive
Epoch 30/30 | Batch 100/413 | Loss 1.7938
Epoch 30/30 | Batch 200/413 | Loss 1.8037
Epoch 30/30 | Batch 300/413 | Loss 1.7848
Epoch 30/30 | Batch 400/413 | Loss 1.7794
Epoch 30/30 | Batch 413/413 | Loss 1.0762

Epoch 30 complete | total=1.795974 | NT-Xent=1.795867 | order=0.000107 | time=5.9s | checkpoint=Drive

[6] Last 5 lambda=1.00 SSL epochs
------------------------------------------------------------------------------

,epoch,lambda_t,total_loss,NT_Xent_loss,temporal_order_loss,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
25,26,1.0,1.804195,1.804104,0.000091,105577,413,1.048486,6.222532
26,27,1.0,1.801869,1.801744,0.000125,105577,413,0.919018,6.727358
27,28,1.0,1.800532,1.800444,0.000088,105577,413,1.149603,5.823959
28,29,1.0,1.799776,1.799710,0.000066,105577,413,1.240923,7.164700
29,30,1.0,1.795974,1.795867,0.000107,105577,413,0.914528,5.857490

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 30
Parameters finite: True
Outputs finite: True
Projection norm error: 1.1920928955e-07

[8] Step A27 validation
------------------------------------------------------------------------------
lambda_t                       : 1.0
Completed SSL epochs           : 30 / 30
Training windows               : 105,577
Binary labels used             : False
Classifier optimized           : False
Held-out DDoS used             : False
Test data used                 : False
Zero-day data used             : False
Final total loss               : 1.795974
Final NT-Xent loss             : 1.795867
Final temporal-order loss      : 0.000107
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A27 PASSED — lambda_t=1.00 completed 30-epoch Fold-1 SSL pretraining successfully.
==============================================================================

# Step A28 — Fine-tune λₜ = 1.00

In [ ]:
# ======================================================================
# STEP A28
# LAMBDA_T SENSITIVITY — SUPERVISED FINE-TUNING FOR lambda_t = 1.00
#
# Fold 1: DDoS held out
# Seed: 13
# FP32
# 20 epochs
# Imbalance method: none
#
# NO threshold selection.
# NO known-test access.
# NO benign-test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A28 — SUPERVISED FINE-TUNING | lambda_t = 1.00")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_27_LAMBDA_100_SSL_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]

missing = [
    name
    for name in required_variables
    if name not in globals()
]

if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_27_LAMBDA_100_SSL_VALID:
    raise RuntimeError("A27 did not pass.")


print("A13 data valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 architecture valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A20 protocol valid:", STEP_20_LAMBDA_PROTOCOL_VALID)
print("A27 lambda=1.00 SSL valid:", STEP_27_LAMBDA_100_SSL_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

print("\n[2] Controlled fine-tuning configuration")
print("-" * 78)

SEED = 13
LAMBDA_T = 1.00

FINETUNE_EPOCHS = 20
BATCH_SIZE = 256
LEARNING_RATE = 1e-3
MAX_GRADIENT_NORM = 5.0

IMBALANCE_METHOD = "none"
PRECISION = "float32"


print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", FINETUNE_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Precision:", PRECISION)
print("Imbalance method:", IMBALANCE_METHOD)
print("Gradient clipping:", MAX_GRADIENT_NORM)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — LOAD lambda=1.00 SSL MODEL
# ======================================================================

print("\n[3] Loading lambda=1.00 SSL-pretrained encoder")
print("-" * 78)


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


SSL_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_1p00_fp32"
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


if not SSL_MODEL_PATH.exists():

    raise RuntimeError(
        "lambda=1.00 SSL final model "
        "was not found in Drive."
    )


SSL_PACKAGE = torch.load(
    SSL_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        SSL_PACKAGE[
            "lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Loaded SSL model has wrong lambda_t."
    )


if int(
    SSL_PACKAGE[
        "completed_epochs"
    ]
) != 30:

    raise RuntimeError(
        "lambda=1.00 SSL model did not complete 30 epochs."
    )


if SSL_PACKAGE.get(
    "labels_used_during_SSL"
):

    raise RuntimeError(
        "SSL package indicates labels were used."
    )


print(
    "SSL epochs:",
    SSL_PACKAGE[
        "completed_epochs"
    ]
)

print(
    "SSL lambda_t:",
    SSL_PACKAGE[
        "lambda_t"
    ]
)

print(
    "SSL precision:",
    SSL_PACKAGE[
        "precision"
    ]
)

print(
    "Labels used during SSL:",
    SSL_PACKAGE[
        "labels_used_during_SSL"
    ]
)


# ======================================================================
# 5 — CREATE FINE-TUNING MODEL
# ======================================================================

set_all_seeds(SEED)


FINETUNE_MODEL_L100 = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


FINETUNE_MODEL_L100.load_state_dict(
    SSL_PACKAGE[
        "model_state_dict"
    ],
    strict=True
)


print(
    "lambda=1.00 SSL state loaded:",
    True
)


# ======================================================================
# 6 — REINITIALIZE CLASSIFIER IDENTICALLY
# ======================================================================

set_all_seeds(
    SEED + 1000
)


for module in (
    FINETUNE_MODEL_L100
    .classifier_head
    .modules()
):

    if hasattr(
        module,
        "reset_parameters"
    ):

        module.reset_parameters()


print(
    "Classifier freshly initialized:",
    True
)

print(
    "Classifier initialization seed:",
    SEED + 1000
)


# ======================================================================
# 7 — FINE-TUNING PARAMETERS
# ======================================================================

FINETUNE_PARAMETERS = (

    list(
        FINETUNE_MODEL_L100
        .feature_encoder
        .parameters()
    )

    +

    list(
        FINETUNE_MODEL_L100
        .temporal_encoder
        .parameters()
    )

    +

    list(
        FINETUNE_MODEL_L100
        .classifier_head
        .parameters()
    )
)


finetune_ids = {
    id(p)
    for p in FINETUNE_PARAMETERS
}


projection_ids = {
    id(p)
    for p in FINETUNE_MODEL_L100
    .projection_head
    .parameters()
}


order_ids = {
    id(p)
    for p in FINETUNE_MODEL_L100
    .temporal_order_head
    .parameters()
}


PROJECTION_INCLUDED = bool(
    finetune_ids
    &
    projection_ids
)


ORDER_HEAD_INCLUDED = bool(
    finetune_ids
    &
    order_ids
)


if PROJECTION_INCLUDED:

    raise RuntimeError(
        "Projection head must not be fine-tuned."
    )


if ORDER_HEAD_INCLUDED:

    raise RuntimeError(
        "Temporal-order head must not be fine-tuned."
    )


print(
    "Fine-tuned parameters:",
    f"{sum(p.numel() for p in FINETUNE_PARAMETERS):,}"
)

print(
    "Projection head optimized:",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized:",
    ORDER_HEAD_INCLUDED
)


# ======================================================================
# 8 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    FINETUNE_PARAMETERS,

    lr=LEARNING_RATE
)


# ======================================================================
# 9 — DETERMINISTIC LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        shuffle=True,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False,

        generator=generator
    )


# ======================================================================
# 10 — OUTPUT PATHS
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_1p00_fp32/"
    "imbalance_none"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_1p00_fp32"
    / "imbalance_none"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)

DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)

DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "fine_tuning_history.csv"
)

DRIVE_HISTORY = (
    DRIVE_DIR
    / "fine_tuning_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)

DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fine_tuning_policy.json"
)

DRIVE_POLICY = (
    DRIVE_DIR
    / "fine_tuning_policy.json"
)


# ======================================================================
# 11 — SAVE POLICY
# ======================================================================

POLICY = {

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "initialization":
        "lambda_1p00_FP32_SSL_encoder",

    "epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "classifier_reinitialized":
        True,

    "classifier_initialization_seed":
        SEED + 1000,

    "feature_encoder_trainable":
        True,

    "GRU_encoder_trainable":
        True,

    "classifier_trainable":
        True,

    "projection_head_trainable":
        False,

    "temporal_order_head_trainable":
        False,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False,

    "controlled_against_other_lambdas":
        True
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 12 — RESUME SUPPORT
# ======================================================================

print("\n[4] Checking lambda=1.00 fine-tuning checkpoint")
print("-" * 78)


START_EPOCH = 1
history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Fine-tuning checkpoint lambda mismatch."
        )


    if checkpoint.get(
        "imbalance_method"
    ) != IMBALANCE_METHOD:

        raise RuntimeError(
            "Imbalance method mismatch."
        )


    FINETUNE_MODEL_L100.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No lambda=1.00 fine-tuning checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 13 — SUPERVISED TRAINING
# ======================================================================

print("\n[5] Starting lambda=1.00 supervised fine-tuning")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= FINETUNE_EPOCHS:

    for epoch in range(
        START_EPOCH,
        FINETUNE_EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        FINETUNE_MODEL_L100.train()


        running_loss = 0.0
        total_examples = 0

        correct_at_05 = 0

        predicted_attack_count = 0
        predicted_benign_count = 0

        actual_attack_count = 0
        actual_benign_count = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            y
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            y = y.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite input at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            logits = (
                FINETUNE_MODEL_L100
                .forward_classifier(
                    X
                )
            )


            loss = (
                F.binary_cross_entropy_with_logits(
                    logits,
                    y
                )
            )


            if not bool(
                torch.isfinite(
                    loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite BCE at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    FINETUNE_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            running_loss += (

                float(
                    loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            total_examples += batch_size


            # Diagnostic threshold only.
            with torch.no_grad():

                probabilities = torch.sigmoid(
                    logits
                )


                predictions = (
                    probabilities
                    >=
                    0.5
                ).float()


                correct_at_05 += int(
                    (
                        predictions == y
                    )
                    .sum()
                    .item()
                )


                predicted_attack_count += int(
                    (
                        predictions == 1
                    )
                    .sum()
                    .item()
                )


                predicted_benign_count += int(
                    (
                        predictions == 0
                    )
                    .sum()
                    .item()
                )


                actual_attack_count += int(
                    (
                        y == 1
                    )
                    .sum()
                    .item()
                )


                actual_benign_count += int(
                    (
                        y == 0
                    )
                    .sum()
                    .item()
                )


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/"
                    f"{FINETUNE_EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| BCE "
                    f"{float(loss.detach().cpu()):.6f}"
                )


        mean_loss = (
            running_loss
            /
            total_examples
        )


        diagnostic_accuracy = (
            correct_at_05
            /
            total_examples
        )


        predicted_attack_fraction = (
            predicted_attack_count
            /
            total_examples
        )


        predicted_benign_fraction = (
            predicted_benign_count
            /
            total_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "training_BCE_loss":
                mean_loss,

            "diagnostic_accuracy_at_0p5":
                diagnostic_accuracy,

            "predicted_attack_fraction_at_0p5":
                predicted_attack_fraction,

            "predicted_benign_fraction_at_0p5":
                predicted_benign_fraction,

            "actual_attack_windows":
                actual_attack_count,

            "actual_benign_windows":
                actual_benign_count,

            "examples":
                total_examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            !=
            epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "precision":
                "float32",

            "imbalance_method":
                IMBALANCE_METHOD,

            "model_state_dict":
                FINETUNE_MODEL_L100
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| BCE={mean_loss:.6f} "
            f"| diagnostic_acc@0.5="
            f"{diagnostic_accuracy:.4f} "
            f"| predicted_attack="
            f"{predicted_attack_fraction:.4f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "lambda=1.00 fine-tuning already "
        "contains all 20 epochs."
    )


# ======================================================================
# 14 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[6] Last 5 lambda=1.00 fine-tuning epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 15 — NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            p
        ).all()
    )

    for p in FINETUNE_MODEL_L100.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=64,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


FINETUNE_MODEL_L100.eval()


with torch.no_grad():

    check_logits = (
        FINETUNE_MODEL_L100
        .forward_classifier(
            X_check
        )
    )


    check_probabilities = (
        torch.sigmoid(
            check_logits
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        check_logits
    ).all()

    and

    torch.isfinite(
        check_probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    (
        check_probabilities
        >=
        0
    ).all()

    and

    (
        check_probabilities
        <=
        1
    ).all()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 16 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        FINETUNE_MODEL_L100
        .state_dict(),

    "experiment":
        "lambda_t_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A28_VALID = bool(

    COMPLETED_EPOCHS
    ==
    20

    and

    NONFINITE_BATCHES
    ==
    0

    and

    not PROJECTION_INCLUDED

    and

    not ORDER_HEAD_INCLUDED

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_28_LAMBDA_100_FINETUNE_VALID = (
    A28_VALID
)


print("\n[8] Step A28 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Completed fine-tuning epochs   :",
    COMPLETED_EPOCHS,
    "/ 20"
)

print(
    "Training windows               :",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Projection head optimized      :",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized  :",
    ORDER_HEAD_INCLUDED
)

print(
    "Threshold selected             :",
    False
)

print(
    "Known-test used                :",
    False
)

print(
    "Benign-test used               :",
    False
)

print(
    "Zero-day DDoS used             :",
    False
)

print(
    "Final BCE                      :",
    f"{float(FINAL_ROW['training_BCE_loss']):.6f}"
)

print(
    "Diagnostic accuracy @ 0.5      :",
    f"{float(FINAL_ROW['diagnostic_accuracy_at_0p5']):.6f}"
)

print(
    "Predicted attack fraction      :",
    f"{float(FINAL_ROW['predicted_attack_fraction_at_0p5']):.6f}"
)

print(
    "Predicted benign fraction      :",
    f"{float(FINAL_ROW['predicted_benign_fraction_at_0p5']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A28_VALID:

    print(
        "✅ STEP A28 PASSED — "
        "lambda_t=1.00 completed controlled "
        "20-epoch supervised fine-tuning."
    )

else:

    print(
        "❌ STEP A28 INCOMPLETE — "
        "rerun this same cell to resume."
    )

print("=" * 78)

==============================================================================
STEP A28 — SUPERVISED FINE-TUNING | lambda_t = 1.00
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 data valid: True
A14 architecture valid: True
A20 protocol valid: True
A27 lambda=1.00 SSL valid: True
Training windows: 105,577
Device: cuda

[2] Controlled fine-tuning configuration
------------------------------------------------------------------------------
lambda_t: 1.0
Seed: 13
Epochs: 20
Batch size: 256
Learning rate: 0.001
Precision: float32
Imbalance method: none
Gradient clipping: 5.0

[3] Loading lambda=1.00 SSL-pretrained encoder
------------------------------------------------------------------------------
SSL epochs: 30
SSL lambda_t: 1.0
SSL precision: float32
Labels used during SSL: False
lambda=1.00 SSL state loaded: True
Classifier freshly initialized: True
Classifier initialization seed: 1013
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[4] Checking lambda=1.00 fine-tuning checkpoint
------------------------------------------------------------------------------
No lambda=1.00 fine-tuning checkpoint.
Starting from epoch 1.

[5] Starting lambda=1.00 supervised fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/413 | BCE 0.127361
Epoch 01/20 | Batch 200/413 | BCE 0.141507
Epoch 01/20 | Batch 300/413 | BCE 0.086403
Epoch 01/20 | Batch 400/413 | BCE 0.086421
Epoch 01/20 | Batch 413/413 | BCE 0.087185

Epoch 01 complete | BCE=0.127242 | diagnostic_acc@0.5=0.9467 | predicted_attack=0.9423 | time=8.7s | checkpoint=Drive
Epoch 02/20 | Batch 100/413 | BCE 0.092759
Epoch 02/20 | Batch 200/413 | BCE 0.078755
Epoch 02/20 | Batch 300/413 | BCE 0.082469
Epoch 02/20 | Batch 400/413 | BCE 0.085275
Epoch 02/20 | Batch 413/413 | BCE 0.087873

Epoch 02 complete | BCE=0.073521 | diagnostic_acc@0.5=0.9673 | predicted_attack=0.9272 | time=5.3s | checkpoint=Drive
Epoch 03/20 | Batch 100/413 | BCE 0.067074
Epoch 03/20 | Batch 200/413 | BCE 0.053930
Epoch 03/20 | Batch 300/413 | BCE 0.060816
Epoch 03/20 | Batch 400/413 | BCE 0.049430
Epoch 03/20 | Batch 413/413 | BCE 0.062043

Epoch 03 complete | BCE=0.062762 | diagnostic_acc@0.5=0.9723 | predicted_attack=0.9265 | time=4.1s | checkpoint=Drive
Epoch 04/20 | Batch 100/413 | BCE 0.044325
Epoch 04/20 | Batch 200/413 | BCE 0.065686
Epoch 04/20 | Batch 300/413 | BCE 0.054790
Epoch 04/20 | Batch 400/413 | BCE 0.058284
Epoch 04/20 | Batch 413/413 | BCE 0.112296

Epoch 04 complete | BCE=0.055654 | diagnostic_acc@0.5=0.9756 | predicted_attack=0.9254 | time=4.7s | checkpoint=Drive
Epoch 05/20 | Batch 100/413 | BCE 0.062377
Epoch 05/20 | Batch 200/413 | BCE 0.042131
Epoch 05/20 | Batch 300/413 | BCE 0.076184
Epoch 05/20 | Batch 400/413 | BCE 0.090890
Epoch 05/20 | Batch 413/413 | BCE 0.034892

Epoch 05 complete | BCE=0.048807 | diagnostic_acc@0.5=0.9790 | predicted_attack=0.9248 | time=3.8s | checkpoint=Drive
Epoch 06/20 | Batch 100/413 | BCE 0.019553
Epoch 06/20 | Batch 200/413 | BCE 0.090902
Epoch 06/20 | Batch 300/413 | BCE 0.053378
Epoch 06/20 | Batch 400/413 | BCE 0.035977
Epoch 06/20 | Batch 413/413 | BCE 0.060324

Epoch 06 complete | BCE=0.044700 | diagnostic_acc@0.5=0.9808 | predicted_attack=0.9248 | time=3.8s | checkpoint=Drive
Epoch 07/20 | Batch 100/413 | BCE 0.037625
Epoch 07/20 | Batch 200/413 | BCE 0.041018
Epoch 07/20 | Batch 300/413 | BCE 0.026656
Epoch 07/20 | Batch 400/413 | BCE 0.062773
Epoch 07/20 | Batch 413/413 | BCE 0.037337

Epoch 07 complete | BCE=0.040558 | diagnostic_acc@0.5=0.9827 | predicted_attack=0.9249 | time=4.9s | checkpoint=Drive
Epoch 08/20 | Batch 100/413 | BCE 0.022156
Epoch 08/20 | Batch 200/413 | BCE 0.053512
Epoch 08/20 | Batch 300/413 | BCE 0.017968
Epoch 08/20 | Batch 400/413 | BCE 0.025995
Epoch 08/20 | Batch 413/413 | BCE 0.048172

Epoch 08 complete | BCE=0.036331 | diagnostic_acc@0.5=0.9844 | predicted_attack=0.9243 | time=3.9s | checkpoint=Drive
Epoch 09/20 | Batch 100/413 | BCE 0.026241
Epoch 09/20 | Batch 200/413 | BCE 0.025901
Epoch 09/20 | Batch 300/413 | BCE 0.025735
Epoch 09/20 | Batch 400/413 | BCE 0.034829
Epoch 09/20 | Batch 413/413 | BCE 0.028391

Epoch 09 complete | BCE=0.031985 | diagnostic_acc@0.5=0.9866 | predicted_attack=0.9241 | time=3.8s | checkpoint=Drive
Epoch 10/20 | Batch 100/413 | BCE 0.029115
Epoch 10/20 | Batch 200/413 | BCE 0.028903
Epoch 10/20 | Batch 300/413 | BCE 0.011955
Epoch 10/20 | Batch 400/413 | BCE 0.031605
Epoch 10/20 | Batch 413/413 | BCE 0.041380

Epoch 10 complete | BCE=0.030118 | diagnostic_acc@0.5=0.9875 | predicted_attack=0.9246 | time=4.4s | checkpoint=Drive
Epoch 11/20 | Batch 100/413 | BCE 0.009914
Epoch 11/20 | Batch 200/413 | BCE 0.035282
Epoch 11/20 | Batch 300/413 | BCE 0.023553
Epoch 11/20 | Batch 400/413 | BCE 0.049845
Epoch 11/20 | Batch 413/413 | BCE 0.018007

Epoch 11 complete | BCE=0.026592 | diagnostic_acc@0.5=0.9889 | predicted_attack=0.9244 | time=4.3s | checkpoint=Drive
Epoch 12/20 | Batch 100/413 | BCE 0.028041
Epoch 12/20 | Batch 200/413 | BCE 0.026680
Epoch 12/20 | Batch 300/413 | BCE 0.029734
Epoch 12/20 | Batch 400/413 | BCE 0.017191
Epoch 12/20 | Batch 413/413 | BCE 0.008035

Epoch 12 complete | BCE=0.024159 | diagnostic_acc@0.5=0.9898 | predicted_attack=0.9241 | time=3.9s | checkpoint=Drive
Epoch 13/20 | Batch 100/413 | BCE 0.052920
Epoch 13/20 | Batch 200/413 | BCE 0.018361
Epoch 13/20 | Batch 300/413 | BCE 0.017131
Epoch 13/20 | Batch 400/413 | BCE 0.031492
Epoch 13/20 | Batch 413/413 | BCE 0.019488

Epoch 13 complete | BCE=0.022532 | diagnostic_acc@0.5=0.9905 | predicted_attack=0.9242 | time=4.0s | checkpoint=Drive
Epoch 14/20 | Batch 100/413 | BCE 0.023456
Epoch 14/20 | Batch 200/413 | BCE 0.009954
Epoch 14/20 | Batch 300/413 | BCE 0.015859
Epoch 14/20 | Batch 400/413 | BCE 0.007032
Epoch 14/20 | Batch 413/413 | BCE 0.015286

Epoch 14 complete | BCE=0.020295 | diagnostic_acc@0.5=0.9912 | predicted_attack=0.9242 | time=4.8s | checkpoint=Drive
Epoch 15/20 | Batch 100/413 | BCE 0.003686
Epoch 15/20 | Batch 200/413 | BCE 0.029705
Epoch 15/20 | Batch 300/413 | BCE 0.015671
Epoch 15/20 | Batch 400/413 | BCE 0.021548
Epoch 15/20 | Batch 413/413 | BCE 0.005439

Epoch 15 complete | BCE=0.018369 | diagnostic_acc@0.5=0.9921 | predicted_attack=0.9241 | time=3.9s | checkpoint=Drive
Epoch 16/20 | Batch 100/413 | BCE 0.040710
Epoch 16/20 | Batch 200/413 | BCE 0.011548
Epoch 16/20 | Batch 300/413 | BCE 0.005021
Epoch 16/20 | Batch 400/413 | BCE 0.015220
Epoch 16/20 | Batch 413/413 | BCE 0.004743

Epoch 16 complete | BCE=0.016842 | diagnostic_acc@0.5=0.9929 | predicted_attack=0.9238 | time=3.9s | checkpoint=Drive
Epoch 17/20 | Batch 100/413 | BCE 0.008427
Epoch 17/20 | Batch 200/413 | BCE 0.003981
Epoch 17/20 | Batch 300/413 | BCE 0.009701
Epoch 17/20 | Batch 400/413 | BCE 0.011493
Epoch 17/20 | Batch 413/413 | BCE 0.031135

Epoch 17 complete | BCE=0.015564 | diagnostic_acc@0.5=0.9936 | predicted_attack=0.9240 | time=4.7s | checkpoint=Drive
Epoch 18/20 | Batch 100/413 | BCE 0.021812
Epoch 18/20 | Batch 200/413 | BCE 0.015679
Epoch 18/20 | Batch 300/413 | BCE 0.033106
Epoch 18/20 | Batch 400/413 | BCE 0.019045
Epoch 18/20 | Batch 413/413 | BCE 0.000099

Epoch 18 complete | BCE=0.014186 | diagnostic_acc@0.5=0.9943 | predicted_attack=0.9241 | time=4.0s | checkpoint=Drive
Epoch 19/20 | Batch 100/413 | BCE 0.027952
Epoch 19/20 | Batch 200/413 | BCE 0.001877
Epoch 19/20 | Batch 300/413 | BCE 0.007620
Epoch 19/20 | Batch 400/413 | BCE 0.012686
Epoch 19/20 | Batch 413/413 | BCE 0.011655

Epoch 19 complete | BCE=0.012588 | diagnostic_acc@0.5=0.9949 | predicted_attack=0.9238 | time=3.9s | checkpoint=Drive
Epoch 20/20 | Batch 100/413 | BCE 0.019987
Epoch 20/20 | Batch 200/413 | BCE 0.006288
Epoch 20/20 | Batch 300/413 | BCE 0.010802
Epoch 20/20 | Batch 400/413 | BCE 0.014078
Epoch 20/20 | Batch 413/413 | BCE 0.049094

Epoch 20 complete | BCE=0.012366 | diagnostic_acc@0.5=0.9952 | predicted_attack=0.9241 | time=4.3s | checkpoint=Drive

[6] Last 5 lambda=1.00 fine-tuning epochs
------------------------------------------------------------------------------

,epoch,lambda_t,training_BCE_loss,diagnostic_accuracy_at_0p5,predicted_attack_fraction_at_0p5,predicted_benign_fraction_at_0p5,actual_attack_windows,actual_benign_windows,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
15,16,1.0,0.016842,0.992934,0.923828,0.076172,97571,8006,105577,413,0.913896,3.856598
16,17,1.0,0.015564,0.993588,0.924027,0.075973,97571,8006,105577,413,1.095966,4.682114
17,18,1.0,0.014186,0.994298,0.924074,0.075926,97571,8006,105577,413,0.738761,4.023506
18,19,1.0,0.012588,0.994923,0.923752,0.076248,97571,8006,105577,413,0.876703,3.872568
19,20,1.0,0.012366,0.995150,0.924112,0.075888,97571,8006,105577,413,0.920079,4.274007

[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
Parameters finite: True
Outputs finite: True
Probability range valid: True

[8] Step A28 validation
------------------------------------------------------------------------------
lambda_t                       : 1.0
Completed fine-tuning epochs   : 20 / 20
Training windows               : 105,577
Imbalance method               : none
Projection head optimized      : False
Temporal-order head optimized  : False
Threshold selected             : False
Known-test used                : False
Benign-test used               : False
Zero-day DDoS used             : False
Final BCE                      : 0.012366
Diagnostic accuracy @ 0.5      : 0.995150
Predicted attack fraction      : 0.924112
Predicted benign fraction      : 0.075888
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A28 PASSED — lambda_t=1.00 completed controlled 20-epoch supervised fine-tuning.
==============================================================================

# Step A29 — Validate λₜ = 1.00 and formally select λ

In [ ]:
# ======================================================================
# STEP A29
# lambda_t = 1.00 DEVELOPMENT VALIDATION
# + FINAL lambda_t SELECTION
#
# Fold 1: DDoS held out
#
# Selection uses DEVELOPMENT VALIDATION ONLY.
#
# NO known-test access.
# NO benign-test access.
# NO zero-day DDoS access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    accuracy_score,
    average_precision_score,
    roc_auc_score
)


print("=" * 78)
print("STEP A29 — VALIDATION + FINAL LAMBDA SELECTION")
print("lambda_t = 1.00 | FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_20_LAMBDA_PROTOCOL_VALID",
    "STEP_28_LAMBDA_100_FINETUNE_VALID",
    "MOTSSLGRU",
    "DEVICE"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_20_LAMBDA_PROTOCOL_VALID:
    raise RuntimeError("A20 did not pass.")

if not STEP_28_LAMBDA_100_FINETUNE_VALID:
    raise RuntimeError("A28 did not pass.")


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A20 lambda protocol valid:",
    STEP_20_LAMBDA_PROTOCOL_VALID
)

print(
    "A28 lambda=1.00 fine-tuning valid:",
    STEP_28_LAMBDA_100_FINETUNE_VALID
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

LAMBDA_T = 1.00

SEED = 13

EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


print("\n[2] Validation configuration")
print("-" * 78)

print(
    "lambda_t:",
    LAMBDA_T
)

print(
    "Seed:",
    SEED
)

print(
    "Expected validation windows:",
    f"{EXPECTED_WINDOWS:,}"
)

print(
    "Expected benign windows:",
    f"{EXPECTED_BENIGN:,}"
)

print(
    "Expected attack windows:",
    f"{EXPECTED_ATTACK:,}"
)

print(
    "Threshold rule:",
    "maximize development-validation F1"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_1p00_fp32"
    / "imbalance_none"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


REGISTRY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "fold_01_lambda_t_experiment_registry.csv"
)


POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "fold_01_lambda_t_selection_policy.json"
)


for path in [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    MODEL_PATH,
    REGISTRY_PATH,
    POLICY_PATH
]:

    if not path.exists():

        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 4 — VERIFY FROZEN A20 POLICY
# ======================================================================

print("\n[3] Verifying frozen A20 protocol")
print("-" * 78)


with open(
    POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:

    selection_policy = json.load(
        file
    )


if (
    selection_policy[
        "selection_data"
    ]
    !=
    "development_validation_only"
):

    raise RuntimeError(
        "Selection partition does not match A20."
    )


if selection_policy[
    "test_data_allowed_for_lambda_selection"
]:

    raise RuntimeError(
        "A20 incorrectly permits test-data selection."
    )


if selection_policy[
    "zero_day_data_allowed_for_lambda_selection"
]:

    raise RuntimeError(
        "A20 incorrectly permits zero-day selection."
    )


print(
    "Primary metric:",
    selection_policy[
        "lambda_primary_selection_metric"
    ]
)

print(
    "Tie-break 1:",
    selection_policy[
        "lambda_tiebreak_1"
    ]
)

print(
    "Tie-break 2:",
    selection_policy[
        "lambda_tiebreak_2"
    ]
)

print(
    "Test data allowed:",
    False
)

print(
    "Zero-day data allowed:",
    False
)


# ======================================================================
# 5 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[4] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        "Expected 75 retained features."
    )


parameter_lookup = (

    parameters

    .set_index(
        "feature"
    )

    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing invalid."
    )


# ======================================================================
# 6 — DEVELOPMENT VALIDATION MANIFEST
# ======================================================================

print("\n[5] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_validation"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


MANIFEST_WINDOWS = int(

    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDOS_WINDOWS = int(

    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation source ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{MANIFEST_WINDOWS:,}"
)

print(
    "DDoS validation windows:",
    DDOS_WINDOWS
)


if len(VAL_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if MANIFEST_WINDOWS != EXPECTED_WINDOWS:

    raise RuntimeError(
        "Validation window-count mismatch."
    )


if DDOS_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 7 — LOAD lambda=1.00 FINE-TUNED MODEL
# ======================================================================

print("\n[6] Loading lambda=1.00 model")
print("-" * 78)


model_package = torch.load(
    MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        model_package[
            "SSL_lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Fine-tuned model lambda mismatch."
    )


if model_package.get(
    "threshold_selected"
):

    raise RuntimeError(
        "Model already indicates threshold selection."
    )


MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


MODEL.eval()


MODEL_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter in MODEL.parameters()
)


print(
    "Loaded lambda_t:",
    model_package[
        "SSL_lambda_t"
    ]
)

print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Model parameters finite:",
    MODEL_FINITE
)


if not MODEL_FINITE:

    raise RuntimeError(
        "Model parameters are non-finite."
    )


# ======================================================================
# 8 — FROZEN PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(table):

    X = (

        table

        .to_pandas()

        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        rows, cols = np.where(
            bad_mask
        )


        X[
            rows,
            cols
        ] = IMPUTE_VALUES[
            cols
        ]


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite transformed values."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite float32 values."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 9 — MODEL INFERENCE
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(windows):

    probability_parts = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,
            len(windows)
        )


        X = torch.from_numpy(

            windows[
                start:stop
            ]

        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                MODEL
                .forward_classifier(
                    X
                )
            )


            probabilities = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                probabilities
            ).all()
        ):

            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        probability_parts.append(

            probabilities

            .detach()

            .cpu()

            .numpy()

            .astype(
                np.float64
            )
        )


    return np.concatenate(
        probability_parts
    )


# ======================================================================
# 10 — RUN VALIDATION INFERENCE
# ======================================================================

print("\n[7] Running lambda=1.00 validation inference")
print("-" * 78)


prediction_parts = []

TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    family = str(
        row[
            "research_family"
        ]
    )


    target = int(
        row[
            "binary_target"
        ]
    )


    partition_start = int(
        row[
            "partition_start_row"
        ]
    )


    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    expected_windows = int(
        row[
            "window_count"
        ]
    )


    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )


    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():

        raise RuntimeError(
            f"Missing Parquet: {parquet_name}"
        )


    if family == "DDoS":

        raise RuntimeError(
            "Held-out DDoS reached validation inference."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probability_parts = []

    source_raw_nonfinite = 0

    absolute_row = 0


    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(

            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row

        group_end = (
            group_start
            +
            row_group_rows
        )


        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(

            row_group_index,

            columns=RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(

            local_start,

            local_end
            -
            local_start
        )


        Z, bad_count = frozen_preprocess(
            table
        )


        source_raw_nonfinite += bad_count


        if len(pending) > 0:

            Z = np.concatenate(
                [
                    pending,
                    Z
                ],
                axis=0
            )


        complete_windows = (
            len(Z)
            //
            8
        )


        complete_rows = (
            complete_windows
            *
            8
        )


        if complete_windows > 0:

            windows = (

                Z[
                    :complete_rows
                ]

                .reshape(
                    complete_windows,
                    8,
                    75
                )
            )


            probabilities = predict_windows(
                windows
            )


            source_probability_parts.append(
                probabilities
            )


        pending = (

            Z[
                complete_rows:
            ]

            .copy()
        )


    if source_probability_parts:

        source_probabilities = np.concatenate(
            source_probability_parts
        )

    else:

        source_probabilities = np.empty(
            0,
            dtype=np.float64
        )


    actual_windows = int(
        len(
            source_probabilities
        )
    )


    actual_tail = int(
        len(
            pending
        )
    )


    source_valid = bool(

        actual_windows
        ==
        expected_windows

        and

        actual_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()

        and

        (
            (
                source_probabilities >= 0
            )
            &
            (
                source_probabilities <= 1
            )
        ).all()
    )


    SOURCE_CHECKS_VALID &= source_valid


    if not source_valid:

        raise RuntimeError(
            f"Validation construction mismatch "
            f"for {source_class}."
        )


    prediction_parts.append(

        pd.DataFrame({

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                target,

            "malicious_probability":
                source_probabilities
        })
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={actual_windows:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 11 — COMBINE VALIDATION PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (

    VALIDATION_PREDICTIONS[
        "binary_target"
    ]

    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (

    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


COUNTS_VALID = bool(

    len(
        y_true
    )
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDOS_WINDOWS
    ==
    0
)


print("\n[8] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(y_true):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDOS_WINDOWS
)

print(
    "Raw non-finite values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{time.time() - inference_start:.2f} seconds"
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Validation counts are invalid."
    )


# ======================================================================
# 12 — THRESHOLD SEARCH FOR lambda=1.00
# ======================================================================

print("\n[9] Selecting lambda=1.00 validation threshold")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (

    2.0
    *
    threshold_precision
    *
    threshold_recall

    /

    np.maximum(
        threshold_precision
        +
        threshold_recall,
        1e-15
    )
)


MAX_F1 = float(
    np.max(
        threshold_f1
    )
)


candidate_indices = np.flatnonzero(

    np.isclose(
        threshold_f1,
        MAX_F1,
        rtol=0.0,
        atol=1e-12
    )
)


BEST_THRESHOLD_INDEX = int(

    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_THRESHOLD_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Threshold tie-break:",
    "highest threshold"
)


# ======================================================================
# 13 — VALIDATION METRICS
# ======================================================================

predictions = (

    y_probability

    >=

    SELECTED_THRESHOLD

).astype(
    np.int64
)


tn, fp, fn, tp = (

    confusion_matrix(
        y_true,
        predictions,
        labels=[
            0,
            1
        ]
    ).ravel()
)


VALIDATION_PRECISION = float(

    precision_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_RECALL = float(

    recall_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_F1 = float(

    f1_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_FPR = float(

    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_ACCURACY = float(

    accuracy_score(
        y_true,
        predictions
    )
)


VALIDATION_PR_AUC = float(

    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(

    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[10] lambda=1.00 validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "TP:",
    int(tp)
)

print(
    "TN:",
    int(tn)
)

print(
    "FP:",
    int(fp)
)

print(
    "FN:",
    int(fn)
)

print(
    "Precision:",
    f"{VALIDATION_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "F1:",
    f"{VALIDATION_F1:.10f}"
)

print(
    "FPR:",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{VALIDATION_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 14 — SAVE lambda=1.00 VALIDATION ARTIFACTS
# ======================================================================

OUTPUT_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "lambda_1p00"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    OUTPUT_DIR
    / "development_validation_predictions.csv"
)


THRESHOLD_CURVE_PATH = (
    OUTPUT_DIR
    / "validation_threshold_search.csv"
)


RESULT_PATH = (
    OUTPUT_DIR
    / "validation_result.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = predictions


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


threshold_table = pd.DataFrame({

    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1
})


threshold_table.to_csv(
    THRESHOLD_CURVE_PATH,
    index=False
)


validation_result = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(
                y_true
            )
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        VALIDATION_PRECISION,

    "validation_recall":
        VALIDATION_RECALL,

    "validation_F1":
        VALIDATION_F1,

    "validation_FPR":
        VALIDATION_FPR,

    "validation_accuracy":
        VALIDATION_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "selection_rule":
        "maximize_validation_F1",

    "threshold_tiebreak":
        "highest_threshold",

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    RESULT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        validation_result,
        file,
        indent=4
    )


# ======================================================================
# 15 — UPDATE REGISTRY TO 4/4
# ======================================================================

print("\n[11] Updating lambda registry")
print("-" * 78)


registry = pd.read_csv(
    REGISTRY_PATH
)


lambda_mask = np.isclose(

    registry[
        "lambda_t"
    ].to_numpy(
        dtype=float
    ),

    LAMBDA_T
)


if int(
    lambda_mask.sum()
) != 1:

    raise RuntimeError(
        "Could not uniquely identify lambda=1.00."
    )


registry.loc[
    lambda_mask,
    "status"
] = "validation_complete"


registry.loc[
    lambda_mask,
    "selected_threshold"
] = SELECTED_THRESHOLD


registry.loc[
    lambda_mask,
    "validation_F1"
] = VALIDATION_F1


registry.loc[
    lambda_mask,
    "validation_FPR"
] = VALIDATION_FPR


registry.loc[
    lambda_mask,
    "validation_recall"
] = VALIDATION_RECALL


registry.loc[
    lambda_mask,
    "test_metrics_used_for_selection"
] = False


registry.loc[
    lambda_mask,
    "zero_day_metrics_used_for_selection"
] = False


completed_configs = int(

    (
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


if completed_configs != 4:

    raise RuntimeError(
        f"Expected 4 completed lambda configs, "
        f"found {completed_configs}."
    )


# ======================================================================
# 16 — FINAL lambda_t SELECTION
#
# Frozen A20 rule:
# 1) highest validation F1
# 2) lower validation FPR
# 3) smaller lambda_t
# ======================================================================

print("\n[12] Applying frozen A20 lambda-selection rule")
print("-" * 78)


selection_table = (

    registry.loc[
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ]

    .copy()

    .sort_values(

        by=[
            "validation_F1",
            "validation_FPR",
            "lambda_t"
        ],

        ascending=[
            False,
            True,
            True
        ],

        kind="mergesort"
    )

    .reset_index(
        drop=True
    )
)


if len(selection_table) != 4:

    raise RuntimeError(
        "Selection table does not contain four lambdas."
    )


if selection_table[
    [
        "validation_F1",
        "validation_FPR",
        "lambda_t"
    ]
].isna().any().any():

    raise RuntimeError(
        "Lambda-selection metrics contain NaN."
    )


SELECTED_LAMBDA_T = float(

    selection_table.loc[
        0,
        "lambda_t"
    ]
)


SELECTED_LAMBDA_THRESHOLD = float(

    selection_table.loc[
        0,
        "selected_threshold"
    ]
)


SELECTED_LAMBDA_F1 = float(

    selection_table.loc[
        0,
        "validation_F1"
    ]
)


SELECTED_LAMBDA_FPR = float(

    selection_table.loc[
        0,
        "validation_FPR"
    ]
)


SELECTED_LAMBDA_RECALL = float(

    selection_table.loc[
        0,
        "validation_recall"
    ]
)


print(
    selection_table[
        [
            "lambda_t",
            "selected_threshold",
            "validation_F1",
            "validation_FPR",
            "validation_recall"
        ]
    ].to_string(
        index=False
    )
)


print(
    "\nSelected lambda_t:",
    SELECTED_LAMBDA_T
)

print(
    "Selected validation F1:",
    f"{SELECTED_LAMBDA_F1:.10f}"
)

print(
    "Selected validation FPR:",
    f"{SELECTED_LAMBDA_FPR:.10f}"
)

print(
    "Selected validation recall:",
    f"{SELECTED_LAMBDA_RECALL:.10f}"
)


# ======================================================================
# 17 — MARK SELECTED CONFIGURATION IN REGISTRY
# ======================================================================

registry[
    "selected_for_primary"
] = np.isclose(

    registry[
        "lambda_t"
    ].to_numpy(
        dtype=float
    ),

    SELECTED_LAMBDA_T
)


registry.to_csv(
    REGISTRY_PATH,
    index=False
)


# ======================================================================
# 18 — SAVE FINAL SELECTION ARTIFACT
# ======================================================================

SELECTION_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "selected_lambda_t.json"
)


SELECTION_TABLE_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "lambda_t_validation_ranking.csv"
)


selection_table.to_csv(
    SELECTION_TABLE_PATH,
    index=False
)


selection_record = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        13,

    "candidate_lambdas":
        [
            0.10,
            0.25,
            0.50,
            1.00
        ],

    "completed_candidates":
        4,

    "selection_partition":
        "development_validation_only",

    "primary_selection_metric":
        "validation_F1",

    "primary_direction":
        "higher_is_better",

    "tiebreak_1":
        "lower_validation_FPR",

    "tiebreak_2":
        "smaller_lambda_t",

    "selected_lambda_t":
        SELECTED_LAMBDA_T,

    "selected_threshold":
        SELECTED_LAMBDA_THRESHOLD,

    "selected_validation_F1":
        SELECTED_LAMBDA_F1,

    "selected_validation_FPR":
        SELECTED_LAMBDA_FPR,

    "selected_validation_recall":
        SELECTED_LAMBDA_RECALL,

    "known_test_used_for_selection":
        False,

    "benign_test_used_for_selection":
        False,

    "zero_day_DDoS_used_for_selection":
        False,

    "previous_lambda_0p25_A18_test_result_used":
        False,

    "selection_finalized":
        True
}


with open(
    SELECTION_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        selection_record,
        file,
        indent=4
    )


# ======================================================================
# 19 — LOCAL BACKUP COPIES
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/lambda_t/"
    "fold_01_DDoS"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


shutil.copy2(
    REGISTRY_PATH,
    LOCAL_DIR
    / REGISTRY_PATH.name
)


shutil.copy2(
    SELECTION_PATH,
    LOCAL_DIR
    / SELECTION_PATH.name
)


shutil.copy2(
    SELECTION_TABLE_PATH,
    LOCAL_DIR
    / SELECTION_TABLE_PATH.name
)


# ======================================================================
# 20 — FINAL VALIDATION
# ======================================================================

REGISTRY_VALID = bool(

    completed_configs
    ==
    4

    and

    int(
        registry[
            "selected_for_primary"
        ].sum()
    )
    ==
    1
)


SELECTION_VALID = bool(

    SELECTED_LAMBDA_T
    in
    [
        0.10,
        0.25,
        0.50,
        1.00
    ]

    and

    np.isfinite(
        SELECTED_LAMBDA_F1
    )

    and

    np.isfinite(
        SELECTED_LAMBDA_FPR
    )

    and

    np.isfinite(
        SELECTED_LAMBDA_THRESHOLD
    )
)


ARTIFACTS_VALID = bool(

    PREDICTIONS_PATH.exists()

    and

    THRESHOLD_CURVE_PATH.exists()

    and

    RESULT_PATH.exists()

    and

    REGISTRY_PATH.exists()

    and

    SELECTION_PATH.exists()

    and

    SELECTION_TABLE_PATH.exists()
)


A29_VALID = bool(

    COUNTS_VALID

    and

    SOURCE_CHECKS_VALID

    and

    PREPROCESSING_VALID

    and

    MODEL_FINITE

    and

    DDOS_WINDOWS == 0

    and

    REGISTRY_VALID

    and

    SELECTION_VALID

    and

    ARTIFACTS_VALID
)


STEP_29_LAMBDA_SELECTION_VALID = (
    A29_VALID
)


FINAL_SELECTED_LAMBDA_T = (
    SELECTED_LAMBDA_T
)


print("\n[13] Step A29 validation")
print("-" * 78)

print(
    "lambda=1.00 validation windows :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDOS_WINDOWS
)

print(
    "lambda=1.00 selected threshold :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "lambda=1.00 validation F1       :",
    f"{VALIDATION_F1:.10f}"
)

print(
    "lambda=1.00 validation FPR      :",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Completed lambda configs       :",
    completed_configs,
    "/ 4"
)

print(
    "FINAL selected lambda_t        :",
    SELECTED_LAMBDA_T
)

print(
    "Selected lambda validation F1  :",
    f"{SELECTED_LAMBDA_F1:.10f}"
)

print(
    "Selected lambda validation FPR :",
    f"{SELECTED_LAMBDA_FPR:.10f}"
)

print(
    "Known-test used for selection  :",
    False
)

print(
    "Benign-test used for selection :",
    False
)

print(
    "Zero-day used for selection    :",
    False
)

print(
    "Registry valid                 :",
    REGISTRY_VALID
)

print(
    "Selection artifact saved       :",
    SELECTION_PATH.exists()
)

print(
    "Ranking artifact saved         :",
    SELECTION_TABLE_PATH.exists()
)


print("\n" + "=" * 78)

if A29_VALID:

    print(
        "✅ STEP A29 PASSED — "
        "all four lambda_t candidates are complete "
        "and the final lambda_t was selected using "
        "development validation only."
    )

else:

    print(
        "❌ STEP A29 FAILED — "
        "do not proceed to the next experiment block."
    )

print("=" * 78)

==============================================================================
STEP A29 — VALIDATION + FINAL LAMBDA SELECTION
lambda_t = 1.00 | FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A20 lambda protocol valid: True
A28 lambda=1.00 fine-tuning valid: True
Device: cuda

[2] Validation configuration
------------------------------------------------------------------------------
lambda_t: 1.0
Seed: 13
Expected validation windows: 167,482
Expected benign windows: 1,715
Expected attack windows: 165,767
Threshold rule: maximize development-validation F1

[3] Verifying frozen A20 protocol
------------------------------------------------------------------------------
Primary metric: development_validation_F1
Tie-break 1: lower_development_validation_FPR
Tie-break 2: smaller_lambda_t
Test data allowed: False
Zero-day data allowed: False

[4] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Preprocessing refitted: False

[5] Loading development-validation manifest
------------------------------------------------------------------------------
Validation source ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[6] Loading lambda=1.00 model
------------------------------------------------------------------------------
Loaded lambda_t: 1.0
Fine-tuning epochs: 20
Imbalance method: none
Model parameters finite: True

[7] Running lambda=1.00 validation inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[8] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite values imputed: 1,516
All source checks valid: True
Probability min: 0.0000000000
Probability max: 1.0000000000
Inference runtime: 5.88 seconds

[9] Selecting lambda=1.00 validation threshold
------------------------------------------------------------------------------
Threshold candidates: 5,118
Maximum validation F1: 0.9971159149
Selected threshold: 0.0069161612
Max-F1 tie count: 1
Threshold tie-break: highest threshold

[10] lambda=1.00 validation metrics
------------------------------------------------------------------------------
Threshold: 0.0069161612
TP: 165432
TN: 1093
FP: 622
FN: 335
Precision: 0.9962542306
Recall: 0.9979790911
F1: 0.9971159149
FPR: 0.3626822157
Accuracy: 0.9942859531
PR-AUC: 0.9999667781
ROC-AUC: 0.9970981645

[11] Updating lambda registry
------------------------------------------------------------------------------

[12] Applying frozen A20 lambda-selection rule
------------------------------------------------------------------------------
 lambda_t  selected_threshold  validation_F1  validation_FPR  validation_recall
     0.25            0.014751       0.997267        0.365598           0.998311
     0.50            0.002280       0.997126        0.387755           0.998257
     0.10            0.002184       0.997122        0.377843           0.998148
     1.00            0.006916       0.997116        0.362682           0.997979

Selected lambda_t: 0.25
Selected validation F1: 0.9972670927
Selected validation FPR: 0.3655976676
Selected validation recall: 0.9983108821

[13] Step A29 validation
------------------------------------------------------------------------------
lambda=1.00 validation windows : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
lambda=1.00 selected threshold : 0.0069161612
lambda=1.00 validation F1       : 0.9971159149
lambda=1.00 validation FPR      : 0.3626822157
Completed lambda configs       : 4 / 4
FINAL selected lambda_t        : 0.25
Selected lambda validation F1  : 0.9972670927
Selected lambda validation FPR : 0.3655976676
Known-test used for selection  : False
Benign-test used for selection : False
Zero-day used for selection    : False
Registry valid                 : True
Selection artifact saved       : True
Ranking artifact saved         : True

==============================================================================
✅ STEP A29 PASSED — all four lambda_t candidates are complete and the final lambda_t was selected using development validation only.
==============================================================================

# Step A30 — Freeze imbalance-handling protocol

In [ ]:
# ======================================================================
# STEP A30
# FREEZE CLASS-IMBALANCE SENSITIVITY PROTOCOL
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# FINAL lambda_t = selected value from A29
#
# Candidates:
#   1. none
#   2. class_weight
#   3. weighted_sampler
#
# Selection:
#   development validation ONLY
#
# NO test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("STEP A30 — FREEZE IMBALANCE-HANDLING SENSITIVITY PROTOCOL")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A29
# ======================================================================

print("\n[1] Verifying lambda-selection prerequisite")
print("-" * 78)


if (
    "STEP_29_LAMBDA_SELECTION_VALID"
    not in globals()
):

    raise RuntimeError(
        "STEP_29_LAMBDA_SELECTION_VALID is missing."
    )


if not STEP_29_LAMBDA_SELECTION_VALID:

    raise RuntimeError(
        "A29 did not pass."
    )


print(
    "A29 lambda selection valid:",
    STEP_29_LAMBDA_SELECTION_VALID
)


# ======================================================================
# 2 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


LAMBDA_SELECTION_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "selected_lambda_t.json"
)


if not LAMBDA_SELECTION_PATH.exists():

    raise RuntimeError(
        "A29 selected_lambda_t.json was not found."
    )


# ======================================================================
# 3 — LOAD FINAL lambda_t
# ======================================================================

print("\n[2] Loading finalized lambda_t")
print("-" * 78)


with open(
    LAMBDA_SELECTION_PATH,
    "r",
    encoding="utf-8"
) as file:

    lambda_selection = json.load(
        file
    )


if not lambda_selection.get(
    "selection_finalized",
    False
):

    raise RuntimeError(
        "Lambda selection is not finalized."
    )


FINAL_LAMBDA_T = float(
    lambda_selection[
        "selected_lambda_t"
    ]
)


FINAL_THRESHOLD_NONE = float(
    lambda_selection[
        "selected_threshold"
    ]
)


NONE_VALIDATION_F1 = float(
    lambda_selection[
        "selected_validation_F1"
    ]
)


NONE_VALIDATION_FPR = float(
    lambda_selection[
        "selected_validation_FPR"
    ]
)


NONE_VALIDATION_RECALL = float(
    lambda_selection[
        "selected_validation_recall"
    ]
)


if not np.isclose(
    FINAL_LAMBDA_T,
    0.25
):

    raise RuntimeError(
        f"Unexpected finalized lambda_t: "
        f"{FINAL_LAMBDA_T}"
    )


print(
    "Final lambda_t:",
    FINAL_LAMBDA_T
)

print(
    "Existing imbalance method:",
    "none"
)

print(
    "Existing validation F1:",
    f"{NONE_VALIDATION_F1:.10f}"
)

print(
    "Existing validation FPR:",
    f"{NONE_VALIDATION_FPR:.10f}"
)

print(
    "Existing threshold:",
    f"{FINAL_THRESHOLD_NONE:.10f}"
)


# ======================================================================
# 4 — FREEZE IMBALANCE CANDIDATES
# ======================================================================

print("\n[3] Freezing imbalance candidates")
print("-" * 78)


IMBALANCE_CANDIDATES = [
    "none",
    "class_weight",
    "weighted_sampler"
]


print(
    "Candidates:",
    IMBALANCE_CANDIDATES
)


# ======================================================================
# 5 — CREATE REGISTRY
# ======================================================================

registry_rows = []


for method in IMBALANCE_CANDIDATES:

    if method == "none":

        status = "validation_complete"

        threshold = (
            FINAL_THRESHOLD_NONE
        )

        validation_f1 = (
            NONE_VALIDATION_F1
        )

        validation_fpr = (
            NONE_VALIDATION_FPR
        )

        validation_recall = (
            NONE_VALIDATION_RECALL
        )

    else:

        status = "pending"

        threshold = np.nan

        validation_f1 = np.nan

        validation_fpr = np.nan

        validation_recall = np.nan


    registry_rows.append({

        "fold_id":
            1,

        "held_out_family":
            "DDoS",

        "seed":
            13,

        "temporal_window":
            8,

        "lambda_t":
            FINAL_LAMBDA_T,

        "imbalance_method":
            method,

        "SSL_epochs":
            30,

        "fine_tuning_epochs":
            20,

        "status":
            status,

        "selected_threshold":
            threshold,

        "validation_F1":
            validation_f1,

        "validation_FPR":
            validation_fpr,

        "validation_recall":
            validation_recall,

        "test_metrics_used_for_selection":
            False,

        "zero_day_metrics_used_for_selection":
            False
    })


REGISTRY = pd.DataFrame(
    registry_rows
)


display(
    REGISTRY
)


# ======================================================================
# 6 — FREEZE SELECTION POLICY
# ======================================================================

SELECTION_POLICY = {

    "experiment":
        "imbalance_handling_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        13,

    "temporal_window":
        8,

    "lambda_t":
        FINAL_LAMBDA_T,

    "imbalance_candidates":
        IMBALANCE_CANDIDATES,

    "selection_data":
        "development_validation_only",

    "per_candidate_threshold_selection":
        "maximize_F1_on_development_validation",

    "primary_selection_metric":
        "development_validation_F1",

    "primary_direction":
        "higher_is_better",

    "tiebreak_1":
        "lower_development_validation_FPR",

    "tiebreak_2":
        "method_priority",

    "method_priority_for_exact_tie": [
        "none",
        "class_weight",
        "weighted_sampler"
    ],

    "test_data_allowed_for_selection":
        False,

    "zero_day_data_allowed_for_selection":
        False,

    "controlled_variables": {

        "seed":
            13,

        "temporal_window":
            8,

        "lambda_t":
            FINAL_LAMBDA_T,

        "training_sample":
            "same_A11_training_sample",

        "architecture":
            "same_A14_architecture",

        "SSL_epochs":
            30,

        "fine_tuning_epochs":
            20,

        "precision":
            "float32",

        "learning_rate":
            0.001,

        "batch_size":
            256
    },

    "implementation_note": (
        "The imbalance-handling selection rule is an "
        "implementation choice and is frozen before "
        "training the remaining candidates."
    )
}


# ======================================================================
# 7 — OUTPUT PATHS
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/imbalance/"
    "fold_01_DDoS"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_REGISTRY = (
    LOCAL_DIR
    / "fold_01_imbalance_experiment_registry.csv"
)


DRIVE_REGISTRY = (
    DRIVE_DIR
    / "fold_01_imbalance_experiment_registry.csv"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fold_01_imbalance_selection_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fold_01_imbalance_selection_policy.json"
)


# ======================================================================
# 8 — SAVE ARTIFACTS
# ======================================================================

REGISTRY.to_csv(
    LOCAL_REGISTRY,
    index=False
)


shutil.copy2(
    LOCAL_REGISTRY,
    DRIVE_REGISTRY
)


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SELECTION_POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 9 — FINAL VALIDATION
# ======================================================================

candidate_count = int(
    len(
        REGISTRY
    )
)


completed_count = int(

    (
        REGISTRY[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


NONE_ROW = (

    REGISTRY.loc[
        REGISTRY[
            "imbalance_method"
        ]
        ==
        "none"
    ]

    .iloc[0]
)


PROTOCOL_VALID = bool(

    candidate_count
    ==
    3

    and

    completed_count
    ==
    1

    and

    np.isclose(
        float(
            NONE_ROW[
                "lambda_t"
            ]
        ),
        0.25
    )

    and

    np.isclose(
        float(
            NONE_ROW[
                "validation_F1"
            ]
        ),
        NONE_VALIDATION_F1
    )

    and

    not bool(
        REGISTRY[
            "test_metrics_used_for_selection"
        ].any()
    )

    and

    not bool(
        REGISTRY[
            "zero_day_metrics_used_for_selection"
        ].any()
    )

    and

    DRIVE_REGISTRY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_30_IMBALANCE_PROTOCOL_VALID = (
    PROTOCOL_VALID
)


print("\n[4] Step A30 validation")
print("-" * 78)

print(
    "Final lambda_t                  :",
    FINAL_LAMBDA_T
)

print(
    "Imbalance candidates            :",
    candidate_count,
    "/ 3"
)

print(
    "Completed validation configs    :",
    completed_count,
    "/ 3"
)

print(
    "none validation F1              :",
    f"{NONE_VALIDATION_F1:.10f}"
)

print(
    "none validation FPR             :",
    f"{NONE_VALIDATION_FPR:.10f}"
)

print(
    "Selection uses test metrics     :",
    False
)

print(
    "Selection uses zero-day metrics :",
    False
)

print(
    "Registry backed up              :",
    DRIVE_REGISTRY.exists()
)

print(
    "Policy backed up                :",
    DRIVE_POLICY.exists()
)


print("\n" + "=" * 78)

if PROTOCOL_VALID:

    print(
        "✅ STEP A30 PASSED — "
        "imbalance-handling sensitivity protocol "
        "is frozen before training the remaining methods."
    )

else:

    print(
        "❌ STEP A30 FAILED — "
        "do not start class_weight training."
    )

print("=" * 78)

==============================================================================
STEP A30 — FREEZE IMBALANCE-HANDLING SENSITIVITY PROTOCOL
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying lambda-selection prerequisite
------------------------------------------------------------------------------
A29 lambda selection valid: True

[2] Loading finalized lambda_t
------------------------------------------------------------------------------
Final lambda_t: 0.25
Existing imbalance method: none
Existing validation F1: 0.9972670927
Existing validation FPR: 0.3655976676
Existing threshold: 0.0147513831

[3] Freezing imbalance candidates
------------------------------------------------------------------------------
Candidates: ['none', 'class_weight', 'weighted_sampler']

,fold_id,held_out_family,seed,temporal_window,lambda_t,imbalance_method,SSL_epochs,fine_tuning_epochs,status,selected_threshold,validation_F1,validation_FPR,validation_recall,test_metrics_used_for_selection,zero_day_metrics_used_for_selection
0,1,DDoS,13,8,0.25,none,30,20,validation_complete,0.014751,0.997267,0.365598,0.998311,False,False
1,1,DDoS,13,8,0.25,class_weight,30,20,pending,NaN,NaN,NaN,NaN,False,False
2,1,DDoS,13,8,0.25,weighted_sampler,30,20,pending,NaN,NaN,NaN,NaN,False,False

[4] Step A30 validation
------------------------------------------------------------------------------
Final lambda_t                  : 0.25
Imbalance candidates            : 3 / 3
Completed validation configs    : 1 / 3
none validation F1              : 0.9972670927
none validation FPR             : 0.3655976676
Selection uses test metrics     : False
Selection uses zero-day metrics : False
Registry backed up              : True
Policy backed up                : True

==============================================================================
✅ STEP A30 PASSED — imbalance-handling sensitivity protocol is frozen before training the remaining methods.
==============================================================================

# Step A31 — Fine-tune with class_weight

In [ ]:
# ======================================================================
# STEP A31
# IMBALANCE SENSITIVITY — CLASS-WEIGHT FINE-TUNING
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# lambda_t = 0.25 (frozen by A29)
#
# Imbalance method:
#   balanced class weighting
#
# Fine-tuning epochs: 20
#
# NO validation threshold selection here.
# NO known-test access.
# NO benign-test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A31 — CLASS-WEIGHT FINE-TUNING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("lambda_t = 0.25")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_29_LAMBDA_SELECTION_VALID",
    "STEP_30_IMBALANCE_PROTOCOL_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_29_LAMBDA_SELECTION_VALID:
    raise RuntimeError("A29 did not pass.")

if not STEP_30_IMBALANCE_PROTOCOL_VALID:
    raise RuntimeError("A30 did not pass.")


print("A13 data valid:", STEP_13_PYTORCH_DATA_VALID)
print("A14 architecture valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A29 lambda selection valid:", STEP_29_LAMBDA_SELECTION_VALID)
print("A30 imbalance protocol valid:", STEP_30_IMBALANCE_PROTOCOL_VALID)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

SEED = 13

LAMBDA_T = 0.25

FINETUNE_EPOCHS = 20

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

MAX_GRADIENT_NORM = 5.0

IMBALANCE_METHOD = "class_weight"


print("\n[2] Controlled configuration")
print("-" * 78)

print("lambda_t:", LAMBDA_T)
print("Seed:", SEED)
print("Epochs:", FINETUNE_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Imbalance method:", IMBALANCE_METHOD)
print("Precision:", "float32")


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — COUNT TRAINING LABELS ONLY
# ======================================================================

print("\n[3] Computing class weights from training data only")
print("-" * 78)


COUNT_LOADER = DataLoader(

    TRAIN_DATASET,

    batch_size=4096,

    shuffle=False,

    num_workers=0
)


BENIGN_COUNT = 0

ATTACK_COUNT = 0


for _, y_count in COUNT_LOADER:

    y_count = y_count.cpu().numpy()

    BENIGN_COUNT += int(
        np.sum(
            y_count == 0
        )
    )

    ATTACK_COUNT += int(
        np.sum(
            y_count == 1
        )
    )


TOTAL_COUNT = (
    BENIGN_COUNT
    +
    ATTACK_COUNT
)


if TOTAL_COUNT != len(TRAIN_DATASET):

    raise RuntimeError(
        "Training label count mismatch."
    )


if BENIGN_COUNT <= 0 or ATTACK_COUNT <= 0:

    raise RuntimeError(
        "Both classes must be present."
    )


# Balanced class-weight formula:
#
# weight(class c) = N / (2 * N_c)

BENIGN_WEIGHT = (

    TOTAL_COUNT

    /

    (
        2.0
        *
        BENIGN_COUNT
    )
)


ATTACK_WEIGHT = (

    TOTAL_COUNT

    /

    (
        2.0
        *
        ATTACK_COUNT
    )
)


print(
    "Benign windows:",
    f"{BENIGN_COUNT:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_COUNT:,}"
)

print(
    "Total windows:",
    f"{TOTAL_COUNT:,}"
)

print(
    "Benign class weight:",
    f"{BENIGN_WEIGHT:.10f}"
)

print(
    "Attack class weight:",
    f"{ATTACK_WEIGHT:.10f}"
)

print(
    "Weights derived from:",
    "training data only"
)


# ======================================================================
# 5 — LOAD FROZEN lambda=0.25 SSL MODEL
# ======================================================================

print("\n[4] Loading selected lambda=0.25 SSL encoder")
print("-" * 78)


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


SSL_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_0p25_fp32"
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


if not SSL_MODEL_PATH.exists():

    raise RuntimeError(
        "Selected lambda=0.25 SSL model "
        "was not found in Drive."
    )


SSL_PACKAGE = torch.load(
    SSL_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        SSL_PACKAGE[
            "lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "SSL lambda mismatch."
    )


if int(
    SSL_PACKAGE[
        "completed_epochs"
    ]
) != 30:

    raise RuntimeError(
        "Selected SSL model did not complete 30 epochs."
    )


if SSL_PACKAGE.get(
    "labels_used_during_SSL"
):

    raise RuntimeError(
        "Selected SSL package reports label use."
    )


print(
    "SSL lambda_t:",
    SSL_PACKAGE[
        "lambda_t"
    ]
)

print(
    "SSL epochs:",
    SSL_PACKAGE[
        "completed_epochs"
    ]
)

print(
    "SSL precision:",
    SSL_PACKAGE[
        "precision"
    ]
)

print(
    "Labels used during SSL:",
    SSL_PACKAGE[
        "labels_used_during_SSL"
    ]
)


# ======================================================================
# 6 — CREATE FRESH FINE-TUNING MODEL
# ======================================================================

set_all_seeds(SEED)


CLASS_WEIGHT_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


CLASS_WEIGHT_MODEL.load_state_dict(
    SSL_PACKAGE[
        "model_state_dict"
    ],
    strict=True
)


# ======================================================================
# 7 — FRESH CLASSIFIER INITIALIZATION
# ======================================================================

# Same classifier-initialization policy as the controlled
# fine-tuning runs.

set_all_seeds(
    SEED + 1000
)


for module in (
    CLASS_WEIGHT_MODEL
    .classifier_head
    .modules()
):

    if hasattr(
        module,
        "reset_parameters"
    ):

        module.reset_parameters()


print(
    "SSL encoder state loaded:",
    True
)

print(
    "Classifier freshly initialized:",
    True
)

print(
    "Classifier initialization seed:",
    SEED + 1000
)


# ======================================================================
# 8 — TRAINABLE PARAMETERS
# ======================================================================

FINETUNE_PARAMETERS = (

    list(
        CLASS_WEIGHT_MODEL
        .feature_encoder
        .parameters()
    )

    +

    list(
        CLASS_WEIGHT_MODEL
        .temporal_encoder
        .parameters()
    )

    +

    list(
        CLASS_WEIGHT_MODEL
        .classifier_head
        .parameters()
    )
)


finetune_ids = {
    id(parameter)
    for parameter in FINETUNE_PARAMETERS
}


projection_ids = {
    id(parameter)
    for parameter in
    CLASS_WEIGHT_MODEL
    .projection_head
    .parameters()
}


order_ids = {
    id(parameter)
    for parameter in
    CLASS_WEIGHT_MODEL
    .temporal_order_head
    .parameters()
}


PROJECTION_INCLUDED = bool(
    finetune_ids
    &
    projection_ids
)


ORDER_INCLUDED = bool(
    finetune_ids
    &
    order_ids
)


if PROJECTION_INCLUDED:

    raise RuntimeError(
        "Projection head must not be fine-tuned."
    )


if ORDER_INCLUDED:

    raise RuntimeError(
        "Temporal-order head must not be fine-tuned."
    )


FINETUNE_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter in FINETUNE_PARAMETERS
)


print(
    "Fine-tuned parameters:",
    f"{FINETUNE_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized:",
    ORDER_INCLUDED
)


# ======================================================================
# 9 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    FINETUNE_PARAMETERS,

    lr=LEARNING_RATE
)


# ======================================================================
# 10 — DETERMINISTIC TRAINING LOADER
# ======================================================================

def make_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        shuffle=True,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False,

        generator=generator
    )


# ======================================================================
# 11 — OUTPUT PATHS
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_0p25_fp32/"
    "imbalance_class_weight"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_class_weight"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "fine_tuning_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "fine_tuning_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fine_tuning_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fine_tuning_policy.json"
)


# ======================================================================
# 12 — SAVE POLICY
# ======================================================================

POLICY = {

    "experiment":
        "imbalance_handling_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "class_weight_formula":
        "N/(2*N_c)",

    "class_weights": {

        "benign":
            float(
                BENIGN_WEIGHT
            ),

        "attack":
            float(
                ATTACK_WEIGHT
            )
    },

    "weight_source":
        "training_partition_only",

    "training_benign_windows":
        BENIGN_COUNT,

    "training_attack_windows":
        ATTACK_COUNT,

    "epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "precision":
        "float32",

    "classifier_initialization_seed":
        SEED + 1000,

    "feature_encoder_trainable":
        True,

    "GRU_encoder_trainable":
        True,

    "classifier_trainable":
        True,

    "projection_head_trainable":
        False,

    "temporal_order_head_trainable":
        False,

    "threshold_selected":
        False,

    "validation_used_during_training":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 13 — RESUME SUPPORT
# ======================================================================

print("\n[5] Checking class-weight checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if checkpoint.get(
        "imbalance_method"
    ) != IMBALANCE_METHOD:

        raise RuntimeError(
            "Checkpoint imbalance-method mismatch."
        )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Checkpoint lambda mismatch."
        )


    CLASS_WEIGHT_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No class-weight checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 14 — CLASS-WEIGHT FINE-TUNING
# ======================================================================

print("\n[6] Starting class-weight fine-tuning")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= FINETUNE_EPOCHS:

    for epoch in range(
        START_EPOCH,
        FINETUNE_EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_loader(
            epoch
        )


        CLASS_WEIGHT_MODEL.train()


        running_loss = 0.0

        total_examples = 0

        correct_at_05 = 0

        predicted_attack_count = 0

        predicted_benign_count = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            y
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            y = y.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite X at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            logits = (
                CLASS_WEIGHT_MODEL
                .forward_classifier(
                    X
                )
            )


            per_example_loss = (
                F.binary_cross_entropy_with_logits(
                    logits,
                    y,
                    reduction="none"
                )
            )


            sample_weights = torch.where(

                y >= 0.5,

                torch.full_like(
                    y,
                    ATTACK_WEIGHT
                ),

                torch.full_like(
                    y,
                    BENIGN_WEIGHT
                )
            )


            loss = (
                per_example_loss
                *
                sample_weights
            ).mean()


            if not bool(
                torch.isfinite(
                    loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite weighted BCE at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    FINETUNE_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at "
                    f"epoch {epoch}, "
                    f"batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            running_loss += (

                float(
                    loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            total_examples += batch_size


            # Diagnostic only — 0.5 is NOT selected.
            with torch.no_grad():

                probabilities = torch.sigmoid(
                    logits
                )


                predictions = (
                    probabilities
                    >=
                    0.5
                ).float()


                correct_at_05 += int(
                    (
                        predictions
                        ==
                        y
                    )
                    .sum()
                    .item()
                )


                predicted_attack_count += int(
                    (
                        predictions
                        ==
                        1
                    )
                    .sum()
                    .item()
                )


                predicted_benign_count += int(
                    (
                        predictions
                        ==
                        0
                    )
                    .sum()
                    .item()
                )


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/"
                    f"{FINETUNE_EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| weighted BCE="
                    f"{float(loss.detach().cpu()):.6f}"
                )


        mean_loss = (
            running_loss
            /
            total_examples
        )


        diagnostic_accuracy = (
            correct_at_05
            /
            total_examples
        )


        predicted_attack_fraction = (
            predicted_attack_count
            /
            total_examples
        )


        predicted_benign_fraction = (
            predicted_benign_count
            /
            total_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "imbalance_method":
                IMBALANCE_METHOD,

            "weighted_BCE_loss":
                mean_loss,

            "diagnostic_accuracy_at_0p5":
                diagnostic_accuracy,

            "predicted_attack_fraction_at_0p5":
                predicted_attack_fraction,

            "predicted_benign_fraction_at_0p5":
                predicted_benign_fraction,

            "examples":
                total_examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            != epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "imbalance_method":
                IMBALANCE_METHOD,

            "benign_weight":
                float(
                    BENIGN_WEIGHT
                ),

            "attack_weight":
                float(
                    ATTACK_WEIGHT
                ),

            "model_state_dict":
                CLASS_WEIGHT_MODEL
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| weighted_BCE={mean_loss:.6f} "
            f"| diagnostic_acc@0.5="
            f"{diagnostic_accuracy:.4f} "
            f"| predicted_attack="
            f"{predicted_attack_fraction:.4f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "Class-weight fine-tuning already "
        "contains all 20 epochs."
    )


# ======================================================================
# 15 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[7] Last 5 class-weight epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 16 — NUMERICAL VALIDATION
# ======================================================================

print("\n[8] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in CLASS_WEIGHT_MODEL.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=64,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


CLASS_WEIGHT_MODEL.eval()


with torch.no_grad():

    check_logits = (
        CLASS_WEIGHT_MODEL
        .forward_classifier(
            X_check
        )
    )


    check_probabilities = (
        torch.sigmoid(
            check_logits
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        check_logits
    ).all()

    and

    torch.isfinite(
        check_probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    (
        check_probabilities >= 0
    ).all()

    and

    (
        check_probabilities <= 1
    ).all()
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 17 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        CLASS_WEIGHT_MODEL
        .state_dict(),

    "experiment":
        "imbalance_handling_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "benign_class_weight":
        float(
            BENIGN_WEIGHT
        ),

    "attack_class_weight":
        float(
            ATTACK_WEIGHT
        ),

    "weight_source":
        "training_partition_only",

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 18 — FINAL A31 VALIDATION
# ======================================================================

FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


A31_VALID = bool(

    COMPLETED_EPOCHS
    ==
    20

    and

    TOTAL_COUNT
    ==
    105_577

    and

    BENIGN_COUNT
    ==
    8_006

    and

    ATTACK_COUNT
    ==
    97_571

    and

    NONFINITE_BATCHES
    ==
    0

    and

    not PROJECTION_INCLUDED

    and

    not ORDER_INCLUDED

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_31_CLASS_WEIGHT_FINETUNE_VALID = (
    A31_VALID
)


print("\n[9] Step A31 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Completed epochs               :",
    COMPLETED_EPOCHS,
    "/ 20"
)

print(
    "Training benign windows        :",
    f"{BENIGN_COUNT:,}"
)

print(
    "Training attack windows        :",
    f"{ATTACK_COUNT:,}"
)

print(
    "Benign class weight            :",
    f"{BENIGN_WEIGHT:.10f}"
)

print(
    "Attack class weight            :",
    f"{ATTACK_WEIGHT:.10f}"
)

print(
    "Weights use training only      :",
    True
)

print(
    "Threshold selected             :",
    False
)

print(
    "Known-test used                :",
    False
)

print(
    "Benign-test used               :",
    False
)

print(
    "Zero-day DDoS used             :",
    False
)

print(
    "Final weighted BCE             :",
    f"{float(FINAL_ROW['weighted_BCE_loss']):.6f}"
)

print(
    "Diagnostic accuracy @ 0.5      :",
    f"{float(FINAL_ROW['diagnostic_accuracy_at_0p5']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A31_VALID:

    print(
        "✅ STEP A31 PASSED — "
        "class_weight completed controlled "
        "20-epoch supervised fine-tuning."
    )

else:

    print(
        "❌ STEP A31 INCOMPLETE — "
        "rerun this same cell to resume."
    )

print("=" * 78)

==============================================================================
STEP A31 — CLASS-WEIGHT FINE-TUNING
FOLD 1 | HELD-OUT FAMILY = DDoS
lambda_t = 0.25
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 data valid: True
A14 architecture valid: True
A29 lambda selection valid: True
A30 imbalance protocol valid: True
Training windows: 105,577
Device: cuda

[2] Controlled configuration
------------------------------------------------------------------------------
lambda_t: 0.25
Seed: 13
Epochs: 20
Batch size: 256
Learning rate: 0.001
Imbalance method: class_weight
Precision: float32

[3] Computing class weights from training data only
------------------------------------------------------------------------------
Benign windows: 8,006
Attack windows: 97,571
Total windows: 105,577
Benign class weight: 6.5936172870
Attack class weight: 0.5410265345
Weights derived from: training data only

[4] Loading selected lambda=0.25 SSL encoder
------------------------------------------------------------------------------
SSL lambda_t: 0.25
SSL epochs: 30
SSL precision: float32
Labels used during SSL: False
SSL encoder state loaded: True
Classifier freshly initialized: True
Classifier initialization seed: 1013
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[5] Checking class-weight checkpoint
------------------------------------------------------------------------------
No class-weight checkpoint.
Starting from epoch 1.

[6] Starting class-weight fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/413 | weighted BCE=0.202502
Epoch 01/20 | Batch 200/413 | weighted BCE=0.290844
Epoch 01/20 | Batch 300/413 | weighted BCE=0.145833
Epoch 01/20 | Batch 400/413 | weighted BCE=0.157380
Epoch 01/20 | Batch 413/413 | weighted BCE=0.111677

Epoch 01 complete | weighted_BCE=0.212400 | diagnostic_acc@0.5=0.8739 | predicted_attack=0.8028 | time=6.5s | checkpoint=Drive
Epoch 02/20 | Batch 100/413 | weighted BCE=0.228866
Epoch 02/20 | Batch 200/413 | weighted BCE=0.111851
Epoch 02/20 | Batch 300/413 | weighted BCE=0.131081
Epoch 02/20 | Batch 400/413 | weighted BCE=0.206377
Epoch 02/20 | Batch 413/413 | weighted BCE=0.099837

Epoch 02 complete | weighted_BCE=0.134483 | diagnostic_acc@0.5=0.9295 | predicted_attack=0.8571 | time=8.3s | checkpoint=Drive
Epoch 03/20 | Batch 100/413 | weighted BCE=0.115799
Epoch 03/20 | Batch 200/413 | weighted BCE=0.098592
Epoch 03/20 | Batch 300/413 | weighted BCE=0.122916
Epoch 03/20 | Batch 400/413 | weighted BCE=0.104654
Epoch 03/20 | Batch 413/413 | weighted BCE=0.081775

Epoch 03 complete | weighted_BCE=0.112290 | diagnostic_acc@0.5=0.9420 | predicted_attack=0.8686 | time=7.6s | checkpoint=Drive
Epoch 04/20 | Batch 100/413 | weighted BCE=0.088077
Epoch 04/20 | Batch 200/413 | weighted BCE=0.090023
Epoch 04/20 | Batch 300/413 | weighted BCE=0.102485
Epoch 04/20 | Batch 400/413 | weighted BCE=0.067014
Epoch 04/20 | Batch 413/413 | weighted BCE=0.139848

Epoch 04 complete | weighted_BCE=0.099834 | diagnostic_acc@0.5=0.9481 | predicted_attack=0.8749 | time=7.8s | checkpoint=Drive
Epoch 05/20 | Batch 100/413 | weighted BCE=0.101809
Epoch 05/20 | Batch 200/413 | weighted BCE=0.111200
Epoch 05/20 | Batch 300/413 | weighted BCE=0.074911
Epoch 05/20 | Batch 400/413 | weighted BCE=0.120475
Epoch 05/20 | Batch 413/413 | weighted BCE=0.082420

Epoch 05 complete | weighted_BCE=0.088596 | diagnostic_acc@0.5=0.9545 | predicted_attack=0.8807 | time=7.3s | checkpoint=Drive
Epoch 06/20 | Batch 100/413 | weighted BCE=0.035264
Epoch 06/20 | Batch 200/413 | weighted BCE=0.163966
Epoch 06/20 | Batch 300/413 | weighted BCE=0.064960
Epoch 06/20 | Batch 400/413 | weighted BCE=0.078317
Epoch 06/20 | Batch 413/413 | weighted BCE=0.103924

Epoch 06 complete | weighted_BCE=0.082065 | diagnostic_acc@0.5=0.9582 | predicted_attack=0.8843 | time=5.1s | checkpoint=Drive
Epoch 07/20 | Batch 100/413 | weighted BCE=0.049292
Epoch 07/20 | Batch 200/413 | weighted BCE=0.070960
Epoch 07/20 | Batch 300/413 | weighted BCE=0.060411
Epoch 07/20 | Batch 400/413 | weighted BCE=0.110078
Epoch 07/20 | Batch 413/413 | weighted BCE=0.066285

Epoch 07 complete | weighted_BCE=0.076176 | diagnostic_acc@0.5=0.9620 | predicted_attack=0.8877 | time=4.0s | checkpoint=Drive
Epoch 08/20 | Batch 100/413 | weighted BCE=0.057366
Epoch 08/20 | Batch 200/413 | weighted BCE=0.152707
Epoch 08/20 | Batch 300/413 | weighted BCE=0.045280
Epoch 08/20 | Batch 400/413 | weighted BCE=0.084878
Epoch 08/20 | Batch 413/413 | weighted BCE=0.072490

Epoch 08 complete | weighted_BCE=0.070258 | diagnostic_acc@0.5=0.9647 | predicted_attack=0.8902 | time=4.1s | checkpoint=Drive
Epoch 09/20 | Batch 100/413 | weighted BCE=0.059500
Epoch 09/20 | Batch 200/413 | weighted BCE=0.075147
Epoch 09/20 | Batch 300/413 | weighted BCE=0.030472
Epoch 09/20 | Batch 400/413 | weighted BCE=0.090528
Epoch 09/20 | Batch 413/413 | weighted BCE=0.060391

Epoch 09 complete | weighted_BCE=0.064202 | diagnostic_acc@0.5=0.9676 | predicted_attack=0.8931 | time=4.9s | checkpoint=Drive
Epoch 10/20 | Batch 100/413 | weighted BCE=0.081112
Epoch 10/20 | Batch 200/413 | weighted BCE=0.073095
Epoch 10/20 | Batch 300/413 | weighted BCE=0.045962
Epoch 10/20 | Batch 400/413 | weighted BCE=0.081641
Epoch 10/20 | Batch 413/413 | weighted BCE=0.073753

Epoch 10 complete | weighted_BCE=0.063208 | diagnostic_acc@0.5=0.9685 | predicted_attack=0.8938 | time=4.0s | checkpoint=Drive
Epoch 11/20 | Batch 100/413 | weighted BCE=0.022669
Epoch 11/20 | Batch 200/413 | weighted BCE=0.074953
Epoch 11/20 | Batch 300/413 | weighted BCE=0.054039
Epoch 11/20 | Batch 400/413 | weighted BCE=0.027180
Epoch 11/20 | Batch 413/413 | weighted BCE=0.072697

Epoch 11 complete | weighted_BCE=0.056054 | diagnostic_acc@0.5=0.9723 | predicted_attack=0.8975 | time=3.9s | checkpoint=Drive
Epoch 12/20 | Batch 100/413 | weighted BCE=0.092857
Epoch 12/20 | Batch 200/413 | weighted BCE=0.041246
Epoch 12/20 | Batch 300/413 | weighted BCE=0.038315
Epoch 12/20 | Batch 400/413 | weighted BCE=0.049191
Epoch 12/20 | Batch 413/413 | weighted BCE=0.023964

Epoch 12 complete | weighted_BCE=0.055196 | diagnostic_acc@0.5=0.9723 | predicted_attack=0.8974 | time=4.9s | checkpoint=Drive
Epoch 13/20 | Batch 100/413 | weighted BCE=0.080371
Epoch 13/20 | Batch 200/413 | weighted BCE=0.065129
Epoch 13/20 | Batch 300/413 | weighted BCE=0.043113
Epoch 13/20 | Batch 400/413 | weighted BCE=0.056227
Epoch 13/20 | Batch 413/413 | weighted BCE=0.019920

Epoch 13 complete | weighted_BCE=0.052713 | diagnostic_acc@0.5=0.9744 | predicted_attack=0.8995 | time=4.0s | checkpoint=Drive
Epoch 14/20 | Batch 100/413 | weighted BCE=0.183675
Epoch 14/20 | Batch 200/413 | weighted BCE=0.026917
Epoch 14/20 | Batch 300/413 | weighted BCE=0.129954
Epoch 14/20 | Batch 400/413 | weighted BCE=0.035258
Epoch 14/20 | Batch 413/413 | weighted BCE=0.072844

Epoch 14 complete | weighted_BCE=0.050952 | diagnostic_acc@0.5=0.9752 | predicted_attack=0.9002 | time=3.9s | checkpoint=Drive
Epoch 15/20 | Batch 100/413 | weighted BCE=0.039021
Epoch 15/20 | Batch 200/413 | weighted BCE=0.067153
Epoch 15/20 | Batch 300/413 | weighted BCE=0.035684
Epoch 15/20 | Batch 400/413 | weighted BCE=0.053062
Epoch 15/20 | Batch 413/413 | weighted BCE=0.076560

Epoch 15 complete | weighted_BCE=0.048339 | diagnostic_acc@0.5=0.9763 | predicted_attack=0.9014 | time=4.5s | checkpoint=Drive
Epoch 16/20 | Batch 100/413 | weighted BCE=0.061822
Epoch 16/20 | Batch 200/413 | weighted BCE=0.030676
Epoch 16/20 | Batch 300/413 | weighted BCE=0.021579
Epoch 16/20 | Batch 400/413 | weighted BCE=0.050672
Epoch 16/20 | Batch 413/413 | weighted BCE=0.009808

Epoch 16 complete | weighted_BCE=0.045891 | diagnostic_acc@0.5=0.9772 | predicted_attack=0.9023 | time=4.4s | checkpoint=Drive
Epoch 17/20 | Batch 100/413 | weighted BCE=0.040803
Epoch 17/20 | Batch 200/413 | weighted BCE=0.028354
Epoch 17/20 | Batch 300/413 | weighted BCE=0.066984
Epoch 17/20 | Batch 400/413 | weighted BCE=0.044602
Epoch 17/20 | Batch 413/413 | weighted BCE=0.024669

Epoch 17 complete | weighted_BCE=0.042515 | diagnostic_acc@0.5=0.9794 | predicted_attack=0.9043 | time=3.9s | checkpoint=Drive
Epoch 18/20 | Batch 100/413 | weighted BCE=0.053178
Epoch 18/20 | Batch 200/413 | weighted BCE=0.039643
Epoch 18/20 | Batch 300/413 | weighted BCE=0.044092
Epoch 18/20 | Batch 400/413 | weighted BCE=0.045886
Epoch 18/20 | Batch 413/413 | weighted BCE=0.008992

Epoch 18 complete | weighted_BCE=0.041498 | diagnostic_acc@0.5=0.9797 | predicted_attack=0.9046 | time=4.0s | checkpoint=Drive
Epoch 19/20 | Batch 100/413 | weighted BCE=0.040838
Epoch 19/20 | Batch 200/413 | weighted BCE=0.036147
Epoch 19/20 | Batch 300/413 | weighted BCE=0.031702
Epoch 19/20 | Batch 400/413 | weighted BCE=0.037199
Epoch 19/20 | Batch 413/413 | weighted BCE=0.034307

Epoch 19 complete | weighted_BCE=0.041326 | diagnostic_acc@0.5=0.9802 | predicted_attack=0.9051 | time=4.8s | checkpoint=Drive
Epoch 20/20 | Batch 100/413 | weighted BCE=0.034847
Epoch 20/20 | Batch 200/413 | weighted BCE=0.033490
Epoch 20/20 | Batch 300/413 | weighted BCE=0.039748
Epoch 20/20 | Batch 400/413 | weighted BCE=0.041202
Epoch 20/20 | Batch 413/413 | weighted BCE=0.027551

Epoch 20 complete | weighted_BCE=0.038705 | diagnostic_acc@0.5=0.9813 | predicted_attack=0.9061 | time=3.9s | checkpoint=Drive

[7] Last 5 class-weight epochs
------------------------------------------------------------------------------

,epoch,lambda_t,imbalance_method,weighted_BCE_loss,diagnostic_accuracy_at_0p5,predicted_attack_fraction_at_0p5,predicted_benign_fraction_at_0p5,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
15,16,0.25,class_weight,0.045891,0.977220,0.902280,0.097720,105577,413,3.051681,4.434934
16,17,0.25,class_weight,0.042515,0.979399,0.904307,0.095693,105577,413,2.887402,3.886110
17,18,0.25,class_weight,0.041498,0.979740,0.904629,0.095371,105577,413,3.800557,4.049870
18,19,0.25,class_weight,0.041326,0.980176,0.905083,0.094917,105577,413,3.732380,4.793600
19,20,0.25,class_weight,0.038705,0.981312,0.906144,0.093856,105577,413,4.121543,3.893260

[8] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
Parameters finite: True
Outputs finite: True
Probability range valid: True

[9] Step A31 validation
------------------------------------------------------------------------------
lambda_t                       : 0.25
Imbalance method               : class_weight
Completed epochs               : 20 / 20
Training benign windows        : 8,006
Training attack windows        : 97,571
Benign class weight            : 6.5936172870
Attack class weight            : 0.5410265345
Weights use training only      : True
Threshold selected             : False
Known-test used                : False
Benign-test used               : False
Zero-day DDoS used             : False
Final weighted BCE             : 0.038705
Diagnostic accuracy @ 0.5      : 0.981312
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A31 PASSED — class_weight completed controlled 20-epoch supervised fine-tuning.
==============================================================================

# Step A32 — Validate class_weight

In [ ]:
# ======================================================================
# STEP A32
# IMBALANCE SENSITIVITY — CLASS_WEIGHT VALIDATION
#
# Fold 1: DDoS held out
# lambda_t = 0.25
#
# DEVELOPMENT VALIDATION ONLY
#
# NO known-test access.
# NO benign-test access.
# NO zero-day DDoS access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    accuracy_score,
    average_precision_score,
    roc_auc_score
)


print("=" * 78)
print("STEP A32 — CLASS_WEIGHT DEVELOPMENT VALIDATION")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("lambda_t = 0.25")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_29_LAMBDA_SELECTION_VALID",
    "STEP_30_IMBALANCE_PROTOCOL_VALID",
    "STEP_31_CLASS_WEIGHT_FINETUNE_VALID",
    "MOTSSLGRU",
    "DEVICE"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_29_LAMBDA_SELECTION_VALID:
    raise RuntimeError("A29 did not pass.")

if not STEP_30_IMBALANCE_PROTOCOL_VALID:
    raise RuntimeError("A30 did not pass.")

if not STEP_31_CLASS_WEIGHT_FINETUNE_VALID:
    raise RuntimeError("A31 did not pass.")


print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A29 lambda selection valid:",
    STEP_29_LAMBDA_SELECTION_VALID
)

print(
    "A30 imbalance protocol valid:",
    STEP_30_IMBALANCE_PROTOCOL_VALID
)

print(
    "A31 class_weight fine-tuning valid:",
    STEP_31_CLASS_WEIGHT_FINETUNE_VALID
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

LAMBDA_T = 0.25

IMBALANCE_METHOD = "class_weight"

SEED = 13

EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


print("\n[2] Validation configuration")
print("-" * 78)

print(
    "lambda_t:",
    LAMBDA_T
)

print(
    "Imbalance method:",
    IMBALANCE_METHOD
)

print(
    "Seed:",
    SEED
)

print(
    "Expected validation windows:",
    f"{EXPECTED_WINDOWS:,}"
)

print(
    "Expected benign windows:",
    f"{EXPECTED_BENIGN:,}"
)

print(
    "Expected attack windows:",
    f"{EXPECTED_ATTACK:,}"
)

print(
    "Threshold rule:",
    "maximize development-validation F1"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_class_weight"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


REGISTRY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "fold_01_imbalance_experiment_registry.csv"
)


POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "fold_01_imbalance_selection_policy.json"
)


for path in [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    MODEL_PATH,
    REGISTRY_PATH,
    POLICY_PATH
]:

    if not path.exists():

        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 4 — VERIFY FROZEN A30 POLICY
# ======================================================================

print("\n[3] Verifying frozen A30 protocol")
print("-" * 78)


with open(
    POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:

    imbalance_policy = json.load(
        file
    )


if (
    imbalance_policy[
        "selection_data"
    ]
    !=
    "development_validation_only"
):

    raise RuntimeError(
        "A30 validation-partition policy mismatch."
    )


if not np.isclose(
    float(
        imbalance_policy[
            "lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "A30 frozen lambda_t mismatch."
    )


if imbalance_policy[
    "test_data_allowed_for_selection"
]:

    raise RuntimeError(
        "A30 incorrectly permits test metrics."
    )


if imbalance_policy[
    "zero_day_data_allowed_for_selection"
]:

    raise RuntimeError(
        "A30 incorrectly permits zero-day metrics."
    )


print(
    "Selection partition:",
    imbalance_policy[
        "selection_data"
    ]
)

print(
    "Frozen lambda_t:",
    imbalance_policy[
        "lambda_t"
    ]
)

print(
    "Primary selection metric:",
    imbalance_policy[
        "primary_selection_metric"
    ]
)

print(
    "Test metrics allowed:",
    False
)

print(
    "Zero-day metrics allowed:",
    False
)


# ======================================================================
# 5 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[4] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(
        file
    )


if len(RETAINED_FEATURES) != 75:

    raise RuntimeError(
        "Expected 75 retained features."
    )


parameter_lookup = (

    parameters

    .set_index(
        "feature"
    )

    .loc[
        RETAINED_FEATURES
    ]
)


IMPUTE_VALUES = (

    parameter_lookup[
        "imputation_value"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (

    parameter_lookup[
        "scaler_mean"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (

    parameter_lookup[
        "scaler_std"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)


if not PREPROCESSING_VALID:

    raise RuntimeError(
        "Frozen preprocessing invalid."
    )


# ======================================================================
# 6 — LOAD VALIDATION MANIFEST
# ======================================================================

print("\n[5] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (

    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_validation"
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


VALIDATION_WINDOWS_MANIFEST = int(

    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDOS_WINDOWS = int(

    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{VALIDATION_WINDOWS_MANIFEST:,}"
)

print(
    "DDoS validation windows:",
    DDOS_WINDOWS
)


if len(VAL_MANIFEST) != 21:

    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if VALIDATION_WINDOWS_MANIFEST != EXPECTED_WINDOWS:

    raise RuntimeError(
        "Validation window-count mismatch."
    )


if DDOS_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 7 — LOAD CLASS-WEIGHT MODEL
# ======================================================================

print("\n[6] Loading class_weight model")
print("-" * 78)


model_package = torch.load(
    MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        model_package[
            "SSL_lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "Model lambda_t mismatch."
    )


if (
    model_package[
        "imbalance_method"
    ]
    !=
    IMBALANCE_METHOD
):

    raise RuntimeError(
        "Model imbalance-method mismatch."
    )


if model_package.get(
    "threshold_selected"
):

    raise RuntimeError(
        "Model already indicates threshold selection."
    )


MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


MODEL.eval()


MODEL_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter in MODEL.parameters()
)


print(
    "Loaded lambda_t:",
    model_package[
        "SSL_lambda_t"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Benign class weight:",
    f"{float(model_package['benign_class_weight']):.10f}"
)

print(
    "Attack class weight:",
    f"{float(model_package['attack_class_weight']):.10f}"
)

print(
    "Model finite:",
    MODEL_FINITE
)


if not MODEL_FINITE:

    raise RuntimeError(
        "Model parameters are non-finite."
    )


# ======================================================================
# 8 — FROZEN PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(table):

    X = (

        table

        .to_pandas()

        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(
            X
        )
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        rows, cols = np.where(
            bad_mask
        )


        X[
            rows,
            cols
        ] = IMPUTE_VALUES[
            cols
        ]


    Z = (

        X
        -
        SCALER_MEANS

    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite transformed values."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():

        raise RuntimeError(
            "Non-finite float32 values."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 9 — PREDICTION FUNCTION
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(windows):

    probability_parts = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,
            len(windows)
        )


        X = torch.from_numpy(

            windows[
                start:stop
            ]

        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                MODEL
                .forward_classifier(
                    X
                )
            )


            probabilities = torch.sigmoid(
                logits
            )


        if not bool(
            torch.isfinite(
                probabilities
            ).all()
        ):

            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        probability_parts.append(

            probabilities

            .detach()

            .cpu()

            .numpy()

            .astype(
                np.float64
            )
        )


    return np.concatenate(
        probability_parts
    )


# ======================================================================
# 10 — RUN DEVELOPMENT-VALIDATION INFERENCE
# ======================================================================

print("\n[7] Running class_weight validation inference")
print("-" * 78)


prediction_parts = []

TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    family = str(
        row[
            "research_family"
        ]
    )


    target = int(
        row[
            "binary_target"
        ]
    )


    partition_start = int(
        row[
            "partition_start_row"
        ]
    )


    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    expected_windows = int(
        row[
            "window_count"
        ]
    )


    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )


    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():

        raise RuntimeError(
            f"Missing Parquet: {parquet_name}"
        )


    if family == "DDoS":

        raise RuntimeError(
            "Held-out DDoS reached validation."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probability_parts = []

    source_raw_nonfinite = 0

    absolute_row = 0


    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(

            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row

        group_end = (
            group_start
            +
            row_group_rows
        )


        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(

            row_group_index,

            columns=RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(

            local_start,

            local_end
            -
            local_start
        )


        Z, bad_count = frozen_preprocess(
            table
        )


        source_raw_nonfinite += (
            bad_count
        )


        if len(pending) > 0:

            Z = np.concatenate(
                [
                    pending,
                    Z
                ],
                axis=0
            )


        complete_windows = (
            len(Z)
            //
            8
        )


        complete_rows = (
            complete_windows
            *
            8
        )


        if complete_windows > 0:

            windows = (

                Z[
                    :complete_rows
                ]

                .reshape(
                    complete_windows,
                    8,
                    75
                )
            )


            probabilities = predict_windows(
                windows
            )


            source_probability_parts.append(
                probabilities
            )


        pending = (

            Z[
                complete_rows:
            ]

            .copy()
        )


    if source_probability_parts:

        source_probabilities = np.concatenate(
            source_probability_parts
        )

    else:

        source_probabilities = np.empty(
            0,
            dtype=np.float64
        )


    actual_windows = int(
        len(
            source_probabilities
        )
    )


    actual_tail = int(
        len(
            pending
        )
    )


    source_valid = bool(

        actual_windows
        ==
        expected_windows

        and

        actual_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()

        and

        (
            (
                source_probabilities >= 0
            )
            &
            (
                source_probabilities <= 1
            )
        ).all()
    )


    SOURCE_CHECKS_VALID &= source_valid


    if not source_valid:

        raise RuntimeError(
            f"Validation mismatch for "
            f"{source_class}."
        )


    prediction_parts.append(

        pd.DataFrame({

            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                target,

            "malicious_probability":
                source_probabilities
        })
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={actual_windows:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 11 — COMBINE PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (

    VALIDATION_PREDICTIONS[
        "binary_target"
    ]

    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (

    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]

    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


COUNTS_VALID = bool(

    len(y_true)
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDOS_WINDOWS
    ==
    0
)


print("\n[8] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(y_true):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDOS_WINDOWS
)

print(
    "Raw non-finite values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{time.time() - inference_start:.2f} seconds"
)


if not COUNTS_VALID:

    raise RuntimeError(
        "Validation counts invalid."
    )


# ======================================================================
# 12 — THRESHOLD SEARCH
# ======================================================================

print("\n[9] Selecting class_weight validation threshold")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (

    2.0
    *
    threshold_precision
    *
    threshold_recall

    /

    np.maximum(
        threshold_precision
        +
        threshold_recall,
        1e-15
    )
)


MAX_F1 = float(
    np.max(
        threshold_f1
    )
)


candidate_indices = np.flatnonzero(

    np.isclose(
        threshold_f1,
        MAX_F1,
        rtol=0.0,
        atol=1e-12
    )
)


BEST_INDEX = int(

    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Threshold tie-break:",
    "highest threshold"
)


# ======================================================================
# 13 — VALIDATION METRICS
# ======================================================================

predictions = (

    y_probability

    >=

    SELECTED_THRESHOLD

).astype(
    np.int64
)


tn, fp, fn, tp = (

    confusion_matrix(
        y_true,
        predictions,
        labels=[
            0,
            1
        ]
    ).ravel()
)


VALIDATION_PRECISION = float(

    precision_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_RECALL = float(

    recall_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_F1 = float(

    f1_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_FPR = float(

    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_ACCURACY = float(

    accuracy_score(
        y_true,
        predictions
    )
)


VALIDATION_PR_AUC = float(

    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(

    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[10] class_weight validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "TP:",
    int(tp)
)

print(
    "TN:",
    int(tn)
)

print(
    "FP:",
    int(fp)
)

print(
    "FN:",
    int(fn)
)

print(
    "Precision:",
    f"{VALIDATION_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "F1:",
    f"{VALIDATION_F1:.10f}"
)

print(
    "FPR:",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{VALIDATION_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 14 — SAVE VALIDATION ARTIFACTS
# ======================================================================

OUTPUT_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "class_weight"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    OUTPUT_DIR
    / "development_validation_predictions.csv"
)


THRESHOLD_CURVE_PATH = (
    OUTPUT_DIR
    / "validation_threshold_search.csv"
)


RESULT_PATH = (
    OUTPUT_DIR
    / "validation_result.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = predictions


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


pd.DataFrame({

    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1

}).to_csv(
    THRESHOLD_CURVE_PATH,
    index=False
)


validation_result = {

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(y_true)
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        VALIDATION_PRECISION,

    "validation_recall":
        VALIDATION_RECALL,

    "validation_F1":
        VALIDATION_F1,

    "validation_FPR":
        VALIDATION_FPR,

    "validation_accuracy":
        VALIDATION_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "selection_rule":
        "maximize_validation_F1",

    "threshold_tiebreak":
        "highest_threshold",

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    RESULT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        validation_result,
        file,
        indent=4
    )


# ======================================================================
# 15 — UPDATE IMBALANCE REGISTRY
# ======================================================================

print("\n[11] Updating imbalance registry")
print("-" * 78)


registry = pd.read_csv(
    REGISTRY_PATH
)


method_mask = (

    registry[
        "imbalance_method"
    ]
    ==
    IMBALANCE_METHOD
)


if int(
    method_mask.sum()
) != 1:

    raise RuntimeError(
        "Could not uniquely identify class_weight "
        "in imbalance registry."
    )


registry.loc[
    method_mask,
    "status"
] = "validation_complete"


registry.loc[
    method_mask,
    "selected_threshold"
] = SELECTED_THRESHOLD


registry.loc[
    method_mask,
    "validation_F1"
] = VALIDATION_F1


registry.loc[
    method_mask,
    "validation_FPR"
] = VALIDATION_FPR


registry.loc[
    method_mask,
    "validation_recall"
] = VALIDATION_RECALL


registry.loc[
    method_mask,
    "test_metrics_used_for_selection"
] = False


registry.loc[
    method_mask,
    "zero_day_metrics_used_for_selection"
] = False


registry.to_csv(
    REGISTRY_PATH,
    index=False
)


print(
    registry[
        [
            "imbalance_method",
            "status",
            "selected_threshold",
            "validation_F1",
            "validation_FPR",
            "validation_recall"
        ]
    ]
)


# ======================================================================
# 16 — LOCAL REGISTRY COPY
# ======================================================================

LOCAL_REGISTRY_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/imbalance/"
    "fold_01_DDoS"
)


LOCAL_REGISTRY_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_REGISTRY_PATH = (
    LOCAL_REGISTRY_DIR
    / "fold_01_imbalance_experiment_registry.csv"
)


shutil.copy2(
    REGISTRY_PATH,
    LOCAL_REGISTRY_PATH
)


# ======================================================================
# 17 — FINAL VALIDATION
# ======================================================================

completed_configs = int(

    (
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


class_weight_row = (

    registry.loc[
        method_mask
    ]

    .iloc[0]
)


REGISTRY_UPDATE_VALID = bool(

    completed_configs
    ==
    2

    and

    np.isclose(
        float(
            class_weight_row[
                "validation_F1"
            ]
        ),
        VALIDATION_F1
    )

    and

    np.isclose(
        float(
            class_weight_row[
                "validation_FPR"
            ]
        ),
        VALIDATION_FPR
    )
)


ARTIFACTS_VALID = bool(

    PREDICTIONS_PATH.exists()

    and

    THRESHOLD_CURVE_PATH.exists()

    and

    RESULT_PATH.exists()

    and

    REGISTRY_PATH.exists()
)


A32_VALID = bool(

    COUNTS_VALID

    and

    SOURCE_CHECKS_VALID

    and

    PREPROCESSING_VALID

    and

    MODEL_FINITE

    and

    DDOS_WINDOWS == 0

    and

    np.isfinite(
        SELECTED_THRESHOLD
    )

    and

    np.isfinite(
        VALIDATION_F1
    )

    and

    np.isfinite(
        VALIDATION_FPR
    )

    and

    REGISTRY_UPDATE_VALID

    and

    ARTIFACTS_VALID
)


STEP_32_CLASS_WEIGHT_VALIDATION_VALID = (
    A32_VALID
)


print("\n[12] Step A32 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Validation windows             :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDOS_WINDOWS
)

print(
    "Selected threshold             :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Validation F1                  :",
    f"{VALIDATION_F1:.10f}"
)

print(
    "Validation recall              :",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "Validation FPR                 :",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Known-test accessed            :",
    False
)

print(
    "Benign-test accessed           :",
    False
)

print(
    "Zero-day DDoS accessed         :",
    False
)

print(
    "Completed imbalance configs    :",
    completed_configs,
    "/ 3"
)

print(
    "Registry updated               :",
    REGISTRY_UPDATE_VALID
)

print(
    "Artifacts saved                :",
    ARTIFACTS_VALID
)


print("\n" + "=" * 78)

if A32_VALID:

    print(
        "✅ STEP A32 PASSED — "
        "class_weight development-validation "
        "result recorded successfully."
    )

else:

    print(
        "❌ STEP A32 FAILED — "
        "do not start weighted_sampler yet."
    )

print("=" * 78)

==============================================================================
STEP A32 — CLASS_WEIGHT DEVELOPMENT VALIDATION
FOLD 1 | HELD-OUT FAMILY = DDoS
lambda_t = 0.25
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A29 lambda selection valid: True
A30 imbalance protocol valid: True
A31 class_weight fine-tuning valid: True
Device: cuda

[2] Validation configuration
------------------------------------------------------------------------------
lambda_t: 0.25
Imbalance method: class_weight
Seed: 13
Expected validation windows: 167,482
Expected benign windows: 1,715
Expected attack windows: 165,767
Threshold rule: maximize development-validation F1

[3] Verifying frozen A30 protocol
------------------------------------------------------------------------------
Selection partition: development_validation_only
Frozen lambda_t: 0.25
Primary selection metric: development_validation_F1
Test metrics allowed: False
Zero-day metrics allowed: False

[4] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Preprocessing refitted: False

[5] Loading development-validation manifest
------------------------------------------------------------------------------
Validation ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[6] Loading class_weight model
------------------------------------------------------------------------------
Loaded lambda_t: 0.25
Imbalance method: class_weight
Fine-tuning epochs: 20
Benign class weight: 6.5936172870
Attack class weight: 0.5410265345
Model finite: True

[7] Running class_weight validation inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[8] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite values imputed: 1,516
All source checks valid: True
Probability min: 0.0000001557
Probability max: 1.0000000000
Inference runtime: 6.44 seconds

[9] Selecting class_weight validation threshold
------------------------------------------------------------------------------
Threshold candidates: 5,416
Maximum validation F1: 0.9970560673
Selected threshold: 0.0053714495
Max-F1 tie count: 1
Threshold tie-break: highest threshold

[10] class_weight validation metrics
------------------------------------------------------------------------------
Threshold: 0.0053714495
TP: 165446
TN: 1059
FP: 656
FN: 321
Precision: 0.9960506195
Recall: 0.9980635470
F1: 0.9970560673
FPR: 0.3825072886
Accuracy: 0.9941665373
PR-AUC: 0.9999735172
ROC-AUC: 0.9974405854

[11] Updating imbalance registry
------------------------------------------------------------------------------
   imbalance_method               status  selected_threshold  validation_F1  \
0              none  validation_complete            0.014751       0.997267
1      class_weight  validation_complete            0.005371       0.997056
2  weighted_sampler              pending                 NaN            NaN

   validation_FPR  validation_recall
0        0.365598           0.998311
1        0.382507           0.998064
2             NaN                NaN

[12] Step A32 validation
------------------------------------------------------------------------------
lambda_t                       : 0.25
Imbalance method               : class_weight
Validation windows             : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
Selected threshold             : 0.0053714495
Validation F1                  : 0.9970560673
Validation recall              : 0.9980635470
Validation FPR                 : 0.3825072886
Known-test accessed            : False
Benign-test accessed           : False
Zero-day DDoS accessed         : False
Completed imbalance configs    : 2 / 3
Registry updated               : True
Artifacts saved                : True

==============================================================================
✅ STEP A32 PASSED — class_weight development-validation result recorded successfully.
==============================================================================

Step A33 — Fine-tune with weighted_sampler

In [ ]:
# ======================================================================
# STEP A33
# IMBALANCE SENSITIVITY — WEIGHTED-SAMPLER FINE-TUNING
#
# Fold 1: DDoS held out
# Seed: 13
# T = 8
# lambda_t = 0.25 (frozen)
#
# Imbalance method:
#   WeightedRandomSampler
#
# Fine-tuning epochs: 20
#
# NO validation threshold selection here.
# NO known-test access.
# NO benign-test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn.functional as F

from torch.utils.data import (
    DataLoader,
    WeightedRandomSampler
)


print("=" * 78)
print("STEP A33 — WEIGHTED-SAMPLER FINE-TUNING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("lambda_t = 0.25")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_13_PYTORCH_DATA_VALID",
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_29_LAMBDA_SELECTION_VALID",
    "STEP_30_IMBALANCE_PROTOCOL_VALID",
    "STEP_32_CLASS_WEIGHT_VALIDATION_VALID",
    "TRAIN_DATASET",
    "MOTSSLGRU",
    "DEVICE"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:

    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_13_PYTORCH_DATA_VALID:
    raise RuntimeError("A13 did not pass.")

if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_29_LAMBDA_SELECTION_VALID:
    raise RuntimeError("A29 did not pass.")

if not STEP_30_IMBALANCE_PROTOCOL_VALID:
    raise RuntimeError("A30 did not pass.")

if not STEP_32_CLASS_WEIGHT_VALIDATION_VALID:
    raise RuntimeError("A32 did not pass.")


print(
    "A13 data valid:",
    STEP_13_PYTORCH_DATA_VALID
)

print(
    "A14 architecture valid:",
    STEP_14_MODEL_ARCHITECTURE_VALID
)

print(
    "A29 lambda selection valid:",
    STEP_29_LAMBDA_SELECTION_VALID
)

print(
    "A30 imbalance protocol valid:",
    STEP_30_IMBALANCE_PROTOCOL_VALID
)

print(
    "A32 class_weight validation valid:",
    STEP_32_CLASS_WEIGHT_VALIDATION_VALID
)

print(
    "Training windows:",
    f"{len(TRAIN_DATASET):,}"
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — CONTROLLED CONFIGURATION
# ======================================================================

SEED = 13

LAMBDA_T = 0.25

FINETUNE_EPOCHS = 20

BATCH_SIZE = 256

LEARNING_RATE = 1e-3

MAX_GRADIENT_NORM = 5.0

IMBALANCE_METHOD = "weighted_sampler"


print("\n[2] Controlled configuration")
print("-" * 78)

print(
    "lambda_t:",
    LAMBDA_T
)

print(
    "Seed:",
    SEED
)

print(
    "Epochs:",
    FINETUNE_EPOCHS
)

print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Learning rate:",
    LEARNING_RATE
)

print(
    "Imbalance method:",
    IMBALANCE_METHOD
)

print(
    "Precision:",
    "float32"
)


# ======================================================================
# 3 — REPRODUCIBILITY
# ======================================================================

def set_all_seeds(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():

        torch.cuda.manual_seed_all(seed)


set_all_seeds(SEED)


if torch.cuda.is_available():

    torch.backends.cudnn.benchmark = False

    torch.backends.cudnn.deterministic = True


# ======================================================================
# 4 — EXTRACT TRAINING LABELS
# ======================================================================

print("\n[3] Building weighted sampler from training labels only")
print("-" * 78)


LABEL_LOADER = DataLoader(

    TRAIN_DATASET,

    batch_size=4096,

    shuffle=False,

    num_workers=0
)


label_parts = []


for _, y_part in LABEL_LOADER:

    label_parts.append(

        y_part

        .detach()

        .cpu()

        .reshape(-1)

        .to(
            dtype=torch.int64
        )
    )


TRAIN_LABELS = torch.cat(
    label_parts,
    dim=0
)


if len(TRAIN_LABELS) != len(TRAIN_DATASET):

    raise RuntimeError(
        "Training-label extraction count mismatch."
    )


BENIGN_COUNT = int(
    (
        TRAIN_LABELS == 0
    ).sum()
)


ATTACK_COUNT = int(
    (
        TRAIN_LABELS == 1
    ).sum()
)


TOTAL_COUNT = int(
    len(
        TRAIN_LABELS
    )
)


if BENIGN_COUNT != 8_006:

    raise RuntimeError(
        f"Unexpected benign count: "
        f"{BENIGN_COUNT}"
    )


if ATTACK_COUNT != 97_571:

    raise RuntimeError(
        f"Unexpected attack count: "
        f"{ATTACK_COUNT}"
    )


# Balanced inverse-frequency weights.
#
# Absolute scale does not affect sampling probabilities.

BENIGN_SAMPLING_WEIGHT = (

    TOTAL_COUNT

    /

    (
        2.0
        *
        BENIGN_COUNT
    )
)


ATTACK_SAMPLING_WEIGHT = (

    TOTAL_COUNT

    /

    (
        2.0
        *
        ATTACK_COUNT
    )
)


SAMPLE_WEIGHTS = torch.where(

    TRAIN_LABELS == 0,

    torch.full(
        TRAIN_LABELS.shape,
        BENIGN_SAMPLING_WEIGHT,
        dtype=torch.double
    ),

    torch.full(
        TRAIN_LABELS.shape,
        ATTACK_SAMPLING_WEIGHT,
        dtype=torch.double
    )
)


SAMPLER_WEIGHTS_VALID = bool(

    len(SAMPLE_WEIGHTS)
    ==
    TOTAL_COUNT

    and

    torch.isfinite(
        SAMPLE_WEIGHTS
    ).all()

    and

    (
        SAMPLE_WEIGHTS > 0
    ).all()
)


print(
    "Benign windows:",
    f"{BENIGN_COUNT:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_COUNT:,}"
)

print(
    "Total windows:",
    f"{TOTAL_COUNT:,}"
)

print(
    "Benign sampling weight:",
    f"{BENIGN_SAMPLING_WEIGHT:.10f}"
)

print(
    "Attack sampling weight:",
    f"{ATTACK_SAMPLING_WEIGHT:.10f}"
)

print(
    "Sampler weights use training only:",
    True
)

print(
    "Sampler weights valid:",
    SAMPLER_WEIGHTS_VALID
)


if not SAMPLER_WEIGHTS_VALID:

    raise RuntimeError(
        "Weighted sampler weights are invalid."
    )


# ======================================================================
# 5 — LOAD FROZEN lambda=0.25 SSL MODEL
# ======================================================================

print("\n[4] Loading selected lambda=0.25 SSL encoder")
print("-" * 78)


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


SSL_MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "ssl_pretraining"
    / "fold_01_DDoS"
    / "seed_13"
    / "lambda_0p25_fp32"
    / "MOT_SSL_GRU_SSL_pretrained_final.pt"
)


if not SSL_MODEL_PATH.exists():

    raise RuntimeError(
        "Selected lambda=0.25 SSL model "
        "was not found in Drive."
    )


SSL_PACKAGE = torch.load(
    SSL_MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        SSL_PACKAGE[
            "lambda_t"
        ]
    ),
    LAMBDA_T
):

    raise RuntimeError(
        "SSL lambda_t mismatch."
    )


if int(
    SSL_PACKAGE[
        "completed_epochs"
    ]
) != 30:

    raise RuntimeError(
        "SSL model did not complete 30 epochs."
    )


if SSL_PACKAGE.get(
    "labels_used_during_SSL"
):

    raise RuntimeError(
        "SSL package indicates label use."
    )


print(
    "SSL lambda_t:",
    SSL_PACKAGE[
        "lambda_t"
    ]
)

print(
    "SSL epochs:",
    SSL_PACKAGE[
        "completed_epochs"
    ]
)

print(
    "SSL precision:",
    SSL_PACKAGE[
        "precision"
    ]
)

print(
    "Labels used during SSL:",
    SSL_PACKAGE[
        "labels_used_during_SSL"
    ]
)


# ======================================================================
# 6 — CREATE MODEL
# ======================================================================

set_all_seeds(SEED)


WEIGHTED_SAMPLER_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


WEIGHTED_SAMPLER_MODEL.load_state_dict(

    SSL_PACKAGE[
        "model_state_dict"
    ],

    strict=True
)


# ======================================================================
# 7 — FRESH CLASSIFIER INITIALIZATION
# ======================================================================

set_all_seeds(
    SEED + 1000
)


for module in (

    WEIGHTED_SAMPLER_MODEL
    .classifier_head
    .modules()

):

    if hasattr(
        module,
        "reset_parameters"
    ):

        module.reset_parameters()


print(
    "SSL encoder state loaded:",
    True
)

print(
    "Classifier freshly initialized:",
    True
)

print(
    "Classifier initialization seed:",
    SEED + 1000
)


# ======================================================================
# 8 — TRAINABLE PARAMETERS
# ======================================================================

FINETUNE_PARAMETERS = (

    list(
        WEIGHTED_SAMPLER_MODEL
        .feature_encoder
        .parameters()
    )

    +

    list(
        WEIGHTED_SAMPLER_MODEL
        .temporal_encoder
        .parameters()
    )

    +

    list(
        WEIGHTED_SAMPLER_MODEL
        .classifier_head
        .parameters()
    )
)


finetune_ids = {
    id(parameter)
    for parameter in FINETUNE_PARAMETERS
}


projection_ids = {
    id(parameter)
    for parameter in
    WEIGHTED_SAMPLER_MODEL
    .projection_head
    .parameters()
}


order_ids = {
    id(parameter)
    for parameter in
    WEIGHTED_SAMPLER_MODEL
    .temporal_order_head
    .parameters()
}


PROJECTION_INCLUDED = bool(
    finetune_ids
    &
    projection_ids
)


ORDER_INCLUDED = bool(
    finetune_ids
    &
    order_ids
)


if PROJECTION_INCLUDED:

    raise RuntimeError(
        "Projection head must not be fine-tuned."
    )


if ORDER_INCLUDED:

    raise RuntimeError(
        "Temporal-order head must not be fine-tuned."
    )


FINETUNE_PARAMETER_COUNT = sum(

    parameter.numel()

    for parameter
    in FINETUNE_PARAMETERS
)


print(
    "Fine-tuned parameters:",
    f"{FINETUNE_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    PROJECTION_INCLUDED
)

print(
    "Temporal-order head optimized:",
    ORDER_INCLUDED
)


# ======================================================================
# 9 — OPTIMIZER
# ======================================================================

OPTIMIZER = torch.optim.Adam(

    FINETUNE_PARAMETERS,

    lr=LEARNING_RATE
)


# ======================================================================
# 10 — DETERMINISTIC WEIGHTED LOADER
# ======================================================================

def make_weighted_loader(epoch):

    generator = torch.Generator()

    generator.manual_seed(
        SEED
        +
        int(epoch)
    )


    sampler = WeightedRandomSampler(

        weights=SAMPLE_WEIGHTS,

        num_samples=TOTAL_COUNT,

        replacement=True,

        generator=generator
    )


    return DataLoader(

        TRAIN_DATASET,

        batch_size=BATCH_SIZE,

        sampler=sampler,

        shuffle=False,

        num_workers=0,

        pin_memory=torch.cuda.is_available(),

        drop_last=False
    )


# ======================================================================
# 11 — OUTPUT PATHS
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "models/fine_tuning/"
    "fold_01_DDoS/"
    "seed_13/"
    "ssl_lambda_0p25_fp32/"
    "imbalance_weighted_sampler"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_weighted_sampler"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_CHECKPOINT = (
    LOCAL_DIR
    / "latest_checkpoint.pt"
)


DRIVE_CHECKPOINT = (
    DRIVE_DIR
    / "latest_checkpoint.pt"
)


LOCAL_HISTORY = (
    LOCAL_DIR
    / "fine_tuning_history.csv"
)


DRIVE_HISTORY = (
    DRIVE_DIR
    / "fine_tuning_history.csv"
)


LOCAL_FINAL = (
    LOCAL_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


DRIVE_FINAL = (
    DRIVE_DIR
    / "MOT_SSL_GRU_finetuned_final.pt"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fine_tuning_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fine_tuning_policy.json"
)


# ======================================================================
# 12 — SAVE POLICY
# ======================================================================

POLICY = {

    "experiment":
        "imbalance_handling_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "sampling_strategy":
        "inverse_class_frequency",

    "replacement":
        True,

    "samples_per_epoch":
        TOTAL_COUNT,

    "sampling_weights": {

        "benign":
            float(
                BENIGN_SAMPLING_WEIGHT
            ),

        "attack":
            float(
                ATTACK_SAMPLING_WEIGHT
            )
    },

    "sampling_weight_source":
        "training_partition_only",

    "training_benign_windows":
        BENIGN_COUNT,

    "training_attack_windows":
        ATTACK_COUNT,

    "loss":
        "unweighted_binary_cross_entropy_with_logits",

    "epochs":
        FINETUNE_EPOCHS,

    "batch_size":
        BATCH_SIZE,

    "learning_rate":
        LEARNING_RATE,

    "precision":
        "float32",

    "classifier_initialization_seed":
        SEED + 1000,

    "threshold_selected":
        False,

    "validation_used_during_training":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 13 — RESUME SUPPORT
# ======================================================================

print("\n[5] Checking weighted-sampler checkpoint")
print("-" * 78)


START_EPOCH = 1

history = []


if DRIVE_CHECKPOINT.exists():

    checkpoint = torch.load(
        DRIVE_CHECKPOINT,
        map_location=DEVICE,
        weights_only=False
    )


    if (
        checkpoint.get(
            "imbalance_method"
        )
        !=
        IMBALANCE_METHOD
    ):

        raise RuntimeError(
            "Checkpoint imbalance-method mismatch."
        )


    if not np.isclose(
        float(
            checkpoint[
                "lambda_t"
            ]
        ),
        LAMBDA_T
    ):

        raise RuntimeError(
            "Checkpoint lambda_t mismatch."
        )


    WEIGHTED_SAMPLER_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    START_EPOCH = (

        int(
            checkpoint[
                "epoch"
            ]
        )

        +

        1
    )


    if DRIVE_HISTORY.exists():

        history = (

            pd.read_csv(
                DRIVE_HISTORY
            )

            .to_dict(
                orient="records"
            )
        )


    print(
        "Existing checkpoint found."
    )

    print(
        "Next epoch:",
        START_EPOCH
    )


else:

    print(
        "No weighted-sampler checkpoint."
    )

    print(
        "Starting from epoch 1."
    )


# ======================================================================
# 14 — WEIGHTED-SAMPLER FINE-TUNING
# ======================================================================

print("\n[6] Starting weighted-sampler fine-tuning")
print("-" * 78)


NONFINITE_BATCHES = 0


if START_EPOCH <= FINETUNE_EPOCHS:

    for epoch in range(
        START_EPOCH,
        FINETUNE_EPOCHS + 1
    ):

        epoch_start = time.time()


        set_all_seeds(
            SEED
            +
            epoch * 10_000
        )


        loader = make_weighted_loader(
            epoch
        )


        WEIGHTED_SAMPLER_MODEL.train()


        running_loss = 0.0

        total_examples = 0

        correct_at_05 = 0

        predicted_attack_count = 0

        predicted_benign_count = 0

        sampled_attack_count = 0

        sampled_benign_count = 0

        maximum_gradient_norm = 0.0


        for batch_number, (
            X,
            y
        ) in enumerate(
            loader,
            start=1
        ):

            X = X.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            y = y.to(
                DEVICE,
                dtype=torch.float32,
                non_blocking=True
            )


            if not bool(
                torch.isfinite(
                    X
                ).all()
            ):

                raise RuntimeError(
                    f"Non-finite X at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            OPTIMIZER.zero_grad(
                set_to_none=True
            )


            logits = (

                WEIGHTED_SAMPLER_MODEL
                .forward_classifier(
                    X
                )
            )


            # Important:
            # sampler handles the imbalance.
            # Loss itself remains unweighted.
            loss = (

                F.binary_cross_entropy_with_logits(
                    logits,
                    y
                )
            )


            if not bool(
                torch.isfinite(
                    loss
                )
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite BCE at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            loss.backward()


            gradient_norm = (
                torch.nn.utils.clip_grad_norm_(
                    FINETUNE_PARAMETERS,
                    MAX_GRADIENT_NORM
                )
            )


            gradient_norm_value = float(
                gradient_norm
                .detach()
                .cpu()
            )


            if not np.isfinite(
                gradient_norm_value
            ):

                NONFINITE_BATCHES += 1

                raise RuntimeError(
                    f"Non-finite gradient at epoch "
                    f"{epoch}, batch {batch_number}."
                )


            maximum_gradient_norm = max(
                maximum_gradient_norm,
                gradient_norm_value
            )


            OPTIMIZER.step()


            batch_size = int(
                X.shape[0]
            )


            running_loss += (

                float(
                    loss
                    .detach()
                    .cpu()
                )

                *

                batch_size
            )


            total_examples += batch_size


            sampled_attack_count += int(
                (
                    y >= 0.5
                )
                .sum()
                .item()
            )


            sampled_benign_count += int(
                (
                    y < 0.5
                )
                .sum()
                .item()
            )


            # Diagnostic only.
            with torch.no_grad():

                probabilities = torch.sigmoid(
                    logits
                )


                predictions = (
                    probabilities
                    >=
                    0.5
                ).float()


                correct_at_05 += int(
                    (
                        predictions
                        ==
                        y
                    )
                    .sum()
                    .item()
                )


                predicted_attack_count += int(
                    (
                        predictions
                        ==
                        1
                    )
                    .sum()
                    .item()
                )


                predicted_benign_count += int(
                    (
                        predictions
                        ==
                        0
                    )
                    .sum()
                    .item()
                )


            if (
                batch_number % 100 == 0

                or

                batch_number == len(loader)
            ):

                print(
                    f"Epoch {epoch:02d}/"
                    f"{FINETUNE_EPOCHS} "
                    f"| Batch {batch_number:03d}/"
                    f"{len(loader):03d} "
                    f"| BCE="
                    f"{float(loss.detach().cpu()):.6f}"
                )


        if total_examples != TOTAL_COUNT:

            raise RuntimeError(
                f"Epoch {epoch} sampled "
                f"{total_examples} windows instead of "
                f"{TOTAL_COUNT}."
            )


        sampled_benign_fraction = (
            sampled_benign_count
            /
            total_examples
        )


        sampled_attack_fraction = (
            sampled_attack_count
            /
            total_examples
        )


        mean_loss = (
            running_loss
            /
            total_examples
        )


        diagnostic_accuracy = (
            correct_at_05
            /
            total_examples
        )


        predicted_attack_fraction = (
            predicted_attack_count
            /
            total_examples
        )


        predicted_benign_fraction = (
            predicted_benign_count
            /
            total_examples
        )


        epoch_seconds = (
            time.time()
            -
            epoch_start
        )


        record = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "imbalance_method":
                IMBALANCE_METHOD,

            "training_BCE_loss":
                mean_loss,

            "sampled_benign_windows":
                sampled_benign_count,

            "sampled_attack_windows":
                sampled_attack_count,

            "sampled_benign_fraction":
                sampled_benign_fraction,

            "sampled_attack_fraction":
                sampled_attack_fraction,

            "diagnostic_accuracy_at_0p5":
                diagnostic_accuracy,

            "predicted_attack_fraction_at_0p5":
                predicted_attack_fraction,

            "predicted_benign_fraction_at_0p5":
                predicted_benign_fraction,

            "examples":
                total_examples,

            "batches":
                len(loader),

            "maximum_preclip_gradient_norm":
                maximum_gradient_norm,

            "epoch_seconds":
                epoch_seconds
        }


        history = [

            old

            for old in history

            if int(
                old[
                    "epoch"
                ]
            )
            != epoch
        ]


        history.append(
            record
        )


        history_df = (

            pd.DataFrame(
                history
            )

            .sort_values(
                "epoch"
            )

            .reset_index(
                drop=True
            )
        )


        history_df.to_csv(
            LOCAL_HISTORY,
            index=False
        )


        shutil.copy2(
            LOCAL_HISTORY,
            DRIVE_HISTORY
        )


        checkpoint = {

            "epoch":
                epoch,

            "lambda_t":
                LAMBDA_T,

            "imbalance_method":
                IMBALANCE_METHOD,

            "model_state_dict":
                WEIGHTED_SAMPLER_MODEL
                .state_dict(),

            "optimizer_state_dict":
                OPTIMIZER
                .state_dict(),

            "seed":
                SEED,

            "epoch_metrics":
                record
        }


        torch.save(
            checkpoint,
            LOCAL_CHECKPOINT
        )


        shutil.copy2(
            LOCAL_CHECKPOINT,
            DRIVE_CHECKPOINT
        )


        print(
            f"\nEpoch {epoch:02d} complete "
            f"| BCE={mean_loss:.6f} "
            f"| sampled benign="
            f"{sampled_benign_fraction:.4f} "
            f"| sampled attack="
            f"{sampled_attack_fraction:.4f} "
            f"| diagnostic_acc@0.5="
            f"{diagnostic_accuracy:.4f} "
            f"| time={epoch_seconds:.1f}s "
            f"| checkpoint=Drive"
        )


else:

    print(
        "Weighted-sampler fine-tuning already "
        "contains all 20 epochs."
    )


# ======================================================================
# 15 — LOAD HISTORY
# ======================================================================

if LOCAL_HISTORY.exists():

    HISTORY = pd.read_csv(
        LOCAL_HISTORY
    )

else:

    HISTORY = pd.read_csv(
        DRIVE_HISTORY
    )


COMPLETED_EPOCHS = int(
    HISTORY[
        "epoch"
    ].max()
)


print("\n[7] Last 5 weighted-sampler epochs")
print("-" * 78)

display(
    HISTORY.tail(5)
)


# ======================================================================
# 16 — NUMERICAL VALIDATION
# ======================================================================

print("\n[8] Final numerical validation")
print("-" * 78)


PARAMETERS_FINITE = all(

    bool(
        torch.isfinite(
            parameter
        ).all()
    )

    for parameter
    in WEIGHTED_SAMPLER_MODEL.parameters()
)


check_loader = DataLoader(

    TRAIN_DATASET,

    batch_size=64,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(check_loader)
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


WEIGHTED_SAMPLER_MODEL.eval()


with torch.no_grad():

    check_logits = (

        WEIGHTED_SAMPLER_MODEL
        .forward_classifier(
            X_check
        )
    )


    check_probabilities = torch.sigmoid(
        check_logits
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        check_logits
    ).all()

    and

    torch.isfinite(
        check_probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    (
        check_probabilities >= 0
    ).all()

    and

    (
        check_probabilities <= 1
    ).all()
)


FINAL_ROW = (

    HISTORY

    .sort_values(
        "epoch"
    )

    .iloc[-1]
)


FINAL_SAMPLED_BENIGN_FRACTION = float(

    FINAL_ROW[
        "sampled_benign_fraction"
    ]
)


FINAL_SAMPLED_ATTACK_FRACTION = float(

    FINAL_ROW[
        "sampled_attack_fraction"
    ]
)


SAMPLING_BALANCE_VALID = bool(

    0.45
    <=
    FINAL_SAMPLED_BENIGN_FRACTION
    <=
    0.55

    and

    0.45
    <=
    FINAL_SAMPLED_ATTACK_FRACTION
    <=
    0.55
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)

print(
    "Final sampled benign fraction:",
    f"{FINAL_SAMPLED_BENIGN_FRACTION:.6f}"
)

print(
    "Final sampled attack fraction:",
    f"{FINAL_SAMPLED_ATTACK_FRACTION:.6f}"
)

print(
    "Sampling balance valid:",
    SAMPLING_BALANCE_VALID
)


# ======================================================================
# 17 — SAVE FINAL MODEL
# ======================================================================

FINAL_PACKAGE = {

    "model_state_dict":
        WEIGHTED_SAMPLER_MODEL
        .state_dict(),

    "experiment":
        "imbalance_handling_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "SSL_lambda_t":
        LAMBDA_T,

    "completed_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "imbalance_method":
        IMBALANCE_METHOD,

    "sampling_strategy":
        "inverse_class_frequency",

    "sampling_replacement":
        True,

    "samples_per_epoch":
        TOTAL_COUNT,

    "benign_sampling_weight":
        float(
            BENIGN_SAMPLING_WEIGHT
        ),

    "attack_sampling_weight":
        float(
            ATTACK_SAMPLING_WEIGHT
        ),

    "sampling_weight_source":
        "training_partition_only",

    "loss":
        "unweighted_BCEWithLogits",

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False
}


torch.save(
    FINAL_PACKAGE,
    LOCAL_FINAL
)


shutil.copy2(
    LOCAL_FINAL,
    DRIVE_FINAL
)


# ======================================================================
# 18 — FINAL A33 VALIDATION
# ======================================================================

HISTORY_COMPLETE = bool(

    HISTORY[
        "epoch"
    ].nunique()
    ==
    20
)


A33_VALID = bool(

    COMPLETED_EPOCHS == 20

    and

    HISTORY_COMPLETE

    and

    TOTAL_COUNT == 105_577

    and

    BENIGN_COUNT == 8_006

    and

    ATTACK_COUNT == 97_571

    and

    SAMPLER_WEIGHTS_VALID

    and

    SAMPLING_BALANCE_VALID

    and

    NONFINITE_BATCHES == 0

    and

    not PROJECTION_INCLUDED

    and

    not ORDER_INCLUDED

    and

    PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    DRIVE_FINAL.exists()

    and

    DRIVE_CHECKPOINT.exists()

    and

    DRIVE_HISTORY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_33_WEIGHTED_SAMPLER_FINETUNE_VALID = (
    A33_VALID
)


print("\n[9] Step A33 validation")
print("-" * 78)

print(
    "lambda_t                       :",
    LAMBDA_T
)

print(
    "Imbalance method               :",
    IMBALANCE_METHOD
)

print(
    "Completed epochs               :",
    COMPLETED_EPOCHS,
    "/ 20"
)

print(
    "Original benign windows        :",
    f"{BENIGN_COUNT:,}"
)

print(
    "Original attack windows        :",
    f"{ATTACK_COUNT:,}"
)

print(
    "Sampler weights use train only :",
    True
)

print(
    "Samples per epoch              :",
    f"{TOTAL_COUNT:,}"
)

print(
    "Final sampled benign fraction  :",
    f"{FINAL_SAMPLED_BENIGN_FRACTION:.6f}"
)

print(
    "Final sampled attack fraction  :",
    f"{FINAL_SAMPLED_ATTACK_FRACTION:.6f}"
)

print(
    "Sampling balance valid         :",
    SAMPLING_BALANCE_VALID
)

print(
    "Loss class-weighted            :",
    False
)

print(
    "Threshold selected             :",
    False
)

print(
    "Known-test used                :",
    False
)

print(
    "Benign-test used               :",
    False
)

print(
    "Zero-day DDoS used             :",
    False
)

print(
    "Final BCE                      :",
    f"{float(FINAL_ROW['training_BCE_loss']):.6f}"
)

print(
    "Non-finite batches             :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite              :",
    PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Final model backed up          :",
    DRIVE_FINAL.exists()
)

print(
    "Training history backed up     :",
    DRIVE_HISTORY.exists()
)


print("\n" + "=" * 78)

if A33_VALID:

    print(
        "✅ STEP A33 PASSED — "
        "weighted_sampler completed controlled "
        "20-epoch supervised fine-tuning."
    )

else:

    print(
        "❌ STEP A33 INCOMPLETE — "
        "do not continue to validation yet."
    )

print("=" * 78)

==============================================================================
STEP A33 — WEIGHTED-SAMPLER FINE-TUNING
FOLD 1 | HELD-OUT FAMILY = DDoS
lambda_t = 0.25
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A13 data valid: True
A14 architecture valid: True
A29 lambda selection valid: True
A30 imbalance protocol valid: True
A32 class_weight validation valid: True
Training windows: 105,577
Device: cuda

[2] Controlled configuration
------------------------------------------------------------------------------
lambda_t: 0.25
Seed: 13
Epochs: 20
Batch size: 256
Learning rate: 0.001
Imbalance method: weighted_sampler
Precision: float32

[3] Building weighted sampler from training labels only
------------------------------------------------------------------------------
Benign windows: 8,006
Attack windows: 97,571
Total windows: 105,577
Benign sampling weight: 6.5936172870
Attack sampling weight: 0.5410265345
Sampler weights use training only: True
Sampler weights valid: True

[4] Loading selected lambda=0.25 SSL encoder
------------------------------------------------------------------------------
SSL lambda_t: 0.25
SSL epochs: 30
SSL precision: float32
Labels used during SSL: False
SSL encoder state loaded: True
Classifier freshly initialized: True
Classifier initialization seed: 1013
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[5] Checking weighted-sampler checkpoint
------------------------------------------------------------------------------
No weighted-sampler checkpoint.
Starting from epoch 1.

[6] Starting weighted-sampler fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/413 | BCE=0.195572
Epoch 01/20 | Batch 200/413 | BCE=0.169635
Epoch 01/20 | Batch 300/413 | BCE=0.139210
Epoch 01/20 | Batch 400/413 | BCE=0.123697
Epoch 01/20 | Batch 413/413 | BCE=0.117132

Epoch 01 complete | BCE=0.186025 | sampled benign=0.5027 | sampled attack=0.4973 | diagnostic_acc@0.5=0.9289 | time=8.1s | checkpoint=Drive
Epoch 02/20 | Batch 100/413 | BCE=0.128616
Epoch 02/20 | Batch 200/413 | BCE=0.073896
Epoch 02/20 | Batch 300/413 | BCE=0.064542
Epoch 02/20 | Batch 400/413 | BCE=0.090256
Epoch 02/20 | Batch 413/413 | BCE=0.066520

Epoch 02 complete | BCE=0.105708 | sampled benign=0.5010 | sampled attack=0.4990 | diagnostic_acc@0.5=0.9631 | time=7.4s | checkpoint=Drive
Epoch 03/20 | Batch 100/413 | BCE=0.098240
Epoch 03/20 | Batch 200/413 | BCE=0.040780
Epoch 03/20 | Batch 300/413 | BCE=0.076449
Epoch 03/20 | Batch 400/413 | BCE=0.050407
Epoch 03/20 | Batch 413/413 | BCE=0.228730

Epoch 03 complete | BCE=0.081757 | sampled benign=0.4980 | sampled attack=0.5020 | diagnostic_acc@0.5=0.9724 | time=8.1s | checkpoint=Drive
Epoch 04/20 | Batch 100/413 | BCE=0.100575
Epoch 04/20 | Batch 200/413 | BCE=0.094204
Epoch 04/20 | Batch 300/413 | BCE=0.058896
Epoch 04/20 | Batch 400/413 | BCE=0.083033
Epoch 04/20 | Batch 413/413 | BCE=0.125066

Epoch 04 complete | BCE=0.068044 | sampled benign=0.5030 | sampled attack=0.4970 | diagnostic_acc@0.5=0.9775 | time=7.1s | checkpoint=Drive
Epoch 05/20 | Batch 100/413 | BCE=0.059119
Epoch 05/20 | Batch 200/413 | BCE=0.059837
Epoch 05/20 | Batch 300/413 | BCE=0.020489
Epoch 05/20 | Batch 400/413 | BCE=0.087056
Epoch 05/20 | Batch 413/413 | BCE=0.050334

Epoch 05 complete | BCE=0.059921 | sampled benign=0.4990 | sampled attack=0.5010 | diagnostic_acc@0.5=0.9814 | time=6.9s | checkpoint=Drive
Epoch 06/20 | Batch 100/413 | BCE=0.074517
Epoch 06/20 | Batch 200/413 | BCE=0.055263
Epoch 06/20 | Batch 300/413 | BCE=0.101093
Epoch 06/20 | Batch 400/413 | BCE=0.037374
Epoch 06/20 | Batch 413/413 | BCE=0.034258

Epoch 06 complete | BCE=0.052290 | sampled benign=0.4987 | sampled attack=0.5013 | diagnostic_acc@0.5=0.9838 | time=5.5s | checkpoint=Drive
Epoch 07/20 | Batch 100/413 | BCE=0.078972
Epoch 07/20 | Batch 200/413 | BCE=0.046926
Epoch 07/20 | Batch 300/413 | BCE=0.046894
Epoch 07/20 | Batch 400/413 | BCE=0.013179
Epoch 07/20 | Batch 413/413 | BCE=0.007596

Epoch 07 complete | BCE=0.046794 | sampled benign=0.4981 | sampled attack=0.5019 | diagnostic_acc@0.5=0.9854 | time=4.9s | checkpoint=Drive
Epoch 08/20 | Batch 100/413 | BCE=0.068564
Epoch 08/20 | Batch 200/413 | BCE=0.054585
Epoch 08/20 | Batch 300/413 | BCE=0.079693
Epoch 08/20 | Batch 400/413 | BCE=0.017673
Epoch 08/20 | Batch 413/413 | BCE=0.066913

Epoch 08 complete | BCE=0.041893 | sampled benign=0.4976 | sampled attack=0.5024 | diagnostic_acc@0.5=0.9875 | time=3.9s | checkpoint=Drive
Epoch 09/20 | Batch 100/413 | BCE=0.061112
Epoch 09/20 | Batch 200/413 | BCE=0.004385
Epoch 09/20 | Batch 300/413 | BCE=0.038948
Epoch 09/20 | Batch 400/413 | BCE=0.041157
Epoch 09/20 | Batch 413/413 | BCE=0.080160

Epoch 09 complete | BCE=0.038677 | sampled benign=0.4992 | sampled attack=0.5008 | diagnostic_acc@0.5=0.9882 | time=3.9s | checkpoint=Drive
Epoch 10/20 | Batch 100/413 | BCE=0.039354
Epoch 10/20 | Batch 200/413 | BCE=0.023156
Epoch 10/20 | Batch 300/413 | BCE=0.004629
Epoch 10/20 | Batch 400/413 | BCE=0.069927
Epoch 10/20 | Batch 413/413 | BCE=0.013908

Epoch 10 complete | BCE=0.033434 | sampled benign=0.4994 | sampled attack=0.5006 | diagnostic_acc@0.5=0.9898 | time=4.5s | checkpoint=Drive
Epoch 11/20 | Batch 100/413 | BCE=0.017933
Epoch 11/20 | Batch 200/413 | BCE=0.049058
Epoch 11/20 | Batch 300/413 | BCE=0.028968
Epoch 11/20 | Batch 400/413 | BCE=0.008459
Epoch 11/20 | Batch 413/413 | BCE=0.091389

Epoch 11 complete | BCE=0.032465 | sampled benign=0.4986 | sampled attack=0.5014 | diagnostic_acc@0.5=0.9899 | time=4.3s | checkpoint=Drive
Epoch 12/20 | Batch 100/413 | BCE=0.013836
Epoch 12/20 | Batch 200/413 | BCE=0.023792
Epoch 12/20 | Batch 300/413 | BCE=0.030804
Epoch 12/20 | Batch 400/413 | BCE=0.009667
Epoch 12/20 | Batch 413/413 | BCE=0.015534

Epoch 12 complete | BCE=0.029297 | sampled benign=0.5023 | sampled attack=0.4977 | diagnostic_acc@0.5=0.9907 | time=3.9s | checkpoint=Drive
Epoch 13/20 | Batch 100/413 | BCE=0.019194
Epoch 13/20 | Batch 200/413 | BCE=0.042294
Epoch 13/20 | Batch 300/413 | BCE=0.025282
Epoch 13/20 | Batch 400/413 | BCE=0.023897
Epoch 13/20 | Batch 413/413 | BCE=0.010413

Epoch 13 complete | BCE=0.027381 | sampled benign=0.5024 | sampled attack=0.4976 | diagnostic_acc@0.5=0.9915 | time=4.0s | checkpoint=Drive
Epoch 14/20 | Batch 100/413 | BCE=0.002459
Epoch 14/20 | Batch 200/413 | BCE=0.031910
Epoch 14/20 | Batch 300/413 | BCE=0.033252
Epoch 14/20 | Batch 400/413 | BCE=0.044387
Epoch 14/20 | Batch 413/413 | BCE=0.012239

Epoch 14 complete | BCE=0.025900 | sampled benign=0.4989 | sampled attack=0.5011 | diagnostic_acc@0.5=0.9923 | time=4.8s | checkpoint=Drive
Epoch 15/20 | Batch 100/413 | BCE=0.007540
Epoch 15/20 | Batch 200/413 | BCE=0.003476
Epoch 15/20 | Batch 300/413 | BCE=0.020411
Epoch 15/20 | Batch 400/413 | BCE=0.010588
Epoch 15/20 | Batch 413/413 | BCE=0.046634

Epoch 15 complete | BCE=0.022462 | sampled benign=0.4974 | sampled attack=0.5026 | diagnostic_acc@0.5=0.9932 | time=3.9s | checkpoint=Drive
Epoch 16/20 | Batch 100/413 | BCE=0.029935
Epoch 16/20 | Batch 200/413 | BCE=0.020724
Epoch 16/20 | Batch 300/413 | BCE=0.010885
Epoch 16/20 | Batch 400/413 | BCE=0.030343
Epoch 16/20 | Batch 413/413 | BCE=0.014713

Epoch 16 complete | BCE=0.022023 | sampled benign=0.5004 | sampled attack=0.4996 | diagnostic_acc@0.5=0.9931 | time=3.9s | checkpoint=Drive
Epoch 17/20 | Batch 100/413 | BCE=0.003617
Epoch 17/20 | Batch 200/413 | BCE=0.028399
Epoch 17/20 | Batch 300/413 | BCE=0.035818
Epoch 17/20 | Batch 400/413 | BCE=0.029653
Epoch 17/20 | Batch 413/413 | BCE=0.055796

Epoch 17 complete | BCE=0.021037 | sampled benign=0.5020 | sampled attack=0.4980 | diagnostic_acc@0.5=0.9935 | time=4.8s | checkpoint=Drive
Epoch 18/20 | Batch 100/413 | BCE=0.006758
Epoch 18/20 | Batch 200/413 | BCE=0.027392
Epoch 18/20 | Batch 300/413 | BCE=0.028827
Epoch 18/20 | Batch 400/413 | BCE=0.012742
Epoch 18/20 | Batch 413/413 | BCE=0.003977

Epoch 18 complete | BCE=0.019452 | sampled benign=0.4975 | sampled attack=0.5025 | diagnostic_acc@0.5=0.9941 | time=4.0s | checkpoint=Drive
Epoch 19/20 | Batch 100/413 | BCE=0.025741
Epoch 19/20 | Batch 200/413 | BCE=0.010332
Epoch 19/20 | Batch 300/413 | BCE=0.012643
Epoch 19/20 | Batch 400/413 | BCE=0.013972
Epoch 19/20 | Batch 413/413 | BCE=0.002024

Epoch 19 complete | BCE=0.016985 | sampled benign=0.4978 | sampled attack=0.5022 | diagnostic_acc@0.5=0.9951 | time=3.8s | checkpoint=Drive
Epoch 20/20 | Batch 100/413 | BCE=0.028117
Epoch 20/20 | Batch 200/413 | BCE=0.029551
Epoch 20/20 | Batch 300/413 | BCE=0.009775
Epoch 20/20 | Batch 400/413 | BCE=0.038164
Epoch 20/20 | Batch 413/413 | BCE=0.024360

Epoch 20 complete | BCE=0.015768 | sampled benign=0.5000 | sampled attack=0.5000 | diagnostic_acc@0.5=0.9953 | time=4.3s | checkpoint=Drive

[7] Last 5 weighted-sampler epochs
------------------------------------------------------------------------------

,epoch,lambda_t,imbalance_method,training_BCE_loss,sampled_benign_windows,sampled_attack_windows,sampled_benign_fraction,sampled_attack_fraction,diagnostic_accuracy_at_0p5,predicted_attack_fraction_at_0p5,predicted_benign_fraction_at_0p5,examples,batches,maximum_preclip_gradient_norm,epoch_seconds
15,16,0.25,weighted_sampler,0.022023,52828,52749,0.500374,0.499626,0.993133,0.495752,0.504248,105577,413,1.414035,3.877315
16,17,0.25,weighted_sampler,0.021037,52995,52582,0.501956,0.498044,0.993502,0.494483,0.505517,105577,413,1.521512,4.770730
17,18,0.25,weighted_sampler,0.019452,52524,53053,0.497495,0.502505,0.994109,0.499626,0.500374,105577,413,1.578684,3.976226
18,19,0.25,weighted_sampler,0.016985,52552,53025,0.497760,0.502240,0.995094,0.499493,0.500507,105577,413,1.542627,3.849116
19,20,0.25,weighted_sampler,0.015768,52787,52790,0.499986,0.500014,0.995293,0.497542,0.502458,105577,413,1.838960,4.295415

[8] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
Parameters finite: True
Outputs finite: True
Probability range valid: True
Final sampled benign fraction: 0.499986
Final sampled attack fraction: 0.500014
Sampling balance valid: True

[9] Step A33 validation
------------------------------------------------------------------------------
lambda_t                       : 0.25
Imbalance method               : weighted_sampler
Completed epochs               : 20 / 20
Original benign windows        : 8,006
Original attack windows        : 97,571
Sampler weights use train only : True
Samples per epoch              : 105,577
Final sampled benign fraction  : 0.499986
Final sampled attack fraction  : 0.500014
Sampling balance valid         : True
Loss class-weighted            : False
Threshold selected             : False
Known-test used                : False
Benign-test used               : False
Zero-day DDoS used             : False
Final BCE                      : 0.015768
Non-finite batches             : 0
Parameters finite              : True
Outputs finite                 : True
Final model backed up          : True
Training history backed up     : True

==============================================================================
✅ STEP A33 PASSED — weighted_sampler completed controlled 20-epoch supervised fine-tuning.
==============================================================================

# Step A34 — Validate weighted_sampler and select final imbalance method

In [ ]:
# ======================================================================
# STEP A34
# WEIGHTED_SAMPLER DEVELOPMENT VALIDATION
# + FINAL IMBALANCE-METHOD SELECTION
#
# Fold 1: DDoS held out
# lambda_t = 0.25
#
# DEVELOPMENT VALIDATION ONLY.
#
# NO known-test access.
# NO benign-test access.
# NO zero-day DDoS access.
# ======================================================================

from pathlib import Path
import json
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

import torch

from sklearn.metrics import (
    precision_recall_curve,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    accuracy_score,
    average_precision_score,
    roc_auc_score
)


print("=" * 78)
print("STEP A34 — WEIGHTED_SAMPLER VALIDATION + FINAL IMBALANCE SELECTION")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("lambda_t = 0.25")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_14_MODEL_ARCHITECTURE_VALID",
    "STEP_29_LAMBDA_SELECTION_VALID",
    "STEP_30_IMBALANCE_PROTOCOL_VALID",
    "STEP_33_WEIGHTED_SAMPLER_FINETUNE_VALID",
    "MOTSSLGRU",
    "DEVICE"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_14_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A14 did not pass.")

if not STEP_29_LAMBDA_SELECTION_VALID:
    raise RuntimeError("A29 did not pass.")

if not STEP_30_IMBALANCE_PROTOCOL_VALID:
    raise RuntimeError("A30 did not pass.")

if not STEP_33_WEIGHTED_SAMPLER_FINETUNE_VALID:
    raise RuntimeError("A33 did not pass.")


print("A14 architecture valid:", STEP_14_MODEL_ARCHITECTURE_VALID)
print("A29 lambda selection valid:", STEP_29_LAMBDA_SELECTION_VALID)
print("A30 imbalance protocol valid:", STEP_30_IMBALANCE_PROTOCOL_VALID)
print("A33 weighted_sampler fine-tuning valid:",
      STEP_33_WEIGHTED_SAMPLER_FINETUNE_VALID)
print("Device:", DEVICE)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

LAMBDA_T = 0.25
IMBALANCE_METHOD = "weighted_sampler"
SEED = 13

EXPECTED_WINDOWS = 167_482
EXPECTED_BENIGN = 1_715
EXPECTED_ATTACK = 165_767


print("\n[2] Validation configuration")
print("-" * 78)

print("lambda_t:", LAMBDA_T)
print("Imbalance method:", IMBALANCE_METHOD)
print("Seed:", SEED)
print("Expected validation windows:", f"{EXPECTED_WINDOWS:,}")
print("Expected benign windows:", f"{EXPECTED_BENIGN:,}")
print("Expected attack windows:", f"{EXPECTED_ATTACK:,}")
print("Threshold rule:", "maximize development-validation F1")


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


TEMPORAL_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


MODEL_PATH = (
    BACKUP_ROOT
    / "models"
    / "fine_tuning"
    / "fold_01_DDoS"
    / "seed_13"
    / "ssl_lambda_0p25_fp32"
    / "imbalance_weighted_sampler"
    / "MOT_SSL_GRU_finetuned_final.pt"
)


REGISTRY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "fold_01_imbalance_experiment_registry.csv"
)


POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "fold_01_imbalance_selection_policy.json"
)


for path in [
    CHRONOLOGICAL_ROOT,
    TEMPORAL_MANIFEST_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH,
    MODEL_PATH,
    REGISTRY_PATH,
    POLICY_PATH
]:
    if not path.exists():
        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 4 — VERIFY FROZEN A30 POLICY
# ======================================================================

print("\n[3] Verifying frozen A30 protocol")
print("-" * 78)


with open(
    POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:
    imbalance_policy = json.load(file)


if (
    imbalance_policy["selection_data"]
    !=
    "development_validation_only"
):
    raise RuntimeError(
        "A30 selection partition mismatch."
    )


if not np.isclose(
    float(imbalance_policy["lambda_t"]),
    LAMBDA_T
):
    raise RuntimeError(
        "A30 frozen lambda_t mismatch."
    )


if imbalance_policy[
    "test_data_allowed_for_selection"
]:
    raise RuntimeError(
        "Test data is incorrectly allowed."
    )


if imbalance_policy[
    "zero_day_data_allowed_for_selection"
]:
    raise RuntimeError(
        "Zero-day data is incorrectly allowed."
    )


print(
    "Selection partition:",
    imbalance_policy["selection_data"]
)

print(
    "Frozen lambda_t:",
    imbalance_policy["lambda_t"]
)

print(
    "Primary metric:",
    imbalance_policy[
        "primary_selection_metric"
    ]
)

print(
    "Tie-break 1:",
    imbalance_policy["tiebreak_1"]
)

print(
    "Tie-break 2:",
    imbalance_policy["tiebreak_2"]
)

print("Test metrics allowed:", False)
print("Zero-day metrics allowed:", False)


# ======================================================================
# 5 — LOAD FROZEN PREPROCESSING
# ======================================================================

print("\n[4] Loading frozen preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:
    RETAINED_FEATURES = json.load(file)


if len(RETAINED_FEATURES) != 75:
    raise RuntimeError(
        "Expected 75 retained features."
    )


parameter_lookup = (
    parameters
    .set_index("feature")
    .loc[RETAINED_FEATURES]
)


IMPUTE_VALUES = (
    parameter_lookup[
        "imputation_value"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (
    parameter_lookup[
        "scaler_mean"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (
    parameter_lookup[
        "scaler_std"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(
    np.isfinite(
        IMPUTE_VALUES
    ).all()
    and
    np.isfinite(
        SCALER_MEANS
    ).all()
    and
    np.isfinite(
        SCALER_STDS
    ).all()
    and
    (
        SCALER_STDS > 0
    ).all()
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)


if not PREPROCESSING_VALID:
    raise RuntimeError(
        "Frozen preprocessing invalid."
    )


# ======================================================================
# 6 — LOAD DEVELOPMENT-VALIDATION MANIFEST
# ======================================================================

print("\n[5] Loading development-validation manifest")
print("-" * 78)


manifest = pd.read_csv(
    TEMPORAL_MANIFEST_PATH
)


VAL_MANIFEST = (
    manifest.loc[
        manifest["partition"]
        ==
        "development_validation"
    ]
    .copy()
    .reset_index(
        drop=True
    )
)


MANIFEST_WINDOWS = int(
    VAL_MANIFEST[
        "window_count"
    ].sum()
)


DDOS_WINDOWS = int(
    VAL_MANIFEST.loc[
        VAL_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


print(
    "Validation ranges:",
    len(VAL_MANIFEST)
)

print(
    "Validation windows:",
    f"{MANIFEST_WINDOWS:,}"
)

print(
    "DDoS validation windows:",
    DDOS_WINDOWS
)


if len(VAL_MANIFEST) != 21:
    raise RuntimeError(
        "Expected 21 validation source ranges."
    )


if MANIFEST_WINDOWS != EXPECTED_WINDOWS:
    raise RuntimeError(
        "Validation window count mismatch."
    )


if DDOS_WINDOWS != 0:
    raise RuntimeError(
        "Held-out DDoS appeared in validation."
    )


# ======================================================================
# 7 — LOAD WEIGHTED-SAMPLER MODEL
# ======================================================================

print("\n[6] Loading weighted_sampler model")
print("-" * 78)


model_package = torch.load(
    MODEL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if not np.isclose(
    float(
        model_package[
            "SSL_lambda_t"
        ]
    ),
    LAMBDA_T
):
    raise RuntimeError(
        "Model lambda_t mismatch."
    )


if (
    model_package[
        "imbalance_method"
    ]
    !=
    IMBALANCE_METHOD
):
    raise RuntimeError(
        "Model imbalance method mismatch."
    )


if model_package.get(
    "threshold_selected"
):
    raise RuntimeError(
        "Model already indicates threshold selection."
    )


MODEL = MOTSSLGRU(
    input_dim=75,
    feature_embed_dim=128,
    gru_hidden_dim=128,
    gru_num_layers=1,
    projection_dim=64,
    order_hidden_dim=128,
    classifier_hidden_dim=64,
    dropout=0.10
).to(
    DEVICE
).float()


MODEL.load_state_dict(
    model_package[
        "model_state_dict"
    ],
    strict=True
)


MODEL.eval()


MODEL_FINITE = all(
    bool(
        torch.isfinite(
            parameter
        ).all()
    )
    for parameter
    in MODEL.parameters()
)


print(
    "Loaded lambda_t:",
    model_package[
        "SSL_lambda_t"
    ]
)

print(
    "Imbalance method:",
    model_package[
        "imbalance_method"
    ]
)

print(
    "Fine-tuning epochs:",
    model_package[
        "completed_epochs"
    ]
)

print(
    "Sampling strategy:",
    model_package[
        "sampling_strategy"
    ]
)

print(
    "Model finite:",
    MODEL_FINITE
)


if not MODEL_FINITE:
    raise RuntimeError(
        "Model parameters are non-finite."
    )


# ======================================================================
# 8 — FROZEN PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(table):

    X = (
        table
        .to_pandas()
        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(X)
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        rows, cols = np.where(
            bad_mask
        )

        X[
            rows,
            cols
        ] = IMPUTE_VALUES[
            cols
        ]


    Z = (
        X
        -
        SCALER_MEANS
    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():
        raise RuntimeError(
            "Non-finite transformed values."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():
        raise RuntimeError(
            "Non-finite float32 values."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 9 — MODEL INFERENCE FUNCTION
# ======================================================================

INFERENCE_BATCH_SIZE = 2048


def predict_windows(windows):

    probability_parts = []


    for start in range(
        0,
        len(windows),
        INFERENCE_BATCH_SIZE
    ):

        stop = min(
            start
            +
            INFERENCE_BATCH_SIZE,
            len(windows)
        )


        X = torch.from_numpy(
            windows[
                start:stop
            ]
        ).to(
            DEVICE,
            dtype=torch.float32
        )


        with torch.no_grad():

            logits = (
                MODEL
                .forward_classifier(
                    X
                )
            )

            probabilities = (
                torch.sigmoid(
                    logits
                )
            )


        if not bool(
            torch.isfinite(
                probabilities
            ).all()
        ):
            raise RuntimeError(
                "Non-finite validation probabilities."
            )


        probability_parts.append(
            probabilities
            .detach()
            .cpu()
            .numpy()
            .astype(
                np.float64
            )
        )


    return np.concatenate(
        probability_parts
    )


# ======================================================================
# 10 — RUN DEVELOPMENT-VALIDATION INFERENCE
# ======================================================================

print("\n[7] Running weighted_sampler validation inference")
print("-" * 78)


prediction_parts = []

TOTAL_RAW_NONFINITE = 0

SOURCE_CHECKS_VALID = True

inference_start = time.time()


for source_number, row in VAL_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )

    family = str(
        row[
            "research_family"
        ]
    )

    target = int(
        row[
            "binary_target"
        ]
    )

    partition_start = int(
        row[
            "partition_start_row"
        ]
    )

    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )

    expected_windows = int(
        row[
            "window_count"
        ]
    )

    expected_tail = int(
        row[
            "unused_tail_rows"
        ]
    )

    parquet_name = Path(
        str(
            row[
                "parquet_path"
            ]
        )
    ).name

    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():
        raise RuntimeError(
            f"Missing Parquet: {parquet_name}"
        )


    if family == "DDoS":
        raise RuntimeError(
            "Held-out DDoS reached validation inference."
        )


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    pending = np.empty(
        (
            0,
            75
        ),
        dtype=np.float32
    )


    source_probability_parts = []

    source_raw_nonfinite = 0

    absolute_row = 0


    for row_group_index in range(
        parquet_file.num_row_groups
    ):

        row_group_rows = int(
            parquet_file
            .metadata
            .row_group(
                row_group_index
            )
            .num_rows
        )


        group_start = absolute_row
        group_end = (
            group_start
            +
            row_group_rows
        )

        absolute_row = group_end


        if group_end <= partition_start:
            continue


        if group_start >= partition_end:
            break


        table = parquet_file.read_row_group(
            row_group_index,
            columns=RETAINED_FEATURES
        )


        local_start = max(
            0,
            partition_start
            -
            group_start
        )


        local_end = min(
            row_group_rows,
            partition_end
            -
            group_start
        )


        if local_end <= local_start:
            continue


        table = table.slice(
            local_start,
            local_end
            -
            local_start
        )


        Z, bad_count = (
            frozen_preprocess(
                table
            )
        )


        source_raw_nonfinite += (
            bad_count
        )


        if len(pending) > 0:

            Z = np.concatenate(
                [
                    pending,
                    Z
                ],
                axis=0
            )


        complete_windows = (
            len(Z)
            //
            8
        )


        complete_rows = (
            complete_windows
            *
            8
        )


        if complete_windows > 0:

            windows = (
                Z[
                    :complete_rows
                ]
                .reshape(
                    complete_windows,
                    8,
                    75
                )
            )


            probabilities = (
                predict_windows(
                    windows
                )
            )


            source_probability_parts.append(
                probabilities
            )


        pending = (
            Z[
                complete_rows:
            ]
            .copy()
        )


    if source_probability_parts:

        source_probabilities = (
            np.concatenate(
                source_probability_parts
            )
        )

    else:

        source_probabilities = (
            np.empty(
                0,
                dtype=np.float64
            )
        )


    actual_windows = int(
        len(
            source_probabilities
        )
    )


    actual_tail = int(
        len(
            pending
        )
    )


    source_valid = bool(
        actual_windows
        ==
        expected_windows

        and

        actual_tail
        ==
        expected_tail

        and

        np.isfinite(
            source_probabilities
        ).all()

        and

        (
            (
                source_probabilities >= 0
            )
            &
            (
                source_probabilities <= 1
            )
        ).all()
    )


    SOURCE_CHECKS_VALID &= (
        source_valid
    )


    if not source_valid:
        raise RuntimeError(
            f"Validation mismatch for "
            f"{source_class}."
        )


    prediction_parts.append(
        pd.DataFrame({
            "source_attack_class":
                source_class,

            "research_family":
                family,

            "binary_target":
                target,

            "malicious_probability":
                source_probabilities
        })
    )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    print(
        f"{source_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| windows={actual_windows:>7,} "
        f"| target={target} "
        f"| raw_nonfinite="
        f"{source_raw_nonfinite:,}"
    )


# ======================================================================
# 11 — COMBINE VALIDATION PREDICTIONS
# ======================================================================

VALIDATION_PREDICTIONS = pd.concat(
    prediction_parts,
    ignore_index=True
)


y_true = (
    VALIDATION_PREDICTIONS[
        "binary_target"
    ]
    .to_numpy(
        dtype=np.int64
    )
)


y_probability = (
    VALIDATION_PREDICTIONS[
        "malicious_probability"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


BENIGN_WINDOWS = int(
    (
        y_true == 0
    ).sum()
)


ATTACK_WINDOWS = int(
    (
        y_true == 1
    ).sum()
)


COUNTS_VALID = bool(
    len(y_true)
    ==
    EXPECTED_WINDOWS

    and

    BENIGN_WINDOWS
    ==
    EXPECTED_BENIGN

    and

    ATTACK_WINDOWS
    ==
    EXPECTED_ATTACK

    and

    DDOS_WINDOWS
    ==
    0
)


print("\n[8] Validation inference summary")
print("-" * 78)

print(
    "Prediction rows:",
    f"{len(y_true):,}"
)

print(
    "Benign windows:",
    f"{BENIGN_WINDOWS:,}"
)

print(
    "Attack windows:",
    f"{ATTACK_WINDOWS:,}"
)

print(
    "DDoS windows:",
    DDOS_WINDOWS
)

print(
    "Raw non-finite values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "All source checks valid:",
    SOURCE_CHECKS_VALID
)

print(
    "Probability min:",
    f"{y_probability.min():.10f}"
)

print(
    "Probability max:",
    f"{y_probability.max():.10f}"
)

print(
    "Inference runtime:",
    f"{time.time() - inference_start:.2f} seconds"
)


if not COUNTS_VALID:
    raise RuntimeError(
        "Validation counts invalid."
    )


# ======================================================================
# 12 — THRESHOLD SEARCH
# ======================================================================

print("\n[9] Selecting weighted_sampler validation threshold")
print("-" * 78)


precision_curve, recall_curve, thresholds = (
    precision_recall_curve(
        y_true,
        y_probability
    )
)


threshold_precision = (
    precision_curve[:-1]
)


threshold_recall = (
    recall_curve[:-1]
)


threshold_f1 = (
    2.0
    *
    threshold_precision
    *
    threshold_recall
    /
    np.maximum(
        threshold_precision
        +
        threshold_recall,
        1e-15
    )
)


MAX_F1 = float(
    np.max(
        threshold_f1
    )
)


candidate_indices = np.flatnonzero(
    np.isclose(
        threshold_f1,
        MAX_F1,
        rtol=0.0,
        atol=1e-12
    )
)


BEST_INDEX = int(
    candidate_indices[
        np.argmax(
            thresholds[
                candidate_indices
            ]
        )
    ]
)


SELECTED_THRESHOLD = float(
    thresholds[
        BEST_INDEX
    ]
)


print(
    "Threshold candidates:",
    f"{len(thresholds):,}"
)

print(
    "Maximum validation F1:",
    f"{MAX_F1:.10f}"
)

print(
    "Selected threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "Max-F1 tie count:",
    len(candidate_indices)
)

print(
    "Threshold tie-break:",
    "highest threshold"
)


# ======================================================================
# 13 — VALIDATION METRICS
# ======================================================================

predictions = (
    y_probability
    >=
    SELECTED_THRESHOLD
).astype(
    np.int64
)


tn, fp, fn, tp = (
    confusion_matrix(
        y_true,
        predictions,
        labels=[
            0,
            1
        ]
    ).ravel()
)


VALIDATION_PRECISION = float(
    precision_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_RECALL = float(
    recall_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_F1 = float(
    f1_score(
        y_true,
        predictions,
        zero_division=0
    )
)


VALIDATION_FPR = float(
    fp
    /
    max(
        fp + tn,
        1
    )
)


VALIDATION_ACCURACY = float(
    accuracy_score(
        y_true,
        predictions
    )
)


VALIDATION_PR_AUC = float(
    average_precision_score(
        y_true,
        y_probability
    )
)


VALIDATION_ROC_AUC = float(
    roc_auc_score(
        y_true,
        y_probability
    )
)


print("\n[10] weighted_sampler validation metrics")
print("-" * 78)

print(
    "Threshold:",
    f"{SELECTED_THRESHOLD:.10f}"
)

print("TP:", int(tp))
print("TN:", int(tn))
print("FP:", int(fp))
print("FN:", int(fn))

print(
    "Precision:",
    f"{VALIDATION_PRECISION:.10f}"
)

print(
    "Recall:",
    f"{VALIDATION_RECALL:.10f}"
)

print(
    "F1:",
    f"{VALIDATION_F1:.10f}"
)

print(
    "FPR:",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Accuracy:",
    f"{VALIDATION_ACCURACY:.10f}"
)

print(
    "PR-AUC:",
    f"{VALIDATION_PR_AUC:.10f}"
)

print(
    "ROC-AUC:",
    f"{VALIDATION_ROC_AUC:.10f}"
)


# ======================================================================
# 14 — SAVE WEIGHTED-SAMPLER VALIDATION ARTIFACTS
# ======================================================================

OUTPUT_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "weighted_sampler"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


PREDICTIONS_PATH = (
    OUTPUT_DIR
    / "development_validation_predictions.csv"
)


THRESHOLD_CURVE_PATH = (
    OUTPUT_DIR
    / "validation_threshold_search.csv"
)


RESULT_PATH = (
    OUTPUT_DIR
    / "validation_result.json"
)


VALIDATION_PREDICTIONS[
    "prediction_at_selected_threshold"
] = predictions


VALIDATION_PREDICTIONS.to_csv(
    PREDICTIONS_PATH,
    index=False
)


pd.DataFrame({
    "threshold":
        thresholds,

    "precision":
        threshold_precision,

    "recall":
        threshold_recall,

    "f1":
        threshold_f1
}).to_csv(
    THRESHOLD_CURVE_PATH,
    index=False
)


validation_result = {
    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "partition_used":
        "development_validation",

    "validation_windows":
        int(
            len(y_true)
        ),

    "validation_benign_windows":
        BENIGN_WINDOWS,

    "validation_attack_windows":
        ATTACK_WINDOWS,

    "held_out_DDoS_windows_used":
        0,

    "selected_threshold":
        SELECTED_THRESHOLD,

    "validation_precision":
        VALIDATION_PRECISION,

    "validation_recall":
        VALIDATION_RECALL,

    "validation_F1":
        VALIDATION_F1,

    "validation_FPR":
        VALIDATION_FPR,

    "validation_accuracy":
        VALIDATION_ACCURACY,

    "validation_PR_AUC":
        VALIDATION_PR_AUC,

    "validation_ROC_AUC":
        VALIDATION_ROC_AUC,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_test_used":
        False
}


with open(
    RESULT_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        validation_result,
        file,
        indent=4
    )


# ======================================================================
# 15 — UPDATE REGISTRY TO 3/3
# ======================================================================

print("\n[11] Updating imbalance registry")
print("-" * 78)


registry = pd.read_csv(
    REGISTRY_PATH
)


method_mask = (
    registry[
        "imbalance_method"
    ]
    ==
    IMBALANCE_METHOD
)


if int(
    method_mask.sum()
) != 1:
    raise RuntimeError(
        "Could not uniquely identify "
        "weighted_sampler."
    )


registry.loc[
    method_mask,
    "status"
] = "validation_complete"


registry.loc[
    method_mask,
    "selected_threshold"
] = SELECTED_THRESHOLD


registry.loc[
    method_mask,
    "validation_F1"
] = VALIDATION_F1


registry.loc[
    method_mask,
    "validation_FPR"
] = VALIDATION_FPR


registry.loc[
    method_mask,
    "validation_recall"
] = VALIDATION_RECALL


registry.loc[
    method_mask,
    "test_metrics_used_for_selection"
] = False


registry.loc[
    method_mask,
    "zero_day_metrics_used_for_selection"
] = False


completed_configs = int(
    (
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


if completed_configs != 3:
    raise RuntimeError(
        f"Expected 3 completed imbalance configs, "
        f"found {completed_configs}."
    )


# ======================================================================
# 16 — FINAL IMBALANCE SELECTION
#
# Frozen A30 rule:
# 1) highest validation F1
# 2) lower validation FPR
# 3) method priority:
#       none
#       class_weight
#       weighted_sampler
# ======================================================================

print("\n[12] Applying frozen A30 imbalance-selection rule")
print("-" * 78)


METHOD_PRIORITY = {
    "none": 0,
    "class_weight": 1,
    "weighted_sampler": 2
}


selection_table = (
    registry.loc[
        registry[
            "status"
        ]
        ==
        "validation_complete"
    ]
    .copy()
)


selection_table[
    "method_priority"
] = (
    selection_table[
        "imbalance_method"
    ]
    .map(
        METHOD_PRIORITY
    )
)


if selection_table[
    "method_priority"
].isna().any():
    raise RuntimeError(
        "Unknown imbalance method in registry."
    )


selection_table = (
    selection_table
    .sort_values(
        by=[
            "validation_F1",
            "validation_FPR",
            "method_priority"
        ],
        ascending=[
            False,
            True,
            True
        ],
        kind="mergesort"
    )
    .reset_index(
        drop=True
    )
)


if len(selection_table) != 3:
    raise RuntimeError(
        "Selection table does not contain 3 methods."
    )


if selection_table[
    [
        "validation_F1",
        "validation_FPR",
        "validation_recall",
        "selected_threshold"
    ]
].isna().any().any():
    raise RuntimeError(
        "Selection metrics contain NaN."
    )


SELECTED_IMBALANCE_METHOD = str(
    selection_table.loc[
        0,
        "imbalance_method"
    ]
)


SELECTED_IMBALANCE_THRESHOLD = float(
    selection_table.loc[
        0,
        "selected_threshold"
    ]
)


SELECTED_IMBALANCE_F1 = float(
    selection_table.loc[
        0,
        "validation_F1"
    ]
)


SELECTED_IMBALANCE_FPR = float(
    selection_table.loc[
        0,
        "validation_FPR"
    ]
)


SELECTED_IMBALANCE_RECALL = float(
    selection_table.loc[
        0,
        "validation_recall"
    ]
)


print(
    selection_table[
        [
            "imbalance_method",
            "selected_threshold",
            "validation_F1",
            "validation_FPR",
            "validation_recall"
        ]
    ].to_string(
        index=False
    )
)


print(
    "\nSelected imbalance method:",
    SELECTED_IMBALANCE_METHOD
)

print(
    "Selected validation F1:",
    f"{SELECTED_IMBALANCE_F1:.10f}"
)

print(
    "Selected validation FPR:",
    f"{SELECTED_IMBALANCE_FPR:.10f}"
)

print(
    "Selected validation recall:",
    f"{SELECTED_IMBALANCE_RECALL:.10f}"
)


# ======================================================================
# 17 — MARK SELECTED METHOD IN REGISTRY
# ======================================================================

registry[
    "selected_for_primary"
] = (
    registry[
        "imbalance_method"
    ]
    ==
    SELECTED_IMBALANCE_METHOD
)


registry.to_csv(
    REGISTRY_PATH,
    index=False
)


# ======================================================================
# 18 — SAVE FINAL SELECTION ARTIFACTS
# ======================================================================

SELECTION_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "selected_imbalance_method.json"
)


RANKING_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "imbalance_validation_ranking.csv"
)


selection_table.to_csv(
    RANKING_PATH,
    index=False
)


selection_record = {
    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        SEED,

    "temporal_window":
        8,

    "lambda_t":
        LAMBDA_T,

    "candidate_methods": [
        "none",
        "class_weight",
        "weighted_sampler"
    ],

    "completed_candidates":
        3,

    "selection_partition":
        "development_validation_only",

    "primary_selection_metric":
        "validation_F1",

    "primary_direction":
        "higher_is_better",

    "tiebreak_1":
        "lower_validation_FPR",

    "tiebreak_2":
        "method_priority",

    "method_priority": [
        "none",
        "class_weight",
        "weighted_sampler"
    ],

    "selected_imbalance_method":
        SELECTED_IMBALANCE_METHOD,

    "selected_threshold":
        SELECTED_IMBALANCE_THRESHOLD,

    "selected_validation_F1":
        SELECTED_IMBALANCE_F1,

    "selected_validation_FPR":
        SELECTED_IMBALANCE_FPR,

    "selected_validation_recall":
        SELECTED_IMBALANCE_RECALL,

    "known_test_used_for_selection":
        False,

    "benign_test_used_for_selection":
        False,

    "zero_day_DDoS_used_for_selection":
        False,

    "selection_finalized":
        True
}


with open(
    SELECTION_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        selection_record,
        file,
        indent=4
    )


# ======================================================================
# 19 — LOCAL BACKUP COPIES
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/imbalance/"
    "fold_01_DDoS"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


shutil.copy2(
    REGISTRY_PATH,
    LOCAL_DIR
    / REGISTRY_PATH.name
)


shutil.copy2(
    SELECTION_PATH,
    LOCAL_DIR
    / SELECTION_PATH.name
)


shutil.copy2(
    RANKING_PATH,
    LOCAL_DIR
    / RANKING_PATH.name
)


# ======================================================================
# 20 — FINAL VALIDATION
# ======================================================================

REGISTRY_VALID = bool(
    completed_configs
    ==
    3

    and

    int(
        registry[
            "selected_for_primary"
        ].sum()
    )
    ==
    1
)


SELECTION_VALID = bool(
    SELECTED_IMBALANCE_METHOD
    in
    [
        "none",
        "class_weight",
        "weighted_sampler"
    ]

    and

    np.isfinite(
        SELECTED_IMBALANCE_THRESHOLD
    )

    and

    np.isfinite(
        SELECTED_IMBALANCE_F1
    )

    and

    np.isfinite(
        SELECTED_IMBALANCE_FPR
    )
)


ARTIFACTS_VALID = bool(
    PREDICTIONS_PATH.exists()
    and
    THRESHOLD_CURVE_PATH.exists()
    and
    RESULT_PATH.exists()
    and
    REGISTRY_PATH.exists()
    and
    SELECTION_PATH.exists()
    and
    RANKING_PATH.exists()
)


A34_VALID = bool(
    COUNTS_VALID
    and
    SOURCE_CHECKS_VALID
    and
    PREPROCESSING_VALID
    and
    MODEL_FINITE
    and
    DDOS_WINDOWS == 0
    and
    REGISTRY_VALID
    and
    SELECTION_VALID
    and
    ARTIFACTS_VALID
)


STEP_34_IMBALANCE_SELECTION_VALID = (
    A34_VALID
)


FINAL_SELECTED_IMBALANCE_METHOD = (
    SELECTED_IMBALANCE_METHOD
)


FINAL_SELECTED_THRESHOLD = (
    SELECTED_IMBALANCE_THRESHOLD
)


print("\n[13] Step A34 validation")
print("-" * 78)

print(
    "weighted_sampler val windows   :",
    f"{len(y_true):,}",
    "/ 167,482"
)

print(
    "Benign validation windows      :",
    f"{BENIGN_WINDOWS:,}",
    "/ 1,715"
)

print(
    "Attack validation windows      :",
    f"{ATTACK_WINDOWS:,}",
    "/ 165,767"
)

print(
    "DDoS validation windows        :",
    DDOS_WINDOWS
)

print(
    "weighted_sampler threshold     :",
    f"{SELECTED_THRESHOLD:.10f}"
)

print(
    "weighted_sampler val F1        :",
    f"{VALIDATION_F1:.10f}"
)

print(
    "weighted_sampler val FPR       :",
    f"{VALIDATION_FPR:.10f}"
)

print(
    "Completed imbalance configs    :",
    completed_configs,
    "/ 3"
)

print(
    "FINAL imbalance method         :",
    SELECTED_IMBALANCE_METHOD
)

print(
    "Selected validation F1         :",
    f"{SELECTED_IMBALANCE_F1:.10f}"
)

print(
    "Selected validation FPR        :",
    f"{SELECTED_IMBALANCE_FPR:.10f}"
)

print(
    "Selected threshold             :",
    f"{SELECTED_IMBALANCE_THRESHOLD:.10f}"
)

print(
    "Known-test used for selection  :",
    False
)

print(
    "Benign-test used for selection :",
    False
)

print(
    "Zero-day used for selection    :",
    False
)

print(
    "Registry valid                 :",
    REGISTRY_VALID
)

print(
    "Selection artifact saved       :",
    SELECTION_PATH.exists()
)

print(
    "Ranking artifact saved         :",
    RANKING_PATH.exists()
)


print("\n" + "=" * 78)

if A34_VALID:

    print(
        "✅ STEP A34 PASSED — "
        "all three imbalance candidates are complete "
        "and the final imbalance method was selected "
        "using development validation only."
    )

else:

    print(
        "❌ STEP A34 FAILED — "
        "do not proceed to the next sensitivity block."
    )

print("=" * 78)

==============================================================================
STEP A34 — WEIGHTED_SAMPLER VALIDATION + FINAL IMBALANCE SELECTION
FOLD 1 | HELD-OUT FAMILY = DDoS
lambda_t = 0.25
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A14 architecture valid: True
A29 lambda selection valid: True
A30 imbalance protocol valid: True
A33 weighted_sampler fine-tuning valid: True
Device: cuda

[2] Validation configuration
------------------------------------------------------------------------------
lambda_t: 0.25
Imbalance method: weighted_sampler
Seed: 13
Expected validation windows: 167,482
Expected benign windows: 1,715
Expected attack windows: 165,767
Threshold rule: maximize development-validation F1

[3] Verifying frozen A30 protocol
------------------------------------------------------------------------------
Selection partition: development_validation_only
Frozen lambda_t: 0.25
Primary metric: development_validation_F1
Tie-break 1: lower_development_validation_FPR
Tie-break 2: method_priority
Test metrics allowed: False
Zero-day metrics allowed: False

[4] Loading frozen preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Preprocessing refitted: False

[5] Loading development-validation manifest
------------------------------------------------------------------------------
Validation ranges: 21
Validation windows: 167,482
DDoS validation windows: 0

[6] Loading weighted_sampler model
------------------------------------------------------------------------------
Loaded lambda_t: 0.25
Imbalance method: weighted_sampler
Fine-tuning epochs: 20
Sampling strategy: inverse_class_frequency
Model finite: True

[7] Running weighted_sampler validation inference
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | windows=     50 | target=1 | raw_nonfinite=0
02/21 Benign_Final                 | windows=  1,715 | target=0 | raw_nonfinite=20
03/21 BrowserHijacking             | windows=     61 | target=1 | raw_nonfinite=0
04/21 CommandInjection             | windows=     72 | target=1 | raw_nonfinite=0
05/21 DNS_Spoofing                 | windows=  1,405 | target=1 | raw_nonfinite=18
06/21 DictionaryBruteForce         | windows=    159 | target=1 | raw_nonfinite=2
07/21 DoS-HTTP_Flood               | windows= 18,104 | target=1 | raw_nonfinite=180
08/21 DoS-SYN_Flood                | windows= 74,945 | target=1 | raw_nonfinite=108
09/21 DoS-TCP_Flood                | windows= 30,713 | target=1 | raw_nonfinite=660
10/21 DoS-UDP_Flood                | windows= 17,512 | target=1 | raw_nonfinite=68
11/21 MITM-ArpSpoofing             | windows=  1,365 | target=1 | raw_nonfinite=10
12/21 Mirai-greeth_flood           | windows=     96 | target=1 | raw_nonfinite=2
13/21 Mirai-greip_flood            | windows=    195 | target=1 | raw_nonfinite=0
14/21 Mirai-udpplain               | windows=    139 | target=1 | raw_nonfinite=0
15/21 Recon-HostDiscovery          | windows=  6,187 | target=1 | raw_nonfinite=28
16/21 Recon-OSScan                 | windows=  2,975 | target=1 | raw_nonfinite=8
17/21 Recon-PingSweep              | windows=     36 | target=1 | raw_nonfinite=0
18/21 Recon-PortScan               | windows=  3,282 | target=1 | raw_nonfinite=22
19/21 SqlInjection                 | windows=    123 | target=1 | raw_nonfinite=0
20/21 VulnerabilityScan            | windows=  8,289 | target=1 | raw_nonfinite=390
21/21 XSS                          | windows=     59 | target=1 | raw_nonfinite=0

[8] Validation inference summary
------------------------------------------------------------------------------
Prediction rows: 167,482
Benign windows: 1,715
Attack windows: 165,767
DDoS windows: 0
Raw non-finite values imputed: 1,516
All source checks valid: True
Probability min: 0.0000000041
Probability max: 1.0000000000
Inference runtime: 6.27 seconds

[9] Selecting weighted_sampler validation threshold
------------------------------------------------------------------------------
Threshold candidates: 5,460
Maximum validation F1: 0.9969812549
Selected threshold: 0.0016511692
Max-F1 tie count: 1
Threshold tie-break: highest threshold

[10] weighted_sampler validation metrics
------------------------------------------------------------------------------
Threshold: 0.0016511692
TP: 165462
TN: 1018
FP: 697
FN: 305
Precision: 0.9958052227
Recall: 0.9981600680
F1: 0.9969812549
FPR: 0.4064139942
Accuracy: 0.9940172675
PR-AUC: 0.9999254935
ROC-AUC: 0.9949126422

[11] Updating imbalance registry
------------------------------------------------------------------------------

[12] Applying frozen A30 imbalance-selection rule
------------------------------------------------------------------------------
imbalance_method  selected_threshold  validation_F1  validation_FPR  validation_recall
            none            0.014751       0.997267        0.365598           0.998311
    class_weight            0.005371       0.997056        0.382507           0.998064
weighted_sampler            0.001651       0.996981        0.406414           0.998160

Selected imbalance method: none
Selected validation F1: 0.9972670927
Selected validation FPR: 0.3655976676
Selected validation recall: 0.9983108821

[13] Step A34 validation
------------------------------------------------------------------------------
weighted_sampler val windows   : 167,482 / 167,482
Benign validation windows      : 1,715 / 1,715
Attack validation windows      : 165,767 / 165,767
DDoS validation windows        : 0
weighted_sampler threshold     : 0.0016511692
weighted_sampler val F1        : 0.9969812549
weighted_sampler val FPR       : 0.4064139942
Completed imbalance configs    : 3 / 3
FINAL imbalance method         : none
Selected validation F1         : 0.9972670927
Selected validation FPR        : 0.3655976676
Selected threshold             : 0.0147513831
Known-test used for selection  : False
Benign-test used for selection : False
Zero-day used for selection    : False
Registry valid                 : True
Selection artifact saved       : True
Ranking artifact saved         : True

==============================================================================
✅ STEP A34 PASSED — all three imbalance candidates are complete and the final imbalance method was selected using development validation only.
==============================================================================

# Step A35 — Freeze window-size sensitivity protocol

In [ ]:
# ======================================================================
# STEP A35
# FREEZE TEMPORAL WINDOW-SIZE SENSITIVITY PROTOCOL
#
# Fold 1: DDoS held out
#
# Window candidates:
#   T = 4
#   T = 8
#   T = 16
#
# Frozen:
#   lambda_t = 0.25
#   imbalance method = none
#   seed = 13
#
# Development validation ONLY for selection.
#
# NO test access.
# NO zero-day access.
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("STEP A35 — FREEZE WINDOW-SIZE SENSITIVITY PROTOCOL")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_29_LAMBDA_SELECTION_VALID",
    "STEP_34_IMBALANCE_SELECTION_VALID"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_29_LAMBDA_SELECTION_VALID:
    raise RuntimeError(
        "A29 lambda selection did not pass."
    )


if not STEP_34_IMBALANCE_SELECTION_VALID:
    raise RuntimeError(
        "A34 imbalance selection did not pass."
    )


print(
    "A29 lambda selection valid:",
    STEP_29_LAMBDA_SELECTION_VALID
)

print(
    "A34 imbalance selection valid:",
    STEP_34_IMBALANCE_SELECTION_VALID
)


# ======================================================================
# 2 — LOAD FINALIZED DEVELOPMENT-ONLY SELECTIONS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


LAMBDA_SELECTION_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "lambda_t"
    / "fold_01_DDoS"
    / "selected_lambda_t.json"
)


IMBALANCE_SELECTION_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "imbalance"
    / "fold_01_DDoS"
    / "selected_imbalance_method.json"
)


for path in [
    LAMBDA_SELECTION_PATH,
    IMBALANCE_SELECTION_PATH
]:
    if not path.exists():
        raise RuntimeError(
            f"Required selection artifact missing:\n{path}"
        )


with open(
    LAMBDA_SELECTION_PATH,
    "r",
    encoding="utf-8"
) as file:
    lambda_selection = json.load(file)


with open(
    IMBALANCE_SELECTION_PATH,
    "r",
    encoding="utf-8"
) as file:
    imbalance_selection = json.load(file)


FINAL_LAMBDA_T = float(
    lambda_selection[
        "selected_lambda_t"
    ]
)


FINAL_IMBALANCE_METHOD = str(
    imbalance_selection[
        "selected_imbalance_method"
    ]
)


T8_THRESHOLD = float(
    imbalance_selection[
        "selected_threshold"
    ]
)


T8_VALIDATION_F1 = float(
    imbalance_selection[
        "selected_validation_F1"
    ]
)


T8_VALIDATION_FPR = float(
    imbalance_selection[
        "selected_validation_FPR"
    ]
)


T8_VALIDATION_RECALL = float(
    imbalance_selection[
        "selected_validation_recall"
    ]
)


if not np.isclose(
    FINAL_LAMBDA_T,
    0.25
):
    raise RuntimeError(
        f"Unexpected selected lambda_t: "
        f"{FINAL_LAMBDA_T}"
    )


if FINAL_IMBALANCE_METHOD != "none":
    raise RuntimeError(
        f"Unexpected selected imbalance method: "
        f"{FINAL_IMBALANCE_METHOD}"
    )


print("\n[2] Frozen configuration")
print("-" * 78)

print(
    "lambda_t:",
    FINAL_LAMBDA_T
)

print(
    "Imbalance method:",
    FINAL_IMBALANCE_METHOD
)

print(
    "Seed:",
    13
)

print(
    "Existing T=8 threshold:",
    f"{T8_THRESHOLD:.10f}"
)

print(
    "Existing T=8 validation F1:",
    f"{T8_VALIDATION_F1:.10f}"
)

print(
    "Existing T=8 validation FPR:",
    f"{T8_VALIDATION_FPR:.10f}"
)


# ======================================================================
# 3 — FREEZE WINDOW CANDIDATES
# ======================================================================

WINDOW_CANDIDATES = [
    4,
    8,
    16
]


print("\n[3] Freezing temporal-window candidates")
print("-" * 78)

print(
    "Candidates:",
    WINDOW_CANDIDATES
)


# ======================================================================
# 4 — CREATE EXPERIMENT REGISTRY
# ======================================================================

registry_rows = []


for temporal_window in WINDOW_CANDIDATES:

    if temporal_window == 8:

        status = "validation_complete"

        threshold = T8_THRESHOLD

        validation_f1 = (
            T8_VALIDATION_F1
        )

        validation_fpr = (
            T8_VALIDATION_FPR
        )

        validation_recall = (
            T8_VALIDATION_RECALL
        )

    else:

        status = "pending"

        threshold = np.nan

        validation_f1 = np.nan

        validation_fpr = np.nan

        validation_recall = np.nan


    registry_rows.append({

        "fold_id":
            1,

        "held_out_family":
            "DDoS",

        "seed":
            13,

        "temporal_window":
            temporal_window,

        "stride":
            temporal_window,

        "lambda_t":
            FINAL_LAMBDA_T,

        "imbalance_method":
            FINAL_IMBALANCE_METHOD,

        "SSL_epochs":
            30,

        "fine_tuning_epochs":
            20,

        "status":
            status,

        "selected_threshold":
            threshold,

        "validation_F1":
            validation_f1,

        "validation_FPR":
            validation_fpr,

        "validation_recall":
            validation_recall,

        "test_metrics_used_for_selection":
            False,

        "zero_day_metrics_used_for_selection":
            False
    })


REGISTRY = pd.DataFrame(
    registry_rows
)


display(
    REGISTRY
)


# ======================================================================
# 5 — FREEZE WINDOW-SENSITIVITY POLICY
# ======================================================================

SELECTION_POLICY = {

    "experiment":
        "temporal_window_sensitivity",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "seed":
        13,

    "window_candidates":
        [
            4,
            8,
            16
        ],

    "stride_rule":
        "stride_equals_window_size",

    "lambda_t":
        FINAL_LAMBDA_T,

    "imbalance_method":
        FINAL_IMBALANCE_METHOD,

    "selection_data":
        "development_validation_only",

    "per_candidate_threshold_selection":
        "maximize_F1_on_development_validation",

    "primary_selection_metric":
        "development_validation_F1",

    "primary_direction":
        "higher_is_better",

    "tiebreak_1":
        "lower_development_validation_FPR",

    "tiebreak_2":
        "smaller_temporal_window",

    "test_data_allowed_for_selection":
        False,

    "zero_day_data_allowed_for_selection":
        False,

    "window_construction_rules": {

        "chronological_order":
            True,

        "cross_source_windows_allowed":
            False,

        "cross_partition_windows_allowed":
            False,

        "cross_class_windows_allowed":
            False,

        "tail_policy":
            "drop_incomplete_tail_per_source_partition",

        "preprocessing":
            "same_frozen_Fold1_training_fitted_preprocessing",

        "timestamp_as_model_feature":
            False
    },

    "training_sampling_rule": {

        "scope":
            "development_train_only",

        "method":
            "deterministic_uniform_source_level_sampling",

        "maximum_windows_per_source":
            10000,

        "same_rule_for_all_window_sizes":
            True,

        "note":
            (
                "Window count may naturally differ with T. "
                "The same source-level sampling rule is used "
                "for every candidate."
            )
    },

    "controlled_variables": {

        "seed":
            13,

        "lambda_t":
            FINAL_LAMBDA_T,

        "imbalance_method":
            FINAL_IMBALANCE_METHOD,

        "architecture_family":
            "same_MOT_SSL_GRU",

        "feature_count":
            75,

        "SSL_epochs":
            30,

        "fine_tuning_epochs":
            20,

        "batch_size":
            256,

        "learning_rate":
            0.001,

        "temperature":
            0.20,

        "feature_mask_probability":
            0.10,

        "gaussian_jitter_std":
            0.01,

        "precision":
            "float32"
    },

    "reuse_T8_result":
        True,

    "T8_result_source":
        "finalized_lambda_and_imbalance_none_development_validation",

    "implementation_note":
        (
            "This is a one-factor-at-a-time sensitivity experiment. "
            "lambda_t and imbalance handling are frozen while only "
            "temporal window size is varied."
        )
}


# ======================================================================
# 6 — OUTPUT PATHS
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "sensitivity/window_size/"
    "fold_01_DDoS"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "sensitivity"
    / "window_size"
    / "fold_01_DDoS"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_REGISTRY = (
    LOCAL_DIR
    / "fold_01_window_size_experiment_registry.csv"
)


DRIVE_REGISTRY = (
    DRIVE_DIR
    / "fold_01_window_size_experiment_registry.csv"
)


LOCAL_POLICY = (
    LOCAL_DIR
    / "fold_01_window_size_selection_policy.json"
)


DRIVE_POLICY = (
    DRIVE_DIR
    / "fold_01_window_size_selection_policy.json"
)


# ======================================================================
# 7 — SAVE ARTIFACTS
# ======================================================================

REGISTRY.to_csv(
    LOCAL_REGISTRY,
    index=False
)


shutil.copy2(
    LOCAL_REGISTRY,
    DRIVE_REGISTRY
)


with open(
    LOCAL_POLICY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SELECTION_POLICY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_POLICY,
    DRIVE_POLICY
)


# ======================================================================
# 8 — FINAL VALIDATION
# ======================================================================

candidate_count = int(
    len(
        REGISTRY
    )
)


completed_count = int(
    (
        REGISTRY[
            "status"
        ]
        ==
        "validation_complete"
    ).sum()
)


T8_ROW = (
    REGISTRY.loc[
        REGISTRY[
            "temporal_window"
        ]
        ==
        8
    ]
    .iloc[0]
)


PROTOCOL_VALID = bool(

    candidate_count == 3

    and

    completed_count == 1

    and

    np.isclose(
        float(
            T8_ROW[
                "lambda_t"
            ]
        ),
        0.25
    )

    and

    str(
        T8_ROW[
            "imbalance_method"
        ]
    )
    ==
    "none"

    and

    np.isclose(
        float(
            T8_ROW[
                "validation_F1"
            ]
        ),
        0.9972670927,
        atol=1e-10
    )

    and

    not bool(
        REGISTRY[
            "test_metrics_used_for_selection"
        ].any()
    )

    and

    not bool(
        REGISTRY[
            "zero_day_metrics_used_for_selection"
        ].any()
    )

    and

    DRIVE_REGISTRY.exists()

    and

    DRIVE_POLICY.exists()
)


STEP_35_WINDOW_PROTOCOL_VALID = (
    PROTOCOL_VALID
)


print("\n[4] Step A35 validation")
print("-" * 78)

print(
    "Frozen lambda_t                :",
    FINAL_LAMBDA_T
)

print(
    "Frozen imbalance method        :",
    FINAL_IMBALANCE_METHOD
)

print(
    "Window candidates              :",
    WINDOW_CANDIDATES
)

print(
    "Stride rule                    :",
    "stride = T"
)

print(
    "Completed validation configs   :",
    completed_count,
    "/ 3"
)

print(
    "Existing T=8 validation F1     :",
    f"{T8_VALIDATION_F1:.10f}"
)

print(
    "Existing T=8 validation FPR    :",
    f"{T8_VALIDATION_FPR:.10f}"
)

print(
    "Cross-source windows allowed   :",
    False
)

print(
    "Cross-partition windows allowed:",
    False
)

print(
    "Selection uses test metrics    :",
    False
)

print(
    "Selection uses zero-day metrics:",
    False
)

print(
    "Registry backed up             :",
    DRIVE_REGISTRY.exists()
)

print(
    "Policy backed up               :",
    DRIVE_POLICY.exists()
)


print("\n" + "=" * 78)

if PROTOCOL_VALID:

    print(
        "✅ STEP A35 PASSED — "
        "temporal-window sensitivity protocol "
        "is frozen before constructing T=4 and T=16 data."
    )

else:

    print(
        "❌ STEP A35 FAILED — "
        "do not construct T=4 windows yet."
    )

print("=" * 78)

==============================================================================
STEP A35 — FREEZE WINDOW-SIZE SENSITIVITY PROTOCOL
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A29 lambda selection valid: True
A34 imbalance selection valid: True

[2] Frozen configuration
------------------------------------------------------------------------------
lambda_t: 0.25
Imbalance method: none
Seed: 13
Existing T=8 threshold: 0.0147513831
Existing T=8 validation F1: 0.9972670927
Existing T=8 validation FPR: 0.3655976676

[3] Freezing temporal-window candidates
------------------------------------------------------------------------------
Candidates: [4, 8, 16]

,fold_id,held_out_family,seed,temporal_window,stride,lambda_t,imbalance_method,SSL_epochs,fine_tuning_epochs,status,selected_threshold,validation_F1,validation_FPR,validation_recall,test_metrics_used_for_selection,zero_day_metrics_used_for_selection
0,1,DDoS,13,4,4,0.25,none,30,20,pending,NaN,NaN,NaN,NaN,False,False
1,1,DDoS,13,8,8,0.25,none,30,20,validation_complete,0.014751,0.997267,0.365598,0.998311,False,False
2,1,DDoS,13,16,16,0.25,none,30,20,pending,NaN,NaN,NaN,NaN,False,False

[4] Step A35 validation
------------------------------------------------------------------------------
Frozen lambda_t                : 0.25
Frozen imbalance method        : none
Window candidates              : [4, 8, 16]
Stride rule                    : stride = T
Completed validation configs   : 1 / 3
Existing T=8 validation F1     : 0.9972670927
Existing T=8 validation FPR    : 0.3655976676
Cross-source windows allowed   : False
Cross-partition windows allowed: False
Selection uses test metrics    : False
Selection uses zero-day metrics: False
Registry backed up             : True
Policy backed up               : True

==============================================================================
✅ STEP A35 PASSED — temporal-window sensitivity protocol is frozen before constructing T=4 and T=16 data.
==============================================================================

# Step A36 — Construct and verify T=4 windows

In [ ]:
# ======================================================================
# STEP A36
# CONSTRUCT + VERIFY T=4 DEVELOPMENT WINDOW MANIFEST
#
# Fold 1: DDoS held out
#
# Development partitions ONLY:
#   - development_train
#   - development_validation
#
# T = 4
# stride = 4
#
# IMPORTANT:
# - no window crosses a source
# - no window crosses a partition
# - incomplete tail rows are dropped per source/partition
# - NO model training
# - NO known-test Parquet access
# - NO benign-test Parquet access
# - NO zero-day DDoS Parquet access
# ======================================================================

from pathlib import Path
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("STEP A36 — CONSTRUCT + VERIFY T=4 DEVELOPMENT WINDOWS")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


if (
    "STEP_35_WINDOW_PROTOCOL_VALID"
    not in globals()
):

    raise RuntimeError(
        "STEP_35_WINDOW_PROTOCOL_VALID is missing."
    )


if not STEP_35_WINDOW_PROTOCOL_VALID:

    raise RuntimeError(
        "A35 did not pass."
    )


print(
    "A35 window protocol valid:",
    STEP_35_WINDOW_PROTOCOL_VALID
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

TEMPORAL_WINDOW = 4
STRIDE = 4

EXPECTED_TRAIN_ROWS = 6_253_058
EXPECTED_VALIDATION_ROWS = 1_339_934

EXPECTED_TRAIN_RANGES = 21
EXPECTED_VALIDATION_RANGES = 21


print("\n[2] T=4 construction configuration")
print("-" * 78)

print(
    "Temporal window:",
    TEMPORAL_WINDOW
)

print(
    "Stride:",
    STRIDE
)

print(
    "Window crossing source allowed:",
    False
)

print(
    "Window crossing partition allowed:",
    False
)

print(
    "Incomplete tail handling:",
    "drop per source/partition"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


REFERENCE_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "fold_01_DDoS_temporal_window_manifest.csv"
)


WINDOW_POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "window_size"
    / "fold_01_DDoS"
    / "fold_01_window_size_selection_policy.json"
)


if not REFERENCE_MANIFEST_PATH.exists():

    raise RuntimeError(
        "Reference T=8 temporal manifest not found."
    )


if not WINDOW_POLICY_PATH.exists():

    raise RuntimeError(
        "A35 window-size policy not found."
    )


# ======================================================================
# 4 — VERIFY FROZEN A35 POLICY
# ======================================================================

print("\n[3] Verifying frozen A35 protocol")
print("-" * 78)


with open(
    WINDOW_POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:

    window_policy = json.load(
        file
    )


if window_policy[
    "window_candidates"
] != [
    4,
    8,
    16
]:

    raise RuntimeError(
        "Window candidate policy mismatch."
    )


if not np.isclose(
    float(
        window_policy[
            "lambda_t"
        ]
    ),
    0.25
):

    raise RuntimeError(
        "Frozen lambda_t mismatch."
    )


if (
    window_policy[
        "imbalance_method"
    ]
    !=
    "none"
):

    raise RuntimeError(
        "Frozen imbalance-method mismatch."
    )


if (
    window_policy[
        "selection_data"
    ]
    !=
    "development_validation_only"
):

    raise RuntimeError(
        "Selection-data policy mismatch."
    )


print(
    "Frozen lambda_t:",
    window_policy[
        "lambda_t"
    ]
)

print(
    "Frozen imbalance method:",
    window_policy[
        "imbalance_method"
    ]
)

print(
    "Candidate windows:",
    window_policy[
        "window_candidates"
    ]
)

print(
    "Selection data:",
    window_policy[
        "selection_data"
    ]
)


# ======================================================================
# 5 — LOAD REFERENCE MANIFEST
#
# We use only the existing partition metadata.
# No Parquet feature data is read in A36.
# ======================================================================

print("\n[4] Loading development partition metadata")
print("-" * 78)


reference_manifest = pd.read_csv(
    REFERENCE_MANIFEST_PATH
)


required_columns = [
    "partition",
    "research_family",
    "source_attack_class",
    "binary_target",
    "partition_start_row",
    "partition_end_row_exclusive",
    "window_count",
    "unused_tail_rows",
    "parquet_path"
]


missing_columns = [
    column
    for column in required_columns
    if column not in reference_manifest.columns
]


if missing_columns:

    raise RuntimeError(
        "Reference manifest missing columns: "
        + ", ".join(missing_columns)
    )


DEV_MANIFEST = (

    reference_manifest.loc[
        reference_manifest[
            "partition"
        ].isin(
            [
                "development_train",
                "development_validation"
            ]
        )
    ]

    .copy()

    .reset_index(
        drop=True
    )
)


TRAIN_RANGE_COUNT = int(

    (
        DEV_MANIFEST[
            "partition"
        ]
        ==
        "development_train"
    ).sum()
)


VALIDATION_RANGE_COUNT = int(

    (
        DEV_MANIFEST[
            "partition"
        ]
        ==
        "development_validation"
    ).sum()
)


print(
    "Development-train ranges:",
    TRAIN_RANGE_COUNT
)

print(
    "Development-validation ranges:",
    VALIDATION_RANGE_COUNT
)

print(
    "Total development ranges:",
    len(
        DEV_MANIFEST
    )
)


if TRAIN_RANGE_COUNT != EXPECTED_TRAIN_RANGES:

    raise RuntimeError(
        "Unexpected development-train range count."
    )


if VALIDATION_RANGE_COUNT != EXPECTED_VALIDATION_RANGES:

    raise RuntimeError(
        "Unexpected development-validation range count."
    )


# ======================================================================
# 6 — VERIFY ORIGINAL T=8 MANIFEST CONSISTENCY
#
# Before deriving T=4, reconstruct every T=8 count from the frozen
# row boundaries.
# ======================================================================

print("\n[5] Verifying reference T=8 boundaries")
print("-" * 78)


DEV_MANIFEST[
    "partition_rows"
] = (

    DEV_MANIFEST[
        "partition_end_row_exclusive"
    ].astype(
        np.int64
    )

    -

    DEV_MANIFEST[
        "partition_start_row"
    ].astype(
        np.int64
    )
)


if (
    DEV_MANIFEST[
        "partition_rows"
    ]
    <=
    0
).any():

    raise RuntimeError(
        "Found non-positive partition row span."
    )


reference_T8_expected_windows = (

    DEV_MANIFEST[
        "partition_rows"
    ]

    //
    8
)


reference_T8_expected_tail = (

    DEV_MANIFEST[
        "partition_rows"
    ]

    %
    8
)


T8_BOUNDARIES_VALID = bool(

    np.array_equal(

        reference_T8_expected_windows
        .to_numpy(
            dtype=np.int64
        ),

        DEV_MANIFEST[
            "window_count"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )

    and

    np.array_equal(

        reference_T8_expected_tail
        .to_numpy(
            dtype=np.int64
        ),

        DEV_MANIFEST[
            "unused_tail_rows"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )
)


print(
    "Reference T=8 boundaries valid:",
    T8_BOUNDARIES_VALID
)


if not T8_BOUNDARIES_VALID:

    raise RuntimeError(
        "Reference T=8 manifest does not reconstruct "
        "from frozen row boundaries."
    )


# ======================================================================
# 7 — CONSTRUCT T=4 COUNTS
# ======================================================================

print("\n[6] Constructing T=4 source/partition windows")
print("-" * 78)


T4_MANIFEST = (
    DEV_MANIFEST.copy()
)


# Preserve the original T=8 values for auditability.

T4_MANIFEST[
    "reference_T8_window_count"
] = (

    T4_MANIFEST[
        "window_count"
    ].astype(
        np.int64
    )
)


T4_MANIFEST[
    "reference_T8_unused_tail_rows"
] = (

    T4_MANIFEST[
        "unused_tail_rows"
    ].astype(
        np.int64
    )
)


# Derive T=4 strictly within each existing source/partition range.

T4_MANIFEST[
    "temporal_window"
] = TEMPORAL_WINDOW


T4_MANIFEST[
    "stride"
] = STRIDE


T4_MANIFEST[
    "window_count"
] = (

    T4_MANIFEST[
        "partition_rows"
    ]

    //
    TEMPORAL_WINDOW
).astype(
    np.int64
)


T4_MANIFEST[
    "unused_tail_rows"
] = (

    T4_MANIFEST[
        "partition_rows"
    ]

    %
    TEMPORAL_WINDOW
).astype(
    np.int64
)


# Exact row-conservation test:
#
# rows =
#   (number_of_complete_windows × T)
#   + dropped_tail

T4_MANIFEST[
    "reconstructed_rows"
] = (

    T4_MANIFEST[
        "window_count"
    ]

    *
    TEMPORAL_WINDOW

    +

    T4_MANIFEST[
        "unused_tail_rows"
    ]
)


T4_MANIFEST[
    "row_conservation_valid"
] = (

    T4_MANIFEST[
        "reconstructed_rows"
    ]

    ==
    T4_MANIFEST[
        "partition_rows"
    ]
)


T4_MANIFEST[
    "tail_valid"
] = (

    (
        T4_MANIFEST[
            "unused_tail_rows"
        ]
        >=
        0
    )

    &

    (
        T4_MANIFEST[
            "unused_tail_rows"
        ]
        <
        TEMPORAL_WINDOW
    )
)


T4_MANIFEST[
    "source_boundary_preserved"
] = True


T4_MANIFEST[
    "partition_boundary_preserved"
] = True


# ======================================================================
# 8 — STRICT LEAKAGE CHECKS
# ======================================================================

print("\n[7] Running leakage/boundary checks")
print("-" * 78)


DDOS_DEV_WINDOWS = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


ONLY_DEVELOPMENT_PARTITIONS = bool(

    set(
        T4_MANIFEST[
            "partition"
        ].unique()
    )

    <=

    {
        "development_train",
        "development_validation"
    }
)


ALL_ROW_CONSERVATION_VALID = bool(

    T4_MANIFEST[
        "row_conservation_valid"
    ].all()
)


ALL_TAILS_VALID = bool(

    T4_MANIFEST[
        "tail_valid"
    ].all()
)


print(
    "Only development partitions:",
    ONLY_DEVELOPMENT_PARTITIONS
)

print(
    "Held-out DDoS T=4 windows:",
    DDOS_DEV_WINDOWS
)

print(
    "All source boundaries preserved:",
    True
)

print(
    "All partition boundaries preserved:",
    True
)

print(
    "All row-conservation checks valid:",
    ALL_ROW_CONSERVATION_VALID
)

print(
    "All tails < T:",
    ALL_TAILS_VALID
)


if not ONLY_DEVELOPMENT_PARTITIONS:

    raise RuntimeError(
        "Non-development partition entered T=4 manifest."
    )


if DDOS_DEV_WINDOWS != 0:

    raise RuntimeError(
        "Held-out DDoS entered T=4 development data."
    )


if not ALL_ROW_CONSERVATION_VALID:

    raise RuntimeError(
        "T=4 row-conservation failure."
    )


if not ALL_TAILS_VALID:

    raise RuntimeError(
        "Invalid T=4 tail count."
    )


# ======================================================================
# 9 — AGGREGATE COUNTS
# ======================================================================

print("\n[8] T=4 aggregate counts")
print("-" * 78)


TRAIN_ROWS = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "partition"
        ]
        ==
        "development_train",
        "partition_rows"
    ].sum()
)


VALIDATION_ROWS = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "partition"
        ]
        ==
        "development_validation",
        "partition_rows"
    ].sum()
)


TRAIN_WINDOWS_T4 = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "partition"
        ]
        ==
        "development_train",
        "window_count"
    ].sum()
)


VALIDATION_WINDOWS_T4 = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "partition"
        ]
        ==
        "development_validation",
        "window_count"
    ].sum()
)


TRAIN_TAIL_ROWS_T4 = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "partition"
        ]
        ==
        "development_train",
        "unused_tail_rows"
    ].sum()
)


VALIDATION_TAIL_ROWS_T4 = int(

    T4_MANIFEST.loc[
        T4_MANIFEST[
            "partition"
        ]
        ==
        "development_validation",
        "unused_tail_rows"
    ].sum()
)


print(
    "Development-train rows:",
    f"{TRAIN_ROWS:,}"
)

print(
    "Development-train T=4 windows:",
    f"{TRAIN_WINDOWS_T4:,}"
)

print(
    "Development-train dropped tail rows:",
    f"{TRAIN_TAIL_ROWS_T4:,}"
)

print()

print(
    "Development-validation rows:",
    f"{VALIDATION_ROWS:,}"
)

print(
    "Development-validation T=4 windows:",
    f"{VALIDATION_WINDOWS_T4:,}"
)

print(
    "Development-validation dropped tail rows:",
    f"{VALIDATION_TAIL_ROWS_T4:,}"
)


if TRAIN_ROWS != EXPECTED_TRAIN_ROWS:

    raise RuntimeError(
        "Development-train row total changed."
    )


if VALIDATION_ROWS != EXPECTED_VALIDATION_ROWS:

    raise RuntimeError(
        "Development-validation row total changed."
    )


# T=8 train had 781,622 windows across 21 source ranges.
# Therefore T=4 must be between:
#
#   2*781622
# and
#   2*781622 + 21
#
# depending on each source's old T=8 remainder.

if not (
    1_563_244
    <=
    TRAIN_WINDOWS_T4
    <=
    1_563_265
):

    raise RuntimeError(
        "T=4 train-window total is outside "
        "the mathematically valid range."
    )


# T=8 validation had 167,482 windows across 21 ranges.

if not (
    334_964
    <=
    VALIDATION_WINDOWS_T4
    <=
    334_985
):

    raise RuntimeError(
        "T=4 validation-window total is outside "
        "the mathematically valid range."
    )


# ======================================================================
# 10 — FAMILY SUMMARY
# ======================================================================

print("\n[9] T=4 family-level development summary")
print("-" * 78)


family_summary = (

    T4_MANIFEST

    .groupby(
        [
            "partition",
            "research_family"
        ],
        as_index=False
    )

    .agg(

        source_ranges=(
            "source_attack_class",
            "count"
        ),

        rows=(
            "partition_rows",
            "sum"
        ),

        windows=(
            "window_count",
            "sum"
        ),

        dropped_tail_rows=(
            "unused_tail_rows",
            "sum"
        )
    )
)


display(
    family_summary
)


# ======================================================================
# 11 — SAVE T=4 MANIFEST
# ======================================================================

LOCAL_OUTPUT_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/temporal_windows/"
    "fold_01_DDoS/T4"
)


DRIVE_OUTPUT_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "T4"
)


LOCAL_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_MANIFEST_PATH = (
    LOCAL_OUTPUT_DIR
    / "fold_01_DDoS_T4_development_manifest.csv"
)


DRIVE_MANIFEST_PATH = (
    DRIVE_OUTPUT_DIR
    / "fold_01_DDoS_T4_development_manifest.csv"
)


LOCAL_SUMMARY_PATH = (
    LOCAL_OUTPUT_DIR
    / "fold_01_DDoS_T4_development_summary.json"
)


DRIVE_SUMMARY_PATH = (
    DRIVE_OUTPUT_DIR
    / "fold_01_DDoS_T4_development_summary.json"
)


T4_MANIFEST.to_csv(
    LOCAL_MANIFEST_PATH,
    index=False
)


shutil.copy2(
    LOCAL_MANIFEST_PATH,
    DRIVE_MANIFEST_PATH
)


# ======================================================================
# 12 — SAVE AUDIT SUMMARY
# ======================================================================

SUMMARY = {

    "step":
        "A36",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "temporal_window":
        TEMPORAL_WINDOW,

    "stride":
        STRIDE,

    "lambda_t":
        0.25,

    "imbalance_method":
        "none",

    "development_train_ranges":
        TRAIN_RANGE_COUNT,

    "development_validation_ranges":
        VALIDATION_RANGE_COUNT,

    "development_train_rows":
        TRAIN_ROWS,

    "development_validation_rows":
        VALIDATION_ROWS,

    "development_train_windows":
        TRAIN_WINDOWS_T4,

    "development_validation_windows":
        VALIDATION_WINDOWS_T4,

    "development_train_tail_rows":
        TRAIN_TAIL_ROWS_T4,

    "development_validation_tail_rows":
        VALIDATION_TAIL_ROWS_T4,

    "held_out_DDoS_windows":
        DDOS_DEV_WINDOWS,

    "cross_source_windows_allowed":
        False,

    "cross_partition_windows_allowed":
        False,

    "reference_T8_boundaries_valid":
        T8_BOUNDARIES_VALID,

    "row_conservation_valid":
        ALL_ROW_CONSERVATION_VALID,

    "tail_validation_valid":
        ALL_TAILS_VALID,

    "known_test_parquet_accessed":
        False,

    "benign_test_parquet_accessed":
        False,

    "zero_day_DDoS_parquet_accessed":
        False,

    "model_training_performed":
        False
}


with open(
    LOCAL_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SUMMARY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_SUMMARY_PATH,
    DRIVE_SUMMARY_PATH
)


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

ARTIFACTS_VALID = bool(

    DRIVE_MANIFEST_PATH.exists()

    and

    DRIVE_SUMMARY_PATH.exists()
)


A36_VALID = bool(

    T8_BOUNDARIES_VALID

    and

    TRAIN_RANGE_COUNT
    ==
    21

    and

    VALIDATION_RANGE_COUNT
    ==
    21

    and

    TRAIN_ROWS
    ==
    EXPECTED_TRAIN_ROWS

    and

    VALIDATION_ROWS
    ==
    EXPECTED_VALIDATION_ROWS

    and

    ONLY_DEVELOPMENT_PARTITIONS

    and

    DDOS_DEV_WINDOWS
    ==
    0

    and

    ALL_ROW_CONSERVATION_VALID

    and

    ALL_TAILS_VALID

    and

    1_563_244
    <=
    TRAIN_WINDOWS_T4
    <=
    1_563_265

    and

    334_964
    <=
    VALIDATION_WINDOWS_T4
    <=
    334_985

    and

    ARTIFACTS_VALID
)


STEP_36_T4_WINDOW_MANIFEST_VALID = (
    A36_VALID
)


print("\n[10] Step A36 validation")
print("-" * 78)

print(
    "Temporal window                 :",
    TEMPORAL_WINDOW
)

print(
    "Stride                          :",
    STRIDE
)

print(
    "Development-train ranges        :",
    TRAIN_RANGE_COUNT,
    "/ 21"
)

print(
    "Development-validation ranges   :",
    VALIDATION_RANGE_COUNT,
    "/ 21"
)

print(
    "Development-train rows          :",
    f"{TRAIN_ROWS:,}",
    "/ 6,253,058"
)

print(
    "Development-validation rows     :",
    f"{VALIDATION_ROWS:,}",
    "/ 1,339,934"
)

print(
    "Development-train T=4 windows  :",
    f"{TRAIN_WINDOWS_T4:,}"
)

print(
    "Development-validation T=4 win :",
    f"{VALIDATION_WINDOWS_T4:,}"
)

print(
    "Held-out DDoS windows           :",
    DDOS_DEV_WINDOWS
)

print(
    "Reference T=8 boundaries valid  :",
    T8_BOUNDARIES_VALID
)

print(
    "Row conservation valid          :",
    ALL_ROW_CONSERVATION_VALID
)

print(
    "Tail counts valid               :",
    ALL_TAILS_VALID
)

print(
    "Cross-source windows created    :",
    False
)

print(
    "Cross-partition windows created :",
    False
)

print(
    "Known-test Parquet accessed     :",
    False
)

print(
    "Benign-test Parquet accessed    :",
    False
)

print(
    "Zero-day DDoS Parquet accessed  :",
    False
)

print(
    "Model training performed        :",
    False
)

print(
    "Manifest backed up              :",
    DRIVE_MANIFEST_PATH.exists()
)

print(
    "Summary backed up               :",
    DRIVE_SUMMARY_PATH.exists()
)


print("\n" + "=" * 78)

if A36_VALID:

    print(
        "✅ STEP A36 PASSED — "
        "T=4 development windows are leakage-free "
        "and boundary/count checks passed."
    )

else:

    print(
        "❌ STEP A36 FAILED — "
        "do not materialize T=4 model-ready data."
    )

print("=" * 78)

==============================================================================
STEP A36 — CONSTRUCT + VERIFY T=4 DEVELOPMENT WINDOWS
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A35 window protocol valid: True

[2] T=4 construction configuration
------------------------------------------------------------------------------
Temporal window: 4
Stride: 4
Window crossing source allowed: False
Window crossing partition allowed: False
Incomplete tail handling: drop per source/partition

[3] Verifying frozen A35 protocol
------------------------------------------------------------------------------
Frozen lambda_t: 0.25
Frozen imbalance method: none
Candidate windows: [4, 8, 16]
Selection data: development_validation_only

[4] Loading development partition metadata
------------------------------------------------------------------------------
Development-train ranges: 21
Development-validation ranges: 21
Total development ranges: 42

[5] Verifying reference T=8 boundaries
------------------------------------------------------------------------------
Reference T=8 boundaries valid: True

[6] Constructing T=4 source/partition windows
------------------------------------------------------------------------------

[7] Running leakage/boundary checks
------------------------------------------------------------------------------
Only development partitions: True
Held-out DDoS T=4 windows: 0
All source boundaries preserved: True
All partition boundaries preserved: True
All row-conservation checks valid: True
All tails < T: True

[8] T=4 aggregate counts
------------------------------------------------------------------------------
Development-train rows: 6,253,058
Development-train T=4 windows: 1,563,258
Development-train dropped tail rows: 26

Development-validation rows: 1,339,934
Development-validation T=4 windows: 334,977
Development-validation dropped tail rows: 26

[9] T=4 family-level development summary
------------------------------------------------------------------------------

,partition,research_family,source_ranges,rows,windows,dropped_tail_rows
0,development_train,Benign,1,64054,16013,2
1,development_train,BruteForce,1,5941,1485,1
2,development_train,DoS,4,5274317,1318577,9
3,development_train,Mirai,3,16106,4026,2
4,development_train,Recon,5,775447,193860,7
5,development_train,Spoofing,2,103453,25863,1
6,development_train,Web,5,13740,3434,4
7,development_validation,Benign,1,13725,3431,1
8,development_validation,BruteForce,1,1273,318,1
9,development_validation,DoS,4,1130210,282551,6
10,development_validation,Mirai,3,3451,862,3
11,development_validation,Recon,5,166166,41540,6
12,development_validation,Spoofing,2,22167,5541,3
13,development_validation,Web,5,2942,734,6

[10] Step A36 validation
------------------------------------------------------------------------------
Temporal window                 : 4
Stride                          : 4
Development-train ranges        : 21 / 21
Development-validation ranges   : 21 / 21
Development-train rows          : 6,253,058 / 6,253,058
Development-validation rows     : 1,339,934 / 1,339,934
Development-train T=4 windows  : 1,563,258
Development-validation T=4 win : 334,977
Held-out DDoS windows           : 0
Reference T=8 boundaries valid  : True
Row conservation valid          : True
Tail counts valid               : True
Cross-source windows created    : False
Cross-partition windows created : False
Known-test Parquet accessed     : False
Benign-test Parquet accessed    : False
Zero-day DDoS Parquet accessed  : False
Model training performed        : False
Manifest backed up              : True
Summary backed up               : True

==============================================================================
✅ STEP A36 PASSED — T=4 development windows are leakage-free and boundary/count checks passed.
==============================================================================

# Step A37 — Build T=4 deterministic training sample

In [ ]:
# ======================================================================
# STEP A37
# BUILD DETERMINISTIC T=4 TRAINING-SAMPLE PLAN
#
# Fold 1: DDoS held out
#
# T = 4
# stride = 4
#
# Sampling rule:
#   maximum 10,000 windows per source
#   deterministic uniform temporal coverage
#
# IMPORTANT:
# - development_train ONLY
# - no feature Parquet reads
# - no validation used for sampling
# - no test access
# - no zero-day access
# - no model training
# ======================================================================

from pathlib import Path
import hashlib
import json
import shutil

import numpy as np
import pandas as pd


print("=" * 78)
print("STEP A37 — T=4 DETERMINISTIC TRAINING-SAMPLE PLAN")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_35_WINDOW_PROTOCOL_VALID",
    "STEP_36_T4_WINDOW_MANIFEST_VALID"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_35_WINDOW_PROTOCOL_VALID:
    raise RuntimeError(
        "A35 did not pass."
    )


if not STEP_36_T4_WINDOW_MANIFEST_VALID:
    raise RuntimeError(
        "A36 did not pass."
    )


print(
    "A35 window protocol valid:",
    STEP_35_WINDOW_PROTOCOL_VALID
)

print(
    "A36 T=4 manifest valid:",
    STEP_36_T4_WINDOW_MANIFEST_VALID
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

TEMPORAL_WINDOW = 4
STRIDE = 4

MAX_WINDOWS_PER_SOURCE = 10_000

EXPECTED_SOURCE_RANGES = 21

REFERENCE_T8_SAMPLE_SIZE = 105_577


print("\n[2] Sampling configuration")
print("-" * 78)

print(
    "Temporal window:",
    TEMPORAL_WINDOW
)

print(
    "Stride:",
    STRIDE
)

print(
    "Maximum windows per source:",
    f"{MAX_WINDOWS_PER_SOURCE:,}"
)

print(
    "Sampling:",
    "deterministic uniform source-level"
)

print(
    "Sampling seed required:",
    False
)

print(
    "Sample reused across seeds:",
    True
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


T4_MANIFEST_PATH = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "T4"
    / "fold_01_DDoS_T4_development_manifest.csv"
)


WINDOW_POLICY_PATH = (
    BACKUP_ROOT
    / "sensitivity"
    / "window_size"
    / "fold_01_DDoS"
    / "fold_01_window_size_selection_policy.json"
)


if not T4_MANIFEST_PATH.exists():
    raise RuntimeError(
        "A36 T=4 manifest not found."
    )


if not WINDOW_POLICY_PATH.exists():
    raise RuntimeError(
        "A35 policy not found."
    )


# ======================================================================
# 4 — VERIFY FROZEN WINDOW POLICY
# ======================================================================

print("\n[3] Verifying frozen window policy")
print("-" * 78)


with open(
    WINDOW_POLICY_PATH,
    "r",
    encoding="utf-8"
) as file:

    window_policy = json.load(
        file
    )


sampling_rule = (
    window_policy[
        "training_sampling_rule"
    ]
)


if (
    int(
        sampling_rule[
            "maximum_windows_per_source"
        ]
    )
    !=
    MAX_WINDOWS_PER_SOURCE
):
    raise RuntimeError(
        "Sampling cap does not match A35."
    )


if (
    sampling_rule[
        "scope"
    ]
    !=
    "development_train_only"
):
    raise RuntimeError(
        "Sampling scope does not match A35."
    )


print(
    "Policy sampling scope:",
    sampling_rule[
        "scope"
    ]
)

print(
    "Policy sampling method:",
    sampling_rule[
        "method"
    ]
)

print(
    "Policy max/source:",
    sampling_rule[
        "maximum_windows_per_source"
    ]
)


# ======================================================================
# 5 — LOAD T=4 TRAIN MANIFEST ONLY
# ======================================================================

print("\n[4] Loading T=4 training metadata")
print("-" * 78)


manifest = pd.read_csv(
    T4_MANIFEST_PATH
)


TRAIN_MANIFEST = (
    manifest.loc[
        manifest[
            "partition"
        ]
        ==
        "development_train"
    ]
    .copy()
    .reset_index(
        drop=True
    )
)


print(
    "Training source ranges:",
    len(
        TRAIN_MANIFEST
    )
)

print(
    "Available T=4 training windows:",
    f"{int(TRAIN_MANIFEST['window_count'].sum()):,}"
)


if len(TRAIN_MANIFEST) != EXPECTED_SOURCE_RANGES:
    raise RuntimeError(
        "Expected exactly 21 training source ranges."
    )


if (
    TRAIN_MANIFEST[
        "temporal_window"
    ]
    !=
    TEMPORAL_WINDOW
).any():
    raise RuntimeError(
        "Unexpected temporal-window value."
    )


if (
    TRAIN_MANIFEST[
        "stride"
    ]
    !=
    STRIDE
).any():
    raise RuntimeError(
        "Unexpected stride value."
    )


DDOS_WINDOWS = int(
    TRAIN_MANIFEST.loc[
        TRAIN_MANIFEST[
            "research_family"
        ]
        ==
        "DDoS",
        "window_count"
    ].sum()
)


if DDOS_WINDOWS != 0:
    raise RuntimeError(
        "Held-out DDoS entered T=4 training metadata."
    )


# ======================================================================
# 6 — CREATE DETERMINISTIC SAMPLE PLAN
# ======================================================================

print("\n[5] Creating deterministic source-level sample")
print("-" * 78)


source_plan_rows = []

sample_rows = []


for source_id, row in TRAIN_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )

    family = str(
        row[
            "research_family"
        ]
    )

    target = int(
        row[
            "binary_target"
        ]
    )

    available_windows = int(
        row[
            "window_count"
        ]
    )

    partition_start = int(
        row[
            "partition_start_row"
        ]
    )

    partition_end = int(
        row[
            "partition_end_row_exclusive"
        ]
    )


    selected_count = min(
        available_windows,
        MAX_WINDOWS_PER_SOURCE
    )


    if selected_count <= 0:
        raise RuntimeError(
            f"No T=4 windows available for {source_class}."
        )


    # Uniform deterministic coverage from the first
    # available window to the last available window.
    if selected_count == available_windows:

        selected_indices = np.arange(
            available_windows,
            dtype=np.int64
        )

    else:

        selected_indices = np.linspace(
            0,
            available_windows - 1,
            num=selected_count,
            dtype=np.int64
        )


    if len(selected_indices) != selected_count:
        raise RuntimeError(
            f"Sampling-count mismatch for {source_class}."
        )


    if len(
        np.unique(
            selected_indices
        )
    ) != selected_count:

        raise RuntimeError(
            f"Duplicate sampled indices for {source_class}."
        )


    if selected_indices.min() < 0:
        raise RuntimeError(
            f"Negative sampled index for {source_class}."
        )


    if selected_indices.max() >= available_windows:
        raise RuntimeError(
            f"Out-of-range sampled index for {source_class}."
        )


    absolute_starts = (
        partition_start
        +
        selected_indices
        *
        TEMPORAL_WINDOW
    )


    absolute_ends = (
        absolute_starts
        +
        TEMPORAL_WINDOW
    )


    if (
        absolute_ends
        >
        partition_end
    ).any():
        raise RuntimeError(
            f"Sample crossed partition boundary "
            f"for {source_class}."
        )


    index_hash = hashlib.sha256(
        selected_indices.tobytes()
    ).hexdigest()


    source_plan_rows.append({

        "source_id":
            source_id,

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            target,

        "parquet_path":
            str(
                row[
                    "parquet_path"
                ]
            ),

        "partition":
            "development_train",

        "partition_start_row":
            partition_start,

        "partition_end_row_exclusive":
            partition_end,

        "temporal_window":
            TEMPORAL_WINDOW,

        "stride":
            STRIDE,

        "available_windows":
            available_windows,

        "sampled_windows":
            selected_count,

        "sampling_fraction":
            selected_count
            /
            available_windows,

        "first_sampled_window_index":
            int(
                selected_indices[0]
            ),

        "last_sampled_window_index":
            int(
                selected_indices[-1]
            ),

        "sample_index_sha256":
            index_hash
    })


    source_sample = pd.DataFrame({

        "source_id":
            source_id,

        "source_attack_class":
            source_class,

        "research_family":
            family,

        "binary_target":
            target,

        "local_window_index":
            selected_indices,

        "absolute_window_start_row":
            absolute_starts,

        "absolute_window_end_row_exclusive":
            absolute_ends
    })


    sample_rows.append(
        source_sample
    )


    print(
        f"{source_id + 1:02d}/21 "
        f"{source_class:<28} "
        f"| available={available_windows:>8,} "
        f"| sampled={selected_count:>6,} "
        f"| family={family}"
    )


# ======================================================================
# 7 — COMBINE SAMPLE
# ======================================================================

SOURCE_PLAN = pd.DataFrame(
    source_plan_rows
)


SAMPLE_INDEX = pd.concat(
    sample_rows,
    ignore_index=True
)


TOTAL_SAMPLED = int(
    len(
        SAMPLE_INDEX
    )
)


SAMPLED_BENIGN = int(
    (
        SAMPLE_INDEX[
            "binary_target"
        ]
        ==
        0
    ).sum()
)


SAMPLED_ATTACK = int(
    (
        SAMPLE_INDEX[
            "binary_target"
        ]
        ==
        1
    ).sum()
)


print("\n[6] T=4 sample totals")
print("-" * 78)

print(
    "Sampled source ranges:",
    len(
        SOURCE_PLAN
    )
)

print(
    "Total sampled windows:",
    f"{TOTAL_SAMPLED:,}"
)

print(
    "Sampled benign windows:",
    f"{SAMPLED_BENIGN:,}"
)

print(
    "Sampled attack windows:",
    f"{SAMPLED_ATTACK:,}"
)

print(
    "Attack : benign ratio:",
    f"{SAMPLED_ATTACK / SAMPLED_BENIGN:.4f}:1"
)

print(
    "Held-out DDoS sampled:",
    int(
        SAMPLE_INDEX.loc[
            SAMPLE_INDEX[
                "research_family"
            ]
            ==
            "DDoS"
        ].shape[0]
    )
)


# ======================================================================
# 8 — FAMILY SUMMARY
# ======================================================================

print("\n[7] T=4 sampled family summary")
print("-" * 78)


FAMILY_SUMMARY = (
    SOURCE_PLAN
    .groupby(
        "research_family",
        as_index=False
    )
    .agg(

        source_ranges=(
            "source_attack_class",
            "count"
        ),

        available_windows=(
            "available_windows",
            "sum"
        ),

        sampled_windows=(
            "sampled_windows",
            "sum"
        )
    )
)


FAMILY_SUMMARY[
    "sampling_fraction"
] = (
    FAMILY_SUMMARY[
        "sampled_windows"
    ]
    /
    FAMILY_SUMMARY[
        "available_windows"
    ]
)


display(
    FAMILY_SUMMARY
)


# ======================================================================
# 9 — STRICT SAMPLE VALIDATION
# ======================================================================

print("\n[8] Validating sample plan")
print("-" * 78)


EXPECTED_PER_SOURCE = np.minimum(
    SOURCE_PLAN[
        "available_windows"
    ].to_numpy(
        dtype=np.int64
    ),
    MAX_WINDOWS_PER_SOURCE
)


PER_SOURCE_CAP_VALID = bool(
    np.array_equal(

        SOURCE_PLAN[
            "sampled_windows"
        ].to_numpy(
            dtype=np.int64
        ),

        EXPECTED_PER_SOURCE
    )
)


PAIR_UNIQUE = bool(

    len(
        SAMPLE_INDEX[
            [
                "source_id",
                "local_window_index"
            ]
        ]
        .drop_duplicates()
    )

    ==
    TOTAL_SAMPLED
)


WINDOW_BOUNDARIES_VALID = bool(

    (
        SAMPLE_INDEX[
            "absolute_window_end_row_exclusive"
        ]

        -

        SAMPLE_INDEX[
            "absolute_window_start_row"
        ]

        ==
        TEMPORAL_WINDOW
    ).all()
)


BENIGN_SAMPLE_VALID = bool(
    SAMPLED_BENIGN
    ==
    10_000
)


SAMPLE_SIZE_VALID = bool(

    TOTAL_SAMPLED
    >=
    REFERENCE_T8_SAMPLE_SIZE

    and

    TOTAL_SAMPLED
    <=
    EXPECTED_SOURCE_RANGES
    *
    MAX_WINDOWS_PER_SOURCE
)


print(
    "Per-source cap rule valid:",
    PER_SOURCE_CAP_VALID
)

print(
    "Sample pairs unique:",
    PAIR_UNIQUE
)

print(
    "Window boundaries valid:",
    WINDOW_BOUNDARIES_VALID
)

print(
    "Benign sampled windows = 10,000:",
    BENIGN_SAMPLE_VALID
)

print(
    "Sample size >= T=8 sample:",
    TOTAL_SAMPLED
    >=
    REFERENCE_T8_SAMPLE_SIZE
)

print(
    "Sample size <= 210,000:",
    TOTAL_SAMPLED
    <=
    210_000
)


# ======================================================================
# 10 — SAVE SAMPLE PLAN
# ======================================================================

LOCAL_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/training_sampling/"
    "fold_01_DDoS/T4"
)


DRIVE_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "training_sampling"
    / "fold_01_DDoS"
    / "T4"
)


LOCAL_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


LOCAL_SOURCE_PLAN = (
    LOCAL_DIR
    / "T4_source_sampling_plan.csv"
)


DRIVE_SOURCE_PLAN = (
    DRIVE_DIR
    / "T4_source_sampling_plan.csv"
)


LOCAL_SAMPLE_INDEX = (
    LOCAL_DIR
    / "T4_sampled_window_indices.csv"
)


DRIVE_SAMPLE_INDEX = (
    DRIVE_DIR
    / "T4_sampled_window_indices.csv"
)


LOCAL_FAMILY_SUMMARY = (
    LOCAL_DIR
    / "T4_sampled_family_summary.csv"
)


DRIVE_FAMILY_SUMMARY = (
    DRIVE_DIR
    / "T4_sampled_family_summary.csv"
)


LOCAL_SUMMARY = (
    LOCAL_DIR
    / "T4_training_sample_summary.json"
)


DRIVE_SUMMARY = (
    DRIVE_DIR
    / "T4_training_sample_summary.json"
)


SOURCE_PLAN.to_csv(
    LOCAL_SOURCE_PLAN,
    index=False
)


SAMPLE_INDEX.to_csv(
    LOCAL_SAMPLE_INDEX,
    index=False
)


FAMILY_SUMMARY.to_csv(
    LOCAL_FAMILY_SUMMARY,
    index=False
)


# Hash the complete selected-window index file.

sample_file_hash = hashlib.sha256(
    LOCAL_SAMPLE_INDEX.read_bytes()
).hexdigest()


SUMMARY = {

    "step":
        "A37",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "temporal_window":
        4,

    "stride":
        4,

    "sampling_method":
        "deterministic_uniform_source_level",

    "maximum_windows_per_source":
        MAX_WINDOWS_PER_SOURCE,

    "source_ranges":
        int(
            len(
                SOURCE_PLAN
            )
        ),

    "available_training_windows":
        int(
            SOURCE_PLAN[
                "available_windows"
            ].sum()
        ),

    "sampled_training_windows":
        TOTAL_SAMPLED,

    "sampled_benign_windows":
        SAMPLED_BENIGN,

    "sampled_attack_windows":
        SAMPLED_ATTACK,

    "held_out_DDoS_sampled_windows":
        0,

    "sample_reused_across_seeds":
        True,

    "sample_index_sha256":
        sample_file_hash,

    "feature_parquet_data_accessed":
        False,

    "validation_used_for_sampling":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_DDoS_used":
        False,

    "model_training_performed":
        False
}


with open(
    LOCAL_SUMMARY,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SUMMARY,
        file,
        indent=4
    )


for local_path, drive_path in [

    (
        LOCAL_SOURCE_PLAN,
        DRIVE_SOURCE_PLAN
    ),

    (
        LOCAL_SAMPLE_INDEX,
        DRIVE_SAMPLE_INDEX
    ),

    (
        LOCAL_FAMILY_SUMMARY,
        DRIVE_FAMILY_SUMMARY
    ),

    (
        LOCAL_SUMMARY,
        DRIVE_SUMMARY
    )
]:

    shutil.copy2(
        local_path,
        drive_path
    )


# ======================================================================
# 11 — FINAL VALIDATION
# ======================================================================

ARTIFACTS_VALID = bool(

    DRIVE_SOURCE_PLAN.exists()

    and

    DRIVE_SAMPLE_INDEX.exists()

    and

    DRIVE_FAMILY_SUMMARY.exists()

    and

    DRIVE_SUMMARY.exists()
)


A37_VALID = bool(

    len(
        SOURCE_PLAN
    )
    ==
    21

    and

    int(
        SOURCE_PLAN[
            "available_windows"
        ].sum()
    )
    ==
    1_563_258

    and

    PER_SOURCE_CAP_VALID

    and

    PAIR_UNIQUE

    and

    WINDOW_BOUNDARIES_VALID

    and

    BENIGN_SAMPLE_VALID

    and

    SAMPLE_SIZE_VALID

    and

    SAMPLED_ATTACK
    +
    SAMPLED_BENIGN
    ==
    TOTAL_SAMPLED

    and

    int(
        SAMPLE_INDEX.loc[
            SAMPLE_INDEX[
                "research_family"
            ]
            ==
            "DDoS"
        ].shape[0]
    )
    ==
    0

    and

    ARTIFACTS_VALID
)


STEP_37_T4_TRAINING_SAMPLE_VALID = (
    A37_VALID
)


T4_TRAINING_SAMPLE_SIZE = (
    TOTAL_SAMPLED
)


print("\n[9] Step A37 validation")
print("-" * 78)

print(
    "Temporal window                 :",
    TEMPORAL_WINDOW
)

print(
    "Training source ranges          :",
    len(
        SOURCE_PLAN
    ),
    "/ 21"
)

print(
    "Available T=4 training windows  :",
    f"{int(SOURCE_PLAN['available_windows'].sum()):,}",
    "/ 1,563,258"
)

print(
    "Maximum windows/source          :",
    f"{MAX_WINDOWS_PER_SOURCE:,}"
)

print(
    "Total sampled windows           :",
    f"{TOTAL_SAMPLED:,}"
)

print(
    "Sampled benign windows          :",
    f"{SAMPLED_BENIGN:,}"
)

print(
    "Sampled attack windows          :",
    f"{SAMPLED_ATTACK:,}"
)

print(
    "Held-out DDoS sampled           :",
    0
)

print(
    "Per-source cap valid            :",
    PER_SOURCE_CAP_VALID
)

print(
    "Sample indices unique           :",
    PAIR_UNIQUE
)

print(
    "Window boundaries valid         :",
    WINDOW_BOUNDARIES_VALID
)

print(
    "Same sample reusable all seeds  :",
    True
)

print(
    "Feature Parquet data accessed   :",
    False
)

print(
    "Validation used for sampling    :",
    False
)

print(
    "Known-test used                 :",
    False
)

print(
    "Benign-test used                :",
    False
)

print(
    "Zero-day DDoS used              :",
    False
)

print(
    "Model training performed        :",
    False
)

print(
    "Sample-index SHA256             :",
    sample_file_hash
)

print(
    "Artifacts backed up             :",
    ARTIFACTS_VALID
)


print("\n" + "=" * 78)

if A37_VALID:

    print(
        "✅ STEP A37 PASSED — "
        "T=4 deterministic training sample "
        "was created and frozen successfully."
    )

else:

    print(
        "❌ STEP A37 FAILED — "
        "do not materialize T=4 feature windows yet."
    )

print("=" * 78)

==============================================================================
STEP A37 — T=4 DETERMINISTIC TRAINING-SAMPLE PLAN
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A35 window protocol valid: True
A36 T=4 manifest valid: True

[2] Sampling configuration
------------------------------------------------------------------------------
Temporal window: 4
Stride: 4
Maximum windows per source: 10,000
Sampling: deterministic uniform source-level
Sampling seed required: False
Sample reused across seeds: True

[3] Verifying frozen window policy
------------------------------------------------------------------------------
Policy sampling scope: development_train_only
Policy sampling method: deterministic_uniform_source_level_sampling
Policy max/source: 10000

[4] Loading T=4 training metadata
------------------------------------------------------------------------------
Training source ranges: 21
Available T=4 training windows: 1,563,258

[5] Creating deterministic source-level sample
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | available=     473 | sampled=   473 | family=Web
02/21 Benign_Final                 | available=  16,013 | sampled=10,000 | family=Benign
03/21 BrowserHijacking             | available=     575 | sampled=   575 | family=Web
04/21 CommandInjection             | available=     673 | sampled=   673 | family=Web
05/21 DNS_Spoofing                 | available=  13,114 | sampled=10,000 | family=Spoofing
06/21 DictionaryBruteForce         | available=   1,485 | sampled= 1,485 | family=BruteForce
07/21 DoS-HTTP_Flood               | available= 168,971 | sampled=10,000 | family=DoS
08/21 DoS-SYN_Flood                | available= 699,494 | sampled=10,000 | family=DoS
09/21 DoS-TCP_Flood                | available= 286,661 | sampled=10,000 | family=DoS
10/21 DoS-UDP_Flood                | available= 163,451 | sampled=10,000 | family=DoS
11/21 MITM-ArpSpoofing             | available=  12,749 | sampled=10,000 | family=Spoofing
12/21 Mirai-greeth_flood           | available=     902 | sampled=   902 | family=Mirai
13/21 Mirai-greip_flood            | available=   1,820 | sampled= 1,820 | family=Mirai
14/21 Mirai-udpplain               | available=   1,304 | sampled= 1,304 | family=Mirai
15/21 Recon-HostDiscovery          | available=  57,747 | sampled=10,000 | family=Recon
16/21 Recon-OSScan                 | available=  27,769 | sampled=10,000 | family=Recon
17/21 Recon-PingSweep              | available=     340 | sampled=   340 | family=Recon
18/21 Recon-PortScan               | available=  30,633 | sampled=10,000 | family=Recon
19/21 SqlInjection                 | available=   1,154 | sampled= 1,154 | family=Web
20/21 VulnerabilityScan            | available=  77,371 | sampled=10,000 | family=Recon
21/21 XSS                          | available=     559 | sampled=   559 | family=Web

[6] T=4 sample totals
------------------------------------------------------------------------------
Sampled source ranges: 21
Total sampled windows: 119,285
Sampled benign windows: 10,000
Sampled attack windows: 109,285
Attack : benign ratio: 10.9285:1
Held-out DDoS sampled: 0

[7] T=4 sampled family summary
------------------------------------------------------------------------------

,research_family,source_ranges,available_windows,sampled_windows,sampling_fraction
0,Benign,1,16013,10000,0.624493
1,BruteForce,1,1485,1485,1.000000
2,DoS,4,1318577,40000,0.030336
3,Mirai,3,4026,4026,1.000000
4,Recon,5,193860,40340,0.208088
5,Spoofing,2,25863,20000,0.773305
6,Web,5,3434,3434,1.000000

[8] Validating sample plan
------------------------------------------------------------------------------
Per-source cap rule valid: True
Sample pairs unique: True
Window boundaries valid: True
Benign sampled windows = 10,000: True
Sample size >= T=8 sample: True
Sample size <= 210,000: True

[9] Step A37 validation
------------------------------------------------------------------------------
Temporal window                 : 4
Training source ranges          : 21 / 21
Available T=4 training windows  : 1,563,258 / 1,563,258
Maximum windows/source          : 10,000
Total sampled windows           : 119,285
Sampled benign windows          : 10,000
Sampled attack windows          : 109,285
Held-out DDoS sampled           : 0
Per-source cap valid            : True
Sample indices unique           : True
Window boundaries valid         : True
Same sample reusable all seeds  : True
Feature Parquet data accessed   : False
Validation used for sampling    : False
Known-test used                 : False
Benign-test used                : False
Zero-day DDoS used              : False
Model training performed        : False
Sample-index SHA256             : 5d4cde334ef2b90c3b249892906d88f016285c4594519d61e67d1fb872a6fd1f
Artifacts backed up             : True

==============================================================================
✅ STEP A37 PASSED — T=4 deterministic training sample was created and frozen successfully.
==============================================================================

# Run only this recovery cell:

In [ ]:
# ======================================================================
# RECOVERY AFTER COLAB RUNTIME RESET
# Restore A36 + A37 validation flags from Google Drive artifacts
# ======================================================================

from pathlib import Path
import json
import hashlib
import pandas as pd

from google.colab import drive


print("=" * 78)
print("RECOVERY — RESTORING A36/A37 STATE FROM GOOGLE DRIVE")
print("=" * 78)


# ----------------------------------------------------------------------
# 1 — MOUNT DRIVE IF NEEDED
# ----------------------------------------------------------------------

DRIVE_ROOT = Path("/content/drive/MyDrive")

if not DRIVE_ROOT.exists():
    drive.mount("/content/drive")


BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)


# ----------------------------------------------------------------------
# 2 — A36 ARTIFACTS
# ----------------------------------------------------------------------

A36_MANIFEST = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "T4"
    / "fold_01_DDoS_T4_development_manifest.csv"
)

A36_SUMMARY = (
    BACKUP_ROOT
    / "processed_data"
    / "temporal_windows"
    / "fold_01_DDoS"
    / "T4"
    / "fold_01_DDoS_T4_development_summary.json"
)


if not A36_MANIFEST.exists() or not A36_SUMMARY.exists():
    raise RuntimeError(
        "A36 Drive artifacts are missing."
    )


with open(A36_SUMMARY, "r", encoding="utf-8") as f:
    a36 = json.load(f)


STEP_36_T4_WINDOW_MANIFEST_VALID = bool(

    a36.get("step") == "A36"

    and
    int(a36.get("temporal_window", -1)) == 4

    and
    int(a36.get("development_train_windows", -1)) == 1_563_258

    and
    int(a36.get("development_validation_windows", -1)) == 334_977

    and
    int(a36.get("held_out_DDoS_windows", -1)) == 0

    and
    bool(a36.get("reference_T8_boundaries_valid"))

    and
    bool(a36.get("row_conservation_valid"))

    and
    bool(a36.get("tail_validation_valid"))

    and
    not bool(a36.get("model_training_performed"))
)


# ----------------------------------------------------------------------
# 3 — A37 ARTIFACTS
# ----------------------------------------------------------------------

A37_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "training_sampling"
    / "fold_01_DDoS"
    / "T4"
)

A37_INDEX = (
    A37_DIR
    / "T4_sampled_window_indices.csv"
)

A37_SOURCE_PLAN = (
    A37_DIR
    / "T4_source_sampling_plan.csv"
)

A37_SUMMARY = (
    A37_DIR
    / "T4_training_sample_summary.json"
)


for path in [
    A37_INDEX,
    A37_SOURCE_PLAN,
    A37_SUMMARY
]:
    if not path.exists():
        raise RuntimeError(
            f"A37 artifact missing:\n{path}"
        )


with open(A37_SUMMARY, "r", encoding="utf-8") as f:
    a37 = json.load(f)


def sha256_file(path):
    h = hashlib.sha256()

    with open(path, "rb") as f:
        while True:
            chunk = f.read(8 * 1024 * 1024)

            if not chunk:
                break

            h.update(chunk)

    return h.hexdigest()


CURRENT_HASH = sha256_file(
    A37_INDEX
)

EXPECTED_HASH = str(
    a37.get(
        "sample_index_sha256",
        ""
    )
)


STEP_37_T4_TRAINING_SAMPLE_VALID = bool(

    a37.get("step") == "A37"

    and
    int(a37.get("temporal_window", -1)) == 4

    and
    int(a37.get("sampled_training_windows", -1)) == 119_285

    and
    int(a37.get("sampled_benign_windows", -1)) == 10_000

    and
    int(a37.get("sampled_attack_windows", -1)) == 109_285

    and
    int(a37.get("held_out_DDoS_sampled_windows", -1)) == 0

    and
    CURRENT_HASH == EXPECTED_HASH

    and
    not bool(a37.get("validation_used_for_sampling"))

    and
    not bool(a37.get("known_test_used"))

    and
    not bool(a37.get("zero_day_DDoS_used"))

    and
    not bool(a37.get("model_training_performed"))
)


# ----------------------------------------------------------------------
# 4 — FINAL CHECK
# ----------------------------------------------------------------------

print()
print("A36 restored:", STEP_36_T4_WINDOW_MANIFEST_VALID)
print("A37 restored:", STEP_37_T4_TRAINING_SAMPLE_VALID)
print("A37 sample hash valid:", CURRENT_HASH == EXPECTED_HASH)


if not STEP_36_T4_WINDOW_MANIFEST_VALID:
    raise RuntimeError(
        "A36 recovery validation failed."
    )


if not STEP_37_T4_TRAINING_SAMPLE_VALID:
    raise RuntimeError(
        "A37 recovery validation failed."
    )


print()
print("=" * 78)
print("✅ RECOVERY PASSED — A36 and A37 state restored from Drive.")
print("=" * 78)

==============================================================================
RECOVERY — RESTORING A36/A37 STATE FROM GOOGLE DRIVE
==============================================================================
Mounted at /content/drive

A36 restored: True
A37 restored: True
A37 sample hash valid: True

==============================================================================
✅ RECOVERY PASSED — A36 and A37 state restored from Drive.
==============================================================================

# Step A38 — Build T=4 model-ready shards

In [ ]:
# ======================================================================
# STEP A38
# MATERIALIZE T=4 MODEL-READY TRAINING SHARDS
#
# Fold 1: DDoS held out
#
# T = 4
# stride = 4
#
# Frozen sample:
#   119,285 windows
#   10,000 benign
#   109,285 attack
#
# IMPORTANT:
# - frozen Fold-1 preprocessing only
# - no preprocessing refit
# - development_train only
# - no validation used for training
# - no known-test data used
# - no zero-day DDoS data used
# - no model training
#
# CPU IS ENOUGH FOR THIS STEP.
# ======================================================================

from pathlib import Path
import hashlib
import json
import re
import shutil
import time

import numpy as np
import pandas as pd
import pyarrow.parquet as pq


print("=" * 78)
print("STEP A38 — MATERIALIZE T=4 MODEL-READY TRAINING SHARDS")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


required_variables = [
    "STEP_36_T4_WINDOW_MANIFEST_VALID",
    "STEP_37_T4_TRAINING_SAMPLE_VALID"
]


missing = [
    name
    for name in required_variables
    if name not in globals()
]


if missing:
    raise RuntimeError(
        "Missing variables: "
        + ", ".join(missing)
    )


if not STEP_36_T4_WINDOW_MANIFEST_VALID:
    raise RuntimeError(
        "A36 did not pass."
    )


if not STEP_37_T4_TRAINING_SAMPLE_VALID:
    raise RuntimeError(
        "A37 did not pass."
    )


print(
    "A36 T=4 manifest valid:",
    STEP_36_T4_WINDOW_MANIFEST_VALID
)

print(
    "A37 T=4 sample valid:",
    STEP_37_T4_TRAINING_SAMPLE_VALID
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

TEMPORAL_WINDOW = 4
FEATURE_COUNT = 75

EXPECTED_SOURCE_SHARDS = 21

EXPECTED_WINDOWS = 119_285
EXPECTED_BENIGN = 10_000
EXPECTED_ATTACK = 109_285

STREAM_BATCH_ROWS = 65_536


print("\n[2] Materialization configuration")
print("-" * 78)

print(
    "Temporal window:",
    TEMPORAL_WINDOW
)

print(
    "Feature count:",
    FEATURE_COUNT
)

print(
    "Expected source shards:",
    EXPECTED_SOURCE_SHARDS
)

print(
    "Expected windows:",
    f"{EXPECTED_WINDOWS:,}"
)

print(
    "Streaming batch rows:",
    f"{STREAM_BATCH_ROWS:,}"
)

print(
    "Output dtype:",
    "float32"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


CHRONOLOGICAL_ROOT = (
    BACKUP_ROOT
    / "chronological_parquet"
)


SAMPLING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "training_sampling"
    / "fold_01_DDoS"
    / "T4"
)


SOURCE_PLAN_PATH = (
    SAMPLING_DIR
    / "T4_source_sampling_plan.csv"
)


SAMPLE_INDEX_PATH = (
    SAMPLING_DIR
    / "T4_sampled_window_indices.csv"
)


SAMPLE_SUMMARY_PATH = (
    SAMPLING_DIR
    / "T4_training_sample_summary.json"
)


PREPROCESSING_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "preprocessing"
    / "fold_01_DDoS"
)


PARAMETERS_PATH = (
    PREPROCESSING_DIR
    / "preprocessing_parameters.csv"
)


FEATURES_PATH = (
    PREPROCESSING_DIR
    / "retained_features.json"
)


for path in [
    CHRONOLOGICAL_ROOT,
    SOURCE_PLAN_PATH,
    SAMPLE_INDEX_PATH,
    SAMPLE_SUMMARY_PATH,
    PARAMETERS_PATH,
    FEATURES_PATH
]:
    if not path.exists():
        raise RuntimeError(
            f"Required artifact missing:\n{path}"
        )


# ======================================================================
# 4 — SHA256 HELPER
# ======================================================================

def sha256_file(path):

    digest = hashlib.sha256()

    with open(path, "rb") as file:

        while True:

            chunk = file.read(
                8 * 1024 * 1024
            )

            if not chunk:
                break

            digest.update(chunk)

    return digest.hexdigest()


# ======================================================================
# 5 — VERIFY A37 SAMPLE INTEGRITY
# ======================================================================

print("\n[3] Verifying frozen A37 sample")
print("-" * 78)


with open(
    SAMPLE_SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as file:

    sample_summary = json.load(file)


source_plan = pd.read_csv(
    SOURCE_PLAN_PATH
)


sample_index = pd.read_csv(
    SAMPLE_INDEX_PATH
)


CURRENT_SAMPLE_HASH = sha256_file(
    SAMPLE_INDEX_PATH
)


EXPECTED_SAMPLE_HASH = str(
    sample_summary[
        "sample_index_sha256"
    ]
)


SAMPLE_HASH_VALID = bool(
    CURRENT_SAMPLE_HASH
    ==
    EXPECTED_SAMPLE_HASH
)


if not SAMPLE_HASH_VALID:
    raise RuntimeError(
        "A37 sample-index hash mismatch."
    )


if int(
    sample_summary[
        "sampled_training_windows"
    ]
) != EXPECTED_WINDOWS:
    raise RuntimeError(
        "A37 sampled-window total changed."
    )


if len(source_plan) != EXPECTED_SOURCE_SHARDS:
    raise RuntimeError(
        "A37 source-plan count changed."
    )


if len(sample_index) != EXPECTED_WINDOWS:
    raise RuntimeError(
        "A37 sample-index count changed."
    )


if int(
    (
        sample_index[
            "binary_target"
        ]
        ==
        0
    ).sum()
) != EXPECTED_BENIGN:
    raise RuntimeError(
        "A37 benign count changed."
    )


if int(
    (
        sample_index[
            "binary_target"
        ]
        ==
        1
    ).sum()
) != EXPECTED_ATTACK:
    raise RuntimeError(
        "A37 attack count changed."
    )


if (
    sample_index[
        "research_family"
    ]
    ==
    "DDoS"
).any():
    raise RuntimeError(
        "Held-out DDoS appeared in A37 sample."
    )


print(
    "Source ranges:",
    len(source_plan)
)

print(
    "Sampled windows:",
    f"{len(sample_index):,}"
)

print(
    "Benign:",
    f"{int((sample_index['binary_target'] == 0).sum()):,}"
)

print(
    "Attack:",
    f"{int((sample_index['binary_target'] == 1).sum()):,}"
)

print(
    "DDoS sampled:",
    0
)

print(
    "Sample-index SHA256 valid:",
    SAMPLE_HASH_VALID
)


# ======================================================================
# 6 — LOAD FROZEN FOLD-1 PREPROCESSING
# ======================================================================

print("\n[4] Loading frozen Fold-1 preprocessing")
print("-" * 78)


parameters = pd.read_csv(
    PARAMETERS_PATH
)


with open(
    FEATURES_PATH,
    "r",
    encoding="utf-8"
) as file:

    RETAINED_FEATURES = json.load(file)


if len(RETAINED_FEATURES) != FEATURE_COUNT:
    raise RuntimeError(
        "Expected exactly 75 retained features."
    )


parameter_lookup = (
    parameters
    .set_index("feature")
    .loc[RETAINED_FEATURES]
)


IMPUTE_VALUES = (
    parameter_lookup[
        "imputation_value"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_MEANS = (
    parameter_lookup[
        "scaler_mean"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


SCALER_STDS = (
    parameter_lookup[
        "scaler_std"
    ]
    .to_numpy(
        dtype=np.float64
    )
)


PREPROCESSING_VALID = bool(

    np.isfinite(
        IMPUTE_VALUES
    ).all()

    and

    np.isfinite(
        SCALER_MEANS
    ).all()

    and

    np.isfinite(
        SCALER_STDS
    ).all()

    and

    (
        SCALER_STDS > 0
    ).all()
)


if not PREPROCESSING_VALID:
    raise RuntimeError(
        "Frozen preprocessing is invalid."
    )


PARAMETERS_SHA256 = sha256_file(
    PARAMETERS_PATH
)


FEATURES_SHA256 = sha256_file(
    FEATURES_PATH
)


print(
    "Retained features:",
    len(RETAINED_FEATURES)
)

print(
    "Frozen preprocessing valid:",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted:",
    False
)

print(
    "Clipping applied:",
    False
)

print(
    "Parameters SHA256:",
    PARAMETERS_SHA256
)

print(
    "Features SHA256:",
    FEATURES_SHA256
)


# ======================================================================
# 7 — FROZEN PREPROCESSING FUNCTION
# ======================================================================

def frozen_preprocess(table):

    X = (
        table
        .to_pandas()
        .to_numpy(
            dtype=np.float64,
            copy=True
        )
    )


    bad_mask = (
        ~np.isfinite(X)
    )


    bad_count = int(
        bad_mask.sum()
    )


    if bad_count > 0:

        rows, cols = np.where(
            bad_mask
        )


        X[
            rows,
            cols
        ] = IMPUTE_VALUES[
            cols
        ]


    Z = (
        X
        -
        SCALER_MEANS
    ) / SCALER_STDS


    if not np.isfinite(
        Z
    ).all():
        raise RuntimeError(
            "Non-finite values after frozen standardization."
        )


    Z = Z.astype(
        np.float32
    )


    if not np.isfinite(
        Z
    ).all():
        raise RuntimeError(
            "Non-finite values after float32 conversion."
        )


    return (
        Z,
        bad_count
    )


# ======================================================================
# 8 — OUTPUT DIRECTORIES
# ======================================================================

LOCAL_OUTPUT_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4/train_shards"
)


DRIVE_OUTPUT_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
    / "T4"
    / "train_shards"
)


LOCAL_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


DRIVE_OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


# ======================================================================
# 9 — MATERIALIZE EACH SOURCE SHARD
# ======================================================================

print("\n[5] Materializing 21 T=4 source shards")
print("-" * 78)


materialization_start = time.time()


shard_records = []

TOTAL_MATERIALIZED = 0
TOTAL_BENIGN = 0
TOTAL_ATTACK = 0
TOTAL_RAW_NONFINITE = 0

GLOBAL_MAX_ABS_Z = 0.0


for _, plan_row in (
    source_plan
    .sort_values("source_id")
    .iterrows()
):

    SOURCE_ID = int(
        plan_row[
            "source_id"
        ]
    )


    SOURCE_CLASS = str(
        plan_row[
            "source_attack_class"
        ]
    )


    FAMILY = str(
        plan_row[
            "research_family"
        ]
    )


    TARGET = int(
        plan_row[
            "binary_target"
        ]
    )


    PARTITION_START = int(
        plan_row[
            "partition_start_row"
        ]
    )


    PARTITION_END = int(
        plan_row[
            "partition_end_row_exclusive"
        ]
    )


    AVAILABLE_WINDOWS = int(
        plan_row[
            "available_windows"
        ]
    )


    SAMPLED_WINDOWS = int(
        plan_row[
            "sampled_windows"
        ]
    )


    if FAMILY == "DDoS":
        raise RuntimeError(
            "Held-out DDoS reached A38."
        )


    partition_rows = (
        PARTITION_END
        -
        PARTITION_START
    )


    expected_available = (
        partition_rows
        //
        TEMPORAL_WINDOW
    )


    expected_tail = (
        partition_rows
        %
        TEMPORAL_WINDOW
    )


    if expected_available != AVAILABLE_WINDOWS:
        raise RuntimeError(
            f"Available-window mismatch for "
            f"{SOURCE_CLASS}."
        )


    source_sample = (
        sample_index.loc[
            sample_index[
                "source_id"
            ]
            ==
            SOURCE_ID
        ]
        .sort_values(
            "local_window_index"
        )
        .reset_index(
            drop=True
        )
    )


    if len(source_sample) != SAMPLED_WINDOWS:
        raise RuntimeError(
            f"Sample count mismatch for "
            f"{SOURCE_CLASS}."
        )


    SELECTED_INDICES = (
        source_sample[
            "local_window_index"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )


    if len(
        np.unique(
            SELECTED_INDICES
        )
    ) != SAMPLED_WINDOWS:
        raise RuntimeError(
            f"Duplicate selected indices for "
            f"{SOURCE_CLASS}."
        )


    if (
        SELECTED_INDICES.min() < 0
        or
        SELECTED_INDICES.max()
        >=
        AVAILABLE_WINDOWS
    ):
        raise RuntimeError(
            f"Out-of-range selected index for "
            f"{SOURCE_CLASS}."
        )


    expected_absolute_starts = (
        PARTITION_START
        +
        SELECTED_INDICES
        *
        TEMPORAL_WINDOW
    )


    actual_absolute_starts = (
        source_sample[
            "absolute_window_start_row"
        ]
        .to_numpy(
            dtype=np.int64
        )
    )


    if not np.array_equal(
        expected_absolute_starts,
        actual_absolute_starts
    ):
        raise RuntimeError(
            f"Absolute window-start mismatch for "
            f"{SOURCE_CLASS}."
        )


    parquet_name = Path(
        str(
            plan_row[
                "parquet_path"
            ]
        )
    ).name


    parquet_path = (
        CHRONOLOGICAL_ROOT
        /
        parquet_name
    )


    if not parquet_path.exists():
        raise RuntimeError(
            f"Missing chronological Parquet:\n"
            f"{parquet_path}"
        )


    # --------------------------------------------------------------
    # Allocate only selected model-ready windows.
    # --------------------------------------------------------------

    X_SHARD = np.empty(
        (
            SAMPLED_WINDOWS,
            TEMPORAL_WINDOW,
            FEATURE_COUNT
        ),
        dtype=np.float32
    )


    write_cursor = 0
    complete_window_cursor = 0


    pending = np.empty(
        (
            0,
            FEATURE_COUNT
        ),
        dtype=np.float32
    )


    source_raw_nonfinite = 0
    source_max_abs_z = 0.0

    absolute_row_cursor = 0


    parquet_file = pq.ParquetFile(
        parquet_path
    )


    # Stream the Parquet rather than loading a whole large source.
    for batch in parquet_file.iter_batches(

        batch_size=STREAM_BATCH_ROWS,

        columns=RETAINED_FEATURES
    ):

        batch_rows = int(
            batch.num_rows
        )


        batch_start = absolute_row_cursor

        batch_end = (
            batch_start
            +
            batch_rows
        )


        absolute_row_cursor = batch_end


        # Entire batch is before development_train.
        if batch_end <= PARTITION_START:
            continue


        # Development_train partition is complete.
        if batch_start >= PARTITION_END:
            break


        local_start = max(
            0,
            PARTITION_START
            -
            batch_start
        )


        local_end = min(
            batch_rows,
            PARTITION_END
            -
            batch_start
        )


        if local_end <= local_start:
            continue


        train_batch = batch.slice(
            local_start,
            local_end
            -
            local_start
        )


        Z, bad_count = frozen_preprocess(
            train_batch
        )


        source_raw_nonfinite += (
            bad_count
        )


        if len(Z) > 0:

            source_max_abs_z = max(

                source_max_abs_z,

                float(
                    np.max(
                        np.abs(
                            Z
                        )
                    )
                )
            )


        # Carry incomplete rows across Parquet streaming batches.
        if len(pending) > 0:

            Z = np.concatenate(
                [
                    pending,
                    Z
                ],
                axis=0
            )


        complete_windows_in_chunk = (
            len(Z)
            //
            TEMPORAL_WINDOW
        )


        complete_rows = (
            complete_windows_in_chunk
            *
            TEMPORAL_WINDOW
        )


        if complete_windows_in_chunk > 0:

            first_window = (
                complete_window_cursor
            )


            last_window_exclusive = (
                complete_window_cursor
                +
                complete_windows_in_chunk
            )


            left = np.searchsorted(
                SELECTED_INDICES,
                first_window,
                side="left"
            )


            right = np.searchsorted(
                SELECTED_INDICES,
                last_window_exclusive,
                side="left"
            )


            if right > left:

                relative_indices = (
                    SELECTED_INDICES[
                        left:right
                    ]
                    -
                    first_window
                )


                complete_view = (
                    Z[
                        :complete_rows
                    ]
                    .reshape(
                        complete_windows_in_chunk,
                        TEMPORAL_WINDOW,
                        FEATURE_COUNT
                    )
                )


                selected_chunk = (
                    complete_view[
                        relative_indices
                    ]
                )


                count = int(
                    len(
                        selected_chunk
                    )
                )


                X_SHARD[
                    write_cursor:
                    write_cursor + count
                ] = selected_chunk


                write_cursor += (
                    count
                )


            complete_window_cursor += (
                complete_windows_in_chunk
            )


        pending = (
            Z[
                complete_rows:
            ]
            .copy()
        )


    # --------------------------------------------------------------
    # Verify source reconstruction.
    # --------------------------------------------------------------

    if complete_window_cursor != AVAILABLE_WINDOWS:
        raise RuntimeError(
            f"Window reconstruction mismatch for "
            f"{SOURCE_CLASS}: "
            f"{complete_window_cursor} vs "
            f"{AVAILABLE_WINDOWS}"
        )


    if len(pending) != expected_tail:
        raise RuntimeError(
            f"Tail mismatch for {SOURCE_CLASS}: "
            f"{len(pending)} vs "
            f"{expected_tail}"
        )


    if write_cursor != SAMPLED_WINDOWS:
        raise RuntimeError(
            f"Materialized sample mismatch for "
            f"{SOURCE_CLASS}: "
            f"{write_cursor} vs "
            f"{SAMPLED_WINDOWS}"
        )


    if not np.isfinite(
        X_SHARD
    ).all():
        raise RuntimeError(
            f"Non-finite model-ready values for "
            f"{SOURCE_CLASS}."
        )


    Y_SHARD = np.full(
        SAMPLED_WINDOWS,
        TARGET,
        dtype=np.float32
    )


    # --------------------------------------------------------------
    # File names
    # --------------------------------------------------------------

    safe_source_name = re.sub(
        r"[^A-Za-z0-9._-]+",
        "_",
        SOURCE_CLASS
    )


    x_filename = (
        f"{SOURCE_ID:02d}_"
        f"{safe_source_name}_X.npy"
    )


    y_filename = (
        f"{SOURCE_ID:02d}_"
        f"{safe_source_name}_y.npy"
    )


    local_x_path = (
        LOCAL_OUTPUT_DIR
        /
        x_filename
    )


    local_y_path = (
        LOCAL_OUTPUT_DIR
        /
        y_filename
    )


    drive_x_path = (
        DRIVE_OUTPUT_DIR
        /
        x_filename
    )


    drive_y_path = (
        DRIVE_OUTPUT_DIR
        /
        y_filename
    )


    np.save(
        local_x_path,
        X_SHARD,
        allow_pickle=False
    )


    np.save(
        local_y_path,
        Y_SHARD,
        allow_pickle=False
    )


    # --------------------------------------------------------------
    # Verify saved local arrays.
    # --------------------------------------------------------------

    X_CHECK = np.load(
        local_x_path,
        mmap_mode="r",
        allow_pickle=False
    )


    Y_CHECK = np.load(
        local_y_path,
        mmap_mode="r",
        allow_pickle=False
    )


    EXPECTED_X_SHAPE = (
        SAMPLED_WINDOWS,
        TEMPORAL_WINDOW,
        FEATURE_COUNT
    )


    if X_CHECK.shape != EXPECTED_X_SHAPE:
        raise RuntimeError(
            f"Saved X shape mismatch for "
            f"{SOURCE_CLASS}."
        )


    if Y_CHECK.shape != (
        SAMPLED_WINDOWS,
    ):
        raise RuntimeError(
            f"Saved y shape mismatch for "
            f"{SOURCE_CLASS}."
        )


    if X_CHECK.dtype != np.float32:
        raise RuntimeError(
            f"Saved X dtype mismatch for "
            f"{SOURCE_CLASS}."
        )


    if Y_CHECK.dtype != np.float32:
        raise RuntimeError(
            f"Saved y dtype mismatch for "
            f"{SOURCE_CLASS}."
        )


    if not np.isfinite(
        X_CHECK
    ).all():
        raise RuntimeError(
            f"Saved X contains non-finite values "
            f"for {SOURCE_CLASS}."
        )


    if not np.all(
        Y_CHECK
        ==
        TARGET
    ):
        raise RuntimeError(
            f"Saved labels mismatch for "
            f"{SOURCE_CLASS}."
        )


    x_hash = sha256_file(
        local_x_path
    )


    y_hash = sha256_file(
        local_y_path
    )


    # --------------------------------------------------------------
    # Back up immediately to Google Drive.
    # --------------------------------------------------------------

    shutil.copy2(
        local_x_path,
        drive_x_path
    )


    shutil.copy2(
        local_y_path,
        drive_y_path
    )


    DRIVE_COPY_VALID = bool(

        drive_x_path.exists()

        and

        drive_y_path.exists()

        and

        drive_x_path.stat().st_size
        ==
        local_x_path.stat().st_size

        and

        drive_y_path.stat().st_size
        ==
        local_y_path.stat().st_size
    )


    if not DRIVE_COPY_VALID:
        raise RuntimeError(
            f"Drive copy failed for "
            f"{SOURCE_CLASS}."
        )


    shard_records.append({

        "source_id":
            SOURCE_ID,

        "source_attack_class":
            SOURCE_CLASS,

        "research_family":
            FAMILY,

        "binary_target":
            TARGET,

        "temporal_window":
            TEMPORAL_WINDOW,

        "feature_count":
            FEATURE_COUNT,

        "available_windows":
            AVAILABLE_WINDOWS,

        "sampled_windows":
            SAMPLED_WINDOWS,

        "X_shape":
            str(
                EXPECTED_X_SHAPE
            ),

        "y_shape":
            str(
                (
                    SAMPLED_WINDOWS,
                )
            ),

        "X_dtype":
            "float32",

        "y_dtype":
            "float32",

        "raw_nonfinite_values_imputed":
            source_raw_nonfinite,

        "max_abs_standardized_value":
            source_max_abs_z,

        "X_filename":
            x_filename,

        "y_filename":
            y_filename,

        "X_sha256":
            x_hash,

        "y_sha256":
            y_hash,

        "X_bytes":
            int(
                local_x_path.stat().st_size
            ),

        "y_bytes":
            int(
                local_y_path.stat().st_size
            ),

        "drive_copy_valid":
            DRIVE_COPY_VALID
    })


    TOTAL_MATERIALIZED += (
        SAMPLED_WINDOWS
    )


    if TARGET == 0:

        TOTAL_BENIGN += (
            SAMPLED_WINDOWS
        )

    else:

        TOTAL_ATTACK += (
            SAMPLED_WINDOWS
        )


    TOTAL_RAW_NONFINITE += (
        source_raw_nonfinite
    )


    GLOBAL_MAX_ABS_Z = max(
        GLOBAL_MAX_ABS_Z,
        source_max_abs_z
    )


    print(
        f"{SOURCE_ID + 1:02d}/21 "
        f"{SOURCE_CLASS:<28} "
        f"| X={str(EXPECTED_X_SHAPE):<18} "
        f"| target={TARGET} "
        f"| nonfinite_imputed="
        f"{source_raw_nonfinite:,} "
        f"| max|z|="
        f"{source_max_abs_z:.3e} "
        f"| Drive=OK"
    )


# ======================================================================
# 10 — BUILD SHARD MANIFEST
# ======================================================================

SHARD_MANIFEST = (
    pd.DataFrame(
        shard_records
    )
    .sort_values(
        "source_id"
    )
    .reset_index(
        drop=True
    )
)


print("\n[6] T=4 shard summary")
print("-" * 78)


print(
    "Logical source shards:",
    len(
        SHARD_MANIFEST
    )
)

print(
    "Materialized windows:",
    f"{TOTAL_MATERIALIZED:,}"
)

print(
    "Benign windows:",
    f"{TOTAL_BENIGN:,}"
)

print(
    "Attack windows:",
    f"{TOTAL_ATTACK:,}"
)

print(
    "Raw non-finite values imputed:",
    f"{TOTAL_RAW_NONFINITE:,}"
)

print(
    "Maximum absolute standardized value:",
    f"{GLOBAL_MAX_ABS_Z:.6e}"
)

print(
    "All Drive copies valid:",
    bool(
        SHARD_MANIFEST[
            "drive_copy_valid"
        ].all()
    )
)


# ======================================================================
# 11 — SAVE MODEL-READY MANIFEST + SUMMARY
# ======================================================================

LOCAL_MANIFEST_PATH = (
    LOCAL_OUTPUT_DIR
    /
    "T4_train_shard_manifest.csv"
)


DRIVE_MANIFEST_PATH = (
    DRIVE_OUTPUT_DIR
    /
    "T4_train_shard_manifest.csv"
)


LOCAL_SUMMARY_PATH = (
    LOCAL_OUTPUT_DIR
    /
    "T4_model_ready_summary.json"
)


DRIVE_SUMMARY_PATH = (
    DRIVE_OUTPUT_DIR
    /
    "T4_model_ready_summary.json"
)


SHARD_MANIFEST.to_csv(
    LOCAL_MANIFEST_PATH,
    index=False
)


shutil.copy2(
    LOCAL_MANIFEST_PATH,
    DRIVE_MANIFEST_PATH
)


TOTAL_X_BYTES = int(
    SHARD_MANIFEST[
        "X_bytes"
    ].sum()
)


TOTAL_Y_BYTES = int(
    SHARD_MANIFEST[
        "y_bytes"
    ].sum()
)


TOTAL_BYTES = (
    TOTAL_X_BYTES
    +
    TOTAL_Y_BYTES
)


SUMMARY = {

    "step":
        "A38",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "temporal_window":
        TEMPORAL_WINDOW,

    "stride":
        TEMPORAL_WINDOW,

    "feature_count":
        FEATURE_COUNT,

    "source_shards":
        int(
            len(
                SHARD_MANIFEST
            )
        ),

    "materialized_windows":
        TOTAL_MATERIALIZED,

    "benign_windows":
        TOTAL_BENIGN,

    "attack_windows":
        TOTAL_ATTACK,

    "held_out_DDoS_windows":
        0,

    "X_dtype":
        "float32",

    "y_dtype":
        "float32",

    "raw_nonfinite_values_imputed":
        TOTAL_RAW_NONFINITE,

    "global_max_abs_standardized_value":
        GLOBAL_MAX_ABS_Z,

    "sample_index_sha256":
        CURRENT_SAMPLE_HASH,

    "preprocessing_parameters_sha256":
        PARAMETERS_SHA256,

    "retained_features_sha256":
        FEATURES_SHA256,

    "preprocessing_refitted":
        False,

    "clipping_applied":
        False,

    "validation_rows_included_in_arrays":
        False,

    "known_test_rows_included":
        False,

    "benign_test_rows_included":
        False,

    "zero_day_DDoS_rows_included":
        False,

    "model_training_performed":
        False,

    "total_X_bytes":
        TOTAL_X_BYTES,

    "total_y_bytes":
        TOTAL_Y_BYTES,

    "total_model_ready_bytes":
        TOTAL_BYTES,

    "total_model_ready_MiB":
        TOTAL_BYTES
        /
        (
            1024 ** 2
        )
}


with open(
    LOCAL_SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        SUMMARY,
        file,
        indent=4
    )


shutil.copy2(
    LOCAL_SUMMARY_PATH,
    DRIVE_SUMMARY_PATH
)


# ======================================================================
# 12 — FINAL GLOBAL VALIDATION
# ======================================================================

SHARD_COUNT_VALID = bool(
    len(
        SHARD_MANIFEST
    )
    ==
    EXPECTED_SOURCE_SHARDS
)


WINDOW_COUNT_VALID = bool(
    TOTAL_MATERIALIZED
    ==
    EXPECTED_WINDOWS
)


LABEL_COUNTS_VALID = bool(

    TOTAL_BENIGN
    ==
    EXPECTED_BENIGN

    and

    TOTAL_ATTACK
    ==
    EXPECTED_ATTACK
)


ALL_SHARD_FILES_EXIST = bool(

    all(

        (
            DRIVE_OUTPUT_DIR
            /
            row[
                "X_filename"
            ]
        ).exists()

        and

        (
            DRIVE_OUTPUT_DIR
            /
            row[
                "y_filename"
            ]
        ).exists()

        for _, row
        in SHARD_MANIFEST.iterrows()
    )
)


ALL_DRIVE_COPIES_VALID = bool(
    SHARD_MANIFEST[
        "drive_copy_valid"
    ].all()
)


ALL_MAX_VALUES_FINITE = bool(

    np.isfinite(
        SHARD_MANIFEST[
            "max_abs_standardized_value"
        ]
        .to_numpy(
            dtype=float
        )
    ).all()
)


ARTIFACTS_VALID = bool(

    DRIVE_MANIFEST_PATH.exists()

    and

    DRIVE_SUMMARY_PATH.exists()

    and

    ALL_SHARD_FILES_EXIST
)


A38_VALID = bool(

    SAMPLE_HASH_VALID

    and

    PREPROCESSING_VALID

    and

    SHARD_COUNT_VALID

    and

    WINDOW_COUNT_VALID

    and

    LABEL_COUNTS_VALID

    and

    TOTAL_MATERIALIZED
    ==
    len(
        sample_index
    )

    and

    int(
        (
            sample_index[
                "research_family"
            ]
            ==
            "DDoS"
        ).sum()
    )
    ==
    0

    and

    ALL_DRIVE_COPIES_VALID

    and

    ALL_MAX_VALUES_FINITE

    and

    ARTIFACTS_VALID
)


STEP_38_T4_MODEL_READY_VALID = (
    A38_VALID
)


T4_MODEL_READY_SHARD_MANIFEST = (
    SHARD_MANIFEST
)


print("\n[7] Step A38 validation")
print("-" * 78)

print(
    "Temporal window                 :",
    TEMPORAL_WINDOW
)

print(
    "Feature count                   :",
    FEATURE_COUNT
)

print(
    "Logical source shards           :",
    len(
        SHARD_MANIFEST
    ),
    "/ 21"
)

print(
    "Materialized windows            :",
    f"{TOTAL_MATERIALIZED:,}",
    "/ 119,285"
)

print(
    "Benign windows                  :",
    f"{TOTAL_BENIGN:,}",
    "/ 10,000"
)

print(
    "Attack windows                  :",
    f"{TOTAL_ATTACK:,}",
    "/ 109,285"
)

print(
    "Held-out DDoS windows           :",
    0
)

print(
    "Sample-index hash valid         :",
    SAMPLE_HASH_VALID
)

print(
    "Frozen preprocessing valid      :",
    PREPROCESSING_VALID
)

print(
    "Preprocessing refitted          :",
    False
)

print(
    "Clipping applied                :",
    False
)

print(
    "All model-ready values finite   :",
    ALL_MAX_VALUES_FINITE
)

print(
    "Validation rows in arrays       :",
    False
)

print(
    "Known-test rows in arrays       :",
    False
)

print(
    "Zero-day DDoS rows in arrays    :",
    False
)

print(
    "Model training performed        :",
    False
)

print(
    "Total model-ready size          :",
    f"{TOTAL_BYTES / (1024 ** 2):.2f} MiB"
)

print(
    "All Drive copies valid          :",
    ALL_DRIVE_COPIES_VALID
)

print(
    "Shard manifest backed up        :",
    DRIVE_MANIFEST_PATH.exists()
)

print(
    "Summary backed up               :",
    DRIVE_SUMMARY_PATH.exists()
)

print(
    "Materialization runtime         :",
    f"{(time.time() - materialization_start) / 60:.2f} minutes"
)


print("\n" + "=" * 78)

if A38_VALID:

    print(
        "✅ STEP A38 PASSED — "
        "all 119,285 T=4 training windows were "
        "materialized into finite model-ready shards "
        "and backed up successfully."
    )

else:

    print(
        "❌ STEP A38 FAILED — "
        "do not create the T=4 PyTorch dataset yet."
    )

print("=" * 78)

==============================================================================
STEP A38 — MATERIALIZE T=4 MODEL-READY TRAINING SHARDS
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A36 T=4 manifest valid: True
A37 T=4 sample valid: True

[2] Materialization configuration
------------------------------------------------------------------------------
Temporal window: 4
Feature count: 75
Expected source shards: 21
Expected windows: 119,285
Streaming batch rows: 65,536
Output dtype: float32

[3] Verifying frozen A37 sample
------------------------------------------------------------------------------
Source ranges: 21
Sampled windows: 119,285
Benign: 10,000
Attack: 109,285
DDoS sampled: 0
Sample-index SHA256 valid: True

[4] Loading frozen Fold-1 preprocessing
------------------------------------------------------------------------------
Retained features: 75
Frozen preprocessing valid: True
Preprocessing refitted: False
Clipping applied: False
Parameters SHA256: f0b19faf3575342cd4acd5252bda08e2baee321f03ff4296931e1c54027d176a
Features SHA256: e5db01766ac945531ab1a5b59f7b3ab777467f59be03c74dbebf333f38ddcb25

[5] Materializing 21 T=4 source shards
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | X=(473, 4, 75)       | target=1 | nonfinite_imputed=0 | max|z|=9.333e+01 | Drive=OK
02/21 Benign_Final                 | X=(10000, 4, 75)     | target=0 | nonfinite_imputed=62 | max|z|=2.473e+02 | Drive=OK
03/21 BrowserHijacking             | X=(575, 4, 75)       | target=1 | nonfinite_imputed=0 | max|z|=1.483e+02 | Drive=OK
04/21 CommandInjection             | X=(673, 4, 75)       | target=1 | nonfinite_imputed=0 | max|z|=1.483e+02 | Drive=OK
05/21 DNS_Spoofing                 | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=104 | max|z|=1.009e+03 | Drive=OK
06/21 DictionaryBruteForce         | X=(1485, 4, 75)      | target=1 | nonfinite_imputed=6 | max|z|=1.483e+02 | Drive=OK
07/21 DoS-HTTP_Flood               | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=56,072 | max|z|=8.377e+02 | Drive=OK
08/21 DoS-SYN_Flood                | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=326 | max|z|=7.367e+02 | Drive=OK
09/21 DoS-TCP_Flood                | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=210 | max|z|=1.471e+03 | Drive=OK
10/21 DoS-UDP_Flood                | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=268 | max|z|=3.256e+02 | Drive=OK
11/21 MITM-ArpSpoofing             | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=42 | max|z|=1.675e+03 | Drive=OK
12/21 Mirai-greeth_flood           | X=(902, 4, 75)       | target=1 | nonfinite_imputed=0 | max|z|=4.427e+02 | Drive=OK
13/21 Mirai-greip_flood            | X=(1820, 4, 75)      | target=1 | nonfinite_imputed=14 | max|z|=1.003e+03 | Drive=OK
14/21 Mirai-udpplain               | X=(1304, 4, 75)      | target=1 | nonfinite_imputed=4 | max|z|=8.243e+02 | Drive=OK
15/21 Recon-HostDiscovery          | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=8 | max|z|=1.483e+02 | Drive=OK
16/21 Recon-OSScan                 | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=82 | max|z|=8.261e+02 | Drive=OK
17/21 Recon-PingSweep              | X=(340, 4, 75)       | target=1 | nonfinite_imputed=0 | max|z|=3.545e+01 | Drive=OK
18/21 Recon-PortScan               | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=18 | max|z|=1.483e+02 | Drive=OK
19/21 SqlInjection                 | X=(1154, 4, 75)      | target=1 | nonfinite_imputed=6 | max|z|=1.483e+02 | Drive=OK
20/21 VulnerabilityScan            | X=(10000, 4, 75)     | target=1 | nonfinite_imputed=1,612 | max|z|=6.729e+02 | Drive=OK
21/21 XSS                          | X=(559, 4, 75)       | target=1 | nonfinite_imputed=0 | max|z|=1.483e+02 | Drive=OK

[6] T=4 shard summary
------------------------------------------------------------------------------
Logical source shards: 21
Materialized windows: 119,285
Benign windows: 10,000
Attack windows: 109,285
Raw non-finite values imputed: 58,834
Maximum absolute standardized value: 1.674877e+03
All Drive copies valid: True

[7] Step A38 validation
------------------------------------------------------------------------------
Temporal window                 : 4
Feature count                   : 75
Logical source shards           : 21 / 21
Materialized windows            : 119,285 / 119,285
Benign windows                  : 10,000 / 10,000
Attack windows                  : 109,285 / 109,285
Held-out DDoS windows           : 0
Sample-index hash valid         : True
Frozen preprocessing valid      : True
Preprocessing refitted          : False
Clipping applied                : False
All model-ready values finite   : True
Validation rows in arrays       : False
Known-test rows in arrays       : False
Zero-day DDoS rows in arrays    : False
Model training performed        : False
Total model-ready size          : 136.97 MiB
All Drive copies valid          : True
Shard manifest backed up        : True
Summary backed up               : True
Materialization runtime         : 1.00 minutes

==============================================================================
✅ STEP A38 PASSED — all 119,285 T=4 training windows were materialized into finite model-ready shards and backed up successfully.
==============================================================================

# A39

In [ ]:
# ======================================================================
# STEP A39
# BUILD + VERIFY T=4 PYTORCH DATASET AND DATALOADER
#
# Fold 1: DDoS held out
#
# T = 4
# Features = 75
# Windows = 119,285
#
# IMPORTANT:
# - no model training
# - no validation access
# - no test access
# - no zero-day access
# - CPU is enough
# ======================================================================

from pathlib import Path
from bisect import bisect_right
import json
import shutil

import numpy as np
import pandas as pd

import torch
from torch.utils.data import Dataset, DataLoader


print("=" * 78)
print("STEP A39 — BUILD + VERIFY T=4 PYTORCH DATASET/DATALOADER")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A38
# ======================================================================

print("\n[1] Verifying prerequisite")
print("-" * 78)


if (
    "STEP_38_T4_MODEL_READY_VALID"
    not in globals()
):
    raise RuntimeError(
        "STEP_38_T4_MODEL_READY_VALID is missing."
    )


if not STEP_38_T4_MODEL_READY_VALID:
    raise RuntimeError(
        "A38 did not pass."
    )


print(
    "A38 model-ready data valid:",
    STEP_38_T4_MODEL_READY_VALID
)


# ======================================================================
# 2 — CONFIGURATION
# ======================================================================

TEMPORAL_WINDOW = 4
FEATURE_COUNT = 75
EXPECTED_WINDOWS = 119_285

EXPECTED_BENIGN = 10_000
EXPECTED_ATTACK = 109_285

BATCH_SIZE = 256
SEED = 13


print("\n[2] Dataset configuration")
print("-" * 78)

print(
    "Temporal window:",
    TEMPORAL_WINDOW
)

print(
    "Feature count:",
    FEATURE_COUNT
)

print(
    "Expected windows:",
    f"{EXPECTED_WINDOWS:,}"
)

print(
    "Batch size:",
    BATCH_SIZE
)

print(
    "Current runtime:",
    "GPU" if torch.cuda.is_available() else "CPU"
)


# ======================================================================
# 3 — PATHS
# ======================================================================

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)


DRIVE_SHARD_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
    / "T4"
    / "train_shards"
)


LOCAL_SHARD_DIR = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4/train_shards"
)


MANIFEST_PATH = (
    DRIVE_SHARD_DIR
    / "T4_train_shard_manifest.csv"
)


SUMMARY_PATH = (
    DRIVE_SHARD_DIR
    / "T4_model_ready_summary.json"
)


if not MANIFEST_PATH.exists():
    raise RuntimeError(
        "A38 shard manifest missing."
    )


if not SUMMARY_PATH.exists():
    raise RuntimeError(
        "A38 summary missing."
    )


# ======================================================================
# 4 — LOAD A38 MANIFEST
# ======================================================================

print("\n[3] Loading A38 shard manifest")
print("-" * 78)


SHARD_MANIFEST = (
    pd.read_csv(
        MANIFEST_PATH
    )
    .sort_values(
        "source_id"
    )
    .reset_index(
        drop=True
    )
)


with open(
    SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as file:
    A38_SUMMARY = json.load(file)


if len(SHARD_MANIFEST) != 21:
    raise RuntimeError(
        "Expected 21 source shards."
    )


if int(
    SHARD_MANIFEST[
        "sampled_windows"
    ].sum()
) != EXPECTED_WINDOWS:
    raise RuntimeError(
        "Shard window total mismatch."
    )


print(
    "Logical source shards:",
    len(SHARD_MANIFEST)
)

print(
    "Manifest windows:",
    f"{int(SHARD_MANIFEST['sampled_windows'].sum()):,}"
)


# ======================================================================
# 5 — RESTORE LOCAL SHARDS IF NECESSARY
# ======================================================================

print("\n[4] Checking local T=4 shards")
print("-" * 78)


LOCAL_SHARD_DIR.mkdir(
    parents=True,
    exist_ok=True
)


restored_files = 0


for _, row in SHARD_MANIFEST.iterrows():

    for filename_column in [
        "X_filename",
        "y_filename"
    ]:

        filename = str(
            row[
                filename_column
            ]
        )


        drive_path = (
            DRIVE_SHARD_DIR
            /
            filename
        )


        local_path = (
            LOCAL_SHARD_DIR
            /
            filename
        )


        if not drive_path.exists():
            raise RuntimeError(
                f"Drive shard missing:\n{drive_path}"
            )


        needs_restore = bool(
            not local_path.exists()
            or
            local_path.stat().st_size
            !=
            drive_path.stat().st_size
        )


        if needs_restore:

            shutil.copy2(
                drive_path,
                local_path
            )

            restored_files += 1


print(
    "Files restored from Drive:",
    restored_files
)

print(
    "Local shard directory ready:",
    True
)


# ======================================================================
# 6 — VERIFY ALL SHARDS
# ======================================================================

print("\n[5] Verifying all T=4 shard arrays")
print("-" * 78)


TOTAL_WINDOWS = 0
TOTAL_BENIGN = 0
TOTAL_ATTACK = 0

ALL_FINITE = True
ALL_SHAPES_VALID = True
ALL_DTYPES_VALID = True
ALL_LABELS_VALID = True


for row_number, row in SHARD_MANIFEST.iterrows():

    source_class = str(
        row[
            "source_attack_class"
        ]
    )


    target = int(
        row[
            "binary_target"
        ]
    )


    expected_count = int(
        row[
            "sampled_windows"
        ]
    )


    X_path = (
        LOCAL_SHARD_DIR
        /
        str(
            row[
                "X_filename"
            ]
        )
    )


    y_path = (
        LOCAL_SHARD_DIR
        /
        str(
            row[
                "y_filename"
            ]
        )
    )


    X = np.load(
        X_path,
        mmap_mode="r",
        allow_pickle=False
    )


    y = np.load(
        y_path,
        mmap_mode="r",
        allow_pickle=False
    )


    expected_X_shape = (
        expected_count,
        TEMPORAL_WINDOW,
        FEATURE_COUNT
    )


    expected_y_shape = (
        expected_count,
    )


    shape_valid = bool(
        X.shape
        ==
        expected_X_shape
        and
        y.shape
        ==
        expected_y_shape
    )


    dtype_valid = bool(
        X.dtype
        ==
        np.float32
        and
        y.dtype
        ==
        np.float32
    )


    finite_valid = bool(
        np.isfinite(
            X
        ).all()
        and
        np.isfinite(
            y
        ).all()
    )


    label_valid = bool(
        np.all(
            y
            ==
            target
        )
    )


    ALL_SHAPES_VALID &= shape_valid
    ALL_DTYPES_VALID &= dtype_valid
    ALL_FINITE &= finite_valid
    ALL_LABELS_VALID &= label_valid


    TOTAL_WINDOWS += expected_count


    if target == 0:
        TOTAL_BENIGN += expected_count
    else:
        TOTAL_ATTACK += expected_count


    print(
        f"{row_number + 1:02d}/21 "
        f"{source_class:<28} "
        f"| X={str(X.shape):<18} "
        f"| y={str(y.shape):<10} "
        f"| finite={finite_valid}"
    )


# ======================================================================
# 7 — DEFINE SHARDED DATASET
# ======================================================================

print("\n[6] Building ShardedTemporalDataset")
print("-" * 78)


class ShardedTemporalDataset(Dataset):

    def __init__(
        self,
        manifest,
        shard_dir
    ):

        self.manifest = (
            manifest
            .sort_values(
                "source_id"
            )
            .reset_index(
                drop=True
            )
        )


        self.shard_dir = Path(
            shard_dir
        )


        self.X_shards = []
        self.y_shards = []

        self.shard_lengths = []


        for _, row in self.manifest.iterrows():

            X_path = (
                self.shard_dir
                /
                str(
                    row[
                        "X_filename"
                    ]
                )
            )


            y_path = (
                self.shard_dir
                /
                str(
                    row[
                        "y_filename"
                    ]
                )
            )


            X = np.load(
                X_path,
                mmap_mode="r",
                allow_pickle=False
            )


            y = np.load(
                y_path,
                mmap_mode="r",
                allow_pickle=False
            )


            self.X_shards.append(
                X
            )


            self.y_shards.append(
                y
            )


            self.shard_lengths.append(
                len(X)
            )


        self.cumulative_lengths = (
            np.cumsum(
                self.shard_lengths
            )
        )


        self.total_length = int(
            self.cumulative_lengths[
                -1
            ]
        )


    def __len__(self):

        return self.total_length


    def __getitem__(
        self,
        index
    ):

        if index < 0:

            index += self.total_length


        if (
            index < 0
            or
            index >= self.total_length
        ):

            raise IndexError(
                "Dataset index out of range."
            )


        shard_index = bisect_right(
            self.cumulative_lengths,
            index
        )


        previous_end = (
            0
            if shard_index == 0
            else
            int(
                self.cumulative_lengths[
                    shard_index - 1
                ]
            )
        )


        local_index = (
            index
            -
            previous_end
        )


        X = np.array(
            self.X_shards[
                shard_index
            ][
                local_index
            ],
            dtype=np.float32,
            copy=True
        )


        y = np.float32(
            self.y_shards[
                shard_index
            ][
                local_index
            ]
        )


        return (
            torch.from_numpy(
                X
            ),
            torch.tensor(
                y,
                dtype=torch.float32
            )
        )


# ======================================================================
# 8 — CREATE DATASET
# ======================================================================

T4_TRAIN_DATASET = ShardedTemporalDataset(
    SHARD_MANIFEST,
    LOCAL_SHARD_DIR
)


print(
    "Dataset windows:",
    f"{len(T4_TRAIN_DATASET):,}"
)


if len(T4_TRAIN_DATASET) != EXPECTED_WINDOWS:
    raise RuntimeError(
        "T=4 dataset length mismatch."
    )


# ======================================================================
# 9 — CREATE DATALOADER
# ======================================================================

generator = torch.Generator()

generator.manual_seed(
    SEED
)


T4_TRAIN_LOADER = DataLoader(

    T4_TRAIN_DATASET,

    batch_size=BATCH_SIZE,

    shuffle=True,

    generator=generator,

    num_workers=0,

    pin_memory=False,

    drop_last=False
)


print(
    "DataLoader batches:",
    len(
        T4_TRAIN_LOADER
    )
)


# ======================================================================
# 10 — VERIFY INDIVIDUAL SAMPLES
# ======================================================================

print("\n[7] Verifying dataset samples")
print("-" * 78)


check_indices = [
    0,
    len(T4_TRAIN_DATASET) // 2,
    len(T4_TRAIN_DATASET) - 1
]


SAMPLES_VALID = True


for index in check_indices:

    X_sample, y_sample = (
        T4_TRAIN_DATASET[
            index
        ]
    )


    valid = bool(

        tuple(
            X_sample.shape
        )
        ==
        (
            TEMPORAL_WINDOW,
            FEATURE_COUNT
        )

        and

        X_sample.dtype
        ==
        torch.float32

        and

        y_sample.dtype
        ==
        torch.float32

        and

        bool(
            torch.isfinite(
                X_sample
            ).all()
        )

        and

        bool(
            torch.isfinite(
                y_sample
            )
        )

        and

        float(
            y_sample.item()
        )
        in
        [
            0.0,
            1.0
        ]
    )


    SAMPLES_VALID &= valid


    print(
        f"Index {index:>7,} "
        f"| X={tuple(X_sample.shape)} "
        f"| y={float(y_sample.item()):.0f} "
        f"| valid={valid}"
    )


# ======================================================================
# 11 — VERIFY ONE DATALOADER BATCH
# ======================================================================

print("\n[8] Verifying one DataLoader batch")
print("-" * 78)


X_batch, y_batch = next(
    iter(
        T4_TRAIN_LOADER
    )
)


BATCH_VALID = bool(

    X_batch.ndim == 3

    and

    X_batch.shape[1]
    ==
    TEMPORAL_WINDOW

    and

    X_batch.shape[2]
    ==
    FEATURE_COUNT

    and

    X_batch.dtype
    ==
    torch.float32

    and

    y_batch.ndim
    ==
    1

    and

    y_batch.shape[0]
    ==
    X_batch.shape[0]

    and

    y_batch.dtype
    ==
    torch.float32

    and

    bool(
        torch.isfinite(
            X_batch
        ).all()
    )

    and

    bool(
        torch.isfinite(
            y_batch
        ).all()
    )
)


print(
    "X batch shape:",
    tuple(
        X_batch.shape
    )
)

print(
    "y batch shape:",
    tuple(
        y_batch.shape
    )
)

print(
    "X dtype:",
    X_batch.dtype
)

print(
    "y dtype:",
    y_batch.dtype
)

print(
    "Batch finite:",
    bool(
        torch.isfinite(
            X_batch
        ).all()
        and
        torch.isfinite(
            y_batch
        ).all()
    )
)

print(
    "Batch valid:",
    BATCH_VALID
)


# ======================================================================
# 12 — SAVE A39 READINESS ARTIFACT
# ======================================================================

OUTPUT_DIR = (
    BACKUP_ROOT
    / "processed_data"
    / "model_ready"
    / "fold_01_DDoS"
    / "T4"
)


OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


READINESS_PATH = (
    OUTPUT_DIR
    / "A39_T4_pytorch_readiness.json"
)


READINESS = {

    "step":
        "A39",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "temporal_window":
        4,

    "feature_count":
        75,

    "dataset_windows":
        int(
            len(
                T4_TRAIN_DATASET
            )
        ),

    "benign_windows":
        TOTAL_BENIGN,

    "attack_windows":
        TOTAL_ATTACK,

    "source_shards":
        int(
            len(
                SHARD_MANIFEST
            )
        ),

    "batch_size":
        BATCH_SIZE,

    "batch_shape":
        list(
            X_batch.shape
        ),

    "labels_shape":
        list(
            y_batch.shape
        ),

    "all_shards_finite":
        ALL_FINITE,

    "dataset_samples_valid":
        SAMPLES_VALID,

    "dataloader_batch_valid":
        BATCH_VALID,

    "held_out_DDoS_used":
        False,

    "validation_used":
        False,

    "known_test_used":
        False,

    "zero_day_used":
        False,

    "model_training_performed":
        False,

    "current_runtime":
        (
            "cuda"
            if torch.cuda.is_available()
            else
            "cpu"
        )
}


with open(
    READINESS_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        READINESS,
        file,
        indent=4
    )


# ======================================================================
# 13 — FINAL VALIDATION
# ======================================================================

A39_VALID = bool(

    len(
        SHARD_MANIFEST
    )
    ==
    21

    and

    TOTAL_WINDOWS
    ==
    EXPECTED_WINDOWS

    and

    TOTAL_BENIGN
    ==
    EXPECTED_BENIGN

    and

    TOTAL_ATTACK
    ==
    EXPECTED_ATTACK

    and

    ALL_SHAPES_VALID

    and

    ALL_DTYPES_VALID

    and

    ALL_FINITE

    and

    ALL_LABELS_VALID

    and

    len(
        T4_TRAIN_DATASET
    )
    ==
    EXPECTED_WINDOWS

    and

    SAMPLES_VALID

    and

    BATCH_VALID

    and

    READINESS_PATH.exists()
)


STEP_39_T4_PYTORCH_DATA_VALID = (
    A39_VALID
)


print("\n[9] Step A39 validation")
print("-" * 78)

print(
    "Temporal window                 :",
    TEMPORAL_WINDOW
)

print(
    "Feature count                   :",
    FEATURE_COUNT
)

print(
    "Logical source shards           :",
    len(
        SHARD_MANIFEST
    ),
    "/ 21"
)

print(
    "Dataset windows                 :",
    f"{len(T4_TRAIN_DATASET):,}",
    "/ 119,285"
)

print(
    "Benign windows                  :",
    f"{TOTAL_BENIGN:,}",
    "/ 10,000"
)

print(
    "Attack windows                  :",
    f"{TOTAL_ATTACK:,}",
    "/ 109,285"
)

print(
    "All shard shapes valid          :",
    ALL_SHAPES_VALID
)

print(
    "All shard dtypes valid          :",
    ALL_DTYPES_VALID
)

print(
    "All shard values finite         :",
    ALL_FINITE
)

print(
    "All labels valid                :",
    ALL_LABELS_VALID
)

print(
    "Dataset samples valid           :",
    SAMPLES_VALID
)

print(
    "Batch shape                     :",
    tuple(
        X_batch.shape
    )
)

print(
    "Batch labels shape              :",
    tuple(
        y_batch.shape
    )
)

print(
    "DataLoader batch valid          :",
    BATCH_VALID
)

print(
    "Held-out DDoS used              :",
    False
)

print(
    "Validation used                 :",
    False
)

print(
    "Known-test used                 :",
    False
)

print(
    "Zero-day used                   :",
    False
)

print(
    "Model training performed        :",
    False
)

print(
    "Readiness artifact backed up    :",
    READINESS_PATH.exists()
)

print(
    "Current runtime                 :",
    "GPU" if torch.cuda.is_available() else "CPU"
)


print("\n" + "=" * 78)

if A39_VALID:

    print(
        "✅ STEP A39 PASSED — "
        "T=4 PyTorch dataset and DataLoader "
        "are valid and ready for SSL training."
    )

else:

    print(
        "❌ STEP A39 FAILED — "
        "do not begin T=4 SSL training."
    )

print("=" * 78)

==============================================================================
STEP A39 — BUILD + VERIFY T=4 PYTORCH DATASET/DATALOADER
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisite
------------------------------------------------------------------------------
A38 model-ready data valid: True

[2] Dataset configuration
------------------------------------------------------------------------------
Temporal window: 4
Feature count: 75
Expected windows: 119,285
Batch size: 256
Current runtime: CPU

[3] Loading A38 shard manifest
------------------------------------------------------------------------------
Logical source shards: 21
Manifest windows: 119,285

[4] Checking local T=4 shards
------------------------------------------------------------------------------
Files restored from Drive: 0
Local shard directory ready: True

[5] Verifying all T=4 shard arrays
------------------------------------------------------------------------------
01/21 Backdoor_Malware             | X=(473, 4, 75)       | y=(473,)     | finite=True
02/21 Benign_Final                 | X=(10000, 4, 75)     | y=(10000,)   | finite=True
03/21 BrowserHijacking             | X=(575, 4, 75)       | y=(575,)     | finite=True
04/21 CommandInjection             | X=(673, 4, 75)       | y=(673,)     | finite=True
05/21 DNS_Spoofing                 | X=(10000, 4, 75)     | y=(10000,)   | finite=True
06/21 DictionaryBruteForce         | X=(1485, 4, 75)      | y=(1485,)    | finite=True
07/21 DoS-HTTP_Flood               | X=(10000, 4, 75)     | y=(10000,)   | finite=True
08/21 DoS-SYN_Flood                | X=(10000, 4, 75)     | y=(10000,)   | finite=True
09/21 DoS-TCP_Flood                | X=(10000, 4, 75)     | y=(10000,)   | finite=True
10/21 DoS-UDP_Flood                | X=(10000, 4, 75)     | y=(10000,)   | finite=True
11/21 MITM-ArpSpoofing             | X=(10000, 4, 75)     | y=(10000,)   | finite=True
12/21 Mirai-greeth_flood           | X=(902, 4, 75)       | y=(902,)     | finite=True
13/21 Mirai-greip_flood            | X=(1820, 4, 75)      | y=(1820,)    | finite=True
14/21 Mirai-udpplain               | X=(1304, 4, 75)      | y=(1304,)    | finite=True
15/21 Recon-HostDiscovery          | X=(10000, 4, 75)     | y=(10000,)   | finite=True
16/21 Recon-OSScan                 | X=(10000, 4, 75)     | y=(10000,)   | finite=True
17/21 Recon-PingSweep              | X=(340, 4, 75)       | y=(340,)     | finite=True
18/21 Recon-PortScan               | X=(10000, 4, 75)     | y=(10000,)   | finite=True
19/21 SqlInjection                 | X=(1154, 4, 75)      | y=(1154,)    | finite=True
20/21 VulnerabilityScan            | X=(10000, 4, 75)     | y=(10000,)   | finite=True
21/21 XSS                          | X=(559, 4, 75)       | y=(559,)     | finite=True

[6] Building ShardedTemporalDataset
------------------------------------------------------------------------------
Dataset windows: 119,285
DataLoader batches: 466

[7] Verifying dataset samples
------------------------------------------------------------------------------
Index       0 | X=(4, 75) | y=1 | valid=True
Index  59,642 | X=(4, 75) | y=1 | valid=True
Index 119,284 | X=(4, 75) | y=1 | valid=True

[8] Verifying one DataLoader batch
------------------------------------------------------------------------------
X batch shape: (256, 4, 75)
y batch shape: (256,)
X dtype: torch.float32
y dtype: torch.float32
Batch finite: True
Batch valid: True

[9] Step A39 validation
------------------------------------------------------------------------------
Temporal window                 : 4
Feature count                   : 75
Logical source shards           : 21 / 21
Dataset windows                 : 119,285 / 119,285
Benign windows                  : 10,000 / 10,000
Attack windows                  : 109,285 / 109,285
All shard shapes valid          : True
All shard dtypes valid          : True
All shard values finite         : True
All labels valid                : True
Dataset samples valid           : True
Batch shape                     : (256, 4, 75)
Batch labels shape              : (256,)
DataLoader batch valid          : True
Held-out DDoS used              : False
Validation used                 : False
Known-test used                 : False
Zero-day used                   : False
Model training performed        : False
Readiness artifact backed up    : True
Current runtime                 : CPU

==============================================================================
✅ STEP A39 PASSED — T=4 PyTorch dataset and DataLoader are valid and ready for SSL training.
==============================================================================

# ⚠️ NOW is the point to switch to T4 GPU

In [ ]:
import torch

print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("GPU NOT AVAILABLE")

CUDA available: True
GPU: Tesla T4

# Fix — remount the Drive account that contains the backup

In [ ]:
# ======================================================================
# FIX — REMOUNT THE CORRECT GOOGLE DRIVE ACCOUNT
# ======================================================================

from pathlib import Path
from google.colab import drive

print("=" * 78)
print("REMOUNTING GOOGLE DRIVE")
print("=" * 78)

# Disconnect the currently mounted wrong account.
try:
    drive.flush_and_unmount()
    print("Previous Drive disconnected.")
except Exception:
    print("No active Drive mount to disconnect.")

print()
print("IMPORTANT:")
print("When Google asks you to authorize Drive,")
print("choose the Google account that contains:")
print("ZeroDay_IoT_Research_Backup")
print()

# Mount again.
drive.mount(
    "/content/drive",
    force_remount=True
)

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

print()
print("-" * 78)
print("Checking research backup")
print("-" * 78)

print("Expected path:")
print(BACKUP_ROOT)

print()
print("Backup root exists:", BACKUP_ROOT.exists())

if BACKUP_ROOT.exists():

    print()
    print("=" * 78)
    print("✅ CORRECT DRIVE ACCOUNT MOUNTED")
    print("Project backup found successfully.")
    print("=" * 78)

else:

    print()
    print("Top-level folders visible in this Drive:")

    mydrive = Path("/content/drive/MyDrive")

    if mydrive.exists():
        for item in sorted(mydrive.iterdir())[:30]:
            print(" -", item.name)

    print()
    print("=" * 78)
    print("❌ BACKUP NOT FOUND")
    print("This is still not the Google account containing the project.")
    print("=" * 78)

==============================================================================
REMOUNTING GOOGLE DRIVE
==============================================================================
Previous Drive disconnected.

IMPORTANT:
When Google asks you to authorize Drive,
choose the Google account that contains:
ZeroDay_IoT_Research_Backup

Mounted at /content/drive

------------------------------------------------------------------------------
Checking research backup
------------------------------------------------------------------------------
Expected path:
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup

Backup root exists: False

Top-level folders visible in this Drive:
 - Colab Notebooks
 - FYDP
 - SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb

==============================================================================
❌ BACKUP NOT FOUND
This is still not the Google account containing the project.
==============================================================================

# ZeroDay_IoT_Research_Backup

In [ ]:
from pathlib import Path

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

print("Backup root exists:", BACKUP_ROOT.exists())

if BACKUP_ROOT.exists():
    print("✅ Project backup is accessible from the T4 account.")
else:
    print("❌ Backup is still not accessible.")

Backup root exists: False
❌ Backup is still not accessible.

In [ ]:
# ======================================================================
# REFRESH GOOGLE DRIVE AFTER ADDING SHARED FOLDER SHORTCUT
# ======================================================================

from google.colab import drive
from pathlib import Path
import time

print("=" * 78)
print("REFRESHING GOOGLE DRIVE MOUNT")
print("=" * 78)

# Disconnect current mount.
try:
    drive.flush_and_unmount()
    print("Old Drive mount disconnected.")
except Exception as e:
    print("Unmount note:", e)

time.sleep(2)

# Remount the SAME T4 Google account.
drive.mount(
    "/content/drive",
    force_remount=True
)

MY_DRIVE = Path(
    "/content/drive/MyDrive"
)

BACKUP_ROOT = (
    MY_DRIVE
    / "ZeroDay_IoT_Research_Backup"
)

print()
print("Backup root exists:", BACKUP_ROOT.exists())

print()
print("Folders/files currently visible in My Drive:")
print("-" * 78)

for item in sorted(MY_DRIVE.iterdir()):
    print(" -", item.name)

print()

if BACKUP_ROOT.exists():

    print("=" * 78)
    print("✅ BACKUP FOUND AFTER DRIVE REFRESH")
    print("=" * 78)

else:

    print("=" * 78)
    print("❌ BACKUP STILL NOT FOUND")
    print("Send me the folder/file list printed above.")
    print("=" * 78)

==============================================================================
REFRESHING GOOGLE DRIVE MOUNT
==============================================================================
Old Drive mount disconnected.
Mounted at /content/drive

Backup root exists: False

Folders/files currently visible in My Drive:
------------------------------------------------------------------------------
 - Colab Notebooks
 - FYDP
 - SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb

==============================================================================
❌ BACKUP STILL NOT FOUND
Send me the folder/file list printed above.
==============================================================================

In [ ]:
# ======================================================================
# RECOVERY — MOUNT THE ORIGINAL PROJECT GOOGLE DRIVE ACCOUNT
# KEEP CURRENT T4 RUNTIME
# ======================================================================

from google.colab import drive
from pathlib import Path
import time

print("=" * 78)
print("MOUNTING ORIGINAL PROJECT DRIVE ACCOUNT")
print("=" * 78)

try:
    drive.flush_and_unmount()
    print("Current Drive disconnected.")
except Exception as e:
    print("Unmount note:", e)

time.sleep(2)

print()
print("IMPORTANT:")
print("When Google authorization opens:")
print("1. Click 'Use another account' if necessary.")
print("2. Choose the ORIGINAL Google account that contains")
print("   ZeroDay_IoT_Research_Backup")
print("3. Do NOT change the Colab runtime.")
print()

drive.mount(
    "/content/drive",
    force_remount=True
)

BACKUP_ROOT = Path(
    "/content/drive/MyDrive/ZeroDay_IoT_Research_Backup"
)

print()
print("Backup root exists:", BACKUP_ROOT.exists())

if BACKUP_ROOT.exists():

    print()
    print("✅ Original project Drive mounted successfully.")
    print("✅ Keep the current Tesla T4 runtime.")

else:

    print()
    print("❌ Backup still not found.")
    print()
    print("My Drive currently shows:")

    mydrive = Path("/content/drive/MyDrive")

    if mydrive.exists():
        for item in sorted(mydrive.iterdir())[:40]:
            print(" -", item.name)

==============================================================================
MOUNTING ORIGINAL PROJECT DRIVE ACCOUNT
==============================================================================
Current Drive disconnected.

IMPORTANT:
When Google authorization opens:
1. Click 'Use another account' if necessary.
2. Choose the ORIGINAL Google account that contains
   ZeroDay_IoT_Research_Backup
3. Do NOT change the Colab runtime.

Mounted at /content/drive

Backup root exists: False

❌ Backup still not found.

My Drive currently shows:
 - Colab Notebooks
 - FYDP
 - SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb

In [ ]:
from pathlib import Path

T4_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4"
)

print("T4 root exists:", T4_ROOT.exists())

if T4_ROOT.exists():
    for item in sorted(T4_ROOT.iterdir()):
        print(" -", item.name)

T4 root exists: False

In [ ]:
from pathlib import Path

MYDRIVE = Path("/content/drive/MyDrive")

print("=" * 78)
print("SEARCHING CURRENT DRIVE FOR T=4 PROJECT ARTIFACTS")
print("=" * 78)

targets = [
    "A39_T4_pytorch_readiness.json",
    "T4_train_shard_manifest.csv",
    "T4_model_ready_summary.json",
]

found_any = False

for target in targets:
    matches = list(MYDRIVE.rglob(target))

    print(f"\n{target}")
    print("-" * 78)

    if matches:
        found_any = True

        for path in matches:
            print("FOUND:", path)
    else:
        print("NOT FOUND")

print("\n" + "=" * 78)

if found_any:
    print("✅ Some T=4 artifacts exist in this Drive.")
else:
    print("❌ No T=4 model-ready artifacts were found in this Drive.")

print("=" * 78)

==============================================================================
SEARCHING CURRENT DRIVE FOR T=4 PROJECT ARTIFACTS
==============================================================================

A39_T4_pytorch_readiness.json
------------------------------------------------------------------------------
NOT FOUND

T4_train_shard_manifest.csv
------------------------------------------------------------------------------
NOT FOUND

T4_model_ready_summary.json
------------------------------------------------------------------------------
NOT FOUND

==============================================================================
❌ No T=4 model-ready artifacts were found in this Drive.
==============================================================================

In [ ]:
# ======================================================================
# TRANSFER T=4 ARTIFACTS FROM ORIGINAL ACCOUNT TO CURRENT T4 RUNTIME
# ======================================================================

from google.colab import files
from pathlib import Path
import zipfile
import shutil

print("=" * 78)
print("UPLOAD T=4 ARTIFACT ZIP")
print("=" * 78)

# ----------------------------------------------------------------------
# 1 — Upload the ZIP you downloaded from the ORIGINAL Drive account
# ----------------------------------------------------------------------

uploaded = files.upload()

if len(uploaded) != 1:
    raise RuntimeError(
        "Please upload exactly one ZIP file containing the T4 folder."
    )

uploaded_name = list(uploaded.keys())[0]

ZIP_PATH = Path("/content") / uploaded_name

if ZIP_PATH.suffix.lower() != ".zip":
    raise RuntimeError(
        f"Expected a ZIP file, got: {ZIP_PATH.name}"
    )

print()
print("Uploaded:", ZIP_PATH.name)


# ----------------------------------------------------------------------
# 2 — Extract to temporary transfer area
# ----------------------------------------------------------------------

TRANSFER_ROOT = Path("/content/T4_transfer")

if TRANSFER_ROOT.exists():
    shutil.rmtree(TRANSFER_ROOT)

TRANSFER_ROOT.mkdir(
    parents=True,
    exist_ok=True
)

with zipfile.ZipFile(
    ZIP_PATH,
    "r"
) as zip_file:

    zip_file.extractall(
        TRANSFER_ROOT
    )

print("ZIP extracted successfully.")


# ----------------------------------------------------------------------
# 3 — Locate the real T4 folder automatically
# ----------------------------------------------------------------------

matches = list(
    TRANSFER_ROOT.rglob(
        "A39_T4_pytorch_readiness.json"
    )
)

if len(matches) == 0:
    raise RuntimeError(
        "A39_T4_pytorch_readiness.json was not found inside the ZIP.\n"
        "Make sure you downloaded the correct T4 folder from the original account."
    )

if len(matches) > 1:
    raise RuntimeError(
        "Multiple A39 readiness files were found. "
        "Please check the ZIP contents."
    )

TRANSFER_T4_ROOT = matches[0].parent

print()
print("Detected T4 folder:")
print(TRANSFER_T4_ROOT)


# ----------------------------------------------------------------------
# 4 — Verify required A38/A39 artifacts
# ----------------------------------------------------------------------

required_files = [
    TRANSFER_T4_ROOT
    / "A39_T4_pytorch_readiness.json",

    TRANSFER_T4_ROOT
    / "train_shards"
    / "T4_train_shard_manifest.csv",

    TRANSFER_T4_ROOT
    / "train_shards"
    / "T4_model_ready_summary.json",
]

for path in required_files:

    if not path.exists():
        raise RuntimeError(
            f"Required file missing:\n{path}"
        )

print()
print("Required A38/A39 artifacts found: True")


# ----------------------------------------------------------------------
# 5 — Copy into the local runtime path expected by A40
# ----------------------------------------------------------------------

LOCAL_T4_ROOT = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4"
)

LOCAL_T4_ROOT.parent.mkdir(
    parents=True,
    exist_ok=True
)

if LOCAL_T4_ROOT.exists():
    shutil.rmtree(
        LOCAL_T4_ROOT
    )

shutil.copytree(
    TRANSFER_T4_ROOT,
    LOCAL_T4_ROOT
)

print("Copied to local runtime:", LOCAL_T4_ROOT)


# ----------------------------------------------------------------------
# 6 — ALSO SAVE A COPY IN CURRENT T4 ACCOUNT DRIVE
# ----------------------------------------------------------------------

CURRENT_DRIVE_T4_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4"
)

CURRENT_DRIVE_T4_ROOT.parent.mkdir(
    parents=True,
    exist_ok=True
)

shutil.copytree(
    TRANSFER_T4_ROOT,
    CURRENT_DRIVE_T4_ROOT,
    dirs_exist_ok=True
)

print("Copied to current Drive:", CURRENT_DRIVE_T4_ROOT)


# ----------------------------------------------------------------------
# 7 — FINAL CHECK
# ----------------------------------------------------------------------

local_manifest = (
    LOCAL_T4_ROOT
    / "train_shards"
    / "T4_train_shard_manifest.csv"
)

drive_manifest = (
    CURRENT_DRIVE_T4_ROOT
    / "train_shards"
    / "T4_train_shard_manifest.csv"
)

TRANSFER_VALID = bool(
    LOCAL_T4_ROOT.exists()
    and
    CURRENT_DRIVE_T4_ROOT.exists()
    and
    local_manifest.exists()
    and
    drive_manifest.exists()
)

print()
print("=" * 78)

if TRANSFER_VALID:
    print("✅ T=4 ARTIFACT TRANSFER PASSED")
    print("Local runtime copy: True")
    print("Current T4-account Drive backup: True")
else:
    print("❌ T=4 ARTIFACT TRANSFER FAILED")

print("=" * 78)

==============================================================================
UPLOAD T=4 ARTIFACT ZIP
==============================================================================

Saving T4-20260930T073324Z-1-001.zip to T4-20260930T073324Z-1-001.zip

Uploaded: T4-20260930T073324Z-1-001.zip
ZIP extracted successfully.

Detected T4 folder:
/content/T4_transfer/T4

Required A38/A39 artifacts found: True
Copied to local runtime: /content/ZeroDay_IoT_Research/processed_data/model_ready/fold_01_DDoS/T4
Copied to current Drive: /content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/model_ready/fold_01_DDoS/T4

==============================================================================
✅ T=4 ARTIFACT TRANSFER PASSED
Local runtime copy: True
Current T4-account Drive backup: True
==============================================================================

# A40 recovery cell

In [ ]:
# ======================================================================
# STEP A40-R
# RESTORE T=4 TRAINING STATE AFTER CROSS-ACCOUNT TRANSFER
#
# NO TRAINING YET
# ======================================================================

from pathlib import Path
from bisect import bisect_right
import json
import numpy as np
import pandas as pd
import torch

from torch.utils.data import Dataset, DataLoader


print("=" * 78)
print("STEP A40-R — RESTORE T=4 TRAINING STATE ON TESLA T4")
print("=" * 78)


# ======================================================================
# 1 — GPU CHECK
# ======================================================================

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA is unavailable. Do not start SSL training."
    )

DEVICE = torch.device("cuda")
GPU_NAME = torch.cuda.get_device_name(0)

print("\n[1] GPU")
print("-" * 78)
print("CUDA available:", True)
print("GPU:", GPU_NAME)
print("Device:", DEVICE)


# ======================================================================
# 2 — PATHS
# ======================================================================

LOCAL_T4_ROOT = Path(
    "/content/ZeroDay_IoT_Research/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4"
)

DRIVE_T4_ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "processed_data/model_ready/"
    "fold_01_DDoS/T4"
)

LOCAL_SHARD_DIR = (
    LOCAL_T4_ROOT
    / "train_shards"
)

DRIVE_SHARD_DIR = (
    DRIVE_T4_ROOT
    / "train_shards"
)

MANIFEST_PATH = (
    LOCAL_SHARD_DIR
    / "T4_train_shard_manifest.csv"
)

SUMMARY_PATH = (
    LOCAL_SHARD_DIR
    / "T4_model_ready_summary.json"
)

A39_PATH = (
    LOCAL_T4_ROOT
    / "A39_T4_pytorch_readiness.json"
)


required_paths = [
    LOCAL_T4_ROOT,
    DRIVE_T4_ROOT,
    LOCAL_SHARD_DIR,
    MANIFEST_PATH,
    SUMMARY_PATH,
    A39_PATH
]

for path in required_paths:
    if not path.exists():
        raise RuntimeError(
            f"Required transferred artifact missing:\n{path}"
        )


print("\n[2] Transferred artifacts")
print("-" * 78)
print("Local T4 root:", LOCAL_T4_ROOT.exists())
print("Drive T4 backup:", DRIVE_T4_ROOT.exists())
print("Shard manifest:", MANIFEST_PATH.exists())
print("A39 readiness:", A39_PATH.exists())


# ======================================================================
# 3 — VERIFY A38/A39 METADATA
# ======================================================================

with open(
    SUMMARY_PATH,
    "r",
    encoding="utf-8"
) as f:
    a38 = json.load(f)

with open(
    A39_PATH,
    "r",
    encoding="utf-8"
) as f:
    a39 = json.load(f)


A38_VALID = bool(
    a38.get("step") == "A38"
    and int(a38.get("temporal_window", -1)) == 4
    and int(a38.get("materialized_windows", -1)) == 119_285
    and int(a38.get("benign_windows", -1)) == 10_000
    and int(a38.get("attack_windows", -1)) == 109_285
    and int(a38.get("held_out_DDoS_windows", -1)) == 0
)

A39_VALID = bool(
    a39.get("step") == "A39"
    and int(a39.get("dataset_windows", -1)) == 119_285
    and bool(a39.get("all_shards_finite"))
    and bool(a39.get("dataset_samples_valid"))
    and bool(a39.get("dataloader_batch_valid"))
)


print("\n[3] Previous-step verification")
print("-" * 78)
print("A38 artifact valid:", A38_VALID)
print("A39 artifact valid:", A39_VALID)


if not A38_VALID:
    raise RuntimeError(
        "Transferred A38 metadata failed validation."
    )

if not A39_VALID:
    raise RuntimeError(
        "Transferred A39 metadata failed validation."
    )


# ======================================================================
# 4 — LOAD SHARD MANIFEST
# ======================================================================

SHARD_MANIFEST = (
    pd.read_csv(
        MANIFEST_PATH
    )
    .sort_values("source_id")
    .reset_index(drop=True)
)


TOTAL_WINDOWS = int(
    SHARD_MANIFEST[
        "sampled_windows"
    ].sum()
)

TOTAL_BENIGN = int(
    SHARD_MANIFEST.loc[
        SHARD_MANIFEST["binary_target"] == 0,
        "sampled_windows"
    ].sum()
)

TOTAL_ATTACK = int(
    SHARD_MANIFEST.loc[
        SHARD_MANIFEST["binary_target"] == 1,
        "sampled_windows"
    ].sum()
)


print("\n[4] T=4 shard manifest")
print("-" * 78)
print("Logical source shards:", len(SHARD_MANIFEST))
print("Total windows:", f"{TOTAL_WINDOWS:,}")
print("Benign windows:", f"{TOTAL_BENIGN:,}")
print("Attack windows:", f"{TOTAL_ATTACK:,}")


if len(SHARD_MANIFEST) != 21:
    raise RuntimeError(
        "Expected 21 source shards."
    )

if TOTAL_WINDOWS != 119_285:
    raise RuntimeError(
        "T=4 window count mismatch."
    )

if TOTAL_BENIGN != 10_000:
    raise RuntimeError(
        "T=4 benign count mismatch."
    )

if TOTAL_ATTACK != 109_285:
    raise RuntimeError(
        "T=4 attack count mismatch."
    )


# ======================================================================
# 5 — VERIFY SHARD FILES
# ======================================================================

for _, row in SHARD_MANIFEST.iterrows():

    X_path = (
        LOCAL_SHARD_DIR
        / str(row["X_filename"])
    )

    y_path = (
        LOCAL_SHARD_DIR
        / str(row["y_filename"])
    )

    if not X_path.exists():
        raise RuntimeError(
            f"Missing X shard:\n{X_path}"
        )

    if not y_path.exists():
        raise RuntimeError(
            f"Missing y shard:\n{y_path}"
        )


print(
    "All local shard files found:",
    True
)


# ======================================================================
# 6 — DATASET CLASS
# ======================================================================

class ShardedTemporalDataset(Dataset):

    def __init__(
        self,
        manifest,
        shard_dir
    ):

        self.manifest = (
            manifest
            .sort_values("source_id")
            .reset_index(drop=True)
        )

        self.shard_dir = Path(
            shard_dir
        )

        self.X_shards = []
        self.y_shards = []
        self.shard_lengths = []

        for _, row in self.manifest.iterrows():

            X = np.load(
                self.shard_dir
                / str(row["X_filename"]),
                mmap_mode="r",
                allow_pickle=False
            )

            y = np.load(
                self.shard_dir
                / str(row["y_filename"]),
                mmap_mode="r",
                allow_pickle=False
            )

            if X.shape[1:] != (4, 75):
                raise RuntimeError(
                    f"Invalid X shape: {X.shape}"
                )

            if len(X) != len(y):
                raise RuntimeError(
                    "X/y length mismatch."
                )

            self.X_shards.append(X)
            self.y_shards.append(y)
            self.shard_lengths.append(len(X))

        self.cumulative_lengths = np.cumsum(
            self.shard_lengths
        )

        self.total_length = int(
            self.cumulative_lengths[-1]
        )


    def __len__(self):
        return self.total_length


    def __getitem__(self, index):

        if index < 0:
            index += self.total_length

        if index < 0 or index >= self.total_length:
            raise IndexError(
                "Dataset index out of range."
            )

        shard_index = bisect_right(
            self.cumulative_lengths,
            index
        )

        previous_end = (
            0
            if shard_index == 0
            else int(
                self.cumulative_lengths[
                    shard_index - 1
                ]
            )
        )

        local_index = (
            index
            -
            previous_end
        )

        X = np.array(
            self.X_shards[
                shard_index
            ][
                local_index
            ],
            dtype=np.float32,
            copy=True
        )

        y = np.float32(
            self.y_shards[
                shard_index
            ][
                local_index
            ]
        )

        return (
            torch.from_numpy(X),
            torch.tensor(
                y,
                dtype=torch.float32
            )
        )


# ======================================================================
# 7 — REBUILD DATASET + LOADER
# ======================================================================

T4_TRAIN_DATASET = ShardedTemporalDataset(
    SHARD_MANIFEST,
    LOCAL_SHARD_DIR
)


generator = torch.Generator()
generator.manual_seed(13)


T4_TRAIN_LOADER = DataLoader(
    T4_TRAIN_DATASET,
    batch_size=256,
    shuffle=True,
    generator=generator,
    num_workers=0,
    pin_memory=True,
    drop_last=False
)


print("\n[5] Dataset/DataLoader restored")
print("-" * 78)

print(
    "Dataset windows:",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "DataLoader batches:",
    len(T4_TRAIN_LOADER)
)


# ======================================================================
# 8 — TEST CPU BATCH
# ======================================================================

X_batch, y_batch = next(
    iter(T4_TRAIN_LOADER)
)


CPU_BATCH_VALID = bool(
    tuple(X_batch.shape) == (256, 4, 75)
    and tuple(y_batch.shape) == (256,)
    and X_batch.dtype == torch.float32
    and y_batch.dtype == torch.float32
    and torch.isfinite(X_batch).all()
    and torch.isfinite(y_batch).all()
)


print("\n[6] CPU batch")
print("-" * 78)

print(
    "X shape:",
    tuple(X_batch.shape)
)

print(
    "y shape:",
    tuple(y_batch.shape)
)

print(
    "CPU batch valid:",
    CPU_BATCH_VALID
)


# ======================================================================
# 9 — TEST GPU TRANSFER
# ======================================================================

X_gpu = X_batch.to(
    DEVICE,
    non_blocking=True
)

y_gpu = y_batch.to(
    DEVICE,
    non_blocking=True
)


GPU_TRANSFER_VALID = bool(
    X_gpu.is_cuda
    and y_gpu.is_cuda
    and tuple(X_gpu.shape) == (256, 4, 75)
    and tuple(y_gpu.shape) == (256,)
    and torch.isfinite(X_gpu).all()
    and torch.isfinite(y_gpu).all()
)


print("\n[7] Tesla T4 transfer")
print("-" * 78)

print(
    "GPU:",
    GPU_NAME
)

print(
    "X on CUDA:",
    X_gpu.is_cuda
)

print(
    "y on CUDA:",
    y_gpu.is_cuda
)

print(
    "GPU transfer valid:",
    GPU_TRANSFER_VALID
)


del X_gpu
del y_gpu

torch.cuda.empty_cache()


# ======================================================================
# 10 — SAVE NEW A40 READINESS
# ======================================================================

A40_PATH = (
    DRIVE_T4_ROOT
    / "A40_T4_GPU_training_readiness.json"
)


A40_RECORD = {
    "step": "A40-R",
    "fold_id": 1,
    "held_out_family": "DDoS",
    "temporal_window": 4,
    "feature_count": 75,
    "dataset_windows": len(T4_TRAIN_DATASET),
    "benign_windows": TOTAL_BENIGN,
    "attack_windows": TOTAL_ATTACK,
    "batch_size": 256,
    "gpu_name": GPU_NAME,
    "cuda_available": True,
    "cpu_batch_valid": CPU_BATCH_VALID,
    "gpu_transfer_valid": GPU_TRANSFER_VALID,
    "model_training_performed": False
}


with open(
    A40_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        A40_RECORD,
        f,
        indent=4
    )


# ======================================================================
# 11 — FINAL VALIDATION
# ======================================================================

A40_VALID = bool(
    torch.cuda.is_available()
    and len(SHARD_MANIFEST) == 21
    and len(T4_TRAIN_DATASET) == 119_285
    and TOTAL_BENIGN == 10_000
    and TOTAL_ATTACK == 109_285
    and CPU_BATCH_VALID
    and GPU_TRANSFER_VALID
    and A40_PATH.exists()
)


STEP_40_T4_GPU_TRAINING_READY = (
    A40_VALID
)


print("\n[8] Step A40-R validation")
print("-" * 78)

print(
    "GPU                             :",
    GPU_NAME
)

print(
    "CUDA available                  :",
    torch.cuda.is_available()
)

print(
    "Dataset windows                 :",
    f"{len(T4_TRAIN_DATASET):,}",
    "/ 119,285"
)

print(
    "Benign windows                  :",
    f"{TOTAL_BENIGN:,}",
    "/ 10,000"
)

print(
    "Attack windows                  :",
    f"{TOTAL_ATTACK:,}",
    "/ 109,285"
)

print(
    "Batch shape                     :",
    tuple(X_batch.shape)
)

print(
    "CPU batch valid                 :",
    CPU_BATCH_VALID
)

print(
    "GPU transfer valid              :",
    GPU_TRANSFER_VALID
)

print(
    "Model training performed        :",
    False
)

print(
    "A40 readiness backed up         :",
    A40_PATH.exists()
)


print("\n" + "=" * 78)

if A40_VALID:

    print(
        "✅ STEP A40-R PASSED — "
        "T=4 training state restored and "
        "Tesla T4 is ready."
    )

else:

    print(
        "❌ STEP A40-R FAILED — "
        "do not begin SSL training."
    )

print("=" * 78)

==============================================================================
STEP A40-R — RESTORE T=4 TRAINING STATE ON TESLA T4
==============================================================================

[1] GPU
------------------------------------------------------------------------------
CUDA available: True
GPU: Tesla T4
Device: cuda

[2] Transferred artifacts
------------------------------------------------------------------------------
Local T4 root: True
Drive T4 backup: True
Shard manifest: True
A39 readiness: True

[3] Previous-step verification
------------------------------------------------------------------------------
A38 artifact valid: True
A39 artifact valid: True

[4] T=4 shard manifest
------------------------------------------------------------------------------
Logical source shards: 21
Total windows: 119,285
Benign windows: 10,000
Attack windows: 109,285
All local shard files found: True

[5] Dataset/DataLoader restored
------------------------------------------------------------------------------
Dataset windows: 119,285
DataLoader batches: 466

[6] CPU batch
------------------------------------------------------------------------------
X shape: (256, 4, 75)
y shape: (256,)
CPU batch valid: True

[7] Tesla T4 transfer
------------------------------------------------------------------------------
GPU: Tesla T4
X on CUDA: True
y on CUDA: True
GPU transfer valid: True

[8] Step A40-R validation
------------------------------------------------------------------------------
GPU                             : Tesla T4
CUDA available                  : True
Dataset windows                 : 119,285 / 119,285
Benign windows                  : 10,000 / 10,000
Attack windows                  : 109,285 / 109,285
Batch shape                     : (256, 4, 75)
CPU batch valid                 : True
GPU transfer valid              : True
Model training performed        : False
A40 readiness backed up         : True

==============================================================================
✅ STEP A40-R PASSED — T=4 training state restored and Tesla T4 is ready.
==============================================================================

# Step A41 — Restore and verify T=4 model architecture

In [ ]:
# ======================================================================
# STEP A41
# RESTORE + VERIFY MOT-SSL-GRU ARCHITECTURE FOR T=4
#
# Fold 1: DDoS held out
# T = 4
# Features = 75
#
# SAME ARCHITECTURE FAMILY AS T=8:
#   Feature encoder: 75 -> 128
#   GRU hidden: 128
#   Projection: 128 -> 64
#   Temporal-order head
#   Binary-classification head
#
# NO TRAINING IN THIS STEP.
# ======================================================================

from pathlib import Path
import json

import torch
import torch.nn as nn
import torch.nn.functional as F


print("=" * 78)
print("STEP A41 — RESTORE + VERIFY T=4 MOT-SSL-GRU ARCHITECTURE")
print("FOLD 1 | HELD-OUT FAMILY = DDoS")
print("=" * 78)


# ======================================================================
# 1 — VERIFY A40-R + GPU
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)


if (
    "STEP_40_T4_GPU_TRAINING_READY"
    not in globals()
):
    raise RuntimeError(
        "STEP_40_T4_GPU_TRAINING_READY is missing."
    )


if not STEP_40_T4_GPU_TRAINING_READY:
    raise RuntimeError(
        "A40-R did not pass."
    )


if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA is unavailable."
    )


DEVICE = torch.device("cuda")
GPU_NAME = torch.cuda.get_device_name(0)


print(
    "A40-R GPU readiness:",
    STEP_40_T4_GPU_TRAINING_READY
)

print(
    "GPU:",
    GPU_NAME
)

print(
    "Device:",
    DEVICE
)


# ======================================================================
# 2 — ARCHITECTURE CONFIGURATION
# ======================================================================

INPUT_DIM = 75
TEMPORAL_WINDOW = 4

FEATURE_EMBED_DIM = 128
GRU_HIDDEN_DIM = 128
GRU_NUM_LAYERS = 1

PROJECTION_DIM = 64
ORDER_HIDDEN_DIM = 128
CLASSIFIER_HIDDEN_DIM = 64

DROPOUT = 0.10


print("\n[2] Architecture configuration")
print("-" * 78)

print("Input features:", INPUT_DIM)
print("Temporal window:", TEMPORAL_WINDOW)
print("Feature embedding:", FEATURE_EMBED_DIM)
print("GRU hidden dimension:", GRU_HIDDEN_DIM)
print("GRU layers:", GRU_NUM_LAYERS)
print("Projection dimension:", PROJECTION_DIM)
print("Dropout:", DROPOUT)


# ======================================================================
# 3 — MODEL COMPONENTS
# ======================================================================

class SharedFeatureEncoder(nn.Module):

    def __init__(
        self,
        input_dim,
        embed_dim,
        dropout
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                embed_dim
            ),

            nn.LayerNorm(
                embed_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            )
        )


    def forward(self, x):

        return self.network(x)


class GRUTemporalEncoder(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim,
        num_layers
    ):

        super().__init__()

        self.gru = nn.GRU(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layers,
            batch_first=True
        )


    def forward(self, x):

        outputs, hidden = self.gru(x)

        representation = hidden[-1]

        return representation


class ProjectionHead(nn.Module):

    def __init__(
        self,
        input_dim,
        projection_dim
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                input_dim
            ),

            nn.LayerNorm(
                input_dim
            ),

            nn.GELU(),

            nn.Linear(
                input_dim,
                projection_dim
            )
        )


    def forward(self, x):

        z = self.network(x)

        z = F.normalize(
            z,
            p=2,
            dim=-1
        )

        return z


class TemporalOrderHead(nn.Module):

    def __init__(
        self,
        representation_dim,
        hidden_dim,
        dropout
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                representation_dim * 2,
                hidden_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden_dim,
                1
            )
        )


    def forward(
        self,
        first_representation,
        second_representation
    ):

        combined = torch.cat(
            [
                first_representation,
                second_representation
            ],
            dim=-1
        )

        return (
            self.network(
                combined
            )
            .squeeze(-1)
        )


class BinaryClassifierHead(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim,
        dropout
    ):

        super().__init__()

        self.network = nn.Sequential(

            nn.Linear(
                input_dim,
                hidden_dim
            ),

            nn.GELU(),

            nn.Dropout(
                dropout
            ),

            nn.Linear(
                hidden_dim,
                1
            )
        )


    def forward(self, x):

        return (
            self.network(x)
            .squeeze(-1)
        )


# ======================================================================
# 4 — COMPLETE MOT-SSL-GRU MODEL
# ======================================================================

class MOTSSLGRU(nn.Module):

    def __init__(
        self,
        input_dim=75,
        feature_embed_dim=128,
        gru_hidden_dim=128,
        gru_num_layers=1,
        projection_dim=64,
        order_hidden_dim=128,
        classifier_hidden_dim=64,
        dropout=0.10
    ):

        super().__init__()


        self.feature_encoder = SharedFeatureEncoder(
            input_dim=input_dim,
            embed_dim=feature_embed_dim,
            dropout=dropout
        )


        self.temporal_encoder = GRUTemporalEncoder(
            input_dim=feature_embed_dim,
            hidden_dim=gru_hidden_dim,
            num_layers=gru_num_layers
        )


        self.projection_head = ProjectionHead(
            input_dim=gru_hidden_dim,
            projection_dim=projection_dim
        )


        self.temporal_order_head = TemporalOrderHead(
            representation_dim=gru_hidden_dim,
            hidden_dim=order_hidden_dim,
            dropout=dropout
        )


        self.classifier_head = BinaryClassifierHead(
            input_dim=gru_hidden_dim,
            hidden_dim=classifier_hidden_dim,
            dropout=dropout
        )


    def encode(self, x):

        features = self.feature_encoder(x)

        representation = self.temporal_encoder(
            features
        )

        return representation


    def forward_projection(self, x):

        representation = self.encode(x)

        projection = self.projection_head(
            representation
        )

        return projection


    def forward_classifier(self, x):

        representation = self.encode(x)

        logits = self.classifier_head(
            representation
        )

        return logits


    def forward_temporal_order(
        self,
        first_sequence,
        second_sequence
    ):

        first_representation = self.encode(
            first_sequence
        )

        second_representation = self.encode(
            second_sequence
        )

        logits = self.temporal_order_head(
            first_representation,
            second_representation
        )

        return logits


# ======================================================================
# 5 — CREATE TEST MODEL
# ======================================================================

print("\n[3] Creating architecture")
print("-" * 78)


T4_ARCHITECTURE_MODEL = MOTSSLGRU(

    input_dim=INPUT_DIM,

    feature_embed_dim=FEATURE_EMBED_DIM,

    gru_hidden_dim=GRU_HIDDEN_DIM,

    gru_num_layers=GRU_NUM_LAYERS,

    projection_dim=PROJECTION_DIM,

    order_hidden_dim=ORDER_HIDDEN_DIM,

    classifier_hidden_dim=CLASSIFIER_HIDDEN_DIM,

    dropout=DROPOUT

).to(
    DEVICE
).float()


# ======================================================================
# 6 — PARAMETER COUNTS
# ======================================================================

ENCODER_PARAMETERS = sum(

    parameter.numel()

    for parameter in (

        list(
            T4_ARCHITECTURE_MODEL
            .feature_encoder
            .parameters()
        )

        +

        list(
            T4_ARCHITECTURE_MODEL
            .temporal_encoder
            .parameters()
        )
    )
)


SSL_HEAD_PARAMETERS = sum(

    parameter.numel()

    for parameter in (

        list(
            T4_ARCHITECTURE_MODEL
            .projection_head
            .parameters()
        )

        +

        list(
            T4_ARCHITECTURE_MODEL
            .temporal_order_head
            .parameters()
        )
    )
)


CLASSIFIER_PARAMETERS = sum(

    parameter.numel()

    for parameter in (

        T4_ARCHITECTURE_MODEL
        .classifier_head
        .parameters()
    )
)


TOTAL_PARAMETERS = sum(

    parameter.numel()

    for parameter in
    T4_ARCHITECTURE_MODEL.parameters()
)


print(
    "Encoder parameters:",
    f"{ENCODER_PARAMETERS:,}"
)

print(
    "SSL-head parameters:",
    f"{SSL_HEAD_PARAMETERS:,}"
)

print(
    "Classifier parameters:",
    f"{CLASSIFIER_PARAMETERS:,}"
)

print(
    "Total parameters:",
    f"{TOTAL_PARAMETERS:,}"
)


# Exact A14 architecture counts.

PARAMETER_COUNTS_VALID = bool(

    ENCODER_PARAMETERS
    ==
    109_056

    and

    SSL_HEAD_PARAMETERS
    ==
    58_049

    and

    CLASSIFIER_PARAMETERS
    ==
    8_321

    and

    TOTAL_PARAMETERS
    ==
    175_426
)


# ======================================================================
# 7 — TEST T=4 FORWARD PASSES
# ======================================================================

print("\n[4] Testing T=4 forward passes")
print("-" * 78)


X_test, y_test = next(
    iter(
        T4_TRAIN_LOADER
    )
)


X_test = X_test.to(
    DEVICE,
    dtype=torch.float32
)


T4_ARCHITECTURE_MODEL.eval()


with torch.no_grad():

    representation = (
        T4_ARCHITECTURE_MODEL
        .encode(
            X_test
        )
    )


    projection = (
        T4_ARCHITECTURE_MODEL
        .forward_projection(
            X_test
        )
    )


    classifier_logits = (
        T4_ARCHITECTURE_MODEL
        .forward_classifier(
            X_test
        )
    )


    reversed_X = torch.flip(
        X_test,
        dims=[
            1
        ]
    )


    order_logits = (
        T4_ARCHITECTURE_MODEL
        .forward_temporal_order(
            X_test,
            reversed_X
        )
    )


EXPECTED_BATCH = int(
    X_test.shape[0]
)


SHAPES_VALID = bool(

    tuple(
        X_test.shape
    )
    ==
    (
        EXPECTED_BATCH,
        4,
        75
    )

    and

    tuple(
        representation.shape
    )
    ==
    (
        EXPECTED_BATCH,
        128
    )

    and

    tuple(
        projection.shape
    )
    ==
    (
        EXPECTED_BATCH,
        64
    )

    and

    tuple(
        classifier_logits.shape
    )
    ==
    (
        EXPECTED_BATCH,
    )

    and

    tuple(
        order_logits.shape
    )
    ==
    (
        EXPECTED_BATCH,
    )
)


OUTPUTS_FINITE = bool(

    torch.isfinite(
        representation
    ).all()

    and

    torch.isfinite(
        projection
    ).all()

    and

    torch.isfinite(
        classifier_logits
    ).all()

    and

    torch.isfinite(
        order_logits
    ).all()
)


PROJECTION_NORMS = torch.linalg.vector_norm(
    projection,
    ord=2,
    dim=1
)


MAX_PROJECTION_NORM_ERROR = float(

    torch.max(
        torch.abs(
            PROJECTION_NORMS
            -
            1.0
        )
    )
    .detach()
    .cpu()
)


PROJECTION_NORMALIZATION_VALID = bool(

    MAX_PROJECTION_NORM_ERROR
    <
    1e-5
)


print(
    "Input shape:",
    tuple(
        X_test.shape
    )
)

print(
    "Representation shape:",
    tuple(
        representation.shape
    )
)

print(
    "Projection shape:",
    tuple(
        projection.shape
    )
)

print(
    "Classifier-logit shape:",
    tuple(
        classifier_logits.shape
    )
)

print(
    "Order-logit shape:",
    tuple(
        order_logits.shape
    )
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Max projection norm error:",
    f"{MAX_PROJECTION_NORM_ERROR:.10e}"
)


# ======================================================================
# 8 — SAVE ARCHITECTURE SPEC
# ======================================================================

ARCHITECTURE_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "models/architecture/"
    "fold_01_DDoS/T4"
)


ARCHITECTURE_DIR.mkdir(
    parents=True,
    exist_ok=True
)


ARCHITECTURE_PATH = (
    ARCHITECTURE_DIR
    / "T4_MOT_SSL_GRU_architecture.json"
)


ARCHITECTURE_SPEC = {

    "step":
        "A41",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "temporal_window":
        4,

    "input_features":
        75,

    "feature_embed_dim":
        128,

    "gru_hidden_dim":
        128,

    "gru_num_layers":
        1,

    "projection_dim":
        64,

    "order_hidden_dim":
        128,

    "classifier_hidden_dim":
        64,

    "dropout":
        0.10,

    "encoder_parameters":
        ENCODER_PARAMETERS,

    "ssl_head_parameters":
        SSL_HEAD_PARAMETERS,

    "classifier_parameters":
        CLASSIFIER_PARAMETERS,

    "total_parameters":
        TOTAL_PARAMETERS,

    "same_architecture_family_as_T8":
        True,

    "model_training_performed":
        False
}


with open(
    ARCHITECTURE_PATH,
    "w",
    encoding="utf-8"
) as file:

    json.dump(
        ARCHITECTURE_SPEC,
        file,
        indent=4
    )


# ======================================================================
# 9 — FINAL VALIDATION
# ======================================================================

A41_VALID = bool(

    STEP_40_T4_GPU_TRAINING_READY

    and

    PARAMETER_COUNTS_VALID

    and

    SHAPES_VALID

    and

    OUTPUTS_FINITE

    and

    PROJECTION_NORMALIZATION_VALID

    and

    ARCHITECTURE_PATH.exists()
)


STEP_41_T4_MODEL_ARCHITECTURE_VALID = (
    A41_VALID
)


print("\n[5] Step A41 validation")
print("-" * 78)

print(
    "Temporal window                 :",
    TEMPORAL_WINDOW
)

print(
    "Input features                  :",
    INPUT_DIM
)

print(
    "Encoder parameters              :",
    f"{ENCODER_PARAMETERS:,}",
    "/ 109,056"
)

print(
    "SSL-head parameters             :",
    f"{SSL_HEAD_PARAMETERS:,}",
    "/ 58,049"
)

print(
    "Classifier parameters           :",
    f"{CLASSIFIER_PARAMETERS:,}",
    "/ 8,321"
)

print(
    "Total parameters                :",
    f"{TOTAL_PARAMETERS:,}",
    "/ 175,426"
)

print(
    "Parameter counts valid          :",
    PARAMETER_COUNTS_VALID
)

print(
    "Forward shapes valid            :",
    SHAPES_VALID
)

print(
    "Outputs finite                  :",
    OUTPUTS_FINITE
)

print(
    "Projection normalization valid  :",
    PROJECTION_NORMALIZATION_VALID
)

print(
    "Architecture backed up          :",
    ARCHITECTURE_PATH.exists()
)

print(
    "Model training performed        :",
    False
)


print("\n" + "=" * 78)

if A41_VALID:

    print(
        "✅ STEP A41 PASSED — "
        "the T=4 MOT-SSL-GRU architecture matches "
        "the verified T=8 architecture and is ready "
        "for SSL pretraining."
    )

else:

    print(
        "❌ STEP A41 FAILED — "
        "do not start SSL pretraining."
    )

print("=" * 78)

==============================================================================
STEP A41 — RESTORE + VERIFY T=4 MOT-SSL-GRU ARCHITECTURE
FOLD 1 | HELD-OUT FAMILY = DDoS
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A40-R GPU readiness: True
GPU: Tesla T4
Device: cuda

[2] Architecture configuration
------------------------------------------------------------------------------
Input features: 75
Temporal window: 4
Feature embedding: 128
GRU hidden dimension: 128
GRU layers: 1
Projection dimension: 64
Dropout: 0.1

[3] Creating architecture
------------------------------------------------------------------------------
Encoder parameters: 109,056
SSL-head parameters: 58,049
Classifier parameters: 8,321
Total parameters: 175,426

[4] Testing T=4 forward passes
------------------------------------------------------------------------------
Input shape: (256, 4, 75)
Representation shape: (256, 128)
Projection shape: (256, 64)
Classifier-logit shape: (256,)
Order-logit shape: (256,)
Outputs finite: True
Max projection norm error: 1.1920928955e-07

[5] Step A41 validation
------------------------------------------------------------------------------
Temporal window                 : 4
Input features                  : 75
Encoder parameters              : 109,056 / 109,056
SSL-head parameters             : 58,049 / 58,049
Classifier parameters           : 8,321 / 8,321
Total parameters                : 175,426 / 175,426
Parameter counts valid          : True
Forward shapes valid            : True
Outputs finite                  : True
Projection normalization valid  : True
Architecture backed up          : True
Model training performed        : False

==============================================================================
✅ STEP A41 PASSED — the T=4 MOT-SSL-GRU architecture matches the verified T=8 architecture and is ready for SSL pretraining.
==============================================================================

# Step A41.5 — Find the original A15-FIX code in your notebook

In [ ]:
# ======================================================================
# STEP A41.5
# FIND ORIGINAL A15-FIX SSL SOURCE CODE IN THE SAVED COLAB NOTEBOOK
# NO TRAINING
# ======================================================================

from pathlib import Path
import json

NOTEBOOK_PATH = Path(
    "/content/drive/MyDrive/"
    "SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb"
)

print("=" * 78)
print("STEP A41.5 — SEARCHING NOTEBOOK FOR ORIGINAL A15-FIX CODE")
print("=" * 78)

print("\nNotebook exists:", NOTEBOOK_PATH.exists())

if not NOTEBOOK_PATH.exists():
    raise RuntimeError(
        "Saved notebook was not found in the current Drive."
    )

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)


search_terms = [
    "A15-FIX",
    "nt_xent",
    "NT-Xent",
    "feature_mask",
    "jitter",
    "temporal_order",
    "lambda_t",
]


matching_cells = []

for cell_number, cell in enumerate(
    notebook.get("cells", [])
):

    if cell.get("cell_type") != "code":
        continue

    source = "".join(
        cell.get("source", [])
    )

    matched_terms = [
        term
        for term in search_terms
        if term.lower() in source.lower()
    ]

    if matched_terms:

        matching_cells.append(
            (
                cell_number,
                matched_terms,
                source
            )
        )


print(
    "\nMatching code cells:",
    len(matching_cells)
)

print("=" * 78)


for cell_number, terms, source in matching_cells:

    print()
    print(
        f"CODE CELL {cell_number} "
        f"| matches: {', '.join(terms)}"
    )

    print("-" * 78)

    # Print at most the first 120 lines of each matching cell.
    lines = source.splitlines()

    for line in lines[:120]:
        print(line)

    if len(lines) > 120:
        print(
            f"... [{len(lines) - 120} more lines not shown]"
        )

    print("=" * 78)

==============================================================================
STEP A41.5 — SEARCHING NOTEBOOK FOR ORIGINAL A15-FIX CODE
==============================================================================

Notebook exists: True

Matching code cells: 0
==============================================================================

In [ ]:
# ======================================================================
# STEP A41.6
# UPLOAD + LOCATE ORIGINAL SSL TRAINING CODE
#
# NO MODEL TRAINING
# ======================================================================

from google.colab import files
from pathlib import Path
import json

print("=" * 78)
print("STEP A41.6 — UPLOAD ORIGINAL NOTEBOOK")
print("=" * 78)

print(
    "\nChoose the ORIGINAL "
    "SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb "
    "that you just downloaded."
)

# ----------------------------------------------------------------------
# 1 — Upload original notebook
# ----------------------------------------------------------------------

uploaded = files.upload()

ipynb_files = [
    name
    for name in uploaded.keys()
    if name.lower().endswith(".ipynb")
]

if len(ipynb_files) != 1:
    raise RuntimeError(
        "Please upload exactly ONE .ipynb notebook."
    )

ORIGINAL_NOTEBOOK = Path(
    "/content"
) / ipynb_files[0]

print("\nUploaded notebook:")
print(ORIGINAL_NOTEBOOK)


# ----------------------------------------------------------------------
# 2 — Read notebook
# ----------------------------------------------------------------------

with open(
    ORIGINAL_NOTEBOOK,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

cells = notebook.get(
    "cells",
    []
)

print(
    "\nTotal notebook cells:",
    len(cells)
)


# ----------------------------------------------------------------------
# 3 — Broad search for SSL-related code
# ----------------------------------------------------------------------

search_terms = [

    # SSL / contrastive
    "nt_xent",
    "nt-xent",
    "contrastive",
    "temperature",

    # augmentation
    "jitter",
    "mask",
    "augmentation",

    # model heads
    "projection_head",
    "temporal_order",
    "order_head",

    # optimization
    "optimizer",
    "adam",
    "clip_grad_norm",

    # common training wording
    "ssl",
    "pretrain",
    "epoch",

    # model
    "MOTSSLGRU",
]


matches = []

for cell_index, cell in enumerate(cells):

    if cell.get("cell_type") != "code":
        continue

    source = "".join(
        cell.get(
            "source",
            []
        )
    )

    lower_source = source.lower()

    matched_terms = [
        term
        for term in search_terms
        if term.lower() in lower_source
    ]

    if matched_terms:

        matches.append(
            {
                "cell_index": cell_index,
                "terms": matched_terms,
                "source": source
            }
        )


# ----------------------------------------------------------------------
# 4 — Show compact results only
# ----------------------------------------------------------------------

print("\n" + "=" * 78)
print("SSL-RELATED CODE CELLS FOUND:", len(matches))
print("=" * 78)


for result in matches:

    cell_index = result[
        "cell_index"
    ]

    terms = result[
        "terms"
    ]

    source = result[
        "source"
    ]

    lines = [
        line
        for line in source.splitlines()
        if line.strip()
    ]

    print()
    print(
        f"CODE CELL {cell_index}"
    )

    print(
        "Matched terms:",
        ", ".join(terms)
    )

    print("-" * 78)

    # Only preview first 15 non-empty lines.
    for line in lines[:15]:
        print(line)

    if len(lines) > 15:
        print(
            f"... [{len(lines) - 15} additional lines]"
        )

    print("-" * 78)


print()
print("=" * 78)

if len(matches) > 0:

    print(
        "✅ ORIGINAL NOTEBOOK SEARCH COMPLETED"
    )

    print(
        "Do NOT run any of the old notebook cells yet."
    )

else:

    print(
        "❌ NO SSL-RELATED CODE WAS FOUND"
    )

print("=" * 78)

==============================================================================
STEP A41.6 — UPLOAD ORIGINAL NOTEBOOK
==============================================================================

Choose the ORIGINAL SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb that you just downloaded.

Saving SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb to SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb

Uploaded notebook:
/content/SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb

Total notebook cells: 30

==============================================================================
SSL-RELATED CODE CELLS FOUND: 6
==============================================================================

CODE CELL 2
Matched terms: ssl, epoch
------------------------------------------------------------------------------
#@markdown ### Run mode
FAST_MODE = False  #@param {type:"boolean"}
#@markdown FAST_MODE = quick pipeline check (2 families, 1 seed, ~2 epochs, small data). Not a valid research result.
#@markdown Uncheck for FULL_MODE = real strict LOAFO protocol (7 families, configurable seeds/epochs).
#@markdown ### FULL_MODE protocol settings (ignored in FAST_MODE)
NUM_SEEDS = 5              #@param {type:"slider", min:1, max:5, step:1}
SSL_EPOCHS = 30            #@param {type:"integer"}
FT_EPOCHS = 20             #@param {type:"integer"}
BATCH_SIZE = 256           #@param {type:"integer"}
WINDOW = 8                 #@param {type:"integer"}
STRIDE = 8                 #@param {type:"integer"}
MAX_WINDOWS_PER_FAMILY = 50000  #@param {type:"integer"}
#@markdown ### Dataset
#@markdown Leave blank to let the notebook auto-download the project's documented
#@markdown timestamp-preserving Hugging Face mirror (`somnath0100/CICIoT2023Small`).
... [32 additional lines]
------------------------------------------------------------------------------

CODE CELL 16
Matched terms: mask, ssl, pretrain
------------------------------------------------------------------------------
import numpy as np
if check_halt():
    pass
else:
    sample = run_loafo.load_data(Path(DATA_DIR))
    print(f"Loaded {len(sample):,} raw rows for inspection.")
    data, label_col, ts_col, capture_col, feature_cols = run_loafo.clean_and_label(sample)
    print(f"Label column: {label_col} | Timestamp column: {ts_col} | Capture column: {capture_col}")
    print(f"Numeric feature columns detected: {len(feature_cols)}")
    missing_pct = sample[feature_cols].apply(lambda c: pd.to_numeric(c, errors="coerce").isna().mean() * 100) \
        if set(feature_cols).issubset(sample.columns) else None
    print("\nFamily / class distribution:")
    print(data["__family"].value_counts())
    if missing_pct is not None:
        worst = missing_pct.sort_values(ascending=False).head(10)
... [23 additional lines]
------------------------------------------------------------------------------

CODE CELL 19
Matched terms: ssl, epoch
------------------------------------------------------------------------------
import time
if check_halt():
    pass
else:
    run_stamp = time.strftime("%Y%m%d_%H%M%S")
    RESULTS_DIR = Path(f"/content/results_run_{run_stamp}")
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    argv = ["--data", str(DATA_DIR), "--output", str(RESULTS_DIR)]
    if FAST_MODE:
        argv += ["--smoke-test"]
        print("Running FAST_MODE (--smoke-test): pipeline verification only, NOT a valid research result.")
    else:
        argv += ["--families", *ALL_FAMILIES,
                  "--seeds", *[str(s) for s in SEEDS],
                  "--window", str(WINDOW), "--stride", str(STRIDE),
... [16 additional lines]
------------------------------------------------------------------------------

CODE CELL 25
Matched terms: ssl
------------------------------------------------------------------------------
if check_halt():
    pass
else:
    model_dir = RESULTS_DIR / "models"
    checkpoints = sorted(model_dir.glob("ssl_gru_holdout_*.pt")) if model_dir.exists() else []
    if not checkpoints:
        print("No saved checkpoints found (none were produced by this run) — skipping demo inference.")
    else:
        ckpt = checkpoints[0]
        heldout_name = ckpt.stem.replace("ssl_gru_holdout_", "")
        candidate_csvs = [p for p in Path(DATA_DIR).rglob("*.csv") if heldout_name.lower() in p.name.lower()
                          or heldout_name.lower() in p.parent.name.lower()]
        if not candidate_csvs:
            candidate_csvs = list(Path(DATA_DIR).rglob("*.csv"))[:1]
        if not candidate_csvs:
... [14 additional lines]
------------------------------------------------------------------------------

CODE CELL 27
Matched terms: ssl
------------------------------------------------------------------------------
if check_halt():
    pass
else:
    FAMILIES_REQ = run_loafo.FAMILIES
    SEEDS_REQ = ALL_SEEDS if not FAST_MODE else SEEDS
    MODELS_REQ = ["Logistic Regression", "Random Forest", "XGBoost", "MLP", "Autoencoder",
                  "Supervised GRU", "SSL + Mean Pooling", "SSL-GRU No Crop", "Proposed SSL-GRU"]
    issues = []
    def ok(msg): print("[PASS]", msg)
    def fail(msg): print("[FAIL]", msg); issues.append(msg)
    required_files = ["fold_metrics.csv", "overall_metrics.csv", "family_zero_day_recall.csv",
                       "family_zero_day_recall_summary.csv", "results.json", "results.tex",
                       "confusion_matrix_hardest.png", "zero_day_recall_by_family.png",
                       "overall_zero_day_recall.png"]
    for name in required_files:
... [35 additional lines]
------------------------------------------------------------------------------

CODE CELL 29
Matched terms: ssl
------------------------------------------------------------------------------
if check_halt():
    pass
else:
    import shutil as _shutil
    package_dir = Path(f"/content/final_package_{run_stamp}")
    package_dir.mkdir(exist_ok=True)
    _shutil.copytree(RESULTS_DIR, package_dir / RESULTS_DIR.name, dirs_exist_ok=True)
    if manifest_path.exists():
        _shutil.copy2(manifest_path, package_dir / "dataset_manifest.csv")
    final_zip = Path(f"/content/SSL_GRU_LOAFO_results_{run_stamp}.zip")
    if final_zip.exists():
        final_zip.unlink()
    _shutil.make_archive(str(final_zip.with_suffix("")), "zip", package_dir)
    print("Final results ZIP created:", final_zip, f"({final_zip.stat().st_size / 1e6:.1f} MB)")
    try:
... [4 additional lines]
------------------------------------------------------------------------------

==============================================================================
✅ ORIGINAL NOTEBOOK SEARCH COMPLETED
Do NOT run any of the old notebook cells yet.
==============================================================================

In [ ]:
# ======================================================================
# STEP A41.7
# FIND WHERE run_loafo.py CAME FROM
# NO TRAINING
# ======================================================================

from pathlib import Path
import json

NOTEBOOK_PATH = Path(
    "/content/SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb"
)

print("=" * 78)
print("STEP A41.7 — SEARCHING ORIGINAL NOTEBOOK FOR run_loafo SOURCE")
print("=" * 78)

if not NOTEBOOK_PATH.exists():
    raise RuntimeError(
        "Original uploaded notebook is no longer in /content."
    )

with open(
    NOTEBOOK_PATH,
    "r",
    encoding="utf-8"
) as f:
    notebook = json.load(f)

search_terms = [
    "run_loafo",
    "wget",
    "curl",
    "git clone",
    "github",
    "raw.githubusercontent",
    "%run",
    "importlib",
    "writefile",
]

matches = []

for i, cell in enumerate(notebook.get("cells", [])):

    source = "".join(
        cell.get("source", [])
    )

    source_lower = source.lower()

    matched = [
        term
        for term in search_terms
        if term.lower() in source_lower
    ]

    if matched:
        matches.append(
            (i, cell.get("cell_type"), matched, source)
        )

print("\nMatching cells:", len(matches))
print("=" * 78)

for i, cell_type, matched, source in matches:

    print()
    print(
        f"CELL {i} | type={cell_type} | "
        f"matches={', '.join(matched)}"
    )
    print("-" * 78)

    print(source)

    print("=" * 78)

print()

if matches:
    print("✅ SEARCH COMPLETED")
else:
    print("❌ No reference to run_loafo was found.")

==============================================================================
STEP A41.7 — SEARCHING ORIGINAL NOTEBOOK FOR run_loafo SOURCE
==============================================================================

Matching cells: 10
==============================================================================

CELL 0 | type=markdown | matches=run_loafo
------------------------------------------------------------------------------
# Self-Supervised Temporal Learning for Zero-Day IoT Intrusion Detection (SSL-GRU)
### LOAFO training notebook — CICIoT2023 Faculty Evidence Package

**What this notebook does, top to bottom:**
1. Installs dependencies, extracts your project ZIP, auto-locates the real project code.
2. Verifies the dataset (timestamp column, label column, hashes, missing values).
3. Runs a genuine **leakage check** using the project's own fold-preparation code.
4. Runs the **strict Leave-One-Attack-Family-Out (LOAFO)** protocol from `TRAINING_PROTOCOL.md`, training the SSL-GRU model and all mandatory/ablation baselines.
5. Computes Precision, Recall, F1, ROC-AUC, PR-AUC, FPR and Zero-Day Recall; builds confusion matrices and comparison charts.
6. Saves checkpoints, logs, and CSV results, then zips everything for download.

## ⚠️ Academic-integrity guardrails (please read)
This notebook **reuses the project's own scripts unmodified** (`run_loafo.py`, `verify_dataset.py`, `demo_predict.py`) rather than re-implementing the pipeline, so results are traceable to the code you audited.

- It will **not** invent a timestamp column or a temporal order. If no real timestamp-preserving CICIoT2023 export is found or downloadable, the notebook **stops** and tells you exactly what dataset is required — it does not fall back to synthetic data.
- `RESULTS/software_validation/*` in your ZIP is explicitly marked `NOT_PAPER_RESULTS` by the project authors (synthetic smoke-test only). This notebook **ignores that folder entirely** and always writes new results to a fresh, timestamped `results_run_*` directory.
- `--smoke-test` / `FAST_MODE` runs are for **pipeline verification only** (2 families, 1 seed, ~2 epochs). They are clearly labeled as **not valid scientific results**, exactly as the project's own `run_loafo.py` docstring states.
- The held-out family in every LOAFO fold is removed **before** preprocessing statistics are fit, before SSL pretraining, and before supervised training — enforced by the project's own `prepare_fold()` function, which this notebook calls directly and also sanity-checks with assertions (Cell: *Leakage self-check*).

## How to run
1. Runtime → Change runtime type → **GPU** (T4 is fine).
2. Run All (`Runtime → Run all`).
3. When prompted, upload your project ZIP (the one containing `TRAINING/run_loafo.py`, `DATASET/…`, `CODE/verify_dataset.py`).
4. If you already have a **real, timestamp-preserving CICIoT2023 export**, upload/mount it and set `CUSTOM_DATASET_DIR` in the Config cell — this is strongly recommended for genuine paper-grade results. Otherwise the notebook will try to fetch the project's documented timestamp-preserving Hugging Face mirror automatically.
5. Read the printed messages at each step — the notebook explains what it is doing and will clearly say **STOP** if a real dataset isn't available.

==============================================================================

CELL 7 | type=markdown | matches=run_loafo
------------------------------------------------------------------------------
## 4. Upload and locate the project
Upload the ZIP you described (containing `TRAINING/run_loafo.py`, `DATASET/...`, `CODE/verify_dataset.py`). The ZIP may contain nested ZIPs — this cell extracts recursively and automatically finds the real project root, wherever it is nested.
==============================================================================

CELL 8 | type=code | matches=run_loafo
------------------------------------------------------------------------------
import os, zipfile, shutil
from pathlib import Path

WORKDIR = Path("/content/project_extracted")
if WORKDIR.exists():
    shutil.rmtree(WORKDIR)
WORKDIR.mkdir(parents=True)

zip_path = PROJECT_ZIP_PATH.strip()
if not zip_path:
    try:
        from google.colab import files
        print("Please upload your project ZIP file...")
        uploaded = files.upload()
        zip_path = list(uploaded.keys())[0]
    except ImportError:
        raise RuntimeError("Not running in Colab and no PROJECT_ZIP_PATH given — set PROJECT_ZIP_PATH in the config cell.")

print("Using ZIP:", zip_path)

def extract_recursive(root: Path):
    """Extract zip_path and any nested .zip files found inside, repeatedly, until none remain."""
    seen = set()
    pending = [Path(zip_path)]
    first = True
    while pending:
        z = pending.pop()
        if str(z) in seen or not z.exists():
            continue
        seen.add(str(z))
        target = root if first else root / (z.stem + "__unzipped")
        first = False
        target.mkdir(parents=True, exist_ok=True)
        try:
            with zipfile.ZipFile(z, "r") as zf:
                zf.extractall(target)
        except zipfile.BadZipFile:
            continue
        for p in target.rglob("*.zip"):
            pending.append(p)

extract_recursive(WORKDIR)

# Auto-locate the real project root: the directory whose child "TRAINING" contains run_loafo.py.
candidates = list(WORKDIR.rglob("run_loafo.py"))
if not candidates:
    raise FileNotFoundError(
        "Could not find TRAINING/run_loafo.py anywhere in the uploaded ZIP (including nested ZIPs). "
        "Please double-check the ZIP contains the CICIoT2023_Faculty_Evidence_Package / TRAINING folder."
    )
RUN_LOAFO_PATH = sorted(candidates, key=lambda p: len(p.parts))[0]
PROJECT_ROOT = RUN_LOAFO_PATH.parent.parent
print("Detected project root:", PROJECT_ROOT)
print("\nProject root contents:")
for p in sorted(PROJECT_ROOT.iterdir()):
    print(" -", p.name)

TRAINING_DIR = PROJECT_ROOT / "TRAINING"
DATASET_DIR = PROJECT_ROOT / "DATASET"
CODE_DIR = PROJECT_ROOT / "CODE"
for required, label in [(TRAINING_DIR / "run_loafo.py", "TRAINING/run_loafo.py"),
                         (TRAINING_DIR / "requirements.txt", "TRAINING/requirements.txt"),
                         (TRAINING_DIR / "TRAINING_PROTOCOL.md", "TRAINING/TRAINING_PROTOCOL.md"),
                         (TRAINING_DIR / "demo_predict.py", "TRAINING/demo_predict.py"),
                         (TRAINING_DIR / "preflight_submission.py", "TRAINING/preflight_submission.py"),
                         (DATASET_DIR / "attack_family_mapping.csv", "DATASET/attack_family_mapping.csv"),
                         (DATASET_DIR / "feature_dictionary.csv", "DATASET/feature_dictionary.csv"),
                         (CODE_DIR / "verify_dataset.py", "CODE/verify_dataset.py")]:
    status = "OK" if required.exists() else "MISSING"
    print(f"[{status}] {label}")

==============================================================================

CELL 10 | type=code | matches=run_loafo, importlib
------------------------------------------------------------------------------
req_file = TRAINING_DIR / "requirements.txt"
lines = [l.strip() for l in req_file.read_text().splitlines() if l.strip() and not l.strip().startswith("#")]
to_install = [l for l in lines if not l.lower().startswith("torch")]
print("Installing (from project requirements.txt, skipping torch):", to_install)
pip_install(to_install)

import sys
for p in [str(TRAINING_DIR), str(CODE_DIR)]:
    if p not in sys.path:
        sys.path.insert(0, p)

import importlib
run_loafo = importlib.import_module("run_loafo")
print("Loaded run_loafo.py OK. Families known to the project:", run_loafo.FAMILIES)

==============================================================================

CELL 15 | type=markdown | matches=run_loafo
------------------------------------------------------------------------------
## 8. Missing-value, feature, and leakage checks
Uses the project's own `clean_and_label()` / `prepare_fold()` functions from `run_loafo.py` directly (not a re-implementation), so the leakage check reflects the code that will actually train the models.
==============================================================================

CELL 16 | type=code | matches=run_loafo
------------------------------------------------------------------------------
import numpy as np

if check_halt():
    pass
else:
    sample = run_loafo.load_data(Path(DATA_DIR))
    print(f"Loaded {len(sample):,} raw rows for inspection.")

    data, label_col, ts_col, capture_col, feature_cols = run_loafo.clean_and_label(sample)
    print(f"Label column: {label_col} | Timestamp column: {ts_col} | Capture column: {capture_col}")
    print(f"Numeric feature columns detected: {len(feature_cols)}")

    missing_pct = sample[feature_cols].apply(lambda c: pd.to_numeric(c, errors="coerce").isna().mean() * 100) \
        if set(feature_cols).issubset(sample.columns) else None
    print("\nFamily / class distribution:")
    print(data["__family"].value_counts())

    if missing_pct is not None:
        worst = missing_pct.sort_values(ascending=False).head(10)
        print("\nTop-10 features by missing-value percentage (imputed with TRAIN-ONLY medians during real training):")
        print(worst.round(2))

    # --- Leakage self-check: does prepare_fold() truly exclude the held-out family from train/val? ---
    heldout_probe = [f for f in run_loafo.FAMILIES if f in set(data["__family"])]
    if not heldout_probe:
        halt("None of the expected attack families "
             f"({run_loafo.FAMILIES}) were found after label mapping — check attack_family_mapping.csv "
             "against the labels actually present in your dataset.")
    else:
        probe_family = heldout_probe[0]
        prep = run_loafo.prepare_fold(data, feature_cols, probe_family, WINDOW, STRIDE,
                                       MAX_WINDOWS_PER_FAMILY, seed=SEEDS[0])
        leaked_train = bool(np.isin(probe_family, prep.train_family).any()) if len(prep.train_family) else False
        leaked_val = bool(np.isin(probe_family, prep.val_family).any()) if len(prep.val_family) else False
        assert not leaked_train, f"LEAKAGE DETECTED: held-out family {probe_family} appears in the training split!"
        assert not leaked_val, f"LEAKAGE DETECTED: held-out family {probe_family} appears in the validation split!"
        assert prep.zd_mask.sum() > 0, f"No zero-day/test windows were produced for held-out family {probe_family}."
        print(f"\nLeakage self-check PASSED for probe family '{probe_family}': "
              f"0 held-out-family windows in train ({len(prep.train_y)} windows) or val ({len(prep.val_y)} windows); "
              f"{int(prep.zd_mask.sum())} zero-day windows correctly isolated to test.")
        print("This is enforced by the project's own prepare_fold()/assign_partitions() functions, which remove "
              "the held-out family before preprocessing statistics are fit, before SSL pretraining, and before "
              "supervised training.")

==============================================================================

CELL 17 | type=markdown | matches=run_loafo
------------------------------------------------------------------------------
## 9. Run the strict LOAFO protocol (`TRAINING/run_loafo.py`)

- **FAST_MODE**: calls the script with `--smoke-test` (2 families, 1 seed, ≤2 epochs, small data) — a pipeline
  sanity check only, exactly as the project's own docstring describes. Results are clearly labeled as not valid
  research results.
- **FULL_MODE**: runs all 7 LOAFO families with your configured seeds/epochs, training every mandatory baseline
  (Logistic Regression, Random Forest, XGBoost, MLP, Autoencoder), the research controls (Supervised GRU,
  SSL + Mean Pooling, SSL-GRU No Crop), and the proposed SSL-GRU model — matching `TRAINING_PROTOCOL.md`.

Results never land in the old `RESULTS/software_validation` folder — every run gets a fresh, timestamped
output directory so old (synthetic) results can never be mistaken for a new run.

==============================================================================

CELL 18 | type=code | matches=run_loafo
------------------------------------------------------------------------------
from pathlib import Path

print("=" * 70)
print("SEARCHING FOR TRAINING FILES")
print("=" * 70)

run_files = list(Path("/content").rglob("run_loafo.py"))

if run_files:
    print("\n✅ Found run_loafo.py:\n")

    for i, path in enumerate(run_files, start=1):
        print(f"{i}. {path}")

else:
    print("\n❌ run_loafo.py was NOT found.")

print("\n" + "=" * 70)

zip_files = list(Path("/content").rglob("*.zip"))

print("ZIP FILES CURRENTLY IN COLAB:\n")

if zip_files:
    for i, path in enumerate(zip_files, start=1):
        print(f"{i}. {path}")
else:
    print("No ZIP files found.")

print("=" * 70)
==============================================================================

CELL 19 | type=code | matches=run_loafo
------------------------------------------------------------------------------
import time

if check_halt():
    pass
else:
    run_stamp = time.strftime("%Y%m%d_%H%M%S")
    RESULTS_DIR = Path(f"/content/results_run_{run_stamp}")
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    argv = ["--data", str(DATA_DIR), "--output", str(RESULTS_DIR)]
    if FAST_MODE:
        argv += ["--smoke-test"]
        print("Running FAST_MODE (--smoke-test): pipeline verification only, NOT a valid research result.")
    else:
        argv += ["--families", *ALL_FAMILIES,
                  "--seeds", *[str(s) for s in SEEDS],
                  "--window", str(WINDOW), "--stride", str(STRIDE),
                  "--ssl-epochs", str(SSL_EPOCHS), "--ft-epochs", str(FT_EPOCHS),
                  "--batch", str(BATCH_SIZE),
                  "--max-windows-per-family", str(MAX_WINDOWS_PER_FAMILY)]
        print("Running FULL_MODE — strict LOAFO protocol. This can take a long time "
              "(hours) depending on dataset size, seeds, and epochs.")

    print("\nEffective arguments:", argv)
    args = run_loafo.build_argparser().parse_args(argv)
    if getattr(args, "max_windows_per_family", None) == 0:
        args.max_windows_per_family = None

    try:
        run_loafo.run(args)
        print("\nTraining complete. Results written to:", RESULTS_DIR)
    except Exception as e:
        halt(f"run_loafo.run() raised an error during training/evaluation:\n{type(e).__name__}: {e}\n\n"
             "Common causes: dataset too small/imbalanced for the requested window size, out-of-memory "
             "(try a smaller BATCH_SIZE or MAX_WINDOWS_PER_FAMILY), or a missing required family in the data.")

==============================================================================

CELL 27 | type=code | matches=run_loafo
------------------------------------------------------------------------------
if check_halt():
    pass
else:
    FAMILIES_REQ = run_loafo.FAMILIES
    SEEDS_REQ = ALL_SEEDS if not FAST_MODE else SEEDS
    MODELS_REQ = ["Logistic Regression", "Random Forest", "XGBoost", "MLP", "Autoencoder",
                  "Supervised GRU", "SSL + Mean Pooling", "SSL-GRU No Crop", "Proposed SSL-GRU"]

    issues = []
    def ok(msg): print("[PASS]", msg)
    def fail(msg): print("[FAIL]", msg); issues.append(msg)

    required_files = ["fold_metrics.csv", "overall_metrics.csv", "family_zero_day_recall.csv",
                       "family_zero_day_recall_summary.csv", "results.json", "results.tex",
                       "confusion_matrix_hardest.png", "zero_day_recall_by_family.png",
                       "overall_zero_day_recall.png"]
    for name in required_files:
        p = RESULTS_DIR / name
        ok(f"Found {name}") if p.exists() and p.stat().st_size > 0 else fail(f"Missing/empty {name}")

    rjson_path = RESULTS_DIR / "results.json"
    if rjson_path.exists():
        blob = rjson_path.read_text().lower()
        bad = [x for x in ["smoke", "synthetic_temporal_smoke"] if x in blob]
        if bad and not FAST_MODE:
            fail("results.json mentions smoke/synthetic markers in a FULL_MODE run: " + ", ".join(bad))
        elif bad and FAST_MODE:
            ok("results.json correctly reflects a FAST_MODE smoke-test run")
        else:
            ok("results.json has no smoke/synthetic markers")

    fold_path = RESULTS_DIR / "fold_metrics.csv"
    if fold_path.exists():
        fdf = pd.read_csv(fold_path)
        families_found = set(fdf["heldout_family"].unique())
        seeds_found = set(int(s) for s in fdf["seed"].unique())
        models_found = set(fdf["model"].unique())
        if not FAST_MODE:
            (ok if families_found == set(FAMILIES_REQ) else fail)(f"Family coverage: {sorted(families_found)}")
            (ok if seeds_found == set(SEEDS_REQ) else fail)(f"Seed coverage: {sorted(seeds_found)}")
        missing_models = [m for m in MODELS_REQ if m not in models_found]
        (ok("All required model rows present") if not missing_models
         else fail(f"Missing model rows: {missing_models}"))
        metric_cols = [c for c in ["precision", "recall", "f1", "roc_auc", "pr_auc", "fpr", "zd_recall"] if c in fdf]
        bad_range = [c for c in metric_cols
                     if pd.to_numeric(fdf[c], errors="coerce").between(-1e-9, 1 + 1e-9).all() is False]
        (ok("All metric values within [0,1]") if not bad_range else fail(f"Out-of-range metrics in: {bad_range}"))

    print("\n=== VERDICT ===")
    if issues:
        print(f"{len(issues)} issue(s) found — see [FAIL] lines above.")
    elif FAST_MODE:
        print("Pipeline sanity check passed. Re-run with FAST_MODE unchecked for real results.")
    else:
        print("All integrity checks passed for a full-protocol run.")

==============================================================================

✅ SEARCH COMPLETED

In [ ]:
# ======================================================================
# STEP A41.8
# LOCK WINDOW-SENSITIVITY IMPLEMENTATION POLICY
# NO TRAINING
# ======================================================================

from pathlib import Path
import json

POLICY_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/fold_01_DDoS"
)

POLICY_DIR.mkdir(
    parents=True,
    exist_ok=True
)

POLICY_PATH = (
    POLICY_DIR
    / "window_size_ssl_implementation_policy.json"
)

policy = {

    "step": "A41.8",

    "fold_id": 1,

    "held_out_family": "DDoS",

    "window_candidates": [4, 8, 16],

    "seed": 13,

    "lambda_t": 0.25,

    "imbalance_method": "none",

    "ssl_epochs": 30,

    "fine_tune_epochs": 20,

    "batch_size": 256,

    "learning_rate": 0.001,

    "temperature": 0.2,

    "feature_mask_probability": 0.1,

    "gaussian_jitter_std": 0.01,

    "precision": "float32",

    "gradient_clip_norm": 5.0,

    "old_run_loafo_source_available": False,

    "sensitivity_rule":
        "T=4, T=8, and T=16 must use the same newly frozen "
        "SSL implementation for a controlled window-size comparison.",

    "existing_T8_fold_result":
        "Retained unchanged as the existing Fold-1 result.",

    "existing_T8_sensitivity_use":
        "Do not directly reuse as the controlled sensitivity comparator; "
        "rerun T=8 later using the same frozen sensitivity implementation.",

    "test_or_zero_day_used_for_this_decision": False
}

with open(
    POLICY_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        policy,
        f,
        indent=4
    )


STEP_41_8_SENSITIVITY_POLICY_VALID = (
    POLICY_PATH.exists()
)

print("=" * 78)
print("STEP A41.8 — WINDOW-SENSITIVITY IMPLEMENTATION POLICY")
print("=" * 78)

print("Policy saved:", POLICY_PATH.exists())
print("Window candidates:", [4, 8, 16])
print("lambda_t frozen:", 0.25)
print("Imbalance method frozen:", "none")
print("Seed:", 13)
print("Old run_loafo source available:", False)
print("Test/zero-day used:", False)

print()

if STEP_41_8_SENSITIVITY_POLICY_VALID:

    print(
        "✅ STEP A41.8 PASSED — "
        "controlled window-size implementation policy is frozen."
    )

else:

    print(
        "❌ STEP A41.8 FAILED"
    )

print("=" * 78)

==============================================================================
STEP A41.8 — WINDOW-SENSITIVITY IMPLEMENTATION POLICY
==============================================================================
Policy saved: True
Window candidates: [4, 8, 16]
lambda_t frozen: 0.25
Imbalance method frozen: none
Seed: 13
Old run_loafo source available: False
Test/zero-day used: False

✅ STEP A41.8 PASSED — controlled window-size implementation policy is frozen.
==============================================================================

# Step A42 — T=4 SSL pretraining

In [ ]:
# ======================================================================
# STEP A42
# T=4 CONTROLLED WINDOW-SENSITIVITY SSL PRETRAINING
#
# Fold 1: DDoS held out
# T = 4
# Seed = 13
# lambda_t = 0.25
#
# Newly frozen sensitivity implementation:
#   - two independently augmented views
#   - NT-Xent contrastive objective
#   - temporal-order objective:
#       split window into first/second temporal halves
#       randomly present correct/reversed order
#   - FP32 only
#
# CHECKPOINT SAVED TO DRIVE AFTER EVERY EPOCH
# ======================================================================

from pathlib import Path
import os
import json
import time
import random
import hashlib
import shutil

import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A42 — T=4 CONTROLLED SSL PRETRAINING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS | SEED = 13")
print("=" * 78)


# ======================================================================
# 1 — PREREQUISITE CHECKS
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_globals = [
    "STEP_40_T4_GPU_TRAINING_READY",
    "STEP_41_T4_MODEL_ARCHITECTURE_VALID",
    "STEP_41_8_SENSITIVITY_POLICY_VALID",
    "T4_TRAIN_DATASET",
    "MOTSSLGRU",
]

for name in required_globals:
    if name not in globals():
        raise RuntimeError(
            f"Required state missing: {name}"
        )


if not STEP_40_T4_GPU_TRAINING_READY:
    raise RuntimeError("A40-R did not pass.")

if not STEP_41_T4_MODEL_ARCHITECTURE_VALID:
    raise RuntimeError("A41 did not pass.")

if not STEP_41_8_SENSITIVITY_POLICY_VALID:
    raise RuntimeError("A41.8 did not pass.")

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA is unavailable. "
        "Do not run A42 without T4 GPU."
    )


DEVICE = torch.device("cuda")
GPU_NAME = torch.cuda.get_device_name(0)


print("A40-R valid:", STEP_40_T4_GPU_TRAINING_READY)
print("A41 valid:", STEP_41_T4_MODEL_ARCHITECTURE_VALID)
print("A41.8 valid:", STEP_41_8_SENSITIVITY_POLICY_VALID)
print("Training windows:", f"{len(T4_TRAIN_DATASET):,}")
print("GPU:", GPU_NAME)
print("Device:", DEVICE)


if len(T4_TRAIN_DATASET) != 119_285:
    raise RuntimeError(
        "Expected exactly 119,285 T=4 training windows."
    )


# ======================================================================
# 2 — FROZEN CONFIGURATION
# ======================================================================

SEED = 13

TEMPORAL_WINDOW = 4

SSL_EPOCHS = 30
BATCH_SIZE = 256
LEARNING_RATE = 1e-3

TEMPERATURE = 0.20
LAMBDA_T = 0.25

MASK_PROBABILITY = 0.10
JITTER_STD = 0.01

GRADIENT_CLIP_NORM = 5.0


print("\n[2] Frozen sensitivity configuration")
print("-" * 78)

print("Window size:", TEMPORAL_WINDOW)
print("Seed:", SEED)
print("Epochs:", SSL_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Temperature:", TEMPERATURE)
print("lambda_t:", LAMBDA_T)
print("Feature masking:", MASK_PROBABILITY)
print("Gaussian jitter:", JITTER_STD)
print("Gradient clipping:", GRADIENT_CLIP_NORM)
print("Precision: float32")
print("Binary labels used in SSL: False")


# ======================================================================
# 3 — FREEZE EXACT SENSITIVITY IMPLEMENTATION SPECIFICATION
# ======================================================================

IMPLEMENTATION_SPEC = {

    "implementation_version":
        "window_sensitivity_ssl_v1",

    "contrastive_views":
        "two independent augmented views of each complete window",

    "augmentation":
        {
            "feature_mask_probability": 0.10,
            "gaussian_jitter_std": 0.01,
            "operation_order": "jitter_then_mask"
        },

    "contrastive_loss":
        "symmetric 2N NT-Xent with in-batch negatives",

    "temperature":
        0.20,

    "temporal_order_task":
        (
            "split complete window into equal first and second temporal "
            "halves; randomly present halves in correct or reversed order"
        ),

    "temporal_order_loss":
        "binary_cross_entropy_with_logits",

    "lambda_t":
        0.25,

    "total_loss":
        "NT_Xent + lambda_t * temporal_order_BCE",

    "precision":
        "float32",

    "optimizer":
        "Adam",

    "learning_rate":
        0.001,

    "gradient_clip_norm":
        5.0,

    "classifier_optimized":
        False,

    "binary_labels_used":
        False,

    "window_candidates_required_to_reuse_this_implementation":
        [4, 8, 16]
}


IMPLEMENTATION_JSON = json.dumps(
    IMPLEMENTATION_SPEC,
    sort_keys=True
)


IMPLEMENTATION_HASH = hashlib.sha256(
    IMPLEMENTATION_JSON.encode("utf-8")
).hexdigest()


print("\nImplementation version:",
      IMPLEMENTATION_SPEC["implementation_version"])

print("Implementation SHA256:",
      IMPLEMENTATION_HASH)


# ======================================================================
# 4 — OUTPUT / CHECKPOINT DIRECTORY
# ======================================================================

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/"
    "fold_01_DDoS/T4/"
    "ssl_pretraining/seed_13"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


CHECKPOINT_PATH = (
    OUTPUT_DIR
    / "A42_T4_SSL_latest_checkpoint.pt"
)

FINAL_MODEL_PATH = (
    OUTPUT_DIR
    / "A42_T4_SSL_final.pt"
)

HISTORY_PATH = (
    OUTPUT_DIR
    / "A42_T4_SSL_history.csv"
)

SPEC_PATH = (
    OUTPUT_DIR
    / "A42_T4_SSL_implementation.json"
)

SUMMARY_PATH = (
    OUTPUT_DIR
    / "A42_T4_SSL_summary.json"
)


with open(
    SPEC_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        {
            **IMPLEMENTATION_SPEC,
            "implementation_sha256":
                IMPLEMENTATION_HASH
        },
        f,
        indent=4
    )


print("\n[3] Drive backup")
print("-" * 78)
print("Output directory:", OUTPUT_DIR)
print("Implementation spec saved:", SPEC_PATH.exists())


# ======================================================================
# 5 — REPRODUCIBILITY
# ======================================================================

def set_global_seed(seed):

    random.seed(seed)

    np.random.seed(seed)

    torch.manual_seed(seed)

    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


set_global_seed(SEED)


# Separate generator controls only DataLoader shuffling.

LOADER_GENERATOR = torch.Generator()
LOADER_GENERATOR.manual_seed(SEED)


T4_SSL_LOADER = DataLoader(

    T4_TRAIN_DATASET,

    batch_size=BATCH_SIZE,

    shuffle=True,

    generator=LOADER_GENERATOR,

    num_workers=0,

    pin_memory=True,

    drop_last=False
)


print("\n[4] Training DataLoader")
print("-" * 78)

print(
    "Dataset windows:",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "Batches per epoch:",
    len(T4_SSL_LOADER)
)


# ======================================================================
# 6 — CREATE FRESH MODEL
# ======================================================================

# Reset seed immediately before initialization.
set_global_seed(SEED)


SSL_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


# Only encoder + SSL heads are optimized.

SSL_PARAMETERS = list(
    SSL_MODEL.feature_encoder.parameters()
) + list(
    SSL_MODEL.temporal_encoder.parameters()
) + list(
    SSL_MODEL.projection_head.parameters()
) + list(
    SSL_MODEL.temporal_order_head.parameters()
)


SSL_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter in SSL_PARAMETERS
)


CLASSIFIER_PARAMETER_IDS = {
    id(parameter)
    for parameter
    in SSL_MODEL.classifier_head.parameters()
}


SSL_PARAMETER_IDS = {
    id(parameter)
    for parameter
    in SSL_PARAMETERS
}


CLASSIFIER_EXCLUDED = bool(
    CLASSIFIER_PARAMETER_IDS.isdisjoint(
        SSL_PARAMETER_IDS
    )
)


if SSL_PARAMETER_COUNT != 167_105:
    raise RuntimeError(
        f"SSL parameter count mismatch: "
        f"{SSL_PARAMETER_COUNT:,}"
    )


if not CLASSIFIER_EXCLUDED:
    raise RuntimeError(
        "Classifier parameters incorrectly included "
        "in SSL optimization."
    )


OPTIMIZER = torch.optim.Adam(
    SSL_PARAMETERS,
    lr=LEARNING_RATE
)


ORDER_CRITERION = nn.BCEWithLogitsLoss()


print("\n[5] Fresh SSL model")
print("-" * 78)

print(
    "SSL trainable parameters:",
    f"{SSL_PARAMETER_COUNT:,}"
)

print(
    "Classifier included:",
    not CLASSIFIER_EXCLUDED
)


# ======================================================================
# 7 — AUGMENTATION
# ======================================================================

def create_augmented_view(x):

    # Gaussian jitter.
    view = (
        x
        +
        torch.randn_like(x)
        * JITTER_STD
    )

    # Independent element-wise masking.
    mask = (
        torch.rand_like(view)
        <
        MASK_PROBABILITY
    )

    view = view.masked_fill(
        mask,
        0.0
    )

    return view


# ======================================================================
# 8 — NT-XENT LOSS
# ======================================================================

def nt_xent_loss(
    z1,
    z2,
    temperature
):

    batch_size = z1.shape[0]

    z = torch.cat(
        [z1, z2],
        dim=0
    )

    # Projection head already normalizes,
    # but normalize again defensively.
    z = F.normalize(
        z,
        p=2,
        dim=1
    )

    logits = (
        torch.matmul(
            z,
            z.T
        )
        /
        temperature
    )

    total_examples = (
        2 * batch_size
    )

    diagonal_mask = torch.eye(
        total_examples,
        device=z.device,
        dtype=torch.bool
    )

    logits = logits.masked_fill(
        diagonal_mask,
        -1e9
    )

    positive_indices = (
        torch.arange(
            total_examples,
            device=z.device
        )
        +
        batch_size
    ) % total_examples

    loss = F.cross_entropy(
        logits,
        positive_indices
    )

    return loss


# ======================================================================
# 9 — TEMPORAL-ORDER LOSS
# ======================================================================

def temporal_order_loss(
    model,
    x
):

    sequence_length = x.shape[1]

    if sequence_length % 2 != 0:
        raise RuntimeError(
            "Window length must be even for "
            "the frozen temporal-order implementation."
        )

    half = sequence_length // 2


    first_half = x[
        :,
        :half,
        :
    ]

    second_half = x[
        :,
        half:,
        :
    ]


    first_representation = model.encode(
        first_half
    )

    second_representation = model.encode(
        second_half
    )


    # 1 = correct temporal order
    # 0 = reversed temporal order

    targets = torch.randint(
        low=0,
        high=2,
        size=(x.shape[0],),
        device=x.device,
        dtype=torch.int64
    )


    correct_mask = targets.bool().unsqueeze(1)


    left_representation = torch.where(
        correct_mask,
        first_representation,
        second_representation
    )


    right_representation = torch.where(
        correct_mask,
        second_representation,
        first_representation
    )


    logits = model.temporal_order_head(
        left_representation,
        right_representation
    )


    loss = ORDER_CRITERION(
        logits,
        targets.float()
    )


    return loss


# ======================================================================
# 10 — CHECKPOINT HELPERS
# ======================================================================

def capture_rng_state():

    return {
        "python":
            random.getstate(),

        "numpy":
            np.random.get_state(),

        "torch_cpu":
            torch.get_rng_state(),

        "torch_cuda":
            torch.cuda.get_rng_state_all(),

        "loader_generator":
            LOADER_GENERATOR.get_state()
    }


def restore_rng_state(state):

    random.setstate(
        state["python"]
    )

    np.random.set_state(
        state["numpy"]
    )

    torch.set_rng_state(
        state["torch_cpu"]
    )

    torch.cuda.set_rng_state_all(
        state["torch_cuda"]
    )

    LOADER_GENERATOR.set_state(
        state["loader_generator"]
    )


def save_checkpoint(
    epoch,
    history
):

    checkpoint = {

        "step":
            "A42",

        "implementation_version":
            IMPLEMENTATION_SPEC[
                "implementation_version"
            ],

        "implementation_sha256":
            IMPLEMENTATION_HASH,

        "fold_id":
            1,

        "held_out_family":
            "DDoS",

        "window_size":
            4,

        "seed":
            SEED,

        "lambda_t":
            LAMBDA_T,

        "completed_epoch":
            epoch,

        "model_state_dict":
            SSL_MODEL.state_dict(),

        "optimizer_state_dict":
            OPTIMIZER.state_dict(),

        "history":
            history,

        "rng_state":
            capture_rng_state()
    }


    temporary_path = (
        OUTPUT_DIR
        / "A42_checkpoint_writing.tmp"
    )


    torch.save(
        checkpoint,
        temporary_path
    )


    os.replace(
        temporary_path,
        CHECKPOINT_PATH
    )


# ======================================================================
# 11 — RESUME IF A42 CHECKPOINT EXISTS
# ======================================================================

HISTORY = []
START_EPOCH = 1


print("\n[6] Checking A42 recovery checkpoint")
print("-" * 78)


if CHECKPOINT_PATH.exists():

    checkpoint = torch.load(
        CHECKPOINT_PATH,
        map_location=DEVICE,
        weights_only=False
    )


    if (
        checkpoint.get(
            "implementation_sha256"
        )
        !=
        IMPLEMENTATION_HASH
    ):
        raise RuntimeError(
            "Existing checkpoint uses a different "
            "sensitivity implementation."
        )


    if int(
        checkpoint.get(
            "window_size",
            -1
        )
    ) != 4:
        raise RuntimeError(
            "Checkpoint window-size mismatch."
        )


    SSL_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    HISTORY = checkpoint.get(
        "history",
        []
    )


    completed_epoch = int(
        checkpoint[
            "completed_epoch"
        ]
    )


    restore_rng_state(
        checkpoint[
            "rng_state"
        ]
    )


    START_EPOCH = (
        completed_epoch + 1
    )


    print(
        "Checkpoint found."
    )

    print(
        "Completed epochs:",
        completed_epoch
    )

    print(
        "Resuming from epoch:",
        START_EPOCH
    )

else:

    print(
        "No A42 checkpoint found."
    )

    print(
        "Starting cleanly from epoch 1."
    )


# ======================================================================
# 12 — SSL TRAINING
# ======================================================================

NONFINITE_BATCHES = 0


print("\n[7] Starting / resuming T=4 SSL training")
print("-" * 78)


for epoch in range(
    START_EPOCH,
    SSL_EPOCHS + 1
):

    epoch_start = time.time()

    SSL_MODEL.train()


    epoch_total_sum = 0.0
    epoch_ntxent_sum = 0.0
    epoch_order_sum = 0.0

    epoch_examples = 0

    maximum_preclip_gradient_norm = 0.0


    for batch_index, (
        X_batch,
        _y_unused
    ) in enumerate(
        T4_SSL_LOADER,
        start=1
    ):


        X_batch = X_batch.to(
            DEVICE,
            dtype=torch.float32,
            non_blocking=True
        )


        if not torch.isfinite(
            X_batch
        ).all():

            raise RuntimeError(
                f"Non-finite input at epoch "
                f"{epoch}, batch {batch_index}."
            )


        # --------------------------------------------------------------
        # Two independently augmented views
        # --------------------------------------------------------------

        view_1 = create_augmented_view(
            X_batch
        )

        view_2 = create_augmented_view(
            X_batch
        )


        # --------------------------------------------------------------
        # Forward SSL objectives
        # --------------------------------------------------------------

        representation_1 = (
            SSL_MODEL.encode(
                view_1
            )
        )

        representation_2 = (
            SSL_MODEL.encode(
                view_2
            )
        )


        projection_1 = (
            SSL_MODEL.projection_head(
                representation_1
            )
        )

        projection_2 = (
            SSL_MODEL.projection_head(
                representation_2
            )
        )


        loss_ntxent = nt_xent_loss(
            projection_1,
            projection_2,
            TEMPERATURE
        )


        loss_order = temporal_order_loss(
            SSL_MODEL,
            X_batch
        )


        total_loss = (
            loss_ntxent
            +
            LAMBDA_T
            *
            loss_order
        )


        if not torch.isfinite(
            total_loss
        ):

            NONFINITE_BATCHES += 1

            raise RuntimeError(
                f"Non-finite loss at epoch "
                f"{epoch}, batch {batch_index}."
            )


        # --------------------------------------------------------------
        # Backpropagation
        # --------------------------------------------------------------

        OPTIMIZER.zero_grad(
            set_to_none=True
        )


        total_loss.backward()


        gradient_norm = (
            torch.nn.utils.clip_grad_norm_(
                SSL_PARAMETERS,
                max_norm=GRADIENT_CLIP_NORM
            )
        )


        gradient_norm_value = float(
            gradient_norm.detach().cpu()
        )


        if not np.isfinite(
            gradient_norm_value
        ):

            NONFINITE_BATCHES += 1

            raise RuntimeError(
                f"Non-finite gradient norm at "
                f"epoch {epoch}, batch {batch_index}."
            )


        maximum_preclip_gradient_norm = max(
            maximum_preclip_gradient_norm,
            gradient_norm_value
        )


        OPTIMIZER.step()


        # --------------------------------------------------------------
        # Statistics
        # --------------------------------------------------------------

        batch_examples = int(
            X_batch.shape[0]
        )


        epoch_total_sum += (
            float(
                total_loss.detach().cpu()
            )
            *
            batch_examples
        )


        epoch_ntxent_sum += (
            float(
                loss_ntxent.detach().cpu()
            )
            *
            batch_examples
        )


        epoch_order_sum += (
            float(
                loss_order.detach().cpu()
            )
            *
            batch_examples
        )


        epoch_examples += (
            batch_examples
        )


        if (
            batch_index % 100 == 0
            or
            batch_index == len(
                T4_SSL_LOADER
            )
        ):

            print(
                f"Epoch {epoch:02d}/{SSL_EPOCHS} "
                f"| Batch "
                f"{batch_index}/{len(T4_SSL_LOADER)} "
                f"| Loss "
                f"{float(total_loss.detach().cpu()):.4f}"
            )


    # ==================================================================
    # Epoch summary
    # ==================================================================

    epoch_total_loss = (
        epoch_total_sum
        /
        epoch_examples
    )


    epoch_ntxent_loss = (
        epoch_ntxent_sum
        /
        epoch_examples
    )


    epoch_order_loss = (
        epoch_order_sum
        /
        epoch_examples
    )


    epoch_seconds = (
        time.time()
        -
        epoch_start
    )


    epoch_record = {

        "epoch":
            epoch,

        "window_size":
            4,

        "seed":
            SEED,

        "lambda_t":
            LAMBDA_T,

        "total_loss":
            epoch_total_loss,

        "NT_Xent_loss":
            epoch_ntxent_loss,

        "temporal_order_loss":
            epoch_order_loss,

        "examples":
            epoch_examples,

        "batches":
            len(T4_SSL_LOADER),

        "maximum_preclip_gradient_norm":
            maximum_preclip_gradient_norm,

        "epoch_seconds":
            epoch_seconds
    }


    # Replace same epoch if recovering from
    # an unusual interrupted history state.

    HISTORY = [
        row
        for row in HISTORY
        if int(row["epoch"]) != epoch
    ]

    HISTORY.append(
        epoch_record
    )

    HISTORY = sorted(
        HISTORY,
        key=lambda row: row["epoch"]
    )


    pd.DataFrame(
        HISTORY
    ).to_csv(
        HISTORY_PATH,
        index=False
    )


    save_checkpoint(
        epoch,
        HISTORY
    )


    print()

    print(
        f"Epoch {epoch:02d} complete "
        f"| total={epoch_total_loss:.6f} "
        f"| NT-Xent={epoch_ntxent_loss:.6f} "
        f"| order={epoch_order_loss:.6f} "
        f"| time={epoch_seconds:.1f}s "
        f"| checkpoint=Drive"
    )

    print()


# ======================================================================
# 13 — FINAL NUMERICAL VALIDATION
# ======================================================================

print("\n[8] Final numerical validation")
print("-" * 78)


COMPLETED_EPOCHS = len(
    HISTORY
)


ALL_PARAMETERS_FINITE = all(

    torch.isfinite(
        parameter
    ).all().item()

    for parameter
    in SSL_MODEL.parameters()
)


SSL_MODEL.eval()


X_check, _ = next(
    iter(
        DataLoader(
            T4_TRAIN_DATASET,
            batch_size=256,
            shuffle=False,
            num_workers=0
        )
    )
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


with torch.no_grad():

    representation_check = (
        SSL_MODEL.encode(
            X_check
        )
    )


    projection_check = (
        SSL_MODEL.projection_head(
            representation_check
        )
    )


OUTPUTS_FINITE = bool(

    torch.isfinite(
        representation_check
    ).all()

    and

    torch.isfinite(
        projection_check
    ).all()
)


projection_norms = (
    torch.linalg.vector_norm(
        projection_check,
        ord=2,
        dim=1
    )
)


MAX_PROJECTION_NORM_ERROR = float(

    torch.max(
        torch.abs(
            projection_norms
            -
            1.0
        )
    )
    .detach()
    .cpu()
)


PROJECTION_NORMALIZATION_VALID = bool(
    MAX_PROJECTION_NORM_ERROR
    <
    1e-5
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "All parameters finite:",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Max projection norm error:",
    f"{MAX_PROJECTION_NORM_ERROR:.10e}"
)


# ======================================================================
# 14 — SAVE FINAL MODEL
# ======================================================================

FINAL_ARTIFACT = {

    "step":
        "A42",

    "implementation_version":
        IMPLEMENTATION_SPEC[
            "implementation_version"
        ],

    "implementation_sha256":
        IMPLEMENTATION_HASH,

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        4,

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "epochs":
        SSL_EPOCHS,

    "precision":
        "float32",

    "binary_labels_used":
        False,

    "classifier_optimized":
        False,

    "model_state_dict":
        SSL_MODEL.state_dict()
}


torch.save(
    FINAL_ARTIFACT,
    FINAL_MODEL_PATH
)


# ======================================================================
# 15 — SAVE SUMMARY
# ======================================================================

FINAL_HISTORY_ROW = (
    HISTORY[-1]
    if HISTORY
    else None
)


A42_SUMMARY = {

    "step":
        "A42",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        4,

    "seed":
        SEED,

    "lambda_t":
        LAMBDA_T,

    "implementation_version":
        IMPLEMENTATION_SPEC[
            "implementation_version"
        ],

    "implementation_sha256":
        IMPLEMENTATION_HASH,

    "training_windows":
        len(T4_TRAIN_DATASET),

    "completed_ssl_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "binary_labels_used":
        False,

    "classifier_optimized":
        False,

    "held_out_DDoS_used":
        False,

    "known_test_used":
        False,

    "zero_day_used":
        False,

    "nonfinite_batches":
        NONFINITE_BATCHES,

    "all_model_parameters_finite":
        ALL_PARAMETERS_FINITE,

    "post_training_outputs_finite":
        OUTPUTS_FINITE,

    "projection_normalization_valid":
        PROJECTION_NORMALIZATION_VALID,

    "max_projection_norm_error":
        MAX_PROJECTION_NORM_ERROR,

    "final_total_loss":
        (
            FINAL_HISTORY_ROW[
                "total_loss"
            ]
            if FINAL_HISTORY_ROW
            else None
        ),

    "final_NT_Xent_loss":
        (
            FINAL_HISTORY_ROW[
                "NT_Xent_loss"
            ]
            if FINAL_HISTORY_ROW
            else None
        ),

    "final_temporal_order_loss":
        (
            FINAL_HISTORY_ROW[
                "temporal_order_loss"
            ]
            if FINAL_HISTORY_ROW
            else None
        )
}


with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        A42_SUMMARY,
        f,
        indent=4
    )


# ======================================================================
# 16 — FINAL STEP VALIDATION
# ======================================================================

A42_VALID = bool(

    COMPLETED_EPOCHS == 30

    and

    SSL_PARAMETER_COUNT == 167_105

    and

    CLASSIFIER_EXCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    ALL_PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROJECTION_NORMALIZATION_VALID

    and

    FINAL_MODEL_PATH.exists()

    and

    CHECKPOINT_PATH.exists()

    and

    HISTORY_PATH.exists()

    and

    SPEC_PATH.exists()

    and

    SUMMARY_PATH.exists()
)


STEP_42_T4_SSL_PRETRAINING_VALID = (
    A42_VALID
)


print("\n[9] Step A42 validation")
print("-" * 78)

print(
    "Window size                     :",
    4
)

print(
    "Training windows                :",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "Completed SSL epochs            :",
    f"{COMPLETED_EPOCHS} / 30"
)

print(
    "Precision                       :",
    "float32"
)

print(
    "lambda_t                        :",
    LAMBDA_T
)

print(
    "Binary labels used              :",
    False
)

print(
    "Classifier optimized            :",
    False
)

print(
    "Held-out DDoS used              :",
    False
)

print(
    "Known-test used                 :",
    False
)

print(
    "Zero-day data used              :",
    False
)

print(
    "Non-finite batches              :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite               :",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite                  :",
    OUTPUTS_FINITE
)

print(
    "Projection normalization valid  :",
    PROJECTION_NORMALIZATION_VALID
)

print(
    "Final model backed up           :",
    FINAL_MODEL_PATH.exists()
)

print(
    "Latest checkpoint backed up     :",
    CHECKPOINT_PATH.exists()
)

print(
    "Training history backed up      :",
    HISTORY_PATH.exists()
)


if FINAL_HISTORY_ROW is not None:

    print(
        "Final total loss                :",
        f"{FINAL_HISTORY_ROW['total_loss']:.6f}"
    )

    print(
        "Final NT-Xent loss              :",
        f"{FINAL_HISTORY_ROW['NT_Xent_loss']:.6f}"
    )

    print(
        "Final temporal-order loss       :",
        f"{FINAL_HISTORY_ROW['temporal_order_loss']:.6f}"
    )


print("\n" + "=" * 78)

if A42_VALID:

    print(
        "✅ STEP A42 PASSED — "
        "T=4 controlled SSL pretraining completed "
        "successfully and was backed up to Drive."
    )

else:

    print(
        "❌ STEP A42 FAILED — "
        "do not proceed to supervised fine-tuning."
    )

print("=" * 78)

==============================================================================
STEP A42 — T=4 CONTROLLED SSL PRETRAINING
FOLD 1 | HELD-OUT FAMILY = DDoS | SEED = 13
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A40-R valid: True
A41 valid: True
A41.8 valid: True
Training windows: 119,285
GPU: Tesla T4
Device: cuda

[2] Frozen sensitivity configuration
------------------------------------------------------------------------------
Window size: 4
Seed: 13
Epochs: 30
Batch size: 256
Learning rate: 0.001
Temperature: 0.2
lambda_t: 0.25
Feature masking: 0.1
Gaussian jitter: 0.01
Gradient clipping: 5.0
Precision: float32
Binary labels used in SSL: False

Implementation version: window_sensitivity_ssl_v1
Implementation SHA256: 378810ed8626a2817ddf5e927b5e62092d3eb451a49d5e1366f5821ee84767bc

[3] Drive backup
------------------------------------------------------------------------------
Output directory: /content/drive/MyDrive/ZeroDay_IoT_Research_Backup/sensitivity/window_size/fold_01_DDoS/T4/ssl_pretraining/seed_13
Implementation spec saved: True

[4] Training DataLoader
------------------------------------------------------------------------------
Dataset windows: 119,285
Batches per epoch: 466

[5] Fresh SSL model
------------------------------------------------------------------------------
SSL trainable parameters: 167,105
Classifier included: False

[6] Checking A42 recovery checkpoint
------------------------------------------------------------------------------
No A42 checkpoint found.
Starting cleanly from epoch 1.

[7] Starting / resuming T=4 SSL training
------------------------------------------------------------------------------
Epoch 01/30 | Batch 100/466 | Loss 2.7337
Epoch 01/30 | Batch 200/466 | Loss 2.4686
Epoch 01/30 | Batch 300/466 | Loss 2.4006
Epoch 01/30 | Batch 400/466 | Loss 2.3962
Epoch 01/30 | Batch 466/466 | Loss 2.3480

Epoch 01 complete | total=2.567367 | NT-Xent=2.395168 | order=0.688794 | time=14.1s | checkpoint=Drive

Epoch 02/30 | Batch 100/466 | Loss 2.2750
Epoch 02/30 | Batch 200/466 | Loss 2.2860
Epoch 02/30 | Batch 300/466 | Loss 2.2673
Epoch 02/30 | Batch 400/466 | Loss 2.2011
Epoch 02/30 | Batch 466/466 | Loss 2.1557

Epoch 02 complete | total=2.274711 | NT-Xent=2.105442 | order=0.677075 | time=13.9s | checkpoint=Drive

Epoch 03/30 | Batch 100/466 | Loss 2.2283
Epoch 03/30 | Batch 200/466 | Loss 2.1667
Epoch 03/30 | Batch 300/466 | Loss 2.1484
Epoch 03/30 | Batch 400/466 | Loss 2.1466
Epoch 03/30 | Batch 466/466 | Loss 2.0919

Epoch 03 complete | total=2.197432 | NT-Xent=2.029387 | order=0.672181 | time=12.7s | checkpoint=Drive

Epoch 04/30 | Batch 100/466 | Loss 2.1882
Epoch 04/30 | Batch 200/466 | Loss 2.1761
Epoch 04/30 | Batch 300/466 | Loss 2.0889
Epoch 04/30 | Batch 400/466 | Loss 2.1539
Epoch 04/30 | Batch 466/466 | Loss 2.1434

Epoch 04 complete | total=2.155896 | NT-Xent=1.988500 | order=0.669586 | time=6.8s | checkpoint=Drive

Epoch 05/30 | Batch 100/466 | Loss 2.1043
Epoch 05/30 | Batch 200/466 | Loss 2.1420
Epoch 05/30 | Batch 300/466 | Loss 2.1174
Epoch 05/30 | Batch 400/466 | Loss 2.1080
Epoch 05/30 | Batch 466/466 | Loss 2.0719

Epoch 05 complete | total=2.125891 | NT-Xent=1.959178 | order=0.666853 | time=7.8s | checkpoint=Drive

Epoch 06/30 | Batch 100/466 | Loss 2.1536
Epoch 06/30 | Batch 200/466 | Loss 2.0524
Epoch 06/30 | Batch 300/466 | Loss 2.1590
Epoch 06/30 | Batch 400/466 | Loss 2.1407
Epoch 06/30 | Batch 466/466 | Loss 2.0503

Epoch 06 complete | total=2.101979 | NT-Xent=1.935954 | order=0.664097 | time=7.2s | checkpoint=Drive

Epoch 07/30 | Batch 100/466 | Loss 2.1433
Epoch 07/30 | Batch 200/466 | Loss 2.0944
Epoch 07/30 | Batch 300/466 | Loss 2.0530
Epoch 07/30 | Batch 400/466 | Loss 2.0605
Epoch 07/30 | Batch 466/466 | Loss 2.0532

Epoch 07 complete | total=2.083750 | NT-Xent=1.918205 | order=0.662178 | time=7.4s | checkpoint=Drive

Epoch 08/30 | Batch 100/466 | Loss 2.0785
Epoch 08/30 | Batch 200/466 | Loss 2.0426
Epoch 08/30 | Batch 300/466 | Loss 2.0345
Epoch 08/30 | Batch 400/466 | Loss 2.0283
Epoch 08/30 | Batch 466/466 | Loss 2.0008

Epoch 08 complete | total=2.068977 | NT-Xent=1.903846 | order=0.660525 | time=7.6s | checkpoint=Drive

Epoch 09/30 | Batch 100/466 | Loss 2.0410
Epoch 09/30 | Batch 200/466 | Loss 2.0395
Epoch 09/30 | Batch 300/466 | Loss 2.0319
Epoch 09/30 | Batch 400/466 | Loss 2.0593
Epoch 09/30 | Batch 466/466 | Loss 2.0370

Epoch 09 complete | total=2.053497 | NT-Xent=1.888882 | order=0.658461 | time=7.2s | checkpoint=Drive

Epoch 10/30 | Batch 100/466 | Loss 2.0458
Epoch 10/30 | Batch 200/466 | Loss 1.9992
Epoch 10/30 | Batch 300/466 | Loss 2.0764
Epoch 10/30 | Batch 400/466 | Loss 2.0138
Epoch 10/30 | Batch 466/466 | Loss 2.0017

Epoch 10 complete | total=2.041145 | NT-Xent=1.876944 | order=0.656802 | time=8.1s | checkpoint=Drive

Epoch 11/30 | Batch 100/466 | Loss 2.0285
Epoch 11/30 | Batch 200/466 | Loss 2.0355
Epoch 11/30 | Batch 300/466 | Loss 2.0149
Epoch 11/30 | Batch 400/466 | Loss 2.0344
Epoch 11/30 | Batch 466/466 | Loss 1.9920

Epoch 11 complete | total=2.031698 | NT-Xent=1.867842 | order=0.655424 | time=6.8s | checkpoint=Drive

Epoch 12/30 | Batch 100/466 | Loss 1.9919
Epoch 12/30 | Batch 200/466 | Loss 2.0483
Epoch 12/30 | Batch 300/466 | Loss 2.0114
Epoch 12/30 | Batch 400/466 | Loss 2.0001
Epoch 12/30 | Batch 466/466 | Loss 1.9583

Epoch 12 complete | total=2.022856 | NT-Xent=1.859524 | order=0.653328 | time=7.9s | checkpoint=Drive

Epoch 13/30 | Batch 100/466 | Loss 1.9968
Epoch 13/30 | Batch 200/466 | Loss 1.9995
Epoch 13/30 | Batch 300/466 | Loss 1.9914
Epoch 13/30 | Batch 400/466 | Loss 1.9963
Epoch 13/30 | Batch 466/466 | Loss 2.0039

Epoch 13 complete | total=2.016526 | NT-Xent=1.853426 | order=0.652401 | time=6.8s | checkpoint=Drive

Epoch 14/30 | Batch 100/466 | Loss 2.0158
Epoch 14/30 | Batch 200/466 | Loss 2.0070
Epoch 14/30 | Batch 300/466 | Loss 2.0101
Epoch 14/30 | Batch 400/466 | Loss 2.0057
Epoch 14/30 | Batch 466/466 | Loss 1.9817

Epoch 14 complete | total=2.009347 | NT-Xent=1.846692 | order=0.650623 | time=7.9s | checkpoint=Drive

Epoch 15/30 | Batch 100/466 | Loss 2.0426
Epoch 15/30 | Batch 200/466 | Loss 2.0158
Epoch 15/30 | Batch 300/466 | Loss 2.0121
Epoch 15/30 | Batch 400/466 | Loss 1.9880
Epoch 15/30 | Batch 466/466 | Loss 1.9567

Epoch 15 complete | total=2.006223 | NT-Xent=1.843750 | order=0.649893 | time=6.8s | checkpoint=Drive

Epoch 16/30 | Batch 100/466 | Loss 1.9981
Epoch 16/30 | Batch 200/466 | Loss 2.0000
Epoch 16/30 | Batch 300/466 | Loss 1.9882
Epoch 16/30 | Batch 400/466 | Loss 2.0260
Epoch 16/30 | Batch 466/466 | Loss 1.9962

Epoch 16 complete | total=2.001865 | NT-Xent=1.839700 | order=0.648660 | time=7.9s | checkpoint=Drive

Epoch 17/30 | Batch 100/466 | Loss 2.0358
Epoch 17/30 | Batch 200/466 | Loss 1.9987
Epoch 17/30 | Batch 300/466 | Loss 2.0005
Epoch 17/30 | Batch 400/466 | Loss 1.9989
Epoch 17/30 | Batch 466/466 | Loss 1.9693

Epoch 17 complete | total=1.996823 | NT-Xent=1.834846 | order=0.647910 | time=7.2s | checkpoint=Drive

Epoch 18/30 | Batch 100/466 | Loss 1.9652
Epoch 18/30 | Batch 200/466 | Loss 1.9774
Epoch 18/30 | Batch 300/466 | Loss 1.9793
Epoch 18/30 | Batch 400/466 | Loss 1.9841
Epoch 18/30 | Batch 466/466 | Loss 2.0093

Epoch 18 complete | total=1.992289 | NT-Xent=1.830625 | order=0.646656 | time=7.6s | checkpoint=Drive

Epoch 19/30 | Batch 100/466 | Loss 1.9575
Epoch 19/30 | Batch 200/466 | Loss 1.9739
Epoch 19/30 | Batch 300/466 | Loss 1.9861
Epoch 19/30 | Batch 400/466 | Loss 2.0007
Epoch 19/30 | Batch 466/466 | Loss 1.9058

Epoch 19 complete | total=1.989107 | NT-Xent=1.827708 | order=0.645593 | time=7.6s | checkpoint=Drive

Epoch 20/30 | Batch 100/466 | Loss 2.0061
Epoch 20/30 | Batch 200/466 | Loss 1.9902
Epoch 20/30 | Batch 300/466 | Loss 1.9539
Epoch 20/30 | Batch 400/466 | Loss 1.9885
Epoch 20/30 | Batch 466/466 | Loss 1.9032

Epoch 20 complete | total=1.984126 | NT-Xent=1.822822 | order=0.645215 | time=7.0s | checkpoint=Drive

Epoch 21/30 | Batch 100/466 | Loss 2.0096
Epoch 21/30 | Batch 200/466 | Loss 1.9755
Epoch 21/30 | Batch 300/466 | Loss 1.9806
Epoch 21/30 | Batch 400/466 | Loss 1.9651
Epoch 21/30 | Batch 466/466 | Loss 1.9517

Epoch 21 complete | total=1.982301 | NT-Xent=1.821327 | order=0.643896 | time=7.9s | checkpoint=Drive

Epoch 22/30 | Batch 100/466 | Loss 1.9851
Epoch 22/30 | Batch 200/466 | Loss 1.9905
Epoch 22/30 | Batch 300/466 | Loss 1.9703
Epoch 22/30 | Batch 400/466 | Loss 1.9826
Epoch 22/30 | Batch 466/466 | Loss 1.9304

Epoch 22 complete | total=1.979188 | NT-Xent=1.818442 | order=0.642985 | time=7.0s | checkpoint=Drive

Epoch 23/30 | Batch 100/466 | Loss 1.9883
Epoch 23/30 | Batch 200/466 | Loss 1.9927
Epoch 23/30 | Batch 300/466 | Loss 2.0234
Epoch 23/30 | Batch 400/466 | Loss 1.9693
Epoch 23/30 | Batch 466/466 | Loss 1.9607

Epoch 23 complete | total=1.977163 | NT-Xent=1.816548 | order=0.642456 | time=8.1s | checkpoint=Drive

Epoch 24/30 | Batch 100/466 | Loss 1.9620
Epoch 24/30 | Batch 200/466 | Loss 2.0096
Epoch 24/30 | Batch 300/466 | Loss 1.9544
Epoch 24/30 | Batch 400/466 | Loss 1.9531
Epoch 24/30 | Batch 466/466 | Loss 1.9718

Epoch 24 complete | total=1.975339 | NT-Xent=1.815009 | order=0.641323 | time=7.0s | checkpoint=Drive

Epoch 25/30 | Batch 100/466 | Loss 1.9790
Epoch 25/30 | Batch 200/466 | Loss 2.0354
Epoch 25/30 | Batch 300/466 | Loss 1.9523
Epoch 25/30 | Batch 400/466 | Loss 1.9941
Epoch 25/30 | Batch 466/466 | Loss 1.9449

Epoch 25 complete | total=1.973802 | NT-Xent=1.813703 | order=0.640396 | time=8.2s | checkpoint=Drive

Epoch 26/30 | Batch 100/466 | Loss 1.9549
Epoch 26/30 | Batch 200/466 | Loss 2.0378
Epoch 26/30 | Batch 300/466 | Loss 2.0055
Epoch 26/30 | Batch 400/466 | Loss 2.0254
Epoch 26/30 | Batch 466/466 | Loss 1.9182

Epoch 26 complete | total=1.969812 | NT-Xent=1.809749 | order=0.640251 | time=7.3s | checkpoint=Drive

Epoch 27/30 | Batch 100/466 | Loss 1.9558
Epoch 27/30 | Batch 200/466 | Loss 1.9811
Epoch 27/30 | Batch 300/466 | Loss 1.9505
Epoch 27/30 | Batch 400/466 | Loss 1.9786
Epoch 27/30 | Batch 466/466 | Loss 1.9527

Epoch 27 complete | total=1.968147 | NT-Xent=1.808329 | order=0.639273 | time=7.9s | checkpoint=Drive

Epoch 28/30 | Batch 100/466 | Loss 1.9546
Epoch 28/30 | Batch 200/466 | Loss 1.9568
Epoch 28/30 | Batch 300/466 | Loss 2.0111
Epoch 28/30 | Batch 400/466 | Loss 1.9989
Epoch 28/30 | Batch 466/466 | Loss 1.9220

Epoch 28 complete | total=1.966196 | NT-Xent=1.806592 | order=0.638416 | time=7.6s | checkpoint=Drive

Epoch 29/30 | Batch 100/466 | Loss 1.9716
Epoch 29/30 | Batch 200/466 | Loss 1.9663
Epoch 29/30 | Batch 300/466 | Loss 1.9608
Epoch 29/30 | Batch 400/466 | Loss 1.9571
Epoch 29/30 | Batch 466/466 | Loss 1.9261

Epoch 29 complete | total=1.965425 | NT-Xent=1.806004 | order=0.637683 | time=7.3s | checkpoint=Drive

Epoch 30/30 | Batch 100/466 | Loss 1.9811
Epoch 30/30 | Batch 200/466 | Loss 1.9613
Epoch 30/30 | Batch 300/466 | Loss 1.9893
Epoch 30/30 | Batch 400/466 | Loss 1.9606
Epoch 30/30 | Batch 466/466 | Loss 1.9172

Epoch 30 complete | total=1.963363 | NT-Xent=1.804103 | order=0.637041 | time=7.9s | checkpoint=Drive


[8] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 30
All parameters finite: True
Outputs finite: True
Max projection norm error: 1.1920928955e-07

[9] Step A42 validation
------------------------------------------------------------------------------
Window size                     : 4
Training windows                : 119,285
Completed SSL epochs            : 30 / 30
Precision                       : float32
lambda_t                        : 0.25
Binary labels used              : False
Classifier optimized            : False
Held-out DDoS used              : False
Known-test used                 : False
Zero-day data used              : False
Non-finite batches              : 0
Parameters finite               : True
Outputs finite                  : True
Projection normalization valid  : True
Final model backed up           : True
Latest checkpoint backed up     : True
Training history backed up      : True
Final total loss                : 1.963363
Final NT-Xent loss              : 1.804103
Final temporal-order loss       : 0.637041

==============================================================================
✅ STEP A42 PASSED — T=4 controlled SSL pretraining completed successfully and was backed up to Drive.
==============================================================================

# Step A43 — T=4 supervised fine-tuning

In [ ]:
# ======================================================================
# STEP A43
# T=4 CONTROLLED SUPERVISED FINE-TUNING
#
# Fold 1: DDoS held out
# Window = 4
# Seed = 13
# lambda_t = 0.25
# Imbalance method = none
#
# Loads encoder from A42 SSL.
# Projection/order heads are NOT optimized.
# Fresh classifier initialization.
#
# CHECKPOINT SAVED AFTER EVERY EPOCH.
# ======================================================================

from pathlib import Path
import os
import json
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A43 — T=4 SUPERVISED FINE-TUNING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS | SEED = 13")
print("=" * 78)


# ======================================================================
# 1 — PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_globals = [
    "STEP_42_T4_SSL_PRETRAINING_VALID",
    "T4_TRAIN_DATASET",
    "MOTSSLGRU",
]

for name in required_globals:
    if name not in globals():
        raise RuntimeError(
            f"Required state missing: {name}"
        )

if not STEP_42_T4_SSL_PRETRAINING_VALID:
    raise RuntimeError(
        "A42 did not pass."
    )

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA unavailable. Keep T4 GPU enabled."
    )


DEVICE = torch.device("cuda")
GPU_NAME = torch.cuda.get_device_name(0)


print("A42 valid:", STEP_42_T4_SSL_PRETRAINING_VALID)
print("Training windows:", f"{len(T4_TRAIN_DATASET):,}")
print("GPU:", GPU_NAME)
print("Device:", DEVICE)


if len(T4_TRAIN_DATASET) != 119_285:
    raise RuntimeError(
        "Expected 119,285 T=4 training windows."
    )


# ======================================================================
# 2 — FROZEN CONFIGURATION
# ======================================================================

SEED = 13
CLASSIFIER_INIT_SEED = 1013

FT_EPOCHS = 20
BATCH_SIZE = 256
LEARNING_RATE = 1e-3

GRADIENT_CLIP_NORM = 5.0

LAMBDA_T = 0.25
IMBALANCE_METHOD = "none"


print("\n[2] Fine-tuning configuration")
print("-" * 78)

print("Window size:", 4)
print("Seed:", SEED)
print("Classifier init seed:", CLASSIFIER_INIT_SEED)
print("Epochs:", FT_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Precision: float32")
print("Imbalance method:", IMBALANCE_METHOD)
print("Gradient clipping:", GRADIENT_CLIP_NORM)


# ======================================================================
# 3 — PATHS
# ======================================================================

SSL_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/"
    "fold_01_DDoS/T4/"
    "ssl_pretraining/seed_13"
)

SSL_FINAL_PATH = (
    SSL_DIR
    / "A42_T4_SSL_final.pt"
)

SSL_SPEC_PATH = (
    SSL_DIR
    / "A42_T4_SSL_implementation.json"
)


OUTPUT_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/"
    "fold_01_DDoS/T4/"
    "fine_tuning/seed_13/"
    "imbalance_none"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


CHECKPOINT_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_latest_checkpoint.pt"
)

FINAL_MODEL_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetuned_final.pt"
)

HISTORY_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_history.csv"
)

SUMMARY_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_summary.json"
)


for path in [
    SSL_FINAL_PATH,
    SSL_SPEC_PATH
]:
    if not path.exists():
        raise RuntimeError(
            f"A42 artifact missing:\n{path}"
        )


# ======================================================================
# 4 — REPRODUCIBILITY
# ======================================================================

def set_global_seed(seed):

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


set_global_seed(SEED)


LOADER_GENERATOR = torch.Generator()
LOADER_GENERATOR.manual_seed(SEED)


FT_LOADER = DataLoader(

    T4_TRAIN_DATASET,

    batch_size=BATCH_SIZE,

    shuffle=True,

    generator=LOADER_GENERATOR,

    num_workers=0,

    pin_memory=True,

    drop_last=False
)


print("\n[3] Fine-tuning DataLoader")
print("-" * 78)

print(
    "Dataset windows:",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "Batches per epoch:",
    len(FT_LOADER)
)


# ======================================================================
# 5 — LOAD A42 SSL ARTIFACT
# ======================================================================

ssl_artifact = torch.load(
    SSL_FINAL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if int(
    ssl_artifact.get(
        "window_size",
        -1
    )
) != 4:
    raise RuntimeError(
        "A42 artifact window mismatch."
    )


if float(
    ssl_artifact.get(
        "lambda_t",
        -1
    )
) != 0.25:
    raise RuntimeError(
        "A42 lambda_t mismatch."
    )


if int(
    ssl_artifact.get(
        "epochs",
        -1
    )
) != 30:
    raise RuntimeError(
        "A42 SSL epoch count mismatch."
    )


print("\n[4] A42 SSL artifact")
print("-" * 78)

print("SSL epochs:", ssl_artifact["epochs"])
print("SSL lambda_t:", ssl_artifact["lambda_t"])
print("SSL precision:", ssl_artifact["precision"])
print("SSL labels used:", ssl_artifact["binary_labels_used"])


# ======================================================================
# 6 — BUILD FINE-TUNING MODEL
# ======================================================================

set_global_seed(SEED)


FT_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


ssl_state = ssl_artifact[
    "model_state_dict"
]


# Load ONLY the feature encoder + GRU temporal encoder.

encoder_state = {
    key: value

    for key, value in ssl_state.items()

    if (
        key.startswith("feature_encoder.")
        or
        key.startswith("temporal_encoder.")
    )
}


load_result = FT_MODEL.load_state_dict(
    encoder_state,
    strict=False
)


ENCODER_LOADED = bool(
    len(
        [
            key
            for key in load_result.missing_keys
            if (
                key.startswith("feature_encoder.")
                or
                key.startswith("temporal_encoder.")
            )
        ]
    )
    == 0
)


if not ENCODER_LOADED:
    raise RuntimeError(
        "Failed to load A42 SSL encoder."
    )


# ======================================================================
# 7 — FRESH CLASSIFIER INITIALIZATION
# ======================================================================

torch.manual_seed(
    CLASSIFIER_INIT_SEED
)

torch.cuda.manual_seed_all(
    CLASSIFIER_INIT_SEED
)


def reset_module(module):

    if hasattr(
        module,
        "reset_parameters"
    ):
        module.reset_parameters()


FT_MODEL.classifier_head.apply(
    reset_module
)


# Restore main experiment seed afterwards.

set_global_seed(SEED)


print("SSL encoder loaded:", ENCODER_LOADED)
print("Classifier freshly initialized:", True)


# ======================================================================
# 8 — OPTIMIZED PARAMETERS
# ======================================================================

FT_PARAMETERS = (

    list(
        FT_MODEL
        .feature_encoder
        .parameters()
    )

    +

    list(
        FT_MODEL
        .temporal_encoder
        .parameters()
    )

    +

    list(
        FT_MODEL
        .classifier_head
        .parameters()
    )
)


FT_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter in FT_PARAMETERS
)


if FT_PARAMETER_COUNT != 117_377:
    raise RuntimeError(
        f"Fine-tuning parameter count mismatch: "
        f"{FT_PARAMETER_COUNT:,}"
    )


FT_PARAMETER_IDS = {
    id(parameter)
    for parameter in FT_PARAMETERS
}


PROJECTION_IDS = {
    id(parameter)
    for parameter
    in FT_MODEL.projection_head.parameters()
}


ORDER_IDS = {
    id(parameter)
    for parameter
    in FT_MODEL.temporal_order_head.parameters()
}


PROJECTION_EXCLUDED = bool(
    FT_PARAMETER_IDS.isdisjoint(
        PROJECTION_IDS
    )
)


ORDER_EXCLUDED = bool(
    FT_PARAMETER_IDS.isdisjoint(
        ORDER_IDS
    )
)


if not PROJECTION_EXCLUDED:
    raise RuntimeError(
        "Projection head incorrectly optimized."
    )


if not ORDER_EXCLUDED:
    raise RuntimeError(
        "Temporal-order head incorrectly optimized."
    )


print(
    "Fine-tuned parameters:",
    f"{FT_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    False
)

print(
    "Temporal-order head optimized:",
    False
)


# ======================================================================
# 9 — OPTIMIZER + LOSS
# ======================================================================

OPTIMIZER = torch.optim.Adam(
    FT_PARAMETERS,
    lr=LEARNING_RATE
)


CRITERION = nn.BCEWithLogitsLoss()


# ======================================================================
# 10 — CHECKPOINT HELPERS
# ======================================================================

def capture_rng_state():

    return {

        "python":
            random.getstate(),

        "numpy":
            np.random.get_state(),

        "torch_cpu":
            torch.get_rng_state(),

        "torch_cuda":
            torch.cuda.get_rng_state_all(),

        "loader_generator":
            LOADER_GENERATOR.get_state()
    }


def restore_rng_state(state):

    random.setstate(
        state["python"]
    )

    np.random.set_state(
        state["numpy"]
    )

    torch.set_rng_state(
        state["torch_cpu"]
    )

    torch.cuda.set_rng_state_all(
        state["torch_cuda"]
    )

    LOADER_GENERATOR.set_state(
        state["loader_generator"]
    )


def save_checkpoint(
    epoch,
    history
):

    artifact = {

        "step":
            "A43",

        "fold_id":
            1,

        "held_out_family":
            "DDoS",

        "window_size":
            4,

        "seed":
            SEED,

        "classifier_init_seed":
            CLASSIFIER_INIT_SEED,

        "lambda_t":
            LAMBDA_T,

        "imbalance_method":
            IMBALANCE_METHOD,

        "completed_epoch":
            epoch,

        "model_state_dict":
            FT_MODEL.state_dict(),

        "optimizer_state_dict":
            OPTIMIZER.state_dict(),

        "history":
            history,

        "rng_state":
            capture_rng_state()
    }


    temporary_path = (
        OUTPUT_DIR
        / "A43_checkpoint_writing.tmp"
    )


    torch.save(
        artifact,
        temporary_path
    )


    os.replace(
        temporary_path,
        CHECKPOINT_PATH
    )


# ======================================================================
# 11 — RESUME CHECK
# ======================================================================

HISTORY = []
START_EPOCH = 1


print("\n[5] Checking fine-tuning checkpoint")
print("-" * 78)


if CHECKPOINT_PATH.exists():

    checkpoint = torch.load(
        CHECKPOINT_PATH,
        map_location=DEVICE,
        weights_only=False
    )


    if int(
        checkpoint.get(
            "window_size",
            -1
        )
    ) != 4:
        raise RuntimeError(
            "Fine-tuning checkpoint window mismatch."
        )


    if checkpoint.get(
        "imbalance_method"
    ) != "none":
        raise RuntimeError(
            "Fine-tuning imbalance-method mismatch."
        )


    FT_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    HISTORY = checkpoint.get(
        "history",
        []
    )


    completed_epoch = int(
        checkpoint[
            "completed_epoch"
        ]
    )


    restore_rng_state(
        checkpoint[
            "rng_state"
        ]
    )


    START_EPOCH = (
        completed_epoch + 1
    )


    print("Checkpoint found.")
    print("Completed epochs:", completed_epoch)
    print("Resuming from epoch:", START_EPOCH)

else:

    print("No fine-tuning checkpoint found.")
    print("Starting from epoch 1.")


# ======================================================================
# 12 — SUPERVISED FINE-TUNING
# ======================================================================

NONFINITE_BATCHES = 0


print("\n[6] Starting / resuming supervised fine-tuning")
print("-" * 78)


for epoch in range(
    START_EPOCH,
    FT_EPOCHS + 1
):

    epoch_start = time.time()

    FT_MODEL.train()


    epoch_loss_sum = 0.0

    epoch_examples = 0

    epoch_correct = 0

    epoch_predicted_attack = 0

    maximum_preclip_gradient_norm = 0.0


    for batch_index, (
        X_batch,
        y_batch
    ) in enumerate(
        FT_LOADER,
        start=1
    ):


        X_batch = X_batch.to(
            DEVICE,
            dtype=torch.float32,
            non_blocking=True
        )


        y_batch = y_batch.to(
            DEVICE,
            dtype=torch.float32,
            non_blocking=True
        )


        if not torch.isfinite(
            X_batch
        ).all():

            raise RuntimeError(
                f"Non-finite input at epoch "
                f"{epoch}, batch {batch_index}."
            )


        logits = (
            FT_MODEL
            .forward_classifier(
                X_batch
            )
        )


        loss = CRITERION(
            logits,
            y_batch
        )


        if not torch.isfinite(
            loss
        ):

            NONFINITE_BATCHES += 1

            raise RuntimeError(
                f"Non-finite BCE at epoch "
                f"{epoch}, batch {batch_index}."
            )


        OPTIMIZER.zero_grad(
            set_to_none=True
        )


        loss.backward()


        gradient_norm = (
            torch.nn.utils.clip_grad_norm_(
                FT_PARAMETERS,
                max_norm=GRADIENT_CLIP_NORM
            )
        )


        gradient_norm_value = float(
            gradient_norm
            .detach()
            .cpu()
        )


        if not np.isfinite(
            gradient_norm_value
        ):

            NONFINITE_BATCHES += 1

            raise RuntimeError(
                f"Non-finite gradient at epoch "
                f"{epoch}, batch {batch_index}."
            )


        maximum_preclip_gradient_norm = max(
            maximum_preclip_gradient_norm,
            gradient_norm_value
        )


        OPTIMIZER.step()


        with torch.no_grad():

            probabilities = torch.sigmoid(
                logits
            )

            predictions = (
                probabilities >= 0.5
            ).float()


        batch_examples = int(
            X_batch.shape[0]
        )


        epoch_loss_sum += (
            float(
                loss.detach().cpu()
            )
            *
            batch_examples
        )


        epoch_examples += (
            batch_examples
        )


        epoch_correct += int(
            (
                predictions
                ==
                y_batch
            )
            .sum()
            .detach()
            .cpu()
        )


        epoch_predicted_attack += int(
            predictions
            .sum()
            .detach()
            .cpu()
        )


        if (
            batch_index % 100 == 0
            or
            batch_index == len(
                FT_LOADER
            )
        ):

            print(
                f"Epoch {epoch:02d}/{FT_EPOCHS} "
                f"| Batch "
                f"{batch_index}/{len(FT_LOADER)} "
                f"| BCE "
                f"{float(loss.detach().cpu()):.6f}"
            )


    epoch_bce = (
        epoch_loss_sum
        /
        epoch_examples
    )


    diagnostic_accuracy = (
        epoch_correct
        /
        epoch_examples
    )


    predicted_attack_fraction = (
        epoch_predicted_attack
        /
        epoch_examples
    )


    predicted_benign_fraction = (
        1.0
        -
        predicted_attack_fraction
    )


    epoch_seconds = (
        time.time()
        -
        epoch_start
    )


    epoch_record = {

        "epoch":
            epoch,

        "window_size":
            4,

        "seed":
            SEED,

        "lambda_t":
            LAMBDA_T,

        "imbalance_method":
            IMBALANCE_METHOD,

        "BCE":
            epoch_bce,

        "diagnostic_accuracy_at_0p5":
            diagnostic_accuracy,

        "predicted_attack_fraction":
            predicted_attack_fraction,

        "predicted_benign_fraction":
            predicted_benign_fraction,

        "examples":
            epoch_examples,

        "batches":
            len(FT_LOADER),

        "maximum_preclip_gradient_norm":
            maximum_preclip_gradient_norm,

        "epoch_seconds":
            epoch_seconds
    }


    HISTORY = [
        row
        for row in HISTORY
        if int(row["epoch"]) != epoch
    ]


    HISTORY.append(
        epoch_record
    )


    HISTORY = sorted(
        HISTORY,
        key=lambda row: row["epoch"]
    )


    pd.DataFrame(
        HISTORY
    ).to_csv(
        HISTORY_PATH,
        index=False
    )


    save_checkpoint(
        epoch,
        HISTORY
    )


    print()

    print(
        f"Epoch {epoch:02d} complete "
        f"| BCE={epoch_bce:.6f} "
        f"| diagnostic_acc@0.5="
        f"{diagnostic_accuracy:.6f} "
        f"| predicted_attack="
        f"{predicted_attack_fraction:.6f} "
        f"| time={epoch_seconds:.1f}s "
        f"| checkpoint=Drive"
    )

    print()


# ======================================================================
# 13 — FINAL NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


COMPLETED_EPOCHS = len(
    HISTORY
)


ALL_PARAMETERS_FINITE = all(

    torch.isfinite(
        parameter
    ).all().item()

    for parameter
    in FT_MODEL.parameters()
)


FT_MODEL.eval()


CHECK_LOADER = DataLoader(
    T4_TRAIN_DATASET,
    batch_size=256,
    shuffle=False,
    num_workers=0
)


X_check, y_check = next(
    iter(
        CHECK_LOADER
    )
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


with torch.no_grad():

    logits_check = (
        FT_MODEL
        .forward_classifier(
            X_check
        )
    )


    probabilities_check = (
        torch.sigmoid(
            logits_check
        )
    )


OUTPUTS_FINITE = bool(
    torch.isfinite(
        logits_check
    ).all()
    and
    torch.isfinite(
        probabilities_check
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    torch.all(
        probabilities_check >= 0
    )

    and

    torch.all(
        probabilities_check <= 1
    )
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 14 — SAVE FINAL MODEL
# ======================================================================

FINAL_ARTIFACT = {

    "step":
        "A43",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        4,

    "seed":
        SEED,

    "classifier_init_seed":
        CLASSIFIER_INIT_SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "epochs":
        FT_EPOCHS,

    "precision":
        "float32",

    "model_state_dict":
        FT_MODEL.state_dict()
}


torch.save(
    FINAL_ARTIFACT,
    FINAL_MODEL_PATH
)


# ======================================================================
# 15 — SAVE SUMMARY
# ======================================================================

FINAL_HISTORY_ROW = (
    HISTORY[-1]
    if HISTORY
    else None
)


A43_SUMMARY = {

    "step":
        "A43",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        4,

    "seed":
        SEED,

    "classifier_init_seed":
        CLASSIFIER_INIT_SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "training_windows":
        len(T4_TRAIN_DATASET),

    "completed_finetune_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "projection_head_optimized":
        False,

    "temporal_order_head_optimized":
        False,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_used":
        False,

    "nonfinite_batches":
        NONFINITE_BATCHES,

    "parameters_finite":
        ALL_PARAMETERS_FINITE,

    "outputs_finite":
        OUTPUTS_FINITE,

    "probability_range_valid":
        PROBABILITY_RANGE_VALID,

    "final_BCE":
        (
            FINAL_HISTORY_ROW["BCE"]
            if FINAL_HISTORY_ROW
            else None
        ),

    "diagnostic_accuracy_at_0p5":
        (
            FINAL_HISTORY_ROW[
                "diagnostic_accuracy_at_0p5"
            ]
            if FINAL_HISTORY_ROW
            else None
        ),

    "predicted_attack_fraction":
        (
            FINAL_HISTORY_ROW[
                "predicted_attack_fraction"
            ]
            if FINAL_HISTORY_ROW
            else None
        ),

    "predicted_benign_fraction":
        (
            FINAL_HISTORY_ROW[
                "predicted_benign_fraction"
            ]
            if FINAL_HISTORY_ROW
            else None
        )
}


with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        A43_SUMMARY,
        f,
        indent=4
    )


# ======================================================================
# 16 — FINAL VALIDATION
# ======================================================================

A43_VALID = bool(

    COMPLETED_EPOCHS == 20

    and

    FT_PARAMETER_COUNT == 117_377

    and

    ENCODER_LOADED

    and

    PROJECTION_EXCLUDED

    and

    ORDER_EXCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    ALL_PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    FINAL_MODEL_PATH.exists()

    and

    CHECKPOINT_PATH.exists()

    and

    HISTORY_PATH.exists()

    and

    SUMMARY_PATH.exists()
)


STEP_43_T4_FINETUNING_VALID = (
    A43_VALID
)


print("\n[8] Step A43 validation")
print("-" * 78)

print(
    "Window size                     :",
    4
)

print(
    "Completed fine-tuning epochs    :",
    f"{COMPLETED_EPOCHS} / 20"
)

print(
    "Training windows                :",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "Imbalance method                :",
    IMBALANCE_METHOD
)

print(
    "SSL encoder loaded              :",
    ENCODER_LOADED
)

print(
    "Classifier freshly initialized  :",
    True
)

print(
    "Fine-tuned parameters           :",
    f"{FT_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized       :",
    False
)

print(
    "Temporal-order head optimized   :",
    False
)

print(
    "Threshold selected              :",
    False
)

print(
    "Known-test used                 :",
    False
)

print(
    "Benign-test used                :",
    False
)

print(
    "Zero-day DDoS used              :",
    False
)

print(
    "Non-finite batches              :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite               :",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite                  :",
    OUTPUTS_FINITE
)

print(
    "Probability range valid         :",
    PROBABILITY_RANGE_VALID
)

print(
    "Final model backed up           :",
    FINAL_MODEL_PATH.exists()
)

print(
    "Latest checkpoint backed up     :",
    CHECKPOINT_PATH.exists()
)

print(
    "Training history backed up      :",
    HISTORY_PATH.exists()
)


if FINAL_HISTORY_ROW is not None:

    print(
        "Final BCE                       :",
        f"{FINAL_HISTORY_ROW['BCE']:.6f}"
    )

    print(
        "Diagnostic accuracy @ 0.5      :",
        f"{FINAL_HISTORY_ROW['diagnostic_accuracy_at_0p5']:.6f}"
    )

    print(
        "Predicted attack fraction      :",
        f"{FINAL_HISTORY_ROW['predicted_attack_fraction']:.6f}"
    )

    print(
        "Predicted benign fraction      :",
        f"{FINAL_HISTORY_ROW['predicted_benign_fraction']:.6f}"
    )


print("\n" + "=" * 78)

if A43_VALID:

    print(
        "✅ STEP A43 PASSED — "
        "T=4 supervised fine-tuning completed "
        "successfully."
    )

else:

    print(
        "❌ STEP A43 FAILED — "
        "do not proceed to validation."
    )

print("=" * 78)

==============================================================================
STEP A43 — T=4 SUPERVISED FINE-TUNING
FOLD 1 | HELD-OUT FAMILY = DDoS | SEED = 13
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A42 valid: True
Training windows: 119,285
GPU: Tesla T4
Device: cuda

[2] Fine-tuning configuration
------------------------------------------------------------------------------
Window size: 4
Seed: 13
Classifier init seed: 1013
Epochs: 20
Batch size: 256
Learning rate: 0.001
Precision: float32
Imbalance method: none
Gradient clipping: 5.0

[3] Fine-tuning DataLoader
------------------------------------------------------------------------------
Dataset windows: 119,285
Batches per epoch: 466

[4] A42 SSL artifact
------------------------------------------------------------------------------
SSL epochs: 30
SSL lambda_t: 0.25
SSL precision: float32
SSL labels used: False
SSL encoder loaded: True
Classifier freshly initialized: True
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[5] Checking fine-tuning checkpoint
------------------------------------------------------------------------------
No fine-tuning checkpoint found.
Starting from epoch 1.

[6] Starting / resuming supervised fine-tuning
------------------------------------------------------------------------------
Epoch 01/20 | Batch 100/466 | BCE 0.141882
Epoch 01/20 | Batch 200/466 | BCE 0.166447
Epoch 01/20 | Batch 300/466 | BCE 0.101365
Epoch 01/20 | Batch 400/466 | BCE 0.135637
Epoch 01/20 | Batch 466/466 | BCE 0.106993

Epoch 01 complete | BCE=0.177968 | diagnostic_acc@0.5=0.922958 | predicted_attack=0.957011 | time=7.6s | checkpoint=Drive

Epoch 02/20 | Batch 100/466 | BCE 0.159490
Epoch 02/20 | Batch 200/466 | BCE 0.151006
Epoch 02/20 | Batch 300/466 | BCE 0.109238
Epoch 02/20 | Batch 400/466 | BCE 0.118014
Epoch 02/20 | Batch 466/466 | BCE 0.122457

Epoch 02 complete | BCE=0.127950 | diagnostic_acc@0.5=0.940328 | predicted_attack=0.940160 | time=6.8s | checkpoint=Drive

Epoch 03/20 | Batch 100/466 | BCE 0.101144
Epoch 03/20 | Batch 200/466 | BCE 0.122177
Epoch 03/20 | Batch 300/466 | BCE 0.147326
Epoch 03/20 | Batch 400/466 | BCE 0.092186
Epoch 03/20 | Batch 466/466 | BCE 0.138583

Epoch 03 complete | BCE=0.116387 | diagnostic_acc@0.5=0.946263 | predicted_attack=0.935516 | time=7.9s | checkpoint=Drive

Epoch 04/20 | Batch 100/466 | BCE 0.079328
Epoch 04/20 | Batch 200/466 | BCE 0.084752
Epoch 04/20 | Batch 300/466 | BCE 0.115238
Epoch 04/20 | Batch 400/466 | BCE 0.101243
Epoch 04/20 | Batch 466/466 | BCE 0.093634

Epoch 04 complete | BCE=0.107289 | diagnostic_acc@0.5=0.949784 | predicted_attack=0.931978 | time=6.7s | checkpoint=Drive

Epoch 05/20 | Batch 100/466 | BCE 0.107479
Epoch 05/20 | Batch 200/466 | BCE 0.129711
Epoch 05/20 | Batch 300/466 | BCE 0.107846
Epoch 05/20 | Batch 400/466 | BCE 0.087291
Epoch 05/20 | Batch 466/466 | BCE 0.120733

Epoch 05 complete | BCE=0.099516 | diagnostic_acc@0.5=0.953456 | predicted_attack=0.929513 | time=8.8s | checkpoint=Drive

Epoch 06/20 | Batch 100/466 | BCE 0.110056
Epoch 06/20 | Batch 200/466 | BCE 0.083298
Epoch 06/20 | Batch 300/466 | BCE 0.084923
Epoch 06/20 | Batch 400/466 | BCE 0.114674
Epoch 06/20 | Batch 466/466 | BCE 0.099211

Epoch 06 complete | BCE=0.093916 | diagnostic_acc@0.5=0.956834 | predicted_attack=0.927476 | time=6.4s | checkpoint=Drive

Epoch 07/20 | Batch 100/466 | BCE 0.071885
Epoch 07/20 | Batch 200/466 | BCE 0.093482
Epoch 07/20 | Batch 300/466 | BCE 0.101853
Epoch 07/20 | Batch 400/466 | BCE 0.079856
Epoch 07/20 | Batch 466/466 | BCE 0.071503

Epoch 07 complete | BCE=0.089229 | diagnostic_acc@0.5=0.958721 | predicted_attack=0.926546 | time=8.7s | checkpoint=Drive

Epoch 08/20 | Batch 100/466 | BCE 0.084938
Epoch 08/20 | Batch 200/466 | BCE 0.098066
Epoch 08/20 | Batch 300/466 | BCE 0.042532
Epoch 08/20 | Batch 400/466 | BCE 0.102932
Epoch 08/20 | Batch 466/466 | BCE 0.058815

Epoch 08 complete | BCE=0.084115 | diagnostic_acc@0.5=0.960674 | predicted_attack=0.925313 | time=4.3s | checkpoint=Drive

Epoch 09/20 | Batch 100/466 | BCE 0.079501
Epoch 09/20 | Batch 200/466 | BCE 0.064625
Epoch 09/20 | Batch 300/466 | BCE 0.095770
Epoch 09/20 | Batch 400/466 | BCE 0.104138
Epoch 09/20 | Batch 466/466 | BCE 0.058550

Epoch 09 complete | BCE=0.080109 | diagnostic_acc@0.5=0.962753 | predicted_attack=0.924056 | time=4.1s | checkpoint=Drive

Epoch 10/20 | Batch 100/466 | BCE 0.060485
Epoch 10/20 | Batch 200/466 | BCE 0.107745
Epoch 10/20 | Batch 300/466 | BCE 0.086833
Epoch 10/20 | Batch 400/466 | BCE 0.113814
Epoch 10/20 | Batch 466/466 | BCE 0.071271

Epoch 10 complete | BCE=0.076273 | diagnostic_acc@0.5=0.964732 | predicted_attack=0.923402 | time=5.0s | checkpoint=Drive

Epoch 11/20 | Batch 100/466 | BCE 0.085596
Epoch 11/20 | Batch 200/466 | BCE 0.085547
Epoch 11/20 | Batch 300/466 | BCE 0.061329
Epoch 11/20 | Batch 400/466 | BCE 0.070062
Epoch 11/20 | Batch 466/466 | BCE 0.086053

Epoch 11 complete | BCE=0.071865 | diagnostic_acc@0.5=0.966660 | predicted_attack=0.922631 | time=4.0s | checkpoint=Drive

Epoch 12/20 | Batch 100/466 | BCE 0.142569
Epoch 12/20 | Batch 200/466 | BCE 0.085585
Epoch 12/20 | Batch 300/466 | BCE 0.073416
Epoch 12/20 | Batch 400/466 | BCE 0.059143
Epoch 12/20 | Batch 466/466 | BCE 0.067655

Epoch 12 complete | BCE=0.068566 | diagnostic_acc@0.5=0.968529 | predicted_attack=0.922572 | time=4.0s | checkpoint=Drive

Epoch 13/20 | Batch 100/466 | BCE 0.054083
Epoch 13/20 | Batch 200/466 | BCE 0.097864
Epoch 13/20 | Batch 300/466 | BCE 0.080748
Epoch 13/20 | Batch 400/466 | BCE 0.083285
Epoch 13/20 | Batch 466/466 | BCE 0.045663

Epoch 13 complete | BCE=0.066449 | diagnostic_acc@0.5=0.969367 | predicted_attack=0.922522 | time=4.8s | checkpoint=Drive

Epoch 14/20 | Batch 100/466 | BCE 0.063152
Epoch 14/20 | Batch 200/466 | BCE 0.072650
Epoch 14/20 | Batch 300/466 | BCE 0.076938
Epoch 14/20 | Batch 400/466 | BCE 0.059165
Epoch 14/20 | Batch 466/466 | BCE 0.054696

Epoch 14 complete | BCE=0.063973 | diagnostic_acc@0.5=0.970407 | predicted_attack=0.921985 | time=4.2s | checkpoint=Drive

Epoch 15/20 | Batch 100/466 | BCE 0.053923
Epoch 15/20 | Batch 200/466 | BCE 0.047733
Epoch 15/20 | Batch 300/466 | BCE 0.060608
Epoch 15/20 | Batch 400/466 | BCE 0.057748
Epoch 15/20 | Batch 466/466 | BCE 0.097981

Epoch 15 complete | BCE=0.061662 | diagnostic_acc@0.5=0.971522 | predicted_attack=0.921960 | time=4.0s | checkpoint=Drive

Epoch 16/20 | Batch 100/466 | BCE 0.035128
Epoch 16/20 | Batch 200/466 | BCE 0.037559
Epoch 16/20 | Batch 300/466 | BCE 0.063113
Epoch 16/20 | Batch 400/466 | BCE 0.075320
Epoch 16/20 | Batch 466/466 | BCE 0.055024

Epoch 16 complete | BCE=0.059481 | diagnostic_acc@0.5=0.972570 | predicted_attack=0.921935 | time=4.6s | checkpoint=Drive

Epoch 17/20 | Batch 100/466 | BCE 0.067182
Epoch 17/20 | Batch 200/466 | BCE 0.108363
Epoch 17/20 | Batch 300/466 | BCE 0.093469
Epoch 17/20 | Batch 400/466 | BCE 0.062111
Epoch 17/20 | Batch 466/466 | BCE 0.066916

Epoch 17 complete | BCE=0.056385 | diagnostic_acc@0.5=0.973861 | predicted_attack=0.921097 | time=4.4s | checkpoint=Drive

Epoch 18/20 | Batch 100/466 | BCE 0.056167
Epoch 18/20 | Batch 200/466 | BCE 0.065422
Epoch 18/20 | Batch 300/466 | BCE 0.063267
Epoch 18/20 | Batch 400/466 | BCE 0.087044
Epoch 18/20 | Batch 466/466 | BCE 0.041697

Epoch 18 complete | BCE=0.054089 | diagnostic_acc@0.5=0.974733 | predicted_attack=0.921113 | time=4.0s | checkpoint=Drive

Epoch 19/20 | Batch 100/466 | BCE 0.065507
Epoch 19/20 | Batch 200/466 | BCE 0.060880
Epoch 19/20 | Batch 300/466 | BCE 0.076222
Epoch 19/20 | Batch 400/466 | BCE 0.078318
Epoch 19/20 | Batch 466/466 | BCE 0.046476

Epoch 19 complete | BCE=0.053027 | diagnostic_acc@0.5=0.975596 | predicted_attack=0.920602 | time=4.3s | checkpoint=Drive

Epoch 20/20 | Batch 100/466 | BCE 0.054370
Epoch 20/20 | Batch 200/466 | BCE 0.043470
Epoch 20/20 | Batch 300/466 | BCE 0.053125
Epoch 20/20 | Batch 400/466 | BCE 0.061007
Epoch 20/20 | Batch 466/466 | BCE 0.074647

Epoch 20 complete | BCE=0.051485 | diagnostic_acc@0.5=0.976502 | predicted_attack=0.921356 | time=4.6s | checkpoint=Drive


[7] Final numerical validation
------------------------------------------------------------------------------
Completed epochs: 20
Parameters finite: True
Outputs finite: True
Probability range valid: True

[8] Step A43 validation
------------------------------------------------------------------------------
Window size                     : 4
Completed fine-tuning epochs    : 20 / 20
Training windows                : 119,285
Imbalance method                : none
SSL encoder loaded              : True
Classifier freshly initialized  : True
Fine-tuned parameters           : 117,377
Projection head optimized       : False
Temporal-order head optimized   : False
Threshold selected              : False
Known-test used                 : False
Benign-test used                : False
Zero-day DDoS used              : False
Non-finite batches              : 0
Parameters finite               : True
Outputs finite                  : True
Probability range valid         : True
Final model backed up           : True
Latest checkpoint backed up     : True
Training history backed up      : True
Final BCE                       : 0.051485
Diagnostic accuracy @ 0.5      : 0.976502
Predicted attack fraction      : 0.921356
Predicted benign fraction      : 0.078644

==============================================================================
✅ STEP A43 PASSED — T=4 supervised fine-tuning completed successfully.
==============================================================================

# Step A43 — T=4 supervised fine-tuning

In [ ]:
# ======================================================================
# STEP A43
# T=4 CONTROLLED SUPERVISED FINE-TUNING
#
# Fold 1: DDoS held out
# Window = 4
# Seed = 13
# lambda_t = 0.25
# Imbalance method = none
#
# Loads encoder from A42 SSL.
# Projection/order heads are NOT optimized.
# Fresh classifier initialization.
#
# CHECKPOINT SAVED AFTER EVERY EPOCH.
# ======================================================================

from pathlib import Path
import os
import json
import time
import random

import numpy as np
import pandas as pd

import torch
import torch.nn as nn

from torch.utils.data import DataLoader


print("=" * 78)
print("STEP A43 — T=4 SUPERVISED FINE-TUNING")
print("FOLD 1 | HELD-OUT FAMILY = DDoS | SEED = 13")
print("=" * 78)


# ======================================================================
# 1 — PREREQUISITES
# ======================================================================

print("\n[1] Verifying prerequisites")
print("-" * 78)

required_globals = [
    "STEP_42_T4_SSL_PRETRAINING_VALID",
    "T4_TRAIN_DATASET",
    "MOTSSLGRU",
]

for name in required_globals:
    if name not in globals():
        raise RuntimeError(
            f"Required state missing: {name}"
        )

if not STEP_42_T4_SSL_PRETRAINING_VALID:
    raise RuntimeError(
        "A42 did not pass."
    )

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA unavailable. Keep T4 GPU enabled."
    )


DEVICE = torch.device("cuda")
GPU_NAME = torch.cuda.get_device_name(0)


print("A42 valid:", STEP_42_T4_SSL_PRETRAINING_VALID)
print("Training windows:", f"{len(T4_TRAIN_DATASET):,}")
print("GPU:", GPU_NAME)
print("Device:", DEVICE)


if len(T4_TRAIN_DATASET) != 119_285:
    raise RuntimeError(
        "Expected 119,285 T=4 training windows."
    )


# ======================================================================
# 2 — FROZEN CONFIGURATION
# ======================================================================

SEED = 13
CLASSIFIER_INIT_SEED = 1013

FT_EPOCHS = 20
BATCH_SIZE = 256
LEARNING_RATE = 1e-3

GRADIENT_CLIP_NORM = 5.0

LAMBDA_T = 0.25
IMBALANCE_METHOD = "none"


print("\n[2] Fine-tuning configuration")
print("-" * 78)

print("Window size:", 4)
print("Seed:", SEED)
print("Classifier init seed:", CLASSIFIER_INIT_SEED)
print("Epochs:", FT_EPOCHS)
print("Batch size:", BATCH_SIZE)
print("Learning rate:", LEARNING_RATE)
print("Precision: float32")
print("Imbalance method:", IMBALANCE_METHOD)
print("Gradient clipping:", GRADIENT_CLIP_NORM)


# ======================================================================
# 3 — PATHS
# ======================================================================

SSL_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/"
    "fold_01_DDoS/T4/"
    "ssl_pretraining/seed_13"
)

SSL_FINAL_PATH = (
    SSL_DIR
    / "A42_T4_SSL_final.pt"
)

SSL_SPEC_PATH = (
    SSL_DIR
    / "A42_T4_SSL_implementation.json"
)


OUTPUT_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/"
    "fold_01_DDoS/T4/"
    "fine_tuning/seed_13/"
    "imbalance_none"
)

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)


CHECKPOINT_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_latest_checkpoint.pt"
)

FINAL_MODEL_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetuned_final.pt"
)

HISTORY_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_history.csv"
)

SUMMARY_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_summary.json"
)


for path in [
    SSL_FINAL_PATH,
    SSL_SPEC_PATH
]:
    if not path.exists():
        raise RuntimeError(
            f"A42 artifact missing:\n{path}"
        )


# ======================================================================
# 4 — REPRODUCIBILITY
# ======================================================================

def set_global_seed(seed):

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


set_global_seed(SEED)


LOADER_GENERATOR = torch.Generator()
LOADER_GENERATOR.manual_seed(SEED)


FT_LOADER = DataLoader(

    T4_TRAIN_DATASET,

    batch_size=BATCH_SIZE,

    shuffle=True,

    generator=LOADER_GENERATOR,

    num_workers=0,

    pin_memory=True,

    drop_last=False
)


print("\n[3] Fine-tuning DataLoader")
print("-" * 78)

print(
    "Dataset windows:",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "Batches per epoch:",
    len(FT_LOADER)
)


# ======================================================================
# 5 — LOAD A42 SSL ARTIFACT
# ======================================================================

ssl_artifact = torch.load(
    SSL_FINAL_PATH,
    map_location=DEVICE,
    weights_only=False
)


if int(
    ssl_artifact.get(
        "window_size",
        -1
    )
) != 4:
    raise RuntimeError(
        "A42 artifact window mismatch."
    )


if float(
    ssl_artifact.get(
        "lambda_t",
        -1
    )
) != 0.25:
    raise RuntimeError(
        "A42 lambda_t mismatch."
    )


if int(
    ssl_artifact.get(
        "epochs",
        -1
    )
) != 30:
    raise RuntimeError(
        "A42 SSL epoch count mismatch."
    )


print("\n[4] A42 SSL artifact")
print("-" * 78)

print("SSL epochs:", ssl_artifact["epochs"])
print("SSL lambda_t:", ssl_artifact["lambda_t"])
print("SSL precision:", ssl_artifact["precision"])
print("SSL labels used:", ssl_artifact["binary_labels_used"])


# ======================================================================
# 6 — BUILD FINE-TUNING MODEL
# ======================================================================

set_global_seed(SEED)


FT_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


ssl_state = ssl_artifact[
    "model_state_dict"
]


# Load ONLY the feature encoder + GRU temporal encoder.

encoder_state = {
    key: value

    for key, value in ssl_state.items()

    if (
        key.startswith("feature_encoder.")
        or
        key.startswith("temporal_encoder.")
    )
}


load_result = FT_MODEL.load_state_dict(
    encoder_state,
    strict=False
)


ENCODER_LOADED = bool(
    len(
        [
            key
            for key in load_result.missing_keys
            if (
                key.startswith("feature_encoder.")
                or
                key.startswith("temporal_encoder.")
            )
        ]
    )
    == 0
)


if not ENCODER_LOADED:
    raise RuntimeError(
        "Failed to load A42 SSL encoder."
    )


# ======================================================================
# 7 — FRESH CLASSIFIER INITIALIZATION
# ======================================================================

torch.manual_seed(
    CLASSIFIER_INIT_SEED
)

torch.cuda.manual_seed_all(
    CLASSIFIER_INIT_SEED
)


def reset_module(module):

    if hasattr(
        module,
        "reset_parameters"
    ):
        module.reset_parameters()


FT_MODEL.classifier_head.apply(
    reset_module
)


# Restore main experiment seed afterwards.

set_global_seed(SEED)


print("SSL encoder loaded:", ENCODER_LOADED)
print("Classifier freshly initialized:", True)


# ======================================================================
# 8 — OPTIMIZED PARAMETERS
# ======================================================================

FT_PARAMETERS = (

    list(
        FT_MODEL
        .feature_encoder
        .parameters()
    )

    +

    list(
        FT_MODEL
        .temporal_encoder
        .parameters()
    )

    +

    list(
        FT_MODEL
        .classifier_head
        .parameters()
    )
)


FT_PARAMETER_COUNT = sum(
    parameter.numel()
    for parameter in FT_PARAMETERS
)


if FT_PARAMETER_COUNT != 117_377:
    raise RuntimeError(
        f"Fine-tuning parameter count mismatch: "
        f"{FT_PARAMETER_COUNT:,}"
    )


FT_PARAMETER_IDS = {
    id(parameter)
    for parameter in FT_PARAMETERS
}


PROJECTION_IDS = {
    id(parameter)
    for parameter
    in FT_MODEL.projection_head.parameters()
}


ORDER_IDS = {
    id(parameter)
    for parameter
    in FT_MODEL.temporal_order_head.parameters()
}


PROJECTION_EXCLUDED = bool(
    FT_PARAMETER_IDS.isdisjoint(
        PROJECTION_IDS
    )
)


ORDER_EXCLUDED = bool(
    FT_PARAMETER_IDS.isdisjoint(
        ORDER_IDS
    )
)


if not PROJECTION_EXCLUDED:
    raise RuntimeError(
        "Projection head incorrectly optimized."
    )


if not ORDER_EXCLUDED:
    raise RuntimeError(
        "Temporal-order head incorrectly optimized."
    )


print(
    "Fine-tuned parameters:",
    f"{FT_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized:",
    False
)

print(
    "Temporal-order head optimized:",
    False
)


# ======================================================================
# 9 — OPTIMIZER + LOSS
# ======================================================================

OPTIMIZER = torch.optim.Adam(
    FT_PARAMETERS,
    lr=LEARNING_RATE
)


CRITERION = nn.BCEWithLogitsLoss()


# ======================================================================
# 10 — CHECKPOINT HELPERS
# ======================================================================

def capture_rng_state():

    return {

        "python":
            random.getstate(),

        "numpy":
            np.random.get_state(),

        "torch_cpu":
            torch.get_rng_state(),

        "torch_cuda":
            torch.cuda.get_rng_state_all(),

        "loader_generator":
            LOADER_GENERATOR.get_state()
    }


def restore_rng_state(state):

    random.setstate(
        state["python"]
    )

    np.random.set_state(
        state["numpy"]
    )

    torch.set_rng_state(
        state["torch_cpu"]
    )

    torch.cuda.set_rng_state_all(
        state["torch_cuda"]
    )

    LOADER_GENERATOR.set_state(
        state["loader_generator"]
    )


def save_checkpoint(
    epoch,
    history
):

    artifact = {

        "step":
            "A43",

        "fold_id":
            1,

        "held_out_family":
            "DDoS",

        "window_size":
            4,

        "seed":
            SEED,

        "classifier_init_seed":
            CLASSIFIER_INIT_SEED,

        "lambda_t":
            LAMBDA_T,

        "imbalance_method":
            IMBALANCE_METHOD,

        "completed_epoch":
            epoch,

        "model_state_dict":
            FT_MODEL.state_dict(),

        "optimizer_state_dict":
            OPTIMIZER.state_dict(),

        "history":
            history,

        "rng_state":
            capture_rng_state()
    }


    temporary_path = (
        OUTPUT_DIR
        / "A43_checkpoint_writing.tmp"
    )


    torch.save(
        artifact,
        temporary_path
    )


    os.replace(
        temporary_path,
        CHECKPOINT_PATH
    )


# ======================================================================
# 11 — RESUME CHECK
# ======================================================================

HISTORY = []
START_EPOCH = 1


print("\n[5] Checking fine-tuning checkpoint")
print("-" * 78)


if CHECKPOINT_PATH.exists():

    checkpoint = torch.load(
        CHECKPOINT_PATH,
        map_location=DEVICE,
        weights_only=False
    )


    if int(
        checkpoint.get(
            "window_size",
            -1
        )
    ) != 4:
        raise RuntimeError(
            "Fine-tuning checkpoint window mismatch."
        )


    if checkpoint.get(
        "imbalance_method"
    ) != "none":
        raise RuntimeError(
            "Fine-tuning imbalance-method mismatch."
        )


    FT_MODEL.load_state_dict(
        checkpoint[
            "model_state_dict"
        ]
    )


    OPTIMIZER.load_state_dict(
        checkpoint[
            "optimizer_state_dict"
        ]
    )


    HISTORY = checkpoint.get(
        "history",
        []
    )


    completed_epoch = int(
        checkpoint[
            "completed_epoch"
        ]
    )


    restore_rng_state(
        checkpoint[
            "rng_state"
        ]
    )


    START_EPOCH = (
        completed_epoch + 1
    )


    print("Checkpoint found.")
    print("Completed epochs:", completed_epoch)
    print("Resuming from epoch:", START_EPOCH)

else:

    print("No fine-tuning checkpoint found.")
    print("Starting from epoch 1.")


# ======================================================================
# 12 — SUPERVISED FINE-TUNING
# ======================================================================

NONFINITE_BATCHES = 0


print("\n[6] Starting / resuming supervised fine-tuning")
print("-" * 78)


for epoch in range(
    START_EPOCH,
    FT_EPOCHS + 1
):

    epoch_start = time.time()

    FT_MODEL.train()


    epoch_loss_sum = 0.0

    epoch_examples = 0

    epoch_correct = 0

    epoch_predicted_attack = 0

    maximum_preclip_gradient_norm = 0.0


    for batch_index, (
        X_batch,
        y_batch
    ) in enumerate(
        FT_LOADER,
        start=1
    ):


        X_batch = X_batch.to(
            DEVICE,
            dtype=torch.float32,
            non_blocking=True
        )


        y_batch = y_batch.to(
            DEVICE,
            dtype=torch.float32,
            non_blocking=True
        )


        if not torch.isfinite(
            X_batch
        ).all():

            raise RuntimeError(
                f"Non-finite input at epoch "
                f"{epoch}, batch {batch_index}."
            )


        logits = (
            FT_MODEL
            .forward_classifier(
                X_batch
            )
        )


        loss = CRITERION(
            logits,
            y_batch
        )


        if not torch.isfinite(
            loss
        ):

            NONFINITE_BATCHES += 1

            raise RuntimeError(
                f"Non-finite BCE at epoch "
                f"{epoch}, batch {batch_index}."
            )


        OPTIMIZER.zero_grad(
            set_to_none=True
        )


        loss.backward()


        gradient_norm = (
            torch.nn.utils.clip_grad_norm_(
                FT_PARAMETERS,
                max_norm=GRADIENT_CLIP_NORM
            )
        )


        gradient_norm_value = float(
            gradient_norm
            .detach()
            .cpu()
        )


        if not np.isfinite(
            gradient_norm_value
        ):

            NONFINITE_BATCHES += 1

            raise RuntimeError(
                f"Non-finite gradient at epoch "
                f"{epoch}, batch {batch_index}."
            )


        maximum_preclip_gradient_norm = max(
            maximum_preclip_gradient_norm,
            gradient_norm_value
        )


        OPTIMIZER.step()


        with torch.no_grad():

            probabilities = torch.sigmoid(
                logits
            )

            predictions = (
                probabilities >= 0.5
            ).float()


        batch_examples = int(
            X_batch.shape[0]
        )


        epoch_loss_sum += (
            float(
                loss.detach().cpu()
            )
            *
            batch_examples
        )


        epoch_examples += (
            batch_examples
        )


        epoch_correct += int(
            (
                predictions
                ==
                y_batch
            )
            .sum()
            .detach()
            .cpu()
        )


        epoch_predicted_attack += int(
            predictions
            .sum()
            .detach()
            .cpu()
        )


        if (
            batch_index % 100 == 0
            or
            batch_index == len(
                FT_LOADER
            )
        ):

            print(
                f"Epoch {epoch:02d}/{FT_EPOCHS} "
                f"| Batch "
                f"{batch_index}/{len(FT_LOADER)} "
                f"| BCE "
                f"{float(loss.detach().cpu()):.6f}"
            )


    epoch_bce = (
        epoch_loss_sum
        /
        epoch_examples
    )


    diagnostic_accuracy = (
        epoch_correct
        /
        epoch_examples
    )


    predicted_attack_fraction = (
        epoch_predicted_attack
        /
        epoch_examples
    )


    predicted_benign_fraction = (
        1.0
        -
        predicted_attack_fraction
    )


    epoch_seconds = (
        time.time()
        -
        epoch_start
    )


    epoch_record = {

        "epoch":
            epoch,

        "window_size":
            4,

        "seed":
            SEED,

        "lambda_t":
            LAMBDA_T,

        "imbalance_method":
            IMBALANCE_METHOD,

        "BCE":
            epoch_bce,

        "diagnostic_accuracy_at_0p5":
            diagnostic_accuracy,

        "predicted_attack_fraction":
            predicted_attack_fraction,

        "predicted_benign_fraction":
            predicted_benign_fraction,

        "examples":
            epoch_examples,

        "batches":
            len(FT_LOADER),

        "maximum_preclip_gradient_norm":
            maximum_preclip_gradient_norm,

        "epoch_seconds":
            epoch_seconds
    }


    HISTORY = [
        row
        for row in HISTORY
        if int(row["epoch"]) != epoch
    ]


    HISTORY.append(
        epoch_record
    )


    HISTORY = sorted(
        HISTORY,
        key=lambda row: row["epoch"]
    )


    pd.DataFrame(
        HISTORY
    ).to_csv(
        HISTORY_PATH,
        index=False
    )


    save_checkpoint(
        epoch,
        HISTORY
    )


    print()

    print(
        f"Epoch {epoch:02d} complete "
        f"| BCE={epoch_bce:.6f} "
        f"| diagnostic_acc@0.5="
        f"{diagnostic_accuracy:.6f} "
        f"| predicted_attack="
        f"{predicted_attack_fraction:.6f} "
        f"| time={epoch_seconds:.1f}s "
        f"| checkpoint=Drive"
    )

    print()


# ======================================================================
# 13 — FINAL NUMERICAL VALIDATION
# ======================================================================

print("\n[7] Final numerical validation")
print("-" * 78)


COMPLETED_EPOCHS = len(
    HISTORY
)


ALL_PARAMETERS_FINITE = all(

    torch.isfinite(
        parameter
    ).all().item()

    for parameter
    in FT_MODEL.parameters()
)


FT_MODEL.eval()


CHECK_LOADER = DataLoader(
    T4_TRAIN_DATASET,
    batch_size=256,
    shuffle=False,
    num_workers=0
)


X_check, y_check = next(
    iter(
        CHECK_LOADER
    )
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


with torch.no_grad():

    logits_check = (
        FT_MODEL
        .forward_classifier(
            X_check
        )
    )


    probabilities_check = (
        torch.sigmoid(
            logits_check
        )
    )


OUTPUTS_FINITE = bool(
    torch.isfinite(
        logits_check
    ).all()
    and
    torch.isfinite(
        probabilities_check
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    torch.all(
        probabilities_check >= 0
    )

    and

    torch.all(
        probabilities_check <= 1
    )
)


print(
    "Completed epochs:",
    COMPLETED_EPOCHS
)

print(
    "Parameters finite:",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite:",
    OUTPUTS_FINITE
)

print(
    "Probability range valid:",
    PROBABILITY_RANGE_VALID
)


# ======================================================================
# 14 — SAVE FINAL MODEL
# ======================================================================

FINAL_ARTIFACT = {

    "step":
        "A43",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        4,

    "seed":
        SEED,

    "classifier_init_seed":
        CLASSIFIER_INIT_SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "epochs":
        FT_EPOCHS,

    "precision":
        "float32",

    "model_state_dict":
        FT_MODEL.state_dict()
}


torch.save(
    FINAL_ARTIFACT,
    FINAL_MODEL_PATH
)


# ======================================================================
# 15 — SAVE SUMMARY
# ======================================================================

FINAL_HISTORY_ROW = (
    HISTORY[-1]
    if HISTORY
    else None
)


A43_SUMMARY = {

    "step":
        "A43",

    "fold_id":
        1,

    "held_out_family":
        "DDoS",

    "window_size":
        4,

    "seed":
        SEED,

    "classifier_init_seed":
        CLASSIFIER_INIT_SEED,

    "lambda_t":
        LAMBDA_T,

    "imbalance_method":
        IMBALANCE_METHOD,

    "training_windows":
        len(T4_TRAIN_DATASET),

    "completed_finetune_epochs":
        COMPLETED_EPOCHS,

    "precision":
        "float32",

    "projection_head_optimized":
        False,

    "temporal_order_head_optimized":
        False,

    "threshold_selected":
        False,

    "known_test_used":
        False,

    "benign_test_used":
        False,

    "zero_day_used":
        False,

    "nonfinite_batches":
        NONFINITE_BATCHES,

    "parameters_finite":
        ALL_PARAMETERS_FINITE,

    "outputs_finite":
        OUTPUTS_FINITE,

    "probability_range_valid":
        PROBABILITY_RANGE_VALID,

    "final_BCE":
        (
            FINAL_HISTORY_ROW["BCE"]
            if FINAL_HISTORY_ROW
            else None
        ),

    "diagnostic_accuracy_at_0p5":
        (
            FINAL_HISTORY_ROW[
                "diagnostic_accuracy_at_0p5"
            ]
            if FINAL_HISTORY_ROW
            else None
        ),

    "predicted_attack_fraction":
        (
            FINAL_HISTORY_ROW[
                "predicted_attack_fraction"
            ]
            if FINAL_HISTORY_ROW
            else None
        ),

    "predicted_benign_fraction":
        (
            FINAL_HISTORY_ROW[
                "predicted_benign_fraction"
            ]
            if FINAL_HISTORY_ROW
            else None
        )
}


with open(
    SUMMARY_PATH,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        A43_SUMMARY,
        f,
        indent=4
    )


# ======================================================================
# 16 — FINAL VALIDATION
# ======================================================================

A43_VALID = bool(

    COMPLETED_EPOCHS == 20

    and

    FT_PARAMETER_COUNT == 117_377

    and

    ENCODER_LOADED

    and

    PROJECTION_EXCLUDED

    and

    ORDER_EXCLUDED

    and

    NONFINITE_BATCHES == 0

    and

    ALL_PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    FINAL_MODEL_PATH.exists()

    and

    CHECKPOINT_PATH.exists()

    and

    HISTORY_PATH.exists()

    and

    SUMMARY_PATH.exists()
)


STEP_43_T4_FINETUNING_VALID = (
    A43_VALID
)


print("\n[8] Step A43 validation")
print("-" * 78)

print(
    "Window size                     :",
    4
)

print(
    "Completed fine-tuning epochs    :",
    f"{COMPLETED_EPOCHS} / 20"
)

print(
    "Training windows                :",
    f"{len(T4_TRAIN_DATASET):,}"
)

print(
    "Imbalance method                :",
    IMBALANCE_METHOD
)

print(
    "SSL encoder loaded              :",
    ENCODER_LOADED
)

print(
    "Classifier freshly initialized  :",
    True
)

print(
    "Fine-tuned parameters           :",
    f"{FT_PARAMETER_COUNT:,}"
)

print(
    "Projection head optimized       :",
    False
)

print(
    "Temporal-order head optimized   :",
    False
)

print(
    "Threshold selected              :",
    False
)

print(
    "Known-test used                 :",
    False
)

print(
    "Benign-test used                :",
    False
)

print(
    "Zero-day DDoS used              :",
    False
)

print(
    "Non-finite batches              :",
    NONFINITE_BATCHES
)

print(
    "Parameters finite               :",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite                  :",
    OUTPUTS_FINITE
)

print(
    "Probability range valid         :",
    PROBABILITY_RANGE_VALID
)

print(
    "Final model backed up           :",
    FINAL_MODEL_PATH.exists()
)

print(
    "Latest checkpoint backed up     :",
    CHECKPOINT_PATH.exists()
)

print(
    "Training history backed up      :",
    HISTORY_PATH.exists()
)


if FINAL_HISTORY_ROW is not None:

    print(
        "Final BCE                       :",
        f"{FINAL_HISTORY_ROW['BCE']:.6f}"
    )

    print(
        "Diagnostic accuracy @ 0.5      :",
        f"{FINAL_HISTORY_ROW['diagnostic_accuracy_at_0p5']:.6f}"
    )

    print(
        "Predicted attack fraction      :",
        f"{FINAL_HISTORY_ROW['predicted_attack_fraction']:.6f}"
    )

    print(
        "Predicted benign fraction      :",
        f"{FINAL_HISTORY_ROW['predicted_benign_fraction']:.6f}"
    )


print("\n" + "=" * 78)

if A43_VALID:

    print(
        "✅ STEP A43 PASSED — "
        "T=4 supervised fine-tuning completed "
        "successfully."
    )

else:

    print(
        "❌ STEP A43 FAILED — "
        "do not proceed to validation."
    )

print("=" * 78)

==============================================================================
STEP A43 — T=4 SUPERVISED FINE-TUNING
FOLD 1 | HELD-OUT FAMILY = DDoS | SEED = 13
==============================================================================

[1] Verifying prerequisites
------------------------------------------------------------------------------
A42 valid: True
Training windows: 119,285
GPU: Tesla T4
Device: cuda

[2] Fine-tuning configuration
------------------------------------------------------------------------------
Window size: 4
Seed: 13
Classifier init seed: 1013
Epochs: 20
Batch size: 256
Learning rate: 0.001
Precision: float32
Imbalance method: none
Gradient clipping: 5.0

[3] Fine-tuning DataLoader
------------------------------------------------------------------------------
Dataset windows: 119,285
Batches per epoch: 466

[4] A42 SSL artifact
------------------------------------------------------------------------------
SSL epochs: 30
SSL lambda_t: 0.25
SSL precision: float32
SSL labels used: False
SSL encoder loaded: True
Classifier freshly initialized: True
Fine-tuned parameters: 117,377
Projection head optimized: False
Temporal-order head optimized: False

[5] Checking fine-tuning checkpoint
------------------------------------------------------------------------------

TypeError: RNG state must be a torch.ByteTensor

In [ ]:
# ======================================================================
# RECOVERY STEP A43-R
# RESTORE COMPLETED T=4 FINE-TUNED MODEL
# FIX RNG CHECKPOINT ISSUE WITHOUT RETRAINING
# ======================================================================

from pathlib import Path
import json
import random

import numpy as np
import pandas as pd
import torch

from torch.utils.data import DataLoader


print("=" * 78)
print("RECOVERY STEP A43-R — RESTORE COMPLETED T=4 FINE-TUNED MODEL")
print("=" * 78)


# ======================================================================
# 1 — PATHS
# ======================================================================

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup/"
    "sensitivity/window_size/"
    "fold_01_DDoS/T4/"
    "fine_tuning/seed_13/"
    "imbalance_none"
)

FINAL_MODEL_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetuned_final.pt"
)

CHECKPOINT_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_latest_checkpoint.pt"
)

HISTORY_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_history.csv"
)

SUMMARY_PATH = (
    OUTPUT_DIR
    / "A43_T4_finetune_summary.json"
)


print("\n[1] Checking saved A43 artifacts")
print("-" * 78)

print("Final model exists :", FINAL_MODEL_PATH.exists())
print("Checkpoint exists  :", CHECKPOINT_PATH.exists())
print("History exists     :", HISTORY_PATH.exists())
print("Summary exists     :", SUMMARY_PATH.exists())


# ======================================================================
# 2 — VERIFY COMPLETED TRAINING
# ======================================================================

if not HISTORY_PATH.exists():
    raise RuntimeError(
        "A43 training history is missing."
    )

history_df = pd.read_csv(
    HISTORY_PATH
)

COMPLETED_EPOCHS = int(
    history_df["epoch"].max()
)

print("\nCompleted epochs:", COMPLETED_EPOCHS)


if COMPLETED_EPOCHS != 20:
    raise RuntimeError(
        f"A43 has only {COMPLETED_EPOCHS}/20 completed epochs. "
        "Do not use this recovery path."
    )


# ======================================================================
# 3 — LOAD FINAL MODEL ARTIFACT
# ======================================================================

if FINAL_MODEL_PATH.exists():

    artifact = torch.load(
        FINAL_MODEL_PATH,
        map_location="cpu",
        weights_only=False
    )

    print(
        "Loading completed FINAL A43 model."
    )

else:

    print(
        "Final model missing — recovering model state "
        "from completed epoch-20 checkpoint."
    )

    if not CHECKPOINT_PATH.exists():
        raise RuntimeError(
            "Neither final model nor checkpoint exists."
        )

    checkpoint = torch.load(
        CHECKPOINT_PATH,
        map_location="cpu",
        weights_only=False
    )

    if int(
        checkpoint.get(
            "completed_epoch",
            -1
        )
    ) != 20:
        raise RuntimeError(
            "Checkpoint is not an epoch-20 checkpoint."
        )

    artifact = {
        "step": "A43",
        "fold_id": 1,
        "held_out_family": "DDoS",
        "window_size": 4,
        "seed": 13,
        "classifier_init_seed": 1013,
        "lambda_t": 0.25,
        "imbalance_method": "none",
        "epochs": 20,
        "precision": "float32",
        "model_state_dict":
            checkpoint["model_state_dict"]
    }

    torch.save(
        artifact,
        FINAL_MODEL_PATH
    )


# ======================================================================
# 4 — METADATA VALIDATION
# ======================================================================

metadata_valid = bool(

    artifact.get("step") == "A43"

    and

    int(
        artifact.get(
            "window_size",
            -1
        )
    ) == 4

    and

    int(
        artifact.get(
            "seed",
            -1
        )
    ) == 13

    and

    float(
        artifact.get(
            "lambda_t",
            -1
        )
    ) == 0.25

    and

    artifact.get(
        "imbalance_method"
    ) == "none"

    and

    int(
        artifact.get(
            "epochs",
            -1
        )
    ) == 20
)


print("\n[2] Metadata validation")
print("-" * 78)

print(
    "Artifact metadata valid:",
    metadata_valid
)

if not metadata_valid:
    raise RuntimeError(
        "Saved A43 model metadata does not match "
        "the controlled T=4 experiment."
    )


# ======================================================================
# 5 — RESTORE MODEL FOR NEXT STEP
# ======================================================================

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA unavailable. Keep Tesla T4 connected."
    )

DEVICE = torch.device("cuda")


FT_MODEL = MOTSSLGRU(

    input_dim=75,

    feature_embed_dim=128,

    gru_hidden_dim=128,

    gru_num_layers=1,

    projection_dim=64,

    order_hidden_dim=128,

    classifier_hidden_dim=64,

    dropout=0.10

).to(
    DEVICE
).float()


FT_MODEL.load_state_dict(
    artifact[
        "model_state_dict"
    ]
)


FT_MODEL.eval()


# ======================================================================
# 6 — NUMERICAL CHECK
# ======================================================================

ALL_PARAMETERS_FINITE = all(

    torch.isfinite(
        parameter
    ).all().item()

    for parameter
    in FT_MODEL.parameters()
)


check_loader = DataLoader(

    T4_TRAIN_DATASET,

    batch_size=256,

    shuffle=False,

    num_workers=0
)


X_check, _ = next(
    iter(
        check_loader
    )
)


X_check = X_check.to(
    DEVICE,
    dtype=torch.float32
)


with torch.no_grad():

    logits = FT_MODEL.forward_classifier(
        X_check
    )

    probabilities = torch.sigmoid(
        logits
    )


OUTPUTS_FINITE = bool(
    torch.isfinite(
        probabilities
    ).all()
)


PROBABILITY_RANGE_VALID = bool(

    torch.all(
        probabilities >= 0
    )

    and

    torch.all(
        probabilities <= 1
    )
)


# ======================================================================
# 7 — CORRECT RNG RESTORE FUNCTION FOR FUTURE USE
# ======================================================================

def restore_rng_state_safe(
    state,
    loader_generator=None
):

    random.setstate(
        state["python"]
    )

    np.random.set_state(
        state["numpy"]
    )

    # CPU RNG MUST remain on CPU.
    torch.set_rng_state(
        state["torch_cpu"].cpu()
    )

    # CUDA RNG states are stored as CPU ByteTensors.
    cuda_states = [
        rng_state.cpu()
        for rng_state
        in state["torch_cuda"]
    ]

    torch.cuda.set_rng_state_all(
        cuda_states
    )

    if (
        loader_generator is not None
        and
        "loader_generator" in state
    ):

        loader_generator.set_state(
            state[
                "loader_generator"
            ].cpu()
        )


# ======================================================================
# 8 — FINAL RECOVERY VALIDATION
# ======================================================================

STEP_43_T4_FINETUNING_VALID = bool(

    COMPLETED_EPOCHS == 20

    and

    metadata_valid

    and

    ALL_PARAMETERS_FINITE

    and

    OUTPUTS_FINITE

    and

    PROBABILITY_RANGE_VALID

    and

    FINAL_MODEL_PATH.exists()

    and

    HISTORY_PATH.exists()
)


print("\n[3] Recovery validation")
print("-" * 78)

print(
    "Completed epochs               :",
    f"{COMPLETED_EPOCHS} / 20"
)

print(
    "Window size                    :",
    4
)

print(
    "lambda_t                       :",
    0.25
)

print(
    "Imbalance method               :",
    "none"
)

print(
    "Model parameters finite        :",
    ALL_PARAMETERS_FINITE
)

print(
    "Outputs finite                 :",
    OUTPUTS_FINITE
)

print(
    "Probability range valid        :",
    PROBABILITY_RANGE_VALID
)

print(
    "Final model restored           :",
    FINAL_MODEL_PATH.exists()
)

print(
    "Model ready for validation     :",
    STEP_43_T4_FINETUNING_VALID
)


print("\n" + "=" * 78)

if STEP_43_T4_FINETUNING_VALID:

    print(
        "✅ RECOVERY A43-R PASSED — "
        "completed T=4 fine-tuned model restored. "
        "NO retraining was performed."
    )

else:

    print(
        "❌ RECOVERY A43-R FAILED — "
        "do not proceed."
    )

print("=" * 78)

==============================================================================
RECOVERY STEP A43-R — RESTORE COMPLETED T=4 FINE-TUNED MODEL
==============================================================================

[1] Checking saved A43 artifacts
------------------------------------------------------------------------------
Final model exists : True
Checkpoint exists  : True
History exists     : True
Summary exists     : True

Completed epochs: 20
Loading completed FINAL A43 model.

[2] Metadata validation
------------------------------------------------------------------------------
Artifact metadata valid: True

[3] Recovery validation
------------------------------------------------------------------------------
Completed epochs               : 20 / 20
Window size                    : 4
lambda_t                       : 0.25
Imbalance method               : none
Model parameters finite        : True
Outputs finite                 : True
Probability range valid        : True
Final model restored           : True
Model ready for validation     : True

==============================================================================
✅ RECOVERY A43-R PASSED — completed T=4 fine-tuned model restored. NO retraining was performed.
==============================================================================

# Step A43.5 — Check T=4 validation artifacts

In [ ]:
# ======================================================================
# STEP A43.5
# CHECK T=4 DEVELOPMENT-VALIDATION ARTIFACTS
#
# NO TRAINING
# NO VALIDATION
# ======================================================================

from pathlib import Path

ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)

T4_MANIFEST = (
    ROOT
    / "processed_data/temporal_windows/"
      "fold_01_DDoS/T4/"
      "fold_01_DDoS_T4_development_manifest.csv"
)

PREPROCESSING_DIR = (
    ROOT
    / "processed_data/preprocessing/"
      "fold_01_DDoS"
)

CHRONOLOGICAL_DIR = (
    ROOT
    / "chronological_parquet"
)

VALIDATION_SHARDS = (
    ROOT
    / "processed_data/model_ready/"
      "fold_01_DDoS/T4/"
      "validation_shards"
)

print("=" * 78)
print("STEP A43.5 — T=4 VALIDATION PREREQUISITE CHECK")
print("=" * 78)

print(
    "T4 development manifest exists :",
    T4_MANIFEST.exists()
)

print(
    "Frozen preprocessing exists    :",
    PREPROCESSING_DIR.exists()
)

print(
    "Chronological Parquet exists   :",
    CHRONOLOGICAL_DIR.exists()
)

print(
    "Validation shards already exist:",
    VALIDATION_SHARDS.exists()
)

print()

if PREPROCESSING_DIR.exists():

    files = sorted(
        PREPROCESSING_DIR.iterdir()
    )

    print("Preprocessing files:")

    for p in files:
        print(" -", p.name)

print()

if CHRONOLOGICAL_DIR.exists():

    parquet_files = list(
        CHRONOLOGICAL_DIR.rglob("*.parquet")
    )

    print(
        "Chronological Parquet files:",
        len(parquet_files)
    )

print("=" * 78)

==============================================================================
STEP A43.5 — T=4 VALIDATION PREREQUISITE CHECK
==============================================================================
T4 development manifest exists : False
Frozen preprocessing exists    : False
Chronological Parquet exists   : False
Validation shards already exist: False


==============================================================================

In [ ]:
# ======================================================================
# STEP A43.6
# ORIGINAL ACCOUNT — FIND MINIMUM T=4 VALIDATION ARTIFACTS
#
# NO TRAINING
# NO DATA MODIFICATION
# ======================================================================

from google.colab import drive
from pathlib import Path
import os

drive.mount("/content/drive")

ROOT = Path(
    "/content/drive/MyDrive/"
    "ZeroDay_IoT_Research_Backup"
)

print("=" * 78)
print("STEP A43.6 — ORIGINAL ACCOUNT VALIDATION ARTIFACT SEARCH")
print("=" * 78)

print("Backup root exists:", ROOT.exists())

# ----------------------------------------------------------------------
# Important known locations
# ----------------------------------------------------------------------

manifest = (
    ROOT
    / "processed_data/temporal_windows/"
      "fold_01_DDoS/T4/"
      "fold_01_DDoS_T4_development_manifest.csv"
)

preprocessing = (
    ROOT
    / "processed_data/preprocessing/"
      "fold_01_DDoS"
)

chronological = (
    ROOT
    / "chronological_parquet"
)

model_ready_t4 = (
    ROOT
    / "processed_data/model_ready/"
      "fold_01_DDoS/T4"
)

print()
print("T4 manifest exists          :", manifest.exists())
print("Preprocessing exists        :", preprocessing.exists())
print("Chronological Parquet exists:", chronological.exists())
print("T4 model-ready root exists  :", model_ready_t4.exists())


# ----------------------------------------------------------------------
# Search only T4 model-ready area for validation-related files
# ----------------------------------------------------------------------

print("\n" + "-" * 78)
print("SEARCHING T4 MODEL-READY FOLDER")
print("-" * 78)

validation_matches = []

if model_ready_t4.exists():

    for p in model_ready_t4.rglob("*"):

        name = p.name.lower()

        if (
            "val" in name
            or
            "validation" in name
            or
            "development" in name
        ):
            validation_matches.append(p)


if validation_matches:

    print(
        f"Validation-related items found: "
        f"{len(validation_matches)}"
    )

    for p in validation_matches[:100]:

        if p.is_file():
            size_mb = p.stat().st_size / (1024 ** 2)

            print(
                f"FILE  | {size_mb:10.2f} MB | {p}"
            )

        else:
            print(
                f"DIR   | {'':10}    | {p}"
            )

else:

    print(
        "No validation-related files found "
        "inside T4 model-ready folder."
    )


# ----------------------------------------------------------------------
# Show preprocessing files
# ----------------------------------------------------------------------

print("\n" + "-" * 78)
print("PREPROCESSING CONTENTS")
print("-" * 78)

if preprocessing.exists():

    for p in sorted(preprocessing.iterdir()):

        if p.is_file():
            print(
                f"{p.name} | "
                f"{p.stat().st_size / 1024:.2f} KB"
            )

else:
    print("Preprocessing directory missing.")


print("\n" + "=" * 78)
print("✅ STEP A43.6 SEARCH COMPLETE")
print("=" * 78)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
==============================================================================
STEP A43.6 — ORIGINAL ACCOUNT VALIDATION ARTIFACT SEARCH
==============================================================================
Backup root exists: True

T4 manifest exists          : False
Preprocessing exists        : False
Chronological Parquet exists: False
T4 model-ready root exists  : True

------------------------------------------------------------------------------
SEARCHING T4 MODEL-READY FOLDER
------------------------------------------------------------------------------
No validation-related files found inside T4 model-ready folder.

------------------------------------------------------------------------------
PREPROCESSING CONTENTS
------------------------------------------------------------------------------
Preprocessing directory missing.

==============================================================================
✅ STEP A43.6 SEARCH COMPLETE
==============================================================================

# Step A43.7 — Search the entire mounted MyDrive

In [ ]:
# ======================================================================
# STEP A43.7
# SEARCH ENTIRE MOUNTED MYDRIVE FOR ORIGINAL RESEARCH ARTIFACTS
#
# NO TRAINING
# NO FILE MODIFICATION
# ======================================================================

from pathlib import Path
import os

MYDRIVE = Path("/content/drive/MyDrive")

print("=" * 78)
print("STEP A43.7 — FULL MYDRIVE ARTIFACT SEARCH")
print("=" * 78)

print("MyDrive exists:", MYDRIVE.exists())

if not MYDRIVE.exists():
    raise RuntimeError("MyDrive is not mounted.")


# ======================================================================
# 1 — EXACT TARGET NAMES
# ======================================================================

target_file_names = {
    "fold_01_DDoS_T4_development_manifest.csv",
}

target_dir_names = {
    "chronological_parquet",
    "preprocessing",
    "ZeroDay_IoT_Research_Backup",
}


exact_files = []
matching_dirs = []
fold01_items = []
zip_candidates = []


# ======================================================================
# 2 — WALK ENTIRE MYDRIVE
# ======================================================================

for root, dirs, files in os.walk(MYDRIVE):

    root_path = Path(root)

    # --------------------------------------------------------------
    # Directories
    # --------------------------------------------------------------

    for d in dirs:

        dpath = root_path / d

        if d in target_dir_names:
            matching_dirs.append(dpath)

        if (
            d == "fold_01_DDoS"
            or "fold_01_DDoS" in d
        ):
            fold01_items.append(dpath)

    # --------------------------------------------------------------
    # Files
    # --------------------------------------------------------------

    for f in files:

        fpath = root_path / f

        if f in target_file_names:
            exact_files.append(fpath)

        lower_name = f.lower()

        if (
            "fold_01_ddos" in lower_name
            or "preprocess" in lower_name
            or "chronological" in lower_name
        ):
            fold01_items.append(fpath)

        if lower_name.endswith(".zip"):

            if any(
                keyword in lower_name
                for keyword in [
                    "iot",
                    "zero",
                    "research",
                    "cic",
                    "fydp",
                    "project",
                    "backup"
                ]
            ):
                zip_candidates.append(fpath)


# ======================================================================
# 3 — DISPLAY RESULTS
# ======================================================================

print("\n[1] Exact T4 development manifest")
print("-" * 78)

if exact_files:
    for p in exact_files:
        print(p)
else:
    print("NOT FOUND")


print("\n[2] Matching important directories")
print("-" * 78)

if matching_dirs:
    for p in matching_dirs:
        print(p)
else:
    print("NONE FOUND")


print("\n[3] Fold-1 / preprocessing-related items")
print("-" * 78)

if fold01_items:

    # avoid huge duplicate display
    unique_items = sorted(
        set(fold01_items),
        key=lambda x: str(x)
    )

    print("Items found:", len(unique_items))

    for p in unique_items[:150]:
        print(p)

    if len(unique_items) > 150:
        print(
            f"... {len(unique_items) - 150} more items not shown"
        )

else:
    print("NONE FOUND")


print("\n[4] Potential project/backup ZIP files")
print("-" * 78)

if zip_candidates:

    for p in sorted(
        set(zip_candidates),
        key=lambda x: str(x)
    ):

        try:
            size_mb = p.stat().st_size / (1024 ** 2)
            print(
                f"{size_mb:10.2f} MB | {p}"
            )
        except Exception:
            print(p)

else:
    print("NONE FOUND")


print("\n" + "=" * 78)
print("✅ STEP A43.7 SEARCH COMPLETE")
print("=" * 78)

==============================================================================
STEP A43.7 — FULL MYDRIVE ARTIFACT SEARCH
==============================================================================
MyDrive exists: True

[1] Exact T4 development manifest
------------------------------------------------------------------------------
NOT FOUND

[2] Matching important directories
------------------------------------------------------------------------------
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup

[3] Fold-1 / preprocessing-related items
------------------------------------------------------------------------------
Items found: 3
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/models/architecture/fold_01_DDoS
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/processed_data/model_ready/fold_01_DDoS
/content/drive/MyDrive/ZeroDay_IoT_Research_Backup/sensitivity/window_size/fold_01_DDoS

[4] Potential project/backup ZIP files
------------------------------------------------------------------------------
NONE FOUND

==============================================================================
✅ STEP A43.7 SEARCH COMPLETE
==============================================================================

# Step A43.8 — Remount the correct original Google Drive

In [ ]:
# ======================================================================
# STEP A43.8
# REMOUNT GOOGLE DRIVE USING THE ORIGINAL ACCOUNT
#
# RUN ONLY IN THE SEPARATE COLAB TAB.
# DO NOT RUN IN THE MAIN T4 TRAINING NOTEBOOK.
# ======================================================================

from google.colab import drive
from pathlib import Path

print("=" * 78)
print("STEP A43.8 — REMOUNT ORIGINAL GOOGLE DRIVE")
print("=" * 78)

# Disconnect the currently mounted partial account.
try:
    drive.flush_and_unmount()
    print("Previous Drive unmounted.")
except Exception as e:
    print("Unmount message:", e)

print()
print("⚠️ When Google asks you to authorize Drive:")
print("   SELECT YOUR ORIGINAL GOOGLE ACCOUNT")
print("   — the account where the ML research was first created.")
print()

# This should trigger a fresh authorization.
drive.mount(
    "/content/drive",
    force_remount=True
)

MYDRIVE = Path("/content/drive/MyDrive")

ROOT = (
    MYDRIVE
    / "ZeroDay_IoT_Research_Backup"
)

targets = {

    "Backup root":
        ROOT,

    "Chronological Parquet":
        ROOT
        / "chronological_parquet",

    "Fold-1 preprocessing":
        ROOT
        / "processed_data/preprocessing/"
          "fold_01_DDoS",

    "T4 development manifest":
        ROOT
        / "processed_data/temporal_windows/"
          "fold_01_DDoS/T4/"
          "fold_01_DDoS_T4_development_manifest.csv",
}


print()
print("=" * 78)
print("VERIFYING ORIGINAL RESEARCH ARTIFACTS")
print("=" * 78)

for name, path in targets.items():

    print(
        f"{name:28}: {path.exists()}"
    )

    if path.exists():
        print("   ", path)


print()
print("Top-level MyDrive folders:")
print("-" * 78)

for p in sorted(
    MYDRIVE.iterdir(),
    key=lambda x: x.name.lower()
)[:50]:

    print(" -", p.name)


print()
print("=" * 78)

if (
    targets["Chronological Parquet"].exists()
    or
    targets["Fold-1 preprocessing"].exists()
    or
    targets["T4 development manifest"].exists()
):

    print(
        "✅ ORIGINAL RESEARCH ARTIFACTS DETECTED"
    )

else:

    print(
        "❌ ORIGINAL RESEARCH ARTIFACTS STILL NOT DETECTED"
    )

print("=" * 78)

==============================================================================
STEP A43.8 — REMOUNT ORIGINAL GOOGLE DRIVE
==============================================================================
Previous Drive unmounted.

⚠️ When Google asks you to authorize Drive:
   SELECT YOUR ORIGINAL GOOGLE ACCOUNT
   — the account where the ML research was first created.

Mounted at /content/drive

==============================================================================
VERIFYING ORIGINAL RESEARCH ARTIFACTS
==============================================================================
Backup root                 : True
    /content/drive/MyDrive/ZeroDay_IoT_Research_Backup
Chronological Parquet       : False
Fold-1 preprocessing        : False
T4 development manifest     : False

Top-level MyDrive folders:
------------------------------------------------------------------------------
 - Colab Notebooks
 - FYDP
 - SSL_GRU_ZeroDay_IoT_LOAFO_Training.ipynb
 - ZeroDay_IoT_Research_Backup

==============================================================================
❌ ORIGINAL RESEARCH ARTIFACTS STILL NOT DETECTED
==============================================================================